-- Migration: Upgrade remaining moderate-scoring FAR questions
-- Fixes: short-stem, length-cuing, absolute-assurance-trap, missing citations, missing wrong-answer analysis
-- Target: all questions score 7+ after this migration

-- === Consolidations ===

-- Q186 [score:5] short-stem(11w) + length-cuing -> expand stem with scenario, balance choices
UPDATE questions SET
  stem = 'Clearwater Corp. acquired 55% of the voting common stock of Ridgemont LLC on March 1, 2025, for $4.2 million. Clearwater''s controller is preparing the year-end financial statements and asks whether Ridgemont must be included in Clearwater''s consolidated financial statements. Under ASC 810, consolidation is generally required when one entity holds:',
  choices = '["Any ownership interest exceeding 20% of the investee''s outstanding voting shares","A controlling financial interest, typically more than 50% of voting shares","Exactly 50% ownership, creating a joint control arrangement with the investee","Only 100% ownership, meaning the subsidiary is wholly owned by the parent"]',
  explanation = 'Under ASC 810-10-15, consolidation is required when one entity has a controlling financial interest in another. For voting interest entities, control is typically evidenced by ownership of more than 50% of the outstanding voting shares. Because Clearwater holds 55%, it must consolidate Ridgemont. For variable interest entities (VIEs), consolidation is required by the primary beneficiary regardless of voting ownership percentage. Choice A is incorrect because 20% ownership triggers equity method accounting under ASC 323, not consolidation. Choice C is incorrect because 50% ownership does not establish unilateral control and would typically be accounted for as a joint venture or equity method investment.'
WHERE id = 186;

-- Q187 [score:6] short-stem(10w) -> expand stem with scenario, cite ASC 350
UPDATE questions SET
  stem = 'Thornfield Industries acquired Barrington Electronics in a business combination and recognized $3.8 million of goodwill. Two years after the acquisition, Thornfield''s CFO must determine the level at which goodwill impairment testing should be performed. Under ASC 350, goodwill acquired in a business combination is tested for impairment at:',
  explanation = 'Under ASC 350-20-35, goodwill is tested for impairment at the reporting unit level. A reporting unit is defined as an operating segment or one level below an operating segment (a component). Goodwill is allocated to reporting units that benefit from the synergies of the business combination, and impairment testing occurs annually at that level. Choice A is incorrect because goodwill is not tested at the individual asset level — it is an asset that relates to a group of assets within a reporting unit. Choice D is incorrect because testing at the consolidated entity level would aggregate reporting units with different economic characteristics, potentially masking impairment in one unit with strong performance in another.'
WHERE id = 187;

-- Q476 [score:6] length-cuing -> balance choice lengths
UPDATE questions SET
  choices = '["The entity holding the largest equity investment in the VIE, regardless of decision-making authority","The entity maintaining the longest contractual or business relationship with the VIE''s management","The entity with a contractual right to receive all of the VIE''s profits and residual returns","The entity with power to direct the VIE''s most significant activities and exposure to significant losses or benefits"]',
  explanation = 'Under ASC 810-10-25-38A, the primary beneficiary of a VIE must satisfy two conditions: (1) the power to direct the activities that most significantly impact the VIE''s economic performance, and (2) the obligation to absorb losses or the right to receive benefits that could potentially be significant to the VIE. Both conditions must be met simultaneously. Choice A is incorrect because the largest equity investor does not necessarily have the power to direct significant activities — a party with minimal equity but contractual control rights could be the primary beneficiary. Choice C is incorrect because a contractual profit interest alone, without decision-making power, does not satisfy the power criterion required under the dual-condition test.'
WHERE id = 476;

-- Q478 [score:6] length-cuing -> balance choice lengths
UPDATE questions SET
  choices = '["Recorded entirely as goodwill on the investor''s books and never subsequently amortized or adjusted","Ignored because the equity method does not track or adjust for basis differences over time","Expensed immediately as acquisition costs in the period the investment is initially acquired","Allocated to identifiable assets based on fair value differences, with any remainder as goodwill"]',
  explanation = 'When an equity method investor pays more than its share of book value, the excess is analyzed similarly to a purchase price allocation under ASC 323-10-35. The excess is allocated to specific identifiable assets (such as undervalued inventory, PP&E, or intangibles) and amortized as those items are consumed or depreciated. Any remaining excess is treated as equity method goodwill, which is not amortized but is tested for impairment as part of the overall investment balance. Choice A is incorrect because recording the entire excess as goodwill ignores identifiable fair value differences in specific assets and liabilities that should be separately allocated and amortized. Choice C is incorrect because the excess represents a basis difference in net assets, not an acquisition cost — it is systematically recognized as the underlying assets are consumed.'
WHERE id = 478;

-- Q483 [score:4] absolute-assurance-trap + length-cuing -> replace trap distractor, balance choices
UPDATE questions SET
  choices = '["Equity investors have proportional voting rights and activities are conducted on their behalf","The entity has received subordinated financial support from a related party sponsor","The entity''s at-risk equity is less than the amount needed to finance activities without support","The entity was specifically designed so that non-equity interests absorb expected losses"]',
  explanation = 'Under ASC 810-10-15-14, an entity is not a VIE if the equity investors have sufficient equity at risk to finance activities without additional subordinated support, possess voting rights proportional to their economic interests, and substantially all activities are conducted on their behalf. These characteristics indicate that the equity holders bear the risks and rewards of ownership, making the standard voting interest model appropriate. Choice B is incorrect because subordinated financial support from a related party is actually an indicator that the entity may be a VIE — it suggests the equity is insufficient to absorb expected losses. Choice D is incorrect because designing the entity so that non-equity holders absorb expected losses is a hallmark of VIE structures under ASC 810-10-15-14(b).'
WHERE id = 483;

-- === Contingencies ===

-- Q192 [score:6] short-stem(10w) -> expand stem with scenario
UPDATE questions SET
  stem = 'Ridgemont Manufacturing is named as a defendant in a product liability lawsuit filed in October 2025. The company''s legal counsel advises that it is probable Ridgemont will lose the case, and estimates the liability at $1.5 million. The controller is preparing the December 31, 2025 financial statements and asks whether the loss should be accrued or only disclosed. Under ASC 450, a loss contingency should be accrued when:',
  explanation = 'Under ASC 450-20-25, accrual of a loss contingency requires two conditions: (1) information available before the financial statements are issued indicates it is probable that an asset has been impaired or a liability has been incurred at the balance sheet date, and (2) the amount of the loss can be reasonably estimated. In Ridgemont''s case, both conditions are met — the loss is probable and estimated at $1.5 million — so a $1.5 million accrual is required. Choice A is incorrect because a "possible" loss does not meet the probability threshold — ASC 450 requires disclosure only when a loss is reasonably possible but not probable. Choice B is incorrect because ASC 450 uses the standard of "probable," not "certain" — waiting for certainty would understate liabilities and violate the conservatism principle.'
WHERE id = 192;

-- === Equity ===

-- Q441 [score:6] short-stem(10w) -> expand stem with scenario, cite ASC 718
UPDATE questions SET
  stem = 'Clearwater Corp. is designing its executive compensation plan for 2026 and is evaluating two equity-based instruments: restricted stock awards and restricted stock units (RSUs). The CFO asks the compensation committee to explain the key difference between these instruments for financial reporting purposes. Under ASC 718, restricted stock differs from restricted stock units in that:',
  explanation = 'Under ASC 718-10-25, restricted stock involves the actual issuance of shares to the employee at the grant date — the employee holds shares subject to forfeiture restrictions and typically receives dividends and voting rights during the vesting period. RSUs, by contrast, are contractual promises to deliver shares (or cash equivalent) upon vesting — the employee does not receive actual shares until the vesting conditions are satisfied. Both instruments are typically equity-classified and measured at grant-date fair value. Choice A is incorrect because restricted stock is generally equity-classified, not liability-classified — liability classification would apply only if the entity is obligated to settle in cash. Choice C is incorrect because it reverses the relationship: restricted stock holders typically have voting rights, while RSU holders do not receive shares (or voting rights) until vesting occurs.'
WHERE id = 441;

-- Q444 [score:6] length-cuing -> balance choice lengths
UPDATE questions SET
  choices = '["APIC from the original issuance up to the amount available, then retained earnings for the remainder","Treasury stock at the full reacquisition cost without any allocation to other equity accounts","Retained earnings for the full excess amount without reducing additional paid-in capital balances","A realized loss account reported in the other expenses section of the income statement"]',
  explanation = 'Under the par value method of treasury stock accounting, treasury stock is debited at par value, and APIC is debited for the amount originally credited to APIC when the shares were issued. Any excess of the reacquisition price over the original issuance price is debited to retained earnings (or APIC from treasury stock transactions, if a credit balance exists from prior treasury stock transactions). This method effectively reverses the original issuance entry. Choice B is incorrect because debiting treasury stock at the full reacquisition cost describes the cost method, not the par value method — the cost method records treasury stock at the price paid to reacquire the shares. Choice D is incorrect because treasury stock transactions are equity transactions that do not flow through the income statement under either method.'
WHERE id = 444;

-- === Governmental Accounting ===

-- Q177 [score:5] short-stem(8w) -> expand stem with scenario
UPDATE questions SET
  stem = 'A newly hired staff accountant at the City of Ridgemont is preparing the general fund financial statements for the fiscal year ended June 30, 2026. She asks her supervisor whether the general fund should report long-term capital assets and long-term debt, as she is accustomed to full accrual accounting from her private-sector experience. The supervisor explains that governmental funds use a different measurement focus. Under GASB standards, governmental funds use the:',
  explanation = 'Under GASB Statement No. 34, governmental funds (general, special revenue, capital projects, debt service, and permanent funds) use the current financial resources measurement focus and modified accrual basis of accounting. This means they report on the sources, uses, and balances of current financial resources — essentially cash and items expected to be converted to cash soon. Long-term assets and long-term liabilities are excluded from governmental fund statements and reported only at the government-wide level. Choice B is incorrect because the economic resources measurement focus is used by proprietary funds, fiduciary funds, and the government-wide financial statements — not by governmental funds. Choice C is incorrect because governmental funds use modified accrual, not the cash basis — revenues are recognized when measurable and available, not solely when cash is received.'
WHERE id = 177;

-- Q178 [score:5] short-stem(11w) -> expand stem with scenario
UPDATE questions SET
  stem = 'The City of Thornfield levied $12 million in property taxes on January 1, 2026, for the fiscal year ending December 31, 2026. By year-end, $11.2 million has been collected, with an additional $500,000 expected to be collected in January 2026 and $300,000 in March 2026. The city''s availability period is 60 days. The finance director must determine how much property tax revenue to recognize in the general fund for fiscal year 2026. Under GASB standards, property tax revenue should be recognized:',
  explanation = 'Under modified accrual accounting as prescribed by GASB Statement No. 34, revenue is recognized when it is both measurable and available. For property taxes, revenue is recognized in the period for which the taxes are levied, provided the taxes are collected within the availability period (typically 60 days after year-end). In Thornfield''s case, the $11.2 million collected during the year plus the $500,000 collected in January (within 60 days) would be recognized as revenue, while the $300,000 collected in March (beyond 60 days) would be reported as deferred inflows of resources. Choice A is incorrect because revenue recognition is not triggered by mailing assessment notices — the levy date and collection timing determine recognition. Choice C is incorrect because modified accrual is not pure cash basis — taxes are recognized as revenue when available, even if not yet collected.'
WHERE id = 178;

-- Q179 [score:5] short-stem(11w) -> expand stem with scenario
UPDATE questions SET
  stem = 'A GASB standards instructor is explaining to new government accounting staff at the City of Clearwater that the city must prepare two sets of financial statements — fund-level statements and government-wide statements — and that these statements use different bases of accounting. When preparing the government-wide statement of net position and statement of activities, the city must use the:',
  explanation = 'Under GASB Statement No. 34, the government-wide financial statements (statement of net position and statement of activities) use the economic resources measurement focus and the full accrual basis of accounting, similar to private-sector entities. This means revenues are recognized when earned and expenses when incurred, regardless of cash timing. Capital assets are reported and depreciated, and long-term liabilities are recognized. Choice A is incorrect because the modified accrual basis is used in governmental fund financial statements, not in the government-wide statements — using modified accrual at the government-wide level would exclude long-term assets and liabilities. Choice B is incorrect because the cash basis only recognizes transactions when cash changes hands, which would fail to report significant receivables, payables, and accruals required for a complete financial picture.'
WHERE id = 179;

-- Q459 [score:6] short-stem(9w) -> expand stem with scenario, cite GASB 75
UPDATE questions SET
  stem = 'The City of Barrington provides post-retirement health insurance benefits to eligible retired employees. The actuary engaged by the city is preparing the total OPEB liability calculation for the year ended June 30, 2026, and asks the finance director which actuarial cost method GASB requires. Under GASB Statement No. 75, the total OPEB liability must be measured using:',
  explanation = 'GASB Statement No. 75 (paragraph 22) requires the entry age normal cost method as the sole permissible actuarial cost method for measuring the total OPEB liability. This method spreads the actuarial present value of projected benefits as a level percentage of pay over each employee''s career from entry age to assumed exit age. Choice B is incorrect because GASB 75 does not permit a choice among actuarial methods — unlike older GASB standards, it prescribes a single method to ensure comparability across government employers. Choice C is incorrect because the projected unit credit method is required under FASB ASC 715 for private-sector employers, not under GASB standards — the two frameworks deliberately use different actuarial approaches.'
WHERE id = 459;

-- Q462 [score:5] short-stem(9w) -> expand stem with scenario
UPDATE questions SET
  stem = 'The public works department of the City of Thornfield issues a $45,000 purchase order on September 15, 2026, for road maintenance equipment to be delivered in November. The city uses the encumbrance system for budgetary control in its general fund. The finance director records an entry at the time the purchase order is issued. Under governmental fund accounting, an encumbrance is recorded when:',
  explanation = 'Under governmental fund budgetary accounting, an encumbrance is recorded when a purchase order or contract is issued, representing a commitment of appropriated budgetary resources for a future expenditure. The entry debits Encumbrances and credits Budgetary Fund Balance — Reserved for Encumbrances. When the equipment is received in November, the encumbrance is reversed and an expenditure is recorded at the actual invoice amount. Encumbrances provide budgetary control by reserving funds and preventing overspending of appropriations. Choice A is incorrect because receipt of goods triggers reversal of the encumbrance and recognition of an expenditure, not the initial encumbrance entry. Choice D is incorrect because budget adoption creates the budgetary entry (debit Estimated Revenues, credit Appropriations), not an encumbrance — encumbrances arise from specific purchasing commitments during the year.'
WHERE id = 462;

-- Q465 [score:6] short-stem(10w) -> expand stem with scenario, cite GASB 34
UPDATE questions SET
  stem = 'The finance director of the City of Clearwater is preparing the government-wide statement of activities for the fiscal year ended June 30, 2026. She must decide how to categorize the city''s $85 million in expenses across police, fire, parks, public works, and administration. Under GASB Statement No. 34, expenses in the government-wide statement of activities are reported by:',
  explanation = 'Under GASB Statement No. 34 (paragraph 38), the statement of activities presents expenses by function or program — such as general government, public safety, education, highways, and health and welfare. Program revenues (charges for services, operating grants, and capital grants) are reported directly alongside the function they support, and the net expense or revenue for each function is displayed. This functional format helps users assess the net cost of each government service. Choice A is incorrect because object classification (salaries, supplies, utilities) is used in detailed budgetary schedules and fund-level reporting, not in the government-wide statement of activities. Choice C is incorrect because fund-based presentation is used in governmental fund financial statements — the government-wide statements consolidate all governmental activities into a single column regardless of fund structure.'
WHERE id = 465;

-- === Intangible Assets ===

-- Q161 [score:6] short-stem(9w) -> expand stem with scenario, cite ASC 730
UPDATE questions SET
  stem = 'Thornfield Pharmaceuticals spent $2.3 million during 2025 on laboratory research to identify compounds for a new cardiovascular drug. The project is in its early stages, and no compounds have advanced to clinical trials. The CFO is determining how to account for these costs in the year-end financial statements. Under ASC 730, research and development costs are generally:',
  explanation = 'Under ASC 730-10-25, research and development costs are expensed as incurred because the future economic benefits are uncertain at the time the costs are incurred. Thornfield must expense the entire $2.3 million in 2025. Limited exceptions exist: R&D assets acquired in a business combination are capitalized at fair value under ASC 805, and software development costs are capitalized after technological feasibility is established under ASC 985-20. Choice A is incorrect because internally generated R&D costs cannot be capitalized as intangible assets — the uncertainty of future benefits fails to meet the asset recognition criteria. Choice B is incorrect because deferral and amortization would require reliable measurement of the benefit period, which is not possible during the research phase when the outcome remains uncertain.'
WHERE id = 161;

-- Q416 [score:5] short-stem(5w) -> expand stem with scenario, cite IAS 38
UPDATE questions SET
  stem = 'Ridgemont BioTech, a company reporting under IFRS, spent EUR 1.8 million during 2025 on basic research to explore potential applications of a new polymer compound. The project has not yet reached the development phase. The controller must determine the appropriate accounting treatment for these expenditures. Under IAS 38, research phase costs are:',
  explanation = 'Under IAS 38.54, research costs must always be expensed as incurred because during the research phase the entity cannot demonstrate that an intangible asset exists that will generate probable future economic benefits. Only development costs may be capitalized, and only when all six criteria in IAS 38.57 are met: technical feasibility, intention to complete, ability to use or sell, probable future economic benefits, availability of resources, and reliable measurement of costs. Choice C is incorrect because the six development criteria apply exclusively to the development phase — costs incurred during the research phase cannot be capitalized regardless of whether any criteria are met. Choice D is incorrect because IAS 38 does not permit arbitrary deferral and amortization of research costs over a fixed period — the standard explicitly requires immediate expensing.'
WHERE id = 416;

-- === Inventory ===

-- Q394 [score:5] short-stem(8w) -> expand stem with scenario
UPDATE questions SET
  stem = 'Clearwater Retailers experienced a warehouse fire that destroyed its inventory records. The controller decides to estimate ending inventory using the gross profit method, applying the company''s historical gross profit margin of 40% to net sales of $800,000. An accounting intern asks whether net markdowns should be factored into the estimate. Under the gross profit method, net markdowns are:',
  explanation = 'The gross profit method estimates ending inventory using only cost data — it does not use retail amounts at any point in the calculation. The method works by subtracting estimated cost of goods sold (net sales multiplied by the cost ratio, derived from the historical gross profit percentage) from cost of goods available for sale. Net markdowns are a concept relevant only to the retail inventory method, where goods are tracked at both cost and retail amounts. In Clearwater''s case, estimated COGS is $800,000 x 60% = $480,000. Choice A is incorrect because the gross profit method has no retail column — subtracting markdowns from retail is a step in the retail inventory method, not the gross profit method. Choice D is incorrect because the gross profit percentage is based on historical cost and sales data, not adjusted by current-period retail markdowns.'
WHERE id = 394;

-- === Leases ===

-- Q164 [score:6] short-stem(10w) -> expand stem with scenario, cite ASC 842
UPDATE questions SET
  stem = 'Ridgemont LLC enters into a lease for office equipment on January 1, 2026, with a lease term of 10 months and no purchase option. The controller asks whether the company can avoid recognizing a right-of-use asset and lease liability for this lease. Under ASC 842, the short-term lease exemption is available for leases with a term at or below:',
  explanation = 'Under ASC 842-20-25-2, a lessee may elect a practical expedient to not recognize right-of-use assets and lease liabilities for leases with a term of 12 months or less at commencement, provided the lease does not include a purchase option the lessee is reasonably certain to exercise. Ridgemont''s 10-month lease qualifies for this exemption, and payments would be recognized as expense on a straight-line basis over the lease term. Choice A is incorrect because ASC 842 uses a 12-month threshold, not 6 months — a 6-month cutoff would be overly restrictive and is not part of the standard. Choice B is incorrect because 36 months significantly exceeds the short-term lease exemption threshold and would require full recognition of a right-of-use asset and lease liability.'
WHERE id = 164;

-- Q166 [score:5] absolute-assurance-trap -> replace trap distractors with realistic misconceptions
UPDATE questions SET
  choices = '["Rental income recognized on a straight-line basis and the underlying asset retained on the balance sheet","A net investment in the lease and a lease receivable, with no derecognition of the underlying asset","A right-of-use asset and a corresponding lease liability measured at present value of payments","A net investment in the lease, any selling profit or loss, and derecognition of the underlying asset"]',
  explanation = 'Under ASC 842-30-25-1, in a sales-type lease the lessor derecognizes the underlying asset from its balance sheet, recognizes a net investment in the lease (comprising the lease receivable and any unguaranteed residual asset), and recognizes selling profit or loss at commencement — measured as the difference between the fair value of the underlying asset and its carrying amount. This treatment reflects that the lessor has effectively transferred control of the asset to the lessee. Choice A is incorrect because straight-line rental income and retaining the asset describe operating lease treatment under ASC 842-30-25-11, not sales-type lease treatment. Choice B is incorrect because a defining feature of a sales-type lease is derecognition of the underlying asset — retaining it on the balance sheet contradicts the economics of the transaction.'
WHERE id = 166;

-- Q418 [score:6] absolute-assurance-trap -> replace trap distractors with realistic misconceptions
UPDATE questions SET
  choices = '["The present value of lease payments equals or exceeds substantially all of the fair value of the asset","The lease term covers at least 50% of the asset''s total remaining economic life at commencement","The lessee has provided a residual value guarantee to the lessor covering any decline in asset value","The lessor has incurred significant initial direct costs in negotiating and arranging the lease"]',
  explanation = 'Under ASC 842-10-25-2, a lessor classifies a lease as sales-type if any of five criteria are met: (1) the lease transfers ownership, (2) there is a purchase option the lessee is reasonably certain to exercise, (3) the lease term is for the major part of the remaining economic life, (4) the present value of lease payments and any residual value guarantee by the lessee equals or exceeds substantially all of the fair value, or (5) the asset is so specialized it has no alternative use to the lessor. Choice B is incorrect because ASC 842 uses "major part" of economic life (generally interpreted as 75%), not 50% — a 50% threshold would capture too many leases that do not represent effective transfers of control. Choice C is incorrect because a residual value guarantee alone does not trigger sales-type classification — it is only factored into the present value calculation under criterion (4).'
WHERE id = 418;

-- Q419 [score:5] absolute-assurance-trap -> replace trap distractors with realistic misconceptions
UPDATE questions SET
  choices = '["A sales-type lease because the lessee obtains substantially all economic benefits from the asset","A direct financing lease because the present value test is partially met at the 60% threshold","An operating lease because none of the five sales-type criteria or direct financing criteria are met","A finance lease under ASC 842 because the lease term exceeds one year at commencement"]',
  explanation = 'Since none of the five sales-type criteria are met — no ownership transfer, no purchase option, 3 out of 10 years is not the major part of economic life, 60% is not substantially all of fair value, and the asset is not specialized — the lease is not classified as sales-type. It also does not meet direct financing criteria (which require the present value test or economic life test to be met, plus no selling profit, and collectibility is probable). Therefore, the lessor classifies this as an operating lease under ASC 842-10-25-3, recognizing rental income on a straight-line basis over the lease term. Choice A is incorrect because none of the five sales-type classification criteria are satisfied — "obtaining economic benefits" is not itself a classification criterion. Choice B is incorrect because 60% of fair value does not meet the "substantially all" threshold required under criterion (4), and direct financing also requires the present value or economic life test to be met.'
WHERE id = 419;

-- === Not-for-Profit Accounting ===

-- Q184 [score:5] short-stem(11w) -> expand stem with scenario, cite ASU 2016-14
UPDATE questions SET
  stem = 'The board of directors of the Ridgemont Community Foundation, a not-for-profit organization, asks the finance director to present a more detailed breakdown of expenses in the annual financial statements. The finance director explains that current standards already require a specific format for expense reporting. Under ASU 2016-14, a not-for-profit organization must report expenses by:',
  explanation = 'Under ASU 2016-14 (ASC 958-720-45), not-for-profit organizations must report expenses by both their functional classification (program services, management and general, fundraising) and their natural classification (salaries, rent, depreciation, supplies). This dual presentation can appear on the face of the statement of activities, in a separate statement of functional expenses, or in the notes to the financial statements. The requirement ensures that financial statement users can evaluate both the purposes for which resources were spent and the types of costs incurred. Choice A is incorrect because reporting expenses by function only would omit the natural classification detail that helps users understand the types of costs incurred within each program. Choice B is incorrect because reporting by nature only would omit the functional classification needed to evaluate how much is spent on programs versus supporting services like administration and fundraising.'
WHERE id = 184;

-- Q467 [score:5] short-stem(11w) -> expand stem with scenario, cite ASU 2018-08
UPDATE questions SET
  stem = 'The Clearwater Arts Foundation receives a $500,000 pledge from a corporate donor. The pledge agreement states that funds will be released only after the Foundation secures matching donations of $500,000 from other sources, and if the match is not achieved within two years, the donor has no obligation to pay. The controller must determine whether this pledge represents a conditional or unconditional contribution. Under ASC 958, as clarified by ASU 2018-08, a contribution is considered conditional if it includes:',
  explanation = 'Under ASU 2018-08 (ASC 958-605-25-5A), a conditional contribution has two essential characteristics: (1) a barrier — a measurable performance-related or other condition that must be overcome (such as the matching requirement in Clearwater''s pledge agreement), and (2) a right of return of assets transferred or a release of the promisor from the obligation if the barrier is not met (the donor has no obligation if the match is not achieved). The Foundation would not recognize revenue until the $500,000 matching condition is satisfied. Choice B is incorrect because a restriction on how funds are used (e.g., "for scholarship purposes only") is a donor restriction under ASC 958-605, not a condition — restricted contributions are recognized as revenue when received. Choice D is incorrect because a reporting requirement is an administrative obligation, not a substantive barrier — the donor retains no right of return simply because a report is not filed.'
WHERE id = 467;

-- Q468 [score:6] length-cuing -> balance choice lengths
UPDATE questions SET
  choices = '["Are donated by a licensed professional such as an attorney, physician, or certified public accountant","Are donated during the entity''s fiscal year and exceed a de minimis fair value threshold","Exceed $5,000 in total fair value when aggregated across all volunteer hours during the period","Create or enhance a nonfinancial asset, or require specialized skills that would need to be purchased"]',
  explanation = 'Under ASC 958-605-25-16, contributed services are recognized as revenue only if they (1) create or enhance a nonfinancial asset (such as constructing a building), or (2) require specialized skills (e.g., accounting, legal, medical), are provided by individuals possessing those skills, and would typically need to be purchased if not donated. General volunteer services — such as ushering, serving food, or filing papers — do not meet these criteria and are not recognized as revenue. Choice A is incorrect because the standard focuses on whether services require specialized skills, not whether the donor holds a specific professional license — an unlicensed person providing skilled carpentry could qualify. Choice C is incorrect because ASC 958 establishes no dollar threshold for contributed services — recognition depends on the nature of the services, not their aggregate value.'
WHERE id = 468;

-- === Revenue Recognition ===

-- Q150 [score:5] short-stem(11w) + length-cuing -> expand stem with scenario, balance choices
UPDATE questions SET
  stem = 'Thornfield Construction enters into a $6 million contract to build a custom warehouse for Barrington Logistics on Barrington''s property. Construction will span 18 months. As work progresses, Barrington controls the partially completed structure. The controller must determine whether revenue should be recognized over time or at a point in time. Under ASC 606, a performance obligation is satisfied over time when:',
  choices = '["The customer makes the final payment upon delivery and formal acceptance of the completed asset","The contract reaches its scheduled completion date and both parties sign a certificate of acceptance","The entity signs the contract and both parties agree to the transaction price and scope of work","The customer receives benefits as work is performed, or the asset has no alternative use with payment rights"]',
  explanation = 'Under ASC 606-10-25-27, a performance obligation is satisfied over time if any one of three criteria is met: (1) the customer simultaneously receives and consumes the benefits as the entity performs (e.g., routine cleaning services), (2) the entity''s performance creates or enhances a customer-controlled asset (as in Thornfield''s case — Barrington controls the warehouse during construction on its property), or (3) the entity''s performance does not create an asset with alternative use to the entity and the entity has an enforceable right to payment for performance completed to date. Choice A is incorrect because conditioning revenue on final payment describes point-in-time recognition, not over-time recognition — under over-time recognition, revenue is recognized as work progresses. Choice B is incorrect because reaching the completion date is a point-in-time event, and ASC 606 over-time criteria focus on the pattern of benefit transfer, not contract milestones.'
WHERE id = 150;

-- Q153 [score:6] short-stem(11w) -> expand stem with scenario, cite ASC 606
UPDATE questions SET
  stem = 'Clearwater Software enters into a three-year license and maintenance contract with Ridgemont Financial for $900,000. Six months into the contract, Ridgemont requests additional customization features and an extended support term. Both parties agree to increase the contract price by $150,000. The controller must determine whether this change constitutes a contract modification. Under ASC 606, a contract modification is:',
  explanation = 'Under ASC 606-10-25-10, a contract modification is a change to the scope or price (or both) of a contract that is approved by the parties to the contract. It creates new or changes existing enforceable rights and obligations. Clearwater''s agreed-upon expansion of scope and $150,000 price increase is a contract modification that must be evaluated to determine whether it should be treated as a separate contract or as a modification of the existing contract. Choice A is incorrect because a change in the transaction price due to variable consideration (such as a performance bonus or penalty) is a remeasurement of the original contract terms, not a modification — no new approval is required. Choice B is incorrect because exercising an existing option was already contemplated in the original contract terms and does not create new enforceable rights — it activates pre-existing rights.'
WHERE id = 153;

-- === Statement of Cash Flows ===

-- Q190 [score:5] short-stem(10w) -> expand stem with scenario
UPDATE questions SET
  stem = 'Thornfield Industries reported several transactions during the year ended December 31, 2025: it purchased a patent for $400,000, collected a $200,000 note receivable from a customer, paid $150,000 in dividends to shareholders, and received $75,000 in interest on short-term investments. The controller is preparing the statement of cash flows and must classify each transaction. Which of the following transactions is classified as a financing activity?',
  explanation = 'Under ASC 230-10-45, financing activities involve transactions with owners and creditors of the entity that affect its capital structure, including issuing and repurchasing stock, borrowing and repaying debt, and paying dividends to shareholders. Thornfield''s $150,000 dividend payment is a financing activity because it represents a distribution of earnings to equity holders. Choice A is incorrect because purchasing a patent is an investing activity — it represents the acquisition of a long-lived asset that will generate future economic benefits. Choice B is incorrect because collecting a note receivable is an investing activity — it represents the recovery of principal on a lending arrangement, which involves deploying resources in assets outside the entity''s primary operations.'
WHERE id = 190;
