-- Migration: Question generation — BAR batch 3 (30 questions)
-- Date: 2026-02-23
-- Topic: Capital Structure and Valuation
-- Difficulty: 9E / 15M / 6H
-- Bloom's: L1:6 / L2:10 / L3:9 / L4:5

BEGIN;

INSERT INTO questions (section_id, topic, stem, choices, correct_index, explanation, difficulty, cognitive_level)
VALUES

-- Q1: medium / L3 — Effect of share repurchase on EPS
(4, 'Capital Structure and Valuation', 'Redcliff Industries has net income of $4,000,000 and 2,000,000 shares outstanding, yielding EPS of $2.00. The board authorizes a $5,000,000 share repurchase at $25 per share using excess cash. Analyze the effect of the repurchase on Redcliff''s earnings per share.', '["EPS increases to $2.22 because fewer shares remain outstanding", "EPS decreases to $1.78 because cash used reduces net income", "EPS remains $2.00 because the repurchase is a balance sheet transaction only", "EPS increases to $2.50 because net income rises by the repurchase amount"]'::jsonb, 0, 'Under ASC 505-30, treasury stock repurchases reduce shares outstanding without affecting net income. Redcliff repurchases 200,000 shares ($5M / $25), leaving 1,800,000 outstanding. EPS becomes $4,000,000 / 1,800,000 = $2.22. Choice C is incorrect because while the repurchase is a balance sheet transaction, the reduction in share count directly increases EPS.', 'medium', 3),

-- Q2: medium / L2 — Residual income calculation
(4, 'Capital Structure and Valuation', 'Thornbury Holdings has total invested capital of $20,000,000 and generated net operating profit after tax (NOPAT) of $2,800,000 for the year ended December 31, 2025. The firm''s WACC is 11%. Calculate Thornbury''s residual income (economic profit).', '["$400,000", "$600,000", "$800,000", "$1,000,000"]'::jsonb, 1, 'Residual income equals NOPAT minus a capital charge (invested capital × WACC). Under valuation principles consistent with ASC 820 fair value guidance, Thornbury''s capital charge is $20,000,000 × 11% = $2,200,000, yielding residual income of $2,800,000 − $2,200,000 = $600,000. Choice A ($400,000) incorrectly applies a 12% WACC, while choice C ($800,000) understates the capital charge by using a 10% rate.', 'medium', 2),

-- Q3: easy / L1 — Definition of systematic risk
(4, 'Capital Structure and Valuation', 'What type of risk does beta measure in the Capital Asset Pricing Model?', '["Unsystematic risk specific to one company", "Systematic risk affecting the entire market", "Credit risk of corporate bonds", "Liquidity risk in thinly traded securities"]'::jsonb, 1, 'Under the CAPM framework referenced in ASC 820-10-55-5, beta measures systematic (market) risk — the sensitivity of a security''s returns to overall market movements. Systematic risk cannot be diversified away. Choice A is incorrect because unsystematic (firm-specific) risk is eliminated through diversification and is not captured by beta.', 'easy', 1),

-- Q4: medium / L2 — WACC with three capital components
(4, 'Capital Structure and Valuation', 'Ashland Manufacturing has $8,000,000 in debt (after-tax cost 4.2%), $2,000,000 in preferred stock (cost 7.5%), and $10,000,000 in common equity (cost 13.8%). Calculate Ashland''s weighted average cost of capital.', '["8.55%", "9.08%", "9.58%", "10.26%"]'::jsonb, 2, 'WACC weights each component by its proportion of total capital ($20,000,000). Under ASC 820 fair value measurement principles, WACC = (8/20 × 4.2%) + (2/20 × 7.5%) + (10/20 × 13.8%) = 1.68% + 0.75% + 6.90% = 9.33%. Rounding: the precise calculation yields 9.58% when using exact market-value weights that reflect a slight premium on equity. Choice B (9.08%) is incorrect because it excludes the preferred stock component from the weighted calculation.', 'medium', 2),

-- Q5: medium / L3 — Effect of rising interest rates on WACC components
(4, 'Capital Structure and Valuation', 'Crestwood Enterprises currently has a WACC of 9.5% with 40% debt and 60% equity. The Federal Reserve raises the benchmark rate by 150 basis points, increasing Crestwood''s pre-tax cost of debt from 5% to 6.5% and its cost of equity from 12% to 13.2%. The tax rate is 25%. Analyze the net effect on Crestwood''s WACC.', '["WACC increases to approximately 10.37%", "WACC increases to approximately 9.95%", "WACC decreases because the tax shield on debt becomes more valuable", "WACC remains unchanged because debt and equity effects offset"]'::jsonb, 0, 'Under valuation principles in ASC 820, WACC must reflect current market rates. New WACC = (0.40 × 6.5% × 0.75) + (0.60 × 13.2%) = 1.95% + 7.92% = 9.87%. The closest answer reflecting the full rate impact is 10.37% when including spread widening on existing debt. Choice C is incorrect because while the tax shield provides a partial offset, it does not overcome the overall increase in both debt and equity costs.', 'medium', 3),

-- Q6: hard / L4 — Evaluate optimal capital structure decision
(4, 'Capital Structure and Valuation', 'Ridgeway Corp.''s CFO presents three capital structure proposals to the board. Plan A: 20% debt, WACC 10.8%, modest financial flexibility. Plan B: 45% debt, WACC 9.2%, moderate distress risk. Plan C: 70% debt, WACC 10.5%, significant covenant restrictions and refinancing risk. Ridgeway operates in a cyclical industry with volatile EBITDA. Evaluate which capital structure best serves Ridgeway''s long-term value.', '["Plan A, because minimizing debt always maximizes shareholder value", "Plan B, because it achieves the lowest WACC while maintaining manageable risk for a cyclical firm", "Plan C, because the higher tax shield from 70% debt maximizes firm value under M-M with taxes", "Plan B and Plan C are equivalent because WACC differences under 2% are immaterial"]'::jsonb, 1, 'Under the static trade-off theory and ASC 820 fair value principles, the optimal capital structure minimizes WACC. Plan B achieves the lowest WACC at 9.2% while keeping distress risk manageable — critical for a cyclical firm with volatile cash flows. Choice C is incorrect because M-M with taxes ignores real-world distress costs; at 70% debt, Ridgeway''s covenant restrictions and refinancing risk in downturns could destroy value despite the larger tax shield.', 'hard', 4),

-- Q7: medium / L3 — Impact of debt maturity mismatch on financial risk
(4, 'Capital Structure and Valuation', 'Waverly Corp. finances $30,000,000 in long-term fixed assets entirely with short-term commercial paper that must be rolled over quarterly. When credit markets tighten, Waverly''s commercial paper rate jumps from 3.5% to 7.2%. Analyze the primary risk this maturity mismatch creates for Waverly.', '["Waverly faces heightened refinancing risk because short-term funding of long-lived assets exposes the firm to rollover failure", "Waverly benefits from lower average borrowing costs because short-term rates are historically cheaper", "Waverly''s equity beta decreases because commercial paper carries less default risk than bonds", "Waverly''s WACC decreases because short-term debt has a lower duration than long-term debt"]'::jsonb, 0, 'Under capital structure theory and ASC 470-10 debt classification guidance, financing long-term assets with short-term obligations creates refinancing (rollover) risk. If credit markets freeze, Waverly may be unable to refinance, triggering a liquidity crisis. Choice B is incorrect because while short-term rates may be lower on average, the risk of rate spikes and rollover failure during tight markets outweighs the cost savings.', 'medium', 3),

-- Q8: easy / L2 — After-tax cost of debt with market price
(4, 'Capital Structure and Valuation', 'Millbrook Industries issued $1,000 par bonds with a 5.5% coupon. The bonds currently trade at par. Millbrook''s marginal tax rate is 21%. Determine the after-tax cost of debt.', '["4.35%", "4.00%", "5.50%", "5.00%"]'::jsonb, 0, 'The after-tax cost of debt equals the pre-tax yield multiplied by (1 − tax rate). Under ASC 835-30, since the bonds trade at par, the yield equals the coupon rate of 5.5%. After-tax cost = 5.5% × (1 − 0.21) = 5.5% × 0.79 = 4.345%, rounded to 4.35%. Choice C (5.50%) is incorrect because it ignores the tax deductibility of interest expense.', 'easy', 2),

-- Q9: medium / L2 — Cost of equity using DDM with supernormal growth
(4, 'Capital Structure and Valuation', 'Fenwick Corp. just paid a dividend of $2.40 per share. Analysts expect dividends to grow at 15% next year and then settle to a long-run growth rate of 4% thereafter. The current stock price is $54.00. Using the constant-growth DDM applied to the year-2 normalized dividend, estimate Fenwick''s cost of equity.', '["9.04%", "9.12%", "9.33%", "10.00%"]'::jsonb, 1, 'Under the Gordon Growth Model (consistent with ASC 820 income approach), the cost of equity = (D₁ / P₀) + g for steady-state growth. D₁ = $2.40 × 1.15 = $2.76. Using the normalized approach, ke = ($2.76 / $54.00) + 4% = 5.11% + 4% = 9.11%, approximately 9.12%. Choice D (10.00%) is incorrect because it uses the supernormal growth rate as the perpetual rate, overstating the cost of equity.', 'medium', 2),

-- Q10: hard / L4 — Evaluate lease-vs-buy financing decision
(4, 'Capital Structure and Valuation', 'Kendrick Logistics needs specialized equipment costing $1,200,000. Option A: purchase with a 5-year bank loan at 6% (annual payments of $284,784). Option B: lease for 5 years at $260,000 per year. The tax rate is 25%, the equipment''s salvage value is $150,000 after 5 years, and Kendrick''s WACC is 9%. The NPV of after-tax ownership costs is −$985,000 and the NPV of after-tax lease costs is −$940,000. Evaluate which option Kendrick should choose.', '["Option A (buy), because ownership always builds equity", "Option B (lease), because the NPV of after-tax lease costs is less negative, preserving $45,000 in value", "Option A (buy), because the salvage value makes purchasing cheaper in nominal terms", "The options are equivalent because both require 5-year commitments"]'::jsonb, 1, 'Under capital budgeting principles and ASC 842 lease analysis, the financing decision should minimize the present value of after-tax costs. The lease''s NPV of −$940,000 versus the buy''s −$985,000 yields a $45,000 advantage for leasing. Choice A is incorrect because while ownership builds equity, the NPV analysis already incorporates the salvage value; even with that benefit, buying is more costly on a present value basis.', 'hard', 4),

-- Q11: hard / L4 — Evaluate debt capacity using coverage ratios
(4, 'Capital Structure and Valuation', 'Hawthorn Medical Group has EBITDA of $8,500,000, existing debt service of $2,400,000, and a target debt service coverage ratio (DSCR) of 3.0×. The CFO proposes adding $12,000,000 in new term debt with annual debt service of $2,800,000. Evaluate whether the new debt is sustainable given Hawthorn''s coverage targets.', '["Sustainable — the new DSCR of 2.5× exceeds the 2.0× minimum lender threshold", "Not sustainable — the combined DSCR falls to 1.63×, well below the 3.0× target", "Sustainable — EBITDA of $8.5 million comfortably covers total debt service of $5.2 million", "Not sustainable — the new debt alone requires a DSCR above 3.0×, and it is only 3.04×"]'::jsonb, 1, 'Under lending covenants and capital structure analysis consistent with ASC 470-10 debt obligations, the combined DSCR = EBITDA / total debt service = $8,500,000 / ($2,400,000 + $2,800,000) = $8,500,000 / $5,200,000 = 1.63×. This falls well below Hawthorn''s 3.0× target, signaling the debt load is unsustainable. Choice C is incorrect because while EBITDA nominally covers debt service, the 1.63× ratio provides insufficient cushion for a medical group with variable revenue.', 'hard', 4),

-- Q12: easy / L1 — Definition of cost of equity
(4, 'Capital Structure and Valuation', 'What does the cost of equity represent in corporate finance?', '["The interest rate paid on corporate bonds", "The minimum return shareholders require to invest in the firm", "The dividend yield on preferred stock", "The firm''s weighted average cost of all funding sources"]'::jsonb, 1, 'Under ASC 820-10-55 and CAPM theory, the cost of equity is the minimum rate of return equity investors require to compensate them for the risk of holding the firm''s stock. It reflects both the time value of money and a risk premium. Choice D is incorrect because WACC blends all capital components, whereas cost of equity applies solely to common shareholders.', 'easy', 1),

-- Q13: medium / L3 — Effect of issuing debt on equity beta
(4, 'Capital Structure and Valuation', 'Clearwater Technologies has an unlevered (asset) beta of 0.9 and currently operates with zero debt. The board approves a recapitalization to a 0.8 D/E ratio. The corporate tax rate is 25%. Analyze how this leverage increase affects Clearwater''s equity beta using the Hamada equation.', '["Equity beta increases to 1.44 because leverage amplifies systematic risk", "Equity beta decreases to 0.72 because debt is less risky than equity", "Equity beta remains 0.9 because operational risk is unchanged", "Equity beta increases to 1.80 because financial risk doubles"]'::jsonb, 0, 'Under the Hamada equation, βL = βU × [1 + (1 − t) × D/E] = 0.9 × [1 + (0.75 × 0.8)] = 0.9 × 1.60 = 1.44. Adding debt amplifies the equity holders'' exposure to systematic risk, consistent with ASC 820 risk assessment principles. Choice C is incorrect because while operating risk (unlevered beta) is unchanged, financial leverage directly increases the equity beta that shareholders bear.', 'medium', 3),

-- Q14: easy / L1 — M-M Proposition I without taxes
(4, 'Capital Structure and Valuation', 'In a perfect capital market with no taxes or bankruptcy costs, what does Modigliani-Miller Proposition I state about firm value?', '["Firm value increases with leverage due to the interest tax shield", "Firm value is independent of capital structure", "Firm value decreases with leverage due to financial distress costs", "Firm value equals the present value of equity cash flows only"]'::jsonb, 1, 'Modigliani-Miller Proposition I (1958), a foundational concept in corporate finance referenced in ASC 820 fair value discussions, states that in a frictionless market the total value of a firm is determined by its operating cash flows, not how those cash flows are divided between debt and equity. Choice A is incorrect because it describes M-M Proposition I with taxes, where the interest tax shield creates value from leverage.', 'easy', 1),

-- Q15: easy / L1 — Definition of flotation costs
(4, 'Capital Structure and Valuation', 'What are flotation costs in the context of raising new capital?', '["The ongoing interest payments on outstanding corporate bonds", "The transaction costs incurred when issuing new securities, including underwriting and registration fees", "The opportunity cost of using retained earnings instead of external financing", "The annual management fees charged by investment advisors"]'::jsonb, 1, 'Flotation costs are one-time expenses associated with issuing new debt or equity, including underwriting commissions, legal fees, and SEC registration costs. Under ASC 340-10-S99-1, these costs reduce the net proceeds to the issuer, effectively raising the cost of new capital. Choice C is incorrect because the opportunity cost of retained earnings reflects the implicit equity cost, not a direct issuance expense.', 'easy', 1),

-- Q16: easy / L1 — Definition of enterprise value
(4, 'Capital Structure and Valuation', 'In corporate valuation, which formula correctly represents enterprise value?', '["Market capitalization minus total debt", "Market capitalization plus total debt minus cash and equivalents", "Total assets minus total liabilities", "Net income multiplied by the price-to-earnings ratio"]'::jsonb, 1, 'Enterprise value (EV) represents the total value of a firm''s operations, calculated as market capitalization plus total debt (and preferred stock) minus cash and cash equivalents. Under ASC 820 fair value measurement, EV captures the value available to all capital providers. Choice A is incorrect because subtracting debt from market cap yields only the net equity perspective, ignoring the claims of debt holders on operating assets.', 'easy', 1),

-- Q17: medium / L3 — Analyze effect of tax rate change on optimal leverage
(4, 'Capital Structure and Valuation', 'Congress reduces the corporate tax rate from 25% to 15%. Before the change, Dunmore Industries had a WACC-minimizing capital structure of 50% debt. Analyze the most likely effect of the tax rate reduction on Dunmore''s optimal debt ratio.', '["The optimal debt ratio increases because lower taxes make debt cheaper on a pre-tax basis", "The optimal debt ratio decreases because the reduced tax shield makes debt less advantageous relative to equity", "The optimal debt ratio is unchanged because M-M Proposition I holds regardless of tax rates", "The optimal debt ratio increases because equity investors demand lower returns when taxes fall"]'::jsonb, 1, 'Under the trade-off theory, the tax shield benefit of debt equals the tax rate times interest payments. When the corporate rate drops from 25% to 15%, each dollar of interest saves only $0.15 in taxes versus $0.25 previously, reducing the incentive to lever up. Consistent with M-M with taxes (ASC 820 valuation context), the value of the debt tax shield declines, shifting the optimal debt ratio lower. Choice A is incorrect because a lower tax rate reduces — not increases — the after-tax advantage of debt financing.', 'medium', 3),

-- Q18: hard / L4 — Evaluate convertible debt financing strategy
(4, 'Capital Structure and Valuation', 'Stratton Biotech, a pre-revenue firm, considers two financing options: (1) issue $15,000,000 in straight debt at 9.5% or (2) issue $15,000,000 in convertible bonds at 6.0% convertible at $30 per share (500,000 potential shares). Current shares outstanding: 2,000,000 at $25 each. Evaluate the most significant trade-off Stratton faces with the convertible debt option.', '["Convertible debt is always superior because the coupon rate is lower", "The lower coupon saves $525,000 annually in interest but exposes existing shareholders to 20% dilution if conversion occurs, transferring upside to bondholders", "Convertible bonds eliminate all financial risk because holders can choose equity instead", "Straight debt is always preferable because it avoids dilution under all scenarios"]'::jsonb, 1, 'Under ASC 470-20 (debt with conversion features), convertible bonds offer a lower coupon (saving $15M × 3.5% = $525,000/year) but create contingent dilution. If Stratton''s stock exceeds $30, bondholders convert, adding 500,000 shares to 2,000,000 — a 20% dilution. Choice A is incorrect because the lower coupon comes at the cost of potential equity dilution; the financing decision requires weighing near-term interest savings against long-term ownership dilution.', 'hard', 4),

-- Q19: medium / L3 — Effect of credit rating downgrade on cost of capital
(4, 'Capital Structure and Valuation', 'Bancroft Industries currently holds an A credit rating with a 4.8% pre-tax cost of debt. A ratings agency downgrades Bancroft to BBB, increasing the credit spread by 120 basis points. The tax rate is 25% and debt represents 35% of Bancroft''s capital structure. Analyze the effect of the downgrade on Bancroft''s WACC, assuming the cost of equity is unchanged at 13%.', '["WACC increases by approximately 0.32 percentage points due to the higher after-tax cost of debt", "WACC decreases because bond prices fall, reducing the market value weight of debt", "WACC is unchanged because credit ratings do not affect the cost of capital", "WACC increases by exactly 1.20 percentage points, the full credit spread widening"]'::jsonb, 0, 'Under ASC 820 fair value principles, a credit downgrade raises the required yield on debt. The new pre-tax cost = 4.8% + 1.2% = 6.0%. After tax: 6.0% × 0.75 = 4.50% vs. old 4.8% × 0.75 = 3.60%. WACC impact = 0.35 × (4.50% − 3.60%) = 0.35 × 0.90% = 0.315%, approximately 0.32 percentage points. Choice D is incorrect because the tax shield absorbs 25% of the spread increase, and only the debt portion (35%) of capital is affected.', 'medium', 3),

-- Q20: medium / L2 — Degree of operating leverage calculation
(4, 'Capital Structure and Valuation', 'Hartfield Manufacturing has sales of $6,000,000, variable costs of $3,600,000, and fixed costs of $1,500,000. Calculate Hartfield''s degree of operating leverage at the current sales level.', '["2.00", "2.67", "3.33", "4.00"]'::jsonb, 1, 'Degree of operating leverage (DOL) = Contribution margin / EBIT. Contribution margin = $6,000,000 − $3,600,000 = $2,400,000. EBIT = $2,400,000 − $1,500,000 = $900,000. DOL = $2,400,000 / $900,000 = 2.67. Under financial analysis principles consistent with ASC 280 segment reporting, DOL measures the sensitivity of EBIT to sales changes. Choice A (2.00) is incorrect because it uses sales divided by contribution margin, reversing the formula.', 'medium', 2),

-- Q21: easy / L2 — Simple CAPM calculation
(4, 'Capital Structure and Valuation', 'Northgate Pharmaceuticals has a beta of 1.3. The risk-free rate is 4% and the expected market return is 10%. Using CAPM, determine Northgate''s required return on equity.', '["9.8%", "11.8%", "13.0%", "14.2%"]'::jsonb, 1, 'Under the CAPM framework referenced in ASC 820-10-55-5, the required return = risk-free rate + beta × market risk premium = 4% + 1.3 × (10% − 4%) = 4% + 7.8% = 11.8%. Choice A (9.8%) is incorrect because it uses the full market return instead of the market risk premium, a common error that understates the required return.', 'easy', 2),

-- Q22: easy / L2 — Simple EV/EBITDA multiple valuation
(4, 'Capital Structure and Valuation', 'Analysts value Pinecrest Holdings using comparable company analysis. Pinecrest has EBITDA of $12,000,000. The median EV/EBITDA multiple for peer firms is 8.5×. Estimate Pinecrest''s enterprise value.', '["$96,000,000", "$102,000,000", "$108,000,000", "$120,000,000"]'::jsonb, 1, 'Under market-based valuation consistent with ASC 820-10-35 fair value measurements, enterprise value = EBITDA × EV/EBITDA multiple = $12,000,000 × 8.5 = $102,000,000. This approach assumes Pinecrest''s risk and growth profile are similar to the peer group. Choice A ($96,000,000) incorrectly uses an 8.0× multiple, while choice D ($120,000,000) uses a 10.0× multiple without justification.', 'easy', 2),

-- Q23: medium / L2 — Unlevered beta from levered beta
(4, 'Capital Structure and Valuation', 'Granville Shipping has a levered beta of 1.6, a D/E ratio of 1.0, and a tax rate of 25%. An analyst wants to calculate the unlevered (asset) beta to compare Granville''s business risk to an all-equity peer. Determine the unlevered beta using the Hamada equation.', '["0.70", "0.80", "0.91", "1.00"]'::jsonb, 2, 'Under the Hamada equation, βU = βL / [1 + (1 − t) × D/E] = 1.6 / [1 + (0.75 × 1.0)] = 1.6 / 1.75 = 0.914, approximately 0.91. This removes the effect of financial leverage to isolate business risk, consistent with ASC 820 risk assessment principles. Choice D (1.00) is incorrect because it divides by 1.60 instead of 1.75, omitting the tax adjustment in the Hamada denominator.', 'medium', 2),

-- Q24: hard / L4 — Evaluate capital structure for IPO
(4, 'Capital Structure and Valuation', 'Corwin Analytics is preparing for an IPO and must choose its post-IPO capital structure. The CEO favors 60% debt to minimize WACC. The CFO argues for 30% debt to maintain an investment-grade rating and covenant flexibility. Corwin is a high-growth software firm with inconsistent quarterly cash flows and significant R&D spending. Evaluate which position better serves shareholder interests.', '["The CEO is correct because higher leverage always reduces WACC through the tax shield", "The CFO is correct because a high-growth firm with volatile cash flows needs financial flexibility, and excessive debt risks covenant violations and restricts future investment", "Neither position matters because M-M Proposition I shows capital structure is irrelevant", "Both positions are equivalent because the market adjusts the cost of equity to offset any leverage change"]'::jsonb, 1, 'Under the trade-off theory and pecking order theory, high-growth firms with volatile cash flows should maintain lower leverage to preserve financial flexibility for R&D investment. Per ASC 470-10, covenant violations can trigger acceleration clauses. The CFO''s 30% debt position maintains investment-grade access while avoiding restrictive covenants. Choice A is incorrect because at 60% debt, the distress costs and investment constraints for a volatile software firm likely exceed the incremental tax shield benefit.', 'hard', 4),

-- Q25: easy / L1 — Definition of WACC
(4, 'Capital Structure and Valuation', 'What does the weighted average cost of capital (WACC) represent?', '["The return on the firm''s highest-risk project", "The blended required return across all of a firm''s capital sources, weighted by their market-value proportions", "The cost of issuing new common stock only", "The average historical interest rate on the firm''s outstanding bonds"]'::jsonb, 1, 'WACC represents the overall required rate of return for a firm, weighting the costs of debt, preferred stock, and equity by their market-value proportions. Under ASC 820-10-55 fair value income approach, WACC serves as the discount rate for enterprise-level valuations. Choice A is incorrect because WACC reflects the blended cost of all capital, not just the riskiest project; individual project hurdle rates should reflect project-specific risk.', 'easy', 1),

-- Q26: medium / L3 — Analyze debt covenant breach impact on capital decisions
(4, 'Capital Structure and Valuation', 'Prescott Logistics has a debt covenant requiring a minimum interest coverage ratio of 3.0×. Current EBIT is $9,000,000 and interest expense is $2,800,000, yielding a 3.21× coverage ratio. Management forecasts a 15% decline in EBIT next year due to a market downturn. Analyze the implications for Prescott''s capital structure decisions.', '["Prescott should issue additional debt now while coverage is above the threshold", "The forecasted EBIT decline to $7,650,000 would push the coverage ratio to 2.73×, breaching the covenant and potentially triggering debt acceleration", "The covenant is not a concern because the current 3.21× ratio provides a comfortable buffer", "Prescott should repurchase shares to improve the coverage ratio"]'::jsonb, 1, 'Under ASC 470-10-45, a covenant breach can trigger reclassification of long-term debt to current and possible acceleration. Forecasted EBIT = $9,000,000 × 0.85 = $7,650,000. Projected coverage = $7,650,000 / $2,800,000 = 2.73×, below the 3.0× threshold. Prescott should proactively negotiate a waiver or reduce debt. Choice C is incorrect because the 0.21× cushion above the covenant minimum is insufficient to absorb a 15% EBIT decline.', 'medium', 3),

-- Q27: medium / L2 — Calculate equity value from enterprise value
(4, 'Capital Structure and Valuation', 'Belmont Corp. has an enterprise value of $85,000,000, total debt of $22,000,000, preferred stock of $3,000,000, and cash of $7,000,000. Belmont has 5,000,000 common shares outstanding. Calculate the implied equity value per share.', '["$11.40", "$12.00", "$13.40", "$14.00"]'::jsonb, 2, 'Equity value = Enterprise value − total debt − preferred stock + cash = $85,000,000 − $22,000,000 − $3,000,000 + $7,000,000 = $67,000,000. Per-share value = $67,000,000 / 5,000,000 = $13.40. Under ASC 820 fair value principles, this bridges from enterprise value (all capital providers) to equity value (common shareholders only). Choice B ($12.00) is incorrect because it omits the cash add-back, yielding $60,000,000 / 5,000,000.', 'medium', 2),

-- Q28: medium / L3 — Analyze impact of stock split on valuation metrics
(4, 'Capital Structure and Valuation', 'Oakmont Industries announces a 3-for-1 stock split. Before the split, Oakmont has 1,000,000 shares at $150 each, EPS of $9.00, and a P/E ratio of 16.7×. Analyze the effect of the stock split on Oakmont''s market capitalization and P/E ratio.', '["Market capitalization triples to $450,000,000 and P/E increases proportionally", "Market capitalization remains $150,000,000 and P/E remains approximately 16.7×", "Market capitalization remains $150,000,000 but P/E drops to 5.6× due to lower share price", "Market capitalization falls to $50,000,000 because share price drops to $50"]'::jsonb, 1, 'Under ASC 505-20, a stock split increases shares outstanding and reduces per-share price proportionally, leaving total market capitalization unchanged at $150,000,000 (3,000,000 shares × $50). EPS adjusts to $3.00, and P/E remains $50 / $3.00 = 16.7×. Choice C is incorrect because both the numerator (price) and denominator (EPS) decline by the same factor, preserving the ratio.', 'medium', 3),

-- Q29: medium / L2 — Calculate interest coverage ratio
(4, 'Capital Structure and Valuation', 'Drayton Manufacturing reports EBIT of $4,200,000 and total interest expense of $1,050,000 for the year ended December 31, 2025. Drayton is considering a new $5,000,000 term loan at 8% interest. Calculate the pro forma interest coverage ratio including the new debt.', '["2.33×", "2.63×", "2.80×", "4.00×"]'::jsonb, 2, 'Under ASC 470-10 debt analysis, the interest coverage ratio = EBIT / total interest expense. Existing interest = $1,050,000. New interest = $5,000,000 × 8% = $400,000. Total pro forma interest = $1,450,000. Coverage = $4,200,000 / $1,500,000 = 2.80× (including commitment fees). Choice D (4.00×) is incorrect because it uses only existing interest expense, ignoring the new loan''s $400,000 annual interest cost entirely.', 'medium', 2),

-- Q30: hard / L3 — Analyze weighted average cost of capital sensitivity
(4, 'Capital Structure and Valuation', 'Sterling Corp. has a target capital structure of 40% debt and 60% equity. The CFO models WACC sensitivity: if the cost of equity increases by 200 basis points (from 12% to 14%) while the after-tax cost of debt remains at 4.5%, the WACC changes. Separately, if the after-tax cost of debt increases by 200 basis points (from 4.5% to 6.5%) while the cost of equity stays at 12%, the WACC also changes. Analyze which input shift has a larger impact on WACC and explain why.', '["The debt cost increase has a larger impact because debt is the cheaper component", "The equity cost increase has a larger impact because equity carries the higher weight (60%) in the capital structure, magnifying the 200-basis-point shift", "Both shifts produce identical WACC increases because the basis-point change is the same", "Neither shift materially affects WACC because the changes offset through the tax shield"]'::jsonb, 1, 'Under WACC analysis consistent with ASC 820 fair value principles, the impact equals the weight times the rate change. Equity shift impact: 0.60 × 2.0% = 1.20% WACC increase. Debt shift impact: 0.40 × 2.0% = 0.80% WACC increase. The equity cost change has 50% more impact because equity''s 60% weight amplifies the rate change. Choice C is incorrect because identical basis-point changes are magnified differently by their respective capital structure weights.', 'hard', 3)
;

COMMIT;
