-- Migration: Question generation — FAR batch 4 (30 questions)
-- Date: 2026-02-23
-- Topic: Governmental Accounting
-- Difficulty: 9E / 15M / 6H
-- Bloom's: L1:8 / L2:9 / L3:8 / L4:5

BEGIN;

INSERT INTO questions (section_id, topic, stem, choices, correct_index, explanation, difficulty, cognitive_level)
VALUES

-- Q1: easy / L1 — Five governmental fund types
(2, 'Governmental Accounting', 'Under GASB standards, which of the following is one of the five governmental fund types?', '["Agency fund", "Internal service fund", "Debt service fund", "Investment trust fund"]'::jsonb, 2, 'Under GASB Statement No. 34, the five governmental fund types are general, special revenue, capital projects, debt service, and permanent funds. The debt service fund accounts for financial resources accumulated for principal and interest payments on general long-term debt. Agency funds (reclassified as custodial under GASB 84) and investment trust funds are fiduciary fund types, while internal service funds are proprietary funds.', 'easy', 1),

-- Q2: medium / L2 — Deferred inflows for unavailable property tax
(2, 'Governmental Accounting', 'The City of Ferndale levies $8,000,000 in property taxes on January 1, 2026. By December 31, $7,200,000 has been collected. An additional $400,000 is expected within 60 days of year-end, and $200,000 will not be collected until April. In the general fund, what amount should Ferndale report as deferred inflows of resources?', '["$400,000", "$200,000", "$600,000", "$800,000"]'::jsonb, 1, 'Under GASB Statement No. 34 and the modified accrual basis, property tax revenue is recognized when measurable and available—collectible within 60 days of year-end. The $7,200,000 collected plus $400,000 expected within 60 days totals $7,600,000 in revenue. The remaining $200,000 is reported as deferred inflows of resources because it is measurable but not available within the availability period. Choice A ($400,000) incorrectly treats the within-60-day amount as deferred rather than recognizable revenue.', 'medium', 2),

-- Q3: medium / L3 — Interfund elimination in government-wide conversion
(2, 'Governmental Accounting', 'The City of Glenbrook''s general fund reports a $600,000 interfund loan receivable from the parks special revenue fund and a $900,000 interfund payable to the water enterprise fund. In preparing the government-wide statement of net position, how should these interfund balances be reported in the governmental activities column?', '["The $600,000 receivable is eliminated, and the $900,000 payable is reclassified as an internal balance", "Both balances are eliminated from the governmental activities column", "The $600,000 receivable remains, and the $900,000 payable is eliminated", "Both balances remain as reported in the fund financial statements"]'::jsonb, 0, 'Under GASB Statement No. 34, paragraph 58, interfund receivables and payables between funds within the same activity type (both governmental) are eliminated. The $600,000 loan between two governmental funds is eliminated within governmental activities. The $900,000 payable to the enterprise fund (business-type) cannot be eliminated within one column and is reclassified as an internal balance. Choice B is incorrect because the cross-activity payable must remain as an internal balance rather than being eliminated within a single column.', 'medium', 3),

-- Q4: easy / L1 — Nonspendable fund balance under GASB 54
(2, 'Governmental Accounting', 'Under GASB Statement No. 54, which of the following describes the nonspendable fund balance classification?', '["Resources restricted by external parties for a specific purpose", "Resources constrained by the government''s highest level of decision-making authority", "Resources designated by management for a particular use", "Resources not in spendable form or legally required to be maintained intact"]'::jsonb, 3, 'Under GASB Statement No. 54, paragraph 6, nonspendable fund balance includes amounts that cannot be spent because they are not in spendable form (such as inventories or prepaid items) or are legally or contractually required to be maintained intact (such as a permanent fund corpus). Choice A is incorrect because it describes restricted fund balance, which requires externally imposed constraints rather than the form-based limits that define nonspendable.', 'easy', 1),

-- Q5: easy / L1 — MD&A classified as RSI
(2, 'Governmental Accounting', 'Under GASB Statement No. 34, management''s discussion and analysis (MD&A) is classified as which component of governmental financial reporting?', '["A basic financial statement", "Required supplementary information", "Supplementary information", "A note to the financial statements"]'::jsonb, 1, 'Under GASB Statement No. 34, paragraph 8, MD&A is classified as required supplementary information (RSI) that precedes the basic financial statements. It provides an analytical overview of the government''s financial activities and is required but not part of the basic financial statements themselves. Choice A is incorrect because MD&A is not a basic financial statement—the basic statements include government-wide statements, fund statements, and notes.', 'easy', 1),

-- Q6: medium / L3 — Capital asset depreciation: fund vs government-wide
(2, 'Governmental Accounting', 'The City of Ridgewood purchases a $3,200,000 public safety radio system from general fund appropriations. The system has a useful life of 10 years and no residual value. In the first year, what is the effect on reported expenditures or expenses in the general fund versus the government-wide governmental activities?', '["General fund reports $320,000 expenditure; government-wide reports $320,000 depreciation expense", "General fund reports $3,200,000 expenditure; government-wide reports $3,200,000 expense", "General fund reports $3,200,000 expenditure; government-wide reports $320,000 depreciation expense", "General fund reports $320,000 expenditure; government-wide reports $3,200,000 expense"]'::jsonb, 2, 'Under GASB Statement No. 34, governmental funds use the current financial resources measurement focus, reporting the full $3,200,000 as an expenditure in the year of purchase. The government-wide statements use the economic resources measurement focus, capitalizing the asset and reporting $320,000 annual straight-line depreciation ($3,200,000 divided by 10 years). Choice B is incorrect because the government-wide statements capitalize the asset rather than expensing the full cost in the year of acquisition.', 'medium', 3),

-- Q7: easy / L1 — General fund always reported as major
(2, 'Governmental Accounting', 'Under GASB Statement No. 34, which fund is always reported as a major fund?', '["The general fund", "The debt service fund", "The capital projects fund", "The largest special revenue fund"]'::jsonb, 0, 'Under GASB Statement No. 34, paragraph 76, the general fund is always reported as a major fund. All other governmental and enterprise funds must meet quantitative thresholds (10% of the category total and 5% of the aggregate total) to qualify as major funds, though a government may also designate any fund as major. Choice B is incorrect because the debt service fund must meet the quantitative thresholds or be designated by management to qualify.', 'easy', 1),

-- Q8: medium / L2 — Special revenue fund revenue source test
(2, 'Governmental Accounting', 'The Town of Cedarville receives an annual state highway maintenance grant of $2,800,000, which constitutes 75% of the highway fund''s total inflows. Under GASB Statement No. 54, is the highway fund properly classified as a special revenue fund?', '["No, because a government grant is not a qualifying revenue source", "No, because the revenue must exceed 90% of total inflows", "No, because special revenue funds may only account for tax revenues", "Yes, because the restricted state grant is a specific revenue source forming a substantial portion of inflows"]'::jsonb, 3, 'Under GASB Statement No. 54, paragraph 30, a special revenue fund must have one or more specific revenue sources that form a substantial portion of its inflows. The $2,800,000 state grant at 75% of inflows is a restricted revenue source that satisfies this requirement. Choice B is incorrect because GASB 54 does not specify a fixed percentage threshold—substantial portion is a principles-based standard, not a bright-line rule.', 'medium', 2),

-- Q9: medium / L2 — GASB 87 lease liability calculation
(2, 'Governmental Accounting', 'On July 1, 2026, the County of Maplewood enters a five-year lease for office equipment with annual payments of $85,000 due at the end of each year. The county''s incremental borrowing rate is 4%. The present value of an ordinary annuity of $1 at 4% for five years is 4.4518. Under GASB 87, what is the initial lease liability?', '["$425,000", "$378,403", "$85,000", "$340,000"]'::jsonb, 1, 'Under GASB Statement No. 87, paragraph 18, a lessee measures the lease liability at the present value of future lease payments discounted at the rate implicit in the lease or the lessee''s incremental borrowing rate. The liability equals $85,000 times 4.4518, which is $378,403. Choice A ($425,000) is incorrect because it uses the undiscounted total of five payments rather than applying the present value factor required by GASB 87.', 'medium', 2),

-- Q10: medium / L2 — Operating vs nonoperating revenue in enterprise fund
(2, 'Governmental Accounting', 'The City of Brookhaven''s water utility enterprise fund reports the following for fiscal year 2026: water service charges of $6,400,000, a $150,000 gain on disposal of equipment, tap fee revenue of $310,000, and investment income of $95,000. Under GASB 34, what total should Brookhaven classify as operating revenues?', '["$6,710,000", "$6,400,000", "$6,805,000", "$6,955,000"]'::jsonb, 0, 'Under GASB Statement No. 34, paragraph 102, proprietary fund operating revenues arise from the fund''s principal ongoing operations. Water service charges ($6,400,000) and tap fees ($310,000) relate to the utility''s core operations, totaling $6,710,000. Investment income and gains on disposal are nonoperating items. Choice D ($6,955,000) is incorrect because investment income is a nonoperating item rather than a component of the utility''s principal operations.', 'medium', 2),

-- Q11: medium / L3 — Blended vs discrete component unit presentation
(2, 'Governmental Accounting', 'The City of Weston has two component units: Weston Building Authority, whose governing board is appointed entirely by the city council and whose sole purpose is financing city facilities, and the Weston Convention Bureau, whose board includes three council members among seven total members and which provides tourism services to the public. How should each be presented?', '["Discrete presentation for both component units", "Blended presentation for both component units", "Blended for Building Authority; discrete for Convention Bureau", "Discrete for Building Authority; blended for Convention Bureau"]'::jsonb, 2, 'Under GASB Statement No. 14 (as amended by GASB 61), a component unit is blended when its governing body is substantively the same as the primary government and it provides services exclusively to the primary government. The Building Authority meets both criteria. The Convention Bureau serves the general public, not exclusively the city, so it is discretely presented. Choice A is incorrect because the Building Authority''s board composition and exclusive service to the city require blending rather than discrete presentation.', 'medium', 3),

-- Q12: medium / L2 — GASB 96 subscription-based IT arrangement
(2, 'Governmental Accounting', 'On January 1, 2026, Hillcrest County enters a three-year subscription agreement for cloud-based financial management software. Annual payments are $120,000 due at the beginning of each year. The county''s incremental borrowing rate is 5%, and the present value of an annuity due of $1 at 5% for three years is 2.8594. Under GASB 96, what initial right-to-use subscription asset should Hillcrest record?', '["$360,000", "$120,000", "$300,000", "$343,128"]'::jsonb, 3, 'Under GASB Statement No. 96, paragraph 14, a government recognizes a right-to-use subscription asset measured at the initial subscription liability plus any prepayments. The initial liability equals the present value of subscription payments: $120,000 times 2.8594 equals $343,128. The subscription asset is recorded at the same amount. Choice A ($360,000) is incorrect because it uses the undiscounted total rather than applying the present value factor required by GASB 96.', 'medium', 2),

-- Q13: medium / L3 — Condition vs restriction in nonexchange revenue
(2, 'Governmental Accounting', 'The State of Redfield awards the City of Dunmore a $4,000,000 grant for after-school youth programs. The grant requires spending on qualifying activities (a restriction) and submission of quarterly enrollment reports demonstrating a minimum of 500 participants (an eligibility condition). Dunmore has met the enrollment threshold but spent only $1,200,000 by year-end. Under GASB 33, how much grant revenue should Dunmore recognize?', '["$1,200,000, matching expenditures to date", "$4,000,000, the full grant amount", "$0, because funds have not been fully spent", "$2,800,000, the unspent grant balance"]'::jsonb, 1, 'Under GASB Statement No. 33, paragraphs 20-22, voluntary nonexchange transactions are recognized as revenue when all eligibility requirements are met. A restriction limits how resources may be used but does not affect recognition timing. Since Dunmore met the eligibility condition (500 participants), the full $4,000,000 is recognized as revenue. Choice A is incorrect because it confuses the spending restriction with an eligibility requirement—restrictions affect use, not recognition timing.', 'medium', 3),

-- Q14: medium / L2 — Interfund services used and provided
(2, 'Governmental Accounting', 'The City of Oakmont''s central motor pool (internal service fund) provides fleet services to the police department (general fund) and charges $480,000 during fiscal year 2026. The actual cost of providing these services is $450,000. Under GASB standards, how should the general fund report this transaction?', '["As a $480,000 expenditure for fleet services", "As a $480,000 transfer out to the internal service fund", "As a $450,000 expenditure, adjusted to eliminate the $30,000 markup", "As a $480,000 reduction in fund balance with no expenditure recorded"]'::jsonb, 0, 'Under GASB Statement No. 34, paragraph 112, interfund services provided and used are reported as revenues and expenditures in the respective funds because they mirror arm''s-length transactions. The general fund reports the $480,000 billed amount as an expenditure. Choice B incorrectly treats the payment as a transfer; interfund service charges are recognized as expenditures, not transfers, because the internal service fund provides a measurable service in return.', 'medium', 2),

-- Q15: hard / L4 — Major fund determination criteria
(2, 'Governmental Accounting', 'The City of Haverford reports three special revenue funds: Fund A (assets $12,000,000, revenues $9,500,000), Fund B (assets $3,200,000, revenues $2,100,000), and Fund C (assets $4,800,000, revenues $3,600,000). All governmental funds total $95,000,000 in assets and $72,000,000 in revenues. Governmental-plus-enterprise totals are $140,000,000 in assets and $105,000,000 in revenues. Evaluate which funds qualify as major under GASB 34.', '["All three funds must be reported as major", "Funds A and C meet the dual threshold criteria", "Only Fund A meets both the 10% and 5% tests", "Funds A and B meet the dual threshold criteria"]'::jsonb, 2, 'Under GASB Statement No. 34, paragraph 76, a fund is major if any element is at least 10% of the governmental fund total AND at least 5% of the combined governmental-plus-enterprise total. Fund A revenues: $9.5M is 13.2% of governmental ($72M) and 9.0% of aggregate ($105M)—both tests met. Fund C revenues: $3.6M is 5.0% of governmental, failing the 10% test. Fund B revenues: $2.1M is 2.9% of governmental, also failing. Choice B is incorrect because Fund C''s revenues are only 5.0% of the governmental total, falling well below the 10% threshold rather than meeting both tests.', 'hard', 4),

-- Q16: easy / L2 — Fines and penalties revenue recognition
(2, 'Governmental Accounting', 'The City of Langford''s municipal court assesses $340,000 in traffic fines during fiscal year 2026 and collects $295,000 by year-end. An additional $30,000 is expected within 60 days. Under modified accrual, what amount of fine revenue should the general fund recognize?', '["$340,000", "$295,000", "$310,000", "$325,000"]'::jsonb, 3, 'Under GASB standards and modified accrual accounting, fines and penalties are recognized as revenue when measurable and available (collectible within the availability period, typically 60 days). The $295,000 collected plus $30,000 expected within 60 days equals $325,000 in recognizable revenue. The remaining $15,000 is not available and is deferred. Choice A ($340,000) is incorrect because modified accrual requires revenue to be available, not merely assessed—the $15,000 collectible beyond 60 days fails the availability test.', 'easy', 2),

-- Q17: medium / L2 — Capital contributions in enterprise fund
(2, 'Governmental Accounting', 'The City of Prescott''s wastewater enterprise fund receives a $2,100,000 developer contribution of sewer infrastructure during fiscal year 2026. The fund also earns $8,400,000 in service charges and incurs $7,300,000 in operating expenses. Under GASB 34, where should the developer contribution appear on the enterprise fund statement of revenues, expenses, and changes in net position?', '["As an operating revenue of the wastewater fund", "As a capital contribution reported after nonoperating items", "As a direct increase to net position, bypassing the operating statement", "As a reduction to total operating expenses for the period"]'::jsonb, 1, 'Under GASB Statement No. 34, paragraph 100, capital contributions from developers are reported separately after nonoperating revenues and expenses on the proprietary fund statement of revenues, expenses, and changes in net position. They are not operating revenues because they do not arise from the fund''s principal ongoing operations. Choice A is incorrect because capital contributions are nonrecurring rather than part of the fund''s principal operations.', 'medium', 2),

-- Q18: medium / L3 — Stabilization arrangement and committed fund balance
(2, 'Governmental Accounting', 'The City of Waverly''s council passes a formal resolution establishing a $5,000,000 stabilization (rainy-day) arrangement in the general fund, requiring a two-thirds council vote to release the funds. State law does not mandate the arrangement. Under GASB 54, how should the $5,000,000 be classified in fund balance?', '["Committed fund balance, because the constraint was imposed by formal action of the city council", "Restricted fund balance, because the resources are set aside for a specific purpose", "Assigned fund balance, because the council designated resources for future use", "Nonspendable fund balance, because the resources must be maintained intact"]'::jsonb, 0, 'Under GASB Statement No. 54, paragraphs 10-11, stabilization arrangements established by the government''s highest level of decision-making authority through formal action (such as a council resolution) are classified as committed fund balance. The constraint can only be removed by the same formal action. Choice B (restricted) is incorrect because restrictions require externally imposed constraints from creditors, grantors, or laws of other governments—an internal council resolution does not create a restriction.', 'medium', 3),

-- Q19: easy / L1 — Fiduciary funds excluded from government-wide
(2, 'Governmental Accounting', 'Under GASB Statement No. 34, which category of funds is excluded from the government-wide financial statements?', '["Proprietary funds", "Governmental funds", "Fiduciary funds", "Internal service funds"]'::jsonb, 2, 'Under GASB Statement No. 34, paragraph 12, fiduciary funds are excluded from the government-wide financial statements because their resources are held in trust or as an agent for external parties and cannot support the government''s own programs. Fiduciary activities are reported only in the fiduciary fund financial statements. Choice A is incorrect because proprietary fund activities are included in the government-wide statements under business-type activities.', 'easy', 1),

-- Q20: hard / L4 — GASB 77 tax abatement disclosure evaluation
(2, 'Governmental Accounting', 'The City of Northgate enters a 10-year property tax abatement with Westbrook Industries, reducing Westbrook''s annual levy by $750,000 in exchange for creating 200 jobs. After three years, only 85 jobs exist. The agreement includes a discretionary clawback provision. Annual property tax revenue is $62,000,000. Evaluate the city''s disclosure obligations under GASB 77.', '["No disclosure is required because the amount is immaterial relative to total property tax revenue", "Footnote disclosure is required only if the city exercises the clawback provision against Westbrook", "Disclosure is required only in the MD&A section, not in the notes to the financial statements", "Note disclosure is required, including the purpose, tax type, dollar amount, and recapture provisions"]'::jsonb, 3, 'Under GASB Statement No. 77, paragraphs 5-7, governments must disclose tax abatement agreements in the notes, including the tax type, authority, eligibility criteria, dollar amount abated, and recapture provisions. The disclosure applies regardless of whether the clawback is exercised. Choice A is incorrect because GASB 77 does not provide a materiality exception based on the ratio of abated taxes to total revenue—significant tax abatement agreements require note disclosure.', 'hard', 4),

-- Q21: hard / L4 — Claims and judgments: accrual vs fund reporting
(2, 'Governmental Accounting', 'The City of Branford is defending a $4,200,000 personal injury lawsuit. The city attorney estimates a 70% probability of an unfavorable outcome and believes $2,800,000 is a reasonable settlement estimate. Resolution is expected in 18 months. Evaluate the appropriate reporting in both the governmental fund and government-wide financial statements.', '["Accrue a $2,800,000 liability in the government-wide statements; no expenditure in the general fund until due", "Accrue a $2,800,000 liability in both the government-wide statements and the general fund", "Disclose the contingency in the notes only; no accrual is needed in either set of statements", "No reporting is required until the lawsuit outcome is determined with certainty"]'::jsonb, 0, 'Under GASB Statement No. 62, paragraphs 104-112, a liability is accrued when probable and reasonably estimable. At 70% probability and $2,800,000, both criteria are met, requiring a long-term liability in the government-wide statements. In the general fund, modified accrual recognizes expenditures only when claims are due and payable—since settlement is 18 months away, no fund expenditure is recorded yet. Choice B is incorrect because the general fund uses the current financial resources measurement focus, which does not recognize long-term liabilities—rather than accruing now, the fund records the expenditure only when payment is due.', 'hard', 4),

-- Q22: hard / L4 — Agent vs cost-sharing pension plan reporting
(2, 'Governmental Accounting', 'Bellfield County participates in an agent multiple-employer pension plan for sheriff deputies and a cost-sharing multiple-employer plan for general employees. Both plans are administered by the State Retirement System. The county''s actuarial department provides separate valuations. Evaluate how the county should report the net pension liability for each plan under GASB 68.', '["Both plans report a proportionate share of the collective net pension liability", "The agent plan uses a plan-specific valuation; the cost-sharing plan uses proportionate share", "Both plans use individual actuarial valuations for net pension liability", "Neither plan requires liability recognition when the state administers both plans"]'::jsonb, 1, 'Under GASB Statement No. 68, paragraphs 28-30 and 48-49, the measurement approach differs by plan type. For an agent plan, the employer reports a net pension liability based on its own actuarial valuation—total pension liability minus the fiduciary net position attributable to that employer. For a cost-sharing plan, the employer reports its proportionate share of the collective NPL. Choice A is incorrect because the agent plan requires an employer-specific valuation rather than the proportionate-share allocation used for cost-sharing plans.', 'hard', 4),

-- Q23: easy / L1 — Required supplementary information definition
(2, 'Governmental Accounting', 'Under GASB standards, which of the following describes required supplementary information (RSI)?', '["Financial data presented as part of the basic financial statements", "Optional disclosures that enhance comparability between governments", "Information that GASB requires to accompany but not be part of the basic financial statements", "Supplementary schedules that auditors are not required to review"]'::jsonb, 2, 'Under GASB Statement No. 34 and GASB Codification Section 2200, required supplementary information is data that GASB has determined is essential for placing the basic financial statements in context. RSI accompanies the basic financial statements but is not part of them; examples include MD&A and pension schedules. Choice A is incorrect because RSI is explicitly distinguished from the basic financial statements, which include government-wide statements, fund statements, and notes.', 'easy', 1),

-- Q24: easy / L1 — Restricted net position in government-wide statements
(2, 'Governmental Accounting', 'Under GASB Statement No. 34, which net position category includes resources constrained by external parties?', '["Restricted net position", "Committed net position", "Unrestricted net position", "Net investment in capital assets"]'::jsonb, 0, 'Under GASB Statement No. 34, paragraph 34, restricted net position includes resources whose use is constrained by external parties—creditors, grantors, contributors, or laws and regulations of other governments. This parallels the restricted fund balance classification in GASB 54. Choice B is incorrect because committed net position is not a recognized government-wide category—committed is a fund balance classification rather than a net position component.', 'easy', 1),

-- Q25: medium / L3 — GASB 87 short-term lease exception analysis
(2, 'Governmental Accounting', 'The City of Ashville enters a lease for portable classrooms on August 1, 2026, with a 15-month term ending October 31, 2027. Monthly payments are $8,500 with no renewal option. The finance director classifies this as a short-term lease exempt from GASB 87 recognition. Analyze whether this classification is correct.', '["Correct, because the total payments are below the city''s capitalization threshold", "Correct, because leases under 24 months are automatically exempt from GASB 87", "Incorrect, because GASB 87 defines short-term as a maximum possible term of 12 months or less", "Incorrect, because only month-to-month leases qualify as short-term under GASB 87"]'::jsonb, 2, 'Under GASB Statement No. 87, paragraph 16, a short-term lease has a maximum possible term (including renewal options) of 12 months or less at lease commencement. The 15-month lease exceeds this threshold and must be recognized as a right-to-use asset and lease liability regardless of payment amounts. Choice B is incorrect because GASB 87 uses a 12-month threshold, not 24 months, and there is no alternative short-term cutoff in the standard.', 'medium', 3),

-- Q26: hard / L4 — Fund balance spending hierarchy judgment
(2, 'Governmental Accounting', 'The City of Redmond''s general fund has $2,000,000 restricted by a federal grant for infrastructure, $1,500,000 committed by council resolution for infrastructure, and $1,200,000 assigned by the city manager for infrastructure. An infrastructure project costing $3,200,000 is approved. The city has not adopted a formal spending policy under GASB 54. Evaluate the order in which fund balance classifications are spent.', '["Assigned, then committed, then restricted", "Restricted, then committed, then assigned", "Committed, then assigned, then restricted", "The city may choose any order since no formal policy exists"]'::jsonb, 1, 'Under GASB Statement No. 54, paragraph 18, when an expenditure can be funded from both restricted and unrestricted resources, restricted is spent first by default absent a formal policy. Within unrestricted fund balance, committed amounts are considered spent before assigned. The project uses $2,000,000 restricted and $1,200,000 committed, totaling $3,200,000. Choice D is incorrect because GASB 54 establishes a default spending hierarchy when no formal policy exists.', 'hard', 4),

-- Q27: medium / L3 — Reconciliation: capital outlay to depreciation
(2, 'Governmental Accounting', 'A government''s general fund reports $14,500,000 in total expenditures, including $4,200,000 for capital outlay and $2,800,000 for debt principal payments. Depreciation on governmental capital assets is $3,100,000 for the year. In the reconciliation to the government-wide statement of activities, what is the net adjustment for capital-related items?', '["Increase net expenses by $3,100,000", "Decrease net expenses by $7,000,000", "Decrease net expenses by $4,200,000", "Decrease net expenses by $1,100,000"]'::jsonb, 3, 'Under GASB Statement No. 34, the reconciliation removes capital outlay expenditures ($4,200,000) because these are capitalized in government-wide statements, then adds depreciation expense ($3,100,000). The net capital-related adjustment decreases expenses by $1,100,000 ($4,200,000 minus $3,100,000). The $2,800,000 debt principal is a separate reconciling item. Choice C is incorrect because it removes the capital outlay without adding back depreciation—the reconciliation requires both adjustments rather than only the removal.', 'medium', 3),

-- Q28: easy / L1 — Statistical section of CAFR
(2, 'Governmental Accounting', 'Under GASB standards, the statistical section of a comprehensive annual financial report provides what type of information?', '["Auditor opinions on individual fund statements", "Adjusting journal entries for year-end close", "Trend data and nonfinancial information covering multiple fiscal years", "The government''s annual operating budget document"]'::jsonb, 2, 'Under GASB Statement No. 44, the statistical section presents trend data, revenue capacity, debt capacity, demographic information, and operating data typically covering ten fiscal years. This information helps users assess a government''s financial condition over time. Choice A is incorrect because auditor opinions are part of the independent auditor''s report, not the statistical section of the financial report.', 'easy', 1),

-- Q29: hard / L3 — Special assessment debt reporting
(2, 'Governmental Accounting', 'The City of Deerfield issues $6,000,000 in special assessment bonds to finance a neighborhood sewer improvement. Property owners in the assessment district will repay the bonds through special levies over 15 years. The city is not obligated in any manner for the debt. Under GASB standards, how should the city report this special assessment debt?', '["The city does not report the debt as a liability but discloses it in the notes", "The city reports the debt as a general long-term liability in government-wide statements", "The city reports the debt in a debt service fund only", "The city reports the debt as an enterprise fund liability"]'::jsonb, 0, 'Under GASB Statement No. 6, paragraph 17, if a government is not obligated in any manner for special assessment debt (neither directly nor through a moral obligation or guarantee), the debt is not reported as a liability. However, GASB 6 requires note disclosure of the outstanding amount. Choice B incorrectly records the debt as a government liability, which applies only when the government has some form of obligation for repayment.', 'hard', 3),

-- Q30: medium / L2 — Pension trust fund classification
(2, 'Governmental Accounting', 'Jefferson County administers a single-employer defined benefit pension plan for its employees. The plan holds $185,000,000 in investments and has a total pension liability of $240,000,000. Under GASB 67, in which fund type should the county report the plan''s fiduciary net position?', '["General fund", "Pension trust fund", "Investment trust fund", "Internal service fund"]'::jsonb, 1, 'Under GASB Statement No. 67, paragraph 4, and GASB Statement No. 34, defined benefit pension plans administered through trusts are reported in a pension (and other employee benefit) trust fund, a fiduciary fund type. The fiduciary net position represents plan assets minus plan liabilities. Choice C (investment trust fund) is incorrect because investment trust funds report the external portion of investment pools, not employee benefit plans.', 'medium', 2)
;

COMMIT;
