-- Migration: Question generation — ISC batch 2 (30 questions)
-- Date: 2026-02-23
-- Topic: Data Protection Technologies
-- Difficulty: 9E / 15M / 6H
-- Bloom's: L1:6 / L2:10 / L3:9 / L4:5

BEGIN;

INSERT INTO questions (section_id, topic, stem, choices, correct_index, explanation, difficulty, cognitive_level)
VALUES

-- Q1: easy / L2 — Hardware Security Module for key storage
(5, 'Data Protection Technologies', 'In January 2026, Pinnacle Financial Services deploys a tamper-resistant physical device to store and manage its TLS private keys, ensuring that keys are never exported in plaintext. Which technology has Pinnacle implemented?', '["Trusted Platform Module (TPM)", "Virtual private network concentrator", "Hardware Security Module (HSM)", "Key management interoperability protocol server"]'::jsonb, 2, 'Per NIST SP 800-57 Part 1, a Hardware Security Module (HSM) is a dedicated cryptographic device that generates, stores, and manages keys within a tamper-resistant boundary, preventing plaintext key export. HSMs are the standard for high-assurance key protection in enterprise environments. While a Trusted Platform Module (TPM) also provides hardware-based key storage, TPMs are embedded in endpoints for platform integrity rather than deployed as centralized key management appliances.', 'easy', 2),

-- Q2: easy / L1 — Hashing vs encryption distinction
(5, 'Data Protection Technologies', 'What is the PRIMARY distinction between hashing and encryption as data protection techniques?', '["Hashing produces fixed-length output while encryption produces variable-length output", "Hashing is a one-way function while encryption is reversible with a key", "Hashing requires a secret key while encryption does not", "Hashing protects data in transit while encryption protects data at rest"]'::jsonb, 1, 'Per NIST SP 800-107, a cryptographic hash function is a one-way transformation that produces a fixed-length digest and cannot be reversed to recover the original input. Encryption, by contrast, is a two-way process where ciphertext can be decrypted back to plaintext using the appropriate key. While choice A is partially true about fixed-length output, it incorrectly states that encryption produces variable-length output—block ciphers produce fixed-size blocks.', 'easy', 1),

-- Q3: medium / L3 — Key rotation impact on encrypted archives
(5, 'Data Protection Technologies', 'In April 2026, Meridian Health Systems rotates its AES-256 master encryption key quarterly as required by policy. The security team discovers that archived patient records encrypted under previous keys remain accessible only by decrypting with the retired key and re-encrypting with the new key. What is the MOST likely operational impact of this key rotation strategy?', '["Archived records become permanently inaccessible after rotation", "The encryption strength degrades with each key rotation cycle", "Network bandwidth consumption increases during the re-encryption process", "Re-encryption of large archives creates significant processing overhead and operational complexity"]'::jsonb, 3, 'Per NIST SP 800-57 Part 1, Section 5.3, key rotation requires that data encrypted under old keys be re-encrypted with the new key to maintain consistent protection. For large-scale archives, this decrypt-then-re-encrypt cycle introduces substantial computational overhead and operational complexity, particularly in healthcare environments with terabytes of stored data. While choice C mentions bandwidth, the primary concern is processing overhead and key management complexity rather than network consumption alone.', 'medium', 3),

-- Q4: hard / L3 — TDE vs column-level encryption trade-offs
(5, 'Data Protection Technologies', 'In February 2026, Crestwood Capital Management processes credit card transactions and stores cardholder data in a PostgreSQL database. The security architect must choose between transparent data encryption (TDE) at the tablespace level and column-level encryption using AES-256-GCM for the 12 columns containing PCI DSS-regulated data. The database serves 500 concurrent analytical queries per second. Which factor MOST accurately distinguishes the two approaches?', '["Column-level encryption protects data against a privileged database administrator viewing regulated columns, while TDE does not", "TDE provides stronger encryption algorithms than column-level encryption", "Column-level encryption eliminates the need for key management infrastructure", "TDE encrypts data in transit between the application and database server"]'::jsonb, 0, 'Per NIST SP 800-111 and PCI DSS Requirement 3.5, TDE encrypts data files at rest transparently, so authorized database users—including DBAs—see plaintext through normal queries. Column-level encryption encrypts individual field values before storage, meaning even privileged DBAs cannot view plaintext without the application-layer decryption key. Choice D is incorrect because TDE protects data at rest on disk, not data in transit, which requires TLS/SSL at the connection layer.', 'hard', 3),

-- Q5: medium / L2 — End-to-end encryption messaging scenario
(5, 'Data Protection Technologies', 'In March 2026, Birchwood Legal Partners implements a messaging platform that encrypts communications on the sender''s device and only decrypts them on the recipient''s device. The firm''s IT department cannot access message content even when monitoring network traffic. Which encryption model has Birchwood deployed?', '["Transport-layer encryption", "End-to-end encryption", "Gateway-based encryption", "Server-side encryption"]'::jsonb, 1, 'Per NIST SP 800-175B, end-to-end encryption (E2EE) ensures that data is encrypted at the originating endpoint and only decrypted at the destination endpoint, with no intermediate party—including the service provider or IT administrators—able to access plaintext. This differs fundamentally from transport-layer encryption, which protects data only between network hops. Choice A is incorrect because transport-layer encryption like TLS terminates at the server, allowing the server to access plaintext content.', 'medium', 2),

-- Q6: medium / L2 — Differential privacy in analytics
(5, 'Data Protection Technologies', 'In January 2026, Westlake Insurance Group releases aggregate claims data for public health research. To prevent re-identification of individual policyholders, the analytics team adds calibrated statistical noise to query results before publication. The technique ensures that including or excluding any single record does not significantly change the output. Which privacy-preserving technique has Westlake applied?', '["Data masking", "Generalization", "Differential privacy", "Pseudonymization"]'::jsonb, 2, 'Per NIST SP 800-188, differential privacy is a mathematical framework that adds calibrated noise to query results so that the output is statistically indistinguishable whether or not any individual''s record is included. This provides formal privacy guarantees for aggregate data releases. However, choice D (pseudonymization) replaces identifiers with tokens but does not add noise to outputs—pseudonymized records can still be re-identified through linkage attacks if auxiliary data is available.', 'medium', 2),

-- Q7: hard / L4 — BYOK vs HYOK cloud key management evaluation
(5, 'Data Protection Technologies', 'Northstar Wealth Advisors stores $3.2 billion in client portfolio data across three cloud providers. The CISO must choose between Bring Your Own Key (BYOK) with an on-premises HSM, cloud-provider-managed keys, and Hold Your Own Key (HYOK) where keys never leave the on-premises HSM. Regulatory requirements mandate that the firm retain sole custody of encryption keys. Which approach should the CISO recommend?', '["Cloud-provider-managed keys, because they offer the highest availability and automatic rotation", "BYOK with on-premises HSM, because the firm imports keys into the cloud provider''s KMS while retaining a master copy", "A hybrid of BYOK and cloud-managed keys to balance availability with control", "HYOK with on-premises HSM, because encryption and decryption occur without keys ever entering the cloud provider''s infrastructure"]'::jsonb, 3, 'Per NIST SP 800-57 Part 1 and CSA cloud security guidance, Hold Your Own Key (HYOK) ensures that encryption keys never leave the organization''s on-premises HSM, with all cryptographic operations performed locally. This satisfies the regulatory mandate for sole key custody. Choice B (BYOK) is incorrect because once keys are imported into the cloud provider''s KMS, the provider''s infrastructure temporarily handles the plaintext key material, violating the sole-custody requirement.', 'hard', 4),

-- Q8: easy / L1 — Symmetric encryption defining characteristic
(5, 'Data Protection Technologies', 'Which statement BEST describes symmetric encryption as a data protection technique?', '["It uses a single shared key for both encryption and decryption", "It uses a public key to encrypt and a private key to decrypt", "It generates a unique key pair for each communication session", "It relies on hash functions rather than keys to protect data"]'::jsonb, 0, 'Per NIST SP 800-175B, symmetric encryption uses a single secret key shared between communicating parties for both encryption and decryption operations. Common symmetric algorithms include AES and 3DES. However, choice B describes asymmetric (public-key) encryption, where a public key encrypts data and only the corresponding private key can decrypt it—this is fundamentally different from the shared-key model of symmetric cryptography.', 'easy', 1),

-- Q9: medium / L2 — Trusted Execution Environment scenario
(5, 'Data Protection Technologies', 'In April 2026, Granite Analytics processes $1.8 million in daily credit-scoring transactions. The firm deploys a processor-level isolated environment that encrypts data in memory during computation, preventing even the host operating system from accessing the plaintext. Which technology has Granite implemented?', '["Virtual private cloud isolation", "Container-based sandboxing", "Trusted Execution Environment (TEE)", "Application-level encryption library"]'::jsonb, 2, 'Per NIST SP 800-215, a Trusted Execution Environment (TEE) provides hardware-enforced memory isolation and encryption, creating a secure enclave where data is decrypted and processed in a protected memory region inaccessible to the host OS, hypervisor, or other processes. This protects data while it is actively being computed—often called protecting "data in use." In contrast, choice B (container sandboxing) isolates processes at the OS level but does not encrypt memory contents, leaving data vulnerable to a compromised host kernel.', 'medium', 2),

-- Q10: hard / L4 — Homomorphic encryption vs alternatives evaluation
(5, 'Data Protection Technologies', 'Clearview Credit Union wants to outsource fraud detection analytics to a third-party vendor without exposing the $450 million loan portfolio''s underlying customer data. The vendor''s models require performing arithmetic operations on the encrypted data and returning encrypted results. The credit union evaluates homomorphic encryption, secure multiparty computation, and standard AES encryption with data sharing agreements. Which approach BEST meets the requirement?', '["Standard AES encryption with contractual data sharing agreements, because it provides proven protection", "Homomorphic encryption, because it allows the vendor to compute on ciphertext without ever accessing plaintext data", "Secure multiparty computation, because it distributes data fragments across multiple vendors for joint analysis", "A combination of AES encryption and differential privacy applied to query results"]'::jsonb, 1, 'Per NIST IR 8214, homomorphic encryption enables computation on ciphertext, producing encrypted results that, when decrypted, match the output of operations performed on plaintext. This uniquely allows the vendor to run fraud-detection models without accessing raw customer data. However, choice C (secure multiparty computation) requires all parties to participate interactively in computation, which is operationally more complex and does not match the outsourcing model where a single vendor performs analytics independently.', 'hard', 4),

-- Q11: medium / L3 — Perfect forward secrecy impact analysis
(5, 'Data Protection Technologies', 'In February 2026, Sterling Consulting Group enables perfect forward secrecy (PFS) on its TLS-protected client portal. A threat actor later compromises the server''s long-term private key. What is the MOST likely effect of PFS on previously recorded encrypted sessions?', '["Previously recorded sessions remain protected because each session used a unique ephemeral key that was discarded after use", "Previously recorded sessions can be decrypted using the compromised long-term key", "Only sessions established after the key compromise are protected", "PFS requires renegotiation of all active sessions, causing service disruption"]'::jsonb, 0, 'Per NIST SP 800-52 Rev. 2, perfect forward secrecy uses ephemeral Diffie-Hellman or ECDHE key exchanges to generate unique session keys that are destroyed after each session completes. Even if the server''s long-term private key is later compromised, past session keys cannot be derived from it. Choice B is incorrect because without PFS, a compromised long-term key would allow decryption of recorded sessions, but PFS specifically prevents this retroactive exposure.', 'medium', 3),

-- Q12: medium / L3 — Digital watermarking for leakage detection
(5, 'Data Protection Technologies', 'In March 2026, Oakmont Financial Group embeds unique invisible identifiers into copies of its $2.1 million client portfolio reports before distributing them to five partner firms. When a leaked copy appears on a public forum, the security team traces it to Partner Firm C. Which technique did Oakmont use, and what is its PRIMARY limitation?', '["Steganography, which hides data within media files but cannot be applied to structured documents", "Data fingerprinting, which generates a unique hash of each document but does not survive format conversion", "Tokenization, which replaces sensitive values with non-reversible tokens unique to each partner", "Digital watermarking, which embeds traceable markers but does not prevent the initial data leakage"]'::jsonb, 3, 'Per NIST SP 800-188, digital watermarking embeds invisible, unique identifiers into documents or datasets that survive copying and distribution, enabling forensic tracing of leaked data to its source. However, watermarking is a detective control—it identifies the source after a leak occurs but does not prevent the unauthorized disclosure. In contrast, choice B (data fingerprinting) creates document hashes for integrity verification but does not embed unique per-recipient identifiers that persist through format changes.', 'medium', 3),

-- Q13: medium / L2 — Key escrow for litigation compliance
(5, 'Data Protection Technologies', 'In January 2026, Lakewood Pharmaceuticals implements an encryption key escrow system, depositing copies of its file encryption keys with a trusted third-party escrow agent. The company''s legal counsel requires the ability to decrypt employee files during litigation holds. Which scenario does key escrow address?', '["Preventing unauthorized key rotation by rogue administrators", "Enabling authorized decryption when the original key holder is unavailable or during legal proceedings", "Eliminating the need for key management infrastructure entirely", "Providing real-time key revocation across distributed systems"]'::jsonb, 1, 'Per NIST SP 800-57 Part 1, key escrow involves depositing a copy of cryptographic keys with a trusted third party to ensure authorized access when the primary key holder is unavailable, such as during employee termination or legal discovery processes. This addresses business continuity and regulatory compliance needs. Choice C is incorrect because key escrow adds complexity to key management infrastructure rather than eliminating it—the escrow agent itself requires secure storage, access controls, and audit procedures.', 'medium', 2),

-- Q14: easy / L1 — Public Key Infrastructure purpose
(5, 'Data Protection Technologies', 'What is the PRIMARY purpose of a Public Key Infrastructure (PKI)?', '["To encrypt all network traffic using symmetric key algorithms", "To provide a firewall between internal and external networks", "To manage digital certificates and public-private key pairs for authentication and encryption", "To store user passwords in a centralized directory"]'::jsonb, 2, 'Per NIST SP 800-32, a Public Key Infrastructure (PKI) provides the framework for creating, managing, distributing, storing, and revoking digital certificates that bind public keys to identities. PKI enables authentication, encryption, and digital signatures across enterprise systems. Choice A is incorrect because PKI manages asymmetric keys and certificates—while PKI may facilitate symmetric key exchange, its primary purpose is lifecycle management of public-private key pairs.', 'easy', 1),

-- Q15: medium / L3 — VPN split tunneling risk analysis
(5, 'Data Protection Technologies', 'In April 2026, Redwood Consulting Group configures its corporate VPN with split tunneling enabled, routing only traffic destined for internal resources through the encrypted tunnel while allowing other internet traffic to flow directly. An analyst working from a coffee shop accesses both the internal CRM and personal web browsing simultaneously. What is the MOST likely residual risk?', '["The analyst''s device becomes a potential bridge between the untrusted public network and the corporate network if the endpoint is compromised", "Split tunneling eliminates all encryption on the VPN connection", "Internal traffic becomes visible to the public Wi-Fi network operator", "The VPN server experiences increased latency from processing split traffic decisions"]'::jsonb, 0, 'Per NIST SP 800-77 Rev. 1, split tunneling routes only designated traffic through the VPN tunnel, leaving other traffic unprotected. If the endpoint is compromised via the unprotected internet connection, the attacker could pivot through the device''s VPN tunnel to reach internal resources. Choice B is incorrect because split tunneling does not remove encryption from VPN-routed traffic—corporate-destined traffic still traverses the encrypted tunnel normally.', 'medium', 3),

-- Q16: medium / L3 — Certificate pinning renewal failure
(5, 'Data Protection Technologies', 'In February 2026, Apex Payment Solutions implements certificate pinning in its mobile banking application, hardcoding the expected TLS certificate fingerprint. Six months later, the organization''s TLS certificate expires and is renewed with a different certificate authority. What is the MOST likely consequence for users of the mobile application?', '["Users experience no disruption because certificate pinning automatically updates", "The application continues to function but with degraded encryption strength", "Users see a standard browser certificate warning that they can bypass", "The application refuses to connect because the renewed certificate''s fingerprint does not match the pinned value"]'::jsonb, 3, 'Per NIST SP 800-52 Rev. 2, certificate pinning associates a specific certificate or public key fingerprint with a host, and the application rejects connections when the presented certificate does not match. When a certificate is renewed through a different CA, the fingerprint changes, causing pinned applications to refuse the connection entirely. Choice A is incorrect because certificate pinning is static by design—it does not auto-update, which is precisely why operational planning for certificate renewals is critical.', 'medium', 3),

-- Q17: easy / L2 — Certificate chain validation process
(5, 'Data Protection Technologies', 'In March 2026, Brightfield Insurance Group''s web server presents a TLS certificate to a client browser. The browser verifies the certificate by checking its signature chain back to a pre-installed root certificate authority. Which process is the browser performing?', '["Certificate chain validation", "Certificate revocation list generation", "Public key extraction and caching", "Symmetric session key negotiation"]'::jsonb, 0, 'Per NIST SP 800-32 and RFC 5280, certificate chain validation (or certificate path validation) is the process by which a relying party verifies each certificate in the chain from the end-entity certificate up to a trusted root CA, confirming that all signatures are valid and certificates are not expired or revoked. However, choice D describes the subsequent TLS handshake step where session keys are negotiated—this occurs after certificate validation has successfully completed.', 'easy', 2),

-- Q18: medium / L3 — Data sovereignty GDPR transfer impact
(5, 'Data Protection Technologies', 'In January 2026, Atlas Financial Group operates in both the EU and the United States, storing customer data in a U.S.-based cloud region. The EU privacy team warns that GDPR Article 44 restricts transfers of personal data outside the European Economic Area without adequate safeguards. What is the MOST likely impact on Atlas''s data protection architecture?', '["Atlas must delete all EU customer data from the U.S. cloud region immediately", "Atlas can continue storing EU data in the U.S. without changes because cloud encryption satisfies GDPR transfer requirements", "Atlas must implement approved transfer mechanisms such as Standard Contractual Clauses or store EU data in an EEA-region data center", "GDPR transfer restrictions apply only to unencrypted personal data"]'::jsonb, 2, 'Per GDPR Article 46 and NIST Privacy Framework, transfers of personal data outside the EEA require approved safeguards such as Standard Contractual Clauses (SCCs), Binding Corporate Rules, or adequacy decisions. Alternatively, data localization in an EEA region eliminates the cross-border transfer issue. Choice B is incorrect because encryption alone does not satisfy GDPR transfer requirements—the regulation addresses data governance and jurisdictional control, not merely technical confidentiality measures.', 'medium', 3),

-- Q19: easy / L1 — Salted hashing purpose
(5, 'Data Protection Technologies', 'What is the PRIMARY purpose of adding a salt to a cryptographic hash?', '["To increase the speed of the hashing algorithm", "To ensure that identical inputs produce different hash outputs, defeating precomputed rainbow table attacks", "To encrypt the hash output for secure network transmission", "To compress the input data before the hashing operation"]'::jsonb, 1, 'Per NIST SP 800-132, a salt is a random value appended to the input before hashing, ensuring that identical plaintext values produce unique hash digests. This defeats precomputed lookup attacks such as rainbow tables, where attackers match known hash values to plaintext. Choice A is incorrect because salting does not improve hashing speed—it adds a small computational step, with the security benefit of preventing hash collision lookups across users.', 'easy', 1),

-- Q20: medium / L3 — SFTP vs FTPS protocol comparison
(5, 'Data Protection Technologies', 'In April 2026, Pendleton Manufacturing must transfer $5.4 million in quarterly payroll files to its outsourced payroll processor. The security policy requires both encryption in transit and mutual authentication. The IT team compares SFTP, FTPS, and unencrypted FTP over a VPN tunnel. Which factor MOST accurately differentiates SFTP from FTPS?', '["SFTP does not provide data encryption while FTPS encrypts using TLS", "SFTP supports larger file sizes than FTPS due to SSH compression features", "SFTP is slower than FTPS because SSH adds compression overhead to transfers", "SFTP uses a single SSH channel on port 22, while FTPS requires separate TLS-wrapped control and data ports"]'::jsonb, 3, 'Per NIST SP 800-113, SFTP operates over SSH using a single encrypted channel (typically port 22), simplifying firewall rules and network configuration. FTPS wraps TLS around the traditional FTP protocol, which inherently uses separate control (port 21) and data channels (dynamic ports), requiring more complex firewall configurations. Choice A is incorrect because both SFTP and FTPS provide encryption—SFTP uses SSH encryption while FTPS uses TLS encryption; neither transmits data in cleartext.', 'medium', 3),

-- Q21: medium / L2 — Data retention policy compliance
(5, 'Data Protection Technologies', 'In March 2026, Ridgeline Healthcare Systems reviews its data retention schedule and discovers that 14 terabytes of patient billing records have exceeded the seven-year retention period mandated by HIPAA compliance policy. The records are stored in encrypted cloud object storage. What action should Ridgeline take?', '["Securely destroy the expired records using a documented sanitization procedure and maintain destruction certificates", "Extend the retention period indefinitely because the data is already encrypted", "Move the records to a lower-cost storage tier for indefinite archival", "Remove the encryption keys but leave the ciphertext in cloud storage"]'::jsonb, 0, 'Per NIST SP 800-88 Rev. 1 and HIPAA 45 CFR 164.530(j), organizations must follow documented retention schedules and securely destroy records after the retention period expires, maintaining verifiable destruction logs. Retaining data beyond its mandated period increases breach liability and regulatory exposure. Choice D (removing keys while leaving ciphertext) is a form of cryptographic erasure but is insufficient alone—formal sanitization with documented evidence of destruction is required for compliance.', 'medium', 2),

-- Q22: easy / L2 — Steganography data concealment
(5, 'Data Protection Technologies', 'In February 2026, a forensic investigator at Blackhawk Security discovers that an employee has been hiding proprietary financial models inside JPEG image files attached to personal emails. The hidden data is invisible to casual inspection. Which data concealment technique was the employee using?', '["Data masking", "Steganography", "Tokenization", "Code obfuscation"]'::jsonb, 1, 'Per NIST SP 800-101 Rev. 1, steganography is the practice of concealing data within other non-secret media files such as images, audio, or video, making the hidden information invisible to casual observers. Unlike encryption, which makes data unreadable, steganography hides the very existence of the data. Choice D (code obfuscation) makes source code harder to understand but does not hide data within carrier files—obfuscation transforms representation while steganography embeds data within innocuous-looking media.', 'easy', 2),

-- Q23: medium / L2 — Full-disk encryption stolen laptop scenario
(5, 'Data Protection Technologies', 'In January 2026, Summit Accounting Group issues 350 laptops to field auditors who travel to client sites. Each laptop contains locally cached client financial data. The IT department enables BitLocker full-disk encryption with TPM-backed key storage on every device. An auditor reports a laptop stolen from a hotel room while powered off. What protection does full-disk encryption provide?', '["It prevents the thief from accessing the laptop''s wireless network connections", "It prevents unauthorized applications from being installed on the device", "It renders the stored data unreadable without the correct authentication credentials, protecting against offline data extraction", "It enables remote tracking and wiping of the laptop through the TPM chip"]'::jsonb, 2, 'Per NIST SP 800-111, full-disk encryption (FDE) protects data at rest by encrypting the entire disk volume, rendering stored data unreadable to anyone who cannot provide valid authentication credentials. When a powered-off encrypted laptop is stolen, the data cannot be extracted by removing the hard drive or booting from external media. Choice A is incorrect because FDE protects stored data, not network connections—network security requires separate controls such as VPNs or firewalls.', 'medium', 2),

-- Q24: medium / L2 — GDPR right to erasure compliance
(5, 'Data Protection Technologies', 'In April 2026, Lakeshore Digital Marketing receives a valid GDPR Article 17 right-to-erasure request from a former customer in Germany. The customer''s personal data exists in the production database, three backup systems, and a third-party analytics platform. What is the MOST complete response to fulfill this request?', '["Delete the record from the production database only, since backups will naturally expire", "Acknowledge the request and schedule deletion for the next quarterly data cleanup cycle", "Delete the record from the production database and mark it for exclusion in future backup restorations", "Delete or anonymize the data across all systems including backups and the third-party platform, and document the actions taken"]'::jsonb, 3, 'Per GDPR Article 17 and NIST Privacy Framework, the right to erasure requires controllers to erase personal data from all processing systems without undue delay, including informing processors (third-party platforms) to delete the data. The organization must document compliance actions for accountability under GDPR Article 5(2). Choice A is incorrect because leaving personal data in backup systems still constitutes processing under GDPR, and natural expiration may take months, violating the "without undue delay" requirement.', 'medium', 2),

-- Q25: hard / L4 — Confidential computing evaluation for high-throughput
(5, 'Data Protection Technologies', 'In March 2026, Broadridge Financial Solutions processes $890 million in daily securities transactions through a multi-tenant cloud environment. Compliance requires that customer transaction data be protected not only at rest and in transit but also during active processing in memory. The team evaluates application-level encryption with decrypt-in-app logic, confidential computing with hardware-based TEEs, and homomorphic encryption. The system must sustain 10,000 transactions per second. Which recommendation BEST balances security and performance?', '["Confidential computing with TEEs, because it protects data in memory with hardware enforcement while maintaining near-native processing speeds", "Homomorphic encryption, because it provides the strongest mathematical privacy protections for in-memory data", "Application-level encryption with decrypt-in-app logic, because it offers the most flexible key management", "A layered approach combining all three technologies for comprehensive defense in depth"]'::jsonb, 0, 'Per NIST IR 8320, hardware-based Trusted Execution Environments (TEEs) provide memory encryption and isolation with minimal performance overhead (typically 2-8%), making them suitable for high-throughput transaction processing. Homomorphic encryption (choice B), while providing strong mathematical privacy, incurs orders-of-magnitude computational overhead that would not sustain 10,000 TPS for complex financial calculations. Unlike TEEs, choice C exposes plaintext in application memory, failing the requirement to protect data during active processing.', 'hard', 4),

-- Q26: easy / L1 — Digital signature purpose
(5, 'Data Protection Technologies', 'What is the PRIMARY purpose of a digital signature applied to an electronic document?', '["To encrypt the document''s contents so only the intended recipient can read them", "To compress the document for efficient storage and transmission", "To verify the identity of the signer and ensure the document has not been altered", "To create a backup copy of the document on the signer''s device"]'::jsonb, 2, 'Per NIST SP 800-89, a digital signature provides authentication (verifying the signer''s identity), integrity (detecting any modification to the signed content), and non-repudiation (preventing the signer from denying having signed). These properties are achieved through asymmetric cryptography applied to a hash of the document. Choice A is incorrect because digital signatures verify identity and integrity but do not encrypt document contents—encryption is a separate operation that protects confidentiality.', 'easy', 1),

-- Q27: medium / L3 — Wire-level vs application-level encryption gap
(5, 'Data Protection Technologies', 'In February 2026, Cascade Payment Systems encrypts all database connections using TLS 1.3 but does not apply application-level encryption to individual credit card fields before storage. A penetration tester gains access to the database server through a compromised administrative account. What is the MOST likely data exposure?', '["No data is exposed because TLS 1.3 protects the stored records", "The tester can read all credit card numbers in plaintext because wire-level encryption only protects data in transit, not data at rest in the database", "Only encrypted data is visible because TLS caches encrypted copies on disk", "The tester can access metadata but not field-level content within tables"]'::jsonb, 1, 'Per NIST SP 800-52 Rev. 2, TLS provides encryption for data in transit between endpoints but does not protect data once it reaches its destination and is stored. Without application-level encryption of sensitive fields, a compromised database administrator account can query and view plaintext credit card data directly. Choice A is incorrect because TLS terminates at the connection boundary—once data is written to the database, TLS provides no protection against local access by compromised accounts.', 'medium', 3),

-- Q28: hard / L4 — Zero-knowledge proof evaluation
(5, 'Data Protection Technologies', 'In April 2026, Vanguard Compliance Solutions develops a client identity verification system for anti-money laundering (AML) compliance. The system must verify that a client''s net worth exceeds $1 million without revealing the exact amount to the verifying party. The team evaluates zero-knowledge proofs, traditional credential sharing with NDAs, and homomorphic encryption. Which approach should the team recommend and what is the PRIMARY trade-off?', '["Zero-knowledge proofs, because they allow the client to prove a statement without revealing the underlying data, though implementation complexity is significant", "Traditional credential sharing with NDAs, because it is the simplest approach and provides adequate legal protection", "Homomorphic encryption, because it allows computation on encrypted financial data with no performance impact", "A blockchain-based attestation system that publicly records the verification without the underlying amount"]'::jsonb, 0, 'Per NIST IR 8214 Rev. 1, zero-knowledge proofs (ZKPs) enable a prover to demonstrate that a statement is true without revealing any information beyond the statement''s validity. For AML compliance, ZKPs allow verification that net worth exceeds a threshold without disclosing the actual figure. The primary trade-off is implementation complexity and computational cost. However, choice C is incorrect because homomorphic encryption introduces significant performance overhead and is designed for computation on encrypted data, not minimal-disclosure proofs.', 'hard', 4),

-- Q29: easy / L1 — Automated data classification function
(5, 'Data Protection Technologies', 'What is the PRIMARY function of an automated data classification tool in an enterprise environment?', '["To encrypt all data files as they are created on the network", "To delete data that has exceeded its defined retention period", "To monitor network traffic for unauthorized data transfers", "To scan and label data assets according to sensitivity levels based on predefined policies"]'::jsonb, 3, 'Per NIST SP 800-60 Vol. 1, data classification assigns sensitivity labels (e.g., public, internal, confidential, restricted) to data assets based on their content and regulatory requirements. Automated classification tools scan repositories and apply labels using pattern matching, machine learning, or policy rules. However, choice C is incorrect because it describes Data Loss Prevention (DLP) functionality rather than data classification—while classification may inform DLP policies, the classification tool''s primary function is labeling and categorization.', 'easy', 1),

-- Q30: hard / L4 — Federated learning privacy evaluation
(5, 'Data Protection Technologies', 'In March 2026, Heritage Health Network, a consortium of 12 hospitals, wants to train a predictive model for early sepsis detection using patient data from all members. HIPAA and state privacy laws prohibit sharing raw patient records between institutions. The consortium evaluates federated learning, centralized anonymized data pooling, and synthetic data generation. Which approach should the consortium recommend, and what residual privacy risk remains?', '["Centralized anonymized data pooling, because de-identification fully removes all privacy risk from the dataset", "Synthetic data generation, because fabricated records contain no information derived from real patients", "Federated learning, because model training occurs locally at each hospital with only weight updates shared, though gradient inversion attacks could partially reconstruct training data", "A combination of all three approaches to maximize both model accuracy and patient privacy"]'::jsonb, 2, 'Per NIST AI 100-1 and HIPAA Privacy Rule, federated learning allows collaborative model training without sharing raw data—each hospital trains locally and shares only aggregated model updates. This satisfies the prohibition on sharing raw patient records. The residual risk is gradient inversion attacks, where an adversary reconstructs training data from shared model gradients. However, choice A is incorrect because anonymized data pooling may fail to prevent re-identification given the richness of clinical data and known re-identification risks.', 'hard', 4)
;

COMMIT;
