-- Migration: Question generation — AUD batch 25 (30 questions)
-- Date: 2026-02-23
-- Topic: Misstatements and Control Deficiencies
-- Difficulty: 9E / 15M / 6H
-- Bloom's: L1:8 / L2:9 / L3:8 / L4:5

BEGIN;

INSERT INTO questions (section_id, topic, stem, choices, correct_index, explanation, difficulty, cognitive_level)
VALUES

-- Q1: easy / L2 — Clearly trivial misstatements and accumulation threshold
(1, 'Misstatements and Control Deficiencies', 'Brookfield Industries has overall materiality set at $100,000. The auditor identifies a $35 clerical error in office supplies. Under AU-C 450, the auditor''s most appropriate treatment of this misstatement is to:', '["Exclude it from accumulated misstatements because it is clearly trivial", "Include it in the summary of uncorrected misstatements for management review", "Document it as a significant deficiency in internal control", "Report it to those charged with governance as a potential fraud indicator"]'::jsonb, 0, 'Under AU-C 450.05, the auditor is not required to accumulate misstatements that are clearly trivial—amounts well below materiality that would not merit attention. A $35 error against $100,000 materiality is clearly trivial and need not be accumulated. Choice B is incorrect because accumulation is only required for misstatements that are not clearly trivial, not for amounts this immaterial.', 'easy', 2),

-- Q2: medium / L3 — Qualitative materiality when misstatement affects earnings trend
(1, 'Misstatements and Control Deficiencies', 'During the audit of Ridgeway Electronics, the auditor discovers a $12,000 understatement of expenses that, if corrected, would change reported net income from a 2% increase over the prior year to a 1% decline. Overall materiality is $250,000. The auditor should conclude that this misstatement:', '["Is immaterial because $12,000 is well below the $250,000 materiality threshold", "Should be treated as clearly trivial and excluded from accumulated misstatements", "May be material due to qualitative factors despite being quantitatively immaterial", "Requires automatic issuance of a qualified audit opinion"]'::jsonb, 2, 'Under AU-C 450.A18, the auditor evaluates misstatements both quantitatively and qualitatively. A misstatement that reverses an earnings trend from positive to negative may be material regardless of its dollar amount because it affects how users interpret performance. Choice A is incorrect because quantitative immateriality alone does not resolve the analysis when qualitative factors indicate the misstatement could influence user decisions.', 'medium', 3),

-- Q3: medium / L2 — Deficiency in operation vs. deficiency in design
(1, 'Misstatements and Control Deficiencies', 'During the audit of Pinnacle Logistics, the auditor discovers that the company has a policy requiring supervisory approval for all purchase orders exceeding $5,000, but the supervisor frequently approves batches without reviewing individual amounts. Under AU-C 265, this situation is best classified as:', '["A deficiency in the design of the control because the approval threshold is set too high", "A deficiency in the operation of the control because the control exists but is not performed effectively", "A material weakness because all purchase order controls have failed", "A compensating control failure because management relies on secondary reviews"]'::jsonb, 1, 'Under AU-C 265.A1, a deficiency in operation exists when a properly designed control does not operate effectively or when the person performing the control lacks the necessary authority or competence. Here, the approval control is well-designed but the supervisor is not executing it properly. Choice A is incorrect because the control''s design—requiring approval above $5,000—is appropriate; the issue is that the supervisor is not performing the review as intended.', 'medium', 2),

-- Q4: easy / L1 — Definition of pervasive misstatement
(1, 'Misstatements and Control Deficiencies', 'Under AU-C 705, a misstatement is considered pervasive when it:', '["Exceeds overall materiality for the financial statements as a whole", "Involves fraud committed by senior management", "Has been identified by the auditor rather than by management", "Affects multiple financial statement elements or represents a substantial proportion of the financial statements"]'::jsonb, 3, 'Under AU-C 705.06, pervasive effects are those not confined to specific elements, accounts, or items, or if confined, represent a substantial proportion of the financial statements or are fundamental to users'' understanding. Choice A is incorrect because exceeding materiality determines whether a misstatement is material, not whether it is pervasive—a misstatement can be material without being pervasive.', 'easy', 1),

-- Q5: easy / L1 — Purpose of the summary of uncorrected misstatements
(1, 'Misstatements and Control Deficiencies', 'The summary of uncorrected misstatements prepared during an audit is used to:', '["Replace the auditor''s need to evaluate materiality at the financial statement level", "Provide management with a formal demand letter for payment of audit adjustments", "Accumulate identified misstatements so the auditor can evaluate their aggregate effect on the financial statements", "Document the auditor''s basis for issuing a disclaimer of opinion"]'::jsonb, 2, 'Under AU-C 450.06, the auditor accumulates misstatements identified during the audit other than those that are clearly trivial. The summary of uncorrected misstatements enables the auditor to evaluate whether uncorrected misstatements are material, individually or in aggregate. Choice A is incorrect because the SUM schedule supports the materiality evaluation—it does not replace the auditor''s obligation to establish and apply materiality thresholds.', 'easy', 1),

-- Q6: medium / L2 — Communication timing for material weaknesses (60-day deadline)
(1, 'Misstatements and Control Deficiencies', 'After completing the audit of Granite Peak Construction, the auditor identified a material weakness on October 15, 2025. The audit report was dated November 3, 2025. Under AU-C 265, the written communication of this material weakness to those charged with governance must be made no later than:', '["60 days after the audit report release date", "The date the audit report is issued to the entity", "30 days after the completion of fieldwork", "The last day of the entity''s fiscal year under audit"]'::jsonb, 0, 'Under AU-C 265.13, the auditor must communicate significant deficiencies and material weaknesses in writing to those charged with governance no later than 60 days following the report release date. This timeline ensures governance receives the communication promptly while allowing the auditor adequate time to finalize the report. Choice B is incorrect because the deadline is tied to the report release date plus 60 days, not to the audit report issuance date itself.', 'medium', 2),

-- Q7: easy / L1 — Accumulation of misstatements excluding clearly trivial
(1, 'Misstatements and Control Deficiencies', 'Under AU-C 450, the auditor is required to accumulate misstatements identified during the audit, other than those that are:', '["Related to accounting estimates", "Clearly trivial", "Below performance materiality", "Caused by errors rather than fraud"]'::jsonb, 1, 'Under AU-C 450.05, the auditor must accumulate all misstatements identified during the audit except those that are clearly trivial. Clearly trivial means amounts well below materiality that would not need to be accumulated because they could not reasonably affect user decisions. Choice C is incorrect because misstatements below performance materiality but above the clearly trivial threshold must still be accumulated for aggregate evaluation.', 'easy', 1),

-- Q8: hard / L3 — IT general control deficiency cascading to application controls
(1, 'Misstatements and Control Deficiencies', 'During the audit of Meridian National Bank, the auditor discovers that the IT department has not restricted access to the production database, allowing developers to modify financial records without approval. The loan origination, accounts payable, and general ledger modules all rely on this database. When assessing the severity of this control deficiency under AU-C 265, the most significant implication is that:', '["Only the loan origination module is affected because developers primarily work with lending data", "The deficiency is limited to access controls and does not affect transaction processing integrity", "The auditor must disclaim an opinion because IT controls cannot be tested when access is unrestricted", "The reliability of automated controls across all three modules is undermined because they depend on the integrity of the shared database"]'::jsonb, 3, 'Under AU-C 265 and AU-C 315.A65, IT general controls support the continued proper functioning of application controls. When a pervasive ITGC deficiency such as unrestricted database access exists, the auditor cannot rely on automated controls in any dependent module, potentially constituting a material weakness. Choice A is incorrect because all three modules share the compromised database, meaning each module''s automated controls are equally affected by the unrestricted access.', 'hard', 3),

-- Q9: medium / L3 — Carryover effect of prior-period uncorrected misstatements
(1, 'Misstatements and Control Deficiencies', 'During last year''s audit of Clearwater Marine Services, the auditor accumulated $40,000 in uncorrected misstatements related to understated accrued liabilities. Management did not correct these misstatements. In the current year, the auditor should consider that these prior-period misstatements:', '["Have no relevance to the current year because they were evaluated in the prior-period audit", "Automatically require a qualified opinion in the current year if they remain uncorrected", "May affect the current-period financial statements and must be included in the current-year evaluation of uncorrected misstatements", "Should be communicated only to the predecessor auditor for documentation purposes"]'::jsonb, 2, 'Under AU-C 450.07, the auditor must determine whether uncorrected misstatements from prior periods affect the current-period financial statements. Prior-year understated accrued liabilities may reverse or persist, impacting current-year expenses and liabilities. These carryover effects must be included when evaluating aggregate uncorrected misstatements. Choice A is incorrect because misstatements do not lose relevance simply because they were previously evaluated—their financial statement effect may carry into or reverse in subsequent periods.', 'medium', 3),

-- Q10: medium / L2 — Projected misstatement calculation from sample
(1, 'Misstatements and Control Deficiencies', 'Apex Regional Hospital has a population of 4,000 patient billing records totaling $8,000,000. The auditor tests a sample of 100 records and identifies overcharges totaling $6,000 in the sample. Under AU-C 530, the projected misstatement for the population is:', '["$240,000", "$6,000", "$60,000", "$480,000"]'::jsonb, 0, 'Under AU-C 530.A20, when using sampling, the auditor projects the misstatement found in the sample to the population. The projection is $6,000 / 100 x 4,000 = $240,000. Choice B is incorrect because $6,000 represents only the known misstatement in the sample; the auditor must project this to the full population to estimate the likely total misstatement in the untested portion.', 'medium', 2),

-- Q11: medium / L3 — Auditor detection of material misstatement as MW indicator
(1, 'Misstatements and Control Deficiencies', 'During the audit of Sterling Aerospace, the auditor detects a material misstatement in the financial statements that would not have been detected by the entity''s internal controls. The auditor is evaluating whether this finding indicates a material weakness under AU-C 265. This situation:', '["Does not indicate a material weakness because the misstatement was ultimately detected by the auditor", "Is classified as a significant deficiency because the auditor served as a compensating control", "Requires no further evaluation because the financial statements will be corrected before issuance", "Is a strong indicator of a material weakness because the entity''s controls failed to prevent or detect a material misstatement"]'::jsonb, 3, 'Under AU-C 265.A14, identification of a material misstatement by the auditor that would not have been prevented or detected by the entity''s internal controls is a strong indicator of a material weakness. The control system should detect material misstatements without relying on the audit. Choice A is incorrect because the auditor is not a compensating control—the entity''s own controls must be sufficient to prevent or detect material misstatements on a timely basis.', 'medium', 3),

-- Q12: easy / L1 — Three categories of misstatements under AU-C 450
(1, 'Misstatements and Control Deficiencies', 'Under AU-C 450, the three categories of misstatements are:', '["Known, estimated, and suspected", "Factual, judgmental, and projected", "Material, immaterial, and trivial", "Quantitative, qualitative, and aggregate"]'::jsonb, 1, 'Under AU-C 450.A2–A4, misstatements are classified as factual (no doubt the misstatement exists), judgmental (arising from management''s unreasonable judgments about estimates or accounting policies), and projected (the auditor''s best estimate of misstatements in populations extrapolated from audit samples). Choice A is incorrect because ''known, estimated, and suspected'' is an older classification not used in current AU-C 450 terminology.', 'easy', 1),

-- Q13: medium / L3 — Misstatement near break-even converts profit to loss
(1, 'Misstatements and Control Deficiencies', 'Lakeshore Retail Group reports net income of $8,000 on total revenues of $12,500,000. The auditor identifies $10,000 in uncorrected misstatements that would convert the reported profit to a net loss. Overall materiality is $125,000. The auditor should conclude that these uncorrected misstatements are:', '["Likely material due to the qualitative significance of converting a profit to a loss, despite being quantitatively below materiality", "Immaterial because $10,000 is far below the $125,000 overall materiality threshold", "Clearly trivial and excluded from the summary of uncorrected misstatements", "A significant deficiency in internal control requiring written communication to governance"]'::jsonb, 0, 'Under AU-C 450.A18, the auditor considers qualitative factors when evaluating misstatements. A misstatement that converts reported income to a loss—even if quantitatively below materiality—can be material because it fundamentally changes the message conveyed by the financial statements. Choice B is incorrect because quantitative analysis alone is insufficient; misstatements near break-even carry heightened qualitative significance that may render them material to user decisions.', 'medium', 3),

-- Q14: medium / L3 — Fraud-related misstatement elevates control deficiency severity
(1, 'Misstatements and Control Deficiencies', 'While auditing Westbrook Manufacturing, the auditor discovers that an accounts payable clerk created fictitious vendor invoices totaling $18,000 over six months. The fraud was not prevented or detected by any internal control. Overall materiality is $200,000. When evaluating this finding under AU-C 265 and AU-C 240, the auditor should consider that:', '["The deficiency is a significant deficiency because the $18,000 is below materiality and the fraud was committed by a lower-level employee", "No control deficiency exists because the fraud was immaterial to the financial statements", "The presence of fraud elevates the severity assessment, and the control deficiency may constitute a material weakness regardless of the dollar amount involved", "The auditor should evaluate this as a projected misstatement and extrapolate the fraud to the full vendor population"]'::jsonb, 2, 'Under AU-C 265.A12 and AU-C 240.36, the identification of fraud—even if quantitatively immaterial—is a strong indicator of a material weakness because it reveals that controls failed to prevent or detect intentional manipulation. The nature of fraud carries qualitative weight beyond the dollar amount. Choice A is incorrect because the employee''s level does not determine severity; what matters is that existing controls failed to prevent or detect the fraudulent activity.', 'medium', 3),

-- Q15: medium / L2 — Management representation letter regarding uncorrected misstatements
(1, 'Misstatements and Control Deficiencies', 'After completing the audit of Birchwood Energy Corp., the auditor has accumulated $28,000 in uncorrected misstatements. Management has reviewed the summary and declined to make adjustments. Under AU-C 580, the auditor should obtain from management:', '["A waiver releasing the auditor from liability for the uncorrected misstatements", "A signed acknowledgment that the financial statements contain material misstatements", "An oral confirmation that the misstatements were considered and rejected", "A written representation that the effects of the uncorrected misstatements are immaterial, individually and in aggregate, to the financial statements as a whole"]'::jsonb, 3, 'Under AU-C 580.A8 and AU-C 450.12, when management does not correct identified misstatements, the auditor must obtain a written representation that the uncorrected misstatements are immaterial, both individually and in aggregate, to the financial statements as a whole. Choice C is incorrect because an oral confirmation is insufficient—AU-C 580 specifically requires written representations to provide appropriate audit evidence.', 'medium', 2),

-- Q16: medium / L2 — Deficiency in design when a necessary control is missing
(1, 'Misstatements and Control Deficiencies', 'During the audit of Thornfield Distribution, the auditor discovers that the company has no procedure to reconcile inventory counts with the perpetual inventory system. Under AU-C 265, this absence of a control is classified as:', '["A deficiency in the operation of the control because the reconciliation is not being performed", "A deficiency in the design of internal control because a necessary control does not exist", "A compensating control gap that must be offset by additional substantive testing", "An inherent limitation of internal control that does not constitute a deficiency"]'::jsonb, 1, 'Under AU-C 265.A1, a deficiency in design exists when a control necessary to meet a control objective is missing or when an existing control is not properly designed to prevent or detect misstatements on a timely basis. The complete absence of an inventory reconciliation procedure is a design deficiency. Choice A is incorrect because an operating deficiency requires that a control exist but not function effectively—here, no reconciliation control exists at all.', 'medium', 2),

-- Q17: medium / L2 — Revise audit plan when significant deficiency found during interim testing
(1, 'Misstatements and Control Deficiencies', 'During interim testing at Cascade Valley Foods, the auditor identifies a significant deficiency in the revenue recognition approval process. The audit plan originally relied on this control to reduce substantive testing. Under AU-C 265 and AU-C 330, the auditor''s most appropriate response is to:', '["Revise the audit plan to increase the nature, timing, or extent of substantive procedures for revenue", "Accept the deficiency and complete the audit using the original plan since interim results may improve by year-end", "Immediately withdraw from the engagement because controls cannot be relied upon", "Communicate the deficiency to management and take no further audit action until the next fiscal year"]'::jsonb, 0, 'Under AU-C 330.18, when control deficiencies indicate controls are not operating effectively, the auditor should revise the assessment of control risk and modify planned substantive procedures accordingly. Choice B is incorrect because the auditor cannot simply hope controls will improve by year-end; the identified deficiency requires an immediate response in the form of modified audit procedures to obtain sufficient appropriate evidence.', 'medium', 2),

-- Q18: hard / L4 — Evaluate whether to modify opinion for uncorrected misstatements near materiality
(1, 'Misstatements and Control Deficiencies', 'During the audit of Harborview Shipping International, the auditor accumulates $175,000 in uncorrected misstatements across accounts receivable and inventory. Overall materiality is $200,000 and performance materiality is $150,000. Management refuses to record adjustments, asserting the amounts are estimates subject to change. The misstatements are concentrated in two accounts and do not affect all financial statement line items. Given these circumstances, the engagement partner should:', '["Issue an unmodified opinion because the aggregate misstatements do not exceed overall materiality", "Issue a disclaimer of opinion because management''s refusal to adjust constitutes a scope limitation", "Issue a qualified opinion because the uncorrected misstatements are material but not pervasive to the financial statements", "Withdraw from the engagement because management''s refusal demonstrates a lack of integrity"]'::jsonb, 2, 'Under AU-C 705.08, when uncorrected misstatements are material but not pervasive, a qualified opinion is appropriate. At $175,000, the aggregate exceeds performance materiality and approaches overall materiality, making it likely material. Because the misstatements are confined to two accounts and not pervasive, a qualified opinion is warranted. Choice A is incorrect because the aggregate, combined with possible further undetected misstatement, likely renders the financial statements materially misstated.', 'hard', 4),

-- Q19: medium / L3 — Corrected misstatements still require control deficiency evaluation
(1, 'Misstatements and Control Deficiencies', 'During the audit of Redwood Capital Partners, the auditor identifies $95,000 in misstatements across revenue and expense accounts. Management promptly corrects all identified misstatements. The auditor is evaluating whether internal control deficiencies exist. The fact that management corrected the misstatements:', '["Eliminates the need to evaluate whether control deficiencies exist because the financial statements are now correct", "Confirms that compensating controls are operating effectively within the revenue cycle", "Reduces the severity of any control deficiency from material weakness to significant deficiency", "Does not eliminate the need to evaluate the underlying control deficiencies that allowed the misstatements to occur"]'::jsonb, 3, 'Under AU-C 265.A7, the auditor must evaluate control deficiencies regardless of whether management corrected the identified misstatements. The correction addresses the financial statement effect, but the underlying control weakness that permitted the errors remains relevant. Choice A is incorrect because correcting misstatements resolves the financial statement issue but does not address the root cause—the control system should prevent or detect misstatements without relying on the external audit.', 'medium', 3),

-- Q20: easy / L1 — Hierarchy of control deficiency severity levels
(1, 'Misstatements and Control Deficiencies', 'Under AU-C 265, the three severity levels for classifying internal control deficiencies from least to most severe are:', '["Control deficiency, significant deficiency, and material weakness", "Minor weakness, moderate weakness, and material weakness", "Observation, finding, and reportable condition", "Immaterial deficiency, significant deficiency, and adverse condition"]'::jsonb, 0, 'Under AU-C 265.07, control deficiencies are classified in ascending severity as a deficiency in internal control, a significant deficiency, or a material weakness. Each level is defined by the magnitude of potential misstatement and the likelihood that the deficiency could result in an undetected misstatement. Choice B is incorrect because ''minor weakness'' and ''moderate weakness'' are not recognized classifications under AU-C 265 or any current AICPA professional standard.', 'easy', 1),

-- Q21: hard / L4 — Evaluate combined deficiencies with delayed compensating control
(1, 'Misstatements and Control Deficiencies', 'Evergreen Regional Health System has three control deficiencies identified during the audit: (1) the accounts payable clerk does not match purchase orders to receiving reports before payment, (2) the purchasing manager does not review vendor master file changes, and (3) the monthly bank reconciliation, which serves as a compensating detective control, is performed two to three months late. Individually, the auditor assessed each as less than a significant deficiency. Under AU-C 265, the auditor should evaluate whether:', '["Each deficiency should be communicated separately to management as an other matter since none individually rises to significant deficiency", "The combination of these deficiencies, particularly given the delayed compensating control, constitutes a significant deficiency or material weakness", "The bank reconciliation alone is the only relevant deficiency because detective controls take priority over preventive controls", "No communication is required because all three deficiencies are individually below the significant deficiency threshold"]'::jsonb, 1, 'Under AU-C 265.A10, the auditor must consider whether a combination of individually less severe deficiencies might together constitute a significant deficiency or material weakness. Two preventive control failures combined with a delayed detective compensating control significantly increase the risk that material disbursement misstatements could go undetected. Choice D is incorrect because AU-C 265 explicitly requires evaluating deficiencies in combination—the aggregate risk from interrelated weaknesses may exceed what any single deficiency suggests.', 'hard', 4),

-- Q22: hard / L4 — Evaluate whether prior-year restatement indicates current-year MW after remediation
(1, 'Misstatements and Control Deficiencies', 'Nova Technologies restated its prior-year financial statements due to an error in capitalizing software development costs, reducing prior-year assets by $420,000. Management implemented new controls over capitalization decisions in the current year, including CFO review and monthly reconciliation of capitalized costs to project budgets. The auditor tested the new controls and found them operating effectively throughout the current year. Under AU-C 265, the auditor should conclude that:', '["A material weakness exists in the current year because any restatement automatically carries forward for at least two years", "A significant deficiency exists because remediated material weaknesses are downgraded to significant deficiencies in the following year", "A material weakness does not exist in the current year if the auditor has sufficient evidence that the new controls are appropriately designed and operating effectively", "No evaluation is necessary because the restatement relates to the prior year and has no bearing on the current-year control assessment"]'::jsonb, 2, 'Under AU-C 265.A14, while a restatement is a strong indicator of a material weakness, the auditor evaluates current-year conditions. If management implemented effective remediation and the auditor confirmed the new controls operate effectively, the material weakness may not exist in the current year. Choice A is incorrect because there is no automatic multi-year carryforward rule—the auditor assesses whether the underlying deficiency has been adequately remediated based on current evidence.', 'hard', 4),

-- Q23: easy / L1 — Recipients of written communication of significant deficiencies and MW
(1, 'Misstatements and Control Deficiencies', 'Under AU-C 265, significant deficiencies and material weaknesses identified during an audit must be communicated in writing to:', '["The external auditor''s national office for quality review", "The entity''s legal counsel for regulatory compliance assessment", "The Securities and Exchange Commission within 30 days of identification", "Those charged with governance of the entity"]'::jsonb, 3, 'Under AU-C 265.11, the auditor is required to communicate in writing to those charged with governance significant deficiencies and material weaknesses identified during the audit. This typically means the audit committee or board of directors. Choice C is incorrect because AU-C 265 does not require communication to the SEC—the auditor''s communication requirement is directed to the entity''s governance, not to regulators.', 'easy', 1),

-- Q24: medium / L3 — Misstatement causing debt covenant violation is qualitatively material
(1, 'Misstatements and Control Deficiencies', 'While auditing Grandview Properties LLC, the auditor identifies $45,000 in uncorrected misstatements that reduce the reported current ratio from 1.52 to 1.48. The entity''s loan agreement requires maintaining a minimum current ratio of 1.50. Overall materiality is $300,000. The auditor should evaluate these misstatements by considering that:', '["The misstatements are likely material because they cause a violation of a debt covenant, regardless of quantitative immateriality", "The misstatements are immaterial because $45,000 is far below the $300,000 materiality threshold", "Debt covenant compliance is a management responsibility outside the scope of the auditor''s evaluation", "The misstatements should be projected to the full population before evaluating covenant impact"]'::jsonb, 0, 'Under AU-C 450.A18, qualitative factors include whether a misstatement affects compliance with loan covenants. Even though $45,000 is quantitatively below materiality, causing a debt covenant violation is qualitatively significant because it could trigger loan default provisions. Choice B is incorrect because qualitative considerations can render a quantitatively immaterial misstatement material when it affects contractual obligations that financial statement users would consider important.', 'medium', 3),

-- Q25: hard / L4 — Management disputes material weakness classification
(1, 'Misstatements and Control Deficiencies', 'During the audit of Sequoia National Insurance, the auditor concludes that deficiencies in the claims reserving process constitute a material weakness. Management strongly disagrees, arguing the deficiencies are only significant deficiencies because no material misstatement actually occurred. The CFO requests that the written communication classify the deficiencies as significant deficiencies instead. Under AU-C 265, the auditor should:', '["Defer to management''s assessment because management has primary responsibility for internal controls", "Communicate the deficiencies as material weaknesses based on the auditor''s independent professional judgment, regardless of management''s disagreement", "Compromise by reporting the deficiencies as elevated significant deficiencies to resolve the disagreement", "Withdraw the written communication until management and the auditor reach consensus on the classification"]'::jsonb, 1, 'Under AU-C 265.A15, the auditor''s classification of control deficiencies is based on independent professional judgment about the magnitude and likelihood of potential misstatement. Management''s disagreement does not change the auditor''s assessment, and the absence of an actual material misstatement does not preclude a material weakness classification. Choice A is incorrect because while management is responsible for controls, the auditor independently evaluates and classifies deficiency severity.', 'hard', 4),

-- Q26: medium / L2 — Communication of other (non-significant) deficiencies to management
(1, 'Misstatements and Control Deficiencies', 'During the audit of Cedar Ridge Community College, the auditor identifies several control deficiencies that do not individually or in combination rise to the level of significant deficiencies. Under AU-C 265, the auditor''s obligation regarding these other deficiencies is:', '["No communication is permitted because only significant deficiencies and material weaknesses may be reported", "The auditor must communicate all deficiencies in writing to the audit committee regardless of severity", "The auditor may communicate these deficiencies to management if the auditor considers them worthy of management''s attention", "The auditor must include these deficiencies in the auditor''s report on the financial statements"]'::jsonb, 2, 'Under AU-C 265.A20, while significant deficiencies and material weaknesses require written communication to governance, the auditor may also communicate other deficiencies to management if the auditor believes they merit attention. This communication is not required but is permitted. Choice A is incorrect because AU-C 265 does not prohibit communicating deficiencies below the significant deficiency threshold—it simply does not require such communication.', 'medium', 2),

-- Q27: easy / L1 — Definition of tolerable misstatement in audit sampling
(1, 'Misstatements and Control Deficiencies', 'In audit sampling, tolerable misstatement is defined as:', '["The total amount of all uncorrected misstatements accumulated during the audit", "The threshold below which misstatements are considered clearly trivial", "The difference between overall materiality and the sum of known misstatements", "The maximum misstatement in a population that the auditor is willing to accept"]'::jsonb, 3, 'Under AU-C 530.05, tolerable misstatement is the application of performance materiality to a particular sampling procedure, representing the maximum monetary misstatement in an account balance or class of transactions that the auditor can accept. Choice A is incorrect because that describes the summary of uncorrected misstatements, which is the accumulated total of identified errors—a separate concept from the acceptable threshold set for sampling.', 'easy', 1),

-- Q28: hard / L4 — Evaluate adverse opinion for pervasive uncorrected misstatements
(1, 'Misstatements and Control Deficiencies', 'During the audit of Atlas Global Trading, the auditor accumulates $1,200,000 in uncorrected misstatements affecting revenue recognition, inventory valuation, and accounts receivable. Overall materiality is $500,000. The misstatements arise from management''s systematic application of an inappropriate revenue recognition policy affecting substantially all revenue transactions. Management refuses to correct the misstatements or change the policy. Given these circumstances, the engagement partner should:', '["Issue an adverse opinion because the uncorrected misstatements are both material and pervasive to the financial statements", "Issue a qualified opinion because the auditor disagrees with management''s accounting policy choice", "Withdraw from the engagement because management''s refusal constitutes an irreconcilable disagreement", "Issue an unmodified opinion with an emphasis-of-matter paragraph describing the accounting policy disagreement"]'::jsonb, 0, 'Under AU-C 705.09, when uncorrected misstatements are both material and pervasive, an adverse opinion is required. Misstatements totaling $1,200,000—more than double the $500,000 materiality—arising from a systematic policy error affecting substantially all revenue are both material and pervasive. Choice B is incorrect because a qualified opinion is appropriate only when misstatements are material but not pervasive; the widespread nature of this policy error affects the financial statements as a whole.', 'hard', 4),

-- Q29: easy / L1 — Documentation requirements for misstatements under AU-C 450
(1, 'Misstatements and Control Deficiencies', 'Under AU-C 450, the auditor is required to document:', '["Only uncorrected misstatements that individually exceed performance materiality", "All misstatements accumulated during the audit and whether they have been corrected", "Only misstatements communicated to those charged with governance", "Only misstatements arising from fraud, not those caused by error"]'::jsonb, 1, 'Under AU-C 450.14, the auditor must include in audit documentation the clearly trivial threshold, all misstatements accumulated during the audit and whether they have been corrected, and the auditor''s conclusion about whether uncorrected misstatements are material. Choice A is incorrect because the documentation requirement covers all accumulated misstatements—not merely those exceeding performance materiality—along with the auditor''s aggregate evaluation.', 'easy', 1),

-- Q30: medium / L2 — Identified misstatements exceeding performance materiality require investigation
(1, 'Misstatements and Control Deficiencies', 'Bridgewater Holdings has overall materiality set at $400,000. The auditor sets performance materiality at $280,000. During testing of accounts payable, the auditor identifies $290,000 in misstatements. Under AU-C 320 and AU-C 450, the auditor should:', '["Disregard the misstatements because they fall below overall materiality of $400,000", "Immediately issue a qualified opinion because performance materiality has been exceeded", "Investigate whether additional misstatements exist and request management correction because the identified amount exceeds performance materiality", "Reclassify the misstatements as clearly trivial because they relate to a single account"]'::jsonb, 2, 'Under AU-C 320.A13 and AU-C 450.08, performance materiality is set below overall materiality to reduce the probability that aggregate uncorrected misstatements exceed materiality. When identified misstatements exceed performance materiality, the auditor should request management correction and consider whether additional procedures are needed. Choice A is incorrect because performance materiality—not overall materiality—is the relevant threshold for evaluating detected misstatements during fieldwork.', 'medium', 2)
;

COMMIT;
