-- Migration: Question generation — AUD batch 23 (30 questions)
-- Date: 2026-02-23
-- Topic: Misstatements and Control Deficiencies
-- Difficulty: 9E / 15M / 6H
-- Bloom's: L1:8 / L2:9 / L3:8 / L4:5

BEGIN;

INSERT INTO questions (section_id, topic, stem, choices, correct_index, explanation, difficulty, cognitive_level)
VALUES

-- Q1: medium / L2 — Clearly trivial threshold application
(1, 'Misstatements and Control Deficiencies', 'Greenfield Manufacturing has overall materiality set at $200,000 and performance materiality at $150,000. During testing, the auditor discovers a $750 misstatement in office supplies expense. Under AU-C 450, the auditor should treat this misstatement as:', '["An immaterial misstatement that must still be accumulated on the summary of uncorrected misstatements", "A projected misstatement requiring extrapolation to the full population", "A clearly trivial amount that need not be accumulated with other misstatements", "A factual misstatement that must be reported to those charged with governance"]'::jsonb, 2, 'Under AU-C 450.A2, misstatements are clearly trivial when they are inconsequential both individually and in the aggregate. At $750, this amount is well below any reasonable threshold relative to $200,000 materiality (typically 5% or less of materiality). Choice A is incorrect because clearly trivial misstatements need not be accumulated on the summary of uncorrected misstatements, unlike those that are merely immaterial.', 'medium', 2),

-- Q2: medium / L3 — Effect of uncorrected misstatements approaching materiality
(1, 'Misstatements and Control Deficiencies', 'After completing fieldwork at Ridgeway Financial Group, the auditor accumulates $180,000 in uncorrected misstatements against overall materiality of $200,000. Management declines to make adjustments, asserting the misstatements are immaterial. Analyze the most likely effect on the auditor''s report.', '["The auditor must issue a qualified opinion because the misstatements are material", "The auditor should request management to correct the misstatements and, if they refuse, evaluate whether a modified opinion is necessary", "The auditor should issue an unqualified opinion because the misstatements do not exceed materiality", "The auditor should withdraw from the engagement because management is being uncooperative"]'::jsonb, 1, 'Under AU-C 450.11, when aggregate uncorrected misstatements approach materiality, the auditor must consider whether additional undetected misstatements could cause the total to exceed materiality. The auditor should request corrections and reassess the opinion. Choice C is incorrect because proximity to materiality, combined with the risk of undetected misstatements, means an unqualified opinion without further consideration would be inappropriate.', 'medium', 3),

-- Q3: easy / L1 — Deficiency in design vs deficiency in operation
(1, 'Misstatements and Control Deficiencies', 'Under AU-C 265, what distinguishes a deficiency in design from a deficiency in operation?', '["A design deficiency means a necessary control is missing or improperly designed; an operation deficiency means an existing control does not operate effectively", "A design deficiency applies to IT controls only; an operation deficiency applies to manual controls only", "A design deficiency involves financial reporting objectives; an operation deficiency involves compliance objectives", "A design deficiency requires immediate disclosure; an operation deficiency can be communicated at year-end"]'::jsonb, 0, 'Under AU-C 265.07, a deficiency in design exists when a control necessary to meet a control objective is missing or not suitably designed. A deficiency in operation exists when a properly designed control does not operate as designed or the person performing it lacks authority or competence. Choice B is incorrect because both design and operation deficiencies can occur in either IT or manual controls.', 'easy', 1),

-- Q4: medium / L3 — Iron curtain vs rollover approach
(1, 'Misstatements and Control Deficiencies', 'Sterling Industries has a $30,000 uncorrected misstatement from the prior year that reverses in the current year, plus a new $25,000 current-year misstatement. Overall materiality is $50,000. The auditor evaluates the effect on current-year financial statements. Analyze which approach yields the more conservative assessment.', '["The rollover approach yields $55,000, exceeding materiality, making it more conservative", "Both approaches yield the same result of $25,000 because the prior-year misstatement reversed", "The iron curtain approach yields $25,000 because it considers only current-year originations", "The iron curtain approach yields $55,000 because it evaluates the cumulative balance sheet effect, making it more conservative"]'::jsonb, 3, 'Under AU-C 450.A16 and SAB No. 108, the iron curtain approach evaluates the total misstatement remaining in the balance sheet ($30,000 + $25,000 = $55,000), while the rollover approach considers only current-year originations ($25,000). The iron curtain method is more conservative here because it captures the cumulative effect. Choice A is incorrect because the rollover approach considers only the current-year misstatement of $25,000, not $55,000.', 'medium', 3),

-- Q5: easy / L2 — Audit adjustment vs reclassification
(1, 'Misstatements and Control Deficiencies', 'During the audit of Bayside Retailers, the auditor proposes moving $45,000 from accounts receivable to other current assets on the balance sheet. Under auditing standards, this proposed change is classified as:', '["A factual misstatement requiring a correcting journal entry", "A reclassification adjustment that corrects financial statement presentation", "A judgmental misstatement based on the auditor''s professional opinion", "A prior-period adjustment affecting retained earnings"]'::jsonb, 1, 'Under AU-C 450, reclassification adjustments correct the classification or presentation of amounts in the financial statements without changing net income or total assets. Moving $45,000 between balance sheet line items is a presentation correction, not an income-affecting adjustment. Choice A is incorrect because factual misstatements involve errors in amounts gathered or processed, whereas reclassifications address presentation and disclosure.', 'easy', 2),

-- Q6: easy / L1 — Clearly trivial definition
(1, 'Misstatements and Control Deficiencies', 'Under AU-C 450, what does the term ''clearly trivial'' mean in the context of audit misstatements?', '["Misstatements below performance materiality that need not be communicated to management", "Misstatements that are immaterial to the financial statements taken as a whole", "Misstatements of an amount wholly inconsequential, whether individually or in the aggregate", "Misstatements that management has agreed to correct before the audit is completed"]'::jsonb, 2, 'Under AU-C 450.A2, clearly trivial is not another expression for not material. Clearly trivial misstatements are of a wholly inconsequential amount, both individually and in the aggregate, representing a smaller threshold than immaterial. Choice B is incorrect because immaterial misstatements must still be accumulated on the summary of uncorrected misstatements, whereas clearly trivial ones need not be.', 'easy', 1),

-- Q7: medium / L3 — Prior-period uncorrected misstatements effect on current year
(1, 'Misstatements and Control Deficiencies', 'Meridian Electronics carried forward $85,000 in uncorrected misstatements from the prior year. The auditor is evaluating current-year financial statements with materiality set at $100,000. Under AU-C 450, analyze how the prior-period misstatements affect the current-year evaluation.', '["The auditor must consider the effect of prior-period uncorrected misstatements on current-year financial statements, including any reversal or continuation", "Prior-period misstatements are excluded from the current-year evaluation because they were already assessed in the prior audit", "The auditor should add the full $85,000 to current-year misstatements regardless of whether they reversed", "Prior-period misstatements only affect the current year if management acknowledged them in the representation letter"]'::jsonb, 0, 'Under AU-C 450.10, the auditor must include the effect of prior-period uncorrected misstatements on current-year financial statements. This requires evaluating whether they reversed, persisted, or created new misstatements in the current period. Choice B is incorrect because prior-period misstatements that affect the current-year balance sheet or income statement remain relevant and cannot simply be excluded from the evaluation.', 'medium', 3),

-- Q8: medium / L2 — Management representations about misstatements
(1, 'Misstatements and Control Deficiencies', 'At the conclusion of the audit of Aspen Ridge Hotels, the auditor prepares the management representation letter. Under AU-C 450, which representation must the auditor obtain from management regarding uncorrected misstatements?', '["Management certifies that all misstatements identified are factual rather than judgmental", "Management acknowledges that the audit was conducted in accordance with GAAS", "Management agrees to correct all uncorrected misstatements in the subsequent period", "Management believes the effects of uncorrected misstatements are immaterial, individually and in the aggregate, to the financial statements as a whole"]'::jsonb, 3, 'Under AU-C 450.14, the auditor must obtain a written representation from management that it believes the effects of uncorrected misstatements are immaterial, individually and in the aggregate, to the financial statements as a whole. A summary of these items must be attached. Choice C is incorrect because the representation does not require management to commit to future corrections, only to acknowledge immateriality.', 'medium', 2),

-- Q9: hard / L4 — Intentional immaterial misstatement and fraud considerations
(1, 'Misstatements and Control Deficiencies', 'During the audit of Cornerstone Financial Partners, the auditor discovers that the controller intentionally reclassified $8,000 of personal expenses as business travel. Overall materiality is $500,000 and the amount is quantitatively immaterial. The engagement partner must evaluate how to proceed. Under AU-C 240 and AU-C 450, what is the most appropriate course of action?', '["Treat the misstatement as clearly trivial because it is far below materiality and does not require accumulation", "Evaluate the implications of the intentional misstatement on the integrity of management and the reliability of management representations throughout the audit", "Issue a qualified opinion because any intentional misstatement automatically constitutes a material weakness", "Reduce planned materiality to $8,000 to capture potential additional intentional misstatements"]'::jsonb, 1, 'Under AU-C 240.35, an intentional misstatement, even if quantitatively immaterial, raises questions about management integrity and may indicate broader fraud risk. The auditor must evaluate the implications on management''s representations and the risk of additional fraud. Choice A is incorrect because AU-C 450.A3 explicitly states that an intentional misstatement is not clearly trivial regardless of amount, since it has qualitative significance related to fraud risk.', 'hard', 4),

-- Q10: hard / L3 — Qualitative factors in misstatement evaluation
(1, 'Misstatements and Control Deficiencies', 'Pinnacle Manufacturing has $65,000 in aggregate uncorrected misstatements against materiality of $150,000. However, $40,000 relates to management compensation and bonus calculations, and $15,000 involves a debt covenant ratio currently near its threshold. Analyze the most significant qualitative factor the auditor should consider.', '["Whether the misstatements originated in the current period or carried forward from prior years", "Whether the misstatements are factual, judgmental, or projected in nature", "Whether the misstatements affect compliance with contractual obligations or involve sensitive line items such as executive compensation", "Whether management has provided a written representation that the misstatements are immaterial"]'::jsonb, 2, 'Under AU-C 450.11 and .A19, qualitative considerations include whether misstatements affect compliance with loan covenants, regulatory requirements, or involve sensitive items like management compensation that could indicate bias. These qualitative factors can make quantitatively immaterial misstatements significant. Choice B is incorrect because while the nature of misstatements matters, the specific qualitative concerns—covenant compliance and compensation sensitivity—are the most critical factors here.', 'hard', 3),

-- Q11: hard / L4 — Pervasive vs non-pervasive effect on opinion type
(1, 'Misstatements and Control Deficiencies', 'During the audit of Lakewood Consolidated Industries, the auditor identifies material misstatements affecting accounts receivable, inventory, and cost of goods sold—representing three of the entity''s five major account groups. Management refuses all corrections. The auditor must evaluate whether the effect is pervasive. Under AU-C 705, recommend the appropriate opinion.', '["An adverse opinion, because misstatements affecting multiple major account groups are pervasive to the financial statements", "A qualified opinion, because the misstatements are material but confined to specific accounts", "A disclaimer of opinion, because the auditor cannot determine the full extent of the misstatements", "An unmodified opinion with an emphasis-of-matter paragraph highlighting the uncorrected misstatements"]'::jsonb, 0, 'Under AU-C 705.08, when material misstatements are pervasive—meaning they affect multiple elements, represent a substantial proportion of the financial statements, or fundamentally affect disclosures—an adverse opinion is required. Three of five major account groups is pervasive. Choice B is incorrect because a qualified opinion applies when misstatements are material but not pervasive, which does not describe misstatements spanning the majority of account groups.', 'hard', 4),

-- Q12: easy / L1 — Three categories of misstatements
(1, 'Misstatements and Control Deficiencies', 'Under AU-C 450, what are the three categories of misstatements that an auditor should accumulate during the audit?', '["Known misstatements, likely misstatements, and possible misstatements", "Material misstatements, immaterial misstatements, and clearly trivial misstatements", "Quantitative misstatements, qualitative misstatements, and disclosure misstatements", "Factual misstatements, judgmental misstatements, and projected misstatements"]'::jsonb, 3, 'Under AU-C 450.04-.06, misstatements are categorized as factual (no doubt about existence), judgmental (differences in estimates or policies the auditor considers unreasonable), and projected (the auditor''s best estimate of misstatements in populations based on audit sampling). Choice A is incorrect because those terms reflect older terminology from SAS 89 and are not the current classification under AU-C 450.', 'easy', 1),

-- Q13: easy / L1 — Summary of uncorrected misstatements attachment
(1, 'Misstatements and Control Deficiencies', 'Under AU-C 450, what must the auditor include with the management representation letter regarding misstatements?', '["A list of all controls tested during the audit and their effectiveness ratings", "A summary of uncorrected misstatements identified during the audit", "A schedule of all journal entries proposed by the auditor during fieldwork", "A description of the sampling methods used to detect misstatements"]'::jsonb, 1, 'Under AU-C 450.14, the auditor must request that management provide written representations and must attach or include a summary of uncorrected misstatements to the representation letter. This ensures management has acknowledged and considered each item. Choice C is incorrect because proposed journal entries that management accepted are corrected misstatements, not uncorrected ones requiring representation.', 'easy', 1),

-- Q14: easy / L1 — Timing of written communication of deficiencies
(1, 'Misstatements and Control Deficiencies', 'Under AU-C 265, when must the auditor communicate significant deficiencies and material weaknesses in writing?', '["No later than 60 days following the report release date", "Within 30 days of the discovery of the deficiency", "Before the auditor begins substantive testing procedures", "Only upon specific request from those charged with governance"]'::jsonb, 0, 'Under AU-C 265.13, the auditor must communicate significant deficiencies and material weaknesses in writing to those charged with governance no later than 60 days following the report release date. This allows time for proper evaluation and drafting. Choice B is incorrect because the 60-day deadline runs from the report release date, not from the date of discovery of the deficiency.', 'easy', 1),

-- Q15: hard / L4 — PCAOB integrated audit vs GAAS nonissuer differences
(1, 'Misstatements and Control Deficiencies', 'A CPA firm audits both Whitfield Industries (a publicly traded company) and Glenmore Services (a privately held company). Both audits reveal material weaknesses. The engagement partners must evaluate how professional standards differ in required communications about control deficiencies. Assess which statement correctly describes the difference.', '["Both PCAOB and GAAS standards require the auditor to express an opinion on internal control over financial reporting", "PCAOB standards require communication only to the SEC, while GAAS requires communication only to the audit committee", "Under PCAOB AS 2201, the auditor must express an opinion on internal control effectiveness, whereas under AU-C 265, the auditor communicates deficiencies but does not opine on internal control", "PCAOB standards classify all control deficiencies as material weaknesses, while GAAS distinguishes between deficiency levels"]'::jsonb, 2, 'Under PCAOB AS 2201, the auditor of a public company must perform an integrated audit and express a separate opinion on internal control over financial reporting. Under AU-C 265 for nonissuers, the auditor communicates significant deficiencies and material weaknesses but does not issue an opinion on ICFR. Choice A is incorrect because only PCAOB standards require an opinion on ICFR; GAAS audits for nonissuers do not include this requirement.', 'hard', 4),

-- Q16: medium / L3 — Entity-level control deficiency analysis
(1, 'Misstatements and Control Deficiencies', 'During the audit of Northwind Technologies, the auditor discovers that the board of directors has not met in over 12 months and the audit committee has no financially literate member. Analyze the most likely classification of these findings under AU-C 265.', '["Individual control deficiencies that do not rise above the level of other deficiencies because they are governance matters, not financial controls", "Indicators of material weakness because deficiencies in entity-level controls such as the control environment are pervasive and affect the overall reliability of financial reporting", "Significant deficiencies that should be communicated only to management since the board is unable to receive communications", "Immaterial findings that need only be documented in the audit workpapers without further communication"]'::jsonb, 1, 'Under AU-C 265.A12 and COSO, the control environment—including board oversight and audit committee competence—is a foundational entity-level control. Deficiencies in these controls are often indicators of material weakness because they undermine the effectiveness of all other controls. Choice A is incorrect because governance-level controls directly affect financial reporting reliability and are explicitly within the scope of AU-C 265.', 'medium', 3),

-- Q17: medium / L3 — Prohibition on netting misstatements across accounts
(1, 'Misstatements and Control Deficiencies', 'At Copperfield Distribution, the auditor identifies a $75,000 overstatement in accounts receivable and a $70,000 understatement in inventory. The CFO argues the net effect is only $5,000. Analyze the appropriate response under AU-C 450.', '["Accept management''s position because the net effect of $5,000 is clearly trivial relative to materiality", "Evaluate only the larger misstatement of $75,000 because it drives the overall risk assessment", "Offset the misstatements only if they affect the same financial statement line item", "Evaluate each misstatement separately and also consider the aggregate effect, because offsetting misstatements in different accounts can mask the true magnitude of errors"]'::jsonb, 3, 'Under AU-C 450.11 and .A18, the auditor should not offset misstatements in different accounts, even if the net effect appears small. Each misstatement may affect different assertions and users'' decisions differently. The auditor must evaluate them individually and in aggregate. Choice A is incorrect because netting misstatements across unrelated accounts obscures their individual significance and could mask a material misstatement in a specific account.', 'medium', 3),

-- Q18: medium / L2 — Documentation of accumulated misstatements
(1, 'Misstatements and Control Deficiencies', 'During the audit of Brightwater Construction, the auditor accumulates identified misstatements throughout fieldwork. Under AU-C 450, the auditor''s documentation of these accumulated misstatements must include:', '["The amount of each misstatement, its nature, and whether it was corrected by management or remains uncorrected", "Only the misstatements that exceed the clearly trivial threshold and remain uncorrected at year-end", "A description of each misstatement cross-referenced to the specific audit procedure that detected it", "Only the net aggregate of all misstatements rather than individual amounts"]'::jsonb, 0, 'Under AU-C 450.12-.14 and AU-C 230, the auditor must document all accumulated misstatements above the clearly trivial threshold, noting their amount, nature, and disposition—whether corrected or uncorrected. This provides a clear record of the evaluation process. Choice B is incorrect because corrected misstatements must also be documented, as they are relevant to understanding the nature and cause of misstatements detected during the audit.', 'medium', 2),

-- Q19: easy / L1 — Severity spectrum of control deficiencies
(1, 'Misstatements and Control Deficiencies', 'Under AU-C 265, what is the correct hierarchy of control deficiency severity from least to most severe?', '["Significant deficiency, control deficiency, material weakness", "Material weakness, significant deficiency, control deficiency", "Control deficiency, significant deficiency, material weakness", "Control deficiency, material weakness, significant deficiency"]'::jsonb, 2, 'Under AU-C 265.07, the severity hierarchy progresses from a control deficiency (least severe) to a significant deficiency (important enough to merit governance attention) to a material weakness (most severe, reasonable possibility of unpreventable or undetectable material misstatement). Choice A is incorrect because it reverses the positions of control deficiency and significant deficiency in the hierarchy.', 'easy', 1),

-- Q20: medium / L2 — Summary of uncorrected misstatements content
(1, 'Misstatements and Control Deficiencies', 'After completing the audit of Redstone Hospitality Group, the auditor prepares the summary of uncorrected misstatements. Five misstatements totaling $42,000 were identified against materiality of $100,000. Under AU-C 450, the summary should contain:', '["Only the single largest misstatement because individually immaterial items are excluded from the summary", "Each misstatement above clearly trivial, showing its individual amount, nature, and effect on the financial statements", "Only projected misstatements from sampling because factual misstatements must be corrected", "A single aggregate dollar amount without detail of individual misstatements"]'::jsonb, 1, 'Under AU-C 450.12, the summary of uncorrected misstatements must include all misstatements above the clearly trivial threshold—whether factual, judgmental, or projected—with sufficient detail for management and governance to evaluate each one individually. Choice D is incorrect because a single aggregate amount does not allow management or those charged with governance to evaluate individual misstatements and decide whether to correct specific items.', 'medium', 2),

-- Q21: medium / L2 — Communication of other (non-significant) deficiencies
(1, 'Misstatements and Control Deficiencies', 'During the audit of Cascade Valley Bank, the auditor identifies several control deficiencies that individually and in combination do not rise to the level of significant deficiencies. Under AU-C 265, the auditor should communicate these other deficiencies to:', '["Management, in writing or orally, depending on the auditor''s professional judgment about the significance and nature of the communication", "Those charged with governance in the same written communication as significant deficiencies", "Only the internal audit department for remediation tracking purposes", "No one, because deficiencies below significant deficiency level do not require communication"]'::jsonb, 0, 'Under AU-C 265.12, the auditor should communicate to management control deficiencies identified during the audit that are not significant deficiencies or material weaknesses but are nevertheless worthy of management''s attention. This communication may be oral or written. Choice D is incorrect because AU-C 265 recognizes that even lower-severity deficiencies may warrant communication to management, though the form and timing are left to professional judgment.', 'medium', 2),

-- Q22: easy / L1 — Restatement trigger from discovered misstatements
(1, 'Misstatements and Control Deficiencies', 'Under auditing standards, when does a previously issued financial statement require restatement due to misstatements?', '["When any misstatement is identified in the current-year audit that relates to a prior period", "When the aggregate of all prior-period misstatements exceeds performance materiality", "When management voluntarily decides to reissue the financial statements for comparability", "When a misstatement in previously issued financial statements is determined to be material to those statements"]'::jsonb, 3, 'Under AU-C 560.14 and AU-C 450, restatement is required when a misstatement is identified that is material to the previously issued financial statements, meaning it would have affected users'' decisions at that time. Materiality is assessed relative to the prior-period statements. Choice A is incorrect because not all prior-period misstatements require restatement—only those that are material to the previously issued statements.', 'easy', 1),

-- Q23: medium / L2 — Risk of material misstatement from segregation of duties failure
(1, 'Misstatements and Control Deficiencies', 'At Franklin Aerospace, the auditor discovers that the accounts payable clerk can both create new vendors and approve invoices without supervisory review. Under AU-C 315 and AU-C 265, the auditor should assess this finding as:', '["An insignificant deficiency because the accounts payable clerk is a low-level employee", "A compliance finding unrelated to the financial statement audit", "A control deficiency indicating inadequate segregation of duties that increases the risk of material misstatement and warrants severity evaluation under AU-C 265", "A material weakness requiring immediate communication before completing the audit"]'::jsonb, 2, 'Under AU-C 315.14 and AU-C 265.08, a lack of segregation of duties is a control deficiency that increases the risk of material misstatement due to potential unauthorized transactions. The auditor must evaluate its severity to determine if it rises to significant deficiency or material weakness. Choice D is incorrect because the auditor must first evaluate the magnitude of potential misstatement and whether compensating controls exist before classifying the severity level.', 'medium', 2),

-- Q24: hard / L4 — Management bias evaluation in estimates
(1, 'Misstatements and Control Deficiencies', 'Over the past three audits of Evergreen Capital Partners, the auditor has observed that management''s accounting estimates consistently result in favorable effects on reported earnings, each within an individually reasonable range. In the current year, the auditor identifies similar patterns in warranty reserves, bad debt allowances, and depreciation estimates. Under AU-C 450 and AU-C 540, evaluate the most appropriate conclusion.', '["No action is required because each individual estimate falls within a reasonable range", "The cumulative pattern of favorable estimates indicates possible management bias, which the auditor must evaluate as a potential risk of material misstatement due to fraud", "The auditor should adjust all estimates to the midpoint of the reasonable range to eliminate the bias", "The auditor should disclose the pattern in the auditor''s report as an emphasis-of-matter paragraph"]'::jsonb, 1, 'Under AU-C 450.A20 and AU-C 540.21, when estimates consistently favor earnings over multiple periods, this may indicate management bias, a fraud risk indicator under AU-C 240. The auditor must evaluate the cumulative effect and whether the overall financial statements are materially misstated. Choice A is incorrect because even though individual estimates may be reasonable, a persistent pattern of one-directional estimates across accounts and periods constitutes a bias indicator requiring fraud risk evaluation.', 'hard', 4),

-- Q25: medium / L3 — Remediation effect on control deficiency classification
(1, 'Misstatements and Control Deficiencies', 'During interim fieldwork at Westbrook Financial, the auditor identifies a material weakness in the revenue recognition process. By year-end, management implements corrective controls and the auditor retests with satisfactory results. Analyze the effect on the auditor''s control deficiency communication.', '["The material weakness need not be communicated because it was fully remediated before year-end", "The auditor must still report it as a material weakness because it existed during the audit period", "The remediation eliminates the need for any written communication about this deficiency", "The auditor should evaluate whether the remediated control operated for a sufficient period to determine if the material weakness still existed at year-end"]'::jsonb, 3, 'Under AU-C 265.A8, if management remediates a control deficiency during the audit period, the auditor must evaluate whether the new control operated effectively for a sufficient period before concluding the deficiency no longer exists at year-end. Brief operation may not provide adequate evidence. Choice A is incorrect because mere implementation of corrective controls does not automatically eliminate a material weakness; the auditor must test operating effectiveness over a sufficient duration.', 'medium', 3),

-- Q26: easy / L1 — Communication of corrected misstatements to governance
(1, 'Misstatements and Control Deficiencies', 'Under AU-C 260, which communication about misstatements is required to those charged with governance?', '["The nature of corrected misstatements brought to management''s attention as a result of audit procedures", "Only uncorrected misstatements exceeding performance materiality", "A complete list of all clearly trivial misstatements identified during the audit", "Only misstatements resulting from fraud, not from error"]'::jsonb, 0, 'Under AU-C 260.A15 and AU-C 450.12, the auditor should communicate to those charged with governance the nature of corrected misstatements brought to management''s attention, as these may indicate control deficiencies or patterns. Choice B is incorrect because AU-C 260 requires communication about the nature of corrected misstatements generally, not only those above performance materiality.', 'easy', 1),

-- Q27: medium / L3 — Dual-purpose testing and deficiency identification
(1, 'Misstatements and Control Deficiencies', 'While performing tests of controls over cash disbursements at Horizon Logistics, the auditor also collects substantive evidence from the same transactions. Five of 40 disbursements lack required supervisory approval, though all amounts are accurately recorded. Analyze the auditor''s most appropriate response.', '["No further action is needed because the substantive testing confirmed the amounts were correctly recorded", "The auditor should increase the sample size for substantive testing but need not evaluate the control failure", "The auditor should evaluate the missing approvals as a control deficiency and assess its severity, regardless of the accuracy of the underlying amounts", "The auditor should report the finding only if the unapproved disbursements exceed materiality"]'::jsonb, 2, 'Under AU-C 265.07 and AU-C 330.10, a control failure is evaluated independently of whether substantive misstatements resulted. Missing supervisory approvals in 5 of 40 items (12.5%) represents a control deficiency that must be assessed for severity. Accurate amounts do not negate the control failure. Choice A is incorrect because substantive accuracy does not eliminate the control deficiency; missing approvals represent a breakdown in the control''s operation that could allow future misstatements.', 'medium', 3),

-- Q28: medium / L2 — Tolerable misstatement relationship to account-level evaluation
(1, 'Misstatements and Control Deficiencies', 'While planning the audit of Summit Trails Outdoor Equipment, the auditor sets overall materiality at $250,000 and tolerable misstatement for accounts receivable at $100,000. During testing, the auditor projects a $90,000 misstatement in accounts receivable. Under AU-C 530, the auditor should:', '["Accept the account balance because $90,000 is below overall materiality of $250,000", "Evaluate the projected misstatement against tolerable misstatement and consider whether additional procedures are needed because it approaches the $100,000 threshold", "Automatically require management to adjust accounts receivable by exactly $90,000", "Issue a qualified opinion on the accounts receivable balance only"]'::jsonb, 1, 'Under AU-C 530.13-.14, when a projected misstatement approaches tolerable misstatement for an account, the auditor must consider the risk that the actual misstatement could exceed tolerable misstatement and evaluate whether additional procedures or adjustments are necessary. Choice A is incorrect because tolerable misstatement, not overall materiality, is the relevant benchmark for evaluating misstatements at the individual account level during sampling.', 'medium', 2),

-- Q29: medium / L2 — Debt covenant compliance effect of misstatements
(1, 'Misstatements and Control Deficiencies', 'Atlas Engineering has a debt covenant requiring a current ratio above 1.5. The current ratio is 1.55 before considering $35,000 in uncorrected misstatements that would reduce current assets. Overall materiality is $200,000. Under AU-C 450, the auditor should:', '["Disregard the misstatements because they are below materiality and cannot affect the audit opinion", "Communicate the finding only in the management letter as a minor observation", "Require management to correct the misstatements before issuing the report", "Consider the qualitative significance of the misstatements because they could cause a covenant violation, even though they are quantitatively immaterial"]'::jsonb, 3, 'Under AU-C 450.11 and .A19, even quantitatively immaterial misstatements take on qualitative significance when they could cause violation of loan covenants or regulatory requirements. The potential $35,000 reduction in current assets could push the ratio below 1.5, triggering default. Choice A is incorrect because immaterial misstatements can still require the auditor''s attention when qualitative factors such as debt covenant compliance are affected.', 'medium', 2),

-- Q30: hard / L4 — Fraud indicator in pattern of misstatements
(1, 'Misstatements and Control Deficiencies', 'During the audit of Prescott Industries, the auditor discovers that over the past two years, all revenue-related misstatements consistently overstated revenue by amounts just below the clearly trivial threshold. Each involves manual journal entries posted by the same senior accountant near quarter-end. Under AU-C 240 and AU-C 450, evaluate the auditor''s best course of action.', '["Conclude that no further action is needed because each individual entry is below the clearly trivial threshold", "Increase the sample size for revenue testing by 10% to improve confidence in the revenue balance", "Treat the pattern as a fraud risk indicator, expand procedures to investigate the accountant''s journal entries, and discuss the matter with the engagement partner and those charged with governance", "Reclassify all the misstatements as projected misstatements and extrapolate them to the full revenue population"]'::jsonb, 2, 'Under AU-C 240.35-.37 and AU-C 450.A3, a systematic pattern of misstatements that consistently overstate revenue through manual entries by the same individual is a strong fraud risk indicator. The auditor must evaluate the implications, expand procedures, communicate with the partner, and consider communication with governance. Choice A is incorrect because even individually trivial misstatements, when forming a deliberate pattern, are not clearly trivial in the aggregate and indicate potential fraudulent intent requiring investigation.', 'hard', 4)
;

COMMIT;
