-- Migration: Question generation — AUD batch 22 (30 questions)
-- Date: 2026-02-23
-- Topic: Misstatements and Control Deficiencies
-- Difficulty: 9E / 15M / 6H
-- Bloom's: L1:8 / L2:9 / L3:8 / L4:5

BEGIN;

INSERT INTO questions (section_id, topic, stem, choices, correct_index, explanation, difficulty, cognitive_level)
VALUES

-- Q1: hard / L3 — Iron curtain vs rollover approach for prior-period misstatements
(1, 'Misstatements and Control Deficiencies', 'During the audit of Redstone Manufacturing for fiscal year 2025, the engagement team identifies $45,000 in uncorrected prior-period misstatements still affecting the current-year balance sheet, alongside $30,000 in current-year misstatements. Overall materiality is $100,000. When evaluating the aggregate effect on the current-year financial statements, the auditor should:', '["Consider both the iron curtain approach and the rollover approach to determine whether the financial statements are materially misstated", "Apply only the rollover approach since the misstatements originated in different periods", "Evaluate only the current-year misstatements since prior-period amounts were previously assessed", "Use the iron curtain approach exclusively because it captures the total ending balance sheet effect"]'::jsonb, 0, 'Under AU-C 450.A16, the auditor should consider both the iron curtain and rollover approaches when evaluating uncorrected misstatements. The iron curtain approach quantifies misstatement as the total amount in the ending balance ($75,000), while the rollover approach focuses on the current-year originating amount ($30,000). Using only the rollover approach is incorrect because it ignores the cumulative balance sheet effect that could be material to users.', 'hard', 3),

-- Q2: hard / L4 — Evaluating combined deficiencies across multiple processes
(1, 'Misstatements and Control Deficiencies', 'Granite Peak Hospital''s audit reveals three individually insignificant control deficiencies: (1) lack of supervisory review over manual journal entries, (2) inadequate access controls to the general ledger system, and (3) no reconciliation of subsidiary ledgers to the general ledger. Each deficiency alone has a low likelihood of causing material misstatement. The auditor should evaluate whether:', '["Each deficiency should be reported separately as a significant deficiency based on the nature of the accounts affected", "The three deficiencies should be combined only if they affect the same financial statement assertion", "The deficiencies cannot constitute a material weakness because no actual misstatement has been identified", "The combination of these related deficiencies could constitute a significant deficiency or material weakness"]'::jsonb, 3, 'Under AU-C 265.A12, the auditor must consider whether individual control deficiencies that are not themselves significant deficiencies may, in combination, represent a significant deficiency or material weakness. These three deficiencies all relate to financial reporting controls and together create a reasonable possibility of material misstatement. The incorrect view that no actual misstatement must exist ignores that deficiency severity is based on potential, not just actual, misstatement.', 'hard', 4),

-- Q3: easy / L1 — Definition of clearly trivial threshold
(1, 'Misstatements and Control Deficiencies', 'What is the "clearly trivial" threshold used by auditors when accumulating identified misstatements?', '["The amount below which misstatements must still be individually evaluated for qualitative significance", "The amount below which misstatements need not be accumulated because they are inconsequential", "The amount equal to one-half of overall materiality established for the audit", "The amount above which misstatements must be communicated to those charged with governance"]'::jsonb, 1, 'Under AU-C 450.05, the auditor accumulates misstatements identified during the audit other than those that are clearly trivial. Clearly trivial means amounts so small they would not be consequential whether individually or in aggregate. This threshold is not defined as a fixed percentage of materiality — choice C incorrectly equates it to half of materiality, whereas clearly trivial is substantially smaller than materiality.', 'easy', 1),

-- Q4: medium / L2 — Deficiency in design vs deficiency in operation
(1, 'Misstatements and Control Deficiencies', 'During the audit of Cascade Electronics, the auditor finds that management designed a three-way match procedure for purchase orders, receiving reports, and vendor invoices before approving payment. However, the accounts payable clerk has been bypassing the receiving report match for the past six months due to time constraints. This situation best illustrates:', '["A deficiency in the design of internal control because the three-way match is inherently inadequate", "A material weakness because the control was completely ineffective for six months", "A deficiency in the operation of internal control because the properly designed control is not operating as intended", "A significant deficiency that requires immediate correction before the audit can continue"]'::jsonb, 2, 'Under AU-C 265.07, a deficiency in operation exists when a properly designed control does not operate as designed or when the person performing the control lacks the authority or competence. Here, the three-way match was properly designed but not executed as intended. A deficiency in design would mean the control, even if operating as designed, would not prevent or detect misstatements — which is not the case here.', 'medium', 2),

-- Q5: hard / L4 — Qualitative factors making immaterial misstatement significant
(1, 'Misstatements and Control Deficiencies', 'During the audit of Pinnacle Financial Group, the auditor identifies a $12,000 uncorrected misstatement in executive bonus accruals. Materiality is $500,000. However, the misstatement resulted from intentional manipulation by the CFO to meet a personal compensation target. Under AU-C 450, the auditor should:', '["Evaluate the misstatement considering qualitative factors, including the involvement of senior management and possible fraud implications, regardless of the quantitative immateriality", "Waive further investigation because the misstatement is clearly trivial relative to the $500,000 materiality threshold", "Project the misstatement across all executive compensation accounts before deciding on further action", "Document the misstatement as immaterial and include it in the summary of uncorrected misstatements without further analysis"]'::jsonb, 0, 'Under AU-C 450.11 and .A18, the auditor evaluates uncorrected misstatements considering both quantitative and qualitative factors. Misstatements involving fraud or management override carry heightened qualitative significance regardless of dollar amount. Simply treating the misstatement as trivial based on size alone is incorrect because intentional manipulation by senior management indicates a fraud risk requiring further evaluation under AU-C 240.', 'hard', 4),

-- Q6: easy / L1 — Definition of an uncorrected misstatement
(1, 'Misstatements and Control Deficiencies', 'What is an "uncorrected misstatement" as defined in auditing standards?', '["A misstatement that the auditor has identified during the audit and that has not been corrected by management", "A misstatement that was identified during the prior-year audit but corrected in the current year", "A misstatement that the auditor has projected from a sample to the entire population", "An error in the financial statements that has been identified but not yet reported to regulators"]'::jsonb, 0, 'Under AU-C 450.06, uncorrected misstatements are misstatements that the auditor has identified during the current audit and that management has not corrected. The auditor accumulates these and evaluates their aggregate effect. Choice C describes projected misstatements, which are a type of misstatement but not the definition of uncorrected — a projected misstatement becomes uncorrected only if management chooses not to adjust for it.', 'easy', 1),

-- Q7: medium / L2 — Identifying a projected misstatement in inventory sampling
(1, 'Misstatements and Control Deficiencies', 'While auditing Birchwood Furniture Company, the auditor selects a statistical sample of 60 inventory items from a population of 3,000 items valued at $2.4 million. The sample reveals pricing errors totaling $6,000 in sample items valued at $48,000. The auditor should:', '["Report only the $6,000 factual misstatement found in the sample as the total inventory misstatement", "Project the $6,000 sample error to the population, resulting in a projected misstatement of $300,000 for the inventory account", "Expand the sample size until all pricing errors in the population are identified", "Disregard the errors because $6,000 is likely below the clearly trivial threshold"]'::jsonb, 1, 'Under AU-C 450.05-.06, when misstatements are identified in a sample, the auditor projects them to the population. The error rate is $6,000/$48,000 = 12.5%, applied to the $2.4 million population yields a projected misstatement of $300,000. Simply reporting the $6,000 sample error as the total misstatement is incorrect because it fails to account for the likely errors in the untested population, which is the purpose of projection.', 'medium', 2),

-- Q8: medium / L3 — IT general control weakness as potential material weakness
(1, 'Misstatements and Control Deficiencies', 'During the audit of Meridian Data Systems, the auditor discovers that the company''s IT administrator has unrestricted access to both the production database and the application that generates financial reports, with no logging or monitoring of changes. This IT general control deficiency is most likely to be classified as a material weakness because:', '["The deficiency affects only IT controls and does not directly impact financial reporting assertions", "Any IT-related finding must be reported as a material weakness under auditing standards", "The lack of access controls and monitoring creates a reasonable possibility that unauthorized changes to financial data could occur without detection", "The IT administrator is a member of senior management with fiduciary responsibilities"]'::jsonb, 2, 'Under AU-C 265.A7, a material weakness exists when there is a reasonable possibility that a material misstatement will not be prevented or detected on a timely basis. Unrestricted database access without monitoring allows unauthorized modifications to financial data, creating a reasonable possibility of undetected material misstatement. Choice A is incorrect because IT general controls directly underpin the reliability of financially significant applications and reports.', 'medium', 3),

-- Q9: hard / L4 — Aggregate uncorrected misstatements affecting trend analysis
(1, 'Misstatements and Control Deficiencies', 'Atlas Corporation has $80,000 in uncorrected misstatements that individually and in aggregate are below the $150,000 materiality threshold. However, correcting these misstatements would change reported net income from a 2% increase to a 1% decrease compared to the prior year, reversing the earnings trend. Under AU-C 450, the auditor should:', '["Issue a qualified opinion because the misstatements exceed performance materiality even though they are below overall materiality", "Accept the misstatements without further action because the aggregate amount is below overall materiality", "Reduce the materiality threshold retroactively to capture the qualitative effect of these misstatements", "Request management to correct the misstatements given their qualitative significance in reversing the reported earnings trend, and if management refuses, evaluate the effect on the auditor''s report"]'::jsonb, 3, 'Under AU-C 450.11 and .A18-.A19, the auditor considers qualitative factors when evaluating uncorrected misstatements, including whether misstatements affect trends or earnings direction. A trend reversal is qualitatively significant. The auditor should request correction and, if refused, consider the implications for the audit opinion. Simply accepting misstatements below materiality without qualitative analysis violates AU-C 450''s requirement to consider the circumstances of the misstatements.', 'hard', 4),

-- Q10: medium / L2 — Classifying a misstatement type
(1, 'Misstatements and Control Deficiencies', 'During the audit of Sterling Automotive, the auditor identifies that management estimated the warranty reserve at $200,000 based on a 3% claim rate. The auditor''s independent analysis, using the same historical data but a more appropriate statistical model, indicates the reserve should be $275,000. Under AU-C 450, this $75,000 difference is best classified as a:', '["Factual misstatement because the auditor''s calculation uses the same underlying data", "Projected misstatement because the difference results from extrapolation of sample data", "Clearly trivial amount if the $75,000 is below overall materiality for the engagement", "Judgmental misstatement arising from a difference in management''s and the auditor''s judgment about an accounting estimate"]'::jsonb, 3, 'Under AU-C 450.A3, judgmental misstatements arise from differences in judgments about accounting estimates that the auditor considers unreasonable or from the selection or application of accounting policies the auditor considers inappropriate. Here, the difference stems from differing judgment about the appropriate statistical model, not from verifiable factual errors or sample projection. Choice A is incorrect because factual misstatements involve amounts that are not in doubt.', 'medium', 2),

-- Q11: easy / L1 — Auditor documentation requirements for misstatements
(1, 'Misstatements and Control Deficiencies', 'What must the auditor document regarding misstatements identified during an audit?', '["Only misstatements that exceed overall materiality and require adjustment by management", "The amount below which misstatements are regarded as clearly trivial, all misstatements accumulated, and whether they have been corrected", "A list of all misstatements communicated to regulatory authorities during the audit", "Only those misstatements that management has agreed to correct in the financial statements"]'::jsonb, 1, 'Under AU-C 450.14, the auditor must document the clearly trivial threshold, all misstatements accumulated during the audit, and whether uncorrected misstatements have been corrected. This documentation requirement applies regardless of whether misstatements are above or below materiality. Choice A is incorrect because the auditor must accumulate and document all misstatements above the clearly trivial threshold, not just those exceeding overall materiality.', 'easy', 1),

-- Q12: medium / L3 — Prudent official test for control deficiency severity
(1, 'Misstatements and Control Deficiencies', 'Lakewood Community Bank''s audit reveals that loan officers can approve credit extensions up to $500,000 without secondary review. The bank processes approximately $80 million in new loans annually. The auditor applies the "prudent official" test to evaluate severity. Under AU-C 265, this test asks whether:', '["A reasonable investor would change their investment decision based solely on the existence of this deficiency", "The deficiency has already resulted in a material misstatement that was detected by other controls", "A prudent official in a similar position would conclude the deficiency is important enough to merit the attention of those charged with governance", "The deficiency would be identified as a finding in a regulatory examination of the bank"]'::jsonb, 2, 'Under AU-C 265.A13, the auditor evaluates whether a prudent official would consider the deficiency important enough to merit the attention of those charged with governance. This standard focuses on the significance of the deficiency to oversight responsibilities, not on whether a misstatement has actually occurred. Choice B is incorrect because the prudent official test evaluates potential impact and governance significance, not whether an actual misstatement was detected.', 'medium', 3),

-- Q13: medium / L2 — Communication timeline for control deficiencies
(1, 'Misstatements and Control Deficiencies', 'During the interim fieldwork at Oakmont Industries in September 2025, the auditor identifies a significant deficiency in the payroll process. The audit report date is expected to be March 2026. Under AU-C 265, when must the auditor communicate this significant deficiency in writing to those charged with governance?', '["Within 30 days of identifying the significant deficiency during interim fieldwork", "Immediately upon detection, before continuing any further audit procedures", "Verbally during the interim fieldwork, with no written communication required until the next annual audit", "No later than 60 days following the audit report date"]'::jsonb, 3, 'Under AU-C 265.13, the auditor must communicate significant deficiencies and material weaknesses in writing to those charged with governance no later than 60 days following the audit report date. While the auditor may choose to communicate earlier, the standard sets the deadline relative to the report date. Choice A is incorrect because no 30-day interim communication deadline exists in the standard.', 'medium', 2),

-- Q14: easy / L1 — Definition of a control deficiency
(1, 'Misstatements and Control Deficiencies', 'What is a control deficiency in the context of a financial statement audit?', '["A condition in which the design or operation of a control does not allow management or employees to prevent or detect misstatements on a timely basis", "A situation where management intentionally overrides established internal controls to commit fraud", "A weakness identified only through substantive testing of account balances during fieldwork", "A finding reported exclusively by internal auditors during their annual control assessment"]'::jsonb, 0, 'Under AU-C 265.07, a control deficiency exists when the design or operation of a control does not allow management or employees, in the normal course of performing their assigned functions, to prevent or detect misstatements on a timely basis. Choice B describes management override, which is a fraud risk factor rather than the definition of a control deficiency. A deficiency can exist in either design or operation of a control.', 'easy', 1),

-- Q15: medium / L3 — Impact of accounting staff turnover on control environment
(1, 'Misstatements and Control Deficiencies', 'Crestfield Energy experienced 80% turnover in its accounting department during 2025, with most replacements having limited industry experience. The auditor notes several month-end close errors and delayed reconciliations. Under AU-C 265, the auditor should evaluate this situation as:', '["A potential significant deficiency or material weakness because the lack of competent personnel affects the entity''s ability to prevent or detect misstatements", "An inherent limitation of internal control that does not constitute a reportable deficiency", "A human resources issue outside the scope of the auditor''s control deficiency assessment", "A business risk that affects only the efficiency, not the effectiveness, of internal controls"]'::jsonb, 0, 'Under AU-C 265.A5, a deficiency in design exists when qualified personnel are not available to perform controls as designed. High turnover combined with inexperienced replacements and resulting errors indicates the control environment cannot reliably prevent or detect misstatements. Choice B is incorrect because while inherent limitations exist, inadequate staffing competence is a specific, reportable control deficiency rather than an inherent limitation of internal control.', 'medium', 3),

-- Q16: medium / L3 — Inadequate segregation of duties classification
(1, 'Misstatements and Control Deficiencies', 'During the audit of Northbrook Medical Supplies, the auditor discovers that the accounts payable manager can create new vendors, approve invoices, and authorize payments without independent review. The company processes $12 million in disbursements annually and has no detective controls monitoring vendor master file changes. The auditor should classify this as:', '["An efficiency concern that does not rise to the level of a reportable control deficiency", "A significant deficiency or material weakness because the lack of segregation creates a reasonable possibility of material misstatement without prevention or detection", "A deficiency in operation only because the company chose not to segregate duties", "A finding that requires reporting only if a misstatement has actually occurred in vendor payments"]'::jsonb, 1, 'Under AU-C 265.A8, inadequate segregation of duties is an indicator of a material weakness, particularly when one individual can initiate, authorize, and record transactions without independent oversight. The absence of compensating detective controls compounds the severity. Choice D is incorrect because control deficiency evaluation is based on the potential for misstatement, not whether an actual misstatement has occurred.', 'medium', 3),

-- Q17: medium / L3 — Misstatement effect on debt covenant compliance
(1, 'Misstatements and Control Deficiencies', 'Harborview Shipping has a debt covenant requiring a current ratio of at least 1.5:1. Before considering uncorrected misstatements, the ratio is 1.55:1. The auditor has accumulated $35,000 in uncorrected misstatements that would reduce current assets, bringing the ratio to 1.48:1. Overall materiality is $200,000. The auditor should:', '["Accept the misstatements because they are well below overall materiality and the covenant effect is not relevant to financial statement fairness", "Require an explanatory paragraph in the audit report disclosing the potential covenant violation", "Request that management correct the misstatements given their qualitative significance in causing a debt covenant violation, and evaluate the effect on the audit report if not corrected", "Withdraw from the engagement because the financial statements cannot be presented fairly"]'::jsonb, 2, 'Under AU-C 450.A18, the auditor considers qualitative factors including whether a misstatement affects compliance with debt covenants. Even though $35,000 is below the $200,000 materiality, the covenant breach is qualitatively significant to financial statement users. Choice A is incorrect because quantitative immateriality does not override qualitative significance when misstatements cause contractual violations that affect user decisions.', 'medium', 3),

-- Q18: easy / L1 — Purpose of summary of uncorrected misstatements
(1, 'Misstatements and Control Deficiencies', 'What is the primary purpose of the auditor''s summary of uncorrected misstatements?', '["To serve as the basis for calculating the audit fee based on the number of errors found", "To identify which accounting staff members were responsible for the errors", "To provide those charged with governance with information needed to evaluate the effect of uncorrected misstatements on the financial statements", "To document the auditor''s compliance with peer review quality control standards"]'::jsonb, 2, 'Under AU-C 450.12, the auditor communicates uncorrected misstatements to those charged with governance and requests that they be corrected. The summary enables governance to evaluate whether the aggregate effect of uncorrected misstatements is material to the financial statements. Choice A is incorrect because the summary of uncorrected misstatements serves a financial reporting quality purpose, not a fee calculation function.', 'easy', 1),

-- Q19: easy / L1 — Pervasive misstatement definition
(1, 'Misstatements and Control Deficiencies', 'What does "pervasive" mean when describing the effect of a misstatement on the financial statements?', '["The misstatement exceeds overall materiality by more than 50 percent", "The misstatement was caused by intentional fraud rather than unintentional error", "The misstatement is confined to a single account balance but exceeds performance materiality", "The misstatement affects multiple elements, accounts, or disclosures, or represents a substantial proportion of the financial statements"]'::jsonb, 3, 'Under AU-C 705.06, effects are pervasive when they are not confined to specific elements or accounts, represent a substantial proportion of the financial statements, or are fundamental to users'' understanding of the financial statements. Pervasiveness relates to the breadth of the misstatement''s impact. Choice A is incorrect because pervasiveness is about the spread of the effect across the financial statements, not simply the magnitude relative to materiality.', 'easy', 1),

-- Q20: medium / L2 — Management adjusts some but not all misstatements
(1, 'Misstatements and Control Deficiencies', 'During the audit of Clearwater Technologies, the auditor identified $180,000 in total misstatements. Management corrected $130,000 but declined to correct the remaining $50,000, citing immateriality. Overall materiality is $100,000. Under AU-C 450, the auditor should:', '["Issue a qualified opinion because the original total of $180,000 exceeded materiality regardless of subsequent corrections", "Reassess the risk of material misstatement at the financial statement level based on the nature of the remaining uncorrected items", "Accept management''s position without further action since $50,000 is below overall materiality", "Evaluate whether the remaining $50,000 in uncorrected misstatements, individually or aggregated with other uncorrected amounts, is material to the financial statements"]'::jsonb, 3, 'Under AU-C 450.11, the auditor evaluates whether uncorrected misstatements are material individually or in aggregate. After management''s corrections, the auditor considers only the remaining $50,000 plus any other uncorrected amounts. Choice C is incorrect because even though $50,000 is below materiality, the auditor must still evaluate qualitative factors and consider the aggregate effect with any prior-period uncorrected misstatements before concluding.', 'medium', 2),

-- Q21: easy / L1 — Who establishes the clearly trivial threshold
(1, 'Misstatements and Control Deficiencies', 'Who is responsible for establishing the amount below which misstatements are considered clearly trivial?', '["Management of the entity being audited, as part of their internal control framework", "The auditor, based on professional judgment and the circumstances of the engagement", "The audit committee or those charged with governance of the entity", "The applicable financial reporting framework, which specifies exact thresholds"]'::jsonb, 1, 'Under AU-C 450.05 and .A2, the auditor establishes the clearly trivial threshold using professional judgment. This amount is set so that any misstatements below it would not be consequential to the financial statements whether individually or in aggregate. Choice A is incorrect because the clearly trivial threshold is an auditing concept determined by the auditor, not a management or entity-level determination.', 'easy', 1),

-- Q22: hard / L4 — Prior-year material weakness remediated — effect on current audit
(1, 'Misstatements and Control Deficiencies', 'During the prior-year audit of Westfield Industries, the auditor identified a material weakness in revenue recognition that led to a $2 million restatement. Management implemented new controls during the current year, including automated cutoff procedures and independent review of significant contracts. In the current-year audit, the auditor finds no misstatements in revenue. The auditor should:', '["Report the material weakness again in the current year because it caused a restatement in the prior period", "Test the design and operating effectiveness of the new controls before concluding whether the prior-year material weakness has been remediated", "Conclude that the material weakness is remediated based solely on the absence of current-year revenue misstatements", "Omit any reference to the prior-year material weakness because it is no longer relevant to the current engagement"]'::jsonb, 1, 'Under AU-C 265.A15, the auditor evaluates whether previously reported deficiencies have been remediated by testing the design and operating effectiveness of new or modified controls. The absence of misstatements alone is insufficient evidence of remediation because the controls must demonstrate sustained effectiveness. Choice C is incorrect because a lack of detected misstatements could result from the nature of testing rather than effective controls.', 'hard', 4),

-- Q23: easy / L2 — Identifying a deficiency in operation (scenario)
(1, 'Misstatements and Control Deficiencies', 'Valley Creek Distributors requires that all credit memos over $5,000 be approved by the sales director. The auditor discovers that the sales director approved 48 of 50 credit memos tested but did not document the basis for approval on any of them. This situation best illustrates:', '["A material weakness because all credit memos lacked adequate documentation", "A deficiency in design because the approval threshold of $5,000 is set too high", "A factual misstatement in the accounts receivable balance", "A deficiency in operation because the control is being performed but not with the rigor required for it to function effectively"]'::jsonb, 3, 'Under AU-C 265.07, a deficiency in operation exists when a properly designed control does not operate effectively. The approval control was designed appropriately (requiring director approval over $5,000) but is operating without adequate documentation of the review basis. Choice B is incorrect because the design — requiring senior approval for significant credit memos — is reasonable; the issue is in execution quality, not control design.', 'easy', 2),

-- Q24: medium / L2 — Misstatement discovered near materiality after adjustments
(1, 'Misstatements and Control Deficiencies', 'During the audit of Ridgeline Construction, materiality is set at $250,000. After management corrects several identified misstatements, remaining uncorrected misstatements total $210,000. The auditor also identifies $25,000 in likely misstatements from sampling that have not been corrected. Under AU-C 450, the auditor should:', '["Require management to correct all remaining misstatements because the aggregate amount exceeds materiality", "Consider the aggregate of $235,000 in uncorrected misstatements, including projected amounts, in determining whether the financial statements are materially misstated", "Report only the $210,000 in known misstatements since projected misstatements are estimates", "Issue an adverse opinion because uncorrected misstatements approach materiality"]'::jsonb, 1, 'Under AU-C 450.11, the auditor evaluates all uncorrected misstatements — including factual, judgmental, and projected misstatements — in aggregate. The total $235,000 approaches the $250,000 materiality threshold, warranting serious consideration of whether the financial statements are materially misstated. Choice C is incorrect because projected misstatements must be included in the aggregate evaluation, not excluded simply because they are estimates.', 'medium', 2),

-- Q25: medium / L3 — Revenue recognition control deficiency evaluation
(1, 'Misstatements and Control Deficiencies', 'Blue Ridge Software records $45 million in annual revenue, primarily from multi-element arrangements requiring significant judgment. The auditor discovers that the company lacks a formal policy for allocating transaction prices to performance obligations, with each sales manager applying different methods. Under AU-C 265, the auditor should evaluate this as:', '["A business strategy decision that falls outside the scope of internal control evaluation", "An acceptable practice if the financial statements are not materially misstated", "A deficiency in the design of internal control over revenue recognition that likely constitutes at least a significant deficiency", "A misstatement in the financial statements rather than a control deficiency"]'::jsonb, 2, 'Under AU-C 265.07-.08, a deficiency in design exists when a necessary control is missing or not properly designed. The absence of a consistent revenue allocation policy for complex arrangements means the control environment cannot reliably prevent or detect revenue misstatements. Given the significance of revenue and the judgment involved, this likely constitutes at least a significant deficiency. Choice B is incorrect because control deficiency severity is evaluated on potential impact, not solely on whether a misstatement has occurred.', 'medium', 3),

-- Q26: easy / L1 — Definition of tolerable misstatement
(1, 'Misstatements and Control Deficiencies', 'What is "tolerable misstatement" in the context of audit sampling?', '["The maximum misstatement in a population that the auditor is willing to accept and still conclude the audit objective is achieved", "The total amount of all misstatements identified during the audit that management has agreed to correct", "The threshold above which the auditor must issue a qualified opinion on the financial statements", "The amount of misstatement that those charged with governance have authorized management to leave uncorrected"]'::jsonb, 0, 'Under AU-C 530.05, tolerable misstatement is the application of performance materiality to a particular sampling procedure. It represents the maximum misstatement in a population that the auditor can accept while still concluding the sample supports the audit objective. Choice D is incorrect because tolerable misstatement is an auditing concept set by the auditor for sampling purposes, not an amount authorized by governance.', 'easy', 1),

-- Q27: medium / L2 — Reassessing risk after finding control deficiency
(1, 'Misstatements and Control Deficiencies', 'During the audit of Summit Aerospace, the auditor initially assessed the risk of material misstatement for inventory as low based on strong internal controls. However, during control testing, the auditor discovers that the perpetual inventory system has not been reconciled to physical counts for nine months. Under AU-C 315, the auditor should:', '["Revise the risk assessment for inventory to reflect the identified control deficiency and modify the nature, timing, or extent of further audit procedures", "Complete the planned substantive procedures without modification since the risk assessment was made at planning", "Document the control deficiency but maintain the original risk assessment if no misstatements have been found in inventory", "Issue an interim communication to management about the deficiency and suspend inventory testing until it is corrected"]'::jsonb, 0, 'Under AU-C 315.31 and AU-C 330.A62, when the auditor identifies that controls are not operating effectively, the risk assessment should be revised. The nine-month gap in reconciliations undermines the basis for the initial low-risk assessment. Choice B is incorrect because the auditor must revise risk assessments whenever new information contradicts the original assessment, which directly affects the planned audit response.', 'medium', 2),

-- Q28: medium / L3 — Compensating control partially mitigating primary deficiency
(1, 'Misstatements and Control Deficiencies', 'Thornton Retail''s purchasing department lacks segregation of duties — the same employee creates purchase orders and receives goods. However, the accounting department independently reconciles receiving reports to purchase orders and vendor invoices monthly. The auditor should evaluate the compensating control by determining whether it:', '["Fully eliminates the need to report the segregation of duties deficiency because any misstatement would eventually be detected", "Reduces the severity of the primary deficiency based on the compensating control''s effectiveness in detecting misstatements on a timely basis", "Is irrelevant because segregation of duties deficiencies must always be reported as material weaknesses", "Compensates only if it was specifically designed by management to address the segregation of duties weakness"]'::jsonb, 1, 'Under AU-C 265.A11, compensating controls may reduce the severity of a control deficiency but do not necessarily eliminate it. The auditor evaluates whether the compensating control operates effectively and detects misstatements on a timely basis. Choice A is incorrect because a detective control operating monthly may not detect misstatements timely enough to fully mitigate the preventive control gap, meaning the deficiency may still warrant reporting.', 'medium', 3),

-- Q29: hard / L4 — Interaction between fraud risk and control deficiencies
(1, 'Misstatements and Control Deficiencies', 'During the audit of Pacific Marine Industries, the auditor identifies a significant deficiency in journal entry controls: any accounting staff member can post entries without approval. Simultaneously, the auditor notes that management is under intense pressure to meet analyst earnings forecasts and that the CFO''s bonus is tied to reported EBITDA. Under AU-C 240 and AU-C 265, the auditor should evaluate whether:', '["The journal entry deficiency should be downgraded to a control deficiency because no actual fraudulent entries have been identified", "The significant deficiency automatically becomes a material weakness whenever fraud risk factors are present", "The combination of the control deficiency and fraud risk factors elevates the severity of the deficiency and warrants expanded testing of journal entries for evidence of management override", "The fraud risk factors should be evaluated independently from the control deficiency assessment"]'::jsonb, 2, 'Under AU-C 240.32 and AU-C 265.A9, the auditor considers fraud risk factors when evaluating control deficiency severity. The combination of weak journal entry controls with management incentive and opportunity increases the reasonable possibility of material misstatement through management override. Choice D is incorrect because AU-C 265.A9 explicitly requires considering fraud risk factors in evaluating whether a deficiency is a significant deficiency or material weakness.', 'hard', 4),

-- Q30: medium / L2 — Misstatement indicating possible fraud
(1, 'Misstatements and Control Deficiencies', 'While testing disbursements at Cedar Grove Manufacturing, the auditor discovers three payments totaling $18,000 to a vendor whose address matches the home address of the purchasing manager. Overall materiality is $400,000. Under AU-C 240, the auditor''s primary responsibility upon discovering this misstatement is to:', '["Evaluate the implications of the misstatement in relation to other aspects of the audit, particularly management representations and the reliability of audit evidence", "Report the finding directly to law enforcement before discussing it with management", "Treat it as a routine factual misstatement and add it to the summary of uncorrected misstatements", "Dismiss the finding as immaterial since $18,000 is well below the $400,000 materiality threshold"]'::jsonb, 0, 'Under AU-C 240.35-.36, when the auditor identifies a misstatement that may result from fraud, the auditor evaluates its implications for other aspects of the audit regardless of materiality. This includes reconsidering the reliability of audit evidence and management representations. Choice D is incorrect because fraud considerations are not limited by quantitative materiality — even small amounts can indicate systemic issues requiring further investigation.', 'medium', 2)
;

COMMIT;
