-- Migration: Question generation — AUD batch 47 (30 questions)
-- Date: 2026-02-23
-- Topic: Misstatements and Control Deficiencies
-- Difficulty: 9E / 15M / 6H
-- Bloom's: L1:8 / L2:9 / L3:8 / L4:5

BEGIN;

INSERT INTO questions (section_id, topic, stem, choices, correct_index, explanation, difficulty, cognitive_level)
VALUES

-- Q1: medium / L3 — Fraud-related misstatement implications for audit response
(1, 'Misstatements and Control Deficiencies', 'During the audit of Greenfield Technologies, the auditor discovers a $12,000 inventory overstatement that appears to result from intentional manipulation of physical count records by a warehouse supervisor. Under AU-C 240, how does identifying this misstatement as potentially fraud-related most likely affect the auditor''s response?', '["The auditor should reconsider the risk assessment and evaluate whether additional procedures are needed beyond those addressing the specific misstatement", "The auditor should limit additional procedures to the inventory account where the misstatement was identified", "The auditor should immediately withdraw from the engagement and report the matter to law enforcement", "The auditor should reclassify the misstatement as a projected misstatement and extrapolate it to the full inventory population"]'::jsonb, 0, 'Under AU-C 240.35-.36, when a misstatement may result from fraud, the auditor must consider the broader implications, including whether the risk assessment remains appropriate and whether additional procedures are needed in other areas. A fraud-related misstatement may indicate a more pervasive problem beyond the specific account tested. Choice B is incorrect because the auditor''s response is not limited to the affected account, since fraud suggests a systemic issue that could affect multiple areas of the financial statements.', 'medium', 3),

-- Q2: medium / L2 — Calculate aggregate effect of uncorrected misstatements on pretax income
(1, 'Misstatements and Control Deficiencies', 'While auditing Ridgecrest Construction, the auditor accumulates the following uncorrected misstatements: an $8,500 overstatement of revenue, a $3,000 understatement of depreciation expense, and a $2,000 overstatement of accrued liabilities. Overall materiality is $20,000. What is the net aggregate effect of these uncorrected misstatements on pretax income?', '["$7,500 overstatement", "$9,500 overstatement", "$13,500 overstatement", "$9,500 understatement"]'::jsonb, 1, 'Under AU-C 450.05, the auditor accumulates identified misstatements during the audit. The revenue overstatement ($8,500) overstates income, the depreciation understatement ($3,000) understates expense and thus overstates income, and the accrued liabilities overstatement ($2,000) overstates expense and understates income. The net effect is $8,500 + $3,000 - $2,000 = $9,500 overstatement. Choice C incorrectly adds all three amounts without considering that the accrued liabilities overstatement reduces rather than increases pretax income.', 'medium', 2),

-- Q3: medium / L2 — Applying clearly trivial threshold to accumulate misstatements
(1, 'Misstatements and Control Deficiencies', 'Atlas Mining Corporation''s auditor sets overall materiality at $50,000 and the clearly trivial threshold at $2,500. During testing, the auditor identifies misstatements of $1,800, $3,200, $900, and $4,100. Under AU-C 450, which misstatements must the auditor accumulate on the summary of audit differences?', '["All four misstatements because they may aggregate to a material amount", "Only the $4,100 misstatement because it exceeds performance materiality", "The $3,200 and $4,100 misstatements, as they exceed the clearly trivial threshold", "Only misstatements that individually exceed $25,000, which is half of materiality"]'::jsonb, 2, 'Under AU-C 450.05, the auditor accumulates all identified misstatements except those that are clearly trivial. At a clearly trivial threshold of $2,500, the $900 and $1,800 misstatements fall below this amount and need not be accumulated. The $3,200 and $4,100 exceed the threshold and must be included on the summary of audit differences. Choice A incorrectly requires accumulation of all misstatements regardless of the clearly trivial threshold established during audit planning.', 'medium', 2),

-- Q4: easy / L1 — Three categories of misstatements under AU-C 450
(1, 'Misstatements and Control Deficiencies', 'Under AU-C 450, misstatements identified during an audit are classified into which three categories?', '["Material, immaterial, and clearly trivial", "Quantitative, qualitative, and pervasive", "Known, likely, and possible", "Factual, judgmental, and projected"]'::jsonb, 3, 'AU-C 450.A2 classifies misstatements into three categories: factual misstatements (errors about which there is no doubt), judgmental misstatements (differences arising from management''s judgments about estimates), and projected misstatements (the auditor''s best estimate of misstatements in populations based on extrapolating from audit samples). Choice C uses terminology from older auditing standards that is no longer the authoritative classification framework under current AU-C guidance.', 'easy', 1),

-- Q5: medium / L3 — Prior-period uncorrected misstatement effect on current year
(1, 'Misstatements and Control Deficiencies', 'During the prior-year audit of Mapleton Industries, the auditor identified a $30,000 revenue cutoff error where revenue from a January 2026 shipment was recorded in December 2025. Management declined to correct the misstatement. What is the most likely effect of this prior-period uncorrected misstatement on the 2026 financial statements?', '["No effect on 2026 because the misstatement was disclosed in the prior-year management representation letter", "A $30,000 overstatement of 2026 revenue because the error carries forward automatically", "A $60,000 misstatement of 2026 revenue because both years are affected simultaneously", "A $30,000 understatement of 2026 revenue because the transaction was already recorded in 2025"]'::jsonb, 3, 'Under AU-C 450.10, the auditor must evaluate the effect of prior-period uncorrected misstatements on the current period. A revenue cutoff error that overstated prior-year revenue by $30,000 causes a corresponding $30,000 understatement of current-year revenue because the sale was already recognized in the wrong period. The misstatement reverses directionally but still impacts the current year''s income statement. Choice A incorrectly assumes that disclosure in a representation letter eliminates the financial statement effect.', 'medium', 3),

-- Q6: medium / L2 — Performance materiality and aggregate risk across accounts
(1, 'Misstatements and Control Deficiencies', 'Beacon Advisory LLC is auditing Sunrise Hospitality Group with overall materiality set at $100,000 and performance materiality at $75,000. During accounts receivable testing, the auditor finds uncorrected misstatements of $68,000 in that account alone. Under AU-C 450, what is the auditor''s most appropriate response?', '["Request that management correct the misstatements because they approach performance materiality and may combine with misstatements in other accounts to exceed overall materiality", "Accept the misstatements because they are below overall materiality of $100,000", "Issue a qualified opinion because the misstatements exceed half of overall materiality", "Expand testing to all remaining accounts before making any determination about the misstatements"]'::jsonb, 0, 'Under AU-C 450.07-.08, the auditor considers whether uncorrected misstatements are material individually or in aggregate. With $68,000 in a single account approaching the $75,000 performance materiality, there is elevated risk that aggregate misstatements across all accounts could exceed overall materiality. The auditor should request correction to reduce this risk. Choice B incorrectly evaluates the misstatement only against overall materiality without considering the aggregate risk when combined with potential misstatements in untested areas.', 'medium', 2),

-- Q7: medium / L3 — Governance oversight deficiency as potential material weakness
(1, 'Misstatements and Control Deficiencies', 'During the audit of Pinnacle Ventures, the auditor discovers that the board of directors has not reviewed quarterly financial reports for the past two quarters, and the audit committee meets only annually rather than quarterly as required by the charter. Under AU-C 265, what is the most likely implication of this finding for the auditor''s control deficiency evaluation?', '["The finding is an operational matter and does not constitute a control deficiency under auditing standards", "The deficiency in governance oversight should be evaluated as a potential material weakness because it affects the entity''s ability to prevent or detect material misstatements on a timely basis", "The deficiency can only be classified as a significant deficiency because governance oversight is not a direct control over financial reporting", "The auditor should defer evaluation until the next audit period to determine whether the oversight lapse is temporary"]'::jsonb, 1, 'Under AU-C 265.A7, a deficiency in the oversight function of those charged with governance is an indicator of a material weakness in internal control. The board''s failure to review financial reports and infrequent audit committee meetings directly impair the entity''s ability to prevent or detect material misstatements. Choice C incorrectly limits the classification to significant deficiency, but AU-C 265 specifically identifies governance oversight failures as potential material weaknesses given their pervasive impact on the control environment.', 'medium', 3),

-- Q8: medium / L3 — IT general control weakness with pervasive implications
(1, 'Misstatements and Control Deficiencies', 'During the audit of Crestwood Financial Corp., the auditor identifies a deficiency in logical access controls over the general ledger system. Multiple users have unrestricted ability to post journal entries without supervisory approval. Under AU-C 265, how should the auditor evaluate the scope of this control deficiency?', '["The deficiency should be evaluated only in relation to the general ledger account balances that were specifically tested", "The deficiency is limited to the journal entry process and does not affect the evaluation of other controls", "The deficiency has pervasive implications because a weakness in IT general controls can undermine the effectiveness of application controls across multiple transaction cycles", "The deficiency is relevant only if unauthorized journal entries were actually posted during the audit period"]'::jsonb, 2, 'Under AU-C 265.A12 and AU-C 315.A67, IT general controls such as logical access controls support the effective functioning of application controls across the entire system. A weakness in access controls over journal entries affects the reliability of controls in all transaction cycles that flow through the general ledger. Choice D incorrectly limits the evaluation to actual misstatements rather than the potential for material misstatement, which is the standard for evaluating severity under AU-C 265.', 'medium', 3),

-- Q9: medium / L2 — Documentation requirements for accumulating misstatements
(1, 'Misstatements and Control Deficiencies', 'While auditing Falcon Distributing, the auditor identifies twelve misstatements ranging from $500 to $8,000. The clearly trivial threshold is $1,000, and overall materiality is $50,000. Under AU-C 450, what documentation is required regarding these misstatements?', '["Only misstatements exceeding performance materiality need to be documented in the working papers", "All twelve misstatements must be documented individually regardless of their size", "Only the aggregate total of all misstatements needs to be documented", "All misstatements above the clearly trivial threshold must be accumulated and documented, along with whether they were corrected"]'::jsonb, 3, 'AU-C 450.12-.14 requires the auditor to accumulate all identified misstatements other than those that are clearly trivial, document the amount below which misstatements are regarded as clearly trivial, and document the nature and effect of uncorrected misstatements along with the conclusion on whether they are material. Choice B is incorrect because misstatements at or below the $1,000 clearly trivial threshold need not be accumulated or individually documented in the working papers.', 'medium', 2),

-- Q10: hard / L4 — Evaluating opinion when aggregate exceeds materiality
(1, 'Misstatements and Control Deficiencies', 'Thornfield & Associates is finalizing the audit of Coastal Marine Services. Overall materiality is $200,000. Aggregate uncorrected misstatements total $215,000, consisting of five individually immaterial items that all overstate net income. Management believes each item is within an acceptable estimation range and declines to make corrections. The auditor has determined the misstatements are not pervasive to the financial statements. What audit opinion should the auditor most likely issue?', '["An unmodified opinion with an emphasis-of-matter paragraph disclosing the uncorrected misstatements", "A qualified opinion because the aggregate uncorrected misstatements are material but not pervasive to the financial statements", "An adverse opinion because management''s refusal to correct misstatements indicates a scope limitation", "An unmodified opinion because the individual misstatements are each immaterial"]'::jsonb, 1, 'Under AU-C 705.08-.09, when uncorrected misstatements are material but not pervasive, the auditor issues a qualified opinion. The $215,000 aggregate exceeds the $200,000 materiality threshold, and all misstatements overstate income in the same direction, precluding a conclusion that they are immaterial in aggregate. Choice D incorrectly focuses on individual immateriality rather than the aggregate effect, which is the appropriate evaluation basis under AU-C 450.11. Choice C mischaracterizes management''s refusal as a scope limitation.', 'hard', 4),

-- Q11: hard / L4 — Timing of material weakness written communication
(1, 'Misstatements and Control Deficiencies', 'On September 15, 2025, during interim fieldwork for the December 31, 2025 audit of Parkview Medical Systems, the auditor identifies a material weakness in the revenue cycle. The audit report is expected to be issued on March 15, 2026. Under AU-C 265, when must the auditor provide the written communication of this material weakness to those charged with governance?', '["Within 30 days of identifying the material weakness, regardless of the audit timeline", "Only after completing the year-end audit to confirm the weakness was not remediated before December 31", "No later than 60 days following the audit report release date, though earlier communication is encouraged when identified during interim work", "Immediately upon identification, with a final written communication issued concurrently with the audit report"]'::jsonb, 2, 'Under AU-C 265.13, the auditor must communicate significant deficiencies and material weaknesses in writing no later than 60 days following the report release date. AU-C 265.A18 notes that timely interim communication may be important to enable management to take corrective action, but the 60-day deadline is the authoritative requirement. Choice A incorrectly imposes a 30-day deadline not specified in the standards, and choice B inappropriately delays all communication until year-end procedures are complete.', 'hard', 4),

-- Q12: easy / L1 — Definition of "clearly trivial"
(1, 'Misstatements and Control Deficiencies', 'Under AU-C 450, the term "clearly trivial" describes misstatements that are:', '["Below 5% of overall materiality by auditing convention", "Less than the tolerable misstatement for any individual account balance", "Immaterial when considered individually but potentially material in aggregate", "Of a size that would clearly be inconsequential, whether taken individually or in aggregate"]'::jsonb, 3, 'AU-C 450.A2 defines clearly trivial as a matter that is clearly inconsequential, whether taken individually or in the aggregate. This is a lower threshold than materiality — a misstatement can be immaterial but not clearly trivial. The auditor must accumulate all misstatements above the clearly trivial threshold. Choice A is incorrect because no fixed percentage is prescribed by auditing standards for determining the clearly trivial threshold; it requires professional judgment.', 'easy', 1),

-- Q13: easy / L1 — Written communication requirement for significant deficiencies
(1, 'Misstatements and Control Deficiencies', 'Under AU-C 265, what form must the auditor''s communication of significant deficiencies and material weaknesses take?', '["Written communication to those charged with governance", "Oral communication during the closing meeting with management", "A separate paragraph included in the auditor''s report on the financial statements", "A formal letter filed with the applicable regulatory body"]'::jsonb, 0, 'AU-C 265.11 explicitly requires that significant deficiencies and material weaknesses be communicated in writing to those charged with governance. Oral communication alone is insufficient for these severity levels, though the auditor may supplement the written communication with oral discussion. Choice B is incorrect because oral communication does not satisfy the AU-C 265 requirement for significant deficiencies and material weaknesses, which must always be documented in writing.', 'easy', 1),

-- Q14: hard / L4 — Evaluating segregation of duties failure as material weakness
(1, 'Misstatements and Control Deficiencies', 'During the audit of Heritage Savings Bank, the auditor discovers that the CFO has sole authority to initiate, approve, and record wire transfers with no independent review or reconciliation. The board of directors was unaware of this arrangement. Despite no actual misstatements being found in wire transfer testing, the auditor is evaluating the severity of this control deficiency. What classification should the auditor most likely assign?', '["A control deficiency that does not rise to significant deficiency because no actual misstatements were identified during testing", "A significant deficiency because the control weakness creates a reasonable possibility of a misstatement that is more than inconsequential but not material", "A material weakness because the absence of segregation of duties in a high-risk area, combined with lack of board awareness, represents a reasonable possibility that a material misstatement would not be prevented or detected on a timely basis", "An operational finding reported to management but not classified as a control deficiency because wire transfers are an operational rather than a financial reporting process"]'::jsonb, 2, 'Under AU-C 265.A8, the severity of a control deficiency depends on the magnitude of potential misstatement and whether a reasonable possibility exists that controls will fail to prevent or detect a material misstatement. The complete absence of segregation of duties over wire transfers combined with governance''s unawareness satisfies the material weakness criteria regardless of actual misstatements found. Choice A incorrectly conditions severity on actual misstatements, but AU-C 265.A5 focuses on potential rather than actual impact.', 'hard', 4),

-- Q15: medium / L3 — Monitoring activities deficiency and cascading severity
(1, 'Misstatements and Control Deficiencies', 'Silverstone Manufacturing''s internal audit function reports directly to the CFO and has not conducted any internal control testing in the current year, despite the internal audit charter requiring quarterly control assessments. Under AU-C 265, what is the most likely effect of this finding on the auditor''s control deficiency evaluation?', '["It has no effect because the external auditor''s procedures substitute for internal audit testing", "It is classified as an operational deficiency rather than a financial reporting control deficiency", "It affects only the auditor''s evaluation of detection risk, not the control environment assessment", "It indicates a deficiency in the monitoring component of internal control that could elevate the severity classification of other identified control deficiencies"]'::jsonb, 3, 'Under AU-C 265.A7 and the COSO framework, the monitoring component ensures that internal controls continue to operate effectively. When internal audit fails to perform required testing and reports to the CFO rather than independently to governance, monitoring is impaired. This deficiency can amplify the severity of other control deficiencies because the entity lacks the mechanism to identify and correct weaknesses. Choice A is incorrect because external audit procedures do not compensate for deficiencies in the entity''s own monitoring activities.', 'medium', 3),

-- Q16: medium / L3 — Projected misstatement calculation from sample results
(1, 'Misstatements and Control Deficiencies', 'Griffin Logistics has 800 freight invoices totaling $2,400,000. The auditor samples 60 invoices totaling $180,000 and identifies overstatement errors of $4,500. Under AU-C 530, what is the projected misstatement for the population, and how should it be treated?', '["$4,500, limited to the errors actually found in the sample with no projection required", "$60,000, which must be included in the aggregate of uncorrected misstatements evaluated under AU-C 450", "$55,500, reflecting projection to only the untested portion of the population", "$2,400,000, because sampling errors indicate the entire population balance is unreliable"]'::jsonb, 1, 'Under AU-C 530.13-.14, the auditor projects misstatements found in the sample to the entire population. The error rate is $4,500 / $180,000 = 2.5%, applied to the $2,400,000 population, yielding a projected misstatement of $60,000. This amount must be accumulated with other misstatements under AU-C 450 to evaluate the aggregate effect on the financial statements. Choice A incorrectly limits the misstatement to the sample errors without projecting to the population, ignoring the fundamental purpose of statistical sampling.', 'medium', 3),

-- Q17: hard / L4 — Recurring unremediated material weakness communication
(1, 'Misstatements and Control Deficiencies', 'During the current-year audit of Northridge Community Hospital, the auditor identifies the same material weakness in payroll processing that was communicated in writing during each of the two prior audits. Management has acknowledged the weakness each year but has not implemented corrective action due to budget constraints. Under AU-C 265, what is the auditor''s most appropriate course of action?', '["The auditor need not communicate the material weakness again because it was already reported in prior years", "The auditor should escalate the communication directly to external regulators since management has repeatedly failed to act", "The auditor should reclassify the material weakness as a significant deficiency after three years without a resulting misstatement", "The auditor must communicate the material weakness in writing again and may reference prior communications, emphasizing that the condition has not been remediated"]'::jsonb, 3, 'Under AU-C 265.14-.15, the auditor is required to communicate material weaknesses in writing each year they exist, even if previously communicated. The standard permits the auditor to refer to prior communications but does not eliminate the annual requirement. Repeated failure to remediate may also affect the auditor''s assessment of the control environment and management integrity. Choice A is incorrect because AU-C 265 explicitly states that previously communicated deficiencies that have not been remediated must be communicated again.', 'hard', 4),

-- Q18: medium / L2 — Communication deadline for significant deficiency found at interim
(1, 'Misstatements and Control Deficiencies', 'Palmer & Reid LLP identifies a significant deficiency in Valley Tech Corporation''s purchasing controls during October 2025 interim fieldwork. The December 31, 2025 audit report is issued on February 28, 2026. Under AU-C 265, by what date must the written communication of this significant deficiency be provided to those charged with governance?', '["October 31, 2025, within 30 days of identification during interim fieldwork", "December 31, 2025, by the client''s fiscal year-end", "April 29, 2026, no later than 60 days following the February 28, 2026 report release date", "February 28, 2026, concurrent with the issuance of the audit report"]'::jsonb, 2, 'AU-C 265.13 requires that written communication of significant deficiencies and material weaknesses be made no later than 60 days following the report release date. With the report released February 28, 2026, the deadline is April 29, 2026. While earlier communication is encouraged when identified during interim work, the authoritative deadline is tied to the report release date. Choice D incorrectly requires simultaneous communication with the audit report, which is not mandated by the standard.', 'medium', 2),

-- Q19: easy / L1 — Purpose of AU-C 450
(1, 'Misstatements and Control Deficiencies', 'What is the primary purpose of AU-C 450, Evaluation of Misstatements Identified During the Audit?', '["To establish requirements for evaluating the effect of identified misstatements on the audit and uncorrected misstatements on the financial statements", "To define materiality thresholds for planning purposes at the beginning of the audit", "To prescribe the auditor''s response to fraud and illegal acts discovered during fieldwork", "To specify documentation requirements for the permanent audit file"]'::jsonb, 0, 'AU-C 450.01-.02 establishes requirements for the auditor to evaluate the effect of identified misstatements on the audit and the effect of uncorrected misstatements on the financial statements as a whole. This includes accumulating misstatements, communicating them to management, and evaluating whether uncorrected misstatements are material. Choice B confuses AU-C 450 with AU-C 320, which addresses materiality in planning and performing an audit.', 'easy', 1),

-- Q20: medium / L2 — Qualitative factors for evaluating quantitatively immaterial misstatement
(1, 'Misstatements and Control Deficiencies', 'During the audit of Meridian Financial Group, the auditor identifies a $15,000 misstatement in executive compensation disclosure. Overall materiality is $500,000. Although the misstatement is quantitatively immaterial, the auditor should evaluate qualitative factors. Under AU-C 450, which qualitative consideration is most relevant to this misstatement?', '["Whether the misstatement was identified through substantive testing or tests of controls", "Whether the misstatement involves an item requiring specific disclosure under securities regulations, such as executive compensation", "Whether the misstatement was communicated to management within 30 days of identification", "Whether the misstatement exceeds the clearly trivial threshold established during planning"]'::jsonb, 1, 'Under AU-C 450.A16, qualitative factors include whether the misstatement affects compliance with regulatory requirements, loan covenants, or relates to items requiring specific disclosure. Executive compensation is a sensitive disclosure area subject to SEC and regulatory scrutiny, making even quantitatively small misstatements qualitatively significant. Choice D addresses the accumulation threshold rather than qualitative evaluation — a misstatement can exceed clearly trivial yet still require separate qualitative assessment.', 'medium', 2),

-- Q21: easy / L2 — Simple scenario: control operating effectively, no deficiency
(1, 'Misstatements and Control Deficiencies', 'Redwood Bakeries has a manual control requiring the accounts payable supervisor to approve all invoices over $5,000 before payment. The auditor''s testing confirms that the supervisor approved all invoices in the sample. Under AU-C 265, what is the classification of this finding?', '["A material weakness requiring written communication to governance", "A significant deficiency requiring written communication to governance", "A control deficiency to be communicated to management in the management letter", "No control deficiency exists because the control is designed appropriately and operating effectively"]'::jsonb, 3, 'Under AU-C 265.06, a control deficiency exists when a control is designed, implemented, or operated in a way that does not allow management or employees to prevent or detect misstatements on a timely basis. Since the supervisor approved all invoices as required, the control is operating as designed with no deficiency to report. Choice C would apply only if the auditor identified a gap in design or operation of the control, which is not present in this scenario.', 'easy', 2),

-- Q22: easy / L1 — Management representation about uncorrected misstatements
(1, 'Misstatements and Control Deficiencies', 'Under AU-C 450, what written representation must the auditor obtain from management regarding uncorrected misstatements?', '["That management believes the effects of uncorrected misstatements are immaterial, individually and in aggregate, to the financial statements as a whole", "That management has corrected all misstatements identified by the auditor during the engagement", "That management will disclose all uncorrected misstatements in the notes to the financial statements", "That management has implemented controls to prevent the same misstatements from recurring"]'::jsonb, 0, 'AU-C 450.14 requires the auditor to obtain a written representation from management that it believes the effects of uncorrected misstatements are immaterial, individually and in the aggregate, to the financial statements as a whole. A summary of such items must be included in or attached to the representation letter. Choice B is incorrect because the standard anticipates that some misstatements may remain uncorrected, and the representation addresses their assessed immateriality rather than their correction.', 'easy', 1),

-- Q23: medium / L2 — Misstatement when estimate falls outside auditor's range
(1, 'Misstatements and Control Deficiencies', 'During the audit of Brookhaven Pharmaceuticals, the auditor determines that a reasonable range for the warranty liability estimate is $280,000 to $340,000. Management recorded the liability at $260,000. Under AU-C 540 and AU-C 450, how should the auditor treat the difference between management''s recorded amount and the auditor''s range?', '["As a projected misstatement requiring extrapolation to the entire warranty liability population", "As a qualitative finding with no quantitative effect on the summary of uncorrected misstatements", "As a reclassification adjustment that does not affect net income or the misstatement evaluation", "As a judgmental misstatement of at least $20,000, representing the difference between management''s recorded amount and the closest reasonable estimate"]'::jsonb, 3, 'Under AU-C 540.18 and AU-C 450.A5, when management''s point estimate falls outside the auditor''s reasonable range, the difference between the recorded amount and the nearest boundary of the range is treated as a misstatement. Since management recorded $260,000 and the low end of the range is $280,000, the minimum misstatement is $20,000. This is a judgmental misstatement arising from a difference in estimates. Choice A incorrectly classifies it as a projected misstatement, which applies to sample-based extrapolations rather than estimate evaluations.', 'medium', 2),

-- Q24: easy / L1 — Communication of deficiencies less severe than significant
(1, 'Misstatements and Control Deficiencies', 'Under AU-C 265, how should the auditor communicate control deficiencies that are not significant deficiencies or material weaknesses?', '["In a written report to those charged with governance within 60 days of the report release date", "To management at an appropriate level of responsibility, either orally or in writing", "No communication is required for deficiencies below the significant deficiency threshold", "In the notes to the audited financial statements as a subsequent event disclosure"]'::jsonb, 1, 'AU-C 265.12 states that the auditor should communicate to management at an appropriate level of responsibility control deficiencies identified during the audit that are of sufficient importance to merit management''s attention. This communication may be oral or written. Choice C is incorrect because the standard does contemplate communication of lesser deficiencies to management, even though written communication to governance is not required for this severity level.', 'easy', 1),

-- Q25: medium / L3 — Management bias in estimates as misstatement indicator
(1, 'Misstatements and Control Deficiencies', 'While auditing Elmwood Properties, the auditor notices that management''s accounting estimates have consistently favored higher reported income over the past three years. Each individual estimate falls within an acceptable range, but all estimates cluster near the upper boundary of their respective ranges. Under AU-C 450, what is the most likely implication of this pattern?', '["The pattern may indicate management bias, and the auditor should evaluate the cumulative effect on whether the financial statements as a whole are materially misstated", "No action is required because each individual estimate falls within an acceptable range", "The auditor should require management to restate all estimates to the midpoint of each range", "The auditor should issue a qualified opinion due to the lack of conservatism in the accounting estimates"]'::jsonb, 0, 'Under AU-C 450.A17, the auditor must consider indicators of possible management bias when evaluating misstatements. A pattern of estimates consistently near the favorable end of acceptable ranges, even if individually reasonable, may collectively indicate bias that causes the financial statements to be materially misstated. Choice B incorrectly focuses on individual reasonableness without considering the cumulative directional effect, which AU-C 450 specifically requires the auditor to evaluate as part of the overall misstatement assessment.', 'medium', 3),

-- Q26: easy / L1 — Definition of control deficiency
(1, 'Misstatements and Control Deficiencies', 'Under AU-C 265, a control deficiency exists when:', '["The auditor identifies a material misstatement in the financial statements during testing", "Management fails to respond to the auditor''s management letter within 30 days of receipt", "A control is designed, implemented, or operated in a manner that does not allow management or employees to prevent or detect and correct misstatements on a timely basis", "The entity''s internal audit function does not test controls over financial reporting annually"]'::jsonb, 2, 'AU-C 265.06 defines a control deficiency as existing when the design or operation of a control does not allow management or employees, in the normal course of performing their functions, to prevent or detect and correct misstatements on a timely basis. This can stem from either a design deficiency or an operating deficiency. Choice A confuses the consequence (misstatement) with the cause (control deficiency) — a misstatement may exist without a control deficiency, and a control deficiency may exist without a resulting misstatement.', 'easy', 1),

-- Q27: easy / L1 — Objective of AU-C 265 communication
(1, 'Misstatements and Control Deficiencies', 'What is the primary objective of communicating control deficiencies under AU-C 265?', '["To inform those charged with governance and management of deficiencies in internal control that are of sufficient importance to merit their attention", "To require management to implement corrective action within a specified timeframe", "To document the auditor''s basis for modifying the audit opinion on the financial statements", "To satisfy regulatory filing requirements for the entity''s annual report"]'::jsonb, 0, 'AU-C 265.03 states that the objective is to communicate appropriately to those charged with governance and management deficiencies in internal control that the auditor has identified during the audit and that are of sufficient importance to merit their respective attention. The standard does not mandate corrective action or establish remediation timelines. Choice B is incorrect because AU-C 265 places the communication responsibility on the auditor but does not impose remediation requirements on management.', 'easy', 1),

-- Q28: hard / L3 — Cascading effect of automated control failure across accounts
(1, 'Misstatements and Control Deficiencies', 'During the audit of Pacific Coast Distributors, the auditor identifies a deficiency in the automated revenue recognition system that incorrectly applies cutoff criteria to transactions near period-end. The same system generates data used for accounts receivable aging, sales commission calculations, and inventory relief entries. Under AU-C 265, how should the auditor analyze the scope of this control deficiency?', '["The auditor should evaluate the deficiency''s potential impact across all accounts and assertions affected by the system, as a single automated control failure can create misstatement risk in revenue, receivables, commissions payable, and inventory simultaneously", "The auditor should evaluate the deficiency only as it relates to revenue recognition, since that is the account where the control operates", "The auditor should treat each affected account as having a separate control deficiency and evaluate their severity independently", "The auditor should limit the evaluation to the accounts where actual misstatements were identified during substantive testing"]'::jsonb, 0, 'Under AU-C 265.A12 and AU-C 315.A67, when evaluating the severity of a control deficiency, the auditor considers the breadth of financial statement accounts and assertions that are or could be affected. An automated system deficiency affecting cutoff in revenue recognition cascades to receivables, commission liabilities, and inventory, creating pervasive risk. Choice B incorrectly isolates the deficiency to one account, failing to recognize that integrated systems propagate errors across multiple transaction cycles and financial statement line items.', 'hard', 3),

-- Q29: medium / L2 — Evaluating misstatement significance at account level vs financial statement level
(1, 'Misstatements and Control Deficiencies', 'Warren & Associates is auditing Lakeview Enterprises. Overall materiality is $120,000. The auditor identifies a $45,000 misstatement in the allowance for doubtful accounts. The allowance balance is $90,000, and total accounts receivable is $3,200,000. Under AU-C 450, how should the auditor evaluate this misstatement?', '["The misstatement is immaterial because it is below the $120,000 overall materiality threshold", "The misstatement is automatically material because it equals 50% of the allowance balance and must result in a qualified opinion", "The misstatement should be evaluated both in relation to the specific account and in aggregate with other misstatements to determine the overall effect on the financial statements", "The misstatement should be evaluated only as a percentage of total accounts receivable, where it represents approximately 1.4%"]'::jsonb, 2, 'Under AU-C 450.11, the auditor evaluates whether uncorrected misstatements are material, individually or in aggregate. While the $45,000 is below overall materiality of $120,000, it represents 50% of the allowance balance and must be considered in the context of both the specific account and the financial statements as a whole when combined with other uncorrected misstatements. Choice A incorrectly evaluates the misstatement in isolation against overall materiality without considering its significance to the specific account or the aggregate effect.', 'medium', 2),

-- Q30: hard / L4 — Evaluating pervasive material weakness and enhanced governance communication
(1, 'Misstatements and Control Deficiencies', 'During the audit of Harborview Marine Technologies, the auditor identifies a material weakness in the financial close process: the company lacks personnel qualified to prepare accurate financial statements in accordance with GAAP. The entity has restated results in two of the past three years, and the current year''s draft financial statements contained 14 adjusting journal entries proposed by the auditor totaling $890,000. Overall materiality is $400,000. The auditor is evaluating the combined implications. What is the auditor''s most appropriate conclusion?', '["Issue an unmodified opinion because management accepted all proposed adjustments and the corrected financial statements are fairly stated", "Consider whether the pervasive nature of the control deficiency, combined with the restatement history, warrants enhanced communication to governance about the systemic risk to financial reporting reliability", "Issue an adverse opinion because the material weakness is so severe that the financial statements cannot be relied upon regardless of audit adjustments", "Withdraw from the engagement because the volume of required adjustments indicates that management lacks integrity"]'::jsonb, 1, 'Under AU-C 265.A8-.A10, when evaluating the severity of control deficiencies, the auditor considers the entity''s ability to prepare reliable financial statements. A pervasive lack of qualified accounting personnel, evidenced by repeated restatements and extensive audit adjustments exceeding materiality, represents a critical governance concern requiring enhanced communication. While the corrected statements may support an unmodified opinion (unlike choice C), the systemic nature of the weakness demands robust communication to governance about remediation urgency. Choice A ignores the auditor''s responsibility to address the underlying control environment.', 'hard', 4)
;

COMMIT;
