-- Migration: Question generation — AUD batch 52 (30 questions)
-- Date: 2026-02-23
-- Topic: Misstatements and Control Deficiencies
-- Difficulty: 9E / 15M / 6H
-- Bloom's: L1:8 / L2:9 / L3:8 / L4:5

BEGIN;

INSERT INTO questions (section_id, topic, stem, choices, correct_index, explanation, difficulty, cognitive_level)
VALUES

-- Q1: medium / L2 — Tolerable misstatement exceeded by projected misstatement
(1, 'Misstatements and Control Deficiencies', 'During the audit of Ridgemont Electronics, the auditor sets tolerable misstatement for inventory at $50,000. After testing a sample of 60 items from 3,000 inventory records, projected misstatements total $62,000. The most appropriate next step is to:', '["Perform additional audit procedures or request that management adjust the inventory balance", "Accept the inventory balance because the projected amount is below planning materiality of $200,000", "Increase tolerable misstatement to $65,000 so the projected amount falls within the threshold", "Issue a qualified opinion based solely on the excess over tolerable misstatement"]'::jsonb, 0, 'AU-C 530.A20 provides that when projected misstatement exceeds tolerable misstatement, the auditor considers expanding the sample, performing alternative procedures, or requesting management adjustment. Comparing projected misstatement only to overall materiality ignores the tolerable misstatement threshold, which already provides a cushion for undetected errors. Increasing tolerable misstatement to accommodate results would defeat its purpose as a pre-determined threshold.', 'medium', 2),

-- Q2: hard / L4 — Qualitative factors in misstatement evaluation involving management incentives
(1, 'Misstatements and Control Deficiencies', 'Pinebrook Medical Corp. has $180,000 in uncorrected misstatements against a $500,000 materiality threshold. However, $95,000 of the uncorrected amount relates to management bonus accruals that directly affect executive compensation. When evaluating whether the financial statements are materially misstated, the auditor should give greatest weight to:', '["The quantitative gap between the aggregate misstatement and materiality", "The nature of the misstatements and whether they indicate potential management bias", "Whether the misstatements were detected through substantive procedures or tests of controls", "The ratio of corrected to uncorrected misstatements found during the audit"]'::jsonb, 1, 'AU-C 450.11 requires the auditor to consider both quantitative and qualitative factors when evaluating uncorrected misstatements. When misstatements affect accounts tied to management incentives, potential bias increases the risk that financial statements are materially misstated regardless of the numerical margin. Focusing solely on the quantitative gap between $180,000 and $500,000 ignores the qualitative dimension that auditing standards emphasize as equally important.', 'hard', 4),

-- Q3: medium / L2 — Likely misstatement from analytical procedures
(1, 'Misstatements and Control Deficiencies', 'During the audit of Coastal Marine Supply, analytical procedures reveal that gross margin dropped from 38% to 29% year-over-year, while industry peers maintained margins near 37%. Management attributes the decline to pricing pressure but provides no supporting documentation. Under AU-C 450, the difference between the expected and recorded amount represents:', '["A factual misstatement requiring immediate correction", "A projected misstatement based on sampling extrapolation", "A likely misstatement from analytical procedures that should be included in the summary of uncorrected misstatements", "An estimate uncertainty that is excluded from misstatement evaluation"]'::jsonb, 2, 'AU-C 450.A4 describes likely misstatements as the auditor''s best estimate of misstatements in populations, including those identified through analytical procedures. Unlike projected misstatements that arise from extrapolating sample results, likely misstatements from analytics compare expected to recorded amounts. Factual misstatements are specific identified errors, not estimates. The auditor should include this difference in the summary of uncorrected misstatements.', 'medium', 2),

-- Q4: medium / L3 — Indicators of management bias across multiple estimates
(1, 'Misstatements and Control Deficiencies', 'While auditing Thornfield Realty, the auditor observes that management consistently selects assumptions at the optimistic end of reasonable ranges for impairment testing, lease classification, and revenue timing. Each individual estimate falls within acceptable bounds. The auditor should conclude that:', '["No further action is needed since each estimate falls within its acceptable range", "The matter should be communicated as a significant deficiency in internal control", "The financial statements contain material misstatement requiring a qualified opinion", "The pattern may indicate management bias, and the cumulative effect should be evaluated as a potential misstatement"]'::jsonb, 3, 'AU-C 540.21 and AU-C 450.A22 require auditors to evaluate whether the cumulative effect of estimates biased toward one end of reasonable ranges indicates management bias. Even when individual estimates are reasonable, a consistent directional pattern may produce aggregate misstatement. This differs from a control deficiency because it relates to management''s judgment rather than a control breakdown. The auditor must consider whether cumulative bias renders statements materially misstated.', 'medium', 3),

-- Q5: medium / L2 — Communication obligation regardless of entity awareness
(1, 'Misstatements and Control Deficiencies', 'During the audit of Granite Peak Construction, the auditor identifies a material weakness in the revenue recognition process. The CFO states the company is already aware of the issue and plans to remediate it next quarter. Under AU-C 265, the auditor should:', '["Communicate the material weakness in writing to those charged with governance regardless of management''s awareness", "Omit the communication since management has acknowledged the deficiency", "Delay the written communication until the remediation is complete to assess effectiveness", "Downgrade the deficiency to a significant deficiency because management has a remediation plan"]'::jsonb, 0, 'AU-C 265.13 requires the auditor to communicate all identified material weaknesses in writing to those charged with governance, regardless of whether the entity is already aware. Management''s knowledge or remediation plans do not relieve the auditor of this obligation. The existence of a remediation plan does not change the current classification; the auditor evaluates the control as it existed during the audit period.', 'medium', 2),

-- Q6: easy / L1 — Clearly trivial misstatement definition
(1, 'Misstatements and Control Deficiencies', 'Under AU-C 450, a clearly trivial misstatement is one that the auditor considers to be:', '["Below the tolerable misstatement threshold for the account balance", "Too small to be material individually or in the aggregate, even after considering qualitative factors", "Less than 5% of the materiality level established for the audit", "Any misstatement that management has already corrected during fieldwork"]'::jsonb, 1, 'AU-C 450.A2 defines clearly trivial as an amount below which misstatements need not be accumulated. It is not simply a fixed percentage of materiality but a threshold considering both size and nature. Unlike tolerable misstatement, which applies to account balances, clearly trivial applies to individual misstatements. Corrected misstatements are tracked separately regardless of their amount.', 'easy', 1),

-- Q7: medium / L3 — IT general control deficiency cascading to application controls
(1, 'Misstatements and Control Deficiencies', 'Greenfield Logistics relies on automated three-way matching to approve vendor payments. The auditor discovers that IT administrators can modify matching tolerances without approval or logging. This IT general control weakness most likely requires the auditor to:', '["Report the finding as an isolated deficiency limited to IT operations", "Rely on manual compensating controls over vendor payments instead", "Evaluate the deficiency''s impact on all application controls dependent on the IT system, potentially affecting multiple financial statement assertions", "Recommend that the entity implement a new ERP system with stronger access controls"]'::jsonb, 2, 'AU-C 315.A137 recognizes that IT general control deficiencies can undermine the reliability of multiple application controls dependent on the affected system. When administrators can modify automated controls without oversight, the auditor cannot rely on those application controls without additional procedures. This differs from an isolated deficiency because the pervasive nature of IT general controls means one weakness can cascade across multiple processes and assertions.', 'medium', 3),

-- Q8: medium / L2 — Management representation letter content regarding uncorrected misstatements
(1, 'Misstatements and Control Deficiencies', 'While completing the audit of Silverton Manufacturing, the auditor prepares the management representation letter. Regarding uncorrected misstatements, management is asked to confirm that:', '["All uncorrected misstatements have been communicated to the audit committee", "The entity''s internal controls are effective in preventing material misstatements", "No fraud-related misstatements were identified during the period", "The effects of uncorrected misstatements are immaterial, individually and in the aggregate, to the financial statements as a whole"]'::jsonb, 3, 'AU-C 450.14 requires the auditor to include a summary of uncorrected misstatements in the representation letter and obtain management''s representation that the effects are immaterial, individually and in the aggregate. This representation specifically addresses the financial statements as a whole. Requiring management to confirm audit committee communication or control effectiveness relates to different representation letter elements under AU-C 580, not AU-C 450.', 'medium', 2),

-- Q9: easy / L1 — Basic definition of a control deficiency
(1, 'Misstatements and Control Deficiencies', 'Under AU-C 265, a control deficiency exists when:', '["The design or operation of a control does not allow management or employees to prevent or detect misstatements on a timely basis", "A material misstatement has actually occurred in the financial statements", "The entity lacks a formal written internal control policy manual", "An employee has committed fraud that bypasses existing controls"]'::jsonb, 0, 'AU-C 265.07 defines a control deficiency as existing when the design or operation of a control does not allow personnel to prevent, or detect and correct, misstatements on a timely basis. A deficiency can exist without any actual misstatement occurring. The absence of a written policy manual is not itself a deficiency if controls function effectively. Fraud through override addresses a different risk than a design or operating deficiency.', 'easy', 1),

-- Q10: medium / L2 — Corrected misstatements and risk reassessment
(1, 'Misstatements and Control Deficiencies', 'During the audit of Pinnacle Distributing, the auditor identifies 15 misstatements in revenue transactions, all of which management corrects. Despite the corrections, these findings most directly require the auditor to:', '["Increase the overall materiality level for the audit", "Reconsider the nature, timing, and extent of audit procedures for revenue", "Remove the corrected misstatements from the summary of audit differences", "Communicate each corrected misstatement to the audit committee as a significant deficiency"]'::jsonb, 1, 'AU-C 450.07 requires the auditor to consider whether corrected misstatements indicate a class of transactions may contain further misstatements. A large number of misstatements in one area suggests the assessed risk of material misstatement may be too low, requiring the auditor to reconsider planned procedures. Corrected misstatements do not automatically constitute significant deficiencies, and increasing materiality would be inappropriate since findings suggest more risk.', 'medium', 2),

-- Q11: hard / L4 — Evaluating deficiency with no actual misstatement but high transaction volume
(1, 'Misstatements and Control Deficiencies', 'Meridian Aerospace''s payroll system lacks automated approval workflows, allowing any HR staff member to process pay rate changes. During testing, the auditor finds no actual payroll misstatements. However, the payroll system processes $40 million annually, and the deficiency has existed for three years. When evaluating severity, the auditor should consider:', '["The deficiency is not reportable because no misstatements resulted from it", "The three-year duration automatically classifies the deficiency as a material weakness", "The magnitude of transactions processed through the deficient control and the reasonable possibility of a material misstatement, despite the absence of identified errors", "Only the current-year testing results, disregarding the deficiency''s duration"]'::jsonb, 2, 'AU-C 265.A13 requires the auditor to evaluate severity based on the magnitude of potential misstatements and the reasonable possibility they could occur, not solely on whether misstatements actually resulted. A control processing $40 million with no approval mechanism creates significant exposure. While duration alone does not classify a deficiency, it is a relevant factor. Ignoring the deficiency because no errors were found confuses actual results with potential risk.', 'hard', 4),

-- Q12: medium / L2 — Timing of written communication of significant deficiencies
(1, 'Misstatements and Control Deficiencies', 'The auditor of Cascadia Health completes fieldwork on March 15, 2026, and issues the audit report on April 1, 2026. Two significant deficiencies were identified during the audit. Under AU-C 265, the written communication of these deficiencies should be made:', '["Within 30 days after the end of the entity''s fiscal year", "Before the auditor issues the audit report", "Concurrently with the audit report on the same date", "No later than 60 days following the release date of the auditor''s report"]'::jsonb, 3, 'AU-C 265.14 requires that written communication of significant deficiencies and material weaknesses be made no later than 60 days following the release date of the auditor''s report. While best practice encourages timely communication, the standard provides this window. The communication is not required before report issuance nor tied to the entity''s fiscal year end. The auditor may communicate earlier but has up to 60 days after the report release.', 'medium', 2),

-- Q13: hard / L4 — Restatement as indicator of material weakness
(1, 'Misstatements and Control Deficiencies', 'Eastwood Industries restates its prior-year financial statements due to a lease accounting error discovered during the current audit. The lease classification error originated from a deficiency in the review process that was not identified in the prior-year audit. The current-year auditor should:', '["Evaluate whether the deficiency that caused the restatement constitutes a material weakness in the current period and communicate accordingly", "Defer to the prior-year auditor''s assessment of internal controls since the error originated in that period", "Report the restatement as a significant deficiency because the current-year controls have since been corrected", "Exclude the deficiency from the current communication because it relates to a prior period"]'::jsonb, 0, 'AU-C 265.A9 indicates that a restatement of previously issued financial statements is a strong indicator of a material weakness. The current-year auditor must evaluate whether the control deficiency persists or has been remediated. Deferring to the prior-year auditor is inappropriate because the current auditor has an independent obligation. Even if controls have improved, the restatement signals that the deficiency should be evaluated and communicated.', 'hard', 4),

-- Q14: easy / L1 — Communication of deficiencies less severe than significant deficiency
(1, 'Misstatements and Control Deficiencies', 'Under AU-C 265, control deficiencies that are less severe than a significant deficiency:', '["Must be communicated in writing to the audit committee", "May be communicated to management but are not required to be communicated in writing to those charged with governance", "Must be included in the auditor''s report on internal controls", "Are required to be documented in the audit workpapers but never communicated to anyone"]'::jsonb, 1, 'AU-C 265.12 states that the auditor may communicate deficiencies less severe than a significant deficiency to management, typically in writing. However, AU-C 265 only requires written communication to those charged with governance for significant deficiencies and material weaknesses. Lesser deficiencies are not required to appear in the audit report. Auditors should still document them in workpapers per AU-C 230 but may choose to communicate them.', 'easy', 1),

-- Q15: easy / L1 — Purpose of accumulating identified misstatements
(1, 'Misstatements and Control Deficiencies', 'The primary reason auditors accumulate identified misstatements during the audit is to:', '["Determine the exact amount of adjusting entries management must record", "Calculate the fee for the audit engagement based on error volume", "Evaluate whether uncorrected misstatements, individually or in aggregate, are material to the financial statements", "Identify which audit team members need additional training"]'::jsonb, 2, 'AU-C 450.05 requires the auditor to accumulate misstatements identified during the audit to enable evaluation of their effect on the financial statements. The aggregation allows the auditor to assess whether uncorrected misstatements cause material misstatement. The purpose is not to prescribe exact adjustments, calculate fees, or evaluate staff performance. The auditor''s professional judgment determines whether the aggregate warrants further action or opinion modification.', 'easy', 1),

-- Q16: medium / L3 — Aggregating multiple deficiencies across processes
(1, 'Misstatements and Control Deficiencies', 'During the audit of Lakeshore Hospitality, the auditor identifies three control deficiencies: (1) no independent review of journal entries over $10,000, (2) the bank reconciliation preparer also approves wire transfers, and (3) general ledger system access is not restricted to authorized personnel. None individually qualifies as a material weakness. The auditor should:', '["Report each deficiency separately as a significant deficiency", "Report only the most severe deficiency to those charged with governance", "Decline to report the deficiencies because none individually is a material weakness", "Evaluate whether the combination represents a material weakness due to their interrelated effect on financial reporting"]'::jsonb, 3, 'AU-C 265.A14 requires the auditor to consider whether multiple deficiencies affecting the same significant account or assertion constitute a significant deficiency or material weakness when combined. These three deficiencies collectively compromise general ledger integrity: unsupervised journal entries, inadequate segregation in cash, and unrestricted system access. Evaluating each in isolation ignores their cumulative impact on preventing material misstatement.', 'medium', 3),

-- Q17: medium / L3 — Pervasive uncorrected misstatements and opinion type
(1, 'Misstatements and Control Deficiencies', 'The auditor of Brookstone Manufacturing identifies $120,000 in uncorrected misstatements spread across revenue, inventory, and accounts payable. Overall materiality is $150,000. The misstatements affect multiple line items and related disclosures throughout the financial statements. If management declines to correct, the most likely opinion modification is:', '["An adverse opinion because the misstatements are both material and pervasive", "A qualified opinion because the aggregate is below materiality", "An unmodified opinion with an emphasis-of-matter paragraph", "A disclaimer of opinion due to scope limitation"]'::jsonb, 0, 'AU-C 705.09 requires an adverse opinion when misstatements are both material and pervasive to the financial statements. At $120,000 against $150,000 materiality, the misstatements are material given their spread across multiple accounts and disclosures. Because they affect numerous line items throughout the statements, they are pervasive. A qualified opinion applies when misstatements are material but not pervasive. A disclaimer applies to scope limitations, not uncorrected misstatements.', 'medium', 3),

-- Q18: easy / L1 — Attachment to the management representation letter
(1, 'Misstatements and Control Deficiencies', 'Under AU-C 450, the auditor is required to include or attach to the management representation letter:', '["A complete list of all internal control deficiencies identified during the audit", "A summary of uncorrected misstatements identified during the audit", "The auditor''s calculation of overall materiality and performance materiality", "A list of all corrected and uncorrected misstatements from both the current and prior audits"]'::jsonb, 1, 'AU-C 450.14 requires the auditor to include or attach a summary of uncorrected misstatements to the written representation letter and request management''s acknowledgment. This does not include corrected misstatements, control deficiency communications, or the auditor''s internal materiality calculations. The purpose is to obtain management''s agreement that the uncorrected items are immaterial to the financial statements taken as a whole.', 'easy', 1),

-- Q19: medium / L2 — Management override misstatement classification
(1, 'Misstatements and Control Deficiencies', 'During the audit of Blackwood Energy, the auditor discovers that the CFO manually overrode the automated revenue cutoff control to record $200,000 in December 2025 revenue for a contract not executed until January 2026. This misstatement is best classified as:', '["A projected misstatement based on analytical procedures", "A judgmental misstatement arising from an accounting estimate", "A factual misstatement resulting from management override that may also indicate a control deficiency", "A likely misstatement that requires extrapolation to the population"]'::jsonb, 2, 'AU-C 450.A3 classifies a factual misstatement as one about which there is no doubt — here, a specific transaction was deliberately recorded in the wrong period. Because the CFO manually overrode an automated control, this also signals a potential control deficiency under AU-C 265. Unlike judgmental misstatements involving estimates or projected misstatements from sampling, this is a known, specific error with intentional characteristics.', 'medium', 2),

-- Q20: medium / L3 — Undocumented informal controls cannot serve as compensating controls
(1, 'Misstatements and Control Deficiencies', 'Whitfield Retail relies on an informal practice where the store manager spot-checks daily cash deposits against POS records. There is no documented policy, no evidence of the reviews, and the manager occasionally skips the check. The auditor discovers a $3,000 cash shortage. When evaluating control deficiency severity, the auditor should conclude that:', '["The informal practice is sufficient because the manager generally performs the review", "The deficiency is not reportable because the $3,000 shortage is below materiality", "The compensating control eliminates the deficiency because some reviews occurred", "An undocumented, inconsistently performed control cannot be relied upon as a compensating control, increasing deficiency severity"]'::jsonb, 3, 'AU-C 265.A11 requires that compensating controls be sufficiently designed and operating effectively to mitigate a deficiency. An informal, undocumented practice performed inconsistently provides no reliable evidence of operation. The actual cash shortage confirms the control gap has real consequences. The severity evaluation considers both the design weakness and the operating failure, not just whether some reviews occurred sporadically.', 'medium', 3),

-- Q21: hard / L4 — Systemic root cause analysis across misstatement types
(1, 'Misstatements and Control Deficiencies', 'Atlas Global Services'' audit reveals factual misstatements in accounts payable ($45,000), a projected misstatement in inventory ($60,000), and a judgmental misstatement in the warranty reserve ($55,000). All three trace to the same newly hired controller who lacks industry experience. Materiality is $200,000. The auditor should:', '["Evaluate the aggregate of $160,000 against materiality and assess whether the common root cause indicates a material weakness in personnel competency", "Evaluate each misstatement type separately because factual, projected, and judgmental misstatements cannot be combined", "Ignore the projected misstatement because it is merely an estimate and focus on the $100,000 factual and judgmental total", "Issue a qualified opinion because the total exceeds 50% of materiality"]'::jsonb, 0, 'AU-C 450.11 requires the auditor to aggregate all categories of uncorrected misstatements — factual, projected, and judgmental — when evaluating their effect on the financial statements. A common root cause strengthens the case for a material weakness under AU-C 265 because it indicates a systemic rather than isolated problem. The $160,000 aggregate approaches materiality, and the qualitative factor of a single-source cause heightens concern beyond quantitative analysis alone.', 'hard', 4),

-- Q22: easy / L1 — Two factors determining control deficiency severity
(1, 'Misstatements and Control Deficiencies', 'Under AU-C 265, the severity of a control deficiency depends on:', '["The dollar amount of misstatements found and the number of transactions tested", "The magnitude of potential misstatement and the likelihood that existing controls would fail to prevent or detect it", "Whether the deficiency was identified by the auditor or by management", "The number of employees affected by the control and the frequency of the control activity"]'::jsonb, 1, 'AU-C 265.A8 states that severity depends on the magnitude of the potential misstatement resulting from the deficiency and the reasonable possibility that existing controls would fail to prevent, or detect and correct, a misstatement. The analysis considers potential rather than actual misstatement amounts. Who discovered the deficiency is irrelevant to severity, and headcount or control frequency are only indirect factors in the likelihood assessment.', 'easy', 1),

-- Q23: hard / L3 — Dual-purpose test yielding both control and substantive findings
(1, 'Misstatements and Control Deficiencies', 'During a dual-purpose test of Redwood Pharmaceuticals'' purchase authorization process, the auditor finds that 8 of 40 purchase orders over $25,000 lack required VP approval. Three of the unapproved purchases contain pricing errors totaling $18,000. The auditor should:', '["Report only the pricing errors as misstatements and disregard the approval exceptions", "Classify all 8 unapproved purchases as misstatements regardless of whether they contain errors", "Evaluate the 8 approval failures as a control deficiency and separately assess the $18,000 in pricing errors as misstatements, projecting to the population", "Treat the findings as a single significant deficiency without separating misstatements from control exceptions"]'::jsonb, 2, 'AU-C 330.A34 recognizes that dual-purpose tests yield both compliance and substantive evidence. The 8 missing approvals represent control operating exceptions evaluated under AU-C 265 for deficiency severity. The $18,000 in pricing errors are factual misstatements subject to projection under AU-C 530. Combining them into a single finding obscures the distinct implications: control deficiency affects reliance, while misstatements affect the financial statement evaluation.', 'hard', 3),

-- Q24: easy / L1 — Documentation requirements under AU-C 450
(1, 'Misstatements and Control Deficiencies', 'Under AU-C 450, the auditor is required to document:', '["Only uncorrected misstatements that individually exceed materiality", "The entity''s internal process for identifying and correcting misstatements", "A comparison of identified misstatements against industry benchmarks", "The clearly trivial threshold, all accumulated misstatements, and the conclusion on whether uncorrected misstatements are material"]'::jsonb, 3, 'AU-C 450.15 requires the auditor to document the clearly trivial threshold, all misstatements accumulated during the audit and whether they were corrected, and the conclusion about whether uncorrected misstatements are material. Documentation limited to items exceeding materiality would miss the aggregation requirement. Industry benchmarks and the entity''s internal processes are not specified documentation requirements under AU-C 450.', 'easy', 1),

-- Q25: medium / L3 — Segregation of duties with partial detective compensating controls
(1, 'Misstatements and Control Deficiencies', 'Brighton Automotive''s accounts payable clerk both enters vendor invoices and prints checks. However, the controller reviews a daily exception report of all payments exceeding $5,000 and reconciles the bank statement monthly. When evaluating deficiency severity, the auditor should:', '["Consider whether the controller''s detective controls operate effectively enough to reduce severity while recognizing that payments under $5,000 remain unmonitored", "Classify the segregation issue as a material weakness regardless of compensating controls", "Determine that no deficiency exists because the controller''s review fully compensates for the segregation weakness", "Ignore the segregation issue because it is common in organizations of this size"]'::jsonb, 0, 'AU-C 265.A12 provides that compensating controls may reduce deficiency severity but do not necessarily eliminate it. The controller''s detective review covers only transactions above $5,000, leaving smaller payments unmonitored. The auditor must evaluate whether compensating controls are sufficient in design and operation. Automatically classifying any segregation issue as a material weakness or dismissing it due to entity size ignores the required assessment of compensating control effectiveness.', 'medium', 3),

-- Q26: medium / L2 — Effect of misstatement direction on aggregation
(1, 'Misstatements and Control Deficiencies', 'During the audit of Oakmont Services, the auditor identifies uncorrected misstatements: revenue overstated by $40,000, inventory understated by $25,000, and prepaid expenses overstated by $15,000. When aggregating these misstatements, the auditor should consider:', '["Only the overstatement items because they inflate net income", "The net effect on the financial statements while also evaluating each misstatement individually for its separate significance", "Each misstatement separately with no consideration of any offsetting effect", "Only the largest single misstatement of $40,000"]'::jsonb, 1, 'AU-C 450.A16 requires the auditor to consider both the net effect and individual misstatements when evaluating aggregate impact. Misstatements in opposite directions may partially offset on certain line items, but each must also be evaluated for individual significance. Considering only overstatements or the largest single item ignores the comprehensive evaluation required. The auditor uses professional judgment to assess both gross and net effects on affected accounts.', 'medium', 2),

-- Q27: easy / L2 — Factual misstatement found through sampling
(1, 'Misstatements and Control Deficiencies', 'During testing at Clearwater Retail, the auditor physically counts 200 inventory items from a population of 10,000 and finds that one item valued at $500 was actually worth $350. This $150 difference is classified as:', '["A projected misstatement because the auditor used sampling to select the item", "A likely misstatement from analytical procedures comparing expected to recorded values", "A factual misstatement for the specific item, which the auditor will then use as a basis for projecting to the population", "A judgmental misstatement because it involves inventory valuation estimates"]'::jsonb, 2, 'AU-C 450.A3 distinguishes factual misstatements as those about which there is no doubt. The $150 pricing error on a specific identified item is a factual misstatement. When found through sampling, the auditor also projects the error to the population under AU-C 530, but the projected amount is a separate calculation. The $150 itself remains factual. Judgmental misstatements relate to estimates, and analytical procedures were not the detection method here.', 'easy', 2),

-- Q28: hard / L4 — Material weakness evaluation with mid-year remediation
(1, 'Misstatements and Control Deficiencies', 'Evergreen Financial discovered a material weakness in its loan loss reserve process in July 2025 and implemented new controls effective October 1, 2025. The auditor tests the new controls for Q4 and finds them operating effectively. For the December 31, 2025 audit, the auditor should report:', '["No material weakness because the remediated controls were effective for the final quarter", "A significant deficiency rather than a material weakness since partial remediation occurred", "The material weakness as fully remediated with no further communication needed", "A material weakness because the deficient controls were in place for a significant portion of the year, despite effective Q4 remediation"]'::jsonb, 3, 'AU-C 265.A17 requires the auditor to evaluate controls as they existed throughout the period under audit. Although new controls operated effectively for Q4, the material weakness existed during Q1 through Q3. Financial statements cover the full year, and deficient controls could have allowed material misstatement during the nine months they were in place. The auditor should communicate the material weakness and may note the remediation, but partial-year effectiveness does not eliminate the classification.', 'hard', 4),

-- Q29: easy / L1 — Three categories of misstatements under AU-C 450
(1, 'Misstatements and Control Deficiencies', 'Under AU-C 450, misstatements identified during an audit are classified into which three categories?', '["Factual misstatements, judgmental misstatements, and projected misstatements", "Material misstatements, immaterial misstatements, and clearly trivial misstatements", "Corrected misstatements, uncorrected misstatements, and passed adjustments", "Quantitative misstatements, qualitative misstatements, and disclosure misstatements"]'::jsonb, 0, 'AU-C 450.A3 defines three categories: factual misstatements (no doubt about the error), judgmental misstatements (arising from management''s estimates or policies the auditor considers unreasonable), and projected misstatements (the auditor''s best estimate of error in a population based on sampling). The other options describe classification schemes not established by AU-C 450 for categorizing the nature of identified misstatements.', 'easy', 1),

-- Q30: medium / L3 — Going concern implications from aggregated uncorrected misstatements
(1, 'Misstatements and Control Deficiencies', 'Valley Creek Enterprises has $280,000 in uncorrected misstatements, primarily understated liabilities, against materiality of $300,000. The entity''s debt covenants require a current ratio above 1.5, and correcting the misstatements would reduce the current ratio from 1.6 to 1.3. The auditor should:', '["Accept the financial statements because the aggregate is below materiality", "Consider the covenant violation as a qualitative factor that increases the significance of the uncorrected misstatements and evaluate potential going concern implications", "Require management to correct only enough misstatements to maintain the covenant ratio", "Issue an unmodified opinion because the quantitative threshold was not breached"]'::jsonb, 1, 'AU-C 450.11 requires evaluating both quantitative and qualitative aspects of uncorrected misstatements. Even though $280,000 falls below $300,000 materiality, the impact on debt covenants introduces a qualitative dimension: a covenant breach could trigger loan acceleration and threaten going concern under AU-C 570. The auditor cannot ignore these downstream consequences merely because the misstatements are quantitatively below the materiality threshold.', 'medium', 3)
;

COMMIT;
