-- Migration: Question generation — AUD batch 51 (30 questions)
-- Date: 2026-02-23
-- Topic: Misstatements and Control Deficiencies
-- Difficulty: 9E / 15M / 6H
-- Bloom's: L1:8 / L2:9 / L3:8 / L4:5

BEGIN;

INSERT INTO questions (section_id, topic, stem, choices, correct_index, explanation, difficulty, cognitive_level)
VALUES

-- Q1: easy / L1 — Clearly trivial misstatement threshold
(1, 'Misstatements and Control Deficiencies', 'Under AU-C 450, what term describes misstatements that the auditor need not accumulate during the audit?', '["Clearly trivial misstatements", "Immaterial misstatements", "De minimis misstatements", "Inconsequential misstatements"]'::jsonb, 0, 'AU-C 450.05 states the auditor should accumulate all misstatements identified during the audit other than those that are clearly trivial. "Clearly trivial" means amounts well below materiality that have no consequence individually or in aggregate. Unlike "immaterial," which still requires accumulation for aggregate assessment, clearly trivial items need not be tracked at all.', 'easy', 1),

-- Q2: medium / L2 — Iron curtain vs rollover approach
(1, 'Misstatements and Control Deficiencies', 'During the audit of Pinnacle Electronics, the auditor finds $30,000 in uncorrected misstatements from the prior year that reversed in the current year, plus $25,000 in new current-year misstatements. Under the rollover approach for evaluating uncorrected misstatements, the auditor would assess the current-year income statement effect as:', '["$55,000, combining both years'' misstatements", "$25,000, considering only the current-year originating amount", "$30,000, focusing on the prior-year carryforward balance", "$5,000, netting the reversal against the new misstatement"]'::jsonb, 1, 'AU-C 450.A18 discusses both the rollover and iron curtain approaches. The rollover method evaluates only the current-year effect of misstatements on the income statement—here, $25,000 in new misstatements. Unlike the iron curtain approach, which would consider the cumulative $55,000 balance sheet effect, the rollover method isolates the current period''s originating amount.', 'medium', 2),

-- Q3: medium / L3 — Control deficiency affecting multiple account balances
(1, 'Misstatements and Control Deficiencies', 'While auditing Redstone Manufacturing, the engagement team discovers that the accounts payable clerk has authority to create vendors, approve invoices, and process payments with no supervisory review. This single deficiency affects three account balances. Under AU-C 265, the auditor should evaluate the severity of this deficiency by considering:', '["Only the largest individual account balance affected", "Each account balance in isolation, reporting three separate deficiencies", "The maximum potential misstatement across all affected account balances combined", "The average misstatement risk across the three account balances"]'::jsonb, 2, 'AU-C 265.A9 requires the auditor to consider the magnitude of the potential misstatement resulting from the deficiency. When a single deficiency—such as inadequate segregation of duties—affects multiple accounts, the auditor evaluates the combined maximum potential misstatement. Rather than evaluating each balance in isolation, which would understate the true severity, the auditor must aggregate the exposure across all affected accounts.', 'medium', 3),

-- Q4: medium / L2 — Design deficiency vs operating effectiveness deficiency
(1, 'Misstatements and Control Deficiencies', 'During the audit of Cascade Financial Group, the auditor notes that the company has a policy requiring dual authorization for wire transfers over $10,000, but the banking software does not enforce this limit and allows single-user processing. This situation represents:', '["An operating effectiveness deficiency because the control is not functioning", "A monitoring deficiency because management has not detected the gap", "A compensating control failure because manual review should catch errors", "A design deficiency because the control cannot meet its objective even if operated as intended"]'::jsonb, 3, 'AU-C 265.A1 distinguishes between design and operating effectiveness deficiencies. A design deficiency exists when a control is missing or improperly designed such that it cannot prevent or detect misstatements even when operating as intended. Unlike an operating deficiency, where a properly designed control is inconsistently executed, this scenario involves a software configuration flaw that prevents the dual-authorization policy from ever functioning.', 'medium', 2),

-- Q5: easy / L1 — Accumulation of identified misstatements
(1, 'Misstatements and Control Deficiencies', 'Under AU-C 450, what is the auditor required to do with all identified misstatements that are not clearly trivial?', '["Accumulate them during the audit", "Report them immediately to those charged with governance", "Require management to correct them before issuing the report", "Disclose them in a footnote to the financial statements"]'::jsonb, 0, 'AU-C 450.05 requires the auditor to accumulate all identified misstatements during the audit, other than those that are clearly trivial. This accumulation enables the auditor to later evaluate whether uncorrected misstatements are material individually or in aggregate. However, immediate reporting to governance is required only for material weaknesses, not for every accumulated misstatement.', 'easy', 1),

-- Q6: medium / L3 — Reassessing risk upon discovering material weakness
(1, 'Misstatements and Control Deficiencies', 'During substantive testing at Birchwood Consulting, the auditor discovers a material weakness in the revenue recognition process that was not identified during the risk assessment phase. Under AU-C 265 and AU-C 315, the auditor''s most appropriate response is to:', '["Document the weakness and proceed with planned substantive procedures", "Withdraw from the engagement due to unreliable internal controls", "Issue a qualified opinion based solely on the material weakness", "Reassess the risks of material misstatement and revise the audit plan accordingly"]'::jsonb, 3, 'AU-C 315.32 requires the auditor to revise the risk assessment when audit evidence contradicts the initial assessment. Discovery of a previously unidentified material weakness per AU-C 265 indicates the initial risk assessment was incomplete. Rather than simply documenting the weakness and proceeding with planned procedures, the auditor must reassess risks and design additional procedures to address the revised assessment.', 'medium', 3),

-- Q7: medium / L2 — Timing of written communication of control deficiencies
(1, 'Misstatements and Control Deficiencies', 'After completing the December 31, 2025 audit of Lakewood Industries, the auditor identifies two significant deficiencies and one material weakness. Under AU-C 265, the written communication of these control deficiencies to those charged with governance must be made:', '["Before releasing the audit report", "No later than 60 days after the report release date", "Within 30 days of completing fieldwork", "At the next scheduled audit committee meeting"]'::jsonb, 1, 'AU-C 265.13 requires the auditor to communicate significant deficiencies and material weaknesses in writing to those charged with governance no later than 60 days following the report release date. Rather than requiring communication before the report release, the standard allows this timeline so the auditor can finalize the evaluation after report issuance.', 'medium', 2),

-- Q8: medium / L3 — Magnitude vs likelihood in deficiency evaluation
(1, 'Misstatements and Control Deficiencies', 'The auditor of Summit Ridge Bank identifies a control deficiency in the loan approval process. The maximum potential misstatement from the deficiency is $2 million, but the likelihood of occurrence is low because a compensating detective control catches most errors. Materiality is $500,000. Under AU-C 265, the auditor should classify this deficiency by evaluating:', '["Only the actual misstatements detected during the audit period", "Only the maximum potential dollar amount that could result from the deficiency", "Both the magnitude of the potential misstatement and the likelihood that the deficiency could result in a misstatement", "The historical frequency of misstatements in similar loan portfolios"]'::jsonb, 2, 'AU-C 265.A8 requires evaluating the severity of a control deficiency based on both the magnitude of the potential misstatement and the likelihood that the deficiency could result in misstatements. Although the $2 million potential exceeds materiality, the low likelihood due to compensating controls affects the classification. Considering only magnitude or only actual errors detected would be an incomplete assessment.', 'medium', 3),

-- Q9: easy / L1 — Definition of a deficiency in internal control
(1, 'Misstatements and Control Deficiencies', 'Under AU-C 265, a deficiency in internal control exists when:', '["The financial statements contain a known material misstatement", "Management refuses to implement the auditor''s recommendations", "An internal audit department is not established by the entity", "A control does not allow timely prevention or detection of misstatements"]'::jsonb, 3, 'AU-C 265.07 defines a deficiency in internal control as existing when the design or operation of a control does not allow management or employees to prevent, or detect and correct, misstatements on a timely basis. Rather than requiring an actual misstatement to have occurred, the deficiency relates to the control''s capability itself. Not having an internal audit department does not automatically constitute a deficiency.', 'easy', 1),

-- Q10: hard / L3 — Aggregation of component misstatements in group audits
(1, 'Misstatements and Control Deficiencies', 'Granite Holdings has five subsidiaries audited by different component auditors. The group engagement team receives summaries showing uncorrected misstatements of $40,000, $35,000, $28,000, $22,000, and $18,000 from each component respectively. Group materiality is $200,000 and component materiality ranges from $50,000 to $80,000. Under AU-C 600 and AU-C 450, the group engagement team should:', '["Aggregate all component misstatements and evaluate them against group materiality", "Evaluate each component''s misstatements only against its own component materiality", "Disregard component misstatements below individual component materiality thresholds", "Request each component auditor to independently assess the group-level effect"]'::jsonb, 0, 'AU-C 600.44 and AU-C 450.06 require the group engagement team to aggregate uncorrected misstatements from all components and evaluate them against group materiality. The combined $143,000 approaches the $200,000 group threshold. Unlike evaluating misstatements only at the component level, aggregation at the group level captures how individually immaterial amounts may become material in combination.', 'hard', 3),

-- Q11: medium / L2 — Restatement as indicator of material weakness
(1, 'Misstatements and Control Deficiencies', 'After filing its 2025 financial statements, Clearwater Technologies discovers an error requiring restatement of previously issued financial statements. The auditor is now evaluating whether this restatement indicates a material weakness. Under AU-C 265, the auditor should consider the restatement:', '["Irrelevant to internal control evaluation because it was voluntarily corrected", "Conclusive evidence of a material weakness without further analysis", "Only relevant if the restatement amount exceeds overall materiality", "A strong indicator of a material weakness that warrants further evaluation of the underlying control failure"]'::jsonb, 3, 'AU-C 265.A13 identifies restatement of previously issued financial statements as a strong indicator of a material weakness. However, the auditor must still evaluate the specific control that failed and the circumstances rather than automatically concluding a material weakness exists. Simply dismissing the restatement because it was voluntarily corrected ignores the underlying control failure that allowed the error.', 'medium', 2),

-- Q12: medium / L3 — Qualitative considerations for misstatement evaluation
(1, 'Misstatements and Control Deficiencies', 'During the audit of Thornton Pharmaceuticals, the auditor identifies a $12,000 uncorrected misstatement that understates a liability related to an ongoing FDA regulatory matter. Overall materiality is $500,000. Under AU-C 450, the auditor should evaluate this misstatement by considering:', '["Only its quantitative effect, since $12,000 is well below materiality", "Whether it affects compliance with debt covenants or regulatory requirements", "Whether management agrees the misstatement is inconsequential", "Only whether it changes the direction of an earnings trend"]'::jsonb, 1, 'AU-C 450.11 requires the auditor to consider both quantitative and qualitative factors when evaluating uncorrected misstatements. Although quantitatively immaterial, a misstatement may be significant if it affects regulatory compliance, debt covenants, management compensation, or masks a change in earnings trends. Focusing solely on the dollar amount rather than also considering qualitative dimensions could lead to an incomplete evaluation.', 'medium', 3),

-- Q13: hard / L4 — Combining deficiencies into a material weakness
(1, 'Misstatements and Control Deficiencies', 'During the audit of Meridian Healthcare, the auditor identifies three control deficiencies: (1) the IT administrator has unlogged access to modify the general ledger database, (2) journal entry approvals are not required for entries under $50,000, and (3) the monthly close checklist does not include a variance analysis of significant accounts. Individually, each is classified as a significant deficiency. Under AU-C 265, the auditor should evaluate whether these three deficiencies together constitute a material weakness by assessing:', '["Whether any single deficiency has historically resulted in a detected misstatement", "Whether management has plans to remediate each deficiency within the next fiscal year", "Whether management has represented in writing that the deficiencies are immaterial", "Whether the combination creates a reasonable possibility that a material misstatement would not be prevented or detected"]'::jsonb, 3, 'AU-C 265.A12 requires the auditor to evaluate whether combinations of significant deficiencies together constitute a material weakness. Unlike evaluating each deficiency in isolation, the combined assessment tests whether the group creates a reasonable possibility of failing to prevent or detect a material misstatement. Here, unlogged IT access plus weak journal entry controls plus absent variance analysis could collectively enable and conceal a material misstatement.', 'hard', 4),

-- Q14: easy / L2 — Identifying a control deficiency from a late reconciliation
(1, 'Misstatements and Control Deficiencies', 'During the audit of Aspen Trail Outfitters, the auditor discovers that the company''s bank reconciliation for October 2025 was not completed until January 2026, three months late. Under AU-C 265, this delay most likely represents:', '["A fraud risk factor requiring expanded substantive testing", "An inherent limitation that does not constitute a deficiency", "A scope limitation preventing the auditor from testing cash", "A deficiency in internal control because the control did not operate on a timely basis"]'::jsonb, 3, 'AU-C 265.07 states that a deficiency exists when a control does not allow management to prevent, or detect and correct, misstatements on a timely basis. A bank reconciliation performed three months late cannot detect errors or irregularities in the cash account promptly. Rather than representing an inherent limitation, this is an operating effectiveness deficiency because the control exists but did not function within its intended timeframe.', 'easy', 2),

-- Q15: medium / L3 — Management override and control deficiency severity
(1, 'Misstatements and Control Deficiencies', 'While auditing Foxworth Energy, the engagement team discovers that the CFO routinely bypasses the three-way matching control for purchases over $100,000, authorizing payments based solely on verbal confirmation. Annual purchases in this category total $8 million. Under AU-C 265, the auditor should evaluate this management override as:', '["A material weakness because management override of controls eliminates their preventive effect", "A deficiency in design because the policy permits executive exceptions", "A significant deficiency mitigated by the CFO''s seniority and knowledge", "An acceptable business practice that does not constitute a control deficiency"]'::jsonb, 0, 'AU-C 265.A7 requires evaluating whether there is a reasonable possibility that a material misstatement could result. Management override of a key control processing $8 million annually eliminates the preventive effect of the three-way match, creating a reasonable possibility of material misstatement. Although the CFO holds a senior position, this does not mitigate the risk—rather than reducing concern, senior personnel override is a primary fraud risk factor under AU-C 240.', 'medium', 3),

-- Q16: medium / L2 — Documentation of misstatement summary
(1, 'Misstatements and Control Deficiencies', 'At the conclusion of the audit of Hawthorne Medical Group, the engagement partner reviews the accumulated misstatement summary before requesting management''s representation letter. Under AU-C 450, the auditor''s documentation of uncorrected misstatements must include:', '["Only misstatements that exceed the planning materiality threshold", "Only misstatements that management has agreed are errors", "A description of all uncorrected misstatements and management''s reasons for not correcting them", "A summary of all misstatements found, including those already corrected by management"]'::jsonb, 2, 'AU-C 450.14-.15 requires the auditor to document all accumulated uncorrected misstatements and the conclusion on whether they are material individually or in aggregate. The auditor must also obtain management''s reasons for not correcting each misstatement. Unlike documentation limited only to items exceeding materiality or only items management agrees are errors, the standard requires a comprehensive record of all uncorrected amounts.', 'medium', 2),

-- Q17: medium / L2 — Known vs likely misstatements from sampling
(1, 'Misstatements and Control Deficiencies', 'During the inventory audit of Beacon Supply Company, the auditor tests 60 items from a population of 3,000 and finds $6,000 in actual pricing errors. The auditor projects the sample results to estimate a total population misstatement of $300,000. Under AU-C 450, the $6,000 represents a known misstatement and the $294,000 difference represents:', '["A factual misstatement that should be corrected immediately", "A likely misstatement arising from projecting the sample error to the population", "An immaterial amount that the auditor should disregard", "A judgmental misstatement based on the auditor''s professional skepticism"]'::jsonb, 1, 'AU-C 450.A4 distinguishes between factual misstatements (specifically identified), projected misstatements (best estimate from projecting sample results), and judgmental misstatements (from differences in estimates). The $6,000 in actual errors is factual, whereas the $294,000 additional projected amount is a likely misstatement derived from extrapolating sample findings to the population. A judgmental misstatement would involve differences in management''s estimates, not sampling projections.', 'medium', 2),

-- Q18: hard / L4 — Fraud and material weakness evaluation
(1, 'Misstatements and Control Deficiencies', 'During the audit of Platinum Ventures, the engagement team discovers that a mid-level accounting manager fabricated $45,000 in fictitious expense reports over 18 months. The fraud was detected only through a tip, not through any internal control. Overall materiality is $1 million. Under AU-C 240 and AU-C 265, the auditor should evaluate this situation by recognizing that:', '["The fraud is immaterial and does not indicate a control deficiency since it was below materiality", "The fraud must be reported to law enforcement before evaluating internal controls", "The amount should be projected to estimate total potential undetected fraud across the organization", "The failure of internal controls to detect the fraud is at least a significant deficiency regardless of the dollar amount"]'::jsonb, 3, 'AU-C 265.A11 and AU-C 240.36 indicate that fraud, even if quantitatively immaterial, is a strong indicator of a control deficiency because it reveals that controls failed to prevent or detect intentional misstatement. Although the $45,000 is below the $1 million materiality threshold, the 18-month duration without detection by any control demonstrates a meaningful gap. Rather than dismissing it based on dollar amount alone, the auditor should evaluate whether this represents a significant deficiency or material weakness.', 'hard', 4),

-- Q19: hard / L4 — IT general control deficiency cascading to application controls
(1, 'Misstatements and Control Deficiencies', 'While auditing Global Logistics Corp, the IT auditor discovers that three programmers have unrestricted production database access with no change management logging. The company relies on 12 automated application controls across revenue, purchasing, and payroll modules for financial reporting. Under AU-C 265 and AU-C 315, the auditor should evaluate this IT general control deficiency by considering:', '["Only the application controls that were actually modified during the audit period", "Only the revenue cycle controls since they carry the highest inherent risk", "Whether the integrity of all dependent automated application controls may be compromised", "Each application control independently without regard to the underlying IT environment"]'::jsonb, 2, 'AU-C 315.A68 establishes that IT general controls support the continued proper functioning of application controls. When ITGCs such as access management and change management fail, the auditor cannot rely on the integrity of any automated controls dependent on that IT environment. Unlike evaluating only controls that were modified or only one cycle, the auditor must assess whether all 12 application controls may be compromised because unauthorized changes could go undetected.', 'hard', 4),

-- Q20: medium / L3 — Evaluating management''s refusal to correct near-material misstatement
(1, 'Misstatements and Control Deficiencies', 'During the audit of Sterling Capital Partners, the auditor identifies an uncorrected misstatement of $180,000 in a depreciation calculation. Overall materiality is $200,000. Management declines to correct the error, arguing it will reverse naturally the following year. Under AU-C 450, the auditor''s primary concern with management''s response should be:', '["Whether the misstatement will actually reverse as management claims", "Whether the $180,000 understates the true error after further investigation", "Whether management''s refusal indicates a possible bias in financial reporting", "Whether the depreciation method complies with GAAP regardless of the dollar amount"]'::jsonb, 2, 'AU-C 450.12 requires the auditor to consider whether uncorrected misstatements indicate a bias in management''s financial reporting. A refusal to correct a $180,000 error when materiality is $200,000 raises concern about management intent, particularly when the justification relies on future reversal rather than current-period accuracy. The auditor must evaluate whether this pattern suggests management is intentionally reporting results that fall just within acceptable thresholds.', 'medium', 3),

-- Q21: easy / L1 — Three categories of misstatements
(1, 'Misstatements and Control Deficiencies', 'What are the three categories of misstatements identified in AU-C 450?', '["Factual, judgmental, and projected", "Material, immaterial, and trivial", "Intentional, unintentional, and systematic", "Quantitative, qualitative, and pervasive"]'::jsonb, 0, 'AU-C 450.A3-.A5 classifies misstatements into three categories: factual misstatements (about which there is no doubt), judgmental misstatements (arising from differences in management''s judgments about estimates), and projected misstatements (the auditor''s best estimate of misstatements in populations based on sample results). Unlike the material/immaterial distinction, which relates to evaluation, these categories describe the nature and source of the misstatement.', 'easy', 1),

-- Q22: easy / L1 — Tolerable misstatement definition
(1, 'Misstatements and Control Deficiencies', 'In the context of audit sampling, tolerable misstatement is best defined as:', '["The total of all misstatements the auditor expects to find during testing", "A monetary amount set by the auditor below which individual misstatements are ignored", "The maximum misstatement in a population that the auditor is willing to accept", "The amount of error that triggers a qualified opinion on the financial statements"]'::jsonb, 2, 'AU-C 530.A3 defines tolerable misstatement as the maximum amount of misstatement in the population that the auditor is willing to accept and still conclude that the audit objective has been achieved. It is set at or below performance materiality for each account. Unlike expected misstatement, which estimates anticipated errors, tolerable misstatement establishes the upper bound of acceptable error.', 'easy', 1),

-- Q23: hard / L4 — Pervasive control environment weakness affecting audit opinion
(1, 'Misstatements and Control Deficiencies', 'During the audit of Whitfield Industries, the auditor identifies a pervasive weakness in the control environment: the CEO dominates all financial decisions, the board lacks independence, and there is no functioning audit committee. Although substantive testing reveals no material misstatements, the auditor must evaluate how this pervasive weakness affects the overall audit approach. Under AU-C 265 and AU-C 700, the auditor should:', '["Issue an adverse opinion due to the pervasive control environment weakness", "Disclaim an opinion because the control weakness prevents obtaining sufficient evidence", "Communicate the material weakness but recognize that an unmodified opinion may still be appropriate if sufficient substantive evidence supports the financial statements", "Withdraw from the engagement because the control environment is too unreliable"]'::jsonb, 2, 'AU-C 265.A14 and AU-C 700.11 establish that a material weakness must be communicated but does not automatically result in a modified opinion. The audit opinion is based on whether sufficient appropriate audit evidence supports the financial statements. However, issuing an adverse opinion requires actual material misstatement rather than solely a control deficiency, so an unmodified opinion may be appropriate if expanded substantive testing provides adequate evidence.', 'hard', 4),

-- Q24: medium / L2 — Written vs oral communication of deficiencies
(1, 'Misstatements and Control Deficiencies', 'During the audit of Ridgeline Software, the auditor identifies several control deficiencies: one material weakness in access controls, two significant deficiencies in the revenue cycle, and four deficiencies that are neither significant deficiencies nor material weaknesses. Under AU-C 265, the auditor is required to communicate in writing:', '["All seven control deficiencies to those charged with governance", "Only the material weakness to those charged with governance", "The material weakness and two significant deficiencies to those charged with governance", "Only deficiencies that resulted in actual misstatements during the audit"]'::jsonb, 2, 'AU-C 265.13 requires the auditor to communicate in writing to those charged with governance all significant deficiencies and material weaknesses identified during the audit. The three items meeting these thresholds—one material weakness and two significant deficiencies—must be communicated in writing. However, the four lesser deficiencies may be communicated orally or in writing at the auditor''s discretion and are not required to be included in the written communication.', 'medium', 2),

-- Q25: easy / L1 — Responsibility for correcting misstatements
(1, 'Misstatements and Control Deficiencies', 'Who bears primary responsibility for correcting misstatements identified during an audit?', '["Management of the entity being audited", "The external auditor performing the engagement", "The audit committee or those charged with governance", "The entity''s internal audit department"]'::jsonb, 0, 'AU-C 450.08 requires the auditor to communicate all accumulated misstatements to management and request correction. However, the responsibility for the financial statements and for correcting misstatements rests with management rather than the auditor. The auditor''s role is to identify and communicate misstatements. Those charged with governance provide oversight but do not bear direct responsibility for correction.', 'easy', 1),

-- Q26: easy / L1 — Purpose of management representation regarding misstatements
(1, 'Misstatements and Control Deficiencies', 'Under AU-C 580, the auditor obtains a written representation from management regarding uncorrected misstatements primarily to:', '["Transfer legal liability for any undetected errors to management", "Confirm that the effects of uncorrected misstatements are immaterial individually and in aggregate", "Document that the auditor informed management of all identified errors", "Ensure the audit committee has reviewed every uncorrected misstatement"]'::jsonb, 1, 'AU-C 580.16 requires the auditor to obtain a written representation from management that the effects of uncorrected misstatements are immaterial, both individually and in the aggregate, to the financial statements as a whole. Rather than transferring liability, this representation confirms management''s assessment. The representation letter supplements the auditor''s own evaluation of materiality, not replaces it.', 'easy', 1),

-- Q27: medium / L2 — Iron curtain approach for cumulative misstatements
(1, 'Misstatements and Control Deficiencies', 'During the audit of Westbrook Holdings, the auditor notes that over the past three years, uncorrected misstatements have accumulated to $450,000 on the balance sheet. Current-year originating misstatements total only $80,000. Overall materiality is $500,000. Under the iron curtain approach described in AU-C 450, the auditor should assess the financial statement impact as:', '["$80,000, since only current-year originating amounts affect the current period", "$450,000, because the cumulative balance sheet effect represents the total misstatement exposure", "$370,000, representing only the prior-year carryforward amounts", "$530,000, adding the balance sheet effect to the current-year income statement effect"]'::jsonb, 1, 'AU-C 450.A18 describes the iron curtain approach as quantifying a misstatement based on the cumulative effect on the current-period balance sheet, regardless of when the misstatements originated. The $450,000 cumulative amount reflects the total balance sheet exposure. Unlike the rollover approach, which would focus on the $80,000 current-year income statement effect, the iron curtain method captures the full accumulated impact.', 'medium', 2),

-- Q28: hard / L4 — Revising risk assessment after discovering material weakness
(1, 'Misstatements and Control Deficiencies', 'Midway through the audit of Cornerstone Investments, the auditor discovers a material weakness in the valuation of complex derivatives—a $40 million portfolio. The initial risk assessment classified derivatives as moderate risk with planned analytical procedures and limited detail testing. Under AU-C 315 and AU-C 330, the auditor''s most appropriate integrated response is to:', '["Complete the planned procedures and add additional analytical procedures for derivatives", "Expand the derivative sample size by 25% while maintaining the original risk assessment", "Document the material weakness, maintain the current procedures, and communicate to governance", "Reclassify derivatives as high risk, design substantive procedures responsive to the revised assessment, and assign more experienced personnel"]'::jsonb, 3, 'AU-C 315.32 and AU-C 330.A1 require the auditor to revise the risk assessment when evidence contradicts the initial evaluation and then design audit procedures responsive to the revised risks. Rather than simply expanding sample size without revising the underlying risk assessment, the auditor must reclassify the risk to high, design substantive procedures addressing specific assertions, and assign qualified personnel per AU-C 330.A17 to address the fundamental change in assessed risk.', 'hard', 4),

-- Q29: easy / L1 — Operating effectiveness deficiency definition
(1, 'Misstatements and Control Deficiencies', 'A deficiency in operating effectiveness of internal control exists when:', '["A necessary control is missing from the entity''s system of internal control", "Management intentionally overrides an established control for personal benefit", "A properly designed control does not operate as intended or is not performed by a qualified person", "The entity has not implemented the auditor''s prior-year recommendations"]'::jsonb, 2, 'AU-C 265.A1 distinguishes between design and operating effectiveness deficiencies. An operating effectiveness deficiency exists when a properly designed control does not operate as designed or when the person performing it lacks competence or authority. Unlike a design deficiency, where the control is missing or improperly structured, an operating deficiency means the control itself is adequate but its execution fails.', 'easy', 1),

-- Q30: medium / L3 — Compensating controls and significant deficiency mitigation
(1, 'Misstatements and Control Deficiencies', 'While auditing Northstar Aerospace, the auditor identifies a significant deficiency: purchase orders over $500,000 do not require a second approval. However, the CFO performs a detailed monthly review of all expenditures over $250,000, comparing them to budgets and investigating variances. Under AU-C 265, the auditor should evaluate whether the compensating control:', '["Automatically reduces the deficiency classification from significant deficiency to a lesser deficiency", "Eliminates the need to communicate the original deficiency to governance", "Operates effectively enough to reduce the likelihood that a material misstatement would go undetected, potentially affecting the severity classification", "Is irrelevant because compensating controls cannot mitigate purchasing process deficiencies"]'::jsonb, 2, 'AU-C 265.A10 requires the auditor to consider compensating controls when evaluating deficiency severity. A functioning detective control—the CFO''s monthly review—may reduce the likelihood that a misstatement resulting from the missing approval would go undetected. However, compensating controls do not automatically reclassify a deficiency; the auditor must evaluate whether they operate effectively enough to change the severity assessment rather than simply assuming mitigation.', 'medium', 3)
;

COMMIT;
