-- Migration: Question generation — REG batch 8 (30 questions)
-- Date: 2026-02-28
-- Topic: Tax-Exempt Organizations
-- Difficulty: 9E / 15M / 6H
-- Bloom's: L1:8 / L2:9 / L3:8 / L4:5

BEGIN;

INSERT INTO questions (section_id, topic, stem, choices, correct_index, explanation, difficulty, cognitive_level)
VALUES

-- Q1: medium / L3 — 501(h) expenditure test election for lobbying
(3, 'Tax-Exempt Organizations', 'Hope Medical Charity, a 501(c)(3) with exempt purpose expenditures of $600,000, elects the Section 501(h) expenditure test. During 2025, the organization spends $95,000 on direct lobbying and $20,000 on grassroots lobbying. How should the charity evaluate its lobbying compliance under the expenditure test?', '["The organization is within its lobbying limits because the nontaxable amount for $600,000 in exempt expenditures allows up to $115,000 in total lobbying", "The organization exceeded its lobbying limits because the $95,000 in direct lobbying alone surpasses the permitted threshold", "The organization loses tax-exempt status immediately because any lobbying over $50,000 is prohibited", "The organization must cease all lobbying because the 501(h) election prohibits grassroots lobbying"]'::jsonb, 0, 'Under IRC Section 501(h), organizations with exempt purpose expenditures of $500,000–$1,000,000 may spend up to 20% of the first $500,000 ($100,000) plus 15% of the excess. For $600,000, the nontaxable amount is $115,000. Total lobbying of $115,000 equals the limit. The grassroots ceiling is 25% of $115,000 ($28,750), and $20,000 is within that. Option B is incorrect because direct lobbying is not independently capped under the expenditure test.', 'medium', 3),

-- Q2: hard / L4 — Supporting organization classification under Section 509(a)(3)
(3, 'Tax-Exempt Organizations', 'Valley Education Support, Inc. was organized as a Section 509(a)(3) Type I supporting organization for Valley Community College, a public charity. The college recently appointed new trustees who removed all college-affiliated directors from Valley Education Support''s board. The organization continues making grants exclusively to the college. Evaluate how this governance change affects the organization''s classification.', '["The organization remains a Type I supporting organization because it continues to fund the college exclusively", "The organization likely loses Type I status because it is no longer operated, supervised, or controlled by the supported public charity and must seek reclassification", "The organization automatically converts to a private foundation after one year without college-affiliated directors", "The organization retains its status because Type I classification depends solely on the destination of grants"]'::jsonb, 1, 'Under IRC Section 509(a)(3), a Type I supporting organization must be "operated, supervised, or controlled by" one or more public charities, requiring the supported organization to appoint a majority of the board. Removing all college-affiliated directors severs this control relationship. Option A is incorrect because Type I status requires governance control, not merely exclusive grant-making to the supported charity.', 'hard', 4),

-- Q3: easy / L1 — Dissolution clause requirement
(3, 'Tax-Exempt Organizations', 'What must an organization''s governing documents provide regarding asset distribution upon dissolution to satisfy the Section 501(c)(3) organizational test?', '["Assets must be distributed to the organization''s founder or largest donor", "Assets must be divided equally among all current members", "Assets must be used to pay debts and the surplus returned to contributors", "Assets must be distributed to another exempt organization or to the government"]'::jsonb, 3, 'Under IRC Section 501(c)(3), the organizational test requires a dissolution clause directing that assets be distributed to another Section 501(c)(3) organization or to a government entity upon dissolution. This prevents private individuals from benefiting when an exempt organization ceases operations. Option A is incorrect because distributing assets to founders would constitute prohibited private inurement.', 'easy', 1),

-- Q4: medium / L3 — Controlled entity payments treated as UBIT
(3, 'Tax-Exempt Organizations', 'Bright Future Foundation, a 501(c)(3), owns 85% of the voting stock of Bright Services Corp. The corporation pays $200,000 in annual rent to the foundation for office space. An independent appraisal values the fair market rent at $150,000. How is the rental payment treated for UBIT purposes?', '["The entire $200,000 is excluded from UBIT as passive rental income from real property", "Only the $150,000 fair market value portion is excluded and the $50,000 excess is subject to UBIT", "The entire $200,000 is subject to UBIT because it is received from a controlled entity", "Only the $50,000 excess over fair market value is subject to UBIT because the foundation controls the subsidiary"]'::jsonb, 3, 'Under IRC Section 512(b)(13), rent received from a controlled entity (80%+ ownership) is included in UBIT only to the extent it exceeds the fair market value of the rented property. Since FMV rent is $150,000, the $50,000 excess is subject to UBIT. Option C is incorrect because the entire amount is not taxable — only the excess over FMV. Option A ignores the controlled entity rules that override the passive income exclusion.', 'medium', 3),

-- Q5: medium / L2 — Personal property rent inclusion in UBIT
(3, 'Tax-Exempt Organizations', 'Metro Arts Council, a 501(c)(3), leases a building to an unrelated tenant. The lease includes both real property and personal property (specialized lighting equipment). Total annual rent is $120,000, of which $8,000 is allocable to the personal property. How is this rental income treated for UBIT purposes?', '["The entire $120,000 is subject to UBIT because the lease includes personal property", "Only the $8,000 allocable to personal property is subject to UBIT", "The entire $120,000 is excluded from UBIT because the personal property rent is incidental at less than 10% of total rent", "The $120,000 is excluded only if the tenant is another exempt organization"]'::jsonb, 2, 'Under IRC Section 512(b)(3), rents from real property are excluded from UBIT. When a lease includes both real and personal property, the personal property portion is excluded if it is incidental — defined as less than 10% of total rent. Here, $8,000/$120,000 = 6.7%, which is under 10%, so the entire rent is excluded. Option B is incorrect because the incidental threshold applies to the total, not as a separate inclusion.', 'medium', 2),

-- Q6: hard / L4 — Public charity one-third support test evaluation
(3, 'Tax-Exempt Organizations', 'Lakewood Community Services received the following support over a four-year period: $400,000 from government grants, $300,000 from small individual donations (no single donor exceeding 2%), $250,000 from a single private foundation, and $50,000 from investment income. Total support is $1,000,000. Evaluate whether Lakewood qualifies as a public charity under the Section 509(a)(1) one-third support test.', '["Lakewood does not qualify because the $250,000 foundation grant must be excluded from the numerator entirely", "Lakewood does not qualify because investment income in the denominator reduces the public support percentage below one-third", "Lakewood qualifies because government grants plus public donations ($700,000) exceed one-third of total support, and the foundation grant exceeding 2% of total support is limited to $20,000 in the numerator", "Lakewood qualifies because all $1,000,000 in support counts toward public support"]'::jsonb, 2, 'Under IRC Section 509(a)(1) and Section 170(b)(1)(A)(vi), public support includes government grants and contributions from the general public, but contributions from any single source exceeding 2% of total support are limited to that 2% amount ($20,000 here). Government grants ($400,000) plus small donations ($300,000) plus $20,000 (2% cap on foundation grant) = $720,000, exceeding one-third ($333,333). Option A incorrectly excludes the entire foundation grant rather than applying the 2% cap.', 'hard', 4),

-- Q7: medium / L2 — Convenience exclusion for hospital cafeteria
(3, 'Tax-Exempt Organizations', 'Regional Medical Center, a 501(c)(3) hospital, operates a cafeteria in the hospital building. The cafeteria serves meals primarily to patients, their families, and hospital staff, though visitors occasionally purchase meals. The cafeteria is staffed by paid employees and generates $180,000 in annual revenue. Is this cafeteria income subject to UBIT?', '["Yes, because the cafeteria is staffed by paid employees rather than volunteers", "Yes, because selling food to visitors makes it an unrelated trade or business", "No, because all hospital revenue is automatically exempt from UBIT", "No, because the convenience exclusion under Section 513(a)(2) applies since the cafeteria primarily serves patients and employees"]'::jsonb, 3, 'Under IRC Section 513(a)(2), a trade or business is excluded from UBIT if it is carried on primarily for the convenience of the organization''s members, students, patients, officers, or employees. A hospital cafeteria serving primarily patients and staff qualifies for this exclusion. Option A is incorrect because the convenience exclusion does not require volunteer labor — that is a separate exclusion under Section 513(a)(1).', 'medium', 2),

-- Q8: easy / L1 — Form 990-PF filing requirement
(3, 'Tax-Exempt Organizations', 'What annual return must all private foundations file regardless of their gross receipts or total assets?', '["Form 990-PF", "Form 990", "Form 990-EZ", "Form 990-N (e-Postcard)"]'::jsonb, 0, 'Under IRC Section 6033, all private foundations must file Form 990-PF annually regardless of their financial size. This detailed return includes computation of excise taxes under Sections 4940 through 4945. Option B is incorrect because Form 990 is the standard return for public charities, not private foundations. The size-based thresholds for 990/990-EZ/990-N do not apply to private foundations.', 'easy', 1),

-- Q9: easy / L1 — Recognized exempt purposes under 501(c)(3)
(3, 'Tax-Exempt Organizations', 'Which of the following is a recognized exempt purpose under Section 501(c)(3)?', '["Operating a commercial business to generate employment", "Providing below-market loans to the organization''s founders", "Fostering national or international amateur sports competition", "Endorsing candidates for elected office"]'::jsonb, 2, 'Under IRC Section 501(c)(3), exempt purposes include religious, charitable, scientific, literary, educational, testing for public safety, fostering amateur sports competition, and preventing cruelty to children or animals. Option A is incorrect because operating a commercial business is not itself an exempt purpose. Option D is wrong because political campaign activity is absolutely prohibited for 501(c)(3) organizations.', 'easy', 1),

-- Q10: easy / L2 — Form 990-N e-Postcard threshold
(3, 'Tax-Exempt Organizations', 'Green Meadow Animal Rescue, a 501(c)(3) organization, has gross receipts of $42,000 and total assets of $85,000 for the current year. Which annual return must the organization file with the IRS?', '["Form 990 because total assets exceed $50,000", "Form 990-EZ because gross receipts are under $200,000", "No filing is required for organizations with gross receipts under $50,000", "Form 990-N (e-Postcard) because gross receipts are normally $50,000 or less"]'::jsonb, 3, 'Under IRC Section 6033, organizations with gross receipts normally $50,000 or less may file Form 990-N (e-Postcard), a simple electronic notice. With $42,000 in gross receipts meeting this threshold, Form 990-N is appropriate. Option B is incorrect because while Form 990-EZ is available for organizations under $200,000 gross receipts and $500,000 assets, the simpler 990-N is the correct filing for organizations this small.', 'easy', 2),

-- Q11: easy / L1 — Filing deadline for Form 990
(3, 'Tax-Exempt Organizations', 'What is the filing deadline for Form 990 for a calendar-year tax-exempt organization?', '["March 15", "May 15", "April 15", "June 15"]'::jsonb, 1, 'Under IRC Section 6033, Form 990 is due on the 15th day of the 5th month after the end of the organization''s tax year. For calendar-year organizations, this is May 15. An automatic six-month extension is available by filing Form 8868. Option C (April 15) is incorrect because that deadline applies to individual income tax returns, not tax-exempt organization information returns.', 'easy', 1),

-- Q12: easy / L1 — Bingo game exclusion from UBIT
(3, 'Tax-Exempt Organizations', 'Under what condition is income from bingo games excluded from UBIT for a tax-exempt organization?', '["Bingo games are always subject to UBIT regardless of circumstances", "Bingo income is excluded only if the games are conducted fewer than four times per year", "Bingo income is excluded only if all proceeds go directly to charitable purposes", "Bingo income is excluded if the game is legal and commercial bingo is not ordinarily carried on in the jurisdiction"]'::jsonb, 3, 'Under IRC Section 513(f), bingo game income is excluded from UBIT if the bingo game is conducted legally and bingo games are not regularly carried on by for-profit businesses in the same jurisdiction. This prevents exempt organizations from competing directly with taxable bingo operations. Option A is incorrect because Congress specifically carved out this exclusion to support legitimate fundraising activities of exempt organizations.', 'easy', 1),

-- Q13: hard / L4 — Debt-financed property ratio computation
(3, 'Tax-Exempt Organizations', 'Riverdale Foundation, a 501(c)(3), purchased a commercial building for $2,000,000 using an $800,000 mortgage. The building generates $300,000 in rental income with $100,000 in directly connected deductions. The average acquisition indebtedness is $750,000 and the average adjusted basis is $1,500,000. Evaluate the taxable portion of net income under Section 514 and explain how the debt/basis ratio determines the UBIT liability.', '["$50,000, because the debt/basis ratio reduces net income by 75%", "The full $200,000 of net income is subject to UBIT because any debt financing triggers full taxation", "No amount is taxable because rental income from real property is always excluded from UBIT", "$100,000, because the debt/basis ratio of 50% applies to net rental income of $200,000"]'::jsonb, 3, 'Under IRC Section 514, income from debt-financed property is subject to UBIT in proportion to the debt/basis ratio. Average acquisition indebtedness ($750,000) divided by average adjusted basis ($1,500,000) = 50%. Net rental income is $300,000 - $100,000 = $200,000. UBIT portion: $200,000 x 50% = $100,000. Option C is incorrect because the passive income exclusion for real property rents does not apply when the property is debt-financed under Section 514.', 'hard', 4),

-- Q14: easy / L1 — Form 990 late filing penalty rate
(3, 'Tax-Exempt Organizations', 'What is the per-day penalty for failure to timely file Form 990 for a small tax-exempt organization with gross receipts under $1,186,000?', '["$10 per day", "$20 per day", "$50 per day", "$100 per day"]'::jsonb, 1, 'Under IRC Section 6652(c)(1)(A), the penalty for failure to file Form 990 is $20 per day for organizations with gross receipts under $1,186,000, up to the lesser of $10,500 or 5% of gross receipts. For larger organizations, the penalty is $100 per day up to $53,000. Option D is incorrect because the $100 per day penalty applies only to organizations exceeding the gross receipts threshold, not to smaller organizations.', 'easy', 1),

-- Q15: hard / L3 — Section 4945 expenditure responsibility for foreign charities
(3, 'Tax-Exempt Organizations', 'Sterling Private Foundation makes a $200,000 grant to a foreign nonprofit organization that is not recognized as a 501(c)(3) by the IRS. The foundation''s board does not perform expenditure responsibility procedures, believing the charitable purpose of the grant is sufficient justification. Apply Section 4945 to determine the tax consequences.', '["No tax applies because the grant was made for a legitimate charitable purpose to a foreign charity", "A 10% excise tax applies because the grant was to a foreign organization rather than a domestic one", "A 20% excise tax ($40,000) applies because grants to non-501(c)(3) organizations without expenditure responsibility are taxable expenditures under Section 4945", "A 5% excise tax applies because the foundation failed to obtain advance IRS approval"]'::jsonb, 2, 'Under IRC Section 4945(d)(4), grants by a private foundation to organizations other than public charities are taxable expenditures unless the foundation exercises expenditure responsibility — requiring a pre-grant inquiry, written agreement, and monitoring of fund use. The initial excise tax is 20% of the expenditure ($40,000). Option A is incorrect because charitable purpose alone does not excuse the requirement for expenditure responsibility when the grantee is not a 501(c)(3).', 'hard', 3),

-- Q16: medium / L3 — Research exclusion from UBIT
(3, 'Tax-Exempt Organizations', 'Pinnacle University, a 501(c)(3), conducts pharmaceutical research under an exclusive contract with a private drug manufacturer. The manufacturer retains all intellectual property rights, and research results are not published. Annual contract payments total $500,000. Apply the UBIT research exclusion to determine the tax treatment.', '["The $500,000 is excluded from UBIT because all research performed by colleges and universities is automatically exempt", "The $500,000 is subject to UBIT because the research results are not freely available to the general public and the manufacturer retains IP rights", "The $500,000 is excluded because the research is performed at a university campus", "The $500,000 is excluded if the university uses the income for educational purposes"]'::jsonb, 1, 'Under IRC Section 512(b)(7)–(9), research performed by a college or university is excluded from UBIT only if the results are freely available to the general public. When a manufacturer retains IP rights and results are not published, this exclusion does not apply. The income meets all three parts of the UBIT test: trade or business, regularly carried on, and not substantially related. Option A is incorrect because the exclusion is not blanket for all university research — it requires public availability of results.', 'medium', 3),

-- Q17: medium / L2 — Additional tax for uncorrected excess benefit
(3, 'Tax-Exempt Organizations', 'Marcus Reed, a disqualified person, received an excess benefit of $150,000 from a 501(c)(3) organization in 2024. The IRS assessed the initial 25% excise tax. Marcus failed to correct the excess benefit within the taxable period. What additional excise tax is imposed on Marcus under Section 4958?', '["An additional 10% excise tax ($15,000)", "An additional 25% excise tax ($37,500)", "No additional tax beyond the initial 25% penalty", "An additional 200% excise tax ($300,000)"]'::jsonb, 3, 'Under IRC Section 4958(b), if a disqualified person fails to correct an excess benefit transaction within the taxable period, an additional excise tax of 200% of the excess benefit is imposed. Here, 200% of $150,000 = $300,000. Option A is incorrect because the 10% tax applies to organization managers who knowingly participated, not as an additional tax on the disqualified person for failure to correct.', 'medium', 2),

-- Q18: medium / L3 — NOL deduction for UBIT uses only UBI items
(3, 'Tax-Exempt Organizations', 'Heritage Cultural Society, a 501(c)(3), has two unrelated business activities. Activity A generates $40,000 net income and Activity B produces a $55,000 net loss. The society also has $20,000 in dividend income from investments. Determine the organization''s unrelated business taxable income for the year.', '["$5,000, after offsetting the loss and adding dividend income", "Negative $35,000, because dividend income offsets UBI and increases the loss", "Zero, because the $1,000 specific deduction eliminates any remaining positive UBI", "Negative $15,000, creating a net operating loss carryforward computed using only UBI items"]'::jsonb, 3, 'Under IRC Section 512(b)(1), dividends are excluded from UBIT as passive income. UBI is computed using only unrelated business items: $40,000 - $55,000 = ($15,000) net UBI loss. The $1,000 specific deduction does not increase a loss. The ($15,000) creates a net operating loss that may be carried forward under Section 512(b)(6). Option B is incorrect because dividend income is excluded from UBIT computation entirely and cannot increase the loss.', 'medium', 3),

-- Q19: medium / L2 — Organization manager tax under Section 4958
(3, 'Tax-Exempt Organizations', 'Sarah Chen, the CFO and board member of a 501(c)(3) hospital, knowingly approves an excess benefit transaction valued at $500,000. The board did not obtain comparability data. What excise tax does Sarah personally face as an organization manager under Section 4958?', '["25% of the excess benefit ($125,000)", "200% of the excess benefit ($1,000,000)", "10% of the excess benefit, capped at $20,000 per transaction", "No tax, because only the disqualified person who received the benefit is liable"]'::jsonb, 2, 'Under IRC Section 4958(a)(2), an organization manager who knowingly participates in an excess benefit transaction faces a 10% excise tax on the excess benefit, capped at $20,000 per transaction. For a $500,000 excess benefit, 10% = $50,000, but the cap limits Sarah''s liability to $20,000. Option A is incorrect because the 25% tax applies to the disqualified person who received the excess benefit, not to the organization manager.', 'medium', 2),

-- Q20: easy / L1 — Section 4940 net investment income tax rate
(3, 'Tax-Exempt Organizations', 'What excise tax rate does Section 4940 impose on a private foundation''s net investment income?', '["0.5%", "2.0%", "1.39%", "3.8%"]'::jsonb, 2, 'Under IRC Section 4940, private foundations are subject to a 1.39% excise tax on net investment income, which includes interest, dividends, rents, royalties, and net capital gains. This tax funds IRS oversight of private foundations. Option D (3.8%) is incorrect because that is the net investment income tax rate under Section 1411 for high-income individuals, not the private foundation excise tax.', 'easy', 1),

-- Q21: easy / L1 — Private inurement prohibition definition
(3, 'Tax-Exempt Organizations', 'What does the private inurement prohibition prevent in a Section 501(c)(3) organization?', '["The organization from earning more than $500,000 in annual revenue", "The organization from employing family members in any capacity", "Any part of net earnings from benefiting any private shareholder or individual who is an insider", "The organization from investing in publicly traded securities"]'::jsonb, 2, 'Under IRC Section 501(c)(3), the private inurement prohibition prevents any part of the organization''s net earnings from inuring to the benefit of private shareholders or individuals — meaning insiders with a personal and private interest in the organization''s activities. Option A is incorrect because there is no revenue cap for 501(c)(3) organizations. The prohibition targets improper benefit to insiders, not organizational income levels.', 'easy', 1),

-- Q22: hard / L4 — Excess business holdings with combined disqualified person ownership
(3, 'Tax-Exempt Organizations', 'Anderson Family Foundation owns 12% of voting stock in TechCorp. The Anderson family members (disqualified persons) individually own an additional 15% of TechCorp''s voting stock. Under Section 4943, evaluate the foundation''s compliance with the excess business holdings rules and determine the required corrective action.', '["No excess exists because the foundation''s 12% ownership alone is below the 20% threshold", "Combined holdings are permitted up to 35% when disqualified persons hold less than 20% individually", "Combined holdings of 27% exceed the 20% permitted limit, requiring the foundation to dispose of 7% within the correction period to avoid additional excise taxes", "The foundation must divest all 12% of its holdings because any stock ownership by a private foundation is prohibited"]'::jsonb, 2, 'Under IRC Section 4943, a private foundation and its disqualified persons combined may not own more than 20% of the voting stock of a business enterprise. Combined ownership here is 12% + 15% = 27%, exceeding the 20% limit by 7%. The foundation must dispose of excess holdings within the correction period, and an initial 10% excise tax applies. Option A is incorrect because Section 4943 considers combined holdings of the foundation and all disqualified persons, not just the foundation alone.', 'hard', 4),

-- Q23: medium / L3 — Form 8868 extension deadline calculation
(3, 'Tax-Exempt Organizations', 'Coastal Conservation Alliance, a calendar-year 501(c)(3), files Form 8868 for an automatic extension of its Form 990 filing deadline. The organization''s fiscal year ends December 31, 2025. Determine the extended due date for the Form 990.', '["August 15, 2026, because the extension is three months from the original May 15 due date", "November 15, 2026, because the automatic extension is six months from the original May 15 due date", "September 15, 2026, because the extension runs six months from the fiscal year end", "July 15, 2026, because exempt organizations receive only a two-month extension"]'::jsonb, 1, 'Under IRC Section 6081, Form 8868 provides an automatic six-month extension for Form 990. The original due date for a calendar-year organization is May 15 (15th day of the 5th month after year-end). Adding six months yields November 15, 2026. Option A is incorrect because the extension is six months, not three months. Option C incorrectly calculates from the fiscal year end rather than the original due date.', 'medium', 3),

-- Q24: medium / L2 — Schedule A of Form 990 for public charity status
(3, 'Tax-Exempt Organizations', 'Horizon Community Foundation, a 501(c)(3) public charity, is completing its annual Form 990. The organization needs to report its public charity classification and demonstrate it meets the public support test. Which Form 990 schedule is used for this purpose?', '["Schedule B — Schedule of Contributors", "Schedule D — Supplemental Financial Statements", "Schedule J — Compensation Information", "Schedule A — Public Charity Status and Public Support"]'::jsonb, 3, 'Schedule A of Form 990 reports the organization''s public charity status and public support calculations, including whether the organization meets the one-third support test under Section 509(a)(1) or the gross receipts test under Section 509(a)(2). Option A (Schedule B) is incorrect because Schedule B reports individual contributors and is confidential — it does not demonstrate public charity classification.', 'medium', 2),

-- Q25: medium / L2 — Automatic public charity classification for churches
(3, 'Tax-Exempt Organizations', 'New Horizons Church was incorporated as a 501(c)(3) organization last year. The church received 90% of its support from a single wealthy family. Despite the concentrated funding source, the church''s attorney advises that it qualifies as a public charity. What is the basis for this classification?', '["The church meets the one-third support test because religious contributions are weighted more heavily", "The church qualifies because it applied for public charity status on Form 1023", "The church does not qualify as a public charity with 90% support from a single family", "Churches are automatically classified as public charities under Section 170(b)(1)(A)(i) regardless of funding sources"]'::jsonb, 3, 'Under IRC Section 170(b)(1)(A)(i), churches are automatically classified as public charities regardless of their funding sources. This automatic classification also applies to schools and hospitals. The one-third support test does not apply to churches. Option C is incorrect because unlike most 501(c)(3) organizations, churches are exempt from demonstrating broad public support to maintain public charity status.', 'medium', 2),

-- Q26: hard / L4 — Section 4941 second-tier penalties for self-dealing
(3, 'Tax-Exempt Organizations', 'Davis Private Foundation leased office space to its founder, James Davis, at below-market rent in January 2025. The IRS identified this as self-dealing under Section 4941 and assessed the initial 10% excise tax on Davis. Davis failed to correct the transaction within the taxable period. Evaluate the total tax consequences for Davis, including second-tier penalties.', '["Davis owes only the initial 10% tax because no additional penalties apply to self-dealing", "Davis owes 25% of the amount involved as the maximum self-dealing penalty", "Davis owes 10% initially plus an additional 200% of the amount involved as a second-tier tax for failure to correct", "Davis owes 10% initially plus an additional 100% of the amount involved for the second-tier tax"]'::jsonb, 2, 'Under IRC Section 4941, the initial excise tax on a self-dealer is 10% of the amount involved. If the self-dealing is not corrected within the taxable period, an additional second-tier tax of 200% of the amount involved is imposed on the self-dealer. Correction requires undoing the transaction and restoring the foundation to its pre-transaction financial position. Option D is incorrect because the second-tier penalty is 200%, not 100%, of the amount involved.', 'hard', 4),

-- Q27: medium / L3 — Operational test applied to mixed-purpose organization
(3, 'Tax-Exempt Organizations', 'Community Outreach Alliance plans to dedicate 60% of its activities to educational programs for underserved youth and 40% to operating a commercial catering business. All catering profits would fund the educational programs. Apply the operational test to determine if this organization qualifies for Section 501(c)(3) status.', '["The organization qualifies because 60% of activities serve exempt purposes, satisfying the majority standard", "The organization qualifies because all profits from the catering business support charitable activities", "The organization likely fails the operational test because 40% commercial activity is more than insubstantial, even though profits fund exempt purposes", "The organization automatically qualifies if it includes an exempt purpose clause in its articles"]'::jsonb, 2, 'Under IRC Section 501(c)(3), the operational test requires that the organization be operated primarily for exempt purposes. Non-exempt activities must be only an insubstantial part of total activities. A 40% commercial activity level is generally considered more than insubstantial, potentially disqualifying the organization. Option B is incorrect because using income for exempt purposes does not make the income-generating activity itself related to exempt purposes.', 'medium', 3),

-- Q28: medium / L3 — Expenditure responsibility for grants to 501(c)(4) organizations
(3, 'Tax-Exempt Organizations', 'Pacific Grove Foundation, a private foundation, awards a $100,000 grant to a 501(c)(4) social welfare organization for community health initiatives. The foundation''s program officer assumes that because the grantee is tax-exempt, no special procedures are required. Apply Section 4945 to evaluate whether expenditure responsibility is needed.', '["No expenditure responsibility is required because the grantee is a tax-exempt organization", "No expenditure responsibility is required because the grant is for charitable purposes", "Expenditure responsibility is required only if the grant exceeds $250,000", "Expenditure responsibility is required because the grantee is not a 501(c)(3) public charity, and failure to exercise it makes the grant a taxable expenditure"]'::jsonb, 3, 'Under IRC Section 4945(d)(4), grants to organizations other than public charities (including 501(c)(4) organizations) are taxable expenditures unless the foundation exercises expenditure responsibility. This includes a pre-grant inquiry, written agreement restricting use to charitable purposes, and annual reporting. Option A is incorrect because expenditure responsibility depends on the grantee''s public charity status, not merely its tax-exempt status.', 'medium', 3),

-- Q29: medium / L2 — Section 4958 applicability to 501(c)(4) organizations
(3, 'Tax-Exempt Organizations', 'A Section 501(c)(4) social welfare organization pays its executive director compensation significantly above market rates. The board consisted entirely of the director''s family members and did not obtain comparability data. Which enforcement mechanism does the IRS apply to this excess compensation?', '["The IRS can only revoke the organization''s tax-exempt status since no excise taxes apply to 501(c)(4) organizations", "Section 4941 self-dealing rules apply because the board members are related to the director", "Section 4958 intermediate sanctions apply to 501(c)(4) organizations, imposing a 25% initial excise tax on the disqualified person", "No enforcement mechanism exists because 501(c)(4) organizations are not subject to private benefit rules"]'::jsonb, 2, 'Under IRC Section 4958, intermediate sanctions apply to both 501(c)(3) and 501(c)(4) organizations. The disqualified person who received the excess benefit faces a 25% initial excise tax. Option A is incorrect because Section 4958 was enacted specifically to provide an alternative to the all-or-nothing remedy of revoking exempt status. Option B is incorrect because Section 4941 applies only to private foundations, not 501(c)(4) organizations.', 'medium', 2),

-- Q30: medium / L2 — Form 990-T filing threshold
(3, 'Tax-Exempt Organizations', 'Willow Creek Education Fund, a 501(c)(3), has $850 of gross income from an unrelated business activity and $200 in related expenses. After the $1,000 specific deduction, the organization has no unrelated business taxable income. Must the organization file Form 990-T?', '["Yes, because any amount of unrelated business income requires Form 990-T filing", "No, because gross unrelated business income is less than $1,000", "Yes, but only if the organization has total revenue exceeding $200,000", "No, because the $1,000 specific deduction eliminates the filing requirement"]'::jsonb, 1, 'Under IRC Section 6012(a)(6), a tax-exempt organization must file Form 990-T only if it has gross income of $1,000 or more from an unrelated trade or business. With only $850 in gross UBI, Willow Creek falls below the $1,000 filing threshold and is not required to file. Option D is incorrect because the specific deduction reduces taxable income but is irrelevant to the filing threshold, which is based on gross income, not net.', 'medium', 2)
;

COMMIT;
