-- Migration: Question generation — REG batch 7 (30 questions)
-- Date: 2026-02-28
-- Topic: Tax-Exempt Organizations
-- Difficulty: 9E / 15M / 6H
-- Bloom's: L1:8 / L2:9 / L3:8 / L4:5

BEGIN;

INSERT INTO questions (section_id, topic, stem, choices, correct_index, explanation, difficulty, cognitive_level)
VALUES

-- Q1: hard / L4 — Section 501(h) expenditure test election strategy
(3, 'Tax-Exempt Organizations', 'Civic Voice, a 501(c)(3) advocacy nonprofit with $600,000 in annual exempt purpose expenditures, spends $90,000 on direct lobbying and $20,000 on grassroots lobbying. The board has not made the Section 501(h) election. Under the expenditure test, the nontaxable lobbying amount for a $600,000 budget is $115,000, with a grassroots sub-limit of $28,750. Evaluate whether making the election would benefit the organization.', '["The election is unnecessary because total lobbying of $110,000 is clearly insubstantial under the substantial part test", "The election is harmful because the $110,000 total exceeds the nontaxable amount for a $600,000 budget", "The election is beneficial because it replaces the vague substantial part test with a specific nontaxable amount of $115,000, and $110,000 falls within that limit", "The election is irrelevant because 501(c)(3) organizations may never engage in lobbying"]'::jsonb, 2, 'Under IRC Section 501(h), eligible 501(c)(3) organizations may elect the expenditure test, which provides specific dollar thresholds: 20% of the first $500,000 plus 15% of the next $100,000 equals a $115,000 nontaxable amount. Total lobbying of $110,000 falls within this limit. Without the election, the vague ''substantial part'' test creates uncertainty — courts have found as little as 5% lobbying potentially substantial. Option B is incorrect because $110,000 does not exceed the $115,000 threshold.', 'hard', 4),

-- Q2: easy / L1 — Dissolution clause requirement
(3, 'Tax-Exempt Organizations', 'Under the organizational test for Section 501(c)(3) status, what must the dissolution clause in governing documents provide?', '["Assets must be distributed equally to all members upon dissolution", "Assets must be distributed to another exempt organization or to the government upon dissolution", "Assets must be donated to a private foundation created by the board", "Assets must be liquidated and returned to the original donors"]'::jsonb, 1, 'Under IRC Section 501(c)(3), the organizational test requires governing documents to include a dissolution clause providing that upon dissolution, remaining assets will be distributed to another 501(c)(3) organization or to government. This prevents private benefit from exempt assets. Option A is incorrect because distribution to members would constitute private inurement, violating a fundamental requirement for tax-exempt status.', 'easy', 1),

-- Q3: easy / L1 — Private inurement prohibition
(3, 'Tax-Exempt Organizations', 'What does the private inurement prohibition under Section 501(c)(3) prevent?', '["Net earnings of the organization from benefiting any private shareholder or individual", "The organization from earning any revenue from business activities", "The organization from investing in publicly traded securities", "The organization from paying reasonable salaries to employees"]'::jsonb, 0, 'Under IRC Section 501(c)(3), the private inurement prohibition provides that no part of the organization''s net earnings may inure to the benefit of any private shareholder or individual. This targets insiders with a personal interest in the organization''s activities. Option D is incorrect because reasonable compensation for services rendered is permissible — only excessive or unjustified payments violate the prohibition.', 'easy', 1),

-- Q4: easy / L1 — Automatic public charity classification
(3, 'Tax-Exempt Organizations', 'Which type of organization is automatically classified as a public charity regardless of its funding sources?', '["A community foundation distributing grants to local nonprofits", "A private operating foundation conducting its own charitable programs", "A 501(c)(4) social welfare organization", "A church meeting the requirements of Section 170(b)(1)(A)(i)"]'::jsonb, 3, 'Under IRC Section 509(a)(1), churches, schools, and hospitals are automatically classified as public charities regardless of their funding sources. They do not need to meet the one-third public support test. Option A is incorrect because a community foundation must demonstrate broad public support to qualify as a public charity and does not receive automatic classification.', 'easy', 1),

-- Q5: medium / L3 — Controlled entity payments as UBIT
(3, 'Tax-Exempt Organizations', 'Mission Health Network, a 501(c)(3) hospital, owns 100% of MedServ LLC, a taxable subsidiary. MedServ pays Mission Health $200,000 in annual rent for office space, but comparable market rent is $150,000. Determine how the rent payment is treated under UBIT rules for controlled entities.', '["The entire $200,000 is excluded from UBIT because rents from real property are always passive income", "The $50,000 excess over fair market value is included in UBIT under the controlled entity rules", "The entire $200,000 is included in UBIT because it is received from a controlled subsidiary", "No amount is subject to UBIT because the transaction occurs between related parties"]'::jsonb, 1, 'Under IRC Section 512(b)(13), rent received from a controlled entity (80% or more ownership) is treated as UBIT to the extent it exceeds fair market value. Here, $200,000 minus $150,000 FMV equals $50,000 subject to UBIT. The general exclusion for real property rents under Section 512(b)(3) does not apply to the excess portion. Option C is incorrect because only the amount exceeding FMV is included — the $150,000 at fair market value retains its passive income exclusion.', 'medium', 3),

-- Q6: medium / L3 — Personal property rents inclusion in UBIT
(3, 'Tax-Exempt Organizations', 'Heritage Arts Center, a 501(c)(3), leases a building to a commercial tenant. Under the lease, $180,000 of rent is attributable to the real property and $30,000 is attributable to personal property (furniture and equipment), totaling $210,000. Apply the UBIT rules to determine which portion of the rent is subject to tax.', '["The entire $210,000 is excluded from UBIT because all rents are classified as passive income", "The entire $210,000 is subject to UBIT because the lease includes personal property", "Only the $30,000 personal property portion is subject to UBIT because personal property rents exceed the 10% incidental threshold", "Only the $180,000 real property portion is subject to UBIT because the organization leases its own building"]'::jsonb, 2, 'Under IRC Section 512(b)(3), rents from real property are generally excluded from UBIT, but rents from personal property are not. When a lease involves both, if personal property rents are less than 10% of total rents, all rents are excluded as incidental. Here, personal property rents are $30,000/$210,000 (14.3%), exceeding the 10% threshold, so the $30,000 personal property portion is taxable. Option A is incorrect because the personal property component loses its passive income exclusion when it exceeds 10% of total rents.', 'medium', 3),

-- Q7: medium / L2 — Form 990 filing thresholds
(3, 'Tax-Exempt Organizations', 'Neighborhood Literacy Project, a 501(c)(3) organization, has gross receipts of $140,000 and total assets of $420,000 for the 2025 tax year. Which annual information return must the organization file with the IRS?', '["Form 990-EZ, because gross receipts are under $200,000 and total assets are under $500,000", "Form 990-N (e-Postcard), because gross receipts are under $200,000", "Form 990, because total assets exceed $200,000", "No return is required because the organization is tax-exempt"]'::jsonb, 0, 'Under IRC Section 6033, a 501(c)(3) organization files Form 990-EZ when gross receipts are less than $200,000 AND total assets are less than $500,000. Here, $140,000 gross receipts and $420,000 total assets both fall below these thresholds. Option B is incorrect because Form 990-N is only available when gross receipts are $50,000 or less — the $140,000 in gross receipts exceeds this limit.', 'medium', 2),

-- Q8: hard / L4 — Convenience exclusion analysis (hospital cafeteria)
(3, 'Tax-Exempt Organizations', 'Valley Regional Hospital, a 501(c)(3), operates a cafeteria open to patients, visitors, and the general public. The cafeteria generates $450,000 in annual revenue — 60% from hospital employees and patients, and 40% from walk-in members of the general public. The hospital argues the convenience exclusion shields all cafeteria income from UBIT. Evaluate whether the convenience exclusion applies and to what extent.', '["The convenience exclusion applies to all $450,000 because the cafeteria is located on hospital premises", "The convenience exclusion does not apply because 40% of revenue comes from the general public, exceeding a de minimis amount", "The entire $450,000 is subject to UBIT because food service is not related to the hospital''s exempt purpose", "The convenience exclusion applies to the extent the cafeteria serves patients and employees, but revenue from general public sales may be subject to UBIT analysis"]'::jsonb, 3, 'Under IRC Section 513(a)(2), the convenience exclusion exempts activities conducted primarily for the convenience of members, patients, students, or employees. A hospital cafeteria serving primarily patients and staff qualifies, but when a significant portion of revenue (40%) comes from the general public, the IRS may treat that portion as an unrelated trade or business. Option A is incorrect because mere location on hospital premises does not automatically invoke the exclusion — the activity must primarily serve the exempt constituency.', 'hard', 4),

-- Q9: hard / L3 — Debt-financed income calculation (debt/basis ratio)
(3, 'Tax-Exempt Organizations', 'Lakeside Education Foundation, a 501(c)(3), purchases a commercial building for $1,000,000, financing $600,000 with a mortgage. The building generates $120,000 in annual rental income. The average acquisition indebtedness for the year is $550,000, and the average adjusted basis is $950,000. Calculate the portion of rental income subject to UBIT under Section 514.', '["$72,000, calculated as $120,000 multiplied by the original loan-to-purchase ratio of $600,000/$1,000,000", "$69,474, calculated as $120,000 multiplied by the average acquisition indebtedness divided by average adjusted basis ($550,000/$950,000)", "$120,000, because all rental income from debt-financed property is subject to UBIT", "$66,000, calculated as $120,000 multiplied by the current mortgage balance divided by purchase price ($550,000/$1,000,000)"]'::jsonb, 1, 'Under IRC Section 514, debt-financed income is subject to UBIT in proportion to the average acquisition indebtedness divided by the average adjusted basis of the property. Here, $550,000/$950,000 equals 57.89%, so $120,000 x 57.89% = $69,474 is subject to UBIT. Option A is incorrect because the calculation uses the original loan-to-purchase ratio rather than the required average indebtedness-to-basis ratio, which accounts for principal payments and depreciation adjustments.', 'hard', 3),

-- Q10: medium / L3 — Section 4958 additional 200% tax if uncorrected
(3, 'Tax-Exempt Organizations', 'Dr. Harris, the CEO of Bright Futures Foundation (a 501(c)(3)), received $750,000 in total compensation when comparable positions pay $400,000. The $350,000 excess benefit was identified in an IRS examination in March 2026. As of the correction deadline, Dr. Harris has not returned the excess amount. Apply the Section 4958 intermediate sanctions.', '["An initial tax of 10% ($35,000) on Dr. Harris, with no additional tax because the IRS identified the excess", "An initial tax of 25% ($87,500) on Dr. Harris, plus automatic revocation of the organization''s exempt status", "An initial tax of 25% ($87,500) on Dr. Harris, plus an additional 200% tax ($700,000) if the excess benefit is not corrected within the taxable period", "An initial tax of 25% ($87,500) on the organization, plus a 10% tax on Dr. Harris"]'::jsonb, 2, 'Under IRC Section 4958, excess benefit transactions trigger a 25% initial excise tax on the disqualified person (Dr. Harris), calculated on the $350,000 excess benefit ($87,500). If the disqualified person fails to correct the excess benefit within the taxable period, an additional 200% tax ($700,000) is imposed. Option A is incorrect because the initial tax rate is 25%, not 10% — the 10% rate applies to organization managers who knowingly participate, not to the disqualified person.', 'medium', 3),

-- Q11: medium / L2 — Supporting organizations under Section 509(a)(3)
(3, 'Tax-Exempt Organizations', 'Sunrise Support Services is organized and operated exclusively to raise funds for Sunrise Community Hospital, a public charity. Sunrise Support Services does not receive broad public support. Under what classification does Sunrise Support Services qualify for public charity status?', '["A supporting organization under Section 509(a)(3), because it is operated exclusively to support a public charity", "A private foundation, because it does not receive broad public support", "A public charity under Section 509(a)(1), because it supports a hospital", "A private operating foundation, because it raises funds for charitable purposes"]'::jsonb, 0, 'Under IRC Section 509(a)(3), an organization qualifies as a public charity if it is organized and operated exclusively to support one or more public charities. Sunrise Support Services meets this test by operating exclusively to raise funds for Sunrise Community Hospital. Option B is incorrect because the Section 509(a)(3) supporting organization classification provides an alternative path to public charity status that does not require broad public support.', 'medium', 2),

-- Q12: medium / L2 — Form 990 Schedule B confidentiality
(3, 'Tax-Exempt Organizations', 'A donor to a 501(c)(3) organization contributed $50,000 during the tax year. The organization files Form 990 annually. The organization''s board member asks whether this donor''s name will be publicly disclosed through the Form 990 filing. Which Form 990 schedule addresses contributor information, and what is its public availability?', '["Schedule A lists all contributors and is available to the public upon request", "Schedule J reports contributor details alongside compensation information and is publicly available", "Schedule D includes contributor information as part of supplemental financial statements and is publicly available", "Schedule B reports contributor information but is not available to the general public — it is confidential"]'::jsonb, 3, 'Form 990, Schedule B (Schedule of Contributors) lists contributors who gave $5,000 or more during the tax year. Unlike most Form 990 schedules, Schedule B is confidential and not available to the general public, protecting donor privacy. The IRS receives Schedule B but does not release it publicly. Option A is incorrect because Schedule A reports public charity status and public support calculations, not contributor names.', 'medium', 2),

-- Q13: medium / L3 — NOL deduction for UBIT (UBI items only)
(3, 'Tax-Exempt Organizations', 'Green Horizons, a 501(c)(3) environmental nonprofit, has $80,000 in unrelated business income from a commercial parking lot and a $95,000 net operating loss carried forward from prior years'' unrelated business activities. The organization also has $200,000 in tax-exempt donation revenue. Determine how the NOL applies to Green Horizons'' UBIT calculation.', '["The NOL cannot be applied because NOL deductions are not permitted against UBIT", "The $80,000 UBI is fully offset by the $95,000 NOL carryforward, resulting in zero UBIT and a $15,000 carryforward", "The $80,000 UBI is partially offset, but the NOL is limited to 80% of UBI ($64,000), leaving $16,000 subject to UBIT", "The $95,000 NOL can offset both the $80,000 UBI and $15,000 of exempt income, eliminating all tax liability"]'::jsonb, 1, 'Under IRC Section 512(b)(6), exempt organizations may deduct net operating losses against UBIT, but the NOL must be computed using only unrelated business income items. The $80,000 UBI is fully offset by the $95,000 NOL carryforward, leaving $15,000 available for future years. Option D is incorrect because the NOL deduction applies only to unrelated business income — it cannot offset tax-exempt donation revenue, which is not included in the UBIT computation.', 'medium', 3),

-- Q14: medium / L2 — Form 990 filing deadline
(3, 'Tax-Exempt Organizations', 'River City Youth Foundation, a 501(c)(3) with a calendar year-end (December 31), needs to file its annual Form 990. The organization has not applied for an extension. By what date must the Form 990 be filed?', '["March 15 of the following year (15th day of the 3rd month)", "April 15 of the following year (15th day of the 4th month)", "May 15 of the following year (15th day of the 5th month)", "June 15 of the following year (15th day of the 6th month)"]'::jsonb, 2, 'Under IRC Section 6072(e), Form 990 must be filed by the 15th day of the 5th month after the end of the organization''s tax year. For a calendar-year organization, the deadline is May 15. Extensions of up to six months are available using Form 8868. Option A is incorrect because the March 15 deadline applies to partnerships (Form 1065) and S corporations (Form 1120-S), not to tax-exempt organizations.', 'medium', 2),

-- Q15: easy / L1 — Research exclusion from UBIT
(3, 'Tax-Exempt Organizations', 'Under the UBIT rules, which type of research activity is excluded from unrelated business taxable income?', '["Research performed for the United States government or a college or university", "Research performed exclusively for a single private corporation under contract", "Research funded by a foreign government with no public access to results", "Research conducted by paid employees on commercially valuable patents"]'::jsonb, 0, 'Under IRC Section 512(b)(7)-(9), research income is excluded from UBIT when performed for the U.S. government, a college or university, or when the results are freely available to the general public. Option B is incorrect because research performed exclusively for a single private corporation is a commercial service that does not qualify for the research exclusion.', 'easy', 1),

-- Q16: hard / L4 — Excess business holdings with attribution
(3, 'Tax-Exempt Organizations', 'The Parker Foundation, a private foundation, directly owns 12% of voting stock in Delta Industries. The founder''s son, a disqualified person under Section 4946, owns 9% of Delta''s voting stock. An unrelated third party offers to sell the foundation an additional 5% block of Delta stock at below-market value. Evaluate the excess business holdings implications under Section 4943 if the foundation acquires the additional shares.', '["The acquisition is permissible because the foundation''s direct ownership would be 17%, under the 20% limit", "The acquisition would create excess business holdings because combined holdings of the foundation (17%) and the disqualified person (9%) would total 26%, exceeding the 20% permitted limit", "The acquisition is permissible because disqualified persons'' holdings are not attributed to the foundation for Section 4943 purposes", "The acquisition would only trigger a 10% excise tax on the below-market purchase price as a self-dealing transaction"]'::jsonb, 1, 'Under IRC Section 4943, a private foundation and its disqualified persons may not collectively own more than 20% of voting stock in a business enterprise. The foundation''s 17% (12% + 5%) plus the disqualified person''s 9% totals 26%, exceeding the 20% permitted holding. Option C is incorrect because Section 4943 explicitly aggregates the holdings of the foundation and all disqualified persons — the son''s 9% must be combined with the foundation''s holdings.', 'hard', 4),

-- Q17: easy / L2 — One-third public support test
(3, 'Tax-Exempt Organizations', 'Bright Minds Education, a 501(c)(3) organization, receives $400,000 in total support. Of this, $120,000 comes from government grants and public donations, and $280,000 comes from a single wealthy donor. Does the organization qualify as a public charity under the one-third support test?', '["Yes, because total support exceeds $100,000", "Yes, because it receives some government funding", "No, because more than half its support comes from a single donor", "No, because public and government support ($120,000) is less than one-third of total support ($400,000)"]'::jsonb, 3, 'Under IRC Section 509(a)(1), an organization qualifies as a public charity under the one-third support test if it normally receives at least one-third of its total support from governmental units and the general public. Here, $120,000/$400,000 equals 30%, which is below the one-third (33.3%) threshold. Option C identifies concentrated support but the disqualification is specifically because public/government support fails the one-third test, not simply because one donor provides more than half.', 'easy', 2),

-- Q18: easy / L1 — Form 990-N (e-Postcard) filing threshold
(3, 'Tax-Exempt Organizations', 'What is the maximum gross receipts threshold for a tax-exempt organization to file Form 990-N (e-Postcard)?', '["$25,000", "$100,000", "$50,000", "$200,000"]'::jsonb, 2, 'Under IRC Section 6033(i), tax-exempt organizations with annual gross receipts normally $50,000 or less may file Form 990-N (e-Postcard), an electronic notice requiring only basic information such as name, address, EIN, and confirmation of continued eligibility. Option D is incorrect because $200,000 is the gross receipts threshold above which an organization must file the full Form 990 rather than Form 990-EZ.', 'easy', 1),

-- Q19: easy / L1 — Bingo games exclusion from UBIT
(3, 'Tax-Exempt Organizations', 'Under Section 513, what condition must be met for bingo game income to be excluded from UBIT?', '["The bingo games must be conducted in a jurisdiction where commercial bingo is not ordinarily carried on", "The bingo games must generate less than $50,000 in annual revenue", "The bingo games must be held no more than once per month", "The bingo games must be operated exclusively by the organization''s board members"]'::jsonb, 0, 'Under IRC Section 513(f), bingo game income is excluded from UBIT when the games are legal and conducted in a jurisdiction where commercial bingo operations are not ordinarily carried on. This prevents exempt organizations from competing with taxable bingo operations. Option B is incorrect because no dollar threshold applies to the bingo exclusion — the test is geographic, based on whether commercial bingo is ordinarily conducted in the same area.', 'easy', 1),

-- Q20: medium / L3 — Section 4945 taxable expenditures (grant without advance IRS approval)
(3, 'Tax-Exempt Organizations', 'The Davidson Foundation, a private foundation, wants to award a $15,000 study grant to an individual graduate student for dissertation research. The foundation has not obtained advance IRS approval for its individual grant-making procedures. Determine how Section 4945 treats this expenditure.', '["The grant is automatically exempt from Section 4945 because it is for educational purposes", "The grant is a taxable expenditure under Section 4945 because the foundation lacks advance IRS approval for its individual grant procedures", "The grant is permissible if the foundation obtains the student''s written acknowledgment of the award", "The grant is a self-dealing transaction under Section 4941 because it benefits a specific individual"]'::jsonb, 1, 'Under IRC Section 4945(g), grants by private foundations to individuals for travel, study, or similar purposes are taxable expenditures unless the foundation obtains advance IRS approval of its grant-making procedures, including objective selection criteria. Without this approval, the $15,000 grant triggers a 20% excise tax on the foundation. Option A is incorrect because educational purpose alone does not exempt the grant — the procedural safeguard of advance IRS approval is required regardless of charitable intent.', 'medium', 3),

-- Q21: hard / L4 — Operational test vs. organizational test distinction
(3, 'Tax-Exempt Organizations', 'New Dawn Initiative files articles of incorporation limiting its purposes to educational and charitable activities under Section 501(c)(3) and including a proper dissolution clause. However, during its first three years, the organization devotes 65% of its activities to consulting services for for-profit clients, using the net proceeds to fund scholarships. Evaluate New Dawn''s compliance with the Section 501(c)(3) qualification tests.', '["New Dawn passes both tests because its articles properly limit exempt purposes and the consulting proceeds fund scholarships", "New Dawn fails the organizational test because consulting services are not listed as an exempt purpose in its articles", "New Dawn fails both the organizational and operational tests because for-profit consulting cannot be conducted by a 501(c)(3)", "New Dawn passes the organizational test but fails the operational test because it is not operated primarily for exempt purposes — using income for scholarships does not make consulting a related activity"]'::jsonb, 3, 'Under IRC Section 501(c)(3), an organization must pass both the organizational test (governing documents limit purposes) and the operational test (operated primarily for exempt purposes). New Dawn''s articles properly limit purposes, satisfying the organizational test. However, devoting 65% of activities to commercial consulting fails the operational test — using revenue for exempt purposes does not make the revenue-generating activity itself an exempt function. Option A is incorrect because the operational test examines how the organization actually operates, not merely how it uses its income.', 'hard', 4),

-- Q22: medium / L3 — Penalty calculation for failure to file Form 990
(3, 'Tax-Exempt Organizations', 'Community Bridge Services, a 501(c)(3) with annual gross receipts of $800,000, fails to file its Form 990 by the May 15 deadline and does not file until 90 days later. The organization had no reasonable cause for the delay. Calculate the penalty under IRC Section 6652(c).', '["$1,800, calculated as $20 per day for 90 days", "$9,000, calculated as $100 per day for 90 days", "$10,500, because the maximum penalty applies immediately upon failure to file", "$4,500, calculated as $50 per day for 90 days"]'::jsonb, 0, 'Under IRC Section 6652(c)(1)(A), organizations with gross receipts under $1,186,000 face a penalty of $20 per day for each day the return is late, up to a maximum of the lesser of $10,500 or 5% of gross receipts. For 90 days, the penalty is $20 x 90 = $1,800. Option B is incorrect because the $100-per-day rate applies to larger organizations with gross receipts of $1,186,000 or more, not to organizations with $800,000 in receipts.', 'medium', 3),

-- Q23: medium / L2 — Private benefit vs. private inurement distinction
(3, 'Tax-Exempt Organizations', 'Helping Hands Foundation, a 501(c)(3), awards a $100,000 contract to a construction company owned by the brother-in-law of a board member. The contract price exceeds fair market value by $20,000. The brother-in-law has no formal role with the foundation. Classify this transaction under the private benefit and private inurement doctrines.', '["This is private inurement because the transaction benefits a family member of an insider", "This is neither private benefit nor private inurement because the brother-in-law is not part of the organization", "This is private benefit but not private inurement because the brother-in-law is not a private shareholder or insider of the organization", "This is both private inurement and private benefit because the contract exceeds fair market value"]'::jsonb, 2, 'Under IRC Section 501(c)(3), private inurement applies only to insiders — private shareholders or individuals with a personal and private interest in the organization''s activities. The brother-in-law has no formal role, so private inurement does not apply. However, the excessive private benefit doctrine is broader and prohibits more than incidental benefit to any person, insider or not. Option A is incorrect because private inurement requires a direct insider relationship — indirect family connections without organizational authority do not create insider status.', 'medium', 2),

-- Q24: medium / L2 — Self-dealing additional tax (200% if uncorrected)
(3, 'Tax-Exempt Organizations', 'The Wilson Foundation, a private foundation, leases office space to its founder at below-market rent, constituting self-dealing under Section 4941. The IRS assesses the initial tax, but the founder fails to correct the transaction by the end of the taxable period. What additional tax is imposed on the founder?', '["An additional tax of 100% of the amount involved", "An additional tax of 200% of the amount involved", "An additional tax of 50% of the amount involved, plus a $10,000 flat penalty", "No additional tax, because the initial 10% tax is the only penalty for self-dealing"]'::jsonb, 1, 'Under IRC Section 4941(b), if a self-dealing transaction is not corrected within the taxable period, an additional excise tax of 200% of the amount involved is imposed on the self-dealer. This is separate from the initial 10% tax assessed at the time of the transaction. Option D is incorrect because Section 4941 provides a two-tier penalty structure — the initial 10% tax incentivizes voluntary correction, and the 200% additional tax penalizes failure to correct.', 'medium', 2),

-- Q25: medium / L2 — Disqualified person definition (5-year lookback)
(3, 'Tax-Exempt Organizations', 'Metro Community Foundation, a 501(c)(3), is considering a business transaction with its former president who resigned two years ago. The board believes Section 4958 intermediate sanctions no longer apply because the individual left the organization. Who qualifies as a disqualified person under Section 4958?', '["Only current officers and directors of the organization", "Only individuals who hold more than 5% ownership interest in the organization", "Only current employees earning more than $100,000 annually", "Any person who was in a position of substantial influence over the organization at any time during the five years before the transaction"]'::jsonb, 3, 'Under IRC Section 4958(f)(1), a disqualified person includes any individual who was in a position to exercise substantial influence over the organization''s affairs at any time during the five-year period ending on the date of the transaction. A former president who resigned two years ago remains a disqualified person. Option A is incorrect because the definition extends beyond current officers and directors to include former insiders within the five-year lookback period and their family members.', 'medium', 2),

-- Q26: hard / L4 — Section 509(a)(2) gross receipts test (two-prong)
(3, 'Tax-Exempt Organizations', 'Community Workshop, a 501(c)(3), receives $100,000 in public donations, $150,000 in program-related workshop fees, and $300,000 in gross investment income, totaling $550,000. The board seeks public charity status under Section 509(a)(2), which requires more than one-third support from contributions and related gross receipts, and no more than one-third from investment income and unrelated business income. Evaluate the organization''s classification.', '["Community Workshop fails the Section 509(a)(2) test because investment income ($300,000) exceeds one-third of total support, even though contributions and program fees satisfy the first prong", "Community Workshop qualifies under Section 509(a)(2) because combined contributions and program fees exceed one-third of total support", "Community Workshop fails because program-related workshop fees do not count as gross receipts from related activities", "Community Workshop qualifies because investment income is passive and excluded from the support calculation"]'::jsonb, 0, 'Under IRC Section 509(a)(2), an organization must meet two prongs: (1) more than one-third of support from contributions, membership fees, and related gross receipts, and (2) no more than one-third from gross investment income and UBI. Community Workshop satisfies prong one ($250,000/$550,000 = 45.5%) but fails prong two ($300,000/$550,000 = 54.5% exceeds one-third). Option B is incorrect because meeting the first prong alone is insufficient — both prongs must be satisfied simultaneously.', 'hard', 4),

-- Q27: easy / L1 — Form 8868 extension for Form 990
(3, 'Tax-Exempt Organizations', 'What is the maximum extension of time available for filing Form 990 using Form 8868?', '["Three months", "Four months", "Six months", "Twelve months"]'::jsonb, 2, 'Under IRC Section 6081, Form 8868 provides an automatic extension of up to six months for filing Form 990, Form 990-EZ, Form 990-PF, and Form 990-T. For calendar-year organizations with a May 15 deadline, the extended due date is November 15. Option A is incorrect because the three-month extension period does not apply to exempt organization returns — the full six-month automatic extension is available.', 'easy', 1),

-- Q28: easy / L1 — Recognized exempt purposes under 501(c)(3)
(3, 'Tax-Exempt Organizations', 'Which of the following is a recognized exempt purpose under Section 501(c)(3)?', '["Providing low-interest loans to small business owners", "Prevention of cruelty to children or animals", "Operating a social club for members with common recreational interests", "Promoting the commercial interests of a particular industry"]'::jsonb, 1, 'Under IRC Section 501(c)(3), recognized exempt purposes include religious, charitable, scientific, educational, literary, testing for public safety, fostering amateur sports competition, and prevention of cruelty to children or animals. Option C is incorrect because social clubs are organized under Section 501(c)(7), not 501(c)(3), and serve member recreational interests rather than charitable purposes.', 'easy', 1),

-- Q29: medium / L3 — Section 4940 net investment income tax calculation
(3, 'Tax-Exempt Organizations', 'The Harmon Family Foundation, a private foundation, reports $400,000 in dividend income, $150,000 in capital gains from stock sales, and $60,000 in investment management expenses for the 2025 tax year. Calculate the excise tax on net investment income under Section 4940.', '["$7,645, calculated as 1.39% of gross investment income ($550,000) without deducting expenses", "$9,800, calculated as 2% of net investment income ($490,000)", "$5,560, calculated as 1.39% of dividend income only ($400,000)", "$6,811, calculated as 1.39% of net investment income ($490,000)"]'::jsonb, 3, 'Under IRC Section 4940, private foundations pay a 1.39% excise tax on net investment income, which includes dividends, interest, rents, royalties, and capital gains, minus ordinary and necessary investment expenses. Here, $400,000 dividends plus $150,000 capital gains minus $60,000 expenses equals $490,000, and $490,000 x 1.39% = $6,811. Option C is incorrect because the tax base includes all investment income — capital gains must be included alongside dividends.', 'medium', 3),

-- Q30: medium / L2 — Convenience exclusion application (university laundry)
(3, 'Tax-Exempt Organizations', 'State University, a 501(c)(3), operates a laundry facility on campus that washes linens for university dormitories and also accepts laundry from off-campus customers. The laundry generates $200,000 in revenue — $160,000 from university operations and $40,000 from off-campus customers. How is the laundry income treated under the convenience exclusion?', '["The $160,000 from university operations qualifies for the convenience exclusion, but the $40,000 from off-campus customers is subject to UBIT analysis", "The entire $200,000 is excluded because the laundry is located on campus", "The entire $200,000 is subject to UBIT because laundry services are not related to education", "The $40,000 from off-campus customers is excluded because it is less than 25% of total revenue"]'::jsonb, 0, 'Under IRC Section 513(a)(2), activities conducted for the convenience of students, patients, or employees are excluded from UBIT. The university laundry serving dormitories qualifies for this exclusion. However, the $40,000 from off-campus customers does not serve the university''s constituency and must be analyzed under the standard three-part UBIT test. Option B is incorrect because the convenience exclusion is based on who the activity serves, not merely where it is located.', 'medium', 2)
;

COMMIT;
