-- Migration: Question generation — AUD batch 62 (30 questions)
-- Date: 2026-02-28
-- Topic: Written Representations
-- Difficulty: 9E / 15M / 6H
-- Bloom's: L1:8 / L2:9 / L3:8 / L4:5

BEGIN;

INSERT INTO questions (section_id, topic, stem, choices, correct_index, explanation, difficulty, cognitive_level)
VALUES

-- Q1: easy / L1 — Addressee of the representation letter
(1, 'Written Representations', 'Under AU-C 580, to whom should the management representation letter be addressed?', '["The entity''s board of directors", "The Securities and Exchange Commission", "The auditor or the auditor''s firm", "The entity''s audit committee"]'::jsonb, 2, 'Under AU-C 580, the management representation letter is addressed to the auditor. The letter serves as direct communication from management confirming matters relevant to the financial statements. While the audit committee oversees the engagement, the representation letter is audit evidence directed to the auditor who relies on it to support the audit opinion.', 'easy', 1),

-- Q2: hard / L4 — Evaluating contradictory evidence against written representations
(1, 'Written Representations', 'During the audit of Sterling Capital Partners'' December 31, 2025 financial statements, Breckenridge & Moore CPA obtains documentary evidence contradicting management''s written representation about completeness of related-party disclosures. Management insists the representation is accurate and declines to revise the disclosure. The engagement partner must determine the most appropriate response.', '["Accept the written representation because it constitutes sufficient appropriate audit evidence on its own", "Consider the effect on the reliability of other representations and the audit opinion", "Withdraw from the engagement without performing further procedures", "Request a second representation letter that supersedes the original"]'::jsonb, 1, 'Under AU-C 580.A25, when contradictory evidence exists regarding a written representation, the auditor must investigate and reconsider the reliability of other representations. However, simply accepting the representation or withdrawing without further procedures would both be premature—the auditor should first resolve the inconsistency and evaluate its broader effect on the audit opinion and management''s integrity.', 'hard', 4),

-- Q3: medium / L3 — Analyzing effect of omitting a required representation
(1, 'Written Representations', 'Waverly & Associates is completing the audit of Crestview Dynamics for December 31, 2025. Management provides a signed representation letter but omits the representation about completeness of litigation disclosures. The senior auditor must analyze the effect on the engagement.', '["The omission is a scope limitation that may affect the auditor''s opinion", "The omission has no effect because litigation letters from attorneys are sufficient", "The auditor should add the representation manually and have management initial it", "The omission can be compensated by increasing substantive testing of legal liabilities"]'::jsonb, 0, 'Under AU-C 580.20, if management does not provide one or more requested written representations, the auditor should discuss the matter with management, reevaluate integrity, and determine the effect on the opinion. An omitted required representation constitutes a scope limitation. Attorney letters supplement but do not replace management''s own representations, because management has primary responsibility for completeness of disclosures.', 'medium', 3),

-- Q4: easy / L2 — Applying the dating rule for the representation letter
(1, 'Written Representations', 'Pemberton & Associates completes fieldwork for Oakdale Corp.''s December 31, 2025 audit on February 20, 2026 and issues the audit report dated March 3, 2026. What date should appear on Oakdale''s management representation letter?', '["The balance sheet date of December 31, 2025", "The fieldwork completion date of February 20, 2026", "The date the letter is physically signed by management", "The auditor''s report date of March 3, 2026"]'::jsonb, 3, 'Under AU-C 580.15, the management representation letter should be dated as of the date of the auditor''s report, ensuring management''s representations cover the entire period including subsequent events. While the balance sheet date or fieldwork completion date might seem appropriate, they are too early because events between those dates and the report date must also be covered by management''s representations.', 'easy', 2),

-- Q5: medium / L2 — Representation about reasonableness of accounting estimates
(1, 'Written Representations', 'During the audit of Ridgeview Holdings'' December 31, 2025 financial statements, the engagement team at Collins & Pratt CPA evaluates management''s estimate of the allowance for doubtful accounts. The team requests a specific written representation related to this estimate. Which representation should management provide?', '["Confirmation that the estimate was calculated using the same method as the prior year", "Assurance that the estimate will not require adjustment in subsequent periods", "Acknowledgment that the methods, data, and assumptions used in the estimate are reasonable", "A statement that actual bad debts will not exceed the estimated allowance"]'::jsonb, 2, 'Under AU-C 580.A11, the auditor may request representations about accounting estimates, including that management believes the methods, assumptions, and data used are appropriate and reasonable. However, a representation that the estimate will not require future adjustment is inappropriate because no estimate can provide assurance about future outcomes. Consistency with prior-year methods is also not required when circumstances change.', 'medium', 2),

-- Q6: medium / L2 — Representation about subsequent events through the letter date
(1, 'Written Representations', 'The engagement partner at Dalton & Keyes CPA is finalizing the audit of Brookstone Manufacturing for December 31, 2025. The audit report will be dated March 8, 2026. The partner ensures the representation letter includes a specific statement about events after the balance sheet date. This subsequent events representation should confirm that:', '["No events have occurred since the balance sheet date that would affect any reported amounts", "All events occurring through the representation letter date requiring adjustment or disclosure have been addressed", "Management has independently verified all subsequent events with external legal counsel", "The entity''s operations have continued without material interruption since the balance sheet date"]'::jsonb, 1, 'Under AU-C 580.A15, the representation letter typically includes management''s confirmation that all subsequent events requiring adjustment or disclosure have been properly reflected. Claiming no events occurred would be factually implausible for most entities. Independent verification with legal counsel is not a standard representation requirement, and continued operations relates to going concern rather than subsequent events disclosure.', 'medium', 2),

-- Q7: hard / L4 — Evaluating management competence to provide representations
(1, 'Written Representations', 'During the audit of Pinnacle Aerospace Corp.''s December 31, 2025 financial statements, the engagement partner at Whitfield & Grant CPA discovers that the CEO joined the company in November 2025 and has limited knowledge of transactions from the first ten months. The CFO served the entire year. The partner must evaluate how to obtain adequate written representations for the full fiscal year.', '["Obtain representations only from the CFO since the CEO lacks sufficient knowledge of the period", "Delay issuing the audit report until the CEO has been with the company for at least six months", "Request separate representation letters from each quarter''s responsible officer", "Obtain representations from both officers but consider supplemental representations from other knowledgeable personnel"]'::jsonb, 3, 'Under AU-C 580.09, the auditor requests representations from members of management with appropriate responsibilities and knowledge. Although the CEO has limited knowledge of the full period, the auditor should still obtain representations from both officers and may supplement these with representations from other knowledgeable personnel. Excluding the CEO entirely would not be appropriate because CEO-level operational representations remain required.', 'hard', 4),

-- Q8: hard / L4 — Evaluating a qualified representation letter
(1, 'Written Representations', 'Ashford & Whitmore CPA is auditing Clearfield Technologies'' December 31, 2025 financial statements. Management provides the representation letter but includes a qualification stating, ''To the best of our knowledge and belief, except for the environmental remediation liability, all information is fairly presented.'' The engagement partner must assess the appropriate response.', '["Investigate the reason for the exception, assess its effect on other representations, and determine the impact on the audit opinion", "Accept the qualification because management has a right to limit the scope of their representations", "Issue the audit report with an emphasis-of-matter paragraph referencing the qualification", "Reject the representation letter outright and require an unqualified resubmission before proceeding"]'::jsonb, 0, 'Under AU-C 580.20, when management qualifies a representation, the auditor must investigate the reasons and evaluate the effect on other representations and the audit opinion. However, simply accepting the qualification without investigation overlooks the auditor''s duty to assess management''s integrity. Rejecting the letter outright would also be premature, as the auditor should first evaluate the circumstances before determining the appropriate response.', 'hard', 4),

-- Q9: medium / L3 — Analyzing effect of timing discrepancy on representation letter
(1, 'Written Representations', 'Mercer & Rhodes CPA receives Thornhill Industries'' signed management representation letter on March 15, 2026, but the auditor''s report is dated March 10, 2026. The engagement partner must analyze whether this timing discrepancy affects the audit.', '["The letter is valid because it was signed within five business days of the report date", "The discrepancy has no effect because the letter covers the period through December 31, 2025", "The letter should be dated as of the auditor''s report date, so the partner should request a corrected letter dated March 10, 2026", "The auditor must change the report date to March 15, 2026 to match the representation letter"]'::jsonb, 2, 'Under AU-C 580.15, the representation letter must be dated as of the date of the auditor''s report to ensure continuous coverage. Although the letter was eventually signed, the dates must align. Changing the report date rather than requesting a corrected letter would improperly extend the auditor''s subsequent events responsibilities without cause, making the corrected letter the appropriate solution.', 'medium', 3),

-- Q10: medium / L3 — Analyzing effect of management turnover on representations
(1, 'Written Representations', 'During the audit of Redstone Logistics'' December 31, 2025 financial statements, the CFO who served throughout the year resigns on February 15, 2026. The new CFO starts March 1, 2026, and the audit report is dated March 12, 2026. The audit team at Crawford & Ellis CPA must determine who should sign the representation letter.', '["Only the former CFO, because that person had direct knowledge of the full fiscal year", "The current management including the new CFO, with supplemental representations from the former CFO if needed", "Only the new CFO, because the letter must be signed by current officers at the report date", "The audit committee chair should sign in place of the CFO during the transition"]'::jsonb, 1, 'Under AU-C 580.09, the representation letter should be signed by management with appropriate responsibilities and knowledge as of the report date. The current CEO and new CFO sign because they are the responsible parties when the report is issued. If the new CFO lacks knowledge about certain matters, the auditor may request supplemental representations from the former CFO rather than excluding current management from their obligations.', 'medium', 3),

-- Q11: easy / L1 — Written representations required for every audit
(1, 'Written Representations', 'Under AU-C 580, are written representations from management required for every audit engagement?', '["Only when the auditor identifies material misstatements during testing", "Only for audits of public companies or entities subject to SEC oversight", "Only when management volunteers to provide them to the auditor", "Yes, written representations are required for all audit engagements"]'::jsonb, 3, 'Under AU-C 580.04, written representations are a required element of sufficient appropriate audit evidence for every audit. Unlike other optional procedures that depend on circumstances, the representation letter requirement is unconditional because representations address matters that may not be corroborated through other audit evidence alone, regardless of entity size or public status.', 'easy', 1),

-- Q12: hard / L4 — Evaluating oral representations from a small entity owner
(1, 'Written Representations', 'Kendrick & Shaw CPA is auditing Maple Lane Bakery LLC, a small owner-managed business, for December 31, 2025. The sole owner-manager states that a formal representation letter is unnecessary because all financial information has already been discussed verbally and the auditor has full access to records. The engagement partner must evaluate the most appropriate response.', '["Accept the oral representations because the small entity exception under AU-C 580 permits verbal confirmation", "Waive the written representation requirement given the owner''s full cooperation and transparency", "Explain that written representations are required regardless of entity size and that oral representations are insufficient", "Substitute the signed engagement letter for the representation letter since both document management''s commitments"]'::jsonb, 2, 'Under AU-C 580.04, written representations are required for every audit with no exceptions for entity size. Oral representations do not substitute for written ones because they cannot be retained with the same reliability. Unlike the representation letter, the engagement letter serves a different purpose—defining the terms of the engagement—and does not cover the specific representations about the financial statements required under AU-C 580.', 'hard', 4),

-- Q13: medium / L2 — Representation about noncompliance with laws and regulations
(1, 'Written Representations', 'The audit team at Prescott & Hale CPA is completing the audit of Westbrook Financial Services for December 31, 2025. Westbrook operates in a heavily regulated industry. The team prepares the representation letter to include a compliance-related representation. Management should represent that:', '["All known instances of noncompliance or suspected noncompliance with laws and regulations have been disclosed to the auditor", "The entity is in full compliance with all applicable laws and regulations without exception", "External legal counsel has confirmed that no violations of laws or regulations have occurred", "Management has reviewed every applicable regulation and confirms no violations exist"]'::jsonb, 0, 'Under AU-C 580.11, the representation letter should include management''s acknowledgment that all known instances of noncompliance or suspected noncompliance with laws and regulations have been disclosed. However, management cannot represent absolute compliance because they may be unaware of all violations. The representation focuses on disclosure of known matters rather than a guarantee of full compliance with every applicable law.', 'medium', 2),

-- Q14: medium / L2 — Representation acknowledging uncorrected misstatements are immaterial
(1, 'Written Representations', 'During the audit of Hartley Manufacturing for December 31, 2025, the engagement team at Vaughn & Cole CPA identifies $18,000 in aggregate uncorrected misstatements that management has declined to adjust. Overall materiality is $75,000. The representation letter must address these uncorrected items. Management should represent that:', '["The uncorrected misstatements have been corrected in the subsequent period''s records", "The effects of the uncorrected misstatements are immaterial, individually and in the aggregate, to the financial statements as a whole", "The uncorrected misstatements resulted from accounting system errors that have since been resolved", "The auditor has approved management''s decision not to correct the identified misstatements"]'::jsonb, 1, 'Under AU-C 580.11, when uncorrected misstatements exist, the representation letter must include management''s acknowledgment that the effects are immaterial, both individually and in the aggregate, to the financial statements as a whole. While a summary of uncorrected items is typically attached, the auditor does not approve the decision to leave items uncorrected—management bears sole responsibility for the financial statements and the judgment of immateriality.', 'medium', 2),

-- Q15: medium / L3 — Analyzing whether one letter can cover comparative periods
(1, 'Written Representations', 'Ashford & Beck CPA was engaged to audit both the December 31, 2024 and December 31, 2025 financial statements of Ridgecrest Enterprises in a comparative-year engagement. The senior auditor asks whether one representation letter can cover both periods. The engagement partner must analyze the appropriate approach.', '["Separate representation letters are required for each fiscal year audited", "The letter should cover only the current year because prior-year representations were already obtained", "A single letter may cover both years but must be signed by two different members of management", "A single representation letter may cover both periods provided it addresses all representations applicable to each year"]'::jsonb, 3, 'Under AU-C 580.A21, when comparative financial statements are presented, a single representation letter may cover all periods provided it addresses all required representations for each year. However, covering only the current year would be insufficient because prior-year representations need refreshing—management''s current knowledge may differ from what was known when the original representations were given.', 'medium', 3),

-- Q16: easy / L1 — Definition of written representations
(1, 'Written Representations', 'Under AU-C 580, what are written representations from management?', '["Written statements provided to the auditor to confirm certain matters or support other audit evidence", "Formal legal opinions prepared by the entity''s external counsel for the auditor", "Internal memoranda circulated among the entity''s accounting staff during the audit", "Signed confirmations obtained from third parties at the auditor''s request"]'::jsonb, 0, 'Under AU-C 580.06, written representations are written statements by management provided to the auditor to confirm certain matters or to support other audit evidence. Unlike legal opinions, internal memoranda, or third-party confirmations, written representations originate directly from management and specifically address the auditor''s need for evidence about matters that may not be corroborated by other means.', 'easy', 1),

-- Q17: medium / L2 — Representation about satisfactory title to assets
(1, 'Written Representations', 'The engagement team at Morrison & Blake CPA is preparing the management representation letter for Alpine Property Holdings'' December 31, 2025 audit. Alpine holds a portfolio of commercial real estate. The partner includes a representation addressing the rights and obligations assertion. Management should represent that:', '["All properties have been appraised by independent appraisers within the last twelve months", "The fair market value of all properties exceeds their carrying amounts in the financial statements", "The entity has satisfactory title to all owned assets and all liens or encumbrances have been disclosed", "Property insurance coverage is adequate to cover replacement costs for all holdings"]'::jsonb, 2, 'Under AU-C 580.A12, the auditor may request representations about the rights and obligations assertion, including that the entity has satisfactory title to all owned assets and that all liens or encumbrances have been disclosed. While appraisals address valuation and insurance addresses risk management, neither directly addresses the rights and obligations assertion that title representations are designed to cover.', 'medium', 2),

-- Q18: hard / L4 — Evaluating integrity concerns from a false representation
(1, 'Written Representations', 'During the audit of Lakewood Capital Corp.''s December 31, 2025 financial statements, Hargrove & Dunn CPA discovers that management''s written representation stating no related-party transactions occurred is contradicted by bank records showing a $425,000 loan to the CEO''s spouse''s company. The CFO states it was an oversight. The engagement partner must evaluate the appropriate course of action.', '["Accept the CFO''s explanation and request an amended representation letter reflecting the transaction", "Issue a qualified opinion solely for the related-party disclosure omission", "Document the finding in the management letter and proceed with an unmodified opinion", "Reconsider the reliability of all management representations and assess the effect on the audit as a whole"]'::jsonb, 3, 'Under AU-C 580.A24, when written representations are contradicted by other audit evidence, the auditor must reconsider the reliability of all representations and assess management''s integrity. Although the CFO characterizes the omission as an oversight, a direct contradiction involving a $425,000 undisclosed related-party loan cannot be dismissed without evaluating whether the false representation reflects broader integrity concerns affecting the entire audit.', 'hard', 4),

-- Q19: medium / L2 — Representation about going-concern plans
(1, 'Written Representations', 'Hartwell & Porter CPA is auditing Cascade Retail Inc. for December 31, 2025. The company has experienced declining sales for three consecutive quarters and cash flow concerns have arisen. The partner includes a going-concern representation in the letter. Management should represent that:', '["Management''s plans to mitigate the going-concern conditions have been disclosed to the auditor", "The entity will continue operations for at least twelve months beyond the report date", "External lenders have provided written assurance that all credit facilities will be renewed", "The auditor has evaluated management''s assessment and agrees the entity is a going concern"]'::jsonb, 0, 'Under AU-C 580.A13, when going-concern issues exist, the auditor may request representations about management''s plans and whether those plans have been communicated. However, management cannot guarantee future operations, making an absolute statement about continued operations inappropriate. Lender assurances are separate evidence rather than management representations, and the auditor''s evaluation is not something management represents.', 'medium', 2),

-- Q20: easy / L1 — Consequence of refusing all representations is disclaimer
(1, 'Written Representations', 'Under AU-C 580, what type of opinion results when management refuses to provide any written representations?', '["A qualified opinion due to the material scope limitation", "A disclaimer of opinion due to the pervasive scope limitation", "An adverse opinion due to pervasive misstatements in the statements", "An unmodified opinion with an emphasis-of-matter paragraph added"]'::jsonb, 1, 'Under AU-C 580.20, refusal to provide required written representations prevents the auditor from obtaining sufficient appropriate audit evidence. Unlike a qualified opinion, which addresses material but not pervasive issues, a disclaimer is required because the refusal raises fundamental questions about management''s integrity and the reliability of all evidence obtained, making the scope limitation pervasive.', 'easy', 1),

-- Q21: easy / L1 — Opening paragraph confirms management responsibility
(1, 'Written Representations', 'Under AU-C 580, what does the opening paragraph of the management representation letter typically confirm?', '["That the auditor has completed all planned audit procedures without restriction", "That the entity''s internal controls are operating effectively throughout the period", "That management is responsible for the fair presentation of the financial statements", "That the financial statements have been reviewed and approved by the audit committee"]'::jsonb, 2, 'Under AU-C 580.10, the representation letter begins with management''s acknowledgment of its responsibility for preparation and fair presentation of the financial statements under the applicable framework. Although the audit committee reviews financial statements and the auditor performs procedures, the opening paragraph specifically establishes management''s accountability rather than addressing those separate activities.', 'easy', 1),

-- Q22: medium / L3 — Analyzing implications of receiving the letter after the report date
(1, 'Written Representations', 'Fairfax & Associates CPA issues the audit report for Meridian Corp. on March 5, 2026. Management does not sign and return the representation letter until March 20, 2026. The engagement partner must analyze the implications for the completed audit.', '["The delayed receipt has no effect because the report was already issued with a valid opinion", "The auditor should have obtained the signed letter before issuing the report, and the delayed receipt is a procedural deficiency requiring evaluation", "The representation letter is automatically void because it was not signed by the report date", "The auditor must reissue the report with a revised date of March 20, 2026"]'::jsonb, 1, 'Under AU-C 580.15, the auditor should obtain the signed management representation letter on or before the date of the auditor''s report. However, issuing the report without the signed letter is a departure from professional standards because the auditor lacked required audit evidence when the opinion was formed. The letter is not automatically void, but the procedural deficiency must be evaluated for potential corrective actions.', 'medium', 3),

-- Q23: medium / L3 — Analyzing whether oral assurances substitute for written representations
(1, 'Written Representations', 'During the audit of Northridge Consulting Group for December 31, 2025, the CEO provides detailed verbal assurances about completeness of revenue recognition and related-party transactions but objects to putting these statements in writing. The engagement team at Burke & Pearson CPA must assess the implications.', '["Oral representations do not substitute for written representations, and the refusal is a scope limitation", "Oral representations are acceptable when provided by the CEO because of the CEO''s authority", "The auditor can document the oral assurances in the working papers as an equivalent to written representations", "Oral representations from the CEO are more reliable than a written letter because they are given in real time"]'::jsonb, 0, 'Under AU-C 580.04, written representations are explicitly required and oral representations do not substitute for them because written representations provide more reliable evidence that can be verified and retained. If management refuses to put required representations in writing, AU-C 580.20 treats this as equivalent to not providing the representations, constituting a scope limitation that may lead to a disclaimer of opinion.', 'medium', 3),

-- Q24: easy / L1 — Format of the representation letter
(1, 'Written Representations', 'Under AU-C 580, in what form should management provide written representations to the auditor?', '["As a verbal statement recorded in the audit documentation by the auditor", "As a notarized affidavit filed with the court clerk", "As an addendum attached to the signed engagement letter", "As a letter on the entity''s letterhead addressed to the auditor"]'::jsonb, 3, 'Under AU-C 580.A22, the written representation letter is typically prepared on the entity''s letterhead and addressed to the auditor as a standalone document. Verbal statements do not satisfy the requirement for written representations because they lack the permanence and verifiability needed to serve as reliable audit evidence. Unlike the engagement letter, the representation letter addresses financial statement matters rather than engagement terms.', 'easy', 1),

-- Q25: medium / L2 — Representation about access to records and personnel
(1, 'Written Representations', 'The audit team at Grayson & Walsh CPA is preparing the representation letter for Cedarbrook Industries'' December 31, 2025 audit. The partner ensures the letter includes management''s acknowledgment about providing the auditor with necessary access. Management should represent that:', '["All financial records were maintained in electronic format and backed up to the cloud", "The auditor was provided with access to all information, records, documentation, and personnel relevant to the audit", "The auditor was given unlimited access to the entity''s bank accounts for independent verification", "Management personally reviewed every document provided to the audit team for completeness"]'::jsonb, 1, 'Under AU-C 580.11, the representation letter must include management''s acknowledgment that the auditor was provided with all information relevant to the financial statements and access to all records, documentation, and personnel. Unlike representations about record format or personal document review, this representation specifically covers the completeness of access necessary for the auditor to perform the audit.', 'medium', 2),

-- Q26: medium / L3 — Analyzing whether representations substitute for substantive testing
(1, 'Written Representations', 'A staff auditor on the engagement for Sunridge Properties'' December 31, 2025 audit suggests skipping the accounts payable completeness test because the management representation letter includes a statement that all liabilities have been recorded. The senior auditor at Fletcher & Doyle CPA must assess this approach.', '["The approach is appropriate because management representations are the highest form of audit evidence available", "The approach is appropriate provided the auditor has no reason to question management''s integrity", "The approach is inappropriate because written representations do not substitute for other audit evidence the auditor expects to obtain", "The approach is inappropriate only if the accounts payable balance exceeds performance materiality"]'::jsonb, 2, 'Under AU-C 580.04, written representations are necessary audit evidence but do not substitute for other evidence that the auditor would otherwise expect to obtain. The auditor cannot rely solely on management''s representation to satisfy the completeness assertion when substantive procedures would normally be performed. This applies regardless of management''s integrity, because representations complement rather than replace other evidence.', 'medium', 3),

-- Q27: hard / L3 — Analyzing conflict between representation letter and attorney letter
(1, 'Written Representations', 'During the audit of Ironclad Security Systems for December 31, 2025, Barrett & Knox CPA obtains both the management representation letter and a legal confirmation from outside counsel. The representation letter states no pending litigation exists, but counsel''s response identifies a $2.1 million patent infringement claim filed in October 2025. The partner must analyze the most significant implication of this conflict.', '["The attorney letter takes precedence over the representation letter in all circumstances", "The conflicting information should be disclosed in an emphasis-of-matter paragraph in the report", "The auditor should rely on the representation letter because management has greater knowledge of operations", "The contradiction raises concerns about management''s integrity that may affect the reliability of other representations"]'::jsonb, 3, 'Under AU-C 580.A24, when information conflicts with management''s written representations, the auditor must investigate and reconsider management''s integrity and the reliability of all representations. Although neither the attorney letter nor the representation letter automatically takes precedence, a direct contradiction where management denies a material claim that counsel confirms raises significant integrity concerns extending beyond the individual misstatement.', 'hard', 3),

-- Q28: easy / L1 — Required fraud representation
(1, 'Written Representations', 'Under AU-C 580, what must management represent regarding fraud in the written representation letter?', '["Management''s knowledge of any fraud or suspected fraud affecting the entity", "That no fraud has occurred at any level of the organization during the period", "That the internal audit department has investigated all reported fraud allegations", "That management has purchased fidelity bond coverage for all key employees"]'::jsonb, 0, 'Under AU-C 580.11, the representation letter must include management''s acknowledgment of its responsibility for controls to prevent and detect fraud, and disclosure of any knowledge of fraud or suspected fraud. Management cannot guarantee that no fraud exists, so the representation focuses on knowledge and disclosure rather than absolute assurance about the absence of fraud throughout the organization.', 'easy', 1),

-- Q29: easy / L1 — Signatories of the representation letter
(1, 'Written Representations', 'Under AU-C 580, which members of management should sign the written representation letter?', '["The chief audit executive and the general counsel", "The chief executive officer and the chief financial officer or their equivalents", "All members of the board of directors", "The controller and the head of internal audit"]'::jsonb, 1, 'Under AU-C 580.09, the representation letter should be signed by members of management with appropriate responsibilities and knowledge, typically the CEO and CFO or their equivalents. While the controller and internal audit head play important roles, they are not the senior-most officers whose representations the auditor requires. The board of directors provides governance oversight but does not sign the representation letter.', 'easy', 1),

-- Q30: medium / L2 — Representation requirements in a group audit
(1, 'Written Representations', 'Caldwell & Associates CPA is the group engagement partner for the consolidated audit of Evergreen Holdings and its three subsidiaries for December 31, 2025. The partner must determine the appropriate approach for obtaining written representations across the group. Under AU-C 600, the most appropriate approach is to:', '["Obtain a single representation letter signed by the parent company''s CEO covering all subsidiaries", "Require each subsidiary to submit its own representation letter directly to the group auditor", "Waive representation letters for subsidiaries whose individual financial statements are immaterial to the group", "Obtain a letter from group management for the consolidated statements and, where applicable, from component management for component audits"]'::jsonb, 3, 'Under AU-C 600.40, the group engagement team obtains representations from group management about the consolidated financial statements, while component auditors obtain separate letters from component management for significant component audits. A single parent letter may not address subsidiary-specific matters, and unlike immaterial balances in other contexts, immateriality does not waive the representation requirement where component audits are performed.', 'medium', 2)
;

COMMIT;
