-- Migration: Question generation — AUD batch 64 (30 questions)
-- Date: 2026-03-01
-- Topic: Written Representations
-- Difficulty: 9E / 15M / 6H
-- Bloom's: L1:8 / L2:9 / L3:8 / L4:5

BEGIN;

INSERT INTO questions (section_id, topic, stem, choices, correct_index, explanation, difficulty, cognitive_level)
VALUES

-- Q1: medium / L2 — Representation about completeness of recorded transactions
(1, 'Written Representations', 'During the 2025 audit of Crestline Distributors, the engagement partner at Kellerman & Shaw CPAs reviews the draft management representation letter. The controller asks which representation addresses whether all transactions have been properly captured. Under AU-C 580, which required representation specifically addresses transaction completeness?', '["Management has provided complete information about side agreements with customers", "Management has recorded all transactions in the correct reporting period", "All transactions have been recorded and are reflected in the financial statements", "Management has disclosed all known instances of non-compliance with laws"]'::jsonb, 2, 'Under AU-C 580.11, management must represent that all transactions have been recorded and are reflected in the financial statements. This completeness assertion ensures nothing material has been omitted. While choice B references recording in the correct period (a cutoff concern), the completeness representation in AU-C 580 addresses whether transactions were captured at all, not merely their timing.', 'medium', 2),

-- Q2: medium / L2 — Representation about selection and application of accounting policies
(1, 'Written Representations', 'Thornberry Manufacturing''s CFO asks the audit team at Langford & Price whether the management representation letter must address the company''s choice of depreciation methods and revenue recognition policies. Under AU-C 580, the representation letter should include a statement that management acknowledges responsibility for:', '["The design and maintenance of internal controls over financial reporting", "The selection and application of accounting policies that are appropriate in the circumstances", "The accuracy of all computations in the financial statements", "The prevention and detection of all fraud within the organization"]'::jsonb, 1, 'Under AU-C 580.10, management must represent that accounting policies selected and applied are appropriate in the circumstances under the applicable financial reporting framework. This covers choices like depreciation methods, revenue recognition, and inventory costing. While choice A (internal controls) is also a required representation, it addresses a different obligation than accounting policy selection.', 'medium', 2),

-- Q3: medium / L2 — Uncorrected misstatements and management's materiality conclusion
(1, 'Written Representations', 'During the 2025 audit of Redwood Financial Services, the auditor at Parkfield & Associates communicates $18,000 in uncorrected misstatements to management. Management declines to correct them, citing immateriality. Under AU-C 580, what must the representation letter include regarding these uncorrected misstatements?', '["A statement that management will correct all misstatements in the subsequent period", "A detailed schedule of every audit adjustment proposed during the engagement", "An acknowledgment that management was informed of all uncorrected misstatements", "A statement that management believes the uncorrected misstatements are immaterial individually and in the aggregate"]'::jsonb, 3, 'Under AU-C 580.11, management must represent that the effects of uncorrected misstatements are immaterial, both individually and in the aggregate, to the financial statements as a whole. A schedule of the uncorrected misstatements should be attached to the letter. While choice C is partially correct, the specific required representation goes further by affirming management''s materiality conclusion, not merely acknowledging notification.', 'medium', 2),

-- Q4: easy / L1 — Format of the management representation letter
(1, 'Written Representations', 'What is the required format for management''s written representations under AU-C 580?', '["A written letter addressed to the auditor", "An oral statement recorded in the audit documentation", "A sworn affidavit notarized by a third party", "A standardized form prescribed by the AICPA"]'::jsonb, 0, 'Under AU-C 580.15, written representations must be in the form of a representation letter addressed to the auditor. Oral representations alone are insufficient because they lack the formality and permanence of written documentation. While choice D might seem plausible, AU-C 580 does not prescribe a standardized form; the letter is tailored to each engagement.', 'easy', 1),

-- Q5: easy / L1 — Management's responsibility for fair presentation
(1, 'Written Representations', 'Which representation in the management representation letter acknowledges management''s core financial reporting obligation?', '["Management has maintained adequate insurance coverage for all assets", "Management has complied with all debt covenants during the period", "Management acknowledges responsibility for the fair presentation of the financial statements", "Management has disclosed all compensating balance arrangements"]'::jsonb, 2, 'Under AU-C 580.10, management must explicitly acknowledge its responsibility for the preparation and fair presentation of the financial statements in accordance with the applicable financial reporting framework. This is a foundational representation. While choice A (insurance coverage) and choice B (debt covenants) may be relevant operational matters, they are not required representations about financial reporting responsibility under AU-C 580.', 'easy', 1),

-- Q6: hard / L3 — Contradictory evidence vs. written representations
(1, 'Written Representations', 'During the audit of Hawthorne Industrial Corp. for the year ended December 31, 2025, the auditor at Sinclair & Whitmore obtains a signed representation letter stating that all related party transactions have been disclosed. However, during subsequent procedures, the auditor discovers a $2.1 million loan to the CEO''s brother-in-law that was not disclosed. What is the most likely effect of this contradictory evidence on the auditor''s assessment?', '["The auditor should accept the representation letter since it was signed before the discovery", "The auditor should question the reliability of all management representations and reconsider whether the engagement can continue", "The auditor should issue an unmodified opinion with an emphasis-of-matter paragraph", "The auditor should request a revised representation letter correcting only the related party omission"]'::jsonb, 1, 'Under AU-C 580.19, if the auditor has concerns about the reliability of written representations or if representations are inconsistent with other audit evidence, the auditor must reconsider the reliability of all representations. A direct contradiction on related parties raises doubt about management''s integrity. Although choice D (requesting a revised letter) may seem reasonable, it is insufficient because the concern extends beyond one omission to the overall trustworthiness of management''s representations.', 'hard', 3),

-- Q7: medium / L3 — Going concern representations and effect on audit procedures
(1, 'Written Representations', 'Birchwood Electronics Inc. is experiencing significant cash flow difficulties for its 2025 fiscal year. Management provides the auditor at Fletcher & Grant with representations about its plans to mitigate going concern issues, including a planned equity raise and cost reductions. How would these going concern representations most likely affect the auditor''s planned procedures?', '["The auditor would reduce substantive testing because management has provided specific remediation plans", "The auditor would eliminate the need to evaluate management''s going concern assessment", "The auditor would discontinue the engagement due to the inherent uncertainty", "The auditor would evaluate the feasibility of management''s plans and obtain corroborating evidence for the stated remediation actions"]'::jsonb, 3, 'Under AU-C 570.16 and AU-C 580.11, when management provides representations about going concern plans, the auditor must evaluate whether those plans are feasible and whether supporting evidence exists. Written representations about future actions do not substitute for corroborating evidence. Choice A is incorrect because representations about plans do not reduce the need for substantive procedures; they increase the auditor''s obligation to investigate.', 'medium', 3),

-- Q8: hard / L4 — Group audit: component management representations
(1, 'Written Representations', 'Greystone Holdings has three wholly owned subsidiaries audited by different component auditors. The group engagement partner at Merritt & Associates is determining whether to require separate management representation letters from each subsidiary''s management in addition to the consolidated representation letter. The subsidiary in Country X has a history of regulatory issues. Evaluate the most appropriate approach for obtaining representations in this group audit.', '["The group auditor should obtain a representation letter from group management that covers all components, and request separate letters from component management where specific risks have been identified at individual components", "The group auditor should rely solely on the component auditors to obtain their own representation letters", "The group auditor should require identical representation letters from all three subsidiaries regardless of risk", "The group auditor should accept the consolidated representation letter and forgo component-level letters entirely"]'::jsonb, 0, 'Under AU-C 600.40, the group engagement partner should obtain representations from group management covering the consolidated financial statements. For components with identified risks, such as regulatory concerns in Country X, separate representations from component management provide additional assurance. However, choice D is incorrect because it ignores the heightened risk at the Country X subsidiary that warrants specific component-level representations.', 'hard', 4),

-- Q9: medium / L3 — Period covered by representations
(1, 'Written Representations', 'Midland Consulting Group''s December 31, 2025 audit is its first year under audit. The engagement partner at Draper & Keane notes that certain representations in the management letter are period-specific while others cover all periods presented. How does the distinction between period-specific and all-periods representations most likely affect the content of the letter for a first-year audit?', '["All representations should be limited to only the current year under audit", "The auditor should decline to include any representations about prior periods", "Representations about matters such as completeness of transactions cover all periods presented, while representations about specific events may be limited to the period under audit", "The representation letter should cover only the balance sheet date and not the full reporting period"]'::jsonb, 2, 'Under AU-C 580.14, written representations cover all periods referred to in the auditor''s opinion. Representations about completeness of information and fraud apply to all periods presented. However, certain event-specific representations may be limited to the period under audit. Choice A is incorrect because AU-C 580 requires that representations cover all periods for which an opinion is expressed, not merely the current year.', 'medium', 3),

-- Q10: easy / L1 — Written representations complement but don't substitute
(1, 'Written Representations', 'Under AU-C 580, written representations from management are best described as which type of audit evidence?', '["The primary source of audit evidence that supersedes all other forms", "Necessary audit evidence that complements, but does not substitute for, other audit procedures", "Optional evidence that the auditor may request at its discretion", "External evidence obtained from a third party independent of management"]'::jsonb, 1, 'Under AU-C 580.04, written representations are necessary information the auditor requires from management in connection with the audit. However, they complement other audit evidence and do not replace substantive testing or other procedures. Choice A is incorrect because no single form of evidence supersedes all others; the auditor must corroborate representations through other procedures.', 'easy', 1),

-- Q11: hard / L4 — Successor auditor discovers missing items in prior-year representation letter
(1, 'Written Representations', 'Ashford & Connelly CPAs is performing the 2025 audit of Summit Ridge Corp., a new client. While reviewing the predecessor auditor''s workpapers, the engagement partner discovers that the prior-year representation letter omitted the required fraud representation and the related party representation. Management asserts no fraud or undisclosed related party transactions existed. Evaluate the most appropriate course of action.', '["Accept management''s verbal assurance and proceed with the current-year audit without further action", "Withdraw from the engagement because the prior-year deficiency indicates unreliable management", "Require the current-year representation letter to cover all periods for which an opinion is expressed, including specific representations about fraud and related parties for the prior period presented in comparative financial statements", "Issue a disclaimer on the prior-year comparative statements and an unmodified opinion on the current year"]'::jsonb, 2, 'Under AU-C 580.14, written representations cover all periods referred to in the auditor''s report. When comparative financial statements are presented, the successor auditor should obtain representations covering all periods for which an opinion is issued. Although choice B (withdrawal) might seem warranted, omissions in the prior-year letter do not necessarily indicate management unreliability; rather than withdrawing, the successor auditor should obtain complete representations for all presented periods in the current engagement.', 'hard', 4),

-- Q12: easy / L1 — Representation about access to all records
(1, 'Written Representations', 'What does the management representation letter typically confirm regarding the auditor''s access to information?', '["Management has provided the auditor with access to all information relevant to the preparation of the financial statements", "Management has provided the auditor with access to external legal counsel", "Management has provided the auditor with access to competitor financial data", "Management has provided the auditor with access to the board''s executive session minutes"]'::jsonb, 0, 'Under AU-C 580.11, management must represent that it has provided the auditor with all information relevant to the financial statements, including access to records, documentation, and personnel. This ensures the auditor can obtain sufficient appropriate evidence. However, choice D is incorrect because it is too narrow; the required representation broadly covers all relevant information, not just specific documents like board minutes.', 'easy', 1),

-- Q13: easy / L2 — Who has appropriate knowledge to sign after CFO departure
(1, 'Written Representations', 'At Pinehurst Capital Advisors, the CEO and CFO are named in the audit engagement letter. The CFO resigned on January 15, 2026, and the auditor''s report date is February 20, 2026. The interim controller has been managing the finance function since the CFO''s departure. Under AU-C 580, who should sign the management representation letter?', '["Only the CEO, since the CFO has resigned", "The CEO and the interim controller, as the individual with appropriate knowledge of the matters covered", "The board chair and the audit committee chair", "The former CFO, since that individual was in place during the audit period"]'::jsonb, 1, 'Under AU-C 580.19, the representation letter should be signed by members of management with appropriate knowledge of the matters addressed. When the CFO has departed, the individual currently responsible for financial matters (the interim controller) should sign alongside the CEO. Choice D is incorrect because the former CFO no longer has authority to represent the entity as of the date of the auditor''s report.', 'easy', 2),

-- Q14: easy / L1 — Representation about compliance with laws and regulations
(1, 'Written Representations', 'Which representation addresses potential legal violations in the management representation letter?', '["Management has retained qualified legal counsel for all litigation matters", "Management has purchased directors and officers liability insurance", "Management has disclosed all known instances of non-compliance with laws and regulations", "Management has obtained regulatory approval for all new products"]'::jsonb, 2, 'Under AU-C 580.11, management must represent that it has disclosed all known instances of non-compliance or suspected non-compliance with laws and regulations whose effects should be considered when preparing the financial statements. While choice A (retaining counsel) may be a prudent business practice, it addresses a different matter and is not a required representation under AU-C 580.', 'easy', 1),

-- Q15: medium / L3 — Effect of omitting a specific representation on the audit report
(1, 'Written Representations', 'During the audit of Clarkson Manufacturing for the year ended December 31, 2025, management provides a signed representation letter but specifically excludes the representation about completeness of related party disclosures, citing ongoing litigation concerns. The auditor at Pemberton & Ross has performed extensive related party testing and found no undisclosed transactions. How would this omission most likely affect the audit report?', '["The auditor should consider this a scope limitation and evaluate whether a qualified opinion or disclaimer is appropriate, regardless of alternative evidence obtained", "The auditor should issue an unmodified opinion because alternative procedures produced satisfactory results", "The auditor should add an emphasis-of-matter paragraph but leave the opinion unmodified", "The auditor should withdraw from the engagement immediately"]'::jsonb, 0, 'Under AU-C 580.20, if management does not provide one or more of the requested written representations, the auditor must discuss the matter with management, reevaluate integrity, and determine the effect on the opinion. A refusal to provide a required representation constitutes a scope limitation even if alternative evidence is obtained, because it raises concerns about management reliability. Choice B is incorrect because alternative testing alone cannot overcome a refusal to provide a required representation.', 'medium', 3),

-- Q16: medium / L2 — Representation about litigation, claims, and assessments
(1, 'Written Representations', 'Waverly Corp. is involved in three pending lawsuits totaling $4.5 million as of December 31, 2025. The engagement team at Howard & Blaine CPAs drafts the management representation letter and includes a litigation-related representation. Under AU-C 580, management''s representation about litigation should state that management has disclosed:', '["The names of all attorneys retained by the entity during the year", "The estimated settlement amounts for each pending lawsuit", "The identity of the entity''s insurance carriers and policy limits", "All known actual or possible litigation, claims, and assessments whose effects should be considered in the financial statements"]'::jsonb, 3, 'Under AU-C 580.11, management must represent that it has disclosed all known actual or possible litigation, claims, and assessments whose effects should be considered when preparing financial statements. This ensures the auditor has complete information for evaluating contingencies. Although choice B (estimated settlement amounts) addresses valuation, it does not satisfy the completeness of disclosure required by the representation.', 'medium', 2),

-- Q17: hard / L4 — Management qualifies a representation about significant estimates
(1, 'Written Representations', 'Summit Creek Financial''s management provides a representation letter for the 2025 audit that includes the qualification: "To the best of our knowledge, the assumptions used in the loan loss reserve estimate are reasonable, except that we cannot assess the impact of certain macroeconomic factors beyond our control." The loan loss reserve is $8.7 million, material to the financial statements. The auditor at Caldwell & Baines must evaluate this qualified representation. What is the most appropriate response?', '["Accept the qualified representation because management has disclosed its limitation transparently", "Evaluate whether the qualification creates a scope limitation and assess whether sufficient appropriate audit evidence about the estimate can be obtained through other procedures", "Issue a disclaimer of opinion solely because management qualified one representation", "Remove the estimate from the financial statements and restate the balance sheet"]'::jsonb, 1, 'Under AU-C 580.20, when management qualifies or limits a representation, the auditor should evaluate the reason and determine whether the qualification constitutes a scope limitation. The auditor should assess whether the limitation can be overcome through alternative evidence. Choice A is incorrect because simply accepting a qualified representation without evaluating its impact fails to exercise professional skepticism, and choice C is excessive since a single qualification does not automatically require a disclaimer.', 'hard', 4),

-- Q18: hard / L4 — Those charged with governance contradict management's representations
(1, 'Written Representations', 'During the audit of Ironwood Development Corp. for 2025, the auditor at Stratton & Paige obtains the signed management representation letter stating no material related party transactions are undisclosed. However, during a private conversation, the audit committee chair mentions a significant loan guarantee the CEO provided to a business owned by the CEO''s spouse that management did not disclose. Evaluate the auditor''s best course of action.', '["Document the conversation but rely on the signed representation letter as the authoritative source", "Request management to review and correct the financial statement disclosures and the representation letter", "Evaluate the inconsistency, discuss the matter with management, assess the reliability of all management representations, and consider the implications for the auditor''s report", "Report the CEO directly to the SEC for concealing related party transactions"]'::jsonb, 2, 'Under AU-C 580.19 and AU-C 240.35, when contradictory evidence from those charged with governance challenges management''s representations, the auditor must investigate the inconsistency, reassess the reliability of all representations, and determine the impact on the audit. While choice B (requesting corrections) may be a step in the process, it is too narrow because it assumes management will cooperate without addressing the deeper integrity concern. The auditor must consider whether the contradiction affects the ability to rely on management representations overall.', 'hard', 4),

-- Q19: easy / L1 — Representation about controls to prevent and detect fraud
(1, 'Written Representations', 'What must management represent regarding internal controls and fraud under AU-C 580?', '["Management acknowledges responsibility for the design, implementation, and maintenance of internal control relevant to preparing financial statements free from material misstatement due to fraud", "Management asserts that no fraud has occurred at any level during the period under audit", "Management certifies that all employees have undergone background checks", "Management warrants that the internal audit function has tested all fraud controls"]'::jsonb, 0, 'Under AU-C 580.10-11, management must acknowledge responsibility for the design, implementation, and maintenance of internal control to prevent and detect fraud. This representation recognizes management''s foundational role in the control environment. However, choice B is incorrect because management cannot assert the complete absence of fraud; the representation addresses responsibility for controls, rather than a warranty against occurrence.', 'easy', 1),

-- Q20: hard / L4 — Reissuance of representation letter for regulatory filing
(1, 'Written Representations', 'Prescott & Hall CPAs issued the audit report for Cascade Logistics on March 1, 2026, covering the December 31, 2025 financial statements. On April 15, 2026, Cascade requests that the auditor reissue the report for a regulatory filing. Between March 1 and April 15, Cascade restated a $320,000 inventory error now considered material in the aggregate. Evaluate the appropriate representation letter requirement for the reissuance.', '["The auditor should rely on the original March 1 representation letter without modification", "The auditor should obtain only a verbal confirmation that nothing else has changed since March 1", "The auditor should request an updated representation letter that addresses only events after the restatement", "The auditor should obtain a new representation letter dated as of the reissue date addressing subsequent events and changes since the original report date, including the restatement"]'::jsonb, 3, 'Under AU-C 580.14 and AU-C 560.14, when reissuing an audit report, the auditor should obtain an updated representation letter covering the period through the reissue date. Given the restatement, the new letter must address changes since the original report date. Although choice C mentions updating for events after the restatement, it is incorrect because it fails to require a letter dated as of the new report date covering the full subsequent period.', 'hard', 4),

-- Q21: medium / L3 — Effect of obtaining representation letter after the report date
(1, 'Written Representations', 'The auditor at Henley & Crawford completes the audit of Willowbrook Inc. and dates the report March 10, 2026. Due to a scheduling conflict, the signed management representation letter is not received until March 15, 2026. How does the timing discrepancy between the report date and the representation letter date most likely affect the engagement?', '["The auditor should backdate the representation letter to match the March 10 report date", "The auditor should consider revising the report date to March 15, or obtain representations dated March 10 with a supplemental representation covering March 10 through March 15", "The engagement is invalid and must be restarted from the planning phase", "The auditor should issue the report without the signed representation letter and document the delay"]'::jsonb, 1, 'Under AU-C 580.15, the representation letter should be dated no earlier than the date of the auditor''s report. If the letter is received after the report date, the auditor should either revise the report date or obtain a letter dated as of the original report date with supplemental coverage through receipt date. While choice A (backdating) might seem expedient, it is inappropriate because it falsifies the date on which management actually signed. Choice D is incorrect because issuing a report without the required signed letter violates AU-C 580.', 'medium', 3),

-- Q22: medium / L2 — Additional (non-standard) representations
(1, 'Written Representations', 'While auditing Northgate Renewable Energy for 2025, the engagement partner at Grayson & Beck identifies significant carbon credit trading activity with complex valuation issues. The partner decides to request additional representations beyond the standard AU-C 580 requirements. Under AU-C 580, when may the auditor request additional written representations from management?', '["The auditor may request additional representations when necessary to support other audit evidence relevant to the financial statements or specific assertions", "The auditor may only request representations specifically listed in AU-C 580", "The auditor may request additional representations only if the client is publicly traded", "The auditor may request additional representations only after obtaining approval from the peer review committee"]'::jsonb, 0, 'Under AU-C 580.13, the auditor may request additional written representations about the financial statements beyond the minimum requirements, particularly when the entity has unique transactions or complex areas requiring management''s acknowledgment. Choice B is incorrect because AU-C 580 explicitly allows the auditor to request representations tailored to the engagement''s specific risks and circumstances.', 'medium', 2),

-- Q23: easy / L1 — Representation about related party disclosure completeness
(1, 'Written Representations', 'Under AU-C 580, what must management represent about related party transactions?', '["Management has conducted arm''s-length pricing studies for all related party sales", "Management has eliminated all intercompany balances in the financial statements", "Management has disclosed all known related parties and all related party relationships and transactions", "Management certifies that no officer or director has any outside business interests"]'::jsonb, 2, 'Under AU-C 580.11, management must represent that it has disclosed the identity of all related parties and all related party relationships and transactions of which it is aware. This ensures the auditor has complete information to evaluate disclosure requirements. While choice A addresses pricing methodology, it is incorrect because it covers a separate concern from the completeness of disclosure required by the representation.', 'easy', 1),

-- Q24: medium / L2 — Representations specific to estimates and fair values
(1, 'Written Representations', 'Brookfield Properties reports a $12.4 million investment property portfolio measured at fair value for its December 31, 2025 financial statements. The auditor at Everett & Walsh requests specific representations about the fair value measurements. Under AU-C 580, management''s representation about significant accounting estimates should state that:', '["Management has engaged an independent appraiser for every fair value measurement", "Management has compared all estimates to competitor valuations for reasonableness", "Management has restricted all assumptions to observable market inputs only", "The methods, significant assumptions, and data used in making the accounting estimates are appropriate in the context of the applicable financial reporting framework"]'::jsonb, 3, 'Under AU-C 580.11, when significant accounting estimates exist, management should represent that the methods, assumptions, and data are appropriate within the applicable financial reporting framework. This is especially important for fair value measurements involving judgment. Choice C is incorrect because many estimates legitimately use unobservable inputs (Level 3 fair values), and restricting assumptions to observable inputs only would be factually inaccurate.', 'medium', 2),

-- Q25: medium / L3 — Management turnover mid-audit impact on representations
(1, 'Written Representations', 'During the 2025 audit of Westshore Manufacturing, the CFO who oversaw financial reporting from January through September resigns in October. A new CFO starts on November 1 and has limited knowledge of transactions in the first three quarters. Analyze how this management turnover most likely affects the auditor''s approach to obtaining written representations.', '["The auditor should obtain representations from the new CFO covering the full year, supplemented by additional audit procedures to address gaps in the new CFO''s knowledge of first-three-quarter transactions", "The auditor should obtain two separate representation letters, one from each CFO", "The auditor should delay the audit until the new CFO has been in the role for at least six months", "The auditor should eliminate the CFO''s signature requirement and have only the CEO sign"]'::jsonb, 0, 'Under AU-C 580.19, the representation letter should be signed by management members with appropriate knowledge. When a new CFO has limited knowledge of earlier periods, the auditor should have the new CFO sign but perform additional procedures to compensate for the knowledge gap. However, choice B (two separate letters) is incorrect because the former CFO no longer has authority to represent the entity, and choice D removes a valuable signatory without addressing the knowledge concern.', 'medium', 3),

-- Q26: medium / L2 — Representations in review engagement vs. audit
(1, 'Written Representations', 'Rivera & Associates CPAs is performing a review engagement for Sandstone Medical Group under AR-C 90 for the year ended December 31, 2025. The practitioner drafts a management representation letter. How do the representation requirements for a review engagement compare to those in an audit under AU-C 580?', '["Review engagements do not require any written representations from management", "Review engagements require written representations similar in nature to audit representations, including management''s responsibility for the financial statements and completeness of information provided", "Review engagements require more extensive representations than audits because less assurance is provided", "Review engagement representations must be signed by all members of the board of directors"]'::jsonb, 1, 'Under AR-C 90.34, review engagements also require written representations from management, including acknowledgment of responsibility for the financial statements and completeness of information provided. While the scope of a review is narrower than an audit, the core representation requirements are similar. Choice A is incorrect because AR-C 90 explicitly requires management representations as a prerequisite for completing the review engagement.', 'medium', 2),

-- Q27: medium / L3 — Verbal vs. written representations and impact on evidence
(1, 'Written Representations', 'During the 2025 audit of Edgewater Technologies, the CEO verbally assures the engagement partner at Copeland & Marsh that all contingent liabilities have been disclosed but refuses to include this specific representation in the written letter, stating it is redundant with the general completeness representation. Analyze the effect of this refusal on the auditor''s evidence.', '["The verbal assurance provides the same level of evidence as a written representation", "The auditor should accept the general completeness representation as adequate coverage for contingent liabilities", "The refusal to provide the specific written representation about contingent liabilities should be treated as a potential scope limitation, because oral representations do not provide the same level of evidence as written ones", "The auditor should instruct the CEO to consult legal counsel before signing the letter"]'::jsonb, 2, 'Under AU-C 580.08 and .20, written representations provide more reliable evidence than oral statements because they formalize management''s acknowledgment and can be retained in the audit file. A refusal to put a specific representation in writing raises concerns about management''s willingness to accept responsibility. Choice A is incorrect because AU-C 580 distinguishes between oral and written representations, treating written forms as more reliable evidence.', 'medium', 3),

-- Q28: medium / L2 — Subsequent events representation in the letter
(1, 'Written Representations', 'The auditor at Sterling & Parker issues the audit report for Oakmont Financial Services on March 8, 2026, covering the December 31, 2025 financial statements. The draft representation letter includes a paragraph about subsequent events. Under AU-C 580, what should management''s subsequent events representation specifically address?', '["Management has monitored the entity''s stock price daily since year-end", "Management acknowledges that no events occurred between year-end and the audit report date", "Management has disclosed the results of the most recent board meeting", "Management has disclosed all events occurring between the balance sheet date and the date of the representation letter that require adjustment of or disclosure in the financial statements"]'::jsonb, 3, 'Under AU-C 580.11 and AU-C 560, management should represent that it has informed the auditor of all subsequent events occurring between the balance sheet date and the representation letter date that require adjustment or disclosure. Choice B is incorrect because the representation requires disclosure of events that occurred, not a blanket statement that nothing happened, which would rarely be accurate.', 'medium', 2),

-- Q29: medium / L3 — Arms-length related party pricing representation and further testing
(1, 'Written Representations', 'Ridgecrest Manufacturing''s management provides a representation that all related party transactions were conducted at arm''s-length terms for the 2025 audit. The auditor at Lancaster & Webb notes $3.8 million in sales to an entity owned by the CEO''s brother at prices 15% below market. Analyze how this representation affects the auditor''s further procedures.', '["The signed representation about arm''s-length pricing obligates the auditor to perform additional procedures to test the assertion, given the observable contradiction between the representation and the pricing data", "The representation eliminates the need for further testing of related party pricing", "The auditor should accept the representation because management has the best knowledge of pricing decisions", "The auditor should immediately withdraw from the engagement upon discovering the pricing discrepancy"]'::jsonb, 0, 'Under AU-C 580.04 and AU-C 550.22, written representations do not replace substantive procedures. When observable evidence (15% below-market pricing) contradicts management''s arm''s-length assertion, the auditor must perform additional procedures to resolve the inconsistency. Choice B is incorrect because written representations complement but do not substitute for other audit evidence, especially when contradictory indicators exist.', 'medium', 3),

-- Q30: easy / L1 — Representation that financial records were made available
(1, 'Written Representations', 'Under AU-C 580, which of the following is a required written representation from management regarding audit access?', '["Management has appointed a liaison to coordinate all auditor requests", "Management has made all financial records and related data available to the auditor", "Management has pre-approved all audit procedures before execution", "Management has provided read-only access to the general ledger system"]'::jsonb, 1, 'Under AU-C 580.11, management must represent that it has made all financial records and related data available to the auditor, as agreed in the terms of the engagement. This ensures unrestricted access to the information necessary for the audit. While choice D refers to system access, it is incorrect because the required representation covers all financial records broadly, rather than just read-only access to the general ledger.', 'easy', 1)
;

COMMIT;
