-- Migration: Question generation — FAR batch 12 (30 questions)
-- Date: 2026-02-28
-- Topic: Earnings Per Share
-- Difficulty: 9E / 15M / 6H
-- Bloom's: L1:8 / L2:9 / L3:8 / L4:5

BEGIN;

INSERT INTO questions (section_id, topic, stem, choices, correct_index, explanation, difficulty, cognitive_level)
VALUES

-- Q1: medium / L2 — Two-class method for participating securities
(2, 'Earnings Per Share', 'Glendale Industries has net income of $900,000 and 200,000 weighted-average common shares outstanding. The company also has 50,000 shares of participating preferred stock that share equally in dividends with common stock after receiving a $2 per share base dividend. Using the two-class method under ASC 260, what is basic EPS attributable to common shareholders?', '["$4.50", "$3.60", "$3.20", "$2.80"]'::jsonb, 2, 'Under ASC 260-10-45-61A, when an entity has participating securities, it must use the two-class method for basic EPS. First, $100,000 of base preferred dividends ($2 x 50,000) is deducted, leaving $800,000 of undistributed earnings. These are allocated proportionally: common gets 200,000/250,000 = 80%, or $640,000. Common EPS = ($640,000) / 200,000 = $3.20. Choice A ($4.50) is incorrect because it ignores the preferred participation in undistributed earnings.', 'medium', 2),

-- Q2: hard / L4 — Evaluate convertible instruments issued mid-year for diluted EPS
(2, 'Earnings Per Share', 'Harrington Corp. reports net income of $1,200,000 with 300,000 weighted-average common shares. On July 1, the company issued $500,000 of 8% convertible bonds, each $1,000 bond convertible into 20 shares. The tax rate is 25%. The CFO must determine whether to include these bonds in diluted EPS and how to weight them. Evaluate the correct treatment under ASC 260.', '["Include for full year: add $40,000 after-tax interest and 10,000 shares", "Include for half year: add $15,000 after-tax interest and 5,000 shares", "Exclude because the bonds are antidilutive", "Include for half year: add $20,000 after-tax interest and 5,000 shares"]'::jsonb, 1, 'Under ASC 260-10-45-40, convertible securities issued during the period are weighted from the issue date. The bonds were outstanding 6 months, so 500 bonds x 20 shares x 6/12 = 5,000 incremental shares. The after-tax interest add-back is $500,000 x 8% x 6/12 x (1 - 0.25) = $15,000. However, Choice D incorrectly uses $20,000 pre-tax instead of the after-tax amount, omitting the required tax adjustment.', 'hard', 4),

-- Q3: easy / L1 — Complex capital structure definition
(2, 'Earnings Per Share', 'Under ASC 260, which of the following defines a complex capital structure?', '["A capital structure that includes outstanding dilutive securities", "A capital structure with more than two classes of stock", "A capital structure with both short-term and long-term debt", "A capital structure with retained earnings exceeding paid-in capital"]'::jsonb, 0, 'Under ASC 260-10-15-2, a complex capital structure exists when an entity has outstanding securities that could dilute basic EPS, such as convertible bonds, stock options, or warrants. An entity with a complex capital structure must present both basic and diluted EPS. Choice B is incorrect because multiple stock classes alone do not create a complex capital structure unless those securities are potentially dilutive.', 'easy', 1),

-- Q4: easy / L1 — Treasury stock method assumptions about proceeds
(2, 'Earnings Per Share', 'Under ASC 260, the treasury stock method for stock options assumes that exercise proceeds are used to:', '["Pay off outstanding debt", "Fund capital expenditures", "Distribute additional dividends to shareholders", "Repurchase common shares at the average market price"]'::jsonb, 3, 'Under ASC 260-10-45-29, the treasury stock method assumes that proceeds from the exercise of options and warrants are used to repurchase common shares at the average market price during the period. This determines the net incremental shares added to the denominator. Choice A is incorrect because the method does not assume proceeds reduce debt.', 'easy', 1),

-- Q5: medium / L2 — Retroactive restatement of EPS for post-period stock split
(2, 'Earnings Per Share', 'Pembrook Textiles reported basic EPS of $6.00 for the year ended December 31, 2025, based on net income of $1,800,000 and 300,000 weighted-average shares. On February 15, 2026, before the financial statements were issued, the company declared a 2-for-1 stock split. What basic EPS should Pembrook report for 2025?', '["$6.00", "$3.00", "$12.00", "$4.50"]'::jsonb, 1, 'Under ASC 260-10-55-12, stock splits and stock dividends occurring after the balance sheet date but before the financial statements are issued must be given retroactive effect in computing EPS. The weighted-average shares become 300,000 x 2 = 600,000, and basic EPS = $1,800,000 / 600,000 = $3.00. Choice A is incorrect because it ignores the required retroactive adjustment for the post-period split.', 'medium', 2),

-- Q6: hard / L3 — Loss from continuing operations makes all securities antidilutive
(2, 'Earnings Per Share', 'Riverton Holdings reports a loss from continuing operations of $450,000 and income from discontinued operations of $700,000, resulting in net income of $250,000. The company has 100,000 common shares and 5,000 dilutive stock options. The controller includes the options in diluted EPS because overall net income is positive. Analyze whether this treatment is correct under ASC 260.', '["Correct, because net income is positive and options would reduce EPS", "Correct, because discontinued operations income offsets the continuing operations loss", "Incorrect, because when there is a loss from continuing operations, all potentially dilutive securities are treated as antidilutive", "Incorrect, because stock options can never be included when discontinued operations exist"]'::jsonb, 2, 'Under ASC 260-10-45-19, the control number for determining whether securities are dilutive or antidilutive is income from continuing operations (not net income). Because Riverton has a loss from continuing operations, all potentially dilutive securities must be excluded from diluted EPS. Choice B is incorrect because discontinued operations income cannot offset the continuing operations loss for this antidilution test.', 'hard', 3),

-- Q7: easy / L2 — Weighted-average shares with mid-year treasury stock repurchase
(2, 'Earnings Per Share', 'Crestwood Inc. had 180,000 common shares outstanding on January 1. On September 1, the company repurchased 24,000 shares as treasury stock. What is the weighted-average number of shares for the year?', '["172,000", "168,000", "156,000", "180,000"]'::jsonb, 0, 'Under ASC 260-10-45-10, the weighted-average shares reflect shares outstanding during the period. The 24,000 shares were repurchased on September 1, so they were outstanding for 8/12 of the year. Weighted-average = 180,000 x (8/12) + 156,000 x (4/12) = 120,000 + 52,000 = 172,000. Choice B is incorrect because it misweights the repurchase period.', 'easy', 2),

-- Q8: medium / L2 — RSUs in diluted EPS using treasury stock method
(2, 'Earnings Per Share', 'Northfield Technologies has net income of $630,000 and 120,000 weighted-average common shares. The company granted 10,000 restricted stock units (RSUs) with $100,000 of total remaining unrecognized compensation cost. The average market price is $25 per share. Using the treasury stock method, what is diluted EPS?', '["$5.25", "$4.50", "$4.85", "$5.00"]'::jsonb, 3, 'Under ASC 260-10-45-29, unvested RSUs are included in diluted EPS using the treasury stock method. Assumed proceeds equal unrecognized compensation cost ($100,000). Shares repurchased = $100,000 / $25 = 4,000. Incremental shares = 10,000 - 4,000 = 6,000. Diluted EPS = $630,000 / (120,000 + 6,000) = $630,000 / 126,000 = $5.00. Choice A ($5.25) is incorrect because it ignores the RSUs entirely, computing only basic EPS ($630,000 / 120,000).', 'medium', 2),

-- Q9: easy / L1 — ASC 260 scope (public entities required to present EPS)
(2, 'Earnings Per Share', 'Under ASC 260, which entities are required to present earnings per share on the face of the income statement?', '["All entities that prepare GAAP financial statements", "Only publicly held entities and entities filing with the SEC", "Only entities with complex capital structures", "Only entities with annual revenues exceeding $10 million"]'::jsonb, 1, 'Under ASC 260-10-15-2, EPS presentation is required only for entities that have issued common stock or potential common stock traded in a public market, or that have filed or are in the process of filing with the SEC. Private companies are not required to present EPS. Choice A is incorrect because nonpublic entities are exempt from EPS presentation requirements.', 'easy', 1),

-- Q10: medium / L3 — Stock buyback program effect on basic EPS
(2, 'Earnings Per Share', 'Bellingham Corp. has net income of $2,000,000 and 400,000 weighted-average common shares, producing basic EPS of $5.00. The board authorizes a share repurchase program that buys back 40,000 shares at the beginning of the next quarter. Assuming net income remains unchanged, analyze the most likely effect on basic EPS.', '["Basic EPS increases because fewer shares are in the denominator", "Basic EPS decreases because the cash spent on repurchases reduces net income", "Basic EPS remains unchanged because treasury stock is excluded from the EPS formula", "Basic EPS increases only if the repurchase price exceeds book value per share"]'::jsonb, 0, 'Under ASC 260-10-45-10, basic EPS uses weighted-average common shares outstanding. Treasury stock repurchases reduce shares outstanding, which lowers the denominator and increases EPS when net income is held constant. Choice B is incorrect because the cash paid for repurchases does not directly reduce net income; it is a balance sheet transaction that reduces equity, not an income statement expense.', 'medium', 3),

-- Q11: easy / L1 — Definition of antidilutive
(2, 'Earnings Per Share', 'In the context of EPS under ASC 260, a security is considered antidilutive when its inclusion in the diluted EPS calculation would:', '["Decrease the numerator of the EPS fraction", "Reduce the number of shares in the denominator", "Increase earnings per share or decrease loss per share", "Require retroactive restatement of prior-period EPS"]'::jsonb, 2, 'Under ASC 260-10-20, antidilutive securities are those whose inclusion in the diluted EPS computation would increase EPS (or decrease loss per share). Antidilutive securities must be excluded from diluted EPS. Choice A is incorrect because decreasing the numerator alone does not define antidilution; the net effect on the per-share amount determines whether a security is antidilutive.', 'easy', 1),

-- Q12: medium / L3 — Two-class method undistributed earnings allocation
(2, 'Earnings Per Share', 'Everett Manufacturing has net income of $1,400,000, pays $200,000 in preferred base dividends, and declares no common dividends. The preferred stock participates equally with common on a per-share basis in undistributed earnings. There are 200,000 common shares and 100,000 preferred shares outstanding. Under the two-class method, analyze how the $1,200,000 of undistributed earnings is allocated to common shareholders.', '["$600,000", "$1,200,000", "$1,000,000", "$800,000"]'::jsonb, 3, 'Under ASC 260-10-45-61B, undistributed earnings ($1,400,000 - $200,000 = $1,200,000) are allocated based on each class''s participation rights. With equal per-share participation, allocation is proportional: common receives 200,000 / (200,000 + 100,000) = 66.67% of $1,200,000 = $800,000. Preferred receives 33.33% = $400,000. Choice B ($1,200,000) is incorrect because it allocates all undistributed earnings to common, ignoring the preferred stock''s participation right.', 'medium', 3),

-- Q13: medium / L2 — After-tax interest add-back for convertible bonds numerator
(2, 'Earnings Per Share', 'Oakmont Financial has net income of $840,000, 200,000 common shares, and $600,000 of 5% convertible bonds convertible into 15,000 common shares. The tax rate is 21%. When computing diluted EPS using the if-converted method, what amount is added to the numerator for the convertible bonds?', '["$23,700", "$30,000", "$6,300", "$18,000"]'::jsonb, 0, 'Under ASC 260-10-45-40, the if-converted method requires adding back the after-tax interest expense to the numerator. Interest = $600,000 x 5% = $30,000. After-tax add-back = $30,000 x (1 - 0.21) = $23,700. Choice B ($30,000) is incorrect because it uses pre-tax interest, whereas the tax benefit from the interest deduction must be removed to avoid overstating the numerator.', 'medium', 2),

-- Q14: easy / L1 — EPS line-item placement on income statement
(2, 'Earnings Per Share', 'Under ASC 260, for an entity with a simple capital structure, where must basic EPS be presented?', '["In the notes to the financial statements only", "On the face of the income statement for each period presented", "In the management discussion and analysis section", "On the statement of stockholders'' equity"]'::jsonb, 1, 'Under ASC 260-10-45-2, EPS amounts must be presented on the face of the income statement for all periods for which an income statement is presented. An entity with a simple capital structure presents only basic EPS. Choice A is incorrect because footnote-only disclosure does not satisfy the ASC 260 requirement for face-of-statement presentation.', 'easy', 1),

-- Q15: easy / L1 — If-converted method assumptions for convertible preferred
(2, 'Earnings Per Share', 'Under ASC 260, the if-converted method for convertible preferred stock assumes conversion occurred at:', '["The date the preferred stock was redeemed", "The date the preferred dividends were declared", "The beginning of the period or issuance date, whichever is later", "The end of the reporting period"]'::jsonb, 2, 'Under ASC 260-10-45-40, the if-converted method assumes that convertible preferred stock was converted into common stock at the beginning of the period (or date of issuance, if later). This requires adding back preferred dividends to the numerator and adding the converted shares to the denominator. Choice D is incorrect because assuming end-of-period conversion would understate the dilutive impact on weighted-average shares.', 'easy', 1),

-- Q16: medium / L3 — Reverse stock split effect on reported EPS
(2, 'Earnings Per Share', 'Whitfield Pharmaceuticals has 600,000 common shares outstanding and net income of $1,200,000, producing basic EPS of $2.00. On July 1, the company executes a 1-for-3 reverse stock split. Analyze the effect on basic EPS for the full year, assuming shares must be retroactively adjusted.', '["Basic EPS remains $2.00 because the split occurs mid-year", "Basic EPS increases to $4.00 because half the shares are reduced", "Basic EPS decreases to $1.00 because more shares are outstanding", "Basic EPS increases to $6.00 because all periods are retroactively adjusted"]'::jsonb, 3, 'Under ASC 260-10-55-12, stock splits and reverse stock splits are given retroactive effect for all periods presented. The 1-for-3 reverse split reduces the weighted-average shares to 200,000 for the entire year (600,000 / 3), producing EPS of $1,200,000 / 200,000 = $6.00. Choice B is incorrect because it applies the reverse split only to the post-split period, whereas ASC 260 requires retroactive adjustment for all periods.', 'medium', 3),

-- Q17: hard / L4 — Anti-dilution sequencing rule with multiple convertible securities
(2, 'Earnings Per Share', 'Pinecrest Holdings has basic EPS of $5.00 based on $750,000 net income and 150,000 shares. Three potentially dilutive securities exist: (1) stock options adding 8,000 incremental shares, (2) $200,000 of 4% convertible bonds adding $6,320 after-tax interest and 6,000 shares, and (3) $300,000 of convertible preferred adding $18,000 dividends and 12,000 shares. Evaluate the correct inclusion sequence and determine diluted EPS.', '["$4.40", "$4.61", "$4.75", "$5.00"]'::jsonb, 0, 'Under ASC 260-10-45-21, potentially dilutive securities are ranked from most to least dilutive. Options ($0 numerator / 8,000 shares) are most dilutive. Bonds ($6,320 / 6,000 = $1.05/share) are next. Preferred ($18,000 / 12,000 = $1.50/share) is least dilutive. Step 1 (options): $750,000 / 158,000 = $4.75. Step 2 (bonds): $756,320 / 164,000 = $4.61. Step 3 (preferred): $774,320 / 176,000 = $4.40. Each step is dilutive. Diluted EPS = $4.40. Choice B ($4.61) is incorrect because it stops after including only options and bonds, whereas the preferred stock must also be tested and included since it remains dilutive.', 'hard', 4),

-- Q18: medium / L3 — Discontinued operations EPS presentation
(2, 'Earnings Per Share', 'Sterling Industries reports income from continuing operations of $680,000 and a loss from discontinued operations (net of tax) of $180,000. Weighted-average shares are 200,000 and diluted shares are 220,000. The controller presents EPS only on the net income line. Analyze whether this presentation complies with ASC 260.', '["Compliant, because EPS on net income is the only required disclosure", "Noncompliant, because EPS must be presented for both continuing operations and net income, with discontinued operations either on the face or in the notes", "Noncompliant, because EPS must be presented for discontinued operations but not for continuing operations", "Compliant, because discontinued operations EPS is optional for simple capital structures"]'::jsonb, 1, 'Under ASC 260-10-45-3, an entity must present EPS for income from continuing operations and net income on the face of the income statement. EPS for discontinued operations may be presented on the face of the statement or in the notes. Presenting EPS only on the net income line omits the required continuing operations EPS. Choice A is incorrect because ASC 260 explicitly requires EPS for continuing operations.', 'medium', 3),

-- Q19: medium / L2 — Warrants in the treasury stock method
(2, 'Earnings Per Share', 'Briarwood Corp. has 250,000 common shares outstanding and net income of $625,000. The company has 20,000 warrants outstanding with an exercise price of $15 per warrant. The average market price during the year was $25. Using the treasury stock method, how many incremental shares are added for diluted EPS?', '["12,000", "20,000", "8,000", "5,000"]'::jsonb, 2, 'Under ASC 260-10-45-29, warrants are treated identically to stock options under the treasury stock method. Proceeds = 20,000 x $15 = $300,000. Shares repurchased at average price = $300,000 / $25 = 12,000. Incremental shares = 20,000 - 12,000 = 8,000. Choice A (12,000) incorrectly reports the repurchased shares rather than the net incremental shares added to the denominator.', 'medium', 2),

-- Q20: medium / L3 — Mandatorily convertible preferred and diluted EPS
(2, 'Earnings Per Share', 'Summit Energy has 100,000 common shares, net income of $500,000, and 10,000 shares of mandatorily convertible preferred stock that will convert into 30,000 common shares in two years. Annual preferred dividends are $50,000. Basic EPS is $4.50. Analyze how the mandatory conversion feature affects diluted EPS under ASC 260.', '["No effect because conversion has not yet occurred", "Mandatorily convertible shares are included in basic EPS, not diluted EPS", "Diluted EPS is reduced because the preferred shares are included using the if-converted method", "Diluted EPS increases because adding shares always increases the denominator more than the numerator"]'::jsonb, 2, 'Under ASC 260-10-45-40, mandatorily convertible securities are included in the diluted EPS calculation using the if-converted method. The $50,000 preferred dividend is added back to the numerator and 30,000 shares to the denominator: ($450,000 + $50,000) / (100,000 + 30,000) = $3.85, which is dilutive compared to basic EPS of $4.50. Choice A is incorrect because ASC 260 requires inclusion of mandatorily convertible securities regardless of when conversion occurs.', 'medium', 3),

-- Q21: medium / L2 — Contingently issuable shares when conditions NOT met
(2, 'Earnings Per Share', 'Meridian Software has 80,000 common shares outstanding and net income of $320,000. Per an acquisition agreement, 10,000 additional shares are contingently issuable if cumulative revenues exceed $5,000,000 by December 31, 2026. As of December 31, 2025, cumulative revenues are $3,800,000. How are the contingent shares treated for basic and diluted EPS at December 31, 2025?', '["Excluded from both basic and diluted EPS", "Included in both basic and diluted EPS", "Excluded from basic EPS but included in diluted EPS if the condition would be met at period end", "Included in basic EPS but excluded from diluted EPS"]'::jsonb, 0, 'Under ASC 260-10-45-48, contingently issuable shares are included in basic EPS only when all necessary conditions are met. For diluted EPS, they are included if the conditions would be satisfied assuming the end of the reporting period is the end of the contingency period. Since cumulative revenues of $3,800,000 do not meet the $5,000,000 threshold at December 31, 2025, the shares are excluded from both calculations. Choice C is incorrect because the revenue condition would not be met if period-end were the measurement date.', 'medium', 2),

-- Q22: hard / L4 — Evaluate two-class method vs. if-converted method for convertible participating preferred
(2, 'Earnings Per Share', 'Lakewood Industries has net income of $2,000,000 and 400,000 common shares. It has 50,000 shares of 6% convertible participating preferred stock ($100 par), each convertible into 3 common shares. The preferred participates equally in dividends above the 6% base rate. The CFO must choose between the if-converted method and the two-class method for basic EPS. Evaluate which method ASC 260 requires and why.', '["The if-converted method because all convertible securities use if-converted for basic EPS", "The two-class method, because participating convertible preferred requires the method that is more dilutive, and the two-class method must be compared against if-converted", "The if-converted method because it always produces lower EPS than the two-class method", "Neither method; participating preferred is excluded from both basic and diluted EPS"]'::jsonb, 1, 'Under ASC 260-10-45-60A, when a convertible security is also a participating security, the entity must use the more dilutive of the two-class method and the if-converted method for basic EPS. This requires computing EPS under both approaches and reporting the lower result. Choice A is incorrect because the if-converted method is not automatically used; the participation feature requires a dual computation and selection of the more dilutive result.', 'hard', 4),

-- Q23: easy / L1 — Weighted-average shares definition
(2, 'Earnings Per Share', 'Under ASC 260, the denominator in the basic EPS calculation uses weighted-average shares, which reflects:', '["The total number of authorized shares", "The number of shares outstanding at the end of the period", "The number of shares outstanding weighted by the portion of the period they were outstanding", "The maximum number of shares that could be outstanding after all conversions"]'::jsonb, 2, 'Under ASC 260-10-45-10, basic EPS uses the weighted-average number of common shares outstanding during the period, reflecting the time each share was outstanding. Shares issued or repurchased during the period are weighted by the fraction of the period they were outstanding. Choice B is incorrect because using only the ending balance would ignore timing of share issuances and repurchases during the year.', 'easy', 1),

-- Q24: easy / L1 — Securities that create a complex capital structure
(2, 'Earnings Per Share', 'Which of the following securities, if outstanding, would cause an entity to have a complex capital structure under ASC 260?', '["Nonconvertible preferred stock with a fixed dividend", "Treasury stock held by the company", "Accounts receivable pledged as collateral", "Stock options granted to employees"]'::jsonb, 3, 'Under ASC 260-10-15-2, a complex capital structure includes potentially dilutive securities such as stock options, warrants, convertible debt, or convertible preferred stock. Stock options can result in additional common shares, creating potential dilution. Choice A is incorrect because nonconvertible preferred stock cannot be converted into common shares and therefore does not create a complex capital structure.', 'easy', 1),

-- Q25: hard / L4 — Written put options on entity's own stock and diluted EPS
(2, 'Earnings Per Share', 'Aldridge Corp. has 200,000 common shares outstanding and net income of $1,000,000. The company wrote put options obligating it to repurchase 10,000 shares at $60 per share. The average market price during the period was $50. Evaluate whether these written puts are dilutive under ASC 260 and determine their effect on diluted EPS.', '["Dilutive; add 2,000 incremental shares using the reverse treasury stock method", "Antidilutive; exclude because the exercise price exceeds the market price", "Dilutive; add 10,000 shares to the denominator", "Antidilutive; exclude because written puts never affect EPS"]'::jsonb, 0, 'Under ASC 260-10-45-35, written put options are dilutive when the exercise price exceeds the average market price. The reverse treasury stock method applies: the entity would repurchase 10,000 shares at $60 ($600,000) and is assumed to issue shares at $50 market price to fund the difference. Shares issued = $600,000 / $50 = 12,000. Incremental shares = 12,000 - 10,000 = 2,000. Choice B is incorrect because for written puts, dilution occurs when exercise price exceeds market price (opposite of call options).', 'hard', 4),

-- Q26: medium / L2 — Convertible preferred stock issued mid-year in diluted EPS
(2, 'Earnings Per Share', 'Thornberry Corp. has net income of $960,000 and 240,000 weighted-average common shares for the full year. On April 1, the company issued 5,000 shares of convertible preferred stock with annual dividends of $40,000. Each preferred share converts into 8 common shares. What is the denominator adjustment for diluted EPS under the if-converted method?', '["40,000 shares", "30,000 shares", "20,000 shares", "10,000 shares"]'::jsonb, 1, 'Under ASC 260-10-45-40, the if-converted method assumes conversion at the issuance date when the security was issued during the period. The preferred was issued April 1 and outstanding 9 months. Share adjustment = 5,000 x 8 x (9/12) = 30,000 weighted shares. Choice A (40,000) is incorrect because it assumes conversion for the full year, whereas the preferred was outstanding only 9 months from the April 1 issuance date.', 'medium', 2),

-- Q27: medium / L3 — Unvested stock compensation awards in diluted EPS
(2, 'Earnings Per Share', 'Clearwater Technologies granted 15,000 unvested performance shares to executives on January 1. The shares vest only if the company achieves 15% revenue growth. At December 31, actual revenue growth is 12%. The average share price is $40 and total unrecognized compensation is $240,000. Analyze how these performance shares affect diluted EPS.', '["Include 15,000 shares because they were granted during the period", "Include 9,000 incremental shares using the treasury stock method", "Exclude entirely because the performance condition is not met at the reporting date", "Include 6,000 shares only if revenue growth exceeds 10%"]'::jsonb, 2, 'Under ASC 260-10-45-48, contingently issuable shares tied to performance conditions are included in diluted EPS only if the condition would be satisfied assuming the end of the reporting period is the end of the contingency period. Since 12% revenue growth does not meet the 15% target, these shares are excluded. Choice A is incorrect because mere granting does not trigger inclusion; the performance condition must be evaluated at each reporting date.', 'medium', 3),

-- Q28: medium / L2 — Bonus share issuance effect on weighted-average
(2, 'Earnings Per Share', 'On July 1, Haverford Holdings distributed 20,000 bonus shares (stock dividend) to existing shareholders who held 200,000 shares. For the year ended December 31, what weighted-average shares should Haverford use in computing basic EPS?', '["200,000", "210,000", "220,000", "215,000"]'::jsonb, 2, 'Under ASC 260-10-55-12, stock dividends (bonus shares) are treated as if they occurred at the beginning of the earliest period presented. Therefore, all 220,000 shares (200,000 original + 20,000 bonus) are treated as outstanding for the entire year. The weighted-average is 220,000, not time-weighted from July 1. Choice B (210,000) is incorrect because it time-weights the bonus shares from the distribution date, whereas stock dividends must be treated as outstanding for the entire period.', 'medium', 2),

-- Q29: hard / L4 — Contract settleable in shares or cash for EPS inclusion
(2, 'Earnings Per Share', 'Bridgeport Dynamics enters a forward contract that can be settled in either 15,000 common shares or $450,000 cash, at the company''s option. The average share price is $35. The contract is in the money. The CFO excludes the contract from diluted EPS because the company intends to settle in cash. Evaluate whether this exclusion is appropriate under ASC 260.', '["Inappropriate; ASC 260 requires contracts settleable in shares or cash to be presumed settled in shares for diluted EPS if the effect is dilutive", "Appropriate; management intent to settle in cash controls the EPS treatment", "Inappropriate; the contract should be included in both basic and diluted EPS", "Appropriate; forward contracts are always excluded from diluted EPS"]'::jsonb, 0, 'Under ASC 260-10-45-45, contracts that may be settled in stock or cash must be presumed settled in shares for diluted EPS purposes if the effect is more dilutive, regardless of management''s stated intent. The share settlement presumption ensures diluted EPS reflects the maximum potential dilution. Choice B is incorrect because ASC 260 does not permit management intent to override the share settlement presumption.', 'hard', 4),

-- Q30: medium / L3 — EPS when entity has continuing ops income but overall net loss
(2, 'Earnings Per Share', 'Ashford Logistics reports income from continuing operations of $350,000 and a loss from discontinued operations of $500,000, resulting in a net loss of $150,000. There are 100,000 common shares and 10,000 dilutive stock options that would add 3,000 incremental shares. Analyze the EPS presentation requirements.', '["Present diluted EPS for all line items using 103,000 shares in the denominator", "Present only basic EPS because the overall net result is a loss", "Use 103,000 diluted shares for continuing operations but switch to 100,000 basic shares for the net loss line", "Use the 103,000 diluted share denominator for continuing operations, discontinued operations, and net loss per share"]'::jsonb, 3, 'Under ASC 260-10-45-19, the control number is income from continuing operations. Since continuing operations is profitable, the options are dilutive and included. ASC 260-10-45-3 requires the same denominator used for continuing operations to be used for all other EPS amounts. Thus, 103,000 shares is used throughout. Choice C is incorrect because it inconsistently switches to basic shares for the net loss line.', 'medium', 3)
;

COMMIT;
