-- Migration: Question generation — REG batch 18 (30 questions)
-- Date: 2026-02-28
-- Topic: Tax-Exempt Organizations
-- Difficulty: 9E / 15M / 6H
-- Bloom's: L1:8 / L2:9 / L3:8 / L4:5

BEGIN;

INSERT INTO questions (section_id, topic, stem, choices, correct_index, explanation, difficulty, cognitive_level)
VALUES

-- Q1: hard / L4 — Section 501(h) expenditure test election analysis
(3, 'Tax-Exempt Organizations', 'Bright Horizons Education Fund, a 501(c)(3) public charity with $2,000,000 in exempt purpose expenditures, spends $180,000 on direct lobbying and $60,000 on grassroots lobbying in 2026. The organization has not elected the Section 501(h) expenditure test. Its board considers whether electing the expenditure test would provide more favorable treatment than the substantial part test. Evaluate the organization''s situation.', '["The organization is safe under either test because $180,000 is less than 10% of total expenditures", "The substantial part test provides clearer safe harbor thresholds than the expenditure test", "Electing the 501(h) expenditure test would provide defined dollar limits, replacing the vague substantial part standard with measurable safe harbors", "The organization cannot elect the 501(h) test because it has already engaged in lobbying"]'::jsonb, 2, 'Under Section 501(h), eligible public charities may elect the expenditure test, which replaces the subjective "substantial part" standard with specific dollar ceilings based on exempt purpose expenditures. For an organization with $2,000,000 in exempt purpose expenditures, the lobbying nontaxable amount provides defined thresholds. Unlike the substantial part test, the 501(h) election offers objective, measurable limits. Option B is incorrect because the substantial part test lacks clear numerical standards, creating uncertainty for organizations that lobby.', 'hard', 4),

-- Q2: hard / L3 — Debt-financed income computation (Section 514)
(3, 'Tax-Exempt Organizations', 'Riverside Medical Foundation, a 501(c)(3), purchases a commercial office building for $1,200,000, financing $800,000 with a mortgage. The building generates $150,000 in annual rental income from unrelated tenants. The average acquisition indebtedness for the year is $780,000, and the average adjusted basis is $1,100,000. How much of the rental income is subject to UBIT under Section 514?', '["$150,000, because all rental income from debt-financed property is taxable", "$106,364, calculated as $150,000 multiplied by the ratio of average acquisition indebtedness to average adjusted basis", "$97,500, calculated using the original mortgage amount divided by the purchase price", "$0, because rental income from real property is always excluded from UBIT"]'::jsonb, 1, 'Under Section 514, income from debt-financed property is subject to UBIT in proportion to the average acquisition indebtedness divided by the average adjusted basis. The debt/basis percentage is $780,000 / $1,100,000 = 70.91%. Applying this to $150,000 in rental income yields $106,364 subject to UBIT. Option D is incorrect because the general exclusion for real property rents under Section 512(b)(3) does not apply when the property is debt-financed under Section 514.', 'hard', 3),

-- Q3: easy / L1 — Dissolution clause requirement
(3, 'Tax-Exempt Organizations', 'What does the dissolution clause requirement mean for a Section 501(c)(3) organization?', '["The organization must dissolve within 30 years of formation", "The organization must file dissolution documents annually with the IRS", "The organization must allow members to withdraw their contributions upon dissolution", "The governing documents must provide that assets will be distributed to another exempt organization or government upon dissolution"]'::jsonb, 3, 'Under Section 501(c)(3), the organizational test requires that governing documents include a dissolution clause providing that remaining assets will be distributed to another 501(c)(3) organization or a governmental unit upon dissolution. This prevents founders or members from receiving a windfall. Option C is incorrect because contributions to a 501(c)(3) are irrevocable, and assets must go to charitable purposes, not back to contributors.', 'easy', 1),

-- Q4: medium / L3 — Convenience exclusion for hospital cafeteria
(3, 'Tax-Exempt Organizations', 'Memorial Regional Hospital, a 501(c)(3), operates a cafeteria open to patients, visitors, and hospital employees. The cafeteria generates $400,000 in annual revenue. A nearby restaurant generates comparable sales from the surrounding community. The hospital''s controller must determine the cafeteria''s UBIT treatment. How should the cafeteria income be classified?', '["The cafeteria income is excluded from UBIT under the convenience exclusion because it primarily serves patients, their visitors, and employees", "The cafeteria income is fully subject to UBIT because it competes with local restaurants", "The cafeteria income is excluded because it is passive investment income", "The cafeteria income is subject to UBIT only to the extent it serves visitors who are not patients"]'::jsonb, 0, 'Under Section 513(a)(2), income from a trade or business carried on primarily for the convenience of members, students, patients, officers, or employees is excluded from UBIT. A hospital cafeteria serving patients, their visitors, and employees meets this exclusion. The activity need only be carried on primarily for their convenience. Option B is incorrect because competition with commercial businesses does not override the statutory convenience exclusion when the cafeteria primarily serves the specified groups.', 'medium', 3),

-- Q5: medium / L2 — One-third support test for public charity classification
(3, 'Tax-Exempt Organizations', 'Helping Hands Community Fund receives the following support during 2026: $100,000 from government grants, $150,000 from public contributions, and $750,000 from investment income generated by a single donor''s endowment. Which classification applies to this organization under Section 509(a)?', '["Public charity, because it receives government grants", "Public charity, because total receipts exceed $1,000,000", "Private foundation, because public and government support of $250,000 is less than one-third of total support of $1,000,000", "Private foundation, because it receives investment income"]'::jsonb, 2, 'Under Section 509(a)(1), a 501(c)(3) organization is classified as a private foundation unless it meets the one-third public support test. Public and government support totals $250,000 ($100,000 + $150,000), while total support is $1,000,000. The 25% public support ratio falls below the one-third threshold, so the organization is presumed to be a private foundation. Option A is incorrect because merely receiving government grants does not automatically confer public charity status—the support must constitute at least one-third of total support.', 'medium', 2),

-- Q6: easy / L1 — Form 990-N (e-Postcard) threshold
(3, 'Tax-Exempt Organizations', 'Which tax-exempt organizations are eligible to file Form 990-N (e-Postcard) instead of the full Form 990?', '["All private foundations regardless of gross receipts", "Organizations with annual gross receipts normally $50,000 or less", "Organizations with gross receipts under $200,000 and total assets under $500,000", "Any organization that has been tax-exempt for fewer than five years"]'::jsonb, 1, 'Under IRC Section 6033, organizations with annual gross receipts normally $50,000 or less may file Form 990-N (e-Postcard), an electronic notice requiring only basic information such as name, address, EIN, and confirmation of continued eligibility. Option C describes the threshold for Form 990-EZ, not Form 990-N. Option A is incorrect because private foundations must file Form 990-PF regardless of their gross receipts.', 'easy', 1),

-- Q7: easy / L1 — Private inurement definition
(3, 'Tax-Exempt Organizations', 'Under the operational test of Section 501(c)(3), what is private inurement?', '["Any net earnings of the organization that benefit a private shareholder or individual who is an insider", "Any charitable distribution made to an individual beneficiary", "The payment of reasonable salaries to officers and employees", "Investment income earned by the organization''s endowment fund"]'::jsonb, 0, 'Under Section 501(c)(3), the private inurement prohibition provides that no part of net earnings may inure to the benefit of any private shareholder or individual. This targets insiders—founders, officers, directors, and key employees—who might divert organizational resources for personal gain. Option C is incorrect because the payment of reasonable compensation for services rendered is permitted and does not constitute private inurement.', 'easy', 1),

-- Q8: hard / L4 — Section 4945 taxable expenditures combined analysis
(3, 'Tax-Exempt Organizations', 'The Parker Family Foundation, a private foundation, undertakes four activities during 2026: (1) a $50,000 unrestricted grant to a 501(c)(3) public charity, (2) a $25,000 scholarship to a graduate student selected through an IRS-approved competitive process, (3) a $40,000 grant to a non-501(c)(3) foreign NGO without exercising expenditure responsibility, and (4) a $15,000 payment to a lobbying firm for legislative advocacy. Which activities constitute taxable expenditures under Section 4945?', '["Only activity 4, because lobbying is the only prohibited expenditure for private foundations", "Activities 2 and 3 only, because grants to individuals and foreign entities are always prohibited", "Activities 1, 3, and 4, because all grants outside the foundation are taxable expenditures", "Activities 3 and 4 only, because the grant without expenditure responsibility and the lobbying payment are taxable expenditures"]'::jsonb, 3, 'Under Section 4945, taxable expenditures include lobbying, political campaign activity, grants to individuals without IRS-approved selection procedures, and grants to non-charities without exercising expenditure responsibility. Activity 3 (grant to foreign NGO without expenditure responsibility) and activity 4 (lobbying payment) are taxable expenditures subject to a 20% tax. Activity 1 (unrestricted grant to a public charity) and activity 2 (scholarship through IRS-approved process) are permissible. Option A is incorrect because activity 3 also qualifies as a taxable expenditure due to the absence of expenditure responsibility.', 'hard', 4),

-- Q9: medium / L2 — Form 990 vs Form 990-EZ filing determination
(3, 'Tax-Exempt Organizations', 'Northern Valley Wildlife Rescue, a 501(c)(3) public charity, reports gross receipts of $175,000 and total assets of $420,000 for its 2026 fiscal year. Which annual information return must this organization file?', '["Form 990-N (e-Postcard)", "Form 990-EZ", "Form 990 (full return)", "Form 990-PF"]'::jsonb, 1, 'Under IRC Section 6033, organizations with gross receipts less than $200,000 AND total assets less than $500,000 are eligible to file Form 990-EZ. Northern Valley meets both thresholds ($175,000 < $200,000 and $420,000 < $500,000). Form 990-N is available only for organizations with gross receipts of $50,000 or less, and Form 990-PF is required for private foundations. Option C is incorrect because the full Form 990 is required only when gross receipts reach $200,000 or total assets reach $500,000.', 'medium', 2),

-- Q10: medium / L3 — Controlled entity payments (80%+ ownership) UBIT
(3, 'Tax-Exempt Organizations', 'Clearwater Foundation, a 501(c)(3), owns 85% of Clearwater Services Inc., a taxable C corporation. Clearwater Services pays the Foundation $120,000 in annual rent for office space. An independent appraisal determines fair market rent is $90,000. How is this rental payment treated for UBIT purposes under Section 512(b)(13)?', '["The entire $120,000 is excluded from UBIT as rent from real property", "The entire $120,000 is subject to UBIT because Clearwater Services is a controlled entity", "$30,000, the excess over fair market value, is subject to UBIT under the controlled entity rules", "$120,000 is excluded because the Foundation uses the rental income for exempt purposes"]'::jsonb, 2, 'Under Section 512(b)(13), rent received from a controlled entity (80%+ ownership) is subject to UBIT to the extent it exceeds fair market value. Clearwater Foundation owns 85% of Clearwater Services, triggering the controlled entity rules. Fair market rent is $90,000, so only the $30,000 excess ($120,000 minus $90,000) is treated as UBIT. Option A is incorrect because the general real property rent exclusion is modified when payments come from a controlled subsidiary and exceed fair market value.', 'medium', 3),

-- Q11: easy / L1 — Form 990 filing deadline
(3, 'Tax-Exempt Organizations', 'What is the filing deadline for Form 990 for a calendar-year tax-exempt organization?', '["May 15 of the following year", "March 15 of the following year", "April 15 of the following year", "June 15 of the following year"]'::jsonb, 0, 'Under IRC Section 6033, tax-exempt organizations must file Form 990 by the 15th day of the 5th month after the end of their tax year. For calendar-year organizations, this deadline is May 15. Extensions of up to six months are available by filing Form 8868. Option C is incorrect because April 15 is the filing deadline for individual income tax returns, not for tax-exempt organization information returns.', 'easy', 1),

-- Q12: medium / L3 — Bingo game exclusion conditions
(3, 'Tax-Exempt Organizations', 'Valley Community Center, a 501(c)(3), hosts weekly bingo nights with $10 admission and $500 in prizes per event. The state permits charitable bingo, but three commercial bingo parlors operate in the same county. Annual net bingo revenue is $35,000. Is this income subject to UBIT?', '["No, because all bingo conducted by tax-exempt organizations is automatically excluded from UBIT", "No, because the activity uses volunteer labor", "Yes, because the income exceeds the $1,000 specific deduction threshold", "Yes, because the bingo exclusion does not apply where commercial bingo is ordinarily carried on in the same jurisdiction"]'::jsonb, 3, 'Under Section 513(f), bingo games are excluded from UBIT only when bingo is not ordinarily carried on in the jurisdiction on a commercial basis. Because three commercial bingo parlors operate in the same county, the statutory exclusion does not apply, and the income meets all three parts of the UBIT test. Option A is incorrect because the bingo exclusion is conditional, not absolute—it depends on whether commercial bingo exists in the jurisdiction.', 'medium', 3),

-- Q13: medium / L2 — Intermediate sanctions initial tax rate (Section 4958)
(3, 'Tax-Exempt Organizations', 'Under Section 4958 intermediate sanctions, what is the initial excise tax rate imposed on a disqualified person who receives an excess benefit from a 501(c)(3) organization?', '["10% of the excess benefit amount", "20% of the excess benefit amount", "25% of the excess benefit amount", "200% of the excess benefit amount"]'::jsonb, 2, 'Under Section 4958, the initial excise tax on a disqualified person who receives an excess benefit from a 501(c)(3) or 501(c)(4) organization is 25% of the excess benefit amount. If the excess benefit is not corrected within the taxable period, an additional 200% tax is imposed. Option A is incorrect because 10% is the tax rate imposed on an organization manager who knowingly participates, not the rate on the disqualified person.', 'medium', 2),

-- Q14: easy / L1 — Automatic public charity classification
(3, 'Tax-Exempt Organizations', 'Which of the following organizations is automatically classified as a public charity regardless of its funding sources?', '["A private operating foundation with assets of $50,000,000", "A church, school, or hospital described in Section 170(b)(1)(A)", "A 501(c)(4) social welfare organization", "A 501(c)(6) trade association"]'::jsonb, 1, 'Under Section 509(a)(1), churches, schools, and hospitals are automatically classified as public charities regardless of their funding sources. They do not need to meet the one-third public support test. Option A is incorrect because a private operating foundation is still a type of private foundation, even though it may face fewer restrictions. Options C and D are not 501(c)(3) entities and fall outside the public charity/private foundation classification.', 'easy', 1),

-- Q15: easy / L1 — Additional 200% tax on uncorrected excess benefit
(3, 'Tax-Exempt Organizations', 'Under Section 4958, what additional excise tax is imposed on a disqualified person who fails to correct an excess benefit transaction within the taxable period?', '["200% of the excess benefit amount", "100% of the excess benefit amount", "50% of the excess benefit amount", "25% of the excess benefit amount"]'::jsonb, 0, 'Under Section 4958, if a disqualified person does not correct the excess benefit transaction within the taxable period, an additional excise tax of 200% of the excess benefit amount is imposed. This severe penalty incentivizes prompt correction by repaying the excess amount plus interest. Option D is incorrect because 25% is the initial tax rate on the disqualified person, not the additional tax for failure to correct.', 'easy', 1),

-- Q16: medium / L2 — Failure-to-file penalty computation
(3, 'Tax-Exempt Organizations', 'Starlight Youth Foundation, a 501(c)(3) with gross receipts of $450,000, fails to file its Form 990 by the due date and files 60 days late without reasonable cause. What is the penalty for late filing?', '["No penalty because the organization''s gross receipts are under $500,000", "$600, calculated as $10 per day for 60 days", "$6,000, calculated as $100 per day for 60 days", "$1,200, calculated as $20 per day for 60 days"]'::jsonb, 3, 'Under IRC Section 6652(c), the penalty for failure to file Form 990 is $20 per day for organizations with gross receipts under $1,186,000, up to the lesser of $10,500 or 5% of gross receipts. At 60 days late, Starlight''s penalty is $20 times 60 = $1,200. Option C is incorrect because the $100 per day rate applies only to organizations with gross receipts of $1,186,000 or more.', 'medium', 2),

-- Q17: medium / L2 — Personal property rents vs real property rents (10% rule)
(3, 'Tax-Exempt Organizations', 'Lakeside Conservancy, a 501(c)(3), leases office space and office furniture to a local business under a single lease. Annual rent is $100,000, of which $8,000 is attributable to the furniture and $92,000 to the real property. How is the rental income treated for UBIT purposes?', '["The entire $100,000 is excluded from UBIT because personal property rents are less than 10% of total rents under the lease", "$8,000 is subject to UBIT as personal property rent and $92,000 is excluded", "The entire $100,000 is subject to UBIT because the lease includes personal property", "$92,000 is excluded and $8,000 is excluded as a de minimis amount unrelated to the 10% rule"]'::jsonb, 0, 'Under Section 512(b)(3), rents from real property are generally excluded from UBIT. When a lease includes both real and personal property, the personal property rents are excluded if they are incidental—less than 10% of total rents under the lease. Here, personal property rents ($8,000) are 8% of total rents ($100,000), below the 10% threshold. Therefore, the entire $100,000 is excluded. Option B is incorrect because the 10% incidental rule exempts the personal property portion when it falls below the threshold.', 'medium', 2),

-- Q18: hard / L4 — Supporting organization analysis (Section 509(a)(3))
(3, 'Tax-Exempt Organizations', 'Metro Arts Alliance is organized to support the City Art Museum, a 501(c)(3) public charity. Metro Arts Alliance''s board consists of five members: three appointed by City Art Museum''s board and two independent community members. Metro Arts Alliance raises funds exclusively through public solicitations and directs all grants to City Art Museum programs. Evaluate whether Metro Arts Alliance qualifies as a supporting organization under Section 509(a)(3).', '["It does not qualify because it raises funds through public solicitations rather than from the supported organization directly", "It qualifies because it is operated exclusively to support a public charity, is supervised by the supported organization through board appointments, and directs resources to the supported organization''s programs", "It does not qualify because fewer than 80% of its board members are appointed by the supported organization", "It qualifies only if it also meets the one-third public support test under Section 509(a)(1)"]'::jsonb, 1, 'Under Section 509(a)(3), a supporting organization must be organized and operated exclusively for the benefit of one or more public charities, be supervised or controlled by the supported organization, and not be controlled by disqualified persons. Metro Arts Alliance meets these requirements: it operates exclusively to benefit City Art Museum, three of five board members are appointed by the supported organization (demonstrating supervisory control), and all grants go to the Museum''s programs. Option D is incorrect because supporting organizations qualify under Section 509(a)(3) independently of the one-third public support test.', 'hard', 4),

-- Q19: hard / L4 — Private inurement vs private benefit distinction
(3, 'Tax-Exempt Organizations', 'Greenfield Education Foundation, a 501(c)(3), hires an outside consultant with no connection to the board or officers. The consultant is paid $250,000 for services that comparable firms provide for $80,000. No board member has a personal relationship with the consultant. Analyze how the IRS would characterize this transaction.', '["This is private inurement because it involves unreasonable compensation", "This is an excess benefit transaction under Section 4958 because the payment exceeds reasonable compensation", "This is impermissible private benefit because the consultant receives more than fair value, even though the consultant is not an insider", "This is permissible because the consultant has no relationship to the organization''s insiders"]'::jsonb, 2, 'The private benefit doctrine under Section 501(c)(3) applies to any person—not just insiders—who receives more than incidental benefit from the organization''s operations. Unlike private inurement (which targets insiders such as founders, officers, and directors), excessive private benefit can arise from transactions with unrelated parties. Because the consultant has no substantial influence over the organization, Section 4958 intermediate sanctions do not apply, but the broader operational test prohibition against excessive private benefit does. Option A is incorrect because private inurement specifically targets insiders, and this consultant is an outsider.', 'hard', 4),

-- Q20: easy / L1 — Form 8868 purpose
(3, 'Tax-Exempt Organizations', 'What is the purpose of IRS Form 8868 for tax-exempt organizations?', '["To apply for initial tax-exempt status under Section 501(c)(3)", "To report unrelated business taxable income to the IRS", "To report changes in the organization''s governing documents", "To request an automatic extension of time to file Form 990 or other exempt organization returns"]'::jsonb, 3, 'Under IRC Section 6081, Form 8868 is used by tax-exempt organizations to request an automatic extension of up to six months to file their annual information returns, including Form 990, Form 990-EZ, Form 990-PF, and Form 990-T. Option A is incorrect because Form 1023 (or Form 1023-EZ) is used to apply for Section 501(c)(3) tax-exempt status, not Form 8868.', 'easy', 1),

-- Q21: medium / L3 — Research exclusion from UBIT
(3, 'Tax-Exempt Organizations', 'Midwest Health Alliance, a 501(c)(3) health advocacy nonprofit (not a university), operates a research division conducting three projects: (1) government-contracted epidemiological research, (2) corporate-sponsored drug efficacy studies with results kept proprietary to the sponsor, and (3) self-funded nutrition research with findings published on its public website. Which projects qualify for the UBIT research exclusion?', '["Projects 1 and 3 qualify; project 2 does not because results are not publicly available and it is not government-funded research", "All three projects qualify because any research by a 501(c)(3) is excluded from UBIT", "Only project 1 qualifies because it is government-funded", "None qualify because only colleges and universities may claim the research exclusion"]'::jsonb, 0, 'Under Section 512(b)(7)-(9), research is excluded from UBIT if performed for the U.S. government, performed by a college or university, or if results are made freely available to the public. Project 1 (government-contracted) and project 3 (publicly available results) meet exclusion criteria. Project 2 does not qualify because results are proprietary, it is not government-funded, and the organization is not a university. Option B is incorrect because the research exclusion requires meeting specific criteria—it is not automatic for all 501(c)(3) organizations.', 'medium', 3),

-- Q22: hard / L4 — Organization manager liability comparison (Sections 4941 and 4958)
(3, 'Tax-Exempt Organizations', 'Dr. Martinez serves as CFO of the Burton Family Foundation, a private foundation. She knowingly approves two prohibited transactions: (1) a $200,000 sale of artwork from the founder to the foundation (self-dealing under Section 4941), and (2) a $300,000 compensation package for the foundation''s program director that constitutes an excess benefit under Section 4958. Analyze Dr. Martinez''s personal excise tax exposure as an organization manager.', '["$10,000 under Section 4941 only, because Section 4958 does not apply to private foundations", "$10,000 under Section 4941 (5% of $200,000) plus $20,000 under Section 4958 (10% of $300,000, capped at $20,000), for a combined $30,000", "$20,000 under Section 4941 (10% of $200,000) plus $30,000 under Section 4958 (10% of $300,000), for a combined $50,000", "$10,000 under Section 4941 plus $0 under Section 4958, because intermediate sanctions cannot apply alongside private foundation excise taxes"]'::jsonb, 1, 'Under Section 4941, a foundation manager who knowingly participates in self-dealing pays 5% of the transaction amount: 5% x $200,000 = $10,000. Under Section 4958, an organization manager who knowingly participates in an excess benefit transaction pays 10% of the excess benefit, capped at $20,000 per transaction: 10% x $300,000 = $30,000, but the cap limits it to $20,000. Combined exposure is $30,000. Option C is incorrect because the Section 4941 manager tax rate is 5%, not 10%—the 10% rate applies to the self-dealer, not the manager.', 'hard', 4),

-- Q23: medium / L3 — NOL deduction for UBI
(3, 'Tax-Exempt Organizations', 'Eastside Community Services, a 501(c)(3), had an unrelated business loss of $35,000 in 2025 from operating a parking lot. In 2026, the organization earns $50,000 of unrelated business income from the same parking lot. How is the 2025 loss treated for 2026 UBIT purposes?', '["The loss cannot be carried forward because tax-exempt organizations are not allowed NOL deductions", "The loss may offset the organization''s 2026 investment income and exempt-function revenue", "The $35,000 loss carries forward and reduces 2026 UBI, resulting in $15,000 of unrelated business income before the specific deduction", "The loss must be carried back two years before any forward carryover is permitted"]'::jsonb, 2, 'Under Section 512(b)(6), tax-exempt organizations may compute a net operating loss deduction using only items of unrelated business income and deductions. The $35,000 UBI loss from 2025 carries forward to 2026, reducing the $50,000 of UBI to $15,000 before the $1,000 specific deduction. Option B is incorrect because NOLs from unrelated business activities may only offset other UBI—they cannot reduce the organization''s investment income or other exempt-function revenue.', 'medium', 3),

-- Q24: easy / L2 — Schedule J (compensation information)
(3, 'Tax-Exempt Organizations', 'A donor researching a 501(c)(3) organization wants to review the compensation paid to the organization''s top executives. Which Form 990 schedule provides this information?', '["Schedule A — Public Charity Status and Public Support", "Schedule B — Schedule of Contributors", "Schedule D — Supplemental Financial Statements", "Schedule J — Compensation Information"]'::jsonb, 3, 'Under IRC Section 6033, Schedule J of Form 990 reports compensation information for officers, directors, trustees, key employees, and highest compensated employees. It discloses base compensation, bonus and incentive pay, deferred compensation, nontaxable benefits, and total compensation. Option B is incorrect because Schedule B reports contributor information and is confidential—not publicly available—so it would not help a donor research executive compensation.', 'easy', 2),

-- Q25: medium / L2 — Royalties exclusion from UBIT
(3, 'Tax-Exempt Organizations', 'Creative Arts Foundation, a 501(c)(3) museum, licenses its name and logo to a merchandise company that manufactures branded products. The foundation receives $75,000 annually in royalty payments and provides no services related to manufacturing or marketing. How are the royalty payments treated for UBIT purposes?', '["The $75,000 is excluded from UBIT as passive royalty income under Section 512(b)(2)", "The $75,000 is subject to UBIT because the licensing involves the organization''s name", "The $75,000 is subject to UBIT because it represents a regularly carried-on trade or business", "Only $74,000 is excluded after applying the $1,000 specific deduction to the full amount"]'::jsonb, 0, 'Under Section 512(b)(2), royalties are specifically excluded from UBIT as passive income. When a tax-exempt organization licenses its name, logo, or other intellectual property and provides no significant services in connection with the license, the payments qualify as royalties. Because the Foundation provides no manufacturing or marketing services, the $75,000 is excluded. Option B is incorrect because licensing an organization''s name does not convert royalties into active trade or business income when no significant services accompany the license.', 'medium', 2),

-- Q26: medium / L2 — "Regularly carried on" test application
(3, 'Tax-Exempt Organizations', 'Heritage Cultural Society, a 501(c)(3), operates a two-week antique sale each December as its annual fundraiser. The event generates $45,000 in net income. No similar activities occur during the rest of the year. Is this income subject to UBIT?', '["Yes, because the sale generates income exceeding the $1,000 specific deduction", "No, because an annual two-week event is not conducted with frequency and continuity comparable to commercial operations and fails the regularly carried on prong", "Yes, because selling merchandise is always an unrelated trade or business for exempt organizations", "No, because all fundraising activities by 501(c)(3) organizations are automatically exempt from UBIT"]'::jsonb, 1, 'Under IRC Section 512, income is subject to UBIT only if the trade or business is regularly carried on. An activity is regularly carried on if conducted with frequency and continuity comparable to commercial enterprises. A two-week annual event lacks the year-round frequency of a commercial antique dealer, so it fails the regularly carried on prong. Option A is incorrect because the dollar amount of income does not determine whether an activity is regularly carried on—the key factor is frequency and continuity of the activity.', 'medium', 2),

-- Q27: medium / L2 — Section 4945 lobbying by private foundation
(3, 'Tax-Exempt Organizations', 'The Henderson Family Foundation, a private foundation, pays $35,000 to a consulting firm for legislative advocacy on education policy. Under which IRC section is this expenditure subject to an excise tax, and what is the applicable rate?', '["Section 4941 — 10% tax as a self-dealing transaction", "Section 4944 — 10% tax as a jeopardizing investment", "Section 4945 — 20% tax as a taxable expenditure for lobbying", "Section 4940 — 1.39% tax on net investment income"]'::jsonb, 2, 'Under Section 4945, lobbying expenditures by a private foundation are classified as taxable expenditures, subject to a 20% initial excise tax on the foundation. Unlike public charities, which may engage in limited lobbying under the substantial part test or Section 501(h) election, private foundations face an excise tax on any lobbying expenditure. Option A is incorrect because Section 4941 addresses self-dealing between the foundation and disqualified persons, not lobbying activities.', 'medium', 2),

-- Q28: medium / L3 — Correction period and total excise tax for excess benefit
(3, 'Tax-Exempt Organizations', 'Marcus Jefferson, the executive director of a 501(c)(3) social services agency, received total compensation of $650,000 when comparable executives earn $280,000. The IRS determines the excess benefit is $370,000 and imposes the initial 25% excise tax of $92,500. Jefferson fails to correct the excess benefit within the taxable period. What is his total excise tax liability?', '["$92,500, representing the initial 25% tax only with no additional penalty", "$370,000, representing 100% of the excess benefit as an additional tax", "$462,500, representing the initial 25% plus an additional 100% of the excess benefit", "$832,500, representing the initial 25% tax of $92,500 plus the additional 200% tax of $740,000"]'::jsonb, 3, 'Under Section 4958, a disqualified person who fails to correct an excess benefit transaction faces both the initial 25% tax ($92,500) and an additional 200% tax ($370,000 x 200% = $740,000), totaling $832,500. Correction requires undoing the excess benefit to the extent possible, typically by repaying the excess amount plus interest. Option C is incorrect because the additional tax is 200%, not 100%, of the excess benefit amount.', 'medium', 3),

-- Q29: easy / L1 — Supporting organization definition
(3, 'Tax-Exempt Organizations', 'Under Section 509(a)(3), what is a supporting organization?', '["An organization that provides grants exclusively to individuals for educational purposes", "A 501(c)(3) organization that is organized and operated exclusively to support one or more public charities", "An organization that supports political campaigns on behalf of candidates for public office", "A for-profit entity that donates a percentage of its revenue to charitable organizations"]'::jsonb, 1, 'Under Section 509(a)(3), a supporting organization is a 501(c)(3) entity organized and operated exclusively for the benefit of, to perform the functions of, or to carry out the purposes of one or more public charities. Supporting organizations are classified as public charities, avoiding private foundation restrictions. Option A is incorrect because supporting organizations direct support to other exempt organizations, and their defining characteristic is their structural relationship with a supported public charity.', 'easy', 1),

-- Q30: medium / L3 — Operational test application
(3, 'Tax-Exempt Organizations', 'Brighter Tomorrow Foundation, organized under Section 501(c)(3) for educational purposes, generates revenue as follows: 55% from tuition and educational program fees, 15% from charitable donations, 10% from investment income, and 20% from operating a commercial catering business serving the general public. The catering revenue funds scholarships. Does the organization satisfy the operational test?', '["The organization likely satisfies the operational test because it is primarily engaged in educational activities, though the 20% commercial catering operation warrants scrutiny as a potentially non-exempt activity", "The organization fails the operational test because it earns investment income from non-educational sources", "The organization fails the operational test because any commercial activity disqualifies it from exempt status", "The organization automatically satisfies the operational test because all catering revenue funds scholarships"]'::jsonb, 0, 'Under the Section 501(c)(3) operational test, an organization must be operated primarily for exempt purposes. With 70% of revenue from educational activities and donations, the organization is primarily engaged in exempt purposes. However, the 20% commercial catering operation is scrutinized as a potentially unrelated activity. Option D is incorrect because using income for exempt purposes does not make the income-generating activity itself related to the exempt purpose—the source activity must be evaluated independently under the substantially related test.', 'medium', 3)
;

COMMIT;
