-- Migration: Question generation — FAR batch 13 (30 questions)
-- Date: 2026-02-28
-- Topic: Earnings Per Share
-- Difficulty: 9E / 15M / 6H
-- Bloom's: L1:8 / L2:9 / L3:8 / L4:5

BEGIN;

INSERT INTO questions (section_id, topic, stem, choices, correct_index, explanation, difficulty, cognitive_level)
VALUES

-- Q1: medium / L2 — actual mid-year conversion of convertible bonds
(2, 'Earnings Per Share', 'On June 30, Bellcrest Corp. has $500,000 of 8% convertible bonds that bondholders convert into 12,500 common shares. Bellcrest had 100,000 shares outstanding on January 1 and reports net income of $720,000 with no preferred stock. What is basic EPS?', '["$6.78", "$7.20", "$6.40", "$6.55"]'::jsonb, 0, 'Under ASC 260-10-45-10, shares issued upon actual conversion are included in the weighted-average from the conversion date. WACSO = (100,000 x 6/12) + (112,500 x 6/12) = 106,250. Basic EPS = $720,000 / 106,250 = $6.78. Choice B ($7.20) incorrectly ignores the 12,500 converted shares and divides by only 100,000.', 'medium', 2),

-- Q2: medium / L2 — weighted-average shares with shares issued for acquisition
(2, 'Earnings Per Share', 'Graystone Inc. had 200,000 shares outstanding on January 1. On September 1, Graystone issued 60,000 shares to acquire Oakmont LLC. What is the weighted-average number of shares for the year?', '["260,000", "230,000", "220,000", "200,000"]'::jsonb, 2, 'Under ASC 260-10-45-10, shares issued for a business acquisition are weighted from the acquisition date. WACSO = (200,000 x 12/12) + (60,000 x 4/12) = 200,000 + 20,000 = 220,000. Choice A (260,000) incorrectly treats all 60,000 shares as outstanding for the full year.', 'medium', 2),

-- Q3: hard / L4 — two-class method for participating preferred
(2, 'Earnings Per Share', 'Merritt Holdings has 80,000 common shares and 20,000 shares of participating preferred stock ($10 par, 5% stated dividend) that shares equally in undistributed earnings after the stated dividend. Net income is $600,000. The controller must decide how to compute basic EPS. Evaluate the proper approach and determine basic EPS for common shareholders.', '["$7.38", "$5.90", "$7.50", "$6.00"]'::jsonb, 1, 'Under ASC 260-10-45-60A, participating securities require the two-class method. Preferred dividend = 20,000 x $10 x 5% = $10,000. Undistributed = $590,000, allocated 80/100 to common = $472,000. Basic EPS = $472,000 / 80,000 = $5.90. Choice A ($7.38) incorrectly deducts only the stated dividend without allocating undistributed earnings to the participating preferred.', 'hard', 4),

-- Q4: medium / L3 — retroactive adjustment for subsequent stock split
(2, 'Earnings Per Share', 'Aldridge Corp. reported basic EPS of $4.80 for 2024 based on 150,000 weighted-average shares. On February 15, 2025, before issuing the 2024 comparative financial statements, Aldridge declares a 2-for-1 stock split. Analyze the effect on the reported 2024 EPS in the comparative statements.', '["2024 EPS remains $4.80 because the split occurred in 2025", "2024 EPS is restated to $3.20 using a 1.5-for-1 adjustment factor", "2024 EPS is disclosed only in footnotes at $2.40 with no face restatement", "2024 EPS is restated to $2.40 to reflect the stock split retroactively"]'::jsonb, 3, 'Under ASC 260-10-55-12, stock splits occurring after the balance sheet date but before financial statement issuance must be retroactively reflected in all EPS calculations presented. Restated WACSO = 300,000; EPS = $720,000 / 300,000 = $2.40. Choice A is incorrect because retroactive restatement is required regardless of the split date.', 'medium', 3),

-- Q5: medium / L2 — convertible preferred if-converted method
(2, 'Earnings Per Share', 'Clearview Technologies has net income of $900,000 and 200,000 weighted-average common shares. It also has 10,000 shares of $50 par, 8% convertible preferred stock, each convertible into 3 common shares. Basic EPS is $4.30 after deducting preferred dividends. Using the if-converted method, what is diluted EPS?', '["$4.30", "$4.09", "$3.91", "$3.74"]'::jsonb, 2, 'Under ASC 260-10-45-40, the if-converted method adds back the $40,000 preferred dividend to the numerator and adds 30,000 conversion shares to the denominator. Diluted EPS = $900,000 / 230,000 = $3.91. Since $3.91 < $4.30, the conversion is dilutive. Choice D ($3.74) incorrectly fails to add back the preferred dividends, double-counting the deduction.', 'medium', 2),

-- Q6: easy / L1 — complex capital structure definition
(2, 'Earnings Per Share', 'Under ASC 260, which of the following securities creates a requirement to present diluted EPS in addition to basic EPS?', '["Outstanding trade accounts payable", "Convertible bonds payable", "A bank revolving line of credit", "Accrued salary obligations"]'::jsonb, 1, 'Under ASC 260-10-45-1, entities with potentially dilutive securities such as convertible bonds, convertible preferred stock, stock options, or warrants must present both basic and diluted EPS. Convertible bonds are potential common shares because they may be converted into common stock. Choice A (accounts payable) is incorrect because trade payables have no conversion feature.', 'easy', 1),

-- Q7: easy / L1 — treasury stock method applies to options and warrants
(2, 'Earnings Per Share', 'Under ASC 260, the treasury stock method is used to calculate the dilutive effect of which type of security?', '["Stock options and warrants", "Convertible bonds", "Convertible preferred stock", "Contingently issuable shares"]'::jsonb, 0, 'Under ASC 260-10-45-22, the treasury stock method is applied to stock options and warrants. It assumes the options are exercised and the proceeds are used to repurchase shares at the average market price. Choice B (convertible bonds) is incorrect because convertible securities use the if-converted method under ASC 260-10-45-40.', 'easy', 1),

-- Q8: easy / L1 — participating securities definition
(2, 'Earnings Per Share', 'Under ASC 260-10-45-59A, which of the following best describes a participating security?', '["A security convertible into common stock at a fixed ratio", "A security granting the right to purchase common stock at a set price", "A security with a liquidation preference over common shareholders", "A security entitled to participate in undistributed earnings with common stock"]'::jsonb, 3, 'Under ASC 260-10-45-59A, a participating security is one that may participate in undistributed earnings with common stock, whether that participation is conditional or unconditional. Choice A describes a convertible security, not a participating security, though some securities may be both.', 'easy', 1),

-- Q9: medium / L3 — discontinued operations: control number for dilution test
(2, 'Earnings Per Share', 'Fenwick Industries reports income from continuing operations of $480,000 and a loss from discontinued operations of $120,000 (net of tax), producing net income of $360,000. Fenwick has 100,000 weighted-average shares and 5,000 stock options adding 2,000 incremental shares under the treasury stock method. Analyze which income figure controls the dilution test.', '["Net income of $360,000, because diluted EPS must reflect total results", "Income before taxes, because tax effects are excluded from the dilution test", "Income from continuing operations of $480,000, because it serves as the control number", "The loss from discontinued operations, because it is the most conservative component"]'::jsonb, 2, 'Under ASC 260-10-45-19, income from continuing operations is the control number for determining whether potentially dilutive securities are dilutive or antidilutive. Because continuing operations income is positive ($480,000), the options are dilutive and included. Choice A is incorrect because net income is not the control number under ASC 260.', 'medium', 3),

-- Q10: medium / L2 — restricted stock units in diluted EPS
(2, 'Earnings Per Share', 'Holbrook Corp. has net income of $750,000 and 150,000 weighted-average common shares. The company granted 12,000 restricted stock units (RSUs) with total unrecognized compensation cost of $180,000. The average market price is $60 per share. Using the treasury stock method, how many incremental shares are added for diluted EPS?', '["12,000", "9,000", "6,000", "3,000"]'::jsonb, 1, 'Under ASC 260-10-45-28, RSUs use the treasury stock method with unrecognized compensation cost as assumed proceeds. Shares repurchased = $180,000 / $60 = 3,000. Incremental shares = 12,000 - 3,000 = 9,000. Choice A (12,000) incorrectly treats all RSUs as incremental without considering the assumed share repurchase from unrecognized compensation.', 'medium', 2),

-- Q11: hard / L4 — loss from continuing operations makes all securities antidilutive
(2, 'Earnings Per Share', 'Northgate Enterprises reports a loss from continuing operations of $200,000, income from discontinued operations of $350,000 (net of tax), and net income of $150,000. The company has 50,000 weighted-average shares and 8,000 stock options adding 3,000 incremental shares. The CFO proposes including the options in diluted EPS because net income is positive. Evaluate whether the CFO''s proposal is correct under ASC 260.', '["The proposal is incorrect; the loss from continuing operations is the control number, making all potentially dilutive securities antidilutive", "The proposal is correct; net income is positive, so dilutive securities should be included", "The proposal is incorrect; discontinued operations income must first offset the continuing operations loss before testing dilution", "The proposal is correct; the treasury stock method is applied regardless of the income or loss position"]'::jsonb, 0, 'Under ASC 260-10-45-19, income from continuing operations (not net income) is the control number for the dilution test. Because Northgate has a loss from continuing operations, including additional shares would reduce the loss per share, which is antidilutive. All potentially dilutive securities must be excluded. Choice B is incorrect because net income is not the relevant control number.', 'hard', 4),

-- Q12: easy / L1 — which entities must present EPS
(2, 'Earnings Per Share', 'Under ASC 260, which type of entity is required to present earnings per share on the face of its income statement?', '["All entities preparing financial statements under U.S. GAAP", "Public entities with common stock or potential common stock traded in a public market", "Only entities with annual revenues exceeding $10 million", "Only entities that have declared dividends during the reporting period"]'::jsonb, 1, 'Under ASC 260-10-15-2, EPS presentation is required for public entities whose common stock or potential common stock is traded in a public market. Nonpublic entities are not required to present EPS. Choice A is incorrect because private companies following U.S. GAAP are exempt from this requirement.', 'easy', 1),

-- Q13: medium / L2 — weighted-average with treasury stock repurchase
(2, 'Earnings Per Share', 'Prescott Corp. had 180,000 shares outstanding on January 1. On August 1, Prescott repurchased 24,000 shares as treasury stock. No other share transactions occurred during the year. What is the weighted-average number of shares for the year?', '["180,000", "156,000", "170,000", "168,000"]'::jsonb, 2, 'Under ASC 260-10-45-10, repurchased shares are removed from the weighted-average from the repurchase date. WACSO = (180,000 x 7/12) + (156,000 x 5/12) = 105,000 + 65,000 = 170,000. Choice A (180,000) incorrectly ignores the repurchase, and Choice B (156,000) incorrectly treats the repurchase as if it occurred on January 1.', 'medium', 2),

-- Q14: medium / L2 — warrants using treasury stock method
(2, 'Earnings Per Share', 'Dunmore Industries has 300,000 common shares outstanding and net income of $1,200,000 with no preferred stock. The company has 15,000 warrants with an exercise price of $35 per share and the average market price during the period is $50. Using the treasury stock method, what is diluted EPS?', '["$4.00", "$3.94", "$3.81", "$3.87"]'::jsonb, 1, 'Under ASC 260-10-45-22, warrants are treated the same as stock options under the treasury stock method. Proceeds = 15,000 x $35 = $525,000. Shares repurchased = $525,000 / $50 = 10,500. Incremental shares = 4,500. Diluted EPS = $1,200,000 / 304,500 = $3.94. Choice C ($3.81) incorrectly adds all 15,000 warrant shares without netting the repurchased shares.', 'medium', 2),

-- Q15: easy / L1 — stock splits after balance sheet date require retroactive restatement
(2, 'Earnings Per Share', 'Under ASC 260, how must a stock split occurring after the balance sheet date but before financial statement issuance be treated for EPS purposes?', '["Disclosed only in the footnotes to the financial statements", "Ignored until the period in which the stock split occurs", "Reported as a subsequent event with no effect on EPS calculations", "Applied retroactively to all periods presented in the financial statements"]'::jsonb, 3, 'Under ASC 260-10-55-12, stock splits and stock dividends occurring after the balance sheet date but before issuance of financial statements must be given retroactive effect in all EPS computations presented. Choice A is incorrect because footnote disclosure alone is insufficient; the per-share amounts must be restated.', 'easy', 1),

-- Q16: easy / L1 — antidilutive securities excluded from diluted EPS
(2, 'Earnings Per Share', 'Under ASC 260, what is the required treatment of antidilutive securities when computing diluted EPS?', '["They are included in diluted EPS to present the most conservative figure", "They are included only if they become dilutive by year-end", "They are excluded from the diluted EPS computation", "They are deducted from the basic EPS numerator as a separate adjustment"]'::jsonb, 2, 'Under ASC 260-10-45-17, securities whose inclusion would increase EPS or decrease the loss per share are antidilutive and must be excluded from diluted EPS. The purpose of diluted EPS is to show the maximum potential dilution. Choice A is incorrect because including antidilutive securities would overstate per-share earnings, not present a conservative figure.', 'easy', 1),

-- Q17: easy / L1 — stock dividends retroactively adjust all prior WACSO
(2, 'Earnings Per Share', 'Under ASC 260, a stock dividend declared during the current year affects the weighted-average shares calculation by:', '["Being applied retroactively to all shares outstanding before the dividend date", "Being weighted from the declaration date through year-end", "Being weighted from the record date through year-end", "Being weighted from the payment date through year-end"]'::jsonb, 0, 'Under ASC 260-10-45-13, stock dividends and stock splits are applied retroactively to all shares outstanding before the event, as if the dividend had occurred at the beginning of the earliest period presented. Choice B is incorrect because stock dividends are not time-weighted like new share issuances for cash or services.', 'easy', 1),

-- Q18: easy / L2 — if-converted numerator adjustment: interest net of tax
(2, 'Earnings Per Share', 'Ridgeway Corp. has $400,000 of 6% convertible bonds outstanding for the full year. The income tax rate is 25%. When applying the if-converted method to test these bonds for dilution, what amount is added back to the numerator?', '["$24,000", "$6,000", "$12,000", "$18,000"]'::jsonb, 3, 'Under ASC 260-10-45-40, the if-converted method adds back interest expense on the convertible bonds, net of income tax. Interest = $400,000 x 6% = $24,000. Net of tax = $24,000 x (1 - 0.25) = $18,000. Choice A ($24,000) incorrectly uses gross interest without the tax adjustment, overstating the numerator add-back.', 'easy', 2),

-- Q19: medium / L3 — contingently issuable shares when conditions not yet met
(2, 'Earnings Per Share', 'Wexford Manufacturing has an agreement to issue 25,000 additional common shares if cumulative revenue over three years exceeds $15 million. After two years, cumulative revenue is $8.2 million and the condition has not been met. Analyze how these shares should be treated in the current year''s basic EPS computation.', '["Included because the company is on track to meet the revenue target", "Excluded because the contingency condition has not yet been satisfied at the reporting date", "Included at a prorated 16,667 shares reflecting two-thirds of the performance period", "Included at a probability-weighted estimate based on projected third-year revenue"]'::jsonb, 1, 'Under ASC 260-10-45-48, contingently issuable shares are included in basic EPS only if all necessary conditions have been satisfied by the end of the reporting period. Since cumulative revenue has not exceeded $15 million, the shares are excluded. Choice A is incorrect because being on track does not satisfy the condition; the threshold must actually be met.', 'medium', 3),

-- Q20: hard / L4 — ranking multiple dilutive securities
(2, 'Earnings Per Share', 'Stratton Financial has basic EPS of $5.00 (net income $1,000,000, 200,000 shares). Three potentially dilutive securities exist: (1) stock options adding 8,000 incremental shares with no numerator effect, (2) $200,000 of 5% convertible bonds (tax rate 25%) converting into 6,000 shares, and (3) 4,000 shares of 6% convertible preferred ($100 par) converting into 10,000 common shares. Evaluate the ranking and determine diluted EPS.', '["$4.60", "$4.71", "$4.81", "$4.50"]'::jsonb, 0, 'Under ASC 260-10-45-21, potentially dilutive securities are ranked by per-share impact: options ($0/8,000 = $0.00), bonds ($7,500/6,000 = $1.25), preferred ($24,000/10,000 = $2.40). Including all three in order: diluted EPS = $1,031,500 / 224,000 = $4.60. Choice D ($4.50) incorrectly includes preferred shares without adding back the $24,000 dividend to the numerator.', 'hard', 4),

-- Q21: medium / L3 — convertible bonds antidilutive scenario
(2, 'Earnings Per Share', 'Hartfield Corp. has basic EPS of $2.50 (net income $500,000, 200,000 shares). The company has $1,000,000 of 10% convertible bonds convertible into 20,000 common shares with a tax rate of 25%. Analyze whether these bonds are dilutive or antidilutive and determine the reported diluted EPS.', '["$2.61, because the bonds must be included under the if-converted method", "$2.39, because the bonds reduce EPS when properly included", "$2.50, because the bonds are antidilutive and must be excluded from diluted EPS", "$2.27, because the full interest amount is deducted without a tax adjustment"]'::jsonb, 2, 'Under ASC 260-10-45-17, if inclusion of a convertible security would increase EPS, it is antidilutive and must be excluded. If-converted: numerator = $500,000 + ($100,000 x 0.75) = $575,000; denominator = 220,000. Tentative EPS = $2.61 > $2.50 basic, confirming antidilution. Choice A is incorrect because antidilutive securities are never included.', 'medium', 3),

-- Q22: hard / L4 — written put options (reverse treasury stock method)
(2, 'Earnings Per Share', 'Kensington Corp. has 250,000 shares outstanding, net income of $1,500,000, and has written a put option obligating it to repurchase 20,000 shares at $60 when the average market price is $50. The controller must evaluate how this in-the-money written put affects diluted EPS under ASC 260. Assess the proper treatment.', '["The put option is antidilutive because repurchasing shares always reduces the denominator", "The put option is dilutive, adding 4,000 incremental shares and producing diluted EPS of $5.91", "The put option requires deducting the $200,000 settlement cost from the EPS numerator", "The put option has no effect on diluted EPS because it has not been exercised"]'::jsonb, 1, 'Under ASC 260-10-45-35, in-the-money written puts are dilutive. Shares assumed purchased at market = (20,000 x $60) / $50 = 24,000. Incremental shares = 24,000 - 20,000 = 4,000. Diluted EPS = $1,500,000 / 254,000 = $5.91. Choice D is incorrect because ASC 260 requires assumed exercise of in-the-money instruments regardless of actual exercise.', 'hard', 4),

-- Q23: medium / L3 — share-based compensation: unrecognized cost in assumed proceeds
(2, 'Earnings Per Share', 'Waverly Corp. grants 20,000 stock options with an exercise price of $30 on January 1, 2025. The average market price for 2025 is $45. Total unrecognized compensation cost as of December 31, 2025, is $400,000. Analyze how the unrecognized compensation cost affects the treasury stock method computation for diluted EPS.', '["The unrecognized cost is ignored; only the exercise price determines assumed proceeds", "The unrecognized cost reduces the numerator as an additional expense adjustment", "The unrecognized cost increases the denominator by 8,889 incremental shares", "The unrecognized cost is added to assumed proceeds, reducing incremental shares and potentially making the options antidilutive"]'::jsonb, 3, 'Under ASC 260-10-45-29, assumed proceeds under the treasury stock method include the exercise price plus unrecognized compensation cost. Total proceeds = $600,000 + $400,000 = $1,000,000. Shares repurchased = $1,000,000 / $45 = 22,222, exceeding the 20,000 options, making them antidilutive. Choice A is incorrect because ASC 260 explicitly requires including unrecognized compensation cost.', 'medium', 3),

-- Q24: hard / L4 — interim period EPS: quarterly vs year-to-date WACSO
(2, 'Earnings Per Share', 'Harborview Inc. has 100,000 shares outstanding on January 1 and issues 30,000 additional shares on March 1. First-quarter net income is $120,000. Second-quarter net income is $90,000 with no additional share transactions. The CFO must compute the weighted-average shares for Q2 standalone and the year-to-date six-month period. Evaluate the correct share counts.', '["Q2: 130,000 shares; year-to-date: 120,000 shares", "Q2: 130,000 shares; year-to-date: 110,000 shares", "Q2: 120,000 shares; year-to-date: 115,000 shares", "Q2: 130,000 shares; year-to-date: 130,000 shares"]'::jsonb, 0, 'Under ASC 260-10-45-10, WACSO must be independently computed for each reporting period. Q2 standalone: 130,000 shares for all three months. Year-to-date: (100,000 x 2/6) + (130,000 x 4/6) = 33,333 + 86,667 = 120,000. Choice D (130,000 for YTD) incorrectly uses the ending balance instead of the time-weighted average.', 'hard', 4),

-- Q25: medium / L2 — weighted-average with shares issued for services
(2, 'Earnings Per Share', 'Brookstone Corp. had 90,000 shares outstanding on January 1. On May 1, it issued 6,000 shares to consultants as compensation. On November 1, it issued 12,000 shares for cash. What is the weighted-average number of shares for the year?', '["108,000", "99,000", "96,000", "90,000"]'::jsonb, 2, 'Under ASC 260-10-45-10, shares issued for services are weighted from the issuance date. WACSO = (90,000 x 4/12) + (96,000 x 6/12) + (108,000 x 2/12) = 30,000 + 48,000 + 18,000 = 96,000. Choice A (108,000) incorrectly uses the year-end outstanding balance without time-weighting.', 'medium', 2),

-- Q26: medium / L3 — two-class method requirement for participating preferred
(2, 'Earnings Per Share', 'Lantern Corp. has common stock and Series A preferred stock outstanding. The Series A preferred receives a 5% cumulative dividend and also participates equally with common stock in any dividends above the stated preferred rate. The controller is determining which EPS computation method to apply. Analyze the correct approach under ASC 260.', '["The treasury stock method, because the preferred stock has a fixed dividend rate", "The two-class method, because the preferred stock is a participating security sharing in undistributed earnings", "Either method at the company''s discretion under ASC 260", "The if-converted method, because the preferred has characteristics similar to convertible securities"]'::jsonb, 1, 'Under ASC 260-10-45-60A, when an entity has participating securities, the two-class method is required for computing basic EPS. The Series A preferred is a participating security because it shares in undistributed earnings beyond its stated rate. Choice D is incorrect because the if-converted method applies to convertible securities, not participating securities.', 'medium', 3),

-- Q27: medium / L2 — diluted EPS with both convertible preferred and stock options
(2, 'Earnings Per Share', 'Marston Inc. reports net income of $840,000 with 200,000 weighted-average shares. It has 5,000 shares of $100 par, 4% convertible preferred stock (each converting into 5 common shares) and 10,000 stock options with an exercise price of $25 (average market price $50). Using the if-converted and treasury stock methods, what is diluted EPS?', '["$4.10", "$4.00", "$3.74", "$3.65"]'::jsonb, 3, 'Under ASC 260-10-45-21, securities are ranked by per-share impact. Options: $0/5,000 = $0.00; preferred: $20,000/25,000 = $0.80. Step 1 (options): $820,000 / 205,000 = $4.00. Step 2 (preferred): $840,000 / 230,000 = $3.65. Both dilutive. Choice C ($3.74) results from incorrectly failing to add back the $20,000 preferred dividend in the if-converted numerator.', 'medium', 2),

-- Q28: hard / L3 — cumulative preferred arrearage effect on basic EPS
(2, 'Earnings Per Share', 'Thornbury Corp. has 10,000 shares of $50 par, 6% cumulative preferred stock. No preferred dividends have been declared for the past three years, including the current year. Net income for the current year is $580,000 with 100,000 weighted-average common shares. Analyze how the three-year arrearage affects the current year''s basic EPS computation.', '["$4.90, because all three years of accumulated dividends must be deducted", "$5.80, because undeclared cumulative dividends are never deducted from EPS", "$5.20, because two years of prior arrearage are deducted as a prior-period adjustment", "$5.50, because only the current year''s preferred dividend is deducted regardless of declaration"]'::jsonb, 3, 'Under ASC 260-10-45-11, for cumulative preferred stock, only the current period''s dividend is deducted from the numerator for basic EPS, whether or not declared. Prior-year arrearages are not deducted again. EPS = ($580,000 - $30,000) / 100,000 = $5.50. Choice A ($4.90) incorrectly deducts all three years of dividends ($90,000) from the current year''s numerator.', 'hard', 3),

-- Q29: medium / L3 — error analysis: using year-end shares instead of WACSO
(2, 'Earnings Per Share', 'Eastgate Corp. had 160,000 shares outstanding on January 1 and net income of $640,000. On July 1, Eastgate repurchased 40,000 shares as treasury stock. An analyst uses the year-end share count of 120,000 to calculate basic EPS as $5.33. Analyze the error and determine the correct basic EPS.', '["$4.57, because shares must be time-weighted to reflect the repurchase date", "$5.33, because year-end outstanding shares is the correct denominator", "$4.00, because the repurchase cost must also be deducted from the numerator", "$3.56, because repurchased shares are excluded from WACSO for the entire year"]'::jsonb, 0, 'Under ASC 260-10-45-10, basic EPS uses weighted-average shares, not year-end outstanding shares. WACSO = (160,000 x 6/12) + (120,000 x 6/12) = 140,000. Correct EPS = $640,000 / 140,000 = $4.57. Choice B ($5.33) reflects the analyst''s error of dividing by the 120,000 year-end balance instead of the time-weighted average.', 'medium', 3),

-- Q30: easy / L1 — diluted EPS is always less than or equal to basic EPS
(2, 'Earnings Per Share', 'Under ASC 260, the relationship between basic EPS and diluted EPS is that diluted EPS is:', '["Always less than or equal to basic EPS", "Always greater than basic EPS when convertible securities exist", "Equal to basic EPS only when there are no preferred dividends", "Computed independently with no required relationship to basic EPS"]'::jsonb, 0, 'Under ASC 260-10-45-17, because antidilutive securities are excluded from diluted EPS, diluted EPS can never exceed basic EPS. If no potentially dilutive securities exist, diluted EPS equals basic EPS. Choice B is incorrect because including convertible securities only decreases (dilutes) EPS or leaves it unchanged if they are antidilutive and excluded.', 'easy', 1)
;

COMMIT;
