-- Migration: Question generation — REG batch 19 (30 questions)
-- Date: 2026-02-28
-- Topic: Tax-Exempt Organizations
-- Difficulty: 9E / 15M / 6H
-- Bloom's: L1:8 / L2:9 / L3:8 / L4:5

BEGIN;

INSERT INTO questions (section_id, topic, stem, choices, correct_index, explanation, difficulty, cognitive_level)
VALUES

-- Q1: hard / L4 — Controlled entity payments as UBIT under Section 512(b)(13)
(3, 'Tax-Exempt Organizations', 'Helping Hands Foundation, a 501(c)(3) charity, owns 100% of CleanCo, Inc., a for-profit cleaning service. CleanCo pays Helping Hands $120,000 in annual rent for office space, which is $30,000 above fair market value. How should Helping Hands treat the $120,000 rent payment for UBIT purposes under Section 512(b)(13)?', '["The $30,000 excess above fair market value is included in UBIT; the $90,000 at fair market value is excluded as passive rental income", "The entire $120,000 is excluded from UBIT because rents from real property are always exempt from UBIT", "The entire $120,000 is included in UBIT because any rent from a controlled subsidiary is fully taxable", "None of the rent is included in UBIT because the foundation uses the income for charitable purposes"]'::jsonb, 0, 'Under IRC Section 512(b)(13), rent received from a controlled entity (80%+ ownership) is treated as UBIT only to the extent it exceeds fair market value. The $90,000 at FMV retains its character as excluded passive rental income, while the $30,000 excess is included in UBIT. Choice C is incorrect because only the excess over FMV, not the entire payment, is reclassified as unrelated business income.', 'hard', 4),

-- Q2: easy / L1 — Section 501(h) expenditure test election
(3, 'Tax-Exempt Organizations', 'What does the Section 501(h) election provide for a 501(c)(3) organization?', '["An exemption from all UBIT on lobbying-related income", "Permission to engage in unlimited political campaign activity", "Specific dollar thresholds as a safe harbor for permissible lobbying expenditures", "Automatic classification as a public charity rather than a private foundation"]'::jsonb, 2, 'Under IRC Section 501(h), eligible 501(c)(3) organizations may elect to use specific dollar-based expenditure limits as a safe harbor for lobbying activities, replacing the vague ''substantial part'' test. Choice B is incorrect because Section 501(h) addresses lobbying only; political campaign activity remains absolutely prohibited for all 501(c)(3) organizations regardless of any election.', 'easy', 1),

-- Q3: medium / L2 — Supporting organization classification under Section 509(a)(3)
(3, 'Tax-Exempt Organizations', 'Literacy Partners, Inc. is organized and operated exclusively to raise funds for Riverside Public Library, a 501(c)(3) public charity. Literacy Partners transfers all net revenue to Riverside annually and is governed by a board appointed by Riverside. Under what provision does Literacy Partners qualify as a public charity?', '["Section 509(a)(1) because it receives substantial public support", "Section 509(a)(3) because it is a supporting organization operated exclusively to benefit a public charity", "Section 509(a)(2) because it meets the gross receipts test", "Section 509(a)(4) because it tests for public safety"]'::jsonb, 1, 'Under IRC Section 509(a)(3), an organization qualifies as a public charity if it is organized and operated exclusively to support one or more public charities. Literacy Partners meets this test by existing solely to raise funds for Riverside Public Library, with governance controlled by the supported organization. Choice A is incorrect because Literacy Partners does not independently receive broad public support—it qualifies through its supporting relationship.', 'medium', 2),

-- Q4: medium / L2 — Dissolution clause requirement in organizational test
(3, 'Tax-Exempt Organizations', 'New Dawn Community Services submits its Form 1023 application for 501(c)(3) status. The IRS reviews the articles of incorporation and notes that the document limits activities to charitable and educational purposes but contains no provision for distributing assets upon dissolution. What is the most likely IRS response?', '["Approval with a condition that the dissolution clause be added within five years", "Automatic approval because the charitable purpose limitation is sufficient", "Approval as a private foundation instead of a public charity", "Denial because the organizational test requires a dissolution clause directing assets to another exempt organization or government"]'::jsonb, 3, 'Under IRC Section 501(c)(3), the organizational test requires that governing documents include a dissolution clause providing that assets will be distributed to another exempt organization or to the government upon dissolution. Without this clause, the application fails the organizational test. Choice A is incorrect because the IRS does not conditionally approve applications with missing dissolution clauses—the deficiency must be corrected before approval.', 'medium', 2),

-- Q5: medium / L3 — Personal property rents vs real property rents in UBIT
(3, 'Tax-Exempt Organizations', 'Heritage Cultural Center, a 501(c)(3), leases a building to a commercial tenant. The lease provides for $200,000 annual rent for the building and $40,000 for furniture, fixtures, and office equipment included in the space. The personal property rent is 20% of total rent. How is the $240,000 total rent treated for UBIT purposes?', '["The entire $240,000 is included in UBIT because personal property rent exceeds the 10% incidental threshold under Section 512(b)(3)", "Only the $40,000 personal property rent is included in UBIT; the $200,000 real property rent is excluded", "The entire $240,000 is excluded because all rents from leasing property are passive income", "Only $24,000 (10% of total rent) is included in UBIT as the statutory maximum"]'::jsonb, 0, 'Under IRC Section 512(b)(3), rents from real property are excluded from UBIT, but when personal property is leased with real property and the personal property rent exceeds 10% of total rent, the entire rental amount becomes UBIT. Here, personal property rent is $40,000/$240,000 = 16.7%, exceeding the 10% threshold, so all $240,000 is taxable. Choice B is incorrect because the rule does not split the rent—once the 10% threshold is exceeded, the full amount is included.', 'medium', 3),

-- Q6: easy / L1 — Form 990-N (e-Postcard) definition and threshold
(3, 'Tax-Exempt Organizations', 'What is the Form 990-N (e-Postcard) for tax-exempt organizations?', '["A detailed annual return required for organizations with gross receipts over $200,000", "A private foundation return required regardless of organization size", "An electronic notice for small organizations with gross receipts normally $50,000 or less", "A quarterly estimated tax payment form for exempt organizations with UBIT"]'::jsonb, 2, 'Under IRC Section 6033, the Form 990-N (e-Postcard) is a simplified electronic notice available to small tax-exempt organizations with gross receipts normally $50,000 or less. It requires only basic information such as name, address, EIN, and confirmation of continued eligibility. Choice A describes Form 990, which is the full annual return for larger organizations with gross receipts of $200,000 or more or total assets of $500,000 or more.', 'easy', 1),

-- Q7: medium / L3 — Foundation manager excise tax rate for self-dealing
(3, 'Tax-Exempt Organizations', 'Palmer Family Foundation, a private foundation, purchases a vacation property from its founder, David Palmer, for $400,000 at fair market value. The foundation''s treasurer, who serves as a board member, reviews and approves the transaction, believing the FMV price makes it permissible. What excise taxes apply under Section 4941?', '["$40,000 on David Palmer only; no tax on the treasurer because the price was fair", "$40,000 initial tax on David Palmer as the self-dealer, plus $20,000 on the treasurer as a foundation manager who knowingly approved the transaction", "$20,000 on David Palmer and $40,000 on the treasurer for approving a prohibited transaction", "No excise tax because the property was purchased at fair market value"]'::jsonb, 1, 'Under IRC Section 4941, self-dealing between a private foundation and a disqualified person is prohibited based on the nature of the transaction, regardless of price. The initial tax is 10% on the self-dealer ($400,000 x 10% = $40,000) and 5% on any foundation manager who knowingly participates ($400,000 x 5% = $20,000). Choice D is incorrect because Section 4941 is a per se rule—fair market value does not excuse the prohibited transaction.', 'medium', 3),

-- Q8: hard / L3 — NOL carryforward deduction for UBIT
(3, 'Tax-Exempt Organizations', 'Beacon Youth Alliance, a 501(c)(3), had $180,000 of unrelated business losses in 2024 and $50,000 of unrelated business losses in 2025. In 2026, Beacon has $300,000 of gross unrelated business income and $60,000 of directly connected expenses. After applying the $1,000 specific deduction and all available NOL carryforwards, what is Beacon''s 2026 unrelated business taxable income?', '["$239,000", "$59,000", "$69,000", "$9,000"]'::jsonb, 3, 'Under IRC Section 512, UBIT allows a net operating loss deduction computed using only unrelated business income items. Beacon''s 2026 net UBI before NOL: $300,000 - $60,000 = $240,000. Less NOL carryforwards: $180,000 + $50,000 = $230,000. Subtotal: $10,000. Less $1,000 specific deduction: $9,000. Choice A is incorrect because it ignores the NOL carryforward entirely, computing only the specific deduction and direct expenses.', 'hard', 3),

-- Q9: easy / L2 — Churches as automatic public charities
(3, 'Tax-Exempt Organizations', 'Grace Community Church receives 95% of its support from a single wealthy family and only 5% from the general public. How is Grace Community Church classified for federal tax purposes?', '["Private foundation because it fails the one-third public support test", "Private operating foundation because it conducts religious activities", "Public charity because churches are automatically classified as public charities regardless of funding sources", "Tax-exempt but unclassified until the IRS reviews its Form 990"]'::jsonb, 2, 'Under IRC Section 509(a)(1) and Section 170(b)(1)(A)(i), churches are automatically classified as public charities regardless of their funding sources. Grace Community Church qualifies as a public charity by virtue of being a church, even though its support comes primarily from one family. Choice A is incorrect because the one-third public support test does not apply to churches—they receive automatic public charity classification.', 'easy', 2),

-- Q10: medium / L2 — Form 990 vs Form 990-EZ filing thresholds
(3, 'Tax-Exempt Organizations', 'Green Valley Animal Rescue, a 501(c)(3), has gross receipts of $185,000 and total assets of $350,000 for the tax year. Which annual information return must Green Valley file with the IRS?', '["Form 990 because gross receipts exceed $50,000", "Form 990-N because total assets are under $500,000", "Form 990-PF because it is presumed to be a private foundation", "Form 990-EZ because gross receipts are under $200,000 and total assets are under $500,000"]'::jsonb, 3, 'Under IRC Section 6033, Form 990-EZ may be filed when gross receipts are less than $200,000 AND total assets are less than $500,000. Green Valley meets both thresholds ($185,000 < $200,000 and $350,000 < $500,000). Choice A is incorrect because Form 990 is required only when gross receipts are $200,000 or more OR total assets are $500,000 or more—neither threshold is met here.', 'medium', 2),

-- Q11: easy / L1 — Bingo games UBIT exclusion
(3, 'Tax-Exempt Organizations', 'Under UBIT rules, when is income from bingo games excluded from unrelated business taxable income?', '["When bingo is legal in the jurisdiction and commercial bingo is not ordinarily carried out in that area", "When bingo proceeds are used exclusively for charitable purposes", "When bingo games are conducted fewer than four times per year", "When bingo games are operated by a private foundation"]'::jsonb, 0, 'Under IRC Section 513(f), bingo game income is excluded from UBIT when the games are conducted legally and commercial bingo is not ordinarily carried out in the same jurisdiction. This ensures the exemption applies only where the exempt organization is not competing with commercial operators. Choice B is incorrect because the exclusion depends on the competitive environment, not on how the proceeds are used.', 'easy', 1),

-- Q12: easy / L1 — Filing deadline for Form 990
(3, 'Tax-Exempt Organizations', 'What is the filing deadline for Form 990 for a calendar-year tax-exempt organization?', '["March 15 of the following year", "May 15 of the following year", "April 15 of the following year", "June 15 of the following year"]'::jsonb, 1, 'Under IRC Section 6033, Form 990 is due on the 15th day of the 5th month after the end of the organization''s tax year. For calendar-year organizations, this is May 15. Extensions of up to 6 months are available using Form 8868. Choice A is incorrect because March 15 is the filing deadline for partnership and S corporation returns, not for exempt organization information returns.', 'easy', 1),

-- Q13: medium / L2 — Convenience exclusion application
(3, 'Tax-Exempt Organizations', 'Regional Medical Center, a 501(c)(3) hospital, operates a cafeteria on its premises that serves meals to patients, their families, visitors, and hospital employees during regular business hours. The cafeteria generates $350,000 in annual revenue. Under the convenience exclusion, how is this cafeteria income treated for UBIT purposes?', '["Fully taxable because the cafeteria is open to visitors who are not patients or employees", "Partially taxable—only income from visitors is subject to UBIT", "Excluded from UBIT because the cafeteria is conducted primarily for the convenience of patients and employees", "Excluded from UBIT because all food service operations at hospitals are automatically exempt"]'::jsonb, 2, 'Under IRC Section 513(a)(2), an activity conducted primarily for the convenience of the organization''s members, students, patients, or employees is excluded from UBIT. A hospital cafeteria primarily serving patients, families, and staff qualifies even though visitors also use it. Choice D is incorrect because there is no blanket exemption for hospital food services—the convenience exclusion requires that the activity primarily serve the specified groups.', 'medium', 2),

-- Q14: medium / L3 — One-third support test under Section 509(a)(1)
(3, 'Tax-Exempt Organizations', 'Coastal Education Alliance, a 501(c)(3), received the following support over the past four years: $600,000 from government grants, $300,000 from public donations, and $200,000 from investment income. Total support is $1,100,000. Under the one-third support test of Section 509(a)(1), does Coastal qualify as a public charity?', '["No, because government grants do not count as public support under Section 509(a)(1)", "No, because investment income is included in the support calculation, reducing the public support ratio", "Yes, because public and government support ($900,000) exceeds one-third of total support ($366,667)", "Yes, but only if Coastal also meets the facts-and-circumstances test"]'::jsonb, 2, 'Under IRC Section 509(a)(1), an organization qualifies as a public charity if it normally receives at least one-third of its total support from government sources and the general public. Coastal received $900,000 in qualifying support out of $1,100,000 total (81.8%), well exceeding the one-third threshold. Choice A is incorrect because government grants are specifically included as qualifying public support under Section 509(a)(1).', 'medium', 3),

-- Q15: medium / L2 — Section 4945 grants to non-501(c)(3) organizations
(3, 'Tax-Exempt Organizations', 'Heritage Arts Foundation, a private foundation, makes a $100,000 grant to a local civic league organized under Section 501(c)(4) to fund community art installations. The foundation does not exercise expenditure responsibility over the grant. How is this grant treated under Section 4945?', '["It is permissible because the civic league is a tax-exempt organization", "It is a taxable expenditure subject to a 20% excise tax because the foundation failed to exercise expenditure responsibility", "It is a self-dealing transaction subject to excise tax under Section 4941", "It is exempt from penalty because community art installations are a charitable purpose"]'::jsonb, 1, 'Under IRC Section 4945, a private foundation''s grant to a non-501(c)(3) organization is a taxable expenditure unless the foundation exercises expenditure responsibility to ensure the funds are used for charitable purposes. The 20% initial excise tax applies to the $100,000 grant. Choice A is incorrect because tax-exempt status under Section 501(c)(4) does not satisfy Section 4945—only grants to 501(c)(3) organizations are exempt from expenditure responsibility requirements.', 'medium', 2),

-- Q16: hard / L4 — Private inurement vs. excessive private benefit distinction
(3, 'Tax-Exempt Organizations', 'Sunrise Community Development, a 501(c)(3), enters two transactions: (1) it pays its board chair, Karen Wells, a $500,000 consulting fee for services that comparable consultants provide for $80,000, and (2) it awards a $200,000 construction contract to an unrelated company whose owner is a friend of the executive director, at $50,000 above the lowest qualified bid. How does the IRS distinguish between these transactions?', '["Both constitute private inurement because they involve excess payments", "Transaction 1 is private benefit and Transaction 2 is private inurement because the board chair has no formal authority", "Neither violates the operational test because the organization retains its charitable purpose", "Transaction 1 is private inurement because Karen Wells is an insider; Transaction 2 is excessive private benefit because the contractor is not an insider"]'::jsonb, 3, 'Under IRC Section 501(c)(3), private inurement applies only to insiders—persons with a personal and private interest in the organization''s activities, such as officers and directors. The board chair''s excess compensation is private inurement. Private benefit applies more broadly to any person, insider or not. The unrelated contractor''s inflated contract is excessive private benefit. Choice A is incorrect because private inurement requires insider status—the contractor has no governance role.', 'hard', 4),

-- Q17: medium / L3 — Late filing penalty calculation for large organizations
(3, 'Tax-Exempt Organizations', 'Springdale Youth Athletics, a 501(c)(3) with gross receipts of $1,500,000, files its Form 990 seventy-five days late without reasonable cause. Under the penalty provisions for late filing, what penalty does the IRS impose?', '["$1,500 ($20 per day for 75 days)", "$7,500 ($100 per day for 75 days)", "$53,000 (maximum penalty for larger organizations)", "$10,500 (maximum penalty for smaller organizations)"]'::jsonb, 1, 'Under IRC Section 6652(c), organizations with gross receipts of $1,186,000 or more are subject to a late-filing penalty of $100 per day, up to a maximum of $53,000. Springdale''s gross receipts of $1,500,000 trigger the higher rate: $100 x 75 days = $7,500, which is below the $53,000 cap. Choice A is incorrect because the $20 per day rate applies only to organizations with gross receipts under $1,186,000.', 'medium', 3),

-- Q18: medium / L3 — 200% additional tax on uncorrected excess benefit
(3, 'Tax-Exempt Organizations', 'Metro Community Alliance, a 501(c)(3), paid its former director, Thomas Grant, a $400,000 bonus that the IRS determined was an excess benefit of $350,000 under Section 4958. Thomas received the initial 25% excise tax assessment but did not correct the excess benefit within the taxable period. What additional consequence does Thomas face?', '["A 10% additional tax on the $350,000 excess benefit", "Automatic revocation of Metro Community Alliance''s tax-exempt status", "A 200% additional tax on the $350,000 excess benefit, totaling $700,000", "Criminal prosecution for tax fraud under Section 7201"]'::jsonb, 2, 'Under IRC Section 4958, if a disqualified person fails to correct an excess benefit transaction within the taxable period, a 200% additional tax is imposed on the excess benefit amount. Thomas faces $700,000 ($350,000 x 200%) in addition to the initial 25% tax of $87,500. Choice A is incorrect because the 10% tax applies to organization managers who knowingly participate, not as an additional penalty on the disqualified person for failure to correct.', 'medium', 3),

-- Q19: medium / L3 — Research exclusion from UBIT
(3, 'Tax-Exempt Organizations', 'Heartland Medical Research Institute, a 501(c)(3) not affiliated with any university or hospital, conducts three research projects: (1) a pharmaceutical study funded by a private drug company with proprietary results, (2) a federally funded study for the National Institutes of Health, and (3) a faculty-led study with results published in peer-reviewed journals. Which projects qualify for the UBIT research exclusion?', '["All three because research organizations are automatically exempt from UBIT on research", "Only Project 1 because commercially funded research generates the most revenue", "Only Project 2 because government-funded research is the sole exclusion", "Projects 2 and 3, but not Project 1, because the exclusion covers government-funded research and research freely available to the public"]'::jsonb, 3, 'Under IRC Section 512(b)(7)-(9), the UBIT research exclusion applies to research performed for the U.S. government and research with results freely available to the public. Project 1 fails because results are proprietary. Projects 2 (government-funded) and 3 (publicly available results) qualify. Choice A is incorrect because standalone research institutes have no blanket exemption; the proprietary nature of Project 1 disqualifies it from the exclusion.', 'medium', 3),

-- Q20: medium / L2 — Form 990-PF required for all private foundations
(3, 'Tax-Exempt Organizations', 'Carter Family Foundation, a private foundation, has gross receipts of only $25,000 and total assets of $100,000 for the tax year. The foundation''s accountant suggests filing Form 990-N because of the organization''s small size. Is the accountant correct?', '["No, all private foundations must file Form 990-PF regardless of size", "Yes, the foundation qualifies for Form 990-N because gross receipts are under $50,000", "No, the foundation should file Form 990-EZ because it meets the simplified filing thresholds", "Yes, but only if the foundation has distributed its required 5% minimum for the year"]'::jsonb, 0, 'Under IRC Section 6033, all private foundations must file Form 990-PF regardless of their size, gross receipts, or total assets. The Form 990-PF includes detailed computations for excise taxes under Sections 4940-4945. Choice B is incorrect because Form 990-N is available only to non-private-foundation exempt organizations with gross receipts of $50,000 or less—private foundations are specifically excluded from this option.', 'medium', 2),

-- Q21: hard / L4 — Mixed lease personal/real property 10% threshold analysis
(3, 'Tax-Exempt Organizations', 'Riverside Education Fund, a 501(c)(3), leases two properties. Lease A covers a building ($180,000 annual rent) with included furniture ($15,000 annual rent). Lease B covers a warehouse ($100,000 annual rent) with included computer equipment ($25,000 annual rent). Analyze how the 10% incidental personal property rule under Section 512(b)(3) applies to each lease, and determine the total amount included in UBIT.', '["$40,000 because only the personal property rent from both leases is included", "$15,000 because only the furniture rent from Lease A exceeds the threshold", "$195,000 because both leases exceed the 10% personal property threshold", "$125,000 because only Lease B exceeds the 10% threshold and its entire rent is included"]'::jsonb, 3, 'Under IRC Section 512(b)(3), when personal property rent exceeds 10% of total lease rent, the entire lease amount is UBIT. Lease A: $15,000/$195,000 = 7.7% (under 10%), so the entire $195,000 is excluded. Lease B: $25,000/$125,000 = 20% (over 10%), so the entire $125,000 is included. Total UBIT: $125,000. Choice C is incorrect because Lease A''s personal property portion is below the 10% threshold, so its full rent remains excluded as passive real property income.', 'hard', 4),

-- Q22: medium / L2 — Schedule B confidentiality on Form 990
(3, 'Tax-Exempt Organizations', 'A donor to Helping Hearts Foundation, a 501(c)(3), is concerned that her $50,000 contribution will become public when the organization files Form 990. Which statement accurately describes the public disclosure rules for Form 990 schedules?', '["All schedules, including contributor names and amounts, are publicly available", "Schedule B (Schedule of Contributors) is not publicly available, protecting donor identities from disclosure", "Only Schedule J (Compensation Information) is kept confidential", "All donor information is public, but only for contributions exceeding $100,000"]'::jsonb, 1, 'Under IRC Section 6104, Form 990 and most schedules are publicly available, but Schedule B (Schedule of Contributors) is specifically excluded from public disclosure, protecting donor identities and contribution amounts. The IRS retains Schedule B for enforcement purposes only. Choice A is incorrect because Congress carved out Schedule B from the general public inspection rules to protect donor privacy.', 'medium', 2),

-- Q23: hard / L4 — Section 4943 combined ownership with multiple disqualified persons
(3, 'Tax-Exempt Organizations', 'Whitfield Family Foundation, a private foundation, owns 12% of the voting stock of Greenleaf Industries. The foundation''s founder, Margaret Whitfield, personally owns 15%. Margaret''s son, a foundation board member, owns an additional 5%. Under the excess business holdings rules of Section 4943, determine whether excess holdings exist and the tax consequences.', '["Combined holdings are 32%, creating 12% excess holdings subject to a 10% initial excise tax on the value of the excess stock", "Only the foundation''s 12% is relevant; disqualified persons'' holdings are not aggregated", "Combined holdings are 20%, exactly at the permitted limit with no excess", "Combined holdings are 27% because the son''s shares are excluded as a non-disqualified person"]'::jsonb, 0, 'Under IRC Section 4943, a private foundation and all disqualified persons combined may not own more than 20% of the voting stock of a business enterprise. The founder (disqualified person) owns 15%, her son (also disqualified as a family member) owns 5%, and the foundation owns 12%, totaling 32%. Excess holdings are 12% (32% - 20%). Choice D is incorrect because family members of substantial contributors are disqualified persons whose holdings must be aggregated.', 'hard', 4),

-- Q24: hard / L4 — Expenditure responsibility mechanics under Section 4945
(3, 'Tax-Exempt Organizations', 'Brighton Arts Foundation, a private foundation, wants to make a $250,000 grant to a 501(c)(4) social welfare organization to fund community murals. The foundation signs a grant agreement requiring funds be used exclusively for the mural project, obtains annual reports from the grantee, and reports on Form 990-PF. Evaluate whether Brighton has properly avoided the taxable expenditure rules under Section 4945.', '["Yes, Brighton has properly exercised expenditure responsibility by establishing a written agreement, requiring reports, and reporting on Form 990-PF", "No, expenditure responsibility only applies to grants to foreign organizations, not domestic 501(c)(4) entities", "No, private foundations are prohibited from making any grants to non-501(c)(3) organizations regardless of oversight", "Yes, but only because the mural project is charitable in nature; expenditure responsibility is not required"]'::jsonb, 0, 'Under IRC Section 4945(h), a private foundation may grant to a non-501(c)(3) organization without triggering the taxable expenditure penalty by exercising expenditure responsibility. This requires a written agreement restricting use to charitable purposes, obtaining reports from the grantee, and reporting on Form 990-PF. Brighton fulfilled all requirements. Choice C is incorrect because Section 4945 does not prohibit grants to non-charities—it permits them when the foundation exercises proper expenditure responsibility.', 'hard', 4),

-- Q25: medium / L3 — Form 8868 automatic extension
(3, 'Tax-Exempt Organizations', 'Sunrise Animal Welfare, a 501(c)(3) with a calendar tax year, realizes on May 10 that it cannot complete its Form 990 by the May 15 deadline. The organization files Form 8868 requesting an extension. How much additional time does the extension provide?', '["A 3-month extension to August 15, requiring a showing of undue hardship", "A 6-month extension to November 15, but only if the organization pays estimated taxes", "A 90-day extension to August 13, available automatically without justification", "An automatic 6-month extension to November 15, without needing to show reasonable cause"]'::jsonb, 3, 'Under IRC Section 6081, Form 8868 provides an automatic 6-month extension for filing Form 990. For a calendar-year organization with an original due date of May 15, the extended deadline is November 15. No showing of reasonable cause or undue hardship is required—the extension is automatic upon timely filing. Choice A is incorrect because the extension is 6 months, not 3 months, and no demonstration of hardship is needed.', 'medium', 3),

-- Q26: easy / L1 — Private foundation presumption under Section 509
(3, 'Tax-Exempt Organizations', 'Under Section 509, what is the default classification for all 501(c)(3) organizations?', '["Public charity until the organization fails to file Form 990 for three consecutive years", "Private foundation, unless the organization demonstrates it qualifies as a public charity", "Supporting organization until it establishes independent operations", "Social welfare organization until it receives its determination letter"]'::jsonb, 1, 'Under IRC Section 509(a), all 501(c)(3) organizations are presumed to be private foundations unless they affirmatively demonstrate they qualify as public charities under one of the statutory exceptions (e.g., broad public support, church, school, hospital, or supporting organization status). Choice A is incorrect because the default classification is private foundation, not public charity—organizations must prove public charity status.', 'easy', 1),

-- Q27: easy / L1 — Convenience exclusion definition
(3, 'Tax-Exempt Organizations', 'Under UBIT rules, what is the convenience exclusion for tax-exempt organizations?', '["An exclusion for activities generating less than $1,000 in annual income", "An exclusion for activities performed entirely by unpaid volunteers", "An exclusion for activities conducted primarily for the convenience of members, students, patients, or employees", "An exclusion for activities conducted on the organization''s premises only"]'::jsonb, 2, 'Under IRC Section 513(a)(2), the convenience exclusion removes from UBIT any trade or business carried on primarily for the convenience of the organization''s members, students, patients, or employees. Common examples include a university bookstore or hospital cafeteria. Choice B describes the volunteer labor exclusion, which is a separate statutory exclusion under Section 513(a)(1).', 'easy', 1),

-- Q28: easy / L1 — Organization manager penalty cap under Section 4958
(3, 'Tax-Exempt Organizations', 'What is the maximum excise tax per transaction on an organization manager who knowingly participates in an excess benefit transaction under Section 4958?', '["$10,000", "$20,000", "$50,000", "$100,000"]'::jsonb, 1, 'Under IRC Section 4958(a)(2), an organization manager who knowingly participates in an excess benefit transaction is subject to a 10% excise tax on the excess benefit, capped at $20,000 per transaction. This cap limits personal liability for managers while still imposing meaningful accountability. Choice A is incorrect because the $10,000 figure does not correspond to any cap under the intermediate sanctions provisions of Section 4958.', 'easy', 1),

-- Q29: medium / L2 — Section 509(a)(2) gross receipts test
(3, 'Tax-Exempt Organizations', 'Prairie Wildlife Conservancy, a 501(c)(3), receives $200,000 from membership fees, $150,000 from admission fees to its nature exhibits, $100,000 from government grants, and $50,000 from investment income. Total support is $500,000. Under the gross receipts test of Section 509(a)(2), does Prairie qualify as a public charity?', '["Yes, because more than one-third of support comes from contributions, membership fees, and gross receipts from exempt-function activities", "No, because investment income disqualifies an organization from the gross receipts test", "Yes, but only if Prairie also passes the facts-and-circumstances test", "No, because admission fees are unrelated business income and must be excluded"]'::jsonb, 0, 'Under IRC Section 509(a)(2), an organization qualifies as a public charity if it normally receives more than one-third of support from contributions, membership fees, and gross receipts from activities related to its exempt function. Prairie''s qualifying support is $450,000 ($200,000 + $150,000 + $100,000), which is 90% of total support—well above one-third. Choice D is incorrect because admission fees to exhibits related to the conservation mission are exempt-function gross receipts, not unrelated business income.', 'medium', 2),

-- Q30: easy / L1 — Operational test for Section 501(c)(3)
(3, 'Tax-Exempt Organizations', 'What does the operational test require for Section 501(c)(3) tax-exempt status?', '["The organization must be incorporated in a state that recognizes tax-exempt entities", "The organization''s governing documents must limit its purposes to exempt activities", "The organization must be operated primarily for exempt purposes with no private inurement", "The organization must receive at least one-third of its support from the general public"]'::jsonb, 2, 'Under IRC Section 501(c)(3), the operational test requires that an organization be operated primarily for exempt purposes, meaning it engages primarily in activities that accomplish its charitable mission. The test also prohibits private inurement—no part of net earnings may benefit private shareholders or individuals. Choice B describes the organizational test, which focuses on governing documents, not actual operations.', 'easy', 1)
;

COMMIT;
