-- Migration: Question generation — REG batch 17 (30 questions)
-- Date: 2026-02-28
-- Topic: Tax-Exempt Organizations
-- Difficulty: 9E / 15M / 6H
-- Bloom's: L1:8 / L2:9 / L3:8 / L4:5

BEGIN;

INSERT INTO questions (section_id, topic, stem, choices, correct_index, explanation, difficulty, cognitive_level)
VALUES

-- Q1: medium / L3 — Section 501(h) expenditure test sliding scale
(3, 'Tax-Exempt Organizations', 'Cedar Valley Education Fund, a 501(c)(3) with $1,000,000 in exempt purpose expenditures, elects the Section 501(h) expenditure test for lobbying. During 2026, the organization spends $150,000 on lobbying activities. Under the 501(h) sliding scale, which analysis correctly determines compliance?', '["The organization is within the lobbying limit because $150,000 is below the $175,000 nontaxable amount calculated under the sliding scale", "The organization has exceeded the lobbying limit because any lobbying over $100,000 violates the 501(h) ceiling", "The organization loses its exempt status because lobbying exceeds 10% of exempt purpose expenditures", "The organization must pay a 25% excise tax because the 501(h) election limits lobbying to $100,000 regardless of expenditure level"]'::jsonb, 0, 'Under IRC Section 501(h), the nontaxable lobbying amount uses a sliding scale: 20% of the first $500,000 of exempt purpose expenditures plus 15% of the next $500,000, yielding a $175,000 ceiling. Since $150,000 falls below this limit, the organization is compliant. Option B incorrectly applies a flat $100,000 cap rather than the graduated formula that increases with exempt purpose expenditures.', 'medium', 3),

-- Q2: medium / L2 — Public charity one-third support test (Section 509(a)(1))
(3, 'Tax-Exempt Organizations', 'Meadowbrook Relief Services, a 501(c)(3), receives the following support over a five-year period: $200,000 from government grants, $150,000 from public contributions, and $250,000 from investment income. Under Section 509(a)(1), how is the organization classified?', '["Private foundation, because investment income exceeds public contributions", "Public charity, because government grants and public contributions exceed one-third of total support", "Private foundation, because it must receive at least 50% of support from public sources", "Public charity, because all 501(c)(3) organizations are automatically classified as public charities"]'::jsonb, 1, 'Under IRC Section 509(a)(1), an organization qualifies as a public charity if it normally receives at least one-third of total support from governmental units and the general public. Here, $350,000 in public and government support equals 58.3% of $600,000 total support, well above the one-third threshold. Option A incorrectly suggests investment income automatically triggers private foundation status rather than evaluating the proportional support test.', 'medium', 2),

-- Q3: medium / L2 — Controlled entity payments and UBIT (Section 512(b)(13))
(3, 'Tax-Exempt Organizations', 'Evergreen Literacy Foundation, a 501(c)(3), owns 85% of Greenleaf Publishing Corp. Greenleaf pays $120,000 in annual rent to the foundation for office space. The fair market value rent for comparable space is $80,000. How is the rent treated for UBIT purposes?', '["The entire $120,000 is excluded from UBIT as passive rental income from real property", "The entire $120,000 is subject to UBIT because the foundation controls the subsidiary", "Only the $40,000 excess over fair market value is subject to UBIT", "The rent is excluded from UBIT because the controlled entity exception applies only to personal property"]'::jsonb, 2, 'Under IRC Section 512(b)(13), rent received from a controlled subsidiary (80% or more ownership) is treated as UBIT to the extent it exceeds fair market value. Since the $120,000 rent exceeds the $80,000 FMV by $40,000, only the excess is subject to UBIT. Option A incorrectly treats all controlled-entity rent as passive income when the rental exclusion does not apply to above-FMV payments from controlled organizations.', 'medium', 2),

-- Q4: easy / L1 — Dissolution clause requirement
(3, 'Tax-Exempt Organizations', 'What does the dissolution clause require for Section 501(c)(3) organizations?', '["That the organization dissolve within 10 years of formation", "That all remaining funds be distributed to the organization''s founders", "That the IRS approve all dissolution proceedings before they occur", "That assets be distributed to another exempt organization or the government upon dissolution"]'::jsonb, 3, 'Under IRC Section 501(c)(3), the organizational test requires that governing documents include a dissolution clause providing that assets will be distributed to another tax-exempt organization or to the government upon dissolution. This ensures exempt assets remain dedicated to charitable purposes. Option B contradicts this requirement, as distributing assets to founders would constitute private inurement.', 'easy', 1),

-- Q5: easy / L1 — Form 990-N e-Postcard threshold
(3, 'Tax-Exempt Organizations', 'What is the gross receipts threshold for filing Form 990-N (e-Postcard)?', '["Gross receipts normally $50,000 or less", "Gross receipts normally $100,000 or less", "Gross receipts normally $200,000 or less", "Gross receipts normally $25,000 or less"]'::jsonb, 0, 'Under IRC Section 6033, tax-exempt organizations with gross receipts normally $50,000 or less may file Form 990-N, an electronic notice requiring only basic information such as name, address, EIN, and confirmation of continued eligibility. Option C reflects the threshold for Form 990-EZ (under $200,000 gross receipts and under $500,000 total assets), not the e-Postcard.', 'easy', 1),

-- Q6: easy / L1 — Exempt purposes under Section 501(c)(3)
(3, 'Tax-Exempt Organizations', 'Which purpose qualifies an organization for Section 501(c)(3) tax-exempt status?', '["Promoting commercial trade among member businesses", "Providing social recreation for members", "Advancing the political interests of a particular party", "Fostering national or international amateur sports competition"]'::jsonb, 3, 'IRC Section 501(c)(3) enumerates specific exempt purposes including religious, charitable, scientific, educational, literary, public safety testing, prevention of cruelty, and fostering national or international amateur sports competition. Option A describes a trade association under Section 501(c)(6), and Option C is directly prohibited since 501(c)(3) organizations face an absolute ban on political campaign activity.', 'easy', 1),

-- Q7: hard / L4 — Convenience exclusion analysis across multiple facilities
(3, 'Tax-Exempt Organizations', 'Memorial Regional Hospital, a 501(c)(3), operates three facilities: (1) a cafeteria serving patients, visitors, and staff at below-market prices; (2) a laundry service washing linens for patients and also accepting laundry from neighborhood residents for a fee; and (3) a parking garage open to the general public. Evaluate which facilities qualify for the convenience exclusion from UBIT.', '["All three facilities qualify because they are operated on hospital premises in connection with exempt activities", "Only the cafeteria qualifies because it primarily serves patients, visitors, and staff for their convenience", "The cafeteria and laundry both qualify because they serve hospital patients directly", "None qualify because the hospital charges fees for all three services"]'::jsonb, 1, 'Under IRC Section 513(a)(2), the convenience exclusion applies to activities conducted primarily for the convenience of members, students, patients, or employees. The cafeteria serving patients, visitors, and staff at below-market prices meets this test. The laundry''s neighborhood service and the public parking garage extend beyond hospital-related individuals. Option A incorrectly assumes on-premises location alone satisfies the exclusion rather than evaluating each activity''s primary beneficiaries.', 'hard', 4),

-- Q8: medium / L3 — Personal property rents exceeding 10% threshold
(3, 'Tax-Exempt Organizations', 'Bright Horizons Academy, a 501(c)(3) school, leases a building and furnished office equipment to a local business. The lease specifies $90,000 annual rent for the building and $15,000 for the equipment. How is the rental income treated for UBIT purposes?', '["The entire $105,000 is excluded from UBIT as rental income from real property", "The entire $105,000 is subject to UBIT because the lease includes personal property", "The $90,000 building rent is excluded, but the $15,000 equipment rent is subject to UBIT because personal property exceeds the 10% incidental threshold", "The $15,000 equipment rent is excluded because it is bundled with the real property lease"]'::jsonb, 2, 'Under IRC Section 512(b)(3), rents from real property are generally excluded from UBIT, but rents from personal property are included unless they represent an incidental amount (less than 10% of total rents). Here, equipment rent is $15,000 of $105,000 total (14.3%), exceeding the 10% threshold. Thus the $15,000 personal property portion is subject to UBIT. Option A incorrectly treats the entire lease as real property rent, ignoring the personal property component.', 'medium', 3),

-- Q9: medium / L3 — Research exclusion from UBIT
(3, 'Tax-Exempt Organizations', 'Central State University, a 501(c)(3), conducts three research activities during 2026: (1) a $200,000 government-funded study with publicly shared results, (2) a $150,000 proprietary pharmaceutical study with results available only to the sponsoring company, and (3) a $100,000 faculty-initiated study published in academic journals. Which activities qualify for the UBIT research exclusion?', '["Only the government-funded study qualifies because it is the sole publicly available research", "All three qualify because universities receive a blanket research exclusion regardless of availability", "Only the proprietary pharmaceutical study is excluded because it generates the most income", "The government-funded study and faculty-initiated study qualify, but the proprietary study with restricted results does not"]'::jsonb, 3, 'Under IRC Section 512(b)(7)-(9), research exclusions from UBIT cover research performed for the government, research by a college or university, and research whose results are freely available to the public. The government contract and published faculty research both qualify. The proprietary study with restricted results does not meet these exclusions. Option B incorrectly assumes a blanket university exemption when research with restricted availability may still be subject to UBIT.', 'medium', 3),

-- Q10: medium / L2 — Bingo game exclusion from UBIT
(3, 'Tax-Exempt Organizations', 'Hope Springs Community Center, a 501(c)(3), hosts weekly bingo nights in a jurisdiction where commercial bingo operations are prohibited by law. The bingo games generate $45,000 annually. How is the bingo income treated for UBIT purposes?', '["Excluded from UBIT because the bingo is legal and commercial bingo is not ordinarily carried on in the jurisdiction", "Subject to UBIT because bingo is a regularly carried-on trade or business unrelated to exempt purposes", "Excluded solely because the $45,000 is below the passive income threshold", "Subject to UBIT because gaming activities are never excluded from unrelated business income"]'::jsonb, 0, 'Under IRC Section 513(f), bingo games are excluded from UBIT if the games are conducted legally and commercial bingo is not ordinarily carried out in the jurisdiction. Both conditions are met here. Option B ignores the specific statutory bingo exclusion that Congress enacted separately from the general UBIT three-part test framework.', 'medium', 2),

-- Q11: easy / L1 — Form 990-PF requirement for all private foundations
(3, 'Tax-Exempt Organizations', 'Which organizations must file Form 990-PF regardless of their size?', '["All 501(c)(3) public charities", "All private foundations", "Only private foundations with gross receipts over $50,000", "Only private foundations with assets exceeding $500,000"]'::jsonb, 1, 'Under IRC Section 6033, all private foundations must file Form 990-PF regardless of their gross receipts or total assets. This differs from public charities, which file Form 990, 990-EZ, or 990-N based on size thresholds. Option C incorrectly applies a gross receipts threshold that does not exist for private foundation returns, as Congress requires full disclosure from all private foundations.', 'easy', 1),

-- Q12: medium / L2 — 200% additional tax for uncorrected excess benefit (Section 4958)
(3, 'Tax-Exempt Organizations', 'Riverside Youth Alliance, a 501(c)(3), pays its program director $400,000 when comparable compensation is $250,000. The IRS determines this is an excess benefit transaction under Section 4958. The program director does not return the excess within the taxable period. What is the total excise tax on the program director?', '["$37,500 (25% of the $150,000 excess benefit)", "$150,000 (100% of the excess benefit amount)", "$300,000 (200% of the excess benefit)", "$337,500 (25% initial tax plus 200% additional tax on the uncorrected $150,000 excess)"]'::jsonb, 3, 'Under IRC Section 4958, when an excess benefit transaction is not corrected within the taxable period, the disqualified person faces both the initial 25% tax ($37,500) and an additional 200% tax ($300,000) on the $150,000 excess benefit, totaling $337,500. Option A reflects only the initial tax and ignores the steep additional penalty that applies when the excess benefit is not returned to the organization.', 'medium', 2),

-- Q13: medium / L2 — Organization manager tax under Section 4958
(3, 'Tax-Exempt Organizations', 'Lake City Wellness Center, a 501(c)(3), enters into an excess benefit transaction totaling $200,000 in excess compensation to its executive director. The board chair knowingly approved the arrangement. What excise tax does the board chair face under Section 4958?', '["$50,000 (25% of the excess benefit)", "$10,000 (5% of the excess benefit, capped at $10,000)", "$20,000 (10% of the excess benefit, capped at $20,000 per transaction)", "$400,000 (200% of the excess benefit)"]'::jsonb, 2, 'Under IRC Section 4958(a)(2), an organization manager who knowingly participates in an excess benefit transaction faces a 10% tax on the excess benefit, capped at $20,000 per transaction. Here, 10% of $200,000 equals $20,000, which meets the statutory cap. Option A confuses the manager''s 10% tax with the 25% initial tax imposed on the disqualified person who received the excess benefit.', 'medium', 2),

-- Q14: easy / L1 — Churches, schools, hospitals automatic public charity classification
(3, 'Tax-Exempt Organizations', 'Which type of 501(c)(3) organization is automatically classified as a public charity regardless of its funding sources?', '["A private operating foundation", "A supporting organization under Section 509(a)(3)", "A church, school, or hospital", "Any organization with annual revenues exceeding $1,000,000"]'::jsonb, 2, 'Under IRC Section 509(a)(1) and Section 170(b)(1)(A), churches, schools, and hospitals are automatically classified as public charities regardless of their funding sources or the one-third support test. Option A describes a type of private foundation that, while subject to fewer restrictions, is not classified as a public charity. Revenue size alone does not determine public charity status.', 'easy', 1),

-- Q15: easy / L2 — Form 990 filing deadline
(3, 'Tax-Exempt Organizations', 'Mountain View Charitable Trust, a calendar-year 501(c)(3), needs to determine its annual Form 990 filing deadline. When is the return due?', '["March 15 of the following year", "April 15 of the following year", "June 15 of the following year", "May 15 of the following year"]'::jsonb, 3, 'Under IRC Section 6033, tax-exempt organizations must file their annual information return by the 15th day of the 5th month after the end of the tax year. For calendar-year organizations, this means May 15. A 6-month extension is available using Form 8868. Option B (April 15) is the individual income tax return deadline, not the deadline for exempt organization returns.', 'easy', 2),

-- Q16: hard / L4 — Section 4945 taxable expenditures analysis (private foundation)
(3, 'Tax-Exempt Organizations', 'Patterson Family Foundation, a private foundation, undertakes these 2026 activities: (1) spends $50,000 lobbying Congress on education policy, (2) awards $30,000 in scholarships through an IRS-approved program with objective criteria, (3) grants $100,000 to a 501(c)(4) social welfare organization without expenditure responsibility, and (4) donates $75,000 to a public charity. Evaluate which constitute taxable expenditures under Section 4945.', '["Activities (1) and (3) are taxable expenditures; (2) and (4) are not", "Only activity (1) is a taxable expenditure because lobbying is always prohibited for foundations", "Activities (1), (2), and (3) are taxable expenditures because only grants to public charities are permitted", "All four activities are taxable expenditures because private foundations cannot make direct grants"]'::jsonb, 0, 'Under IRC Section 4945, taxable expenditures include lobbying, political activity, grants to individuals without IRS-approved procedures, and grants to non-charities without expenditure responsibility. Activity (1) is taxable because private foundations may not lobby. Activity (3) is taxable because the grant to a 501(c)(4) lacked expenditure responsibility. Activity (2) uses an IRS-approved program, and activity (4) is a permissible grant to a public charity. Option B overlooks the expenditure responsibility requirement for non-charity grants.', 'hard', 4),

-- Q17: medium / L3 — NOL deduction for UBI purposes
(3, 'Tax-Exempt Organizations', 'Hilltop Services Foundation, a 501(c)(3), has the following unrelated business results: 2024 loss of $40,000, 2025 loss of $15,000, and 2026 income of $90,000 before the specific deduction. How should Hilltop compute its 2026 unrelated business taxable income?', '["The NOL deduction cannot be used because tax-exempt organizations may not carry forward losses", "$34,000 after deducting the $55,000 NOL carryforward and the $1,000 specific deduction", "$89,000 because only the $1,000 specific deduction is available against UBI", "$35,000 after deducting only the 2025 loss because 2024 losses have expired"]'::jsonb, 1, 'Under IRC Section 512(b)(6), unrelated business taxable income allows a net operating loss deduction computed using only UBI items. Both the 2024 ($40,000) and 2025 ($15,000) losses carry forward to offset 2026 income: $90,000 minus $55,000 NOL minus the $1,000 specific deduction equals $34,000. Option A incorrectly states that exempt organizations cannot carry forward UBI losses when the Code explicitly permits this deduction.', 'medium', 3),

-- Q18: hard / L4 — Expenditure responsibility requirements and consequences
(3, 'Tax-Exempt Organizations', 'Kendall Arts Foundation, a private foundation, plans a $200,000 grant to Arts Forward Inc., a 501(c)(4) social welfare organization, to fund community art programs. The foundation''s attorney advises expenditure responsibility is required. Evaluate what this requires and the consequences of failure.', '["The foundation must convert the grantee to a 501(c)(3) before distributing the grant; failure results in loss of exempt status", "The foundation must only verify the grantee''s tax-exempt status at the time of the grant; failure results in a $10,000 penalty", "The foundation must obtain prior IRS approval of the grant; failure results in revocation of the grantee''s exempt status", "The foundation must conduct a pre-grant inquiry, execute a written agreement restricting use to charitable purposes, require annual reports, and report to the IRS; failure makes the grant a taxable expenditure subject to 20% excise tax under Section 4945"]'::jsonb, 3, 'Under IRC Section 4945(h), expenditure responsibility requires a pre-grant inquiry into the grantee, a written agreement that charitable purposes will be served, annual reports from the grantee, and IRS reporting by the foundation. Failure to exercise expenditure responsibility on grants to non-501(c)(3) organizations makes the entire grant a taxable expenditure subject to a 20% initial excise tax. Option B minimizes the obligation to a simple status check, ignoring the ongoing oversight requirements Congress imposed.', 'hard', 4),

-- Q19: medium / L2 — Excess business holdings combined with disqualified persons
(3, 'Tax-Exempt Organizations', 'Sterling Heritage Foundation, a private foundation, owns 12% of the voting stock of Consolidated Industries Inc. The foundation''s substantial contributors and their family members collectively own 15% of the voting stock. Under Section 4943, what is the combined holding status?', '["Compliant, because the foundation''s own 12% holding is below the 20% threshold", "Compliant, because the 20% limit applies only to the foundation and not to disqualified persons", "In violation, because the combined 27% holding exceeds the permitted 20% threshold", "In violation, because private foundations cannot own any voting stock in for-profit corporations"]'::jsonb, 2, 'Under IRC Section 4943, the combined holdings of a private foundation and all disqualified persons in a business enterprise cannot exceed 20% of the voting stock. Here, the foundation''s 12% plus the disqualified persons'' 15% equals 27%, exceeding the 20% permitted holding by 7%. Option A incorrectly evaluates only the foundation''s direct holding rather than the combined total required by the statute.', 'medium', 2),

-- Q20: medium / L2 — Section 509(a)(2) gross receipts test for public charity
(3, 'Tax-Exempt Organizations', 'Harmony Performing Arts Center, a 501(c)(3), receives $180,000 from ticket sales, $120,000 from membership fees, $90,000 from public donations, and $60,000 from investment income over a representative period. Under Section 509(a)(2), how is the organization classified?', '["Private foundation, because ticket sales constitute commercial activity", "Public charity, because contributions, membership fees, and exempt-function receipts exceed one-third of total support and investment income does not exceed one-third", "Private foundation, because performing arts organizations cannot qualify under Section 509(a)(2)", "Public charity, because all organizations with membership fees are automatically public charities"]'::jsonb, 1, 'Under IRC Section 509(a)(2), an organization qualifies as a public charity if it normally receives more than one-third of support from contributions, membership fees, and gross receipts from exempt functions, and not more than one-third from investment income. Here, 86.7% comes from qualifying sources and only 13.3% from investments. Option A incorrectly treats exempt-function ticket sales as disqualifying commercial activity rather than qualifying support.', 'medium', 2),

-- Q21: easy / L1 — Private inurement prohibition
(3, 'Tax-Exempt Organizations', 'What does the private inurement prohibition require of Section 501(c)(3) organizations?', '["That no more than 25% of net earnings benefit insiders", "That the organization pay market-rate salaries to all employees", "That the organization have no paid employees", "That no part of net earnings inure to the benefit of any private shareholder or individual"]'::jsonb, 3, 'Under IRC Section 501(c)(3), the private inurement prohibition requires that no part of net earnings benefit any private shareholder or individual who has a personal or private interest in the organization. This is an absolute prohibition, not a percentage-based threshold. Option A incorrectly suggests a 25% tolerance when any level of inurement can jeopardize exempt status.', 'easy', 1),

-- Q22: hard / L4 — Private benefit vs private inurement distinction
(3, 'Tax-Exempt Organizations', 'Sunrise Learning Center, a 501(c)(3), enters two transactions in 2026. First, it pays its founder (also board president) a $500,000 consulting fee for services worth $100,000. Second, it pays an outside marketing firm with no connection to the organization $300,000 for services worth $150,000. Evaluate how these transactions differ under the private inurement and private benefit doctrines.', '["The founder''s fee violates the private inurement prohibition because the founder is an insider, while the marketing overpayment violates the broader private benefit doctrine applicable to non-insiders; both can jeopardize exempt status", "Both transactions violate the private inurement prohibition because any overpayment constitutes inurement", "Neither transaction threatens exempt status because the organization received services in exchange for payment", "Only the founder''s fee is problematic because the private benefit doctrine does not apply to arm''s-length transactions with outsiders"]'::jsonb, 0, 'Under IRC Section 501(c)(3), private inurement specifically prohibits net earnings benefiting insiders (private shareholders or individuals with a personal interest), making the founder''s excessive fee a clear inurement violation. The private benefit doctrine is broader, prohibiting excessive benefits to any person, including non-insiders. The marketing overpayment is not inurement but may still constitute impermissible private benefit. Option B incorrectly conflates the two doctrines when they have distinct scopes.', 'hard', 4),

-- Q23: easy / L1 — Form 8868 extension purpose
(3, 'Tax-Exempt Organizations', 'What is the purpose of IRS Form 8868 for tax-exempt organizations?', '["To apply for initial tax-exempt status", "To request an automatic extension of time to file Form 990", "To report changes in the organization''s governing documents", "To elect the Section 501(h) expenditure test for lobbying"]'::jsonb, 1, 'Form 8868 is used by tax-exempt organizations to request an automatic 6-month extension of time to file their annual information returns (Form 990, 990-EZ, 990-PF, or 990-T). Option A describes Form 1023 (or 1023-EZ), which is the application for Section 501(c)(3) recognition, not an extension request.', 'easy', 1),

-- Q24: medium / L3 — Penalties for late Form 990 filing
(3, 'Tax-Exempt Organizations', 'Golden State Arts Council, a 501(c)(3) with $800,000 in annual gross receipts, files its Form 990 sixty days late without reasonable cause. What is the penalty for the late filing?', '["$600 ($10 per day for 60 days)", "$6,000 ($100 per day for 60 days)", "$1,200 ($20 per day for 60 days, subject to a maximum of $10,500)", "$10,500 (the maximum flat penalty regardless of days late)"]'::jsonb, 2, 'Under IRC Section 6652(c)(1)(A), the penalty for failure to file Form 990 is $20 per day for each day the return is late, up to the lesser of $10,500 or 5% of gross receipts for organizations with gross receipts under $1,186,000. At 60 days late, the penalty is 60 x $20 = $1,200. Option B applies the $100-per-day rate reserved for larger organizations with gross receipts of $1,186,000 or more.', 'medium', 3),

-- Q25: medium / L3 — Supporting organization under Section 509(a)(3)
(3, 'Tax-Exempt Organizations', 'Alliance Education Support, Inc. is organized and operated exclusively to raise funds for City Community College, a public charity. Alliance has no independent programs and transfers all net revenue to the college. Under Section 509(a)(3), how is Alliance classified?', '["Public charity, because it is a supporting organization operated exclusively to support a public charity", "Private foundation, because it does not directly receive broad public support", "Private operating foundation, because it conducts fundraising activities", "Public charity only if it independently passes the one-third support test"]'::jsonb, 0, 'Under IRC Section 509(a)(3), an organization operated exclusively to support one or more public charities qualifies as a supporting organization and is classified as a public charity. Alliance meets this test by operating solely to raise funds for City Community College. Option B incorrectly assumes broad public support is required when the supporting organization classification provides an alternative path to public charity status.', 'medium', 3),

-- Q26: hard / L4 — Section 4940 net investment income tax calculation
(3, 'Tax-Exempt Organizations', 'Wellington Family Foundation, a private foundation, reports the following for 2026: $300,000 in dividend income, $150,000 in capital gains from securities sales, $50,000 in interest income, and $80,000 in investment management expenses directly connected to producing the investment income. Calculate the excise tax on net investment income under Section 4940.', '["$6,950 (1.39% of $500,000 gross investment income without deducting expenses)", "$4,865 (1.39% of dividends and interest only, excluding capital gains)", "$3,500 (applying a 1% rate to $350,000 after excluding capital gains)", "$5,838 (1.39% of $420,000 net investment income after deducting $80,000 in management expenses)"]'::jsonb, 3, 'Under IRC Section 4940, private foundations pay a 1.39% excise tax on net investment income, which includes dividends, interest, and capital gains, reduced by directly connected expenses. Net investment income is $500,000 minus $80,000, yielding $420,000. The tax is 1.39% x $420,000 = $5,838. Option A incorrectly omits the deduction for investment management expenses, which Section 4940(c) explicitly allows against gross investment income.', 'hard', 4),

-- Q27: easy / L1 — Operational test primary requirement
(3, 'Tax-Exempt Organizations', 'What is the primary requirement of the operational test for Section 501(c)(3) status?', '["That the organization generate no revenue from any source", "That the organization file annual returns with the IRS", "That the organization be operated primarily for one or more exempt purposes", "That the organization maintain a minimum balance of $100,000 in assets"]'::jsonb, 2, 'Under IRC Section 501(c)(3), the operational test requires that an organization be operated primarily for one or more exempt purposes, engaging in activities that accomplish those purposes. Option A is incorrect because exempt organizations may generate revenue; the key is whether operations serve exempt purposes. Revenue generation does not disqualify an organization.', 'easy', 1),

-- Q28: medium / L2 — Self-dealer 10% vs foundation manager 5% initial tax rates
(3, 'Tax-Exempt Organizations', 'A disqualified person sells real estate to the Davidson Family Foundation, a private foundation, for $400,000 at fair market value. The foundation''s investment manager, who serves on the board, approves the purchase knowing it involves a disqualified person. Under Section 4941, what are the initial excise taxes?', '["$40,000 on the self-dealer (10%) and $20,000 on the foundation manager (5%)", "$20,000 on the self-dealer (5%) and $40,000 on the foundation manager (10%)", "$40,000 on the self-dealer (10%) and no tax on the manager because the price was fair", "No tax on either party because the transaction was at fair market value"]'::jsonb, 0, 'Under IRC Section 4941, self-dealing is determined by the nature of the transaction, not the price. Any sale between a disqualified person and a private foundation triggers self-dealing taxes: 10% of the amount involved on the self-dealer ($40,000) and 5% on a foundation manager who knowingly participates ($20,000). Option D reflects the common misconception that fair market value pricing avoids self-dealing, when Section 4941 imposes strict liability regardless of price.', 'medium', 2),

-- Q29: hard / L3 — Section 4945 taxable expenditure 20% rate on foreign grants
(3, 'Tax-Exempt Organizations', 'Northfield Community Foundation, a private foundation, makes a $500,000 grant to a domestic 501(c)(3) public charity and a $100,000 grant to a foreign non-governmental organization not recognized as a 501(c)(3), without exercising expenditure responsibility. Under Section 4945, what is the excise tax consequence?', '["$120,000 (20% of both grants combined)", "$20,000 (20% of the $100,000 foreign grant that lacked expenditure responsibility)", "$10,000 (10% of the $100,000 foreign grant)", "$5,000 (5% of the $100,000 foreign grant, treated as a jeopardizing investment)"]'::jsonb, 1, 'Under IRC Section 4945, grants to organizations that are not 501(c)(3) public charities require expenditure responsibility. Without it, the grant is a taxable expenditure subject to a 20% initial excise tax. The $500,000 grant to a domestic public charity is not a taxable expenditure. Only the $100,000 foreign grant triggers the 20% tax ($20,000). Option C incorrectly applies the 10% self-dealing rate from Section 4941 rather than the 20% taxable expenditure rate under Section 4945.', 'hard', 3),

-- Q30: medium / L3 — Form 990-EZ filing thresholds
(3, 'Tax-Exempt Organizations', 'Pine Ridge Wildlife Rescue, a 501(c)(3) public charity, has gross receipts of $180,000 and total assets of $450,000 for the current tax year. Which annual information return must the organization file?', '["Form 990-N (e-Postcard) because gross receipts are under $200,000", "Form 990-EZ because gross receipts are under $200,000 and total assets are under $500,000", "Form 990 because total assets exceed $200,000", "Form 990-PF because the organization has significant assets"]'::jsonb, 1, 'Under IRC Section 6033, Form 990-EZ may be filed by organizations with gross receipts under $200,000 and total assets under $500,000. Pine Ridge meets both thresholds ($180,000 and $450,000). Option A is incorrect because Form 990-N is only available when gross receipts are $50,000 or less, far below Pine Ridge''s $180,000. Option D applies only to private foundations, not public charities.', 'medium', 3)
;

COMMIT;
