-- Migration: Question generation — AUD batch 75 (30 questions)
-- Date: 2026-02-28
-- Topic: Written Representations
-- Difficulty: 9E / 15M / 6H
-- Bloom's: L1:8 / L2:9 / L3:8 / L4:5

BEGIN;

INSERT INTO questions (section_id, topic, stem, choices, correct_index, explanation, difficulty, cognitive_level)
VALUES

-- Q1: hard / L4 — New management full-period representation responsibility
(1, 'Written Representations', 'During the audit of Lakewood Industries for the year ended December 31, 2025, the engagement partner at Barrett & Townsend CPA notes that the current CFO joined the company in August 2025 and has limited firsthand knowledge of transactions before that date. The CFO offers to sign the representation letter but wants to add a qualification excluding the first seven months. Under AU-C 580, what is the auditor''s best course of action?', '["Accept the letter without the qualification, because management''s representations must cover the entire period of the financial statements regardless of individual tenure", "Obtain a separate representation letter from the former CFO covering January through July 2025", "Accept the qualified letter and note the limitation in the auditor''s report as a scope restriction", "Decline the engagement because the current CFO cannot provide informed representations for the full audit period"]'::jsonb, 0, 'Under AU-C 580.09, written representations are required from management with appropriate responsibilities for the financial statements. Current management is responsible for the financial statements in their entirety, regardless of when individuals assumed their roles. The CFO cannot exclude a portion of the audit period because the representations relate to the financial statements as a whole. While option B (former CFO letter) might seem reasonable, AU-C 580 requires representations from current management, not former officers who no longer bear responsibility.', 'hard', 4),

-- Q2: medium / L3 — Representation about accounting estimates omission
(1, 'Written Representations', 'While completing the audit of Monarch Properties LLC for the year ended December 31, 2025, the engagement team at Feldman & Associates reviews the management representation letter. The letter includes standard representations but omits any mention of the reasonableness of significant assumptions used in estimating the allowance for doubtful accounts. Under AU-C 580, the most likely impact of this omission is that the auditor should:', '["Take no action, because the reasonableness of estimates is verified through substantive procedures rather than representations", "Consider the omission immaterial since the representation letter covers completeness of information generally", "Request that management add a representation about the reasonableness of significant assumptions and methods used in accounting estimates", "Issue a qualified opinion due to the missing representation"]'::jsonb, 2, 'Under AU-C 580.11, the auditor should request written representations about significant assumptions used in making accounting estimates that management considers reasonable. Omitting this representation means the auditor lacks necessary evidence about management''s assessment of its own estimates. The auditor should request the addition before issuing the report. While option A suggests substantive procedures alone suffice, AU-C 580 requires written representations as complementary evidence even when other testing has been performed.', 'medium', 3),

-- Q3: hard / L3 — Component management representations in group audits
(1, 'Written Representations', 'Westbrook Partners LLP is the group auditor for Cascade Holdings'' consolidated December 31, 2025 financial statements. Cascade has three subsidiaries, each audited by separate component auditors. The group engagement partner is determining what written representations are needed from subsidiary management. Under AU-C 600 and AU-C 580, the group auditor should obtain:', '["Written representations from group management only, covering all components in the consolidated financial statements", "Written representations from both group management and, when appropriate, component management regarding matters relevant to the group financial statements", "No separate representations from component management, because the component auditors'' reports serve as sufficient evidence", "Written representations from component management only, because subsidiary managers have the most direct knowledge of their operations"]'::jsonb, 1, 'Under AU-C 600.40 and AU-C 580, the group auditor obtains written representations from group management about the consolidated financial statements. Additionally, the group auditor may request representations from component management when matters relevant to the group audit require them. Both levels of management may need to provide representations. While option A (group management only) seems logical, AU-C 600 recognizes that component management may have unique knowledge of matters affecting the group financial statements.', 'hard', 3),

-- Q4: easy / L1 — Addressee of the representation letter
(1, 'Written Representations', 'To whom should the management representation letter be addressed under AU-C 580?', '["The entity''s board of directors or audit committee", "The engagement quality reviewer", "The SEC or applicable regulatory body", "The auditor performing the engagement"]'::jsonb, 3, 'Under AU-C 580.10, the management representation letter is addressed to the auditor. The letter is a direct communication from management to the auditor confirming certain matters and supporting other audit evidence obtained during the engagement. While option A (board of directors) might seem relevant because the board oversees the financial reporting process, the representation letter is specifically directed to the auditor as the intended user.', 'easy', 1),

-- Q5: medium / L2 — Comparative financial statements multi-period
(1, 'Written Representations', 'Barrett & Nash CPA is auditing Greenfield Corp.''s December 31, 2025 financial statements, which include comparative 2024 figures. The firm also audited the 2024 financial statements. The engagement partner prepares the management representation letter for the current engagement. Under AU-C 580, the representation letter should address:', '["Only the current year ending December 31, 2025, because the prior year was covered by the previous engagement''s representation letter", "Only matters that have changed since the prior year''s representation letter was issued", "The current year plus a separate addendum for the prior year''s representations", "All periods covered by the auditor''s current report, including the comparative 2024 financial statements"]'::jsonb, 3, 'Under AU-C 580.14, when comparative financial statements are presented and the auditor reports on all periods, the management representation letter should cover all periods referred to in the auditor''s report. A single letter covering both 2025 and 2024 is appropriate because the auditor is currently reporting on both years. While option A suggests the prior year letter sufficed, the current engagement requires fresh representations for all reported periods.', 'medium', 2),

-- Q6: easy / L1 — Written representations as necessary but not sufficient evidence
(1, 'Written Representations', 'In the context of an audit, written representations from management are best described as:', '["A substitute for other forms of audit evidence when direct testing is impractical", "Necessary audit evidence that complements but does not replace other audit procedures", "Optional communications that strengthen the auditor''s documentation file", "The most reliable form of audit evidence available to the auditor"]'::jsonb, 1, 'Under AU-C 580.04, written representations are necessary information that the auditor requires in connection with the audit. They complement other audit procedures but cannot replace evidence the auditor would otherwise obtain. While option D suggests representations are highly reliable, they are actually among the least reliable forms of evidence because they are internally generated and not independently verified.', 'easy', 1),

-- Q7: hard / L4 — Management offers only verbal representations
(1, 'Written Representations', 'During the audit of Summit Ridge Healthcare for the year ended December 31, 2025, the CEO tells the engagement partner at Crawford & Wells CPA that he will verbally confirm all required representations but refuses to put them in writing due to legal counsel''s advice. The CEO states that his verbal assurances should carry the same weight. Under AU-C 580, what should the auditor do?', '["Accept the verbal representations because the substance of the communication matters more than the form", "Document the verbal representations in the working papers and treat them as equivalent to written representations", "Treat the refusal to provide written representations as a scope limitation and consider the impact on the auditor''s opinion", "Issue a qualified opinion citing management''s preference for verbal over written communication"]'::jsonb, 2, 'Under AU-C 580.19-.20, if management does not provide the requested written representations, the auditor must treat this as a scope limitation. Verbal representations cannot substitute for the required written letter. The auditor should discuss the matter with management and evaluate the effect on the opinion, which may result in a disclaimer. While option D (qualified opinion) acknowledges an issue, AU-C 580 states that refusal to provide written representations ordinarily results in a disclaimer, not merely a qualification.', 'hard', 4),

-- Q8: medium / L2 — Representation about completeness of pending litigation
(1, 'Written Representations', 'During the audit of Canterbury Industries for the year ended December 31, 2025, the engagement team at Prescott & Lane CPA obtains the management representation letter. A new lawsuit is filed against Canterbury on January 15, 2026, before the auditor''s report date of February 20, 2026. The representation letter, dated February 20, should:', '["Include the January 15 lawsuit because the letter must cover events through the date of the auditor''s report", "Exclude the January lawsuit because it was filed after year-end and is not a balance sheet date condition", "Reference the lawsuit only if it exceeds the materiality threshold established during planning", "Note the lawsuit in a separate subsequent events letter rather than the representation letter"]'::jsonb, 0, 'Under AU-C 580.10, the representation letter is dated as of the date of the auditor''s report, meaning it covers events up to that date. Because the lawsuit was filed on January 15 and the report is dated February 20, management must include this disclosure in the representation letter. While option B attempts to apply subsequent event classification rules, the representation about completeness of litigation disclosures spans through the report date, not just the balance sheet date.', 'medium', 2),

-- Q9: medium / L2 — Additional representations beyond AU-C 580 requirements
(1, 'Written Representations', 'The engagement partner at Morrison & Clarke CPA is completing the audit of Stratford Engineering for the year ended December 31, 2025. During the audit, the team identified unusual revenue recognition practices involving bill-and-hold transactions. The partner considers requesting an additional representation from management beyond the standard AU-C 580 requirements. Under auditing standards, the auditor:', '["May only request representations explicitly listed in AU-C 580 and cannot customize the letter", "Must obtain prior approval from the firm''s quality control partner before adding non-standard representations", "Should add supplemental representations only if the engagement involves a public company", "May request additional written representations about matters specific to the entity''s business or industry"]'::jsonb, 3, 'Under AU-C 580.13, the auditor may determine that additional representations beyond those required by AU-C 580 are needed based on the circumstances of the engagement. The auditor has discretion to request representations about specific matters such as unusual revenue arrangements. While option A implies a closed list, AU-C 580 establishes minimum requirements and explicitly contemplates additional representations as the auditor deems necessary.', 'medium', 2),

-- Q10: easy / L1 — Form of written representations
(1, 'Written Representations', 'Under AU-C 580, written representations from management should be provided in the form of:', '["A representation letter addressed to the auditor", "A sworn affidavit filed with the SEC", "An oral statement documented in the auditor''s workpapers", "A formal resolution adopted by the board of directors"]'::jsonb, 0, 'Under AU-C 580.15, written representations are provided in the form of a representation letter addressed to the auditor. The letter is a written communication directly from management confirming certain matters. While option D (board resolution) is a formal document, AU-C 580 specifically requires a letter format addressed to the auditor rather than internal corporate governance documents.', 'easy', 1),

-- Q11: hard / L4 — Contradictions between representations and other evidence
(1, 'Written Representations', 'While auditing Pinnacle Distributors for the year ended December 31, 2025, the audit team at Henderson & Cole CPA obtains a management representation letter stating that all related-party transactions have been disclosed. However, during substantive testing, the team discovers a $340,000 loan to the CEO''s spouse that was not disclosed anywhere in the financial statements or representation letter. Management claims it was an inadvertent omission. Under AU-C 580, what should the auditor do?', '["Accept the explanation and have management amend the representation letter to include the loan", "Reevaluate the reliability of management''s representations and consider the effect on other representations provided", "Withdraw from the engagement immediately because management has demonstrated dishonesty", "Issue an adverse opinion based solely on the undisclosed related-party transaction"]'::jsonb, 1, 'Under AU-C 580.17-.18, when written representations are inconsistent with other audit evidence, the auditor should perform audit procedures to resolve the matter and reevaluate the reliability of management''s representations as a whole. A single contradicted representation calls into question the integrity of all representations. While option A (amend the letter) addresses the immediate omission, it fails to address the broader concern about whether other representations are also unreliable.', 'hard', 4),

-- Q12: medium / L2 — Representation about compliance with contractual covenants
(1, 'Written Representations', 'Ridgecrest Manufacturing has a revolving credit facility with First National Bank containing financial covenants requiring a minimum current ratio of 1.5:1 and a maximum debt-to-equity ratio of 2:1. The engagement team at Ashford & Partners CPA includes a representation about compliance with all material contractual agreements. Under AU-C 580, this representation is:', '["Unnecessary because the auditor can verify covenant compliance through independent recalculation", "Required only when the entity has publicly traded debt instruments", "Prohibited because it shifts the auditor''s testing responsibility to management", "Appropriate because the auditor may request representations about matters specific to the entity''s circumstances"]'::jsonb, 3, 'Under AU-C 580.13, the auditor may request additional written representations beyond minimum requirements when circumstances warrant. A representation about compliance with debt covenants is appropriate because management has direct knowledge of contractual terms and obligations. While option A suggests independent verification suffices, the representation supplements audit procedures by confirming management''s own assessment of compliance status.', 'medium', 2),

-- Q13: medium / L2 — Representation about accounting policies
(1, 'Written Representations', 'The engagement team at Whitfield & Grant CPA is drafting the management representation letter for the audit of Oakmont Enterprises for the year ended December 31, 2025. The team includes a representation that management believes the significant accounting policies selected and applied are appropriate. Under AU-C 580, this representation about accounting policies is:', '["Optional and only needed when the entity has changed accounting methods during the year", "Not required because the appropriateness of accounting policies is the auditor''s professional judgment", "Required only for first-year audit engagements when the auditor is unfamiliar with the entity", "A required element of the management representation letter for every audit engagement"]'::jsonb, 3, 'Under AU-C 580.11, the auditor should obtain written representations that management believes the significant accounting policies are appropriate and properly applied in the financial statements. This is a required element in every audit, not just when changes occur. While option B correctly notes that the auditor exercises judgment about accounting policies, the representation confirms management''s own acknowledgment that the policies are appropriate.', 'medium', 2),

-- Q14: medium / L3 — Impact of limiting representation about uncorrected misstatements
(1, 'Written Representations', 'During the audit of Birchwood Financial Group for the year ended December 31, 2025, the engagement team at Calloway & Reed CPA presents management with a summary of $38,000 in uncorrected misstatements, below the $45,000 materiality threshold. Management signs the representation letter but crosses out the representation stating that the effects of uncorrected misstatements are immaterial. The CFO says she disagrees that the misstatements are immaterial. The most likely effect on the audit is:', '["No effect, because the uncorrected misstatements are below materiality and management''s agreement is unnecessary", "The auditor should discuss the basis for management''s disagreement and, if management still refuses, evaluate this as a scope limitation", "The auditor must adjust the financial statements to correct all misstatements regardless of materiality", "The auditor should issue an adverse opinion because management has challenged the auditor''s materiality determination"]'::jsonb, 1, 'Under AU-C 580.19, if management does not provide a requested written representation, the auditor treats it as a scope limitation. Even when uncorrected misstatements are below materiality, management must acknowledge them in the representation letter. The auditor should discuss the rationale for management''s refusal and evaluate the impact on the audit opinion. While option A suggests the refusal is inconsequential, AU-C 580 requires this specific representation regardless of the dollar amount relative to materiality.', 'medium', 3),

-- Q15: easy / L1 — Representation about plans and intentions
(1, 'Written Representations', 'Which of the following is a written representation that management may provide regarding plans and intentions under AU-C 580?', '["Management''s plans and intentions may affect the carrying value or classification of certain assets and liabilities", "Management guarantees that all projected revenues will be realized as forecasted", "Management certifies that no accounting estimates were used in the financial statements", "Management warrants that internal controls prevented all material misstatements"]'::jsonb, 0, 'Under AU-C 580.11, the auditor may request representations about management''s plans and intentions that may affect the carrying value or classification of assets and liabilities, such as plans to discontinue a product line or dispose of assets. While option B references projections, management representations address plans and intentions rather than guarantees about future outcomes.', 'easy', 1),

-- Q16: hard / L4 — Non-receipt of representation letter before report release
(1, 'Written Representations', 'The audit of Ridgemont Aerospace for the year ended December 31, 2025 is complete, and the engagement partner at Sinclair & Whitmore CPA plans to date the auditor''s report on March 10, 2026. As of March 10, management has not returned the signed representation letter despite multiple requests. Management indicates the CEO is traveling internationally and will sign upon return on March 18. Under AU-C 580, the auditor should:', '["Date the report March 10 and release it with a note that the representation letter is pending", "Accept a verbal confirmation from the CEO by phone and proceed with the March 10 report date", "Not date or release the auditor''s report until the signed representation letter is received", "Issue the report with a qualified opinion citing the delayed representation letter"]'::jsonb, 2, 'Under AU-C 580.10 and .20, the management representation letter must be dated as of the date of the auditor''s report. If the auditor has not received the signed letter, the report cannot be dated or released. The written representation letter is a prerequisite for issuing the opinion. While option B (verbal confirmation) might seem practical, AU-C 580 requires written representations, and oral assurances cannot substitute for the signed letter.', 'hard', 4),

-- Q17: easy / L1 — What the completeness representation covers
(1, 'Written Representations', 'The "completeness" representation in the management representation letter means that management has:', '["Provided the auditor with access to all relevant information, records, and personnel as agreed upon in the terms of the engagement", "Completed all year-end closing entries before the audit fieldwork began", "Filed all required regulatory reports with the applicable government agencies", "Fully implemented all internal control recommendations from the prior year audit"]'::jsonb, 0, 'Under AU-C 580.11, the completeness representation confirms that management has provided the auditor with all information relevant to the audit, including access to records and personnel. This ensures the auditor has received everything needed to form an opinion. While option C (regulatory filings) relates to compliance, it is not what the completeness representation in the management letter addresses under AU-C 580.', 'easy', 1),

-- Q18: easy / L1 — Representation about management responsibility for internal control
(1, 'Written Representations', 'In the management representation letter, the representation about internal control typically states that management acknowledges:', '["Its responsibility for designing, implementing, and maintaining internal control relevant to the preparation of financial statements free from material misstatement", "That the entity''s internal controls detected all fraud that occurred during the audit period", "That the auditor is primarily responsible for evaluating and testing internal controls", "That all control deficiencies identified during the audit have been fully remediated"]'::jsonb, 0, 'Under AU-C 580.11 and AU-C 210, management acknowledges its responsibility for designing, implementing, and maintaining internal controls relevant to fair presentation of financial statements. This representation reinforces the allocation of responsibilities between management and the auditor. While option C might reflect a common misconception, auditing standards clearly place responsibility for internal control with management, not the auditor.', 'easy', 1),

-- Q19: medium / L3 — Management denies fraud knowledge despite auditor suspicion
(1, 'Written Representations', 'During the audit of Harvest Point Enterprises for the year ended December 31, 2025, the engagement team at Donovan & Pearce CPA identifies unusual journal entries totaling $215,000 posted by the controller after normal business hours. The management representation letter states that management has no knowledge of fraud or suspected fraud affecting the entity. The auditor should analyze this situation by:', '["Accepting the representation because management is in the best position to know about fraud within the entity", "Considering whether the representation is reliable given the contradictory audit evidence and performing additional procedures to resolve the inconsistency", "Treating the representation as eliminating the auditor''s responsibility to further investigate the unusual journal entries", "Immediately withdrawing from the engagement because management has provided a false representation"]'::jsonb, 1, 'Under AU-C 580.17, when the auditor identifies audit evidence that is inconsistent with written representations, the auditor should perform procedures to resolve the inconsistency. The unusual journal entries create doubt about the reliability of management''s fraud representation. The auditor must investigate further rather than accept the representation at face value. While option D (withdrawal) could eventually be appropriate, AU-C 580 first requires the auditor to attempt resolution before considering such a drastic step.', 'medium', 3),

-- Q20: easy / L2 — Updated representation letter when report is reissued
(1, 'Written Representations', 'Mercer & Holt CPA originally issued the auditor''s report for Brightwater Holdings on March 5, 2026, for the year ended December 31, 2025. On April 10, 2026, the firm is asked to reissue the report for inclusion in a regulatory filing. Under AU-C 580, the auditor should:', '["Use the original representation letter dated March 5 because the audit was already completed", "Request only a verbal update from management confirming no changes since March 5", "Obtain an updated representation letter covering the period from the original report date through the reissuance date", "Decline to reissue the report because the original representation letter has expired"]'::jsonb, 2, 'Under AU-C 580.A27, when the auditor reissues the report, the auditor should obtain an updated representation letter covering the period since the original report date. This ensures management confirms that nothing has occurred since the original report date that would require adjustment or disclosure. While option A suggests the original letter suffices, a gap in representation coverage would leave the auditor without evidence about events after the original report date.', 'easy', 2),

-- Q21: medium / L2 — Representation about title to assets
(1, 'Written Representations', 'The engagement team at Thornton & Associates CPA is preparing the management representation letter for the audit of Meridian Supply Chain Corp. for the year ended December 31, 2025. The company holds $4.2 million in inventory across three warehouses, including $1.1 million stored at a third-party logistics facility. The representation about ownership of assets should:', '["Be omitted because the auditor independently confirms asset ownership through physical inspection and confirmations", "Cover only assets exceeding the materiality threshold", "Confirm that the entity has satisfactory title to all assets and that there are no liens or encumbrances not disclosed in the financial statements", "Be limited to assets physically located on the entity''s premises"]'::jsonb, 2, 'Under AU-C 580.11, the auditor requests a representation that the entity has satisfactory title to assets and that any liens, pledges, or encumbrances have been properly disclosed. This applies to all recognized assets regardless of location. While option A suggests independent verification is sufficient, the representation supplements other procedures by obtaining management''s direct confirmation of ownership and disclosure of any restrictions on assets.', 'medium', 2),

-- Q22: medium / L3 — Evidentiary weight of written vs oral representations
(1, 'Written Representations', 'During the audit of Falcon Ridge Technologies for the year ended December 31, 2025, the engagement team at Kinsley & Porter CPA obtains both written management representations and extensive oral explanations from the CFO during fieldwork. A staff auditor asks the engagement partner how the two types of management communications compare as audit evidence. The partner''s analysis should be that:', '["Written and oral representations carry equal evidentiary weight because both originate from management", "Oral representations are more reliable because they are spontaneous and less likely to be scripted", "Written representations are only necessary when the auditor doubts the truthfulness of oral statements", "Written representations provide stronger evidence than oral representations because they are more formal, documented, and make management more deliberate in their assertions"]'::jsonb, 3, 'Under AU-C 580.04, written representations are required because they provide more reliable evidence than oral representations. The written form creates a formal record, reduces misunderstandings, and makes management more accountable for their assertions. While option A suggests equal weight, auditing standards recognize that written communications are inherently more reliable than oral ones because they cannot be easily disputed or denied after the fact.', 'medium', 3),

-- Q23: medium / L3 — Off-balance-sheet arrangement representation omission
(1, 'Written Representations', 'During the audit of Pacific Rim Investments LLC for the year ended December 31, 2025, the engagement partner at Drayton & Steele CPA reviews the management representation letter and notices it contains no mention of guarantees, commitments, or other off-balance-sheet arrangements. The entity has a history of entering into variable interest entity arrangements. The auditor should analyze this omission as:', '["Acceptable because off-balance-sheet items are addressed through substantive testing rather than representations", "A potential concern requiring the auditor to request that management specifically represent the completeness of disclosures about off-balance-sheet arrangements and commitments", "Irrelevant because off-balance-sheet items are not within the scope of AU-C 580", "A matter for the audit committee to resolve rather than the auditor"]'::jsonb, 1, 'Under AU-C 580.11 and .13, the auditor should request representations about completeness of disclosures, which includes off-balance-sheet arrangements, guarantees, and commitments. Given the entity''s history of variable interest entity arrangements, the omission warrants attention. The auditor should request that management add specific representations. While option A suggests testing alone suffices, the representation letter must address completeness of all financial statement disclosures.', 'medium', 3),

-- Q24: hard / L4 — Whether representations reduce substantive testing
(1, 'Written Representations', 'The engagement partner at Calloway & Nash CPA is planning the audit of Sterling Medical Devices for the year ended December 31, 2025. A new staff auditor suggests that if management provides extensive additional representations about inventory valuation and obsolescence beyond AU-C 580 requirements, the audit team could reduce the extent of physical observation and price testing. The partner should evaluate this suggestion as:', '["Appropriate because additional representations from management demonstrate cooperation and reduce audit risk", "Acceptable if the additional representations are corroborated by management''s internal documentation", "Inappropriate because written representations cannot substitute for substantive audit procedures that the auditor would otherwise perform", "Permitted under AU-C 580 as long as the engagement quality reviewer approves the reduced testing"]'::jsonb, 2, 'Under AU-C 580.04, written representations complement but do not replace audit procedures the auditor considers necessary. Even extensive additional representations cannot reduce substantive testing requirements because management representations are among the least reliable forms of audit evidence. The auditor must obtain sufficient appropriate evidence through independent procedures. While option A suggests cooperation reduces risk, the source of evidence (management) does not change its low reliability ranking.', 'hard', 4),

-- Q25: medium / L3 — Assumptions in fair value estimates representation
(1, 'Written Representations', 'During the audit of Ironwood Capital Partners for the year ended December 31, 2025, the engagement team at Prescott & Wynn CPA reviews management''s fair value measurements for a portfolio of Level 3 investments totaling $8.7 million. The team requests that the representation letter include a statement about the reasonableness of significant assumptions underlying these valuations. The purpose of this additional representation is to:', '["Transfer responsibility for the fair value measurements from the auditor to management", "Confirm that management has considered the appropriateness of methods, data, and assumptions used in measuring fair values", "Eliminate the need for the auditor to engage a valuation specialist", "Serve as the primary audit evidence for the Level 3 fair value measurements"]'::jsonb, 1, 'Under AU-C 580.11, representations about accounting estimates confirm that management considers the methods, data, and assumptions used to be reasonable and appropriate. For Level 3 fair values, this representation supplements other procedures by documenting management''s own assessment. While option D suggests the representation is primary evidence, written representations are complementary evidence and cannot serve as the sole basis for the auditor''s conclusions about complex estimates.', 'medium', 3),

-- Q26: easy / L1 — Required vs additional representations
(1, 'Written Representations', 'Under AU-C 580, which best describes the distinction between required and additional written representations?', '["Required representations are included in every letter; additional representations are prohibited by auditing standards", "Required representations apply to public companies; additional representations apply to private companies", "Required representations are mandated by AU-C 580 for every audit; additional representations are requested at the auditor''s discretion based on engagement circumstances", "Required representations are signed by the CEO; additional representations are signed by lower-level management"]'::jsonb, 2, 'Under AU-C 580.11 and .13, certain representations are required for every audit engagement, such as management''s responsibility for the financial statements and completeness of information. Additional representations are requested at the auditor''s discretion based on specific engagement circumstances or industry considerations. While option A suggests additional representations are prohibited, AU-C 580 explicitly provides for auditor-requested supplemental representations.', 'easy', 1),

-- Q27: easy / L1 — Representation about side agreements
(1, 'Written Representations', 'The management representation letter may include a statement about side agreements. In this context, "side agreements" refers to:', '["Supplemental engagement letters between the audit firm and management", "Undisclosed arrangements or understandings that could affect the financial statements but are not reflected in the formal records", "Agreements between the entity and its external legal counsel regarding litigation strategy", "Informal arrangements between audit team members about the division of fieldwork"]'::jsonb, 1, 'Under AU-C 580, the auditor may request representations about the absence of side agreements or undisclosed arrangements that could affect the financial statements. Side agreements are informal or unrecorded understandings between parties that may alter the terms of formal contracts or create undisclosed obligations. While option A refers to engagement letters, side agreements in the representation letter context concern arrangements that could affect the entity''s financial reporting.', 'easy', 1),

-- Q28: medium / L2 — Representation about subsequent events in the rep letter
(1, 'Written Representations', 'The engagement team at Whitmore & Associates CPA is preparing the management representation letter for the audit of Sterling Analytics Corp. for the year ended December 31, 2025. The report will be dated March 12, 2026. On February 28, 2026, a fire damaged Sterling''s regional office causing an estimated $1.8 million in losses. The representation letter, dated March 12, 2026, should include management''s representation that:', '["All events occurring between December 31, 2025 and March 12, 2026 that require adjustment or disclosure have been properly addressed in the financial statements", "Only events that existed at December 31, 2025 have been reflected in the financial statements", "The fire loss has been excluded from the representation letter because it is a Type II subsequent event requiring disclosure only", "Subsequent events are covered by the auditor''s own procedures and do not require management representations"]'::jsonb, 0, 'Under AU-C 580.11, the management representation letter includes a representation about subsequent events occurring between the balance sheet date and the report date requiring adjustment or disclosure. Management must acknowledge all such events, including the February fire, and confirm proper treatment. While option C correctly classifies the fire as a Type II event, management must still represent in the letter that the event''s disclosure is adequate.', 'medium', 2),

-- Q29: medium / L3 — "To the best of my knowledge and belief" qualifier
(1, 'Written Representations', 'During the audit of Northgate Distribution Center for the year ended December 31, 2025, the CFO signs the management representation letter but inserts the phrase "to the best of my knowledge and belief" before several key representations, including the completeness and fraud representations. The engagement partner at Walton & Hayes CPA should analyze this language as:', '["Unacceptable because all representations must be absolute statements without qualifiers", "An indication that the CFO is attempting to limit personal liability, requiring the auditor to withdraw from the engagement", "Generally acceptable for representations involving matters where management is expected to have knowledge and belief rather than certainty", "A required modification that must appear in every management representation letter"]'::jsonb, 2, 'Under AU-C 580.A15, the phrase "to the best of my knowledge and belief" is acceptable for representations involving matters where management is expected to have knowledge and belief rather than certainty, such as fraud awareness and completeness of information. This qualifier is standard language. While option A suggests all representations must be absolute, AU-C 580 recognizes that some matters inherently involve management''s state of knowledge rather than verifiable certainty.', 'medium', 3),

-- Q30: medium / L2 — Representation about completeness of board minutes
(1, 'Written Representations', 'The engagement team at Preston & Mitchell CPA is drafting the management representation letter for Silverleaf Holdings for the year ended December 31, 2025. The partner includes a representation requesting management to confirm that all minutes of meetings of stockholders, directors, and committees have been made available to the auditor. Under AU-C 580, this representation:', '["Supports the auditor''s ability to identify matters discussed by the board that may affect the financial statements, such as dividend declarations and major transaction authorizations", "Is unnecessary because the auditor independently inspects the minute books as a standard audit procedure", "Is required only when the entity has a formal audit committee", "Should be excluded from the representation letter because minute access is governed by the engagement letter"]'::jsonb, 0, 'Under AU-C 580.11, the completeness representation encompasses management providing all relevant records and information, including minutes of meetings. A specific representation about meeting minutes confirms that the auditor has access to board decisions that may affect financial reporting. While option B suggests independent inspection suffices, the representation ensures management affirmatively confirms that no meeting records have been withheld from the auditor.', 'medium', 2)
;

COMMIT;
