-- Migration: Question generation — REG batch 30 (30 questions)
-- Date: 2026-02-28
-- Topic: Tax-Exempt Organizations
-- Difficulty: 9E / 15M / 6H
-- Bloom's: L1:8 / L2:9 / L3:8 / L4:5

BEGIN;

INSERT INTO questions (section_id, topic, stem, choices, correct_index, explanation, difficulty, cognitive_level)
VALUES

-- Q1: hard / L3 — 501(h) election vs substantial part test for lobbying
(3, 'Tax-Exempt Organizations', 'Heritage Literacy Alliance, a 501(c)(3) public charity, spends 18% of its total expenditures on lobbying activities. The organization has not made a Section 501(h) election. Under the "substantial part" test, how should this level of lobbying activity be evaluated?', '["The lobbying is clearly insubstantial because it is below 20%", "The lobbying is permissible because 501(c)(3) organizations face no restrictions on lobbying activity", "The IRS may consider 18% substantial, potentially jeopardizing exempt status, because the substantial part test has no fixed percentage thresholds", "The organization must retroactively elect 501(h) to avoid automatic revocation of exempt status"]'::jsonb, 2, 'Under IRC Section 501(c)(3), a tax-exempt organization may not devote a "substantial part" of its activities to lobbying. Without the Section 501(h) election, the substantial part test applies, which uses a facts-and-circumstances analysis with no fixed percentage safe harbor. At 18%, the IRS could determine lobbying is substantial, risking exempt status. Choice A is incorrect because there is no bright-line 20% threshold under the substantial part test — that certainty is only available through the 501(h) expenditure test election.', 'hard', 3),

-- Q2: medium / L2 — Supporting organizations under Section 509(a)(3)
(3, 'Tax-Exempt Organizations', 'Bright Scholars Support Inc. is organized and operated exclusively to provide fundraising and administrative services for three public universities. It is controlled by and responsive to the universities. Under Section 509(a)(3), how is Bright Scholars Support classified?', '["A private foundation because it does not receive broad public support", "A public charity because it qualifies as a supporting organization", "A private operating foundation because it provides services rather than grants", "A public charity only if it passes the one-third support test"]'::jsonb, 1, 'Under IRC Section 509(a)(3), an organization that is organized and operated exclusively to support one or more public charities qualifies as a "supporting organization" and is classified as a public charity. Bright Scholars Support meets this test because it supports public universities (which are automatic public charities) and is controlled by them. Choice A is incorrect because Section 509(a)(3) provides an alternative path to public charity status that does not require broad public support.', 'medium', 2),

-- Q3: medium / L3 — Convenience exclusion from UBIT
(3, 'Tax-Exempt Organizations', 'Mountain View University, a 501(c)(3) institution, operates a campus laundry facility open only to enrolled students and on-campus residents. The laundry generates $95,000 in annual revenue. The university''s controller asks whether this income is subject to UBIT. How should this revenue be analyzed?', '["Subject to UBIT because operating a laundry is a trade or business unrelated to education", "Subject to UBIT because the laundry charges commercial prices to students", "Partially subject to UBIT based on the percentage of student versus non-student usage", "Excluded from UBIT under the convenience exclusion because it serves students of the educational institution"]'::jsonb, 3, 'Under IRC Section 513(a)(2), activities conducted primarily for the convenience of members, students, patients, or employees are excluded from UBIT. The campus laundry serves enrolled students and on-campus residents, falling squarely within the convenience exclusion. Choice A is incorrect because even though the laundry meets the trade-or-business test, the statutory convenience exclusion overrides the three-part test when the activity serves the institution''s students.', 'medium', 3),

-- Q4: medium / L3 — Controlled entity payments exceeding FMV as UBIT
(3, 'Tax-Exempt Organizations', 'Cornerstone Health Foundation, a 501(c)(3), owns 100% of a for-profit medical supply company. The subsidiary pays $200,000 in annual rent to the foundation, which is $60,000 above fair market value for comparable space. How is this rental payment treated for UBIT purposes?', '["The $60,000 excess over fair market value is treated as UBIT because it is rent from a controlled subsidiary exceeding FMV", "The entire $200,000 is excluded from UBIT because real property rents are passive income", "The entire $200,000 is subject to UBIT because any rent from a subsidiary is unrelated business income", "Only $100,000 is subject to UBIT because 50% of controlled entity payments are taxable"]'::jsonb, 0, 'Under IRC Section 512(b)(13), rent, interest, or royalties received from a controlled subsidiary (80% or more ownership) are treated as UBIT to the extent they exceed fair market value. The $60,000 excess over FMV is included in UBTI. Choice B is incorrect because while real property rents are generally excluded as passive income, the controlled entity rule under Section 512(b)(13) creates an exception when payments from an 80%+ owned subsidiary exceed fair market value.', 'medium', 3),

-- Q5: easy / L1 — Dissolution clause requirement
(3, 'Tax-Exempt Organizations', 'What must a 501(c)(3) organization''s governing documents provide regarding asset distribution upon dissolution?', '["Assets must be distributed equally among the organization''s members", "Assets must be returned to the original donors or their estates", "Assets must be distributed to another exempt organization or to the government", "Assets must be placed in an escrow account for five years"]'::jsonb, 2, 'Under IRC Section 501(c)(3) and Treasury Regulation 1.501(c)(3)-1(b)(4), the organizational test requires a dissolution clause providing that upon dissolution, assets will be distributed to another tax-exempt organization or to the government. Choice A is incorrect because distributing assets to members would constitute private inurement, which is prohibited for 501(c)(3) organizations.', 'easy', 1),

-- Q6: medium / L3 — Personal property rents vs real property rents in UBIT
(3, 'Tax-Exempt Organizations', 'Westfield Community Foundation, a 501(c)(3), leases a fully furnished office building. The lease specifies $180,000 for the building and $45,000 for the office furniture and equipment. How is the personal property rental income treated for UBIT purposes?', '["The entire $225,000 is excluded because all rental income is passive", "The $45,000 personal property rent is included in UBTI because personal property rents exceed 10% of total rents under the lease", "Only $18,000 of the personal property rent is taxable based on a proportional allocation", "The entire $225,000 is subject to UBIT because the lease includes personal property"]'::jsonb, 1, 'Under IRC Section 512(b)(3), rents from real property are generally excluded from UBTI, but rents from personal property are included unless they are incidental (less than 10% of total rents under the lease). Here, personal property rent of $45,000 represents 20% of total rents ($225,000), exceeding the 10% threshold, so the $45,000 is included in UBTI. Choice D is incorrect because only the personal property portion is taxable — the $180,000 real property rent remains excluded.', 'medium', 3),

-- Q7: medium / L2 — Form 990-N (e-Postcard) threshold
(3, 'Tax-Exempt Organizations', 'Tiny Paws Animal Rescue, a small 501(c)(3), has gross receipts of $38,000 and total assets of $42,000 for the current year. Which annual information return must the organization file with the IRS?', '["Form 990-N (e-Postcard), an electronic notice requiring only basic information", "Form 990-EZ, a simplified version of the full Form 990", "Form 990, the full annual information return with financial statements", "No filing is required for organizations with gross receipts under $50,000"]'::jsonb, 0, 'Under IRC Section 6033(i), tax-exempt organizations with annual gross receipts of $50,000 or less may file Form 990-N (e-Postcard), an electronic notice requiring only the organization''s name, address, EIN, and confirmation of continued eligibility. Choice D is incorrect because even small exempt organizations must file an annual notice — failure to file for three consecutive years results in automatic revocation under Section 6033(j).', 'medium', 2),

-- Q8: medium / L2 — Schedule B confidentiality
(3, 'Tax-Exempt Organizations', 'A donor to Pacific Arts Council, a 501(c)(3), asks the executive director whether the donor''s identity and contribution amount will be publicly disclosed on the organization''s Form 990. Which schedule contains contributor information, and what is its public availability?', '["Schedule A, which is publicly available and discloses all contributor names and amounts", "Schedule J, which lists all donors receiving compensation and is publicly available", "Schedule O, which includes supplemental information about donors and is publicly available", "Schedule B, which contains contributor information but is not publicly available"]'::jsonb, 3, 'Schedule B (Schedule of Contributors) to Form 990 lists an organization''s significant contributors but is confidential and not publicly available. While most of Form 990 is available for public inspection under IRC Section 6104, Schedule B is specifically excepted to protect donor privacy. Choice A is incorrect because Schedule A reports public charity status and public support calculations, not individual contributor identities.', 'medium', 2),

-- Q9: medium / L3 — NOL deduction for UBIT computed only from UBI items
(3, 'Tax-Exempt Organizations', 'Oakdale Cultural Society, a 501(c)(3), incurred a $15,000 net operating loss from unrelated business activities in 2024. In 2025, the organization has $22,000 of UBTI before the NOL deduction and $180,000 of tax-exempt program revenue. How is the NOL applied against 2025 income?', '["The $15,000 NOL offsets both the $22,000 UBTI and a portion of the exempt program revenue", "The $15,000 NOL is applied against the $22,000 UBTI, reducing it to $7,000, because the NOL is computed using only UBI items", "The NOL cannot be carried forward because tax-exempt organizations are not permitted NOL deductions", "The $15,000 NOL is limited to 50% of UBTI under current NOL limitation rules"]'::jsonb, 1, 'Under IRC Section 512(b)(6), a net operating loss deduction is allowed against UBTI, but it is computed using only unrelated business income items. The $15,000 NOL from 2024 reduces 2025 UBTI of $22,000 to $7,000. Choice A is incorrect because NOLs from unrelated business activities can only offset unrelated business taxable income — they cannot reduce tax-exempt program revenue, which is not subject to UBIT.', 'medium', 3),

-- Q10: hard / L4 — Private inurement vs private benefit doctrine distinction
(3, 'Tax-Exempt Organizations', 'Horizon Medical Foundation, a 501(c)(3), awards a $200,000 research contract to a university laboratory at a reasonable price. The lab director has no connection to the foundation''s officers. However, the contract is structured so that 90% of the research benefit flows to a single pharmaceutical company that funds the foundation. Which 501(c)(3) prohibition does this arrangement potentially violate?', '["Private inurement, because the pharmaceutical company receives financial benefit from the foundation''s activities", "The self-dealing rules under Section 4941, because the foundation is transacting with a related for-profit entity", "The private benefit doctrine, because a substantial benefit flows to a specific private interest even though no insider is involved", "The lobbying restriction, because the research contract advances a commercial interest rather than an exempt purpose"]'::jsonb, 2, 'Under IRC Section 501(c)(3) and Treasury Regulation 1.501(c)(3)-1(d)(1)(ii), the operational test prohibits an organization from providing excessive private benefit to any individual or entity, regardless of whether they are insiders. The pharmaceutical company is not a disqualified person, so private inurement (Choice A) does not apply — inurement requires an insider relationship. The private benefit doctrine is broader and applies even when the beneficiary has no organizational affiliation.', 'hard', 4),

-- Q11: hard / L4 — Section 4945 taxable expenditures — dual violation analysis
(3, 'Tax-Exempt Organizations', 'Aurora Family Foundation, a private foundation, makes a $50,000 grant to an individual researcher for overseas travel without obtaining advance IRS approval or establishing objective selection criteria. It also makes a $75,000 grant to a 501(c)(4) social welfare organization without requiring expenditure responsibility. Which grants constitute taxable expenditures under Section 4945?', '["Both grants are taxable expenditures — the individual grant lacks IRS-approved procedures, and the 501(c)(4) grant lacks expenditure responsibility", "Only the individual grant is a taxable expenditure because grants to 501(c)(4) organizations are always permissible", "Only the 501(c)(4) grant is a taxable expenditure because individual grants are never subject to Section 4945", "Neither grant is a taxable expenditure because the foundation acted in good faith"]'::jsonb, 0, 'Under IRC Section 4945(d), both grants are taxable expenditures. Individual grants for travel and study are taxable expenditures unless made pursuant to IRS-approved procedures with objective selection criteria (Section 4945(g)). Grants to non-charitable organizations, including 501(c)(4) entities, are taxable expenditures unless the foundation exercises expenditure responsibility (Section 4945(d)(4)). Choice B is incorrect because 501(c)(4) organizations are not 501(c)(3) charities, so grants to them require expenditure responsibility.', 'hard', 4),

-- Q12: medium / L3 — Research exclusion: proprietary vs public
(3, 'Tax-Exempt Organizations', 'Valley State University, a 501(c)(3), conducts pharmaceutical research under a $2,000,000 contract with a private drug manufacturer. The findings are proprietary and available only to the manufacturer. The university also performs $500,000 of government-funded research whose results are published publicly. How is each research activity treated for UBIT?', '["Both are excluded from UBIT because all university research qualifies for the research exclusion", "Both are subject to UBIT because the university receives payment for the research services", "The government-funded research is subject to UBIT, but the private contract research is excluded", "The private contract research is subject to UBIT, but the government-funded research is excluded under Section 512(b)(8)"]'::jsonb, 3, 'Under IRC Section 512(b)(7)-(9), research performed for the U.S. government or by a college/university is excluded from UBIT, as is research whose results are freely available to the public. The government-funded research qualifies for exclusion. The proprietary pharmaceutical research does not qualify because results are not publicly available and the work is for a private entity. Choice A is incorrect because the research exclusion does not cover proprietary contract research restricted to the sponsoring company.', 'medium', 3),

-- Q13: medium / L3 — Debt-financed property ratio calculation
(3, 'Tax-Exempt Organizations', 'River City Historical Society, a 501(c)(3), purchases a rental building for $600,000 using a $360,000 mortgage. The property generates $48,000 in annual rental income. During the tax year, the average acquisition indebtedness is $330,000 and the average adjusted basis is $550,000. What portion of rental income is subject to UBIT as debt-financed income under Section 514?', '["$21,600, based on the original mortgage-to-purchase-price ratio", "$48,000, the entire rental income because the property carries any debt", "$28,800, based on the debt/basis percentage of $330,000 divided by $550,000 equaling 60%", "$0, because rental income from real property is always excluded from UBIT"]'::jsonb, 2, 'Under IRC Section 514, income from debt-financed property is subject to UBIT in proportion to the average acquisition indebtedness divided by the average adjusted basis. Here, $330,000/$550,000 = 60%, so 60% of the $48,000 rental income ($28,800) is included in UBTI. Choice D is incorrect because while real property rents are generally excluded as passive income, Section 514 creates an exception for income from property acquired or improved with borrowed funds.', 'medium', 3),

-- Q14: hard / L4 — Intermediate sanctions 200% additional tax for uncorrected excess benefit
(3, 'Tax-Exempt Organizations', 'DataBridge Solutions, a 501(c)(3), pays its CFO a $1,200,000 annual bonus in addition to her $400,000 salary. An independent study shows total reasonable compensation for the position is $500,000. The CFO does not return the excess benefit during the taxable period. Analyze the full excise tax consequences under Section 4958 for the CFO.', '["A 25% initial tax of $275,000 on the $1,100,000 excess benefit, plus a 200% additional tax of $2,200,000 for failure to correct", "A 10% tax on the CFO and a 5% tax on the board members who approved the arrangement", "Only a 25% tax of $275,000 because the 200% additional tax applies only to private foundations", "Automatic revocation of exempt status with no excise taxes on the individual"]'::jsonb, 0, 'Under IRC Section 4958, the excess benefit is $1,100,000 ($1,600,000 total compensation minus $500,000 reasonable compensation). The initial excise tax on the disqualified person is 25% of $1,100,000 = $275,000. If the excess benefit is not corrected within the taxable period, an additional 200% tax ($2,200,000) is imposed. Choice C is incorrect because the 200% additional tax applies to all Section 4958 excess benefit transactions involving 501(c)(3) or 501(c)(4) organizations, not just private foundations.', 'hard', 4),

-- Q15: medium / L2 — Churches automatic public charity regardless of funding
(3, 'Tax-Exempt Organizations', 'Grace Community Church receives 95% of its funding from a single wealthy family. The church does not solicit donations from the general public and has no formal fundraising program. Under Section 509, how is Grace Community Church classified?', '["A private foundation because it receives substantially all support from a single family", "A public charity because churches are automatically classified as public charities regardless of funding sources", "A private operating foundation because it receives concentrated funding but operates religious programs", "A public charity only if it elects to be treated as such by filing Form 1023"]'::jsonb, 1, 'Under IRC Section 509(a)(1) and Section 170(b)(1)(A)(i), churches are automatically classified as public charities regardless of their funding sources. They are not required to meet the one-third support test or any other public support test. Choice A is incorrect because the private foundation presumption is overridden for churches, schools, and hospitals, which receive automatic public charity status by virtue of their organizational category.', 'medium', 2),

-- Q16: easy / L1 — Filing deadline for Form 990
(3, 'Tax-Exempt Organizations', 'What is the filing deadline for Form 990 for a calendar-year tax-exempt organization?', '["March 15", "April 15", "June 15", "May 15"]'::jsonb, 3, 'Under IRC Section 6033, Form 990 is due on the 15th day of the 5th month after the end of the organization''s tax year. For calendar-year organizations, this is May 15. Choice B is incorrect because April 15 is the individual income tax filing deadline — exempt organization returns follow a different schedule under Section 6033.', 'easy', 1),

-- Q17: easy / L1 — Form 8868 extension
(3, 'Tax-Exempt Organizations', 'Which IRS form does a tax-exempt organization use to request an automatic extension of time to file its annual return?', '["Form 8868", "Form 4868", "Form 7004", "Form 2758"]'::jsonb, 0, 'Under IRC Section 6081, Form 8868 is used by tax-exempt organizations to request an automatic extension of up to six months for filing Form 990, 990-EZ, 990-PF, or 990-T. Choice B is incorrect because Form 4868 is the automatic extension form for individual income tax returns (Form 1040), not for exempt organization returns.', 'easy', 1),

-- Q18: medium / L2 — Section 509(a)(2) gross receipts test
(3, 'Tax-Exempt Organizations', 'Sunrise Swim Club, a 501(c)(3) nonprofit, receives 40% of its revenue from membership fees, 25% from swim lesson fees related to its exempt purpose, and 35% from a small number of wealthy patrons. Under Section 509(a)(2), which factor determines public charity status?', '["The club must receive at least 50% of support from the general public", "The club must demonstrate that no single patron provides more than 25% of total support", "The club must receive more than one-third of support from contributions, membership fees, and gross receipts from exempt-function activities", "The club must apply for public charity status through a separate IRS determination"]'::jsonb, 2, 'Under IRC Section 509(a)(2), an organization qualifies as a public charity if it normally receives more than one-third of its support from contributions, membership fees, and gross receipts from activities related to its exempt functions. Sunrise Swim Club receives 65% from membership and lesson fees (both exempt-function activities), exceeding the one-third threshold. Choice A is incorrect because Section 509(a)(2) uses a one-third test, not a 50% test.', 'medium', 2),

-- Q19: easy / L1 — Organization manager 10% tax cap for intermediate sanctions
(3, 'Tax-Exempt Organizations', 'Under Section 4958, what excise tax is imposed on an organization manager who knowingly participates in an excess benefit transaction?', '["25% of the excess benefit with no dollar cap", "10% of the excess benefit, up to $20,000 per transaction", "5% of the excess benefit, up to $10,000 per transaction", "200% of the excess benefit if not corrected"]'::jsonb, 1, 'Under IRC Section 4958(a)(2), an organization manager who knowingly participates in an excess benefit transaction is subject to a 10% excise tax on the excess benefit, capped at $20,000 per transaction. Choice A is incorrect because the 25% initial tax applies to the disqualified person who received the excess benefit, not to the organization manager.', 'easy', 1),

-- Q20: medium / L2 — Penalty for late filing of Form 990
(3, 'Tax-Exempt Organizations', 'Clearwater Arts Foundation, a 501(c)(3) with gross receipts of $650,000, files its Form 990 seventy days late without reasonable cause. Under IRC Section 6652(c), what penalty structure applies?', '["$20 per day for each day the return is late, up to the lesser of $10,500 or 5% of gross receipts", "$100 per day for each day the return is late, up to $53,000", "A flat penalty of $10,000 regardless of the number of days late", "No penalty because tax-exempt organizations are not subject to late-filing penalties"]'::jsonb, 0, 'Under IRC Section 6652(c)(1)(A), tax-exempt organizations with gross receipts under $1,186,000 that file Form 990 late without reasonable cause are penalized $20 per day for each day late, up to the lesser of $10,500 or 5% of gross receipts. At $650,000 in gross receipts, the 5% cap is $32,500, so the $10,500 cap applies. Choice B is incorrect because the $100/day penalty applies only to organizations with gross receipts of $1,186,000 or more.', 'medium', 2),

-- Q21: easy / L1 — Bingo games exclusion from UBIT
(3, 'Tax-Exempt Organizations', 'Under Section 513, which type of fundraising activity is specifically excluded from unrelated business taxable income?', '["Casino nights with professional dealers", "Charity auctions of donated artwork", "Annual raffles and sweepstakes with cash prizes", "Bingo games where commercial bingo is not ordinarily carried on in the jurisdiction"]'::jsonb, 3, 'Under IRC Section 513(f), income from bingo games is excluded from UBIT provided that the game is legal and commercial bingo is not regularly carried on in the jurisdiction. This is a specific statutory exclusion. Choice A is incorrect because casino-style activities with professional dealers do not qualify for the bingo exclusion — the exclusion is limited to traditional bingo games meeting the statutory conditions.', 'easy', 1),

-- Q22: easy / L1 — Form 990-EZ thresholds
(3, 'Tax-Exempt Organizations', 'Which conditions allow a tax-exempt organization to file Form 990-EZ instead of the full Form 990?', '["Gross receipts under $50,000 and total assets under $250,000", "Gross receipts under $200,000 and total assets under $500,000", "Gross receipts under $500,000 regardless of total assets", "Gross receipts under $100,000 and total assets under $250,000"]'::jsonb, 1, 'Under IRC Section 6033, an exempt organization may file Form 990-EZ if its gross receipts are less than $200,000 AND total assets are less than $500,000. Both thresholds must be met. Choice A is incorrect because organizations with gross receipts of $50,000 or less may file the even simpler Form 990-N (e-Postcard), not the 990-EZ.', 'easy', 1),

-- Q23: medium / L3 — Section 509(a)(1) one-third support test calculation
(3, 'Tax-Exempt Organizations', 'Green Valley Land Trust, a 501(c)(3), receives the following support over a four-year measuring period: $600,000 from government grants, $200,000 from public donations, and $400,000 from investment income. Total support is $1,200,000. Under Section 509(a)(1), does the organization qualify as a public charity?', '["No, because investment income exceeds public donations", "No, because government grants do not count toward the one-third support test", "Yes, because public support of $800,000 from government grants plus public donations exceeds one-third of total support", "Yes, because any organization receiving government grants automatically qualifies"]'::jsonb, 2, 'Under IRC Section 509(a)(1) and Section 170(b)(1)(A)(vi), an organization qualifies as a public charity if it receives a substantial part of its support from the general public or government. Government grants and public contributions both count as public support. Here, $800,000 in public support is 66.7% of $1,200,000 total support, well exceeding one-third. Choice B is incorrect because government grants are explicitly included in the public support calculation.', 'medium', 3),

-- Q24: easy / L2 — Operational test basics
(3, 'Tax-Exempt Organizations', 'A 501(c)(3) educational nonprofit uses 85% of its resources for tutoring programs and 15% for an unrelated commercial printing business. Does the organization satisfy the operational test?', '["Yes, because it is operated primarily for exempt purposes and the unrelated activity is insubstantial", "No, because any commercial activity disqualifies an organization from 501(c)(3) status", "Yes, but only if the printing business revenue is used entirely for the tutoring programs", "No, because the operational test requires 100% of activities to be exempt"]'::jsonb, 0, 'Under IRC Section 501(c)(3) and Treasury Regulation 1.501(c)(3)-1(c)(1), the operational test requires that the organization be operated primarily for exempt purposes. An insubstantial amount of non-exempt activity is permitted. With 85% devoted to tutoring (an exempt educational purpose), the organization satisfies the test. Choice D is incorrect because the operational test does not require 100% exempt activity — it allows for an insubstantial portion of unrelated activity.', 'easy', 2),

-- Q25: hard / L4 — Controlled entity + debt-financed income combined UBTI analysis
(3, 'Tax-Exempt Organizations', 'Pinnacle Community Foundation, a 501(c)(3), owns 90% of a for-profit subsidiary that pays $300,000 rent for office space with a fair market value of $250,000. Separately, the foundation owns a rental warehouse purchased with a $400,000 mortgage (average adjusted basis $500,000) generating $60,000 in annual rent from unrelated tenants. Evaluate the total amount included in UBTI from these two sources.', '["$110,000, combining $50,000 controlled entity excess plus $60,000 full warehouse rent", "$360,000, combining $300,000 controlled entity rent plus $60,000 warehouse rent", "$50,000, only the controlled entity excess because warehouse rent is excluded as passive income", "$98,000, combining $50,000 excess rent from the controlled subsidiary plus $48,000 debt-financed warehouse income"]'::jsonb, 3, 'Under IRC Section 512(b)(13), rent from a controlled subsidiary (90% ownership) exceeding FMV is UBTI — here, $50,000 ($300,000 minus $250,000). Under Section 514, debt-financed property income is taxable proportionally: $400,000/$500,000 = 80% times $60,000 = $48,000. Total UBTI = $98,000. Choice C is incorrect because while warehouse rent is normally passive, Section 514 overrides the passive income exclusion for debt-financed property.', 'hard', 4),

-- Q26: medium / L2 — Schedule J compensation disclosure
(3, 'Tax-Exempt Organizations', 'Lakewood Children''s Fund, a 501(c)(3), files Form 990 annually. The board chair asks which schedule reports compensation paid to officers, directors, and key employees. Which Form 990 schedule provides this information?', '["Schedule A, which reports public charity status and public support", "Schedule J, which reports compensation information for officers, directors, and key employees", "Schedule B, which reports contributor information and related compensation", "Schedule D, which reports supplemental financial statements including compensation"]'::jsonb, 1, 'Schedule J to Form 990 reports compensation information for the organization''s officers, directors, trustees, key employees, and highest compensated employees. It requires disclosure of base compensation, bonus, other compensation, and nontaxable benefits. Choice A is incorrect because Schedule A reports public charity status and public support test calculations, not compensation data.', 'medium', 2),

-- Q27: hard / L4 — Section 4943 combined holdings with disqualified persons
(3, 'Tax-Exempt Organizations', 'The Collins Family Foundation, a private foundation, owns 12% of Apex Manufacturing''s voting stock. Sarah Collins, the foundation''s primary donor and a disqualified person, personally owns 15% of Apex''s voting stock. Under Section 4943, evaluate whether excess business holdings exist and the consequences.', '["No excess holdings because the foundation itself owns only 12%, below the 20% limit", "No excess holdings because disqualified person holdings are counted separately from foundation holdings", "Excess holdings of 7% exist because the combined 27% exceeds the 20% limit, subjecting the excess to a 10% initial excise tax", "The foundation must divest all Apex stock because any foundation ownership in a business is prohibited"]'::jsonb, 2, 'Under IRC Section 4943, a private foundation and its disqualified persons may not together hold more than 20% of the voting stock of a business enterprise. Combined holdings are 27% (12% foundation plus 15% disqualified person), creating 7% excess. The initial excise tax is 10% of the value of the excess holdings. Choice A is incorrect because Section 4943 aggregates holdings of the foundation and all disqualified persons — the 20% limit applies to combined ownership, not the foundation''s holdings alone.', 'hard', 4),

-- Q28: easy / L1 — Form 990-PF required for all private foundations
(3, 'Tax-Exempt Organizations', 'Which annual return must all private foundations file regardless of their size or gross receipts?', '["Form 990-PF", "Form 990", "Form 990-EZ", "Form 990-N"]'::jsonb, 0, 'Under IRC Section 6033(a), all private foundations must file Form 990-PF (Return of Private Foundation) annually, regardless of their financial size. Unlike public charities that may file simplified returns based on gross receipts thresholds, private foundations have no size-based filing alternatives. Choice C is incorrect because Form 990-EZ is a simplified return available only to certain public charities — private foundations may not use it.', 'easy', 1),

-- Q29: easy / L1 — Section 4945 taxable expenditure categories
(3, 'Tax-Exempt Organizations', 'Under Section 4945, which of the following is classified as a taxable expenditure for a private foundation?', '["A grant to a 501(c)(3) public charity for general operating support", "An investment in U.S. Treasury bonds", "Payment of reasonable administrative salaries to foundation staff", "Spending funds to support or oppose a candidate for public office"]'::jsonb, 3, 'Under IRC Section 4945(d)(1), any amount paid by a private foundation to influence the outcome of a public election or to carry on certain voter registration drives is a taxable expenditure. Political campaign activity is absolutely prohibited. Choice A is incorrect because grants to 501(c)(3) public charities are not taxable expenditures — the rules target grants to non-charities, unapproved individual grants, lobbying, and political activity.', 'easy', 1),

-- Q30: medium / L2 — Form 990-T filing threshold
(3, 'Tax-Exempt Organizations', 'Redwood Nature Conservancy, a 501(c)(3), has gross unrelated business income of $850 for the current year. Must the organization file Form 990-T?', '["Yes, because all exempt organizations with any unrelated business income must file Form 990-T", "Yes, because Form 990-T must be filed whenever UBTI exceeds $500", "No, because Form 990-T is required only when gross unrelated business income is $1,000 or more", "No, because only private foundations are required to file Form 990-T"]'::jsonb, 2, 'Under IRC Section 6012(a)(6), a tax-exempt organization must file Form 990-T only when it has gross unrelated business income of $1,000 or more. With $850 in gross UBI, Redwood Nature Conservancy is below this threshold and is not required to file. Choice A is incorrect because the $1,000 filing threshold exempts organizations with minimal unrelated business income from the Form 990-T requirement.', 'medium', 2)
;

COMMIT;
