-- Migration: Question generation — FAR batch 30 (30 questions)
-- Date: 2026-03-01
-- Topic: Earnings Per Share
-- Difficulty: 9E / 15M / 6H
-- Bloom's: L1:8 / L2:9 / L3:8 / L4:5

BEGIN;

INSERT INTO questions (section_id, topic, stem, choices, correct_index, explanation, difficulty, cognitive_level)
VALUES

-- Q1: easy / L1 — Which entities must present EPS
(2, 'Earnings Per Share', 'Under U.S. GAAP, which type of entity is required to present earnings per share on the face of the income statement?', '["A publicly traded entity", "A private company with more than $10 million in revenue", "Any entity that prepares GAAP financial statements", "A not-for-profit organization with investment income"]'::jsonb, 0, 'Under ASC 260-10-15-2, EPS presentation is required only for entities with publicly traded common stock or potential common stock. This is correct because the standard limits the EPS requirement to public entities whose shares trade in public markets. While choice B suggests private companies with large revenues must present EPS, private companies are not required to do so, though they may voluntarily elect to.', 'easy', 1),

-- Q2: easy / L1 — Definition of complex capital structure
(2, 'Earnings Per Share', 'What defines a complex capital structure for earnings per share purposes under ASC 260?', '["The entity has more than one class of common stock", "The entity has outstanding securities that could dilute basic EPS", "The entity has both debt and equity on its balance sheet", "The entity uses multiple reporting currencies"]'::jsonb, 1, 'Under ASC 260-10-15-3, a complex capital structure exists when an entity has outstanding dilutive securities such as options, warrants, or convertible instruments that could reduce EPS upon exercise or conversion. This is correct because the presence of potentially dilutive securities triggers the dual-presentation requirement. While choice A references multiple stock classes, having multiple classes alone does not create a complex capital structure unless those securities are dilutive.', 'easy', 1),

-- Q3: medium / L3 — Participating securities and two-class method
(2, 'Earnings Per Share', 'Bellmont Industries has net income of $900,000, 200,000 common shares outstanding, and 50,000 participating preferred shares that receive dividends on a 1:1 basis with common. No preferred dividends were declared. Analyze how the participating preferred shares affect the basic EPS calculation compared to treating the preferred as nonparticipating.', '["Basic EPS is $3.60, which is lower than the $4.50 that would result from ignoring participation rights", "Basic EPS is $4.50 because undeclared dividends on participating preferred are ignored", "Basic EPS is $3.00 because all preferred shares reduce the numerator by their par value", "Basic EPS is $3.60, which equals the result if preferred were nonparticipating"]'::jsonb, 0, 'Under ASC 260-10-45-61A, participating securities require the two-class method for basic EPS. Undistributed earnings are allocated between common and participating preferred: $900,000 allocated as $720,000 to common (200,000/250,000) and $180,000 to preferred, yielding basic EPS of $3.60. This is lower than $4.50 ($900,000 / 200,000) because participation rights divert earnings to preferred. However, choice B is incorrect because it ignores the allocation requirement for participating securities.', 'medium', 3),

-- Q4: medium / L2 — Retroactive adjustment for stock split after year-end
(2, 'Earnings Per Share', 'Greystone Corp. reports net income of $640,000 for the year ended December 31, 2025, with 160,000 weighted-average shares outstanding. On February 15, 2026, before the financial statements are issued, Greystone declares a 2-for-1 stock split. What basic EPS should be reported in the 2025 financial statements?', '["$4.00", "$2.00", "$3.20", "$6.40"]'::jsonb, 1, 'Under ASC 260-10-55-12, stock splits and stock dividends occurring after the balance sheet date but before financial statements are issued must be retroactively reflected in the EPS computation. The weighted-average shares are adjusted to 320,000 (160,000 x 2), yielding basic EPS of $2.00 ($640,000 / 320,000). However, choice A ($4.00) incorrectly uses the pre-split share count of 160,000 and ignores the retroactive adjustment requirement.', 'medium', 2),

-- Q5: hard / L3 — Written put options effect on diluted EPS
(2, 'Earnings Per Share', 'Harmon Industries wrote put options obligating it to repurchase 20,000 of its own shares at $50 per share. The average market price during the period was $40. Net income is $750,000 and weighted-average common shares are 200,000. Analyze how the written put options affect diluted EPS under the reverse treasury stock method.', '["Diluted EPS decreases because 5,000 incremental shares are added to the denominator", "Diluted EPS is unaffected because out-of-the-money put options are excluded", "Diluted EPS decreases because the reverse treasury stock method adds 5,000 incremental shares when the exercise price exceeds market price", "Diluted EPS increases because the company receives cash from put holders"]'::jsonb, 2, 'Under ASC 260-10-45-35, written put options that are in the money (exercise price > market price) are potentially dilutive. The reverse treasury stock method assumes the entity uses proceeds from issuing shares at market ($40) to buy back shares at the exercise price ($50): 20,000 x $50 / $40 = 25,000 shares issued, producing 5,000 incremental shares (25,000 - 20,000). While choice A states the correct incremental share count, it omits the method name. However, choice B is incorrect because in-the-money written puts are dilutive, not excluded.', 'hard', 3),

-- Q6: easy / L1 — Dual presentation requirement
(2, 'Earnings Per Share', 'Under ASC 260, a public company with a complex capital structure must present which earnings per share amounts on the income statement?', '["Basic EPS only, presented on the income statement", "Diluted EPS only, presented on the income statement", "Both basic and diluted EPS with equal prominence", "Basic EPS on the income statement and diluted EPS in the notes"]'::jsonb, 2, 'Under ASC 260-10-45-2, entities with complex capital structures must present both basic and diluted EPS with equal prominence on the face of the income statement. This is correct because the dual presentation allows users to assess both current per-share earnings and the potential dilutive impact. Choice D is incorrect because ASC 260 requires both figures on the face of the income statement, not in the notes.', 'easy', 1),

-- Q7: easy / L1 — Treasury stock method denominator-only adjustment
(2, 'Earnings Per Share', 'When applying the treasury stock method for diluted EPS, which component of the EPS formula is affected by the assumed exercise of stock options?', '["Only the numerator", "Only the denominator", "Both the numerator and the denominator", "Neither the numerator nor the denominator"]'::jsonb, 1, 'Under ASC 260-10-45-22, the treasury stock method affects only the denominator of the EPS calculation. Proceeds from the assumed exercise are used to hypothetically repurchase shares at the average market price, and only the net incremental shares increase the denominator. Choice C is incorrect because, unlike the if-converted method for convertible debt, the treasury stock method does not adjust the numerator for interest savings or other income effects.', 'easy', 1),

-- Q8: hard / L4 — Forward purchase contracts and EPS judgment
(2, 'Earnings Per Share', 'Kensington Corp. enters a forward contract obligating it to repurchase 30,000 of its own shares at $60 per share in 12 months. The current average market price is $48. Net income is $1,200,000 with 300,000 weighted-average shares. The CFO argues the forward contract should be excluded from diluted EPS because no shares have actually been repurchased. Evaluate whether the CFO''s position is consistent with ASC 260.', '["The CFO is correct because forward contracts are only reflected when settled", "The CFO is incorrect because the contract is dilutive and adds 7,500 incremental shares to the denominator", "The CFO is correct because forward contracts at above-market prices are always antidilutive", "The CFO is incorrect because the contract requires removing 30,000 shares from the denominator entirely"]'::jsonb, 1, 'Under ASC 260-10-45-35, forward purchase contracts at above-market prices are treated similarly to written put options using the reverse treasury stock method. The entity would issue 30,000 x $60 / $48 = 37,500 shares to fund the repurchase, adding 7,500 incremental shares (37,500 - 30,000). The CFO''s position is inconsistent with ASC 260 because potentially dilutive contracts must be included regardless of settlement status. However, choice C is incorrect because above-market repurchase commitments are dilutive, not antidilutive.', 'hard', 4),

-- Q9: medium / L2 — Warrants in treasury stock method
(2, 'Earnings Per Share', 'Foxworth Holdings has 150,000 weighted-average common shares and net income of $480,000. The company has 12,000 outstanding warrants with an exercise price of $30. The average market price during 2025 was $50. Using the treasury stock method, what is diluted EPS?', '["$3.20", "$2.96", "$3.10", "$3.00"]'::jsonb, 2, 'Under ASC 260-10-45-22, the treasury stock method assumes warrants are exercised: 12,000 shares issued, with proceeds of $360,000 (12,000 x $30) used to repurchase 7,200 shares at the $50 average market price. Incremental shares are 4,800 (12,000 - 7,200). Diluted EPS = $480,000 / (150,000 + 4,800) = $480,000 / 154,800 = $3.10. However, choice A ($3.20) incorrectly uses the basic share count of 150,000 without adding the 4,800 incremental shares from the warrants.', 'medium', 2),

-- Q10: medium / L2 — Convertible preferred if-converted add-back
(2, 'Earnings Per Share', 'Dunmore Corp. has net income of $720,000, 180,000 common shares, and 10,000 shares of $50 par, 8% convertible preferred stock. Each preferred share converts into 3 common shares. Using the if-converted method, what is diluted EPS?', '["$3.44", "$3.24", "$3.43", "$3.60"]'::jsonb, 2, 'Under ASC 260-10-45-40, the if-converted method for convertible preferred adds back preferred dividends to the numerator and adds converted shares to the denominator. Preferred dividends = 10,000 x $50 x 8% = $40,000. Diluted numerator = $720,000 (no deduction for preferred dividends since conversion is assumed). Diluted denominator = 180,000 + 30,000 = 210,000. Diluted EPS = $720,000 / 210,000 = $3.43. However, choice D ($3.60) incorrectly omits the additional 30,000 converted shares from the denominator.', 'medium', 2),

-- Q11: medium / L2 — EPS for discontinued operations
(2, 'Earnings Per Share', 'Sutherland Inc. reports income from continuing operations of $500,000 and a loss from discontinued operations (net of tax) of $120,000. Weighted-average common shares are 100,000 with no preferred stock. What EPS amounts must Sutherland present on the income statement?', '["$5.00 for continuing operations and $3.80 for net income only", "$3.80 for net income as the sole EPS disclosure required", "$5.00 for continuing operations as the sole EPS disclosure", "$5.00 continuing operations, $(1.20) discontinued operations, and $3.80 net income"]'::jsonb, 3, 'Under ASC 260-10-45-3, EPS must be presented for income from continuing operations and for net income on the face of the income statement. EPS for discontinued operations may be presented on the face or in the notes. Continuing operations EPS = $500,000 / 100,000 = $5.00; discontinued = $(120,000) / 100,000 = $(1.20); net income EPS = $380,000 / 100,000 = $3.80. Choice B is incorrect because EPS for continuing operations must be presented separately, not just net income EPS.', 'medium', 2),

-- Q12: medium / L2 — Actual exercise of options during period
(2, 'Earnings Per Share', 'Whitfield Corp. had 200,000 shares outstanding on January 1, 2025, and 8,000 stock options with an exercise price of $25. On July 1, all 8,000 options were exercised when the market price was $55. The average market price for the January–June period was $50. Net income is $600,000. What is diluted EPS?', '["$2.88", "$2.93", "$2.91", "$2.95"]'::jsonb, 2, 'Under ASC 260-10-45-26, for options exercised mid-year, the treasury stock method applies for the pre-exercise period and actual shares for the post-exercise period. Pre-exercise incremental shares: 8,000 - (8,000 x $25 / $50) = 4,000 for 6/12 = 2,000 weighted. Post-exercise actual shares: 8,000 for 6/12 = 4,000 weighted. Total diluted shares: 200,000 + 2,000 + 4,000 = 206,000. Diluted EPS = $600,000 / 206,000 = $2.91. However, choice A ($2.88) incorrectly applies the treasury stock method for the full year rather than splitting the pre- and post-exercise periods.', 'medium', 2),

-- Q13: medium / L3 — Effect of share repurchase on basic EPS
(2, 'Earnings Per Share', 'Prescott Industries had 300,000 common shares outstanding on January 1, 2025, and repurchased 60,000 shares as treasury stock on October 1, 2025. Net income was $810,000 with no preferred dividends. Analyze the effect of the treasury stock repurchase on Prescott''s basic EPS compared to what EPS would have been without the buyback.', '["Basic EPS increases from $2.70 to $2.84 because the repurchase reduces weighted-average shares", "Basic EPS decreases because the cash used for repurchase reduces net income", "Basic EPS is unchanged because treasury stock is excluded from EPS calculations entirely", "Basic EPS increases from $2.70 to $3.38 because all 60,000 shares are removed for the full year"]'::jsonb, 0, 'Under ASC 260-10-45-10, repurchased shares are excluded from weighted-average shares from the repurchase date. Weighted-average = (300,000 x 9/12) + (240,000 x 3/12) = 225,000 + 60,000 = 285,000. Basic EPS = $810,000 / 285,000 = $2.84. Without the buyback, EPS = $810,000 / 300,000 = $2.70. The repurchase increased EPS by $0.14. Choice D ($3.38) is incorrect because the 60,000 shares are excluded only from October 1 forward, not retroactively for the full year.', 'medium', 3),

-- Q14: medium / L2 — Interim period EPS computation
(2, 'Earnings Per Share', 'Meridian Corp. had 100,000 shares outstanding on January 1, 2025, and issued 20,000 new shares on April 1. For the six months ending June 30, 2025, net income was $330,000. What is basic EPS for the six-month interim period?', '["$3.30", "$2.75", "$3.00", "$3.10"]'::jsonb, 2, 'Under ASC 260-10-45-60, interim EPS uses the weighted-average shares for that specific interim period. January–March: 100,000 shares for 3 months; April–June: 120,000 shares for 3 months. Weighted-average = (100,000 x 3/6) + (120,000 x 3/6) = 50,000 + 60,000 = 110,000. Basic EPS = $330,000 / 110,000 = $3.00. However, choice A ($3.30) incorrectly uses only the beginning share count of 100,000, ignoring the mid-period issuance.', 'medium', 2),

-- Q15: medium / L2 — Convertible debt interest savings net of tax
(2, 'Earnings Per Share', 'Ashland Corp. has net income of $400,000 and 100,000 weighted-average shares. It has $1,000,000 of 5% convertible bonds, each $1,000 bond convertible into 20 common shares. The tax rate is 21%. Using the if-converted method, what is diluted EPS?', '["$3.66", "$3.72", "$3.58", "$3.33"]'::jsonb, 0, 'Under ASC 260-10-45-40, the if-converted method for convertible bonds adds back after-tax interest to the numerator and converted shares to the denominator. Interest = $1,000,000 x 5% = $50,000; after-tax savings = $50,000 x (1 - 0.21) = $39,500. Diluted numerator = $400,000 + $39,500 = $439,500. Converted shares = 1,000 bonds x 20 = 20,000. Diluted denominator = 120,000. Diluted EPS = $439,500 / 120,000 = $3.66. However, choice C ($3.58) incorrectly applies a 25% tax rate rather than the stated 21%.', 'medium', 2),

-- Q16: hard / L4 — Antidilutive convertible bonds evaluation
(2, 'Earnings Per Share', 'Clarendon Corp. has net income of $750,000 with 250,000 weighted-average shares (basic EPS = $3.00). The company has $2,000,000 of 12% convertible bonds, each $1,000 bond convertible into 8 common shares. The tax rate is 21%. The treasurer recommends including these bonds in diluted EPS because they are convertible. Evaluate whether the treasurer''s recommendation is appropriate under ASC 260.', '["The recommendation is appropriate because all convertible securities must be included in diluted EPS", "The recommendation is inappropriate because the bonds are antidilutive with a per-share impact of $11.85, which exceeds basic EPS", "The recommendation is inappropriate because convertible bonds can never be included in diluted EPS", "The recommendation is appropriate because the after-tax interest add-back offsets the additional shares"]'::jsonb, 1, 'Under ASC 260-10-45-17, antidilutive securities must be excluded from diluted EPS. Per-share impact = after-tax interest / converted shares = ($2,000,000 x 12% x 0.79) / (2,000 x 8) = $189,600 / 16,000 = $11.85. Since $11.85 exceeds basic EPS of $3.00, including the bonds would increase EPS, making them antidilutive. The treasurer''s recommendation is inappropriate. Choice A is incorrect because ASC 260 explicitly requires exclusion of antidilutive securities — not all convertible securities are automatically included.', 'hard', 4),

-- Q17: medium / L3 — Mandatorily redeemable preferred stock and EPS
(2, 'Earnings Per Share', 'Redstone Holdings issues 5,000 shares of mandatorily redeemable preferred stock classified as a liability under ASC 480. Each share has a $100 par value and pays an 8% annual dividend. Net income is $950,000 with 200,000 common shares outstanding. Analyze how the mandatorily redeemable preferred dividends affect the basic EPS numerator.', '["Preferred dividends of $40,000 are deducted from the numerator, yielding basic EPS of $4.55", "Preferred dividends are treated as interest expense and already reduce net income, yielding basic EPS of $4.75", "The dividends are ignored because the preferred stock is classified as a liability", "Preferred dividends of $40,000 are added back to the numerator because they are liabilities"]'::jsonb, 1, 'Under ASC 260-10-45-11A, dividends on mandatorily redeemable preferred stock classified as liabilities under ASC 480 are recognized as interest expense in the income statement, not as equity distributions. Therefore, they already reduce net income and are not separately deducted in the EPS numerator. Basic EPS = $950,000 / 200,000 = $4.75. However, choice A incorrectly double-counts the preferred dividends by deducting them again from net income that already reflects the interest expense.', 'medium', 3),

-- Q18: medium / L3 — Rights issue with below-market element
(2, 'Earnings Per Share', 'Caldwell Corp. has 500,000 shares outstanding and issues rights to existing shareholders to purchase 1 share for every 5 held at $20 per share when the market price is $35. After the rights issue, 100,000 new shares are issued. Analyze whether a bonus element exists and its effect on the weighted-average share calculation for prior periods.', '["No bonus element exists because rights were issued to all shareholders proportionally", "A bonus element exists, requiring an adjustment factor to retroactively restate prior-period weighted-average shares", "The rights issue is treated identically to a stock split for all EPS purposes", "A bonus element exists but only affects diluted EPS, not basic EPS"]'::jsonb, 1, 'Under ASC 260-10-55-20, a rights issue at below-market price contains a bonus element similar to a stock dividend. The theoretical ex-rights price is calculated as [(500,000 x $35) + (100,000 x $20)] / 600,000 = $32.50. The adjustment factor is $35 / $32.50 = 1.077, applied retroactively to prior-period weighted-average shares to maintain comparability. Choice A is incorrect because even pro-rata rights issues at below-market prices contain a bonus element requiring adjustment under ASC 260.', 'medium', 3),

-- Q19: hard / L4 — Contracts settleable in cash or shares
(2, 'Earnings Per Share', 'Waverly Inc. issues a financial instrument that allows the holder to receive either $500,000 in cash or 25,000 common shares at settlement. The average market price is $22 per share. Net income is $880,000 with 200,000 weighted-average shares. The controller argues the instrument should be excluded from diluted EPS because the company intends to settle in cash. Evaluate whether the controller''s position is correct under ASC 260.', '["The controller is correct because the company''s intent to settle in cash determines the EPS treatment", "The controller is incorrect because ASC 260 requires the more dilutive settlement method to be used", "The controller is correct because cash-settled instruments never affect EPS", "The controller is incorrect because both settlement methods must be presented side by side"]'::jsonb, 1, 'Under ASC 260-10-45-45, when a contract may be settled in shares or cash at the issuer''s option, the more dilutive alternative must be assumed for diluted EPS purposes regardless of the entity''s stated intent. Share settlement would add 25,000 shares to the denominator, which is more dilutive than cash settlement. The controller''s reliance on intent is inconsistent with ASC 260''s presumption of maximum dilution. Choice A is incorrect because issuer intent does not override the more-dilutive presumption required by the standard.', 'hard', 4),

-- Q20: easy / L1 — Definition of antidilutive securities
(2, 'Earnings Per Share', 'Under ASC 260, what are antidilutive securities in the context of earnings per share?', '["Securities that decrease net income when exercised or converted", "Securities whose inclusion in the computation would increase EPS or decrease loss per share", "Securities that reduce the number of shares outstanding", "Securities that are classified as equity rather than debt"]'::jsonb, 1, 'Under ASC 260-10-20, antidilutive securities are those whose assumed exercise or conversion would increase EPS or decrease loss per share. This is correct because antidilutive securities must be excluded from diluted EPS to ensure diluted EPS is never higher than basic EPS. Choice A is incorrect because the impact on net income alone does not determine whether a security is antidilutive — it is the net effect on the per-share amount that matters.', 'easy', 1),

-- Q21: easy / L1 — Simple capital structure EPS presentation
(2, 'Earnings Per Share', 'A public entity with a simple capital structure is required to present which EPS figure on the income statement?', '["Basic EPS only, on the income statement", "Diluted EPS only, on the income statement", "Both basic and diluted EPS together", "No EPS is required for simple capital structures"]'::jsonb, 0, 'Under ASC 260-10-45-2, entities with simple capital structures (no potentially dilutive securities) present only basic EPS. This is correct because without dilutive securities, basic and diluted EPS would be identical, making dual presentation unnecessary. Choice C is incorrect because the requirement to present both basic and diluted EPS applies only to entities with complex capital structures.', 'easy', 1),

-- Q22: easy / L2 — Basic weighted-average calculation with shares issued for acquisition
(2, 'Earnings Per Share', 'Oakmont Corp. had 100,000 shares outstanding on January 1, 2025. On September 1, Oakmont issued 24,000 shares to acquire a subsidiary. What is the weighted-average number of common shares for 2025?', '["108,000", "124,000", "112,000", "116,000"]'::jsonb, 0, 'Under ASC 260-10-45-10, shares issued during the period are weighted from the issuance date. The 24,000 shares are outstanding for 4 months (September through December). Weighted-average = 100,000 + (24,000 x 4/12) = 100,000 + 8,000 = 108,000. However, choice B (124,000) incorrectly includes all 24,000 shares for the full year rather than weighting them for the period outstanding.', 'easy', 2),

-- Q23: medium / L3 — Year-to-date vs. quarterly EPS
(2, 'Earnings Per Share', 'Fairview Corp. reports quarterly basic EPS of $1.20, $0.80, $1.50, and $1.00 for quarters 1 through 4. An analyst sums the four quarters to report annual EPS of $4.50. Analyze whether this approach is consistent with ASC 260 for annual EPS reporting.', '["The approach is correct because annual EPS equals the sum of quarterly EPS", "The approach is incorrect because annual EPS must use the annual weighted-average shares, which may differ from the sum of quarterly figures", "The approach is correct as long as share counts did not change during the year", "The approach is incorrect because annual EPS should be the average of the four quarterly EPS figures"]'::jsonb, 1, 'Under ASC 260-10-45-60, annual EPS must be computed independently using the annual weighted-average share count, not by summing quarterly EPS amounts. Due to share issuances, repurchases, or conversions at different points during the year, quarterly weighted-average shares differ, and summing quarterly EPS does not yield the correct annual figure. Choice A is incorrect because the sum-of-quarters approach produces a mathematically inconsistent result when weighted-average shares change across periods.', 'medium', 3),

-- Q24: easy / L1 — EPS rounding convention
(2, 'Earnings Per Share', 'Under ASC 260, to how many decimal places must earnings per share amounts be presented at a minimum?', '["The nearest whole dollar amount", "Two decimal places, to the nearest cent", "Four decimal places for maximum precision", "No specific number of decimal places is required"]'::jsonb, 1, 'Under ASC 260-10-45-5, EPS amounts must be presented for all periods for which an income statement is presented, and common practice supported by SEC guidance requires reporting to the nearest cent (two decimal places). This is correct because per-share data should be precise enough for investment analysis. Choice A is incorrect because rounding to the nearest whole dollar would obscure meaningful differences in per-share performance between periods.', 'easy', 1),

-- Q25: medium / L3 — Stock compensation expense effect on EPS
(2, 'Earnings Per Share', 'Bridgewater Inc. records $180,000 in stock-based compensation expense for unvested restricted stock units (RSUs) under ASC 718. Net income after this expense is $620,000 with 100,000 weighted-average shares. The RSUs represent 15,000 shares expected to vest. Analyze how the stock compensation expense and the RSUs separately affect basic and diluted EPS.', '["The expense reduces both basic and diluted EPS equally through the numerator only", "The expense reduces the basic EPS numerator, and the unvested RSUs increase the diluted EPS denominator using the treasury stock method", "The expense is added back to the numerator for diluted EPS because it is a noncash charge", "The RSUs affect basic EPS by increasing the denominator immediately upon grant"]'::jsonb, 1, 'Under ASC 260-10-45-16 and ASC 718-10-45-4, stock compensation expense reduces net income (the numerator) for both basic and diluted EPS. For diluted EPS, unvested RSUs are treated as potential common shares using the treasury stock method, adding incremental shares to the denominator. The expense is not added back because it is a real operating cost. Choice C is incorrect because, unlike depreciation in cash flow statements, stock compensation expense is not reversed in the EPS numerator.', 'medium', 3),

-- Q26: medium / L3 — Contingently issuable shares with unmet conditions
(2, 'Earnings Per Share', 'Stratton Corp. will issue 40,000 additional shares to former shareholders of an acquired company if cumulative net income exceeds $5,000,000 over three years. After Year 2, cumulative net income is $2,800,000. Analyze how these contingently issuable shares are treated in Year 2 basic and diluted EPS.', '["Included in both basic and diluted EPS because issuance is probable", "Excluded from both basic and diluted EPS because the earnings condition is not yet met", "Excluded from basic EPS but included in diluted EPS if the condition were met at the reporting date", "Included in basic EPS because the shares are legally committed"]'::jsonb, 2, 'Under ASC 260-10-45-48, contingently issuable shares are included in basic EPS only when all conditions are satisfied. For diluted EPS, they are included if the conditions would be met assuming the end of the reporting period is the end of the contingency period. Since $2,800,000 after two years does not meet the $5,000,000 threshold even if projected, they are excluded from basic EPS but would be included in diluted EPS only if current-period earnings extrapolated to the end of the contingency period would satisfy the target. Choice B is incorrect because diluted EPS requires a separate ''as if'' test, not automatic exclusion.', 'medium', 3),

-- Q27: medium / L2 — Shares issued mid-year for cash
(2, 'Earnings Per Share', 'Thornbury Ltd. had 200,000 shares outstanding on January 1, 2025. On July 1, the company issued 40,000 shares for $35 per share. Net income for 2025 is $660,000 with no preferred dividends. What is basic EPS?', '["$3.00", "$2.75", "$3.30", "$3.67"]'::jsonb, 0, 'Under ASC 260-10-45-10, shares are included in the weighted-average from their issuance date. Weighted-average shares = (200,000 x 6/12) + (240,000 x 6/12) = 100,000 + 120,000 = 220,000. Basic EPS = $660,000 / 220,000 = $3.00. However, choice C ($3.30) incorrectly uses the beginning share count of 200,000 for the full year, ignoring the mid-year issuance weighting.', 'medium', 2),

-- Q28: easy / L1 — Where EPS is NOT required
(2, 'Earnings Per Share', 'Which of the following financial statements does NOT require per-share amounts under ASC 260?', '["The income statement", "The statement of comprehensive income", "The balance sheet", "Discontinued operations presentation"]'::jsonb, 2, 'Under ASC 260-10-45-2, per-share amounts are required on the face of the income statement for continuing operations and net income. EPS for discontinued operations and other comprehensive income may also be presented. However, the balance sheet does not present earnings per share data. Choice A is incorrect because the income statement is the primary location where EPS must be reported under ASC 260.', 'easy', 1),

-- Q29: hard / L4 — Multi-step dilution ordering
(2, 'Earnings Per Share', 'Pinnacle Enterprises has basic EPS of $5.00 (net income $1,000,000, 200,000 shares). It has three potentially dilutive securities: (1) stock options adding 8,000 incremental shares, (2) 6% convertible bonds ($500,000 face, 10,000 converted shares, 21% tax rate), and (3) 4% convertible preferred ($200,000 par, 5,000 converted shares, $8,000 dividends). Evaluate the correct inclusion order and determine which securities, if any, should be excluded as antidilutive.', '["All three are dilutive and should be included in the order: options, preferred, bonds", "Options and preferred are dilutive but the bonds are antidilutive after sequential testing", "All three are dilutive in the order: options, bonds, preferred", "Options are dilutive but both convertible securities are antidilutive"]'::jsonb, 0, 'Under ASC 260-10-45-21, potentially dilutive securities are ranked by per-share impact (lowest first) and included sequentially. Options: no numerator impact, 8,000 incremental shares = $0.00 per share. Preferred: $8,000 / 5,000 = $1.60 per share. Bonds: $500,000 x 6% x 0.79 / 10,000 = $23,700 / 10,000 = $2.37 per share. Order: options ($0.00), preferred ($1.60), bonds ($2.37). After including options: EPS = $1,000,000 / 208,000 = $4.81. After preferred: $1,008,000 / 213,000 = $4.73. After bonds: $1,031,700 / 223,000 = $4.63. All reduce EPS, so all are dilutive. Choice B is incorrect because bonds at $2.37 per share still decrease diluted EPS below $4.73.', 'hard', 4),

-- Q30: hard / L4 — Loss period dilution assessment
(2, 'Earnings Per Share', 'Marlow Technologies reports a net loss of $450,000 with 150,000 weighted-average shares, producing basic loss per share of $(3.00). The company has 20,000 in-the-money stock options (5,000 incremental shares via treasury stock method) and $300,000 of 5% convertible bonds (6,000 converted shares, 21% tax rate). The CFO proposes presenting diluted loss per share of $(2.55) by including both securities. Evaluate whether this presentation complies with ASC 260.', '["The presentation complies because both securities are in-the-money and must be included", "The presentation does not comply because all potentially dilutive securities are antidilutive during a loss period, and diluted loss per share should equal basic loss per share", "The presentation complies because convertible bonds reduce the loss through interest add-back", "The presentation does not comply because only the options should be included, not the bonds"]'::jsonb, 1, 'Under ASC 260-10-45-17, when an entity reports a net loss from continuing operations, all potentially dilutive securities are antidilutive because adding shares to the denominator would reduce the loss per share (making it appear less negative). ASC 260 prohibits presenting diluted loss per share that is less negative than basic loss per share. Therefore, diluted loss per share must equal basic loss per share at $(3.00). Choice C is incorrect because even though the bond interest add-back reduces the loss, the incremental shares still reduce the per-share loss, making the security antidilutive in a loss period.', 'hard', 4)
;

COMMIT;
