-- Migration: Question generation — FAR batch 33 (30 questions)
-- Date: 2026-03-01
-- Topic: Earnings Per Share
-- Difficulty: 9E / 15M / 6H
-- Bloom's: L1:8 / L2:9 / L3:8 / L4:5

BEGIN;

INSERT INTO questions (section_id, topic, stem, choices, correct_index, explanation, difficulty, cognitive_level)
VALUES

-- Q1: easy / L1 — ASC 260 scope: which entities must present EPS
(2, 'Earnings Per Share', 'Under ASC 260, which entities are required to present earnings per share on the face of the income statement?', '["All entities that prepare financial statements under U.S. GAAP", "Only public entities whose common stock or potential common stock is publicly traded", "Only entities with annual revenues exceeding $25 million", "All entities with complex capital structures"]'::jsonb, 1, 'Under ASC 260-10-15-2, EPS presentation is required only for entities whose common stock or potential common stock is traded in a public market. Nonpublic entities are exempt from EPS disclosure, though they may voluntarily present it. Choice A is incorrect because private entities preparing GAAP financial statements are not required to present EPS.', 'easy', 1),

-- Q2: medium / L2 — Two-class method for participating securities
(2, 'Earnings Per Share', 'Haverford Industries reports net income of $1,500,000 for 2025. The company has 400,000 common shares and 100,000 participating preferred shares outstanding all year. Preferred shareholders receive a $2.00 per-share base dividend and then participate equally per share with common stock in undistributed earnings. Total declared dividends were $1,000,000 ($200,000 to preferred, $800,000 to common). Using the two-class method under ASC 260, what is basic EPS for common stock?', '["$3.25", "$3.75", "$3.00", "$2.50"]'::jsonb, 2, 'Under ASC 260-10-45-61A, participating securities require the two-class method. Undistributed earnings = $1,500,000 - $1,000,000 = $500,000. Common''s share = 400,000 / 500,000 total shares = 80%, so $400,000. Common earnings = $800,000 dividends + $400,000 undistributed = $1,200,000. EPS = $1,200,000 / 400,000 = $3.00. Choice A ($3.25) incorrectly deducts only the preferred base dividend without sharing undistributed earnings with the participating preferred.', 'medium', 2),

-- Q3: hard / L4 — Evaluate antidilutive convertible bonds
(2, 'Earnings Per Share', 'Silverton Corp. has net income of $1,200,000 with 400,000 weighted-average shares (basic EPS = $3.00). The company has $5,000,000 face value, 10% convertible bonds outstanding all year, convertible into 100,000 common shares. The tax rate is 25%. The controller believes the bonds should be included in diluted EPS because interest savings would increase income. Evaluate whether the bonds are dilutive and determine the correct diluted EPS.', '["The bonds are antidilutive and must be excluded; diluted EPS equals basic EPS of $3.00", "The bonds are dilutive; diluted EPS is $3.15", "The bonds are dilutive; diluted EPS is $2.75", "The bonds are antidilutive because the face value exceeds net income"]'::jsonb, 0, 'Under ASC 260-10-45-17, securities are antidilutive if inclusion would increase EPS. After-tax interest add-back = $5,000,000 x 10% x (1 - 0.25) = $375,000. Per-share impact = $375,000 / 100,000 = $3.75, which exceeds basic EPS of $3.00. Including the bonds would yield ($1,200,000 + $375,000) / 500,000 = $3.15, increasing EPS above $3.00, confirming antidilution. Choice B incorrectly includes the bonds despite the antidilutive result.', 'hard', 4),

-- Q4: medium / L3 — EPS restatement for retroactive stock split after balance sheet date
(2, 'Earnings Per Share', 'Creston Manufacturing reported basic EPS of $5.00 for 2025, based on net income of $1,000,000 and 200,000 weighted-average shares. On February 15, 2026, before the 2025 financial statements are issued, Creston declares a 2-for-1 stock split. What is the effect on 2025 EPS as reported in the financial statements?', '["EPS remains $5.00 because the split occurred after the balance sheet date", "EPS is restated to $2.50 to reflect the split retroactively", "EPS is reported as $5.00 with a footnote disclosing the split only", "EPS is restated to $3.33 using a time-weighted adjustment"]'::jsonb, 1, 'Under ASC 260-10-55-12, stock splits occurring after the balance sheet date but before financial statements are issued must be given retroactive effect in EPS computations. The weighted-average shares double to 400,000, producing restated EPS of $2.50. Choice A is incorrect because ASC 260 requires retroactive restatement for stock splits regardless of timing relative to year-end.', 'medium', 3),

-- Q5: medium / L2 — RSUs in diluted EPS using treasury stock method
(2, 'Earnings Per Share', 'Belmont Technologies has net income of $630,000 and 300,000 weighted-average shares during 2025. The company granted 18,000 unvested restricted stock units with average unrecognized compensation cost of $10 per share. The average market price during 2025 was $60. Using the treasury stock method, what is diluted EPS?', '["$2.10", "$2.06", "$2.00", "$1.90"]'::jsonb, 2, 'Under ASC 260-10-45-28, unvested RSUs use the treasury stock method with unrecognized compensation as assumed proceeds. Assumed proceeds = 18,000 x $10 = $180,000; shares repurchased at $60 = 3,000; incremental shares = 18,000 - 3,000 = 15,000. Diluted EPS = $630,000 / (300,000 + 15,000) = $2.00. Choice A ($2.10) is basic EPS and incorrectly excludes the dilutive effect of the RSUs.', 'medium', 2),

-- Q6: medium / L2 — Weighted-average shares for business combination
(2, 'Earnings Per Share', 'On September 1, 2025, Northbrook Corp. acquired Glendale Inc. by issuing 60,000 shares of common stock. Northbrook had 240,000 shares outstanding on January 1, 2025, and issued no other shares during the year. What is Northbrook''s weighted-average number of common shares for 2025?', '["300,000", "280,000", "270,000", "260,000"]'::jsonb, 3, 'Under ASC 260-10-45-10, shares issued in a business combination are included in the weighted-average from the acquisition date. The 60,000 shares issued September 1 are weighted for 4/12 of the year: 60,000 x 4/12 = 20,000. Added to 240,000 shares outstanding all year, the weighted-average is 260,000. Choice A (300,000) incorrectly treats the acquired shares as outstanding for the full year.', 'medium', 2),

-- Q7: medium / L2 — Warrants using treasury stock method
(2, 'Earnings Per Share', 'Kensington Holdings has net income of $1,040,000 and 200,000 weighted-average common shares during 2025. The company has 20,000 warrants outstanding with an exercise price of $30 per share. The average market price during 2025 was $50. Using the treasury stock method, what is diluted EPS?', '["$5.20", "$5.00", "$4.73", "$4.95"]'::jsonb, 1, 'Under ASC 260-10-45-22, warrants use the treasury stock method identically to stock options. Assumed proceeds = 20,000 x $30 = $600,000; shares repurchased at $50 = 12,000; incremental shares = 20,000 - 12,000 = 8,000. Diluted EPS = $1,040,000 / (200,000 + 8,000) = $5.00. Choice C ($4.73) incorrectly adds all 20,000 warrant shares without reducing for the assumed treasury stock repurchase.', 'medium', 2),

-- Q8: hard / L4 — Written put options: evaluate controller exclusion
(2, 'Earnings Per Share', 'Ashfield Corp. has net income of $2,600,000 and 500,000 weighted-average shares (basic EPS = $5.20). The company wrote put options obligating it to repurchase 40,000 shares at $75 per share if exercised. The average market price during 2025 was $50. The controller excluded these puts from diluted EPS, reasoning that repurchase obligations do not create new shares. Evaluate the controller''s decision.', '["The controller is incorrect; the puts are dilutive and must be included using the reverse treasury stock method, producing diluted EPS of $5.00", "The controller is correct; written put options only affect treasury stock accounting, not EPS", "The controller is incorrect; the puts should be treated as stock options using the standard treasury stock method", "The controller is correct; written put options are always antidilutive because they reduce shares outstanding"]'::jsonb, 0, 'Under ASC 260-10-45-35, written put options with exercise prices above market are dilutive. The reverse treasury stock method assumes repurchase of 40,000 shares at $75 ($3,000,000), then issuance of $3,000,000 / $50 = 60,000 shares at market price, creating 20,000 net incremental shares. Diluted EPS = $2,600,000 / 520,000 = $5.00. Choice D incorrectly claims puts are always antidilutive; they are dilutive when exercise price exceeds market price.', 'hard', 4),

-- Q9: medium / L2 — If-converted method for convertible preferred stock
(2, 'Earnings Per Share', 'Wellington Corp. has net income of $960,000 and 200,000 weighted-average common shares during 2025. The company has 4,000 shares of $100 par, 5% convertible preferred stock outstanding all year, each convertible into 10 common shares. What is diluted EPS?', '["$4.70", "$4.50", "$4.00", "$3.80"]'::jsonb, 2, 'Under ASC 260-10-45-40, convertible preferred stock uses the if-converted method. Preferred dividend = 4,000 x $100 x 5% = $20,000. Basic EPS = ($960,000 - $20,000) / 200,000 = $4.70. For diluted EPS, add back the $20,000 dividend (numerator = $960,000) and add 40,000 conversion shares (4,000 x 10). Diluted EPS = $960,000 / 240,000 = $4.00. Choice A ($4.70) is basic EPS and omits the convertible preferred from diluted EPS.', 'medium', 2),

-- Q10: medium / L3 — Effect of share buyback on basic EPS
(2, 'Earnings Per Share', 'Mercer Industries reported net income of $1,200,000 in both 2024 and 2025, with 400,000 shares outstanding all of 2024. During 2025, Mercer repurchased shares evenly throughout the year, ending with 300,000 shares outstanding on December 31. The weighted-average for 2025 was 350,000 shares. Compared to 2024, what is the most likely effect of the buyback on 2025 basic EPS?', '["EPS decreases from $3.00 to $2.73 because retained earnings decline by the buyback cost", "EPS remains at $3.00 because treasury stock transactions do not affect net income", "EPS increases from $3.00 to $4.00 because all repurchased shares are removed for the full year", "EPS increases from $3.00 to $3.43 because the weighted-average shares decrease to 350,000"]'::jsonb, 3, 'Under ASC 260-10-45-10, repurchased shares reduce the weighted-average from their respective purchase dates. With net income constant at $1,200,000 and weighted-average shares declining from 400,000 to 350,000, EPS rises from $3.00 to $3.43. The numerator is unaffected because treasury stock transactions bypass the income statement. Choice C ($4.00) incorrectly uses year-end shares of 300,000 rather than the weighted-average of 350,000.', 'medium', 3),

-- Q11: medium / L2 — Treasury stock repurchase effect on weighted-average shares
(2, 'Earnings Per Share', 'Pinnacle Corp. had 300,000 common shares outstanding on January 1, 2025. On July 1, Pinnacle repurchased 100,000 shares as treasury stock. No shares were reissued. Net income for 2025 was $1,000,000 with no preferred dividends. What is basic EPS?', '["$4.00", "$3.33", "$5.00", "$4.44"]'::jsonb, 0, 'Under ASC 260-10-45-10, treasury shares are excluded from the weighted-average from the repurchase date. Weighted-average = (300,000 x 6/12) + (200,000 x 6/12) = 250,000. Basic EPS = $1,000,000 / 250,000 = $4.00. Choice C ($5.00) incorrectly uses the year-end count of 200,000 as if the repurchase occurred on January 1 rather than weighting from the actual repurchase date.', 'medium', 2),

-- Q12: medium / L3 — Loss from continuing operations makes all securities antidilutive
(2, 'Earnings Per Share', 'Oakridge Electronics reports a loss from continuing operations of $500,000 and income from discontinued operations of $200,000, resulting in a net loss of $300,000. The company has 100,000 weighted-average shares and 10,000 stock options producing 5,000 incremental shares under the treasury stock method. How should the options be treated for diluted EPS?', '["Include options for discontinued operations EPS but exclude from continuing operations EPS", "Exclude options from diluted EPS for all line items because the loss from continuing operations is the control number", "Include options for all EPS line items because total net loss is the control number", "Exclude options from continuing operations only and use management judgment for other line items"]'::jsonb, 1, 'Under ASC 260-10-45-19, income (loss) from continuing operations is the control number for determining dilution. Because Oakridge has a loss from continuing operations, all potentially dilutive securities are antidilutive for every EPS line item, including discontinued operations. Choice A is incorrect because ASC 260 prohibits selectively including dilutive securities for some line items while excluding them from others.', 'medium', 3),

-- Q13: medium / L2 — Mandatorily convertible preferred in diluted EPS
(2, 'Earnings Per Share', 'Wexford Corp. issued 10,000 shares of mandatorily convertible preferred stock on January 1, 2025, each mandatorily converting into 3 common shares on December 31, 2027. Annual preferred dividends are $2.00 per share. Wexford has net income of $690,000 and 200,000 weighted-average common shares during 2025. What is diluted EPS?', '["$3.35", "$3.22", "$3.10", "$3.00"]'::jsonb, 3, 'Under ASC 260-10-45-45, mandatorily convertible instruments use the if-converted method regardless of conversion probability. Basic EPS = ($690,000 - $20,000) / 200,000 = $3.35. For diluted EPS, add back the $20,000 preferred dividend (numerator = $690,000) and add 30,000 conversion shares (10,000 x 3), totaling 230,000. Diluted EPS = $690,000 / 230,000 = $3.00. Choice A ($3.35) is basic EPS and incorrectly omits the mandatory conversion.', 'medium', 2),

-- Q14: easy / L1 — Dual presentation: basic and diluted EPS on income statement
(2, 'Earnings Per Share', 'Under U.S. GAAP, which EPS figures must a public company with a complex capital structure present on the face of the income statement?', '["Only basic EPS for each period presented", "Only diluted EPS for each period presented", "Both basic and diluted EPS with equal prominence for each period presented", "Basic EPS on the income statement and diluted EPS in the footnotes"]'::jsonb, 2, 'Under ASC 260-10-45-2, entities with complex capital structures must present both basic and diluted EPS with equal prominence on the face of the income statement for income from continuing operations and net income. Choice D is incorrect because diluted EPS cannot be relegated to the footnotes — ASC 260 requires both measures on the face of the income statement.', 'easy', 1),

-- Q15: medium / L2 — EPS presentation for discontinued operations
(2, 'Earnings Per Share', 'Ferndale Corp. reports income from continuing operations of $900,000 and a loss from discontinued operations of $150,000, resulting in net income of $750,000. The company has 250,000 weighted-average shares and no potentially dilutive securities. How must EPS be presented on the income statement?', '["$3.60 for continuing operations and $3.00 for net income on the face, with discontinued operations EPS either on the face or in the notes", "Only $3.00 per share for net income", "$3.60 for continuing operations only; no other EPS amounts required", "$3.60 for continuing operations, $(0.60) for discontinued operations, and $3.00 for net income — all required on the face"]'::jsonb, 0, 'Under ASC 260-10-45-3, EPS must be presented on the face of the income statement for income from continuing operations ($3.60) and net income ($3.00). Per ASC 260-10-45-3A, the per-share amount for discontinued operations may be presented either on the face or in the notes. Choice D is incorrect because discontinued operations EPS is not required on the face of the income statement.', 'medium', 2),

-- Q16: medium / L3 — Rights offering with bonus element adjustment factor
(2, 'Earnings Per Share', 'Stratford Corp. had 200,000 shares outstanding when it announced a rights offering allowing shareholders to purchase 1 new share for every 4 shares held at $20 per share. The market price before the offering was $40 per share. The theoretical ex-rights price is $36. What adjustment factor should be applied to the pre-rights weighted-average shares to maintain EPS comparability?', '["0.90", "1.00", "0.80", "1.11"]'::jsonb, 3, 'Under ASC 260-10-55-19, a rights offering below market price contains a bonus element requiring a retroactive adjustment to weighted-average shares. The theoretical ex-rights price = (4 x $40 + 1 x $20) / 5 = $36. The adjustment factor = pre-rights market price / ex-rights price = $40 / $36 = 1.11. Choice B (1.00) incorrectly assumes no adjustment, which would only apply if the offering price equaled the market price.', 'medium', 3),

-- Q17: easy / L1 — Definition of weighted-average shares
(2, 'Earnings Per Share', 'In computing basic EPS under ASC 260, what does the term weighted-average common shares outstanding represent?', '["Common shares weighted by the portion of the reporting period they were outstanding", "The total number of authorized shares available for issuance", "The arithmetic average of beginning and ending shares outstanding", "All issued shares including treasury stock held at year-end"]'::jsonb, 0, 'Under ASC 260-10-45-10, the weighted-average is computed by weighting shares by the fraction of the period they were outstanding. Shares issued or repurchased mid-period receive proportional weight from the transaction date. Choice C is incorrect because a simple average of beginning and ending balances would not properly reflect the timing of share transactions occurring throughout the period.', 'easy', 1),

-- Q18: medium / L3 — Contracts settleable in stock or cash
(2, 'Earnings Per Share', 'Brookfield Corp. has a forward contract that permits settlement in either 50,000 common shares or $2,000,000 cash at Brookfield''s option. The average market price during 2025 was $45 per share. The controller excluded this contract from diluted EPS because cash settlement is more likely. Under ASC 260, what is the correct treatment?', '["Exclude the contract because management intends cash settlement", "Include at 44,444 shares using the treasury stock method", "Presume share settlement under ASC 260, adding 50,000 shares to the diluted EPS denominator", "Include only if share settlement is considered probable under ASC 450"]'::jsonb, 2, 'Under ASC 260-10-45-45, contracts that may be settled in stock or cash must use the more dilutive settlement method for diluted EPS computation. Share settlement adds 50,000 shares to the denominator, which is more dilutive than cash settlement. Management''s intent does not override this presumption. Choice A is incorrect because ASC 260 does not allow exclusion based solely on an intention to settle in cash.', 'medium', 3),

-- Q19: hard / L3 — Reverse treasury stock method for written put options
(2, 'Earnings Per Share', 'Dunmore Corp. has net income of $2,600,000 and 500,000 weighted-average shares (basic EPS = $5.20). Dunmore wrote put options requiring repurchase of 40,000 shares at $75 if exercised. The average market price during 2025 was $50. Under the reverse treasury stock method, what is diluted EPS?', '["$5.20, because the puts are excluded as antidilutive", "$5.00, because the puts add 20,000 net incremental shares", "$4.73, because 60,000 shares are added to the denominator", "$5.42, because the puts reduce the denominator by 20,000 shares"]'::jsonb, 1, 'Under ASC 260-10-45-35, written puts with exercise prices above market are dilutive. The reverse treasury stock method assumes repurchase of 40,000 shares at $75 ($3,000,000), then issuance of 60,000 shares at the $50 market price to fund the repurchase, creating 20,000 net incremental shares. Diluted EPS = $2,600,000 / 520,000 = $5.00. Choice A incorrectly excludes the puts; they are dilutive because exercise price ($75) exceeds market price ($50).', 'hard', 3),

-- Q20: easy / L2 — Simple basic EPS with mid-year stock issuance
(2, 'Earnings Per Share', 'Granville Corp. had 150,000 common shares outstanding on January 1, 2025. On October 1, 2025, Granville issued 30,000 additional shares. Net income for 2025 was $535,500 with no preferred stock outstanding. What is basic EPS?', '["$3.57", "$2.98", "$3.25", "$3.40"]'::jsonb, 3, 'Under ASC 260-10-45-10, shares issued during the period are weighted from the issuance date. Weighted-average = (150,000 x 9/12) + (180,000 x 3/12) = 112,500 + 45,000 = 157,500. Basic EPS = $535,500 / 157,500 = $3.40. Choice A ($3.57) incorrectly uses the beginning share count of 150,000 without weighting the October issuance.', 'easy', 2),

-- Q21: medium / L3 — Contingently issuable shares: conditions not met
(2, 'Earnings Per Share', 'Halford Corp. has 200,000 common shares and net income of $800,000 for 2025. An acquisition agreement requires issuance of 25,000 additional shares to former owners if Halford''s 2025 revenue exceeds $5,000,000. Actual 2025 revenue was $4,800,000. How are the contingent shares treated in basic and diluted EPS?', '["Excluded from both basic and diluted EPS because the revenue condition was not met as of year-end", "Excluded from basic but included in diluted EPS as potentially issuable shares", "Included in both basic and diluted EPS because the condition relates to the current period", "Included in basic EPS only because the revenue is close to the threshold"]'::jsonb, 0, 'Under ASC 260-10-45-48, contingently issuable shares are included in basic EPS only when all conditions are satisfied. Under ASC 260-10-45-51, for diluted EPS, shares are included if conditions would be met assuming the reporting date is the end of the contingency period. Since revenue of $4,800,000 fell short of $5,000,000, the shares are excluded from both computations. Choice B is incorrect because diluted EPS applies the same end-of-period test.', 'medium', 3),

-- Q22: easy / L1 — Definition of antidilutive security
(2, 'Earnings Per Share', 'Under ASC 260, what is an antidilutive security?', '["A security that reduces earnings available to common shareholders", "A security whose inclusion in diluted EPS would increase EPS or decrease loss per share", "A security that has been converted into common stock during the period", "A security excluded from basic EPS but always included in diluted EPS"]'::jsonb, 1, 'Under ASC 260-10-20, an antidilutive security is one whose inclusion in diluted EPS would increase the per-share amount or decrease the loss per share. Antidilutive securities must be excluded from diluted EPS. Choice A is incorrect because reducing earnings available to common shareholders describes the effect of preferred dividends on the basic EPS numerator, not antidilution.', 'easy', 1),

-- Q23: easy / L1 — Treasury stock method assumption
(2, 'Earnings Per Share', 'What does the treasury stock method assume when computing diluted EPS for stock options?', '["All options are exercised at average market price and proceeds retire debt", "All options are exercised at period-end and shares are added to the denominator", "Options are exercised at the beginning of the period and proceeds repurchase shares at the average market price", "Only in-the-money options are exercised at the closing price on the last day of the period"]'::jsonb, 2, 'Under ASC 260-10-45-22, the treasury stock method assumes options are exercised at the beginning of the period (or grant date if later) and the proceeds are used to repurchase common shares at the average market price. Only net incremental shares increase the denominator. Choice D is incorrect because the method uses average market price, not closing price, for the assumed repurchase.', 'easy', 1),

-- Q24: medium / L3 — NCI adjustment: net income attributable to parent for EPS
(2, 'Earnings Per Share', 'Westbrook Holdings owns 70% of Cedarvale Inc. In 2025, consolidated net income is $2,500,000, of which $500,000 is attributable to the noncontrolling interest. Westbrook has 400,000 weighted-average common shares and no preferred dividends. How does the noncontrolling interest affect basic EPS?', '["NCI income is included in the numerator, producing EPS of $6.25", "NCI income is deducted only from diluted EPS, not basic EPS", "NCI income does not affect EPS because it is a balance sheet item only", "NCI income of $500,000 is deducted from consolidated net income, producing EPS of $5.00"]'::jsonb, 3, 'Under ASC 260-10-45-11, the EPS numerator uses net income attributable to the parent entity, excluding the noncontrolling interest. Consolidated net income of $2,500,000 less NCI of $500,000 yields $2,000,000. EPS = $2,000,000 / 400,000 = $5.00. Choice A ($6.25) incorrectly includes the NCI share in the numerator, overstating earnings available to the parent''s common shareholders.', 'medium', 3),

-- Q25: hard / L4 — Ordering multiple dilutive securities for diluted EPS
(2, 'Earnings Per Share', 'Cascade Industries reports basic EPS of $6.00 based on earnings available to common of $1,200,000 and 200,000 weighted-average shares. Three potentially dilutive securities are outstanding all year: (1) stock options producing 5,000 incremental shares, (2) convertible preferred with per-share impact of $2.00 ($40,000 dividend / 20,000 conversion shares), and (3) convertible bonds with per-share impact of $7.00 ($56,000 after-tax interest / 8,000 conversion shares). Evaluate the proper inclusion order and determine which securities belong in diluted EPS.', '["Include options and preferred; exclude bonds because their $7.00 impact exceeds cumulative EPS after prior securities, making them antidilutive", "Include all three in order of per-share impact; diluted EPS is $5.56", "Include options and bonds; exclude preferred because its $2.00 impact is below the dilution threshold", "Include only options; both convertible securities exceed the $6.00 basic EPS threshold"]'::jsonb, 0, 'Under ASC 260-10-45-16, potentially dilutive securities are ranked by per-share impact (lowest first) and tested sequentially. Options ($0 impact) then preferred ($2.00) are included, reducing EPS to approximately $5.51. The bonds'' $7.00 per-share impact exceeds $5.51, so including them would increase EPS, making them antidilutive. Choice B incorrectly includes the antidilutive bonds, violating the sequential testing requirement of ASC 260.', 'hard', 4),

-- Q26: hard / L4 — Actual mid-year conversion: if-converted method application
(2, 'Earnings Per Share', 'Ridgeway Corp. began 2025 with 400,000 common shares and $2,000,000 face value 6% convertible bonds. On July 1, all bondholders converted into 80,000 common shares. The tax rate is 25%. The CFO computed diluted EPS using year-end shares of 480,000 with no numerator adjustment for pre-conversion interest. Evaluate the CFO''s methodology.', '["The CFO''s approach understates dilution by omitting the pre-conversion period interest add-back", "Once bonds actually convert, no further if-converted adjustment is necessary", "The CFO should apply the if-converted method assuming conversion at January 1, adding back after-tax interest for January through June and using 480,000 shares for the full year", "The CFO should use 440,000 weighted-average shares and add back twelve months of after-tax interest"]'::jsonb, 2, 'Under ASC 260-10-45-40, when convertible bonds are actually converted mid-period, diluted EPS applies the if-converted method from the beginning of the period. The numerator adds back six months of after-tax interest ($2,000,000 x 6% x 6/12 x 0.75 = $45,000), and the denominator uses 480,000 shares for the full year as if converted January 1. Choice B is incorrect because actual conversion does not eliminate the if-converted treatment for the pre-conversion portion.', 'hard', 4),

-- Q27: easy / L1 — Definition of the if-converted method
(2, 'Earnings Per Share', 'Under ASC 260, what is the if-converted method used for in computing diluted EPS?', '["A method that converts foreign currency EPS into the reporting currency", "A method that assumes convertible securities were converted into common stock at the beginning of the period", "A method that calculates the probability of conversion based on current market conditions", "A method that adjusts basic EPS only for conversions that actually occurred during the period"]'::jsonb, 1, 'Under ASC 260-10-45-40, the if-converted method assumes convertible bonds or preferred stock were converted at the beginning of the period (or issuance date if later). The numerator is adjusted by adding back interest or dividends, and the denominator includes conversion shares. Choice D is incorrect because the if-converted method is a hypothetical assumption applied regardless of whether actual conversion occurred.', 'easy', 1),

-- Q28: hard / L4 — Evaluate correct diluted EPS with options
(2, 'Earnings Per Share', 'Thornberry Inc. has net income of $1,800,000, 300,000 weighted-average shares, and no preferred stock (basic EPS = $6.00). The company has 20,000 stock options with an exercise price of $30 and average market price of $60, producing 10,000 incremental shares under the treasury stock method. The controller reports diluted EPS as $5.81. A reviewer claims diluted EPS should be $5.63 because all 20,000 option shares should be added to the denominator. Assess which figure is correct.', '["The reviewer is correct at $5.63; all shares underlying options must be added", "Neither figure is correct; diluted EPS is $6.00 because the options are antidilutive", "Neither is correct; exercise proceeds should be added to the numerator, yielding $5.87", "The controller is correct at $5.81; the treasury stock method nets 20,000 issued shares against 10,000 repurchased shares"]'::jsonb, 3, 'Under ASC 260-10-45-22, the treasury stock method assumes exercise proceeds of $600,000 (20,000 x $30) are used to repurchase 10,000 shares at the $60 average market price, producing 10,000 net incremental shares. Diluted EPS = $1,800,000 / 310,000 = $5.81. The reviewer''s error was adding all 20,000 shares without the treasury stock offset, violating ASC 260. Choice A ($5.63) overstates dilution by ignoring the assumed share repurchase.', 'hard', 4),

-- Q29: easy / L1 — Which securities create a complex capital structure
(2, 'Earnings Per Share', 'Which of the following securities, if outstanding, would cause an entity to have a complex capital structure under ASC 260?', '["Stock options granted to employees", "Nonconvertible preferred stock", "Treasury stock held by the company", "Accounts receivable sold with recourse"]'::jsonb, 0, 'Under ASC 260-10-15-3, a complex capital structure exists when an entity has potentially dilutive securities such as stock options, warrants, or convertible instruments. Stock options can be exercised for common shares, making them potential common stock. Choice B is incorrect because nonconvertible preferred stock has no potential to become common stock and does not create a complex capital structure.', 'easy', 1),

-- Q30: easy / L1 — EPS presentation location on financial statements
(2, 'Earnings Per Share', 'Under ASC 260, where must earnings per share be presented for a public company?', '["In the notes to the financial statements only", "In the management discussion and analysis section", "On the face of the income statement", "In a supplemental schedule accompanying the financial statements"]'::jsonb, 2, 'Under ASC 260-10-45-2, EPS must be presented on the face of the income statement for all periods for which an income statement is presented. This applies to both basic and diluted EPS for entities with complex capital structures. Choice A is incorrect because although additional EPS disclosures may appear in notes, the primary EPS figures must appear on the face of the income statement.', 'easy', 1)

;

COMMIT;