-- Migration: Question generation — FAR batch 36 (30 questions)
-- Date: 2026-03-01
-- Topic: Earnings Per Share
-- Difficulty: 9E / 15M / 6H
-- Bloom's: L1:8 / L2:9 / L3:8 / L4:5

BEGIN;

INSERT INTO questions (section_id, topic, stem, choices, correct_index, explanation, difficulty, cognitive_level)
VALUES

-- Q1: medium / L3 — Discontinued operations EPS presentation
(2, 'Earnings Per Share', 'Meridian Corp. reports income from continuing operations of $900,000 and a loss from discontinued operations (net of tax) of $150,000. The company has 300,000 weighted-average common shares outstanding with no preferred stock. Analyze how discontinued operations affect the presentation of EPS on the income statement.', '["EPS is reported only for net income at $2.50 per share", "EPS is reported only for income from continuing operations at $3.00 per share", "EPS must be reported separately for continuing operations and discontinued operations", "EPS for discontinued operations is disclosed only in the notes, not on the income statement face"]'::jsonb, 2, 'Under ASC 260-10-45-2, entities must present EPS for income from continuing operations and for net income on the face of the income statement. An entity reporting discontinued operations must also present per-share amounts for that line item either on the face of the income statement or in the notes. Choice A is incorrect because presenting EPS solely for net income omits the required separate disclosure for continuing operations, which could obscure the impact of discontinued items on core profitability.', 'medium', 3),

-- Q2: medium / L3 — Retroactive adjustment for stock split after balance sheet date
(2, 'Earnings Per Share', 'Waverly Industries had 400,000 weighted-average common shares during 2025 and reported basic EPS of $5.00. On February 15, 2026, before the 2025 financial statements were issued, the company declared a 2-for-1 stock split. Analyze the effect of this subsequent event on the 2025 EPS presentation.', '["The 2025 EPS remains $5.00 because the split occurred after year-end", "The 2025 EPS must be retroactively restated to $2.50 per share", "The 2025 EPS is reported as $5.00 with only a footnote disclosing the subsequent split", "The 2025 EPS is reported as $3.75 based on a partial-year adjustment for the split"]'::jsonb, 1, 'Under ASC 260-10-55-12, stock dividends and stock splits occurring after the balance sheet date but before financial statements are issued must be given retroactive effect in computing EPS for all periods presented. The weighted-average shares are adjusted to 800,000, reducing EPS to $2.50. Choice A is incorrect because ASC 260 specifically requires retroactive treatment of stock splits regardless of when they occur relative to year-end, ensuring comparability across periods.', 'medium', 3),

-- Q3: medium / L2 — If-converted method for convertible bonds (after-tax interest add-back)
(2, 'Earnings Per Share', 'Belmont Corp. has net income of $500,000 and 100,000 weighted-average common shares. The company has $200,000 face value of 5% convertible bonds, each $1,000 bond convertible into 40 common shares. The tax rate is 25%. Using the if-converted method, what is diluted EPS?', '["$4.63", "$4.72", "$5.00", "$4.70"]'::jsonb, 3, 'Under ASC 260-10-45-16, the if-converted method adds after-tax interest to the numerator and assumed converted shares to the denominator. After-tax interest is $200,000 x 5% x 0.75 = $7,500. The numerator becomes $507,500, and the denominator is 100,000 + 8,000 = 108,000, yielding $4.70. Choice B ($4.72) is incorrect because it adds the full pre-tax interest of $10,000 rather than the after-tax amount, overstating the numerator adjustment.', 'medium', 2),

-- Q4: hard / L3 — Two-class method for participating securities
(2, 'Earnings Per Share', 'Ironclad Holdings has net income of $1,200,000, 500,000 common shares, and 100,000 participating preferred shares that receive dividends equally with common stock on a per-share basis. The company declared $300,000 in total dividends. Under the two-class method required by ASC 260, analyze how undistributed earnings are allocated and determine basic EPS for common shareholders.', '["$2.00", "$2.40", "$1.80", "$1.50"]'::jsonb, 0, 'Under ASC 260-10-45-61A, entities with participating securities must use the two-class method to compute basic EPS. Distributed earnings ($300,000) and undistributed earnings ($900,000) are allocated between common and participating preferred shares based on their respective participation rights. Common shareholders receive $250,000 in dividends plus $750,000 (5/6) of undistributed earnings, yielding $1,000,000 / 500,000 = $2.00. Choice B ($2.40) is incorrect because it ignores the participating preferred shares'' claim on earnings, overstating common shareholders'' portion.', 'hard', 3),

-- Q5: easy / L1 — Complex capital structure definition
(2, 'Earnings Per Share', 'Under ASC 260, which of the following best describes a complex capital structure?', '["A capital structure with both common and preferred stock outstanding", "A capital structure that includes potentially dilutive securities such as options, warrants, or convertible instruments", "A capital structure where the entity has issued debt instruments of any kind", "A capital structure with multiple classes of common stock"]'::jsonb, 1, 'Under ASC 260-10-15-2, a complex capital structure exists when an entity has outstanding securities that could potentially dilute EPS, such as stock options, warrants, convertible debt, or convertible preferred stock. Choice A is incorrect because simply having preferred stock does not create a complex structure unless the preferred stock is convertible or otherwise potentially dilutive.', 'easy', 1),

-- Q6: hard / L4 — Written put options (reverse treasury stock method)
(2, 'Earnings Per Share', 'Greystone Corp. has entered a forward purchase contract obligating it to repurchase 20,000 shares of its own stock at $50 per share in 18 months. The average market price during the period is $40 per share. The company has net income of $600,000 and 200,000 weighted-average common shares. The CFO contends the contract should be excluded from diluted EPS because it is a derivative. Evaluate whether the CFO''s position is correct under ASC 260.', '["The CFO is correct; derivative instruments on an entity''s own stock are excluded from diluted EPS", "The contract is included using the if-converted method, adding 20,000 shares to the denominator", "The CFO is incorrect; the contract is dilutive and adds approximately 5,000 incremental shares using the reverse treasury stock method", "The contract is antidilutive because the company is repurchasing shares, which reduces the share count"]'::jsonb, 2, 'Under ASC 260-10-45-35, forward purchase contracts on an entity''s own shares are evaluated using the reverse treasury stock method. Because the $50 repurchase price exceeds the $40 market price, the entity effectively overpays. The $1,000,000 outflow could purchase 25,000 shares at market but acquires only 20,000, producing 5,000 incremental dilutive shares. Choice D is incorrect because although share repurchases typically reduce the denominator, the above-market price in a forward contract creates net dilution rather than accretion.', 'hard', 4),

-- Q7: medium / L2 — Shares issued in business combination weighted from acquisition date
(2, 'Earnings Per Share', 'Crestline Corp. had 300,000 common shares outstanding on January 1, 2025. On September 1, 2025, Crestline acquired Hilltop Inc. and issued 60,000 new common shares as consideration. What is the weighted-average number of common shares for 2025?', '["320,000 shares", "360,000 shares", "330,000 shares", "345,000 shares"]'::jsonb, 0, 'Under ASC 260-10-45-10, shares issued in a business combination are included in the weighted-average calculation from the acquisition date. The 60,000 shares issued September 1 are weighted for 4 months (4/12), adding 20,000 to the 300,000 base shares, totaling 320,000. Choice B (360,000) is incorrect because it includes the acquisition shares for the entire year rather than from the September 1 acquisition date.', 'medium', 2),

-- Q8: hard / L4 — Contingently issuable shares with earnings target currently met
(2, 'Earnings Per Share', 'Under a 2023 acquisition agreement, Vanguard Corp. must issue 40,000 additional shares to former Apex Inc. shareholders if Vanguard''s cumulative net income for 2023-2027 exceeds $8,000,000. Through December 31, 2025, cumulative net income is $9,100,000. Vanguard''s controller proposes excluding the shares from both basic and diluted EPS because the contingency period ends in 2027. Evaluate the controller''s position for the 2025 financial statements.', '["The controller is correct; shares are excluded until the contingency period ends in 2027", "The controller is partially correct; shares are excluded from basic EPS but included in diluted EPS only", "The controller is incorrect; shares should be included in basic EPS but excluded from diluted EPS", "The controller is incorrect; shares should be included in both basic and diluted EPS because the earnings target is currently satisfied"]'::jsonb, 3, 'Under ASC 260-10-45-48, contingently issuable shares are included in basic EPS when all necessary conditions are satisfied by the end of the reporting period. Since cumulative income ($9,100,000) exceeds the $8,000,000 target at December 31, 2025, the 40,000 shares are included in basic EPS. Under ASC 260-10-45-50, the same shares are included in diluted EPS because the condition would be met if year-end were the contingency end date. Choice A is incorrect because the contingency period''s end date is irrelevant when the earnings conditions are already satisfied at the reporting date.', 'hard', 4),

-- Q9: medium / L3 — Share buyback effect on basic EPS
(2, 'Earnings Per Share', 'Stonebridge Corp. had 500,000 shares outstanding at the start of 2025 and repurchased 60,000 shares as treasury stock on July 1, 2025. Net income was $1,500,000 with no preferred dividends. The CEO states the buyback increased EPS. Analyze whether the CEO''s claim is valid and determine basic EPS.', '["$3.00; the buyback has no effect on EPS because the shares were outstanding for part of the year", "$3.19; the buyback reduces the weighted-average shares, thereby increasing EPS", "$3.41; the repurchased shares are excluded from the weighted-average for the entire year", "$3.00; treasury shares are still counted in the weighted-average denominator"]'::jsonb, 1, 'Under ASC 260-10-45-10, shares repurchased reduce the weighted-average from the repurchase date. The 60,000 shares repurchased July 1 reduce the denominator by 30,000 (60,000 x 6/12), yielding 470,000 weighted-average shares and EPS of $3.19. The CEO''s claim is valid. Choice C ($3.41) is incorrect because it excludes the repurchased shares for the entire year rather than weighting them only for the period they were outstanding before repurchase.', 'medium', 3),

-- Q10: medium / L2 — Restricted stock units in diluted EPS (treasury stock method)
(2, 'Earnings Per Share', 'Hawthorne Inc. has net income of $840,000, 200,000 weighted-average common shares, and 12,000 unvested restricted stock units (RSUs). The average unrecognized compensation cost for the RSUs is $180,000, and the average market price of the stock is $60 per share. Using the treasury stock method, how many incremental shares from the RSUs are included in diluted EPS?', '["12,000 shares", "3,000 shares", "9,000 shares", "6,000 shares"]'::jsonb, 2, 'Under ASC 260-10-45-28, unvested RSUs are treated as options under the treasury stock method. The assumed proceeds equal the average unrecognized compensation cost ($180,000). Dividing by the $60 average market price yields 3,000 shares assumed repurchased from the treasury. The incremental shares are 12,000 - 3,000 = 9,000. Choice A (12,000) is incorrect because it includes all RSUs without reducing for the assumed treasury share repurchase using unrecognized compensation cost proceeds.', 'medium', 2),

-- Q11: medium / L3 — Income from continuing operations as control number for dilution testing
(2, 'Earnings Per Share', 'Fenwick Corp. reports income from continuing operations of $2.00 per diluted share. Convertible bonds would increase diluted EPS from continuing operations to $2.10 per share but decrease diluted EPS for net income (which includes a discontinued operations gain). The controller includes the bonds in diluted EPS. Analyze whether this treatment is correct under ASC 260.', '["The controller is incorrect; the bonds are antidilutive because they increase diluted EPS from continuing operations, which is the control number", "The controller is correct; net income is the control number for dilutive and antidilutive testing", "The controller is correct; any security that reduces net income per share must be included", "The controller is incorrect; both continuing operations and net income must show dilution for inclusion"]'::jsonb, 0, 'Under ASC 260-10-45-19, income from continuing operations is the control number for determining whether a security is dilutive or antidilutive. A security that increases EPS from continuing operations is antidilutive and must be excluded from the diluted EPS computation for all line items, even if it would reduce EPS for net income. Choice B is incorrect because ASC 260 explicitly designates income from continuing operations, not net income, as the benchmark for the dilution test.', 'medium', 3),

-- Q12: easy / L2 — Reverse stock split retroactive adjustment
(2, 'Earnings Per Share', 'Redwood Corp. had 600,000 shares outstanding on January 1, 2025. On April 1, 2025, the company executed a 1-for-3 reverse stock split. What is the weighted-average number of shares for 2025?', '["400,000 shares", "350,000 shares", "600,000 shares", "200,000 shares"]'::jsonb, 3, 'Under ASC 260-10-55-12, reverse stock splits are applied retroactively to all periods presented, just like regular stock splits and stock dividends. The 1-for-3 reverse split reduces shares to 200,000 (600,000 / 3) for the entire year, not just from the split date forward. Choice A (400,000) is incorrect because it improperly weights the pre-split and post-split shares rather than applying the required retroactive treatment.', 'easy', 2),

-- Q13: medium / L2 — Actual conversion of preferred stock mid-year (basic EPS)
(2, 'Earnings Per Share', 'Oakmont Corp. had 200,000 common shares on January 1, 2025, and net income of $880,000. On July 1, holders of 2,000 shares of $100 par, 10% cumulative convertible preferred stock convert into 20,000 common shares. What is basic EPS for 2025?', '["$4.40", "$4.14", "$4.10", "$3.95"]'::jsonb, 1, 'Under ASC 260-10-45-10 and 45-12, when convertible preferred stock is actually converted, preferred dividends are deducted from the numerator only for the pre-conversion period. The half-year deduction is 2,000 x $100 x 10% x 6/12 = $10,000. The denominator includes converted shares from July 1: 200,000 + (20,000 x 6/12) = 210,000. Basic EPS = $870,000 / 210,000 = $4.14. Choice C ($4.10) is incorrect because it deducts a full year of preferred dividends ($20,000) rather than only the six-month pre-conversion portion.', 'medium', 2),

-- Q14: easy / L1 — Dual EPS presentation requirement
(2, 'Earnings Per Share', 'Under U.S. GAAP, which entities are required to present both basic and diluted EPS on the face of the income statement?', '["Public entities with common stock or potential common stock traded in a public market", "All entities that prepare financial statements under U.S. GAAP", "Only entities with a complex capital structure", "Only SEC registrants filing 10-K annual reports"]'::jsonb, 0, 'Under ASC 260-10-15-2, EPS presentation is required for entities whose common stock or potential common stock is traded in a public market, including stock exchanges and over-the-counter markets. Both basic and diluted EPS must appear on the face of the income statement. Choice B is incorrect because private companies are not required to present EPS, though they may voluntarily do so following ASC 260 if they choose.', 'easy', 1),

-- Q15: hard / L4 — Forward purchase contract (reverse treasury stock method)
(2, 'Earnings Per Share', 'Bridgewater Corp. has entered a forward purchase contract obligating it to repurchase 30,000 shares of its own stock at $50 per share in 18 months. The average market price during the reporting period is $40 per share. The treasury team argues the contract should be excluded from diluted EPS because it is a derivative rather than a traditional convertible security. Evaluate the proper treatment under ASC 260.', '["The treasury team is correct; derivative instruments are excluded from the diluted EPS computation entirely", "The contract is included using the if-converted method, adding all 30,000 shares to the denominator", "The contract is dilutive and adds approximately 7,500 incremental shares using the reverse treasury stock method", "The contract is antidilutive because the forward price exceeds the market price and should be excluded"]'::jsonb, 2, 'Under ASC 260-10-45-35, forward purchase contracts on an entity''s own shares are evaluated using the reverse treasury stock method. Because the $50 repurchase price exceeds the $40 market price, the entity effectively overpays. The $1,500,000 outflow could purchase 37,500 shares at market ($40) but acquires only 30,000 shares, producing 7,500 incremental dilutive shares. Choice D is incorrect because for repurchase contracts, dilution occurs when the contract price exceeds market price, which is the opposite of the call option test.', 'hard', 4),

-- Q16: medium / L2 — Warrants treasury stock method calculation
(2, 'Earnings Per Share', 'Lakewood Industries has 200,000 weighted-average common shares, net income of $660,000, and no preferred stock. The company has 12,000 warrants outstanding with an exercise price of $25 per share. The average market price during 2025 was $50 per share. What is diluted EPS?', '["$3.11", "$3.30", "$4.53", "$3.20"]'::jsonb, 3, 'Under ASC 260-10-45-22, warrants are evaluated using the treasury stock method. The 12,000 warrants at $25 generate assumed proceeds of $300,000, which would repurchase 6,000 shares at the $50 average market price. The net incremental 6,000 shares increase the denominator to 206,000, yielding diluted EPS of $660,000 / 206,000 = $3.20. Choice A ($3.11) is incorrect because it adds all 12,000 warrant shares to the denominator without accounting for the assumed share repurchase with exercise proceeds.', 'medium', 2),

-- Q17: easy / L1 — Definition of weighted-average shares outstanding
(2, 'Earnings Per Share', 'What does the weighted-average number of common shares outstanding represent in an EPS calculation?', '["The total number of shares authorized by the corporate charter", "The number of shares outstanding adjusted for the time period each share was outstanding during the year", "The number of shares outstanding at the end of the reporting period", "The total shares issued minus shares held in treasury at year-end"]'::jsonb, 1, 'Under ASC 260-10-45-10, the weighted-average number of common shares outstanding reflects shares adjusted for the fraction of the period they were outstanding. Shares issued or repurchased mid-year receive proportional weighting rather than full-year treatment. Choice C is incorrect because using only the ending balance ignores shares issued or repurchased during the period, potentially overstating or understating the denominator.', 'easy', 1),

-- Q18: easy / L1 — Antidilutive securities exclusion rule
(2, 'Earnings Per Share', 'Under ASC 260, what is the treatment of antidilutive securities when computing diluted EPS?', '["They are included in diluted EPS to present the most conservative scenario", "They reduce the denominator to reflect potential share reductions", "They are excluded from the diluted EPS computation entirely", "They are included in basic EPS but excluded from diluted EPS"]'::jsonb, 2, 'Under ASC 260-10-45-17, securities whose inclusion would increase EPS or decrease the loss per share are antidilutive and must be excluded from the diluted EPS computation. Diluted EPS must always be less than or equal to basic EPS. Choice A is incorrect because including antidilutive securities would overstate dilution and misrepresent the potential impact on common shareholders'' earnings.', 'easy', 1),

-- Q19: medium / L3 — Rights issue bonus element adjustment
(2, 'Earnings Per Share', 'Prescott Corp. had 400,000 shares outstanding and completed a rights offering on March 1, 2025, allowing shareholders to purchase one new share for every four held at $20 per share. The market price was $36 before the offering. The theoretical ex-rights price is $32.80. Analyze how the bonus element affects the weighted-average shares for prior periods.', '["Prior-period weighted-average shares are increased by an adjustment factor of approximately 1.10 to reflect the bonus element", "Prior-period weighted-average shares remain unchanged because the rights issue occurred in the current year", "Prior-period weighted-average shares are decreased to reflect the dilutive effect of the new shares", "Prior-period weighted-average shares are adjusted only if the rights were exercised below fair value by more than 20%"]'::jsonb, 0, 'Under ASC 260-10-55-20, when a rights issue contains a bonus element (exercise price below market), prior-period EPS must be retroactively adjusted using an adjustment factor equal to the fair value per share before the rights exercise divided by the theoretical ex-rights price ($36 / $32.80 = 1.0976, approximately 1.10). This ensures comparability across periods. Choice B is incorrect because ASC 260 requires retroactive adjustment of all prior periods to account for the bonus element, similar to stock dividend treatment.', 'medium', 3),

-- Q20: medium / L3 — Year-to-date vs quarterly EPS (sum of quarters does not equal annual)
(2, 'Earnings Per Share', 'Edgewater Corp. reports quarterly EPS as follows: Q1 $1.20, Q2 $0.80, Q3 $1.50, and Q4 $1.00. An analyst sums the quarterly figures to arrive at annual EPS of $4.50. Analyze why this approach may produce an incorrect annual EPS figure under ASC 260.', '["The approach is correct because annual EPS equals the sum of quarterly EPS amounts", "The approach is incorrect because annual EPS must be calculated using only Q4 shares outstanding", "The approach is incorrect because each quarter requires a different tax rate assumption", "The approach is incorrect because each quarter''s weighted-average shares may differ, making the sum of quarterly EPS figures unequal to annual EPS"]'::jsonb, 3, 'Under ASC 260-10-45-10 and ASC 270-10-50-1, annual EPS is computed using the annual weighted-average shares, which may differ from any individual quarter''s weighted-average. Because share issuances or repurchases during the year change quarterly denominators, summing four independently computed quarterly EPS figures does not necessarily equal the annual EPS computed from annual totals. Choice A is incorrect because differences in quarterly weighted-average shares make the arithmetic sum of quarterly EPS an unreliable proxy for annual EPS.', 'medium', 3),

-- Q21: medium / L3 — Contingently issuable shares (earnings condition not met at interim date)
(2, 'Earnings Per Share', 'Aldrich Corp. agreed to issue 50,000 additional shares to sellers if a newly acquired subsidiary achieves $3,000,000 in revenue during 2025. Through September 30, 2025, subsidiary revenue totals $1,800,000. The CFO is preparing the third-quarter 10-Q. Analyze how these shares should be treated in the September 30 diluted EPS computation.', '["Include 50,000 shares because the revenue target may still be met by year-end", "Exclude from diluted EPS because the revenue condition is not satisfied as of September 30", "Include 37,500 shares (50,000 x 9/12) to reflect the partial-year period", "Include 50,000 shares in both basic and diluted EPS as a conservative presentation"]'::jsonb, 1, 'Under ASC 260-10-45-50, contingently issuable shares are included in diluted EPS only if the conditions would be satisfied assuming the end of the reporting period were the end of the contingency period. Since subsidiary revenue of $1,800,000 at September 30 does not meet the $3,000,000 threshold, the 50,000 shares are excluded. Choice A is incorrect because ASC 260 does not consider the probability of future achievement; it tests conditions only as of the current reporting date.', 'medium', 3),

-- Q22: easy / L1 — EPS note disclosure requirements
(2, 'Earnings Per Share', 'Under ASC 260, which of the following disclosures is required in the notes to financial statements regarding EPS?', '["The market price of common stock at each quarter-end", "Projected EPS for the next fiscal year", "The names of all shareholders holding more than 5% of common stock", "A reconciliation of the numerators and denominators used in basic and diluted EPS computations"]'::jsonb, 3, 'Under ASC 260-10-50-1, entities must disclose a reconciliation of the numerators and denominators of basic and diluted EPS, including the individual effect of each class of securities on the computation. This allows financial statement users to understand which securities drive dilution. Choice A is incorrect because market price disclosure relates to SEC periodic reporting requirements, not to the EPS computation disclosures mandated by ASC 260.', 'easy', 1),

-- Q23: hard / L4 — Sequencing multiple dilutive securities (ranking by per-share impact)
(2, 'Earnings Per Share', 'Silverton Corp. has basic EPS of $3.00 from net income of $900,000 and 300,000 shares. Three potentially dilutive securities exist: (1) stock options adding 15,000 incremental shares, (2) 6% convertible bonds adding $18,000 after-tax interest and 20,000 shares (per-share impact $0.90), and (3) 8% convertible preferred adding $96,000 dividends and 25,000 shares (per-share impact $3.84). Evaluate the order of inclusion and determine which securities are included in diluted EPS.', '["Options and convertible bonds are included; convertible preferred is excluded as antidilutive, yielding diluted EPS of $2.74", "All three securities are included, yielding diluted EPS of $2.82", "Only stock options are included because the per-share impact of both convertible securities exceeds basic EPS", "Convertible bonds are tested first because they have the highest dollar adjustment to the numerator"]'::jsonb, 0, 'Under ASC 260-10-45-21, potentially dilutive securities must be ranked by per-share dilutive impact from most to least dilutive and included sequentially. Options ($0.00) and bonds ($0.90) are included because each incrementally reduces EPS. When the preferred stock ($3.84 per-share impact) is tested, diluted EPS would increase from $2.74 to $2.82, making it antidilutive. Choice B is incorrect because the preferred stock''s high per-share impact ($3.84) causes it to increase EPS when added after the other securities, triggering the antidilution prohibition under ASC 260-10-45-17.', 'hard', 4),

-- Q24: medium / L2 — Actual bond conversion mid-year (basic EPS calculation)
(2, 'Earnings Per Share', 'Hartwell Corp. had 250,000 common shares outstanding on January 1, 2025, and net income of $750,000 with no preferred stock. On April 1, 2025, holders of $400,000 face value, 6% convertible bonds convert into 16,000 common shares. What is basic EPS for 2025?', '["$3.00", "$2.82", "$2.86", "$2.84"]'::jsonb, 2, 'Under ASC 260-10-45-10, when convertible bonds are actually converted, the resulting common shares are included in the weighted-average from the conversion date. The 16,000 shares from April 1 are weighted 9/12 (12,000 shares), producing a denominator of 262,000. The numerator is net income of $750,000 with no adjustment because pre-conversion interest expense is already reflected in net income. Choice B ($2.82) is incorrect because it weights the converted shares for the full year rather than from the April 1 conversion date.', 'medium', 2),

-- Q25: medium / L2 — Treasury stock repurchase and reissuance weighted-average calculation
(2, 'Earnings Per Share', 'Marlowe Corp. had 180,000 common shares outstanding on January 1, 2025. On May 1, it repurchased 24,000 shares as treasury stock. On November 1, it reissued 12,000 of those treasury shares. What is the weighted-average number of common shares for 2025?', '["168,000 shares", "166,000 shares", "180,000 shares", "170,000 shares"]'::jsonb, 1, 'Under ASC 260-10-45-10, treasury stock transactions change the weighted-average from the transaction dates. The calculation is: 180,000 x 4/12 = 60,000; 156,000 x 6/12 = 78,000; 168,000 x 2/12 = 28,000; total = 166,000 weighted-average shares. Choice A (168,000) is incorrect because it uses only the year-end balance without weighting for the periods when different numbers of shares were outstanding during the year.', 'medium', 2),

-- Q26: easy / L1 — Relationship between basic and diluted EPS
(2, 'Earnings Per Share', 'Under ASC 260, what is the relationship between basic EPS and diluted EPS?', '["Diluted EPS must always be less than or equal to basic EPS", "Diluted EPS must always be greater than basic EPS", "Diluted EPS may be either greater than or less than basic EPS", "Diluted EPS equals basic EPS only when the entity has a simple capital structure"]'::jsonb, 0, 'Under ASC 260-10-45-17, diluted EPS incorporates the effect of all dilutive potential common shares, which can only reduce or maintain EPS. Securities that would increase EPS are antidilutive and must be excluded. Therefore, diluted EPS can never exceed basic EPS. Choice D is incorrect because diluted EPS can also equal basic EPS when an entity has a complex capital structure if all potentially dilutive securities happen to be antidilutive in that period.', 'easy', 1),

-- Q27: easy / L1 — Which entities must present EPS
(2, 'Earnings Per Share', 'Which of the following entities is required to present EPS on its income statement under U.S. GAAP?', '["A privately held limited liability company", "A not-for-profit organization", "A publicly traded corporation listed on a stock exchange", "A private partnership filing audited financial statements"]'::jsonb, 2, 'Under ASC 260-10-15-2, EPS presentation is required only for entities with publicly traded common stock or potential common stock. Privately held entities, not-for-profit organizations, and partnerships are not required to present EPS, though they may voluntarily do so. Choice A is incorrect because private entities have no public market for their equity and therefore fall outside the scope of ASC 260''s mandatory EPS presentation requirements.', 'easy', 1),

-- Q28: medium / L2 — RSU vesting schedule and incremental shares (different from Q10)
(2, 'Earnings Per Share', 'Ferndale Corp. has net income of $1,050,000 and 300,000 weighted-average common shares. The company granted 18,000 restricted stock units with a 3-year cliff vest. At December 31, 2025, the average unrecognized compensation cost is $540,000 and the average market price is $60 per share. What is the incremental share effect of the RSUs on diluted EPS?', '["18,000 shares", "6,000 shares", "12,000 shares", "9,000 shares"]'::jsonb, 3, 'Under ASC 260-10-45-28, unvested RSUs use the treasury stock method with assumed proceeds equal to the average unrecognized compensation cost ($540,000). Dividing by the $60 average market price yields 9,000 shares assumed repurchased, producing 9,000 incremental shares (18,000 - 9,000). Choice B (6,000 shares) is incorrect because it divides the unrecognized cost by the $45 grant-date fair value rather than the $60 average market price, which the treasury stock method requires for the share repurchase assumption.', 'medium', 2),

-- Q29: hard / L4 — Loss from continuing operations makes all securities antidilutive
(2, 'Earnings Per Share', 'Blackstone Manufacturing reports a loss from continuing operations of $400,000 and income from discontinued operations (net of tax) of $600,000, yielding net income of $200,000. The company has 100,000 weighted-average shares and 10,000 dilutive stock options that produce 5,000 incremental shares under the treasury stock method. The controller includes the options in diluted EPS for all line items. Evaluate whether this treatment is appropriate.', '["The controller is correct because the options reduce net income per share from $2.00 to $1.90", "The controller is incorrect; the options are antidilutive because including them reduces the loss per share from continuing operations", "The controller is correct because options are always dilutive when the exercise price is below the market price", "The controller is incorrect; stock options must be excluded whenever discontinued operations are present on the income statement"]'::jsonb, 1, 'Under ASC 260-10-45-19, income (loss) from continuing operations is the control number for determining dilution. Although net income is positive ($200,000), the entity has a loss from continuing operations (-$400,000). Including the 5,000 incremental shares would reduce the loss per share from -$4.00 to -$3.81, which is antidilutive. All potentially dilutive securities must be excluded for every EPS line item. Choice A is incorrect because it uses net income rather than continuing operations as the control number, violating ASC 260''s antidilution framework.', 'hard', 4),

-- Q30: easy / L1 — Definition of potentially dilutive securities
(2, 'Earnings Per Share', 'What are potentially dilutive securities in the context of EPS computations?', '["Securities that could reduce EPS if exercised or converted into common stock", "Securities that increase the numerator in the EPS calculation", "Securities that are reported as liabilities on the balance sheet", "Securities issued exclusively to employees as compensation"]'::jsonb, 0, 'Under ASC 260-10-20, potentially dilutive securities are instruments such as stock options, warrants, convertible bonds, and convertible preferred stock that could result in the issuance of additional common shares, thereby reducing EPS. They are evaluated for inclusion in diluted EPS using the treasury stock or if-converted methods. Choice D is incorrect because while employee stock options are one type of potentially dilutive security, the category also encompasses warrants, convertible instruments, and other contracts regardless of whether they relate to compensation.', 'easy', 1)
;

COMMIT;
