-- Migration: Question generation — FAR batch 44 (30 questions)
-- Date: 2026-03-01
-- Topic: Earnings Per Share
-- Difficulty: 9E / 15M / 6H
-- Bloom's: L1:8 / L2:9 / L3:8 / L4:5

BEGIN;

INSERT INTO questions (section_id, topic, stem, choices, correct_index, explanation, difficulty, cognitive_level)
VALUES

-- Q1: easy / L2 — Shares issued for services affect weighted-average from issuance date
(2, 'Earnings Per Share', 'On September 1, 2025, Briarwood Consulting Inc. issued 6,000 shares of common stock to an attorney in exchange for legal services. Briarwood had 100,000 shares outstanding on January 1 and no other share activity during the year. What is the weighted-average number of common shares outstanding for 2025?', '["102,000", "106,000", "100,000", "104,000"]'::jsonb, 0, 'Under ASC 260-10-45-10, shares issued during the period are weighted from the date of issuance. The 6,000 shares were outstanding for 4 months (September through December), contributing 2,000 to the weighted average (6,000 x 4/12). Adding this to 100,000 yields 102,000. Choice B (106,000) incorrectly includes the shares for the full year rather than weighting from the issuance date.', 'easy', 2),

-- Q2: medium / L2 — RSUs with service-only vesting in diluted EPS
(2, 'Earnings Per Share', 'Whitfield Technologies has 200,000 weighted-average common shares, net income of $1,000,000, and 12,000 unvested restricted stock units (RSUs) that vest in three years based solely on continued employment. The average market price of Whitfield''s stock is $50. Under ASC 260, how are the unvested RSUs treated in diluted EPS?', '["Excluded because the vesting condition has not yet been met", "Included as 12,000 incremental shares in the denominator", "Included using the treasury stock method based on average market price", "Included only if the RSUs would have been dilutive using the if-converted method"]'::jsonb, 1, 'Under ASC 260-10-45-48, unvested RSUs with service-only vesting conditions are treated as issued shares for diluted EPS because continued employment is presumed satisfied. The full 12,000 shares are added to the denominator. Choice A is incorrect because time-based vesting conditions are assumed met for diluted EPS purposes — exclusion applies only when performance conditions are not satisfied at period end.', 'medium', 2),

-- Q3: medium / L2 — If-converted method for convertible preferred stock
(2, 'Earnings Per Share', 'Lakewood Industries reports net income of $750,000 with 200,000 weighted-average common shares. The company has 5,000 shares of $100 par, 7% convertible preferred stock, each convertible into 4 common shares. Basic EPS is $3.575 after deducting preferred dividends. Under the if-converted method, what is diluted EPS?', '["$3.25 (forgot to add back preferred dividends to numerator)", "$3.575 (same as basic — did not apply conversion)", "$3.41 (correctly applied the if-converted method)", "$3.33 (used incorrect conversion ratio of 5 shares per preferred)"]'::jsonb, 2, 'Under ASC 260-10-45-40, the if-converted method adds back preferred dividends ($35,000) to the numerator and adds conversion shares (5,000 x 4 = 20,000) to the denominator. Diluted EPS = $750,000 / 220,000 = $3.41. Since $3.41 < $3.575 (basic), the security is dilutive. Choice A ($3.25) incorrectly fails to add back the preferred dividends, double-counting the deduction.', 'medium', 2),

-- Q4: easy / L1 — Definition of a complex capital structure
(2, 'Earnings Per Share', 'Under ASC 260, what defines a complex capital structure?', '["A structure with more than one class of common stock outstanding", "A structure with both current and long-term debt obligations", "A structure with total assets exceeding $500 million", "A structure that includes securities potentially convertible into common stock"]'::jsonb, 3, 'Under ASC 260-10-15-2, a complex capital structure exists when an entity has outstanding securities that could potentially dilute EPS, such as convertible bonds, convertible preferred stock, options, or warrants. Choice A is incorrect because multiple classes of common stock alone do not create a complex structure — it is the existence of potentially dilutive securities that matters.', 'easy', 1),

-- Q5: easy / L1 — Nonpublic entity EPS exemption
(2, 'Earnings Per Share', 'Which type of entity is exempt from presenting earnings per share under ASC 260?', '["A nonpublic entity with no publicly traded securities", "A publicly traded entity with a simple capital structure", "An entity reporting under IFRS rather than U.S. GAAP", "A publicly traded entity reporting net losses for the period"]'::jsonb, 0, 'Under ASC 260-10-15-3, only entities with publicly traded common stock or potential common stock are required to present EPS. Nonpublic entities are exempt from EPS disclosure. Choice B is incorrect because all public entities must present EPS regardless of capital structure complexity — simple-structure entities report basic and diluted EPS at the same amount.', 'easy', 1),

-- Q6: hard / L4 — Two-class method evaluation for participating preferred
(2, 'Earnings Per Share', 'Hartwell Corp. reports net income of $2,000,000 with 500,000 weighted-average common shares. Hartwell has 50,000 shares of participating preferred stock entitled to share equally in dividends on a per-share basis after receiving a $4 per-share preference. Total dividends declared are $800,000. The CFO calculates basic EPS by deducting only the $200,000 preference amount from net income, yielding $3.60. Evaluate whether this approach complies with ASC 260.', '["The approach is correct because preferred dividends are limited to the stated preference", "The approach violates ASC 260 because the two-class method must allocate undistributed earnings to both common and participating preferred shares", "The approach violates ASC 260 because participating preferred shares should be included in the denominator", "The approach is correct because the participation feature applies only to declared dividends exceeding the preference"]'::jsonb, 1, 'Under ASC 260-10-45-60A, when participating securities exist, the two-class method requires allocating both distributed and undistributed earnings between common stock and the participating security. The CFO erred by deducting only the preference, ignoring the allocation of $1,200,000 in undistributed earnings. Choice D is incorrect because the participation feature requires allocation of all undistributed earnings, not just declared excess dividends.', 'hard', 4),

-- Q7: hard / L4 — Evaluate anti-dilution ordering with three securities
(2, 'Earnings Per Share', 'Pennington Corp. has basic EPS of $5.00. Three potentially dilutive securities exist: (1) stock options adding 8,000 incremental shares with no numerator effect; (2) $600,000 of 8% convertible bonds (tax rate 25%) converting to 15,000 shares; (3) $200,000 of 4% convertible preferred adding 6,000 shares. The controller includes all three simultaneously and reports diluted EPS of $4.52. Evaluate whether this approach complies with ASC 260.', '["The approach is correct because all three securities reduce EPS below basic", "The approach is incorrect because the preferred stock should be entirely excluded", "The approach is incorrect because securities must be ranked by per-share impact and tested sequentially from most dilutive to least dilutive", "The approach is incorrect because only one dilutive security may be included per period"]'::jsonb, 2, 'Under ASC 260-10-45-21, potentially dilutive securities must be tested individually in order from most dilutive (lowest per-share impact) to least dilutive. Options with zero numerator impact go first, followed by each convertible ranked by per-share earnings effect. Simultaneous inclusion may mask an antidilutive security. Choice A is incorrect because a security that appears dilutive in isolation may become antidilutive when tested after more dilutive securities.', 'hard', 4),

-- Q8: medium / L2 — Reverse stock split retroactive adjustment
(2, 'Earnings Per Share', 'Alderton Manufacturing had 300,000 common shares outstanding on January 1, 2025. On August 1, 2025, Alderton executed a 1-for-3 reverse stock split. No other share activity occurred during the year. What is the weighted-average number of shares outstanding for 2025?', '["200,000 (weighted pre-split and post-split shares)", "300,000 (ignored the reverse split entirely)", "183,333 (reversed the weighting periods)", "100,000 (retroactively applied the reverse split)"]'::jsonb, 3, 'Under ASC 260-10-55-12, stock splits and reverse stock splits are applied retroactively to all periods presented. The 1-for-3 reverse split reduces shares to 100,000, applied as if it occurred at the beginning of the year. Choice A (200,000) is incorrect because it attempts to weight pre-split and post-split shares, but ASC 260 requires full retroactive treatment with no weighting.', 'medium', 2),

-- Q9: hard / L3 — Post-period stock split retroactive EPS restatement
(2, 'Earnings Per Share', 'Clearwater Holdings reports basic EPS of $4.00 for the year ended December 31, 2025, based on net income of $2,000,000 and 500,000 weighted-average shares. On February 15, 2026, before the financial statements are issued, the board authorizes a 2-for-1 stock split. Analyze how this post-period stock split affects the EPS reported in the 2025 financial statements.', '["Basic EPS must be restated to $2.00 using 1,000,000 shares because post-period splits are retroactively applied before issuance", "Basic EPS remains $4.00 because the split occurred after year-end and is a subsequent event requiring disclosure only", "Basic EPS is reported as $4.00 with a pro forma EPS of $2.00 in supplemental information", "Basic EPS is restated only if the split is effective before the SEC filing date"]'::jsonb, 0, 'Under ASC 260-10-55-12, stock splits occurring after the balance sheet date but before financial statements are issued must be retroactively reflected in EPS. The weighted-average becomes 1,000,000 shares (500,000 x 2), yielding restated basic EPS of $2.00. Choice B is incorrect because ASC 260 specifically requires retroactive adjustment, unlike typical subsequent events that warrant disclosure only.', 'hard', 3),

-- Q10: easy / L1 — Definition of participating securities
(2, 'Earnings Per Share', 'Under ASC 260, what is a participating security?', '["A security that can be converted into common stock at the holder''s option", "A security that may participate in undistributed earnings with common stock", "A security that carries voting rights equal to common stock", "A security that is traded on a public exchange alongside common stock"]'::jsonb, 1, 'Under ASC 260-10-20, a participating security may participate in undistributed earnings with common stock, whether or not that participation is contingent on conditions being met. This includes certain preferred stock with dividend participation rights. Choice A describes a convertible security, not a participating security — conversion rights and participation rights are distinct concepts under ASC 260.', 'easy', 1),

-- Q11: hard / L4 — Evaluate convertible instrument inclusion ordering by per-share impact
(2, 'Earnings Per Share', 'Riverside Corp. has basic EPS of $3.00 with net income of $900,000 and 300,000 shares. Two convertibles exist: (1) $500,000 face value, 10% convertible bonds (tax rate 25%, each $1,000 bond converts to 40 shares); (2) 10,000 shares of convertible preferred with $20,000 annual dividends, each converting into 3 common shares. The treasurer includes the bonds first because of their larger face value. Evaluate whether this ordering is correct.', '["Correct, because higher face value instruments should be tested first in the dilution sequence", "Correct, because debt securities always precede equity securities in dilution testing", "Incorrect, because the preferred''s per-share impact ($0.67) is lower than the bonds'' ($1.88), requiring it first", "Incorrect, because convertible preferred must always be excluded from diluted EPS computations"]'::jsonb, 2, 'Under ASC 260-10-45-21, dilutive securities are ranked by per-share impact from lowest to highest. The preferred''s impact is $0.67 ($20,000 / 30,000 shares), lower than the bonds'' $1.88 ($37,500 / 20,000 shares), making the preferred more dilutive and requiring first inclusion. Choice B is incorrect because ASC 260 does not prescribe a debt-before-equity order — ranking is based solely on per-share earnings impact.', 'hard', 4),

-- Q12: medium / L2 — Discontinued operations separate EPS disclosure
(2, 'Earnings Per Share', 'Glenworth Corp. reports income from continuing operations of $800,000 and a loss from discontinued operations of $200,000 for the year ended December 31, 2025. Glenworth has 250,000 weighted-average common shares and no preferred stock. Under ASC 260, what EPS amounts must Glenworth present on the face of the income statement?', '["Only a single basic EPS of $2.40 based on net income", "Basic EPS of $3.20 from continuing operations and basic EPS of ($0.80) from discontinued operations", "Basic EPS of $3.20 from continuing operations only, with discontinued EPS in the notes", "Basic EPS of $2.40 from net income with a memo disclosure of the discontinued operations effect"]'::jsonb, 1, 'Under ASC 260-10-45-3, entities must present EPS for income from continuing operations and for net income on the face of the income statement. EPS for discontinued operations must also be presented on the face or in the notes. Choice A is incorrect because a single net income EPS fails to separately disclose the continuing operations component required by ASC 260.', 'medium', 2),

-- Q13: medium / L3 — After-tax interest add-back error for convertible bonds
(2, 'Earnings Per Share', 'Stratton Dynamics has $1,000,000 of 8% convertible bonds outstanding, convertible into 25,000 common shares. The tax rate is 25%. The controller adds $80,000 to the numerator for the if-converted adjustment. Analyze whether the controller''s numerator adjustment is correct and its effect on diluted EPS.', '["Incorrect — only the after-tax interest of $60,000 should be added, and the error overstates the numerator, making diluted EPS appear less dilutive", "Correct, because interest on convertible bonds is added back at its full pretax amount", "Incorrect — no interest should be added because the bonds have not actually been converted", "Incorrect — the $20,000 tax savings should be subtracted from net income instead of adding interest"]'::jsonb, 0, 'Under ASC 260-10-45-40, the if-converted method requires adding back interest expense net of tax. The correct adjustment is $80,000 x (1 - 0.25) = $60,000. By adding $80,000, the controller overstates the numerator by $20,000, producing a higher (less dilutive) diluted EPS than warranted. Choice B is incorrect because the pretax amount ignores the tax deduction lost upon conversion.', 'medium', 3),

-- Q14: medium / L2 — Warrants and the treasury stock method
(2, 'Earnings Per Share', 'Mapleton Inc. has 200,000 weighted-average common shares, net income of $900,000, and 10,000 outstanding warrants with an exercise price of $25. The average market price during 2025 was $50. Using the treasury stock method, what is diluted EPS?', '["$4.29 (added all 10,000 warrant shares without treasury stock offset)", "$4.50 (excluded the warrants as antidilutive)", "$4.37 (used period-end price instead of average market price)", "$4.39 (correctly applied the treasury stock method)"]'::jsonb, 3, 'Under ASC 260-10-45-22, the treasury stock method assumes exercise proceeds of $250,000 (10,000 x $25) are used to repurchase 5,000 shares at the $50 average market price, yielding 5,000 incremental shares. Diluted EPS = $900,000 / 205,000 = $4.39. Choice A ($4.29) is incorrect because the treasury stock method requires offsetting assumed proceeds against assumed share repurchases, not simply adding all warrant shares.', 'medium', 2),

-- Q15: medium / L3 — Effect of income level on dilutive impact percentage
(2, 'Earnings Per Share', 'Orion Enterprises has 100,000 common shares and 8,000 stock options with an exercise price of $40 when the average market price is $48. In Year 1, net income was $200,000 and the options were dilutive. In Year 2, net income increases to $500,000 while all other factors remain unchanged. Analyze how the increase in net income affects the options'' dilutive impact.', '["The options become antidilutive because higher income reduces the per-share dilution effect", "The dilutive impact as a percentage of basic EPS increases proportionally with income", "The options remain dilutive with the same percentage reduction in EPS, but the absolute per-share reduction is larger at higher income", "The options have no dilutive impact once basic EPS exceeds the exercise price"]'::jsonb, 2, 'Under ASC 260-10-45-22, the treasury stock method produces 1,333 incremental shares regardless of income (8,000 - [8,000 x $40 / $48]). These shares dilute EPS by the same percentage (~1.3%) in both years, but the absolute dollar reduction per share rises proportionally with income ($0.03 in Year 1 vs. $0.07 in Year 2). Choice A is incorrect because in-the-money options remain dilutive regardless of income level.', 'medium', 3),

-- Q16: easy / L1 — Definition of the treasury stock method
(2, 'Earnings Per Share', 'Under ASC 260, what is the treasury stock method used to compute?', '["The number of shares distributed in a stock dividend", "The cost of treasury shares repurchased during the period", "The effect of convertible bonds on diluted earnings per share", "The incremental shares from assumed exercise of stock options and warrants"]'::jsonb, 3, 'Under ASC 260-10-45-22, the treasury stock method determines incremental dilutive shares from in-the-money options and warrants by assuming exercise proceeds are used to repurchase shares at the average market price. The net difference represents the dilutive share increase. Choice C is incorrect because convertible bonds use the if-converted method, not the treasury stock method.', 'easy', 1),

-- Q17: medium / L2 — Contingent shares with earnings target met at period end
(2, 'Earnings Per Share', 'Haverford Group has 400,000 weighted-average common shares and net income of $2,400,000. An agreement requires issuance of 40,000 additional shares if cumulative net income over three years exceeds $6,000,000. At December 31, 2025 (end of Year 2), cumulative net income totals $4,800,000 and current-period earnings would satisfy the remaining target. How are the contingent shares treated in diluted EPS?', '["Included in diluted EPS because the condition would be met if the current period were the end of the contingency period", "Excluded from diluted EPS until the three-year period ends", "Included in basic EPS because the target is substantially certain to be met", "Included in diluted EPS only to the extent of the elapsed contingency period"]'::jsonb, 0, 'Under ASC 260-10-45-48, contingently issuable shares are included in diluted EPS if all conditions would be satisfied assuming the reporting date were the end of the contingency period. Since cumulative plus current-period earnings exceed $6,000,000, the condition is presumed met. Choice B is incorrect because ASC 260 does not require waiting until the contingency expires — the end-of-period test applies.', 'medium', 2),

-- Q18: medium / L3 — Why convertible preferred becomes antidilutive
(2, 'Earnings Per Share', 'Stonegate Corp. reports net income of $400,000 with 200,000 common shares and $180,000 in convertible preferred dividends. The preferred converts into 40,000 common shares. Basic EPS is $1.10. The CFO includes the preferred in diluted EPS using the if-converted method and reports $1.67. Analyze whether the CFO''s treatment is correct.', '["Correct, because diluted EPS must reflect assumed conversion of all convertible securities", "Incorrect, because the preferred''s per-share impact of $4.50 exceeds basic EPS of $1.10, making it antidilutive and requiring exclusion", "Correct, because the if-converted EPS of $1.67 exceeds basic EPS, indicating a more favorable result for shareholders", "Incorrect, because convertible preferred stock should use the treasury stock method"]'::jsonb, 1, 'Under ASC 260-10-45-17, a security is antidilutive when inclusion increases EPS or decreases loss per share. The preferred''s per-share impact is $4.50 ($180,000 / 40,000 shares), exceeding basic EPS of $1.10. Including it raises diluted EPS to $1.67, confirming it is antidilutive. Choice C is incorrect because diluted EPS should never exceed basic EPS — a higher figure signals the security must be excluded.', 'medium', 3),

-- Q19: medium / L2 — Assumed proceeds include unrecognized compensation cost
(2, 'Earnings Per Share', 'Creston Financial has 250,000 weighted-average common shares, net income of $1,250,000, and 15,000 nonqualified stock options with an exercise price of $20 per share. The average market price is $60 and the average unrecognized compensation cost for the options is $75,000. Under ASC 260, what total assumed proceeds are used in the treasury stock method?', '["$300,000 (exercise price proceeds only, excluding compensation cost)", "$225,000 (exercise proceeds minus unrecognized compensation cost)", "$375,000 (exercise proceeds plus average unrecognized compensation)", "$975,000 (used market price instead of exercise price plus compensation)"]'::jsonb, 2, 'Under ASC 260-10-45-29, assumed proceeds include the exercise price (15,000 x $20 = $300,000) and the average unrecognized compensation cost attributable to future services ($75,000), totaling $375,000. These proceeds are used to compute shares repurchased at the average market price. Choice A is incorrect because it omits the unrecognized compensation component required by ASC 260.', 'medium', 2),

-- Q20: hard / L4 — Mandatorily redeemable preferred treated as liability in EPS
(2, 'Earnings Per Share', 'Northbridge Holdings issues 20,000 shares of mandatorily redeemable preferred stock at $50 per share paying a 6% annual dividend of $60,000, redeemable at par in 10 years. Under ASC 480, this instrument is classified as a liability. The treasurer deducts $60,000 as preferred dividends in the basic EPS numerator. Evaluate whether this treatment is appropriate.', '["Appropriate, because all preferred dividends are deducted regardless of balance sheet classification", "Appropriate, because the instrument has preferred stock characteristics for EPS purposes", "Inappropriate, because liability-classified preferred should be excluded from EPS entirely", "Inappropriate, because the $60,000 is interest expense under ASC 480, already reflected in net income, so no further numerator adjustment is needed"]'::jsonb, 3, 'Under ASC 480-10-25-4, mandatorily redeemable preferred stock classified as a liability has its periodic payments reported as interest expense in the income statement. Since the $60,000 already reduces net income, deducting it again as preferred dividends double-counts the charge. Choice A is incorrect because the dividend deduction applies only to equity-classified instruments — liability-classified instruments have their cost reflected through interest expense.', 'hard', 4),

-- Q21: easy / L1 — Only common shares in basic EPS denominator
(2, 'Earnings Per Share', 'What type of shares are included in the weighted-average denominator for basic earnings per share under ASC 260?', '["Only common shares outstanding during the period", "Both common and preferred shares outstanding during the period", "All authorized shares regardless of issuance status", "Common shares plus all potentially dilutive securities"]'::jsonb, 0, 'Under ASC 260-10-45-10, the basic EPS denominator includes only the weighted-average number of common shares outstanding during the period. Preferred shares are excluded from the denominator; preferred dividends are deducted from the numerator instead. Choice D is incorrect because potentially dilutive securities are included only in diluted EPS, not basic EPS.', 'easy', 1),

-- Q22: medium / L3 — Analyze share buyback effect on basic EPS
(2, 'Earnings Per Share', 'Belmont Industries has net income of $3,000,000 and 500,000 shares outstanding at January 1. On July 1, Belmont repurchases 50,000 shares at $50 per share. Net income is unaffected. Analyze the effect of the share repurchase on Belmont''s basic EPS for the year.', '["Basic EPS decreases to $5.71 because the cash outflow reduces earning capacity", "Basic EPS increases to $6.32 because the weighted-average shares decrease to 475,000", "Basic EPS remains $6.00 because the repurchase is a financing activity with no EPS effect", "Basic EPS increases to $6.67 because the repurchase immediately removes 50,000 shares for the full year"]'::jsonb, 1, 'Under ASC 260-10-45-10, repurchased shares are removed from the weighted average starting on the repurchase date. The weighted average = (500,000 x 6/12) + (450,000 x 6/12) = 475,000. Basic EPS = $3,000,000 / 475,000 = $6.32. Choice D ($6.67) is incorrect because shares repurchased mid-year are weighted from the repurchase date, not retroactively removed for the full year.', 'medium', 3),

-- Q23: easy / L1 — When exercised stock rights enter WACSO
(2, 'Earnings Per Share', 'Under ASC 260, when are shares issued upon exercise of stock rights included in the weighted-average computation for basic EPS?', '["From the date the stock rights are granted to the employee", "From the beginning of the period in which the rights were granted", "From the date the rights are exercised and shares are issued", "From the date the stock rights become vested"]'::jsonb, 2, 'Under ASC 260-10-45-10, shares are included in the basic EPS weighted-average denominator from the date they are issued and outstanding. Stock rights create potential shares until exercise; only upon exercise do newly issued shares enter the weighted average. Choice A is incorrect because the grant date creates a contingent right, not an outstanding share — diluted EPS considers unexercised rights.', 'easy', 1),

-- Q24: easy / L1 — EPS is computed per common share only
(2, 'Earnings Per Share', 'Under ASC 260, earnings per share is computed and reported on a per-share basis for which class of equity?', '["Total equity including both preferred and common stock", "Preferred stock only, excluding common shareholders", "All outstanding shares including treasury shares", "Common stock only, excluding preferred stock"]'::jsonb, 3, 'Under ASC 260-10-45-2, EPS is computed and presented for common stock. The numerator begins with net income and deducts preferred dividends to arrive at income available to common shareholders. Choice A is incorrect because combining preferred and common equity would obscure the earnings attributable specifically to common shareholders, defeating the purpose of per-share reporting.', 'easy', 1),

-- Q25: medium / L2 — Partially paid shares in weighted-average computation
(2, 'Earnings Per Share', 'Waverly Corp. issued 20,000 shares of common stock on March 1, 2025, with subscribers paying 60% of the $25 per share issue price at issuance. The remaining 40% was paid on November 1, 2025. Under ASC 260, how should Waverly compute the weighted-average shares for these partially paid shares?', '["Include 12,000 share-equivalents from March 1 and an additional 8,000 share-equivalents from November 1", "Include all 20,000 shares from March 1 because the subscription agreement is binding", "Exclude all 20,000 shares until fully paid on November 1", "Include 20,000 shares weighted from March 1 through December 31"]'::jsonb, 0, 'Under ASC 260-10-45-13, partially paid shares are included as the equivalent fraction of shares corresponding to the percentage paid, to the extent they participate in dividends. At 60% paid, 12,000 share-equivalents enter the average from March 1. When fully paid November 1, the remaining 8,000 equivalents are added. Choice B is incorrect because partially paid shares cannot be counted as fully outstanding.', 'medium', 2),

-- Q26: easy / L1 — Retroactive restatement of prior-period EPS for stock dividends
(2, 'Earnings Per Share', 'Under ASC 260, how must a company adjust prior-period earnings per share when a stock dividend is declared in the current period?', '["No adjustment — prior-period EPS is reported as originally calculated", "Prior-period EPS must be retroactively restated to reflect the stock dividend", "Prior-period EPS is adjusted prospectively beginning in the dividend period", "Prior-period EPS is restated only if the stock dividend exceeds 10% of outstanding shares"]'::jsonb, 1, 'Under ASC 260-10-55-12, stock dividends and stock splits must be retroactively applied to all prior periods presented to maintain comparability. This ensures per-share amounts are computed on a consistent share basis. Choice A is incorrect because presenting prior-period EPS on a different share base would make year-over-year comparisons misleading and violate ASC 260 requirements.', 'easy', 1),

-- Q27: medium / L3 — Year-to-date vs quarterly diluted EPS
(2, 'Earnings Per Share', 'Prescott Logistics has 100,000 common shares and 5,000 stock options with an exercise price of $35. The average market price was $50 in Q1 and $30 in Q2, making the options dilutive in Q1 but antidilutive in Q2. Analyze how Prescott should report diluted EPS for the six-month year-to-date period ending June 30.', '["Exclude the options for the year-to-date period because they were antidilutive in Q2", "Include the options only for the Q1 portion and exclude them for the Q2 portion", "Test the options using the six-month average market price to determine dilutive status for the year-to-date period", "Use the Q2 average market price because it is the most recent measure of dilutive status"]'::jsonb, 2, 'Under ASC 260-10-45-29A, each interim period and year-to-date period computes diluted EPS independently using that period''s average market price. The six-month average market price determines dilutive status for the year-to-date computation, regardless of individual quarterly results. Choice A is incorrect because antidilution in one quarter does not automatically exclude options from the cumulative year-to-date calculation.', 'medium', 3),

-- Q28: hard / L4 — Forward purchase contract and reverse treasury stock method
(2, 'Earnings Per Share', 'Highland Corp. enters a forward contract obligating it to repurchase 25,000 of its own shares at $55 per share in one year. The average market price during the period is $45. Highland''s controller excludes the contract from diluted EPS, reasoning that share repurchases reduce the denominator. Evaluate whether the controller''s exclusion is appropriate under ASC 260.', '["Appropriate, because the contract is a repurchase commitment that reduces shares like treasury stock", "Inappropriate, because the repurchase price exceeds market price, making the contract dilutive under the reverse treasury stock method, which adds incremental shares", "Appropriate, because forward contracts on own shares are financing arrangements with no EPS impact", "Inappropriate, because the full 25,000 shares must be added to the denominator as potential common shares"]'::jsonb, 1, 'Under ASC 260-10-45-35, when the repurchase price exceeds the average market price, a forward purchase contract is dilutive. The reverse treasury stock method assumes the entity issues shares at market to fund the repurchase: ($55 x 25,000) / $45 = 30,556 shares issued minus 25,000 repurchased = 5,556 incremental shares. Choice A is incorrect because a premium repurchase price effectively creates additional shares, increasing dilution.', 'hard', 4),

-- Q29: medium / L3 — Effect of coupon rate on per-share dilutive impact of convertible bonds
(2, 'Earnings Per Share', 'Summit Holdings has two convertible bond issues: Bond A ($800,000 face, 3% coupon, converts to 20,000 shares) and Bond B ($800,000 face, 9% coupon, converts to 20,000 shares). The tax rate is 25%. Analyze which bond has a greater dilutive impact on EPS and explain why.', '["Bond A is more dilutive because its lower coupon produces a smaller after-tax numerator add-back per incremental share", "Bond B is more dilutive because its higher coupon provides a larger tax shield on interest expense", "Both bonds are equally dilutive because they share the same face value and conversion ratio", "Bond B is more dilutive because its higher interest payments reduce net income more, lowering basic EPS"]'::jsonb, 0, 'Under ASC 260-10-45-40, the if-converted method adds back after-tax interest. Bond A''s add-back is $18,000 ($800,000 x 3% x 75%), yielding a per-share impact of $0.90. Bond B''s add-back is $54,000 ($800,000 x 9% x 75%), yielding $2.70 per share. The lower per-share impact makes Bond A more dilutive. Choice C is incorrect because identical face values and conversion ratios do not equalize dilutive impact when coupon rates differ.', 'medium', 3),

-- Q30: medium / L3 — Continuing operations as control number for dilution
(2, 'Earnings Per Share', 'Marfield Enterprises reports a loss from continuing operations of $300,000 and income from discontinued operations of $150,000, resulting in a net loss of $150,000. Marfield has 100,000 common shares and 5,000 in-the-money stock options. Analyze whether the stock options should be included in Marfield''s diluted EPS computation.', '["Yes, because the options are in the money and increase the denominator for all EPS figures", "Yes, because the net loss is smaller than the continuing operations loss, making the options dilutive on a net basis", "No, because stock options can never be included in diluted EPS when any loss is reported", "No, because the loss from continuing operations is the control number, and including additional shares would reduce the loss per share, which is antidilutive"]'::jsonb, 3, 'Under ASC 260-10-45-19, income from continuing operations is the control number for determining whether securities are dilutive. Because Marfield reports a loss from continuing operations, including additional shares would reduce the loss per share, which is antidilutive. All potentially dilutive securities must be excluded. Choice A is incorrect because the in-the-money status is irrelevant when the control number is a loss.', 'medium', 3)
;

COMMIT;
