-- Migration: Question generation — FAR batch 43 (30 questions)
-- Date: 2026-03-01
-- Topic: Earnings Per Share
-- Difficulty: 9E / 15M / 6H
-- Bloom's: L1:8 / L2:9 / L3:8 / L4:5

BEGIN;

INSERT INTO questions (section_id, topic, stem, choices, correct_index, explanation, difficulty, cognitive_level)
VALUES

-- Q1: medium / L3 — Two-class method: participating securities reduce basic EPS
(2, 'Earnings Per Share', 'Greystone Corp. reports net income of $900,000 with 200,000 weighted-average common shares outstanding. The company also has 50,000 shares of participating preferred stock that share equally in undistributed earnings after receiving a $2.00 per-share base dividend. No dividends were declared. Analyze how the participating preferred stock affects the computation of basic EPS compared to nonparticipating preferred stock.', '["Basic EPS is the same because no dividends were declared", "Basic EPS increases because preferred holders forgo their dividend", "Basic EPS decreases because undistributed earnings must be allocated to both common and preferred shares under the two-class method", "Basic EPS decreases only if the preferred dividends were cumulative"]'::jsonb, 2, 'Under ASC 260-10-45-60A, participating securities require the two-class method for basic EPS. Undistributed earnings are allocated to common and participating preferred based on their respective participation rights, reducing the numerator available to common shareholders. Choice A is incorrect because even when dividends are not declared, participating preferred shares are allocated a portion of undistributed earnings, unlike nonparticipating preferred stock.', 'medium', 3),

-- Q2: medium / L3 — Retrospective restatement of prior-year EPS for stock splits
(2, 'Earnings Per Share', 'On March 1, 2026, Pinehurst Industries announces a 2-for-1 stock split. The company''s 2025 comparative financial statements reported basic EPS of $4.80 based on 150,000 weighted-average shares and net income of $720,000. What is the effect of the stock split on the prior-year basic EPS presented in the 2026 comparative statements?', '["Prior-year basic EPS remains $4.80 with footnote disclosure of the stock split", "Prior-year basic EPS is restated to $2.40 to reflect the stock split retrospectively", "Prior-year basic EPS is restated to $4.80 using 300,000 shares and adjusted net income", "Prior-year basic EPS is not restated because the split occurred in the subsequent period"]'::jsonb, 1, 'Under ASC 260-10-55-12, stock splits and stock dividends must be applied retrospectively to all prior periods presented. The 2025 weighted-average shares are restated from 150,000 to 300,000, producing restated basic EPS of $2.40 ($720,000 / 300,000). Choice A is incorrect because ASC 260 requires retrospective restatement of all EPS data, not merely footnote disclosure, ensuring period-to-period comparability.', 'medium', 3),

-- Q3: easy / L1 — Definition of a complex capital structure
(2, 'Earnings Per Share', 'Under ASC 260, which of the following best describes a complex capital structure?', '["A structure with more than one class of common stock outstanding", "A structure in which the entity has both debt and equity securities", "A structure requiring consolidation of a variable interest entity", "A structure with outstanding securities that could dilute basic EPS upon conversion or exercise"]'::jsonb, 3, 'Under ASC 260-10-15-2, a complex capital structure exists when an entity has outstanding potentially dilutive securities such as convertible bonds, convertible preferred stock, stock options, or warrants. Choice A is incorrect because multiple classes of common stock alone do not create a complex capital structure; the key factor is the existence of securities that could reduce EPS if converted or exercised.', 'easy', 1),

-- Q4: medium / L3 — Antidilutive convertible bonds excluded from diluted EPS
(2, 'Earnings Per Share', 'Cedarbrook Inc. reports net income of $100,000 with 50,000 weighted-average common shares, producing basic EPS of $2.00. The company has $1,000,000 of 10% convertible bonds, each $1,000 bond converting into 10 shares. The tax rate is 25%. Analyze whether these convertible bonds should be included in diluted EPS.', '["The bonds are antidilutive and must be excluded because their per-share impact of $7.50 exceeds basic EPS of $2.00", "The bonds are dilutive and must be included because convertible securities always reduce diluted EPS", "The bonds are dilutive because adding 10,000 shares to the denominator reduces EPS", "The bonds are antidilutive only if the bondholder elects not to convert"]'::jsonb, 0, 'Under ASC 260-10-45-19, a potentially dilutive security is antidilutive when its inclusion would increase EPS or decrease loss per share. The bonds'' per-share impact is $7.50 [($1,000,000 x 10% x 0.75) / 10,000 shares], which exceeds basic EPS of $2.00, meaning inclusion would raise diluted EPS to $2.92. Choice B is incorrect because convertible securities are excluded from diluted EPS whenever their effect is antidilutive.', 'medium', 3),

-- Q5: hard / L4 — Control number: loss from continuing ops makes all securities antidilutive
(2, 'Earnings Per Share', 'Fairview Holdings reports a loss from continuing operations of $150,000, income from discontinued operations of $400,000 (net of tax), and net income of $250,000. The company has 100,000 common shares outstanding and 10,000 stock options with an exercise price of $20 when the average market price is $30. The controller proposes including the stock options in diluted EPS because net income is positive. Evaluate whether the controller''s approach is correct.', '["The controller is correct because diluted EPS is computed using net income as the control number", "The controller is incorrect because income from continuing operations is the control number, and the loss from continuing operations makes the options antidilutive", "The controller is incorrect because discontinued operations must be excluded from all EPS calculations", "The controller is correct because the options are in-the-money and therefore always dilutive"]'::jsonb, 1, 'Under ASC 260-10-45-19A, income from continuing operations serves as the control number for determining whether securities are dilutive. Because Fairview has a loss from continuing operations of $150,000, all potentially dilutive securities are antidilutive and must be excluded from diluted EPS, regardless of positive net income. Choice A is incorrect because net income is not the control number when discontinued operations exist.', 'hard', 4),

-- Q6: hard / L4 — Mid-year conversion: if-converted for pre-conversion, actual shares post-conversion
(2, 'Earnings Per Share', 'On September 1, 2026, holders of Whitfield Corp.''s convertible preferred stock convert all 5,000 shares (annual dividend $8 per share) into 20,000 common shares. Whitfield had 100,000 common shares outstanding on January 1. Net income is $600,000. The CFO must determine the proper treatment of the mid-year conversion when computing diluted EPS. Assess the correct approach under ASC 260.', '["Include 20,000 shares weighted for only four months (September through December) with no preferred dividend adjustment", "Exclude the converted shares entirely from diluted EPS because conversion occurred before year-end", "Include 20,000 shares as if outstanding for the entire year and add back all $40,000 of preferred dividends in the numerator", "Use the if-converted method only for September through December because diluted EPS applies only to the conversion period"]'::jsonb, 2, 'Under ASC 260-10-45-40, when convertible securities are actually converted during the period, diluted EPS applies the if-converted method from the beginning of the year. The 20,000 shares are included for the full year, and the entire $40,000 preferred dividend ($8 x 5,000) is added back to the numerator since conversion is assumed at January 1. Choice A is incorrect because the four-month weighting applies only to basic EPS, not diluted EPS.', 'hard', 4),

-- Q7: medium / L3 — RSUs effect on diluted EPS via treasury stock method
(2, 'Earnings Per Share', 'Hartwell Industries granted 12,000 restricted stock units (RSUs) to employees on January 1, 2026. The RSUs vest over three years and have $180,000 in total unrecognized compensation cost remaining. The average market price of Hartwell''s stock during 2026 was $45 per share. Analyze how these RSUs affect diluted EPS under the treasury stock method.', '["All 12,000 RSUs are added to the denominator because they represent committed shares", "The RSUs have no effect on diluted EPS until they vest", "The RSUs add 12,000 shares and subtract 6,000 assumed repurchased shares, yielding 6,000 incremental shares", "Assumed proceeds of $180,000 repurchase 4,000 shares at $45, yielding 8,000 incremental dilutive shares"]'::jsonb, 3, 'Under ASC 260-10-45-29, unvested RSUs are treated as potential common shares using the treasury stock method. The assumed proceeds equal the unrecognized compensation cost ($180,000), which could repurchase 4,000 shares ($180,000 / $45). The incremental shares are 12,000 minus 4,000 = 8,000. Choice A is incorrect because the treasury stock method requires reducing the share count by shares assumed repurchased with the unamortized compensation cost.', 'medium', 3),

-- Q8: hard / L3 — Written put options: reverse treasury stock method
(2, 'Earnings Per Share', 'Meridian Corp. wrote put options on its own stock during 2026, obligating it to repurchase 8,000 shares at $50 per share if exercised. The average market price during 2026 was $40 per share. Net income is $500,000 with 100,000 weighted-average shares outstanding. Analyze the effect of the written put options on Meridian''s diluted EPS calculation.', '["The written puts are dilutive and add 2,000 incremental shares to the denominator because the exercise price exceeds the market price", "The written puts are antidilutive and excluded because Meridian would repurchase shares, reducing the denominator", "The written puts have no effect on diluted EPS because they reduce rather than increase shares outstanding", "The written puts add 8,000 shares to the denominator because the full obligation must be reflected"]'::jsonb, 0, 'Under ASC 260-10-45-35, written put options use the reverse treasury stock method when the exercise price exceeds the average market price. Meridian is assumed to repurchase 8,000 shares at $50 ($400,000), then issue 10,000 shares at the $40 market price to fund the purchase. The net 2,000 incremental shares (10,000 minus 8,000) increase the denominator, making the puts dilutive. Choice B is incorrect because the reverse treasury stock method recognizes that funding the repurchase at above-market prices requires issuing more shares than are retired.', 'hard', 3),

-- Q9: medium / L2 — If-converted method for convertible preferred stock calculation
(2, 'Earnings Per Share', 'Lockwood Enterprises reports net income of $480,000 with 120,000 weighted-average common shares outstanding. The company has 10,000 shares of $50 par, 6% convertible preferred stock, each share converting into 3 common shares. The preferred dividends were declared and paid. Calculate diluted EPS using the if-converted method.', '["$3.75", "$3.20", "$3.00", "$4.00"]'::jsonb, 1, 'Under ASC 260-10-45-40, the if-converted method adds back preferred dividends ($30,000 = 10,000 x $50 x 6%) to the numerator and adds conversion shares (30,000 = 10,000 x 3) to the denominator. Diluted EPS = $480,000 / 150,000 = $3.20. Choice C ($3.00) is incorrect because it fails to add back preferred dividends to the numerator, effectively deducting them twice: ($480,000 minus $30,000) / 150,000 = $3.00.', 'medium', 2),

-- Q10: easy / L1 — Definition of potentially dilutive securities
(2, 'Earnings Per Share', 'Under ASC 260, which of the following is considered a potentially dilutive security?', '["Treasury stock held by the issuing company", "Nonconvertible cumulative preferred stock", "Stock options granted to employees", "Bonds payable without a conversion feature"]'::jsonb, 2, 'Under ASC 260-10-15-2, potentially dilutive securities include options, warrants, convertible debt, and convertible preferred stock — any instrument that could result in the issuance of additional common shares. Stock options are potentially dilutive because their exercise would increase shares outstanding. Choice B is incorrect because nonconvertible preferred stock, while it reduces the EPS numerator, cannot result in additional common shares.', 'easy', 1),

-- Q11: easy / L1 — Dual EPS presentation requirement for complex capital structures
(2, 'Earnings Per Share', 'Which of the following correctly describes the EPS disclosure requirement for public entities with complex capital structures under ASC 260?', '["Both basic and diluted EPS must be presented on the face of the income statement", "Only diluted EPS must be presented on the face of the income statement", "Basic EPS is presented on the income statement and diluted EPS is disclosed in the notes", "Both basic and diluted EPS are disclosed only in the notes to the financial statements"]'::jsonb, 0, 'Under ASC 260-10-45-2, entities with complex capital structures must present both basic and diluted EPS with equal prominence on the face of the income statement for income from continuing operations and net income. Choice B is incorrect because ASC 260 explicitly requires dual presentation of both basic and diluted EPS, not just diluted EPS alone.', 'easy', 1),

-- Q12: medium / L3 — Shares issued in acquisition weighted from acquisition date
(2, 'Earnings Per Share', 'On July 1, 2026, Belmont Corp. issues 40,000 shares of common stock to acquire Creekside LLC in a business combination. Belmont had 200,000 shares outstanding from January 1. No other share transactions occurred. Analyze the effect of the acquisition on Belmont''s weighted-average common shares for 2026 basic EPS.', '["240,000 shares because acquisition shares are treated as outstanding from January 1", "200,000 shares because acquisition shares are excluded from EPS until the following year", "240,000 shares because business combinations require retroactive adjustment of share counts", "220,000 shares because the acquisition shares are weighted from the July 1 acquisition date"]'::jsonb, 3, 'Under ASC 260-10-45-13, shares issued in a business combination are included in weighted-average shares from the acquisition date, not retroactively. The 40,000 shares are weighted for six months (July through December): 200,000 + (40,000 x 6/12) = 220,000. Choice A is incorrect because retroactive treatment applies only to stock splits and stock dividends, not to shares issued for consideration in an acquisition.', 'medium', 3),

-- Q13: medium / L3 — Stock dividend (retroactive) vs new issuance (weighted) treatment
(2, 'Earnings Per Share', 'Oakmont Holdings has 100,000 shares outstanding on January 1, 2026. On April 1, the company declares a 20% stock dividend. On October 1, the company issues 10,000 new shares for cash. Analyze how these two events differ in their effect on the weighted-average shares for 2026 basic EPS.', '["Both events are weighted from their respective dates, producing 120,000 plus 2,500 equaling 122,500 shares", "The stock dividend is applied retroactively to all periods, making the January 1 balance 120,000, while the new issuance is weighted from October 1, producing 122,500 shares", "Both events are applied retroactively, producing 132,000 weighted-average shares for the year", "The stock dividend is weighted from April 1 and the new issuance from October 1, producing 117,500 shares"]'::jsonb, 1, 'Under ASC 260-10-55-12, stock dividends are treated as if they occurred at the beginning of the earliest period presented, restating the January 1 share count to 120,000 (100,000 x 1.20). Shares issued for cash are weighted from the issuance date (October 1), adding 2,500 shares (10,000 x 3/12). Total: 122,500. Choice D is incorrect because stock dividends are never weighted from the distribution date; they receive full retroactive treatment.', 'medium', 3),

-- Q14: hard / L4 — Evaluate which capital structure change most improves diluted EPS
(2, 'Earnings Per Share', 'Kensington Corp. has net income of $1,200,000 and 300,000 weighted-average shares (basic EPS: $4.00). The CFO is evaluating two strategies to improve diluted EPS: (1) retire $2,000,000 of 8% convertible bonds (each $1,000 bond converts to 30 shares, tax rate 25%), or (2) cancel 15,000 outstanding stock options with an exercise price of $25 (average market price: $50). Evaluate which strategy produces a greater improvement in diluted EPS.', '["Cancel the stock options because they add more incremental shares per security", "Both strategies produce the same improvement because each removes dilutive securities", "Retire the convertible bonds because their per-share impact is well below basic EPS, making them highly dilutive", "Cancel the stock options because removing 7,500 incremental shares has a larger percentage effect"]'::jsonb, 2, 'Under ASC 260-10-45-19, retiring the bonds eliminates 60,000 dilutive shares and the $120,000 after-tax interest add-back. The bonds'' per-share impact of $2.00 ($120,000 / 60,000) is well below basic EPS of $4.00, making them highly dilutive. Bond retirement improves diluted EPS by $0.31 (from $3.59 to $3.90), while canceling options improves it by only $0.08. Choice D is incorrect because the options'' 7,500 incremental shares have a smaller absolute impact than the bonds'' 60,000 shares.', 'hard', 4),

-- Q15: easy / L2 — Weighted-average shares with treasury stock repurchase
(2, 'Earnings Per Share', 'Ferndale Corp. had 80,000 shares of common stock outstanding on January 1, 2026. On October 1, the company repurchased 12,000 shares as treasury stock. What is the weighted-average number of common shares outstanding for 2026?', '["77,000", "74,000", "68,000", "80,000"]'::jsonb, 0, 'Under ASC 260-10-45-10, treasury shares repurchased are excluded from the weighted-average calculation from the repurchase date. Ferndale had 80,000 shares for nine months and 68,000 shares for three months: (80,000 x 9/12) + (68,000 x 3/12) = 60,000 + 17,000 = 77,000. Choice C is incorrect because it deducts the full 12,000 shares for the entire year rather than weighting them from the October 1 repurchase date.', 'easy', 2),

-- Q16: easy / L1 — Definition of the treasury stock method
(2, 'Earnings Per Share', 'What does the treasury stock method assume when calculating diluted EPS for stock options?', '["Options are exercised at the average market price and shares are repurchased at the exercise price", "Options are exercised at the exercise price and the proceeds are used to repurchase shares at the average market price", "Options are exercised at the year-end market price and proceeds are used to retire outstanding debt", "Options are exercised at the exercise price and all resulting shares are added to the denominator"]'::jsonb, 1, 'Under ASC 260-10-45-22, the treasury stock method assumes stock options are exercised at the exercise price, and the assumed proceeds are used to repurchase common shares at the average market price for the period. Only the net incremental shares (issued minus repurchased) increase the denominator. Choice A is incorrect because it reverses the prices — exercise occurs at the exercise price, and repurchase occurs at the average market price.', 'easy', 1),

-- Q17: medium / L2 — Diluted EPS calculation with convertible preferred (if-converted)
(2, 'Earnings Per Share', 'Riverstone Inc. reports net income of $720,000 with 180,000 weighted-average common shares outstanding. The company has 8,000 shares of $25 par, 8% convertible preferred stock, each share converting into 2 common shares. The preferred dividends were declared. Calculate diluted EPS.', '["$3.91", "$3.59", "$4.00", "$3.67"]'::jsonb, 3, 'Under ASC 260-10-45-40, the if-converted method adds back preferred dividends ($16,000 = 8,000 x $25 x 8%) to the numerator and adds conversion shares (16,000 = 8,000 x 2) to the denominator. Diluted EPS = $720,000 / 196,000 = $3.67. Choice B ($3.59) is incorrect because it deducts preferred dividends from the numerator instead of adding them back, which double-counts the deduction that the if-converted method reverses.', 'medium', 2),

-- Q18: easy / L1 — EPS required only for public business entities
(2, 'Earnings Per Share', 'Under ASC 260, which type of entity is required to present earnings per share on the income statement?', '["Public business entities whose common stock is traded in a public market", "All entities that prepare GAAP financial statements", "All entities with net income exceeding $1 million", "Only SEC registrants that file Form 10-K"]'::jsonb, 0, 'Under ASC 260-10-15-2, EPS presentation is required only for public business entities with common stock or potential common stock traded in a public market, or that file with the SEC. Nonpublic entities may voluntarily present EPS but are not required to do so. Choice D is incorrect because the requirement extends beyond 10-K filers to any entity with publicly traded common stock or potential common stock.', 'easy', 1),

-- Q19: medium / L3 — Mid-year option grant: incremental shares weighted from grant date
(2, 'Earnings Per Share', 'Briarwood Corp. grants 15,000 stock options with an exercise price of $30 on July 1, 2026. The average market price from July 1 through December 31 is $50. Analyze how the mid-year grant date affects the incremental share calculation compared to options outstanding for the full year.', '["The incremental shares are the same regardless of the grant date because the treasury stock method uses the annual average price", "The incremental shares are higher for mid-year grants because fewer shares are assumed repurchased", "The incremental shares are lower because the 6,000 shares from the treasury stock method are weighted for only six months, adding 3,000 shares to the denominator", "The options are excluded from diluted EPS because they were not outstanding for the full year"]'::jsonb, 2, 'Under ASC 260-10-45-22, stock options are included in diluted EPS from the grant date. The 15,000 options at a $30 exercise price produce 6,000 incremental shares [15,000 minus ($450,000 / $50)], but weighted for six months (July through December), only 3,000 shares are added to the denominator. Choice A is incorrect because while the treasury stock method uses the period''s average price, the resulting incremental shares are still weighted for the portion of the year the options were outstanding.', 'medium', 3),

-- Q20: medium / L2 — Assumed proceeds include unamortized compensation cost
(2, 'Earnings Per Share', 'Clearfield Technologies has 20,000 stock options outstanding with an exercise price of $35 per share and $60,000 in unamortized compensation cost. The average market price during 2026 is $50. Under the treasury stock method, what are the total assumed proceeds and the resulting incremental shares for diluted EPS?', '["Assumed proceeds of $700,000 with 6,000 incremental shares", "Assumed proceeds of $760,000 with 4,800 incremental shares", "Assumed proceeds of $760,000 with 6,000 incremental shares", "Assumed proceeds of $700,000 with 14,000 incremental shares"]'::jsonb, 1, 'Under ASC 260-10-45-29, assumed proceeds under the treasury stock method include the exercise price ($700,000 = 20,000 x $35) plus any unamortized compensation cost ($60,000), totaling $760,000. These proceeds repurchase 15,200 shares ($760,000 / $50), yielding 4,800 incremental shares (20,000 minus 15,200). Choice A is incorrect because it excludes the $60,000 unamortized compensation from assumed proceeds, overstating the incremental share count by 1,200.', 'medium', 2),

-- Q21: medium / L2 — EPS presentation for discontinued operations
(2, 'Earnings Per Share', 'Sycamore Financial Corp. reports income from continuing operations of $450,000 and a loss from discontinued operations (net of tax) of $120,000. The company has 100,000 weighted-average common shares and no preferred stock. Determine the basic EPS amounts that must be presented on the income statement.', '["Net income EPS of $3.30, presented as a single line item", "Continuing operations EPS of $4.50 and net income EPS of $3.30", "Continuing operations EPS of $4.50 as the sole per-share amount", "Continuing operations EPS of $4.50, discontinued operations loss per share of $(1.20), and net income EPS of $3.30"]'::jsonb, 3, 'Under ASC 260-10-45-2, entities must present per-share amounts for income from continuing operations and net income on the face of the income statement. Per-share amounts for discontinued operations may be presented on the face or in the notes. The figures are: $4.50 for continuing operations, $(1.20) for discontinued operations, and $3.30 for net income. Choice A is incorrect because presenting only net income EPS as a single line item fails to meet the requirement of also disclosing EPS from continuing operations.', 'medium', 2),

-- Q22: medium / L2 — Weighted-average shares with shares issued as compensation
(2, 'Earnings Per Share', 'Ridgeway Corp. had 150,000 common shares outstanding on January 1, 2026. On May 1, the company issued 6,000 shares to executives as stock compensation. No other share transactions occurred during 2026. What is the weighted-average number of common shares for basic EPS?', '["154,000", "156,000", "153,000", "150,000"]'::jsonb, 0, 'Under ASC 260-10-45-10, shares issued as compensation are included in the weighted-average from their issuance date. The 6,000 shares were outstanding for eight months (May through December): 150,000 + (6,000 x 8/12) = 150,000 + 4,000 = 154,000. Choice B is incorrect because it includes the full 6,000 shares for the entire year rather than weighting them from the May 1 issuance date.', 'medium', 2),

-- Q23: easy / L1 — Numerator for basic EPS
(2, 'Earnings Per Share', 'What is the starting point for the numerator in the basic EPS calculation under ASC 260?', '["Gross profit available to common shareholders", "Operating income minus preferred dividends", "Net income minus preferred dividends on preferred stock", "Comprehensive income minus preferred dividends"]'::jsonb, 2, 'Under ASC 260-10-45-10, the numerator for basic EPS is net income (or loss) attributable to common shareholders, which is net income reduced by any preferred stock dividends (whether declared or, for cumulative preferred, accumulated). Choice D is incorrect because comprehensive income includes other comprehensive income items that are not part of the EPS numerator — only net income is used.', 'easy', 1),

-- Q24: medium / L2 — Two-class method calculation for basic EPS
(2, 'Earnings Per Share', 'Ashworth Industries reports net income of $500,000 with 100,000 common shares and 25,000 participating preferred shares outstanding for the full year. The preferred stock receives a base dividend of $2.00 per share and participates equally in remaining earnings. Calculate basic EPS under the two-class method.', '["$4.50", "$3.60", "$5.00", "$4.00"]'::jsonb, 1, 'Under ASC 260-10-45-60A, the two-class method allocates undistributed earnings between common and participating preferred shares based on their respective participation rights. After deducting the $50,000 base dividend, the remaining $450,000 is allocated 80% to common (100,000 / 125,000), yielding $360,000 / 100,000 = $3.60. Choice A ($4.50) is incorrect because it deducts only the base preferred dividend without allocating undistributed earnings to participating preferred shares.', 'medium', 2),

-- Q25: hard / L4 — Net loss not allocated to participating preferred without contractual obligation
(2, 'Earnings Per Share', 'Pemberton Corp. reports a net loss of $300,000 with 200,000 common shares and 50,000 shares of participating preferred stock outstanding for the full year. The preferred stock participates equally in earnings but has no contractual obligation to absorb losses. The controller allocates the loss proportionally between common and preferred shares, reporting basic loss per share of $(1.20). Evaluate whether the controller''s treatment is correct under ASC 260.', '["The treatment is correct because participating securities must share in both earnings and losses proportionally", "The treatment is correct because the two-class method applies to all periods regardless of income or loss", "The treatment is incorrect because loss allocation should use total shares outstanding divided into net loss", "The treatment is incorrect because losses are not allocated to participating securities unless they have a contractual obligation to share in losses"]'::jsonb, 3, 'Under ASC 260-10-45-66, net losses are not allocated to participating securities under the two-class method unless the security has a contractual obligation to share in the entity''s losses. Since Pemberton''s preferred has no such obligation, the entire $300,000 loss is attributed to common shares, producing loss per share of $(1.50), not $(1.20). Choice A is incorrect because proportional loss allocation applies only when the participating security contractually requires loss sharing.', 'hard', 4),

-- Q26: medium / L2 — Diluted EPS numerator adjustment for convertible bonds (after-tax interest)
(2, 'Earnings Per Share', 'Waverly Industries reports net income of $850,000 with 250,000 weighted-average common shares. The company has $600,000 face value of 5% convertible bonds, each $1,000 bond converting into 20 shares. The income tax rate is 25%. Calculate the numerator adjustment and diluted EPS assuming the bonds are dilutive.', '["$3.33", "$3.36", "$3.24", "$3.49"]'::jsonb, 0, 'Under ASC 260-10-45-40, the if-converted method adds after-tax interest expense to the numerator and conversion shares to the denominator. The numerator adjustment is $22,500 ($600,000 x 5% x 0.75), and 12,000 conversion shares (600 bonds x 20) are added. Diluted EPS = ($850,000 + $22,500) / 262,000 = $3.33. Choice B ($3.36) is incorrect because it adds the full pre-tax interest of $30,000 rather than the after-tax amount of $22,500.', 'medium', 2),

-- Q27: hard / L4 — Ranking multiple dilutive securities and identifying antidilutive preferred
(2, 'Earnings Per Share', 'Halcyon Corp. reports net income of $600,000 with 200,000 weighted-average common shares. Three potentially dilutive securities exist: (A) 10,000 stock options with exercise price $25 and average market price $50, (B) $400,000 of 5% convertible bonds converting into 12,000 shares (tax rate 25%), and (C) 3,000 shares of convertible preferred stock with a $10 annual dividend, each converting into 1 common share. Assess the correct diluted EPS by ranking and testing each security for dilution.', '["$2.80, with all three securities included", "$2.78, with only stock options included", "$2.70, with options and bonds included but preferred excluded as antidilutive", "$2.85, with no dilutive securities included"]'::jsonb, 2, 'Under ASC 260-10-45-21, securities are ranked by per-share impact: options ($0), bonds ($1.25 = $15,000 / 12,000), preferred ($10.00 = $30,000 / 3,000). After including options and bonds, running EPS is $2.70. Testing the preferred: ($585,000 + $30,000) / 220,000 = $2.80, which exceeds $2.70, so the preferred is antidilutive and excluded. Choice A ($2.80) is incorrect because including the antidilutive preferred would improperly increase diluted EPS above the running total.', 'hard', 4),

-- Q28: easy / L1 — Where EPS must be reported
(2, 'Earnings Per Share', 'Under U.S. GAAP, where must earnings per share be reported for public entities?', '["Only in the notes to the financial statements", "In the management discussion and analysis section", "On the statement of cash flows", "On the face of the income statement"]'::jsonb, 3, 'Under ASC 260-10-45-2, public entities must present earnings per share on the face of the income statement for income from continuing operations and net income. Choice A is incorrect because while additional EPS disclosures may appear in the notes, the basic and diluted EPS figures themselves must be presented on the face of the income statement, not solely in footnote disclosures.', 'easy', 1),

-- Q29: medium / L2 — Contingently issuable shares included from beginning of period when conditions met
(2, 'Earnings Per Share', 'Brookfield Corp. has 200,000 common shares outstanding and a contingent agreement to issue 25,000 additional shares if 2026 revenues exceed $5 million. Revenues reached $5.8 million on September 30, 2026, satisfying the condition. Net income is $400,000 with no preferred stock. Determine how the contingent shares are treated for basic EPS.', '["$1.78, with 25,000 shares included from January 1 because all conditions were met by year-end", "$1.94, with 25,000 shares weighted from October 1 when the revenue condition was satisfied", "$2.00, with contingent shares excluded until formally issued", "$1.60, with 25,000 shares included from January 1 and additional assumed shares from dilution"]'::jsonb, 0, 'Under ASC 260-10-45-50, when all conditions for contingently issuable shares are satisfied by the end of the reporting period, the shares are included in basic EPS from the beginning of the period. The 25,000 shares are included for the full year: $400,000 / 225,000 = $1.78. Choice B is incorrect because contingently issuable shares are not weighted from the date conditions are met; once satisfied, they are retroactively included from the beginning of the period.', 'medium', 2),

-- Q30: easy / L1 — Definition of antidilutive securities
(2, 'Earnings Per Share', 'Under ASC 260, what does the term ''antidilutive'' mean in the context of earnings per share?', '["A security that reduces the number of shares outstanding when exercised", "A security whose inclusion in the EPS calculation would increase EPS or decrease loss per share", "A security that has been converted from debt to equity during the period", "A security that management intends to retire before the end of the fiscal year"]'::jsonb, 1, 'Under ASC 260-10-20, antidilutive refers to an increase in earnings per share or a decrease in loss per share resulting from the assumed conversion, exercise, or issuance of certain securities. Antidilutive securities are excluded from diluted EPS to prevent it from exceeding basic EPS. Choice A is incorrect because antidilutive refers to the mathematical effect on EPS, not to the physical reduction in shares outstanding.', 'easy', 1)
;

COMMIT;
