-- Migration: Question generation — FAR batch 47 (30 questions)
-- Date: 2026-03-01
-- Topic: Earnings Per Share
-- Difficulty: 9E / 15M / 6H
-- Bloom's: L1:8 / L2:9 / L3:8 / L4:5

BEGIN;

INSERT INTO questions (section_id, topic, stem, choices, correct_index, explanation, difficulty, cognitive_level)
VALUES

-- Q1: easy / L2 — EPS disclosure for discontinued operations
(2, 'Earnings Per Share', 'Pemberton Inc. reports income from continuing operations of $450,000 and a loss from discontinued operations of $50,000 for the year. The company has 100,000 weighted-average common shares and no preferred stock. How should Pemberton present earnings per share?', '["Report only basic EPS of $4.00 based on net income", "Report only basic EPS of $4.50 based on continuing operations", "Report EPS for both continuing operations ($4.50) and net income ($4.00) on the income statement", "Report a single combined EPS figure with a footnote for discontinued operations"]'::jsonb, 2, 'Under ASC 260-10-45-2, entities must present EPS for income from continuing operations and net income on the face of the income statement. EPS for discontinued operations may be presented on the face or in the notes. Reporting only a single net income figure (choice A) omits required continuing operations detail. A footnote-only approach (choice D) does not satisfy the face-of-statement presentation requirement.', 'easy', 2),

-- Q2: hard / L4 — Two-class method for participating securities
(2, 'Earnings Per Share', 'Glenworth Corp. has net income of $900,000, 200,000 common shares, and 50,000 participating preferred shares that share ratably in undistributed earnings on an as-converted basis (1:1 conversion). Declared dividends total $100,000 ($60,000 common, $40,000 preferred). Under the two-class method, determine basic EPS for common shareholders and evaluate why the treasury stock method would be inappropriate here.', '["$4.00 — undistributed earnings are allocated entirely to common shares", "$3.50 — allocate undistributed earnings pro rata between common and preferred shares", "$4.50 — preferred dividends are simply subtracted from net income", "$3.20 — both declared and undistributed earnings go entirely to common"]'::jsonb, 1, 'Under ASC 260-10-45-61A, the two-class method allocates undistributed earnings between common and participating securities based on participation rights. Undistributed earnings = $900,000 − $100,000 = $800,000, allocated 200/250 to common = $640,000. Basic EPS = ($60,000 + $640,000) / 200,000 = $3.50. Choice C incorrectly applies the standard preferred-dividend-subtraction method, ignoring participation rights. The treasury stock method applies only to options and warrants, not participating securities.', 'hard', 4),

-- Q3: medium / L3 — Mid-year actual conversion of bonds affecting basic EPS
(2, 'Earnings Per Share', 'Brixton Industries has $500,000 of 8% convertible bonds outstanding on January 1. On July 1, all bondholders convert into 20,000 common shares. Brixton had 100,000 common shares outstanding before conversion and net income of $800,000. The tax rate is 25%. Apply the appropriate EPS rules to determine how the conversion affects the basic EPS denominator.', '["The weighted-average shares include 10,000 incremental shares (20,000 x 6/12) from the conversion date", "The full 20,000 shares are included for the entire year as a retroactive adjustment", "No adjustment is needed because converted shares are excluded from the current period", "The weighted-average shares include 20,000 incremental shares for the full year using the if-converted method"]'::jsonb, 0, 'Under ASC 260-10-45-10, when convertible securities are actually converted during the period, the resulting common shares are included in basic EPS from the conversion date. The 20,000 shares are weighted for 6/12, adding 10,000 to the weighted average. Choice B is incorrect because retroactive treatment applies only to stock splits and stock dividends, not to conversions. The if-converted method (choice D) applies to diluted EPS hypothetical conversions, not actual conversions.', 'medium', 3),

-- Q4: medium / L2 — Stock compensation shares issued mid-year
(2, 'Earnings Per Share', 'Waverly Corp. has 150,000 shares outstanding on January 1. On April 1, Waverly issues 6,000 restricted shares to employees as part of a stock compensation plan. The shares are fully vested at issuance. What is the weighted-average number of common shares for computing basic EPS?', '["150,000", "156,000", "150,000 plus a pro rata portion based on the vesting period", "154,500"]'::jsonb, 3, 'Under ASC 260-10-45-10, shares issued during a period are included in the weighted-average from the date they are issued. The 6,000 shares are weighted 9/12 (April 1 to December 31) = 4,500. Total WACSO = 150,000 + 4,500 = 154,500. Choice B incorrectly assumes the shares were outstanding the full year. Because the shares are fully vested at issuance, no vesting period adjustment is needed — choice C conflates vesting with date of issuance.', 'medium', 2),

-- Q5: medium / L3 — Written put options and reverse treasury stock method
(2, 'Earnings Per Share', 'Oakdale Inc. has 300,000 common shares outstanding and net income of $600,000. The company wrote put options obligating it to repurchase 15,000 shares at $50 per share. The average market price during the period was $40. Apply the reverse treasury stock method to determine the effect on diluted EPS.', '["The put options are antidilutive because the exercise price exceeds the market price, so they are excluded", "The put options add 15,000 shares to the denominator", "The put options add 3,750 incremental shares to the denominator, making diluted EPS lower than basic EPS", "The put options reduce the numerator by $150,000"]'::jsonb, 2, 'Under ASC 260-10-45-35, written put options that are in the money (exercise price > market price) are dilutive. Using the reverse treasury stock method: proceeds to repurchase = 15,000 x $50 = $750,000; shares repurchased at market = $750,000 / $40 = 18,750; incremental shares = 18,750 − 15,000 = 3,750 added to the denominator. Choice A is incorrect because written puts are dilutive when the exercise price exceeds the market price, unlike call options. Choice B incorrectly adds all 15,000 without applying the reverse treasury stock method.', 'medium', 3),

-- Q6: easy / L1 — Definition of complex capital structure
(2, 'Earnings Per Share', 'Under ASC 260, what defines a complex capital structure?', '["The entity has more than one class of common stock", "The entity has outstanding potentially dilutive securities", "The entity has convertible debt exceeding 10% of total liabilities", "The entity reports both continuing and discontinued operations"]'::jsonb, 1, 'Under ASC 260-10-15-2, a complex capital structure exists when an entity has outstanding securities that could potentially dilute EPS, such as stock options, warrants, or convertible securities. A simple capital structure has only common stock and possibly nonconvertible preferred. Choice A is incorrect because multiple classes of common stock alone do not make the structure complex — what matters is whether dilutive potential shares exist.', 'easy', 1),

-- Q7: medium / L3 — Retrospective adjustment for post-period stock dividend
(2, 'Earnings Per Share', 'Hartwell Corp. reports basic EPS of $5.00 for Year 1 based on 200,000 weighted-average shares. On February 15 of Year 2 (before the Year 1 financial statements are issued), Hartwell declares a 20% stock dividend. Apply the EPS restatement rules to determine how Year 1 EPS should be presented in the Year 1 financial statements.', '["Restate Year 1 EPS to $4.17 using 240,000 adjusted shares", "Present Year 1 EPS as $5.00 with a footnote about the subsequent stock dividend", "Restate Year 1 EPS to $4.00 using 250,000 shares", "No adjustment — the stock dividend affects only Year 2 EPS"]'::jsonb, 0, 'Under ASC 260-10-55-12, stock dividends and splits occurring after the balance sheet date but before financial statements are issued must be retroactively reflected in all EPS calculations. Adjusted shares = 200,000 x 1.20 = 240,000. Restated EPS = $1,000,000 / 240,000 = $4.17. Choice D is incorrect because ASC 260 requires retrospective treatment for comparability. A footnote-only approach (choice B) does not satisfy the retroactive restatement requirement.', 'medium', 3),

-- Q8: medium / L2 — Preferred dividends exceeding net income
(2, 'Earnings Per Share', 'Dunmore Co. reports net income of $120,000 with 80,000 weighted-average common shares outstanding. Dunmore has cumulative preferred stock requiring annual dividends of $180,000. No preferred dividends were declared. What is basic EPS?', '["$1.50", "($0.75)", "$0.00", "$1.50 with a footnote about undeclared dividends"]'::jsonb, 1, 'Under ASC 260-10-45-11, cumulative preferred dividends are deducted from net income whether or not declared. Earnings available to common = $120,000 − $180,000 = ($60,000). Basic EPS = ($60,000) / 80,000 = ($0.75). Choice A ignores the preferred dividend deduction entirely. Choice C incorrectly assumes EPS cannot be negative. Even though dividends were not declared, the cumulative feature requires deduction from the EPS numerator.', 'medium', 2),

-- Q9: hard / L4 — Anti-dilutive security sequencing with exclusion
(2, 'Earnings Per Share', 'Pinecrest Corp. reports net income of $1,000,000 with 250,000 common shares. It has three potentially dilutive securities: (1) stock options adding 8,000 incremental shares with no numerator effect; (2) $300,000 face, 6% convertible bonds converting into 25,000 shares (tax rate 25%); and (3) $500,000 face, 12% convertible bonds converting into 5,000 shares (tax rate 25%). Evaluate the sequencing of securities and determine diluted EPS.', '["$3.49 — include all three securities", "$3.68 — include only the stock options and 12% bonds", "$3.88 — include only the stock options", "$3.58 — include the options and 6% bonds; the 12% bonds are antidilutive"]'::jsonb, 3, 'Under ASC 260-10-45-21, securities are ranked by per-share dilutive impact: options ($0.00), 6% bonds ($0.54), 12% bonds ($9.00). After including options and 6% bonds, EPS = ($1,000,000 + $13,500) / (258,000 + 25,000) = $3.58. The 12% bonds'' per-share impact ($45,000 / 5,000 = $9.00) exceeds $3.58, so they are antidilutive and excluded. Choice A incorrectly includes the antidilutive 12% bonds. The sequencing requirement ensures each security is tested incrementally.', 'hard', 4),

-- Q10: hard / L4 — Noncontrolling interest and consolidated EPS
(2, 'Earnings Per Share', 'Highland Group reports consolidated net income of $2,000,000, of which $300,000 is attributable to noncontrolling interests. Highland has 400,000 weighted-average common shares and $80,000 in cumulative preferred dividends. Evaluate how noncontrolling interests and preferred dividends interact to determine consolidated basic EPS.', '["$4.05", "$4.80", "$5.00", "$4.25"]'::jsonb, 0, 'Under ASC 260-10-45-11, consolidated EPS is based on income attributable to the parent entity, not total consolidated income. Parent income = $2,000,000 − $300,000 = $1,700,000. After deducting preferred dividends: $1,700,000 − $80,000 = $1,620,000. Basic EPS = $1,620,000 / 400,000 = $4.05. Choice B ($4.80) uses consolidated income minus preferred without removing NCI. Choice D fails to deduct preferred dividends from the parent''s income.', 'hard', 4),

-- Q11: medium / L2 — Contingently issuable shares when condition NOT met
(2, 'Earnings Per Share', 'Felton Corp. agreed to issue 25,000 additional shares to former shareholders of an acquired company if Felton''s revenue exceeds $50 million by Year 3. At the end of Year 1, revenue is $38 million and the condition has not been met. How are the 25,000 contingent shares treated for basic EPS in Year 1?', '["Include all 25,000 shares in the weighted-average denominator", "Include a proportional estimate (76%) based on revenue progress", "Exclude the shares from the basic EPS calculation", "Include the shares in basic EPS but disclose the contingency"]'::jsonb, 2, 'Under ASC 260-10-45-48, contingently issuable shares are included in basic EPS only when all necessary conditions have been met. Since Felton''s revenue of $38 million has not reached the $50 million target, the shares are excluded from the basic EPS denominator. Choice A incorrectly includes shares for which the contingency is unresolved. A proportional approach (choice B) is not permitted — the condition is binary, not prorated.', 'medium', 2),

-- Q12: medium / L2 — Forward purchase contract and reverse treasury stock method
(2, 'Earnings Per Share', 'Caldwell Inc. has 200,000 common shares outstanding and net income of $800,000. Caldwell entered into a forward contract obligating it to repurchase 10,000 of its own shares at $60 per share. The average market price during the year was $50. How does this contract affect diluted EPS?', '["The contract is antidilutive because it reduces share count and is excluded", "The contract adds 2,000 incremental shares to the denominator using the reverse treasury stock method", "The contract reduces the denominator by 10,000 shares", "The contract has no effect on diluted EPS because no shares have been repurchased"]'::jsonb, 1, 'Under ASC 260-10-45-35, forward purchase contracts where the repurchase price exceeds the market price are treated like written put options. Using the reverse treasury stock method: assumed proceeds = 10,000 x $60 = $600,000; shares assumed repurchased at market = $600,000 / $50 = 12,000; incremental shares = 12,000 − 10,000 = 2,000 added to denominator. Choice C incorrectly reduces the denominator. Contracts requiring repurchase above market price are dilutive, not antidilutive (choice A).', 'medium', 2),

-- Q13: medium / L2 — Options exercised mid-year split treatment
(2, 'Earnings Per Share', 'Lexington Inc. has 180,000 shares outstanding and 12,000 stock options with an exercise price of $25. The average market price is $50. On September 1, all 12,000 options are exercised. For diluted EPS, how are the options treated for the period before exercise?', '["Apply the treasury stock method for January 1 through August 31, adding incremental shares for 8/12 of the year", "Ignore the options entirely because they were exercised during the year", "Apply the treasury stock method for the full year as if the options remained outstanding", "Include all 12,000 shares for the full year since they were eventually exercised"]'::jsonb, 0, 'Under ASC 260-10-45-26, when options are exercised during a period, the treasury stock method applies for the portion before exercise. From January through August (8 months), incremental shares = 12,000 − (12,000 x $25 / $50) = 6,000, weighted 8/12 = 4,000. From September onward, the 12,000 actual shares are in basic EPS. Choice B ignores the pre-exercise dilutive effect. Choice C overstates dilution by applying the method for the full year.', 'medium', 2),

-- Q14: medium / L3 — Rights issuance below fair value bonus element
(2, 'Earnings Per Share', 'Monroe Corp. has 400,000 shares outstanding and issues rights to existing shareholders allowing them to purchase one new share for every four held at $30 per share when the market price is $50. All rights are exercised on October 1. Determine how the bonus element in the rights offering affects the weighted-average shares for basic EPS.', '["Include 100,000 new shares weighted 3/12 with no adjustment for the bonus element", "Include 100,000 new shares for the full year since rights offerings are treated like stock dividends", "Apply an adjustment factor to the pre-rights shares to reflect the below-market element, then weight the new shares from October 1", "Exclude the bonus element and weight only the cash-paid portion of the new shares"]'::jsonb, 2, 'Under ASC 260-10-55-20, when rights are issued at below fair value, the offering contains a bonus element similar to a stock dividend. A theoretical ex-rights price is computed, and a ratio of the fair value to the ex-rights price is applied retroactively to all pre-rights shares. New shares are then weighted from the exercise date. Choice A ignores the bonus element entirely. Choice B incorrectly treats the entire issuance as retroactive — only the bonus portion receives retroactive treatment.', 'medium', 3),

-- Q15: medium / L2 — Convertible preferred if-converted method numerator add-back
(2, 'Earnings Per Share', 'Ridgeway Corp. has net income of $750,000, 200,000 weighted-average common shares, and 10,000 shares of $50 par, 8% convertible preferred stock. Each preferred share converts into 3 common shares. What is diluted EPS using the if-converted method?', '["$3.55", "$3.75", "$3.09", "$3.26"]'::jsonb, 3, 'Under ASC 260-10-45-40, the if-converted method for convertible preferred stock adds back preferred dividends to the numerator and adds converted shares to the denominator. Preferred dividends = 10,000 x $50 x 8% = $40,000. Diluted numerator = $750,000 (no deduction). Diluted denominator = 200,000 + 30,000 = 230,000. Diluted EPS = $750,000 / 230,000 = $3.26. Choice C ($3.09) deducts preferred dividends while also adding converted shares — double-counting the dilution.', 'medium', 2),

-- Q16: easy / L1 — Definition of weighted-average common shares
(2, 'Earnings Per Share', 'What does the term ''weighted-average common shares outstanding'' mean in EPS calculations?', '["Shares outstanding weighted by the fraction of the reporting period they were outstanding", "The total shares outstanding at the end of the reporting period", "The average of beginning and ending shares outstanding", "The maximum number of shares outstanding during any point in the period"]'::jsonb, 0, 'Under ASC 260-10-45-10, weighted-average common shares outstanding reflects the number of shares weighted by the portion of the period they were outstanding. This accounts for shares issued or repurchased during the period. Choice B uses only the ending balance, which ignores mid-period changes. Choice C is a simplified average that does not properly weight shares for partial-period transactions.', 'easy', 1),

-- Q17: hard / L3 — Unvested RSUs as dilutive potential shares
(2, 'Earnings Per Share', 'Stratton Inc. granted 20,000 restricted stock units (RSUs) to employees on January 1. The RSUs vest over three years and are subject to continued service. Stratton''s average market price is $60, and the average unrecognized compensation cost per RSU is $18 during the year. Using the treasury stock method, determine the incremental shares added to diluted EPS.', '["20,000 shares — all unvested RSUs are included as if fully outstanding", "14,000 incremental shares", "6,000 incremental shares", "0 shares — unvested RSUs are excluded from diluted EPS until they vest"]'::jsonb, 1, 'Under ASC 260-10-45-28A, unvested share-based payment awards are treated as potential common shares using the treasury stock method. Assumed proceeds include unrecognized compensation cost. Assumed proceeds = 20,000 x $18 = $360,000. Shares repurchased at market = $360,000 / $60 = 6,000. Incremental shares = 20,000 − 6,000 = 14,000. Choice C reverses the incremental share calculation. Choice D is incorrect because unvested awards are included in diluted EPS as potential shares even before vesting.', 'hard', 3),

-- Q18: easy / L1 — Basic EPS numerator definition
(2, 'Earnings Per Share', 'What is the numerator used to calculate basic earnings per share?', '["Net income", "Comprehensive income minus preferred dividends", "Net income minus preferred dividends", "Operating income minus preferred dividends"]'::jsonb, 2, 'Under ASC 260-10-45-11, the numerator for basic EPS is income available to common shareholders, calculated as net income minus preferred dividends (both declared and, for cumulative preferred, undeclared). Choice A omits the preferred dividend deduction. Choice B incorrectly uses comprehensive income, which includes OCI items that are not part of the EPS numerator under ASC 260.', 'easy', 1),

-- Q19: easy / L1 — Entities required to present EPS
(2, 'Earnings Per Share', 'Under U.S. GAAP, which entities are required to present earnings per share on the income statement?', '["All entities that prepare financial statements in conformity with GAAP", "Only public business entities", "All entities with more than $10 million in revenue", "Only entities with complex capital structures"]'::jsonb, 1, 'Under ASC 260-10-15-2, EPS presentation requirements apply only to public business entities — those with publicly traded equity or debt securities or that are SEC registrants. Private companies are exempt from presenting EPS. Choice A is overly broad since private entities are not required to present EPS. Choice D incorrectly limits the requirement to complex capital structures when all public entities must present EPS.', 'easy', 1),

-- Q20: hard / L4 — Two-class method distributed vs undistributed earnings
(2, 'Earnings Per Share', 'Westgate Corp. has net income of $1,200,000 with 300,000 common shares and 100,000 participating preferred shares that participate equally in undistributed earnings on a per-share basis. Declared dividends total $280,000 ($200,000 common, $80,000 preferred). Evaluate the allocation of undistributed earnings and calculate basic EPS for common shareholders using the two-class method.', '["$3.73 — allocate undistributed earnings entirely to common stock", "$3.33 — divide total net income equally among all shares", "$2.97 — allocate undistributed earnings proportionally between common and preferred", "$3.07 — subtract all dividends from net income before dividing by common shares"]'::jsonb, 2, 'Under ASC 260-10-45-61A, the two-class method separates distributed and undistributed earnings. Undistributed = $1,200,000 − $280,000 = $920,000. Common share of undistributed = 300,000 / 400,000 x $920,000 = $690,000. Common EPS = ($200,000 + $690,000) / 300,000 = $2.97. Choice A ($3.73) ignores preferred participation in undistributed earnings. Choice D ($3.07) uses simple dividend subtraction ($920,000 / 300,000) instead of the required two-class allocation.', 'hard', 4),

-- Q21: medium / L2 — Treasury stock repurchase effect on WACSO
(2, 'Earnings Per Share', 'Beacon Corp. has 250,000 shares outstanding on January 1. On August 1, Beacon repurchases 30,000 shares as treasury stock. No other share transactions occur during the year. What is the weighted-average number of common shares for basic EPS?', '["220,000", "250,000", "240,000", "237,500"]'::jsonb, 3, 'Under ASC 260-10-45-10, treasury shares reduce the weighted-average from the repurchase date. Shares outstanding: 250,000 for 7/12 (Jan–Jul) and 220,000 for 5/12 (Aug–Dec). WACSO = (250,000 x 7/12) + (220,000 x 5/12) = 145,833 + 91,667 = 237,500. Choice A uses only the ending balance. Choice C uses an incorrect weighting period. Treasury stock repurchases are weighted from the repurchase date, unlike stock dividends which are retroactive.', 'medium', 2),

-- Q22: easy / L1 — Definition of diluted EPS
(2, 'Earnings Per Share', 'What does diluted earnings per share represent?', '["Earnings per share using only shares outstanding at the end of the period", "Earnings per share before deducting preferred dividends", "Earnings per share using the highest share count during the period", "Earnings per share reflecting maximum potential dilution from all dilutive securities"]'::jsonb, 3, 'Under ASC 260-10-45-16, diluted EPS reflects the potential dilution from securities that could result in additional common shares, such as stock options, warrants, and convertible securities. It assumes conversion or exercise of all dilutive potential common shares. Choice A describes only actual shares, not potential dilution. Choice C conflates the peak share count with the dilutive impact of potential shares.', 'easy', 1),

-- Q23: easy / L1 — Definition of antidilutive security
(2, 'Earnings Per Share', 'Under ASC 260, what is an antidilutive security?', '["A security whose inclusion would increase EPS or decrease loss per share", "A security whose inclusion would decrease EPS", "A security that has been retired during the period", "A security that cannot be converted into common stock"]'::jsonb, 0, 'Under ASC 260-10-20, an antidilutive security is one whose assumed conversion or exercise would increase EPS or decrease loss per share. Such securities are excluded from diluted EPS because their inclusion would not represent potential dilution. Choice B describes a dilutive security — one that decreases EPS. Choice D is incorrect because convertibility is not the distinguishing feature; what matters is the effect on the EPS calculation.', 'easy', 1),

-- Q24: medium / L3 — Convertible bonds that are antidilutive
(2, 'Earnings Per Share', 'Palmer Corp. reports basic EPS of $2.00 based on net income of $400,000 and 200,000 shares. It has $1,000,000 face value, 10% convertible bonds, each $1,000 bond converting into 10 shares (tax rate 25%). Determine whether the convertible bonds are dilutive or antidilutive and explain the impact on diluted EPS.', '["Dilutive — diluted EPS drops to $1.97", "Antidilutive — the per-share impact of $7.50 exceeds basic EPS of $2.00", "Dilutive — diluted EPS drops to $1.80 after including the bonds", "Antidilutive — all convertible bonds are excluded from diluted EPS by default"]'::jsonb, 1, 'Under ASC 260-10-45-17, convertible securities are antidilutive when their per-share impact exceeds basic EPS. Bond interest saved (net of tax) = $1,000,000 x 10% x (1 − 0.25) = $75,000. Additional shares = 1,000 bonds x 10 = 10,000. Per-share impact = $75,000 / 10,000 = $7.50. Since $7.50 > $2.00, inclusion would increase EPS, making the bonds antidilutive. Choice D wrongly implies all convertible bonds are excluded regardless of calculation.', 'medium', 3),

-- Q25: hard / L4 — Post-period stock split retrospective restatement
(2, 'Earnings Per Share', 'In Year 1, Thornberry Inc. reported basic EPS of $6.00 (net income $1,800,000; 300,000 weighted-average shares) and diluted EPS of $5.40 (333,333 diluted shares). On January 20 of Year 2, before Year 1 financial statements are issued, Thornberry declares a 3-for-1 stock split. Evaluate how the stock split affects the EPS amounts presented in the Year 1 financial statements.', '["Restate Year 1 basic EPS to $2.00 and diluted EPS to $1.80", "Present Year 1 EPS as originally calculated with a footnote about the subsequent split", "Restate basic EPS to $2.00 but leave diluted EPS at $5.40", "Present basic EPS of $6.00 and diluted EPS of $5.40 because splits only affect future periods"]'::jsonb, 0, 'Under ASC 260-10-55-12, stock splits occurring after the balance sheet date but before financial statements are issued must be retroactively reflected in all EPS calculations. Adjusted basic shares = 300,000 x 3 = 900,000; basic EPS = $1,800,000 / 900,000 = $2.00. Adjusted diluted shares = 333,333 x 3 = 999,999; diluted EPS ≈ $1.80. Both basic and diluted must be restated. Choice B is incorrect — a footnote alone does not satisfy the retroactive restatement requirement.', 'hard', 4),

-- Q26: easy / L1 — ASC 260 as authoritative guidance
(2, 'Earnings Per Share', 'Which section of the FASB Accounting Standards Codification provides guidance on earnings per share?', '["ASC 220", "ASC 250", "ASC 260", "ASC 280"]'::jsonb, 2, 'ASC 260, Earnings Per Share, provides comprehensive guidance on computing and presenting basic and diluted EPS. ASC 220 covers comprehensive income, ASC 250 addresses accounting changes and error corrections, and ASC 280 covers segment reporting. Candidates should associate ASC 260 with all EPS-related requirements including the treasury stock method, if-converted method, and presentation rules.', 'easy', 1),

-- Q27: medium / L3 — Interim period EPS computation
(2, 'Earnings Per Share', 'Greystone Inc. reports the following quarterly data: Q1 net income $200,000 with 100,000 shares, Q2 net income $300,000 with 120,000 shares (new shares issued April 1). No preferred stock exists. Apply the ASC 260 interim EPS rules to determine EPS for Q2 and for the six months ended June 30.', '["Q2 EPS = $2.50; six-month EPS = $2.50", "Q2 EPS = $2.50; six-month EPS = $4.55", "Q2 EPS = $2.27; six-month EPS = $4.55", "Q2 EPS = $2.50; six-month EPS = $2.27"]'::jsonb, 1, 'Under ASC 260-10-45-1, EPS is computed independently for each period presented. Q2 EPS = $300,000 / 120,000 = $2.50. For the six months ended June 30, WACSO = (100,000 x 3/6) + (120,000 x 3/6) = 110,000. Six-month EPS = $500,000 / 110,000 = $4.55. Choice D incorrectly assumes year-to-date EPS equals the average of quarterly figures. Each period uses its own weighted-average shares independently.', 'medium', 3),

-- Q28: easy / L1 — Where EPS is reported
(2, 'Earnings Per Share', 'Under U.S. GAAP, where must earnings per share be reported?', '["Only in the notes to the financial statements", "In the management discussion and analysis section", "On the statement of cash flows", "On the face of the income statement"]'::jsonb, 3, 'Under ASC 260-10-45-2, EPS must be presented on the face of the income statement for all periods presented. Presenting EPS solely in the notes (choice A) does not satisfy this requirement. The income statement is the required location, ensuring prominence and comparability for users of the financial statements. The MD&A section (choice B) is a non-GAAP supplement that does not replace financial statement presentation.', 'easy', 1),

-- Q29: medium / L3 — Contingent consideration shares from business combination
(2, 'Earnings Per Share', 'Mercer Corp. acquired Dalton Co. and agreed to issue 40,000 additional shares if Dalton''s annual operating income exceeds $3 million in any year through Year 3. In Year 1, Dalton''s operating income is $4.2 million, but the contractual measurement date has not yet been reached. Determine how these shares are treated for diluted EPS in Year 1.', '["Include the 40,000 shares in diluted EPS because current-period earnings satisfy the condition", "Exclude the shares from both basic and diluted EPS until the measurement date", "Include a prorated portion based on progress toward the contractual measurement date", "Include the 40,000 shares in basic EPS because the condition has been substantively met"]'::jsonb, 0, 'Under ASC 260-10-45-52, contingently issuable shares based on earnings are included in diluted EPS if current-period earnings would satisfy the contingency as if the period-end were the end of the contingency period. Year 1 operating income of $4.2 million exceeds the $3 million target, so all 40,000 shares are included in diluted EPS. Choice B incorrectly withholds shares from diluted EPS despite current earnings meeting the threshold. Choice D is wrong because contingent shares enter basic EPS only when all conditions are actually met.', 'medium', 3),

-- Q30: medium / L2 — Mandatorily redeemable preferred stock and EPS
(2, 'Earnings Per Share', 'Silverton Corp. has net income of $500,000 and 125,000 weighted-average common shares. The company has 5,000 shares of mandatorily redeemable preferred stock classified as a liability under ASC 480. Annual preferred dividends of $60,000 are reported as interest expense. How is the mandatorily redeemable preferred treated for basic EPS?', '["Deduct $60,000 as preferred dividends from the numerator", "Exclude the preferred stock from the EPS calculation entirely", "No additional numerator adjustment is needed because the cost is already in interest expense", "Add back $60,000 to the numerator because liability-classified preferred is excluded from EPS"]'::jsonb, 2, 'Under ASC 480-10-25-4, mandatorily redeemable preferred stock classified as a liability results in its dividends being treated as interest expense in the income statement. Since the cost is already reflected in net income as interest expense, no separate deduction from the EPS numerator is needed. Choice A double-counts the preferred cost by deducting it again as a dividend. The key distinction is liability classification versus equity classification of the preferred stock.', 'medium', 2)
;

COMMIT;
