-- Migration: Question generation — FAR batch 46 (30 questions)
-- Date: 2026-03-01
-- Topic: Earnings Per Share
-- Difficulty: 9E / 15M / 6H
-- Bloom's: L1:8 / L2:9 / L3:8 / L4:5

BEGIN;

INSERT INTO questions (section_id, topic, stem, choices, correct_index, explanation, difficulty, cognitive_level)
VALUES

-- Q1: medium / L2 — Reverse stock split retroactive treatment on weighted-average shares
(2, 'Earnings Per Share', 'Pemberton Industries has 300,000 shares outstanding on January 1. On June 1, the company executes a 1-for-3 reverse stock split. No other share transactions occur during the year. What is the weighted-average number of common shares outstanding for the year?', '["100,000", "200,000", "166,667", "300,000"]'::jsonb, 0, 'Under ASC 260-10-55-12, reverse stock splits are applied retroactively to all periods presented, identical to forward stock splits and stock dividends. The 1-for-3 reverse split reduces all shares to one-third, producing a weighted-average of 100,000 for the entire year. Choice D (300,000) incorrectly treats the reverse split as prospective rather than retroactive, ignoring the mandatory restatement requirement.', 'medium', 2),

-- Q2: easy / L1 — Simple capital structure definition
(2, 'Earnings Per Share', 'Which type of capital structure requires a company to present only basic EPS on the income statement?', '["A complex capital structure", "A diluted capital structure", "A simple capital structure", "A hybrid capital structure"]'::jsonb, 2, 'Under ASC 260-10-45-2, entities with simple capital structures—those with only common stock outstanding and no potentially dilutive securities—present only basic EPS. A complex capital structure (choice A) must present both basic and diluted EPS because it includes securities such as convertible bonds, options, or warrants that could potentially dilute earnings per share.', 'easy', 1),

-- Q3: medium / L2 — Shares issued in a business combination weighted-average
(2, 'Earnings Per Share', 'Meridian Corp. has 150,000 shares outstanding all year. On September 1, Meridian acquires Redfield Inc. by issuing 60,000 shares of common stock. No other share transactions occur. What is the weighted-average number of shares for basic EPS?', '["170,000", "190,000", "180,000", "210,000"]'::jsonb, 0, 'Under ASC 260-10-45-10, shares issued in a business combination are included in the weighted-average from the acquisition date. The 60,000 shares are weighted for 4/12 of the year (September through December): 150,000 + (60,000 x 4/12) = 170,000. Choice B (190,000) incorrectly weights the new shares for 8/12, reversing the pre- and post-acquisition periods.', 'medium', 2),

-- Q4: medium / L3 — Retroactive restatement of prior-year EPS for stock dividend
(2, 'Earnings Per Share', 'Fairview Industries reported basic EPS of $2.50 in its originally issued Year 1 financial statements based on net income of $500,000 and 200,000 weighted-average shares. In Year 2, the company declared a 20% stock dividend. What is the effect on the comparative Year 1 basic EPS figure when presented alongside Year 2?', '["Year 1 EPS remains $2.50 because stock dividends only affect future periods", "Year 1 EPS is restated to $3.00 because the stock dividend reduces the denominator", "Year 1 EPS is restated to $2.00 because the additional shares increase the denominator retroactively", "Year 1 EPS is restated to $2.08 because the 20% stock dividend is retroactively applied"]'::jsonb, 3, 'Under ASC 260-10-55-12, stock dividends are applied retroactively to all prior periods presented. Year 1 weighted-average shares are restated from 200,000 to 240,000 (200,000 x 1.20), producing restated EPS of $2.08 ($500,000 / 240,000). Choice A incorrectly assumes stock dividends affect only prospective periods, ignoring the mandatory retroactive restatement that ensures period-to-period comparability.', 'medium', 3),

-- Q5: medium / L3 — Participating securities and two-class method requirement
(2, 'Earnings Per Share', 'Northgate Enterprises has net income of $900,000, 100,000 common shares, and 25,000 shares of participating preferred stock entitled to share equally in dividends above the stated $4 per share preferred rate. The company declares $8 per share to common shareholders. Under ASC 260, what is the most likely effect of the participating preferred stock on the basic EPS calculation?', '["Basic EPS is calculated using only common shares since preferred dividends are simply deducted", "Basic EPS is unaffected because participating securities only impact diluted EPS", "Basic EPS must be calculated using the two-class method, which allocates undistributed earnings to the preferred stock", "Basic EPS is calculated by including participating preferred shares in the weighted-average denominator"]'::jsonb, 2, 'Under ASC 260-10-45-59A, participating securities that may share in undistributed earnings require the two-class method for basic EPS. Undistributed earnings are allocated between common and participating preferred shares based on their respective participation rights. Choice A incorrectly treats participating preferred like non-participating preferred, which requires only a simple dividend deduction from the numerator.', 'medium', 3),

-- Q6: medium / L2 — Convertible preferred stock if-converted method full calculation
(2, 'Earnings Per Share', 'Holloway Corp. reports net income of $750,000 with 200,000 weighted-average common shares. The company has 10,000 shares of $100 par, 7% cumulative convertible preferred stock, each convertible into 5 common shares. What is diluted EPS under the if-converted method?', '["$2.72 per share", "$3.40 per share", "$3.75 per share", "$3.00 per share"]'::jsonb, 3, 'Under ASC 260-10-45-21, the if-converted method for convertible preferred stock adds back preferred dividends ($70,000) to the numerator and adds converted shares (10,000 x 5 = 50,000) to the denominator. Diluted EPS = $750,000 / 250,000 = $3.00. Since $3.00 is less than basic EPS of $3.40, the conversion is dilutive and must be included. Choice A ($2.72) incorrectly fails to add back preferred dividends, dividing $680,000 by 250,000.', 'medium', 2),

-- Q7: medium / L3 — Loss from continuing operations as control number for dilution testing
(2, 'Earnings Per Share', 'Crestview Holdings reports a loss from continuing operations of $180,000, income from discontinued operations (net of tax) of $300,000, and net income of $120,000 with 60,000 weighted-average common shares. The company has 5,000 dilutive stock options outstanding. How should the potentially dilutive securities be treated when computing diluted EPS?', '["The stock options are excluded from diluted EPS for all line items because the control number shows a loss from continuing operations", "The stock options are included in diluted EPS for both continuing operations and discontinued operations", "The stock options are included for discontinued operations only but excluded for continuing operations", "The stock options are excluded only for continuing operations and included for net income"]'::jsonb, 0, 'Under ASC 260-10-45-19, income (loss) from continuing operations serves as the control number for determining dilution. Because Crestview reports a loss from continuing operations, including the options would reduce the loss per share (antidilutive), so they are excluded from diluted EPS for all line items. Choice B incorrectly includes options despite the loss control number, which would improperly reduce the reported per-share loss.', 'medium', 3),

-- Q8: hard / L4 — Evaluate inclusion sequence when convertible bonds become antidilutive
(2, 'Earnings Per Share', 'Beckett Manufacturing reports net income of $800,000 and 200,000 weighted-average common shares (basic EPS of $4.00). The company has two potentially dilutive securities: (1) 20,000 stock options with an exercise price of $25 and an average market price of $50, producing 10,000 incremental shares via the treasury stock method; and (2) $1,000,000 of 8% convertible bonds (25% tax rate) convertible into 12,000 shares. Evaluate the correct inclusion sequence and determine diluted EPS.', '["$3.81 per share", "$3.87 per share", "$3.60 per share", "$4.00 per share"]'::jsonb, 0, 'Under ASC 260-10-45-16, potentially dilutive securities are ranked by per-share impact and included sequentially. Options ($0/share) are included first, reducing EPS to $3.81 ($800,000 / 210,000). The convertible bonds produce a per-share impact of $5.00 ($60,000 after-tax interest / 12,000 shares), exceeding $3.81, making them antidilutive and excluded. Choice B ($3.87) incorrectly includes the antidilutive bonds, which would actually increase EPS above $3.81.', 'hard', 4),

-- Q9: easy / L1 — Complex capital structure definition
(2, 'Earnings Per Share', 'Under ASC 260, what defines a complex capital structure?', '["A structure with more than two classes of equity securities", "A structure with both common stock and long-term debt outstanding", "A structure with securities that could potentially dilute basic EPS", "A structure with both common and preferred stock outstanding"]'::jsonb, 2, 'Under ASC 260-10-05-3, a complex capital structure includes securities that could potentially dilute basic EPS, such as convertible bonds, convertible preferred stock, stock options, and warrants. An entity with a complex structure must present both basic and diluted EPS. Choice D is incorrect because simply having preferred stock does not create a complex structure unless the preferred is convertible or otherwise potentially dilutive.', 'easy', 1),

-- Q10: medium / L2 — Written put options and reverse treasury stock method
(2, 'Earnings Per Share', 'Silverline Corp. has 200,000 weighted-average shares, net income of $600,000, and written put options on 10,000 of its own shares with an exercise price of $50. The average market price during the year is $40. Using the reverse treasury stock method, how many incremental shares are added to the denominator for diluted EPS?', '["10,000 shares", "2,000 shares", "12,500 shares", "2,500 shares"]'::jsonb, 3, 'Under ASC 260-10-45-35, written put options use the reverse treasury stock method when the exercise price exceeds the average market price. The company is assumed to issue shares at the $40 market price to generate the $500,000 needed ($500,000 / $40 = 12,500 shares issued), then retire 10,000 shares. The net incremental shares are 2,500 (12,500 minus 10,000). Choice A (10,000) incorrectly adds the full option shares without computing the net dilutive increment.', 'medium', 2),

-- Q11: medium / L3 — Effect of treasury stock repurchase on basic EPS
(2, 'Earnings Per Share', 'Granite Peak Corp. has 200,000 shares outstanding on January 1 and reports net income of $600,000 with no preferred stock. On October 1, the company repurchases 24,000 shares as treasury stock at $35 per share. What is the most likely effect of the treasury stock purchase on Granite Peak''s basic EPS compared to if no repurchase had occurred?', '["Basic EPS decreases because the cash outflow reduces net income", "Basic EPS increases because the weighted-average share count decreases", "Basic EPS is unchanged because treasury stock has no effect on EPS until shares are retired", "Basic EPS decreases because the repurchase price exceeds book value per share"]'::jsonb, 1, 'Under ASC 260-10-45-10, treasury stock repurchases reduce the weighted-average shares outstanding from the repurchase date forward. Granite Peak''s weighted-average decreases from 200,000 to 194,000 (200,000 x 9/12 + 176,000 x 3/12), increasing basic EPS from $3.00 to $3.09. Choice A is incorrect because treasury stock purchases reduce equity, not net income—they are a balance sheet transaction, not an income statement charge.', 'medium', 3),

-- Q12: medium / L2 — Warrants using treasury stock method calculation
(2, 'Earnings Per Share', 'Pinecrest Holdings has 150,000 weighted-average shares and net income of $525,000. The company has 12,000 outstanding warrants with an exercise price of $30. The average market price during the year was $45. What is diluted EPS?', '["$3.50 per share", "$3.24 per share", "$3.41 per share", "$3.32 per share"]'::jsonb, 2, 'Under ASC 260-10-45-22, warrants are treated like options using the treasury stock method. Assumed exercise proceeds = 12,000 x $30 = $360,000; assumed shares repurchased at market = $360,000 / $45 = 8,000; incremental shares = 12,000 minus 8,000 = 4,000. Diluted EPS = $525,000 / 154,000 = $3.41. Choice B ($3.24) incorrectly adds all 12,000 warrant shares to the denominator without applying the treasury stock repurchase offset.', 'medium', 2),

-- Q13: easy / L1 — EPS reporting requirement for public vs private entities
(2, 'Earnings Per Share', 'Which entities are required to report earnings per share on the face of the income statement under U.S. GAAP?', '["All entities that prepare financial statements under GAAP", "All entities with more than $500,000 in net income", "All not-for-profit organizations and governmental entities", "Public business entities with common stock or potential common stock traded in a public market"]'::jsonb, 3, 'Under ASC 260-10-15-2, EPS presentation is required only for public business entities that have issued common stock or potential common stock traded in a public market. Private entities are not required to report EPS, though they may do so voluntarily. Choice A is incorrect because private companies, not-for-profit entities, and governmental entities are generally exempt from the EPS reporting requirements of ASC 260.', 'easy', 1),

-- Q14: medium / L3 — Effect of preferred dividends in arrears on cumulative multi-year EPS
(2, 'Earnings Per Share', 'Westbrook Industries has net income of $400,000 and 100,000 weighted-average shares. The company has 5,000 shares of $100 par, 8% cumulative preferred stock. No preferred dividends were declared in Year 1 or Year 2. In Year 3, all arrearages plus the current year dividend are paid. What is Year 3 basic EPS?', '["$3.60, the same as Years 1 and 2, because only the current year''s preferred dividend is deducted", "$2.40, because all three years of preferred dividends ($120,000) are deducted in the payment year", "$4.00, because no preferred deduction applies when dividends are finally paid in arrears", "$1.60, because total cash dividends paid reduce the EPS numerator"]'::jsonb, 0, 'Under ASC 260-10-45-11, for cumulative preferred stock, only the current period''s dividend is deducted from the basic EPS numerator each year—regardless of whether declared—because prior years'' dividends were already deducted in their respective periods. Year 3 basic EPS is $3.60 ($400,000 minus $40,000) / 100,000. Choice B ($2.40) incorrectly deducts all three years of dividends in the payment year, double-counting prior deductions.', 'medium', 3),

-- Q15: hard / L4 — Evaluate contingently issuable shares with cumulative earnings condition
(2, 'Earnings Per Share', 'Oakmont Enterprises reports net income of $1,500,000 and 400,000 weighted-average shares. A contingent share agreement requires issuance of 50,000 additional shares if cumulative net income over a three-year period exceeds $4,000,000. After Year 2, cumulative net income is $3,800,000. Year 3 net income brings the cumulative total to $5,300,000. Evaluate whether the contingently issuable shares should be included in Year 3 basic and diluted EPS.', '["The shares are excluded from both basic and diluted EPS because the contingency spans multiple periods", "The shares are included in both basic and diluted EPS because the cumulative condition is met at year-end", "The shares are included in diluted EPS only, but excluded from basic EPS until actually issued", "The shares are included in basic EPS only because the condition is met, but excluded from diluted EPS"]'::jsonb, 1, 'Under ASC 260-10-45-48, contingently issuable shares are included in basic EPS when all necessary conditions are satisfied as of the reporting date. Because Oakmont''s cumulative net income of $5,300,000 exceeds the $4,000,000 threshold at December 31 of Year 3, the 50,000 shares are included in both basic and diluted EPS calculations. Choice C incorrectly excludes the shares from basic EPS; once the condition is met at the reporting date, inclusion is required regardless of actual issuance timing.', 'hard', 4),

-- Q16: medium / L2 — Mid-year preferred stock issuance effect on basic EPS
(2, 'Earnings Per Share', 'Ridgeline Corp. reports net income of $720,000 and has 180,000 common shares outstanding all year. On July 1, Ridgeline issues 6,000 shares of $50 par, 10% noncumulative preferred stock and declares the preferred dividend for the period outstanding. What is basic EPS for the year?', '["$3.83 per share", "$3.92 per share", "$4.00 per share", "$3.67 per share"]'::jsonb, 1, 'Under ASC 260-10-45-11, declared preferred dividends on noncumulative stock are deducted from the numerator for the period outstanding. The preferred dividend is $15,000 (6,000 x $50 x 10% x 6/12). Basic EPS = ($720,000 minus $15,000) / 180,000 = $3.92. Choice A ($3.83) incorrectly deducts a full year of preferred dividends ($30,000) despite the preferred stock being outstanding for only six months.', 'medium', 2),

-- Q17: hard / L3 — Rights offering with bonus element affecting prior-year EPS restatement
(2, 'Earnings Per Share', 'Elkwood Industries has 500,000 shares outstanding and reported basic EPS of $3.00 for the prior year. On March 1 of the current year, the company completes a rights offering, issuing one new share for every five shares held at a subscription price of $20 per share when the market price was $30. How does the bonus element in the rights offering affect the weighted-average shares used to compute prior-year restated EPS?', '["Prior-year shares are increased by the adjustment factor, reducing restated EPS", "Prior-year shares are decreased by the adjustment factor, increasing restated EPS", "Prior-year shares remain unchanged because rights offerings are not retroactively adjusted", "Prior-year shares are increased by the full number of new shares issued, reducing restated EPS"]'::jsonb, 0, 'Under ASC 260-10-55-23, a rights offering below market price contains a bonus element similar to a stock dividend. The theoretical ex-rights price is $28.33 [(5 x $30 + 1 x $20) / 6], producing an adjustment factor of 1.059 ($30 / $28.33) that increases prior-period weighted-average shares and reduces restated EPS. Choice C is incorrect because the below-market subscription price creates a bonus element requiring retroactive adjustment, unlike a simple issuance at market value.', 'hard', 3),

-- Q18: easy / L1 — Definition of weighted-average shares outstanding
(2, 'Earnings Per Share', 'What does "weighted-average common shares outstanding" measure in the EPS calculation?', '["The total number of shares authorized by the corporate charter", "The number of shares outstanding at the end of the reporting period", "The time-weighted number of shares outstanding during the reporting period", "The total shares issued minus all treasury shares at the beginning of the period"]'::jsonb, 2, 'Under ASC 260-10-45-10, the weighted-average number of common shares outstanding reflects shares weighted by the portion of the period they were outstanding, ensuring EPS reflects the time dimension of capital available to generate earnings. Choice B is incorrect because using only end-of-period shares ignores the timing of share issuances and repurchases throughout the year.', 'easy', 1),

-- Q19: easy / L2 — Simple weighted-average with mid-year share retirement
(2, 'Earnings Per Share', 'Elm Street Holdings has 80,000 shares outstanding on January 1. On April 1, the company retires 12,000 shares. No other transactions occur. What is the weighted-average number of shares for the year?', '["74,000", "71,000", "68,000", "80,000"]'::jsonb, 1, 'Under ASC 260-10-45-10, shares are weighted by the portion of the year outstanding. The 80,000 shares are weighted for 3/12 (January through March), and the post-retirement 68,000 shares for 9/12 (April through December): (80,000 x 3/12) + (68,000 x 9/12) = 71,000. Choice C (68,000) incorrectly uses only the year-end balance without weighting for the time the retired shares were outstanding.', 'easy', 2),

-- Q20: medium / L2 — Convertible bond if-converted method with mid-year actual conversion
(2, 'Earnings Per Share', 'Stonebridge Corp. has net income of $900,000 and 300,000 weighted-average common shares. On January 1, the company had $500,000 of 6% convertible bonds convertible into 20,000 common shares. On July 1, all bonds were converted. The tax rate is 25%. What is diluted EPS?', '["$2.94 per share", "$3.00 per share", "$2.85 per share", "$2.81 per share"]'::jsonb, 0, 'Under ASC 260-10-45-21, when convertible bonds are actually converted mid-year, the if-converted method assumes conversion at the beginning of the period. The numerator adds back after-tax interest for the pre-conversion period ($500,000 x 6% x 6/12 x 0.75 = $11,250), and the denominator adds the 10,000 incremental shares for January through June. Diluted EPS = $911,250 / 310,000 = $2.94. Choice C ($2.85) incorrectly adds the full 20,000 converted shares rather than only the pre-conversion increment.', 'medium', 2),

-- Q21: hard / L4 — Evaluate treatment of convertible participating preferred for basic and diluted EPS
(2, 'Earnings Per Share', 'Highland Capital reports net income of $2,000,000 with 500,000 weighted-average common shares and 100,000 shares of convertible participating preferred stock ($10 par, 6% dividend rate), each convertible into 2 common shares. The preferred shareholders participate equally with common in dividends beyond the stated rate. Evaluate the appropriate method for computing basic and diluted EPS.', '["Basic EPS uses the simple deduction method; diluted EPS uses the if-converted method", "Basic EPS uses the two-class method because the preferred is participating; diluted EPS uses the more dilutive of the two-class or if-converted method", "Basic and diluted EPS both use only the if-converted method because the preferred is convertible", "Basic EPS uses the two-class method; diluted EPS always excludes participating preferred as antidilutive"]'::jsonb, 1, 'Under ASC 260-10-45-59A and ASC 260-10-45-40, convertible participating preferred stock requires the two-class method for basic EPS because of its participation feature, and the more dilutive of the two-class or if-converted method for diluted EPS. Choice A incorrectly uses the simple deduction method for basic EPS, ignoring the participation feature that entitles preferred shareholders to a share of undistributed earnings.', 'hard', 4),

-- Q22: hard / L4 — Evaluate restricted stock units in diluted EPS using treasury stock method
(2, 'Earnings Per Share', 'Ironclad Technologies grants 30,000 restricted stock units (RSUs) to employees on January 1 of Year 1, vesting over 3 years. The grant-date fair value is $45 per share, and by December 31 of Year 1, $450,000 of the total $1,350,000 compensation cost has been recognized. The average market price during Year 1 is $60 per share. Evaluate how the RSUs should be treated in the Year 1 diluted EPS calculation.', '["The 30,000 RSU shares are included using the treasury stock method, with unamortized compensation cost of $900,000 treated as assumed proceeds, adding 15,000 incremental shares", "RSUs are excluded from diluted EPS because they have not yet vested", "All 30,000 RSU shares are added to the denominator at their full amount because no exercise price exists", "RSUs are included using the if-converted method, adding $450,000 to the numerator and 30,000 shares to the denominator"]'::jsonb, 0, 'Under ASC 260-10-45-28A, unvested share-settled RSUs are potential common shares for diluted EPS. The treasury stock method treats unamortized compensation cost ($900,000) as assumed proceeds, which would repurchase 15,000 shares ($900,000 / $60). Net incremental shares = 30,000 minus 15,000 = 15,000. Choice C incorrectly adds all 30,000 shares without considering the treasury stock method''s offset for unamortized compensation cost.', 'hard', 4),

-- Q23: hard / L4 — Evaluate mandatory redeemable preferred stock classification and EPS impact
(2, 'Earnings Per Share', 'Corinth Industries issues 20,000 shares of mandatorily redeemable preferred stock at $50 per share, paying a $4 annual dividend per share. The shares must be redeemed at par in five years. The company also has 300,000 common shares outstanding and net income of $1,200,000. Evaluate the proper treatment of the mandatorily redeemable preferred stock in the EPS calculation.', '["The $80,000 dividend is deducted from the numerator as a preferred dividend adjustment", "The preferred shares are included in the denominator as potential common stock", "The preferred stock is classified as a liability under ASC 480, and its dividends are treated as interest expense reducing net income rather than as a preferred dividend adjustment in the EPS numerator", "The preferred stock is excluded from EPS entirely because it will be redeemed"]'::jsonb, 2, 'Under ASC 480-10-25-4, mandatorily redeemable preferred stock is classified as a liability, not equity. The $80,000 annual payment (20,000 x $4) is accounted for as interest expense, reducing net income directly rather than being presented as a preferred dividend adjustment in the EPS numerator. Choice A incorrectly treats the mandatorily redeemable preferred as equity, which would overstate the EPS numerator by not recognizing the expense within net income.', 'hard', 4),

-- Q24: medium / L3 — At-the-money options produce zero incremental shares
(2, 'Earnings Per Share', 'Brayden Corp. has 250,000 weighted-average shares, net income of $750,000, and 15,000 stock options with an exercise price of $40. The average market price during the year was exactly $40 per share. What is the effect of these options on diluted EPS?', '["Diluted EPS decreases because the options add 15,000 shares to the denominator", "Diluted EPS increases slightly because the treasury stock method generates a net share buyback", "Diluted EPS is reduced by the assumed compensation cost related to the options", "Diluted EPS is unchanged because at-the-money options produce zero incremental shares under the treasury stock method"]'::jsonb, 3, 'Under ASC 260-10-45-22, the treasury stock method assumes options are exercised and proceeds ($600,000) are used to repurchase shares at the average market price ($40). Since both prices equal $40, the 15,000 shares issued exactly offset the 15,000 shares repurchased, producing zero incremental shares and no impact on diluted EPS. Choice A incorrectly assumes all option shares are added without the treasury stock repurchase offset.', 'medium', 3),

-- Q25: easy / L1 — Numerator deduction in basic EPS formula
(2, 'Earnings Per Share', 'In the basic EPS formula, which item is deducted from net income in the numerator?', '["Interest expense on all outstanding debt", "Income tax expense for the current period", "Preferred stock dividends", "Depreciation and amortization expense"]'::jsonb, 2, 'Under ASC 260-10-45-11, the basic EPS numerator is net income minus preferred stock dividends—whether declared for noncumulative or accumulated for cumulative preferred. This represents earnings available to common shareholders. Choice A is incorrect because interest expense is already deducted in computing net income and is not a separate EPS adjustment.', 'easy', 1),

-- Q26: easy / L1 — Treasury stock method definition
(2, 'Earnings Per Share', 'What does the treasury stock method assume when computing diluted EPS for stock options?', '["Options are exercised at the closing market price and proceeds are distributed as dividends", "Options expire unexercised and their compensation cost is added to the numerator", "The conversion ratio is applied to determine the number of additional shares issued", "Exercise proceeds are used to repurchase shares at the average market price, and only net incremental shares are added to the denominator"]'::jsonb, 3, 'Under ASC 260-10-45-22, the treasury stock method assumes that stock option exercise proceeds are used to buy back shares at the average market price. Only the incremental shares (options exercised minus shares repurchased) increase the denominator. Choice C describes the if-converted method used for convertible securities, not the treasury stock method used for options and warrants.', 'easy', 1),

-- Q27: medium / L3 — High-coupon convertible bonds antidilutive per-share impact analysis
(2, 'Earnings Per Share', 'Sycamore Industries has basic EPS of $3.00 based on net income of $600,000 and 200,000 weighted-average shares. The company has $400,000 face value of 12% convertible bonds (25% tax rate) convertible into 10,000 common shares. What does the per-share impact of the convertible bonds reveal about their inclusion in diluted EPS?', '["The per-share impact is $3.60, which is less than basic EPS, so the bonds are dilutive and included", "The per-share impact is $3.60, which exceeds basic EPS of $3.00, so the bonds are antidilutive and excluded from diluted EPS", "The per-share impact is $4.80, which exceeds basic EPS, so the bonds are antidilutive", "The per-share impact is $3.00, which equals basic EPS, so the bonds have no dilutive effect"]'::jsonb, 1, 'Under ASC 260-10-45-16, each potentially dilutive security is tested by comparing its per-share impact to current EPS. The after-tax interest is $36,000 ($400,000 x 12% x 0.75), producing a per-share impact of $3.60 ($36,000 / 10,000). Since $3.60 exceeds basic EPS of $3.00, including the bonds would increase EPS, making them antidilutive and excluded. Choice C ($4.80) incorrectly uses pre-tax interest of $48,000, ignoring the tax benefit of the interest deduction.', 'medium', 3),

-- Q28: medium / L2 — Interim period EPS computation with quarterly preferred dividend
(2, 'Earnings Per Share', 'Baxter Industries reports net income of $180,000 for the second quarter of 2026. Weighted-average shares for the quarter are 120,000. Baxter has 3,000 shares of $100 par, 8% cumulative preferred stock outstanding all year. What is basic EPS for the second quarter?', '["$1.50 per share", "$1.45 per share", "$1.30 per share", "$1.35 per share"]'::jsonb, 1, 'Under ASC 260-10-45-11 and ASC 270-10-50-1, interim EPS deducts only the preferred dividends attributable to the interim period. The quarterly preferred dividend is $6,000 (3,000 x $100 x 8% / 4). Basic EPS = ($180,000 minus $6,000) / 120,000 = $1.45. Choice C ($1.30) incorrectly deducts the full annual preferred dividend of $24,000, overstating the preferred adjustment for a single quarter.', 'medium', 2),

-- Q29: easy / L1 — EPS presentation for discontinued operations
(2, 'Earnings Per Share', 'Under ASC 260, where must earnings per share for discontinued operations be presented?', '["Only in the notes to the financial statements", "On the face of the income statement or in the notes to the financial statements", "On the face of the income statement as a mandatory line item with no alternative", "In the statement of stockholders'' equity"]'::jsonb, 1, 'Under ASC 260-10-45-3, an entity must present EPS for income from continuing operations and net income on the face of the income statement. However, EPS for discontinued operations may be presented either on the face of the income statement or disclosed in the notes. Choice C is incorrect because discontinued operations EPS is not strictly required on the income statement face; note disclosure is an acceptable alternative under ASC 260.', 'easy', 1),

-- Q30: easy / L1 — Definition of the if-converted method
(2, 'Earnings Per Share', 'What does the if-converted method assume when computing diluted EPS for convertible securities?', '["Convertible securities are assumed to have been redeemed for cash at the beginning of the period", "Convertible securities are excluded from EPS until actual conversion occurs", "Convertible securities are assumed to have been exercised and proceeds used to repurchase shares", "Convertible securities are assumed to have been converted into common stock at the beginning of the period"]'::jsonb, 3, 'Under ASC 260-10-45-21, the if-converted method assumes convertible bonds or convertible preferred stock were converted into common shares at the beginning of the period (or issuance date, if later). The numerator is adjusted by removing the related interest expense or preferred dividends. Choice C describes the treasury stock method used for options and warrants, not the if-converted method used for convertible securities.', 'easy', 1)
;

COMMIT;
