-- Migration: Question generation — REG batch 35 (30 questions)
-- Date: 2026-03-02
-- Topic: C Corporations
-- Difficulty: 9E / 15M / 6H
-- Bloom's: L1:8 / L2:9 / L3:8 / L4:5

BEGIN;

INSERT INTO questions (section_id, topic, stem, choices, correct_index, explanation, difficulty, cognitive_level)
VALUES

-- Q1: medium / L3 — E&P depreciation adjustment (MACRS vs ADS)
(3, 'C Corporations', 'Harmon Corp. places $400,000 of equipment in service and claims $80,000 of MACRS depreciation for the current year. The straight-line alternative depreciation system (ADS) amount would be $50,000. How does the depreciation method difference affect Harmon''s current-year earnings and profits?', '["E&P is reduced by $80,000 because MACRS depreciation is used for both taxable income and E&P", "E&P is reduced by $50,000 because E&P depreciation must use the alternative depreciation system rather than MACRS", "E&P is reduced by $30,000, representing only the difference between the two methods", "E&P is increased by $30,000 because accelerated depreciation creates a positive E&P adjustment"]'::jsonb, 1, 'Under IRC Section 312(k), E&P depreciation must be computed using the alternative depreciation system (ADS) with straight-line method, not the accelerated MACRS method used for taxable income. Harmon reduces E&P by only $50,000 even though it claims an $80,000 tax deduction. Choice A is incorrect because MACRS depreciation overstates the economic reduction in earnings; E&P is designed to reflect the corporation''s true economic ability to pay dividends, requiring the slower ADS method.', 'medium', 3),

-- Q2: hard / L3 — Section 304 related corporation stock redemption
(3, 'C Corporations', 'Mercer owns 80% of Alpha Corp and 70% of Beta Corp. Alpha Corp purchases 100 shares of Beta Corp stock from Mercer for $200,000. Mercer''s basis in the Beta shares is $60,000. Because Mercer controls both corporations, analyze how this purchase is treated for federal income tax purposes under Section 304.', '["The $200,000 is treated as a distribution from Alpha Corp, taxable as a dividend to the extent of both corporations'' combined E&P", "Mercer recognizes a $140,000 capital gain because the transaction is treated as a sale of stock", "The $200,000 is a tax-free return of capital because Mercer maintains control of both corporations", "Mercer recognizes no gain because the transaction qualifies for nonrecognition under Section 351"]'::jsonb, 0, 'Under IRC Section 304(a)(1), when a person controlling two corporations sells stock of one to the other, the transaction is treated as a distribution under Section 301 rather than a sale. The acquiring corporation (Alpha) is deemed to have made a distribution, taxable as a dividend to the extent of E&P. Choice B is incorrect because Section 304 specifically overrides sale treatment to prevent shareholders from extracting corporate earnings at capital gain rates through related-corporation transfers.', 'hard', 3),

-- Q3: medium / L3 — Section 1059 extraordinary dividends basis reduction
(3, 'C Corporations', 'Crestview Holdings, a C corporation owning 15% of Ridgeway Corp, receives a $500,000 dividend that exceeds 10% of Crestview''s $3,000,000 adjusted basis in the Ridgeway stock. How does Section 1059 affect Crestview''s treatment of this extraordinary dividend?', '["Crestview must recognize the entire $500,000 as ordinary income with no dividends received deduction", "Crestview must increase its basis in the Ridgeway stock by the nontaxable portion of the dividend", "Crestview must reduce its stock basis by the nontaxable portion — the amount sheltered by the dividends received deduction", "Crestview must immediately dispose of its Ridgeway stock to avoid the extraordinary dividend penalty"]'::jsonb, 2, 'Under IRC Section 1059, when a corporate shareholder receives an extraordinary dividend (exceeding 10% of basis for non-preferred stock), it must reduce its stock basis by the nontaxable portion — the amount sheltered by the DRD. This prevents claiming a DRD and then recognizing a larger capital loss on later sale. Choice B is incorrect because the adjustment reduces (not increases) basis to reflect the economic benefit already received tax-free through the DRD.', 'medium', 3),

-- Q4: easy / L1 — Schedule M-3 filing requirement
(3, 'C Corporations', 'Which C corporations are required to file Schedule M-3 instead of Schedule M-1 with Form 1120?', '["All C corporations regardless of size", "Corporations with gross receipts exceeding $5 million", "Corporations with total assets exceeding $50 million", "Corporations with total assets of $10 million or more"]'::jsonb, 3, 'Under IRC reporting requirements and IRS Form 1120 instructions, C corporations with total assets of $10 million or more must file Schedule M-3, which provides a more detailed reconciliation of book income to taxable income than the simpler Schedule M-1. Choice C is incorrect because the threshold is $10 million, not $50 million — the lower threshold ensures broader transparency from mid-to-large corporations.', 'easy', 1),

-- Q5: medium / L3 — Section 7872 below-market shareholder loan
(3, 'C Corporations', 'Caldwell Corp loans $500,000 to its sole shareholder, Harris, at 1% annual interest when the applicable federal rate is 5%. The demand loan is outstanding for the full year. Analyze the tax consequences of this below-market loan arrangement under Section 7872.', '["The 4% interest differential is treated solely as additional compensation to Harris with no dividend implication", "Caldwell is treated as paying Harris a $20,000 constructive dividend, and Harris is treated as paying $20,000 of interest back to Caldwell", "The arrangement has no tax consequences because Caldwell actually charges some interest on the loan", "Harris must recognize $25,000 of imputed interest income on the full loan amount"]'::jsonb, 1, 'Under IRC Section 7872, a below-market loan from a corporation to a shareholder triggers a two-step recharacterization. The forgone interest ($500,000 x 4% = $20,000) is treated as a constructive dividend from Caldwell to Harris, and Harris is deemed to pay that amount back as interest to Caldwell. Choice A is incorrect because the payment is recharacterized as a dividend (not compensation) when made to a shareholder in that capacity, reflecting the shareholder-corporation relationship.', 'medium', 3),

-- Q6: medium / L3 — Nontaxable stock dividend effect on E&P
(3, 'C Corporations', 'Glenwood Corp declares a 10% nontaxable common stock dividend to all common shareholders, issuing 5,000 new shares when 50,000 shares are outstanding. Glenwood''s current E&P is $300,000. Analyze the effect of this stock dividend on Glenwood''s earnings and profits.', '["E&P is not reduced because a nontaxable stock dividend does not represent a distribution of corporate assets", "E&P is reduced by the fair market value of the 5,000 shares distributed", "E&P is reduced by the par value of the 5,000 shares distributed", "E&P is reduced by 10% of total outstanding shares'' aggregate basis"]'::jsonb, 0, 'Under IRC Section 305(a), a pro rata distribution of common stock on common stock is generally nontaxable to shareholders. Because no corporate assets leave the corporation, E&P is not reduced — the same earnings are divided among more shares. Choice B is incorrect because E&P is reduced only when the corporation distributes property or cash that depletes corporate assets; issuing additional shares merely dilutes existing ownership without affecting dividend-paying capacity.', 'medium', 3),

-- Q7: hard / L4 — Evaluate C-to-S conversion risks (BIG tax + passive income)
(3, 'C Corporations', 'Meridian Corp, a C corporation with $800,000 of accumulated E&P and built-in gain assets (FMV $2,000,000, basis $1,200,000), is considering an S election. Its income consists of 40% passive investment income. Evaluate the primary risk factors Meridian should consider before making the election.', '["Meridian faces no additional taxes after the S election because all income passes through to shareholders", "The only concern is the built-in gains tax on asset sales within the recognition period, avoidable by holding assets indefinitely", "Meridian faces both the built-in gains tax under Section 1374 if assets are sold within five years and potential termination of the S election under Section 1375 if passive income exceeds 25% of gross receipts for three consecutive years", "The S election would be automatically denied because Meridian has accumulated E&P exceeding $500,000"]'::jsonb, 2, 'Under IRC Sections 1374 and 1375, a C corporation converting to S status faces two risks: the built-in gains tax imposes a corporate-level tax on gains recognized within five years, and the excess passive income tax applies when an S corporation with C corp E&P has passive income exceeding 25% of gross receipts — potentially terminating the S election after three consecutive years. Choice A is incorrect because these corporate-level taxes survive the S election when C corporation attributes exist.', 'hard', 4),

-- Q8: easy / L1 — Quarterly estimated tax due dates
(3, 'C Corporations', 'On what dates are quarterly estimated tax installments due for a calendar-year C corporation?', '["March 15, June 15, September 15, and December 15", "January 15, April 15, July 15, and October 15", "March 15, May 15, August 15, and November 15", "April 15, June 15, September 15, and December 15"]'::jsonb, 3, 'Under IRC Section 6655, a calendar-year C corporation must make estimated tax installments on the 15th day of the 4th, 6th, 9th, and 12th months — April 15, June 15, September 15, and December 15. Choice A is incorrect because the first installment is due in the 4th month (April), not the 3rd month (March). The corporate estimated tax schedule differs from the individual schedule.', 'easy', 1),

-- Q9: easy / L2 — Section 1244 small business stock ordinary loss
(3, 'C Corporations', 'Lawson purchases 500 shares of newly issued stock in Redfield Corp, a qualifying small business corporation, for $80,000. Two years later the stock becomes worthless. Lawson files as single. What is the tax treatment of the loss?', '["$80,000 capital loss, deductible only against capital gains plus $3,000 per year", "$50,000 ordinary loss and $30,000 capital loss", "$80,000 ordinary loss fully deductible against ordinary income", "$80,000 capital loss with no carryforward permitted"]'::jsonb, 1, 'Under IRC Section 1244, an individual sustaining a loss on qualifying small business stock may treat up to $50,000 ($100,000 on a joint return) as an ordinary loss rather than a capital loss. Because Lawson files as single, $50,000 is ordinary loss and the remaining $30,000 is capital loss. Choice C is incorrect because the ordinary loss benefit is capped at $50,000 for single filers, not the full loss amount.', 'easy', 2),

-- Q10: medium / L2 — Section 291 additional recapture for corporations
(3, 'C Corporations', 'Branford Corp, a C corporation, sells a commercial building for $900,000. The building was purchased for $750,000, and accumulated straight-line depreciation is $200,000 (adjusted basis $550,000). No Section 1250 recapture exists because only straight-line depreciation was used. What additional recapture does Branford recognize under Section 291?', '["$40,000 of the gain is treated as ordinary income under Section 291", "$200,000 of the gain is treated as ordinary income under Section 291", "$70,000 of the gain is treated as ordinary income under Section 291", "No additional recapture applies because Branford used straight-line depreciation"]'::jsonb, 0, 'Under IRC Section 291(a)(1), C corporations must recognize additional ordinary income equal to 20% of the amount that would have been recaptured under Section 1245 had the property been Section 1245 property. The additional recapture is 20% x $200,000 (total depreciation) = $40,000. Choice D is incorrect because Section 291 applies specifically to corporations regardless of depreciation method, requiring 20% of straight-line depreciation as ordinary income on real property.', 'medium', 2),

-- Q11: medium / L2 — Section 563 throwback dividends (75-day rule)
(3, 'C Corporations', 'Stanton Corp, a calendar-year C corporation under IRS review for the accumulated earnings tax, pays $300,000 in dividends on February 10, 2027. Stanton''s 2026 accumulated taxable income before the dividends paid deduction is $500,000. How much of the February 2027 dividend reduces Stanton''s 2026 AET base?', '["$0 because dividends paid after year-end cannot reduce the prior year''s AET base", "$300,000 because the dividend was paid within 75 days after the close of the 2026 tax year", "$150,000 because only 50% of post-year-end dividends qualify as throwback dividends", "$500,000 because the entire accumulated taxable income is offset by the dividend"]'::jsonb, 1, 'Under IRC Section 563(a), dividends paid within 2-1/2 months (approximately 75 days) after the close of the taxable year are treated as paid during that year for the accumulated earnings tax dividends paid deduction. February 10 falls within this window, so the full $300,000 reduces the 2026 AET base. Choice A is incorrect because Congress enacted the throwback dividend provision to give corporations a short grace period to distribute earnings and avoid the penalty tax.', 'medium', 2),

-- Q12: easy / L1 — DRD applies only to domestic corporation dividends
(3, 'C Corporations', 'Which type of dividends does NOT qualify for the dividends received deduction under Section 243?', '["Dividends from a corporation in which the recipient owns less than 20%", "Dividends from a corporation in which the recipient owns between 20% and 80%", "Dividends from an affiliated group member with 80% or greater ownership", "Dividends received from a foreign corporation"]'::jsonb, 3, 'Under IRC Section 243, the dividends received deduction applies only to dividends received from domestic corporations. Dividends from foreign corporations do not qualify; instead, they may be eligible for a foreign tax credit under Section 901 or a deduction under Section 245A for certain foreign-source dividends. Choice A is incorrect because dividends from domestic corporations with less than 20% ownership do qualify — at the 50% DRD rate.', 'easy', 1),

-- Q13: hard / L4 — Brother-sister controlled group (Section 1563)
(3, 'C Corporations', 'Reynolds owns 80% of Cedar Corp and 70% of Maple Corp. Jefferson owns 20% of Cedar Corp and 30% of Maple Corp. Both corporations independently claim the full $250,000 accumulated earnings credit. Evaluate whether the IRS can challenge the duplicated credits under the controlled group rules.', '["The corporations form a brother-sister controlled group under Section 1563 because identical ownership exceeds 50%, requiring them to share the $250,000 credit", "Each corporation may claim the full $250,000 credit because they file separate returns", "The controlled group rules apply only to parent-subsidiary groups, not brother-sister groups", "The IRS may challenge the credits only if both corporations operate in the same industry"]'::jsonb, 0, 'Under IRC Section 1563(a)(2), a brother-sister controlled group exists when five or fewer persons own more than 50% identical ownership in each corporation. Reynolds''s identical ownership is 70% (min of 80% and 70%) and Jefferson''s is 20% (min of 20% and 30%), totaling 90% — well above 50%. Members of a controlled group must share the $250,000 credit under Section 1561. Choice B is incorrect because filing separate returns does not override controlled group allocation rules.', 'hard', 4),

-- Q14: medium / L3 — Section 267 accrued expense deduction timing
(3, 'C Corporations', 'Waverly Corp, an accrual-basis C corporation, accrues a $75,000 bonus to its sole shareholder, Chen, who reports on the cash basis. The bonus is accrued on December 31, 2026, but not paid until March 15, 2027. How does Section 267 affect the timing of Waverly''s deduction?', '["Waverly cannot deduct the bonus until 2027 when Chen includes it in income, because Section 267 requires matching between related parties", "Waverly deducts the bonus in 2026 when accrued because the all-events test is satisfied regardless of the shareholder relationship", "Waverly loses the deduction permanently because the bonus was not paid within 75 days of year-end", "Waverly deducts half the bonus in 2026 and half in 2027 under a Section 267 proration rule"]'::jsonb, 0, 'Under IRC Section 267(a)(2), when an accrual-basis payor owes an amount to a related cash-basis payee, the deduction is deferred until the payee includes it in income. Because Chen (>50% shareholder) is related to Waverly under Section 267(b), the deduction is deferred to 2027 when Chen receives payment. Choice B is incorrect because Section 267 specifically overrides the normal accrual-basis all-events test for related-party transactions to prevent mismatched timing benefits.', 'medium', 3),

-- Q15: easy / L1 — Automatic extension for Form 1120
(3, 'C Corporations', 'What is the length of the automatic extension for filing Form 1120 for a C corporation?', '["Three months", "Five months", "Six months", "Seven months"]'::jsonb, 2, 'Under IRC Section 6081, a C corporation filing Form 1120 may obtain an automatic six-month extension by filing Form 7004 on or before the original due date. For a calendar-year corporation with an April 15 due date, this extends the deadline to October 15. Choice A is incorrect because three months applies to certain other entity types, not C corporations filing Form 1120.', 'easy', 1),

-- Q16: easy / L1 — Schedule M-2 purpose on Form 1120
(3, 'C Corporations', 'What does Schedule M-2 of Form 1120 report?', '["A reconciliation of book income to taxable income", "A detailed breakdown of officer compensation", "A summary of the corporation''s balance sheet", "An analysis of unappropriated retained earnings per books"]'::jsonb, 3, 'Under IRC Section 6012 and Form 1120 instructions, Schedule M-2 provides an analysis of unappropriated retained earnings per books, showing the beginning balance, increases from net income, decreases from dividends, and the ending balance. Choice A is incorrect because the reconciliation of book income to taxable income is reported on Schedule M-1 (or Schedule M-3 for corporations with total assets of $10 million or more).', 'easy', 1),

-- Q17: hard / L4 — Section 269 acquisition to evade tax
(3, 'C Corporations', 'Westbrook Industries acquires 100% of Thornton Corp, which has $3 million in NOL carryforwards. Westbrook''s primary motivation, documented in board minutes, is to use Thornton''s NOLs to offset Westbrook''s profitable operations. Thornton has minimal ongoing business operations. Evaluate the IRS''s authority to challenge this acquisition.', '["The IRS cannot challenge the acquisition because NOL carryforwards automatically transfer with an acquired corporation", "The IRS may disallow the NOL deductions under Section 269 if the principal purpose of the acquisition was to obtain a tax benefit not otherwise available", "The IRS can challenge only if the acquisition price exceeds the fair market value of Thornton''s net assets", "Section 269 applies only to asset acquisitions, not stock purchases"]'::jsonb, 1, 'Under IRC Section 269(a), if any person acquires control (50%+) of a corporation and the principal purpose is to obtain a deduction, credit, or allowance not otherwise available, the IRS may disallow such benefits. Westbrook''s documented intent to use Thornton''s NOLs with minimal business purpose supports disallowance. Choice A is incorrect because while NOLs technically survive an acquisition, Section 269 provides independent authority to disallow tax benefits when the acquisition lacks genuine business purpose.', 'hard', 4),

-- Q18: medium / L2 — Life insurance proceeds effect on E&P
(3, 'C Corporations', 'Northfield Corp receives $400,000 in life insurance proceeds upon the death of its CEO. The proceeds are excluded from taxable income under Section 101(a). What is the effect on Northfield''s current-year earnings and profits?', '["E&P increases by $400,000 because life insurance proceeds, though excluded from taxable income, are included in E&P", "E&P is not affected because the proceeds are excluded from both taxable income and E&P", "E&P increases by only half the proceeds under a special insurance adjustment rule", "E&P decreases because only the nondeductible premium expense affects E&P"]'::jsonb, 0, 'Under IRC Section 312, E&P must include all economic income, including amounts excluded from taxable income. Life insurance proceeds excluded under Section 101(a) increase E&P by the full amount received because they enhance the corporation''s economic capacity to pay dividends. Choice B is incorrect because E&P is broader than taxable income — it captures tax-exempt income to accurately measure the corporation''s true dividend-paying ability.', 'medium', 2),

-- Q19: medium / L2 — Charitable contribution of appreciated capital gain property
(3, 'C Corporations', 'Oakmont Corp, a C corporation, donates publicly traded stock held for three years (basis $60,000, FMV $150,000) to a qualified 501(c)(3) public charity. Oakmont''s taxable income before the charitable deduction is $2,000,000. What is Oakmont''s charitable contribution deduction?', '["$60,000, the adjusted basis of the donated stock", "$200,000, which is 10% of taxable income before the deduction", "$150,000, the fair market value of the donated stock", "$90,000, the gain amount on the donated stock"]'::jsonb, 2, 'Under IRC Section 170(e), a C corporation donating long-term appreciated capital gain property (publicly traded stock held over one year) to a public charity may deduct the full fair market value of $150,000. The 10% limitation ($2,000,000 x 10% = $200,000) is not exceeded. Choice A is incorrect because the basis limitation applies only to certain property types (ordinary income property, short-term capital gain property, or tangible personal property unrelated to the charity''s exempt purpose), not long-term publicly traded stock.', 'medium', 2),

-- Q20: medium / L2 — Annualized income installment method
(3, 'C Corporations', 'Riverton Corp, a calendar-year C corporation, earns most of its income in the fourth quarter due to seasonal operations. Its first-quarter taxable income is $40,000 and full-year taxable income is $800,000. Under the annualized income installment method, what is Riverton''s required first-quarter estimated tax installment?', '["$42,000, based on 25% of the full-year estimated tax of $168,000", "$33,600, based on the full annualized first-quarter income tax", "$2,100, based on the first-quarter income taxed at a reduced seasonal rate", "$8,400, based on the annualized first-quarter income of $160,000 taxed at 21% and multiplied by 25%"]'::jsonb, 3, 'Under IRC Section 6655(e), the annualized income installment method allows seasonal corporations to base estimated payments on income actually earned during each period. First-quarter income ($40,000) is annualized to $160,000 ($40,000 x 4), producing $33,600 tax ($160,000 x 21%). The first installment is 25% of $33,600 = $8,400. Choice A is incorrect because it uses full-year estimated tax, overstating the required installment for a seasonal corporation earning most income later in the year.', 'medium', 2),

-- Q21: medium / L2 — Excess charitable contribution 5-year carryforward
(3, 'C Corporations', 'Hawthorn Corp, a C corporation, has taxable income of $500,000 and makes $80,000 in charitable contributions in 2026. In 2027, Hawthorn''s taxable income is $1,200,000 and it makes $70,000 in charitable contributions. What is Hawthorn''s allowable charitable deduction for 2027?', '["$70,000, the current year''s contributions only", "$100,000, combining the $70,000 current-year contribution with the $30,000 carryforward from 2026", "$120,000, which is 10% of Hawthorn''s 2027 taxable income", "$80,000, the prior year''s full contribution amount"]'::jsonb, 1, 'Under IRC Section 170(d)(2), a C corporation''s charitable contributions exceeding the 10% limitation carry forward five years. In 2026, the limit was $50,000 (10% x $500,000), so $30,000 carries forward. In 2027, the $70,000 current contribution plus $30,000 carryforward ($100,000 total) is within the $120,000 limit (10% x $1,200,000). Choice A is incorrect because it ignores the carryforward; unused charitable contributions from prior years supplement the current year''s deduction.', 'medium', 2),

-- Q22: easy / L1 — PHC income test threshold
(3, 'C Corporations', 'What percentage of adjusted ordinary gross income must consist of personal holding company income for a corporation to meet the PHC income test?', '["At least 60%", "At least 50%", "At least 75%", "At least 80%"]'::jsonb, 0, 'Under IRC Section 542(a)(1), the income test for personal holding company classification requires that at least 60% of the corporation''s adjusted ordinary gross income (AOGI) consist of PHC income such as dividends, interest, certain rents, and royalties. Choice B is incorrect because the 50% threshold relates to the stock ownership test (more than 50% owned by five or fewer individuals), not the income test.', 'easy', 1),

-- Q23: easy / L1 — Late filing penalty rate for Form 1120
(3, 'C Corporations', 'What is the monthly penalty rate for a C corporation that fails to timely file Form 1120 without reasonable cause?', '["0.5% of the unpaid tax per month", "1% of the unpaid tax per month", "5% of the unpaid tax per month, up to a maximum of 25%", "10% of the total tax liability per month"]'::jsonb, 2, 'Under IRC Section 6651(a)(1), the failure-to-file penalty is 5% of the unpaid tax for each month or part of a month the return is late, up to a maximum of 25%. This penalty is separate from the failure-to-pay penalty. Choice A is incorrect because 0.5% per month is the failure-to-pay penalty under Section 6651(a)(2), not the failure-to-file penalty.', 'easy', 1),

-- Q24: medium / L3 — PSC required calendar year (Section 441(i))
(3, 'C Corporations', 'Carrington Consulting Corp is a personal service corporation owned entirely by three licensed CPAs who perform all services. The owners want to adopt a June 30 fiscal year-end to defer income. Analyze whether Carrington may use this fiscal year.', '["Carrington may freely choose any fiscal year-end because all C corporations have unrestricted year-end selection", "Personal service corporations are automatically assigned a September 30 fiscal year by the IRS", "Carrington must use a calendar year under Section 441(i) unless it establishes a business purpose or makes a Section 444 election with required payments", "Carrington may adopt any fiscal year as long as all three shareholders use the same year-end"]'::jsonb, 2, 'Under IRC Section 441(i), a personal service corporation must use the calendar year unless it establishes a business purpose for a different year-end to the IRS''s satisfaction or makes a Section 444 election (requiring annual payments to offset the deferral benefit). Choice A is incorrect because PSCs face this specific restriction to prevent owner-employees from using a fiscal year to defer their compensation income into a later calendar year.', 'medium', 3),

-- Q25: medium / L2 — Section 362(e)(2) loss limitation in Section 351 transfer
(3, 'C Corporations', 'Dalton transfers land with an adjusted basis of $250,000 and a fair market value of $170,000 to Evergreen Corp for 100% of the stock in a qualifying Section 351 exchange. What is Evergreen Corp''s basis in the land?', '["$250,000, the transferor''s carryover basis", "$170,000, the fair market value at the time of transfer", "$210,000, the average of basis and fair market value", "$80,000, the difference between basis and fair market value"]'::jsonb, 1, 'Under IRC Section 362(e)(2), when property with a built-in loss (basis exceeds FMV) is transferred to a corporation in a Section 351 exchange, the corporation''s basis is limited to fair market value ($170,000) to prevent duplication of the loss. Alternatively, the transferor and corporation may jointly elect to reduce the transferor''s stock basis instead. Choice A is incorrect because the standard carryover basis rule of Section 362(a) is overridden by Section 362(e)(2) when property has a net built-in loss at transfer.', 'medium', 2),

-- Q26: hard / L4 — Section 382 NUBIG recognition period
(3, 'C Corporations', 'Sentinel Corp undergoes an ownership change under Section 382. At the change date, Sentinel has a net unrealized built-in gain (NUBIG) of $2,000,000 and a Section 382 annual limitation of $300,000. During the first post-change year, Sentinel recognizes $500,000 of built-in gains from selling appreciated assets. Evaluate how the NUBIG affects Sentinel''s ability to use pre-change NOLs.', '["The Section 382 limitation remains $300,000 regardless of built-in gains because the limitation is fixed at the ownership change date", "Sentinel must reduce its pre-change NOLs by $500,000 before applying the Section 382 limitation", "The NUBIG has no effect on the Section 382 limitation because only pre-change losses are subject to the annual cap", "The $500,000 recognized built-in gain increases the Section 382 limitation to $800,000 for that year, allowing greater use of pre-change NOLs"]'::jsonb, 3, 'Under IRC Section 382(h), if a loss corporation has a net unrealized built-in gain at the ownership change date, built-in gains recognized during the five-year recognition period increase the Section 382 limitation for that year. The $500,000 supplements the $300,000 base, yielding an $800,000 limitation. Choice A is incorrect because Section 382(h)(1)(A) specifically allows recognized built-in gains to augment the annual limitation, reflecting that these gains accrued before the change and should not be restricted.', 'hard', 4),

-- Q27: easy / L1 — Consent dividends definition (Section 565)
(3, 'C Corporations', 'What is a consent dividend under Section 565?', '["A dividend actually paid in cash to shareholders with their written consent", "A dividend declared by the board of directors but deferred to a future payment date", "A hypothetical dividend that shareholders agree to report as income without receiving an actual distribution", "A dividend paid only to preferred shareholders to satisfy seniority requirements"]'::jsonb, 2, 'Under IRC Section 565, a consent dividend is an amount that shareholders agree to treat as if distributed, even though no actual payment is made. The corporation receives a dividends paid deduction, and shareholders report the amount as dividend income. Choice A is incorrect because the distinguishing feature of a consent dividend is that no cash or property is actually distributed — it is a constructive mechanism used to reduce personal holding company or accumulated earnings tax exposure.', 'easy', 1),

-- Q28: hard / L4 — Consolidated return intercompany transaction deferral
(3, 'C Corporations', 'Atlas Corp and its 100%-owned subsidiary, Beacon Corp, file a consolidated return. Atlas sells inventory with a $200,000 basis to Beacon for $350,000. Beacon holds the inventory at year-end without reselling it to a third party. Evaluate the consolidated group''s tax treatment of this intercompany sale.', '["Atlas recognizes $150,000 of gain on the consolidated return because the sale is a completed transaction", "The $150,000 gain is permanently eliminated because both corporations are in the same consolidated group", "Beacon takes a $200,000 carryover basis in the inventory and Atlas recognizes no gain or loss", "Atlas''s $150,000 gain is deferred under the intercompany transaction rules and recognized when Beacon sells the inventory to an outside party"]'::jsonb, 3, 'Under Treas. Reg. Section 1.1502-13, intercompany transactions within a consolidated group result in deferred gain or loss until a triggering event occurs, such as a sale to a third party. Atlas''s $150,000 gain is deferred (not eliminated) and will be recognized when Beacon resells the inventory outside the group. Choice B is incorrect because the gain is deferred, not permanently eliminated — deferral ensures the consolidated group recognizes the gain when it exits the economic unit.', 'hard', 4),

-- Q29: medium / L2 — Capital loss carryback computation across years
(3, 'C Corporations', 'Ashford Corp, a calendar-year C corporation, has a net capital loss of $60,000 in 2026. In 2023 Ashford had net capital gains of $25,000, in 2024 net capital gains of $20,000, and in 2025 net capital gains of $10,000. How much of the 2026 capital loss can Ashford carry back?', '["$60,000, carried back to 2023 in full", "$55,000 total — $25,000 to 2023, $20,000 to 2024, and $10,000 to 2025", "$25,000, carried back only to the earliest year with available gains", "$0 because corporate capital losses cannot be carried back under the TCJA"]'::jsonb, 1, 'Under IRC Section 1212(a), a corporation''s net capital loss is carried back three years and forward five years, applied to the earliest year first. Ashford carries back $25,000 to 2023, $20,000 to 2024, and $10,000 to 2025 — absorbing $55,000 total. The remaining $5,000 carries forward. Choice D is incorrect because the TCJA eliminated NOL carrybacks (Section 172), not capital loss carrybacks — corporate capital losses retain the three-year carryback rule.', 'medium', 2),

-- Q30: medium / L3 — PHC rental income 50% of AOGI test
(3, 'C Corporations', 'Pryor Corp, a closely held C corporation meeting the stock ownership test, has adjusted ordinary gross income (AOGI) of $500,000 consisting of $280,000 in rental income and $220,000 in dividends and interest. The rental income exceeds 50% of AOGI. Analyze whether the rental income is excluded from personal holding company income.', '["The rental income remains PHC income because the exception requires both that rents equal 50% or more of AOGI and that other PHC income not exceed 10% of ordinary gross income — the second condition fails here", "The rental income is excluded from PHC income because it exceeds 50% of AOGI, satisfying the sole requirement for the rental exception", "All rental income is automatically classified as PHC income regardless of the percentage of AOGI", "The rental income is excluded because only dividends, interest, and royalties qualify as PHC income"]'::jsonb, 0, 'Under IRC Section 543(a)(2), adjusted income from rents is excluded from PHC income only if two conditions are met: (1) rents equal 50% or more of AOGI, and (2) other PHC income does not exceed 10% of ordinary gross income. Here, rents are 56% of AOGI (satisfying condition 1), but $220,000 in other PHC income far exceeds 10% of OGI (failing condition 2). Choice B is incorrect because the rental exclusion requires both conditions, not just the 50% threshold.', 'medium', 3)
;

COMMIT;
