-- Migration: Question generation — FAR batch 51 (30 questions)
-- Date: 2026-03-02
-- Topic: Employee Benefit Plans
-- Difficulty: 9E / 15M / 6H
-- Bloom's: L1:8 / L2:9 / L3:8 / L4:5

BEGIN;

INSERT INTO questions (section_id, topic, stem, choices, correct_index, explanation, difficulty, cognitive_level)
VALUES

-- Q1: medium / L3 — Multi-employer plan accounting (treated as DC)
(2, 'Employee Benefit Plans', 'Thornton Manufacturing participates in a multi-employer defined benefit pension plan alongside four other companies. Thornton''s required annual contribution is $180,000, and the plan''s actuary reports that the overall plan has a PBO of $25 million and plan assets of $22 million. How should Thornton account for its participation in this plan?', '["Record a proportionate share of the $3 million underfunded status as a liability", "Recognize net periodic pension cost using the five-component model for its share of the plan", "Record pension expense equal to the $180,000 required contribution for the period", "Capitalize its share of the plan assets as an investment on the balance sheet"]'::jsonb, 2, 'Under ASC 715-80, a participating employer in a multi-employer plan generally accounts for its participation as if it were a defined contribution plan. The employer recognizes pension expense equal to its required contribution for the period. Unlike single-employer DB plans, the employer does not report the plan''s funded status on its own balance sheet. Recording a proportionate share of the underfunded status (choice A) would apply to single-employer plans, not multi-employer plans.', 'medium', 3),

-- Q2: medium / L3 — Actual return decomposition (expected return vs OCI deferral)
(2, 'Employee Benefit Plans', 'Waverly Corp.''s defined benefit plan has beginning plan assets of $4,200,000. The expected rate of return is 7%, yielding an expected return of $294,000. The actual return on plan assets for the year is $340,000. How are the expected and actual returns reflected in Waverly''s pension accounting?', '["The $340,000 actual return reduces pension expense; no amount is recorded in OCI", "The $294,000 expected return reduces pension expense, and the $46,000 excess is a credit to OCI", "The $340,000 actual return reduces pension expense, and the $46,000 excess increases the PBO", "The $294,000 expected return is reported in OCI, and the $46,000 difference reduces pension expense"]'::jsonb, 1, 'Under ASC 715-30-35, the expected return on plan assets (not the actual return) is used to compute net periodic pension cost. The difference between actual return ($340,000) and expected return ($294,000) is a $46,000 asset gain deferred in other comprehensive income. Using the actual return directly in pension expense (choice A) would bypass the smoothing mechanism ASC 715 uses to reduce earnings volatility.', 'medium', 3),

-- Q3: easy / L1 — Discount rate selection criteria
(2, 'Employee Benefit Plans', 'Under ASC 715, what rate is used to calculate interest cost on the projected benefit obligation?', '["A high-quality corporate bond rate matching the timing of expected benefit payments", "The expected long-term rate of return on plan assets", "The federal funds rate as of the measurement date", "The weighted-average cost of capital of the sponsoring employer"]'::jsonb, 0, 'ASC 715-30-35-43 requires the discount rate to reflect rates at which pension benefits could be effectively settled. In practice, this is based on high-quality (AA-rated) corporate bond yields with durations matching the expected timing of benefit payments. The expected rate of return on plan assets (choice B) is a separate assumption used only for the return-on-assets component of pension expense.', 'easy', 1),

-- Q4: medium / L2 — EPBO vs APBO distinction (calculating APBO from EPBO)
(2, 'Employee Benefit Plans', 'Ferndale Inc. estimates the total cost of providing postretirement healthcare benefits to current employees will be $8,000,000 over their retirement years. To date, employees have completed 60% of their total expected service to the full eligibility date. Under ASC 715-60, what is the accumulated postretirement benefit obligation (APBO)?', '["$8,000,000", "$3,200,000", "$5,000,000", "$4,800,000"]'::jsonb, 3, 'Under ASC 715-60-35, the EPBO is the total expected cost of postretirement benefits ($8,000,000). The APBO represents the portion attributed to service already rendered. Since employees have completed 60% of service to the full eligibility date, the APBO is $8,000,000 x 60% = $4,800,000. The full $8,000,000 (choice A) is the EPBO, not the APBO, as it includes benefits attributable to future service.', 'medium', 2),

-- Q5: hard / L4 — Cash balance plan classification and accounting
(2, 'Employee Benefit Plans', 'NorthBridge Corp. sponsors a cash balance pension plan that credits each participant''s hypothetical account with 5% of annual salary plus interest at the 30-year Treasury rate. Unlike traditional defined benefit plans, participants receive periodic account balance statements resembling defined contribution accounts. The plan''s actuary computes a PBO of $12 million with plan assets of $10.5 million. Which of the following best describes the accounting classification and reporting for this plan?', '["Classified as a defined contribution plan because each employee has a hypothetical individual account", "Classified as a defined benefit plan; the employer reports the $1.5 million underfunded status as a liability", "Classified as a hybrid plan with separate DB and DC reporting requirements", "Classified as a defined contribution plan; the employer expenses only the 5% salary credit each period"]'::jsonb, 1, 'Under ASC 715-30, a cash balance plan is classified as a defined benefit plan because the employer bears the investment risk and guarantees the promised benefits, regardless of account-style presentation. The employer must report the funded status ($10.5M minus $12M = $1.5M underfunded) as a net pension liability. Classification as a DC plan (choice A) is incorrect because the employer guarantees the benefit formula, and hypothetical account balances do not transfer investment risk to employees.', 'hard', 4),

-- Q6: medium / L2 — Benefits paid symmetric effect on PBO and plan assets
(2, 'Employee Benefit Plans', 'Prescott Industries'' defined benefit plan pays $500,000 in retirement benefits during the year. The beginning PBO is $7,000,000 and beginning plan assets are $5,800,000. How does the payment of benefits affect the funded status of the plan?', '["Funded status improves by $500,000 because the PBO decreases", "Funded status worsens by $500,000 because plan assets decrease", "Funded status is unchanged because both the PBO and plan assets decrease by the same amount", "Funded status worsens by $250,000 because only plan assets decrease"]'::jsonb, 2, 'Under ASC 715-30-35, the payment of benefits reduces both the PBO and plan assets by the same amount ($500,000 each). Since funded status equals plan assets minus PBO, the net effect is zero. The funded status remains at $5,800,000 minus $7,000,000 = ($1,200,000) before and after the payment. Choice A incorrectly ignores the equal reduction in plan assets, overstating the improvement.', 'medium', 2),

-- Q7: hard / L3 — Market-related value of plan assets (5-year smoothing)
(2, 'Employee Benefit Plans', 'Crestview Corp.''s pension plan has beginning plan assets of $6,000,000 at fair value. The company uses a market-related value of plan assets that recognizes asset gains and losses over five years. At the beginning of the year, the market-related value is $5,700,000 and the PBO is $7,200,000. The cumulative unrecognized net actuarial loss is $800,000. What is the corridor amount for determining required amortization of the net loss?', '["$720,000", "$600,000", "$570,000", "$800,000"]'::jsonb, 0, 'Under ASC 715-30-35-24, the corridor is 10% of the greater of the beginning PBO or the market-related value of plan assets. The PBO is $7,200,000 (10% = $720,000) and the market-related value is $5,700,000 (10% = $570,000). The corridor is $720,000. When a company elects to use market-related value rather than fair value, that smoothed amount is used for the corridor test. Choice B ($600,000) incorrectly uses 10% of fair value of plan assets instead.', 'hard', 3),

-- Q8: hard / L4 — Negative plan amendment with existing unamortized PSC offset
(2, 'Employee Benefit Plans', 'Belmont Industries amends its defined benefit plan to reduce future benefits, creating a negative prior service cost of $400,000. The plan currently has unamortized prior service cost of $250,000 in accumulated OCI from a previous benefit increase. The average remaining service period of affected employees is 12 years. What is the net effect of this amendment on accumulated other comprehensive income and the first-year amortization?', '["Decrease AOCI by $400,000; amortize $33,333 as a credit to pension expense", "Decrease AOCI by $150,000; amortize $20,833 as a charge to pension expense", "Increase AOCI by $400,000; amortize $33,333 as a charge to pension expense", "Decrease AOCI by $150,000; amortize $12,500 as a reduction of pension expense"]'::jsonb, 3, 'Under ASC 715-30-35-10, a negative plan amendment first offsets existing unamortized prior service cost in AOCI. The $400,000 credit offsets the $250,000 debit, leaving a net $150,000 credit (decrease) in AOCI. Annual amortization is $150,000 / 12 years = $12,500, which reduces pension expense. Choice A incorrectly ignores the offset against existing unamortized PSC, overstating the AOCI impact.', 'hard', 4),

-- Q9: medium / L2 — Special termination benefits recognition timing
(2, 'Employee Benefit Plans', 'Lakewood Corp. offers a voluntary early retirement package providing a one-time payment of $50,000 to any employee with 20+ years of service who retires within 90 days. Of 40 eligible employees, 25 accept the offer. Under ASC 715, when and how much should Lakewood recognize for these special termination benefits?', '["$2,000,000 when the offer is communicated to employees", "$1,250,000 when employees accept the offer and the amount can be reasonably estimated", "$1,250,000 at the end of the 90-day offer period regardless of acceptance", "$2,000,000 ratably over the remaining service period of accepting employees"]'::jsonb, 1, 'Under ASC 715-20-25, special (voluntary) termination benefits are recognized when employees accept the offer and the amount can be reasonably estimated. The cost is 25 employees x $50,000 = $1,250,000. Recognition at the communication date (choice A) would apply to contractual termination benefits triggered by a specified event, not voluntary offers where employee acceptance is uncertain.', 'medium', 2),

-- Q10: hard / L4 — Substantive plan vs written plan in OPEB
(2, 'Employee Benefit Plans', 'Harbor Medical Group has a written OPEB plan that requires retirees to pay 30% of healthcare premiums. However, for the past eight years, Harbor has consistently subsidized retiree premiums at 90%, absorbing costs well beyond the written terms. Harbor''s actuary must determine the appropriate cost-sharing assumption for measuring the APBO. Under ASC 715-60, which plan should govern the measurement?', '["The written plan, because GAAP requires adherence to documented terms", "The written plan, adjusted only for legally enforceable side agreements", "The substantive plan as evidenced by Harbor''s consistent past practice of 90% cost-sharing", "An average of the written plan (70%) and substantive plan (90%), yielding 80% employer share"]'::jsonb, 2, 'ASC 715-60-35-5 requires that if the substantive plan differs from the written plan, the substantive plan governs the accounting measurement. Harbor''s consistent eight-year practice of subsidizing 90% of premiums represents a substantive commitment that establishes employee expectations. Relying solely on the written plan (choice A) would understate the APBO because the actual obligation exceeds the documented terms.', 'hard', 4),

-- Q11: medium / L2 — Interim quarterly pension expense allocation
(2, 'Employee Benefit Plans', 'Palmer Corp. estimates its annual net periodic pension cost at $480,000 for the fiscal year. In the second quarter, an actuarial loss of $200,000 arises from a change in mortality assumptions. Under ASC 270 and ASC 715, how should Palmer allocate pension expense in its quarterly interim financial statements?', '["Recognize $120,000 each quarter as pension expense, with the actuarial loss deferred in OCI", "Recognize $120,000 in Q1 and $320,000 in Q2 to reflect the actuarial loss immediately", "Recognize $170,000 each quarter by spreading the actuarial loss evenly across all four quarters", "Recognize $480,000 in Q4 because pension costs are recognized annually"]'::jsonb, 0, 'Under ASC 270-10-45 and ASC 715-30-35, net periodic pension cost is an estimated annual amount allocated ratably to interim periods ($480,000 / 4 = $120,000 per quarter). The $200,000 actuarial loss from the assumption change is recognized in OCI, not directly in pension expense. It only affects future expense through corridor amortization. Choice B incorrectly treats the actuarial loss as an immediate expense item rather than an OCI deferral.', 'medium', 2),

-- Q12: medium / L2 — DC plan liability for unpaid contribution
(2, 'Employee Benefit Plans', 'Eastwood Corp. sponsors a 401(k) plan and is required to contribute $150,000 for the current fiscal year. By year-end, Eastwood has remitted $110,000 to the plan trustee. How should Eastwood report the pension-related amounts at December 31?', '["Record $110,000 as pension expense and no liability", "Record $150,000 as pension expense and a $150,000 prepaid pension asset", "Record $110,000 as pension expense and a $40,000 accrued liability", "Record $150,000 as pension expense and a $40,000 accrued liability"]'::jsonb, 3, 'Under ASC 715-70-25, a defined contribution plan sponsor recognizes pension expense equal to the required contribution for the period ($150,000). When the amount funded ($110,000) is less than the required contribution, the $40,000 difference is reported as an accrued pension liability. Choice C incorrectly limits pension expense to the cash actually contributed, ignoring the accrual basis of accounting.', 'medium', 2),

-- Q13: medium / L3 — Asset gain/loss deferral to OCI
(2, 'Employee Benefit Plans', 'Oakridge Corp.''s defined benefit plan has beginning plan assets of $3,600,000 with an expected rate of return of 6%. During the year, actual plan asset returns total $156,000 due to a market downturn. How should Oakridge account for the difference between expected and actual returns?', '["Increase pension expense by $60,000 for the asset loss in the current year", "Recognize a $60,000 loss in other comprehensive income as part of net actuarial gains and losses", "Reduce plan assets to $3,540,000 and recognize a $60,000 impairment loss on the income statement", "Recognize a $60,000 charge against retained earnings as a prior period adjustment"]'::jsonb, 1, 'Under ASC 715-30-35, expected return is $3,600,000 x 6% = $216,000. The actual return of $156,000 produces a $60,000 asset loss ($216,000 minus $156,000). This difference is deferred in other comprehensive income as part of cumulative net actuarial gains and losses, subject to future corridor amortization. Recognizing the loss immediately in pension expense (choice A) would bypass the smoothing mechanism prescribed by ASC 715.', 'medium', 3),

-- Q14: medium / L2 — VBO and vesting requirements
(2, 'Employee Benefit Plans', 'A company has 100 employees participating in its defined benefit pension plan. Fifty employees have met the plan''s five-year vesting requirement; the remaining 50 employees have two to four years of service. The PBO is $10,000,000, the ABO is $8,500,000, and the VBO is $5,200,000. Which group of employees'' benefits is reflected in the vested benefit obligation?', '["All 100 employees, based on projected future salary levels", "All 100 employees, based on current salary levels", "Only the 50 employees who have met the five-year vesting requirement", "Only the 50 employees who have not yet vested, using current salary levels"]'::jsonb, 2, 'Under ASC 715-20, the vested benefit obligation (VBO) includes only benefits that have become nonforfeitable — those earned by employees who have met the plan''s vesting requirements. The VBO of $5,200,000 reflects benefits for the 50 vested employees only, using current salary levels. The ABO (choice B with all 100 employees) includes both vested and nonvested employees at current salaries.', 'medium', 2),

-- Q15: easy / L1 — ERISA funding vs GAAP expense
(2, 'Employee Benefit Plans', 'What is the primary distinction between ERISA funding requirements and GAAP pension expense under ASC 715?', '["ERISA governs cash contributions to the plan; ASC 715 governs the expense recognized in financial statements", "ERISA determines pension expense; ASC 715 determines the funding contribution", "ERISA applies only to defined contribution plans; ASC 715 applies only to defined benefit plans", "ERISA and ASC 715 produce identical pension expense and funding amounts each year"]'::jsonb, 0, 'ERISA (Employee Retirement Income Security Act) sets minimum funding requirements for pension plan contributions, while ASC 715 governs the measurement and recognition of pension expense in GAAP financial statements. These amounts often differ because ERISA uses different actuarial methods and assumptions than GAAP. Choice D is incorrect because the funding contribution required by ERISA frequently does not equal the pension expense recognized under ASC 715.', 'easy', 1),

-- Q16: medium / L3 — Negative plan amendment (no existing PSC)
(2, 'Employee Benefit Plans', 'Sterling Industries amends its defined benefit plan to eliminate a supplemental benefit for future retirees, reducing the PBO by $320,000. There is no existing unamortized prior service cost in AOCI. The average remaining service period of affected employees is 8 years. How should Sterling initially recognize and subsequently amortize this plan amendment?', '["Recognize a $320,000 gain in pension expense immediately", "Record a $320,000 reduction in the PBO with no effect on AOCI or pension expense", "Recognize a $320,000 credit to retained earnings and amortize over 8 years", "Recognize a $320,000 credit in AOCI and amortize $40,000 per year as a reduction of pension expense"]'::jsonb, 3, 'Under ASC 715-30-35-10, a plan amendment that reduces benefits creates negative prior service cost, which is initially recognized as a credit in AOCI. This credit is then amortized over the average remaining service period: $320,000 / 8 years = $40,000 per year, reducing pension expense. Immediate gain recognition (choice A) is not permitted because ASC 715 requires amortization over the service period.', 'medium', 3),

-- Q17: medium / L3 — SIRAE mnemonic calculation
(2, 'Employee Benefit Plans', 'Mercer Industries has the following pension data: service cost $300,000; interest cost $180,000; expected return on plan assets $210,000; amortization of prior service cost $25,000; and amortization of net actuarial loss $15,000. Using the SIRAE framework for the five components of net periodic pension cost, what is Mercer''s total pension expense?', '["$310,000", "$270,000", "$520,000", "$730,000"]'::jsonb, 0, 'Under ASC 715-30-35, net periodic pension cost using SIRAE is: Service cost ($300,000) + Interest cost ($180,000) minus Return on plan assets ($210,000) + Amortization of prior service cost ($25,000) + Excess loss amortization ($15,000) = $310,000. Choice B ($270,000) omits both amortization components. Choice C ($520,000) fails to subtract the expected return on plan assets.', 'medium', 3),

-- Q18: medium / L2 — Transition obligation from initial ASC 715 adoption
(2, 'Employee Benefit Plans', 'When ASC 715 (formerly SFAS 87) was initially adopted, companies were required to recognize a transition obligation or asset. Under ASC 715, how was this transition amount originally accounted for?', '["Recognized immediately as a cumulative effect adjustment to retained earnings", "Amortized from AOCI over the greater of 15 years or the average remaining service period", "Recognized immediately as a charge or credit to OCI with no subsequent amortization", "Expensed immediately in the income statement as a special item"]'::jsonb, 1, 'Under ASC 715 (originally SFAS 87), the transition obligation or asset at initial adoption was amortized on a straight-line basis over the average remaining service period of active employees, with a minimum amortization period of 15 years if the service period was less than 15 years. Immediate recognition (choice A) was not required; the delayed recognition approach was designed to smooth the adoption impact on financial statements.', 'medium', 2),

-- Q19: hard / L4 — Net gain corridor amortization reduces pension expense
(2, 'Employee Benefit Plans', 'Aldrich Corp.''s defined benefit plan has a cumulative unrecognized net actuarial gain of $1,100,000 at the beginning of the year. The beginning PBO is $8,000,000 and the market-related value of plan assets is $8,500,000. The average remaining service period is 10 years. Before considering gain amortization, the other four components of pension cost total $420,000. What is Aldrich''s net periodic pension cost after including the required gain amortization?', '["$420,000", "$445,000", "$395,000", "$390,000"]'::jsonb, 2, 'Under ASC 715-30-35-24, the corridor is 10% of the greater of beginning PBO ($800,000) or market-related plan assets ($850,000), yielding an $850,000 corridor. The excess gain is $1,100,000 minus $850,000 = $250,000; amortization is $250,000 / 10 = $25,000. Because it is a net gain, it reduces pension expense: $420,000 minus $25,000 = $395,000. Choice D ($390,000) incorrectly uses 10% of the PBO as the corridor rather than the greater amount.', 'hard', 4),

-- Q20: easy / L1 — EPBO definition
(2, 'Employee Benefit Plans', 'Under ASC 715-60, what does the expected postretirement benefit obligation (EPBO) represent?', '["The present value of benefits earned by employees who have met vesting requirements", "The excess of the APBO over the fair value of plan assets", "The present value of benefits attributed to service already rendered", "The total expected cost of all postretirement benefits, including those attributable to future service"]'::jsonb, 3, 'Under ASC 715-60-20, the EPBO is the actuarial present value of all postretirement benefits expected to be paid, including benefits attributable to both past and future employee service. It represents the full expected cost of the plan. The APBO (choice C) is the portion of the EPBO attributed only to service already rendered. The EPBO is always equal to or greater than the APBO.', 'easy', 1),

-- Q21: easy / L1 — Pension liability current vs noncurrent classification
(2, 'Employee Benefit Plans', 'Under ASC 715, how is the current portion of an underfunded pension liability classified on the balance sheet?', '["As a current liability for benefits expected to be paid in the next 12 months that exceed plan assets", "As a noncurrent liability because all pension obligations are long-term by nature", "As a contra-asset offsetting the pension plan assets", "As an operating expense accrual in accounts payable"]'::jsonb, 0, 'Under ASC 715-20-45, if a defined benefit plan is underfunded, the employer reports the underfunded status as a liability. The current portion equals the amount by which benefits payable within 12 months exceed the fair value of plan assets. Any remaining underfunded amount is noncurrent. Choice B is incorrect because ASC 715 does require bifurcation into current and noncurrent components when applicable.', 'easy', 1),

-- Q22: easy / L1 — Plan assets held in trust definition
(2, 'Employee Benefit Plans', 'Under ASC 715, what qualifies as plan assets of a defined benefit pension plan?', '["Any investment held by the sponsoring employer designated for future benefit payments", "Assets that have been segregated and restricted in a trust or equivalent arrangement to provide pension benefits", "The sponsoring employer''s general corporate assets up to the amount of the PBO", "Cash held in the employer''s operating accounts earmarked for retirement contributions"]'::jsonb, 1, 'Under ASC 715-30-35-10, plan assets are assets that have been segregated and restricted (usually in a trust) to provide pension benefits. They must be beyond the reach of the employer''s general creditors. General corporate assets (choice C) do not qualify as plan assets even if the employer intends to use them for future contributions, because they have not been legally segregated.', 'easy', 1),

-- Q23: medium / L3 — Remeasurement events for pension
(2, 'Employee Benefit Plans', 'Brighton Corp. sponsors a defined benefit plan with a December 31 fiscal year-end. On September 1, Brighton curtails the plan by closing a major operating division, affecting 40% of plan participants. The last remeasurement was at the prior year-end. Under ASC 715, what must Brighton do regarding the plan''s measurement?', '["No interim remeasurement is required; use the prior year-end assumptions until December 31", "Remeasure the plan at December 31 only, incorporating the curtailment effect at that date", "Remeasure the plan''s benefit obligation and plan assets as of September 1 to reflect the curtailment", "Remeasure only the PBO at September 1; plan assets remain at the prior year-end fair value"]'::jsonb, 2, 'Under ASC 715-30-35-67, a significant event such as a curtailment requires remeasurement of the plan''s benefit obligation and plan assets as of the date of the event. A curtailment affecting 40% of participants is clearly significant. Waiting until year-end (choices A and B) would delay recognition of the curtailment''s financial impact. Both the PBO and plan assets must be remeasured (choice D is incomplete).', 'medium', 3),

-- Q24: easy / L1 — Expected return assumption basis
(2, 'Employee Benefit Plans', 'Under ASC 715, what is the basis for determining the expected long-term rate of return on plan assets?', '["The actual return earned on plan assets during the most recent year", "The risk-free rate based on U.S. Treasury securities", "The sponsoring employer''s weighted-average cost of capital", "The average rate of return expected over the period benefits will be paid, considering the plan''s asset allocation"]'::jsonb, 3, 'Under ASC 715-30-35-47, the expected return on plan assets reflects the average rate of earnings expected over the long term, based on the plan''s investment policy and asset mix. It is a forward-looking assumption, not based on a single year''s actual results (choice A). The risk-free rate (choice B) is too conservative and does not reflect the plan''s actual investment strategy.', 'easy', 1),

-- Q25: medium / L3 — OPEB per capita claims cost and healthcare cost trend rate
(2, 'Employee Benefit Plans', 'Cascade Health Systems measures its OPEB obligation for retiree healthcare. The actuary uses age-specific per capita claims costs that increase with age: $6,000 for ages 55-60, $8,500 for ages 61-65, and $11,000 for ages 66-70. The healthcare cost trend rate is 7% for the coming year, declining to 5% over six years. Under ASC 715-60, which factor most significantly affects the measurement of the APBO?', '["The healthcare cost trend rate, because it compounds the per capita claims cost projections over the entire benefit period", "The discount rate alone, because claims costs are already fixed by the actuary", "The plan''s asset allocation, because higher returns offset claims cost growth", "The number of active employees, because the APBO excludes retirees already receiving benefits"]'::jsonb, 0, 'Under ASC 715-60-35, the healthcare cost trend rate is the most significant assumption unique to OPEB measurement. It compounds the already age-increasing per capita claims costs over the entire expected benefit period, creating a multiplicative effect on the APBO. The discount rate (choice B) also matters but is not unique to OPEB. The APBO includes both active employees and retirees (choice D is factually incorrect).', 'medium', 3),

-- Q26: easy / L1 — DC plan forfeitures from non-vested employees
(2, 'Employee Benefit Plans', 'Under a defined contribution plan, what happens to nonvested employer contributions when an employee terminates before meeting vesting requirements?', '["The nonvested amounts are returned to the departing employee as a taxable distribution", "The nonvested amounts are forfeited and may be used to reduce future employer contributions or reallocated to remaining participants", "The nonvested amounts remain in the employee''s account indefinitely until the employee returns", "The nonvested amounts are reported as pension expense in the year of forfeiture"]'::jsonb, 1, 'Under defined contribution plan provisions and ERISA regulations, when an employee leaves before fully vesting, the nonvested portion of employer contributions is forfeited. These forfeitures are typically used to reduce future employer contributions or reallocated among remaining plan participants, depending on the plan document. Returning nonvested amounts to the departing employee (choice A) would contradict the purpose of vesting schedules.', 'easy', 1),

-- Q27: easy / L1 — AOCI pension components
(2, 'Employee Benefit Plans', 'Under ASC 715, which pension-related items are reported in accumulated other comprehensive income (AOCI)?', '["Service cost and interest cost for the current period", "The funded status of the plan and accrued benefit payments", "Unamortized prior service cost and unamortized net actuarial gains or losses", "Employer contributions and benefits paid during the period"]'::jsonb, 2, 'Under ASC 715-20-50, the pension-related items in AOCI include unamortized prior service cost from plan amendments and unamortized net actuarial gains and losses from assumption changes and experience differences. These items are reclassified to pension expense as they are amortized. Service cost and interest cost (choice A) are components of pension expense recognized currently, not deferred in AOCI.', 'easy', 1),

-- Q28: hard / L4 — Medicare eligibility effect on OPEB measurement
(2, 'Employee Benefit Plans', 'Redwood Manufacturing provides postretirement healthcare benefits to employees who retire after age 55 with 15 years of service. When retirees reach age 65 and become eligible for Medicare, Redwood''s plan becomes secondary to Medicare, significantly reducing per-retiree claims costs. The actuary is measuring the APBO for a workforce with an average current age of 52. How does Medicare eligibility at age 65 affect the measurement of Redwood''s OPEB obligation?', '["It reduces the APBO because projected per-retiree claims costs decline substantially once Medicare becomes the primary payer after age 65", "It has no effect on the APBO because Medicare is a government program outside the scope of ASC 715-60", "It increases the APBO because the company must fund the Medicare Part B premium for each retiree", "It eliminates the OPEB obligation entirely at age 65 because Medicare replaces the employer plan"]'::jsonb, 0, 'Under ASC 715-60-35, the measurement of the APBO must reflect all relevant factors affecting future benefit costs, including the expected impact of Medicare. When retirees become Medicare-eligible at 65, the employer plan becomes secondary, substantially reducing projected claims costs for the post-65 period. This lowers the APBO. Choice D is incorrect because the employer plan typically continues as a supplement to Medicare, covering deductibles and copayments.', 'hard', 4),

-- Q29: medium / L2 — Pension disclosure requirements
(2, 'Employee Benefit Plans', 'Under ASC 715-20-50, which of the following is required to be disclosed in the notes to the financial statements for a defined benefit pension plan?', '["The individual investment holdings of the pension trust and their market prices", "The names and compensation of the plan''s trustees and investment managers", "A reconciliation of the plan''s tax returns to GAAP pension expense", "The expected employer contributions to the plan for the upcoming fiscal year"]'::jsonb, 3, 'ASC 715-20-50-1 requires disclosure of an employer''s best estimate of contributions expected to be paid to the plan during the next fiscal year. This helps financial statement users assess future cash flow demands. Individual investment holdings at the security level (choice A) are not required; instead, ASC 715 requires disclosure of plan assets by major category such as equity, fixed income, and real estate.', 'medium', 2),

-- Q30: easy / L2 — DC plan expense recognition timing (accrual basis)
(2, 'Employee Benefit Plans', 'Richmond Corp. has a December 31 fiscal year-end and sponsors a defined contribution plan requiring quarterly contributions. The Q4 contribution of $75,000 is due January 15 of the following year. How should Richmond report the Q4 contribution in its December 31 financial statements?', '["No expense or liability until the $75,000 is actually paid on January 15", "Pension expense of $75,000 and an accrued liability of $75,000 at December 31", "Pension expense of $75,000 and a prepaid asset of $75,000 at December 31", "No pension expense; the $75,000 is disclosed only in the footnotes"]'::jsonb, 1, 'Under ASC 715-70-25, defined contribution plan expense is recognized in the period in which employees earn the benefit, regardless of when the contribution is paid. Since the Q4 contribution relates to Q4 service, Richmond recognizes $75,000 of pension expense and a corresponding accrued liability at December 31. Deferring recognition until payment (choice A) violates the accrual basis of accounting required under GAAP.', 'easy', 2)
;

COMMIT;
