-- Migration: Question generation — REG batch 41 (30 questions)
-- Date: 2026-03-03
-- Topic: Individual Taxation: Deductions
-- Difficulty: 9E / 15M / 6H
-- Bloom's: L1:8 / L2:9 / L3:8 / L4:5

BEGIN;

INSERT INTO questions (section_id, topic, stem, choices, correct_index, explanation, difficulty, cognitive_level)
VALUES

-- Q1: medium / L2 — Additional standard deduction for age 65+
(3, 'Individual Taxation: Deductions', 'Mitchell, age 68 and single, is deciding whether to itemize or take the standard deduction for 2026. His itemizable expenses total $15,800. The 2026 standard deduction for single filers is $15,000. Mitchell is unaware of the additional standard deduction for taxpayers age 65 or older (approximately $1,950 for single filers). What is the most accurate advice?', '["Mitchell should take the standard deduction because the additional amount for age 65+ brings his total to approximately $16,950, exceeding his $15,800 in itemized deductions", "Mitchell should itemize because $15,800 exceeds the $15,000 base standard deduction", "Mitchell should take the standard deduction because taxpayers over 65 cannot itemize", "Mitchell should itemize because the additional standard deduction only applies to married filers"]'::jsonb, 0, 'Under IRC Section 63(f), taxpayers age 65 or older receive an additional standard deduction (~$1,950 for single filers in 2026), bringing Mitchell''s total standard deduction to approximately $16,950. Since this exceeds his $15,800 in itemizable expenses, the standard deduction is more beneficial. Being over 65 does not prohibit itemizing — the additional amount simply makes the standard deduction more competitive. The common error is comparing itemized deductions only to the base standard deduction without considering the age-related addition.', 'medium', 2),

-- Q2: medium / L3 — Charitable contribution carryforward (5-year rule)
(3, 'Individual Taxation: Deductions', 'Barnes, a single filer with AGI of $100,000, donates appreciated stock (held 4 years, FMV $45,000, basis $12,000) to a public charity in 2026. The 30% AGI limit allows a maximum deduction of $30,000 in 2026. How should Barnes treat the remaining $15,000?', '["The $15,000 excess is permanently lost and cannot be deducted", "The $15,000 carries forward for up to five years, subject to the same AGI percentage limits", "The $15,000 must be deducted on an amended return for the prior year", "The $15,000 converts to an above-the-line deduction in the following year"]'::jsonb, 1, 'Under IRC Section 170(d)(1), charitable contributions exceeding the applicable AGI percentage limit carry forward for up to five years, subject to the same limitation in each carryforward year. Barnes deducts $30,000 (30% of $100,000 AGI) in 2026 and carries the remaining $15,000 to 2027. The excess is not lost — unlike the misconception that unused charitable deductions expire immediately, the five-year carryforward ensures taxpayers eventually benefit from large donations.', 'medium', 3),

-- Q3: medium / L3 — Casualty and theft loss calculation
(3, 'Individual Taxation: Deductions', 'Patel''s home sustains $25,000 in damage from a federally declared hurricane in 2026. Insurance reimburses $10,000. Patel''s AGI is $120,000. Applying the casualty loss limitations under current law, what is Patel''s deductible casualty loss on Schedule A?', '["$14,900", "$12,000", "$2,900", "$15,000"]'::jsonb, 2, 'Under IRC Section 165(h), personal casualty losses (limited to federally declared disasters under current law) are reduced by a $100 per-event floor and then by 10% of AGI. Patel''s $15,000 unreimbursed loss ($25,000 minus $10,000) minus $100 = $14,900, then minus 10% x $120,000 ($12,000) = $2,900 deductible. The most common error is applying only one of the two thresholds — both the $100 floor and the 10% AGI floor must be applied sequentially.', 'medium', 3),

-- Q4: medium / L2 — Medical expenses: qualifying vs. non-qualifying
(3, 'Individual Taxation: Deductions', 'Harrison, a single filer with AGI of $60,000, paid the following in 2026: $3,000 for prescription medications, $2,500 for elective cosmetic surgery, $1,800 for dental work, and $600 for over-the-counter vitamins. What is Harrison''s total qualifying medical expense before applying the 7.5% AGI floor?', '["$7,900", "$6,300", "$5,300", "$4,800"]'::jsonb, 3, 'Under IRC Section 213, deductible medical expenses include costs for diagnosis, treatment, and prevention of disease. Prescription medications ($3,000) and dental work ($1,800) qualify, totaling $4,800. Elective cosmetic surgery is specifically excluded under Section 213(d)(9) unless it addresses a deformity from disease, accident, or congenital abnormality. General-health vitamins and supplements taken without a prescription do not qualify. The common error is including cosmetic surgery as a medical expense.', 'medium', 2),

-- Q5: easy / L1 — Charitable contributions of ordinary income property
(3, 'Individual Taxation: Deductions', 'What is the deduction amount for donating ordinary income property (such as inventory or short-term capital gain property) to a qualified charity?', '["Fair market value of the property", "60% of the donor''s AGI", "30% of the donor''s AGI", "The property''s adjusted basis"]'::jsonb, 3, 'Under IRC Section 170(e)(1)(A), when a taxpayer donates ordinary income property to a charity, the deduction is limited to the property''s adjusted basis rather than fair market value. This applies to inventory, short-term capital gain property, and other assets that would produce ordinary income if sold. The FMV deduction is reserved for long-term capital gain property donated to public charities — a key distinction tested on the exam.', 'easy', 1),

-- Q6: medium / L2 — Grandfathered $1M mortgage interest limit
(3, 'Individual Taxation: Deductions', 'Dawson purchased a primary residence in 2015 with a $950,000 mortgage. In 2026, the outstanding balance is $820,000 and Dawson paid $34,000 in mortgage interest. How much mortgage interest can Dawson deduct on Schedule A?', '["$34,000 because the pre-December 15, 2017 mortgage is grandfathered under the $1,000,000 limit", "$30,625, proportionally limited to $750,000 of debt", "$0 because the original mortgage exceeded $750,000", "$27,000, limited to a fixed percentage of the interest paid"]'::jsonb, 0, 'Under IRC Section 163(h)(3), as modified by the TCJA, the $750,000 acquisition debt limit applies only to mortgages originated after December 15, 2017. Dawson''s mortgage originated in 2015 and is grandfathered under the prior $1,000,000 limit. Since the $820,000 balance remains under $1,000,000, the full $34,000 of interest is deductible. The common error is applying the $750,000 cap retroactively to pre-TCJA mortgages.', 'medium', 2),

-- Q7: medium / L3 — Moving expenses deduction (military only)
(3, 'Individual Taxation: Deductions', 'Two taxpayers relocate for work in 2026. Sergeant Adams, active-duty military, moves due to a permanent change of station order. Brooks, a civilian marketing manager, moves 500 miles for a new employer. Both incur $6,000 in moving costs. Under current law, how do their moving expense deductions compare?', '["Both can deduct $6,000 as above-the-line deductions", "Both can deduct $6,000 as itemized deductions", "Only Adams can deduct $6,000; Brooks receives no moving expense deduction", "Adams can deduct $6,000; Brooks can deduct up to $3,000"]'::jsonb, 2, 'Under IRC Section 217, as amended by the TCJA and continued under H.R. 1, the moving expense deduction is available only to active-duty members of the Armed Forces who move pursuant to a military order for a permanent change of station. The deduction was suspended for all other taxpayers beginning in 2018. Adams qualifies for the full $6,000 above-the-line deduction, while Brooks receives no deduction. The common error is assuming the civilian moving deduction was restored.', 'medium', 3),

-- Q8: easy / L1 — MFS: both must itemize or both take standard
(3, 'Individual Taxation: Deductions', 'When a married couple files separately (MFS), what rule applies to their choice between the standard deduction and itemized deductions?', '["Each spouse may independently choose to itemize or take the standard deduction", "If one spouse itemizes, the other must also itemize", "Neither spouse is permitted to itemize when filing separately", "The spouse with lower income must take the standard deduction"]'::jsonb, 1, 'Under IRC Section 63(c)(6)(A), when married taxpayers file separately, if one spouse itemizes deductions, the other must also itemize — the standard deduction becomes zero for the non-itemizing spouse. This rule prevents one spouse from claiming itemized deductions while the other takes a standard deduction, which could provide a combined benefit exceeding MFJ. The common misconception is that MFS filers can independently choose their deduction method.', 'easy', 1),

-- Q9: easy / L1 — Gambling losses limited to winnings
(3, 'Individual Taxation: Deductions', 'Under IRC Section 165(d), how are gambling losses treated for individual taxpayers?', '["Gambling losses are fully deductible as above-the-line deductions", "Gambling losses are deductible up to $3,000 per year", "Gambling losses are not deductible under any circumstances", "Gambling losses are deductible as itemized deductions but only to the extent of gambling winnings"]'::jsonb, 3, 'Under IRC Section 165(d), gambling losses are deductible as an itemized deduction on Schedule A but only to the extent of gambling winnings reported as income. A taxpayer cannot create a net loss from gambling to offset other income. Gambling winnings must be reported in full as gross income, and losses exceeding winnings cannot be carried forward. The common error is confusing gambling losses with capital losses, which have a $3,000 annual deduction limit.', 'easy', 1),

-- Q10: medium / L2 — Charitable substantiation $250+ requirement
(3, 'Individual Taxation: Deductions', 'Collins donates $500 in cash to a qualified church in 2026. She obtains a bank statement showing the transfer but does not receive written acknowledgment from the church. Can Collins claim the charitable deduction on Schedule A?', '["Yes, the bank statement alone is sufficient for any cash donation amount", "No, a contemporaneous written acknowledgment from the donee is required for contributions of $250 or more", "Yes, because donations to religious organizations are exempt from substantiation rules", "No, charitable deductions require a qualified appraisal for all donations over $250"]'::jsonb, 1, 'Under IRC Section 170(f)(8), no deduction is allowed for a charitable contribution of $250 or more unless the taxpayer obtains a contemporaneous written acknowledgment from the donee organization. The acknowledgment must state the amount of cash contributed and whether the organization provided goods or services in return. A bank statement alone is insufficient for donations of $250 or more. The common error is confusing the $250 acknowledgment rule with the $5,000 appraisal requirement for noncash property.', 'medium', 2),

-- Q11: hard / L4 — Investment interest expense limitation
(3, 'Individual Taxation: Deductions', 'Harper, a single filer, has the following 2026 investment activity: $18,000 margin interest paid on a brokerage account, $6,000 in taxable interest income, $4,000 in qualified dividends, and $3,000 in short-term capital gains. Harper does not elect to treat qualified dividends as ordinary income. Under Section 163(d), what is her maximum investment interest deduction and where does it appear in the tax formula?', '["Above-the-line deduction of $18,000", "Itemized deduction of $13,000", "Itemized deduction of $9,000", "Itemized deduction of $18,000"]'::jsonb, 2, 'Under IRC Section 163(d), investment interest expense is deductible as an itemized deduction, limited to net investment income. Harper''s net investment income includes taxable interest ($6,000) and short-term capital gains ($3,000) = $9,000. Qualified dividends are excluded from net investment income unless the taxpayer elects to treat them as ordinary income under Section 163(d)(4)(B). The remaining $9,000 carries forward indefinitely. The common error is including qualified dividends in net investment income without the election.', 'hard', 4),

-- Q12: hard / L4 — HSA eligibility and disqualifying coverage
(3, 'Individual Taxation: Deductions', 'In 2026, Ellis (age 58, single) is enrolled in a high-deductible health plan and contributes to an HSA. She also has a traditional health FSA through her employer that reimburses all medical expenses. Her spouse, employed separately, has standard PPO coverage. Under Section 223, what disqualifies Ellis from making tax-deductible HSA contributions?', '["Being over age 55 limits HSA eligibility to reduced amounts", "Her spouse''s PPO coverage makes Ellis ineligible for HSA contributions", "HSA contributions are only deductible for self-employed taxpayers", "The general-purpose health FSA provides disqualifying other coverage"]'::jsonb, 3, 'Under IRC Section 223(c)(1), an eligible individual must be covered by a high-deductible health plan and must NOT be covered by other health coverage that is not an HDHP. A general-purpose health FSA constitutes disqualifying coverage because it provides first-dollar medical reimbursement. Only a limited-purpose FSA (dental/vision only) or post-deductible FSA is compatible with HSA eligibility. The common error is assuming the spouse''s separate PPO coverage disqualifies the HSA participant — only the participant''s own coverage matters.', 'hard', 4),

-- Q13: medium / L3 — Mortgage points: purchase vs. refinance
(3, 'Individual Taxation: Deductions', 'Ortega purchases a new primary residence in 2026, paying $6,000 in loan origination points on a $300,000 30-year mortgage. Her colleague Franklin refinances an existing $300,000 mortgage and also pays $6,000 in points. How should each taxpayer treat the points for tax purposes?', '["Ortega deducts $6,000 in full in 2026; Franklin must amortize $6,000 over the 30-year loan term", "Both deduct $6,000 in full in 2026", "Both must amortize $6,000 over the 30-year loan term", "Ortega must amortize over 30 years; Franklin deducts in full in 2026"]'::jsonb, 0, 'Under IRC Section 461(g) and Rev. Proc. 94-27, points paid on the purchase of a primary residence are deductible in the year paid if they meet standard lending practice requirements. Points paid on a refinance must be amortized over the life of the new loan because they are prepaid interest for a non-purchase transaction. Ortega deducts $6,000 immediately, while Franklin deducts $200 per year ($6,000 / 30). The common error is assuming refinance points receive the same immediate deduction as purchase points.', 'medium', 3),

-- Q14: medium / L2 — Non-cash charitable appraisal $5,000+ threshold
(3, 'Individual Taxation: Deductions', 'Cooper donates a painting (held 5 years, FMV $8,000, basis $1,500) to a qualified museum in 2026. What substantiation requirement must Cooper satisfy to claim the charitable deduction?', '["A cancelled check or receipt from the museum is sufficient", "A written acknowledgment from the museum stating the FMV is sufficient", "Cooper must complete Form 8283, Section A only", "Cooper must obtain a qualified appraisal and complete Form 8283, Section B"]'::jsonb, 3, 'Under IRC Section 170(f)(11)(C) and Reg. 1.170A-13(c), noncash charitable contributions exceeding $5,000 require a qualified appraisal by a qualified appraiser and completion of Form 8283, Section B. Cooper''s painting has an FMV of $8,000, triggering this requirement. Section A of Form 8283 applies to noncash donations between $500 and $5,000. The common error is assuming the donee organization''s acknowledgment alone satisfies substantiation for high-value noncash gifts.', 'medium', 2),

-- Q15: medium / L3 — HOH standard deduction application
(3, 'Individual Taxation: Deductions', 'Reeves, unmarried, pays more than half the cost of maintaining a home for her 10-year-old dependent son in 2026. She has $6,000 in mortgage interest, $4,500 in state income taxes, and $2,000 in charitable contributions as potential itemized deductions. The 2026 standard deduction for Head of Household filers is approximately $22,500. What should Reeves do?', '["Itemize because $12,500 in deductions exceeds any standard deduction", "Take the $22,500 HOH standard deduction because it exceeds her $12,500 in itemized deductions", "File as single and take the $15,000 standard deduction", "Itemize because Head of Household filers are required to itemize"]'::jsonb, 1, 'Under IRC Section 2(b), Reeves qualifies for Head of Household status (unmarried, pays over half household costs, qualifying child lived in home over half the year). The HOH standard deduction (~$22,500) substantially exceeds her $12,500 in itemizable expenses. HOH filers are not required to itemize and benefit from a larger standard deduction than single filers. The common error is failing to apply the correct filing status and comparing against the $15,000 single standard deduction.', 'medium', 3),

-- Q16: easy / L1 — Personal interest is non-deductible
(3, 'Individual Taxation: Deductions', 'Under current tax law, which type of interest is generally NOT deductible by individual taxpayers?', '["Mortgage interest on a primary residence", "Investment interest on margin loans", "Interest on personal credit card balances", "Student loan interest"]'::jsonb, 2, 'Under IRC Section 163(h), personal interest is not deductible. Personal interest includes interest on credit card balances, car loans (unless qualifying under H.R. 1 for U.S.-made vehicles), and other consumer debt. Mortgage interest, investment interest, and student loan interest each have specific Code provisions allowing deduction subject to their respective limitations. Personal (consumer) interest has been nondeductible since the Tax Reform Act of 1986.', 'easy', 1),

-- Q17: hard / L4 — Charitable deduction bunching strategy analysis
(3, 'Individual Taxation: Deductions', 'Wheeler, a single filer, has $10,000 in annual non-charitable itemized deductions and typically donates $5,000 to charity each year, bringing total itemized deductions to $15,000 — equal to the $15,000 standard deduction. Her advisor suggests a bunching strategy: donate $10,000 in Year 1 and $0 in Year 2 instead of $5,000 each year. What is the additional two-year deduction benefit of the bunching approach?', '["No additional benefit — total deductions over two years are identical", "$2,500 in additional deductions", "$4,000 in additional deductions", "$5,000 in additional deductions"]'::jsonb, 3, 'Under the bunching strategy, Wheeler concentrates charitable giving to exceed the standard deduction threshold. Without bunching: each year she takes the $15,000 standard deduction (equal to itemized), totaling $30,000. With bunching: Year 1 she itemizes $20,000 ($10,000 non-charitable + $10,000 charity); Year 2 she takes the $15,000 standard deduction — totaling $35,000, a $5,000 benefit. This strategy became especially valuable after the TCJA increased the standard deduction, pushing many taxpayers below the itemizing threshold.', 'hard', 4),

-- Q18: easy / L1 — Personal interest non-deductible rule
(3, 'Individual Taxation: Deductions', 'Under IRC Section 163(h)(1), personal interest paid on consumer debt is:', '["Not deductible for individual taxpayers", "Deductible as an itemized deduction on Schedule A", "Deductible as an above-the-line adjustment to gross income", "Deductible up to $2,500 per year"]'::jsonb, 0, 'Under IRC Section 163(h)(1), personal interest is not deductible. Personal interest includes interest on credit cards, personal loans, and non-qualifying auto loans. This rule, in effect since the Tax Reform Act of 1986, distinguishes personal interest from deductible categories such as qualified residence interest under Section 163(h)(3), investment interest under Section 163(d), and student loan interest under Section 221. The $2,500 limit applies to student loan interest, not personal interest.', 'easy', 1),

-- Q19: medium / L2 — Charitable donation of used clothing
(3, 'Individual Taxation: Deductions', 'Nelson donates used clothing with an original cost of $2,000 and a current thrift-store value of $300 to a qualified charity in 2026. The items are in good condition. What charitable deduction may Nelson claim?', '["$2,000, the original cost", "$300, the fair market value in current condition", "$0 because used clothing is never deductible", "$1,000, which is 50% of original cost"]'::jsonb, 1, 'Under IRC Section 170(f)(16), donations of clothing and household items must be in at least good used condition to qualify for a deduction. When this standard is met, the deduction equals the property''s fair market value at the time of donation — typically the thrift-store or resale value, not the original purchase price. Nelson''s $300 FMV is the correct deduction amount. The common error is claiming the original cost basis rather than the current FMV of used items.', 'medium', 2),

-- Q20: medium / L2 — Medical expense: capital improvements for medical purposes
(3, 'Individual Taxation: Deductions', 'Hoffman, who uses a wheelchair, spends $20,000 installing a ramp and widening doorways at her home in 2026. A qualified appraiser determines the improvements increase the home''s value by $8,000. Her AGI is $100,000. What amount of the capital improvement qualifies as a medical expense before applying the 7.5% AGI floor?', '["$20,000, the full cost of the improvements", "$0 because capital improvements are never deductible as medical expenses", "$8,000, the increase in property value", "$12,000, the cost exceeding the increase in property value"]'::jsonb, 3, 'Under IRC Section 213(a) and Reg. 1.213-1(e)(1)(iii), capital improvements for medical purposes are deductible as medical expenses to the extent the cost exceeds the increase in property value. Hoffman spent $20,000 and the improvements added $8,000 in value, so $12,000 qualifies ($20,000 minus $8,000). This amount then joins other medical expenses subject to the 7.5% AGI floor. The common error is deducting the full cost without reducing it by the value added to the property.', 'medium', 2),

-- Q21: medium / L3 — Student loan interest phase-out calculation
(3, 'Individual Taxation: Deductions', 'Yang, a single filer, has MAGI of $85,000 in 2026 and paid $2,500 in qualifying student loan interest. The Section 221 phase-out range for single filers begins at $80,000 and ends at $95,000. How much student loan interest can Yang deduct?', '["$2,500", "$0", "$1,667", "$1,250"]'::jsonb, 2, 'Under IRC Section 221, the student loan interest deduction (maximum $2,500) phases out ratably over the applicable MAGI range. Yang''s MAGI of $85,000 is $5,000 into the $15,000 phase-out range ($80,000 to $95,000), reducing the deduction by one-third ($833). The allowable deduction is $2,500 minus $833 = $1,667. This is an above-the-line deduction available regardless of itemizing. The common error is assuming the deduction is fully eliminated once the phase-out range begins.', 'medium', 3),

-- Q22: easy / L1 — Charitable contribution carryforward period
(3, 'Individual Taxation: Deductions', 'What is the maximum carryforward period for unused charitable contributions that exceed the applicable AGI percentage limitations?', '["5 years", "3 years", "7 years", "20 years"]'::jsonb, 0, 'Under IRC Section 170(d)(1), charitable contributions that exceed the applicable AGI percentage limitation in the current year may be carried forward for up to five subsequent tax years. The carryforward contributions are subject to the same AGI percentage limits in each future year. Unused amounts remaining after five years expire permanently. The 20-year carryforward applies to corporate charitable contributions under different rules — not individual taxpayers.', 'easy', 1),

-- Q23: medium / L2 — SE tax deduction calculation (50%)
(3, 'Individual Taxation: Deductions', 'Nakamura, a self-employed web designer, has net self-employment earnings of $120,000 in 2026. Her total self-employment tax (Social Security and Medicare combined) is $16,956. What is her above-the-line deduction for self-employment tax?', '["$16,956", "$12,000", "$6,000", "$8,478"]'::jsonb, 3, 'Under IRC Section 164(f), self-employed individuals may deduct 50% of self-employment tax as an above-the-line deduction (adjustment to gross income). Nakamura''s deduction is $16,956 x 50% = $8,478. This mirrors the employer''s share of FICA that W-2 employees never see as taxable income. The deduction reduces AGI, which can improve eligibility for other phase-out-dependent tax benefits. The common error is deducting the full SE tax amount rather than the 50% deductible portion.', 'medium', 2),

-- Q24: medium / L3 — IRA deduction for non-active participant spouse
(3, 'Individual Taxation: Deductions', 'Grant and Lee file jointly for 2026. Grant participates in his employer''s 401(k) plan; Lee does not participate in any employer retirement plan. Lee contributes $7,000 to a traditional IRA. Their combined MAGI is $220,000. The 2026 phase-out for a non-active-participant spouse is $230,000 to $240,000 (MFJ). What is Lee''s deductible IRA contribution?', '["$0 because Grant''s 401(k) participation eliminates both spouses'' IRA deductions", "$7,000 because Lee is below the non-active-participant spouse phase-out range", "$3,500 because Lee can only deduct half when filing jointly with an active participant", "$0 because their MAGI exceeds $200,000"]'::jsonb, 1, 'Under IRC Section 219(g)(7), a spouse who does not actively participate in an employer retirement plan has a separate, higher MAGI phase-out range for the traditional IRA deduction. For 2026 MFJ filers, this range is $230,000 to $240,000. Since their MAGI of $220,000 is below $230,000, Lee can deduct the full $7,000 contribution. The common error is applying the active participant phase-out range ($123,000 to $143,000 MFJ) to the non-participating spouse.', 'medium', 3),

-- Q25: hard / L4 — Conservation easement charitable deduction
(3, 'Individual Taxation: Deductions', 'Reynolds, a single taxpayer with AGI of $200,000, donates a qualified conservation easement valued at $120,000 on property with a basis of $50,000 to a qualified land trust in 2026. Reynolds is not a qualified farmer or rancher. What is the maximum charitable deduction Reynolds can claim in 2026 for this easement?', '["$120,000", "$60,000, limited to 30% of AGI", "$100,000, limited to 50% of AGI", "$50,000, limited to basis"]'::jsonb, 2, 'Under IRC Section 170(b)(1)(E), qualified conservation contributions by non-farmer/rancher individuals are deductible up to 50% of the taxpayer''s contribution base (essentially AGI) for the year, with a 15-year carryforward for excess amounts. This is more generous than the standard 30% limit for appreciated property. Reynolds'' $200,000 AGI x 50% = $100,000 maximum for 2026, with the remaining $20,000 carrying forward. The common error is applying the standard 30% capital gain property limit to conservation easements.', 'hard', 4),

-- Q26: hard / L4 — Comprehensive itemized deduction analysis with multiple limits
(3, 'Individual Taxation: Deductions', 'Walsh, age 45 and single, has AGI of $200,000 in 2026. She paid: $16,000 in unreimbursed medical expenses, $6,000 in state income tax, $5,000 in property tax, $20,000 in mortgage interest on a $700,000 acquisition loan, and donated $125,000 cash to a public charity. Calculate Walsh''s total itemized deductions.', '["$156,000", "$151,000", "$152,000", "$166,000"]'::jsonb, 1, 'Under IRC Sections 213, 164, 163(h), and 170, each itemized deduction has specific limitations. Medical: $16,000 minus 7.5% of AGI ($15,000) = $1,000. SALT: $6,000 + $5,000 = $11,000, capped at $10,000. Mortgage interest: $20,000 (loan under $750,000 limit). Cash charitable: 60% of AGI = $120,000 cap ($125,000 donated, $5,000 carries forward). Total: $1,000 + $10,000 + $20,000 + $120,000 = $151,000. The most common errors are forgetting the SALT cap ($152,000) or the charitable AGI ceiling ($156,000).', 'hard', 4),

-- Q27: hard / L3 — Mortgage interest MFS limit vs. MFJ
(3, 'Individual Taxation: Deductions', 'Crawford and Dixon are married. Crawford has $500,000 in acquisition debt on a home purchased in 2020 and pays $22,000 in mortgage interest. If they file jointly, the full $22,000 is deductible under the $750,000 MFJ limit. If Crawford files separately, what is the deductible mortgage interest?', '["$16,500, because the MFS acquisition debt limit is $375,000", "$22,000, because the $750,000 limit applies regardless of filing status", "$22,000, because the 2020 origination date grandfathers the higher limit", "$0, because MFS filers cannot deduct mortgage interest"]'::jsonb, 0, 'Under IRC Section 163(h)(3)(F)(i)(II), the acquisition debt limit for married filing separately is $375,000 — half the $750,000 MFJ limit. Since Crawford''s $500,000 debt exceeds $375,000, the interest deduction is proportionally limited: $22,000 x ($375,000 / $500,000) = $16,500. The 2020 origination date falls after December 15, 2017, so the TCJA limits apply (not the grandfathered $1M/$500K amounts). The common error is assuming the full MFJ limit applies regardless of filing status.', 'hard', 3),

-- Q28: easy / L2 — Medical expense items that qualify
(3, 'Individual Taxation: Deductions', 'Chen has AGI of $50,000 in 2026 and paid $5,000 for eyeglasses and contact lenses, $2,000 for a gym membership to improve general fitness, and $1,500 for prescription medications. Which expenses qualify as deductible medical expenses under Section 213?', '["$5,000 for eyeglasses and contacts only", "$8,500 for all three expenses", "$6,500 for eyeglasses, contacts, and prescriptions", "$1,500 for prescriptions only"]'::jsonb, 2, 'Under IRC Section 213(d), deductible medical expenses include costs for diagnosis, cure, treatment, or prevention of disease. Eyeglasses, contact lenses ($5,000), and prescription medications ($1,500) qualify, totaling $6,500. Gym memberships for general fitness do not qualify as medical expenses even if recommended by a physician for overall health improvement. Only exercise programs specifically prescribed to treat a diagnosed condition may qualify. The common error is including general wellness costs.', 'easy', 2),

-- Q29: easy / L1 — Taxable income formula
(3, 'Individual Taxation: Deductions', 'What is the correct formula for calculating an individual taxpayer''s taxable income?', '["AGI minus the greater of the standard deduction or itemized deductions, minus the QBI deduction if applicable", "Gross income minus itemized deductions only", "AGI minus above-the-line deductions", "Gross income minus the standard deduction minus tax credits"]'::jsonb, 0, 'Under IRC Sections 63 and 199A, taxable income equals AGI minus the greater of the standard deduction or itemized deductions, minus the qualified business income (QBI) deduction if applicable. Above-the-line deductions are already subtracted to arrive at AGI and are not deducted again. Tax credits reduce tax liability, not taxable income. Understanding this formula sequence (Gross Income to AGI to Taxable Income) is fundamental to individual tax computation.', 'easy', 1),

-- Q30: easy / L1 — ACID mnemonic for above-the-line deductions
(3, 'Individual Taxation: Deductions', 'The mnemonic ACID helps taxpayers remember major above-the-line deductions (adjustments to gross income). What does ACID represent?', '["Alternative tax, Credits, Insurance premiums, Depreciation", "Alimony (pre-2019), Contributions to IRA, Interest on student loans, Deduction for 50% SE tax", "Adjusted income, Capital losses, Itemized deductions, Dividends received", "Accounting fees, Charitable gifts, Investment expenses, Dues"]'::jsonb, 1, 'The ACID mnemonic represents four major above-the-line deductions: Alimony paid (for pre-2019 divorce agreements), Contributions to a traditional IRA, Interest on student loans (up to $2,500), and Deduction for 50% of self-employment tax. These deductions reduce gross income to arrive at AGI and are available regardless of whether the taxpayer itemizes. The mnemonic captures that these adjustments dissolve income before AGI is calculated, consistent with the individual tax formula.', 'easy', 1)
;

COMMIT;
