-- Migration: Question generation — REG batch 40 (30 questions)
-- Date: 2026-03-02
-- Topic: Individual Taxation: Credits/AMT
-- Difficulty: 9E / 15M / 6H
-- Bloom's: L1:8 / L2:9 / L3:8 / L4:5

BEGIN;

INSERT INTO questions (section_id, topic, stem, choices, correct_index, explanation, difficulty, cognitive_level)
VALUES

-- Q1: medium / L3 — CTC phaseout calculation
(3, 'Individual Taxation: Credits/AMT', 'Patterson, a single filer, has AGI of $215,000 and two qualifying children under age 17 in 2026. The Child Tax Credit phases out by $50 for each $1,000 (or fraction thereof) above $200,000 for single filers. What is Patterson''s total Child Tax Credit after the phaseout reduction?', '["$3,250", "$3,500", "$4,000", "$2,500"]'::jsonb, 0, 'Under IRC Section 24, the Child Tax Credit provides $2,000 per qualifying child under 17. The credit phases out at $200,000 AGI (single), reduced by $50 per $1,000 of excess AGI. Patterson''s excess is $15,000, yielding a $750 reduction (15 × $50). The total credit is $4,000 − $750 = $3,250. The $4,000 answer incorrectly ignores the phaseout, which is mandatory once AGI exceeds the threshold.', 'medium', 3),

-- Q2: hard / L4 — AOTC vs LLC multi-student family optimization
(3, 'Individual Taxation: Credits/AMT', 'Whitfield and Garcia (MFJ, MAGI $155,000) have three dependents in college: two undergraduates in year 2 and one graduate student in an MBA program. Each incurs $5,000 in qualifying tuition. Which filing strategy maximizes their total education credit?', '["Claim the LLC for all three students for a total credit of $3,000", "Claim the AOTC for both undergraduates for a total credit of $5,000", "Claim the AOTC for both undergraduates and the LLC for the graduate student for a total credit of $6,000", "Claim the AOTC for all three students for a total credit of $7,500"]'::jsonb, 2, 'Under IRC Section 25A, the AOTC ($2,500/student, first 4 years) applies to the undergraduates, while the LLC (20% of up to $10,000, per return) covers the graduate student. This yields $5,000 (AOTC) + $1,000 (LLC on $5,000 tuition) = $6,000. Claiming AOTC for all three fails because graduate students are ineligible for the AOTC, which is limited to the first four years of postsecondary education.', 'hard', 4),

-- Q3: medium / L2 — FTC limitation formula
(3, 'Individual Taxation: Credits/AMT', 'Nakamura has worldwide taxable income of $300,000, including $75,000 of foreign-source general category income. Her U.S. tax liability is $60,000, and she paid $18,000 in foreign taxes. Under IRC Section 904, what is her allowable foreign tax credit?', '["$18,000", "$15,000", "$12,000", "$60,000"]'::jsonb, 1, 'Under IRC Section 904, the foreign tax credit is limited to U.S. tax liability multiplied by the ratio of foreign-source income to worldwide income: $60,000 × ($75,000 ÷ $300,000) = $15,000. Although $18,000 was paid, only $15,000 is allowable. The $3,000 excess carries back one year and forward ten years. The $18,000 answer incorrectly ignores the limitation, which prevents the credit from reducing tax on U.S.-source income.', 'medium', 2),

-- Q4: easy / L1 — Refundable vs nonrefundable credits
(3, 'Individual Taxation: Credits/AMT', 'What is the key difference between a refundable tax credit and a nonrefundable tax credit?', '["A refundable credit reduces taxable income rather than tax liability", "A nonrefundable credit can generate a cash refund to the taxpayer", "A refundable credit is always larger in dollar amount than a nonrefundable credit", "A refundable credit can reduce tax liability below zero and generate a refund"]'::jsonb, 3, 'Under IRC Section 6401, a refundable credit can reduce tax liability below zero, resulting in a refund to the taxpayer. A nonrefundable credit can only reduce tax to zero. This distinction is fundamental: the EITC and a portion of the CTC are refundable, while credits like the Foreign Tax Credit are nonrefundable. The statement that nonrefundable credits generate refunds reverses the correct classification.', 'easy', 1),

-- Q5: hard / L4 — Estimated tax safe harbor with high AGI
(3, 'Individual Taxation: Credits/AMT', 'Dawson, a self-employed consultant (single filer), had $180,000 AGI and $35,000 tax liability in 2025. In 2026, she projects AGI of $250,000 and tax liability of $55,000. She has no withholding. Dawson wants to pay the minimum estimated tax to avoid underpayment penalties under IRC Section 6654. What is the minimum she must pay through quarterly estimates?', '["$38,500", "$35,000", "$49,500", "$55,000"]'::jsonb, 0, 'Under IRC Section 6654, taxpayers with prior year AGI exceeding $150,000 must pay the lesser of 90% of current year tax ($49,500) or 110% of prior year tax ($38,500) to avoid the underpayment penalty. The $38,500 is the minimum safe harbor. The $35,000 answer incorrectly applies the 100% prior year threshold, which only applies when prior year AGI is $150,000 or less.', 'hard', 4),

-- Q6: hard / L4 — Kiddie tax comprehensive analysis
(3, 'Individual Taxation: Credits/AMT', 'Harper, age 15, receives $18,000 in dividend income and $6,000 in wages from a summer job in 2026. Her parents are in the 37% marginal tax bracket. The kiddie tax threshold is approximately $2,500 (first $1,250 tax-free, next $1,250 at child''s rate). Evaluate the tax treatment of Harper''s total income.', '["All $24,000 is taxed at the parents'' 37% rate", "The $18,000 in dividends is entirely taxed at Harper''s rate because she is under 18", "The $6,000 in wages and all $18,000 in dividends are taxed at the parents'' 37% rate", "The $6,000 in wages is taxed at Harper''s rate, and $15,500 of dividends is taxed at the parents'' rate"]'::jsonb, 3, 'Under IRC Section 1(g), the kiddie tax applies only to unearned income exceeding approximately $2,500. Harper''s $6,000 wages are always taxed at her own rate. Of her $18,000 dividends, the first $1,250 is tax-free, the next $1,250 is taxed at her rate, and the remaining $15,500 is taxed at the parents'' 37% rate. The answer including wages at the parents'' rate is incorrect because the kiddie tax never applies to earned income.', 'hard', 4),

-- Q7: easy / L1 — AOTC maximum credit amount
(3, 'Individual Taxation: Credits/AMT', 'What is the maximum American Opportunity Tax Credit available per eligible student?', '["$2,000", "$2,500", "$1,000", "$4,000"]'::jsonb, 1, 'Under IRC Section 25A(i), the AOTC provides a maximum credit of $2,500 per eligible student: 100% of the first $2,000 plus 25% of the next $2,000 in qualified expenses. The $2,000 figure is the maximum Lifetime Learning Credit per return. The $1,000 amount represents the maximum refundable portion (40%) of the AOTC, not the full credit.', 'easy', 1),

-- Q8: medium / L2 — Child and Dependent Care Credit
(3, 'Individual Taxation: Credits/AMT', 'Velasquez, a single working parent, pays $4,500 in daycare expenses for her one qualifying child under age 13 in 2026. Her AGI is $14,000, qualifying her for the maximum 35% credit rate. What is Velasquez''s Child and Dependent Care Credit?', '["$1,575", "$1,500", "$1,050", "$4,500"]'::jsonb, 2, 'Under IRC Section 21, the Child and Dependent Care Credit allows qualifying expenses up to $3,000 for one qualifying individual (or $6,000 for two or more). Even though Velasquez paid $4,500, only $3,000 qualifies. At the maximum 35% rate, the credit is $3,000 × 35% = $1,050. The $1,575 answer incorrectly applies 35% to the full $4,500 paid without capping expenses at the statutory limit.', 'medium', 2),

-- Q9: hard / L3 — FTC separate baskets
(3, 'Individual Taxation: Credits/AMT', 'Hoffman (single filer) has $400,000 worldwide taxable income and U.S. tax liability of $90,000. She has $60,000 of foreign-source general category income with $16,000 foreign taxes paid, and $40,000 of foreign-source passive income with $14,000 foreign taxes paid. Under IRC Section 904, what is her total allowable foreign tax credit?', '["$30,000", "$22,500", "$25,000", "$18,000"]'::jsonb, 1, 'Under IRC Section 904, the FTC limitation is computed separately for each basket. General: $90,000 × ($60,000/$400,000) = $13,500 (paid $16,000, limited). Passive: $90,000 × ($40,000/$400,000) = $9,000 (paid $14,000, limited). Total allowable: $22,500. The $30,000 answer ignores the per-basket limitation, which prevents excess credits in one basket from offsetting tax on another category of income.', 'hard', 3),

-- Q10: medium / L2 — EITC investment income disqualification
(3, 'Individual Taxation: Credits/AMT', 'Williams, a single filer age 30 with one qualifying child, has $22,000 in wages and $12,500 in investment income (interest and dividends) for 2026. The EITC investment income limitation is approximately $11,600. Is Williams eligible for the Earned Income Tax Credit?', '["Yes, because Williams has earned income from wages", "Yes, because the EITC phases out based on AGI, not investment income", "No, because Williams does not have at least two qualifying children", "No, because Williams''s investment income exceeds the $11,600 threshold"]'::jsonb, 3, 'Under IRC Section 32(i), a taxpayer is ineligible for the EITC if investment income exceeds approximately $11,600. Williams''s $12,500 investment income exceeds this threshold, disqualifying her regardless of earned income level. The answer citing earned income alone is insufficient because the EITC has both an earned income requirement and a separate investment income cap.', 'medium', 2),

-- Q11: easy / L1 — EITC fully refundable
(3, 'Individual Taxation: Credits/AMT', 'Which of the following credits is fully refundable, meaning it can generate a cash refund even if the taxpayer has no tax liability?', '["Earned Income Tax Credit", "Foreign Tax Credit", "Child and Dependent Care Credit", "Lifetime Learning Credit"]'::jsonb, 0, 'Under IRC Section 32, the Earned Income Tax Credit is fully refundable, meaning it can produce a cash refund to the taxpayer even when tax liability is zero. The Foreign Tax Credit (Section 901), Child and Dependent Care Credit (Section 21), and Lifetime Learning Credit (Section 25A) are all nonrefundable credits that can only reduce tax to zero but cannot generate a refund.', 'easy', 1),

-- Q12: easy / L1 — CTC qualifying child age limit
(3, 'Individual Taxation: Credits/AMT', 'What is the maximum age at which a dependent child qualifies for the $2,000 Child Tax Credit?', '["Under 13", "Under 18", "Under 17", "Under 19"]'::jsonb, 2, 'Under IRC Section 24(c), a qualifying child for the Child Tax Credit must be under age 17 at the end of the tax year. The under-13 threshold applies to the Child and Dependent Care Credit, not the CTC. A dependent aged 17 is ineligible for the $2,000 CTC but may qualify for the $500 Credit for Other Dependents.', 'easy', 1),

-- Q13: medium / L3 — AOTC refundable portion calculation
(3, 'Individual Taxation: Credits/AMT', 'Franklin, a first-year undergraduate enrolled full-time, qualifies for the full $2,500 AOTC. His tax liability before credits is $800. Applying the AOTC, determine Franklin''s total tax benefit, including any refundable amount.', '["$800", "$1,800", "$2,500", "$1,000"]'::jsonb, 1, 'Under IRC Section 25A(i), 40% of the AOTC ($1,000) is refundable, while the remaining 60% ($1,500) is nonrefundable. The nonrefundable portion reduces Franklin''s $800 liability to $0 (wasting $700). The $1,000 refundable portion generates a refund. Total benefit: $800 + $1,000 = $1,800. The $2,500 answer is incorrect because the $700 excess nonrefundable portion is lost.', 'medium', 3),

-- Q14: medium / L2 — Saver's Credit calculation
(3, 'Individual Taxation: Credits/AMT', 'Cooper, a single filer age 28 with AGI of $20,000, contributes $1,500 to a traditional IRA in 2026. Based on his income level, Cooper qualifies for the 50% Saver''s Credit rate. What is his Retirement Savings Contributions Credit?', '["$1,500", "$1,000", "$750", "$300"]'::jsonb, 2, 'Under IRC Section 25B, the Saver''s Credit is a nonrefundable credit equal to the applicable percentage times qualified retirement contributions up to $2,000 ($4,000 MFJ). At the 50% rate, Cooper''s credit is 50% × $1,500 = $750. The $1,000 answer incorrectly assumes the maximum credit applies regardless of actual contribution; the credit is based on the lesser of contributions or the $2,000 cap.', 'medium', 2),

-- Q15: medium / L3 — Estimated tax safe harbor (AGI ≤ $150K)
(3, 'Individual Taxation: Credits/AMT', 'Reeves had prior year AGI of $120,000 and prior year tax liability of $18,000. In 2026, his projected tax liability is $25,000. He has $2,000 in withholding. Under IRC Section 6654, what minimum additional amount must Reeves pay in estimated taxes to satisfy the safe harbor?', '["$16,000", "$20,500", "$17,800", "$23,000"]'::jsonb, 0, 'Under IRC Section 6654, taxpayers with prior year AGI of $150,000 or less must pay the lesser of 90% of current year tax ($22,500) or 100% of prior year tax ($18,000). The safe harbor is $18,000, less $2,000 withholding, requiring $16,000 in estimates. The $17,800 answer incorrectly applies the 110% prior year threshold, which only applies when prior year AGI exceeds $150,000.', 'medium', 3),

-- Q16: medium / L3 — Other Dependent Credit ($500)
(3, 'Individual Taxation: Credits/AMT', 'Morrison and Taylor (MFJ, AGI $180,000) claim three dependents: a 10-year-old daughter, a 17-year-old son, and Taylor''s 68-year-old mother who lives with them. Apply the rules under IRC Section 24 to determine the family''s total combined child-related credits.', '["$6,000", "$4,000", "$2,000", "$3,000"]'::jsonb, 3, 'Under IRC Section 24, the $2,000 CTC applies only to qualifying children under age 17. The 10-year-old qualifies for the $2,000 CTC. The 17-year-old and the dependent mother each qualify for the $500 Credit for Other Dependents. Total: $2,000 + $500 + $500 = $3,000. The $6,000 answer incorrectly applies the full $2,000 CTC to all three dependents, ignoring the age-17 cutoff.', 'medium', 3),

-- Q17: medium / L2 — AOTC qualified expenses
(3, 'Individual Taxation: Credits/AMT', 'Patel, a full-time undergraduate in her second year, pays the following for 2026: tuition $3,500, required course textbooks $400, campus meal plan $2,800, and student health insurance $600. Which expenses qualify for the American Opportunity Tax Credit?', '["Tuition and campus meal plan", "Tuition and required course textbooks", "Tuition, textbooks, and health insurance", "All four expenses"]'::jsonb, 1, 'Under IRC Section 25A(f), qualified expenses for the AOTC include tuition, required enrollment fees, and course materials (books, supplies, equipment) needed for enrollment. Room, board, insurance, and personal expenses are excluded. Patel''s qualifying expenses are $3,500 (tuition) + $400 (textbooks) = $3,900. The answer including the campus meal plan incorrectly treats room and board as qualified education expenses.', 'medium', 2),

-- Q18: medium / L2 — FTC carryback and carryforward periods
(3, 'Individual Taxation: Credits/AMT', 'Singh paid $25,000 in foreign taxes in 2026 but her foreign tax credit limitation under IRC Section 904 allows only $19,000. She has $6,000 in excess foreign taxes. Under which provision can Singh use the excess credit, and for how long?', '["The excess is permanently lost with no carryover", "Carry forward 5 years only", "Carry back 2 years and carry forward 20 years", "Carry back 1 year and carry forward 10 years"]'::jsonb, 3, 'Under IRC Section 904(c), excess foreign tax credits that exceed the limitation may be carried back one year and carried forward ten years. This prevents permanent loss of credits from temporary mismatches between foreign and U.S. tax rates. The 2-year back/20-year forward periods apply to net operating losses, not foreign tax credits.', 'medium', 2),

-- Q19: medium / L2 — Annualized income installment method
(3, 'Individual Taxation: Credits/AMT', 'Brooks, a self-employed real estate agent, earns 80% of her annual income during Q3 and Q4. She made no estimated payments in Q1 and Q2 because she had minimal income during those periods. Under IRC Section 6654(d)(2), which method allows Brooks to reduce or eliminate underpayment penalties for the earlier quarters when income was lower?', '["Pay 110% of prior year tax divided equally across all four quarters", "Request a penalty waiver from the IRS based on uneven income", "Use the annualized income installment method to base payments on income actually received", "Deduct estimated tax penalties as a business expense on Schedule C"]'::jsonb, 2, 'Under IRC Section 6654(d)(2), the annualized income installment method bases each quarterly payment on income actually received through that period, annualized to a full year. This benefits taxpayers whose income is concentrated in later quarters, reducing required payments in Q1 and Q2. Paying equal quarterly installments does not account for seasonal income patterns.', 'medium', 2),

-- Q20: easy / L1 — LLC nonrefundable classification
(3, 'Individual Taxation: Credits/AMT', 'Which of the following correctly describes the Lifetime Learning Credit?', '["It is a nonrefundable credit of up to $2,000 per tax return", "It is a refundable credit of up to $2,500 per student", "It is available only for the first four years of postsecondary education", "It requires at least half-time enrollment"]'::jsonb, 0, 'Under IRC Section 25A(c), the Lifetime Learning Credit is a nonrefundable credit equal to 20% of up to $10,000 in qualified tuition expenses, for a maximum of $2,000 per return. Unlike the AOTC, there is no limit on the number of years it can be claimed, no half-time enrollment requirement, and it covers graduate as well as undergraduate courses.', 'easy', 1),

-- Q21: easy / L1 — Zero prior year liability exception
(3, 'Individual Taxation: Credits/AMT', 'Under the estimated tax rules, which taxpayer is exempt from the underpayment penalty regardless of the current year tax owed?', '["A taxpayer who filed an extension for the current year return", "A taxpayer who claimed only the standard deduction", "A taxpayer who made at least one quarterly estimated payment", "A taxpayer who had zero tax liability in the prior year and was a U.S. citizen for the entire year"]'::jsonb, 3, 'Under IRC Section 6654(e)(2), no underpayment penalty applies if the taxpayer had zero tax liability in the prior year and was a U.S. citizen or resident for the entire year. Filing an extension delays only the filing deadline, not the payment obligation. Making one quarterly payment does not satisfy the safe harbor unless total payments meet the required threshold.', 'easy', 1),

-- Q22: easy / L2 — AOTC four-year limitation
(3, 'Individual Taxation: Credits/AMT', 'Ortega, a fifth-year undergraduate who changed majors midway through college, pays $4,000 in tuition for 2026. She claimed the AOTC for each of her first four academic years. Which education credit, if any, is available to Ortega?', '["The AOTC, because she is still an undergraduate", "The Lifetime Learning Credit", "Neither credit, because she exhausted all education benefits", "The AOTC at a reduced 50% rate for fifth-year students"]'::jsonb, 1, 'Under IRC Section 25A(b)(2), the AOTC is limited to the first four taxable years of postsecondary education. Since Ortega used all four years, she cannot claim another AOTC. However, the Lifetime Learning Credit (Section 25A(c)) has no limit on the number of years, making it available for her fifth year. The answer claiming both credits are exhausted ignores the LLC''s unlimited availability.', 'easy', 2),

-- Q23: easy / L1 — Kiddie tax applies to unearned income
(3, 'Individual Taxation: Credits/AMT', 'The kiddie tax under IRC Section 1(g) applies to which type of income?', '["Earned income such as wages and salaries", "All income regardless of source", "Unearned income such as interest, dividends, and capital gains", "Only income from a family business"]'::jsonb, 2, 'Under IRC Section 1(g), the kiddie tax applies only to a child''s unearned income (interest, dividends, capital gains) exceeding approximately $2,500. Earned income from wages or self-employment is always taxed at the child''s own rate. The answer including all income is incorrect because the kiddie tax specifically targets investment income used in income-shifting strategies.', 'easy', 1),

-- Q24: hard / L4 — CTC + ACTC with earned income formula
(3, 'Individual Taxation: Credits/AMT', 'Gutierrez, a single parent with earned income of $12,000 and three qualifying children under age 17, has a regular tax liability of $0 after the standard deduction. The Child Tax Credit is $2,000 per child. The Additional Child Tax Credit is refundable for up to $1,700 per child, computed as 15% of earned income exceeding $2,500. Analyze Gutierrez''s total CTC benefit.', '["$6,000", "$5,100", "$0", "$1,425"]'::jsonb, 3, 'Under IRC Section 24(d), the Additional Child Tax Credit is refundable, computed as 15% of earned income exceeding $2,500, up to $1,700 per child. With $0 tax liability, the nonrefundable CTC provides no benefit. The ACTC is 15% × ($12,000 − $2,500) = $1,425, which is below the $5,100 maximum (3 × $1,700). The $5,100 answer ignores the earned income formula, which is the binding constraint here.', 'hard', 4),

-- Q25: hard / L4 — FTC vs deduction optimization
(3, 'Individual Taxation: Credits/AMT', 'Yang (single, 32% bracket) has $50,000 in foreign-source income and paid $12,000 in foreign taxes. Her U.S. tax liability is $48,000 on $200,000 worldwide income. The FTC limitation is $12,000. Yang considers whether to claim the foreign tax credit or deduct the foreign taxes on Schedule A. Which approach produces the greater tax benefit, and by how much?', '["The credit saves $8,160 more than the deduction", "The deduction saves $8,160 more than the credit", "Both produce the same tax benefit of $12,000", "The credit saves $4,000 more than the deduction"]'::jsonb, 0, 'Under IRC Section 901, the foreign tax credit provides a dollar-for-dollar reduction in tax liability ($12,000), while deducting foreign taxes on Schedule A only reduces taxable income, saving $12,000 × 32% = $3,840. The credit saves $8,160 more. A taxpayer cannot claim both for the same taxes, and the credit is almost always more beneficial because it directly offsets tax rather than merely reducing the tax base.', 'hard', 4),

-- Q26: medium / L3 — EITC maximum with two children
(3, 'Individual Taxation: Credits/AMT', 'Jenkins, a single filer age 35, has $20,000 in earned income from wages and two qualifying children in 2026. Her investment income is $3,000. Approximate EITC maximums are: no children ~$650, one child ~$4,200, two children ~$6,900, three or more ~$7,800. Assuming Jenkins is within the eligible income range, which maximum EITC amount applies to her?', '["$4,200", "$6,900", "$7,800", "$650"]'::jsonb, 1, 'Under IRC Section 32, the EITC maximum increases with the number of qualifying children. With two qualifying children and investment income ($3,000) below the ~$11,600 threshold, Jenkins qualifies for the maximum credit of approximately $6,900. The $4,200 answer applies to taxpayers with only one qualifying child, while $7,800 requires three or more children.', 'medium', 3),

-- Q27: medium / L3 — Cannot claim both AOTC and LLC for same student
(3, 'Individual Taxation: Credits/AMT', 'Campbell has a daughter, Mia, who is a third-year undergraduate paying $6,000 in tuition. Campbell wants to claim both the AOTC and the Lifetime Learning Credit for Mia to maximize the total education benefit. His MAGI is $75,000 (single). What is the maximum combined education credit Campbell can claim for Mia?', '["$3,700 by combining both credits", "$1,200 by claiming only the LLC", "$4,500 by combining both credits", "$2,500 by claiming only the AOTC"]'::jsonb, 3, 'Under IRC Section 25A(c)(2)(A), a taxpayer cannot claim both the AOTC and the LLC for the same student in the same tax year. The AOTC yields $2,500 (100% of $2,000 + 25% of next $2,000). The LLC yields only $1,200 (20% × $6,000). Campbell should claim the AOTC for the greater benefit. The $3,700 answer violates the same-student prohibition.', 'medium', 3),

-- Q28: medium / L2 — AOTC felony drug conviction disqualification
(3, 'Individual Taxation: Credits/AMT', 'Rivera is a sophomore enrolled full-time with $4,000 in qualified tuition expenses and MAGI of $70,000. She was convicted of a felony drug offense in 2025. Which education credit can Rivera claim for 2026?', '["The Lifetime Learning Credit only", "The AOTC only", "Both the AOTC and the LLC", "Neither credit due to the conviction"]'::jsonb, 0, 'Under IRC Section 25A(b)(2)(D), a student with a felony drug conviction at the end of the tax year is ineligible for the AOTC. However, no such restriction applies to the Lifetime Learning Credit under Section 25A(c). Rivera can claim the LLC (20% × $4,000 = $800) but not the AOTC. The answer denying both credits incorrectly extends the drug conviction restriction to the LLC.', 'medium', 2),

-- Q29: easy / L1 — De minimis underpayment penalty exception
(3, 'Individual Taxation: Credits/AMT', 'Under IRC Section 6654, when is the estimated tax underpayment penalty automatically waived?', '["When the balance due is less than $5,000", "When the taxpayer files an extension", "When the total tax owed after withholding and credits is less than $1,000", "When the taxpayer makes at least one quarterly payment"]'::jsonb, 2, 'Under IRC Section 6654(e)(1), no underpayment penalty applies if the tax owed after withholding and credits is less than $1,000. This de minimis exception protects taxpayers with small balances due. The $5,000 threshold is incorrect, and filing an extension extends only the filing deadline, not the payment obligation or penalty waiver.', 'easy', 1),

-- Q30: medium / L3 — ACTC earned income threshold
(3, 'Individual Taxation: Credits/AMT', 'Dixon, a single parent with one qualifying child under 17, has earned income of $5,500 and zero tax liability. Under IRC Section 24(d), the Additional Child Tax Credit equals 15% of earned income exceeding $2,500, up to $1,700 per child. What is Dixon''s refundable ACTC?', '["$450", "$825", "$1,700", "$2,000"]'::jsonb, 0, 'Under IRC Section 24(d), the ACTC is 15% of earned income exceeding $2,500. Dixon''s calculation: 15% × ($5,500 − $2,500) = $450. This is below the $1,700 per-child maximum, so $450 is the refundable amount. The $825 answer incorrectly applies 15% to total earned income without subtracting the $2,500 threshold required by the statute.', 'medium', 3)
;

COMMIT;
