-- Migration: Question generation — REG batch 51 (30 questions)
-- Date: 2026-03-02
-- Topic: Government Regulation of Business
-- Difficulty: 9E / 15M / 6H
-- Bloom's: L1:8 / L2:9 / L3:8 / L4:5

BEGIN;

INSERT INTO questions (section_id, topic, stem, choices, correct_index, explanation, difficulty, cognitive_level)
VALUES

-- Q1: easy / L1 — FTC Act Section 5 unfair/deceptive practices
(3, 'Government Regulation of Business', 'Under the Federal Trade Commission Act, which type of business practice is primarily prohibited by Section 5?', '["Mergers that substantially lessen competition", "Formation of monopolies through predatory pricing", "Unfair or deceptive acts or practices in commerce", "Price discrimination between competing purchasers"]'::jsonb, 2, 'Under Section 5 of the FTC Act, the Federal Trade Commission is authorized to prevent unfair or deceptive acts or practices in or affecting commerce. This broad authority allows the FTC to address consumer protection violations and anticompetitive behavior beyond specific antitrust statutes. While choice A (mergers lessening competition) is addressed by the Clayton Act Section 7, not Section 5 of the FTC Act.', 'easy', 1),

-- Q2: easy / L1 — Robinson-Patman Act price discrimination
(3, 'Government Regulation of Business', 'The Robinson-Patman Act primarily addresses which anticompetitive practice?', '["Horizontal price-fixing among competitors", "Price discrimination in the sale of commodities of like grade and quality", "Tying arrangements in product distribution", "Monopolization through exclusive dealing contracts"]'::jsonb, 1, 'The Robinson-Patman Act (1936) amends the Clayton Act and specifically prohibits price discrimination in the sale of commodities of like grade and quality where the effect may substantially lessen competition. The statute targets sellers who offer unjustifiably different prices to competing buyers. While choice A (horizontal price-fixing) is a per se violation under Section 1 of the Sherman Act, not the Robinson-Patman Act.', 'easy', 1),

-- Q3: easy / L1 — SOX Section 806 whistleblower protections
(3, 'Government Regulation of Business', 'Under the Sarbanes-Oxley Act, Section 806 provides whistleblower protection to which group?', '["Employees who report securities fraud or violations of SEC rules", "External auditors who discover material misstatements during an audit", "Shareholders who file derivative lawsuits against management", "Board members who dissent from fraudulent financial reporting decisions"]'::jsonb, 0, 'SOX Section 806 provides whistleblower protections to employees of publicly traded companies who report conduct they reasonably believe constitutes securities fraud, violations of SEC rules, or federal anti-fraud statutes. Protected employees cannot be retaliated against through discharge, demotion, or harassment. While choice B (external auditors) has separate professional responsibilities under auditing standards, Section 806 specifically protects employee whistleblowers, not auditors.', 'easy', 1),

-- Q4: hard / L4 — Evaluating Section 11 vs Rule 10b-5 for CPA liability
(3, 'Government Regulation of Business', 'Greenfield Manufacturing''s audited financial statements contain a material overstatement of inventory. An investor purchased shares in the IPO on April 10, 2026, relying on the registration statement. The audit firm, Claymore & Associates, conducted the audit negligently but without intent to deceive. The investor sues the CPA firm. Evaluate which federal securities provision offers the investor the strongest claim against the auditors.', '["Rule 10b-5, because it applies to any purchase or sale of securities", "Section 18, because the financial statements were filed with the SEC", "Section 12(a)(2), because the investor purchased in the public offering", "Section 11, because the investor need not prove scienter against the auditors"]'::jsonb, 3, 'Under Section 11 of the Securities Act of 1933, an investor can hold auditors liable as ''experts'' for material misstatements in audited financial statements included in the registration statement without proving scienter or reliance. The CPA firm''s negligence is sufficient for liability because the issuer bears strict liability and auditors must prove due diligence. While Rule 10b-5 (choice A) requires proof of scienter, which the investor cannot establish because the auditors acted negligently, not intentionally.', 'hard', 4),

-- Q5: medium / L2 — Rule 506(c) general solicitation with accredited investors
(3, 'Government Regulation of Business', 'Redwood Capital LLC plans to raise $15 million through general solicitation on June 1, 2026, using television advertisements and social media. All 40 investors are verified accredited investors. Redwood''s counsel advises using a Regulation D exemption. Under which rule does this offering qualify?', '["Rule 504, because the offering is under $10 million", "Rule 506(c), because general solicitation is permitted when all purchasers are verified accredited investors", "Rule 506(b), because there are fewer than 35 non-accredited investors", "Rule 147, because the offering involves only accredited investors"]'::jsonb, 1, 'Under SEC Rule 506(c) of Regulation D, issuers may use general solicitation and advertising to offer securities, provided all purchasers are accredited investors and the issuer takes reasonable steps to verify their accredited status. This JOBS Act provision expanded Reg D to allow public marketing under strict conditions. While Rule 506(b) (choice C) prohibits general solicitation entirely, making it unavailable when the issuer uses television and social media advertising.', 'medium', 2),

-- Q6: hard / L4 — SOX Section 301 audit committee independence
(3, 'Government Regulation of Business', 'Pinnacle Industries appoints its audit committee in March 2026 with three directors. Adams receives a $75,000 annual consulting fee beyond board compensation. Bell is a former partner of the external audit firm who left 18 months ago. Chen has no financial relationship beyond board fees. Evaluate which director(s) can serve under SOX Section 301.', '["Adams and Bell only, because both have relevant financial expertise", "Bell and Chen only, because Adams''s consulting fee disqualifies him", "Chen only, because both Adams and Bell lack the required independence", "All three directors, because SOX only requires financial expertise, not independence"]'::jsonb, 2, 'Under SOX Section 301, every audit committee member must be an independent director who may not accept any consulting, advisory, or compensatory fee from the company beyond director compensation. Adams is disqualified by the $75,000 consulting fee, and Bell''s recent affiliation with the audit firm within the cooling-off period compromises independence under SEC rules. While choice B correctly excludes Adams but incorrectly includes Bell, whose former audit firm relationship creates an independence violation.', 'hard', 4),

-- Q7: medium / L2 — Rule 504 Regulation D offering
(3, 'Government Regulation of Business', 'Atlas Startup Inc. plans to raise $4.5 million from 50 investors, including 40 non-accredited individuals, on September 15, 2026, without general solicitation. Under Regulation D, which rule governs this offering?', '["Rule 504, because the offering does not exceed $10 million and places no limit on non-accredited investors", "Rule 506(b), because there are fewer than 50 non-accredited investors", "Rule 506(c), because the offering amount is under $10 million", "Rule 147, because all investors reside in the same state"]'::jsonb, 0, 'Under SEC Rule 504 of Regulation D, issuers may sell up to $10 million of securities in a 12-month period without limiting the number of non-accredited investors. Because Atlas has 40 non-accredited investors, it exceeds Rule 506(b)''s 35-person cap for non-accredited purchasers. While Rule 506(b) (choice B) would otherwise be available, it limits non-accredited investors to 35 sophisticated individuals, disqualifying this offering.', 'medium', 2),

-- Q8: hard / L3 — Hart-Scott-Rodino pre-merger notification
(3, 'Government Regulation of Business', 'Cascade Holdings Corp. announces on February 15, 2026, that it will acquire Riverstone Industries for $420 million. Both companies compete in the domestic chemical manufacturing market. Under the Hart-Scott-Rodino Act, what is the most likely effect on the companies'' regulatory obligations?', '["The acquisition is automatically prohibited because both companies compete in the same market", "The companies must obtain prior approval from the SEC before completing the transaction", "The FTC must challenge the merger within 90 days or the transaction proceeds automatically", "The companies must file pre-merger notification with the FTC and DOJ and observe a waiting period before closing"]'::jsonb, 3, 'Under the Hart-Scott-Rodino Antitrust Improvements Act of 1976, parties to mergers and acquisitions exceeding statutory size thresholds must file pre-merger notification with the FTC and DOJ and observe a mandatory waiting period (typically 30 days) before consummating the transaction. This allows antitrust agencies to evaluate competitive effects. While choice A incorrectly states the merger is automatically prohibited; Hart-Scott-Rodino requires review and a waiting period, not outright prohibition of competitor mergers.', 'hard', 3),

-- Q9: medium / L2 — Rule 147 intrastate offering requirements
(3, 'Government Regulation of Business', 'Magnolia Foods LLC, incorporated in Georgia, plans to raise $3 million on July 1, 2026, by selling shares exclusively to Georgia residents. The company derives 85% of its gross revenues from Georgia operations. Under SEC Rule 147, which requirement must Magnolia satisfy?', '["File a registration statement with the SEC within 15 days of the first sale", "Limit sales to accredited Georgia residents only", "Derive at least 80% of its gross revenues from operations within the state", "Obtain written approval from the Georgia Secretary of State"]'::jsonb, 2, 'Under SEC Rule 147, the intrastate offering exemption requires that the issuer derive at least 80% of its gross revenues from operations within the state, have at least 80% of its assets located within the state, and use at least 80% of the offering proceeds within the state. Magnolia''s 85% in-state revenue meets this threshold. While choice B is incorrect because Rule 147 does not require investors to be accredited, only that they are residents of the issuing state.', 'medium', 2),

-- Q10: easy / L1 — ADEA age discrimination threshold
(3, 'Government Regulation of Business', 'The Age Discrimination in Employment Act (ADEA) protects employees who are at least what age?', '["40 years old", "50 years old", "55 years old", "65 years old"]'::jsonb, 0, 'Under the Age Discrimination in Employment Act of 1967, employees and job applicants age 40 and older are protected from discrimination based on age in hiring, firing, compensation, and other terms of employment. The ADEA applies to employers with 20 or more employees. While choice B (50 years old) is a common misconception, the statutory protection threshold is 40, providing broader coverage than many candidates expect.', 'easy', 1),

-- Q11: medium / L2 — SOX Section 802 document destruction penalties
(3, 'Government Regulation of Business', 'On March 10, 2026, the SEC begins an investigation into Windham Corp.''s financial reporting. On March 15, Windham''s CFO instructs staff to shred documents related to revenue recognition adjustments. Under SOX Section 802, what is the potential consequence for the CFO?', '["Civil monetary penalty up to $100,000 assessed by the PCAOB", "Criminal penalties including fines and imprisonment up to 20 years", "Suspension from practicing before the SEC for one year", "Mandatory restatement of financial statements for the prior three years"]'::jsonb, 1, 'Under SOX Section 802, any person who knowingly alters, destroys, mutilates, or conceals documents with intent to impede or obstruct a federal investigation faces criminal penalties including fines and imprisonment for up to 20 years. The CFO''s intentional destruction during an active SEC investigation constitutes obstruction. While choice A (PCAOB civil penalty) is incorrect because Section 802 imposes criminal, not civil, penalties for willful document destruction.', 'medium', 2),

-- Q12: easy / L1 — ADA reasonable accommodation
(3, 'Government Regulation of Business', 'Under the Americans with Disabilities Act (ADA), employers are required to provide which of the following to qualified individuals with disabilities?', '["Automatic employment regardless of job qualifications", "Priority hiring over non-disabled applicants", "Medical insurance covering all disability-related expenses", "Reasonable accommodations that do not impose undue hardship"]'::jsonb, 3, 'Under the Americans with Disabilities Act of 1990, employers with 15 or more employees must provide reasonable accommodations to qualified individuals with disabilities unless doing so would impose an undue hardship on the business. Examples include job restructuring, modified schedules, or assistive equipment. While choice A is incorrect because the ADA does not guarantee employment; it prohibits discrimination against qualified individuals who can perform essential job functions with or without accommodation.', 'easy', 1),

-- Q13: medium / L3 — Section 5 waiting period marketing restrictions
(3, 'Government Regulation of Business', 'Brightstar Pharmaceuticals files a registration statement with the SEC on April 1, 2026, for a $200 million IPO. During the waiting period, management wants to generate investor interest. What is the most likely effect of Section 5 restrictions on the company''s marketing activities?', '["Brightstar may distribute preliminary prospectuses and make oral offers but cannot confirm sales or accept payments", "Brightstar may accept binding commitments from institutional investors but not retail investors", "Brightstar may conduct roadshows but cannot distribute any written materials to investors", "Brightstar may sell securities to underwriters only, with retail sales beginning on the effective date"]'::jsonb, 0, 'Under Section 5 of the Securities Act of 1933, during the waiting period between filing and the effective date, the issuer may make oral offers and distribute preliminary prospectuses (''red herrings'') but may not sell or deliver securities or accept purchase payments. This allows investor interest to develop while preventing premature sales. While choice C is incorrect because written materials in the form of preliminary prospectuses are specifically permitted during the waiting period.', 'medium', 3),

-- Q14: medium / L3 — SOX Section 906 criminal penalties vs Section 302
(3, 'Government Regulation of Business', 'Stonebridge Financial Corp.''s CEO certifies the 2025 annual report on March 1, 2026, knowing that revenue figures materially overstate performance. How does SOX Section 906 affect the CEO''s potential liability compared to Section 302?', '["Section 906 reduces liability by providing a safe harbor for good-faith certifications", "Section 906 limits penalties to the amount of investor losses directly caused by the false statement", "Section 906 imposes criminal penalties including fines up to $5 million and imprisonment up to 20 years for willful false certifications", "Section 906 shifts liability from the CEO to the company''s board of directors"]'::jsonb, 2, 'Under SOX Section 906, officers who willfully certify a report knowing it does not comply with SEC requirements face criminal penalties of up to $5 million in fines and up to 20 years imprisonment. This significantly escalates consequences beyond Section 302''s civil accountability framework. While choice A is incorrect because Section 906 provides no safe harbor; it specifically targets knowing and willful false certifications with criminal sanctions more severe than Section 302''s civil remedies.', 'medium', 3),

-- Q15: medium / L3 — Regulation A Tier 1 vs Tier 2 comparison
(3, 'Government Regulation of Business', 'Silverline Dynamics Inc. plans a Regulation A offering to raise $35 million and wants to avoid individual state securities registration requirements. What is the most significant difference between Tier 1 and Tier 2 that affects this decision?', '["Tier 2 limits offerings to accredited investors only, while Tier 1 has no investor qualification requirements", "Tier 1 allows up to $20 million and requires state registration, while Tier 2 allows up to $75 million and preempts state registration", "Tier 1 requires audited financial statements, while Tier 2 permits unaudited statements", "Tier 2 requires SEC registration identical to a full IPO, while Tier 1 uses simplified filing"]'::jsonb, 1, 'Under Regulation A (amended by the JOBS Act), Tier 1 offerings are limited to $20 million in a 12-month period and remain subject to state securities registration (Blue Sky laws), while Tier 2 offerings may raise up to $75 million and benefit from federal preemption of state registration. Silverline must use Tier 2 because its $35 million target exceeds Tier 1''s cap. While choice C reverses the auditing requirements; Tier 2, not Tier 1, requires audited financial statements.', 'medium', 3),

-- Q16: medium / L2 — Form 8-K triggering events
(3, 'Government Regulation of Business', 'On April 20, 2026, Crestview Holdings, a publicly traded company, enters into a definitive merger agreement to acquire Lakewood Partners for $180 million. Under the Securities Exchange Act of 1934, which report must Crestview file with the SEC to disclose this event?', '["Form 10-K, because the acquisition affects annual financial reporting", "Form 10-Q, because the merger agreement was signed during the fiscal quarter", "Form S-1, because the merger involves the potential issuance of new securities", "Form 8-K, because entering into a material definitive agreement is a current reportable event"]'::jsonb, 3, 'Under the Securities Exchange Act of 1934, publicly traded companies must file a Form 8-K within four business days of specified triggering events, including entry into a material definitive agreement such as a merger agreement. Item 1.01 of Form 8-K specifically covers this disclosure obligation. While choice A (Form 10-K) is incorrect because Form 10-K is an annual report filed after the fiscal year end, not a mechanism for timely disclosure of material current events.', 'medium', 2),

-- Q17: medium / L2 — Clayton Act tying arrangements
(3, 'Government Regulation of Business', 'Dominion Software Corp. requires all purchasers of its accounting platform to also buy Dominion''s proprietary data storage service, even though competing storage services exist. On June 1, 2026, a competitor files a complaint. Under the Clayton Act, which anticompetitive practice is at issue?', '["A tying arrangement, because the sale of one product is conditioned on buying another product from the same seller", "Price discrimination, because competing storage providers cannot match Dominion''s bundled pricing", "A group boycott, because Dominion effectively excludes competing storage vendors", "Predatory pricing, because Dominion sells below cost to eliminate competition"]'::jsonb, 0, 'Under Section 3 of the Clayton Act, a tying arrangement occurs when a seller conditions the sale of one product (the tying product) on the buyer''s purchase of a separate product (the tied product). Dominion''s requirement that customers buy its storage service with the accounting platform is a classic tie. While choice B (price discrimination) under the Robinson-Patman Act involves charging different buyers different prices for the same product, not conditioning purchases.', 'medium', 2),

-- Q18: easy / L2 — NLRA collective bargaining rights
(3, 'Government Regulation of Business', 'Harmon Manufacturing employs 200 workers. On March 5, 2026, a group of employees organizes to negotiate wages and working conditions. Under the National Labor Relations Act, what right do these employees have?', '["The right to strike only if approved by the National Labor Relations Board", "The right to organize and bargain collectively through representatives of their choosing", "The right to compel management to accept all proposed terms of employment", "The right to bypass management and set wages through direct employee vote"]'::jsonb, 1, 'Under Section 7 of the National Labor Relations Act (NLRA) of 1935, employees have the right to self-organize, form or join labor organizations, and bargain collectively through representatives of their own choosing. The NLRA protects these organizing activities from employer interference or retaliation. While choice A is incorrect because employees may lawfully strike without prior NLRB approval; the right to strike is protected by Section 7 independently.', 'easy', 2),

-- Q19: hard / L4 — Dodd-Frank vs SOX whistleblower evaluation
(3, 'Government Regulation of Business', 'Rivera, an internal auditor at a publicly traded company, discovers that the CFO inflated revenue by $12 million in 2025. Rivera reports internally on January 15, 2026, and is terminated on February 10, 2026. Evaluate which federal whistleblower framework best protects Rivera and offers the strongest remedies.', '["SOX Section 806 only, because internal auditors must exhaust the administrative complaint process with OSHA", "Neither statute, because Rivera reported internally rather than directly to the SEC", "The Dodd-Frank Act, because it provides broader protections including potential monetary awards for reporting securities violations to the SEC", "The False Claims Act, because the inflated revenue constitutes a false claim against the federal government"]'::jsonb, 2, 'Under the Dodd-Frank Wall Street Reform and Consumer Protection Act of 2010, whistleblowers who voluntarily provide original information to the SEC about securities violations may receive monetary awards of 10-30% of sanctions exceeding $1 million, plus anti-retaliation protections. Unlike SOX Section 806, Dodd-Frank offers direct financial incentives and broader remedies. While choice A is incomplete because although SOX Section 806 requires filing with OSHA, Dodd-Frank provides Rivera additional protections and monetary awards unavailable under SOX alone.', 'hard', 4),

-- Q20: easy / L1 — Equal Pay Act prohibition
(3, 'Government Regulation of Business', 'Under the Equal Pay Act of 1963, employers are prohibited from engaging in which practice?', '["Requiring employees to work overtime without premium pay", "Discriminating in compensation based on race or national origin", "Terminating employees who discuss their wages with coworkers", "Paying different wages to men and women for substantially equal work"]'::jsonb, 3, 'The Equal Pay Act of 1963 prohibits employers from paying different wages to employees of opposite sexes for substantially equal work performed under similar working conditions requiring equal skill, effort, and responsibility. Exceptions exist for seniority, merit, and productivity-based systems. While choice B (race or national origin) is prohibited under Title VII of the Civil Rights Act of 1964, not the Equal Pay Act, which specifically addresses sex-based wage disparities.', 'easy', 1),

-- Q21: medium / L3 — CPA third-party liability Restatement approach
(3, 'Government Regulation of Business', 'Ashford & Co. CPAs audits Meridian Corp. without identifying third-party users in the engagement letter. Pinnacle Bank lends $2 million to Meridian relying on the audited statements. Ashford negligently fails to detect a material misstatement. Under the Restatement approach, what factor most likely determines Pinnacle''s ability to recover?', '["Whether Pinnacle Bank was a foreseen user or member of a foreseen class of users of the audit report", "Whether Pinnacle Bank had a direct contractual relationship with Ashford & Co.", "Whether Ashford & Co. obtained professional liability insurance covering third-party claims", "Whether the material misstatement exceeded 10% of total assets"]'::jsonb, 0, 'Under the Restatement (Second) of Torts Section 552, a CPA''s liability for negligent misrepresentation extends to foreseen users and foreseen classes of users who justifiably rely on the CPA''s work. Pinnacle Bank can recover if Ashford knew or should have known that lenders would rely on the audit. While choice B reflects the restrictive Ultramares (privity) approach, not the Restatement approach, which extends liability beyond parties in direct contractual privity.', 'medium', 3),

-- Q22: medium / L3 — SEC enforcement remedies and powers
(3, 'Government Regulation of Business', 'The SEC completes an investigation into Falcon Trading Corp. on April 5, 2026, finding evidence of widespread financial statement fraud. What is the most likely effect of the SEC''s enforcement authority on Falcon''s officers and directors?', '["The SEC can only refer the matter to the DOJ and has no independent enforcement powers", "The SEC may seek civil injunctions, disgorgement of ill-gotten gains, and officer or director bars through administrative proceedings or federal court", "The SEC must obtain a criminal conviction before imposing any penalties on officers", "The SEC can impose criminal fines but cannot bar officers or directors from serving"]'::jsonb, 1, 'Under Section 21 of the Securities Exchange Act of 1934, the SEC has broad enforcement authority including the power to seek civil injunctions, disgorgement of profits, civil monetary penalties, and officer/director bars. The SEC can pursue these remedies through administrative proceedings or by filing actions in federal court without requiring prior criminal proceedings. While choice A is incorrect because the SEC has independent civil enforcement authority and does not rely solely on DOJ criminal referrals.', 'medium', 3),

-- Q23: easy / L1 — Exempt securities under Securities Act 1933
(3, 'Government Regulation of Business', 'Under the Securities Act of 1933, which type of security is exempt from the registration requirement?', '["Corporate bonds issued by a Fortune 500 company", "Preferred stock of a publicly traded technology firm", "U.S. government securities and municipal bonds", "Common stock offered through an initial public offering"]'::jsonb, 2, 'Under Section 3 of the Securities Act of 1933, certain securities are permanently exempt from registration, including U.S. government securities, municipal bonds, bank securities, and insurance policies. These exemptions recognize that such securities are already subject to separate regulatory oversight or carry government backing. While choice A (corporate bonds) is not exempt from registration regardless of the issuer''s size; all corporate securities must be registered unless a transaction exemption applies.', 'easy', 1),

-- Q24: hard / L4 — SOX Section 402 loan prohibition to officers
(3, 'Government Regulation of Business', 'Vanguard Electronics Inc., a publicly traded company, considers three proposals at its March 2026 board meeting: (1) a $500,000 personal loan to the CEO for a vacation home, (2) a $200,000 advance to the CFO for business travel expenses, and (3) a $1 million relocation loan to a newly hired executive vice president. Evaluate which proposal(s) are prohibited under SOX Section 402.', '["Proposals 1 and 3, because personal loans and new credit extensions to executive officers are prohibited regardless of purpose", "Only proposal 1, because personal loans are prohibited but relocation assistance and business advances are standard employee benefits", "All three proposals, because SOX bans all financial transactions between companies and their executive officers", "Only proposals 1 and 2, because travel advances to financial officers create prohibited conflicts of interest"]'::jsonb, 0, 'Under SOX Section 402, publicly traded companies are prohibited from directly or indirectly extending credit in the form of personal loans to directors or executive officers. Both the $500,000 personal loan (proposal 1) and the $1 million relocation loan (proposal 3) constitute prohibited credit extensions to executive officers. Ordinary business travel advances (proposal 2) are operational reimbursements, not personal loans. While choice B incorrectly treats the relocation loan as exempt; SOX Section 402 broadly prohibits new credit arrangements to officers.', 'hard', 4),

-- Q25: medium / L3 — Section 18 good faith defense
(3, 'Government Regulation of Business', 'Waverly Corp. files a Form 10-K on May 1, 2026, containing misstated inventory figures. An investor purchases stock in reliance on the filing and sues under Section 18 of the Securities Exchange Act of 1934. How does the good faith defense affect Waverly''s liability?', '["The good faith defense is unavailable because Section 18 imposes strict liability on all corporate officers", "The good faith defense requires the defendant to prove that investors did not actually rely on the filing", "The good faith defense shifts the burden to the investor to prove the defendant acted with scienter", "The defendant may avoid liability by proving it acted in good faith and had no knowledge the statement was false or misleading"]'::jsonb, 3, 'Under Section 18 of the Securities Exchange Act of 1934, persons who make false or misleading statements in SEC filings are liable to investors who purchased or sold in reliance on those statements. However, Section 18 provides a good faith defense allowing defendants to escape liability by proving they acted in good faith without knowledge of the falsity. While choice A is incorrect because Section 18, unlike Section 11, is not a strict liability provision; it expressly provides the good faith defense.', 'medium', 3),

-- Q26: medium / L3 — Clean Air Act EPA enforcement
(3, 'Government Regulation of Business', 'Steelridge Manufacturing operates a factory emitting sulfur dioxide above National Ambient Air Quality Standards. On March 20, 2026, the EPA issues a notice of violation. What is the most likely regulatory consequence under the Clean Air Act?', '["The EPA may only issue a warning for the first violation, with penalties beginning on the second offense", "The EPA may impose civil penalties, require corrective action, or seek injunctive relief to bring emissions into compliance", "The EPA must refer the matter to a state environmental agency before taking any federal action", "The EPA can impose penalties only if emissions cause documented health effects in the surrounding community"]'::jsonb, 1, 'Under the Clean Air Act, the EPA has authority to enforce National Ambient Air Quality Standards (NAAQS) by imposing civil penalties of up to $37,500 per day per violation, requiring corrective action plans, and seeking injunctive relief in federal court. Criminal penalties are also available for knowing violations. While choice A is incorrect because the Clean Air Act does not require a warning before imposing penalties; the EPA may enforce compliance on the first documented violation.', 'medium', 3),

-- Q27: medium / L2 — Section 12(a)(2) liability and rescission remedy
(3, 'Government Regulation of Business', 'Hartwell Biotech offers securities through a public offering on April 10, 2026. The prospectus contains a material misstatement about drug trial results. An investor purchases 2,000 shares at $25 per share. Under Section 12(a)(2) of the Securities Act of 1933, what remedy is available to the investor?', '["The investor can seek criminal prosecution of the company''s officers for securities fraud", "The investor must prove that Hartwell acted with intent to deceive before recovering damages", "The investor may rescind the purchase or recover damages from the seller without proving scienter", "The investor may recover only if the investor can demonstrate reliance on the specific misstatement"]'::jsonb, 2, 'Under Section 12(a)(2) of the Securities Act of 1933, any person who offers or sells securities by means of a prospectus containing a material misstatement or omission is liable to the purchaser. The remedy is rescission or damages if the security has been sold. Importantly, scienter is not required for this claim. While choice B is incorrect because Section 12(a)(2) does not require proof of intent to deceive; liability attaches upon proof of a material misstatement in the offering materials.', 'medium', 2),

-- Q28: easy / L1 — Securities Act 1933 definition of security
(3, 'Government Regulation of Business', 'Under the Securities Act of 1933, which of the following is included in the statutory definition of a ''security''?', '["An investment contract, as defined by the Howey test", "A fixed annuity issued by a state-regulated insurance company", "A certificate of deposit issued by a federally insured bank", "A whole life insurance policy with a stated cash value component"]'::jsonb, 0, 'Under Section 2(a)(1) of the Securities Act of 1933, the term ''security'' includes investment contracts. The Supreme Court defined an investment contract in SEC v. W.J. Howey Co. (1946) as an investment of money in a common enterprise with the expectation of profits derived from the efforts of others. While choice B (fixed annuity) is generally excluded from the definition of a security because it does not involve investment risk; only variable annuities are typically treated as securities.', 'easy', 1),

-- Q29: hard / L4 — Regulation D exemption loss from general solicitation
(3, 'Government Regulation of Business', 'Trident Ventures LLC conducted a Rule 506(b) offering in January 2026 to raise $8 million. The company sold to 30 accredited and 3 non-accredited investors. Trident discovers that one accredited investor overstated net worth, and a sales agent made telephone solicitations to 50 unknown individuals without resulting purchases. Evaluate the impact on Trident''s exemption.', '["The exemption is preserved because the unqualified investor was not a non-accredited purchaser at the time of sale", "The exemption is preserved because the unsuccessful solicitations did not result in actual sales", "The exemption remains valid for accredited investor sales but is void for non-accredited sales only", "The exemption is likely lost because the telephone solicitations constitute general solicitation prohibited under Rule 506(b)"]'::jsonb, 3, 'Under SEC Rule 506(b) of Regulation D, general solicitation or general advertising is strictly prohibited. The sales agent''s telephone solicitations to 50 unknown individuals constitute general solicitation, which violates a fundamental condition of Rule 506(b) regardless of whether any solicited persons actually purchased. Loss of the exemption exposes the entire offering to potential registration violations. While choice B incorrectly assumes unsuccessful solicitations are harmless; Rule 506(b) prohibits the conduct itself, not merely resulting sales.', 'hard', 4),

-- Q30: medium / L2 — Section 16(b) short-swing profit disgorgement
(3, 'Government Regulation of Business', 'Chen, a director of Oakmont Corp., purchased 10,000 shares of Oakmont stock at $30 per share on January 15, 2026. On April 20, 2026, Chen sold all 10,000 shares at $45 per share. Under Section 16(b) of the Securities Exchange Act of 1934, what is the company entitled to recover?', '["Nothing, because directors are exempt from the short-swing profit rule", "$150,000, because Section 16(b) requires disgorgement of profits from purchases and sales within six months", "$75,000, because Section 16(b) allows recovery of only half the profit as a deterrent", "Nothing, because Chen must first be convicted of insider trading"]'::jsonb, 1, 'Under Section 16(b) of the Securities Exchange Act of 1934, any profit realized by a statutory insider (director, officer, or 10%+ shareholder) from a purchase and sale of the company''s equity securities within six months must be disgorged to the company. Chen''s profit is $150,000 (10,000 shares x $15 gain). Section 16(b) is strict liability requiring no proof of insider trading intent. While choice A is incorrect because directors are expressly included as statutory insiders subject to Section 16(b) disgorgement.', 'medium', 2)
;

COMMIT;
