-- Migration: Question generation — REG batch 50 (30 questions)
-- Date: 2026-03-03
-- Topic: Debtor-Creditor Relationships
-- Difficulty: 9E / 15M / 6H
-- Bloom's: L1:8 / L2:9 / L3:8 / L4:5

BEGIN;

INSERT INTO questions (section_id, topic, stem, choices, correct_index, explanation, difficulty, cognitive_level)
VALUES

-- Q1: easy / L1 — Involuntary petition creditor threshold
(3, 'Debtor-Creditor Relationships', 'How many creditors must join an involuntary bankruptcy petition when the debtor has 12 or more creditors?', '["At least three creditors with aggregate unsecured claims meeting the statutory minimum", "At least one creditor with a claim exceeding $10,000", "A majority of all creditors regardless of claim amounts", "Any single creditor with an undisputed claim"]'::jsonb, 0, 'Under Section 303(b) of the Bankruptcy Code, when a debtor has 12 or more creditors, at least three creditors with aggregate noncontingent, undisputed unsecured claims meeting the statutory threshold must join the involuntary petition. A single creditor may file only when the debtor has fewer than 12 creditors. The majority-of-creditors standard is incorrect because the Code specifies a minimum number, not a majority.', 'easy', 1),

-- Q2: hard / L4 — Chapter 11 cramdown evaluation
(3, 'Debtor-Creditor Relationships', 'Acme Industries files Chapter 11 and proposes a plan classifying unsecured creditors into two classes. Class 3 (trade creditors) accepts by majority in number and two-thirds in amount. Class 4 (bondholders) rejects unanimously. Acme asks the court to confirm over Class 4''s objection. Under Section 1129(b), which additional requirement must the court verify?', '["That all creditors in Class 4 voted on the plan within the statutory period", "That the plan is fair and equitable and does not discriminate unfairly against Class 4", "That Class 4 bondholders receive full payment of their claims within 90 days", "That the debtor obtains written consent from at least one Class 4 bondholder"]'::jsonb, 1, 'Under Section 1129(b) of the Bankruptcy Code, a court may confirm a plan over a dissenting class''s objection (cramdown) only if the plan is fair and equitable and does not discriminate unfairly. For unsecured creditors, fair and equitable means no junior class receives anything unless the dissenting class is paid in full. Requiring full payment within 90 days confuses cramdown with administrative expense priority rules.', 'hard', 4),

-- Q3: medium / L2 — UCC-1 financing statement content requirements
(3, 'Debtor-Creditor Relationships', 'Pacific Credit Union files a financing statement to perfect its security interest in Harmon LLC''s accounts receivable. The filing lists the secured party''s name and describes the collateral but omits the debtor''s name. Under UCC Article 9, what is the effect of this omission?', '["The filing is valid but establishes lower priority than a complete filing", "The filing is effective for 90 days while the creditor corrects the error", "The financing statement is seriously misleading and fails to perfect the interest", "The filing is valid because only the collateral description is required"]'::jsonb, 2, 'Under UCC Section 9-502, a financing statement must include the debtor''s name, the secured party''s name, and a description of the collateral. Section 9-506(b) provides that a financing statement that fails to sufficiently identify the debtor is seriously misleading and ineffective for perfection. Unlike a minor error in a secured party''s name, omitting the debtor''s name entirely cannot be cured retroactively.', 'medium', 2),

-- Q4: medium / L2 — Automatic perfection of PMSI in consumer goods
(3, 'Debtor-Creditor Relationships', 'Rivera purchases a home entertainment system for $3,500 on credit from an electronics retailer on February 10, 2026. The retailer retains a security interest in the system but does not file a UCC-1 financing statement. Under UCC Article 9, is the retailer''s security interest perfected?', '["No, because the retailer failed to file within 20 days of delivery", "No, because perfection requires either filing or possession of the collateral", "No, because automatic perfection applies only to purchase money security interests exceeding $5,000", "Yes, because a PMSI in consumer goods perfects automatically upon attachment"]'::jsonb, 3, 'Under UCC Section 9-309(1), a purchase money security interest in consumer goods perfects automatically upon attachment without the need to file a financing statement. A home entertainment system purchased for personal use qualifies as consumer goods. The 20-day grace period in choice A applies to PMSI super-priority for non-inventory goods under Section 9-324(a), not to the automatic perfection rule.', 'medium', 2),

-- Q5: hard / L4 — Surety subrogation analysis
(3, 'Debtor-Creditor Relationships', 'Kendall Corp. borrows $250,000 from Valley National Bank, secured by a lien on Kendall''s warehouse. Ortega serves as surety. Kendall defaults. Ortega pays the full $250,000 to the bank. Evaluate which right allows Ortega to enforce the bank''s lien on Kendall''s warehouse.', '["Subrogation, because paying in full entitles the surety to step into the creditor''s position and enforce all of the creditor''s rights", "Reimbursement, because the surety is entitled to recover the amount paid from any collateral held by the creditor", "Exoneration, because the surety can compel the creditor to foreclose on the collateral before demanding payment", "Contribution, because the surety shares the loss equally with the creditor under the co-obligation principle"]'::jsonb, 0, 'Under suretyship law, subrogation entitles a surety who pays the creditor in full to step into the creditor''s shoes and exercise all of the creditor''s rights, including enforcing liens and security interests against the principal debtor. Using the ERS mnemonic, Subrogation is the post-full-payment right. Reimbursement allows recovery of the amount paid from the debtor but does not transfer the creditor''s lien rights.', 'hard', 4),

-- Q6: medium / L3 — Chapter 13 best interests test application
(3, 'Debtor-Creditor Relationships', 'Morgan files Chapter 13 and proposes a 5-year plan paying unsecured creditors 25 cents per dollar. If Morgan had filed Chapter 7, the trustee would have distributed 40 cents per dollar to unsecured creditors from nonexempt assets. Under Section 1325(a)(4), what must the court do?', '["Approve the plan because Chapter 13 debtors may set their own repayment percentage", "Approve the plan because the 5-year commitment period satisfies the good faith requirement", "Deny confirmation because unsecured creditors must receive at least what they would get in Chapter 7", "Deny confirmation because Chapter 13 plans must pay unsecured creditors in full"]'::jsonb, 2, 'Under Section 1325(a)(4) of the Bankruptcy Code, a Chapter 13 plan must satisfy the best interests test, requiring that each unsecured creditor receive at least as much as it would in a Chapter 7 liquidation. The proposed 25 cents is less than 40 cents available in Chapter 7, so the court must deny confirmation. The 5-year commitment period satisfies a different requirement under Section 1325(b), not the best interests test.', 'medium', 3),

-- Q7: medium / L2 — Financing statement duration and continuation
(3, 'Debtor-Creditor Relationships', 'First Federal Bank filed a UCC-1 financing statement on March 15, 2021, covering all equipment of Dalton Manufacturing. The bank has not filed a continuation statement. As of April 1, 2026, what is the status of the bank''s perfection?', '["The financing statement remains effective indefinitely until the debt is paid", "The financing statement lapsed on March 15, 2026, rendering the security interest unperfected", "The financing statement expired after 3 years on March 15, 2024", "The financing statement is effective until the bank files a termination statement"]'::jsonb, 1, 'Under UCC Section 9-515(a), a financing statement is effective for five years from the date of filing. A continuation statement must be filed within six months before expiration to maintain effectiveness. Since the bank filed on March 15, 2021, the statement lapsed on March 15, 2026. Without a continuation statement, the security interest becomes unperfected. Choice C is incorrect because UCC Article 9 specifies five years, not three.', 'medium', 2),

-- Q8: easy / L2 — Surety vs. guarantor distinction
(3, 'Debtor-Creditor Relationships', 'Nakamura guarantees Patel''s $75,000 loan from Central Bank as a guarantor of collection. Patel defaults and Central Bank immediately demands payment from Nakamura without first pursuing Patel. What is Nakamura''s best defense?', '["Guarantors have no obligation until the debt is 90 days past due", "The guaranty is void because separate consideration was not provided", "Nakamura is discharged because the bank modified the loan terms without consent", "The bank must first exhaust remedies against Patel before demanding payment from Nakamura"]'::jsonb, 3, 'A guarantor of collection has secondary liability, meaning the creditor must first exhaust remedies against the principal debtor before proceeding against the guarantor. This distinguishes a guarantor of collection from a surety, who has primary liability and can be pursued directly without first seeking payment from the debtor. The 90-day waiting period in choice A is fictitious and has no basis in guaranty law.', 'easy', 2),

-- Q9: easy / L1 — Debtor-in-possession definition
(3, 'Debtor-Creditor Relationships', 'In a Chapter 11 bankruptcy, what is a debtor-in-possession?', '["A creditor appointed by the court to manage the debtor''s property", "A debtor who retains control of business operations during reorganization", "A trustee who liquidates the debtor''s nonexempt assets for distribution", "A secured creditor who holds collateral pending completion of the plan"]'::jsonb, 1, 'Under Section 1101(1) of the Bankruptcy Code, a debtor-in-possession (DIP) is the debtor who continues to operate the business during Chapter 11 reorganization. The DIP has the same powers and duties as a trustee, including the authority to use, sell, or lease property of the estate. A DIP is distinct from a liquidating trustee in Chapter 7, who sells assets rather than continuing operations.', 'easy', 1),

-- Q10: easy / L1 — Perfection by control
(3, 'Debtor-Creditor Relationships', 'Under UCC Article 9, which type of collateral may be perfected by the secured party obtaining control?', '["Tangible equipment used in the debtor''s business operations", "Consumer goods purchased on credit from a retail seller", "Deposit accounts maintained at a financial institution", "Inventory held for sale in the ordinary course of business"]'::jsonb, 2, 'Under UCC Section 9-312(b)(1), a security interest in a deposit account may be perfected only by control, not by filing a financing statement. Control over a deposit account is established under Section 9-104 when the secured party is the bank, the debtor consents to the bank''s instructions, or the secured party becomes the bank''s customer. Equipment, consumer goods, and inventory are typically perfected by filing, not control.', 'easy', 1),

-- Q11: hard / L4 — Relief from automatic stay analysis
(3, 'Debtor-Creditor Relationships', 'Harper files Chapter 7 on January 5, 2026. Crestview Bank holds a mortgage on Harper''s rental property valued at $180,000, with a $220,000 mortgage balance. Harper has no equity, the property generates no income for the estate, and the insurance has lapsed. Evaluate whether Crestview should obtain relief from the automatic stay.', '["Yes, because the debtor has no equity and the property is not necessary for an effective reorganization", "Yes, but only if the bank demonstrates irreparable harm within 60 days", "No, because the automatic stay remains in effect until discharge regardless of collateral value", "No, because relief from stay is available only in Chapter 11 reorganization proceedings"]'::jsonb, 0, 'Under Section 362(d)(2) of the Bankruptcy Code, a court shall grant relief from the automatic stay if the debtor has no equity in the property and the property is not necessary for an effective reorganization. Here, the $220,000 mortgage exceeds the $180,000 value (no equity), and in Chapter 7 there is no reorganization. Choice D is incorrect because Section 362(d) applies in all bankruptcy chapters, not only Chapter 11.', 'hard', 4),

-- Q12: medium / L2 — Material modification defense for surety
(3, 'Debtor-Creditor Relationships', 'Campos serves as surety on Newton''s $200,000 loan from Heritage Bank. Without Campos''s consent, Heritage Bank and Newton agree to extend the repayment period by two years and increase the interest rate from 5% to 8%. Newton later defaults. What is the effect on Campos''s liability?', '["Campos remains fully liable because sureties cannot raise defenses based on contract modifications", "Campos remains liable for the original amount but owes interest at the higher 8% rate", "Campos is liable only if the creditor proves that the modification did not increase the surety''s risk", "Campos is discharged to the extent that the material modification without consent caused prejudice"]'::jsonb, 3, 'Under suretyship law, a material modification of the underlying obligation without the surety''s consent discharges the surety to the extent of any resulting prejudice. Extending the term and increasing the interest rate are material changes that increase the surety''s risk exposure. Choice A is incorrect because material modification is a well-established surety defense under the Restatement (Third) of Suretyship and Guaranty Section 41.', 'medium', 2),

-- Q13: medium / L2 — Denial of discharge vs. nondischargeable debts
(3, 'Debtor-Creditor Relationships', 'Walters files Chapter 7 and the court discovers that Walters concealed $50,000 in cash before filing, made a false oath on the bankruptcy schedules, and received a Chapter 7 discharge three years ago. Under Section 727, what is the most likely outcome?', '["Only the $50,000 concealment is nondischargeable while all other debts are discharged", "The court denies discharge of debts obtained through fraud but discharges the remaining debts", "The court denies Walters''s entire discharge, leaving all pre-petition debts enforceable", "The court grants a partial discharge covering only secured debts"]'::jsonb, 2, 'Under Section 727(a) of the Bankruptcy Code, the court may deny the debtor''s entire discharge for misconduct including concealment of property, false oaths, and receiving a prior Chapter 7 discharge within eight years. Walters committed concealment, made a false oath, and received a discharge only three years ago. This is distinct from Section 523 nondischargeability, which exempts specific debts while allowing the general discharge to proceed.', 'medium', 2),

-- Q14: easy / L1 — Property of the bankruptcy estate
(3, 'Debtor-Creditor Relationships', 'What does property of the bankruptcy estate include under Section 541?', '["Only assets the debtor acquired after the petition date", "All legal and equitable interests of the debtor in property as of the filing date", "Only real property owned by the debtor at the time of filing", "Only assets that the debtor''s creditors have specifically identified in their claims"]'::jsonb, 1, 'Under Section 541(a)(1) of the Bankruptcy Code, property of the estate includes all legal and equitable interests of the debtor in property as of the commencement of the case. This encompasses real and personal property, tangible and intangible assets, and causes of action. Choice A is incorrect because property of the estate is determined as of the petition date, with limited exceptions for certain post-petition acquisitions under Section 541(a)(5).', 'easy', 1),

-- Q15: hard / L4 — Lien creditor vs. perfected SI timing analysis
(3, 'Debtor-Creditor Relationships', 'On May 1, 2026, Apex Bank makes a loan to Drake Corp. and obtains a security agreement covering Drake''s equipment. Apex does not file a UCC-1. On May 15, a judgment creditor obtains a judicial lien on Drake''s equipment. On May 20, Apex files its financing statement. Analyze who has priority in Drake''s equipment.', '["Apex Bank, because its security interest attached before the judicial lien", "Apex Bank, because filing within 20 days gives retroactive priority to the attachment date", "The judgment creditor and Apex Bank share equal priority because both claims are valid", "The judgment creditor, because a lien creditor prevails over a security interest unperfected at the time the lien arose"]'::jsonb, 3, 'Under UCC Section 9-317(a)(2), a lien creditor has priority over a security interest that is unperfected at the time the lien arises. Apex''s interest attached May 1 but was not perfected until May 20. The judicial lien arose May 15 when Apex was still unperfected. The 20-day retroactive priority under Section 9-324(a) applies only to purchase money security interests, not ordinary security interests. The judgment creditor prevails.', 'hard', 4),

-- Q16: medium / L2 — Pro rata distribution within priority level
(3, 'Debtor-Creditor Relationships', 'Westfall Corp. files Chapter 7 with $60,000 remaining after paying all higher-priority claims. Three general unsecured creditors hold claims: Creditor A ($80,000), Creditor B ($40,000), and Creditor C ($80,000). How is the $60,000 distributed?', '["Creditor A receives $24,000, Creditor B receives $12,000, and Creditor C receives $24,000", "Creditor A receives $30,000, Creditor B receives $10,000, and Creditor C receives $20,000", "Creditor A receives $20,000, Creditor B receives $20,000, and Creditor C receives $20,000", "Creditor A receives $40,000, Creditor B receives $20,000, and Creditor C receives $0"]'::jsonb, 0, 'Under Section 726(b) of the Bankruptcy Code, claims within the same priority level are paid pro rata when assets are insufficient. Total claims equal $200,000, so each receives 30% ($60,000/$200,000). Creditor A: $80,000 x 30% = $24,000. Creditor B: $40,000 x 30% = $12,000. Creditor C: $80,000 x 30% = $24,000. Equal distribution (choice C) is incorrect because pro rata allocates proportionally to claim size, not equally.', 'medium', 2),

-- Q17: hard / L4 — Chapter 13 disposable income commitment period
(3, 'Debtor-Creditor Relationships', 'Franklin, whose income exceeds the state median, files Chapter 13 and proposes a 3-year plan committing $1,500 per month to unsecured creditors. The means test shows $2,200 in monthly disposable income. The Chapter 13 trustee objects. Evaluate the likely basis for the trustee''s objection under Section 1325(b).', '["The plan must be converted to Chapter 7 because Franklin''s income exceeds the state median", "Franklin must commit all projected disposable income for a 5-year period, not 3 years", "Franklin must increase the monthly payment to equal 75% of disposable income as a statutory minimum", "The plan must pay all unsecured creditors in full because Franklin earns above the median"]'::jsonb, 1, 'Under Section 1325(b)(4), a debtor whose income exceeds the state median must commit all projected disposable income to the plan for five years, not three. Franklin must also commit the full $2,200, not $1,500. Choice A is incorrect because above-median debtors are not automatically converted to Chapter 7; they may file Chapter 13 but face the longer commitment period and stricter disposable income requirements.', 'hard', 4),

-- Q18: easy / L1 — Reaffirmation agreement purpose
(3, 'Debtor-Creditor Relationships', 'In a Chapter 7 bankruptcy, what is the purpose of a reaffirmation agreement?', '["To require the trustee to distribute assets to a specific creditor first", "To convert the Chapter 7 case to a Chapter 13 repayment plan", "To extend the automatic stay beyond the discharge date for specific creditors", "To allow the debtor to voluntarily remain liable on a specific debt after discharge"]'::jsonb, 3, 'Under Section 524(c) of the Bankruptcy Code, a reaffirmation agreement is a voluntary agreement by the debtor to remain personally liable on a debt that would otherwise be discharged in Chapter 7. Debtors commonly reaffirm debts to retain collateral such as a car or home. The agreement must be executed before discharge and may require court approval. Choice B is incorrect because reaffirmation does not convert the case to a different chapter.', 'easy', 1),

-- Q19: easy / L1 — Corporations do not receive Chapter 7 discharge
(3, 'Debtor-Creditor Relationships', 'Parker Industries, a corporation, files Chapter 7 bankruptcy. What happens regarding discharge of the corporation''s debts?', '["The corporation receives a discharge identical to an individual debtor", "The corporation receives a limited discharge covering only unsecured debts", "The corporation does not receive a discharge and ceases to exist after liquidation", "The corporation receives a discharge after completing a mandatory repayment plan"]'::jsonb, 2, 'Under Section 727(a)(1) of the Bankruptcy Code, a discharge is available only to individual debtors in Chapter 7. A corporation filing Chapter 7 does not receive a discharge; instead, the trustee liquidates the entity''s assets, distributes proceeds to creditors, and the corporation ceases to exist. Choice A is incorrect because the Code expressly limits Chapter 7 discharge to individuals, not partnerships or corporations.', 'easy', 1),

-- Q20: medium / L3 — Impairment of collateral defense
(3, 'Debtor-Creditor Relationships', 'Liu serves as surety on Bennett''s $150,000 loan from Meridian Bank, secured by Bennett''s delivery truck worth $80,000. Meridian Bank releases its lien on the truck without Liu''s consent. Bennett later defaults. Apply suretyship principles to determine the effect on Liu''s liability.', '["Liu remains fully liable because the surety cannot object to the creditor''s disposition of collateral", "Liu is completely discharged because any impairment of collateral voids the surety''s entire obligation", "Liu''s liability is reduced by $150,000 because the creditor breached its duty to the surety", "Liu''s liability is reduced by $80,000, reflecting the value of the impaired collateral"]'::jsonb, 3, 'Under suretyship law, a creditor who impairs collateral without the surety''s consent discharges the surety to the extent of the impairment. The Restatement (Third) of Suretyship and Guaranty Section 42 provides that the surety is discharged proportionally to the value of the impaired collateral. Since the truck was worth $80,000, Liu''s liability is reduced from $150,000 to $70,000. Complete discharge (choice B) is incorrect because discharge is limited to the extent of impairment.', 'medium', 3),

-- Q21: medium / L3 — After-acquired property clause
(3, 'Debtor-Creditor Relationships', 'Cornerstone Bank''s security agreement with Preston Distributors covers "all inventory now owned or hereafter acquired." Cornerstone files a UCC-1 on January 10, 2026. On March 5, Preston acquires a new shipment of inventory worth $120,000. Apply UCC Article 9 to determine Cornerstone''s rights in the new inventory.', '["Cornerstone''s security interest automatically attaches to the new inventory without additional filing", "Cornerstone must file an amended financing statement within 20 days to cover the new inventory", "Cornerstone must execute a new security agreement for each subsequent acquisition of inventory", "Cornerstone has no rights in the new inventory because the original agreement covers only existing collateral"]'::jsonb, 0, 'Under UCC Section 9-204(a), a security agreement may provide for a security interest in after-acquired collateral. When the agreement contains an after-acquired property clause, the security interest automatically attaches to new collateral as the debtor acquires rights in it, without requiring a new agreement or amended filing. The original UCC-1 continues to cover after-acquired inventory. Choice B is incorrect because the 20-day rule applies to PMSI super-priority, not after-acquired property.', 'medium', 3),

-- Q22: medium / L2 — Chapter 13 eligibility debt limits
(3, 'Debtor-Creditor Relationships', 'Yamada, an individual with regular income, has $1,800,000 in unsecured debts and $600,000 in secured debts. Yamada wants to file Chapter 13 to retain her home and car while repaying creditors over 5 years. Under the Bankruptcy Code, is Yamada eligible?', '["No, because Chapter 13 is available only to debtors with unsecured debts below $500,000", "Yes, because the combined debt of $2,400,000 falls below the Chapter 13 eligibility limit", "No, because Chapter 13 requires total unsecured debts to be less than $1,000,000", "Yes, but only if Yamada''s annual income exceeds the combined debt amount"]'::jsonb, 1, 'Under Section 109(e) of the Bankruptcy Code, Chapter 13 is available to individuals with regular income whose total noncontingent, liquidated debts do not exceed the statutory limit ($2,750,000 combined secured and unsecured under current thresholds). Yamada''s combined $2,400,000 falls below this ceiling. Choice A is incorrect because the debt limit is significantly higher than $500,000, and the Code uses a combined threshold rather than separate caps.', 'medium', 2),

-- Q23: medium / L3 — Setoff rights and automatic stay
(3, 'Debtor-Creditor Relationships', 'Gallagher owes $90,000 to National Commerce Bank on an unsecured loan. Gallagher also has a $30,000 checking account at the same bank. Gallagher files Chapter 7 on April 1, 2026. The bank wants to apply the $30,000 deposit against Gallagher''s loan. Under Section 553, can the bank exercise its setoff right?', '["Yes, the bank may offset immediately because mutual debts are exempt from the automatic stay", "No, because setoff rights are permanently extinguished when a bankruptcy petition is filed", "The bank must obtain court permission because the automatic stay prohibits unilateral setoff", "No, because setoff is available only to secured creditors holding perfected security interests"]'::jsonb, 2, 'Under Section 362(a)(7), the automatic stay prohibits the setoff of mutual debts without court approval. However, Section 553 preserves the substantive right of setoff — it is not extinguished by the bankruptcy filing. The bank must seek relief from the automatic stay before exercising the setoff. Choice A is incorrect because while mutual debts can be set off, the stay requires the bank to obtain court permission first rather than acting unilaterally.', 'medium', 3),

-- Q24: medium / L3 — Defenses NOT available to surety
(3, 'Debtor-Creditor Relationships', 'Torres serves as surety on Drake''s $100,000 promissory note payable to Beacon Finance. Drake files Chapter 7 bankruptcy and receives a discharge. Torres argues that because Drake''s obligation has been discharged, Torres should also be released. Apply suretyship principles to evaluate Torres''s argument.', '["Torres is correct because the surety''s obligation terminates when the principal debtor is discharged", "Torres is correct because the surety has a right of exoneration that prevents the creditor from demanding payment", "Torres is correct because the discharge constitutes a release of the principal debtor without the surety''s consent", "Torres is incorrect because the principal debtor''s discharge in bankruptcy does not release the surety"]'::jsonb, 3, 'Under established suretyship law, the principal debtor''s bankruptcy discharge does not release the surety from liability. A discharge releases the debtor personally but does not extinguish the underlying debt for suretyship purposes. The Restatement (Third) of Suretyship and Guaranty Section 39 confirms that the debtor''s discharge in bankruptcy is not a defense available to the surety. Choice C is incorrect because a bankruptcy discharge is not a voluntary release by the creditor.', 'medium', 3),

-- Q25: medium / L2 — Relief from stay grounds
(3, 'Debtor-Creditor Relationships', 'In a bankruptcy proceeding, a secured creditor petitions the court for relief from the automatic stay under Section 362(d). Which of the following is a recognized ground for granting relief from the stay?', '["The creditor demonstrates cause, including lack of adequate protection of its interest in property", "The creditor proves that the debtor filed the petition in bad faith to delay foreclosure proceedings", "The creditor shows that the debtor''s attorney failed to file the petition within the statutory deadline", "The creditor establishes that the debt was incurred within 60 days before the filing date"]'::jsonb, 0, 'Under Section 362(d)(1), a court shall grant relief from the automatic stay for cause, including the lack of adequate protection. Examples include declining collateral value without insurance or equity cushion. Section 362(d)(2) provides an alternative ground when the debtor has no equity and the property is not necessary for reorganization. Choice B, while potentially relevant to case dismissal under Section 707(b), is not a statutory ground under Section 362(d).', 'medium', 2),

-- Q26: hard / L3 — Financing statement lapse and priority reversal
(3, 'Debtor-Creditor Relationships', 'Alpine Bank filed a UCC-1 on January 10, 2021, covering Delta Corp.''s equipment. Summit Credit Union filed a UCC-1 on June 15, 2024, covering the same equipment. Alpine Bank failed to file a continuation statement. On February 1, 2026, Delta defaults on both loans. Apply UCC Article 9 priority rules to determine who has first priority.', '["Alpine Bank, because its original filing date of January 10, 2021, establishes permanent first-in-time priority", "Summit Credit Union, because Alpine''s financing statement lapsed on January 10, 2026, rendering its interest unperfected", "Neither party, because both financing statements are ineffective after five years", "Alpine Bank and Summit share equal priority because both have valid security interests"]'::jsonb, 1, 'Under UCC Section 9-515(a), a financing statement is effective for five years. Alpine''s filing lapsed January 10, 2026, making its interest unperfected. Under Section 9-322(a)(2), a perfected interest defeats an unperfected one. Summit''s filing on June 15, 2024, remains effective through June 15, 2029. Choice A is incorrect because a lapsed filing loses its priority date — the first-to-file rule requires a continuously effective filing.', 'hard', 3),

-- Q27: easy / L1 — Trustee avoiding powers purpose
(3, 'Debtor-Creditor Relationships', 'In Chapter 7 bankruptcy, what is the primary purpose of the trustee''s avoiding powers?', '["To prevent creditors from filing claims against the estate after the bar date", "To allow the trustee to reject executory contracts that are unfavorable to the estate", "To recover preferential transfers and fraudulent conveyances made before filing", "To deny the debtor''s discharge for failure to cooperate with the proceedings"]'::jsonb, 2, 'Under Sections 547 and 548 of the Bankruptcy Code, the trustee has the power to avoid preferential transfers (payments to creditors within 90 days of filing, or one year for insiders) and fraudulent conveyances (transfers made with intent to defraud or for less than reasonably equivalent value). These powers recover assets for all creditors'' benefit. Choice B describes the separate power to reject executory contracts under Section 365, not the avoiding powers.', 'easy', 1),

-- Q28: medium / L3 — Exempt vs. nonexempt property application
(3, 'Debtor-Creditor Relationships', 'Carson files Chapter 7 in a state with its own exemption scheme. Carson owns a primary residence with $40,000 in equity (state homestead exemption is $30,000), a personal vehicle worth $5,000 (state vehicle exemption is $6,000), and a stamp collection worth $15,000 (no applicable exemption). What can the trustee liquidate?', '["$10,000 of home equity above the exemption and the $15,000 stamp collection", "Only the stamp collection because real property is fully exempt in all states", "All three assets because Chapter 7 exemptions do not apply to personal property", "Only the vehicle because it is the lowest-value asset in the estate"]'::jsonb, 0, 'Under Section 522 of the Bankruptcy Code, debtors may exempt certain property using either federal or state exemptions. Carson''s $40,000 home equity exceeds the $30,000 homestead exemption by $10,000, so the trustee can reach that excess. The vehicle ($5,000) is fully covered by the $6,000 exemption. The stamp collection has no applicable exemption and is fully reachable. Choice B is incorrect because only the exempt portion of home equity is protected.', 'medium', 3),

-- Q29: medium / L3 — Chapter 11 creditor voting requirements
(3, 'Debtor-Creditor Relationships', 'In Atlas Corp.''s Chapter 11 case, Class 5 unsecured creditors vote on the proposed plan. Ten creditors hold total claims of $600,000. Six creditors holding $350,000 vote to accept. Four creditors holding $250,000 vote to reject. Apply Section 1126(c) to determine whether Class 5 has accepted the plan.', '["Yes, because a simple majority of six out of ten creditors voted in favor of the plan", "No, because unanimous approval of each creditor class is required for plan confirmation", "Yes, because the plan received both a majority in number and two-thirds in dollar amount", "No, because the plan received majority in number but not two-thirds in dollar amount"]'::jsonb, 3, 'Under Section 1126(c) of the Bankruptcy Code, a class accepts a plan if approved by creditors holding at least two-thirds in amount AND a majority in number. Here, 6/10 creditors (60% — majority in number) accepted, but $350,000/$600,000 = 58.3% in dollar amount, falling short of the 66.7% threshold. Both conditions must be met. Choice C is incorrect because while the majority-in-number test is satisfied, the two-thirds-in-amount test is not.', 'medium', 3),

-- Q30: easy / L1 — Surety's right of exoneration
(3, 'Debtor-Creditor Relationships', 'What is the surety''s right of exoneration in a suretyship arrangement?', '["The right to compel the principal debtor to pay the creditor before the surety is required to pay", "The right to recover from the principal debtor amounts the surety has already paid the creditor", "The right to step into the creditor''s position after paying the debt in full", "The right to demand that co-sureties share in the payment of the obligation"]'::jsonb, 0, 'Under suretyship law, exoneration is the surety''s pre-payment right to petition a court to compel the principal debtor to perform before the surety must pay. Using the ERS mnemonic, Exoneration comes first (before payment), Reimbursement follows payment (recover from debtor), and Subrogation occurs after full payment (step into creditor''s shoes). Choice B describes reimbursement, and choice C describes subrogation — both are distinct post-payment rights.', 'easy', 1)
;

COMMIT;
