-- Migration: Question generation — FAR batch 54 (30 questions)
-- Date: 2026-03-03
-- Topic: Governmental Accounting
-- Difficulty: 9E / 15M / 6H
-- Bloom's: L1:8 / L2:9 / L3:8 / L4:5

BEGIN;

INSERT INTO questions (section_id, topic, stem, choices, correct_index, explanation, difficulty, cognitive_level)
VALUES

-- Q1: easy / L1 — Capital assets not subject to depreciation under GASB 34
(2, 'Governmental Accounting', 'Under GASB Statement No. 34, which category of capital assets is not subject to depreciation?', '["Land and construction in progress", "Buildings and improvements", "Infrastructure assets reported under the depreciation approach", "Equipment and vehicles"]'::jsonb, 0, 'Under GASB Statement No. 34, paragraphs 22-26, capital assets with indefinite or inexhaustible useful lives — including land, construction in progress, and certain works of art and historical treasures — are not depreciated. Unlike land and CIP, buildings and improvements (choice B) have finite useful lives and must be depreciated under the standard approach.', 'easy', 1),

-- Q2: easy / L1 — Custodial credit risk definition under GASB 40
(2, 'Governmental Accounting', 'Under GASB Statement No. 40, what is custodial credit risk for government deposits?', '["The risk that interest rate changes will reduce the fair value of investments", "The risk that a government will be unable to recover deposits because of general counterparty default", "The risk that deposits not covered by depository insurance or collateralization could be lost if the financial institution fails", "The risk that a government''s investment portfolio is overly concentrated in a single issuer"]'::jsonb, 2, 'Under GASB Statement No. 40, paragraph 8, custodial credit risk for deposits is the risk that in the event of a depository institution failure, the government''s deposits may not be returned because they are uninsured and uncollateralized. Choice B describes general credit risk rather than the specific custodial credit risk concept, which focuses on the absence of insurance and collateralization coverage.', 'easy', 1),

-- Q3: easy / L2 — Bond anticipation notes fund reporting
(2, 'Governmental Accounting', 'The City of Ridgemont issues $3,000,000 in bond anticipation notes on September 1, 2026, to fund preliminary construction of a new fire station. The city has a signed underwriting agreement for long-term bonds expected to close in March 2027. Under GASB standards, how should the BANs be reported in the capital projects fund?', '["As a long-term liability reported on the fund balance sheet", "As a fund liability if take-out criteria are unmet; otherwise as government-wide long-term debt only", "As an other financing source regardless of the take-out agreement", "As a deferred inflow of resources until the long-term bonds are issued"]'::jsonb, 1, 'Under GASB Interpretation No. 1, bond anticipation notes that meet take-out financing criteria — meaning the government has entered into a financing agreement to convert them to long-term debt — are excluded from governmental fund liabilities and reported only in the government-wide statements as long-term debt. Choice C is incorrect because BANs are not automatically classified as other financing sources; they must first be evaluated against the take-out criteria.', 'easy', 2),

-- Q4: easy / L1 — Voluntary nonexchange transactions under GASB 33
(2, 'Governmental Accounting', 'Under GASB Statement No. 33, which of the following best characterizes a voluntary nonexchange transaction?', '["A transaction imposed by a higher level of government with eligibility requirements", "A tax levied on assessed property values by the government", "A transaction derived from an underlying exchange between the taxpayer and a third party", "A transaction entered into willingly by both parties, such as a donation or a voluntary grant"]'::jsonb, 3, 'Under GASB Statement No. 33, paragraph 7, voluntary nonexchange transactions result from legislative or contractual agreements that are not imposed on the provider or recipient, including grants, donations, and entitlements. Choice A describes a government-mandated nonexchange transaction, which differs because the higher-level government compels participation rather than both parties entering the arrangement willingly.', 'easy', 1),

-- Q5: hard / L3 — GASB 18 landfill closure cost calculation with capacity used
(2, 'Governmental Accounting', 'The City of Summerville operates a municipal landfill with estimated total closure and postclosure care costs of $18,000,000. The landfill has a total permitted capacity of 4,000,000 cubic yards, and as of June 30, 2026, the city has used 2,600,000 cubic yards. The city holds $4,200,000 in restricted investments for closure costs. Under GASB Statement No. 18, what landfill closure and postclosure care liability should the city report on its government-wide statement of net position?', '["$11,700,000", "$7,500,000", "$18,000,000", "$13,800,000"]'::jsonb, 0, 'Under GASB Statement No. 18, paragraphs 8-9, the closure and postclosure liability is calculated based on the percentage of landfill capacity used: (2,600,000 / 4,000,000) × $18,000,000 = $11,700,000. Restricted investments are reported separately. Choice B ($7,500,000) is incorrect because it subtracts the $4,200,000 in restricted investments from the computed liability, whereas GASB 18 requires the liability and restricted assets to be reported independently.', 'hard', 3),

-- Q6: medium / L3 — Advance refunding: deferred amount on refunding presentation
(2, 'Governmental Accounting', 'The City of Thornfield advance-refunds $10,000,000 of outstanding general obligation bonds by placing $10,400,000 of new bond proceeds in an irrevocable escrow trust. The original bonds are legally defeased. The $400,000 difference between escrow deposits and defeased debt represents a deferred amount on refunding. Under GASB standards, how does the advance refunding affect the government-wide statement of net position?', '["Both the old and new debt are reported as liabilities, and the $400,000 is expensed immediately", "The old debt is removed, the new debt is reported, and the $400,000 is recognized as interest expense in the current period", "The old debt is removed, the new debt is reported, and the $400,000 is reported as a deferred outflow of resources amortized over the shorter of the remaining life of the old or new debt", "The old debt remains on the statement until the escrow trust formally retires it at maturity"]'::jsonb, 2, 'Under GASB Statement No. 86 and GASB 65, paragraph 7, when debt is advance-refunded through an irrevocable trust, the defeased debt is removed from the statement of net position and the difference is reported as a deferred outflow of resources, amortized over the remaining life of the old or new debt, whichever is shorter. Choice B is incorrect because the $400,000 is not expensed immediately — it is systematically amortized as an adjustment to interest expense over future periods.', 'medium', 3),

-- Q7: hard / L4 — Demand bond classification evaluation with standby liquidity
(2, 'Governmental Accounting', 'The City of Bakersville issues $15,000,000 in variable-rate demand bonds for infrastructure improvements. The bonds include a put option allowing holders to tender bonds on seven days'' notice. The city secures a three-year standby liquidity agreement with First National Bank to purchase any tendered bonds. The bank''s obligation expires in 2029. The finance director classifies the bonds as long-term debt in the government-wide statements and excludes them from governmental fund current liabilities. Under GASB Interpretation No. 1, evaluate whether the classification is appropriate.', '["Incorrect because demand bonds must always be reported as current liabilities due to the put option", "Appropriate because the standby liquidity agreement extends beyond the current fiscal year, meets the take-out criteria, and allows the government to exclude the bonds from fund current liabilities", "Incorrect because variable-rate debt cannot be reported as long-term regardless of the liquidity arrangement", "Appropriate only if the government has historically never experienced bond tenders"]'::jsonb, 1, 'Under GASB Interpretation No. 1, paragraphs 10-12, demand bonds may be excluded from governmental fund current liabilities and classified as long-term on government-wide statements if the government has a valid take-out agreement extending beyond the balance sheet date. The three-year standby liquidity agreement satisfies this criterion. Choice A is incorrect because the put option alone does not require current classification when a qualifying take-out agreement exists.', 'hard', 4),

-- Q8: medium / L2 — Revenue anticipation notes in governmental fund
(2, 'Governmental Accounting', 'The Town of Glenfield issues $2,500,000 in revenue anticipation notes at 4% annual interest on August 1, 2026, to cover operating expenses until property tax receipts arrive in November. The notes mature December 31, 2026. Under modified accrual, how should the general fund report the RAN proceeds and repayment?', '["Record $2,500,000 as revenue at issuance and $2,500,000 as expenditure at maturity", "Record $2,500,000 as an other financing source at issuance and an other financing use at repayment", "Record $2,500,000 as a deferred inflow at issuance and recognize revenue as property taxes are collected", "Record $2,500,000 as a fund liability at issuance, reduce the liability at repayment, and recognize interest expenditure when due"]'::jsonb, 3, 'Under GASB standards and modified accrual accounting, short-term revenue anticipation notes are reported as fund liabilities in the governmental fund because they will be repaid from current financial resources within the fiscal year. Interest is recognized as an expenditure when due. Choice B is incorrect because other financing source treatment applies to long-term debt proceeds, not short-term borrowings that create a current fund liability.', 'medium', 2),

-- Q9: medium / L2 — On-behalf payments under GASB 24
(2, 'Governmental Accounting', 'The State of Franklin pays $8,200,000 directly to the state pension fund for teacher retirement benefits on behalf of the Greendale School District during fiscal year 2026. The school district does not remit any pension contributions itself. Under GASB Statement No. 24, how should the Greendale School District report the state''s payment in its government-wide financial statements?', '["Disclose the payment in the notes but do not recognize revenue or expense", "Recognize $8,200,000 as both intergovernmental revenue and pension expense", "Record $8,200,000 as a reduction of the net pension liability with no effect on revenue or expense", "Report the $8,200,000 as an other financing source in governmental fund statements only"]'::jsonb, 1, 'Under GASB Statement No. 24, paragraph 7, on-behalf payments for fringe benefits and salaries made by one government for employees of another must be recognized as both revenue and expenditure/expense by the employer government. The school district reports $8,200,000 as intergovernmental revenue and pension expense. Choice A is incorrect because GASB 24 requires recognition, not merely disclosure, of on-behalf payments.', 'medium', 2),

-- Q10: hard / L4 — GASB 10 ISF self-insurance premium adequacy evaluation
(2, 'Governmental Accounting', 'The City of Oakfield established an internal service fund for workers'' compensation self-insurance eight years ago. The fund charges departmental premiums based on payroll. Current-year data: premiums billed $4,800,000; claims paid $3,200,000; incurred-but-not-reported claims estimated at $1,100,000; accumulated net position $3,600,000. Over the past three years, premiums have exceeded total claims (including IBNR) by an average of $900,000 annually. The external auditor questions whether premium charges are reasonable. Under GASB Statement No. 10, evaluate the most appropriate conclusion.', '["The premiums are appropriate because risk financing funds should maintain large reserves for catastrophic events", "The premiums are unreasonable because the surplus demonstrates premiums exceed actuarially determined levels and rates must be lowered immediately", "The premiums should approximate the cost of claims including IBNR, and the persistent surplus indicates rates should be reduced so government-wide expenses are not overstated", "The premiums are irrelevant because internal service fund transactions are eliminated entirely in government-wide statements"]'::jsonb, 2, 'Under GASB Statement No. 10, paragraphs 62-64, internal service fund charges should approximate the cost of providing coverage, including estimated claims and IBNR. A persistent surplus indicates premiums exceed actual costs, overstating departmental expenditures and potentially distorting function-level expenses in government-wide statements after allocation. Choice D is incorrect because while ISF markup is eliminated, the underlying cost allocation to individual functions is affected by premium levels.', 'hard', 4),

-- Q11: easy / L1 — Special-purpose government reporting options
(2, 'Governmental Accounting', 'Under GASB Statement No. 34, what reporting option is available to a special-purpose government engaged in a single governmental activity?', '["It must prepare both government-wide and fund financial statements with full reconciliation", "It must report using only proprietary fund statements", "It may prepare only fiduciary fund statements if it holds resources for external parties", "It may combine government-wide and fund financial statements into a single set of statements"]'::jsonb, 3, 'Under GASB Statement No. 34, paragraphs 135-137, special-purpose governments engaged in a single governmental activity (such as certain school districts or library districts) may present combined government-wide and fund financial statements using a single-column presentation. Choice A is incorrect because the dual-perspective requirement for general-purpose governments does not mandate full separate presentations for single-activity special-purpose entities.', 'easy', 1),

-- Q12: medium / L2 — GASB 46 enabling legislation and restricted net position
(2, 'Governmental Accounting', 'The State of Pinecrest enacts legislation imposing a 1% hotel tax, dedicating proceeds exclusively to tourism promotion. As of June 30, 2026, the state holds $5,800,000 in unspent hotel tax collections. The legislature has the authority to repeal the enabling legislation. Under GASB Statement No. 46 and GASB 34, how should the $5,800,000 be classified on the government-wide statement of net position?', '["Restricted net position, because the resources are constrained by enabling legislation currently in force", "Unrestricted net position, because the legislature can repeal the statute at any time", "Committed net position, because the constraint can be removed by legislative action", "Assigned net position, because the funds are earmarked but not externally restricted"]'::jsonb, 0, 'Under GASB Statement No. 46 and GASB 34, paragraph 34, resources constrained by enabling legislation are classified as restricted net position as long as the legislation remains in effect. The mere possibility of future repeal does not remove the restriction. Choice B is incorrect because GASB 46 specifically provides that restricted classification applies when enabling legislation is legally enforceable, regardless of the legislature''s theoretical power to change the law.', 'medium', 2),

-- Q13: easy / L1 — Public entity risk pool definition under GASB 10
(2, 'Governmental Accounting', 'Under GASB Statement No. 10, what is a public entity risk pool?', '["A private insurance company that provides coverage exclusively to governments", "A federal program that reimburses state governments for natural disaster losses", "An internal service fund that charges departmental premiums for self-insured claims", "A cooperative arrangement through which governments pool risks and resources to finance losses"]'::jsonb, 3, 'Under GASB Statement No. 10, paragraph 2, a public entity risk pool is a cooperative group of governmental entities joining together to pool risks and resources to finance risk of loss. It may operate as a separate entity or as part of a participating government. Choice C describes an individual government''s internal risk financing arrangement rather than a multi-government cooperative pool, which is the distinguishing feature.', 'easy', 1),

-- Q14: medium / L3 — Revenue accrual reconciliation adjustment: fund to government-wide
(2, 'Governmental Accounting', 'The County of Mapleton levies $24,000,000 in property taxes for fiscal year 2026. By December 31, the county collects $22,400,000 and expects $800,000 within 60 days. The remaining $800,000 is expected in April. The governmental fund recognizes $23,200,000 in revenue. When reconciling to the government-wide statements, how does the $800,000 due in April affect the reconciliation?', '["No reconciliation adjustment is required because it is deferred in both fund and government-wide statements", "The $800,000 is added to revenues in the government-wide statements because the full accrual basis does not apply the 60-day availability criterion", "The $800,000 reduces net position because it represents an uncertain receivable requiring an allowance", "The $800,000 is reported as a deferred outflow of resources on the government-wide statement"]'::jsonb, 1, 'Under GASB Statement No. 34, the government-wide statements use the full accrual basis, which recognizes imposed nonexchange revenue in the period for which levied regardless of availability. The $800,000 due in April is recognized as revenue in government-wide statements but deferred in the fund statements, creating an $800,000 reconciliation adjustment. Choice A is incorrect because full accrual eliminates the availability criterion, requiring recognition in the government-wide statements.', 'medium', 3),

-- Q15: medium / L2 — Current refunding of debt in debt service fund
(2, 'Governmental Accounting', 'The City of Marblewood currently refunds $6,000,000 in outstanding general obligation bonds by issuing $6,000,000 in new bonds at a lower interest rate. The old bonds are called and retired on the same date using proceeds from the new issue. Under GASB standards, how should the debt service fund report this current refunding?', '["Record the $6,000,000 new bond proceeds as revenue and the retirement as an expenditure", "Record the proceeds as a fund liability and the retirement as a gain", "Record the $6,000,000 new bond proceeds as an other financing source and the $6,000,000 retirement as an other financing use", "Record no entries because the transaction is a noncash exchange between creditor groups"]'::jsonb, 2, 'Under GASB standards for governmental funds, long-term bond proceeds are classified as other financing sources, and debt principal retirements are classified as other financing uses. In a current refunding, the new proceeds ($6,000,000) are an other financing source and the retired bonds ($6,000,000) are an other financing use. Choice A is incorrect because bond proceeds and debt retirements are never classified as revenues or expenditures in governmental funds.', 'medium', 2),

-- Q16: medium / L2 — GASB 88 direct borrowings disclosure requirements
(2, 'Governmental Accounting', 'Hillside County enters a $4,500,000 term loan directly with Mountain View Bank on March 1, 2026, at 5.2% fixed interest to finance road improvements. The loan requires quarterly payments over 10 years and is secured by the county''s motor fuel tax revenue. Under GASB Statement No. 88, what additional disclosures must the county provide for this direct borrowing beyond standard debt disclosures?', '["Only the total principal and interest payments over the life of the loan", "The terms including interest rate, assets pledged as collateral, events of default with finance-related consequences, and termination events", "A comparison of the interest rate obtained versus the prevailing market rate on the borrowing date", "The creditworthiness assessment of the bank providing the loan"]'::jsonb, 1, 'Under GASB Statement No. 88, paragraphs 5-7, direct borrowings and direct placements require additional note disclosures including terms specified in the debt agreement, amounts of unused lines of credit, assets pledged as collateral, and terms related to significant events of default with finance-related consequences and termination events. Choice C is incorrect because GASB 88 does not require market rate comparisons — it focuses on contractual terms and risks specific to direct borrowings.', 'medium', 2),

-- Q17: medium / L2 — GASB 74 OPEB plan-level fiduciary reporting
(2, 'Governmental Accounting', 'The Franklin County Retiree Health Benefits Trust is a single-employer OPEB plan providing medical coverage to retired county employees. The trust holds $32,000,000 in investments at fair value, and the total OPEB liability is $58,000,000. The plan administrator is preparing the plan''s standalone financial report. Under GASB Statement No. 74, what financial statements must the trust present?', '["A statement of fiduciary net position and a statement of changes in fiduciary net position", "A statement of net position and a statement of activities, consistent with government-wide reporting", "A balance sheet and an income statement, consistent with commercial GAAP", "Only a schedule of changes in net OPEB liability as required supplementary information"]'::jsonb, 0, 'Under GASB Statement No. 74, paragraphs 14-17, OPEB plans report using fiduciary fund financial statements: a statement of fiduciary net position and a statement of changes in fiduciary net position. Required supplementary information includes a schedule of changes in net OPEB liability and related ratios. Choice D is incorrect because the schedule of changes is RSI supplementing the basic financial statements, not a substitute for them.', 'medium', 2),

-- Q18: hard / L4 — Evaluate advance refunding vs current refunding strategies
(2, 'Governmental Accounting', 'The City of Grandview has $20,000,000 in outstanding general obligation bonds at 5.5% maturing in 2036 with a call date in 2028. Market rates are currently 3.8%. The finance director considers two options: (1) advance-refund now by escrowing $21,200,000 of new bond proceeds in Treasury securities, or (2) wait until the 2028 call date for a current refunding at estimated rates of 4.2%. The financial advisor recommends advance refunding, citing immediate debt service savings of $320,000 per year. Evaluate which option most likely serves the city''s long-term financial interest.', '["Advance refunding is preferable because the immediate savings exceed the premium and GASB 86 allows the excess to be fully amortized", "Current refunding is preferable because it avoids arbitrage rebate obligations and negative arbitrage on escrowed securities", "Advance refunding is preferable because defeased debt is removed from the statement of net position, immediately improving debt ratios", "Current refunding is most likely preferable because the advance refunding creates $1,200,000 in additional debt, negative arbitrage on the escrow, and potential arbitrage rebate obligations that may offset the annual savings"]'::jsonb, 3, 'Under GASB Statement No. 86 and IRC Section 148, advance refundings create economic costs beyond face value savings: the $1,200,000 in additional debt, negative arbitrage (Treasury yields typically below the new bond coupon), and potential arbitrage rebate obligations can erode or eliminate the $320,000 annual savings. Choice C is incorrect because while defeased debt is removed, the new debt replaces it, so improved ratios alone do not justify the economic costs of advance refunding.', 'hard', 4),

-- Q19: easy / L1 — GASB 88 direct borrowings vs public offerings
(2, 'Governmental Accounting', 'Under GASB Statement No. 88, what distinguishes a direct borrowing from other forms of government debt?', '["The debt is secured by specific revenue streams rather than general taxing authority", "The debt is issued through an underwriter and sold on the open market to investors", "The debt is negotiated directly with a lender, such as a bank, rather than sold through a public offering", "The debt carries a variable interest rate that adjusts with market conditions"]'::jsonb, 2, 'Under GASB Statement No. 88, paragraph 4, a direct borrowing is a debt arrangement entered into directly with a lender (bank, credit union, or other financial institution) rather than through a public securities offering. Choice B describes the opposite — a publicly offered bond issue — which is the traditional form of municipal debt and is not classified as a direct borrowing or direct placement under GASB 88.', 'easy', 1),

-- Q20: hard / L4 — GASB 40 concentration of credit risk disclosure evaluation
(2, 'Governmental Accounting', 'Lakewood County''s investment portfolio totals $45,000,000: $22,000,000 in U.S. Treasury obligations, $12,000,000 in a single corporate bond issuer (Apex Financial Corp., rated AA), $6,000,000 in a state investment pool, and $5,000,000 in certificates of deposit at one local bank (FDIC coverage is $250,000). The county''s investment policy limits single-issuer exposure to 15% of the portfolio. The external auditor reviews GASB 40 compliance. Evaluate the most significant disclosure concern.', '["The $12,000,000 Apex Financial Corp. holding exceeds the 5% threshold for concentration of credit risk disclosure and breaches the county''s own 15% policy limit, requiring GASB 40 disclosure and a policy violation note", "The U.S. Treasury obligations require interest rate risk disclosure because they constitute the largest portfolio allocation", "The state investment pool requires custodial credit risk disclosure because it is not FDIC insured", "The certificates of deposit create no disclosure obligation because they are fully covered by depository insurance"]'::jsonb, 0, 'Under GASB Statement No. 40, paragraph 12, investments in any single issuer representing 5% or more of total investments (excluding U.S. government securities and mutual fund or external investment pools) require concentration of credit risk disclosure. The Apex holding is 26.7% ($12M/$45M), exceeding both the GASB 40 threshold and the county''s 15% policy limit. Choice D is incorrect because only $250,000 of the $5,000,000 CD is FDIC-insured, creating custodial credit risk for the remaining $4,750,000.', 'hard', 4),

-- Q21: hard / L4 — Related organization vs component unit evaluation under GASB 14/39
(2, 'Governmental Accounting', 'Camden County appoints a majority of the board of the Camden Arts Council, a legally separate nonprofit. The Arts Council raises its own revenue through ticket sales and donations, sets its own budget and programs, and does not provide a direct financial benefit or impose a financial burden on the county. The county does not approve the Arts Council''s budget or set its rates. Under GASB Statement No. 14 as amended by GASB 61, evaluate the most appropriate reporting treatment.', '["Discrete component unit because the county appoints the board majority, which alone establishes financial accountability", "Blended component unit because the county''s governance role creates an inseparable relationship", "No reporting obligation because the Arts Council is a private nonprofit organization", "Related organization disclosed in the notes, because the county appoints the board majority but does not meet the additional criteria for financial accountability"]'::jsonb, 3, 'Under GASB Statement No. 14, paragraphs 21-22, and GASB 61, financial accountability requires appointment of a voting majority PLUS either the ability to impose its will or a fiscal dependency/benefit/burden relationship. The county appoints the majority but cannot impose its will (no budget approval or rate-setting) and has no financial benefit or burden. Choice A is incorrect because board appointment alone does not establish financial accountability — additional criteria must also be satisfied.', 'hard', 4),

-- Q22: easy / L1 — Purpose of combining financial statements for nonmajor funds
(2, 'Governmental Accounting', 'Under GASB Statement No. 34, what is the purpose of combining financial statements for nonmajor governmental funds?', '["To present individual fund detail for nonmajor funds that are aggregated into a single column on the basic fund financial statements", "To replace the government-wide financial statements for small governments", "To reconcile measurement focus differences between fund and government-wide statements", "To report fiduciary fund activity that is excluded from government-wide statements"]'::jsonb, 0, 'Under GASB Statement No. 34, paragraph 75, combining statements present individual fund information for nonmajor governmental, proprietary, and fiduciary funds that are aggregated into the "other governmental funds" or similar column in the basic fund financial statements. Choice C is incorrect because reconciliation is a separate schedule bridging measurement focus and basis of accounting differences, not the purpose of combining statements.', 'easy', 1),

-- Q23: medium / L3 — Enterprise fund segment information requirements under GASB 34
(2, 'Governmental Accounting', 'The City of Millhaven operates three enterprise funds: a water utility with $18,000,000 in outstanding revenue bonds, a sewer system with $12,000,000 in revenue bonds, and a parking authority with no outstanding debt. The finance director asks whether segment information must be disclosed. Under GASB Statement No. 34, which factor most likely determines whether an enterprise fund requires segment disclosure?', '["Whether the enterprise fund is reported as a major fund in the basic financial statements", "Whether the enterprise fund generates operating revenues exceeding 10% of total governmental revenues", "Whether the enterprise fund has outstanding revenue-backed debt with a revenue pledge creating an identifiable activity requiring segment disclosure", "Whether the enterprise fund provides services to external users rather than other government departments"]'::jsonb, 2, 'Under GASB Statement No. 34, paragraph 122, segment information is required for identifiable activities reported in enterprise funds that have outstanding revenue-backed bonds or other debt with revenues pledged in support of that debt. The water and sewer funds require segment disclosure because of their revenue bonds; the parking authority does not. Choice A is incorrect because major fund status determines basic statement presentation, not segment reporting requirements.', 'medium', 3),

-- Q24: medium / L3 — GASB 86 in-substance defeasance and note disclosure
(2, 'Governmental Accounting', 'The Town of Ridgedale places $8,200,000 in U.S. Treasury securities into an irrevocable trust to service $8,000,000 of outstanding general obligation bonds that are not callable until 2030. The trust cash flows match the bond payment schedule exactly. The finance director removes the $8,000,000 from the government-wide statement of net position. Under GASB Statement No. 86, how does this in-substance defeasance most likely affect financial reporting?', '["The defeased debt remains on the statement of net position until the bonds are formally called or mature", "The defeased debt is removed, and the $200,000 excess escrow is recognized as a gain in the current period", "The defeased debt is removed, and no further disclosure is required once the trust is established", "The defeased debt is removed from the statement of net position, but the outstanding amount must be disclosed in the notes until the bonds are fully retired"]'::jsonb, 3, 'Under GASB Statement No. 86, paragraphs 3-5, an in-substance defeasance through an irrevocable trust removes the debt from the statement of net position. However, the government must continue disclosing the amount of defeased debt outstanding in the notes until the bonds are fully retired. Choice C is incorrect because the note disclosure requirement persists for the life of the defeased bonds, not just through the defeasance date.', 'medium', 3),

-- Q25: medium / L2 — Interest on long-term debt: modified accrual recognition timing
(2, 'Governmental Accounting', 'The Town of Ashwood has $10,000,000 in general obligation bonds with semiannual interest payments due March 1 and September 1 at 5% annual interest. The town''s fiscal year ends June 30, 2026. The March 1 payment of $250,000 was made on time. The next $250,000 payment is due September 1, 2026. As of June 30, four months of interest ($166,667) have accrued since March 1. Under modified accrual in the debt service fund, how much interest expenditure should the town recognize for the fiscal year ended June 30?', '["$250,000, representing only the March 1 payment that was legally due during the fiscal year", "$416,667, representing the March payment plus four months of accrued interest", "$500,000, representing both semiannual payments", "$166,667, representing only the interest accrued but not yet due"]'::jsonb, 0, 'Under modified accrual accounting per GASB standards, interest on general long-term debt in governmental funds is recognized as an expenditure when the payment is legally due (the maturity date), not as interest accrues over time. Only the $250,000 March 1 payment was due during the fiscal year. Choice B is incorrect because the $166,667 accrued interest is not yet legally due and will be recognized in the next fiscal year when the September 1 payment matures.', 'medium', 2),

-- Q26: medium / L3 — Change in depreciation method as change in accounting principle under GASB 62
(2, 'Governmental Accounting', 'The City of Ridgehaven has historically depreciated fleet vehicles using the straight-line method. In fiscal year 2026, the finance director determines the units-of-production method better reflects economic benefit consumption and changes the depreciation method. The cumulative effect for prior years is $340,000 of additional depreciation. Under GASB Statement No. 62, how does this change affect the government-wide financial statements?', '["The $340,000 is recognized as a current-year expense adjustment on the statement of activities", "The $340,000 is reported as a restatement of beginning net position for the earliest period presented, and the change is applied retroactively", "The $340,000 is reported as a deferred outflow of resources and amortized over the remaining fleet useful life", "No adjustment is required because a change in depreciation method is treated as a change in accounting estimate"]'::jsonb, 1, 'Under GASB Statement No. 62, paragraphs 63-68, a change in depreciation method is classified as a change in accounting principle requiring retroactive application with restatement of beginning net position. Choice D is incorrect because while FASB (ASU 2015-01) treats depreciation method changes as changes in estimate applied prospectively, GASB follows its own guidance classifying this as a change in accounting principle requiring retroactive restatement.', 'medium', 3),

-- Q27: medium / L3 — Dedicated tax as general revenue, not program revenue
(2, 'Governmental Accounting', 'The City of Henderson receives $3,200,000 from a local-option 0.5% sales tax that the state legislature dedicated specifically to public transit operations. The transit department''s total operating costs are $5,100,000. The finance director classifies the dedicated sales tax as program revenue for the transit function on the government-wide statement of activities. Under GASB 34, analyze whether this classification is correct.', '["Correct, because the tax is legally dedicated to a specific function by enabling legislation", "Correct, because all revenue directly supporting a single function qualifies as program revenue", "Incorrect, because the sales tax should be split between program and general revenue proportionally", "Incorrect, because taxes — even those dedicated to specific purposes — are classified as general revenues under GASB 34"]'::jsonb, 3, 'Under GASB Statement No. 34, paragraph 52, taxes are always classified as general revenues, even when dedicated by law to a particular function. Only charges for services, operating grants/contributions, and capital grants/contributions qualify as program revenues. Choice A is incorrect because legal dedication does not change revenue classification — the distinction depends on whether revenue arises from an exchange-like transaction or eligibility-based grant, not from legislative earmarking.', 'medium', 3),

-- Q28: medium / L2 — Donated capital assets recorded at acquisition value
(2, 'Governmental Accounting', 'On April 15, 2026, the Greendale Foundation donates a parcel of land appraised at $1,800,000 to the City of Greendale for use as a public park. The city incurs $45,000 in title transfer fees and environmental inspection costs. Under GASB 34, at what amount should the city record the donated land in its government-wide statement of net position?', '["$0, because donated assets are not recorded in government financial statements", "$1,800,000, representing only the appraised value without ancillary costs", "$1,845,000, representing the acquisition value plus ancillary charges to place the asset in its intended use", "$45,000, representing only the city''s out-of-pocket costs"]'::jsonb, 2, 'Under GASB Statement No. 34, paragraph 18, and GASB 72, donated capital assets are recorded at acquisition value (fair value at the date of donation) plus ancillary costs such as title fees and inspection costs necessary to place the asset in service: $1,800,000 + $45,000 = $1,845,000. Choice B is incorrect because ancillary costs are capitalized along with the acquisition value, consistent with the treatment of purchased assets.', 'medium', 2),

-- Q29: medium / L3 — GASB 83 ARO measurement approach
(2, 'Governmental Accounting', 'The City of Rockdale operates a wastewater treatment plant built on leased state land. The ground lease requires the city to remove the plant and restore the site at the end of the 30-year lease. Engineers estimate restoration costs of $4,200,000 in current dollars. The plant was built 10 years ago with 20 years remaining. Under GASB Statement No. 83, which measurement approach should the city apply to the asset retirement obligation?', '["Present value of the total $4,200,000 discounted at the government''s incremental borrowing rate", "Best estimate of current cost adjusted for inflation and discounted using the yield on U.S. Treasury obligations of similar maturity", "Proportional share based on elapsed lease term: ($4,200,000 multiplied by 10/30) equals $1,400,000", "No liability is recognized until the final five years when restoration becomes imminent"]'::jsonb, 1, 'Under GASB Statement No. 83, paragraphs 10-14, asset retirement obligations are measured using the best estimate of current cost to settle the obligation, adjusted for inflation, and discounted using the yield on U.S. Treasury obligations of comparable term. Choice C is incorrect because GASB 83 does not use a proportional capacity-based approach — the full obligation is recognized when the liability is incurred at the obligating event, not allocated over the asset''s useful life.', 'medium', 3),

-- Q30: easy / L1 — GASB 83 asset retirement obligation recognition trigger
(2, 'Governmental Accounting', 'Under GASB Statement No. 83, what triggers a government''s recognition of an asset retirement obligation?', '["The government budgets funds for eventual asset removal costs", "A legally enforceable obligation to perform asset retirement activities exists, such as a requirement to dismantle a structure at the end of its useful life", "The asset reaches the midpoint of its estimated useful life", "The government files an environmental impact report with a regulatory agency"]'::jsonb, 1, 'Under GASB Statement No. 83, paragraphs 5-7, an asset retirement obligation is recognized when a legally enforceable liability associated with the retirement of a tangible capital asset exists, arising from laws, regulations, contracts, or court judgments. Choice C is incorrect because recognition timing depends on the existence of a legal obligation, not on the asset reaching any particular point in its useful life.', 'easy', 1)
;

COMMIT;
