-- Migration: Question generation — FAR batch 71 (30 questions)
-- Date: 2026-03-03
-- Topic: Bonds and Debt
-- Difficulty: 9E / 15M / 6H
-- Bloom's: L1:8 / L2:9 / L3:8 / L4:5

BEGIN;

INSERT INTO questions (section_id, topic, stem, choices, correct_index, explanation, difficulty, cognitive_level)
VALUES

-- Q1: medium / L2 — Bonds issued between interest dates (accrued interest received by issuer)
(2, 'Bonds and Debt', 'Hartfield Corp. issues $500,000 of 8% bonds at par on March 1, Year 1. The bonds are dated January 1, Year 1, and pay interest semiannually on July 1 and January 1. What total cash amount does Hartfield receive from the bond purchasers on March 1?', '["$500,000", "$520,000", "$506,667", "$513,333"]'::jsonb, 2, 'Under ASC 835-30, when bonds are issued between interest dates, the purchaser pays face value plus accrued interest from the last interest date to the issue date. Accrued interest = $500,000 × 8% × 2/12 = $6,667. Total cash = $500,000 + $6,667 = $506,667. However, Choice A ($500,000) is incorrect because it ignores the accrued interest the purchaser must pay to compensate the issuer for the period since the last interest date.', 'medium', 2),

-- Q2: medium / L3 — TDR modification of terms: future CFs < carrying amount (debtor gain)
(2, 'Bonds and Debt', 'Bergen Industries is in financial difficulty and negotiates a TDR with its lender. The loan has a carrying amount of $800,000 (including accrued interest). Under the modified terms, Bergen will pay $700,000 in total future cash flows (reduced principal of $650,000 and reduced interest of $50,000). Under ASC 470-60, what should Bergen record?', '["A new effective interest rate on the restructured debt and no gain", "A gain of $100,000 and reduce the carrying amount of the debt to $700,000", "A gain of $150,000 and reduce the carrying amount to $650,000", "No entry until the first payment is made under the new terms"]'::jsonb, 1, 'Under ASC 470-60-35, when total future cash flows under modified terms ($700,000) are less than the carrying amount ($800,000), the debtor recognizes a gain of $100,000 and reduces the liability to $700,000. No interest expense is recognized going forward. However, Choice A describes the outcome when future CFs exceed the carrying amount, where no gain is recognized and a new effective rate is computed instead.', 'medium', 3),

-- Q3: hard / L3 — Debt modification vs extinguishment (10% cash flow test, ASC 470-50)
(2, 'Bonds and Debt', 'Prescott Corp. modifies the terms of a $2,000,000 note payable with its bank. The original note has 4 years remaining at 6% annual interest. Under the new terms, the interest rate is reduced to 4% with the maturity extended to 6 years. Prescott calculates that the present value of the cash flows under the new terms differs from the present value of the remaining cash flows under the old terms by 12%, using the original effective rate. Under ASC 470-50, how should Prescott account for this modification?', '["As a modification — adjust the carrying amount and recognize a new effective interest rate prospectively", "As a modification — recognize the 12% difference as a gain immediately in earnings", "Continue using the original interest rate and maturity since no cash was exchanged", "As an extinguishment — derecognize the old debt and record the new debt at fair value, recognizing any difference as a gain or loss"]'::jsonb, 3, 'Under ASC 470-50-40, a debt modification between the same debtor and creditor is treated as an extinguishment if the present value of cash flows under the new terms differs by more than 10% from the present value under the old terms (discounted at the original effective rate). Since 12% exceeds the threshold, Prescott must derecognize the old debt and record new debt at fair value. However, Choice A would apply only if the change were less than 10%, in which case modification accounting is used.', 'hard', 3),

-- Q4: medium / L2 — Debt issuance costs amortization method
(2, 'Bonds and Debt', 'Waverly Inc. issues $3,000,000 of 10-year, 7% bonds at par and incurs $90,000 in debt issuance costs. Under ASC 835-30, the issuance costs are recorded as a direct deduction from the bond liability. How should Waverly amortize the issuance costs?', '["Using the effective interest method over the term of the bonds, increasing interest expense each period", "Expensed immediately as a period cost in the year of issuance", "Using the straight-line method over 10 years, which is the only permitted method", "Amortized only when the bonds are retired or when a principal payment is made"]'::jsonb, 0, 'Under ASC 835-30-35-2, debt issuance costs recorded as a contra-liability are amortized using the effective interest method over the life of the related debt, consistent with discount amortization. This increases effective interest expense each period. Choice B is incorrect because issuance costs are not period costs — they are deferred and amortized. The straight-line method is acceptable only if not materially different from the effective interest method.', 'medium', 2),

-- Q5: easy / L1 — Debenture definition
(2, 'Bonds and Debt', 'What type of bond is backed only by the general creditworthiness of the issuer, with no specific collateral pledged?', '["A mortgage bond", "A debenture", "A revenue bond", "A convertible bond"]'::jsonb, 1, 'Under ASC 470, a debenture is an unsecured bond backed solely by the issuer''s general credit standing and reputation, rather than by specific pledged assets. It carries higher risk for investors because no collateral secures repayment. A mortgage bond, in contrast, is secured by specific real property. Convertible bonds grant conversion rights but may be either secured or unsecured.', 'easy', 1),

-- Q6: easy / L1 — Premium condition (stated rate > market rate)
(2, 'Bonds and Debt', 'When is a bond issued at a premium?', '["When the stated rate is below the market rate at issuance", "When the market rate exceeds the stated rate at issuance", "When the stated rate exceeds the market rate at issuance", "When the bond is callable above face value"]'::jsonb, 2, 'Under ASC 835-30, a bond is issued at a premium when the stated (coupon) rate exceeds the prevailing market (effective) rate at issuance. Investors pay more than face value because the bond''s coupon payments exceed market returns. However, Choices A and B describe conditions that produce a discount, not a premium. Callability relates to early retirement rights, not issuance pricing.', 'easy', 1),

-- Q7: easy / L1 — Serial bonds definition
(2, 'Bonds and Debt', 'Under U.S. GAAP, what is a serial bond and how does it differ from a term bond?', '["A bond that matures in installments at regular intervals rather than all at once", "A bond that can be converted into common stock at the holder''s option", "A bond that pays interest only at maturity along with the principal", "A bond backed by a specific revenue stream of the issuer"]'::jsonb, 0, 'Under ASC 470, a serial bond is a bond issue in which portions of the principal mature at scheduled intervals over the life of the issue, rather than the entire face amount maturing on a single date (a term bond). This structure reduces refinancing risk for the issuer. However, Choice C describes a zero-coupon bond, while Choice D describes a revenue bond typically issued by governments.', 'easy', 1),

-- Q8: hard / L4 — TDR asset transfer to settle debt (two-component gain)
(2, 'Bonds and Debt', 'Kendall Corp. is in financial difficulty and transfers land with a carrying amount of $320,000 and a fair value of $400,000 to its lender to fully settle a $500,000 note payable. Under ASC 470-60, what total gain should Kendall recognize, and how is it reported?', '["$100,000 gain on the asset transfer only; no gain on the debt settlement", "$180,000 total gain, reported entirely as a gain on debt restructuring", "$100,000 gain on extinguishment of debt only; the asset transfer is recorded at carrying amount with no separate disposal gain", "An $80,000 gain on asset disposal and a $100,000 gain on debt extinguishment, reported as separate components"]'::jsonb, 3, 'Under ASC 470-60-35-2, a TDR involving transfer of assets requires two measurements. The difference between the asset''s fair value ($400,000) and carrying amount ($320,000) produces an $80,000 gain on disposal. The difference between the debt''s carrying amount ($500,000) and the asset''s fair value ($400,000) produces a $100,000 gain on extinguishment. Both are recognized but reported separately. Choice C is incorrect because it recognizes only the extinguishment gain while ignoring the $80,000 disposal gain — ASC 470-60-35-2 requires separate recognition of both components when the asset''s fair value exceeds its carrying amount.', 'hard', 4),

-- Q9: hard / L4 — Current refunding with call premium and unamortized discount
(2, 'Bonds and Debt', 'Lexington Corp. calls its $5,000,000 outstanding bonds (carrying amount $4,920,000, reflecting $80,000 of unamortized discount) at a call price of 103. To finance the redemption, Lexington simultaneously issues new bonds at par. Under ASC 470-50, what is the loss on extinguishment of the old bonds?', '["$70,000", "$230,000", "$150,000", "$80,000"]'::jsonb, 1, 'Under ASC 470-50-40, the loss on early extinguishment equals the reacquisition price minus the carrying amount. Call price = $5,000,000 × 103% = $5,150,000. Carrying amount = $4,920,000. Loss = $5,150,000 − $4,920,000 = $230,000. This is recognized immediately in income from continuing operations. However, Choice C ($150,000) is incorrect because it reflects only the call premium while ignoring the unamortized discount component.', 'hard', 4),

-- Q10: medium / L2 — Carrying amount computation from amortization data (discount bond)
(2, 'Bonds and Debt', 'When Paulson Inc. issued 4% bonds with a face value of $1,000,000 at $926,399, the effective market rate was 6%. Under the effective interest method, Year 1 interest expense is $55,584 and Paulson pays $40,000 in cash interest. What carrying amount should Paulson report for these bonds at December 31 of the first year?', '["$926,399", "$955,983", "$941,983", "$966,399"]'::jsonb, 2, 'Under the effective interest method (ASC 835-30), discount amortization each period equals interest expense minus cash paid. Year 1 amortization = $55,584 − $40,000 = $15,584. End-of-Year 1 carrying amount = $926,399 + $15,584 = $941,983. The carrying amount increases toward face value as the discount is amortized. However, Choice B adds the full interest expense rather than the amortization amount, which overstates the carrying amount.', 'medium', 2),

-- Q11: easy / L1 — Bond sinking fund purpose
(2, 'Bonds and Debt', 'What is the purpose of a bond sinking fund?', '["To provide collateral for the bond issue", "To record premium amortization over the bond''s life", "To pay for bond issuance costs as they are incurred", "To set aside assets for the retirement of bonds at maturity"]'::jsonb, 3, 'Under ASC 470, a bond sinking fund is a segregated pool of assets that the issuer sets aside, typically with a trustee, to ensure funds are available to retire bonds at maturity or to make scheduled redemptions. It is classified as a noncurrent asset on the balance sheet. However, Choice A is incorrect because it describes secured bond collateral rather than a sinking fund arrangement.', 'easy', 1),

-- Q12: medium / L2 — Premium amortization amount for a specific period
(2, 'Bonds and Debt', 'Palmer Corp. issues $1,500,000 of 10-year, 8% bonds at $1,614,000 when the market rate is 6.5%, paying interest annually. Under the effective interest method, Year 1 interest expense is $104,910 and the annual cash coupon is $120,000. What is the premium amortization for Year 1?', '["$15,090", "$104,910", "$120,000", "$114,000"]'::jsonb, 0, 'Under ASC 835-30, premium amortization each period equals the cash coupon payment minus interest expense. Cash coupon = $1,500,000 × 8% = $120,000. Year 1 amortization = $120,000 − $104,910 = $15,090. This amount reduces the carrying amount from $1,614,000 to $1,598,910. However, Choice B ($104,910) is incorrect because it represents interest expense rather than the amortization portion, while Choice C ($120,000) confuses the cash payment with amortization.', 'medium', 2),

-- Q13: medium / L2 — Induced conversion expense measurement
(2, 'Bonds and Debt', 'Quentin Corp. has $4,000,000 of convertible bonds outstanding. To encourage early conversion, Quentin offers bondholders an additional $200,000 cash payment if they convert within 30 days. All bondholders convert. Under ASC 470-20, how should Quentin account for the $200,000 additional consideration?', '["Capitalize the $200,000 as part of the equity issued upon conversion", "Recognize $200,000 as a conversion expense in the income statement", "Deduct the $200,000 from additional paid-in capital", "Reduce retained earnings by $200,000 as a direct equity charge"]'::jsonb, 1, 'Under ASC 470-20-40-13, when an issuer induces conversion by offering additional consideration beyond the original terms, the fair value of that additional consideration ($200,000) is recognized as an expense in the income statement. It is not capitalized or charged to equity. Choice A is incorrect because the sweetener is an incremental inducement cost, separate from the standard book-value reclassification of carrying amount to equity.', 'medium', 2),

-- Q14: easy / L1 — Reporting location for gain/loss on early extinguishment
(2, 'Bonds and Debt', 'Since the elimination of the extraordinary items classification under ASU 2015-01, where is a gain or loss on the early extinguishment of debt reported?', '["In income from continuing operations", "As an extraordinary item below income from continuing operations", "In other comprehensive income", "As a direct adjustment to retained earnings"]'::jsonb, 0, 'Under ASC 470-50 and ASU 2015-01, gains and losses on the early extinguishment of debt are reported in income from continuing operations. The extraordinary items category was eliminated by ASU 2015-01, so these items can no longer be segregated below the line. Choice C is incorrect because OCI is reserved for items like unrealized AFS gains and foreign currency translation adjustments, not debt extinguishment results.', 'easy', 1),

-- Q15: easy / L1 — Callable bond definition
(2, 'Bonds and Debt', 'What feature distinguishes a callable bond from other bonds?', '["It can be converted into equity shares at the holder''s option", "It pays no periodic interest and is issued at a deep discount", "The issuer has the right to redeem the bond before its scheduled maturity date", "The principal is repaid in installments rather than at maturity"]'::jsonb, 2, 'Under ASC 470, a callable bond gives the issuer the right to redeem (call) the bond before its stated maturity date, typically at a specified call price above par. This feature benefits the issuer when interest rates decline, allowing refinancing at lower rates. However, Choice A describes a convertible bond, while Choice B describes a zero-coupon bond. Choice D describes a serial bond.', 'easy', 1),

-- Q16: medium / L3 — Variable-rate bond interest expense and carrying amount behavior
(2, 'Bonds and Debt', 'Anderson Corp. issues $5,000,000 of variable-rate bonds at par with interest reset quarterly based on SOFR plus 200 basis points. After two quarters, SOFR has increased from 3% to 4.5%. Under ASC 835-30, what is the most likely effect on Anderson''s interest expense and the bonds'' carrying amount?', '["Interest expense increases and the carrying amount decreases below par", "Interest expense remains constant and the carrying amount fluctuates with market rates", "Both interest expense and carrying amount remain unchanged from issuance", "Interest expense increases each quarter as rates reset, but the carrying amount remains at par"]'::jsonb, 3, 'Under ASC 835-30, variable-rate bonds adjust their coupon to the current market rate at each reset date. Because the coupon tracks the market rate, the bond''s fair value stays near par and there is no discount or premium to amortize — the carrying amount remains at face value. Interest expense increases or decreases as the variable rate resets. Choice A is incorrect because the carrying amount does not decline for variable-rate bonds at amortized cost.', 'medium', 3),

-- Q17: easy / L2 — Current vs noncurrent classification of serial bonds
(2, 'Bonds and Debt', 'Rankin Corp. has $3,000,000 of serial bonds outstanding on December 31, Year 3. The bonds mature in annual installments of $600,000 each. What amount should Rankin classify as a current liability on its balance sheet?', '["All $3,000,000 as current", "Only $600,000 as current", "The remaining $2,400,000 as current", "No amount as current since serial bonds are noncurrent"]'::jsonb, 1, 'Under ASC 210-10-45, the portion of long-term debt due within one year (or the operating cycle, if longer) must be classified as a current liability. For serial bonds maturing in annual installments of $600,000, the next installment due is current. The remaining $2,400,000 stays in noncurrent liabilities. Choice D is incorrect because serial bonds always require a current/noncurrent split based on maturity timing.', 'easy', 2),

-- Q18: medium / L2 — Detachable warrants vs non-detachable conversion feature (post-ASU 2020-06)
(2, 'Bonds and Debt', 'Meridian Corp. issues $2,000,000 of bonds with detachable stock warrants at 105. Nexus Corp. issues $2,000,000 of convertible bonds with a non-detachable conversion feature at 105. Under ASC 470-20 and ASU 2020-06, how does the initial accounting differ?', '["Meridian allocates proceeds between debt and equity for the warrants; Nexus records the entire amount as a liability with no equity component", "Both companies record the full proceeds as a liability with no equity allocation", "Meridian records the full proceeds as a liability; Nexus bifurcates the conversion feature into equity", "Both companies allocate proceeds between debt and equity using the residual method"]'::jsonb, 0, 'Under ASC 470-20-25-2, bonds with detachable warrants require allocation of proceeds between debt and warrants (equity) based on relative fair values. Under ASU 2020-06, convertible bonds with non-detachable conversion features are recorded entirely as a liability — the conversion option is no longer bifurcated. Choice B is incorrect because detachable warrants still require equity allocation regardless of ASU 2020-06.', 'medium', 2),

-- Q19: hard / L4 — TDR modification: future CFs > carrying amount (new effective rate, no gain)
(2, 'Bonds and Debt', 'Drayton Industries is in financial difficulty and restructures a loan with a carrying amount of $1,250,000 (including $50,000 accrued interest). The restructured terms require total future cash payments of $1,350,000 (principal of $1,100,000 plus reduced interest of $250,000 over 5 years). Under ASC 470-60, how should Drayton account for the restructured loan?', '["Recognize a $100,000 gain and reduce the liability to $1,250,000", "Reduce the carrying amount to $1,100,000 and recognize a gain of $150,000", "Compute a new effective interest rate that equates the $1,250,000 carrying amount to the present value of $1,350,000 in future payments, and recognize no gain", "Record the restructured debt at fair value and recognize the difference as a gain"]'::jsonb, 2, 'Under ASC 470-60-35-6, when total future cash payments under modified terms ($1,350,000) exceed the carrying amount ($1,250,000), no gain is recognized. Instead, a new effective interest rate is computed that equates the carrying amount to the present value of modified future payments. However, Choice A is incorrect because a gain arises only when future CFs are less than the carrying amount, unlike the situation here. Choice D applies ASC 470-50 fair value extinguishment rather than TDR debtor guidance.', 'hard', 4),

-- Q20: medium / L3 — Premium bond mid-life interest expense computation
(2, 'Bonds and Debt', 'Thornton Corp. issues $1,000,000 of 8-year, 9% bonds at $1,046,500 when the market rate is 8%, paying interest annually. At the end of Year 3, the carrying amount is $1,033,900. What is the interest expense for Year 4?', '["$93,510", "$90,000", "$80,000", "$82,712"]'::jsonb, 3, 'Under the effective interest method (ASC 835-30-35), interest expense equals the carrying amount at the beginning of the period multiplied by the market rate at issuance. Year 4 interest expense = $1,033,900 × 8% = $82,712. However, Choice B ($90,000) is incorrect because it represents the cash coupon payment ($1,000,000 × 9%) rather than the expense. For premium bonds, interest expense is always less than the cash payment, with the difference reducing the premium.', 'medium', 3),

-- Q21: hard / L4 — Convertible bond if-converted diluted EPS numerical computation
(2, 'Bonds and Debt', 'Oakridge Inc. reports net income of $900,000 and has 200,000 weighted-average shares outstanding. It also has $1,000,000 of 6% convertible bonds outstanding the entire year, with each $1,000 bond convertible into 30 shares. The tax rate is 25%. Under ASC 260 and ASU 2020-06, what is diluted EPS using the if-converted method?', '["$4.11", "$4.50", "$3.91", "$4.13"]'::jsonb, 0, 'Under ASC 260-10-45, the if-converted method adds back after-tax interest to the numerator and conversion shares to the denominator. After-tax interest = $1,000,000 × 6% × (1 − 0.25) = $45,000. Adjusted NI = $900,000 + $45,000 = $945,000. Conversion shares = 1,000 bonds × 30 = 30,000. Diluted EPS = $945,000 / 230,000 = $4.11. However, Choice B ($4.50) reflects basic EPS rather than diluted, because it omits the if-converted adjustments entirely.', 'hard', 4),

-- Q22: medium / L3 — Premium bond early extinguishment gain with unamortized premium
(2, 'Bonds and Debt', 'Stratford Corp. decides to retire its premium bonds early by purchasing them on the open market for $3,030,000. The bonds originally had a $3,000,000 face value and currently carry $72,000 of unamortized premium on the books. Under ASC 470-50, what is the result of this extinguishment?', '["Loss of $30,000", "Gain of $42,000", "Loss of $42,000", "Gain of $72,000"]'::jsonb, 1, 'Under ASC 470-50-40, the gain or loss equals the carrying amount minus the reacquisition price. Carrying amount = $3,000,000 + $72,000 premium = $3,072,000. Reacquisition price = $3,030,000. Gain = $3,072,000 − $3,030,000 = $42,000. The unamortized premium must be included in the carrying amount. Choice A ($30,000 loss) erroneously compares only the face value to the purchase price while ignoring the premium component.', 'medium', 3),

-- Q23: easy / L1 — Stated rate (coupon rate) definition
(2, 'Bonds and Debt', 'What does the stated rate (coupon rate) on a bond represent?', '["The yield investors earn based on the bond''s market price", "The rate used to discount future cash flows to determine issue price", "The rate of return required by the market at the date of issuance", "The contractual rate applied to the bond''s face value to determine periodic cash interest payments"]'::jsonb, 3, 'Under ASC 835-30, the stated rate (also called the coupon rate or nominal rate) is the contractual rate printed on the bond that determines periodic cash interest payments when applied to the face (par) value. It remains fixed over the bond''s life. However, Choices A and C describe the market (effective) rate, which reflects investor-required returns and determines the bond''s issue price rather than the cash coupon.', 'easy', 1),

-- Q24: easy / L1 — Secured bond characteristics
(2, 'Bonds and Debt', 'Which characteristic is unique to a secured bond?', '["It can be redeemed before maturity at the issuer''s option", "It is backed only by the issuer''s general creditworthiness", "Specific assets are pledged as collateral for the obligation", "It pays interest only upon maturity along with principal"]'::jsonb, 2, 'Under ASC 470, a secured bond is backed by specific assets (such as real property, equipment, or receivables) pledged as collateral. If the issuer defaults, the bondholder has a claim on the pledged assets. In contrast, Choice B describes an unsecured bond (debenture) rather than a secured instrument. Choice A describes a callable bond feature, while Choice D describes a zero-coupon bond.', 'easy', 1),

-- Q25: medium / L3 — ASC 405-20 legal defeasance conditions
(2, 'Bonds and Debt', 'Ellison Corp. places $4,000,000 of U.S. Treasury securities into an irrevocable trust that will generate cash flows sufficient to service and retire its $4,000,000 bonds payable. Ellison has not been legally released by its bondholders. Under ASC 405-20, should Ellison derecognize the bonds payable?', '["No — the debtor must be legally released from the obligation, and an irrevocable trust alone is insufficient", "Yes — placing sufficient assets in an irrevocable trust always qualifies as an extinguishment", "Yes — matching the trust''s cash flows to the debt payments constitutes a legal defeasance", "No — in-substance defeasance is prohibited entirely under U.S. GAAP"]'::jsonb, 0, 'Under ASC 405-20-40-1, a debtor may derecognize a liability only if (a) the debtor pays the creditor and is relieved, or (b) the debtor is legally released from being the primary obligor. Placing assets in an irrevocable trust (in-substance defeasance) does not qualify unless the debtor obtains legal release. Choice D is incorrect because legal defeasance (with creditor release) is permitted; only in-substance defeasance without legal release fails to qualify.', 'medium', 3),

-- Q26: medium / L3 — Current refunding at maturity (no gain or loss)
(2, 'Bonds and Debt', 'Morrison Inc. redeems its outstanding $6,000,000 of 7% bonds at maturity using proceeds from a new 5% bond issue. The old bonds have a carrying amount equal to face value with no remaining premium or discount. Under ASC 470-50, what gain or loss does Morrison recognize on the retirement of the old bonds?', '["A gain equal to the present value of the interest savings from the lower rate", "No gain or loss — the bonds are retired at their carrying amount equal to face value", "A loss equal to the difference in coupon rates times the face value", "A gain of $120,000 representing one year of interest savings"]'::jsonb, 1, 'Under ASC 470-50, gain or loss on extinguishment equals the reacquisition price minus the carrying amount. At maturity, the reacquisition price equals face value and the carrying amount also equals face value (any premium or discount is fully amortized). No gain or loss arises. The new bond issuance is a separate financing transaction. However, Choice A is incorrect because future interest savings are not recognized as a gain at the refinancing date.', 'medium', 3),

-- Q27: medium / L2 — Accrued interest paid by bond purchaser between interest dates
(2, 'Bonds and Debt', 'On May 1, Year 1, Fielding Corp. purchases $1,000,000 face value of 6% bonds at par in the secondary market. The bonds pay interest semiannually on January 1 and July 1. How much accrued interest does Fielding pay the seller at purchase?', '["$30,000", "$10,000", "$15,000", "$20,000"]'::jsonb, 3, 'Under ASC 835-30, when bonds are purchased between interest dates, the buyer pays accrued interest from the last payment date to the purchase date. Accrued interest from January 1 to May 1 = 4 months. Amount = $1,000,000 × 6% × 4/12 = $20,000. However, Choice A ($30,000) is incorrect because it represents a full semiannual payment (6 months) rather than the 4-month accrual. Fielding recovers the accrued amount when the next full coupon is received on July 1.', 'medium', 2),

-- Q28: medium / L2 — Premium bond total interest cost (less than coupon payments)
(2, 'Bonds and Debt', 'Sinclair Corp. issues $4,000,000 of 10-year, 8% bonds at $4,280,000. Interest is paid annually. What is the total interest cost to Sinclair over the life of the bonds?', '["$3,200,000", "$3,480,000", "$2,920,000", "$2,720,000"]'::jsonb, 2, 'Under ASC 835-30, total interest cost on a premium bond equals total cash coupon payments minus the premium received. Total coupons = $4,000,000 × 8% × 10 = $3,200,000. Premium = $4,280,000 − $4,000,000 = $280,000. Total interest cost = $3,200,000 − $280,000 = $2,920,000. However, Choice A ($3,200,000) is incorrect because it includes only coupon payments while ignoring the premium that reduces the issuer''s net borrowing cost.', 'medium', 2),

-- Q29: medium / L3 — Effective interest premium bond: declining interest expense pattern
(2, 'Bonds and Debt', 'Northfield Corp. issues $2,000,000 of 6-year, 7% bonds at $2,093,000 when the market rate is 6%, paying interest annually. In Year 1, interest expense is $125,580 and premium amortization is $14,420. In Year 2, interest expense is $124,715. By how much does interest expense decline from Year 1 to Year 2, and why does this pattern occur?', '["$865, because the effective interest method applies a constant market rate to a declining carrying amount as the premium is amortized", "$865, because the stated rate decreases each year under premium amortization", "$14,420, because premium amortization replaces interest expense over time", "$0 — interest expense is constant under the effective interest method"]'::jsonb, 0, 'Under ASC 835-30-35, the effective interest method applies the market rate (6%) to the carrying amount each period. As premium amortization reduces the carrying amount, interest expense declines: Year 1 = $125,580, Year 2 = $124,715, a decline of $865. The stated rate remains fixed at 7% for cash payment purposes. However, Choice D is incorrect because constant expense describes the straight-line method rather than the effective interest method.', 'medium', 3),

-- Q30: hard / L4 — Partial early extinguishment of bonds (proportionate allocation)
(2, 'Bonds and Debt', 'Whitmore Corp. has $10,000,000 of 6% bonds outstanding with a carrying amount of $9,820,000 (reflecting $180,000 of unamortized discount). Whitmore calls 40% of the bonds at 102. Under ASC 470-50, what loss should Whitmore recognize on the partial extinguishment?', '["$180,000", "$152,000", "$48,000", "$108,000"]'::jsonb, 1, 'Under ASC 470-50-40, partial extinguishment requires proportionate allocation of the carrying amount. The 40% portion: face = $4,000,000, proportionate carrying amount = $9,820,000 × 40% = $3,928,000, call price = $4,000,000 × 102% = $4,080,000. Loss = $4,080,000 − $3,928,000 = $152,000. Choice A ($180,000) incorrectly uses the full unamortized discount rather than the 40% proportionate share.', 'hard', 4)
;

COMMIT;
