-- Migration: Question generation — FAR batch 66 (30 questions)
-- Date: 2026-03-03
-- Topic: Income Taxes
-- Difficulty: 9E / 15M / 6H
-- Bloom's: L1:8 / L2:9 / L3:8 / L4:5

BEGIN;

INSERT INTO questions (section_id, topic, stem, choices, correct_index, explanation, difficulty, cognitive_level)
VALUES

-- Q1: hard / L4 — Goodwill tax amortization creating indefinite-lived DTL
(2, 'Income Taxes', 'Becker Industries acquired $1,500,000 of goodwill in a taxable business combination. For tax purposes, goodwill is amortized over 15 years. Under GAAP, goodwill is not amortized but is tested annually for impairment. After three years with no impairment recorded, the enacted tax rate is 21%. What deferred tax liability related to goodwill should Becker report at the end of Year 3?', '["$63,000", "$105,000", "$315,000", "$21,000"]'::jsonb, 0, 'Under ASC 740-10-25-3, a temporary difference arises when tax-deductible goodwill amortization reduces the tax basis below the book carrying amount. After three years, cumulative tax amortization is $300,000 ($1,500,000 ÷ 15 × 3), creating a taxable temporary difference of $300,000 and a DTL of $300,000 × 21% = $63,000. Option B incorrectly uses five years of amortization rather than three.', 'hard', 4),

-- Q2: hard / L4 — Valuation allowance sourcing: NOL-related vs OCI-related DTA
(2, 'Income Taxes', 'Weston Corp. has a deferred tax asset of $280,000 from net operating loss carryforwards and a separate DTA of $42,000 from unrealized losses on available-for-sale debt securities recorded in OCI. Management establishes a full valuation allowance against the NOL-related DTA but determines the AFS-related DTA requires no allowance. What is the increase to income tax expense from the valuation allowance?', '["$322,000", "$280,000", "$42,000", "$238,000"]'::jsonb, 1, 'Under ASC 740-20-45-11, the valuation allowance for the NOL carryforward DTA, which originated from continuing operations, is charged to income tax expense. The AFS-related DTA requires no allowance in this scenario, so it has no effect. The total increase to income tax expense is $280,000. Option A incorrectly adds the AFS DTA amount, which is not subject to an allowance here.', 'hard', 4),

-- Q3: hard / L4 — Multi-jurisdiction combined deferred tax rate
(2, 'Income Taxes', 'Redfield Corp. operates in a single state with a 5% income tax rate. The federal rate is 21%, and state income taxes are deductible for federal purposes. Redfield has a taxable temporary difference of $400,000 from accelerated depreciation. What is the combined federal and state deferred tax liability?', '["$84,000", "$104,000", "$99,800", "$20,000"]'::jsonb, 2, 'Under ASC 740-10-10-3, deferred taxes must reflect both federal and state tax consequences. When state taxes are deductible for federal purposes, the combined rate is state + federal × (1 − state) = 5% + 21% × 95% = 24.95%. The DTL is $400,000 × 24.95% = $99,800. Option B incorrectly adds the rates (26%) without adjusting for the federal deductibility of state taxes.', 'hard', 4),

-- Q4: medium / L2 — Stock-based compensation DTA timing
(2, 'Income Taxes', 'Dalton Inc. granted 10,000 stock options with a total grant-date fair value of $300,000, vesting over three years. In Year 1, Dalton records $100,000 of compensation expense for book purposes. No options have been exercised, and no tax deduction is available until exercise. The tax rate is 21%. What deferred tax asset should Dalton record at the end of Year 1?', '["$63,000", "$100,000", "$0", "$21,000"]'::jsonb, 3, 'Under ASC 740-10-25-47 and ASC 718-10-25, a DTA is recognized as compensation cost is recorded for book purposes, even though the tax deduction occurs at exercise. The DTA equals cumulative book expense times the enacted rate: $100,000 × 21% = $21,000. Option C is incorrect because a DTA is recognized for the future deductible amount when book expense is recorded, not deferred until the tax deduction becomes available.', 'medium', 2),

-- Q5: easy / L1 — Definition of enacted tax rate
(2, 'Income Taxes', 'Under ASC 740, which rate is used to measure deferred tax assets and liabilities?', '["The rate proposed in pending tax legislation", "The rate signed into law expected to apply when the temporary difference reverses", "The company''s current-year effective tax rate", "A weighted average of all currently enacted rates"]'::jsonb, 1, 'Under ASC 740-10-25-2, deferred tax assets and liabilities are measured using the enacted tax rate expected to apply to taxable income in the periods when temporary differences reverse. Enacted means signed into law — proposed rates or rates passed by only one chamber do not qualify. Option C confuses the effective rate (which includes permanent differences) with the enacted statutory rate.', 'easy', 1),

-- Q6: medium / L2 — Credit loss allowance (CECL) creating DTA
(2, 'Income Taxes', 'Foster Bank records a $2,400,000 allowance for credit losses under ASC 326 (CECL) at year-end. For tax purposes, bad debts are deductible only when specifically charged off. During the year, $600,000 of loans were written off. The enacted tax rate is 21%. What deferred tax asset should Foster record related to the remaining allowance?', '["$504,000", "$378,000", "$126,000", "$630,000"]'::jsonb, 0, 'Under ASC 740-10-25-20, the $2,400,000 credit loss allowance is a future deductible temporary difference because it is expensed for book purposes but not deductible for tax until loans are charged off. The DTA is $2,400,000 × 21% = $504,000. Option B incorrectly subtracts the $600,000 already written off, but those amounts have been deducted for both book and tax and are no longer part of the temporary difference.', 'medium', 2),

-- Q7: medium / L3 — Interest and penalties on UTPs: policy election
(2, 'Income Taxes', 'Hayward Corp. accrues $120,000 as an unrecognized tax benefit liability for an uncertain position. In Year 2, $18,000 of interest and $5,000 of penalties accumulate on this position. Hayward''s accounting policy classifies interest and penalties as income tax expense. Under ASC 740-10-50-15, what disclosure is required regarding these amounts?', '["Only the interest must be disclosed separately from penalties", "The amounts must be reclassified to interest expense and other expense", "The company must disclose its policy of classifying interest and penalties within income tax expense", "No disclosure is required because the amounts are below the recognition threshold"]'::jsonb, 2, 'Under ASC 740-10-50-15, an entity must disclose its accounting policy for classifying interest and penalties related to uncertain tax positions. ASC 740 permits a policy election: they may be classified in income tax expense or as interest expense and other expense. The chosen policy must be disclosed. Option B is incorrect because the classification is an accounting policy choice, not a mandatory reclassification.', 'medium', 3),

-- Q8: medium / L2 — Accrued vacation/compensated absences creating DTA
(2, 'Income Taxes', 'Langley Corp. has an accrued vacation liability of $180,000 at year-end. Under the company''s policy, vacation pay is deductible for tax purposes only when paid. During the year, $140,000 in vacation pay was distributed. The enacted tax rate is 21%. What deferred tax asset should Langley report related to the accrued vacation liability?', '["$29,400", "$37,800", "$67,200", "$0"]'::jsonb, 1, 'Under ASC 740-10-25-20, the $180,000 accrued vacation liability represents a future deductible temporary difference because it is expensed for book purposes but deductible for tax only when paid. The DTA is $180,000 × 21% = $37,800. Option A incorrectly applies the rate to the $140,000 already paid, which has been deducted for both book and tax and is no longer a temporary difference.', 'medium', 2),

-- Q9: medium / L3 — Section 174 R&D capitalization creating DTA
(2, 'Income Taxes', 'Newkirk Labs spent $500,000 on research and development in Year 1. Under GAAP, the full amount is expensed immediately. For federal tax purposes under Section 174, the costs must be capitalized and amortized over 5 years ($100,000 per year). The tax rate is 21%. What deferred tax effect should Newkirk record in Year 1?', '["A deferred tax liability of $84,000", "A deferred tax asset of $105,000", "A deferred tax liability of $105,000", "A deferred tax asset of $84,000"]'::jsonb, 3, 'Under ASC 740-10-25-20, when GAAP expense ($500,000) exceeds the tax deduction ($100,000 amortization), taxable income exceeds book income by $400,000, creating a future deductible temporary difference. The DTA is $400,000 × 21% = $84,000. Option A incorrectly classifies this as a DTL; because more tax deductions will occur in future years, the difference creates future tax savings, not future obligations.', 'medium', 3),

-- Q10: medium / L2 — Prepaid insurance creating DTL
(2, 'Income Taxes', 'Oakridge Inc. pays $240,000 for a 3-year insurance policy on July 1, Year 1. For tax purposes, the full $240,000 is deductible in Year 1. For book purposes, only $40,000 is expensed in Year 1 (6 months of the annual amount). The enacted tax rate is 21%. What deferred tax effect should Oakridge record at December 31, Year 1?', '["A deferred tax liability of $42,000", "A deferred tax asset of $42,000", "A deferred tax liability of $50,400", "A deferred tax asset of $50,400"]'::jsonb, 0, 'Under ASC 740-10-25-20, when the tax deduction ($240,000) exceeds the book expense ($40,000), the $200,000 taxable temporary difference creates a DTL because future book expense will exceed future tax deductions. The DTL is $200,000 × 21% = $42,000. Option C incorrectly applies the rate to the full $240,000 premium rather than the $200,000 temporary difference.', 'medium', 2),

-- Q11: easy / L1 — ASC 740 prohibition on discounting deferred taxes
(2, 'Income Taxes', 'Under ASC 740, how should deferred tax assets and liabilities be measured with respect to the time value of money?', '["They should be discounted to present value using the risk-free rate", "They should be discounted using the entity''s incremental borrowing rate", "They are reported at undiscounted amounts without present-value adjustment", "Discounting is required only for differences expected to reverse after five years"]'::jsonb, 2, 'ASC 740-10-30-8 explicitly prohibits discounting deferred tax assets and liabilities to present value. They are reported at the nominal amounts computed by multiplying temporary differences by the enacted tax rate, regardless of when the differences reverse. Option A is incorrect because no present-value adjustment is permitted under ASC 740, regardless of the discount rate used.', 'easy', 1),

-- Q12: medium / L3 — Installment sale creating DTL
(2, 'Income Taxes', 'Pennington Corp. sells equipment with a book value of $200,000 for $500,000 on an installment basis. The buyer pays $100,000 at closing, with $400,000 due over four years. Pennington recognizes the full $300,000 gain for book purposes in Year 1 but elects the installment method for tax. The tax rate is 21%. What deferred tax liability should Pennington record in Year 1?', '["$63,000", "$50,400", "$12,600", "$84,000"]'::jsonb, 1, 'Under ASC 740-10-25-20, the full $300,000 book gain minus the $60,000 tax gain (gross profit ratio of 60% × $100,000 collected) yields a $240,000 taxable temporary difference. The DTL is $240,000 × 21% = $50,400. Option A incorrectly treats the entire $300,000 book gain as the temporary difference, ignoring the $60,000 portion already recognized for tax in Year 1.', 'medium', 3),

-- Q13: easy / L1 — Deferred tax benefit definition
(2, 'Income Taxes', 'Under ASC 740, what is a deferred tax benefit?', '["A decrease in DTLs or an increase in DTAs during the period that reduces income tax expense", "An additional tax refund received from the taxing authority", "The current-year tax deduction from a net operating loss carryback", "The cash tax savings realized when a temporary difference reverses"]'::jsonb, 0, 'Under ASC 740-10-45-4, a deferred tax benefit reduces total income tax expense and arises when deferred tax liabilities decrease or deferred tax assets increase during the period. It represents anticipated future tax savings on an accrual basis. Option D confuses the deferred tax benefit (an accrual-basis concept) with the actual cash tax savings, which may occur in a different period.', 'easy', 1),

-- Q14: easy / L1 — OCI items receive their own tax allocation
(2, 'Income Taxes', 'Under ASC 740, how is the tax effect of items reported in other comprehensive income (OCI) presented in the financial statements?', '["Combined with income tax expense from continuing operations", "Reported as a separate line item on the income statement", "Excluded from financial reporting until realized in earnings", "Allocated directly to each OCI component so items are reported net of tax"]'::jsonb, 3, 'Under ASC 740-20-45-2, intraperiod tax allocation requires that the tax effect of OCI items be allocated directly to those items, so each OCI component is presented net of its own tax effect. The tax on OCI items does not flow through income tax expense from continuing operations. Option A would distort both the income statement and the OCI presentation.', 'easy', 1),

-- Q15: medium / L3 — Change in valuation allowance affecting income tax expense
(2, 'Income Taxes', 'Quincy Corp. had a valuation allowance of $150,000 against its deferred tax assets at the beginning of Year 2. During Year 2, Quincy secured a major long-term contract, and management now determines that only $40,000 of the valuation allowance is needed. What is the effect on Year 2 income tax expense?', '["Increase of $110,000", "Decrease of $40,000", "Decrease of $110,000", "Decrease of $150,000"]'::jsonb, 2, 'Under ASC 740-10-30-5, changes in the valuation allowance are recognized in income tax expense from continuing operations. Reducing the allowance from $150,000 to $40,000 releases $110,000, decreasing income tax expense by that amount and reflecting the increased likelihood that the DTAs will be realized. Option D incorrectly eliminates the entire original allowance rather than adjusting to the $40,000 balance still required.', 'medium', 3),

-- Q16: medium / L2 — Asset impairment creating DTA
(2, 'Income Taxes', 'Sheffield Corp. records a $350,000 impairment loss on a long-lived asset, reducing the book carrying amount from $700,000 to $350,000. For tax purposes, no deduction is allowed until the asset is sold; the tax basis remains $700,000. The enacted tax rate is 21%. What deferred tax effect should Sheffield record?', '["A deferred tax asset of $73,500", "A deferred tax liability of $73,500", "A deferred tax asset of $147,000", "No deferred tax effect because impairment is a permanent difference"]'::jsonb, 0, 'Under ASC 740-10-25-20, the book impairment reduces the carrying amount below the tax basis by $350,000, creating a deductible temporary difference and a DTA of $350,000 × 21% = $73,500. The future tax deduction at disposal will exceed the remaining book basis. Option D is incorrect because impairment losses generating future tax deductions are temporary, not permanent, differences.', 'medium', 2),

-- Q17: easy / L1 — WUCC mnemonic for DTA-creating items
(2, 'Income Taxes', 'The mnemonic WUCC identifies common items that create deferred tax assets. What does WUCC stand for?', '["Write-downs, Unrealized gains, Credits, Cash payments", "Warranties, Unearned revenue, Compensation, Credit losses", "Write-offs, Uncertain positions, Carryforwards, Contingencies", "Withholdings, Unfunded pensions, Capitalized costs, Contributions"]'::jsonb, 1, 'The WUCC mnemonic stands for Warranties (accrued), Unearned revenue (taxed on receipt), Compensation (accrued), and Credit losses (estimated). Each creates a deferred tax asset because the expense is recognized for book purposes before it becomes deductible for tax, resulting in future tax savings when the amounts reverse. Option A incorrectly includes items that do not consistently create DTAs.', 'easy', 1),

-- Q18: hard / L4 — Subsequent recognition of previously unrecognized UTP
(2, 'Income Taxes', 'Thorne Corp. has carried an unrecognized tax benefit liability of $84,000 for three years related to a tax position that did not meet the more-likely-than-not threshold. In the current year, a favorable court ruling on a substantially similar case causes Thorne to conclude the position now meets the recognition threshold. Under Step 2, the full $84,000 tax benefit has greater than 50% cumulative likelihood. What is the effect on current-year financial statements?', '["Debit Retained Earnings $84,000, Credit Unrecognized Tax Benefit Liability $84,000", "No financial statement effect until the statute of limitations expires", "Debit Unrecognized Tax Benefit Liability $84,000, Credit Cash $84,000", "Debit Unrecognized Tax Benefit Liability $84,000, Credit Income Tax Expense $84,000"]'::jsonb, 3, 'Under ASC 740-10-25-9 and 740-10-35-2, when a previously unrecognized tax benefit is subsequently recognized because new evidence satisfies the more-likely-than-not threshold, the liability is removed and the benefit reduces income tax expense in the current period. Option A is incorrect because the recognition flows through the income statement, not directly through retained earnings.', 'hard', 4),

-- Q19: hard / L3 — Scheduling reversals with different enacted rates per year
(2, 'Income Taxes', 'Granger Corp. has a taxable temporary difference of $600,000 from accelerated depreciation expected to reverse as follows: $200,000 in Year 2, $250,000 in Year 3, and $150,000 in Year 4. Currently enacted rates are 21% for Year 2 and 25% for Years 3 and 4 (enacted but effective in future years). What DTL should Granger report at the end of Year 1?', '["$126,000", "$150,000", "$142,000", "$138,000"]'::jsonb, 2, 'Under ASC 740-10-25-23, when different enacted rates apply to different reversal periods, the DTL must be computed by applying each year''s rate to its reversal amount: ($200,000 × 21%) + ($250,000 × 25%) + ($150,000 × 25%) = $42,000 + $62,500 + $37,500 = $142,000. Option A incorrectly applies 21% to all years, ignoring the enacted rate change effective in Years 3 and 4.', 'hard', 3),

-- Q20: medium / L3 — Excess tax benefit on stock compensation (ASU 2016-09)
(2, 'Income Taxes', 'Morrison Corp. recognized $200,000 of book compensation expense for stock options over the vesting period. When employees exercised the options, the tax deduction based on intrinsic value was $320,000. The enacted tax rate is 21%. Under ASU 2016-09, how should the excess tax benefit be reported?', '["Recognized as a $25,200 reduction of income tax expense", "Recognized as a $25,200 increase to additional paid-in capital", "Recognized as a $120,000 reduction of income tax expense", "Recognized as a $25,200 increase to retained earnings"]'::jsonb, 0, 'Under ASU 2016-09 (ASC 718-740-25-10), all excess tax benefits from stock compensation are recognized in income tax expense. The excess benefit is ($320,000 − $200,000) × 21% = $25,200, recorded as a reduction of income tax expense. Option B reflects the pre-ASU 2016-09 treatment of crediting APIC, which is no longer applicable under current guidance.', 'medium', 3),

-- Q21: hard / L4 — Interim period estimated annual effective tax rate
(2, 'Income Taxes', 'Porter Corp. estimates its annual effective tax rate (AETR) at 28% at the end of Q1 and reports Q1 pretax income of $400,000. By the end of Q2, cumulative year-to-date pretax income is $900,000 and the revised AETR estimate is 26%. What income tax expense should Porter report for the second quarter alone?', '["$130,000", "$140,000", "$112,000", "$122,000"]'::jsonb, 3, 'Under ASC 740-270-30-2, interim tax expense is computed by applying the estimated AETR to cumulative year-to-date pretax income, then subtracting tax already recognized. Cumulative tax through Q2 is $900,000 × 26% = $234,000, less $112,000 recognized in Q1 ($400,000 × 28%), yielding Q2 expense of $122,000. Option A incorrectly applies the 26% AETR to Q2 income alone without the cumulative catch-up adjustment.', 'hard', 4),

-- Q22: easy / L2 — Restructuring charge creating DTA
(2, 'Income Taxes', 'Richfield Corp. accrues a $300,000 restructuring liability for employee severance in Year 1. The severance payments will be made in Year 2, at which time they become deductible for tax purposes. The enacted tax rate is 21%. What deferred tax effect should Richfield record in Year 1?', '["A deferred tax liability of $63,000", "A deferred tax asset of $63,000", "No deferred tax effect because restructuring charges are permanent differences", "A deferred tax asset of $300,000"]'::jsonb, 1, 'Under ASC 740-10-25-20, the $300,000 accrued restructuring liability creates a deductible temporary difference because the expense is recognized for book purposes in Year 1 but deductible for tax only when paid in Year 2. The DTA is $300,000 × 21% = $63,000. Option C is incorrect because restructuring charges that will be tax-deductible when paid are temporary differences, not permanent ones.', 'easy', 2),

-- Q23: medium / L2 — Operating lease DTA/DTL offset at inception (ASC 842)
(2, 'Income Taxes', 'Saunders Corp. enters into a 5-year operating lease and recognizes a right-of-use asset of $450,000 and a lease liability of $450,000 at inception under ASC 842. For tax purposes, no asset or liability is recognized; only the annual lease payments are deductible. The enacted tax rate is 21%. What is the net deferred tax effect at inception?', '["A net deferred tax liability of $94,500", "A net deferred tax asset of $94,500", "A net deferred tax effect of zero", "No deferred tax is recognized because operating leases are off-balance-sheet for tax"]'::jsonb, 2, 'Under ASC 740-10-25-20, the ROU asset (book $450,000, tax basis $0) creates a DTL of $94,500, while the lease liability (book $450,000, tax basis $0) creates an offsetting DTA of $94,500. At inception these net to zero. As the lease progresses, the asset and liability may amortize at different rates, creating a temporary net difference. Option A considers only the ROU asset without the offsetting DTA from the liability.', 'medium', 2),

-- Q24: medium / L2 — NOL carryforward under current law (no carryback, 80% limitation)
(2, 'Income Taxes', 'Tanner Corp. reports a net operating loss of $800,000 in Year 3. Under current federal law, NOLs may not be carried back but may be carried forward indefinitely, subject to an 80% taxable income limitation per year. The enacted rate is 21%, and management expects sufficient future income to fully utilize the NOL. What deferred tax asset should Tanner record?', '["$168,000", "$134,400", "$800,000", "$0"]'::jsonb, 0, 'Under ASC 740-10-25-30, a DTA is recognized for NOL carryforwards at the enacted rate. The DTA is $800,000 × 21% = $168,000. The 80% limitation restricts annual usage but does not reduce the total DTA because the NOL may be carried forward indefinitely until fully utilized. Option B incorrectly applies the 80% cap to the DTA calculation rather than treating it as a timing constraint on utilization.', 'medium', 2),

-- Q25: medium / L3 — Asset retirement obligation deferred tax
(2, 'Income Taxes', 'Underwood Mining records an asset retirement obligation of $500,000 in Year 1 under ASC 410. By Year 3, the ARO liability has accreted to $560,000 and the capitalized asset retirement cost has been depreciated to a net book amount of $350,000. For tax purposes, no deduction occurs until retirement. The tax rate is 21%. What is the net deferred tax asset related to the ARO at Year 3?', '["$105,000", "$44,100", "$117,600", "$73,500"]'::jsonb, 1, 'Under ASC 740-10-25-20, the ARO creates two temporary differences: the $560,000 liability (future deductible) and the $350,000 remaining capitalized cost (future taxable since tax basis is zero). The net deductible temporary difference is $560,000 − $350,000 = $210,000, yielding a DTA of $210,000 × 21% = $44,100. Option C considers only the liability without offsetting the asset''s temporary difference.', 'medium', 3),

-- Q26: medium / L2 — Tax credit carryforward DTA (face value, not rate-adjusted)
(2, 'Income Taxes', 'Vernon Corp. has $250,000 of unused general business tax credits that may be carried forward for 20 years. Management expects sufficient taxable income to utilize the credits within five years. Under ASC 740, how should Vernon account for the unused credits?', '["Record a liability of $250,000 for unearned credits", "Disclose the credits in footnotes but record no DTA", "Record a DTA of $52,500 by multiplying the credits by the 21% enacted rate", "Record a deferred tax asset of $250,000"]'::jsonb, 3, 'Under ASC 740-10-25-30, tax credit carryforwards are recognized as deferred tax assets at face value because credits reduce tax liability dollar-for-dollar, unlike NOL carryforwards which must be multiplied by the tax rate. The DTA equals the $250,000 credit amount, subject to a valuation allowance if realization is not more likely than not. Option C incorrectly applies the tax rate, which is appropriate only for NOLs.', 'medium', 2),

-- Q27: easy / L1 — DTA vs current tax receivable distinction
(2, 'Income Taxes', 'Under ASC 740, what distinguishes a deferred tax asset from a current income tax receivable?', '["A DTA represents future tax benefits from temporary differences or carryforwards, while a receivable represents an overpayment of current taxes", "A DTA is always noncurrent while a receivable is always current", "A DTA must be offset against DTLs while a receivable cannot be offset", "A DTA always requires a valuation allowance while a receivable requires no allowance"]'::jsonb, 0, 'Under ASC 740-10-25-2, a deferred tax asset arises from deductible temporary differences or carryforwards and represents expected future tax savings, whereas a current income tax receivable results from an overpayment or refund claim on taxes already assessed. Option D is only partially true — DTAs may need a valuation allowance, but this does not define the fundamental distinction between future benefits and current overpayments.', 'easy', 1),

-- Q28: medium / L3 — Percentage-of-completion vs completed-contract DTL
(2, 'Income Taxes', 'Wallace Construction uses the percentage-of-completion method for a $3,000,000 contract with expected profit of $600,000. At year-end, the project is 40% complete and $240,000 of profit is recognized for book purposes. For tax purposes, Wallace uses the completed-contract method and recognizes no profit until the project is finished. The tax rate is 21%. What deferred tax effect arises?', '["A deferred tax asset of $50,400", "A deferred tax liability of $126,000", "A deferred tax liability of $50,400", "No deferred tax effect until contract completion"]'::jsonb, 2, 'Under ASC 740-10-25-20, recognizing $240,000 of profit for book while deferring it entirely for tax creates a $240,000 taxable temporary difference, producing a DTL of $240,000 × 21% = $50,400 because the profit will be taxed upon completion. Option B incorrectly applies the tax rate to total contract revenue of $600,000 rather than the $240,000 profit difference between book and tax.', 'medium', 3),

-- Q29: easy / L1 — DR DIGS mnemonic for DTL-creating items
(2, 'Income Taxes', 'The mnemonic DR DIGS identifies common items that create deferred tax liabilities. What does DR DIGS represent?', '["Dividends, Reserves, Deferrals, Interest, Gains, Settlements", "Depreciation, Receivables, Discounts, Interest, Gross-up, Surcharges", "Deferrals, Reductions, Distributions, Income, Grants, Subsidies", "Depreciation, Rent, Depletion, Interest on bonds, Goodwill amortization, Start-up costs"]'::jsonb, 3, 'The DR DIGS mnemonic stands for Depreciation, Rent, Depletion, Interest (on bonds), Goodwill (amortization/impairment), and Start-up costs. These items commonly create deferred tax liabilities because the tax deduction exceeds the book expense in early periods, with the difference reversing in future years. Option B incorrectly identifies the components of the mnemonic.', 'easy', 1),

-- Q30: easy / L1 — GAAP enacted rate vs IFRS substantively enacted rate
(2, 'Income Taxes', 'Under U.S. GAAP (ASC 740), deferred taxes are measured using the enacted tax rate. How does this compare to the IFRS requirement under IAS 12?', '["IFRS prohibits deferred tax recognition entirely", "IFRS allows rates that are enacted or substantively enacted by the reporting date", "IFRS requires discounting deferred taxes to present value", "IFRS uses the entity''s marginal tax rate rather than the statutory rate"]'::jsonb, 1, 'Under ASC 740-10-25-2, U.S. GAAP requires rates formally enacted (signed into law). IAS 12.47 permits rates that are enacted or substantively enacted (e.g., passed by the legislature but awaiting formal assent), a lower threshold. Option C is incorrect because IAS 12, like ASC 740, generally does not permit discounting of deferred taxes. This is a key GAAP-IFRS difference tested on the CPA exam.', 'easy', 1)
;

COMMIT;
