-- Migration: Question generation — FAR batch 67 (30 questions)
-- Date: 2026-03-03
-- Topic: Not-for-Profit Accounting
-- Difficulty: 9E / 15M / 6H
-- Bloom's: L1:8 / L2:9 / L3:8 / L4:5

BEGIN;

INSERT INTO questions (section_id, topic, stem, choices, correct_index, explanation, difficulty, cognitive_level)
VALUES

-- Q1: easy / L1 — Board-designated net assets classification
(2, 'Not-for-Profit Accounting', 'Under ASC 958, how are board-designated net assets classified on an NFP''s statement of financial position?', '["Net assets without donor restrictions", "Net assets with donor restrictions", "A separate third category of net assets", "Liabilities until the designation is spent"]'::jsonb, 0, 'Under ASC 958-210-45, board-designated funds are internally restricted by the governing board, not by donors. Because the board can reverse its own designation at any time, these amounts remain classified as net assets without donor restrictions. Unlike donor-imposed restrictions, board designations do not trigger the "with donor restrictions" classification and can be reversed without external approval.', 'easy', 1),

-- Q2: hard / L4 — Variance power intermediary recognition
(2, 'Not-for-Profit Accounting', 'The Maplewood Foundation receives $1,000,000 from a donor who specifies that the funds be transferred to Crossroads Outreach, a separate NFP. However, the gift agreement grants Maplewood the unilateral right to redirect the funds to any organization serving the same community. When evaluating whether Maplewood is an agent or a donee, which factor is most determinative under ASC 958-605?', '["Whether Maplewood charges an administrative fee for processing the gift", "Whether Maplewood has variance power to redirect the contribution to an unrelated beneficiary", "Whether Crossroads Outreach has already been notified of the pending transfer", "Whether the donor claimed a charitable deduction on the gift to Maplewood"]'::jsonb, 1, 'Under ASC 958-605-25-24, when a recipient NFP has variance power—the unilateral ability to redirect transferred assets to another beneficiary—it is treated as a donee rather than an agent. Maplewood recognizes the $1,000,000 as contribution revenue because variance power indicates economic substance. However, without variance power, Maplewood would record a liability as an agent, not revenue.', 'hard', 4),

-- Q3: medium / L3 — Joint costs allocation criteria
(2, 'Not-for-Profit Accounting', 'Hope Rising Ministries conducts a $75,000 direct-mail campaign that includes an appeal for donations alongside educational information about homelessness prevention. Management must determine whether the $75,000 in costs can be allocated between fundraising and program activities. Under ASC 958-720, which set of criteria must ALL be met to allocate joint costs?', '["The campaign must generate donations exceeding its costs", "A qualified independent appraiser must approve the allocation methodology", "The educational content must comprise at least 50% of the mailing", "Purpose, audience, and content criteria must all be satisfied"]'::jsonb, 3, 'Under ASC 958-720-45-1, joint costs of activities that include a fundraising appeal may be allocated between fundraising and program functions only if the purpose, audience, and content criteria are all met. However, if any single criterion fails, the entire cost must be charged to fundraising rather than being split. There is no minimum content percentage or revenue threshold requirement for allocation eligibility.', 'medium', 3),

-- Q4: hard / L4 — NFP mergers carryover method
(2, 'Not-for-Profit Accounting', 'Two independent not-for-profit organizations—Harmony Health Services (total net assets $8.2 million) and Wellspring Clinics (total net assets $5.6 million)—agree to merge into a single new entity. Neither organization transfers consideration to the other, and neither is identified as the acquirer. Under ASC 958-805, what measurement basis applies to the assets and liabilities of the combined entity on the merger date?', '["Fair value for both entities'' assets and liabilities", "Carrying values for the larger entity and fair value for the smaller entity", "Fair value for the acquirer and carrying values for the acquiree", "Carrying values for both entities'' assets and liabilities"]'::jsonb, 3, 'Under ASC 958-805-25, a merger of NFPs where no consideration is exchanged and no acquirer is identified uses the carryover method. All assets and liabilities of both entities are combined at their existing carrying values, and no goodwill is recognized. In contrast, an acquisition under ASC 805 measures the acquiree''s assets and liabilities at fair value rather than carrying amounts.', 'hard', 4),

-- Q5: easy / L1 — Investment return net presentation
(2, 'Not-for-Profit Accounting', 'Under ASU 2016-14, how should a not-for-profit present investment return on its statement of activities?', '["Gross of all investment expenses", "Net of external investment expenses only", "Net of external and direct internal investment expenses", "As a separate component of other comprehensive income"]'::jsonb, 1, 'Under ASC 958-320-45 as amended by ASU 2016-14, NFPs report investment return net of external investment expenses (such as custodial fees and advisory fees paid to outside managers) on the statement of activities. However, direct internal investment expenses are no longer netted against investment return; rather than being deducted from returns, they are reported in functional expense categories alongside other operating expenses.', 'easy', 1),

-- Q6: medium / L2 — Intention vs promise to give
(2, 'Not-for-Profit Accounting', 'At a fundraising dinner, a prominent local business owner tells the executive director of Sunrise Education Foundation, ''I intend to give your organization $200,000 sometime next year.'' The business owner does not sign a pledge card or any written agreement. Under ASC 958, how should Sunrise account for this statement?', '["Recognize $200,000 as contribution revenue with donor restrictions", "Recognize $200,000 as contribution revenue without donor restrictions", "Record a $200,000 refundable advance liability", "Do not recognize any amount because an intention to give is not an unconditional promise"]'::jsonb, 3, 'Under ASC 958-605-25-2, contribution revenue is recognized only when an unconditional promise to give is made. A mere intention or expression of willingness to give does not constitute a legally enforceable promise. Unlike an unconditional pledge—which would be recognized at present value when made—an intention lacks the verifiable documentation needed for recognition and creates no asset for the NFP.', 'medium', 2),

-- Q7: medium / L3 — Refundable advance reversal upon meeting condition
(2, 'Not-for-Profit Accounting', 'Greenfield Environmental Alliance receives a $300,000 grant from Donovan Industries. The grant agreement requires Greenfield to obtain LEED certification for its new facility within 12 months; failure to do so obligates Greenfield to return all funds. After 8 months, Greenfield obtains the LEED certification. What journal entry should Greenfield record at that point?', '["Debit Cash $300,000, Credit Contribution Revenue $300,000", "Debit Contribution Revenue $300,000, Credit Refundable Advance $300,000", "No entry because the grant was already recognized when cash was received", "Debit Refundable Advance $300,000, Credit Contribution Revenue $300,000"]'::jsonb, 3, 'Under ASC 958-605-25-5A (as amended by ASU 2018-08), the LEED certification constitutes a barrier, and the return obligation creates a right of return, making this a conditional contribution. When originally received, Greenfield recorded a refundable advance (liability) rather than revenue. Upon obtaining certification, the barrier is overcome, so Greenfield debits Refundable Advance and credits Contribution Revenue. However, no cash entry is needed because cash was already received.', 'medium', 3),

-- Q8: hard / L3 — Multi-year conditional grant with milestones
(2, 'Not-for-Profit Accounting', 'Brightpath Research Institute receives a 3-year, $900,000 federal research grant disbursed as $300,000 annually. Each annual tranche requires the institute to submit an acceptable progress report; unspent funds from any year with an unacceptable report must be returned. In Year 1, the institute submits an acceptable report and spends $280,000 of the $300,000. How should Brightpath recognize revenue in Year 1?', '["$900,000 because the full grant is awarded", "$300,000 because the Year 1 tranche was received and the barrier was met", "$280,000 because revenue equals qualifying expenditures incurred", "$300,000 less $20,000 refundable advance for unspent funds"]'::jsonb, 2, 'Under ASC 958-605 and ASU 2018-08, this grant contains a barrier (acceptable progress report) and a right of return for unspent funds, making it conditional. While the Year 1 barrier was overcome, the return provision means only amounts spent on qualifying activities ($280,000) satisfy the condition. The $300,000 answer is incorrect because it ignores the return clause for unspent amounts; the remaining $20,000 is reported as a refundable advance.', 'hard', 3),

-- Q9: medium / L2 — Membership dues contribution vs exchange bifurcation
(2, 'Not-for-Profit Accounting', 'Riverdale Arts Council charges annual membership dues of $150. Members receive a quarterly newsletter (fair value $10 per year), free admission to two gallery events (fair value $40 total), and a member directory listing with negligible value. The remaining value of the dues provides no direct benefit to the member. Under ASC 958, how should the Arts Council classify the $150 membership dues?', '["Entirely as contribution revenue", "Entirely as exchange transaction revenue under ASC 606", "$100 as contribution revenue and $50 as exchange revenue", "$50 as exchange revenue and $100 as contribution revenue"]'::jsonb, 3, 'Under ASC 958-605, when membership dues provide some benefits but the payment exceeds the fair value of those benefits, the transaction is bifurcated. The exchange component equals the fair value of benefits received ($10 newsletter + $40 events = $50), recognized under ASC 606, whereas the excess ($150 − $50 = $100) is a contribution because the member receives no commensurate value. Choice C reverses the two amounts.', 'medium', 2),

-- Q10: medium / L2 — Contributed use of facilities
(2, 'Not-for-Profit Accounting', 'Cascade Community Theater, a not-for-profit, is granted free use of a commercial warehouse for one year by the property owner. The warehouse has a fair rental value of $48,000 per year. The theater uses the space exclusively for rehearsals and set construction. Under ASC 958-605, how should Cascade account for this arrangement?', '["Recognize $48,000 as contribution revenue and $48,000 as occupancy expense", "Recognize $48,000 as contribution revenue only with no corresponding expense", "Disclose the arrangement in the notes but do not recognize any amount", "Recognize $48,000 as a deferred rent liability amortized over the lease term"]'::jsonb, 0, 'Under ASC 958-605-25-2, donated use of facilities is recognized as contribution revenue at fair value when reasonably estimable. The NFP simultaneously records an occupancy expense of $48,000 because the organization consumed the economic benefit. Unlike choice B, which records only revenue, the correct treatment requires a dual entry—contribution revenue and operating expense—resulting in no net effect on the change in net assets.', 'medium', 2),

-- Q11: medium / L2 — Contributed inventory exit price valuation
(2, 'Not-for-Profit Accounting', 'Harvest Hope Food Bank receives 50,000 pounds of canned goods from a national grocery chain. The grocery chain''s original cost was $85,000 and retail shelf price is $120,000. The food bank determines the exit price in the principal wholesale market for these goods is $65,000. Under ASC 958-605, at what amount should Harvest Hope recognize the contributed inventory?', '["$85,000, the donor''s original cost", "$120,000, the retail shelf price", "$65,000, the fair value in the principal market", "$0, because food donations are not recognized as assets"]'::jsonb, 2, 'Under ASC 958-605-30-2 and ASC 820, contributed nonfinancial assets are measured at fair value on the date of receipt using the exit price in the principal market. The food bank''s principal market is wholesale, yielding $65,000. Unlike the donor''s cost ($85,000) or the retail price ($120,000), the wholesale exit price represents fair value from the perspective of a market participant in the NFP''s principal market.', 'medium', 2),

-- Q12: hard / L4 — NFP as donee vs agent indicators
(2, 'Not-for-Profit Accounting', 'Sycamore Community Trust receives $750,000 from the Fielding Family Foundation with instructions to transfer the funds to three specified local charities. Sycamore cannot redirect the funds, has no discretion over the amounts each charity receives, and earns a 2% processing fee. The foundation retains the right to recall unspent funds. Under ASC 958-605, Sycamore should account for the $750,000 received as:', '["Contribution revenue with donor restrictions", "Contribution revenue without donor restrictions", "An agency liability, net of the $15,000 processing fee", "A refundable advance liability"]'::jsonb, 2, 'Under ASC 958-605-25-24 through 25-27, an NFP that receives assets with instructions to transfer them to specified beneficiaries, without variance power or other donee indicators, acts as an agent. Unlike a donee with variance power, Sycamore has no discretion, bears no risk of loss, and the foundation retains recall rights. Agent transactions are recorded as liabilities rather than revenue. The $15,000 fee (2% × $750,000) is agency fee revenue; the remaining $735,000 is a liability.', 'hard', 4),

-- Q13: medium / L3 — Bad debt on pledges receivable
(2, 'Not-for-Profit Accounting', 'Sterling Youth Foundation recognizes $500,000 in unconditional pledges receivable. Historical data suggests 6% will be uncollectible. During the year, $18,000 of specific pledges are determined to be worthless and written off. What is the net pledges receivable on the year-end statement of financial position?', '["$482,000", "$452,000", "$470,000", "$500,000"]'::jsonb, 2, 'Under ASC 958-310-35, pledges receivable are reported net of an allowance for uncollectible amounts. The allowance is $500,000 × 6% = $30,000. Writing off $18,000 reduces both gross receivables and the allowance: gross becomes $482,000 and allowance becomes $12,000. Net pledges receivable = $482,000 − $12,000 = $470,000. However, $482,000 is incorrect because it ignores the remaining $12,000 allowance, whereas $452,000 double-counts the write-off.', 'medium', 3),

-- Q14: easy / L1 — NFP balance sheet terminology
(2, 'Not-for-Profit Accounting', 'What is the not-for-profit equivalent of the for-profit balance sheet under ASC 958?', '["Statement of financial position", "Statement of net assets", "Statement of net position", "Statement of activities"]'::jsonb, 0, 'Under ASC 958-210, an NFP entity reports its assets, liabilities, and net assets on the statement of financial position. This serves the same purpose as the for-profit balance sheet but uses NFP-specific terminology reflecting the absence of owners'' equity. Unlike the "statement of net position," which is a governmental accounting term under GASB, the statement of financial position is the correct term for private NFPs under FASB standards.', 'easy', 1),

-- Q15: medium / L3 — Simultaneous purpose and time restriction release
(2, 'Not-for-Profit Accounting', 'In January 2025, Pinnacle Arts Foundation receives a $200,000 contribution restricted for the purchase of musical instruments, which must be acquired after July 1, 2025. Pinnacle purchases $200,000 of instruments on September 15, 2025. Pinnacle does not have a policy of implying a time restriction on long-lived assets. When should Pinnacle reclassify the net assets from "with donor restrictions" to "without donor restrictions"?', '["January 2025, when the contribution is received", "July 1, 2025, when the time restriction expires", "September 15, 2025, when both the purpose and time restrictions are met", "Over the useful life of the instruments"]'::jsonb, 2, 'Under ASC 958-205-45-8, when a contribution has both a purpose restriction and a time restriction, both conditions must be satisfied before reclassification. The full $200,000 is released on September 15, 2025, when the instruments are purchased after the time threshold. However, July 1 alone does not trigger release because the purpose restriction (purchasing instruments) had not yet been met, whereas the January receipt date precedes both restrictions.', 'medium', 3),

-- Q16: easy / L2 — Board-designated endowment reversibility
(2, 'Not-for-Profit Accounting', 'The board of directors of Westlake Community Services votes to designate $500,000 of unrestricted funds as a quasi-endowment to generate investment income for future programs. Two years later, facing a cash shortfall, the board reverses the designation. Under ASC 958, which statement best describes this situation?', '["The reversal is prohibited because endowment designations are irrevocable", "The board may reverse the designation because board-designated funds are not donor-restricted", "The reversal requires donor approval before the funds can be released", "The funds must be reclassified from net assets with donor restrictions to net assets without donor restrictions"]'::jsonb, 1, 'Under ASC 958-205-45-1, board-designated or quasi-endowment funds are classified as net assets without donor restrictions because the restriction is internally imposed. Since the governing board created the designation, it can reverse it at any time without external approval. Unlike donor-restricted endowments, where restrictions can only be removed by the donor or through legal proceedings such as cy pres, board designations are entirely within the board''s control.', 'easy', 2),

-- Q17: medium / L2 — Special events contribution/exchange/direct cost reporting
(2, 'Not-for-Profit Accounting', 'Oakdale Humane Society holds an annual charity auction. Ticket sales total $120,000, and attendees receive dinner and entertainment with a fair value of $35,000. The organization incurs $28,000 in direct catering and entertainment costs. How should Oakdale report the event on the statement of activities?', '["$120,000 contribution revenue and $28,000 fundraising expense", "$85,000 contribution revenue, $35,000 exchange revenue, and $28,000 cost of direct benefits to donors", "$120,000 special event revenue with $28,000 netted against it", "$85,000 contribution revenue and $28,000 fundraising expense"]'::jsonb, 1, 'Under ASC 958-225-45-5, when a special event has both a contribution element and an exchange element, each component is reported separately. The exchange portion equals the fair value of direct benefits ($35,000), whereas the contribution portion is the excess ($120,000 − $35,000 = $85,000). The $28,000 in direct costs is reported as cost of direct benefits to donors rather than as a general fundraising expense.', 'medium', 2),

-- Q18: hard / L4 — NFP consolidation controlling financial interest
(2, 'Not-for-Profit Accounting', 'Cornerstone Health System, a not-for-profit hospital with $450 million in total assets, has a controlling financial interest in two legally separate NFP entities: a physician practice group and a medical research foundation. Cornerstone appoints a majority of each entity''s board and directs their strategic and financial decisions. A third entity, the Hospital Auxiliary, raises funds and donates them exclusively to Cornerstone but is governed by an independent board. Under ASC 958-810, which entities must Cornerstone consolidate?', '["All three entities because they all support Cornerstone''s mission", "Only the physician group and research foundation over which Cornerstone has a controlling financial interest", "Only the Hospital Auxiliary because its resources flow to Cornerstone", "None, because NFPs are never required to consolidate other entities"]'::jsonb, 1, 'Under ASC 958-810-15, an NFP must consolidate another NFP when it has a controlling financial interest, evidenced by majority voting interest in the board or economic interest combined with control. Cornerstone appoints the majority of the board for both the physician group and research foundation. However, the Hospital Auxiliary is independently governed, and although it donates to Cornerstone, an economic interest alone without control does not trigger consolidation.', 'hard', 4),

-- Q19: medium / L2 — Endowment investment gains with donor stipulation
(2, 'Not-for-Profit Accounting', 'A donor contributes $1,000,000 to Cedarwood University''s endowment, stipulating that the principal is permanent and investment income must be used for need-based scholarships. In Year 1, the endowment earns $60,000 in dividends and interest. How should the $60,000 investment income be classified?', '["Net assets without donor restrictions", "Temporarily suspended in the endowment corpus", "Contribution revenue without donor restrictions", "Net assets with donor restrictions—purpose restricted for scholarships"]'::jsonb, 3, 'Under ASC 958-205-45-10, investment income earned on a donor-restricted endowment follows the donor''s stipulation. Because the donor specified that income must be used for scholarships, the $60,000 is classified as net assets with donor restrictions (purpose-restricted) until spent on qualifying scholarships. However, if the donor had not restricted the use of investment income, it would instead be classified as net assets without donor restrictions.', 'medium', 2),

-- Q20: medium / L2 — Pledges receivable discount rate selection
(2, 'Not-for-Profit Accounting', 'Summit Trail Foundation receives an unconditional pledge of $300,000 payable in three equal annual installments of $100,000 beginning one year from the pledge date. When measuring the pledge at present value for initial recognition, which discount rate is most appropriate under ASC 958?', '["The federal funds rate on the pledge date", "The NFP''s weighted average cost of capital", "The donor''s incremental borrowing rate", "A risk-adjusted rate commensurate with the pledge''s expected collection period"]'::jsonb, 3, 'Under ASC 958-605-30-1, unconditional promises to give expected to be collected in more than one year are measured at present value using a discount rate commensurate with the risks involved. This rate reflects the credit risk of the specific pledge rather than a general benchmark. Unlike the federal funds rate or the NFP''s cost of capital, the appropriate rate is specific to the risk profile of the particular pledge receivable.', 'medium', 2),

-- Q21: hard / L4 — UPMIFA endowment appropriation and net asset classification
(2, 'Not-for-Profit Accounting', 'Meridian Cultural Foundation maintains a $5,000,000 permanent endowment in a state that has adopted UPMIFA. The donor''s gift instrument is silent regarding the use of investment returns. In the current year, the endowment earns $350,000 in net investment returns. The board appropriates $200,000 for program spending. Under ASC 958, how is the $350,000 classified at year-end?', '["$350,000 as net assets without donor restrictions", "$200,000 released to net assets without donor restrictions, $150,000 remaining as net assets with donor restrictions", "$350,000 as net assets with donor restrictions until all amounts are appropriated", "$200,000 as program expense, $150,000 as temporarily restricted revenue"]'::jsonb, 1, 'Under ASC 958-205-45-10 and UPMIFA, when a donor''s instrument is silent on investment return usage, net appreciation on endowment funds is classified as net assets with donor restrictions until appropriated for expenditure. Upon board appropriation, amounts are reclassified as net assets released from restrictions. Although the full $350,000 initially enters the restricted category, the $200,000 appropriated is released, whereas the unappropriated $150,000 remains restricted until future action.', 'hard', 4),

-- Q22: medium / L2 — Dual journal entry for contributed specialized services
(2, 'Not-for-Profit Accounting', 'A licensed CPA donates 100 hours of audit work to Whitewater Relief Alliance, a not-for-profit entity. Her normal billing rate is $250 per hour. The audit services would otherwise need to be purchased. Under ASC 958-605, what is the total effect on Whitewater''s statement of activities?', '["$25,000 increase in contribution revenue and $25,000 increase in professional fees expense", "$25,000 increase in contribution revenue only", "$25,000 decrease in net assets without donor restrictions", "No recognition because volunteer services are never recorded"]'::jsonb, 0, 'Under ASC 958-605-25-16, contributed services that require specialized skills, are provided by qualified individuals, and would typically need to be purchased are recognized at fair value. Whitewater records $25,000 (100 × $250) as contribution revenue and $25,000 as professional fees expense. Although the net effect on change in net assets is zero, both revenue and expense increase. Choice B is incorrect because it omits the corresponding expense recognition.', 'medium', 2),

-- Q23: easy / L1 — Liquidity and availability disclosures
(2, 'Not-for-Profit Accounting', 'Under ASU 2016-14, what must a not-for-profit disclose about its liquidity?', '["Qualitative and quantitative information about managing liquid resources available within one year", "Only the total amount of cash and cash equivalents", "A schedule of all investments at fair value by maturity date", "Projected cash inflows and outflows for the next five fiscal years"]'::jsonb, 0, 'ASC 958-210-50 (as amended by ASU 2016-14) requires NFPs to provide both qualitative and quantitative information about how they manage liquid resources to meet cash needs for general expenditures within one year. Unlike the limited prior requirements, this disclosure includes the availability of financial assets, limitations from donor restrictions or board designations, and how the entity manages liquidity risk.', 'easy', 1),

-- Q24: easy / L1 — Fund accounting vs GAAP net asset reporting
(2, 'Not-for-Profit Accounting', 'Internally, many NFPs track resources using fund accounting. Under ASC 958, how must net assets be classified on external financial statements?', '["By individual fund such as general fund, endowment fund, and capital fund", "Into three categories: unrestricted, temporarily restricted, and permanently restricted", "By program, management, and fundraising designations", "Into two categories: without donor restrictions and with donor restrictions"]'::jsonb, 3, 'Under ASC 958-210-45 (as amended by ASU 2016-14), external financial statements classify net assets into two categories: without donor restrictions and with donor restrictions. While NFPs may use fund accounting internally, fund-based classifications are not displayed on GAAP financial statements. The three-category model (choice B) was eliminated by ASU 2016-14, which simplified reporting from the former unrestricted/temporarily restricted/permanently restricted system.', 'easy', 1),

-- Q25: medium / L3 — Statement of functional expenses matrix format
(2, 'Not-for-Profit Accounting', 'Harmony Shelter, a voluntary health and welfare organization, prepares its statement of functional expenses. Program services include housing assistance ($180,000) and job training ($95,000). Supporting activities include management ($65,000) and fundraising ($40,000). Each function''s expenses are broken down by salaries, rent, supplies, and depreciation. Under ASC 958-720, what presentation format does this statement require?', '["A single column listing total expenses by natural classification", "A matrix with functions as columns and natural classifications as rows", "A pie chart showing the percentage of expenses by function", "Separate statements for program services and supporting activities"]'::jsonb, 1, 'Under ASC 958-720-45-1 (as updated by ASU 2016-14), the statement of functional expenses presents expenses in a matrix format with functional categories as columns and natural classifications as rows. Unlike a single-column listing, this cross-tabulation enables users to see both how resources were used (function) and what was consumed (nature). All NFPs must present this analysis, although VHWOs are specifically required to use a separate statement.', 'medium', 3),

-- Q26: medium / L3 — Joint activity audience criterion failure
(2, 'Not-for-Profit Accounting', 'Meadowbrook Animal Rescue sends a $42,000 direct-mail campaign to its existing donor list of 15,000 individuals. The mailing requests donations and includes a two-page brochure about responsible pet ownership. Management wants to allocate costs between fundraising and program activities. However, 95% of recipients are prior donors selected for their giving history. Under ASC 958-720, can costs be allocated to program activities?', '["Yes, because the brochure has educational content that satisfies the content criterion", "Yes, because any campaign with program-related content qualifies for joint cost allocation", "No, because the audience criterion is not met when the primary recipients are existing donors", "No, because direct-mail campaigns are always 100% fundraising"]'::jsonb, 2, 'Under ASC 958-720-45-12, the audience criterion requires that the target audience be selected based on its ability to take the desired programmatic action rather than its propensity to donate. When 95% of recipients are prior donors selected for giving history, the audience criterion fails. Although the brochure may have strong educational content, all three criteria (purpose, audience, content) must be met, and failure of any one means the entire cost is charged to fundraising.', 'medium', 3),

-- Q27: medium / L3 — Agency transaction pass-through contributions
(2, 'Not-for-Profit Accounting', 'Metro United Way collects $2,000,000 during its annual campaign. Donors designate $600,000 for specific partner agencies, and Metro United Way has no discretion to redirect these designated funds. The remaining $1,400,000 is undesignated. Under ASC 958-605, how should Metro United Way account for the $600,000 in donor-designated gifts?', '["$600,000 as contribution revenue with donor restrictions", "$600,000 as contribution revenue without donor restrictions", "$600,000 as an agency liability payable to the designated organizations", "$600,000 as a refundable advance"]'::jsonb, 2, 'Under ASC 958-605-25-24, when an NFP receives assets it must transfer to specified beneficiaries and lacks variance power, it acts as an agent. Unlike the undesignated $1,400,000 over which Metro has variance power and recognizes as contribution revenue, the $600,000 in donor-designated gifts is recorded as an agency liability rather than revenue because Metro has no discretion to redirect these funds.', 'medium', 3),

-- Q28: easy / L1 — Direct vs indirect method for NFP cash flows
(2, 'Not-for-Profit Accounting', 'Under ASC 958, which methods may a not-for-profit use to present operating activities on the statement of cash flows?', '["Either the direct method or the indirect method", "Only the direct method", "Only the indirect method", "A modified accrual method specific to not-for-profits"]'::jsonb, 0, 'Under ASC 958-230-45 and ASC 230, NFPs may present operating cash flows using either the direct method or the indirect method, the same options available to for-profit entities. Unlike governmental entities, which follow GASB standards, private NFPs follow FASB guidance. There is no special modified accrual method for NFP cash flow reporting; rather than a unique approach, NFPs use the same framework as commercial enterprises.', 'easy', 1),

-- Q29: easy / L1 — Measure of operations optional intermediate
(2, 'Not-for-Profit Accounting', 'Under ASU 2016-14, may a not-for-profit present an intermediate measure of operations on its statement of activities?', '["Yes, at the entity''s discretion, with disclosure of what is included and excluded", "No, ASU 2016-14 prohibits any intermediate operating measures", "Yes, but only if the measure is labeled operating income", "Yes, but only voluntary health and welfare organizations may present it"]'::jsonb, 0, 'Under ASC 958-225-45-12 (per ASU 2016-14), an NFP may elect to present an intermediate measure of operations on the statement of activities. However, if presented, the entity must disclose items included in or excluded from the measure. Unlike choice C, there is no required label, and unlike choice D, this option is available to all NFPs rather than only voluntary health and welfare organizations.', 'easy', 1),

-- Q30: easy / L1 — Conditional contribution two-element definition
(2, 'Not-for-Profit Accounting', 'Under ASU 2018-08, what two elements must be present for a contribution to be classified as conditional?', '["A barrier to entitlement and a right of return or right of release", "A written pledge agreement and a specified payment schedule", "A donor restriction and a matching fund requirement", "A purpose restriction and a time restriction"]'::jsonb, 0, 'Under ASC 958-605-25-5A (per ASU 2018-08), a contribution is conditional if it contains both a barrier that must be overcome before the recipient is entitled to the assets and a right of return or release if the barrier is not met. Unlike restrictions, which affect classification rather than timing, conditions delay revenue recognition entirely until the barrier is substantially met and no right of return remains.', 'easy', 1)
;

COMMIT;
