-- Migration: Question generation — FAR batch 62 (30 questions)
-- Date: 2026-03-03
-- Topic: Consolidations
-- Difficulty: 9E / 15M / 6H
-- Bloom's: L1:8 / L2:9 / L3:8 / L4:5

BEGIN;

INSERT INTO questions (section_id, topic, stem, choices, correct_index, explanation, difficulty, cognitive_level)
VALUES

-- Q1: medium / L2 — Equity method investor's share of investee OCI
(2, 'Consolidations', 'Maple Corp. holds a 25% equity interest in Birch Inc. During the year, Birch reports net income of $600,000 and other comprehensive income of $80,000 from unrealized gains on available-for-sale debt securities. Under the equity method, what amount should Maple report as its share of Birch''s other comprehensive income?', '["$80,000", "$150,000", "$20,000", "$0"]'::jsonb, 2, 'Under ASC 323-10-35-18, an equity method investor recognizes its proportionate share of the investee''s OCI in its own OCI. Maple''s share is 25% × $80,000 = $20,000, reported in Maple''s OCI rather than net income. The $0 answer incorrectly assumes OCI is ignored under the equity method; however, the investor must track all changes in the investee''s equity, including OCI items.', 'medium', 2),

-- Q2: medium / L3 — Intercompany fixed asset sale Year 2 depreciation catch-up
(2, 'Consolidations', 'On January 1, Year 1, Parent Co. sold equipment with a net book value of $200,000 to its wholly owned subsidiary for $260,000. The subsidiary depreciates the equipment straight-line over 4 years with no salvage value. In the Year 2 consolidation workpaper, what is the net adjustment to increase consolidated net income?', '["$0", "$60,000", "$15,000", "$45,000"]'::jsonb, 2, 'Under ASC 810-10-45, intercompany gains on asset transfers are eliminated and recognized through depreciation over the asset''s remaining life. The $60,000 gain was eliminated in Year 1, with $15,000 ($60,000 ÷ 4 years) recognized annually through lower excess depreciation. In Year 2, the $15,000 depreciation catch-up increases consolidated net income. Choice D ($45,000) incorrectly represents the remaining unrecognized gain rather than the single-year annual portion.', 'medium', 3),

-- Q3: hard / L3 — Push-down accounting for acquired subsidiary
(2, 'Consolidations', 'Garrison Holdings acquires 100% of Trident Corp. for $12 million. Trident''s identifiable net assets have a book value of $8 million and a fair value of $10 million. Garrison elects push-down accounting for Trident. On Trident''s separate-entity financial statements after the acquisition, at what amount should Trident report its identifiable net assets?', '["$12,000,000 (purchase price)", "$8,000,000 (historical book value)", "$9,000,000 (average of book and fair value)", "$10,000,000 (acquisition-date fair value)"]'::jsonb, 3, 'Under ASC 805-50-25-4, when push-down accounting is applied, the acquired subsidiary adjusts its own financial statements to reflect the new basis established by the acquirer — the acquisition-date fair values of identifiable net assets. Trident reports $10 million, not book value or purchase price. Choice A ($12 million) confuses total consideration with identifiable net assets; the $2 million excess represents goodwill, which is reported separately.', 'hard', 3),

-- Q4: medium / L3 — Measurement period adjustment for provisional amounts
(2, 'Consolidations', 'Nova Corp. acquired 100% of Stellar Inc. on April 1, Year 1. Nova initially estimated Stellar''s customer relationships at $500,000. On January 15, Year 2, Nova obtains new information about conditions that existed at the acquisition date, revising the fair value to $700,000. How should Nova account for this adjustment?', '["Recognize $200,000 as a gain in Year 2 earnings", "Recognize $200,000 in Year 2 other comprehensive income", "No adjustment is permitted because the initial estimate is final", "Adjust goodwill and recognized assets retroactively as if the revised values were known at the acquisition date"]'::jsonb, 3, 'Under ASC 805-10-25-17, during the measurement period (up to one year from the acquisition date), the acquirer adjusts provisional amounts retroactively, with corresponding adjustments to goodwill. The revised customer relationships increase by $200,000, reducing goodwill by $200,000 as of the acquisition date. Choice A incorrectly treats this as a subsequent gain; measurement period adjustments correct provisional acquisition-date amounts, not post-combination earnings.', 'medium', 3),

-- Q5: medium / L2 — Equity method losses exceeding investment balance
(2, 'Consolidations', 'Cedar Corp. holds a 40% equity investment in Pine Inc. with a carrying amount of $150,000 and no guaranteed obligations or advances. Pine reports a net loss of $500,000 for the year. Under the equity method, what loss should Cedar recognize?', '["$150,000", "$200,000", "$0", "$500,000"]'::jsonb, 0, 'Under ASC 323-10-35-19, when an investor''s share of investee losses ($200,000 = 40% × $500,000) exceeds the carrying amount of the investment, the investor recognizes losses only to the extent of its investment balance plus any additional financial commitments. Since Cedar has no guaranteed obligations, the loss is capped at $150,000, reducing the investment to zero. Choice B ($200,000) ignores the limitation that prevents a negative investment balance.', 'medium', 2),

-- Q6: medium / L2 — NCI roll-forward with fair value amortization
(2, 'Consolidations', 'Apex Group owns 70% of Zenith Corp., acquired when Zenith''s identifiable intangible assets required a $100,000 annual fair value amortization. Zenith reports Year 2 net income of $800,000 before fair value adjustments and declares no dividends. What is the noncontrolling interest''s share of Zenith''s adjusted income?', '["$210,000", "$240,000", "$230,000", "$200,000"]'::jsonb, 0, 'Under ASC 810-10-45-20, the NCI''s share of subsidiary income is based on adjusted net income after fair value amortization. Zenith''s adjusted income = $800,000 − $100,000 = $700,000. NCI at 30% = $700,000 × 30% = $210,000. Choice B ($240,000) incorrectly uses unadjusted income ($800,000 × 30%), failing to account for the fair value amortization that flows through the consolidated income statement.', 'medium', 2),

-- Q7: medium / L2 — Deconsolidation gain or loss on disposal of subsidiary
(2, 'Consolidations', 'Orion Corp. owns 80% of Vega Inc. The consolidated carrying amount of Vega''s net assets is $2,000,000, including noncontrolling interest of $400,000. Orion sells its entire 80% interest for $1,800,000. Under ASC 810-10-40, what gain or loss does Orion recognize on deconsolidation?', '["$400,000 gain", "$200,000 gain", "$1,800,000 gain", "$600,000 gain"]'::jsonb, 1, 'Under ASC 810-10-40-5, upon deconsolidation, the parent recognizes a gain or loss measured as the difference between proceeds received and the parent''s share of the subsidiary''s carrying amount. Parent''s 80% share = $2,000,000 − $400,000 NCI = $1,600,000. Gain = $1,800,000 − $1,600,000 = $200,000. Choice A ($400,000) incorrectly deducts total net assets from proceeds rather than the parent''s controlling portion.', 'medium', 2),

-- Q8: medium / L3 — Change in ownership without loss of control (equity transaction)
(2, 'Consolidations', 'Summit Corp. owns 90% of Ridge Inc. Summit sells a 10% interest in Ridge to an outside investor for $350,000. The carrying amount of the 10% interest sold, including NCI adjustments, is $300,000. Summit retains 80% control. Under ASC 810-10-45-23, how should Summit account for this transaction?', '["Recognize a $50,000 gain in earnings", "Recognize a $50,000 gain in other comprehensive income", "Reduce goodwill by $50,000", "Record a $50,000 increase to additional paid-in capital"]'::jsonb, 3, 'Under ASC 810-10-45-23, changes in a parent''s ownership interest in a subsidiary while retaining control are accounted for as equity transactions. No gain or loss is recognized in earnings or OCI. The $50,000 difference between the $350,000 proceeds and the $300,000 carrying amount is recorded directly to additional paid-in capital. Choice A incorrectly treats this as an earnings event; gain or loss recognition only applies when control is lost.', 'medium', 3),

-- Q9: medium / L3 — Intercompany bond constructive retirement
(2, 'Consolidations', 'Parent Co. has outstanding bonds with a carrying amount of $980,000 (net of unamortized discount). Its wholly owned subsidiary purchases these bonds on the open market for $960,000. On the consolidated financial statements, what gain or loss is recognized from this constructive retirement?', '["$0, because the bonds still legally exist", "$980,000 loss", "$20,000 gain", "$20,000 loss"]'::jsonb, 2, 'Under ASC 810-10-45, when a subsidiary purchases its parent''s bonds, a constructive retirement occurs for consolidation purposes. The gain or loss equals the difference between the issuer''s carrying amount ($980,000) and the price paid by the affiliate ($960,000), yielding a $20,000 gain on the consolidated income statement. Choice A incorrectly ignores that consolidation treats affiliated entities as a single economic unit where intercompany debt must be eliminated.', 'medium', 3),

-- Q10: easy / L1 — Consolidated retained earnings equals parent adjusted RE
(2, 'Consolidations', 'In consolidated financial statements, consolidated retained earnings typically equals:', '["The sum of parent and subsidiary retained earnings", "The parent company''s retained earnings adjusted for consolidation entries", "The subsidiary''s retained earnings only", "The average of parent and subsidiary retained earnings"]'::jsonb, 1, 'Under ASC 810-10-45, consolidated retained earnings reflects the parent company''s retained earnings as adjusted for consolidation eliminations such as intercompany profit deferrals. The subsidiary''s retained earnings are eliminated during consolidation since they are replaced by the line-by-line combination. Choice A is incorrect because adding both would double-count the subsidiary''s earnings already reflected in the parent''s retained earnings through consolidation.', 'easy', 1),

-- Q11: hard / L4 — Complex VIE analysis where no single entity qualifies
(2, 'Consolidations', 'Entity X manages VIE Corp. under a management contract and directs all significant activities. Entity X receives a fixed fee equal to 2% of assets but absorbs none of VIE Corp.''s residual gains or losses. Entity Y holds 80% of VIE Corp.''s equity and absorbs 80% of expected losses but cannot remove the manager or direct operations. Under ASC 810-10-25, which entity should consolidate VIE Corp.?', '["Entity X, because it has power over significant activities", "Entity Y, because it absorbs the majority of expected losses", "Neither entity, because no single entity has both power and significant economics", "Both entities consolidate proportionately"]'::jsonb, 2, 'Under ASC 810-10-25-38A, the primary beneficiary must have both (1) power to direct the VIE''s most significant activities and (2) the obligation to absorb losses or rights to receive benefits that could be significant. Entity X has power but no significant variable economics (only a fixed fee). Entity Y has significant economics but no power. Because no single entity meets both criteria, neither consolidates. Choice B incorrectly assumes economics alone triggers consolidation.', 'hard', 4),

-- Q12: hard / L4 — Noncash consideration fair value in goodwill calculation
(2, 'Consolidations', 'Highland Corp. acquires 100% of Lakeside Inc. by issuing 500,000 shares of its common stock (market price $12 per share on acquisition date) and transferring a building with a book value of $1,500,000 and a fair value of $2,200,000. Lakeside''s identifiable net assets have a fair value of $7,500,000. What amount of goodwill should Highland recognize?', '["$0", "$1,700,000", "$700,000", "$200,000"]'::jsonb, 2, 'Under ASC 805-30-30-7, consideration in a business combination is measured at acquisition-date fair value. Stock = 500,000 × $12 = $6,000,000. Building = $2,200,000 (fair value, not book). Total consideration = $8,200,000. Goodwill = $8,200,000 − $7,500,000 = $700,000. Choice A ($0) incorrectly uses the building''s book value ($1,500,000), yielding total consideration of $7,500,000 that would equal net assets. Noncash consideration must be measured at fair value.', 'hard', 4),

-- Q13: easy / L1 — Intercompany dividends are eliminated
(2, 'Consolidations', 'In consolidated financial statements, dividends paid by a subsidiary to its parent company are:', '["Eliminated in consolidation", "Reported as dividend income by the parent", "Reported as a financing outflow on the cash flow statement", "Deducted from consolidated revenue"]'::jsonb, 0, 'Under ASC 810-10-45, all intercompany transactions, including dividends from subsidiary to parent, are eliminated in preparing consolidated financial statements. Subsidiary dividends to the parent are intra-entity transfers with no effect on the consolidated entity''s total equity. Choice B is incorrect because while the parent may record dividend income on its separate books, this is reversed during consolidation to avoid double-counting income already included line by line.', 'easy', 1),

-- Q14: easy / L1 — Subsidiary with different fiscal year-end
(2, 'Consolidations', 'Under ASC 810, if a subsidiary''s fiscal year-end differs from the parent''s by more than three months, the subsidiary must:', '["Use its own fiscal year-end data without adjustment", "Prepare interim financial statements aligned with the parent''s reporting date", "Delay reporting until both year-ends are synchronized", "Convert to the parent''s fiscal year permanently"]'::jsonb, 1, 'Under ASC 810-10-45-12, when a subsidiary''s fiscal year-end differs from the parent''s by more than approximately three months, the subsidiary must prepare financial information as of the parent''s reporting date (typically interim statements). If the difference is three months or less, the subsidiary''s statements may be used with disclosure of intervening material events. Choice A is incorrect because using misaligned data without adjustment would distort the consolidated financial position.', 'easy', 1),

-- Q15: easy / L1 — NCI presentation on consolidated balance sheet
(2, 'Consolidations', 'Under ASC 810, noncontrolling interest in a consolidated subsidiary is presented on the consolidated balance sheet as:', '["A current liability", "A separate component of equity", "A contra-asset reducing total assets", "A deferred credit between liabilities and equity"]'::jsonb, 1, 'Under ASC 810-10-45-16, noncontrolling interest is reported as a separate component of equity in the consolidated balance sheet, clearly distinguished from the parent''s equity. It is not classified as a liability, contra-asset, or deferred credit. Choice A is incorrect — earlier standards sometimes placed NCI between liabilities and equity (mezzanine), but ASC 810 requires equity classification for all noncontrolling interests.', 'easy', 1),

-- Q16: hard / L4 — Contingent consideration revision after acquisition date
(2, 'Consolidations', 'On July 1, Year 1, Drake Corp. acquires 100% of Ember Inc. for $5,000,000 cash plus contingent consideration initially valued at $600,000 tied to revenue targets. At December 31, Year 1, the contingent consideration''s fair value increases to $850,000. Ember''s identifiable net assets have a fair value of $4,200,000 at acquisition. What is the effect on Drake''s Year 1 consolidated financial statements?', '["Goodwill of $1,400,000 and no charge to earnings", "Goodwill of $1,650,000 and no charge to earnings", "Goodwill of $1,400,000 and a $250,000 charge to earnings", "Goodwill of $1,650,000 and a $250,000 charge to earnings"]'::jsonb, 2, 'Under ASC 805-30-35-1, goodwill is calculated using the acquisition-date fair value of contingent consideration ($600,000): Goodwill = ($5,000,000 + $600,000) − $4,200,000 = $1,400,000. Post-acquisition changes in contingent consideration fair value are recognized in earnings, not as goodwill adjustments. The $250,000 increase is a Year 1 expense. Choice B incorrectly recalculates goodwill using the updated fair value, violating the principle that goodwill is locked at the acquisition date.', 'hard', 4),

-- Q17: easy / L1 — Equity method dividends reduce investment balance
(2, 'Consolidations', 'Under the equity method, when an investee declares and pays dividends, the investor records the dividends received as:', '["Revenue on the income statement", "Other comprehensive income", "An increase to the investment account", "A reduction of the investment account"]'::jsonb, 3, 'Under ASC 323-10-35-4, dividends received from an equity method investee reduce the carrying amount of the investment rather than being recognized as income. The investor already recognizes its share of the investee''s net income through equity earnings, so dividends represent a distribution (return of investment), not additional revenue. Choice A is incorrect because recording dividends as revenue would double-count the investee''s earnings.', 'easy', 1),

-- Q18: medium / L2 — Subsidiary preferred stock held by outside investors
(2, 'Consolidations', 'Atlas Corp. owns 100% of the common stock of Branch Inc. Outside investors hold $2,000,000 of Branch''s cumulative preferred stock paying 6% annual dividends. Branch reports net income of $500,000 for the year. What amount of Branch''s income is attributable to the noncontrolling interest in the consolidated statements?', '["$500,000", "$120,000", "$0, because Atlas owns all common stock", "$380,000"]'::jsonb, 1, 'Under ASC 810-10-45-20, noncontrolling interest includes any subsidiary equity not owned by the parent. The outside preferred stockholders'' dividend claim of $120,000 ($2,000,000 × 6%) is allocated to NCI. Choice C incorrectly assumes that owning 100% of common stock eliminates all NCI; however, third-party preferred stockholders represent a noncontrolling interest requiring separate recognition in the consolidated financial statements.', 'medium', 2),

-- Q19: medium / L3 — Equity method downstream intercompany profit deferral
(2, 'Consolidations', 'Crescent Corp. holds a 30% equity method investment in Dune Inc. During Year 1, Crescent sold inventory costing $200,000 to Dune for $300,000. At year-end, 50% of the inventory remains unsold by Dune. Under the equity method, what amount of intercompany profit should Crescent defer?', '["$15,000", "$50,000", "$30,000", "$100,000"]'::jsonb, 0, 'Under ASC 323-10-35-7, for equity method investments, the investor eliminates its proportionate share of unrealized intercompany profit on downstream transactions. Unrealized gross profit = ($300,000 − $200,000) × 50% = $50,000. Crescent defers its 30% share: $50,000 × 30% = $15,000. Choice B ($50,000) incorrectly eliminates 100% of the unrealized profit, which applies only to full consolidation, not to the equity method where only the investor''s proportionate share is eliminated.', 'medium', 3),

-- Q20: easy / L1 — Acquisition-related restructuring costs not part of combination
(2, 'Consolidations', 'Under ASC 805, costs the acquirer plans to incur to restructure or exit activities of the acquiree after a business combination are:', '["Expensed in the periods incurred", "Included in the goodwill calculation", "Charged against the noncontrolling interest", "Recognized as a liability at the acquisition date"]'::jsonb, 0, 'Under ASC 805-10-25-23, restructuring costs that the acquirer expects to incur in the future to exit or restructure the acquiree''s activities are not acquisition-date liabilities. They are recognized as post-combination expenses in the periods incurred. Choice D is incorrect because only liabilities that existed at the acquisition date and meet ASC 805 recognition criteria are recorded. Future restructuring plans are not assumed liabilities of the acquiree.', 'easy', 1),

-- Q21: medium / L2 — Fair value amortization in subsequent consolidation years
(2, 'Consolidations', 'Polaris Group acquired 100% of Quasar Corp. three years ago. At acquisition, customer relationships were assigned a fair value $300,000 above book value with a 10-year remaining life. On the Year 3 consolidated income statement, what annual adjustment is made for this fair value difference?', '["No adjustment is needed because fair value differences are recognized only at acquisition", "A $300,000 expense in Year 3", "A $30,000 increase to consolidated net income", "A $30,000 decrease to consolidated net income"]'::jsonb, 3, 'Under ASC 805-20-35-1, identifiable intangible assets recognized at fair value in a business combination are amortized over their useful lives. The $300,000 excess is amortized at $30,000 per year ($300,000 ÷ 10), creating additional amortization expense that reduces consolidated net income annually. Choice A incorrectly assumes fair value adjustments have no subsequent impact; these adjustments systematically flow through income via amortization throughout the asset''s useful life.', 'medium', 2),

-- Q22: medium / L2 — Consolidated EPS uses parent company shares only
(2, 'Consolidations', 'Titan Holdings owns 75% of Comet Industries. When computing consolidated basic earnings per share, which entity''s outstanding common shares form the denominator?', '["The combined shares of Titan and Comet", "Titan''s shares only", "75% of Titan''s shares plus 25% of Comet''s shares", "Comet''s shares only"]'::jsonb, 1, 'Under ASC 260-10-45-11, consolidated EPS is calculated using the parent company''s outstanding common shares as the denominator. The subsidiary''s shares are not included because they do not represent claims on the consolidated entity''s earnings by public shareholders. Choice A incorrectly adds subsidiary shares, which would dilute the metric and misrepresent the economic interest of the parent''s shareholders in the consolidated group.', 'medium', 2),

-- Q23: medium / L3 — Equity method goodwill not separately tested for impairment
(2, 'Consolidations', 'Northstar Corp. holds a 35% equity method investment in Compass Inc. The original purchase price included $400,000 attributable to equity method goodwill. At year-end, Compass''s stock price has declined significantly. How should Northstar evaluate this equity method goodwill for impairment?', '["Apply the quantitative goodwill impairment test at the reporting unit level", "Perform a fair value test on the goodwill component alone", "Write down the $400,000 directly to zero if any decline in fair value occurs", "Evaluate the total investment for other-than-temporary impairment rather than testing goodwill separately"]'::jsonb, 3, 'Under ASC 323-10-35-32, equity method goodwill is not tested separately for impairment. Instead, the entire equity method investment (including embedded goodwill) is evaluated for other-than-temporary impairment (OTTI). If fair value is below carrying amount and the decline is OTTI, the investment is written down. Choice A is incorrect because the ASC 350 reporting unit test applies to goodwill from consolidated subsidiaries, not equity method investments.', 'medium', 3),

-- Q24: hard / L4 — Foreign subsidiary translation adjustment in AOCI
(2, 'Consolidations', 'Global Corp. consolidates a foreign subsidiary whose functional currency is the euro. After translating the subsidiary''s financial statements under the current rate method per ASC 830, a $420,000 cumulative translation adjustment arises due to exchange rate changes between the beginning and end of the year. Where does Global report this translation adjustment?', '["In accumulated other comprehensive income within equity", "As a foreign currency gain in consolidated net income", "As an adjustment to goodwill arising from the foreign acquisition", "As a direct reduction to the foreign subsidiary''s investment account"]'::jsonb, 0, 'Under ASC 830-30-45-12, translation adjustments arising from translating a foreign subsidiary''s functional currency financial statements into the reporting currency are reported in accumulated other comprehensive income (AOCI) within equity. They bypass the income statement entirely. Choice B is incorrect because only remeasurement gains and losses (when functional currency differs from local recording currency) are recorded in net income under ASC 830.', 'hard', 4),

-- Q25: easy / L1 — VIE reconsideration is ongoing
(2, 'Consolidations', 'Under ASC 810, an entity must reconsider whether it is the primary beneficiary of a variable interest entity:', '["Only at the initial investment date", "Every five years", "Only when the entity''s annual financial statements are issued", "On an ongoing basis whenever events indicate a change in circumstances"]'::jsonb, 3, 'Under ASC 810-10-35-4, a reporting entity must continuously reassess whether it is the primary beneficiary of a VIE whenever events or changes in circumstances occur that could affect the determination. This is an ongoing requirement, not limited to specific dates or intervals. Choice A is incorrect because changes in contractual terms, governance structures, or financial arrangements after the initial date can shift the primary beneficiary designation.', 'easy', 1),

-- Q26: hard / L4 — Downstream intercompany land sale with no depreciation unwind
(2, 'Consolidations', 'Sentinel Corp. owns 80% of Tower Inc. In Year 1, Sentinel sold land with a $500,000 carrying amount to Tower for $750,000. Tower still holds the land at the end of Year 3. What consolidation adjustment is needed in the Year 3 workpaper?', '["No adjustment because the gain was fully recognized in Year 1", "Reduce land by $250,000 and reduce beginning retained earnings by $250,000", "Reduce land by $250,000, reduce NCI by $50,000, and reduce retained earnings by $200,000", "Reduce land by $250,000 and recognize a $250,000 current-year loss"]'::jsonb, 1, 'Under ASC 810-10-45, when a parent sells land to a subsidiary at a gain and the land remains within the consolidated group, the unrealized gain must be eliminated every year until the asset is sold to an outside party. Since land is not depreciated, the full $250,000 remains unrealized. The workpaper entry reduces land to original cost and reverses the gain from retained earnings. Choice C incorrectly allocates to NCI, which applies to upstream (subsidiary-to-parent) sales, not downstream sales.', 'hard', 4),

-- Q27: medium / L3 — Cross-subsidiary intercompany sale elimination
(2, 'Consolidations', 'Regal Corp. owns 100% of both Alpha Inc. and Beta Inc. During the year, Alpha sold merchandise to Beta for $400,000 (cost to Alpha: $280,000). At year-end, Beta has resold 60% to external customers but retains 40% in ending inventory. What is the consolidation elimination for this transaction?', '["Eliminate $120,000 from cost of goods sold only", "Eliminate $48,000 from revenue and $48,000 from cost of goods sold", "Eliminate $400,000 from revenue and $400,000 from cost of goods sold, and reduce inventory by $48,000", "Eliminate $48,000 from revenue and reduce inventory by $48,000"]'::jsonb, 2, 'Under ASC 810-10-45, all intercompany transactions between consolidated entities must be eliminated, including sales between fellow subsidiaries. The full $400,000 intercompany revenue and cost of goods sold are eliminated. Unrealized profit in ending inventory = ($400,000 − $280,000) × 40% = $48,000, which reduces inventory and increases COGS. Choice B incorrectly eliminates only the unrealized profit amount rather than the full intercompany revenue and COGS.', 'medium', 3),

-- Q28: medium / L2 — Intercompany management fee elimination net effect
(2, 'Consolidations', 'Harbor Corp. owns 100% of Marina Inc. During the year, Harbor charged Marina a $600,000 management fee, which Marina recorded as an operating expense and Harbor recorded as fee revenue. In the consolidated income statement, what is the net effect of eliminating this intercompany fee?', '["No effect on consolidated net income", "$600,000 decrease in consolidated net income", "$600,000 increase in consolidated net income", "$300,000 decrease in consolidated net income"]'::jsonb, 0, 'Under ASC 810-10-45, intercompany management fees are eliminated in consolidation. Harbor''s $600,000 fee revenue and Marina''s $600,000 operating expense both cancel out, producing no net effect on consolidated net income. The elimination reduces both revenue and expense by equal amounts. Choice B incorrectly assumes only the expense is eliminated, which would misstate the consolidated entity''s results by ignoring the offsetting revenue.', 'medium', 2),

-- Q29: easy / L2 — Stock issuance costs in a business combination reduce APIC
(2, 'Consolidations', 'In a business combination, Westfield Corp. incurs $150,000 in legal and registration costs to issue its common stock as acquisition consideration. Under ASC 805, these stock issuance costs are:', '["Added to goodwill as part of acquisition costs", "Deducted from additional paid-in capital", "Expensed as acquisition costs on the income statement", "Recorded as a deferred asset and amortized"]'::jsonb, 1, 'Under ASC 805-10-25-23 and SEC Staff guidance, costs to issue equity securities such as registration fees and legal costs reduce the proceeds of the equity issuance and are deducted from additional paid-in capital. They are distinct from direct acquisition costs (advisory, legal due diligence) which are expensed. Choice C is incorrect because stock issuance costs follow equity accounting rules and reduce APIC rather than flowing through the income statement.', 'easy', 2),

-- Q30: easy / L1 — NCI absorbs subsidiary losses even below zero
(2, 'Consolidations', 'Under ASC 810, when a consolidated subsidiary reports a net loss, the noncontrolling interest''s share of that loss is:', '["Ignored until the subsidiary returns to profitability", "Allocated to the noncontrolling interest even if it creates a deficit NCI balance", "Absorbed entirely by the parent company", "Capped at the noncontrolling interest''s original investment amount"]'::jsonb, 1, 'Under ASC 810-10-45-21, losses of a subsidiary are allocated to the noncontrolling interest based on its ownership percentage, even if this results in a deficit NCI balance within equity. Prior standards limited loss allocation to the NCI''s positive balance, but current GAAP removed that cap. Choice C is incorrect because the parent does not absorb the NCI''s proportionate share of losses; the NCI continues receiving its allocation regardless of its balance.', 'easy', 1)
;

COMMIT;
