-- Migration: Question generation — FAR batch 77 (30 questions)
-- Date: 2026-03-04
-- Topic: Inventory
-- Difficulty: 9E / 15M / 6H
-- Bloom's: L1:8 / L2:9 / L3:8 / L4:5

BEGIN;

INSERT INTO questions (section_id, topic, stem, choices, correct_index, explanation, difficulty, cognitive_level)
VALUES

-- Q1: medium / L2 — FOB destination goods in transit
(2, 'Inventory', 'Glendale Wholesale shipped $48,000 of merchandise to Baxter Retailers on December 29 under FOB destination terms. The goods were in transit on December 31 and arrived on January 3. Which company should include the $48,000 of in-transit inventory on its December 31 balance sheet?', '["Baxter Retailers, because legal title transfers at the time of shipment", "Baxter Retailers, because the buyer always owns goods once shipped", "Glendale Wholesale, because title does not transfer until the goods reach the buyer''s location", "Neither company, because goods in transit are excluded from inventory"]'::jsonb, 2, 'Under ASC 330 and UCC shipping terms, FOB destination means title transfers when goods arrive at the buyer''s location. Since the goods were in transit on December 31, Glendale retains title and must include them in its ending inventory. FOB shipping point, by contrast, transfers title at shipment, making goods the buyer''s inventory immediately upon dispatch.', 'medium', 2),

-- Q2: easy / L2 — Freight-in as inventoriable cost
(2, 'Inventory', 'Marlow Industries purchases raw materials for $60,000 and pays $3,500 in freight charges to have the materials delivered to its warehouse. How should the freight charges be classified?', '["As a selling expense on the income statement", "As an inventoriable cost added to the cost of the raw materials", "As a general and administrative expense", "As a separate intangible asset"]'::jsonb, 1, 'Under ASC 330-10-30, all costs necessary to bring inventory to its present location and condition are inventoriable, including freight-in. Freight-out (delivery to customers) is a selling expense, not an inventory cost. The $3,500 should be capitalized alongside the $60,000 materials cost.', 'easy', 2),

-- Q3: medium / L2 — Specific identification method applicability
(2, 'Inventory', 'Parkfield Jewelers sells high-end diamond rings, each with unique characteristics and price points ranging from $5,000 to $75,000. The controller is selecting an inventory cost flow method. Which method is most appropriate for this type of inventory?', '["FIFO, because it matches the physical flow of perishable goods", "LIFO, because it provides the best tax benefit on high-value items", "Weighted average, because it smooths out price fluctuations across units", "Specific identification, because each item is unique and individually distinguishable"]'::jsonb, 3, 'Under ASC 330-10-30-7, specific identification is most appropriate when inventory items are not interchangeable, such as unique, high-value items like jewelry, artwork, or custom goods. FIFO, LIFO, and weighted average are designed for fungible, interchangeable goods where tracking individual units is impractical.', 'medium', 2),

-- Q4: medium / L2 — Inventory overstatement effect on COGS and net income
(2, 'Inventory', 'Sterling Manufacturing accidentally overstated its December 31, Year 1 ending inventory by $22,000 due to a counting error. The error was not discovered until Year 2. What is the effect of this error on Year 1 cost of goods sold and net income before taxes?', '["COGS is understated by $22,000 and net income is overstated by $22,000", "COGS is overstated by $22,000 and net income is understated by $22,000", "COGS is understated by $22,000 and net income is understated by $22,000", "COGS and net income are both overstated by $22,000"]'::jsonb, 0, 'Under ASC 250, the periodic COGS formula is Beginning Inventory + Purchases − Ending Inventory. Overstating ending inventory by $22,000 reduces COGS by the same amount, which inflates gross profit and net income by $22,000. An understatement of ending inventory, by contrast, would overstate COGS and understate net income.', 'medium', 2),

-- Q5: medium / L3 — Self-correcting inventory errors over two periods
(2, 'Inventory', 'Redfield Corp. understated its Year 1 ending inventory by $15,000. The error was not discovered until Year 3. Assuming no other errors, what is the cumulative effect of this error on retained earnings at the end of Year 2?', '["Retained earnings is understated by $15,000", "Retained earnings is correctly stated", "Retained earnings is overstated by $15,000", "Retained earnings is understated by $30,000"]'::jsonb, 1, 'Under ASC 250, inventory errors are self-correcting over two periods. Understating Year 1 ending inventory overstates Year 1 COGS by $15,000 (reducing Year 1 income). That same understatement flows into Year 2 beginning inventory, understating Year 2 COGS by $15,000 (increasing Year 2 income). The two effects offset, leaving Year 2 ending retained earnings correctly stated.', 'medium', 3),

-- Q6: hard / L4 — Abnormal vs normal spoilage treatment
(2, 'Inventory', 'Oakmont Canning processes 100,000 units monthly, with normal spoilage averaging 2% of production (2,000 units at $8 each). In October, a cooling system malfunction caused total spoilage of 5,500 units. How should Oakmont account for the total October spoilage?', '["Charge all 5,500 units ($44,000) to inventory as a product cost", "Charge all 5,500 units ($44,000) to a period loss on the income statement", "Charge 2,000 normal units ($16,000) to a period loss and 3,500 abnormal units ($28,000) to inventory", "Charge 2,000 normal units ($16,000) to inventory and 3,500 abnormal units ($28,000) to a period loss"]'::jsonb, 3, 'Under ASC 330-10-30, normal spoilage is an expected production cost allocated to inventory as a product cost. Abnormal spoilage (5,500 − 2,000 = 3,500 units) is excluded from inventory and recognized as a period loss of $28,000 (3,500 × $8). Charging all spoilage to inventory would overstate the asset and violate the matching principle.', 'hard', 4),

-- Q7: medium / L3 — Moving average under perpetual system
(2, 'Inventory', 'Waverly Supply uses a perpetual inventory system with the moving-average method. On March 1, it had 400 units at $10 each ($4,000). On March 10, it purchased 600 units at $13 each ($7,800). On March 20, it sold 500 units. What is the cost of goods sold for the March 20 sale?', '["$5,000", "$6,500", "$5,900", "$5,500"]'::jsonb, 2, 'Under the perpetual moving-average method (ASC 330-10-30), a new weighted-average cost is computed after each purchase. After the March 10 purchase: ($4,000 + $7,800) / 1,000 units = $11.80 per unit. COGS for 500 units = 500 × $11.80 = $5,900. Under periodic weighted average, all period purchases would be averaged at period end, producing a different result.', 'medium', 3),

-- Q8: easy / L1 — Manufacturing inventory classifications
(2, 'Inventory', 'What are the three classifications of inventory reported by a manufacturing company?', '["Raw materials, work-in-process, and finished goods", "Direct materials, indirect materials, and overhead", "Beginning inventory, purchases, and ending inventory", "Current assets, noncurrent assets, and cost of goods sold"]'::jsonb, 0, 'Under ASC 330-10-45, a manufacturing entity classifies inventory into raw materials (unprocessed inputs), work-in-process (partially completed goods), and finished goods (completed items ready for sale). These categories reflect the stages of production and are separately disclosed in the balance sheet or notes.', 'easy', 1),

-- Q9: easy / L1 — Standard cost method acceptability
(2, 'Inventory', 'Under U.S. GAAP, when is the standard cost method an acceptable basis for valuing inventory?', '["Only when the entity uses LIFO for tax purposes", "When standard costs reasonably approximate actual costs and are regularly adjusted", "Only for entities with fewer than 500 employees", "When approved by the entity''s external auditor"]'::jsonb, 1, 'Under ASC 330-10-30-12, standard costs are acceptable for inventory valuation only if adjusted at reasonable intervals to reflect current conditions, such that results reasonably approximate actual cost. If standard costs deviate significantly from actual costs, the inventory valuation is materially misstated and must be corrected.', 'easy', 1),

-- Q10: medium / L2 — Cost of goods manufactured calculation
(2, 'Inventory', 'Prescott Manufacturing reports: raw materials used $120,000, direct labor $85,000, factory overhead applied $68,000, selling expenses $42,000, beginning work-in-process $35,000, and ending work-in-process $28,000. What is the cost of goods manufactured?', '["$273,000", "$308,000", "$280,000", "$322,000"]'::jsonb, 2, 'Under ASC 330, cost of goods manufactured equals beginning WIP plus total manufacturing costs minus ending WIP: $35,000 + $120,000 + $85,000 + $68,000 − $28,000 = $280,000. Selling expenses ($42,000) are period costs excluded from inventory and manufacturing cost calculations.', 'medium', 2),

-- Q11: medium / L3 — Inventory shrinkage recognition
(2, 'Inventory', 'Hartwell Stores conducts a year-end physical count and finds its perpetual inventory records show $485,000, but the physical count totals $471,000. The $14,000 difference is attributed to normal shoplifting losses. How should Hartwell account for this difference?', '["Record a $14,000 debit to a contra asset account and disclose separately", "Reclassify $14,000 from inventory to accounts receivable", "No adjustment is needed because the perpetual system is more accurate than a physical count", "Reduce inventory by $14,000 and recognize the shrinkage as a component of cost of goods sold"]'::jsonb, 3, 'Under ASC 330, when a physical count reveals inventory shrinkage, the perpetual records must be adjusted to match the physical count. Normal shrinkage is typically charged to COGS. The entry debits COGS and credits Inventory for $14,000. Ignoring the physical count would overstate inventory on the balance sheet.', 'medium', 3),

-- Q12: easy / L1 — Bill-and-hold arrangement definition
(2, 'Inventory', 'What is a bill-and-hold arrangement under U.S. GAAP?', '["A sale in which the seller retains physical possession of goods at the buyer''s request but transfers control to the buyer", "A consignment arrangement where the consignee holds goods until sold", "A layaway plan where the buyer makes installment payments before delivery", "A financing arrangement where inventory is pledged as collateral"]'::jsonb, 0, 'Under ASC 606-10-55-81 through 84, a bill-and-hold arrangement is a contract where the seller bills the customer but retains physical possession at the customer''s request. Revenue is recognized when control transfers, provided the arrangement has a substantive reason and the goods are separately identified. This differs from consignment, where the consignor retains title.', 'easy', 1),

-- Q13: medium / L2 — Goods held on approval ownership
(2, 'Inventory', 'Dalton Electronics ships $32,000 of merchandise to Kline Corp. under a sale-on-approval agreement. On December 31, Kline has not yet accepted or rejected the goods. Which company should include the $32,000 in its ending inventory?', '["Kline Corp., because physical possession determines ownership", "Dalton Electronics, because title does not transfer until the buyer accepts the goods", "Neither company, because sale-on-approval goods are classified as prepaid expenses", "Both companies should each record 50% of the value"]'::jsonb, 1, 'Under ASC 606-10-55-80 and UCC Section 2-327, goods shipped on approval remain the seller''s property until the buyer formally accepts them. Since Kline has not accepted, Dalton retains title and must include the $32,000 in its own inventory. Kline recording these goods would incorrectly overstate its assets before acceptance occurs.', 'medium', 2),

-- Q14: medium / L3 — Purchase returns effect on COGS
(2, 'Inventory', 'Camden Supply had beginning inventory of $65,000, gross purchases of $310,000, purchase returns of $18,000, freight-in of $9,000, and ending inventory per physical count of $72,000. What is Camden''s cost of goods sold?', '["$312,000", "$276,000", "$294,000", "$303,000"]'::jsonb, 2, 'Under ASC 330, COGS under the periodic system is beginning inventory ($65,000) plus net purchases ($310,000 − $18,000 = $292,000) plus freight-in ($9,000) minus ending inventory ($72,000) = $294,000. Purchase returns must reduce gross purchases before computing goods available for sale. Omitting the $18,000 returns would overstate COGS.', 'medium', 3),

-- Q15: medium / L3 — Change from LIFO to FIFO accounting treatment
(2, 'Inventory', 'Fernwood Corp. changes its inventory method from LIFO to FIFO in Year 3. Under ASC 250, how should this accounting change be reported?', '["Restate prior periods retrospectively and adjust beginning retained earnings of the earliest period presented", "Apply prospectively from Year 3 forward with no restatement of prior periods", "Record a cumulative adjustment in Year 3 other comprehensive income", "Disclose the change in the notes only with no financial statement adjustment"]'::jsonb, 0, 'Under ASC 250-10-45-5, a change in inventory costing method is a change in accounting principle requiring retrospective application. Prior-period financial statements are restated as if the new method had always been used, with an adjustment to beginning retained earnings. Prospective treatment applies to changes in estimates, not changes in accounting principles.', 'medium', 3),

-- Q16: easy / L1 — Dollar-value LIFO deflation purpose
(2, 'Inventory', 'Under the dollar-value LIFO method, what is the purpose of deflating ending inventory at current-year prices to base-year prices?', '["To determine the entity''s taxable income for the current year", "To convert inventory from retail prices to cost prices", "To calculate the cost-to-retail ratio for the retail inventory method", "To measure real inventory growth by removing the effects of price changes"]'::jsonb, 3, 'Under ASC 330-10-30 and IRC Reg. 1.472-8, dollar-value LIFO deflates current-year ending inventory to base-year prices to isolate real quantity changes from price inflation. If the deflated amount exceeds beginning inventory at base-year cost, a new LIFO layer is added. Without deflation, price increases alone would create phantom layers.', 'easy', 1),

-- Q17: easy / L1 — Retail method FIFO variant exclusion
(2, 'Inventory', 'When applying the retail inventory method using the FIFO cost flow assumption, which component is excluded from the cost-to-retail ratio?', '["Net markdowns", "Net purchases at retail", "Beginning inventory at both cost and retail", "Net markups"]'::jsonb, 2, 'Under ASC 330-10-30, the FIFO retail method excludes beginning inventory from the cost-to-retail ratio. This approach assumes the oldest goods (beginning inventory) sell first, so only current-period layers (purchases, markups, and markdowns) determine the ratio applied to ending inventory. The average cost method, by contrast, includes beginning inventory.', 'easy', 1),

-- Q18: easy / L1 — Net markup definition
(2, 'Inventory', 'In the context of the retail inventory method, what is a net markup?', '["The original selling price minus the cost of goods", "The increase in retail price above the original retail price, less any markup cancellations", "A reduction in retail price below the original retail price", "The gross profit percentage applied to net sales"]'::jsonb, 1, 'Under ASC 330-10-30, a markup (additional markup) is an increase in retail price above the original selling price. Net markups equal total markups minus markup cancellations. A markdown, by contrast, is a decrease below the original retail price. These distinctions determine the cost-to-retail ratio under various retail method variants.', 'easy', 1),

-- Q19: hard / L4 — Interest capitalization on qualifying inventory
(2, 'Inventory', 'Rutherford Distillers ages whiskey for three years before sale. Average accumulated expenditures on aging inventory during the year are $1,800,000. The company''s only borrowing is $2,400,000 at 6% annually (total interest $144,000). Temporary investment income is $12,000. Under ASC 835-20, how much interest should be capitalized to inventory, and what is the income statement interest expense?', '["Capitalize $108,000 to inventory; recognize $36,000 as interest expense", "Capitalize $144,000 to inventory; recognize $0 as interest expense", "Capitalize $96,000 to inventory; recognize $48,000 as interest expense", "Capitalize $0 because interest cannot be added to inventory"]'::jsonb, 0, 'Under ASC 835-20-30, interest is capitalized on qualifying assets requiring a substantial period for preparation, including aged inventory like whiskey. Capitalizable interest = avoidable interest ($1,800,000 × 6% = $108,000), capped at total actual interest ($144,000). The remaining $36,000 is expensed. Investment income ($12,000) does not offset the capitalized amount per ASC 835-20-15.', 'hard', 4),

-- Q20: medium / L3 — Interim reporting gross profit method limitations
(2, 'Inventory', 'Lakewood Corp. prepares quarterly interim financial statements and uses the gross profit method to estimate inventory each quarter since physical counts occur only at year-end. Under ASC 270, what is the primary concern with this practice?', '["The gross profit method is prohibited for all interim reporting under ASC 270", "Interim inventory estimates must always use the retail method instead", "The method is acceptable only when the entity uses FIFO for annual reporting", "The method may produce unreliable estimates if the actual gross profit rate changes due to seasonal or product mix shifts, requiring disclosure"]'::jsonb, 3, 'Under ASC 270-10-45-4, the gross profit method is acceptable for interim inventory estimation but has inherent limitations. If the gross profit rate fluctuates seasonally or due to product mix changes, estimates may differ materially from physical counts. The estimation method requires disclosure, and any significant differences should be adjusted.', 'medium', 3),

-- Q21: medium / L2 — Lower of cost or market floor calculation
(2, 'Inventory', 'Whitfield Corp. uses LIFO and has an inventory item with cost of $50, replacement cost of $30, selling price of $60, estimated selling costs of $8, and a normal profit margin of $12. Under the lower of cost or market rule, what is the floor value?', '["$30", "$40", "$52", "$48"]'::jsonb, 1, 'Under ASC 330-10-35 for LIFO entities, the lower of cost or market rule defines the floor as NRV minus a normal profit margin. NRV = selling price ($60) less selling costs ($8) = $52 (the ceiling). Floor = $52 − $12 normal profit = $40. Since replacement cost ($30) is below the floor, designated market value is the floor ($40), not replacement cost.', 'medium', 2),

-- Q22: medium / L2 — Basket purchase allocation to inventory
(2, 'Inventory', 'Trenton Retailers purchases a lot of mixed merchandise from a liquidating competitor for $180,000. The lot contains electronics (fair value $120,000), furniture (fair value $60,000), and clothing (fair value $20,000). How should Trenton allocate the purchase price to inventory?', '["Based on relative fair values: electronics $108,000, furniture $54,000, clothing $18,000", "Equally at $60,000 to each category", "Electronics at $120,000 with the remaining $60,000 split between furniture and clothing", "Record the entire $180,000 as a single inventory line item"]'::jsonb, 0, 'Under ASC 330 and general allocation principles, a basket (lump-sum) purchase is allocated based on relative fair values. Total fair value is $200,000. Electronics: ($120,000 / $200,000) × $180,000 = $108,000; furniture: ($60,000 / $200,000) × $180,000 = $54,000; clothing: ($20,000 / $200,000) × $180,000 = $18,000. Equal allocation ignores relative values.', 'medium', 2),

-- Q23: hard / L4 — Consignment accounting (consignor gross profit)
(2, 'Inventory', 'Beaumont Manufacturing consigns 500 units (cost $40 each) to a dealer and pays $2,000 in freight. The dealer sells 350 units at $70 each, deducts a 15% commission, and remits the net proceeds. What is Beaumont''s gross profit on the consignment sales, and what is the cost of the 150 unsold consigned units?', '["Gross profit $6,825; unsold inventory $6,000", "Gross profit $10,500; unsold inventory $6,600", "Gross profit $5,425; unsold inventory $6,600", "Gross profit $5,425; unsold inventory $6,000"]'::jsonb, 2, 'Under ASC 606 and ASC 330, the consignor recognizes revenue only when the consignee sells to end customers. Revenue = 350 × $70 = $24,500. Deductions: COGS ($14,000), prorated freight (350/500 × $2,000 = $1,400), and commission (15% × $24,500 = $3,675). Gross profit = $24,500 − $14,000 − $1,400 − $3,675 = $5,425. Unsold inventory = (150 × $40) + (150/500 × $2,000) = $6,600.', 'hard', 4),

-- Q24: hard / L4 — Perpetual vs periodic LIFO COGS difference
(2, 'Inventory', 'Briarcliff Supply uses LIFO: beginning inventory 200 units at $10; January 8 purchase 300 units at $12; January 15 sale of 400 units; January 22 purchase 100 units at $15. Under perpetual LIFO, COGS is computed at each sale date. Under periodic LIFO, COGS is computed at period end. What is the difference in January COGS between the two methods?', '["Periodic COGS is $300 higher than perpetual", "No difference; LIFO produces the same result under both systems", "Perpetual COGS is $500 higher than periodic", "Periodic COGS is $500 higher than perpetual"]'::jsonb, 3, 'Under perpetual LIFO, the January 15 sale draws from inventory on hand at that date: 300 @ $12 + 100 @ $10 = $4,600. Under periodic LIFO, all January purchases are available: 100 @ $15 + 300 @ $12 = $5,100. The $500 difference arises because periodic LIFO includes the January 22 purchase in the "last-in" pool, while perpetual uses only units available at the sale date.', 'hard', 4),

-- Q25: easy / L1 — Periodic system purchases account
(2, 'Inventory', 'Under the periodic inventory system, how are inventory purchases initially recorded?', '["In a temporary Purchases account, separate from the Inventory account", "Directly to the Inventory asset account as each purchase occurs", "As cost of goods sold at the time of purchase", "In an Other Comprehensive Income account until period end"]'::jsonb, 0, 'Under ASC 330 and the periodic system, purchases are recorded in a temporary Purchases account (along with related accounts like Purchase Returns and Freight-In). The Inventory account is updated only at period end after a physical count. The perpetual system, by contrast, debits the Inventory account directly with each purchase.', 'easy', 1),

-- Q26: medium / L3 — Interim LIFO liquidation replacement accrual
(2, 'Inventory', 'Dunmore Metals uses LIFO. During Q1, the company temporarily liquidated a LIFO layer costing $22 per unit (current replacement cost $58 per unit). Management expects to replace the inventory by year-end. How should Dunmore report cost of goods sold in its Q1 interim financial statements?', '["At the old LIFO layer cost of $22 per unit, reflecting the actual cost flow", "At the expected replacement cost of $58 per unit, because the liquidation is expected to be temporary", "At the average of the old cost and replacement cost ($40 per unit)", "At replacement cost only if a binding purchase order has been placed"]'::jsonb, 1, 'Under ASC 270-10-45-6, when a LIFO liquidation occurs in an interim period and replacement is expected by year-end, COGS should be charged at expected replacement cost, not the old layer cost. This prevents interim income from being artificially inflated by a temporary inventory drawdown. If the liquidation becomes permanent, the actual old-layer cost is reported.', 'medium', 3),

-- Q27: hard / L3 — Absorption vs variable costing income difference
(2, 'Inventory', 'Rockford Manufacturing produced 10,000 units and sold 8,000 units with no beginning inventory. Variable manufacturing cost is $15 per unit. Fixed manufacturing overhead totals $50,000 ($5 per unit). Under absorption costing, fixed overhead is inventoried; under variable costing, it is expensed immediately. What is the difference in operating income between the two methods?', '["Variable costing reports $10,000 higher operating income", "No difference because total costs are the same", "Absorption costing reports $10,000 higher operating income", "Absorption costing reports $50,000 higher operating income"]'::jsonb, 2, 'Under ASC 330 and cost accounting principles, absorption costing includes fixed overhead in product costs, while variable costing expenses it as a period cost. With 2,000 unsold units, absorption costing defers $10,000 of fixed overhead (2,000 × $5) in ending inventory. Absorption income is therefore $10,000 higher than variable costing income.', 'hard', 3),

-- Q28: easy / L1 — Pledged inventory disclosure requirement
(2, 'Inventory', 'Under U.S. GAAP, when inventory is pledged as collateral for a loan, what is the required accounting treatment?', '["Remove the inventory from the balance sheet and record a receivable", "Reduce the inventory''s carrying value to the loan amount", "Reclassify the inventory as a noncurrent asset", "Disclose the pledge in the notes to the financial statements"]'::jsonb, 3, 'Under ASC 330-10-50 and ASC 860, inventory pledged as collateral remains on the entity''s balance sheet at its normal carrying value. The entity must disclose the nature and extent of the pledge in the notes. The inventory is not removed or reclassified because the pledgor retains title and risks of ownership.', 'easy', 1),

-- Q29: hard / L4 — Dollar-value LIFO multiple pools layer analysis
(2, 'Inventory', 'Hargrove Industries uses dollar-value LIFO with two pools. Pool A has beginning base-year cost of $200,000; year-end current-year cost of $231,000 with price index 1.10. Pool B has beginning base-year cost of $350,000; year-end current-year cost of $357,000 with price index 1.05. Which pool(s) added a new LIFO layer?', '["Only Pool A, because its deflated ending ($210,000) exceeds its beginning base-year cost ($200,000)", "Both pools, because their current-year costs exceed their beginning base-year costs", "Only Pool B, because its price index is lower and therefore more conservative", "Neither pool, because all increases are attributable entirely to inflation"]'::jsonb, 0, 'Under ASC 330-10-30 and IRC Reg. 1.472-8, each dollar-value LIFO pool is analyzed independently by deflating to base-year prices. Pool A: $231,000 / 1.10 = $210,000 exceeds $200,000, so a $10,000 real layer was added. Pool B: $357,000 / 1.05 = $340,000 is below $350,000, indicating quantities declined and an existing layer was partially eroded. Comparing current-year costs without deflation ignores inflation.', 'hard', 4),

-- Q30: medium / L2 — Inventory write-down journal entry under LCNRV
(2, 'Inventory', 'Elmwood Supply carries FIFO inventory at a cost of $125,000. At year-end, net realizable value has declined to $109,000. Under ASC 330, what journal entry should Elmwood record?', '["Debit Inventory $16,000; Credit Sales Revenue $16,000", "Debit Cost of Goods Sold (or Loss) $16,000; Credit Inventory (or Allowance to Reduce Inventory to NRV) $16,000", "Debit Other Comprehensive Income $16,000; Credit Inventory $16,000", "No entry is needed because FIFO inventory must remain at historical cost"]'::jsonb, 1, 'Under ASC 330-10-35 (as amended by ASU 2015-11), FIFO inventory must be written down when NRV falls below cost. The $16,000 write-down ($125,000 − $109,000) is recognized as a charge to COGS or a separate loss account, with a credit to Inventory or a contra-asset allowance. The loss flows through the income statement, not OCI.', 'medium', 2)
;

COMMIT;
