-- Migration: Question generation — FAR batch 85 (30 questions)
-- Date: 2026-03-04
-- Topic: Accounting Changes and Error Corrections
-- Difficulty: 9E / 15M / 6H
-- Bloom's: L1:8 / L2:9 / L3:8 / L4:5

BEGIN;

INSERT INTO questions (section_id, topic, stem, choices, correct_index, explanation, difficulty, cognitive_level)
VALUES

-- Q1: medium / L3 — Change in estimate effected by a change in principle (hybrid)
(2, 'Accounting Changes and Error Corrections', 'Redstone Industries changes its depreciation method from sum-of-the-years-digits to straight-line on January 1, Year 4, and also revises the remaining useful life of its machinery from 8 years to 5 years at the same time. Under ASC 250, how should Redstone account for these simultaneous changes?', '["Apply both changes prospectively from the beginning of Year 4", "Apply the depreciation method change retrospectively and the useful life change prospectively", "Apply both changes retrospectively to all prior periods presented", "Apply the useful life change retrospectively and the depreciation method change prospectively"]'::jsonb, 0, 'Under ASC 250-10-45-18, a change in depreciation method is treated as a change in accounting estimate effected by a change in accounting principle and is applied prospectively. When combined with a simultaneous change in useful life (also an estimate change), both are applied prospectively from the beginning of the current period. Option B is incorrect because ASC 250 does not require retrospective application for depreciation method changes — they are inseparable from the estimate.', 'medium', 3),

-- Q2: easy / L1 — Definition of preferability letter
(2, 'Accounting Changes and Error Corrections', 'Under ASC 250, what is the auditor''s role when a company voluntarily changes an accounting principle?', '["Issue a preferability letter confirming the new method is preferable", "Approve the change before the company can implement it", "Recalculate all prior-period financial statements independently", "Determine whether the change qualifies as a change in estimate"]'::jsonb, 0, 'Under ASC 250-10-45-2 and AU-C 708, when an entity voluntarily changes an accounting principle, the auditor must evaluate whether the newly adopted principle is preferable in the circumstances and issue a preferability letter. The auditor does not approve or implement the change (Option B) but rather assesses whether the entity has justified the change as preferable.', 'easy', 1),

-- Q3: medium / L2 — Big R restatement vs little r revision
(2, 'Accounting Changes and Error Corrections', 'Thornton Corp. (a public company) discovers a $15,000 error in its Year 2 financial statements. The error was immaterial to Year 2 when it occurred but correcting it entirely in Year 3 would be material to Year 3 income. Under SEC guidance, how should Thornton handle this error?', '["Correct the error in Year 3 as a current-period charge", "File a restatement (Big R) of the Year 2 financial statements", "Record a revision (little r) by correcting Year 2 comparatives without amending prior filings", "Disclose the error in the footnotes but make no adjustment"]'::jsonb, 2, 'Under SEC Staff guidance and SAB 108, when an error is immaterial to the period in which it occurred but would be material if corrected entirely in the current period, the entity should revise the prior-period comparative statements (a ''little r'' revision) rather than filing an amended 10-K (Big R restatement). Option A is incorrect because iron curtain analysis shows the cumulative effect is material and cannot simply be charged to the current period.', 'medium', 2),

-- Q4: medium / L2 — SAB 108 dual approach (iron curtain + rollover)
(2, 'Accounting Changes and Error Corrections', 'Whitmore Industries has an error that understated expenses by $10,000 in each of Years 1 through 3. In Year 4, the company considers correcting the full $30,000. Under SEC SAB 108, the company must evaluate materiality using which approach?', '["Only the rollover approach, which evaluates each year''s $10,000 error individually", "Only the iron curtain approach, which evaluates the $30,000 cumulative balance sheet effect", "A dual approach evaluating both the $30,000 cumulative effect and each year''s $10,000 error", "The higher of the rollover or iron curtain amount, but not both simultaneously"]'::jsonb, 2, 'Under SAB 108, an entity must quantify errors using both the rollover (income statement) approach and the iron curtain (balance sheet) approach and evaluate materiality under each. If the error is material under either method, correction is required. Option A is incorrect because using only the rollover approach could miss a material cumulative balance sheet misstatement. Option D is incorrect because both methods must be considered, not just the higher amount.', 'medium', 2),

-- Q5: medium / L3 — Interim error correction and restatement of prior interim periods
(2, 'Accounting Changes and Error Corrections', 'In the third quarter of Year 2, Calloway Corp. discovers that it overstated revenue by $80,000 in the first quarter of Year 2. The Year 2 annual statements have not yet been issued. Under ASC 250-10-45-23, how should Calloway handle this error in its interim reporting?', '["Correct the entire $80,000 in the third-quarter interim statements as discovered", "Restate the previously issued first-quarter interim financial data when presented in later interim or annual reports", "Treat the $80,000 as a change in accounting estimate and apply it prospectively", "Defer the correction until the Year 2 annual financial statements are prepared"]'::jsonb, 1, 'Under ASC 250-10-45-23, if an error is discovered in a current-year interim period that relates to a prior interim period of the same fiscal year, the prior interim data must be restated when subsequently presented. Option A is incorrect because simply correcting the error in Q3 would misstate both Q1 and Q3 figures. Option C is incorrect because this is an error correction, not a change in estimate.', 'medium', 3),

-- Q6: hard / L4 — Principle change effect on deferred tax balances
(2, 'Accounting Changes and Error Corrections', 'Atlas Manufacturing changes from LIFO to FIFO on January 1, Year 3, and presents two years of comparative statements. The LIFO reserve at December 31, Year 1, was $180,000 and at December 31, Year 2, was $240,000. Atlas uses LIFO for tax purposes and the tax rate is 25%. Evaluate the deferred tax effects that Atlas must recognize in the restated comparative balance sheets and the impact on the Year 2 opening retained earnings adjustment.', '["Record DTL of $45,000 at 12/31/Y1 and $60,000 at 12/31/Y2; adjust Y2 opening RE by $135,000", "Record DTL of $45,000 at 12/31/Y1 and $60,000 at 12/31/Y2; adjust Y1 opening RE by $135,000", "Record DTA of $45,000 at 12/31/Y1 and $60,000 at 12/31/Y2; adjust Y1 opening RE by $135,000", "Record DTL of $45,000 at 12/31/Y1 and $60,000 at 12/31/Y2; adjust Y1 opening RE by $180,000"]'::jsonb, 1, 'Under ASC 250-10-45-5, retrospective application requires restating all periods presented. Switching to FIFO increases inventory (and assets) by the LIFO reserve, creating a temporary difference since tax remains on LIFO. DTL = LIFO reserve × 25%: $45,000 at 12/31/Y1 and $60,000 at 12/31/Y2. The after-tax cumulative effect at the beginning of the earliest period presented (Y1 opening) equals the pre-Y1 LIFO reserve × 75% = $135,000 net RE adjustment. Option A incorrectly places the adjustment at Y2 opening instead of Y1 opening.', 'hard', 4),

-- Q7: easy / L1 — Prospective application affects only current and future periods
(2, 'Accounting Changes and Error Corrections', 'Under ASC 250, prospective application of an accounting change means that the change affects which periods?', '["Only the current and future periods", "All prior periods presented in comparative statements", "Only the period of the change, with no effect on future periods", "All periods since the entity''s inception"]'::jsonb, 0, 'Under ASC 250-10-45-17, prospective application means recognizing the effect of the change in the current period and future periods. Prior periods are not restated. Option B describes retrospective application. Option C is incorrect because prospective changes inherently affect future periods by changing the ongoing methodology.', 'easy', 1),

-- Q8: medium / L3 — Inventory error spanning two consecutive years
(2, 'Accounting Changes and Error Corrections', 'Bartlett Corp. overstated ending inventory by $50,000 in Year 1 and understated ending inventory by $20,000 in Year 2. Year 3 books are still open. Ignoring taxes, what is the cumulative effect of these two errors on retained earnings as of December 31, Year 2?', '["Overstated by $50,000", "Understated by $20,000", "Overstated by $30,000", "Understated by $70,000"]'::jsonb, 1, 'Under ASC 250, the Year 1 ending inventory overstatement understated Year 1 COGS by $50,000 (overstating Year 1 NI by $50,000). That overstatement carries into Year 2 beginning inventory, overstating Year 2 COGS by $50,000 (understating Year 2 NI by $50,000). These effects net to zero in cumulative RE at 12/31/Year 2. The separate Year 2 ending inventory understatement of $20,000 overstates Year 2 COGS, understating Year 2 NI by $20,000. Net cumulative effect: RE is understated by $20,000. Option A incorrectly treats only the Year 1 error without considering the counterbalancing effect.', 'medium', 3),

-- Q9: easy / L1 — Definition: what qualifies as a change in reporting entity
(2, 'Accounting Changes and Error Corrections', 'Under ASC 250, which type of accounting change requires the entity to retrospectively adjust financial statements for all prior periods presented as if the new entity had always existed?', '["A change in accounting estimate", "A correction of an error", "A change in reporting entity", "A change from non-GAAP to GAAP"]'::jsonb, 2, 'Under ASC 250-10-45-21, a change in reporting entity (e.g., presenting consolidated statements instead of individual-entity statements) requires retrospective adjustment of all prior periods as if the new reporting entity had always existed. Option A is incorrect because estimate changes are applied prospectively. Option B involves restatement, not retrospective application as-if the entity always existed.', 'easy', 1),

-- Q10: medium / L3 — Catch-up depreciation when estimate change affects accumulated depreciation
(2, 'Accounting Changes and Error Corrections', 'On January 1, Year 1, Greystone Corp. purchased equipment for $500,000 with a 10-year life and no salvage value (straight-line). At the beginning of Year 6, the estimated total useful life is revised to 8 years total (3 years remaining from Year 6). Under ASC 250, what is the depreciation expense for Year 6?', '["$50,000", "$62,500", "$83,333", "$100,000"]'::jsonb, 2, 'Under ASC 250-10-45-17, a change in useful life is a change in estimate applied prospectively. Book value at January 1, Year 6 = $500,000 − (5 × $50,000) = $250,000. New remaining life = 3 years (Years 6, 7, 8). Depreciation for Year 6 = $250,000 ÷ 3 = $83,333. Option A ($50,000) is the old annual amount. Option B ($62,500) incorrectly uses $500,000 ÷ 8 years total.', 'medium', 3),

-- Q11: easy / L1 — Scope of ASC 250: what is excluded
(2, 'Accounting Changes and Error Corrections', 'Which of the following is specifically excluded from the scope of ASC 250, Accounting Changes and Error Corrections?', '["A voluntary change from LIFO to FIFO inventory method", "A change in depreciation method from DDB to straight-line", "The initial adoption of an accounting principle for a new type of transaction", "A change in the estimated useful life of equipment"]'::jsonb, 2, 'Under ASC 250-10-15-3, the initial adoption of an accounting principle for transactions or events that did not previously occur or were immaterial is not considered a change in accounting principle and is excluded from ASC 250. Option A is a voluntary principle change clearly within ASC 250 scope. Option D is a standard estimate change within scope.', 'easy', 1),

-- Q12: hard / L4 — Non-counterbalancing error over three years
(2, 'Accounting Changes and Error Corrections', 'On January 1, Year 1, Hawthorn Corp. purchased a patent for $150,000 with a 15-year useful life but incorrectly expensed the entire cost in Year 1. The error is discovered at the beginning of Year 4 before closing the books. Ignoring taxes, evaluate the correcting entry Hawthorn must record and the net effect on Year 4 beginning retained earnings.', '["Debit Patent $150,000, credit Accumulated Amortization $30,000 and Retained Earnings $120,000", "Debit Patent $120,000, credit Retained Earnings $120,000", "Debit Patent $150,000, credit Accumulated Amortization $30,000 and Retained Earnings $120,000; RE is understated by $120,000", "Debit Patent $150,000, credit Accumulated Amortization $30,000 and Prior Period Adjustment $120,000; RE is overstated by $120,000"]'::jsonb, 2, 'Under ASC 250-10-45-23, this non-counterbalancing error requires restatement. The patent should have been capitalized at $150,000 and amortized $10,000/year for 3 years (Years 1-3). Correcting entry: Dr. Patent $150,000, Cr. Accumulated Amortization $30,000 (3 × $10,000), Cr. Retained Earnings $120,000. Beginning RE was understated by $120,000 because the full $150,000 was expensed in Year 1 instead of $10,000 amortization per year ($30,000 total through Year 3). Net understatement = $150,000 − $30,000 = $120,000. Option B omits the gross asset and accumulated amortization presentation.', 'hard', 4),

-- Q13: hard / L4 — Change from cost to equity method upon gaining significant influence
(2, 'Accounting Changes and Error Corrections', 'Monarch Inc. held a 10% interest in Falcon Corp. and accounted for it at cost. On April 1, Year 3, Monarch purchases an additional 15% interest, giving it 25% ownership and significant influence. Under ASC 250 and ASC 323, evaluate how Monarch should account for this change.', '["Apply the equity method prospectively from April 1, Year 3, with no adjustment to the carrying amount of the original 10% interest", "Restate all prior periods to reflect the equity method as if Monarch always had significant influence", "Apply the equity method retroactively to the original 10% investment from its acquisition date, adjusting retained earnings for the difference", "Record the change as a change in estimate, applying the equity method only to the newly acquired 15% interest"]'::jsonb, 2, 'Under ASC 323-10-35-33, when an investor obtains significant influence over an investee, it must apply the equity method retroactively to the date of the original investment. The investor adjusts the carrying amount of the previously held interest and retained earnings as if the equity method had always been applied. Option A is incorrect because ASC 323 requires retroactive (not prospective) application. Option D incorrectly treats this as an estimate change.', 'hard', 4),

-- Q14: easy / L1 — Definition of direct vs indirect effects
(2, 'Accounting Changes and Error Corrections', 'Under ASC 250, what are "indirect effects" of a change in accounting principle?', '["Effects on current or future cash flows resulting from the change applied retrospectively", "Changes to prior-period financial statement line items from restating the accounting method", "The cumulative effect of the change on retained earnings at the beginning of the earliest period", "Adjustments to comparative per-share amounts from the accounting change"]'::jsonb, 0, 'Under ASC 250-10-20, indirect effects are changes to current or future cash flows that result from applying a change in accounting principle retrospectively (e.g., royalty payments, profit-sharing contributions that change because restated income differs). Option B describes direct effects on financial statement amounts. Option C describes the cumulative effect adjustment, which is also a direct effect.', 'easy', 1),

-- Q15: medium / L2 — Disclosure of indirect effects separately
(2, 'Accounting Changes and Error Corrections', 'Lumina Corp. voluntarily changes its inventory method from LIFO to FIFO and applies the change retrospectively. The restated higher income triggers an additional $45,000 in nondiscretionary bonus payments to employees. Under ASC 250-10-50-7, how should Lumina report this $45,000 indirect effect?', '["Include the $45,000 in the retrospective restatement of prior-period income", "Recognize the $45,000 in the period the change is made and disclose the amount separately", "Exclude the $45,000 from all periods because it is a cash flow effect, not an accounting effect", "Offset the $45,000 against the cumulative effect adjustment to retained earnings"]'::jsonb, 1, 'Under ASC 250-10-50-7, indirect effects such as bonus payments linked to restated income are recognized in the period of the change (not retroactively) and must be disclosed separately. Option A is incorrect because indirect effects are never included in the retrospective restatement of prior periods. Option C is incorrect because the bonus obligation is an accounting liability that must be recognized.', 'medium', 2),

-- Q16: medium / L3 — Change in amortization method for finite-life intangibles
(2, 'Accounting Changes and Error Corrections', 'Skyline Technologies has been amortizing a customer-list intangible asset using the straight-line method over 10 years. At the beginning of Year 5, management determines that an accelerated method better reflects the pattern of economic benefit consumption. Under ASC 250, how should Skyline account for this change?', '["Retrospectively adjust all prior periods to reflect the accelerated method", "Apply the accelerated method prospectively to the remaining book value over the remaining 6 years", "Recognize a cumulative catch-up adjustment in Year 5 income for the prior-period difference", "Restate Year 4 comparatives under the accelerated method but not earlier years"]'::jsonb, 1, 'Under ASC 250-10-45-18, a change in the amortization method for an intangible asset is treated as a change in accounting estimate effected by a change in accounting principle and is applied prospectively. Skyline applies the accelerated method to the remaining book value over the remaining useful life starting in Year 5. Option A is incorrect because this type of change does not require retrospective application. Option C is incorrect because there is no catch-up adjustment.', 'medium', 3),

-- Q17: medium / L3 — Error correction when only current-year statements are presented
(2, 'Accounting Changes and Error Corrections', 'Durant Corp. discovers a material error that overstated Year 1 net income by $60,000 (after tax). Durant presents only Year 2 financial statements with no comparative Year 1 data. Under ASC 250, how should Durant correct this error?', '["Adjust the opening balance of retained earnings for Year 2 and disclose the nature and effect of the error", "Report the $60,000 as an expense in the Year 2 income statement", "No action is required since Year 1 statements are not presented comparatively", "Record a contra-equity account for the error and amortize it over 5 years"]'::jsonb, 0, 'Under ASC 250-10-45-23 and 250-10-50-7, when prior-period financial statements are not presented, the entity must adjust the opening balance of retained earnings for the earliest period presented (Year 2 opening) and disclose the nature and effect of the error. Option B is incorrect because error corrections are never reported as current-period income or expense. Option C is incorrect because correction is always required regardless of comparative presentation.', 'medium', 3),

-- Q18: hard / L4 — Prohibition on changing to a less preferable method
(2, 'Accounting Changes and Error Corrections', 'Zenith Corp., a public company, voluntarily changed from FIFO to LIFO for inventory valuation three years ago and obtained a preferability letter from its auditor. Now Zenith proposes changing back to FIFO, citing rising inventory costs. Under ASC 250 and SEC requirements, evaluate whether Zenith can make this change.', '["Zenith may change freely because ASC 250 permits any voluntary principle change", "Zenith must demonstrate that FIFO is now preferable under the current circumstances and obtain a new preferability letter from its auditor", "Zenith is permanently prohibited from returning to FIFO once it elected LIFO", "Zenith may change back without a preferability letter since it is reverting to a previously used method"]'::jsonb, 1, 'Under ASC 250-10-45-2, any voluntary change in accounting principle requires justification that the new method is preferable. SEC registrants must also file a preferability letter from their independent auditor (per Rule 10-01(b)(6) of Regulation S-X). Zenith is not prohibited from reverting (Option C is too absolute), but changing back shortly after switching may face heightened scrutiny. Option A ignores the preferability requirement. Option D incorrectly assumes reverting exempts the entity from the preferability assessment.', 'hard', 4),

-- Q19: medium / L2 — Warranty estimate revision — purely prospective
(2, 'Accounting Changes and Error Corrections', 'Pinnacle Manufacturing originally estimated warranty costs at 3% of sales. In Year 3, based on updated claim data, management revises the estimate to 5% of sales. Under ASC 250, how should Pinnacle account for this change?', '["Retrospectively restate Years 1 and 2 warranty expense at 5%", "Apply the 5% rate prospectively beginning in Year 3 with no adjustment to prior periods", "Record a cumulative catch-up adjustment in Year 3 for the 2% difference on prior-year sales", "Treat the change as an error correction requiring restatement of prior periods"]'::jsonb, 1, 'Under ASC 250-10-45-17, a change in accounting estimate is applied prospectively in the period of the change and future periods. Pinnacle applies the 5% warranty rate to Year 3 sales going forward. Option A is incorrect because estimate changes are never applied retrospectively. Option C incorrectly applies a catch-up adjustment, which is not permitted for estimate changes. Option D mischaracterizes an estimate revision as an error.', 'medium', 2),

-- Q20: hard / L3 — Interim catch-up adjustment for principle change
(2, 'Accounting Changes and Error Corrections', 'Sterling Corp. makes a voluntary change in accounting principle effective January 1, Year 3. The change is adopted in the second quarter. Sterling presents quarterly interim financial data. Under ASC 250-10-45-20, what financial data must Sterling adjust in its second-quarter interim report?', '["Only second-quarter results, applying the new method from April 1 forward", "The first-quarter interim data must be restated as if the new method had been applied from January 1, and Year 2 interim periods are also retrospectively adjusted", "Only the cumulative effect is reported as a separate line item in the second-quarter income statement", "The first and second quarters are combined and reported as a single six-month period"]'::jsonb, 1, 'Under ASC 250-10-45-20, when a change in principle is made other than in the first interim period, the entity must restate prior interim periods of the current fiscal year and also retrospectively apply the change to all prior-year interim data presented. This ensures comparability. Option A incorrectly treats it as a prospective change from Q2. Option C reflects the pre-SFAS 154 cumulative-effect approach, which is no longer permitted under ASC 250.', 'hard', 3),

-- Q21: medium / L3 — Effect of error correction on beginning retained earnings vs current expense
(2, 'Accounting Changes and Error Corrections', 'Crestline Corp. discovers in Year 3 that it failed to record $90,000 of accrued salaries at December 31, Year 1. The Year 1 and Year 2 financial statements have been issued. Crestline presents Years 2 and 3 comparatively. Ignoring taxes, where does the $90,000 correction appear in the restated Year 2 financial statements?', '["As salary expense in the Year 2 income statement", "As an adjustment to Year 2 opening retained earnings", "As a prior period adjustment disclosed only in the footnotes", "As a reduction to Year 2 ending retained earnings with no income statement effect"]'::jsonb, 1, 'Under ASC 250-10-45-23, since the error originated in Year 1 and Year 2 is the earliest period presented, the $90,000 correction appears as an adjustment to Year 2 opening retained earnings (because it should have been recognized in Year 1). Option A is incorrect because the expense belongs to Year 1, not Year 2. Option D fails to show the proper presentation through the opening balance.', 'medium', 3),

-- Q22: easy / L1 — Definition: what constitutes a restatement trigger
(2, 'Accounting Changes and Error Corrections', 'Under ASC 250, the correction of a material error in previously issued financial statements is accomplished through which method?', '["Prospective application", "Retrospective application", "Restatement of prior-period financial statements", "Cumulative effect adjustment in the current period"]'::jsonb, 2, 'Under ASC 250-10-45-23, material errors in previously issued financial statements are corrected by restating the prior-period financial statements. The term "restatement" under ASC 250 is reserved exclusively for error corrections. Option B (retrospective application) is the term used for changes in accounting principle, not error corrections. Option D reflects the old APB 20 cumulative-effect method, which is no longer permitted.', 'easy', 1),

-- Q23: easy / L2 — Initial adoption of a principle for new transactions
(2, 'Accounting Changes and Error Corrections', 'Beacon Corp. enters into its first-ever hedging arrangement in Year 3 and adopts hedge accounting under ASC 815. Under ASC 250, is this considered a change in accounting principle?', '["Yes, because Beacon is adopting a new accounting method it has never used before", "Yes, because hedge accounting is an elective principle under ASC 815", "No, because adopting a principle for a new type of transaction is not a change under ASC 250", "No, because hedge accounting is an estimate, not a principle"]'::jsonb, 2, 'Under ASC 250-10-15-3, the initial adoption of an accounting principle in recognition of events or transactions occurring for the first time or that were previously immaterial is not a change in accounting principle. Since Beacon had no prior hedging transactions, this adoption is outside the scope of ASC 250 as an accounting change. Option A is incorrect because novelty of the transaction type excludes it from the change-in-principle definition.', 'easy', 2),

-- Q24: medium / L2 — Retrospective application effect on comparative balance sheet
(2, 'Accounting Changes and Error Corrections', 'Aldridge Corp. changes from weighted-average to FIFO for inventory valuation on January 1, Year 3, presenting Years 1 and 2 comparatively. The FIFO inventory exceeds weighted-average inventory by $40,000 at December 31, Year 1, and $55,000 at December 31, Year 2. Assuming a 25% tax rate, what is the after-tax adjustment to inventory on the restated December 31, Year 1, balance sheet?', '["Increase inventory by $40,000", "Increase inventory by $30,000", "Increase inventory by $55,000", "No adjustment is needed because the change is prospective"]'::jsonb, 0, 'Under ASC 250-10-45-5, retrospective application adjusts financial statements for each prior period presented. On the restated December 31, Year 1, balance sheet, inventory increases by the full $40,000 difference between FIFO and weighted-average. The tax effect creates a $10,000 DTL, reducing retained earnings to a net $30,000 increase — but the inventory line itself increases by the gross $40,000. Option B confuses the after-tax RE effect with the inventory adjustment.', 'medium', 2),

-- Q25: medium / L2 — GAAP hierarchy: mandatory vs voluntary principle changes
(2, 'Accounting Changes and Error Corrections', 'Under ASC 250, how does the treatment of a change in accounting principle required by a newly issued FASB Accounting Standards Update differ from a voluntary change?', '["Required changes must be applied retrospectively; voluntary changes may be applied prospectively", "Both are applied retrospectively, but required changes follow the ASU''s transition guidance while voluntary changes always use full retrospective application", "Required changes are applied prospectively; voluntary changes require retrospective application", "There is no difference; both follow identical retrospective application requirements"]'::jsonb, 1, 'Under ASC 250-10-45-3 through 45-8, both required and voluntary principle changes generally use retrospective application. However, a required change follows the specific transition provisions in the new ASU (which may specify modified retrospective, full retrospective, or prospective transition), while a voluntary change defaults to full retrospective application under ASC 250. Option A is incorrect because voluntary changes are not typically prospective. Option C reverses the treatments.', 'medium', 2),

-- Q26: hard / L4 — Effect of error correction on previously declared dividends
(2, 'Accounting Changes and Error Corrections', 'Ridgeway Corp. declared and paid $100,000 of dividends in Year 2 based on reported retained earnings. In Year 3, Ridgeway discovers a material error that reduces Year 2 net income by $400,000 (after tax), which would have caused negative retained earnings at the time dividends were declared. Evaluate the accounting implications of this restatement on the Year 2 dividends.', '["The dividends must be reversed and returned because retained earnings were insufficient", "The dividends remain as reported; the restatement corrects income and retained earnings but does not retroactively invalidate properly declared dividends", "The dividends are reclassified as a return of capital (liquidating dividends) in the restated Year 2 statements", "The dividends are added back to retained earnings and redistributed based on restated amounts"]'::jsonb, 2, 'Under ASC 250, restatement corrects the financial statements but does not undo legal transactions that already occurred. However, dividends paid from a deficit in restated retained earnings are reclassified as liquidating dividends (return of capital) in the restated financial statements, because they exceeded earnings. Option B is partially correct on the legal point but fails to address the financial statement reclassification. Option A is incorrect because restatement does not require physical return of dividends.', 'hard', 4),

-- Q27: medium / L2 — Change in entity structure affecting reporting entity
(2, 'Accounting Changes and Error Corrections', 'In Year 3, Banner Corp. acquires 100% of Flagstone Inc. and begins presenting consolidated financial statements for the first time. Previously, Banner presented only its own standalone statements. Under ASC 250, how are the Year 1 and Year 2 comparative statements affected?', '["No adjustment needed; consolidation begins in Year 3 only", "The Year 1 and Year 2 statements are restated as consolidated to include Flagstone retroactively", "The Year 1 and Year 2 statements are retrospectively adjusted to reflect the new reporting entity as if it always existed", "Only the Year 2 comparative statements are adjusted; Year 1 remains standalone"]'::jsonb, 2, 'Under ASC 250-10-45-21, a change in reporting entity requires retrospective application so that all prior-period financial statements are adjusted to show the entity as it currently exists. The consolidation with Flagstone means prior periods must be presented as if the consolidated entity had always existed. Option A is incorrect because the reporting entity change mandates retrospective adjustment. Option B uses "restated," which ASC 250 reserves for error corrections, not reporting entity changes.', 'medium', 2),

-- Q28: medium / L2 — Disclosure of reason for voluntary principle change
(2, 'Accounting Changes and Error Corrections', 'Waverly Corp. voluntarily changes its revenue recognition method and applies the change retrospectively. Under ASC 250-10-50-1, which of the following disclosures is required in the period of the change?', '["Only the cumulative effect on retained earnings", "The nature of and reason for the change, including an explanation of why the new method is preferable", "Only the effect on the current year''s financial statements", "A statement that the change was approved by the audit committee"]'::jsonb, 1, 'Under ASC 250-10-50-1, when an entity makes a voluntary change in accounting principle, it must disclose: the nature of and reason for the change (including why the new principle is preferable), the method of applying the change, the effect on each affected financial statement line item and EPS, and the cumulative effect on retained earnings. Option A is incomplete. Option D is not a required ASC 250 disclosure.', 'medium', 2),

-- Q29: easy / L1 — Definition: what is the cumulative effect of an accounting change
(2, 'Accounting Changes and Error Corrections', 'Under ASC 250, the cumulative effect of a change in accounting principle refers to which amount?', '["The difference between retained earnings at the beginning of the earliest period presented under the old and new methods", "The total effect on net income in the year the change is adopted", "The difference in total assets under the old and new methods at the end of the current year", "The tax impact of switching from one accounting method to another"]'::jsonb, 0, 'Under ASC 250-10-20, the cumulative effect of a change in accounting principle is the difference between the carrying amounts of assets and liabilities (and thus retained earnings) at the beginning of the earliest period presented as calculated under the old versus new principle. This amount is used to adjust opening retained earnings. Option B describes a single-year effect, not the cumulative amount.', 'easy', 1),

-- Q30: easy / L1 — Error vs estimate change: key distinguishing factor
(2, 'Accounting Changes and Error Corrections', 'What is the primary factor that distinguishes a correction of an error from a change in accounting estimate under ASC 250?', '["An error results from a mathematical mistake, misuse of facts, or oversight; an estimate change results from new information or better judgment", "An error affects only the balance sheet; an estimate change affects only the income statement", "An error always involves fraud; an estimate change is always good-faith", "An error requires auditor approval; an estimate change requires management approval"]'::jsonb, 0, 'Under ASC 250-10-20, an error results from mathematical mistakes, mistakes in applying GAAP, or oversight or misuse of facts that existed at the time. A change in estimate results from new information, additional experience, or subsequent developments. The distinction is whether the information was available and misused (error) versus genuinely new or refined (estimate). Option B is incorrect because both can affect any financial statement. Option C is incorrect because errors do not require fraudulent intent.', 'easy', 1)
;

COMMIT;
