-- Migration: Question generation — FAR batch 91 (30 questions)
-- Date: 2026-03-05
-- Topic: Earnings Per Share
-- Difficulty: 9E / 15M / 6H
-- Bloom's: L1:8 / L2:9 / L3:8 / L4:5

BEGIN;

INSERT INTO questions (section_id, topic, stem, choices, correct_index, explanation, difficulty, cognitive_level)
VALUES

-- Q1: medium / L3 — Diluted EPS with performance-based stock options whose targets are not yet met
(2, 'Earnings Per Share', 'Claymore Industries granted 40,000 performance-contingent stock options exercisable only if cumulative EBITDA exceeds $5 million over three years. At December 31, Year 2, cumulative EBITDA is $3.2 million. The options are in-the-money (exercise price $18, average market price $30). Should these options be included in Year 2 diluted EPS?', '["Yes — they are in-the-money, so the treasury stock method applies regardless of the performance condition", "Yes — all outstanding options must be included in diluted EPS under the treasury stock method", "No — because the performance target has not been met as of the reporting date, the options are excluded from diluted EPS", "No — performance options are never included in diluted EPS until they are fully vested and exercisable"]'::jsonb, 2, 'Under ASC 260-10-45-48, contingently issuable shares (including performance-based options) are included in diluted EPS only if the contingency condition is satisfied as of the reporting date. Since cumulative EBITDA ($3.2M) has not reached the $5M target, the performance condition is unmet and the options are excluded. Choice A incorrectly prioritizes the in-the-money status over the unfulfilled performance contingency.', 'medium', 3),

-- Q2: easy / L1 — Nonpublic entities exempt from EPS presentation
(2, 'Earnings Per Share', 'Hartwell LLC is a privately held company that prepares GAAP financial statements. The CFO asks whether the company must present earnings per share on the face of the income statement. Which statement is correct?', '["Nonpublic entities are not required to present EPS under ASC 260 but may elect to do so", "All entities preparing GAAP financial statements must present EPS regardless of public status", "Nonpublic entities must present basic EPS but not diluted EPS", "Nonpublic entities present EPS only if they have outstanding stock options"]'::jsonb, 0, 'Under ASC 260-10-15-2, EPS presentation is required only for public business entities or entities that have filed (or are in the process of filing) with a regulatory agency. Nonpublic entities may voluntarily present EPS but are not required to. Choice B overstates the scope of ASC 260 by applying it to all GAAP preparers.', 'easy', 1),

-- Q3: hard / L4 — Antidilution sequencing: individually dilutive security becomes antidilutive in aggregate
(2, 'Earnings Per Share', 'Grantham Corp. has income from continuing operations of $1,000,000 and 500,000 weighted-average shares (basic EPS: $2.00). It has three potentially dilutive securities ranked by dilution: Security A produces $1.50 per incremental share, Security B produces $2.10 per incremental share, and Security C produces $1.80 per incremental share. The analyst includes all three because each is individually dilutive when compared to basic EPS. Evaluate this approach.', '["Correct — each security is compared only to basic EPS to determine inclusion", "Incorrect — Security B at $2.10 exceeds the running diluted EPS after including Security A, so it is antidilutive and excluded along with all less-dilutive securities", "Incorrect — all three should be excluded because only the most dilutive single security is ever included", "Correct — the order of inclusion does not matter as long as all securities reduce basic EPS individually"]'::jsonb, 1, 'Under ASC 260-10-45-21, securities must be ranked from most dilutive to least dilutive and included sequentially. After including Security A ($1.50), running diluted EPS falls below $2.00. Security B at $2.10 per incremental share exceeds the running diluted EPS, making it antidilutive at that point. Under the sequential test, once a security is antidilutive, it and all less-dilutive securities are excluded. Choice A incorrectly compares each security only to basic EPS rather than applying the cumulative sequential test.', 'hard', 4),

-- Q4: hard / L4 — Change in accounting principle and its effect on restated EPS in comparative statements
(2, 'Earnings Per Share', 'Brookhaven Corp. voluntarily changes its depreciation method from double-declining balance to straight-line in Year 3, which ASC 250 treats as a change in accounting estimate effected by a change in accounting principle. The controller restates Year 1 and Year 2 EPS in the comparative financial statements to reflect what EPS would have been under straight-line depreciation. Evaluate this approach.', '["Correct — all voluntary accounting changes require retrospective restatement of prior-period EPS", "Correct — depreciation method changes are always applied retrospectively under ASC 250", "Incorrect — a change in depreciation method is treated prospectively under ASC 250-10-45-18, so prior-period EPS is not restated", "Incorrect — prior-period EPS is restated but only for the immediately preceding year, not for Year 1"]'::jsonb, 2, 'Under ASC 250-10-45-18, a change in depreciation method is a change in accounting estimate effected by a change in principle and is applied prospectively from the date of the change. Prior-period financial statements (and their EPS figures) are not restated. The controller''s approach incorrectly applies retrospective treatment. Choice A conflates voluntary accounting principle changes (which are retrospective under ASC 250-10-45-5) with this specific category of estimate-driven changes.', 'hard', 4),

-- Q5: medium / L3 — Business combination mid-year: acquiree shares enter weighted average from acquisition date only
(2, 'Earnings Per Share', 'On September 1, 2025, Denholm Corp. acquires Hartley Inc. by issuing 80,000 new shares of its common stock. Denholm had 400,000 shares outstanding before the acquisition. Denholm''s consolidated net income for 2025 includes Hartley''s results only from September 1 onward. What weighted-average share count does Denholm use for 2025 basic EPS?', '["480,000 — the new shares are applied retroactively to January 1 because they were issued for a business combination", "400,000 — the acquiree shares are excluded from the weighted average entirely in the acquisition year", "426,667 — the 80,000 shares are weighted from the acquisition date: 400,000 + (80,000 × 4/12)", "440,000 — the 80,000 shares are weighted for half the year"]'::jsonb, 2, 'Under ASC 260-10-45-13, shares issued in a business combination are included in the weighted average from the acquisition date (September 1), not retroactively. Weighted average = 400,000 + (80,000 × 4/12) = 426,667. This matches the consolidation of the acquiree''s income from that same date. Choice A incorrectly applies retroactive treatment, which is reserved for stock splits and dividends, not share issuances for acquisitions.', 'medium', 3),

-- Q6: medium / L2 — Diluted EPS disclosure requirement: reconciliation of numerator and denominator
(2, 'Earnings Per Share', 'Under ASC 260, what reconciliation must a public entity disclose regarding diluted EPS in the notes or on the face of the income statement?', '["A reconciliation of the basic EPS numerator and denominator to the diluted EPS numerator and denominator, showing each class of dilutive security individually", "Only a reconciliation of the denominator; numerator differences need not be disclosed", "A reconciliation is optional and may be replaced by a narrative explanation", "A reconciliation is required only when diluted EPS differs from basic EPS by more than 5%"]'::jsonb, 0, 'Under ASC 260-10-50-1(a), entities must provide a reconciliation of both the numerators and denominators used in basic and diluted EPS computations. This includes the individual effect of each dilutive security class on both the numerator (e.g., interest add-backs for convertible debt) and denominator (e.g., incremental shares from options). Choice B omits the numerator reconciliation, which is equally required.', 'medium', 2),

-- Q7: medium / L2 — Large stock dividends (>25%) treated same as small for EPS retroactive adjustment
(2, 'Earnings Per Share', 'Garfield Corp. declares a 30% stock dividend when 200,000 shares are outstanding. An analyst argues that because the distribution exceeds 25%, it should be weighted from the distribution date rather than applied retroactively for EPS purposes. Evaluate the analyst''s argument.', '["Correct — large stock dividends are weighted from the distribution date like a share issuance", "Correct — large stock dividends require a separate computation using the par value method", "Incorrect — ASC 260 treats all stock dividends the same, requiring retroactive adjustment regardless of size", "Correct — large stock dividends are excluded from the EPS computation entirely"]'::jsonb, 2, 'Under ASC 260-10-55-12, all stock dividends — whether small or large — are treated as retroactive adjustments to the weighted-average shares outstanding. While ASC 505-20 distinguishes between small (under 20-25%) and large stock dividends for accounting purposes, ASC 260 makes no such distinction for EPS computation. Choice A incorrectly applies stock issuance rules to a stock dividend.', 'medium', 2),

-- Q8: medium / L2 — Preferred stock with liquidation preference but no dividend right: no EPS numerator deduction
(2, 'Earnings Per Share', 'Gresham Holdings has Series C preferred stock with a liquidation preference of $25 per share but no stated dividend right and no participation feature. The preferred stockholders receive distributions only upon liquidation. How does this preferred stock affect Gresham''s basic EPS numerator?', '["Deduct an imputed dividend based on the liquidation preference amortized over the expected holding period", "Deduct the liquidation preference in full as a deemed preferred dividend each year", "No deduction — preferred stock without a dividend right does not reduce the basic EPS numerator in any period", "Deduct an amount equal to the risk-free rate applied to the liquidation preference as an implicit return"]'::jsonb, 2, 'Under ASC 260-10-45-11, preferred dividends (whether declared or, for cumulative stock, earned) are deducted from the EPS numerator. When preferred stock has no dividend right (neither stated nor participating), there is no amount to deduct. The liquidation preference affects distributions only upon winding up the entity, not periodic EPS. Choice A incorrectly imputes a periodic dividend where none contractually exists.', 'medium', 2),

-- Q9: easy / L1 — Minimum EPS line items required on the income statement
(2, 'Earnings Per Share', 'Waverly Corp. is a public entity preparing its annual income statement. At a minimum, which per-share amounts must Waverly present on the face of the income statement under ASC 260?', '["Basic and diluted EPS for income from continuing operations and for net income", "Only basic EPS for net income", "Basic and diluted EPS for each revenue and expense line item", "Basic EPS for net income and diluted EPS for comprehensive income"]'::jsonb, 0, 'Under ASC 260-10-45-2, public entities must present basic and diluted EPS for income from continuing operations and net income on the face of the income statement. If discontinued operations exist, per-share data for that component is also required. Choice B omits diluted EPS and the continuing operations line. Choice C overstates the requirement by applying EPS to individual revenue and expense items.', 'easy', 1),

-- Q10: medium / L2 — Stock split affects only denominator, not numerator
(2, 'Earnings Per Share', 'Glendale Corp. has net income of $600,000, no preferred dividends, and 200,000 weighted-average shares. On July 1, the company declares a 2-for-1 stock split. Which component of the basic EPS formula is affected by the stock split?', '["Both the numerator and denominator change proportionally", "Only the denominator changes — it is retroactively adjusted to 400,000 shares", "Only the numerator changes — net income is divided by the split ratio", "Neither component changes — the stock split is disclosed but not reflected in EPS"]'::jsonb, 1, 'Under ASC 260-10-55-12, a stock split retroactively adjusts the weighted-average denominator as if the split occurred at the beginning of the earliest period presented. The numerator (net income minus preferred dividends) is unaffected. Here, the denominator becomes 400,000. Choice A is wrong because net income does not change due to a stock split.', 'medium', 2),

-- Q11: medium / L2 — EPS treatment of shares held in a rabbi trust for deferred compensation
(2, 'Earnings Per Share', 'Holbrook Corp. holds 25,000 of its own common shares in a rabbi trust established to fund a deferred compensation plan for executives. The shares have not been legally retired. For computing basic EPS, how should the rabbi trust shares be treated?', '["Included in the weighted-average denominator because they have not been legally retired", "Excluded from the weighted-average denominator because shares held in a rabbi trust are treated as treasury stock for EPS purposes", "Included at half their value in the denominator to reflect the restricted nature of the trust", "Excluded from the denominator only if the deferred compensation has been expensed"]'::jsonb, 1, 'Under ASC 260-10-45-10 and ASC 710-10, shares of the reporting entity held in a rabbi trust are not considered outstanding for EPS purposes and are excluded from the weighted-average denominator. They are analogous to treasury shares because the entity controls the shares and they do not represent a residual ownership interest held by outside parties. Choice A incorrectly treats legal retirement as the threshold for exclusion.', 'medium', 2),

-- Q12: medium / L3 — EPS effect of share buyback announcement vs actual repurchase date
(2, 'Earnings Per Share', 'On March 15, 2025, the board of Winfield Corp. publicly announces a plan to repurchase up to 100,000 shares. On August 1, 2025, the company repurchases 60,000 shares in the open market. For computing 2025 basic EPS, from what date do the repurchased shares reduce the weighted-average denominator?', '["March 15, the announcement date, because the market has priced in the expected buyback", "January 1, because board-authorized repurchases are applied retroactively for the full year", "August 1, the actual repurchase date, because shares leave the weighted average only when physically retired or held as treasury", "December 31, because repurchased shares are excluded only in the following fiscal year"]'::jsonb, 2, 'Under ASC 260-10-45-10, shares are removed from the weighted-average calculation based on when they are no longer outstanding (i.e., the repurchase date). A board announcement or authorization has no effect on the share count until shares are actually acquired. The 60,000 shares reduce the denominator from August 1 onward (5/12 of the year). Choice A incorrectly treats the announcement as a share-reducing event.', 'medium', 3),

-- Q13: easy / L1 — Basic EPS uses weighted-average, not ending share count
(2, 'Earnings Per Share', 'At December 31, 2025, Tresham Corp. has 500,000 shares of common stock outstanding. A new staff accountant divides net income by the 500,000 ending share count to calculate basic EPS. Is this approach correct?', '["Yes — basic EPS always uses the number of shares outstanding at the end of the period", "Yes — the ending share count is required unless a stock split occurred during the year", "No — basic EPS requires the weighted-average number of shares outstanding during the period, which may differ from the ending count", "No — basic EPS uses the beginning-of-period share count, not the ending count"]'::jsonb, 2, 'Under ASC 260-10-45-10, basic EPS uses the weighted-average number of shares outstanding during the period. If shares were issued or repurchased mid-year, the weighted average will differ from the year-end count. Choice A is incorrect because the ending balance ignores the timing of share issuances and repurchases throughout the period.', 'easy', 1),

-- Q14: medium / L2 — Diluted EPS equals basic EPS when all securities are out-of-the-money
(2, 'Earnings Per Share', 'Prescott Industries has basic EPS of $2.40 from net income of $480,000 and 200,000 weighted-average shares. Its only potentially dilutive securities are 15,000 stock options with an exercise price of $55 when the average market price is $42 for the year. What does Prescott report as diluted EPS?', '["Less than $2.40, because all outstanding options must be included in diluted EPS", "$2.40, equal to basic EPS, because out-of-the-money options are antidilutive and excluded", "Greater than $2.40, because the treasury stock method produces a net share reduction when exercise price exceeds market price", "Diluted EPS is not reported when all securities are antidilutive"]'::jsonb, 1, 'Under ASC 260-10-45-22, the treasury stock method for options assumes exercise and repurchase of shares at the average market price. When the exercise price ($55) exceeds the average market price ($42), the assumed buyback exceeds the assumed issuance, producing a net share reduction. Including them would increase EPS, making them antidilutive. Therefore, diluted EPS equals basic EPS at $2.40. Choice D is incorrect because diluted EPS is still reported — it simply equals basic EPS.', 'medium', 2),

-- Q15: medium / L3 — Treasury stock method: average market price vs period-end price for option dilution
(2, 'Earnings Per Share', 'Fenwick Corp.''s stock price was $30 on January 1, averaged $40 during the year, and closed at $55 on December 31. It has 25,000 stock options with a $25 exercise price outstanding all year. An analyst uses the December 31 closing price of $55 to compute the treasury stock method buyback. Is this correct for annual diluted EPS?', '["Yes — the year-end price reflects the most current market valuation and should be used", "Yes — whichever price produces the most dilutive result must be selected", "No — the treasury stock method uses the average market price during the period ($40), not the closing price", "No — the treasury stock method uses the beginning-of-period price ($30)"]'::jsonb, 2, 'Under ASC 260-10-45-28, the treasury stock method assumes the proceeds from option exercise are used to repurchase shares at the average market price during the period. Using the $40 average: assumed proceeds = 25,000 × $25 = $625,000; buyback = $625,000 / $40 = 15,625; incremental = 9,375 shares. The closing price is irrelevant for annual computations. Choice A incorrectly substitutes the period-end price, which would overstate dilution.', 'medium', 3),

-- Q16: medium / L3 — Share-based compensation awards with service conditions: graded vesting and diluted EPS
(2, 'Earnings Per Share', 'Colburn Inc. grants 30,000 restricted stock units (RSUs) on January 1, 2025, vesting in three equal annual tranches (10,000 each year). The grant-date fair value is $45 per unit. By December 31, 2025, unamortized compensation cost is $900,000 and the average share price is $60. Under the treasury stock method for diluted EPS, how many incremental shares does the first-year tranche contribute to the denominator?', '["10,000 shares with no reduction, because RSUs require no exercise payment", "5,000 incremental shares — assumed proceeds equal unamortized cost for that tranche, and the buyback reduces the share count", "10,000 shares weighted for 4 months from the first vesting date", "Zero incremental shares because none of the RSUs have vested yet"]'::jsonb, 1, 'Under ASC 260-10-45-28A, unvested share-based payment awards are included in diluted EPS using the treasury stock method. The assumed proceeds include unamortized compensation cost (allocated to the tranche). For the first tranche: unamortized cost = $300,000. Assumed buyback: $300,000 / $60 = 5,000 shares. Incremental shares = 10,000 − 5,000 = 5,000. Choice A ignores the compensation cost offset, which serves the same role as exercise price in the treasury stock method.', 'medium', 3),

-- Q17: medium / L2 — Cumulative preferred dividends in arrears deducted for EPS without balance sheet liability
(2, 'Earnings Per Share', 'Fernwood Corp. has 5,000 shares of cumulative preferred stock with a $10 annual dividend per share. No preferred dividends have been declared for the past two years. The controller notes that no dividend liability appears on the balance sheet. How does the current year''s undeclared preferred dividend affect basic EPS?', '["No deduction because no liability exists on the balance sheet", "A deduction only in the year the dividends are eventually declared and paid", "A deduction only when the board of directors formally acknowledges the arrearage", "A deduction of $50,000 in the current year regardless of whether a dividend liability is recognized"]'::jsonb, 3, 'Under ASC 260-10-45-11, the current period''s cumulative preferred dividend is always deducted from the basic EPS numerator, whether or not it is declared. The absence of a liability on the balance sheet is irrelevant — dividends in arrears are not liabilities until declared, but they still reduce income available to common shareholders for EPS. Choice A confuses balance sheet recognition with EPS treatment.', 'medium', 2),

-- Q18: easy / L1 — Diluted EPS can never exceed basic EPS
(2, 'Earnings Per Share', 'A newly hired analyst calculates diluted EPS for Pennworth Corp. at $3.80 and basic EPS at $3.50. The analyst concludes the computation must be correct because diluted EPS accounts for additional securities. Is this conclusion valid?', '["Yes — diluted EPS can exceed basic EPS when convertible securities have high income add-backs", "Yes — there is no required relationship between basic and diluted EPS", "No — diluted EPS must always be equal to or less than basic EPS; a higher figure indicates a computational error", "No — diluted EPS must always be exactly equal to basic EPS unless there is a net loss"]'::jsonb, 2, 'Under ASC 260-10-45-11 and the antidilution provisions, diluted EPS can never exceed basic EPS. Securities are included in diluted EPS only if they are dilutive (i.e., they reduce EPS). If including a security would increase EPS above the basic figure, that security is antidilutive and excluded. A diluted EPS above basic EPS signals an error. Choice A misunderstands the antidilution safeguard — income add-backs that increase per-share amounts cause exclusion, not inclusion.', 'easy', 1),

-- Q19: easy / L2 — Simple vs complex capital structure determines EPS presentation requirements
(2, 'Earnings Per Share', 'Dunham Corp. has only common stock and short-term trade payables — no options, warrants, convertible securities, or contingently issuable shares. What EPS presentation is required on Dunham''s income statement?', '["Both basic and diluted EPS must be presented regardless of capital structure", "Only basic EPS is required because Dunham has a simple capital structure", "Neither basic nor diluted EPS is required if there are no dilutive securities", "Only diluted EPS is presented, set equal to basic EPS with a footnote"]'::jsonb, 1, 'Under ASC 260-10-45-3, an entity with a simple capital structure (no potentially dilutive securities) is required to present only basic EPS on the face of the income statement. Diluted EPS presentation is not required because there are no securities that could dilute earnings. Choice A incorrectly mandates dual presentation for all entities, which applies only to complex capital structures.', 'easy', 2),

-- Q20: hard / L4 — SEC registrant year-to-date diluted EPS cannot be averaged from quarterly results
(2, 'Earnings Per Share', 'Eastlake Corp. (SEC registrant) computes diluted EPS each quarter: Q1 = $1.20, Q2 = $0.80, Q3 = $1.50, Q4 = $1.00. The CFO sums the four quarters ($4.50) as the annual diluted EPS. Separately, computing diluted EPS from full-year figures yields $4.30 because the diluted share counts differ each quarter. Evaluate which figure should be reported in the annual filing.', '["$4.50, because annual EPS is the sum of the four quarterly EPS figures", "$4.30, because diluted EPS must be computed independently using full-year income and weighted-average shares", "$4.40, the average of the two methods, to balance quarterly and annual consistency", "$4.50, because SEC rules require quarterly amounts to reconcile to annual EPS"]'::jsonb, 1, 'Under ASC 260-10-45-2 and SEC guidance, annual EPS is independently computed using full-year numerator and denominator figures, not by summing or averaging quarterly EPS. Quarterly diluted share counts vary as options move in and out of the money, so summing quarterly EPS produces an incorrect result. Choice A incorrectly assumes additivity of quarterly EPS figures, which does not hold when diluted denominators change across periods.', 'hard', 4),

-- Q21: hard / L3 — Warrants with a cashless exercise feature: treasury stock method still applies
(2, 'Earnings Per Share', 'Norwood Inc. has 400,000 weighted-average shares and net income of $1,200,000. It has 50,000 warrants outstanding with an exercise price of $20 that include a net-settlement (cashless exercise) provision. The average market price is $40 during the period. The controller argues that because no cash will be received under cashless exercise, no proceeds should be assumed and all 50,000 shares should be added to the diluted denominator. Evaluate this position.', '["Correct — cashless warrants add the full number of warrant shares to the denominator with no buyback assumption", "Correct — net-settlement warrants are excluded from diluted EPS entirely because no cash changes hands", "Incorrect — under ASC 260-10-45-22, the treasury stock method applies regardless of the settlement mechanism, assuming exercise at $20 and share repurchase at $40", "Incorrect — cashless warrants are treated as contingently issuable shares rather than under the treasury stock method"]'::jsonb, 2, 'Under ASC 260-10-45-22, the treasury stock method applies to all options and warrants regardless of whether they have a cash or cashless exercise feature. Assumed proceeds: 50,000 × $20 = $1,000,000. Shares repurchased: $1,000,000 / $40 = 25,000. Incremental shares: 25,000. The settlement mechanism does not change the computational method. Choice A incorrectly skips the buyback assumption, overstating dilution.', 'hard', 3),

-- Q22: easy / L1 — Basic EPS can be a negative number
(2, 'Earnings Per Share', 'Can basic earnings per share be reported as a negative amount under ASC 260?', '["No — basic EPS is always reported as zero or a positive number", "Yes — basic EPS is negative when net income less preferred dividends produces a loss available to common shareholders", "No — a negative result is reported as N/A on the income statement", "Yes — but only when the entity reports a net loss, not when preferred dividends cause the negative amount"]'::jsonb, 1, 'Under ASC 260-10-45-11, basic EPS equals (net income − preferred dividends) / weighted-average shares. If this produces a negative number — whether from a net loss or from preferred dividends exceeding net income — the negative EPS is reported. There is no floor at zero. Choice D is incorrect because preferred dividends exceeding net income also produce negative EPS.', 'easy', 1),

-- Q23: easy / L1 — Where EPS is displayed on financial statements
(2, 'Earnings Per Share', 'Where must a public entity display its earnings per share data under ASC 260?', '["On the face of the income statement (or statement of comprehensive income if used as a combined statement)", "In the notes to the financial statements only", "On the balance sheet alongside shareholders'' equity", "In management''s discussion and analysis but not the financial statements"]'::jsonb, 0, 'Under ASC 260-10-45-2, EPS data must be presented on the face of the income statement for each period for which an income statement is presented. It is not sufficient to relegate EPS disclosure to the notes alone. Choice B is incorrect because while supplemental EPS disclosures appear in the notes, the basic and diluted EPS figures themselves must appear on the face of the statement.', 'easy', 1),

-- Q24: medium / L3 — Adjusting diluted EPS denominator when options expire mid-period
(2, 'Earnings Per Share', 'Kenmore Systems had 30,000 in-the-money stock options (exercise price $15, average market price $45) that expired unexercised on September 30, 2025. For the nine months the options were outstanding, the treasury stock method yields 20,000 incremental shares. How are these incremental shares reflected in the 2025 annual diluted EPS?', '["20,000 shares for the full twelve months because the options existed during the fiscal year", "Zero shares because unexercised expired options are never included in diluted EPS", "15,000 shares — the 20,000 incremental shares time-weighted for nine months (20,000 × 9/12)", "20,000 shares for the nine-month interim period only, with separate annual and interim diluted EPS figures"]'::jsonb, 2, 'Under ASC 260-10-45-22, options are included in diluted EPS only for the period they were outstanding. The 20,000 incremental shares from the treasury stock method are time-weighted: 20,000 × 9/12 = 15,000 shares added to the annual diluted denominator. Once options expire, they cease contributing incremental shares. Choice A incorrectly includes the full incremental amount without time-weighting for the period of expiration.', 'medium', 3),

-- Q25: easy / L1 — Interim financial statements require EPS
(2, 'Earnings Per Share', 'Under ASC 260 and ASC 270, when must a public entity present earnings per share data in its interim financial reports?', '["Only in the fourth quarter interim report", "Only when interim net income differs materially from the prior year", "Only in annual financial statements, not interim reports", "In each interim period for which an income statement is presented"]'::jsonb, 3, 'Under ASC 260-10-45-2 and ASC 270-10-45-2, a public entity must present EPS data for each period for which an income statement is presented, including interim periods. Choice C is incorrect because interim financial reports are explicitly within the scope of ASC 260.', 'easy', 1),

-- Q26: easy / L1 — Weighted-average shares use days or months outstanding
(2, 'Earnings Per Share', 'Oakmont Corp. issues 60,000 new common shares on September 1, 2025. For computing the 2025 weighted-average number of shares, how are these newly issued shares factored into the calculation?', '["The shares are weighted for the fraction of the year they were outstanding — four months out of twelve", "The shares are included for the full year because they were issued before year-end", "The shares are excluded entirely because they were not outstanding for more than six months", "The shares are weighted only if they were outstanding on the last day of the fiscal year"]'::jsonb, 0, 'Under ASC 260-10-45-10, shares issued during the period are weighted by the fraction of the period they were outstanding. Shares issued September 1 are outstanding for 4 months (September through December), so they contribute 60,000 × 4/12 = 20,000 to the weighted average. Choice B incorrectly treats mid-year shares as outstanding all year.', 'easy', 1),

-- Q27: hard / L4 — Dual-class common stock with different dividend rights requires separate EPS
(2, 'Earnings Per Share', 'Highfield Corp. has two classes of common stock: Class A (400,000 shares) with full participation in all dividends and undistributed earnings, and Class B (100,000 shares) limited to a maximum $1.00 per share annual dividend with no participation in additional earnings. Net income is $900,000 and total declared dividends are $400,000 ($300,000 to Class A, $100,000 to Class B). Under the charter, all undistributed earnings are allocated to Class A. Evaluate the correct EPS presentation.', '["A single EPS of $1.80 for both classes combined", "Class A EPS of $2.25 and Class B EPS of $0.75", "Class A EPS of $2.00 and Class B EPS of $1.00, presented separately", "Only Class A EPS is presented because Class B has limited rights"]'::jsonb, 2, 'Under ASC 260-10-45-60B, when multiple classes of common stock exist with different dividend rights, the two-class method requires separate EPS for each class. Class A: ($300,000 + $500,000 undistributed) / 400,000 = $2.00. Class B: $100,000 / 100,000 = $1.00. Choice A improperly combines the classes, ignoring their different contractual rights to earnings.', 'hard', 4),

-- Q28: hard / L4 — Subsidiary with different fiscal year-end: reconciling EPS periods in consolidated statements
(2, 'Earnings Per Share', 'Hartland Corp. (December 31 fiscal year) consolidates Voss Ltd. (September 30 fiscal year) using Voss''s October 1 – September 30 results with appropriate disclosures. The auditor questions whether the consolidated weighted-average share count should adjust for the mismatch in reporting periods. Under ASC 260, evaluate the proper treatment.', '["The parent''s December 31 share data is used for the consolidated weighted average; the subsidiary''s different fiscal year affects only the income numerator through consolidation adjustments", "The weighted-average shares must be computed using the subsidiary''s September 30 year-end share count blended with the parent''s December share count", "Consolidated EPS cannot be presented when subsidiary fiscal years differ by more than one quarter", "The subsidiary''s shares are excluded from the denominator because of the fiscal year mismatch"]'::jsonb, 0, 'Under ASC 810-10-45 and ASC 260-10-45, the consolidated EPS denominator reflects the parent''s equity structure (common shares and dilutive instruments). A subsidiary''s different fiscal year-end is addressed through consolidation of its financial results with appropriate lag disclosures, but the EPS denominator uses only the parent''s weighted-average shares. Choice B incorrectly blends subsidiary and parent share counts, conflating consolidation of results with EPS share computation.', 'hard', 4),

-- Q29: medium / L2 — EPS numerator adjustment for preferred stock redemption premium
(2, 'Earnings Per Share', 'Talbott Corp. redeems all 20,000 shares of its callable preferred stock for $52 per share. The original issuance price was $48 per share. The $4 per share excess paid to preferred shareholders over the carrying amount totals $80,000. How does the redemption premium affect the basic EPS numerator in the period of redemption?', '["No effect — the redemption premium is a financing transaction that bypasses the EPS numerator", "The $80,000 is deducted from the numerator as an additional charge to common shareholders", "The $80,000 is added to the numerator because the preferred claims have been extinguished", "The $80,000 is amortized over the remaining original term of the preferred stock"]'::jsonb, 1, 'Under ASC 260-10-S99-2, when preferred stock is redeemed at an amount exceeding its carrying value, the excess (redemption premium) is treated as a deduction from income available to common shareholders — analogous to a dividend. The $80,000 premium reduces the basic EPS numerator in the redemption period. Choice A incorrectly ignores the premium''s impact on the residual interest of common shareholders. Choice C reverses the direction of the adjustment.', 'medium', 2),

-- Q30: medium / L3 — Diluted EPS disclosure of securities excluded due to antidilution
(2, 'Earnings Per Share', 'Kingsford Corp. excludes 50,000 shares underlying out-of-the-money stock options from its diluted EPS calculation because they are antidilutive. An audit associate argues that no disclosure about excluded securities is necessary since they had no effect on reported EPS. Evaluate whether additional disclosure is required.', '["No disclosure is needed — antidilutive securities are irrelevant to financial statement users", "Disclosure is required only if the securities become dilutive in the subsequent year", "The securities must be disclosed in the notes, including a description and the number of shares, because they could potentially dilute EPS in future periods", "Disclosure is required only for convertible instruments, not for stock options"]'::jsonb, 2, 'Under ASC 260-10-50-1(c), entities must disclose a description of securities that could potentially dilute basic EPS in the future but were excluded from the current diluted EPS computation because they were antidilutive. This includes the number of shares represented. The disclosure alerts users that dilution risk exists even though no current effect was recognized. Choice A incorrectly dismisses the disclosure requirement for excluded securities.', 'medium', 3)
;

COMMIT;
