-- Migration: Question generation — FAR batch 88 (30 questions)
-- Date: 2026-03-05
-- Topic: Earnings Per Share
-- Difficulty: 9E / 15M / 6H
-- Bloom's: L1:8 / L2:9 / L3:8 / L4:5

BEGIN;

INSERT INTO questions (section_id, topic, stem, choices, correct_index, explanation, difficulty, cognitive_level)
VALUES

-- Q1: medium / L2 — Rabbi trust shares excluded from EPS denominator
(2, 'Earnings Per Share', 'Harmon Industries maintains a rabbi trust that holds 10,000 shares of Harmon''s own common stock for executive deferred compensation. Harmon has 300,000 shares outstanding and net income of $900,000 with no preferred stock. The controller includes the rabbi trust shares in the basic EPS denominator. Evaluate whether this approach is correct.', '["The approach is correct because rabbi trust shares have voting rights", "The approach is correct because rabbi trust shares are legally outstanding", "The approach is incorrect because rabbi trust shares should be treated as treasury shares and excluded from the denominator", "The approach is incorrect because rabbi trust shares should reduce the numerator instead"]'::jsonb, 2, 'Under ASC 260-10-45-7, shares of the reporting entity held in a rabbi trust are treated as treasury stock and excluded from the weighted-average denominator for basic EPS. Harmon should use 290,000 shares (300,000 minus 10,000), not 300,000. Option B is incorrect because legal outstanding status alone does not determine EPS inclusion; the economic substance as treasury shares controls the treatment.', 'medium', 2),

-- Q2: easy / L1 — Cash dividends have no effect on weighted-average shares
(2, 'Earnings Per Share', 'Under ASC 260, what effect does the declaration of a cash dividend have on the weighted-average number of common shares used in computing basic EPS?', '["Cash dividends increase the weighted-average shares", "Cash dividends decrease the weighted-average shares", "Cash dividends require a retroactive adjustment to all prior-period shares", "Cash dividends have no effect on the weighted-average shares"]'::jsonb, 3, 'Under ASC 260-10-45-10, only stock dividends, stock splits, and reverse splits require adjustment to the weighted-average share count. Cash dividends are a distribution of retained earnings and do not change the number of shares outstanding. Option C is incorrect because retroactive adjustment applies to stock dividends and splits, not cash dividends.', 'easy', 1),

-- Q3: medium / L3 — Graded vesting: each tranche as separate award for diluted EPS
(2, 'Earnings Per Share', 'Belford Technologies grants 30,000 stock options on January 1, 2025, with a three-year graded vesting schedule: 10,000 vest each year. The exercise price is $20, and the average market price is $40. Average unrecognized compensation cost is $80,000 for Tranche 1, $160,000 for Tranche 2, and $200,000 for Tranche 3. The controller treats all 30,000 options as a single pool for diluted EPS. Analyze the correct treatment.', '["Each tranche must be treated as a separate award, using its own unrecognized compensation cost in the treasury stock method", "The single-pool approach is acceptable because all options have the same exercise price and grant date", "Only the 10,000 vested options should be included because unvested options are always excluded from diluted EPS", "All 30,000 options should be included using only the exercise price as assumed proceeds"]'::jsonb, 0, 'Under ASC 718-10-55-8 and ASC 260-10-45-29, a graded-vesting award is treated as multiple separate awards for EPS purposes. Each tranche has its own unrecognized compensation cost, affecting assumed proceeds in the treasury stock method differently. Option B is incorrect because, despite identical exercise prices, different vesting dates create different compensation cost profiles requiring separate treatment.', 'medium', 3),

-- Q4: easy / L1 — Stock splits affect only the denominator, not the numerator
(2, 'Earnings Per Share', 'Under ASC 260, what effect does a stock split have on the numerator of the basic EPS formula?', '["A stock split increases the numerator proportionally", "A stock split has no effect on the numerator", "A stock split decreases the numerator proportionally", "A stock split requires adding back a stock dividend adjustment to the numerator"]'::jsonb, 1, 'Under ASC 260-10-55-12, a stock split affects only the denominator of the EPS calculation by increasing the weighted-average number of shares retroactively. The numerator (net income minus preferred dividends) remains unchanged because a stock split does not alter the total earnings available to common shareholders. Option A is incorrect because the split changes only the number of shares, not the income figure.', 'easy', 1),

-- Q5: hard / L3 — Reverse acquisition: legal acquiree's historical shares restated for exchange ratio
(2, 'Earnings Per Share', 'On April 1, 2025, Larkspur Corp. (legal acquirer, 100,000 shares outstanding) issues 250,000 new shares to acquire all of Netherfield Inc. (150,000 shares outstanding). For accounting purposes, Netherfield is determined to be the acquirer under ASC 805 (a reverse acquisition). When presenting comparative EPS for the combined entity, which share count forms the basis of the 2024 comparative-period denominator?', '["Larkspur''s 100,000 historical shares because it is the legal acquirer", "Netherfield''s 150,000 historical shares multiplied by the exchange ratio (250,000 / 150,000)", "The sum of both entities'' shares: 100,000 + 150,000", "Netherfield''s 150,000 historical shares without any exchange ratio adjustment"]'::jsonb, 1, 'Under ASC 805-40-45-1 and ASC 260-10-45-61B, in a reverse acquisition the comparative-period EPS denominator is the accounting acquirer''s (Netherfield''s) historical weighted-average shares multiplied by the exchange ratio established in the acquisition. The exchange ratio is 250,000 / 150,000 = 1.667, so the 2024 denominator uses 150,000 x 1.667 = 250,000 shares. Option A is incorrect because, despite being the legal acquirer, Larkspur''s historical shares do not represent the continuing accounting entity.', 'hard', 3),

-- Q6: medium / L2 — Shares placed in escrow excluded from denominator until contingency resolved
(2, 'Earnings Per Share', 'On January 1, 2025, Pemberton Corp. completes a business combination and places 60,000 of its own shares in escrow, returnable to Pemberton if the acquired subsidiary fails to meet a 2025 revenue target. Pemberton has 400,000 other shares outstanding all year. The revenue target is not met by December 31, 2025, and the shares are returned in January 2026. How should the escrowed shares be treated in Pemberton''s 2025 basic EPS?', '["Include all 60,000 shares for the full year because they were legally issued", "Include the 60,000 shares weighted from the acquisition date", "Exclude the 60,000 shares from the denominator because the contingency was not satisfied during the period", "Include 30,000 shares as a probability-weighted estimate"]'::jsonb, 2, 'Under ASC 260-10-45-13A, shares placed in escrow subject to contingent return are treated as contingently issuable shares and excluded from the basic EPS denominator until the contingency is resolved in the shareholders'' favor. Because the revenue target was not met, the 60,000 shares remained contingent throughout 2025 and are excluded entirely. The weighted-average is 400,000 shares. Option A is incorrect because legal issuance alone does not determine inclusion when a return contingency exists.', 'medium', 2),

-- Q7: easy / L1 — Weighted-average uses time-weighting, not simple average
(2, 'Earnings Per Share', 'Under ASC 260, is the denominator for basic EPS computed using a simple average of beginning and ending shares outstanding or a time-weighted average?', '["A time-weighted average reflecting the portion of the period each share count was outstanding", "A simple average of beginning and ending shares", "The ending shares outstanding on the balance sheet date", "The greater of beginning or ending shares outstanding"]'::jsonb, 0, 'Under ASC 260-10-45-10, the denominator for basic EPS is the weighted-average number of common shares outstanding during the period, reflecting the time each share count was in effect. A simple average of beginning and ending shares would produce an incorrect result when multiple share transactions occur at different dates. Option C is incorrect because end-of-period shares ignore the timing of share transactions throughout the year.', 'easy', 1),

-- Q8: hard / L4 — Conversion inducement: extra consideration reduces basic EPS numerator
(2, 'Earnings Per Share', 'Prescott Industries has $1,000,000 face value, 5% convertible bonds outstanding. To encourage early conversion, Prescott offers bondholders an additional 3,000 shares beyond the original conversion terms if they convert within 30 days. All bondholders accept. The market price of Prescott''s stock is $50 per share on the conversion date. Net income is $2,000,000 with 500,000 weighted-average shares. Analyze how the inducement affects the basic EPS numerator.', '["The par value of the additional shares is deducted from the basic EPS numerator", "The fair value of the additional 3,000 shares ($150,000) is deducted from net income in the basic EPS numerator", "The inducement has no effect on the basic EPS numerator because it is a capital transaction", "The full face value of the bonds ($1,000,000) is deducted from net income"]'::jsonb, 1, 'Under ASC 470-20-40-16 and ASC 260-10-45-15, when an entity offers additional consideration to induce conversion of convertible debt, the fair value of the additional securities ($150,000 = 3,000 shares x $50) is recognized as inducement expense and deducted from the basic EPS numerator. Option C is incorrect because the inducement is not a routine capital transaction; it represents additional consideration to retire the debt and is treated as expense.', 'hard', 4),

-- Q9: medium / L2 — Shares held by unconsolidated equity-method investee are NOT treasury stock for EPS
(2, 'Earnings Per Share', 'Paragon Corp. owns 35% of Bridgewell Inc. (accounted for under the equity method). Bridgewell holds 12,000 shares of Paragon''s common stock as a long-term investment. Paragon has 500,000 total shares outstanding. The controller proposes excluding the 12,000 shares from the EPS denominator, analogizing to the consolidated subsidiary treasury-stock rule. Evaluate this proposal.', '["The proposal is correct because equity-method investees are treated the same as consolidated subsidiaries for EPS purposes", "The proposal is correct because any affiliated entity holding the reporting entity''s shares triggers the treasury stock exclusion", "The proposal is incorrect; the treasury stock analogy applies only to shares held by consolidated subsidiaries, not equity-method investees", "The proposal is incorrect; the shares should be excluded from the numerator rather than the denominator"]'::jsonb, 2, 'Under ASC 260-10-45-7, shares of the reporting entity held by a consolidated subsidiary are treated as treasury shares and excluded from the denominator. However, this treatment does not extend to unconsolidated equity-method investees because they are not part of the consolidated reporting entity. Bridgewell''s 12,000 shares remain in Paragon''s 500,000-share weighted-average. Option A is incorrect because the treasury stock analogy in ASC 260 is limited to the consolidated group; equity-method investees operate outside that boundary.', 'medium', 2),

-- Q10: medium / L2 — Employee share purchase plan discount creates dilutive options for EPS
(2, 'Earnings Per Share', 'Oakmont Corp. sponsors a qualified employee stock purchase plan (ESPP) under Section 423 that allows employees to purchase shares at 85% of the lower of the stock price at the beginning or end of the offering period. During 2025, the average market price is $60, and the average ESPP purchase price is $42. Employees are expected to purchase 8,000 shares. The controller excludes the ESPP from diluted EPS because no stock options were granted. Evaluate this treatment.', '["The treatment is correct because ESPPs are not stock options and fall outside ASC 260", "The treatment is correct because Section 423 plans are tax-qualified and exempt from diluted EPS", "The treatment is incorrect; the ESPP discount is treated as an option with the purchase price as the exercise price, and the treasury stock method applies", "The treatment is incorrect; all 8,000 shares should be added to the denominator without any treasury stock offset"]'::jsonb, 2, 'Under ASC 260-10-55-38, a discounted ESPP is treated as equivalent to a stock option for diluted EPS purposes. The purchase price ($42) serves as the exercise price, and the treasury stock method is applied using the average market price ($60). Incremental shares = 8,000 minus (8,000 x $42 / $60) = 8,000 minus 5,600 = 2,400 shares added to the denominator. Option A is incorrect because ASC 260 explicitly addresses compensatory employee purchase plans and requires inclusion in diluted EPS when the effect is dilutive.', 'medium', 2),

-- Q11: medium / L2 — Beneficial conversion feature recognized at issuance reduces EPS numerator as a deemed dividend
(2, 'Earnings Per Share', 'Langford Corp. issues convertible preferred stock with a beneficial conversion feature (BCF) valued at $200,000 under ASC 470-20. The BCF is recognized as a discount on the preferred stock and accreted over the period to the earliest conversion date. In the issuance year, Langford accretes $80,000 of the BCF. Net income is $1,000,000 with 250,000 weighted-average common shares. How does the BCF accretion affect basic EPS?', '["No effect because the BCF is an equity-to-equity reclassification with no income statement impact", "The $200,000 BCF is deducted from the numerator immediately at issuance as a deemed dividend", "The $80,000 accretion is deducted from the numerator as an adjustment similar to a preferred dividend", "The $80,000 accretion is added back to the numerator because it reduces the preferred stock claim"]'::jsonb, 2, 'Under ASC 260-10-45-12 and ASC 470-20-25-5, the accretion of a beneficial conversion feature on preferred stock is treated as a deemed dividend to the preferred shareholders. The $80,000 of current-year accretion is deducted from the EPS numerator, reducing income available to common shareholders to $920,000. Option A is incorrect because, although the BCF does not hit the income statement, it has a direct effect on the EPS numerator through the deemed dividend mechanism, just like declared preferred dividends.', 'medium', 2),

-- Q12: easy / L1 — Convertible debt issued mid-year: if-converted assumes beginning-of-period conversion
(2, 'Earnings Per Share', 'Barrington Corp. issues $2,000,000 of 5% convertible bonds on October 1, 2025, convertible into 40,000 common shares. The bonds are outstanding for only three months during 2025. When computing diluted EPS for the full year 2025, over what period does the if-converted method assume the bonds were converted?', '["Only the three months the bonds were outstanding, from October 1 to December 31", "The full twelve months, assuming conversion at the beginning of the annual period", "Six months, using the midpoint of the issuance date and year-end", "The bonds are excluded from 2025 diluted EPS because they were outstanding for less than half the year"]'::jsonb, 0, 'Under ASC 260-10-45-40, the if-converted method assumes conversion occurred at the beginning of the period (or the date of issuance, if later). Because the bonds were issued October 1, the assumption runs from October 1 through December 31, meaning three months of after-tax interest is added back to the numerator and 40,000 shares are added to the denominator weighted for three months (10,000 full-year equivalent shares). Option B is incorrect because the beginning-of-period assumption cannot precede the issuance date; when bonds are issued mid-year, conversion is assumed from the issuance date.', 'easy', 1),

-- Q13: hard / L4 — Sequencing halts when next security would raise cumulative diluted EPS
(2, 'Earnings Per Share', 'Alderton Corp. has basic EPS of $4.00 ($800,000 income to common, 200,000 shares). Three securities are ranked by per-share impact: Security X adds 6,000 incremental shares with $0 numerator effect (impact $0.00), Security Y adds $12,000 and 8,000 shares (impact $1.50), and Security Z adds $50,000 and 10,000 shares (impact $5.00). After including X, cumulative EPS drops to $3.88. After including Y, cumulative EPS drops to $3.79. What should the controller do next regarding Security Z?', '["Include Z because it is a potentially dilutive security and must be tested", "Include Z because all convertible securities must appear in diluted EPS", "Exclude Z because its per-share impact of $5.00 exceeds the cumulative diluted EPS of $3.79, making it antidilutive", "Exclude Z and also remove Y because Y''s inclusion is now antidilutive"]'::jsonb, 2, 'Under ASC 260-10-45-21, securities are tested in order from most dilutive to least dilutive. Security Z''s per-share impact of $5.00 exceeds the cumulative diluted EPS of $3.79, so including Z would raise EPS (antidilutive). The controller reports diluted EPS of $3.79 including only X and Y. Option A is incorrect because the antidilution provision prohibits including any security whose effect would increase EPS or decrease loss per share.', 'hard', 4),

-- Q14: easy / L2 — Restricted shares with forfeitable dividends excluded from basic EPS two-class denominator
(2, 'Earnings Per Share', 'Wavecrest Inc. grants 12,000 nonvested restricted shares to employees. Dividends paid on the restricted shares are forfeitable if the employee terminates before vesting. The company has 250,000 vested common shares outstanding and net income of $600,000. The controller includes the 12,000 restricted shares in the two-class method denominator for basic EPS. Evaluate this treatment.', '["The treatment is correct because the restricted shares receive dividends during the vesting period", "The treatment is correct because all legally issued shares must appear in basic EPS", "The treatment is incorrect; restricted shares with forfeitable dividends are not participating securities for the two-class method", "The treatment is incorrect; restricted shares are always excluded from both basic and diluted EPS"]'::jsonb, 2, 'Under ASC 260-10-45-59A, nonvested shares with forfeitable dividend rights are not considered participating securities and are excluded from the two-class method for basic EPS. Only nonvested shares with nonforfeitable dividend rights qualify as participating securities. The 12,000 restricted shares should instead be evaluated for dilutive effect using the treasury stock method in diluted EPS. Option A is incorrect because receipt of dividends alone does not make a security participating if those dividends must be returned upon forfeiture.', 'easy', 2),

-- Q15: medium / L3 — Year-to-date interim EPS uses cumulative income / cumulative weighted-average
(2, 'Earnings Per Share', 'Meridian Corp. reports quarterly data for 2025: Q1 net income $200,000 with 100,000 shares, Q2 net income $400,000 with 100,000 shares, Q3 net income $150,000 with 140,000 shares (40,000 new shares issued July 1). An analyst computes nine-month year-to-date EPS as the sum of quarterly EPS figures: $2.00 + $4.00 + $1.07 = $7.07. Evaluate whether this approach complies with ASC 260 and ASC 270.', '["The approach is incorrect; year-to-date EPS is computed as cumulative income ($750,000) divided by the nine-month weighted-average shares, yielding approximately $6.62", "The approach is correct because ASC 260 permits summing quarterly EPS for year-to-date figures", "The approach is incorrect; only the most recent quarter''s EPS should be reported", "The approach is correct for interim reporting but the sum must be reconciled in the annual filing"]'::jsonb, 0, 'Under ASC 260-10-45-2 and ASC 270-10-45-8, year-to-date EPS is computed using cumulative net income divided by the year-to-date weighted-average shares, not by summing discrete quarterly EPS figures. The nine-month weighted-average is (100,000 x 6/9) + (140,000 x 3/9) = 113,333, yielding EPS of approximately $6.62. Option B is incorrect because changes in share count across quarters make the sum of quarterly EPS unequal to the properly computed year-to-date figure.', 'medium', 3),

-- Q16: hard / L4 — Error correction in prior-year EPS: restate rather than disclose prospectively
(2, 'Earnings Per Share', 'In preparing its 2025 financial statements, Belmont Corp. discovers that it overstated its 2024 weighted-average share count by 20,000 shares due to a computational error. The original 2024 basic EPS was reported as $3.80 (net income $950,000 / 250,000 shares). The correct denominator should have been 230,000 shares. The controller proposes disclosing the error in the 2025 footnotes without changing the comparative 2024 EPS column. Evaluate this proposal.', '["The proposal is acceptable because prior-period EPS is locked once filed", "The proposal is acceptable if the error is immaterial to overall financial statements", "The proposal is incorrect; ASC 250 requires retrospective restatement of the 2024 comparative EPS to approximately $4.13", "The proposal is incorrect; the correction should be reported as a cumulative adjustment to 2025 opening retained earnings only"]'::jsonb, 2, 'Under ASC 250-10-45-23 and ASC 260-10-45-16, a correction of an error affecting prior-period EPS requires retrospective restatement of the comparative amounts. The restated 2024 basic EPS is $950,000 / 230,000 = approximately $4.13 per share. Footnote-only disclosure without restatement is insufficient for an error correction. Option A is incorrect because prior-period EPS figures are subject to restatement under ASC 250 whenever a material error is identified, regardless of whether they were previously filed.', 'hard', 4),

-- Q17: easy / L1 — Contingently convertible (Co-Co) debt: conversion shares excluded until trigger met
(2, 'Earnings Per Share', 'Fairhaven Corp. issues contingently convertible (Co-Co) bonds that convert into common shares only if Fairhaven''s stock price exceeds $80 for 20 consecutive trading days. During 2025, the stock price never exceeds $65. Under ASC 260, are the potential conversion shares included in diluted EPS for 2025?', '["Yes, because all convertible securities must be included in diluted EPS regardless of market conditions", "Yes, but only at a probability-weighted number of shares", "No, because the market-price contingency was not satisfied as of the reporting date", "No, because contingently convertible bonds are always excluded from EPS"]'::jsonb, 2, 'Under ASC 260-10-45-46, for contingently convertible instruments, the potential conversion shares are included in diluted EPS only if the market-price (or other) contingency has been met as of the reporting date. Because Fairhaven''s stock never reached $80, the conversion trigger was not satisfied, and the shares are excluded from the 2025 diluted EPS denominator. Option A is incorrect because contingently convertible instruments receive special treatment under ASC 260 — unlike standard convertibles, the contingency must first be met.', 'easy', 1),

-- Q18: medium / L2 — Retrospective accounting change requires prior-period EPS restatement
(2, 'Earnings Per Share', 'In 2025, Thornton Corp. voluntarily changes its inventory method from LIFO to FIFO, applying the change retrospectively under ASC 250. The change increases 2024 net income by $80,000. Thornton had 200,000 weighted-average shares in 2024 and originally reported basic EPS of $3.50. How should Thornton present 2024 EPS in the 2025 comparative financial statements?', '["Report the original $3.50 with a footnote describing the change", "Report restated EPS of $3.10 reflecting a reduction in 2024 income", "Report both original and restated EPS side by side on the face of the income statement", "Report restated EPS of $3.90 reflecting the $80,000 increase in 2024 net income"]'::jsonb, 3, 'Under ASC 250-10-45-5 and ASC 260-10-45-16, a retrospective change in accounting principle requires restatement of prior-period financial statements, including EPS. Thornton''s restated 2024 basic EPS is ($700,000 + $80,000) / 200,000 = $3.90. Option A is incorrect because ASC 250 requires retrospective application, not merely footnote disclosure, when an accounting principle is changed voluntarily.', 'medium', 2),

-- Q19: easy / L1 — Mandatorily redeemable preferred classified as liability: interest deducted, not dividend
(2, 'Earnings Per Share', 'Under ASC 480, Linfield Corp. classifies its mandatorily redeemable preferred stock as a liability. The preferred stock requires annual payments of $200,000 that are reported as interest expense on the income statement. For basic EPS, how should these payments be treated in the numerator?', '["Deducted from net income as a preferred dividend adjustment", "Already reflected in net income through interest expense, so no further deduction from the numerator", "Added back to net income because they are noncash charges", "Deducted twice: once as interest and once as a preferred dividend"]'::jsonb, 1, 'Under ASC 260-10-45-11A, when preferred stock is classified as a liability under ASC 480, the related payments are recognized as interest expense in the income statement and are already reflected in net income. No additional deduction from the EPS numerator is needed because the charge flows through earnings, unlike traditional preferred dividends that bypass the income statement. Option A is incorrect because the liability classification means the payments are treated as interest, not as a dividend requiring a separate numerator adjustment.', 'easy', 1),

-- Q20: medium / L3 — Business combination: contingent consideration shares included in diluted EPS if dilutive
(2, 'Earnings Per Share', 'On January 1, 2025, Marston Corp. acquires a subsidiary and agrees to issue up to 50,000 additional shares if the subsidiary''s 2025 operating income exceeds $3,000,000. By June 30, the subsidiary''s year-to-date operating income is $1,200,000. The contingency has not yet been met. Marston has 400,000 weighted-average shares, net income of $1,600,000, and no preferred stock. How should the contingent shares be treated in diluted EPS for the six months ended June 30?', '["Include all 50,000 shares because the contingency is probable of being met", "Exclude the shares from both basic and diluted EPS because the contingency is not yet satisfied", "Include the shares in diluted EPS only if, based on current-period results as though the period end were the end of the contingency period, the condition would be satisfied", "Include a probability-weighted number of shares based on estimated likelihood"]'::jsonb, 2, 'Under ASC 260-10-45-48, contingently issuable shares in a business combination are included in diluted EPS if the shares would be issuable based on conditions existing at the end of the current reporting period, assuming the reporting date were the end of the contingency period. The test uses actual current-period results, not probability estimates. If the subsidiary''s year-to-date income extrapolated or as-of the period end would meet the target, the shares are included. Option D is incorrect because ASC 260 uses a period-end conditions test, not a probability-weighting approach.', 'medium', 3),

-- Q21: easy / L1 — Share buyback authorization has no effect until shares are actually repurchased
(2, 'Earnings Per Share', 'On November 1, 2025, Caldwell Corp.''s board authorizes repurchasing up to 100,000 shares of common stock, but no shares have been repurchased by December 31, 2025. Caldwell has 500,000 shares outstanding all year and net income of $1,500,000. What effect does the authorization have on basic EPS for 2025?', '["Basic EPS decreases because the market anticipates fewer shares", "The authorization increases basic EPS by reducing the denominator by 100,000 shares", "The authorization has no effect on basic EPS because no shares have been repurchased", "The authorization reduces the numerator by the estimated repurchase cost"]'::jsonb, 2, 'Under ASC 260-10-45-10, only actual changes in shares outstanding affect the weighted-average denominator for basic EPS. A board authorization to repurchase shares is a plan, not an executed transaction. Until shares are actually bought back, the weighted-average remains 500,000 and basic EPS is $3.00. Option B is incorrect because announced but unexecuted repurchase programs do not change the share count for EPS purposes.', 'easy', 1),

-- Q22: medium / L2 — ESOP committed-to-be-released shares included in weighted-average denominator
(2, 'Earnings Per Share', 'Oakdale Corp. sponsors an employee stock ownership plan (ESOP) that holds 80,000 shares. Of these, 30,000 are allocated (released) shares, 20,000 are committed-to-be-released shares, and 30,000 are suspense (unearned) shares. Oakdale has 400,000 other shares outstanding. For basic EPS, which ESOP shares are included in the weighted-average denominator?', '["All 80,000 ESOP shares because they are legally outstanding", "Only the 30,000 allocated shares", "The 30,000 allocated shares plus the 20,000 committed-to-be-released shares", "None of the ESOP shares because they are held in trust"]'::jsonb, 2, 'Under ASC 718-40-45-3 and ASC 260-10-45-7, allocated shares and committed-to-be-released shares are included in the weighted-average denominator for basic EPS because they represent shares that will be distributed to employees. Suspense (unearned) shares are excluded because they have not yet been earned or committed. Option A is incorrect because suspense shares, while legally outstanding, are treated similarly to treasury shares for EPS purposes and are excluded until committed or released.', 'medium', 2),

-- Q23: medium / L3 — Spinoff: parent adjusts prior-period EPS denominator using distribution ratio
(2, 'Earnings Per Share', 'On October 1, 2025, Redfield Corp. distributes 100% of its subsidiary Vantage Inc. to Redfield shareholders as a pro rata spinoff. Before the spinoff, Redfield had 500,000 shares outstanding. After the distribution, Redfield''s stock price drops from $80 to $60, implying the spun-off entity accounts for 25% of pre-distribution value. When presenting comparative 2024 EPS, how should Redfield adjust its prior-period denominator?', '["No adjustment is needed because the number of Redfield shares outstanding did not change", "Prior-period shares should be increased by 25% to reflect the value distributed", "Prior-period shares should be reduced by 25% because the entity is smaller post-spinoff", "Prior-period shares should be adjusted by a factor of $80 / $60 to compensate for the value transfer, similar to a stock dividend adjustment"]'::jsonb, 3, 'Under ASC 260-10-55-12C and SEC Staff guidance, a pro rata spinoff contains a distribution-of-value element analogous to a large stock dividend. The parent adjusts prior-period EPS denominators by the ratio of pre-distribution price to ex-distribution price ($80 / $60 = 1.333) to maintain comparability, because each pre-spinoff share represented a larger economic interest. Option A is incorrect because, although the share count did not change, the per-share economic value decreased, requiring an adjustment to make prior EPS comparable.', 'medium', 3),

-- Q24: medium / L2 — Cash-settled SARs do not affect diluted EPS denominator
(2, 'Earnings Per Share', 'Kingsley Corp. grants 25,000 stock appreciation rights (SARs) that require cash settlement based on the increase in Kingsley''s stock price over a $30 base price. The average market price during 2025 is $50. The controller adds incremental shares to the diluted EPS denominator using the treasury stock method, treating the SARs like stock options. Evaluate this treatment.', '["The treatment is correct because SARs are economically equivalent to options for EPS purposes", "The treatment is correct, but the controller should also adjust the numerator for compensation expense", "The treatment is incorrect; cash-settled SARs create a liability and do not affect the diluted EPS share count because no shares will be issued", "The treatment is incorrect; SARs are always antidilutive regardless of settlement method"]'::jsonb, 2, 'Under ASC 260-10-45-28 and ASC 718-10-25-11, only share-settled awards can add incremental shares to the diluted EPS denominator. Cash-settled SARs are classified as liabilities, and the entity will never issue shares upon exercise. The related compensation expense is already reflected in the income statement (reducing the numerator), and no dilution of the share count occurs. Option A is incorrect because the settlement method matters: share-settled SARs use the treasury stock method, but cash-settled SARs do not affect the denominator.', 'medium', 2),

-- Q25: hard / L4 — Make-whole premium on early conversion adds shares to diluted EPS denominator
(2, 'Earnings Per Share', 'Wexfield Corp. issued $5,000,000 of 4% convertible bonds with a make-whole provision requiring an additional 8,000 shares if bondholders convert before the fifth anniversary. Under the standard if-converted method, the bonds add 100,000 potential shares and $150,000 of after-tax interest. The controller excludes the 8,000 make-whole shares from diluted EPS, arguing they are contingent on early conversion. Evaluate the controller''s position.', '["The controller is correct; make-whole shares are contingent and excluded until the contingency is resolved", "The controller is correct; make-whole provisions are always antidilutive", "The controller is incorrect; the additional 8,000 make-whole shares must be included in diluted EPS if their inclusion would be dilutive", "The controller is incorrect; the make-whole shares replace the standard 100,000 conversion shares"]'::jsonb, 2, 'Under ASC 260-10-45-22 and 45-40, the if-converted method assumes conversion under the most advantageous terms available to the holder. Make-whole provisions that provide additional shares upon conversion are part of the convertible''s terms. Since the if-converted method assumes conversion occurred at the beginning of the period, the make-whole premium applies, and the 8,000 shares should be added to the 100,000 base conversion shares if dilutive. Option A is incorrect because the make-whole is an embedded feature, not a separate contingency.', 'hard', 4),

-- Q26: medium / L3 — Partially paid share subscriptions: equivalent shares in denominator
(2, 'Earnings Per Share', 'Clayborne Inc. has 180,000 fully paid shares outstanding. On March 1, 2025, it issues 30,000 shares under a subscription agreement at $40 per share. Subscribers paid 50% at issuance and the remaining 50% on September 1, 2025. Under ASC 260-10-45-13, partially paid shares are included based on the proportion paid. Calculate the weighted-average shares for basic EPS.', '["195,000 shares because the subscribed shares are fully included from March 1", "180,000 shares because subscribed shares are excluded until fully paid", "197,500 shares reflecting the equivalent paid portion weighted from each payment date", "210,000 shares because all subscribed shares are included for the full year"]'::jsonb, 2, 'Under ASC 260-10-45-13, partially paid shares are included in the weighted-average based on the proportion of the subscription price paid. From March 1 to August 31 (6 months), 15,000 equivalent shares (50% of 30,000) are included. From September 1 to December 31 (4 months), all 30,000 shares are included (fully paid). Weighted-average = 180,000 + (15,000 x 6/12) + (30,000 x 4/12) = 180,000 + 7,500 + 10,000 = 197,500. Option A is incorrect because only the paid portion counts before full payment.', 'medium', 3),

-- Q27: medium / L3 — Dual effect: stock comp expense reduces numerator, unvested awards increase diluted denominator
(2, 'Earnings Per Share', 'Bramwell Technologies reports net income of $800,000 after recognizing $120,000 of stock-based compensation expense for 15,000 unvested RSUs. The company has 200,000 weighted-average shares. For diluted EPS, the RSUs produce 8,000 incremental shares under the treasury stock method. A financial analyst asserts that the $120,000 expense and the 8,000 diluted shares create a double-counting effect. Analyze this assertion.', '["The analyst is correct; the diluted EPS denominator should exclude RSUs because the expense is already recognized in the numerator", "The analyst is correct; the RSU expense and diluted shares create a genuine double-counting effect that must be adjusted", "The analyst is incorrect; the expense should be added back to the numerator before computing diluted EPS", "The analyst is incorrect; the expense reduces the numerator in basic EPS while the incremental shares increase the denominator in diluted EPS, and both adjustments are required"]'::jsonb, 3, 'Under ASC 260-10-45-29 and ASC 718, stock-based compensation expense reduces net income (the numerator), and unvested awards that are dilutive add incremental shares to the denominator. These are two separate and required effects. The numerator reflects the cost of the arrangement, while the denominator reflects the potential future dilution from share issuance. Option A is incorrect because no double-counting exists; removing RSUs from diluted EPS would understate dilution.', 'medium', 3),

-- Q28: hard / L4 — ASU 2020-06: capped call excluded from diluted EPS as purchased option
(2, 'Earnings Per Share', 'Rexford Corp. issues $10,000,000 of 2% convertible notes and simultaneously purchases a capped call with a cap price of $70. Under ASU 2020-06, the notes are a single liability. The average market price is $65 with a conversion price of $50. The controller excludes the capped call from diluted EPS and applies the if-converted method only to the notes. Evaluate this approach.', '["The approach is incorrect; the capped call must be combined with the notes for diluted EPS to reflect the net dilutive effect", "The approach is correct; the capped call is a separate freestanding purchased option that is antidilutive and excluded, while the notes use the if-converted method", "The approach is incorrect; both the notes and the capped call should use the treasury stock method under ASU 2020-06", "The approach is correct, but only because the capped call is out of the money"]'::jsonb, 1, 'Under ASU 2020-06, convertible notes use the if-converted method. The capped call is a separate freestanding derivative (a purchased call option). Under ASC 260-10-45-35A, purchased options are never included in diluted EPS because they are antidilutive by nature: the entity paid cash for the right to buy its own shares. Option A is incorrect because GAAP does not permit combining the capped call with the convertible notes for EPS purposes, even though they were entered simultaneously.', 'hard', 4),

-- Q29: medium / L3 — Acquirer includes acquiree''s results only from acquisition date in EPS numerator
(2, 'Earnings Per Share', 'On July 1, 2025, Stratton Corp. acquires 100% of Millbrook Inc. in a business combination accounted for under ASC 805. Millbrook earned $600,000 in the first half of 2025 (pre-acquisition) and $500,000 in the second half (post-acquisition). Stratton issues 80,000 new shares as consideration. Stratton''s own pre-acquisition net income is $2,000,000 with 400,000 shares outstanding all year. What numerator and denominator should Stratton use for 2025 basic EPS?', '["Numerator: $3,100,000 (all of Millbrook''s earnings); denominator: 480,000 shares for the full year", "Numerator: $2,500,000 (Stratton''s income plus Millbrook''s post-acquisition income); denominator: 440,000 shares (400,000 + 80,000 x 6/12)", "Numerator: $2,000,000 (Stratton''s income only); denominator: 400,000 shares (excluding consideration shares)", "Numerator: $2,500,000; denominator: 480,000 shares for the full year"]'::jsonb, 1, 'Under ASC 805-10-45-1 and ASC 260-10-45-10, in a business combination, the acquirer includes the acquiree''s results only from the acquisition date. The numerator includes Stratton''s $2,000,000 plus Millbrook''s $500,000 post-acquisition income = $2,500,000. The 80,000 consideration shares enter the weighted-average from July 1, yielding 400,000 + (80,000 x 6/12) = 440,000. Option A is incorrect because Millbrook''s pre-acquisition earnings of $600,000 belong to the former owners and are excluded from the acquirer''s EPS.', 'medium', 3),

-- Q30: easy / L1 — Share repurchase reduces outstanding shares but retirement vs. treasury has same EPS effect
(2, 'Earnings Per Share', 'Calloway Inc. repurchases 20,000 of its own common shares on July 1, 2025, and retires them permanently rather than holding them as treasury stock. Before the repurchase, 300,000 shares were outstanding. For basic EPS, how does the retirement differ from holding the shares as treasury stock?', '["Retired shares reduce the denominator more than treasury shares because authorized shares also decrease", "Treasury shares remain in the denominator but retired shares do not", "Retired shares have no effect on EPS because they are a permanent capital reduction", "There is no difference; both retirement and treasury stock treatment remove the shares from the weighted-average as of the repurchase date"]'::jsonb, 3, 'Under ASC 260-10-45-10, both retired shares and treasury shares are excluded from the weighted-average from the repurchase date. The method of accounting for the reacquired shares (retirement versus treasury) does not change the EPS computation. In both cases, the weighted-average is (300,000 x 6/12) + (280,000 x 6/12) = 290,000. Option B is incorrect because treasury shares are also excluded from the weighted-average, not just retired shares.', 'easy', 1)
;

COMMIT;
