-- Migration: Question generation — ISC batch 10 (30 questions)
-- Date: 2026-03-24
-- Topic: Security Controls and Monitoring
-- Difficulty: 9E / 15M / 6H
-- Bloom's: L1:6 / L2:10 / L3:9 / L4:5

BEGIN;

INSERT INTO questions (section_id, topic, stem, choices, correct_index, explanation, difficulty, cognitive_level)
VALUES

-- Q1: easy / L1 — Hashing definition (one-way function)
(5, 'Security Controls and Monitoring', $EXPL$What is the PRIMARY characteristic that distinguishes hashing from encryption?$EXPL$, $EXPL$["Hashing is a one-way function that cannot be reversed to recover the original data", "Hashing uses a public and private key pair for transformation", "Hashing produces variable-length output depending on input size", "Hashing requires a shared secret key between sender and receiver"]$EXPL$::jsonb, 0, $EXPL$Correct (A): Per NIST SP 800-107, a cryptographic hash function produces a fixed-length digest from arbitrary input and is computationally infeasible to reverse. This one-way property distinguishes hashing from encryption, which is designed to be reversible with the correct key. Wrong (B): Asymmetric encryption uses key pairs, not hashing. Wrong (C): Hash output is always fixed-length regardless of input size (e.g., SHA-256 always produces 256 bits). Wrong (D): Hashing requires no key at all; symmetric encryption requires a shared key.$EXPL$, 'easy', 1),

-- Q2: medium / L3 — SSO credential compromise scenario
(5, 'Security Controls and Monitoring', $EXPL$Merrifield Consulting implements Single Sign-On (SSO) across its 14 cloud applications, including email, CRM, and financial reporting. A security assessment reveals that SSO credentials are protected only by passwords. The CISO requests a risk analysis. Which of the following BEST describes the primary risk introduced by this SSO configuration?$EXPL$, $EXPL$["SSO eliminates the need for application-level access controls", "Compromise of the single SSO credential grants the attacker access to all 14 connected applications", "SSO prevents the organization from implementing role-based access controls", "SSO requires each application to maintain its own separate user directory"]$EXPL$::jsonb, 1, $EXPL$Correct (B): Per NIST SP 800-63B, SSO centralizes authentication so that a single compromised credential exposes all connected systems. Without MFA protecting the SSO credential, password theft through phishing or brute force gives an attacker broad access across the entire application portfolio. Wrong (A): SSO handles authentication, not authorization; application-level access controls remain independent. Wrong (C): RBAC operates independently of SSO and can be enforced within each application. Wrong (D): SSO centralizes the user directory rather than requiring separate directories per application.$EXPL$, 'medium', 3),

-- Q3: medium / L2 — Biometric CER interpretation
(5, 'Security Controls and Monitoring', $EXPL$Hartwell Securities is evaluating two biometric systems for data center access. System A has a Crossover Error Rate (CER) of 2.1%, while System B has a CER of 4.7%. The security team needs to select the more accurate system. Which of the following BEST interprets these CER values?$EXPL$, $EXPL$["System B is more accurate because a higher CER indicates fewer false rejections", "Both systems are equally accurate because CER measures only false acceptances", "System A is more accurate because a lower CER indicates the point where false acceptance and false rejection rates are equal is lower", "System A is less accurate because a lower CER means the system rejects more authorized users"]$EXPL$::jsonb, 2, $EXPL$Correct (C): Per NIST SP 800-76, the Crossover Error Rate is the point where the False Acceptance Rate (FAR) equals the False Rejection Rate (FRR). A lower CER indicates a more accurate biometric system overall, making System A with 2.1% the superior choice. Wrong (A): A higher CER indicates lower accuracy, not fewer false rejections. Wrong (B): CER measures the intersection of both FAR and FRR, not just false acceptances. Wrong (D): A lower CER means the system achieves better balance between accepting unauthorized and rejecting authorized users at a lower error rate.$EXPL$, 'medium', 2),

-- Q4: easy / L1 — DMZ purpose
(5, 'Security Controls and Monitoring', $EXPL$What is the PRIMARY purpose of a demilitarized zone (DMZ) in network architecture?$EXPL$, $EXPL$["To encrypt all internal network traffic between servers", "To store backup copies of sensitive data offsite", "To replace the need for internal firewalls", "To isolate public-facing services from the internal network"]$EXPL$::jsonb, 3, $EXPL$Correct (D): Per NIST SP 800-41, a DMZ is an isolated network segment positioned between the external internet and the internal network. It hosts public-facing services such as web servers and email gateways, preventing direct external access to internal systems. Wrong (A): A DMZ provides network segmentation, not encryption; TLS or VPNs handle encryption. Wrong (B): A DMZ hosts services, not backup data; offsite backups are a separate control. Wrong (C): A DMZ supplements internal firewalls rather than replacing them; defense-in-depth requires multiple layers.$EXPL$, 'easy', 1),

-- Q5: hard / L3 — Defense-in-depth gap analysis
(5, 'Security Controls and Monitoring', $EXPL$Ashburn Technology conducts a security architecture review and documents the following controls: perimeter firewall filtering inbound traffic, endpoint antivirus on all workstations, and encrypted VPN for remote access. The security architect notes that no network-level monitoring exists between the perimeter firewall and the endpoints. An attacker who bypasses the firewall using a zero-day exploit would face which specific gap in the defense-in-depth strategy?$EXPL$, $EXPL$["No detection layer exists to identify lateral movement or malicious traffic within the internal network", "The VPN encryption prevents the firewall from inspecting outbound traffic", "The endpoint antivirus would automatically block all network-based attacks", "The perimeter firewall would log the zero-day exploit for later forensic analysis"]$EXPL$::jsonb, 0, $EXPL$Correct (A): Per NIST SP 800-53 (SI-4), defense-in-depth requires layered controls including network monitoring (IDS/IPS) between perimeter and endpoint layers. Without internal network monitoring, an attacker who bypasses the firewall can move laterally undetected until reaching an endpoint, leaving a critical detection gap. Wrong (B): VPN encryption protects remote access traffic but does not prevent firewall inspection of other outbound traffic. Wrong (C): Endpoint antivirus detects known malware signatures but cannot block all network-based attacks, especially novel exploits. Wrong (D): A zero-day exploit by definition exploits unknown vulnerabilities, so the firewall may not have signatures to log it.$EXPL$, 'hard', 3),

-- Q6: easy / L1 — DAC model definition
(5, 'Security Controls and Monitoring', $EXPL$What is the defining characteristic of Discretionary Access Control (DAC)?$EXPL$, $EXPL$["Access is determined by system-enforced classification labels", "The resource owner decides who can access the resource", "Access is assigned based on the user's organizational role", "Access decisions are based on multiple attributes evaluated by policies"]$EXPL$::jsonb, 1, $EXPL$Correct (B): Per NIST SP 800-12, Discretionary Access Control allows the resource owner to grant or revoke access at their discretion. This model provides flexibility but is less secure because access decisions depend on individual owner judgment. Wrong (A): System-enforced classification labels describe Mandatory Access Control (MAC), not DAC. Wrong (C): Role-based access assignment describes RBAC, where permissions attach to roles rather than individual owner decisions. Wrong (D): Attribute-based policy evaluation describes ABAC, which uses user, resource, and environment attributes.$EXPL$, 'easy', 1),

-- Q7: easy / L2 — MAC classification labels scenario
(5, 'Security Controls and Monitoring', $EXPL$A defense contractor stores documents classified as Confidential, Secret, and Top Secret. An analyst with Secret clearance attempts to access a Top Secret document, but the system automatically denies the request regardless of any manager override. Which access control model is this system using?$EXPL$, $EXPL$["Discretionary Access Control (DAC)", "Role-Based Access Control (RBAC)", "Mandatory Access Control (MAC)", "Attribute-Based Access Control (ABAC)"]$EXPL$::jsonb, 2, $EXPL$Correct (C): Per NIST SP 800-12, Mandatory Access Control enforces access based on classification labels assigned to both subjects and objects. The system prevents any user from accessing data above their clearance level, and users cannot override these restrictions. Wrong (A): DAC would allow the resource owner to grant access at their discretion, which contradicts the automatic denial. Wrong (B): RBAC assigns access based on organizational roles, not classification levels that prevent manager overrides. Wrong (D): ABAC evaluates multiple attributes via policies but does not inherently enforce hierarchical classification labels.$EXPL$, 'easy', 2),

-- Q8: medium / L3 — Log integrity tamper scenario
(5, 'Security Controls and Monitoring', $EXPL$Glendale Financial discovers during an incident investigation that an attacker gained administrative access to the centralized log server and deleted all authentication logs from a 48-hour period. The forensic team cannot reconstruct the timeline of the breach. Which control would have MOST effectively prevented this evidence destruction?$EXPL$, $EXPL$["Increasing the log retention period to seven years", "Implementing real-time SIEM alerting on failed login attempts", "Encrypting all log files with AES-256 at rest", "Forwarding logs to write-once immutable storage that administrators cannot modify"]$EXPL$::jsonb, 3, $EXPL$Correct (D): Per NIST SP 800-92, log integrity requires protection against tampering, including by privileged insiders. Write-once immutable storage (such as WORM media or append-only cloud storage) prevents deletion or modification even by administrators, preserving forensic evidence. Wrong (A): Longer retention does not prevent deletion; if the attacker has admin access, they can delete logs regardless of retention policy. Wrong (B): SIEM alerting detects suspicious activity but does not prevent an administrator from deleting the underlying log files. Wrong (C): Encrypting logs at rest protects confidentiality but does not prevent an administrator with the proper keys from deleting the encrypted files.$EXPL$, 'medium', 3),

-- Q9: medium / L3 — Alerting threshold configuration scenario
(5, 'Security Controls and Monitoring', $EXPL$Crestview Bank configures its SIEM to alert on any single failed login attempt. Within one week, the security operations center receives over 50,000 alerts, most caused by employees mistyping passwords. Analysts begin ignoring alerts entirely. Which remediation would BEST address this operational problem while maintaining detection capability?$EXPL$, $EXPL$["Configuring threshold-based alerting that triggers only after five or more failed attempts within a 10-minute window from the same account", "Disabling failed login alerting entirely to reduce analyst workload", "Requiring all employees to use password managers to eliminate mistyped passwords", "Routing all alerts directly to the help desk instead of the security team"]$EXPL$::jsonb, 0, $EXPL$Correct (A): Per NIST SP 800-92, alerting thresholds should balance detection sensitivity with operational sustainability. Threshold-based rules (e.g., five failures in 10 minutes) filter routine typos while still detecting brute-force attacks, preventing alert fatigue that leads analysts to ignore genuine threats. Wrong (B): Disabling alerting eliminates a critical detective control and leaves brute-force attacks undetected. Wrong (C): Password managers may reduce typos but do not address the alerting configuration problem, and adoption cannot be guaranteed. Wrong (D): Routing alerts to the help desk shifts the burden without reducing volume or improving detection accuracy.$EXPL$, 'medium', 3),

-- Q10: easy / L2 — Environmental controls identification
(5, 'Security Controls and Monitoring', $EXPL$A data center installs an uninterruptible power supply (UPS), a fire suppression system, and humidity-controlled HVAC. These controls collectively protect against which category of threat?$EXPL$, $EXPL$["Unauthorized logical access to servers and databases", "Environmental threats that could damage physical infrastructure", "Social engineering attacks targeting data center personnel", "Malware infections spreading across networked systems"]$EXPL$::jsonb, 1, $EXPL$Correct (B): Per NIST SP 800-53 (PE-9 through PE-15), UPS, fire suppression, and HVAC are environmental controls designed to protect physical infrastructure from power outages, fire, and temperature or humidity extremes that could damage hardware. Wrong (A): Logical access controls such as authentication and authorization protect against unauthorized system access, not environmental hazards. Wrong (C): Security awareness training and verification procedures address social engineering, not environmental threats. Wrong (D): Antivirus software and network segmentation address malware, not physical environmental conditions.$EXPL$, 'easy', 2),

-- Q11: medium / L2 — Full-disk vs column-level encryption decision
(5, 'Security Controls and Monitoring', $EXPL$Whitfield Medical Group stores patient records in a database and needs to encrypt Social Security numbers and diagnosis codes while still allowing clinicians to query patient names and appointment dates without decryption overhead. Which encryption approach BEST meets this requirement?$EXPL$, $EXPL$["Full-disk encryption using BitLocker on the database server", "Encrypting the entire database backup with a single AES key", "Column-level encryption applied only to the sensitive fields", "Implementing TLS on all database connections"]$EXPL$::jsonb, 2, $EXPL$Correct (C): Per NIST SP 800-111, column-level encryption (also called field-level encryption) encrypts individual database columns, allowing queries on non-encrypted columns without decryption overhead. This precisely targets sensitive fields while maintaining performance for routine queries. Wrong (A): Full-disk encryption protects the entire volume transparently but does not provide selective field-level protection; all data must be decrypted when the disk is mounted. Wrong (B): Encrypting backups with a single key protects data at rest in storage but does not address selective encryption of live database fields. Wrong (D): TLS protects data in transit between application and database but does not encrypt data stored within the database itself.$EXPL$, 'medium', 2),

-- Q12: hard / L4 — Biometric FAR/FRR sensitivity tradeoff evaluation
(5, 'Security Controls and Monitoring', $EXPL$Oakmont Defense installs a fingerprint scanner for its classified research facility. During initial configuration, the security team must choose the biometric sensitivity threshold. A more sensitive setting reduces the False Acceptance Rate (FAR) to 0.01% but increases the False Rejection Rate (FRR) to 12%, meaning authorized researchers are frequently locked out and must call security for manual verification. A less sensitive setting reduces FRR to 1% but increases FAR to 3%. Which recommendation BEST balances security requirements with operational impact for a classified environment?$EXPL$, $EXPL$["Use the less sensitive setting because researcher productivity is more important than access security", "Disable the biometric system and use badge-only access to eliminate both error types", "Use a moderate sensitivity setting that sets FAR and FRR to approximately equal levels", "Use the more sensitive setting (low FAR) because preventing unauthorized access to classified data outweighs the inconvenience of occasional false rejections"]$EXPL$::jsonb, 3, $EXPL$Correct (D): Per NIST SP 800-76, environments handling classified data must prioritize preventing unauthorized access (low FAR) over user convenience. The 12% FRR creates operational friction but can be mitigated with a manual verification fallback, whereas a 3% FAR in a classified facility represents an unacceptable risk of unauthorized access to sensitive materials. Wrong (A): In a classified environment, security requirements take precedence over convenience; a 3% false acceptance rate is too high. Wrong (B): Eliminating biometrics removes a strong authentication factor and weakens the overall security posture. Wrong (C): The Crossover Error Rate (CER) balances both rates but may not be appropriate for high-security environments where preventing unauthorized access is paramount.$EXPL$, 'hard', 4),

-- Q13: easy / L1 — Deterrent control definition
(5, 'Security Controls and Monitoring', $EXPL$What is the PRIMARY purpose of a deterrent security control?$EXPL$, $EXPL$["To discourage potential threats before they occur", "To detect security incidents while they are in progress", "To restore systems to normal operation after an incident", "To automatically block malicious network traffic"]$EXPL$::jsonb, 0, $EXPL$Correct (A): Per COBIT 2019, deterrent controls are designed to discourage potential threat actors from attempting an attack. Examples include warning banners, security cameras, and acceptable use policies that signal consequences. Wrong (B): Detecting incidents in progress describes detective controls such as IDS or SIEM alerting. Wrong (C): Restoring systems after an incident describes corrective controls such as backup restoration or patch deployment. Wrong (D): Automatically blocking traffic describes a preventive control such as a firewall or IPS.$EXPL$, 'easy', 1),

-- Q14: medium / L2 — Mantrap physical access control
(5, 'Security Controls and Monitoring', $EXPL$Calloway Data Services installs a mantrap (interlocking door system) at the entrance to its server room. The mantrap requires badge authentication at the first door and biometric verification at the second door. Only one door can be open at a time. What security risk does this physical control PRIMARILY mitigate?$EXPL$, $EXPL$["Malware infection of servers through removable media", "Tailgating, where an unauthorized person follows an authorized person through a secured entrance", "Denial-of-service attacks against the building's network infrastructure", "Insider threats from authorized employees accessing unauthorized data"]$EXPL$::jsonb, 1, $EXPL$Correct (B): Per NIST SP 800-116, mantraps (also called airlock entries or interlocking doors) prevent tailgating by ensuring only one authenticated individual can pass through at a time. The interlocking mechanism requires the first door to close before the second opens, trapping anyone who did not authenticate. Wrong (A): Removable media policies and endpoint security address malware from physical media, not physical entry control. Wrong (C): DDoS protection is a network-level control unrelated to physical entry mechanisms. Wrong (D): Mantraps control physical entry, not logical access to data; insider data access is managed by authorization controls like RBAC.$EXPL$, 'medium', 2),

-- Q15: easy / L2 — Password hashing vs plaintext storage
(5, 'Security Controls and Monitoring', $EXPL$A company stores user passwords as SHA-256 hashes in its authentication database rather than storing them in plaintext. If an attacker gains access to the database, what protection does this hashing provide?$EXPL$, $EXPL$["The attacker can easily reverse the hash to recover the original passwords", "The attacker can use the hashes directly to log in without knowing the passwords", "The attacker cannot derive the original passwords from the hashes because hashing is a one-way function", "The hashes automatically expire after 90 days, rendering them useless"]$EXPL$::jsonb, 2, $EXPL$Correct (C): Per NIST SP 800-63B, storing passwords as cryptographic hashes ensures that even if the database is compromised, the original passwords cannot be recovered because hash functions are one-way. The attacker would need to use computationally expensive methods like brute force or rainbow tables. Wrong (A): Cryptographic hashes are designed to be irreversible; easy reversal would defeat their purpose. Wrong (B): Hashes cannot be used directly for authentication because the system hashes the entered password and compares it to the stored hash. Wrong (D): Hashes do not expire; password expiration policies are a separate administrative control.$EXPL$, 'easy', 2),

-- Q16: hard / L4 — SSO with conditional access evaluation
(5, 'Security Controls and Monitoring', $EXPL$Redfield Financial implements SSO across its application portfolio and wants to add adaptive access controls. The security architect proposes conditional access policies that evaluate device compliance status, geographic location, and user risk score before granting SSO tokens. During a tabletop exercise, the team identifies that an attacker who compromises a compliant corporate laptop in the office would satisfy all conditional access checks. Which additional control layer would MOST effectively mitigate this residual risk?$EXPL$, $EXPL$["Requiring password changes every 30 days for all SSO users", "Removing SSO and requiring separate credentials for each application", "Extending the conditional access policy to include additional geographic zones", "Implementing continuous session monitoring that re-evaluates risk signals and revokes access upon anomalous behavior"]$EXPL$::jsonb, 3, $EXPL$Correct (D): Per NIST SP 800-207 (Zero Trust Architecture), continuous session evaluation monitors behavioral signals (unusual data access patterns, privilege escalation attempts) throughout the session rather than only at initial authentication. This detects post-authentication compromise that passed initial conditional access checks. Wrong (A): Password rotation does not address the scenario where the attacker has already compromised the device and can capture new passwords. Wrong (B): Eliminating SSO increases password fatigue and attack surface without addressing the compromised device problem. Wrong (C): Adding geographic locations does not help because the attacker is already operating from the legitimate corporate location.$EXPL$, 'hard', 4),

-- Q17: hard / L4 — Log architecture compliance evaluation
(5, 'Security Controls and Monitoring', $EXPL$Kensington Pharmaceuticals must comply with FDA 21 CFR Part 11 requirements for electronic records, which mandate that audit trails be retained, tamper-evident, and available for regulatory inspection. The current architecture stores logs locally on each application server with a 90-day retention period and no integrity verification. The IT director asks the auditor to evaluate three remediation options: (1) extend local retention to two years, (2) replicate logs to a centralized SIEM with one-year retention, or (3) replicate logs to a WORM-compliant centralized archive with cryptographic integrity verification and two-year retention. Which option BEST satisfies the regulatory requirements?$EXPL$, $EXPL$["Option 3, because WORM storage with cryptographic verification provides both tamper-evidence and adequate retention for regulatory inspection", "Option 1, because extending local retention to two years exceeds the regulatory minimum", "Option 2, because SIEM centralization automatically provides tamper-evidence", "All three options equally satisfy the regulatory requirements"]$EXPL$::jsonb, 0, $EXPL$Correct (A): Per FDA 21 CFR Part 11 and NIST SP 800-92, compliant audit trails require tamper-evidence, adequate retention, and availability for inspection. WORM (Write Once Read Many) storage with cryptographic integrity verification satisfies tamper-evidence requirements, and two-year retention exceeds the minimum. Wrong (B): Extending local retention does not address tamper-evidence; an administrator could still modify or delete local logs. Wrong (C): SIEM centralization improves log aggregation but does not inherently provide tamper-evidence unless specifically configured with immutable storage. Wrong (D): Options 1 and 2 fail to address the tamper-evidence requirement, a critical regulatory mandate.$EXPL$, 'hard', 4),

-- Q18: medium / L3 — Network segmentation lateral movement scenario
(5, 'Security Controls and Monitoring', $EXPL$Prescott Retail operates a flat network where point-of-sale (POS) terminals, employee workstations, and the inventory database all share the same network segment. An attacker compromises an employee workstation through a phishing email and discovers that the POS terminals are directly reachable. Which network architecture change would MOST effectively limit the attacker's ability to pivot from the workstation to the POS environment?$EXPL$, $EXPL$["Installing antivirus software on all POS terminals", "Implementing network segmentation with firewall rules restricting traffic between the employee and POS network segments", "Encrypting all traffic between workstations and POS terminals", "Upgrading the network switches to support higher bandwidth"]$EXPL$::jsonb, 1, $EXPL$Correct (B): Per NIST SP 800-53 (SC-7) and PCI DSS Requirement 1, network segmentation isolates the POS environment into a separate network segment with firewall rules controlling inter-segment traffic. This limits lateral movement by preventing a compromised workstation from directly reaching POS terminals. Wrong (A): Antivirus on POS terminals is a detective/corrective control at the endpoint but does not prevent the attacker from reaching the POS network. Wrong (C): Encrypting traffic protects data confidentiality in transit but does not prevent network connectivity or lateral movement. Wrong (D): Higher bandwidth does not address security segmentation and may actually enable faster data exfiltration.$EXPL$, 'medium', 3),

-- Q19: medium / L3 — SHA-1 deprecation collision risk scenario
(5, 'Security Controls and Monitoring', $EXPL$Dunmore Software uses SHA-1 to verify the integrity of software patches before deployment. A security researcher publishes a practical collision attack demonstrating that two different files can produce the same SHA-1 hash. The security team must assess the risk to Dunmore's patch verification process. What is the MOST significant risk this collision vulnerability creates?$EXPL$, $EXPL$["SHA-1 hashes will no longer produce fixed-length output for software patches", "The collision vulnerability only affects password storage, not file integrity verification", "An attacker could create a malicious patch that produces the same SHA-1 hash as the legitimate patch, bypassing integrity verification", "SHA-1 collision attacks require quantum computing and are not practically exploitable"]$EXPL$::jsonb, 2, $EXPL$Correct (C): Per NIST SP 800-131A, SHA-1 is deprecated because practical collision attacks allow an adversary to craft a malicious file with the same hash as a legitimate file. This undermines integrity verification because the system cannot distinguish between the genuine and malicious versions. Wrong (A): SHA-1 still produces fixed-length 160-bit output; collisions do not change the output format. Wrong (B): Collision vulnerabilities affect all uses of the hash function, including file integrity, digital signatures, and certificate validation. Wrong (D): SHA-1 collision attacks have been demonstrated on commodity hardware since 2017 and do not require quantum computing.$EXPL$, 'medium', 3),

-- Q20: medium / L2 — UPS as environmental control classification
(5, 'Security Controls and Monitoring', $EXPL$An organization deploys an uninterruptible power supply (UPS) in its data center to maintain server operations during power outages until the backup generator activates. In the context of the NIST control framework, how should the UPS be classified?$EXPL$, $EXPL$["A detective control because it identifies when power failures occur", "A corrective control because it restores power after a failure", "A deterrent control because it discourages attackers from targeting power systems", "A preventive control because it prevents service interruption from power loss"]$EXPL$::jsonb, 3, $EXPL$Correct (D): Per NIST SP 800-53 (PE-11), a UPS is classified as a preventive control because it provides immediate power continuity during an outage, preventing service interruption before the backup generator starts. It stops the threat (power loss) from causing the impact (system downtime). Wrong (A): The UPS does not merely detect power failures; it actively prevents their impact on operations. Wrong (B): A corrective control remediates after impact occurs; the UPS acts proactively before systems lose power. Wrong (C): A deterrent control discourages threat actors; a UPS has no deterrent effect on power failures, which are typically environmental.$EXPL$, 'medium', 2),

-- Q21: medium / L2 — Visitor management as physical control
(5, 'Security Controls and Monitoring', $EXPL$A data center requires all visitors to sign a log, present government-issued identification, receive a temporary badge, and be escorted by an authorized employee at all times. Which type of security control does this visitor management process represent?$EXPL$, $EXPL$["A physical security control that combines preventive and detective elements", "A logical access control that authenticates visitors to the network", "A corrective control that responds to unauthorized physical access", "A compensating control that substitutes for electronic badge readers"]$EXPL$::jsonb, 0, $EXPL$Correct (A): Per NIST SP 800-53 (PE-8), visitor management is a physical security control with preventive elements (ID verification, escort requirements preventing unauthorized access) and detective elements (sign-in logs creating an audit trail). Together these controls manage physical access risk. Wrong (B): Visitor management controls physical access, not logical network access; network authentication uses different mechanisms. Wrong (C): Corrective controls remediate after an incident; visitor management proactively prevents and tracks access before incidents occur. Wrong (D): Visitor management is a primary control in its own right, not a substitute for another control.$EXPL$, 'medium', 2),

-- Q22: medium / L3 — DNS query logging for threat detection
(5, 'Security Controls and Monitoring', $EXPL$Fairview Credit Union enables DNS query logging on its internal DNS servers after a threat intelligence report indicates that advanced malware frequently uses DNS tunneling to exfiltrate data. During the first week of monitoring, the security analyst identifies one workstation generating 5,000 DNS queries per hour to a single external domain with encoded subdomains. What does this pattern MOST likely indicate?$EXPL$, $EXPL$["Normal web browsing behavior generating cached DNS lookups", "A potential DNS tunneling exfiltration channel where data is encoded in DNS query subdomains", "A misconfigured DNS server causing recursive query loops", "An employee streaming media content that requires frequent DNS resolution"]$EXPL$::jsonb, 1, $EXPL$Correct (B): Per NIST SP 800-86, DNS tunneling encodes data in DNS query subdomains to bypass network controls. The pattern of thousands of queries per hour to a single domain with encoded subdomains is a strong indicator of command-and-control communication or data exfiltration using the DNS protocol. Wrong (A): Normal browsing generates diverse DNS queries across many domains, not repetitive queries with encoded subdomains to a single domain. Wrong (C): Recursive DNS loops produce queries to DNS infrastructure, not repetitive queries with encoded subdomains to one external domain. Wrong (D): Media streaming uses standard HTTP/HTTPS connections and does not generate encoded DNS subdomain queries.$EXPL$, 'medium', 3),

-- Q23: medium / L2 — Fire suppression system selection
(5, 'Security Controls and Monitoring', $EXPL$A company is designing a new data center and must select a fire suppression system. The architect recommends a clean-agent gas suppression system instead of a traditional water sprinkler system. What is the PRIMARY reason for choosing clean-agent suppression in a data center environment?$EXPL$, $EXPL$["Clean-agent systems are less expensive to install than water sprinkler systems", "Water sprinkler systems cannot detect fires in enclosed server cabinets", "Clean-agent gas suppresses fire without causing water damage to electronic equipment", "Clean-agent systems eliminate the need for smoke detection systems"]$EXPL$::jsonb, 2, $EXPL$Correct (C): Per NIST SP 800-53 (PE-13), clean-agent gas suppression systems (such as FM-200 or Novec 1230) extinguish fires by removing oxygen or interrupting the chemical reaction without leaving residue or causing water damage to sensitive electronic equipment. This is critical in data centers where water damage could destroy servers. Wrong (A): Clean-agent systems are typically more expensive than water sprinkler systems, not less. Wrong (B): Both fire suppression types rely on separate smoke detection systems for activation; fire detection is independent of suppression method. Wrong (D): Clean-agent systems still require smoke detection for activation; they replace the suppression medium, not the detection mechanism.$EXPL$, 'medium', 2),

-- Q24: medium / L3 — Write-once storage for audit trail integrity
(5, 'Security Controls and Monitoring', $EXPL$Stonebridge Investments is implementing audit trail controls to comply with SEC Rule 17a-4, which requires broker-dealers to preserve electronic records in a non-rewritable, non-erasable format. The compliance officer evaluates the current practice of storing audit logs on a standard network-attached storage (NAS) device with administrator delete permissions. Which specific control deficiency does this practice create?$EXPL$, $EXPL$["The NAS device does not encrypt logs during transmission", "The logs are not aggregated in a centralized SIEM for correlation", "The retention period on the NAS may be insufficient for regulatory requirements", "An administrator can modify or delete audit records, violating the non-rewritable, non-erasable requirement"]$EXPL$::jsonb, 3, $EXPL$Correct (D): Per SEC Rule 17a-4 and NIST SP 800-92, non-rewritable, non-erasable storage (WORM) is required to ensure audit trail integrity. Standard NAS with administrator delete permissions allows privileged users to tamper with or destroy records, directly violating the regulatory mandate for immutable audit trails. Wrong (A): Encryption in transit protects confidentiality but is a separate requirement from the non-rewritable storage mandate. Wrong (B): SIEM aggregation improves monitoring and correlation but does not inherently make logs non-rewritable or non-erasable. Wrong (C): While retention is important, the specific deficiency described is the ability to modify or delete records, not the retention period.$EXPL$, 'medium', 3),

-- Q25: hard / L4 — Column-level vs TDE encryption architecture evaluation
(5, 'Security Controls and Monitoring', $EXPL$Thornburg Healthcare's compliance team must encrypt patient health information (PHI) in a production database serving a high-volume web application. The database contains 40 columns, of which 6 store PHI. The DBA presents two options: (1) Transparent Data Encryption (TDE), which encrypts the entire database at the storage level, or (2) column-level encryption on the 6 PHI columns using application-managed AES-256 keys. The application performs 10,000 queries per second, and 80% of queries access only non-PHI columns. Which option BEST satisfies both security and performance requirements?$EXPL$, $EXPL$["Column-level encryption on PHI columns, avoiding decryption overhead for the 80% of queries accessing only non-PHI data", "TDE, because it provides stronger encryption algorithms than column-level encryption does", "Column-level encryption on all 40 columns to maximize overall data protection coverage", "TDE, because column-level encryption cannot use the AES-256 cipher"]$EXPL$::jsonb, 0, $EXPL$Correct (A): Per NIST SP 800-111, column-level encryption targets specific sensitive fields, so the 80% of queries touching only non-PHI columns incur zero decryption overhead. TDE encrypts at the storage level and decrypts all data when the database engine reads any page, providing no selective performance benefit. For high-volume applications with a minority of sensitive columns, column-level encryption optimizes both security and performance. Wrong (B): TDE and column-level encryption can both use AES-256; TDE does not provide stronger encryption, just a different scope. Wrong (C): Encrypting all 40 columns defeats the performance advantage and encrypts non-sensitive data unnecessarily. Wrong (D): Column-level encryption fully supports AES-256; this is a factually incorrect premise.$EXPL$, 'hard', 4),

-- Q26: medium / L3 — Proxy server log analysis scenario
(5, 'Security Controls and Monitoring', $EXPL$Ridgeway Accounting's security team reviews web proxy logs and discovers that a single workstation has been connecting to an external IP address over HTTPS every 60 seconds for the past 14 days, transmitting small encrypted payloads. The destination IP is not associated with any known business application. No employee has reported unusual activity. What should the security team's PRIMARY concern be regarding this traffic pattern?$EXPL$, $EXPL$["The HTTPS encryption is causing excessive bandwidth consumption on the proxy", "The workstation is likely communicating with a command-and-control server using beaconing behavior", "The employee is using an unauthorized streaming service during business hours", "The proxy server is misconfigured and generating false log entries"]$EXPL$::jsonb, 1, $EXPL$Correct (B): Per NIST SP 800-83, regular periodic connections (beaconing) to an unknown external IP with small encrypted payloads is a hallmark of command-and-control (C2) communication by malware. The consistent 60-second interval and 14-day duration strongly suggest automated malicious software maintaining persistence. Wrong (A): Small encrypted payloads at 60-second intervals consume negligible bandwidth; the concern is the behavior pattern, not bandwidth. Wrong (C): Streaming services generate variable, high-bandwidth traffic patterns, not consistent small payloads at fixed intervals. Wrong (D): Proxy logs showing consistent patterns from a specific workstation are unlikely to be false entries; the regularity suggests real traffic.$EXPL$, 'medium', 3),

-- Q27: easy / L1 — False Rejection Rate definition
(5, 'Security Controls and Monitoring', $EXPL$What does the False Rejection Rate (FRR) measure in a biometric authentication system?$EXPL$, $EXPL$["The percentage of unauthorized users incorrectly granted access", "The speed at which the biometric system processes authentication requests", "The percentage of authorized users incorrectly denied access", "The total number of authentication attempts processed per hour"]$EXPL$::jsonb, 2, $EXPL$Correct (C): Per NIST SP 800-76, the False Rejection Rate measures the percentage of legitimate, authorized users who are incorrectly denied access by the biometric system. A high FRR causes operational friction as authorized users are repeatedly locked out. Wrong (A): The percentage of unauthorized users incorrectly granted access describes the False Acceptance Rate (FAR), not the FRR. Wrong (B): Processing speed is a throughput metric unrelated to authentication accuracy or error rates. Wrong (D): Total authentication attempts per hour is a volume metric, not an accuracy measurement.$EXPL$, 'easy', 1),

-- Q28: easy / L1 — Bollards as perimeter control
(5, 'Security Controls and Monitoring', $EXPL$What is the PRIMARY purpose of bollards installed around a data center facility?$EXPL$, $EXPL$["To provide wireless network access points for outdoor areas", "To serve as mounting points for external security cameras", "To improve the visual aesthetics of the facility entrance", "To prevent vehicle-borne attacks by blocking unauthorized vehicles from approaching the building"]$EXPL$::jsonb, 3, $EXPL$Correct (D): Per NIST SP 800-116, bollards are physical perimeter controls designed to prevent vehicles from ramming into or approaching a facility. They protect against vehicle-borne threats including accidental collisions and intentional attacks targeting building infrastructure. Wrong (A): Bollards are physical barriers, not network equipment; wireless access points are separate IT infrastructure. Wrong (B): Security cameras are mounted on walls, poles, or dedicated mounts, not on bollards. Wrong (C): While bollards may have aesthetic design elements, their primary purpose is physical security, not decoration.$EXPL$, 'easy', 1),

-- Q29: hard / L4 — Defense-in-depth compensating control analysis
(5, 'Security Controls and Monitoring', $EXPL$Ferndale Manufacturing's legacy SCADA system controlling the production line cannot support modern endpoint security agents, network encryption, or centralized authentication due to vendor restrictions. The system must remain operational while the organization plans a multi-year replacement. The security architect must design compensating controls that provide equivalent protection. Which combination of compensating controls MOST effectively addresses the legacy system's security gaps?$EXPL$, $EXPL$["Network isolation in a dedicated VLAN with firewall rules, IDS monitoring, and physical access restrictions to SCADA terminals", "Installing antivirus software on the SCADA system despite the stated vendor restrictions against endpoint agents", "Requiring SCADA operators to change their passwords every 30 days to reduce credential compromise risk", "Implementing full-disk encryption on the SCADA workstations to protect data stored on local drives"]$EXPL$::jsonb, 0, $EXPL$Correct (A): Per NIST SP 800-82 (Guide to ICS Security), when legacy systems cannot support modern security controls, compensating controls must provide equivalent protection through alternative means. Network isolation limits attack surface, IDS monitoring provides detection capability, and physical access restrictions prevent unauthorized interaction — together addressing the gaps left by unsupported endpoint security, encryption, and authentication. Wrong (B): Installing unsupported software violates vendor restrictions and could destabilize the SCADA system, potentially causing production outages or safety hazards. Wrong (C): Password rotation alone does not compensate for missing endpoint security, encryption, or network isolation, and provides minimal protection for a system lacking centralized authentication. Wrong (D): Full-disk encryption is an endpoint control that the legacy system cannot support per the vendor restrictions stated in the scenario.$EXPL$, 'hard', 4),

-- Q30: medium / L2 — SFTP vs FTP security difference
(5, 'Security Controls and Monitoring', $EXPL$An auditor discovers that a client transfers sensitive financial reports to a third-party processor using standard FTP. The auditor recommends switching to SFTP. What is the PRIMARY security weakness of standard FTP that SFTP addresses?$EXPL$, $EXPL$["FTP does not support file transfers larger than 100 megabytes", "SFTP encrypts data in transit, whereas standard FTP transmits credentials and file contents in plaintext", "FTP cannot authenticate users before allowing file transfers", "SFTP compresses files to reduce transfer time"]$EXPL$::jsonb, 1, $EXPL$Correct (B): Per NIST SP 800-53 (SC-8), standard FTP transmits authentication credentials and file contents in unencrypted plaintext, making them vulnerable to interception. SFTP uses SSH encryption to protect both credentials and data in transit, addressing this fundamental confidentiality weakness. Wrong (A): FTP has no inherent file size limitation; large files can be transferred via FTP. Wrong (C): FTP does authenticate users with username and password, but transmits these credentials in plaintext. Wrong (D): While SSH may include compression, the primary security advantage of SFTP is encryption, not compression.$EXPL$, 'medium', 2)
;

COMMIT;
