-- Migration: Question generation — AUD batch 87 (30 questions)
-- Date: 2026-03-24
-- Topic: Responding to Assessed Risks
-- Difficulty: 9E / 15M / 6H
-- Bloom's: L1:8 / L2:9 / L3:8 / L4:5

BEGIN;

INSERT INTO questions (section_id, topic, stem, choices, correct_index, explanation, difficulty, cognitive_level)
VALUES

-- Q1: hard / L4 — Evaluating combined vs. primarily substantive approach
(1, 'Responding to Assessed Risks', $EXPL$Montclair Electronics Inc. has well-designed automated controls over its revenue cycle, but turnover in the IT department has resulted in undocumented changes to several key application controls during 2025. The engagement partner must decide between a combined approach and a primarily substantive approach for revenue. Which recommendation is most appropriate?$EXPL$, $EXPL$["Proceed with the combined approach after re-evaluating and testing the modified controls", "Adopt a primarily substantive approach because the undocumented changes undermine control reliability", "Rely on the prior year's tests of controls since the underlying control objectives remain unchanged", "Defer the decision until management completes a formal IT change management review"]$EXPL$::jsonb, 1, $EXPL$Correct (B): Under AU-C 330.08, when the auditor plans to rely on controls, those controls must be tested for operating effectiveness. Undocumented changes to application controls mean the auditor cannot establish that the controls operated effectively throughout the period, making a primarily substantive approach the most appropriate response. Wrong (A): Re-evaluating modified controls could be viable, but without documentation of changes, the auditor cannot confirm what was actually modified or when. Wrong (C): Prior year test results cannot be relied upon when controls have been changed, per AU-C 330.14. Wrong (D): The auditor cannot defer audit planning decisions pending management action.$EXPL$, 'hard', 4),

-- Q2: medium / L2 — Dual-purpose tests combining controls and substantive
(1, 'Responding to Assessed Risks', $EXPL$Pineview Manufacturing's auditor, Chen & Associates, plans to select a sample of 40 purchase transactions to simultaneously test the operating effectiveness of the three-way match control and to substantively test the accuracy of accounts payable. This type of procedure is best described as which of the following?$EXPL$, $EXPL$["A walk-through procedure", "A dual-purpose test", "A substantive analytical procedure", "A reperformance test"]$EXPL$::jsonb, 1, $EXPL$Correct (B): Under AU-C 330.A22, a dual-purpose test combines a test of controls with a substantive test on the same transaction. This allows the auditor to simultaneously assess control effectiveness and obtain substantive evidence about account balances. Wrong (A): A walk-through traces a single transaction through a process to confirm understanding, not to test controls or provide substantive evidence. Wrong (C): Substantive analytical procedures involve evaluating financial data through plausible relationships, not transaction-level testing. Wrong (D): Reperformance is a specific audit technique, not a term for combined testing.$EXPL$, 'medium', 2),

-- Q3: hard / L4 — Evaluating response to suspected fraud indicators
(1, 'Responding to Assessed Risks', $EXPL$During the audit of Redstone Financial Group's December 2025 statements, the senior auditor identifies three unusual journal entries totaling $1.2 million posted by the CFO on December 30 with no supporting documentation. The entries increased revenue and decreased an accrued liability. The engagement partner should evaluate whether to take which course of action?$EXPL$, $EXPL$["Expand the sample of journal entries tested and discuss the entries with the audit committee", "Accept the CFO's explanation if it is consistent with the entity's accounting policies", "Modify the audit opinion to reflect the identified misstatement without further investigation", "Limit inquiries to the CFO to avoid alerting other members of management"]$EXPL$::jsonb, 0, $EXPL$Correct (A): Under AU-C 240.36-.37, when conditions indicate possible fraud, the auditor should extend procedures such as expanding journal entry testing and communicating with those charged with governance. The entries' characteristics — posted by a senior executive, near year-end, lacking documentation, and increasing revenue — are strong fraud indicators requiring escalation. Wrong (B): Accepting management's explanation without corroboration fails the auditor's duty of professional skepticism under AU-C 240. Wrong (C): Modifying the opinion before completing investigation is premature. Wrong (D): AU-C 240.41 requires inquiries beyond the individual suspected of involvement.$EXPL$, 'hard', 4),

-- Q4: medium / L3 — Analyzing effect of weak control environment on planned approach
(1, 'Responding to Assessed Risks', $EXPL$Ashford Distribution LLC's control environment is weak: the board lacks financial expertise, management has overridden approval controls twice in the past year, and no formal code of conduct exists. The auditor assessed financial statement-level risk as high. What is the most likely effect on the auditor's planned further audit procedures?$EXPL$, $EXPL$["The auditor may reduce the extent of substantive procedures for low-risk assertions", "The auditor should rely more on analytical procedures to compensate for weak controls", "The auditor should increase the use of external evidence sources and assign more experienced staff", "The auditor should expand tests of controls to determine the actual severity of the weakness"]$EXPL$::jsonb, 3, $EXPL$Correct (D): Under AU-C 330.05-.06, when financial statement-level risk is high due to a weak control environment, overall responses include assigning more experienced staff, increasing supervision, using more external and independent evidence, and incorporating unpredictability. The auditor responds at the overall audit level rather than relying on internal controls. Wrong (A): A weak control environment does not justify reducing procedures for any assertions. Wrong (B): Analytical procedures alone are less reliable when the control environment is weak. Wrong (C): While partially correct about external evidence and experienced staff, expanding tests of controls is inappropriate when the environment itself undermines control reliability.$EXPL$, 'medium', 3),

-- Q5: hard / L3 — Analyzing roll-forward procedures from interim to year-end
(1, 'Responding to Assessed Risks', $EXPL$Baxter Healthcare Corp.'s auditor performed substantive tests of accounts receivable at October 31, 2025, for a December 31 year-end. Between October 31 and year-end, the entity acquired a new division adding $8.5 million in receivables and experienced a significant increase in customer defaults. What is the most likely effect on the auditor's roll-forward procedures?$EXPL$, $EXPL$["The auditor must perform additional substantive procedures to cover the intervening period and address the changed conditions", "The interim testing results remain valid because the original sample was selected from the same population", "The auditor can extend the interim conclusions by performing only analytical procedures for the remaining period", "The auditor should discard the interim work and retest the entire receivable balance at year-end"]$EXPL$::jsonb, 0, $EXPL$Correct (A): Under AU-C 330.23, when substantive procedures are performed at an interim date, the auditor must perform additional procedures to cover the remaining period. Significant changes such as a business acquisition and deteriorating credit conditions increase risk and require more extensive roll-forward procedures. Wrong (B): Changed conditions mean the population and risk profile at year-end differ materially from the interim testing date. Wrong (C): Analytical procedures alone may be insufficient given the magnitude of changes. Wrong (D): Discarding all interim work is unnecessarily inefficient; roll-forward procedures build on interim results.$EXPL$, 'hard', 3),

-- Q6: medium / L2 — Applying the inverse relationship between RMM and detection risk
(1, 'Responding to Assessed Risks', $EXPL$Clearwater Services Inc.'s auditor assesses the combined risk of material misstatement for the accounts payable completeness assertion as low. Under the audit risk model, how does this assessment affect the acceptable level of detection risk for that assertion?$EXPL$, $EXPL$["Detection risk must also be set at a low level", "The auditor may accept a higher level of detection risk", "Detection risk is not affected by the assessed risk of material misstatement", "The auditor must eliminate detection risk entirely for low-risk assertions"]$EXPL$::jsonb, 1, $EXPL$Correct (B): Under AU-C 330.07, there is an inverse relationship between the assessed risk of material misstatement and the acceptable level of detection risk. When assessed RMM is low, the auditor may accept a higher detection risk while still maintaining audit risk at an acceptably low level. Wrong (A): Setting detection risk low when RMM is already low would result in unnecessarily extensive procedures. Wrong (C): Detection risk is directly determined by the assessed RMM through the audit risk model per AU-C 200.A44. Wrong (D): Detection risk can never be completely eliminated because of inherent limitations in audit procedures.$EXPL$, 'medium', 2),

-- Q7: medium / L2 — Using external confirmations as substantive response
(1, 'Responding to Assessed Risks', $EXPL$Greenfield Mortgage Corp.'s auditor assesses the risk of material misstatement for cash balances as moderate. The auditor decides to send bank confirmation requests to all five financial institutions where Greenfield holds accounts. Under AU-C 505, which statement about this procedure is correct?$EXPL$, $EXPL$["Bank confirmations address only the existence assertion for cash", "The auditor must obtain management's agreement before sending confirmation requests", "Non-responses to confirmation requests are considered confirmation exceptions", "Bank confirmations are required only when the risk of material misstatement is high"]$EXPL$::jsonb, 1, $EXPL$Correct (C): Under AU-C 505.07-.08, the auditor must maintain control over confirmation requests and is required to obtain management's agreement before sending them. If management refuses, the auditor must evaluate the reasonableness of the refusal and perform alternative procedures. Wrong (A): Bank confirmations address multiple assertions including existence, completeness, and rights and obligations. Wrong (B): Non-responses are not confirmation exceptions; they require alternative procedures per AU-C 505.12. Wrong (D): Bank confirmations are a common audit procedure regardless of the risk level.$EXPL$, 'medium', 2),

-- Q8: medium / L2 — Designing procedures responsive to completeness vs. occurrence
(1, 'Responding to Assessed Risks', $EXPL$Summit Retail Group's auditor identifies a significant risk related to the completeness of accounts payable. To obtain evidence about unrecorded liabilities, the auditor should design substantive procedures that start from which of the following?$EXPL$, $EXPL$["The accounts payable subsidiary ledger to vendor invoices", "The general ledger balance to confirm recorded amounts with vendors", "Subsequent cash disbursements and unmatched receiving reports to the accounting records", "The trial balance to analytical expectations based on prior year balances"]$EXPL$::jsonb, 3, $EXPL$Correct (D): Under AU-C 330.A30, procedures to test completeness trace from the source to the accounting records. For unrecorded liabilities, the auditor examines subsequent disbursements, unmatched receiving reports, and vendor statements and traces them to the payable records to identify omissions. Wrong (A): Tracing from the ledger to invoices tests occurrence (whether recorded items actually happened), not completeness. Wrong (B): Confirming recorded amounts tests existence and accuracy but does not identify unrecorded amounts. Wrong (C): While analytical procedures may highlight completeness issues, they do not provide the direct evidence of the tracing approach.$EXPL$, 'medium', 2),

-- Q9: medium / L2 — Applying risk response to related party transactions
(1, 'Responding to Assessed Risks', $EXPL$Meridian Holdings Inc.'s auditor discovers that Meridian sold a commercial building to an entity controlled by Meridian's CEO for $4.1 million, which is $900,000 below the appraised fair value. Under AU-C 550, what is the auditor's primary responsibility when responding to this identified related party transaction?$EXPL$, $EXPL$["Evaluate whether the transaction has been properly recorded, disclosed, and has an identifiable business purpose", "Require management to reverse the transaction because it was not conducted at arm's length", "Report the below-market sale directly to the SEC as a potential violation", "Conclude that the transaction is fraudulent because the price was below fair value"]$EXPL$::jsonb, 0, $EXPL$Correct (A): Under AU-C 550.20-.21, the auditor must evaluate whether identified related party transactions have been appropriately accounted for and disclosed, and whether the terms and underlying business rationale suggest the transaction may have been entered into for fraudulent purposes. Wrong (B): The auditor cannot require management to reverse transactions; the auditor evaluates proper accounting and disclosure. Wrong (C): The auditor reports to those charged with governance, not directly to regulatory agencies in normal circumstances. Wrong (D): A below-market price alone does not establish fraud; the auditor must evaluate the facts and circumstances.$EXPL$, 'medium', 2),

-- Q10: medium / L3 — Analyzing effect of control deficiency on planned procedures
(1, 'Responding to Assessed Risks', $EXPL$During interim fieldwork at Lakewood Construction Co., the auditor discovers that the employee responsible for bank reconciliations also has authority to initiate wire transfers. This segregation of duties deficiency most likely affects the auditor's planned procedures in which way?$EXPL$, $EXPL$["The auditor should decrease reliance on cash controls and increase substantive testing of cash balances", "The auditor should report the deficiency but need not modify planned audit procedures", "The auditor can compensate by increasing reliance on information technology general controls", "The auditor should perform additional tests of controls to determine if the deficiency caused misstatements"]$EXPL$::jsonb, 1, $EXPL$Correct (B): Under AU-C 330.09-.10, when a control deficiency such as inadequate segregation of duties is identified, the auditor must reassess control risk. The lack of segregation means controls over cash cannot be relied upon, requiring the auditor to reduce planned reliance on controls and increase substantive testing of the affected account. Wrong (A): This reversal of the correct answer letter is wrong — merely reporting without modifying procedures fails to address the increased risk. Wrong (C): IT general controls do not compensate for a manual segregation of duties weakness in this context. Wrong (D): Testing a control that is poorly designed will not provide evidence of effective operation.$EXPL$, 'medium', 3),

-- Q11: easy / L1 — Definition of further audit procedures
(1, 'Responding to Assessed Risks', $EXPL$What are the two categories of further audit procedures the auditor designs in response to assessed risks at the assertion level?$EXPL$, $EXPL$["Risk assessment procedures and analytical procedures", "Tests of controls and substantive procedures", "Inquiry procedures and observation procedures", "Walk-through procedures and compliance procedures"]$EXPL$::jsonb, 2, $EXPL$Correct (C): Under AU-C 330.06, further audit procedures comprise tests of controls and substantive procedures. These are designed and performed in response to the auditor's assessment of risks of material misstatement at the assertion level. Wrong (A): Risk assessment procedures are performed to identify risks, not to respond to assessed risks. Wrong (B): Inquiry and observation are audit techniques, not categories of further audit procedures. Wrong (D): Walk-throughs and compliance procedures are not the standard AU-C classifications of further audit procedures.$EXPL$, 'easy', 1),

-- Q12: easy / L1 — Definition of substantive procedures
(1, 'Responding to Assessed Risks', $EXPL$Which of the following are the two types of substantive procedures an auditor may perform?$EXPL$, $EXPL$["Walk-throughs and reperformance", "Inquiry of management and inspection of documents", "Tests of controls and tests of transactions", "Tests of details and substantive analytical procedures"]$EXPL$::jsonb, 3, $EXPL$Correct (D): Under AU-C 330.04, substantive procedures include tests of details (of classes of transactions, account balances, and disclosures) and substantive analytical procedures. These procedures are designed to detect material misstatements at the assertion level. Wrong (A): Walk-throughs and reperformance are specific audit techniques, not the two categories of substantive procedures. Wrong (B): Inquiry and inspection are individual audit techniques used within various procedure types. Wrong (C): Tests of controls are a separate category from substantive procedures, not a type within them.$EXPL$, 'easy', 1),

-- Q13: easy / L1 — Purpose of tests of controls
(1, 'Responding to Assessed Risks', $EXPL$What is the primary purpose of performing tests of controls during an audit?$EXPL$, $EXPL$["To evaluate the operating effectiveness of controls in preventing or detecting material misstatements", "To determine the dollar amount of misstatements in account balances", "To identify all fraud that occurred during the period", "To satisfy regulatory requirements for internal control documentation"]$EXPL$::jsonb, 0, $EXPL$Correct (A): Under AU-C 330.08, tests of controls are designed to evaluate the operating effectiveness of controls in preventing or detecting and correcting material misstatements at the assertion level. The auditor performs these tests when planning to rely on controls to reduce substantive testing. Wrong (B): Determining dollar misstatements is the purpose of substantive procedures, not tests of controls. Wrong (C): The auditor provides reasonable, not absolute, assurance and is not required to detect all fraud. Wrong (D): Tests of controls evaluate effectiveness, not merely document the existence of controls.$EXPL$, 'easy', 1),

-- Q14: hard / L4 — Evaluating use of auditor's specialist for high-uncertainty estimates
(1, 'Responding to Assessed Risks', $EXPL$Westbrook Insurance Corp. reports a $47 million loss reserve that involves complex actuarial models and significant judgment about future claim development. The engagement partner is evaluating whether to use an auditor's specialist. Under AU-C 620, which factor should the partner weigh most heavily in this evaluation?$EXPL$, $EXPL$["Whether the specialist's findings will be disclosed in the audit report", "The complexity and subjectivity of the matter and whether the audit team possesses sufficient expertise to evaluate it", "Whether management has already engaged its own actuary to prepare the estimate", "The additional cost of the specialist relative to the overall audit fee"]$EXPL$::jsonb, 1, $EXPL$Correct (B): Under AU-C 620.07, the auditor determines whether to use a specialist based on the nature and complexity of the matter and whether the audit team has the necessary competence to evaluate the work. For complex actuarial models with significant estimation uncertainty, the engagement partner should focus on whether the team can independently assess the reasonableness of the methods and assumptions. Wrong (A): Whether findings are disclosed in the report does not drive the decision to engage a specialist. Wrong (C): Management's use of its own specialist does not eliminate the auditor's need for independent expertise. Wrong (D): Cost considerations should not override the need for appropriate audit evidence.$EXPL$, 'hard', 4),

-- Q15: easy / L1 — Audit evidence reliability hierarchy
(1, 'Responding to Assessed Risks', $EXPL$When designing audit procedures in response to assessed risks, which source of audit evidence is generally considered most reliable?$EXPL$, $EXPL$["Oral representations from management", "Internally generated documents reviewed by the auditor", "Evidence obtained directly from independent external sources", "Photocopies of internally generated documents"]$EXPL$::jsonb, 2, $EXPL$Correct (C): Under AU-C 500.A31, audit evidence obtained directly from independent external sources (such as bank confirmations or third-party invoices) is generally more reliable than evidence generated internally by the entity. The auditor considers evidence reliability when designing procedures responsive to assessed risks. Wrong (A): Oral representations are the least reliable form of evidence because they cannot be independently verified. Wrong (B): Internally generated documents are less reliable than external sources, though controls may enhance their reliability. Wrong (D): Photocopies of internal documents are even less reliable because their authenticity is harder to verify.$EXPL$, 'easy', 1),

-- Q16: hard / L4 — Evaluating appropriate response when misstatements suggest systematic error
(1, 'Responding to Assessed Risks', $EXPL$During the audit of Thornberry Manufacturing's inventory, the auditor discovers that 8 of 25 sampled items have quantity discrepancies averaging 12% overstatement, all involving the same warehouse location. The engagement partner must assess the best course of action. Which response is most appropriate?$EXPL$, $EXPL$["Project the error rate across the entire inventory population and adjust the opinion accordingly", "Expand testing at the specific warehouse location and reassess whether the pattern indicates a pervasive control failure or potential fraud", "Accept the discrepancies as immaterial if the projected misstatement is below performance materiality", "Request management to perform a complete physical count at all locations before the auditor can continue"]$EXPL$::jsonb, 3, $EXPL$Correct (D): Under AU-C 330.28-.29, when identified misstatements reveal a systematic pattern, the auditor should consider whether the risk assessment remains appropriate and whether additional procedures are needed. A 32% error rate concentrated in one location suggests either a control breakdown or intentional manipulation, warranting expanded testing and reassessment of fraud risk per AU-C 240. Wrong (A): Simply projecting the error and adjusting the opinion skips the investigation step required by standards. Wrong (C): The pattern of errors suggests a systematic issue that cannot be dismissed based on materiality thresholds alone. Wrong (B): While requesting management to recount may eventually be necessary, the auditor's first responsibility is to investigate the pattern.$EXPL$, 'hard', 4),

-- Q17: medium / L3 — Analyzing effect of IT dependence on substantive procedure design
(1, 'Responding to Assessed Risks', $EXPL$Crestfield Financial Services processes all loan payments through an automated system that calculates interest, applies payments, and updates loan balances with no manual intervention. The auditor has not tested the IT general controls over this system. What is the most likely effect on the auditor's substantive procedures for the loan portfolio?$EXPL$, $EXPL$["The auditor may reduce substantive testing because automated systems are inherently more reliable than manual processes", "The auditor should increase the extent of substantive detail testing because system-generated data cannot be relied upon without testing underlying IT controls", "The auditor can use the system-generated reports as audit evidence without modification", "The auditor should disclaim an opinion because automated systems cannot be audited substantively"]$EXPL$::jsonb, 1, $EXPL$Correct (B): Under AU-C 330.A26, when the auditor has not tested IT general controls, the reliability of system-generated information for use as audit evidence is uncertain. The auditor must increase the extent of substantive detail testing because reports and calculations produced by the system cannot be assumed accurate. Wrong (A): Automation does not inherently ensure reliability; IT general controls must be effective for automated application controls to be trusted. Wrong (C): System-generated reports require validation of their completeness and accuracy per AU-C 500. Wrong (D): An inability to test IT controls does not require a disclaimer; a substantive approach can still provide sufficient evidence.$EXPL$, 'medium', 3),

-- Q18: medium / L3 — Analyzing effect of prior year misstatements on current year risk response
(1, 'Responding to Assessed Risks', $EXPL$Last year, Valley Enterprises had three audit adjustments totaling $185,000 related to improper revenue cutoff. In planning the current year's audit, the engagement team is designing further audit procedures for revenue. How should the prior year findings most likely affect the current year's risk response?$EXPL$, $EXPL$["The auditor should treat the prior year adjustments as resolved and maintain the same risk assessment", "The auditor should increase the assessed risk for revenue cutoff and design more extensive year-end cutoff testing procedures", "The auditor should issue a qualified opinion because the recurring nature suggests a material weakness", "The auditor should require management to hire additional accounting staff before the audit begins"]$EXPL$::jsonb, 1, $EXPL$Correct (B): Under AU-C 315.32, the auditor considers prior period misstatements when assessing current period risks. Recurring cutoff issues indicate a persistent control weakness or process failure, warranting heightened risk assessment and more extensive cutoff procedures such as testing transactions before and after the reporting date. Wrong (A): Ignoring the pattern of prior misstatements violates the requirement to consider historical audit information in risk assessment. Wrong (C): Prior year adjustments alone do not dictate the current year opinion; the auditor must first test the current period. Wrong (D): The auditor cannot require management to hire staff; the auditor responds through the design of audit procedures.$EXPL$, 'medium', 3),

-- Q19: hard / L4 — Evaluating appropriate response to going concern risks
(1, 'Responding to Assessed Risks', $EXPL$Sterling Technologies Inc. has reported operating losses for three consecutive years, its primary credit facility expires in four months, and its largest customer representing 40% of revenue recently filed for bankruptcy. Management asserts that a planned equity offering will resolve liquidity concerns but has not yet filed the registration statement. The engagement partner should evaluate which response as most appropriate?$EXPL$, $EXPL$["Accept management's assertion because the planned equity offering demonstrates a viable mitigation strategy", "Disclaim an opinion because the going concern uncertainty makes it impossible to form a conclusion", "Obtain and evaluate management's plans, assess their feasibility with corroborating evidence, and consider the adequacy of disclosures under AU-C 570", "Issue an adverse opinion because the conditions indicate the entity cannot continue as a going concern"]$EXPL$::jsonb, 2, $EXPL$Correct (C): Under AU-C 570.12-.14, when conditions raising substantial doubt about going concern are identified, the auditor must obtain and evaluate management's plans. The auditor assesses whether the plans are feasible and can be effectively implemented by examining supporting evidence. A planned but unfiled equity offering requires the auditor to evaluate the likelihood of successful completion. Wrong (A): Accepting unsubstantiated assertions violates professional skepticism requirements. Wrong (B): Going concern uncertainty does not automatically warrant a disclaimer; the auditor must first evaluate management's plans. Wrong (D): An adverse opinion relates to GAAP departures, not going concern; going concern issues result in an emphasis-of-matter paragraph or going concern modification.$EXPL$, 'hard', 4),

-- Q20: medium / L2 — Applying required procedures for accounting estimates
(1, 'Responding to Assessed Risks', $EXPL$Hartwell Construction Inc. records a $3.2 million allowance for doubtful accounts based on management's estimate of uncollectible receivables. The auditor is designing substantive procedures for this estimate under AU-C 540. Which of the following approaches is the auditor required to use?$EXPL$, $EXPL$["Accept management's estimate if it is within a range the auditor considers reasonable", "Develop an independent estimate to replace management's estimate in the financial statements", "Test how management made the estimate, develop an independent expectation, or review subsequent events — using one or a combination of these approaches", "Use only analytical procedures to evaluate the reasonableness of the estimate"]$EXPL$::jsonb, 3, $EXPL$Correct (D): Under AU-C 540.13, the auditor must use one or a combination of three approaches: (1) test how management made the estimate and the data on which it is based, (2) develop an independent point estimate or range, or (3) review subsequent events or transactions occurring before the audit report date. Wrong (A): Simply accepting the estimate without performing procedures does not provide sufficient audit evidence. Wrong (B): Developing an independent estimate is one permitted approach but the auditor is not required to replace management's estimate. Wrong (C): Analytical procedures alone may be insufficient for evaluating estimates with significant judgment.$EXPL$, 'medium', 2),

-- Q21: easy / L1 — Definition of the combined approach
(1, 'Responding to Assessed Risks', $EXPL$What does a combined approach to auditing an assertion involve?$EXPL$, $EXPL$["Performing only analytical procedures and inquiries of management", "Using both tests of controls and substantive procedures", "Combining the work of multiple audit firms on one engagement", "Performing substantive procedures at both interim and year-end dates"]$EXPL$::jsonb, 1, $EXPL$Correct (B): Under AU-C 330.08-.18, a combined approach involves performing both tests of controls (to evaluate operating effectiveness) and substantive procedures (to detect material misstatements). The auditor uses this approach when planning to rely on controls to support a reduced assessment of control risk. Wrong (A): Analytical procedures and inquiries alone are insufficient to constitute a complete audit approach for an assertion. Wrong (C): A combined approach refers to the mix of procedure types, not the involvement of multiple firms. Wrong (D): Testing at multiple dates relates to timing, not the approach of combining controls testing with substantive work.$EXPL$, 'easy', 1),

-- Q22: medium / L2 — Applying unpredictability in fraud risk response procedures
(1, 'Responding to Assessed Risks', $EXPL$Morrison & Burke CPAs is auditing Falcon Industries' December 2025 financial statements. The engagement team is designing procedures to address fraud risk. Under AU-C 240, which of the following is an example of incorporating unpredictability into the audit?$EXPL$, $EXPL$["Informing management in advance about which locations will be visited for inventory observations", "Performing substantive procedures on accounts not typically tested or adjusting timing from what is expected", "Using the same sample sizes and selection methods as the prior year audit", "Completing all fieldwork procedures before the client's year-end date"]$EXPL$::jsonb, 1, $EXPL$Correct (B): Under AU-C 240.30, the auditor incorporates unpredictability by varying the nature, timing, and extent of procedures in ways that would not be anticipated by entity personnel. Examples include testing accounts not normally tested, adjusting timing unexpectedly, or using different sampling methods. Wrong (A): Informing management of planned locations in advance defeats the purpose of unpredictability. Wrong (C): Using the same approach as the prior year creates predictability, which is contrary to the standard's requirement. Wrong (D): Completing all work before year-end does not introduce unpredictability and may reduce audit effectiveness.$EXPL$, 'medium', 2),

-- Q23: easy / L1 — Audit procedures cannot be solely reliant on inquiry
(1, 'Responding to Assessed Risks', $EXPL$Which statement is true about the use of inquiry as an audit procedure when responding to assessed risks?$EXPL$, $EXPL$["Inquiry alone is sufficient to test the operating effectiveness of controls", "Inquiry may corroborate other evidence but is not sufficient by itself as the sole audit procedure for any assertion", "Inquiry is the most reliable form of audit evidence available to the auditor", "Inquiry of management is required only when fraud risk factors are present"]$EXPL$::jsonb, 2, $EXPL$Correct (C): Under AU-C 500.A23-.A25, inquiry alone is generally not sufficient to provide appropriate audit evidence. While inquiry is an important procedure that the auditor uses extensively, it must be combined with other procedures such as inspection, observation, or reperformance to provide sufficient appropriate evidence. Wrong (A): Tests of controls require procedures beyond inquiry, such as observation, inspection, or reperformance per AU-C 330.10. Wrong (B): Oral inquiry is among the least reliable forms of evidence. Wrong (D): Inquiry of management is a standard procedure throughout the audit, not limited to fraud situations.$EXPL$, 'easy', 1),

-- Q24: medium / L3 — Analyzing need to revise risk assessment based on evidence obtained
(1, 'Responding to Assessed Risks', $EXPL$While performing substantive testing of Northgate Corp.'s inventory, the auditor discovers that management has been capitalizing shipping costs as inventory rather than expensing them. The total impact is $420,000 against overall materiality of $350,000. The original risk assessment for inventory valuation was low. What is the most likely effect on the audit?$EXPL$, $EXPL$["The auditor should continue with the planned procedures since the original risk assessment was low", "The auditor should communicate the finding to management and accept any adjustment they propose", "The auditor should modify the risk assessment to high and consider whether the planned procedures remain adequate", "The auditor should immediately issue a qualified opinion based on the identified misstatement"]$EXPL$::jsonb, 3, $EXPL$Correct (D): Under AU-C 315.32 and AU-C 330.31, when audit evidence contradicts the original risk assessment, the auditor must revise the assessment and evaluate whether the nature, timing, and extent of planned procedures remain sufficient. A material misstatement in an area assessed as low risk indicates the original assessment was incorrect. Wrong (A): Continuing with procedures designed for low risk when evidence indicates higher risk violates AU-C 330. Wrong (B): Simply accepting management's adjustment without reconsidering the broader risk implications is insufficient. Wrong (C): An opinion decision comes after all evidence is gathered, not immediately upon discovering a single misstatement.$EXPL$, 'medium', 3),

-- Q25: easy / L2 — Applying direction of testing for existence assertion
(1, 'Responding to Assessed Risks', $EXPL$Silverline Corp.'s auditor is testing the existence of fixed assets recorded on the balance sheet. The auditor selects 15 items from the fixed asset register and physically inspects each asset at the client's facility. This procedure tests existence because the auditor is tracing from which direction?$EXPL$, $EXPL$["From the accounting records to the physical assets", "From the physical assets to the accounting records", "From vendor invoices to the general ledger", "From bank statements to the cash disbursements journal"]$EXPL$::jsonb, 0, $EXPL$Correct (A): Under AU-C 330.A30, testing existence involves selecting items from the accounting records and verifying they exist in reality. Tracing from the recorded item to the physical asset confirms that recorded assets are real and present. Wrong (B): Tracing from physical assets to records tests completeness, not existence. Wrong (C): Tracing from invoices to the ledger tests accuracy of recording, not physical existence. Wrong (D): Bank statement procedures relate to cash, not fixed asset existence.$EXPL$, 'easy', 2),

-- Q26: easy / L1 — Definition of tests of details
(1, 'Responding to Assessed Risks', $EXPL$Which of the following best describes a test of details performed in response to an assessed risk?$EXPL$, $EXPL$["A procedure that evaluates financial information through analysis of plausible relationships", "A procedure that involves examining individual transactions, balances, or disclosures for evidence of misstatement", "A procedure limited to inquiries of management about significant account balances", "A procedure that tests the overall reasonableness of the financial statements taken as a whole"]$EXPL$::jsonb, 1, $EXPL$Correct (B): Under AU-C 330.04, tests of details are substantive procedures that involve examining individual transactions, account balances, or disclosures. They provide direct evidence about whether specific assertions are materially misstated by inspecting supporting documentation at the item level. Wrong (A): Evaluating financial information through plausible relationships describes substantive analytical procedures, not tests of details. Wrong (C): Inquiry alone is not a test of details and is insufficient as the sole source of evidence for an assertion. Wrong (D): Evaluating overall reasonableness describes analytical procedures applied at a high level, not detailed transaction testing.$EXPL$, 'easy', 1),

-- Q27: medium / L3 — Analyzing appropriateness of CAATs as a risk response
(1, 'Responding to Assessed Risks', $EXPL$Ridgeway Electronics processes over 500,000 sales transactions per year through its ERP system. The auditor is considering using computer-assisted audit techniques to analyze the entire population of transactions for unusual patterns. Compared to traditional manual sampling, what is the most significant advantage of this approach for responding to assessed risks?$EXPL$, $EXPL$["It eliminates the need for the auditor to exercise professional judgment about identified anomalies", "It allows the auditor to test 100% of transactions, improving the likelihood of detecting anomalies that sampling might miss", "It satisfies the requirement for tests of controls without separate control testing", "It removes sampling risk entirely and replaces the need for professional skepticism"]$EXPL$::jsonb, 2, $EXPL$Correct (C): Under AU-C 330.A21, computer-assisted audit techniques enable the auditor to test entire populations rather than samples, improving detection of unusual items, outliers, and patterns. This is especially valuable for high-volume transaction environments where sampling risk could cause anomalies to go undetected. Wrong (A): CAATs do not replace professional judgment; the auditor must still evaluate results and determine their audit significance. Wrong (B): CAATs provide substantive evidence but do not substitute for separate tests of controls. Wrong (D): While CAATs eliminate sampling risk, they do not replace the need for professional skepticism when evaluating results.$EXPL$, 'medium', 3),

-- Q28: easy / L1 — Requirement to document linkage between risks and procedures
(1, 'Responding to Assessed Risks', $EXPL$What must the auditor's documentation include regarding the relationship between assessed risks and further audit procedures?$EXPL$, $EXPL$["Only the final conclusion on each material account balance", "Only the results of tests of controls performed during the audit", "Only a listing of substantive procedures performed, without reference to specific risks", "The linkage between the assessed risks and the nature, timing, and extent of further audit procedures"]$EXPL$::jsonb, 3, $EXPL$Correct (D): Under AU-C 330.29, the auditor must document the overall responses to address the assessed risks at the financial statement level and the linkage between the further audit procedures and the assessed risks at the assertion level. This demonstrates that the audit plan is responsive to identified risks. Wrong (A): Final conclusions alone do not show the connection between risks and the procedures designed to address them. Wrong (B): Documenting only control tests ignores the required linkage to assessed risks. Wrong (C): Listing procedures without linking them to specific risks fails the documentation requirement.$EXPL$, 'easy', 1),

-- Q29: medium / L2 — Applying concept of sufficient appropriate audit evidence
(1, 'Responding to Assessed Risks', $EXPL$Briarwood Health Systems' auditor is determining how many accounts receivable confirmations to send. The auditor assessed the risk of material misstatement for the receivables existence assertion as high. Under AU-C 330, compared to a low risk assessment, the auditor should most likely adjust the planned confirmations in which way?$EXPL$, $EXPL$["Send confirmations to a larger number of accounts and include higher-dollar balances", "Send fewer confirmations because the high risk makes confirmation evidence less reliable", "Replace confirmations entirely with analytical procedures", "Send the same number of confirmations regardless of risk assessment"]$EXPL$::jsonb, 0, $EXPL$Correct (A): Under AU-C 330.07-.08, when the assessed risk is higher, the auditor must obtain more persuasive evidence. This is accomplished by increasing the extent of procedures (larger sample sizes) and focusing on higher-risk items such as large balances. More confirmations at higher dollar amounts increase the likelihood of detecting misstatements. Wrong (B): Higher risk requires more evidence, not less; the reliability of confirmations does not decrease with higher risk. Wrong (C): Replacing confirmations with analytical procedures would reduce evidence quality when more persuasive evidence is needed. Wrong (D): The extent of procedures must be responsive to the assessed risk level per AU-C 330.$EXPL$, 'medium', 2),

-- Q30: medium / L3 — Analyzing whether substantive analytical procedures alone are appropriate
(1, 'Responding to Assessed Risks', $EXPL$During the audit of Windermere Hospitality Group, the engagement team proposes using only substantive analytical procedures to test room revenue, which is a significant risk. The senior manager reviews the proposed approach. What is the most likely outcome of this review?$EXPL$, $EXPL$["The approach is approved because substantive analytical procedures are efficient for revenue testing", "The approach is rejected because substantive analytical procedures alone are not sufficient for a significant risk", "The approach is approved if the analytical procedures use data from management's own records", "The approach is modified to add inquiry of management as a corroborating procedure"]$EXPL$::jsonb, 1, $EXPL$Correct (B): Under AU-C 330.22, for a significant risk, the auditor's substantive procedures must include tests of details or a combination of tests of details and substantive analytical procedures. Substantive analytical procedures alone are not sufficient to address a significant risk because they may not provide the precision needed for higher-risk areas. Wrong (A): Efficiency does not override the requirement for tests of details when addressing significant risks. Wrong (C): Using management's own data without independent corroboration actually reduces the reliability of analytical procedures. Wrong (D): Adding inquiry does not satisfy the requirement for tests of details; inquiry alone is not a substantive procedure sufficient for significant risks.$EXPL$, 'medium', 3)
;

COMMIT;
