-- Migration: Question generation — REG batch 57 (16 questions)
-- Date: 2026-03-24
-- Topic: Like-Kind Exchanges
-- Difficulty: 5E / 8M / 3H
-- Bloom's: L1:4 / L2:6 / L3:4 / L4:2

BEGIN;

INSERT INTO questions (section_id, topic, stem, choices, correct_index, explanation, difficulty, cognitive_level)
VALUES

-- Q1: hard / L4 — Related party disposition within 2 years triggers deferred gain
(3, 'Like-Kind Exchanges', $EXPL$Dunbar exchanges investment land (basis $90,000, FMV $210,000) for like-kind property owned by her brother Marcus. Fourteen months later, Marcus sells the property he received from Dunbar to an unrelated third party. What is the consequence for Dunbar?$EXPL$, $EXPL$["No consequence, because Dunbar completed a valid Section 1031 exchange", "Dunbar must amend her return to report the $120,000 deferred gain because a related party disposed of the property within two years", "Only Marcus recognizes gain on the third-party sale; Dunbar's deferral remains intact", "Dunbar and Marcus split the deferred gain equally under the related-party rules"]$EXPL$::jsonb, 1, $EXPL$Correct (B): IRC Section 1031(f). When a like-kind exchange occurs between related parties (as defined in Sections 267(b) and 707(b)), and either party disposes of the exchanged property within two years, the original deferred gain is recognized by both parties as of the date of the subsequent disposition. Marcus's sale at 14 months triggers Dunbar's $120,000 deferred gain. Wrong (A): The related-party rules override the general deferral rule when a disposition occurs within two years. Wrong (C): Section 1031(f) requires both parties to recognize previously deferred gain, not just the disposing party. Wrong (D): There is no equal-splitting rule; each party recognizes their own deferred gain in full.$EXPL$, 'hard', 4),

-- Q2: easy / L1 — Partnership interests are statutorily excluded from Section 1031
(3, 'Like-Kind Exchanges', $EXPL$Holloway wants to exchange her 40% interest in a real estate partnership for a 30% interest in a different real estate partnership. Both partnerships hold only investment real property. Does this exchange qualify under Section 1031?$EXPL$, $EXPL$["Yes, because both partnerships hold like-kind real property", "Yes, if the partnership interests have equal fair market value", "No, because interests in a partnership are specifically excluded from Section 1031 treatment", "No, unless Holloway holds the replacement interest for at least two years"]$EXPL$::jsonb, 2, $EXPL$Correct (C): IRC Section 1031(a)(2)(D). Interests in a partnership are explicitly excluded from like-kind exchange treatment, regardless of the underlying assets held by the partnerships. Wrong (A): The nature of the partnership's underlying assets is irrelevant; the statute excludes partnership interests categorically. Wrong (B): Equal FMV does not cure the statutory exclusion of partnership interests. Wrong (D): No holding period can overcome the exclusion; partnership interests simply do not qualify.$EXPL$, 'easy', 1),

-- Q3: hard / L3 — Mortgage relief as boot when liabilities are assumed
(3, 'Like-Kind Exchanges', $EXPL$Navarro exchanges a rental building (basis $200,000, FMV $500,000, subject to a $150,000 mortgage) for a like-kind rental property (FMV $350,000) with no mortgage. The buyer assumes Navarro's $150,000 mortgage. What amount of gain must Navarro recognize?$EXPL$, $EXPL$["$0, because no cash was received", "$300,000, the full realized gain", "$150,000, because mortgage relief is treated as boot received", "$50,000, the difference between the properties' fair market values"]$EXPL$::jsonb, 2, $EXPL$Correct (C): IRC Section 1031(b) and Treas. Reg. 1.1031(j)-1. When a mortgage on the relinquished property is assumed by the other party, the mortgage relief is treated as boot received. Navarro's realized gain is $500,000 - $200,000 = $300,000. Boot received (mortgage relief) is $150,000, and recognized gain is the lesser of boot received ($150,000) or realized gain ($300,000), so $150,000. Wrong (A): Although no cash changed hands, liability relief is economic boot and triggers gain recognition. Wrong (B): Recognized gain is capped at boot received, not the full realized gain. Wrong (D): The FMV difference between properties is not the correct measure; mortgage relief determines boot.$EXPL$, 'hard', 3),

-- Q4: hard / L4 — Build-to-suit / improvement exchange within exchange period
(3, 'Like-Kind Exchanges', $EXPL$Medina transfers relinquished property to a qualified intermediary. Medina wants the QI to use the exchange proceeds to purchase vacant land and construct a warehouse on it before transferring the completed property to Medina as replacement property. This construction will take approximately 120 days. The CPA must evaluate whether the improvements count toward Medina's replacement property. What is the critical requirement for the improvements to qualify?$EXPL$, $EXPL$["The improvements must be completed within 45 days of the transfer of the relinquished property", "The replacement property, including improvements, must be received within the exchange period, and the QI or EAT must hold title during construction", "Medina must personally supervise the construction to satisfy the active business use requirement", "Improvement exchanges are prohibited under current regulations; only existing structures qualify"]$EXPL$::jsonb, 1, $EXPL$Correct (B): Treas. Reg. 1.1031(k)-1(e)(2) and Rev. Proc. 2000-37. In a build-to-suit or improvement exchange, the QI or exchange accommodation titleholder must hold title to the property during construction so that improvements are part of the replacement property when transferred. All improvements must be completed and the property delivered within the 180-day exchange period (or tax return due date, if earlier). Wrong (A): The 45-day period is for identification only, not for completing improvements. Wrong (C): There is no requirement that the taxpayer personally supervise construction; the QI or EAT manages the improvement process. Wrong (D): Improvement exchanges are expressly permitted under Treasury Regulations and IRS guidance.$EXPL$, 'hard', 4),

-- Q5: medium / L2 — Form 8824 reporting requirement even for fully deferred exchanges
(3, 'Like-Kind Exchanges', $EXPL$Chambers completes a Section 1031 exchange of investment real property with no boot received, resulting in full gain deferral. Chambers's CPA prepares the tax return. What reporting obligation applies to this exchange?$EXPL$, $EXPL$["No reporting is required because no gain was recognized", "Chambers must file Form 8824 to report the exchange, even though no gain is recognized", "Only Schedule D reporting is required for the deferred gain", "The exchange must be reported only if the properties' FMV exceeds $250,000"]$EXPL$::jsonb, 1, $EXPL$Correct (B): IRC Section 1031 and Form 8824 instructions. Taxpayers must file Form 8824, Like-Kind Exchanges, for the tax year of the exchange regardless of whether gain is recognized. The form reports the properties exchanged, basis calculations, and any deferred gain. Wrong (A): Reporting is mandatory even with full deferral; the IRS needs to track the exchange and verify compliance. Wrong (C): Schedule D is for capital gains and losses actually recognized; Form 8824 is the required form for like-kind exchanges. Wrong (D): There is no dollar threshold that determines whether reporting is required; all Section 1031 exchanges must be reported on Form 8824.$EXPL$, 'medium', 2),

-- Q6: easy / L1 — Holding period of replacement property tacks onto relinquished
(3, 'Like-Kind Exchanges', $EXPL$Vega acquires replacement property in a qualifying Section 1031 exchange. How is the holding period of the replacement property determined?$EXPL$, $EXPL$["The holding period starts on the date Vega receives the replacement property", "The holding period of the relinquished property tacks onto the replacement property", "The holding period is always treated as more than one year for capital gain purposes", "The holding period resets to zero and begins on the date the exchange is reported on Form 8824"]$EXPL$::jsonb, 1, $EXPL$Correct (B): IRC Section 1223(1). When property is acquired in a like-kind exchange, the holding period of the relinquished property includes (tacks onto) the holding period of the replacement property. This preserves the taxpayer's long-term capital gain status if the relinquished property was already held long-term. Wrong (A): The holding period does not restart; it carries over from the relinquished property. Wrong (C): While tacking usually results in long-term treatment, the rule is about inclusion of the prior period, not an automatic classification. Wrong (D): The filing date of Form 8824 has no bearing on the holding period calculation.$EXPL$, 'easy', 1),

-- Q7: medium / L2 — Netting of liabilities: offsetting mortgage assumed with cash boot given
(3, 'Like-Kind Exchanges', $EXPL$Prescott exchanges a rental condo (basis $180,000, FMV $300,000, mortgage $100,000) for a like-kind property (FMV $250,000, no mortgage). The buyer assumes Prescott's mortgage, and Prescott pays $50,000 cash to equalize values. Under the netting rules, what is the net boot Prescott received?$EXPL$, $EXPL$["$100,000, the full mortgage relief amount", "$50,000, because mortgage relief minus cash paid equals net boot", "$0, because cash boot given fully offsets mortgage relief", "$150,000, because both mortgage relief and the FMV difference are boot"]$EXPL$::jsonb, 1, $EXPL$Correct (B): Treas. Reg. 1.1031(b)-1(c). When a taxpayer both gives cash boot and receives boot in the form of mortgage relief, the cash paid offsets the liability relief. Prescott's mortgage relief ($100,000) minus cash paid ($50,000) equals net boot received of $50,000. Wrong (A): Cash boot given must be netted against mortgage relief before determining boot received. Wrong (C): The cash given ($50,000) does not fully offset the mortgage relief ($100,000); $50,000 of net boot remains. Wrong (D): The FMV difference itself is not an additional category of boot; boot consists of cash, liabilities, and non-like-kind property.$EXPL$, 'medium', 2),

-- Q8: medium / L2 — Drop-and-swap: partner distributes property then exchanges
(3, 'Like-Kind Exchanges', $EXPL$A three-member LLC taxed as a partnership wants to dispose of a commercial building. Two members want cash, but the third member, Garrett, wants to defer gain using Section 1031. The partnership cannot do a Section 1031 exchange because two members want cash. What structure allows Garrett to defer gain?$EXPL$, $EXPL$["The partnership allocates the gain away from Garrett's capital account under Section 704", "The partnership distributes a TIC interest to Garrett, who then executes a Section 1031 exchange individually", "Garrett files a Section 1031 election with the partnership return to opt out of gain recognition", "Garrett reinvests his share of the sale proceeds in like-kind property within 180 days after the partnership sells"]$EXPL$::jsonb, 1, $EXPL$Correct (B): This is the "drop-and-swap" technique recognized under case law and IRS guidance. The partnership distributes an undivided tenancy-in-common interest in the property to Garrett, who then holds it individually and conducts a Section 1031 exchange. The distribution is generally tax-free under Section 731 if done properly. Wrong (A): Section 704 allocation rules cannot eliminate a partner's share of recognized gain from a partnership-level sale; the gain follows the partner's interest. Wrong (C): There is no Section 1031 election available to individual partners; Section 1031 applies at the property-owner level, not the partnership level. Wrong (D): Reinvesting cash sale proceeds after the partnership sells does not qualify as a Section 1031 exchange; the exchange structure must be in place before the disposition.$EXPL$, 'medium', 2),

-- Q9: medium / L3 — Depreciation recapture (Section 1250) on boot portion
(3, 'Like-Kind Exchanges', $EXPL$Santiago exchanges a depreciated commercial building (original cost $400,000, accumulated depreciation $100,000, adjusted basis $300,000, FMV $500,000) for like-kind property (FMV $460,000) plus $40,000 cash. Santiago has $100,000 of unrecaptured Section 1250 gain. How is the $40,000 recognized gain characterized?$EXPL$, $EXPL$["Entirely as capital gain at the standard long-term rate", "Entirely as ordinary income under Section 1245 depreciation recapture", "As unrecaptured Section 1250 gain taxed at a maximum rate of 25%, to the extent of prior depreciation", "As a combination of 50% ordinary income and 50% capital gain"]$EXPL$::jsonb, 2, $EXPL$Correct (C): IRC Sections 1031(b) and 1(h)(1)(E). When gain is recognized in a like-kind exchange involving depreciable real property, unrecaptured Section 1250 gain (prior depreciation on the building) is recaptured first, taxed at a maximum 25% rate. Since Santiago has $100,000 of unrecaptured Section 1250 gain and only $40,000 is recognized, the entire $40,000 is characterized as unrecaptured Section 1250 gain. Wrong (A): Depreciation recapture rules override the standard capital gain rate; unrecaptured Section 1250 gain is taxed at up to 25%. Wrong (B): Real property is subject to Section 1250 recapture, not Section 1245. Section 1245 applies to personal property. Wrong (D): There is no 50/50 split rule; the character follows the ordering rules, with unrecaptured Section 1250 gain recognized first.$EXPL$, 'medium', 3),

-- Q10: easy / L1 — TCJA eliminated personal property from Section 1031 after 2017
(3, 'Like-Kind Exchanges', $EXPL$Prior to the Tax Cuts and Jobs Act of 2017, Section 1031 applied to exchanges of both real and personal property. After TCJA, which type of property remains eligible for like-kind exchange treatment?$EXPL$, $EXPL$["Both real and personal property continue to qualify", "Only tangible personal property used in a trade or business qualifies", "Only real property held for productive use in a trade or business or for investment qualifies", "Only residential real property qualifies; commercial property is excluded"]$EXPL$::jsonb, 2, $EXPL$Correct (C): IRC Section 1031(a)(1), as amended by TCJA Section 13303. Effective for exchanges completed after December 31, 2017, Section 1031 is limited to real property held for productive use in a trade or business or for investment. Wrong (A): TCJA eliminated personal property from Section 1031 eligibility; only real property qualifies after 2017. Wrong (B): The change went in the opposite direction — personal property was removed, not made the sole qualifying category. Wrong (D): Both residential and commercial real property qualify, provided the holding requirements are met; there is no distinction based on property type within real property.$EXPL$, 'easy', 1),

-- Q11: medium / L3 — Failed exchange: all proceeds become taxable if deadlines missed
(3, 'Like-Kind Exchanges', $EXPL$Hartley transfers relinquished property to a qualified intermediary on January 10, 2026. Hartley properly identifies three replacement properties by February 24, 2026. However, due to financing delays, Hartley does not close on any replacement property until July 15, 2026 — the 186th day after the transfer. What is the tax consequence?$EXPL$, $EXPL$["Hartley may still complete the exchange by filing for a 30-day extension with the IRS", "The exchange fails entirely, and Hartley must recognize the full gain on the relinquished property in 2026", "Only the gain attributable to the six excess days is recognized", "The QI may hold the funds until Hartley finds a suitable replacement, with no deadline"]$EXPL$::jsonb, 1, $EXPL$Correct (B): IRC Section 1031(a)(3)(B). The replacement property must be received by the earlier of 180 days after the transfer or the due date of the taxpayer's return (including extensions). Closing on day 186 exceeds the 180-day limit, and the exchange fails entirely. The QI must release the proceeds to Hartley, and the full gain is recognized. Wrong (A): There is no provision for extending the 180-day deadline beyond filing a tax return extension. Wrong (C): The deadline is absolute; missing it by even one day causes the entire exchange to fail, not just a partial recognition. Wrong (D): The QI cannot hold funds indefinitely; the exchange period is fixed by statute.$EXPL$, 'medium', 3),

-- Q12: medium / L2 — Qualified intermediary safe harbor requirements
(3, 'Like-Kind Exchanges', $EXPL$Rivera plans a deferred Section 1031 exchange and needs a qualified intermediary. Rivera's real estate attorney, who handled the original purchase of the relinquished property within the past two years, offers to serve as QI. Is the attorney eligible?$EXPL$, $EXPL$["Yes, any licensed attorney can serve as a qualified intermediary", "No, a person who has acted as the taxpayer's attorney within the preceding two years is a disqualified person and cannot serve as QI", "Yes, but only if the attorney places the funds in a separate escrow account", "No, only banks and title companies may serve as qualified intermediaries"]$EXPL$::jsonb, 1, $EXPL$Correct (B): Treas. Reg. 1.1031(k)-1(k)(2). A disqualified person cannot serve as a QI. Disqualified persons include the taxpayer's agent, which encompasses anyone who has acted as the taxpayer's employee, attorney, accountant, investment banker, or real estate agent within the two-year period ending on the date of the transfer. Wrong (A): Being a licensed attorney does not override the disqualified person rules; the prior relationship creates the disqualification. Wrong (C): Segregating funds does not cure the disqualification; the two-year lookback is a bright-line rule. Wrong (D): There is no restriction limiting QI status to banks and title companies; any non-disqualified person or entity may serve.$EXPL$, 'medium', 2),

-- Q13: medium / L2 — Identification must be unambiguous and in writing
(3, 'Like-Kind Exchanges', $EXPL$Franklin is in a deferred Section 1031 exchange and verbally tells the qualified intermediary on day 40 which replacement property she wants. Franklin does not provide anything in writing before the 45-day deadline. Is Franklin's identification valid?$EXPL$, $EXPL$["Yes, verbal identification to the QI satisfies the requirement", "Yes, if the QI confirms the identification in writing on Franklin's behalf", "No, the identification must be in a written document signed by the taxpayer and delivered to the QI or other involved party before the 45-day deadline", "No, unless the identification is filed directly with the IRS within 45 days"]$EXPL$::jsonb, 2, $EXPL$Correct (C): Treas. Reg. 1.1031(k)-1(c)(2). Replacement property must be identified in a written document signed by the taxpayer and hand-delivered, mailed, faxed, or otherwise sent to the QI or another person involved in the exchange before midnight of the 45th day. Verbal identification does not satisfy the requirement. Wrong (A): Verbal statements are insufficient; the regulations require a signed writing. Wrong (B): The taxpayer must sign the identification document; the QI cannot create it on the taxpayer's behalf. Wrong (D): The identification is sent to the QI or other exchange party, not to the IRS.$EXPL$, 'medium', 2),

-- Q14: medium / L3 — Partial exchange: only like-kind portion deferred
(3, 'Like-Kind Exchanges', $EXPL$Doyle exchanges a commercial office (basis $250,000, FMV $400,000) for a retail storefront (FMV $310,000) and $90,000 in publicly traded stock. How much gain does Doyle recognize, and what is Doyle's basis in the retail storefront?$EXPL$, $EXPL$["$90,000 recognized gain; basis in storefront is $250,000", "$150,000 recognized gain; basis in storefront is $250,000", "$90,000 recognized gain; basis in storefront is $310,000", "$0 recognized gain; basis in storefront is $160,000"]$EXPL$::jsonb, 0, $EXPL$Correct (A): IRC Sections 1031(b) and 1031(d). Realized gain is $400,000 - $250,000 = $150,000. The stock is not like-kind property and constitutes $90,000 of boot. Recognized gain is the lesser of boot received ($90,000) or realized gain ($150,000), so $90,000. Basis of the replacement property = old basis ($250,000) - boot received ($90,000) + gain recognized ($90,000) = $250,000. The stock takes a basis equal to its FMV ($90,000). Wrong (B): Recognized gain is limited to boot received ($90,000), not the full realized gain. Wrong (C): Using FMV as basis ignores the deferral mechanism; basis must be computed using the Section 1031(d) formula. Wrong (D): Boot was received, so full deferral is unavailable.$EXPL$, 'medium', 3),

-- Q15: easy / L1 — Primary residence does not qualify (personal use)
(3, 'Like-Kind Exchanges', $EXPL$Henderson lives in a single-family home that has appreciated significantly. Henderson wants to exchange it for a different home under Section 1031 to defer the gain. Henderson has never rented the home or used it in a business. Can Henderson use Section 1031?$EXPL$, $EXPL$["Yes, because all real property qualifies regardless of how it is used by the owner", "Yes, provided Henderson has owned the home for more than two years before the exchange", "No, because a primary residence used exclusively for personal purposes is not held for business or investment", "No, unless Henderson first converts the home to rental use for at least 90 days before exchanging"]$EXPL$::jsonb, 2, $EXPL$Correct (C): IRC Section 1031(a)(1). Section 1031 requires that property be held for productive use in a trade or business or for investment. A personal residence used solely for personal purposes does not satisfy either requirement. Henderson should consider Section 121 (primary residence exclusion) instead. Wrong (A): Being real property is necessary but not sufficient; the use requirement must also be met. Wrong (B): Length of ownership does not convert personal-use property into qualifying property under Section 1031. Wrong (D): While conversion to rental use can eventually qualify a property, a 90-day minimum is not a bright-line rule established in the statute; the facts and circumstances must show genuine investment or business intent.$EXPL$, 'easy', 1),

-- Q16: easy / L2 — Section 121/1031 combination for converted primary residence
(3, 'Like-Kind Exchanges', $EXPL$Yamamoto lived in a home for three years, then converted it to a rental property for two years before exchanging it for a like-kind rental property under Section 1031. Yamamoto's total gain on the property is $400,000. Yamamoto's CPA advises combining Section 121 and Section 1031. What is the tax benefit of this combination?$EXPL$, $EXPL$["Yamamoto can exclude up to $250,000 of gain under Section 121 and defer the remaining $150,000 under Section 1031", "Yamamoto must choose either Section 121 or Section 1031 but cannot use both on the same property", "Yamamoto receives a double exclusion of $500,000 by combining the two provisions", "The Section 121 exclusion is permanently lost once a property is converted to rental use"]$EXPL$::jsonb, 0, $EXPL$Correct (A): IRC Sections 121 and 1031 and Rev. Proc. 2005-14. A taxpayer who meets the Section 121 ownership and use tests (owned and used as principal residence for at least two of the five years before the exchange) may exclude up to $250,000 ($500,000 if married filing jointly) under Section 121 and defer any remaining gain under Section 1031. Yamamoto lived in the home for three of the five years, meeting the Section 121 requirement. Wrong (B): The two provisions can be combined; IRS guidance explicitly permits sequential application. Wrong (C): The exclusion amount is not doubled by combining the sections; Section 121 limits remain unchanged. Wrong (D): Conversion to rental use does not eliminate the Section 121 exclusion if the ownership and use tests are still met within the five-year lookback period.$EXPL$, 'easy', 2)
;

COMMIT;
