-- Migration: Question generation — ISC batch 19 (30 questions)
-- Date: 2026-03-24
-- Topic: Change Management
-- Difficulty: 9E / 15M / 6H
-- Bloom's: L1:6 / L2:10 / L3:9 / L4:5

BEGIN;

INSERT INTO questions (section_id, topic, stem, choices, correct_index, explanation, difficulty, cognitive_level)
VALUES

-- Q1: easy / L1 — Forward schedule of changes definition
(5, 'Change Management', $EXPL$What is a forward schedule of changes (FSC) in IT service management?$EXPL$, $EXPL$["A calendar listing all approved upcoming changes with their planned implementation dates", "A historical log of all changes completed in the prior fiscal year", "A risk register documenting potential future threats to IT systems", "A list of emergency changes that bypassed the standard approval process"]$EXPL$::jsonb, 0, $EXPL$Correct (A): ITIL defines the forward schedule of changes as a document listing all approved changes and their planned implementation dates. The FSC enables coordination across teams by providing visibility into upcoming modifications, helping prevent scheduling conflicts and ensuring adequate resource allocation.
Wrong (B): A historical log is a change record or change log, not a forward schedule. The FSC is forward-looking by definition.
Wrong (C): A risk register tracks threats and vulnerabilities, which is a risk management tool, not a change scheduling artifact.
Wrong (D): Emergency changes that bypassed approval would appear in an emergency change log or audit trail, not in a forward schedule of planned changes.$EXPL$, 'easy', 1),

-- Q2: medium / L2 — Configuration drift detection
(5, 'Change Management', $EXPL$Granite Systems Corp runs quarterly configuration audits comparing live server settings against the approved Configuration Management Database (CMDB) baseline. The latest audit reveals that 11 production servers have firewall rules that differ from the CMDB records, yet no change tickets exist for these modifications. Under COBIT DSS06, which conclusion should the IT auditor draw?$EXPL$, $EXPL$["The CMDB baseline was set too long ago and should be refreshed", "Configuration drift has occurred due to unauthorized changes bypassing the change management process", "The firewall vendor automatically pushed updates that override local settings", "The differences are expected because production servers require dynamic configurations"]$EXPL$::jsonb, 1, $EXPL$Correct (B): COBIT DSS06 (Manage Business Process Controls) requires that all changes to IT assets be authorized, documented, and traceable. Discrepancies between the CMDB and actual configurations without corresponding change tickets indicate configuration drift from unauthorized changes — a control failure requiring immediate investigation and remediation.
Wrong (A): While refreshing baselines is good practice, the absence of change tickets is the primary issue, not baseline age.
Wrong (C): Vendor-pushed updates would still need to be documented through the change management process; their source does not excuse missing change records.
Wrong (D): Production environments must still adhere to controlled change processes; dynamic needs do not justify undocumented modifications.$EXPL$, 'medium', 2),

-- Q3: hard / L4 — Conflicting change policies across SDLC and operations
(5, 'Change Management', $EXPL$Ironclad Financial Services maintains separate change management processes for its application development team (governed by SDLC procedures) and its infrastructure operations team (governed by ITIL change management). During a major release, the development team completes all SDLC gates including UAT and security review, but the infrastructure team rejects the deployment because the change request was not submitted through their CAB process. The CIO asks the IT governance officer to evaluate the situation. Which recommendation BEST addresses the root cause?$EXPL$, $EXPL$["Exempt SDLC-governed changes from the CAB process since they already have sufficient controls", "Allow either process to serve as the authoritative approval for production deployments", "Establish a unified change management policy that integrates SDLC gates with the operational CAB process at defined handoff points", "Require the development team to submit a separate change request after completing all SDLC gates"]$EXPL$::jsonb, 2, $EXPL$Correct (C): COBIT APO09 and ITIL best practices recommend a unified change management framework. The root cause is two parallel processes without integration. Establishing defined handoff points — where SDLC completion triggers the operational change request — ensures both development rigor and operational oversight without duplication or gaps.
Wrong (A): Exempting SDLC changes removes operational oversight of production deployments, creating a control gap for infrastructure impact assessment.
Wrong (B): Allowing either process as authoritative creates ambiguity and may result in changes bypassing one set of controls entirely.
Wrong (D): A separate change request after SDLC gates addresses the symptom but not the root cause; it adds bureaucracy without integrating the processes.$EXPL$, 'hard', 4),

-- Q4: easy / L2 — Change model concept
(5, 'Change Management', $EXPL$Vertex Consulting's IT department processes approximately 40 routine password reset requests per week for its internal applications. Each request currently goes through the full CAB review cycle, consuming significant time. The IT manager proposes creating a predefined process with pre-approved steps for this recurring task. Under ITIL, what is this predefined process called?$EXPL$, $EXPL$["A change policy exception for low-risk tasks", "A service level agreement with the business", "A standard operating procedure for incidents", "A change model with pre-approved steps"]$EXPL$::jsonb, 3, $EXPL$Correct (D): ITIL defines a change model as a predefined, repeatable approach for handling a particular type of change. Change models include pre-approved steps, roles, and timescales for frequently recurring changes, reducing the need for full CAB review each time while maintaining control through standardized procedures.
Wrong (A): A policy exception would bypass controls rather than standardize them, which is not the intent of creating a repeatable process.
Wrong (B): A service level agreement defines performance targets between a service provider and customer, not predefined change procedures.
Wrong (C): Password resets handled through the change process are changes, not incidents; an SOP for incidents addresses disruptions, not planned modifications.$EXPL$, 'easy', 2),

-- Q5: medium / L3 — Back-out testing before implementation
(5, 'Change Management', $EXPL$Oakridge Credit Union is preparing to deploy a major upgrade to its loan origination system during a weekend maintenance window. The change manager has documented a detailed rollback plan specifying the steps to revert to the previous version if the upgrade fails. The IT auditor reviewing the change request notices that the rollback plan has never been tested. Applying the "Is This Change Properly Authorized?" decision framework, which action should the change manager take before proceeding?$EXPL$, $EXPL$["Execute a rehearsal of the rollback plan in the test environment to verify it can restore the system to its pre-change state within the defined RTO", "Proceed with the deployment since the rollback plan is documented and the change has CAB approval", "Delay the deployment until the next quarterly maintenance cycle to allow more preparation time", "Assign a second team member to review the rollback plan documentation for completeness"]$EXPL$::jsonb, 0, $EXPL$Correct (A): NIST SP 800-128 and ITIL best practices require that rollback plans be tested before implementation, not merely documented. A rehearsal in the test environment validates that the reversion steps actually work and can be completed within the recovery time objective, reducing the risk of an extended outage if the change fails.
Wrong (B): CAB approval and documentation are necessary but insufficient; an untested rollback plan is a control gap because there is no assurance the plan will work when needed.
Wrong (C): Delaying does not address the core issue — the rollback plan must be tested regardless of when deployment occurs.
Wrong (D): A documentation review checks completeness but does not validate that the rollback steps function correctly in practice.$EXPL$, 'medium', 3),

-- Q6: hard / L4 — Governance escalation for high-risk changes
(5, 'Change Management', $EXPL$Silverline Insurance Group's change advisory board approves a database migration that will restructure the claims processing tables. The migration is scheduled for a four-hour maintenance window on Saturday. On Friday afternoon, the DBA team discovers that the migration script takes six hours in the staging environment, exceeding the approved window by two hours. The extended downtime would affect the automated claims batch processing that runs Sunday morning. The change manager must decide how to proceed. Which action BEST demonstrates effective change governance?$EXPL$, $EXPL$["Proceed with the migration and extend the maintenance window, notifying affected users Monday morning", "Escalate to the CAB for re-evaluation, presenting the new timeline and downstream batch processing impact for re-approval", "Cancel the change permanently and redesign the migration from scratch", "Split the migration into two phases and deploy the first phase within the original window without re-approval"]$EXPL$::jsonb, 1, $EXPL$Correct (B): COBIT APO09 and ITIL change management require that material deviations from approved change parameters — including timeline, scope, or impact — be escalated back to the approval authority. The new six-hour timeline and downstream batch impact represent a material change in risk that the CAB must reassess before the change proceeds.
Wrong (A): Extending the window without re-approval bypasses the governance controls; the original approval was based on a four-hour window with no downstream impact.
Wrong (C): Permanent cancellation is disproportionate; the migration may still be viable with a revised window or approach after CAB re-evaluation.
Wrong (D): Splitting the migration changes the scope without re-approval, and deploying a partial migration may introduce data integrity risks not assessed in the original change request.$EXPL$, 'hard', 4),

-- Q7: medium / L2 — Change request vs service request distinction
(5, 'Change Management', $EXPL$Meadowbrook Accounting's help desk receives two tickets on the same morning. Ticket A requests that a new employee be granted access to the firm's tax preparation software using an existing role template. Ticket B requests that a custom report be added to the general ledger application, requiring code modifications. The IT service desk analyst must classify each ticket appropriately. Under ITIL's RICE framework, how should these tickets be classified?$EXPL$, $EXPL$["Both are changes because they modify the IT environment", "Ticket A is a service request; Ticket B is a change", "Both are service requests because they originate from end users", "Ticket A is a change; Ticket B is an incident"]$EXPL$::jsonb, 1, $EXPL$Correct (B): Under the RICE framework (Request, Incident, Change, Event), Ticket A is a service request — a routine, pre-approved provisioning action using an existing role template that does not modify the IT infrastructure. Ticket B is a change because it requires code modifications to an application, which must go through the formal change management process including impact assessment and CAB review.
Wrong (A): Not both are changes; Ticket A follows a pre-approved template for routine access provisioning and does not require CAB review.
Wrong (C): Not both are service requests; Ticket B involves code modifications that alter system functionality, requiring formal change management.
Wrong (D): Ticket A is not a change, and Ticket B is not an incident — an incident is an unplanned service interruption, not a request for new functionality.$EXPL$, 'medium', 2),

-- Q8: medium / L3 — Stakeholder communication plan for changes
(5, 'Change Management', $EXPL$Clearfield Manufacturing is deploying a new inventory management module that will change how warehouse staff scan and record incoming shipments. The IT project manager focuses entirely on the technical deployment plan and completes the migration on schedule. On Monday morning, warehouse staff are unable to process shipments because they were not informed of the new scanning procedures. Using the change management process outlined in the lesson, which step was inadequately performed?$EXPL$, $EXPL$["The request step, because the change lacked business justification", "The review step, because stakeholder impact was not fully assessed", "The implement step, because training and communication should accompany deployment", "The close step, because post-implementation review was not conducted"]$EXPL$::jsonb, 2, $EXPL$Correct (C): The implementation step encompasses not just the technical deployment but also communication and training for affected users. Per COBIT BAI06 and ITIL change management, deployment planning must include stakeholder notification and readiness activities. The project manager focused only on technical execution and neglected the human elements of change implementation.
Wrong (A): The change had business justification in the request; the request step was not the failure point.
Wrong (B): While review should have flagged user impact, the direct failure was in the implementation step where communication was omitted.
Wrong (D): The close step occurs after deployment; the problem emerged immediately upon go-live, before the close step would occur.$EXPL$, 'medium', 3),

-- Q9: medium / L3 — Environment promotion controls
(5, 'Change Management', $EXPL$Ridgeline Software's development team uses three environments: development, staging, and production. An IT auditor reviewing the promotion process discovers that developers can promote code directly from the development environment to production, bypassing the staging environment entirely. Applying the "Is This Change Properly Authorized?" decision framework, which control deficiency does this practice represent?$EXPL$, $EXPL$["A testing control gap, because all changes must be validated in a non-production environment before deployment to production", "A documentation deficiency, because the promotion path is not recorded in the change log", "An approval deficiency, because the CAB did not authorize the deployment", "A rollback deficiency, because no reversion plan exists for direct promotions"]$EXPL$::jsonb, 0, $EXPL$Correct (A): The decision framework asks "Was the change tested in a non-production environment before deployment?" Bypassing staging means changes reach production without validation in a controlled test environment. This is a fundamental SDLC and ITGC control — separation of environments ensures changes are tested before they affect production systems and data.
Wrong (B): While documentation may also be lacking, the primary deficiency is the absence of testing in the staging environment, not the logging of the promotion path.
Wrong (C): The question does not state that CAB approval was missing; the issue is specifically about environment separation and testing controls.
Wrong (D): A rollback plan is a separate control concern; the direct deficiency described is the bypass of the testing environment.$EXPL$, 'medium', 3),

-- Q10: hard / L4 — Automated vs manual change controls trade-offs
(5, 'Change Management', $EXPL$Apex Digital Services runs a fully automated CI/CD pipeline with peer code review, automated unit tests, integration tests, and security scans. The pipeline deploys to production 15-20 times per day. A new IT auditor argues that each deployment should require a manual CAB approval ticket. The DevOps manager counters that the automated controls provide equivalent or superior assurance to manual approvals. The CTO asks the IT governance officer to evaluate both positions. Which recommendation BEST balances control effectiveness with operational efficiency?$EXPL$, $EXPL$["Require manual CAB approval for every deployment to ensure proper governance", "Accept the automated controls as sufficient since they exceed the rigor of manual reviews", "Implement a risk-based approach where automated controls govern routine deployments but high-risk changes require additional manual review and approval", "Reduce deployment frequency to once per week to allow time for manual CAB review of each batch"]$EXPL$::jsonb, 2, $EXPL$Correct (C): COBIT APO09 and ITIL 4 recognize that automated controls can satisfy change management requirements when properly designed. A risk-based approach maintains governance by allowing automated controls for routine, low-risk deployments while requiring additional manual oversight for changes that affect critical systems, database schemas, security configurations, or compliance-sensitive components. This preserves both control effectiveness and deployment velocity.
Wrong (A): Requiring manual CAB approval for 15-20 daily deployments would create an unsustainable bottleneck without proportional risk reduction, since the automated controls already address the key control objectives.
Wrong (B): Accepting all automated controls as universally sufficient ignores that some high-risk changes may require human judgment beyond what automated tests can assess.
Wrong (D): Reducing deployment frequency to accommodate manual review sacrifices the operational benefits of CI/CD without addressing the underlying control question.$EXPL$, 'hard', 4),

-- Q11: easy / L1 — Change ownership definition
(5, 'Change Management', $EXPL$In change management, what is the role of the change owner?$EXPL$, $EXPL$["The person who writes the source code for the change", "The executive who funds the IT department's annual budget", "The individual accountable for ensuring the change is completed successfully through all process steps", "The external auditor who reviews change management controls"]$EXPL$::jsonb, 2, $EXPL$Correct (C): ITIL defines the change owner as the individual who is accountable for ensuring a specific change is shepherded through all stages of the change management process — from request through implementation and closure. The change owner tracks progress, ensures approvals are obtained, and confirms successful completion.
Wrong (A): The person who writes source code is the developer; the change owner is an accountability role, not necessarily a technical role.
Wrong (B): The executive who funds the IT budget is a financial sponsor, not the change owner for a specific change request.
Wrong (D): The external auditor evaluates controls but does not own or manage individual changes through the process.$EXPL$, 'easy', 1),

-- Q12: medium / L2 — Technical debt from deferred changes
(5, 'Change Management', $EXPL$Cornerstone Retail's IT department has maintained a change backlog of 180 approved but unimplemented changes for over six months. During a quarterly review, the IT audit team notes that 45 of these changes are security patches for known vulnerabilities, and 30 are application updates that address calculation errors in the point-of-sale system. The IT director explains that resource constraints have prevented implementation. Under COBIT DSS05, which risk does this deferred backlog MOST directly create?$EXPL$, $EXPL$["Increased change success rate due to more thorough planning", "Reduced audit trail integrity because changes are not being logged", "Accumulated technical debt and unmitigated security exposure from known but unpatched vulnerabilities", "Higher employee satisfaction because fewer system changes reduce disruption"]$EXPL$::jsonb, 2, $EXPL$Correct (C): Under COBIT DSS05 (Manage Security Services), organizations must address known vulnerabilities in a timely manner. A prolonged backlog of 45 security patches creates accumulated technical debt and sustained exposure to known attack vectors. The 30 calculation error fixes represent operational risk from known defects. Together, this deferred backlog compounds risk over time.
Wrong (A): A growing backlog does not improve change success rate; it increases the risk of outdated patches and conflicting changes.
Wrong (B): The changes are logged as approved in the backlog; the audit trail issue is not the primary risk — unmitigated vulnerabilities are.
Wrong (D): Fewer implemented changes may reduce disruption but at the cost of sustained security and operational risk from known issues.$EXPL$, 'medium', 2),

-- Q13: medium / L3 — Data migration validation during deployment
(5, 'Change Management', $EXPL$Bayshore Medical Group is migrating its patient billing database from a legacy system to a new cloud-based platform. The migration script runs successfully in the staging environment, and the IT team proceeds to production deployment. After go-live, the billing department discovers that 2,300 patient records have incorrect insurance policy numbers due to a field mapping error. Applying the change management process, which control was MOST likely deficient?$EXPL$, $EXPL$["Post-migration data validation and reconciliation testing before go-live", "CAB approval of the original change request submitted by the team", "Rollback plan documentation specifying reversion procedures", "Emergency change classification and expedited approval routing"]$EXPL$::jsonb, 0, $EXPL$Correct (A): COBIT BAI06 and ITIL change management require that deployment includes validation testing to confirm the change produced the expected results. For data migrations, this means reconciling record counts and verifying data accuracy in key fields before releasing the system to end users. The field mapping error should have been caught by post-migration validation checks.
Wrong (B): CAB approval addresses whether the change should proceed, not whether the migrated data is accurate post-deployment.
Wrong (C): A rollback plan addresses reverting the change if it fails, but does not prevent data integrity errors — validation testing does.
Wrong (D): This was a planned migration, not an emergency change; classification is not relevant to the data integrity failure.$EXPL$, 'medium', 3),

-- Q14: medium / L3 — Change closure criteria
(5, 'Change Management', $EXPL$Ridgemont Financial completes a major upgrade to its trading platform. The implementation team reports that the software is running without errors, and the change manager immediately closes the change ticket. Two weeks later, traders report intermittent latency issues during peak trading hours that were not present before the upgrade. Using the change management process, which requirement was skipped during the close step?$EXPL$, $EXPL$["A formal post-implementation review with an adequate monitoring period before closure", "Rollback plan execution to revert the system to its prior state", "CAB re-approval of the completed change before ticket closure", "Emergency change documentation and retroactive review procedures"]$EXPL$::jsonb, 0, $EXPL$Correct (A): The close step of the change management process requires a formal post-implementation review (PIR) that evaluates whether the change achieved its objectives over a defined monitoring period. Closing the ticket immediately after deployment without observing system behavior under real-world conditions — including peak load — bypasses this critical control. The latency issue would likely have been detected during a proper monitoring period.
Wrong (B): Rollback plan execution is only triggered when a change fails; it is not a standard closure requirement for changes that appear to function correctly.
Wrong (C): The CAB approves changes before implementation, not after completion; re-approval is not a standard closure step.
Wrong (D): This was a planned upgrade, not an emergency change; emergency documentation requirements are not applicable.$EXPL$, 'medium', 3),

-- Q15: medium / L3 — Parallel testing vs pilot testing distinction
(5, 'Change Management', $EXPL$Thornton Manufacturing is replacing its legacy payroll system with a new cloud-based solution. The CFO insists that both the old and new systems process payroll simultaneously for two pay cycles before the legacy system is decommissioned, so that the results can be compared. The IT manager suggests instead deploying the new system to one department first and expanding to others after confirming it works correctly. Which testing approaches are the CFO and IT manager proposing, respectively?$EXPL$, $EXPL$["Regression testing and integration testing", "Stress testing and user acceptance testing", "Parallel testing and pilot testing", "Acceptance testing and canary deployment"]$EXPL$::jsonb, 2, $EXPL$Correct (C): The CFO proposes parallel testing — running both old and new systems simultaneously and comparing outputs to verify the new system produces accurate results. The IT manager proposes pilot testing — deploying to a limited group first to validate functionality before a full rollout. Both are valid deployment strategies with different risk profiles and resource requirements.
Wrong (A): Regression testing checks that existing functionality is not broken by changes; integration testing verifies component interactions. Neither describes the approaches in the scenario.
Wrong (B): Stress testing evaluates system performance under heavy load; UAT involves business users validating requirements. Neither matches the described approaches.
Wrong (D): Acceptance testing is a broader category, and while canary deployment is similar to pilot testing, it specifically involves routing a small percentage of production traffic, not deploying to a specific department.$EXPL$, 'medium', 3),

-- Q16: easy / L1 — Change enablement vs change control
(5, 'Change Management', $EXPL$Under ITIL 4, what does the term "change enablement" emphasize compared to traditional change control?$EXPL$, $EXPL$["Eliminating all approval steps to increase deployment speed", "Facilitating beneficial changes while still managing risk appropriately", "Restricting changes to only emergency situations during business hours", "Delegating all change decisions to the development team exclusively"]$EXPL$::jsonb, 1, $EXPL$Correct (B): ITIL 4 rebranded "change management" to "change enablement" to emphasize that the process should facilitate and enable beneficial changes rather than act solely as a gatekeeping function. The practice still manages risk through appropriate controls but shifts the mindset toward enabling value delivery while maintaining governance.
Wrong (A): Change enablement does not eliminate approvals; it streamlines them based on risk level while retaining necessary controls.
Wrong (C): Restricting changes only to emergencies would impede business operations; change enablement supports all types of beneficial changes with proportionate controls.
Wrong (D): Delegating all decisions to developers would remove governance oversight; change enablement maintains appropriate approval structures.$EXPL$, 'easy', 1),

-- Q17: medium / L2 — Audit trail requirements for change records
(5, 'Change Management', $EXPL$During an ITGC audit at Ferndale Logistics, the auditor requests the change management records for the past 12 months. The IT manager provides a spreadsheet listing 340 completed changes with dates and brief descriptions, but the records lack the names of individuals who requested, approved, and implemented each change. Under COBIT MEA02, which audit trail deficiency should the auditor report?$EXPL$, $EXPL$["Insufficient change records — the total number of changes is too low for an organization of this size", "Incomplete change documentation — records must identify the individuals responsible for each step in the change process to establish accountability and enable audit traceability", "Improper storage medium — change records must be maintained in a database, not a spreadsheet", "Excessive record retention — 12 months of records exceeds the standard retention period"]$EXPL$::jsonb, 1, $EXPL$Correct (B): COBIT MEA02 (Manage the System of Internal Control) requires that change management records maintain a complete audit trail, including the identity of individuals who requested, reviewed, approved, and implemented each change. Without this information, the organization cannot establish accountability, verify segregation of duties, or trace changes to authorized personnel.
Wrong (A): The number of changes is not inherently too low; change volume depends on the organization's size and complexity. The deficiency is in documentation quality, not quantity.
Wrong (C): The storage medium (spreadsheet vs. database) is not the primary audit concern; completeness of the audit trail is the issue regardless of format.
Wrong (D): Twelve months of retention is appropriate for most audit purposes; the deficiency is incomplete records, not excessive retention.$EXPL$, 'medium', 2),

-- Q18: medium / L2 — Change collision detection
(5, 'Change Management', $EXPL$Brookdale Financial Services has three IT teams submitting change requests for the same two-week period. Team A plans to upgrade the database server OS on Tuesday. Team B plans to deploy a new reporting module that depends on the database server on Wednesday. Team C plans to migrate network storage on Thursday, which requires the database to be offline. The change manager reviews all three requests. Which change management concept does this review process demonstrate?$EXPL$, $EXPL$["Emergency change triage based on severity and business impact", "Change collision analysis identifying interdependent or conflicting changes", "Post-implementation review of previously completed changes", "Standard change pre-authorization using predefined templates"]$EXPL$::jsonb, 1, $EXPL$Correct (B): Change collision analysis (also called change conflict detection) is the process of reviewing the forward schedule of changes to identify overlapping, interdependent, or conflicting changes planned for the same timeframe. The change manager must assess whether Team B's deployment could be affected by Team A's OS upgrade and whether Team C's storage migration conflicts with both prior changes.
Wrong (A): Emergency change triage prioritizes unplanned urgent changes, not three planned changes in the normal schedule.
Wrong (C): Post-implementation review evaluates changes after completion, not before implementation during the planning phase.
Wrong (D): Standard change pre-authorization applies to routine, low-risk changes with predefined steps, not to the coordination of multiple complex changes.$EXPL$, 'medium', 2),

-- Q19: hard / L4 — Evaluating change management maturity
(5, 'Change Management', $EXPL$Landmark Healthcare's IT governance committee reviews its change management metrics for the past year: 92% change success rate, 4% emergency change ratio, mean time to implement of 8 business days, and zero unauthorized changes detected. However, a deeper analysis reveals that 60% of all changes are classified as "standard" using broadly defined change models, and the CAB meets only when "normal" changes are submitted. The IT auditor suspects the metrics may overstate the maturity of the program. Which finding MOST supports the auditor's concern?$EXPL$, $EXPL$["The 8-day mean time to implement is too long for an effective change management process", "The zero unauthorized changes finding proves the process is working perfectly", "Broadly defined standard change models may be channeling changes that warrant individual risk assessment and CAB review away from proper scrutiny, artificially inflating success metrics", "The 4% emergency change ratio is below the recommended threshold, indicating insufficient responsiveness"]$EXPL$::jsonb, 2, $EXPL$Correct (C): COBIT APO09 and ITIL best practices require that standard change models be narrowly defined for truly routine, low-risk changes. When 60% of changes are classified as standard under broad definitions, changes that should receive individual impact assessment and CAB oversight may bypass proper review. This inflates the change success rate and masks potential control gaps because standard changes receive less scrutiny.
Wrong (A): An 8-day mean time to implement is not inherently problematic; appropriate timelines depend on change complexity and organizational context.
Wrong (B): Zero unauthorized changes could indicate strong controls, but it could also indicate that the broadly defined standard change models are absorbing changes that should be individually assessed — the auditor's exact concern.
Wrong (D): A 4% emergency change ratio is well within the recommended threshold of under 10%, which indicates appropriate classification, not insufficient responsiveness.$EXPL$, 'hard', 4),

-- Q20: medium / L3 — SDLC requirements phase and change management
(5, 'Change Management', $EXPL$Suncoast Insurance is building a new claims adjudication system. During the requirements phase of the SDLC, the project team collects detailed specifications from the claims department. Six months later, during user acceptance testing, claims adjusters reject the system because it does not handle multi-party claims — a requirement that was discussed verbally but never formally documented. Applying SDLC controls, which control failure is the root cause?$EXPL$, $EXPL$["Inadequate UAT procedures that failed to detect the gap", "Failure to formally document and obtain stakeholder sign-off on requirements", "Insufficient development resources allocated to the project", "Missing rollback plan for the production deployment"]$EXPL$::jsonb, 1, $EXPL$Correct (B): The SDLC requirements phase requires that all business and technical requirements be formally documented in a requirements specification and approved by stakeholders. Verbal requirements that are not captured in the signed-off specification create scope gaps that propagate through design, development, and testing. Formal documentation and stakeholder sign-off ensure completeness and prevent disputes during UAT.
Wrong (A): UAT procedures functioned correctly — the adjusters identified the missing functionality. The failure occurred upstream in requirements gathering.
Wrong (C): Development resources are not the issue; the system was built to spec, but the spec was incomplete.
Wrong (D): A rollback plan addresses deployment failures, not requirements gaps discovered during testing.$EXPL$, 'medium', 3),

-- Q21: easy / L2 — Change categorization by risk and impact
(5, 'Change Management', $EXPL$Pinecrest Accounting's IT team receives two change requests on the same day. Change A is a routine update to the firm's email signature template affecting cosmetic appearance only. Change B is a database schema modification to the general ledger application that will alter how journal entries are stored. The change manager must assign a risk category to each. How should the changes be categorized?$EXPL$, $EXPL$["Both should be categorized as high risk because they affect production systems", "Change A is low risk; Change B is high risk based on the potential impact to financial data integrity", "Both should be categorized as low risk because they are internally requested", "Change A is high risk because it affects all users; Change B is low risk because it is a backend change"]$EXPL$::jsonb, 1, $EXPL$Correct (B): Change risk categorization is based on potential impact to business operations and data integrity. Change A modifies cosmetic elements with no impact on system functionality or data, warranting low-risk classification. Change B alters the database schema of a financial application, directly affecting how critical accounting data is stored, warranting high-risk classification with full CAB review and extensive testing.
Wrong (A): Not all production changes carry equal risk; a cosmetic email signature change does not warrant the same scrutiny as a database schema modification.
Wrong (C): The source of the request does not determine risk level; impact to operations and data integrity are the determining factors.
Wrong (D): User count alone does not determine risk; a backend database schema change to the general ledger carries far greater risk to financial reporting integrity than a cosmetic change.$EXPL$, 'easy', 2),

-- Q22: easy / L1 — Post-implementation review definition
(5, 'Change Management', $EXPL$What is the primary purpose of a post-implementation review (PIR) in the change management process?$EXPL$, $EXPL$["To evaluate whether a completed change achieved its objectives and identify lessons learned", "To approve the change request before implementation begins in production", "To assign technical resources for the upcoming deployment window", "To negotiate the project budget with executive stakeholders"]$EXPL$::jsonb, 0, $EXPL$Correct (A): ITIL and COBIT BAI06 define the post-implementation review as the final step in the change management process. The PIR evaluates whether the change achieved its intended objectives, documents any unintended consequences, and captures lessons learned to improve future change management practices.
Wrong (B): Approving the change request occurs during the approval step before implementation, not during the post-implementation review.
Wrong (C): Assigning technical resources is part of implementation planning, not the post-implementation review conducted after deployment.
Wrong (D): Budget negotiation is a project management activity, not part of the change management post-implementation review.$EXPL$, 'easy', 1),

-- Q23: easy / L2 — Smoke testing after deployment
(5, 'Change Management', $EXPL$Ashford Technology deploys a patch to its accounts payable application during a Saturday maintenance window. Immediately after deployment, the operations team runs a set of basic functional checks — verifying that the application starts, users can log in, and core transactions can be processed — before declaring the deployment successful. What is this type of post-deployment validation commonly called?$EXPL$, $EXPL$["Regression testing", "Stress testing", "Smoke testing", "Penetration testing"]$EXPL$::jsonb, 2, $EXPL$Correct (C): Smoke testing (also called sanity testing or build verification testing) is a set of basic functional checks performed immediately after deployment to verify that the most critical functions of the application work correctly. It confirms the system is stable enough for more thorough testing or for release to users, without exhaustively testing every feature.
Wrong (A): Regression testing is a comprehensive check that existing functionality has not been broken by changes, which is broader and more time-consuming than smoke testing.
Wrong (B): Stress testing evaluates system performance under heavy load conditions, not basic post-deployment functionality.
Wrong (D): Penetration testing simulates attacks to identify security vulnerabilities, which is a security assessment, not a deployment validation check.$EXPL$, 'easy', 2),

-- Q24: medium / L3 — Immutable deployment artifacts
(5, 'Change Management', $EXPL$Harborview Tech's IT audit reveals that a developer modified a deployment package after it passed quality assurance testing but before it was deployed to production. The modification added a logging configuration change that was not included in the original change request or test plan. The change was deployed to production without the QA team's knowledge. Using the "Is This Change Properly Authorized?" decision framework, which control principle was violated?$EXPL$, $EXPL$["The principle that deployment artifacts must remain unchanged (immutable) between testing and production deployment to ensure what was tested is exactly what is deployed", "The principle that changes must be submitted as formal change requests", "The principle that emergency changes require retroactive documentation", "The principle that the CAB must meet weekly to review all changes"]$EXPL$::jsonb, 0, $EXPL$Correct (A): NIST SP 800-128 and COBIT BAI06 require that deployment artifacts remain immutable between the testing and production environments. Modifying a package after QA approval but before production deployment means the production system receives untested code, undermining the assurance provided by the testing process. This violates the fundamental control that what is tested must be exactly what is deployed.
Wrong (B): A formal change request was submitted for the original change; the violation is the post-approval modification of the tested artifact, not the absence of a request.
Wrong (C): This was not an emergency change; retroactive documentation requirements for emergency changes are not applicable here.
Wrong (D): CAB meeting frequency is a governance practice, not the specific control principle violated by modifying a tested deployment package.$EXPL$, 'medium', 3),

-- Q25: easy / L1 — SDLC planning phase deliverable
(5, 'Change Management', $EXPL$What is the primary deliverable of the planning phase of the System Development Life Cycle (SDLC)?$EXPL$, $EXPL$["A project charter and feasibility analysis defining scope, objectives, and resource requirements", "Working software components ready for user testing", "A completed system design document with data models and interface specifications", "Test results and defect reports from integration testing"]$EXPL$::jsonb, 0, $EXPL$Correct (A): The SDLC planning phase produces a project charter and feasibility analysis that define the project scope, objectives, resource allocation, and an assessment of whether the project is technically, economically, and operationally feasible. These deliverables establish the foundation for all subsequent SDLC phases.
Wrong (B): Working software components are the deliverable of the development phase, not the planning phase.
Wrong (C): A system design document is the deliverable of the design phase, which follows the requirements phase.
Wrong (D): Test results and defect reports are deliverables of the testing phase, which occurs after development.$EXPL$, 'easy', 1),

-- Q26: medium / L2 — Change success rate calculation and interpretation
(5, 'Change Management', $EXPL$Whitfield Insurance processed 200 changes during Q1. Of these, 14 required rollback after deployment, 8 caused unplanned incidents, and 3 changes both required rollback and caused incidents. The IT governance committee asks the change manager to calculate the change success rate for the quarter. Using standard change management metrics, what is the change success rate?$EXPL$, $EXPL$["86%", "89%", "90.5%", "91%"]$EXPL$::jsonb, 2, $EXPL$Correct (C): The change success rate measures the percentage of changes implemented without causing incidents or requiring rollback. Failed changes are those requiring rollback OR causing incidents. Using inclusion-exclusion to avoid double-counting: 14 + 8 - 3 = 19 unique failed changes. Success rate = (200 - 19) / 200 = 181 / 200 = 90.5%.
Wrong (A): 86% would result from adding all 22 failures (14 + 8) without removing the 3 overlapping changes, double-counting failures.
Wrong (B): 89% (178/200) uses an incorrect failure count and does not properly apply inclusion-exclusion.
Wrong (D): 91% would undercount the failures, possibly by excluding one category entirely.$EXPL$, 'medium', 2),

-- Q27: easy / L1 — Separation of environments
(5, 'Change Management', $EXPL$In the SDLC and change management, why must development, testing, and production environments be separated?$EXPL$, $EXPL$["To reduce the cost of server hardware by distributing workloads across multiple machines", "To allow developers to work remotely from different geographic locations", "To prevent untested or unauthorized changes from directly affecting production systems and data", "To ensure that all employees have equal access to the organization's IT systems"]$EXPL$::jsonb, 2, $EXPL$Correct (C): Separation of environments is a fundamental SDLC and ITGC control. It ensures that changes are developed and tested in isolated environments before being promoted to production through a controlled process. This prevents untested code, configuration errors, or unauthorized modifications from directly impacting production systems and the integrity of live data.
Wrong (A): Cost reduction is not the purpose of environment separation; it may actually increase infrastructure costs by requiring multiple environments.
Wrong (B): Geographic distribution of developers is a workforce management concern, not the rationale for environment separation.
Wrong (D): Equal access is not the goal; in fact, environment separation restricts access — developers should not have production access.$EXPL$, 'easy', 1),

-- Q28: hard / L4 — Evaluating change management controls across merged organizations
(5, 'Change Management', $EXPL$Cascade Holdings acquires Riverstone Analytics. Cascade uses a formal ITIL-based change management process with weekly CAB meetings, CMDB tracking, and mandatory post-implementation reviews. Riverstone operates an agile DevOps model with automated CI/CD pipelines, feature flags, and real-time monitoring replacing formal CAB reviews. The CTO must integrate both approaches into a unified change management framework for the combined organization. Which approach BEST achieves this integration?$EXPL$, $EXPL$["Mandate that Riverstone abandon DevOps and adopt Cascade's ITIL-based process for all changes", "Allow both organizations to continue their existing processes independently without integration", "Design a risk-tiered framework where CI/CD controls govern routine deployments and CAB governs high-risk changes, with unified CMDB tracking", "Replace both existing processes with a new custom framework designed and built from scratch"]$EXPL$::jsonb, 2, $EXPL$Correct (C): COBIT APO01 (Manage the IT Management Framework) and ITIL 4's change enablement practice recognize that different change types warrant different levels of control. A risk-tiered framework leverages the strengths of both approaches: automated CI/CD controls provide efficient governance for routine, low-risk deployments, while formal CAB oversight ensures appropriate scrutiny for high-risk changes affecting financial systems. Unified CMDB tracking maintains a single source of truth across both models.
Wrong (A): Mandating ITIL for all changes would destroy Riverstone's deployment velocity and agile culture without proportional risk reduction for low-risk changes.
Wrong (B): Independent processes create governance gaps, inconsistent risk assessment, and potential conflicts when changes span both organizations' systems.
Wrong (D): Building from scratch wastes the proven controls already in place in both organizations and introduces unnecessary implementation risk.$EXPL$, 'hard', 4),

-- Q29: medium / L2 — Business impact analysis informing change priority
(5, 'Change Management', $EXPL$Elkridge Bank's business impact analysis (BIA) classifies its online banking platform as a Tier 1 critical system with a maximum tolerable downtime of 30 minutes, and its internal HR portal as a Tier 3 system with a maximum tolerable downtime of 72 hours. Both systems require patches for a newly disclosed vulnerability. The IT manager has resources to patch only one system this weekend. Based on the BIA classifications, which system should be patched first and why?$EXPL$, $EXPL$["The online banking platform, because its Tier 1 classification and 30-minute maximum tolerable downtime indicate that any vulnerability exposure creates significantly greater business risk", "The HR portal, because internal systems are more frequently targeted by attackers", "Both systems simultaneously by splitting the available resources equally", "Neither system, because patches should wait until both can be addressed in the same maintenance window"]$EXPL$::jsonb, 0, $EXPL$Correct (A): The BIA classification directly informs change prioritization. The online banking platform's Tier 1 status and 30-minute maximum tolerable downtime indicate it supports critical business operations where any compromise would have severe impact. COBIT APO09 and NIST SP 800-40 recommend prioritizing patch deployment based on system criticality and business impact, making the Tier 1 system the clear priority.
Wrong (B): BIA classification, not attack frequency assumptions, should drive prioritization; Tier 1 criticality outweighs speculation about targeting patterns.
Wrong (C): Splitting resources may result in neither system being properly patched and tested, increasing risk to both.
Wrong (D): Delaying patches for known vulnerabilities on a Tier 1 system violates the principle of timely risk mitigation based on system criticality.$EXPL$, 'medium', 2),

-- Q30: hard / L3 — Evaluating change management in cloud-managed services
(5, 'Change Management', $EXPL$Maplewood Accounting migrates its practice management application to a SaaS platform. Three months later, the SaaS vendor deploys an automatic update that changes the report formatting for client invoices, breaking the firm's customized templates. The firm's IT manager had no advance notice of the update and no ability to test it before deployment. The managing partner asks the IT manager how to prevent this from occurring again. Which recommendation MOST effectively addresses this risk within the constraints of a SaaS model?$EXPL$, $EXPL$["Migrate back to an on-premises solution where all changes are controlled internally", "Negotiate contractual provisions requiring advance notification of updates, access to a pre-release testing environment, and defined rollback procedures for changes that affect customized configurations", "Accept vendor updates without controls since SaaS platforms are the vendor's responsibility", "Implement a firewall rule to block automatic updates from the SaaS vendor"]$EXPL$::jsonb, 1, $EXPL$Correct (B): COBIT APO09 (Manage Service Agreements) and NIST SP 800-145 recommend that organizations using SaaS establish contractual provisions addressing change management. These provisions should include advance notification of updates affecting functionality, access to sandbox or pre-release environments for testing, and defined rollback procedures. This extends the organization's change management controls to vendor-managed changes through contractual governance.
Wrong (A): Migrating back to on-premises is disproportionate and sacrifices the benefits of SaaS; the issue can be addressed through contractual and governance controls.
Wrong (C): Accepting vendor updates without controls abdicates the organization's responsibility to manage risk; the firm is still accountable for the integrity of its client-facing outputs.
Wrong (D): Blocking automatic updates from a SaaS vendor is typically not technically feasible since the vendor controls the infrastructure, and it would prevent the firm from receiving security patches and functionality improvements.$EXPL$, 'hard', 3)
;

COMMIT;
