-- Migration: Question generation — TCP batch 16 (30 questions)
-- Date: 2026-03-24
-- Topic: Entity Tax Compliance: NOLs and Consolidated Returns
-- Difficulty: 9E / 15M / 6H
-- Bloom's: L1:6 / L2:10 / L3:9 / L4:5

BEGIN;

INSERT INTO questions (section_id, topic, stem, choices, correct_index, explanation, difficulty, cognitive_level)
VALUES

-- Q1: easy / L1 — Joint and several liability in consolidated groups
(6, 'Entity Tax Compliance: NOLs and Consolidated Returns', $EXPL$What is the liability standard that applies to all members of a consolidated return group regarding the group's federal income tax?$EXPL$, $EXPL$["Joint and several liability", "Proportional liability based on each member's income", "Liability limited to the parent corporation only", "Liability limited to each member's separate tax"]$EXPL$::jsonb, 0, $EXPL$Correct (A): Under Treas. Reg. Section 1.1502-6, each member of a consolidated group is jointly and severally liable for the entire consolidated tax liability. This means the IRS can collect the full tax from any single member. Wrong (B): Liability is not proportional — each member bears full responsibility for the group's tax. Wrong (C): Liability extends to all members, not just the parent corporation. Wrong (D): Filing consolidated eliminates separate tax computation; the group files one return with shared liability.$EXPL$, 'easy', 1),

-- Q2: medium / L2 — Charitable contribution limitation on consolidated basis
(6, 'Entity Tax Compliance: NOLs and Consolidated Returns', $EXPL$Brennan Industries files a consolidated return with its wholly owned subsidiary, Crestwood Corp. Brennan has taxable income of $600,000 and Crestwood has taxable income of $400,000 before charitable contributions. The group made $150,000 in charitable contributions. What is the maximum charitable contribution deduction on the consolidated return?$EXPL$, $EXPL$["$60,000", "$100,000", "$150,000", "$40,000"]$EXPL$::jsonb, 1, $EXPL$Correct (B): Under IRC Section 170(b)(2), a corporation's charitable contribution deduction is limited to 10% of taxable income. For a consolidated group, the 10% limit is applied to consolidated taxable income. Consolidated taxable income is $1,000,000 ($600,000 + $400,000), so the limit is $100,000. Wrong (A): This incorrectly applies 10% only to Brennan's income. Wrong (C): The full $150,000 exceeds the 10% consolidated limit. Wrong (D): This incorrectly applies 10% only to Crestwood's income.$EXPL$, 'medium', 2),

-- Q3: easy / L2 — Capital loss netting across consolidated group
(6, 'Entity Tax Compliance: NOLs and Consolidated Returns', $EXPL$Ridgeway Corp files a consolidated return with its 100%-owned subsidiary, Lakewood Inc. In 2025, Ridgeway has $90,000 of capital gains and Lakewood has $60,000 of capital losses. How are these amounts treated on the consolidated return?$EXPL$, $EXPL$["Each member reports its own capital gains and losses separately", "The capital losses are suspended until Lakewood has its own capital gains", "The group nets them, reporting $30,000 of net capital gains on the consolidated return", "Lakewood's capital losses are disallowed because they exceed its own capital gains"]$EXPL$::jsonb, 2, $EXPL$Correct (C): Under Treas. Reg. Section 1.1502-22, capital gains and losses of all members are netted at the consolidated level. The group reports net capital gains of $30,000 ($90,000 − $60,000). This is a key advantage of consolidated filing. Wrong (A): Consolidated returns aggregate capital items across all members rather than reporting separately. Wrong (B): Capital losses are netted currently against other members' gains, not suspended. Wrong (D): The losses are not disallowed; they offset the group's capital gains.$EXPL$, 'easy', 2),

-- Q4: medium / L2 — Section 1231 netting across consolidated group
(6, 'Entity Tax Compliance: NOLs and Consolidated Returns', $EXPL$Harmon Group files a consolidated return. During 2025, Subsidiary A recognizes a $200,000 Section 1231 gain on sale of equipment, while Subsidiary B recognizes a $275,000 Section 1231 loss on sale of real property. What is the consolidated group's net Section 1231 result?$EXPL$, $EXPL$["$200,000 long-term capital gain and $275,000 ordinary loss", "$275,000 ordinary loss", "$75,000 net long-term capital loss", "$75,000 ordinary loss"]$EXPL$::jsonb, 3, $EXPL$Correct (D): Under Treas. Reg. Section 1.1502-23, Section 1231 gains and losses are netted at the consolidated level. The net result is a $75,000 loss ($200,000 − $275,000). When Section 1231 losses exceed gains, the net loss is characterized as an ordinary loss, fully deductible against other income. Wrong (A): The items are not reported separately; they are netted at the consolidated level. Wrong (B): This ignores the $200,000 gain that offsets part of the loss. Wrong (C): A net Section 1231 loss is treated as ordinary, not capital.$EXPL$, 'medium', 2),

-- Q5: easy / L1 — Consolidated return year-end conformity
(6, 'Entity Tax Compliance: NOLs and Consolidated Returns', $EXPL$What tax year must all members of a consolidated return group use?$EXPL$, $EXPL$["The common parent's tax year", "Each member's independently elected fiscal year", "A calendar year regardless of the parent's year", "The tax year of the member with the most revenue"]$EXPL$::jsonb, 0, $EXPL$Correct (A): Under Treas. Reg. Section 1.1502-76(a), all members of a consolidated group must use the common parent's tax year. A subsidiary joining an existing group must change its tax year to conform to the parent's. Wrong (B): Members cannot retain independent fiscal years; they must conform to the parent. Wrong (C): The group uses the parent's year, which may be a fiscal year rather than a calendar year. Wrong (D): Revenue size has no bearing on tax year selection for consolidated groups.$EXPL$, 'easy', 1),

-- Q6: medium / L3 — Intercompany depreciation triggering deferred gain
(6, 'Entity Tax Compliance: NOLs and Consolidated Returns', $EXPL$Waverly Corp sells a machine with a basis of $100,000 to its fellow consolidated group member, Dalton Inc., for $140,000. Dalton depreciates the machine over 5 years using straight-line. Under Treas. Reg. Section 1.1502-13, how much of Waverly's deferred intercompany gain is recognized in the first full year?$EXPL$, $EXPL$["No gain until Dalton sells to an outsider", "$8,000 per year", "$28,000 per year", "$40,000 in the first year"]$EXPL$::jsonb, 1, $EXPL$Correct (B): Under the matching rule of Treas. Reg. Section 1.1502-13, Waverly's $40,000 deferred gain is recognized as Dalton takes depreciation. Dalton depreciates $140,000 over 5 years ($28,000/year), but a single entity would depreciate only $100,000 over 5 years ($20,000/year). The $8,000 annual difference ($28,000 − $20,000) triggers recognition of $8,000 of Waverly's deferred gain each year. Wrong (A): Gain is triggered by depreciation, not only by external sale. Wrong (C): This is Dalton's total annual depreciation, not the amount of deferred gain recognized. Wrong (D): The entire $40,000 gain is not recognized at once; it is recognized proportionally as depreciation creates a difference.$EXPL$, 'medium', 3),

-- Q7: medium / L3 — SRLY overlap rule with Section 382
(6, 'Entity Tax Compliance: NOLs and Consolidated Returns', $EXPL$Orion Group acquires 100% of Vanguard Corp, which has $500,000 of pre-acquisition NOLs. The acquisition triggers an ownership change under Section 382. Orion's tax advisor notes that both the SRLY rules and Section 382 would otherwise limit Vanguard's NOL usage within the consolidated group. Under Treas. Reg. Section 1.1502-21(g), how do these overlapping limitations interact?$EXPL$, $EXPL$["Both SRLY and Section 382 limits apply cumulatively", "The SRLY rules are waived, and only the Section 382 limitation applies", "The Section 382 limitation is waived, and only the SRLY rules apply", "The group may choose whichever limitation produces the lower restriction"]$EXPL$::jsonb, 1, $EXPL$Correct (B): Under the SRLY overlap rule in Treas. Reg. Section 1.1502-21(g), when a corporation joins a consolidated group in a transaction that also constitutes an ownership change under Section 382, the SRLY rules are turned off and Section 382 serves as the sole limitation. This avoids redundant restrictions. Wrong (A): The regulations specifically prevent cumulative application; only one limitation applies. Wrong (C): This reverses the rule — the SRLY rules are waived, not Section 382. Wrong (D): The overlap rule is mandatory, not elective; the group cannot choose.$EXPL$, 'medium', 3),

-- Q8: medium / L3 — Stock basis decrease for nondeductible expenses
(6, 'Entity Tax Compliance: NOLs and Consolidated Returns', $EXPL$Meridian Corp owns 100% of Beacon Inc., which is included in Meridian's consolidated return. Beacon's stock basis at the beginning of 2025 is $500,000. During 2025, Beacon earns $200,000 of taxable income, pays $40,000 in nondeductible fines and penalties, and distributes $80,000 to Meridian. What is Meridian's adjusted basis in Beacon's stock at year-end?$EXPL$, $EXPL$["$620,000", "$660,000", "$500,000", "$580,000"]$EXPL$::jsonb, 3, $EXPL$Correct (D): Under Treas. Reg. Section 1.1502-32, the parent's stock basis in a subsidiary is adjusted for the subsidiary's items. Basis increases for taxable income (+$200,000) and decreases for nondeductible expenses (−$40,000) and distributions (−$80,000). Adjusted basis = $500,000 + $200,000 − $40,000 − $80,000 = $580,000. Wrong (A): This adds income and subtracts only the distribution, ignoring the nondeductible expense reduction. Wrong (B): This adds income and subtracts only the nondeductible expenses, ignoring the distribution. Wrong (C): This fails to make any adjustments for the year's activity.$EXPL$, 'medium', 3),

-- Q9: medium / L2 — Common parent as agent for the group
(6, 'Entity Tax Compliance: NOLs and Consolidated Returns', $EXPL$Fletcher Holdings files a consolidated return with three wholly owned subsidiaries. The IRS issues a notice of deficiency related to the consolidated return. Under Treas. Reg. Section 1.1502-77, which entity serves as the sole agent for the group in dealings with the IRS regarding the consolidated return?$EXPL$, $EXPL$["The common parent corporation", "Each subsidiary acts independently with the IRS", "The subsidiary that generated the deficiency", "An independent third-party agent appointed by the group"]$EXPL$::jsonb, 0, $EXPL$Correct (A): Under Treas. Reg. Section 1.1502-77, the common parent corporation is the sole agent authorized to act for the group in all procedural and administrative matters with the IRS regarding the consolidated return. This includes receiving notices, filing claims, and executing agreements. Wrong (B): Subsidiaries do not act independently; the parent is the exclusive agent. Wrong (C): The deficiency-generating subsidiary has no special standing; the parent acts for all members. Wrong (D): No third-party agent is appointed; the parent serves this role by regulation.$EXPL$, 'medium', 2),

-- Q10: hard / L4 — Evaluating consolidated vs. separate filing with intercompany services
(6, 'Entity Tax Compliance: NOLs and Consolidated Returns', $EXPL$Pinnacle Corp owns 100% of Summit Inc. and Ridge LLC (taxed as a C corp). Summit provides management services to Ridge for $300,000 annually. Summit has $800,000 of other income and Ridge has $1,200,000 of income before the management fee. Ridge also has $400,000 of capital losses with no capital gains. Summit has $400,000 of capital gains. If the group files a consolidated return, the management fee is eliminated, and capital items are netted across members. If filing separately, each entity reports independently. Evaluate the tax advantage of consolidated filing.$EXPL$, $EXPL$["Consolidated filing saves approximately $84,000 in tax", "Consolidated filing saves approximately $63,000 in tax", "Separate filing produces lower total tax", "Both filing methods produce the same total tax liability"]$EXPL$::jsonb, 0, $EXPL$Correct (A): Under consolidated filing, the $300,000 management fee is eliminated (nets to zero), and Ridge's $400,000 capital losses offset Summit's $400,000 capital gains. Consolidated taxable income = $800,000 + $1,200,000 = $2,000,000. Tax = $420,000. Under separate filing, Summit has $1,100,000 income + $400,000 capital gains = $1,500,000 taxable income; Ridge has $900,000 income, $400,000 capital losses cannot offset ordinary income. Combined tax = $315,000 + $189,000 = $504,000. Difference is $84,000. Wrong (B): This understates the benefit by miscalculating the capital loss netting advantage. Wrong (C): Consolidated filing produces the lower tax due to capital loss netting. Wrong (D): The elimination of intercompany transactions and capital loss netting create a difference.$EXPL$, 'hard', 4),

-- Q11: medium / L3 — Tax-exempt income increasing stock basis
(6, 'Entity Tax Compliance: NOLs and Consolidated Returns', $EXPL$Northfield Corp owns 100% of Clover Inc. in a consolidated group. Clover receives $50,000 of tax-exempt municipal bond interest during 2025 and has no other income or loss. Northfield's basis in Clover stock was $300,000 at the start of the year. Under Treas. Reg. Section 1.1502-32, what is Northfield's adjusted basis in Clover stock at year-end, and why?$EXPL$, $EXPL$["$300,000, because tax-exempt income does not affect stock basis", "Tax-exempt income reduces basis to $250,000", "$350,000, because tax-exempt income increases the parent's stock basis", "$300,000, because only taxable income triggers an adjustment"]$EXPL$::jsonb, 2, $EXPL$Correct (C): Under Treas. Reg. Section 1.1502-32(b)(2), a parent's basis in subsidiary stock is increased by the subsidiary's tax-exempt income. This prevents double taxation when the subsidiary is later sold, as the tax-exempt income is reflected in higher stock basis. Adjusted basis = $300,000 + $50,000 = $350,000. Wrong (A): Tax-exempt income does affect stock basis — it increases it. Wrong (B): Tax-exempt income increases, not decreases, stock basis. Wrong (D): Both taxable and tax-exempt income trigger upward basis adjustments.$EXPL$, 'medium', 3),

-- Q12: medium / L2 — New member must conform to parent's tax year
(6, 'Entity Tax Compliance: NOLs and Consolidated Returns', $EXPL$Apex Holdings uses a June 30 fiscal year-end and files consolidated returns. On October 1, 2025, Apex acquires 100% of Sterling Corp, which has always used a December 31 calendar year-end. Under Treas. Reg. Section 1.1502-76, what must Sterling do regarding its tax year upon joining the group?$EXPL$, $EXPL$["Continue using its December 31 year-end for the first consolidated year", "File a short-period return through September 30 and adopt the June 30 fiscal year", "Retroactively restate its prior returns to a June 30 year-end", "Change its tax year to June 30 beginning the following January 1"]$EXPL$::jsonb, 3, $EXPL$Correct (D): Under Treas. Reg. Section 1.1502-76(a), a new member must adopt the common parent's tax year. Sterling files a short-period separate return for January 1 through September 30, 2025 (the day before joining), and then joins the consolidated return using the parent's June 30 fiscal year going forward. Wrong (A): Sterling cannot retain its own year-end; it must conform to the parent's. Wrong (B): While Sterling files a short period return, the correct treatment is described in choice D with the conformity requirement. Wrong (C): Retroactive restatement of prior returns is not required.$EXPL$, 'medium', 2),

-- Q13: hard / L3 — Section 382 NUBIG increases annual limitation
(6, 'Entity Tax Compliance: NOLs and Consolidated Returns', $EXPL$Keystone Corp undergoes an ownership change under Section 382. Keystone's stock value immediately before the change is $5,000,000 and the long-term tax-exempt rate is 4%, producing an annual Section 382 limitation of $200,000. Keystone has a net unrealized built-in gain (NUBIG) of $800,000. During the first year after the ownership change, Keystone recognizes $350,000 of built-in gains from selling appreciated assets. How does the recognized built-in gain affect the Section 382 limitation for that year?$EXPL$, $EXPL$["The annual limitation increases to $550,000 for that year", "The recognized built-in gain has no effect on the annual limitation", "The annual limitation is permanently increased by $350,000 for all future years", "The recognized built-in gain reduces the available NOL carryforward"]$EXPL$::jsonb, 0, $EXPL$Correct (A): Under IRC Section 382(h), recognized built-in gains (RBIG) during the 5-year recognition period increase the Section 382 limitation for the year recognized. The $350,000 RBIG is added to the base $200,000 limitation, producing a $550,000 limit for that year. This allows the loss corporation to use more of its pre-change NOLs in years with RBIG. Wrong (B): RBIG directly increases the annual limitation — it is not ignored. Wrong (C): The increase applies only to the year the gain is recognized, not permanently. Wrong (D): RBIG increases the limitation rather than reducing the NOL carryforward itself.$EXPL$, 'hard', 3),

-- Q14: easy / L2 — NOL ordering rule (FIFO)
(6, 'Entity Tax Compliance: NOLs and Consolidated Returns', $EXPL$Prescott Corp has NOL carryforwards from three different tax years: $100,000 from 2021, $150,000 from 2022, and $200,000 from 2023. In 2025, Prescott has taxable income of $300,000 before any NOL deduction. In what order must Prescott apply the NOL carryforwards?$EXPL$, $EXPL$["Largest NOL first to maximize the current deduction", "Oldest NOL first: 2021, then 2022, then 2023", "The taxpayer may choose any order", "Most recent NOL first: 2023, then 2022, then 2021"]$EXPL$::jsonb, 1, $EXPL$Correct (B): Under IRC Section 172(b)(2), NOL carryforwards must be applied in chronological order, with the earliest loss used first (FIFO). Prescott must use the 2021 NOL first, then 2022, then 2023. The 80% limit applies to the aggregate deduction ($240,000 max). Wrong (A): Taxpayers cannot choose to apply the largest NOL first; the order is mandatory. Wrong (C): The ordering is mandatory under the statute, not elective. Wrong (D): Most recent first (LIFO) is not permitted; the earliest NOL must be used first.$EXPL$, 'easy', 2),

-- Q15: medium / L3 — Deconsolidation event triggering deferred items
(6, 'Entity Tax Compliance: NOLs and Consolidated Returns', $EXPL$Trident Group files a consolidated return. In 2024, Member A sold land with a basis of $200,000 to Member B for $350,000. The $150,000 intercompany gain was deferred under Treas. Reg. Section 1.1502-13. In 2025, Trident sells all of Member B's stock to an unrelated buyer while Member B still holds the land. What happens to the $150,000 deferred gain?$EXPL$, $EXPL$["The gain remains deferred and transfers to the new owner of Member B", "The gain is permanently eliminated because the land was never sold externally", "$150,000 of gain is accelerated and recognized in 2025", "The gain is allocated between the group and the buyer"]$EXPL$::jsonb, 2, $EXPL$Correct (C): Under the acceleration rule of Treas. Reg. Section 1.1502-13(d), when matching cannot occur because a member leaves the consolidated group, any deferred intercompany gain or loss is triggered immediately. Member B's departure from the group accelerates recognition of the $150,000 deferred gain in 2025. Wrong (A): Deferred gains do not transfer to new owners; they are accelerated upon deconsolidation. Wrong (B): The gain is not eliminated; it must be recognized when matching is no longer possible. Wrong (D): The gain is fully recognized by the selling group, not allocated to the buyer.$EXPL$, 'medium', 3),

-- Q16: medium / L3 — Consolidated group charitable deduction carryover
(6, 'Entity Tax Compliance: NOLs and Consolidated Returns', $EXPL$Zenith Group files a consolidated return with consolidated taxable income of $800,000 in 2025. The group makes $120,000 of charitable contributions during the year. Under IRC Section 170, what is the charitable deduction allowed for 2025, and how is the excess treated?$EXPL$, $EXPL$["$120,000 deduction; no excess", "$80,000 deduction; $40,000 carried forward 5 years", "$80,000 deduction; $40,000 carried back 1 year", "$80,000 deduction; $40,000 is permanently disallowed"]$EXPL$::jsonb, 1, $EXPL$Correct (B): Under IRC Section 170(b)(2), a corporation's charitable deduction is limited to 10% of taxable income. The consolidated group may deduct $80,000 (10% × $800,000). Under Section 170(d)(2), the $40,000 excess is carried forward up to 5 years for use in future tax years. Wrong (A): The full $120,000 exceeds the 10% consolidated limit. Wrong (C): Charitable contribution excess is carried forward, not carried back. Wrong (D): The excess is not permanently disallowed; it may be carried forward for 5 years.$EXPL$, 'medium', 3),

-- Q17: medium / L2 — NOL computation: capital losses cannot increase NOL
(6, 'Entity Tax Compliance: NOLs and Consolidated Returns', $EXPL$Granite Corp has gross income of $400,000, business deductions of $480,000, and a net capital loss of $70,000 in 2025. What is Granite's net operating loss for 2025?$EXPL$, $EXPL$["$80,000", "$150,000", "$70,000", "$10,000"]$EXPL$::jsonb, 0, $EXPL$Correct (A): Under IRC Section 172(d), a corporation's net capital losses cannot create or increase an NOL. The NOL is computed using only the excess of deductions over gross income from operations: $480,000 − $400,000 = $80,000. The $70,000 net capital loss is excluded from the NOL computation. Wrong (B): This incorrectly adds the $70,000 capital loss to the $80,000 operating loss. Wrong (C): This reflects only the capital loss, which cannot constitute an NOL. Wrong (D): This improperly nets the capital loss against the operating loss.$EXPL$, 'medium', 2),

-- Q18: easy / L2 — Estimated tax for consolidated groups
(6, 'Entity Tax Compliance: NOLs and Consolidated Returns', $EXPL$Cascade Holdings files a consolidated return with two wholly owned subsidiaries. For estimated tax purposes, how does the consolidated group make its quarterly estimated tax payments?$EXPL$, $EXPL$["Each subsidiary makes its own estimated tax payments independently", "The common parent makes a single estimated tax payment on behalf of the entire group", "Estimated tax payments are not required for consolidated groups", "Only the subsidiary with the highest income makes the payments"]$EXPL$::jsonb, 1, $EXPL$Correct (B): Under Treas. Reg. Section 1.1502-5, the consolidated group makes a single estimated tax payment through the common parent corporation. The parent computes estimated tax based on consolidated taxable income and remits payments on behalf of all members. Wrong (A): Subsidiaries do not make separate estimated tax payments when included in a consolidated return. Wrong (C): Consolidated groups are still required to make estimated tax payments. Wrong (D): The payment obligation rests with the parent, not a specific subsidiary.$EXPL$, 'easy', 2),

-- Q19: medium / L3 — Investment adjustment with multiple items
(6, 'Entity Tax Compliance: NOLs and Consolidated Returns', $EXPL$Sterling Group owns 100% of Atlas Corp. Atlas's beginning stock basis is $400,000. During 2025, Atlas has $150,000 of taxable income, $20,000 of tax-exempt interest, $30,000 of nondeductible meal expenses, and pays a $50,000 dividend to Sterling. Under Treas. Reg. Section 1.1502-32, what is Sterling's adjusted basis in Atlas stock at year-end?$EXPL$, $EXPL$["$520,000", "$470,000", "$490,000", "$540,000"]$EXPL$::jsonb, 2, $EXPL$Correct (C): Under Treas. Reg. Section 1.1502-32, basis is adjusted for all of the subsidiary's items. Starting basis $400,000 + taxable income $150,000 + tax-exempt income $20,000 − nondeductible expenses $30,000 − distributions $50,000 = $490,000. All four types of adjustments apply. Wrong (A): This omits the deduction for nondeductible expenses. Wrong (B): This omits the increase for tax-exempt income. Wrong (D): This omits both the nondeductible expense and distribution decreases.$EXPL$, 'medium', 3),

-- Q20: hard / L4 — Evaluating Section 382 with NUBIL reducing limitation usefulness
(6, 'Entity Tax Compliance: NOLs and Consolidated Returns', $EXPL$Vanguard Industries is considering acquiring Omega Corp, which has $8,000,000 of NOL carryforwards and assets with a fair market value of $4,500,000 and a tax basis of $6,000,000. The purchase price would be $4,500,000. The long-term tax-exempt rate is 4%, producing a Section 382 annual limitation of $180,000. The $1,500,000 net unrealized built-in loss (NUBIL) will further reduce NOL utilization during the 5-year recognition period. Without the acquisition, Omega projects using $1,000,000 of NOLs annually against its own income. Evaluate the acquisition's impact on NOL utilization.$EXPL$, $EXPL$["The acquisition preserves NOL usage at $1,000,000 annually", "The acquisition improves NOL usage because of the NUBIL benefit", "The acquisition is advisable because the 382 limit exceeds Omega's projected income", "The acquisition restricts annual NOL usage to approximately $180,000, destroying most of the NOL benefit"]$EXPL$::jsonb, 3, $EXPL$Correct (D): Under IRC Section 382, the ownership change limits annual NOL usage to $180,000 (stock value × long-term tax-exempt rate). Additionally, under Section 382(h), the NUBIL means recognized built-in losses during the 5-year period further reduce the effective limitation. Compared to Omega's standalone $1,000,000 annual usage, the acquisition destroys approximately $820,000 per year of NOL benefit. Wrong (A): The 382 limitation drastically reduces annual usage from $1,000,000 to $180,000. Wrong (B): NUBIL reduces, not improves, the effective limitation during the recognition period. Wrong (C): The $180,000 limit is far below Omega's projected $1,000,000 annual income.$EXPL$, 'hard', 4),

-- Q21: hard / L4 — Reverse acquisition in consolidated groups
(6, 'Entity Tax Compliance: NOLs and Consolidated Returns', $EXPL$Small Corp has a market capitalization of $20,000,000, while Large Corp has a market capitalization of $5,000,000. Large Corp acquires 100% of Small Corp by issuing enough new shares that Small Corp's former shareholders own 80% of the combined entity. Under Treas. Reg. Section 1.1502-75(d)(3), this qualifies as a reverse acquisition. What is the primary tax consequence of reverse acquisition treatment?$EXPL$, $EXPL$["Small Corp is treated as the continuing parent and its consolidated return group survives", "Large Corp's consolidated group terminates and a new group is formed", "Both corporations must file separate returns for the year of acquisition", "The entity with the larger NOL carryforward is treated as the surviving group"]$EXPL$::jsonb, 0, $EXPL$Correct (A): Under Treas. Reg. Section 1.1502-75(d)(3), a reverse acquisition occurs when the former shareholders of the acquired corporation (Small Corp) end up owning more than 50% of the acquiring corporation (Large Corp). In this case, Small Corp is treated as the continuing common parent, and its consolidated return group survives. This preserves Small Corp's tax attributes and consolidated group continuity. Wrong (B): In a reverse acquisition, the acquired corporation's group continues rather than terminating. Wrong (C): Separate filing is not required; the surviving group files a consolidated return. Wrong (D): The determination is based on shareholder ownership percentages, not NOL size.$EXPL$, 'hard', 4),

-- Q22: easy / L1 — ELA character on disposition
(6, 'Entity Tax Compliance: NOLs and Consolidated Returns', $EXPL$When a subsidiary with an excess loss account is disposed of, what is the character of the income recognized from the ELA recapture?$EXPL$, $EXPL$["Capital gain", "Ordinary income", "Section 1231 gain", "Tax-exempt income"]$EXPL$::jsonb, 1, $EXPL$Correct (B): Under Treas. Reg. Section 1.1502-19(b), an excess loss account that is triggered upon disposition of a subsidiary's stock is generally treated as ordinary income to the parent. This prevents the parent from converting ordinary deductions into capital gain treatment. Wrong (A): ELA recapture is ordinary income, not capital gain. Wrong (C): Section 1231 treatment does not apply to ELA recapture. Wrong (D): The ELA recapture is fully taxable as ordinary income, not tax-exempt.$EXPL$, 'easy', 1),

-- Q23: medium / L2 — DRD computation in NOL year
(6, 'Entity Tax Compliance: NOLs and Consolidated Returns', $EXPL$Redwood Corp has gross income of $300,000, business deductions of $350,000, and receives $100,000 of dividends from a corporation in which it owns 25% of the stock. The dividends-received deduction (DRD) rate is 65%. In computing Redwood's NOL, how is the DRD treated?$EXPL$, $EXPL$["The DRD is disallowed entirely in an NOL year", "The DRD is limited to 65% of taxable income", "The DRD is computed at the full 65% rate without the taxable income limitation", "The DRD is reduced proportionally based on the ratio of losses to income"]$EXPL$::jsonb, 2, $EXPL$Correct (C): Under IRC Section 172(d)(5), when computing a corporation's NOL, the dividends-received deduction is calculated without regard to the taxable income limitation of Section 246(b). This means Redwood claims the full DRD of $65,000 (65% × $100,000) in computing its NOL. NOL = $300,000 + $100,000 − $350,000 − $65,000 = ($15,000). Wrong (A): The DRD is not disallowed; it is computed at the full rate. Wrong (B): The taxable income limitation on the DRD is specifically removed for NOL computation purposes. Wrong (D): No proportional reduction applies; the full DRD is allowed.$EXPL$, 'medium', 2),

-- Q24: easy / L1 — First-year consent requirement
(6, 'Entity Tax Compliance: NOLs and Consolidated Returns', $EXPL$In the first year a consolidated return is filed, what consent is required from the affiliated group members?$EXPL$, $EXPL$["Only the common parent must consent", "IRS approval is required before the election can be made", "Each subsidiary must file Form 1122 or consent through the consolidated return", "Consent is only required from subsidiaries with taxable income"]$EXPL$::jsonb, 2, $EXPL$Correct (C): Under Treas. Reg. Section 1.1502-75(b), each subsidiary must consent to the initial consolidated return election. Consent is demonstrated by filing Form 1122 (Authorization and Consent of Subsidiary Corporation) or by being included in the first consolidated return. All includible members must participate. Wrong (A): All members must consent, not just the parent corporation. Wrong (B): IRS approval is not required — the election is made by filing the consolidated return. Wrong (D): Consent is required from every subsidiary regardless of whether it has income or losses.$EXPL$, 'easy', 1),

-- Q25: easy / L1 — Includible corporation definition
(6, 'Entity Tax Compliance: NOLs and Consolidated Returns', $EXPL$Which type of entity is classified as an "includible corporation" eligible for membership in an affiliated group under Section 1504?$EXPL$, $EXPL$["A domestic C corporation", "A real estate investment trust (REIT)", "An S corporation", "A tax-exempt organization under Section 501"]$EXPL$::jsonb, 0, $EXPL$Correct (A): Under IRC Section 1504(b), an includible corporation is generally any domestic corporation. However, Section 1504(b) specifically excludes S corporations, REITs, RICs, tax-exempt organizations, and certain insurance companies. A standard domestic C corporation qualifies as an includible corporation. Wrong (B): REITs are specifically excluded from the definition of includible corporation under Section 1504(b)(6). Wrong (C): S corporations are excluded under Section 1504(b)(8). Wrong (D): Tax-exempt organizations are excluded under Section 1504(b)(5).$EXPL$, 'easy', 1),

-- Q26: easy / L1 — Consolidated NOL carryforward indefinite period
(6, 'Entity Tax Compliance: NOLs and Consolidated Returns', $EXPL$When a consolidated group generates a consolidated net operating loss (CNOL) in a post-2017 tax year, for how many years may the CNOL be carried forward?$EXPL$, $EXPL$["20 years", "Indefinitely", "5 years", "10 years"]$EXPL$::jsonb, 1, $EXPL$Correct (B): Under IRC Section 172(b)(1)(A)(ii), as amended by the TCJA, NOLs arising in tax years beginning after December 31, 2017 may be carried forward indefinitely. This applies equally to consolidated NOLs (CNOLs) generated by the consolidated group. Wrong (A): The 20-year carryforward period was the pre-TCJA rule for NOLs arising before 2018. Wrong (C): Five years is not a standard NOL carryforward period under current law. Wrong (D): Ten years is not the applicable carryforward period for post-TCJA NOLs.$EXPL$, 'easy', 1),

-- Q27: hard / L4 — Multi-year Section 382 limitation with unused limitation carryforward
(6, 'Entity Tax Compliance: NOLs and Consolidated Returns', $EXPL$Phoenix Corp undergoes an ownership change with a Section 382 annual limitation of $150,000. Phoenix has $2,000,000 of pre-change NOLs. In Year 1 after the change, Phoenix has taxable income of $80,000 (before NOL deduction). In Year 2, Phoenix has taxable income of $300,000. Under IRC Section 382(b)(2), unused Section 382 limitation carries forward. What is the maximum NOL deduction Phoenix may claim in Year 2?$EXPL$, $EXPL$["$150,000", "$220,000", "$240,000", "$300,000"]$EXPL$::jsonb, 1, $EXPL$Correct (B): Under IRC Section 382(b)(2), any unused portion of the annual Section 382 limitation carries forward. In Year 1, the $150,000 limit exceeds the $80,000 of taxable income, so only $80,000 of NOL is used and $70,000 of unused limitation carries to Year 2. Year 2 Section 382 limit = $150,000 + $70,000 = $220,000. The 80% limitation under Section 172(a)(2) allows up to $240,000 (80% × $300,000). The binding constraint is the Section 382 limit of $220,000. Wrong (A): This ignores the $70,000 carryforward of unused limitation from Year 1. Wrong (C): This is the 80% limitation, but the Section 382 limit of $220,000 is more restrictive. Wrong (D): This exceeds both the Section 382 and 80% limitations.$EXPL$, 'hard', 4),

-- Q28: medium / L3 — Intercompany loss on depreciable property with basis adjustment
(6, 'Entity Tax Compliance: NOLs and Consolidated Returns', $EXPL$In a consolidated group, Parent Corp sells a building with a basis of $500,000 to Subsidiary Corp for $400,000. Subsidiary uses the building and depreciates it over 10 years using straight-line. Under the matching rule of Treas. Reg. Section 1.1502-13, how is Parent's $100,000 deferred intercompany loss recognized over time?$EXPL$, $EXPL$["The $100,000 loss is recognized immediately", "The loss is permanently disallowed under related-party rules", "The loss is never recognized because intercompany losses are eliminated", "$10,000 of loss is recognized annually as Subsidiary takes depreciation"]$EXPL$::jsonb, 3, $EXPL$Correct (D): Under the matching rule of Treas. Reg. Section 1.1502-13, the deferred loss is recognized to produce the same result as if the members were divisions of a single entity. Subsidiary depreciates $400,000 over 10 years ($40,000/year), but a single entity would depreciate $500,000 over 10 years ($50,000/year). The $10,000 annual difference triggers recognition of $10,000 of Parent's deferred loss each year. Wrong (A): The loss is deferred, not immediately recognized, under intercompany transaction rules. Wrong (B): The loss is deferred, not permanently disallowed. Related-party rules under Section 267 do not apply to consolidated group intercompany transactions governed by Reg. 1.1502-13. Wrong (C): The loss is recognized over time through the matching rule, not permanently eliminated.$EXPL$, 'medium', 3),

-- Q29: medium / L2 — Pre-TCJA vs post-TCJA NOL ordering when both exist
(6, 'Entity Tax Compliance: NOLs and Consolidated Returns', $EXPL$Magellan Corp has two NOL carryforwards: $200,000 from 2017 (pre-TCJA) and $300,000 from 2022 (post-TCJA). In 2025, Magellan has taxable income of $400,000 before any NOL deduction. What is Magellan's taxable income after applying both NOLs?$EXPL$, $EXPL$["$0 taxable income", "$40,000 taxable income", "$200,000 taxable income", "$100,000 taxable income"]$EXPL$::jsonb, 1, $EXPL$Correct (B): Under IRC Section 172, NOLs are applied chronologically. The 2017 pre-TCJA NOL ($200,000) is applied first and can offset 100% of taxable income (no 80% limitation for pre-2018 NOLs). Remaining income = $400,000 − $200,000 = $200,000. The 2022 post-TCJA NOL is then limited to 80% of the remaining taxable income: 80% × $200,000 = $160,000. Final taxable income = $200,000 − $160,000 = $40,000. Wrong (A): Taxable income cannot be reduced to zero because the post-TCJA NOL is limited to 80% of remaining income. Wrong (C): This only accounts for the pre-TCJA NOL and ignores the post-TCJA deduction entirely. Wrong (D): This miscalculates the 80% limitation on the post-TCJA NOL.$EXPL$, 'medium', 2),

-- Q30: hard / L4 — Dual consolidated loss limitation
(6, 'Entity Tax Compliance: NOLs and Consolidated Returns', $EXPL$Atlas Corp, a U.S. parent, owns 100% of a foreign branch that generates a $500,000 loss in 2025. Atlas wants to use this loss on its U.S. consolidated return and also deduct the same loss on the foreign country's tax return. Under Section 1503(d), what is the dual consolidated loss rule's effect?$EXPL$, $EXPL$["The loss may be freely deducted on both returns without limitation", "The loss may only be used on the U.S. return unless a domestic use agreement is filed", "The loss must be split equally between the U.S. and foreign returns", "The loss is automatically suspended for 5 years"]$EXPL$::jsonb, 1, $EXPL$Correct (B): Under IRC Section 1503(d), a dual consolidated loss — a loss that could be used to offset income in both the U.S. and a foreign jurisdiction — generally cannot be used on the U.S. consolidated return. However, the taxpayer may file a domestic use agreement certifying the loss will not be used to offset foreign income, thereby preserving the U.S. deduction. If the loss is later used abroad, recapture applies. Wrong (A): Section 1503(d) specifically prohibits double use of the same loss in two jurisdictions. Wrong (C): There is no equal-split rule; the loss must be used in one jurisdiction or the other. Wrong (D): The loss is not automatically suspended for a fixed period; it is restricted unless a domestic use agreement is filed.$EXPL$, 'hard', 4)
;

COMMIT;
