-- Migration: Question generation — TCP batch 15 (30 questions)
-- Date: 2026-03-24
-- Topic: Entity Formation and Restructuring
-- Difficulty: 9E / 15M / 6H
-- Bloom's: L1:6 / L2:10 / L3:9 / L4:5

BEGIN;

INSERT INTO questions (section_id, topic, stem, choices, correct_index, explanation, difficulty, cognitive_level)
VALUES

-- Q1: easy / L2 — Section 355(e) anti-Morris Trust rule
(6, 'Entity Formation and Restructuring', $EXPL$Stratton Corp spins off its logistics subsidiary to Stratton shareholders under Section 355. Within 18 months after the spin-off, an unrelated acquirer purchases 60% of the logistics subsidiary stock. Under Section 355(e), what is the consequence to Stratton Corp?$EXPL$, $EXPL$["Stratton recognizes gain on the distribution of the logistics subsidiary stock as if it had been sold at fair market value", "The spin-off is retroactively disqualified and all shareholders must amend their returns", "No consequence because Section 355(e) applies only to split-offs, not spin-offs", "Stratton must recapture the tax benefit by paying a 20% excise tax on the subsidiary value"]$EXPL$::jsonb, 0, $EXPL$Correct (A): Section 355(e) provides that if a Section 355 distribution is part of a plan or series of related transactions in which one or more persons acquire a 50%-or-greater interest in the distributing or controlled corporation within two years, the distributing corporation must recognize gain as if the stock were sold at FMV. The 60% acquisition within 18 months triggers this rule.
Wrong (B): Section 355(e) imposes gain recognition at the corporate level but does not retroactively disqualify the tax-free treatment for shareholders.
Wrong (C): Section 355(e) applies to all forms of Section 355 distributions, including spin-offs, split-offs, and split-ups.
Wrong (D): Section 355(e) triggers gain recognition under normal tax principles, not an excise tax mechanism.$EXPL$, 'easy', 2),

-- Q2: hard / L3 — Section 354(a)(2) securities boot in reorganization
(6, 'Entity Formation and Restructuring', $EXPL$In a qualifying Type A reorganization, shareholder Novak surrenders Target Corp stock (basis $100,000) and Target Corp bonds with a principal amount of $20,000 (basis $18,000). Novak receives Acquiring Corp stock worth $160,000 and Acquiring Corp bonds with a principal amount of $50,000. Under Section 354(a)(2), what amount is treated as boot to Novak?$EXPL$, $EXPL$["$50,000 because all securities received are treated as boot", "$30,000 representing the excess of securities received over securities surrendered", "$20,000 representing the fair market value of the securities surrendered", "$0 because securities received in a reorganization are never boot"]$EXPL$::jsonb, 1, $EXPL$Correct (B): Section 354(a)(2)(A) treats securities received in a reorganization as boot to the extent the principal amount of securities received ($50,000) exceeds the principal amount of securities surrendered ($20,000). The excess principal of $30,000 is treated as other property (boot) subject to gain recognition under Section 356.
Wrong (A): Securities are not entirely boot; only the excess principal amount over securities surrendered is treated as boot under Section 354(a)(2).
Wrong (C): The boot amount is measured by comparing principal amounts received versus surrendered, not by the FMV of the securities surrendered.
Wrong (D): Securities received in excess of the principal amount surrendered are treated as boot; the nonrecognition rule for securities is limited under Section 354(a)(2).$EXPL$, 'hard', 3),

-- Q3: medium / L2 — Section 368(a)(2)(C) post-reorganization drop-down
(6, 'Entity Formation and Restructuring', $EXPL$Trident Corp acquires all assets of Reef Corp in a qualifying Type A statutory merger. Immediately after the merger, Trident transfers the former Reef assets to its wholly owned subsidiary, Neptune LLC. Under Section 368(a)(2)(C), what is the effect of this drop-down on the reorganization?$EXPL$, $EXPL$["The drop-down disqualifies the Type A reorganization retroactively", "The drop-down converts the transaction into a taxable asset purchase", "The drop-down does not disqualify the reorganization because Section 368(a)(2)(C) permits a transferee corporation to transfer acquired assets to a controlled subsidiary", "The drop-down is permitted only if Neptune LLC was in existence for at least one year"]$EXPL$::jsonb, 2, $EXPL$Correct (C): Section 368(a)(2)(C) specifically permits the acquiring corporation in a reorganization to transfer part or all of the acquired assets to a controlled subsidiary without disqualifying the reorganization. This drop-down provision facilitates operational flexibility while preserving tax-free treatment.
Wrong (A): The drop-down is expressly authorized by Section 368(a)(2)(C) and does not disqualify the reorganization.
Wrong (B): The statutory provision ensures the transaction retains its reorganization character despite the subsequent asset transfer to a subsidiary.
Wrong (D): There is no minimum existence period for the subsidiary receiving the dropped-down assets under Section 368(a)(2)(C).$EXPL$, 'medium', 2),

-- Q4: easy / L1 — Section 1032 issuing corporation nonrecognition
(6, 'Entity Formation and Restructuring', $EXPL$Under Section 1032, when a corporation issues its own stock in exchange for property, the issuing corporation:$EXPL$, $EXPL$["Recognizes gain to the extent the property FMV exceeds the stock par value", "Recognizes gain or loss measured by the difference between FMV of property received and stock basis", "Must report the transaction as a deemed sale of treasury shares", "Recognizes no gain or loss regardless of the value of property received"]$EXPL$::jsonb, 3, $EXPL$Correct (D): Section 1032(a) provides that no gain or loss is recognized by a corporation on the receipt of money or other property in exchange for its own stock, including treasury stock. This ensures corporations are not taxed on capital-raising transactions.
Wrong (A): Par value is irrelevant to Section 1032; the issuing corporation recognizes no gain regardless of the relationship between FMV and par value.
Wrong (B): There is no gain or loss computation for the issuing corporation; Section 1032 provides complete nonrecognition.
Wrong (C): Section 1032 applies to both newly issued shares and treasury stock; neither triggers gain or loss recognition to the issuing corporation.$EXPL$, 'easy', 1),

-- Q5: medium / L2 — Section 357(a) liability assumption in reorganization
(6, 'Entity Formation and Restructuring', $EXPL$In a qualifying Type C reorganization, Willow Corp transfers all of its assets to Aspen Corp in exchange for Aspen voting stock. Aspen also assumes $3 million of Willow's liabilities as part of the transaction. Under Section 357(a), how is the liability assumption treated for purposes of the reorganization?$EXPL$, $EXPL$["The liability assumption is not treated as boot or other property received by the transferor, and does not trigger gain recognition", "The liability assumption is treated as cash boot equal to $3 million", "The liability assumption triggers gain equal to the excess over Willow's aggregate asset basis", "The liability assumption disqualifies the transaction from Type C treatment"]$EXPL$::jsonb, 0, $EXPL$Correct (A): Section 357(a) provides that if, as part of a reorganization exchange, the acquiring corporation assumes liabilities of the transferor, the assumption is not treated as money or other property received by the transferor. This prevents the liability assumption alone from triggering gain recognition.
Wrong (B): Section 357(a) specifically excludes liability assumptions from boot treatment in qualifying reorganizations, unlike the treatment of actual cash or non-stock property.
Wrong (C): The Section 357(c) excess-liabilities-over-basis rule applies to Section 351 formations, not to reorganization exchanges under Section 361.
Wrong (D): Liability assumptions do not disqualify Type C reorganizations; Section 357(a) accommodates them without affecting qualification.$EXPL$, 'medium', 2),

-- Q6: medium / L2 — Section 382 testing period
(6, 'Entity Formation and Restructuring', $EXPL$Drake Holdings is evaluating whether an ownership change has occurred under Section 382. Over the past four years, various 5-percent shareholders have increased their ownership positions. Under Section 382(i), what is the standard testing period used to measure whether ownership shifts exceed the 50-percentage-point threshold?$EXPL$, $EXPL$["One year ending on the testing date", "Three years ending on the testing date", "Five years ending on the testing date", "The entire period since the corporation was formed"]$EXPL$::jsonb, 1, $EXPL$Correct (B): Section 382(i) provides that the testing period is generally the three-year period ending on the testing date (or the date the loss corporation was formed, if shorter). Ownership shifts by 5-percent shareholders are measured over this rolling three-year window.
Wrong (A): A one-year testing period would be too short and could miss cumulative shifts that trigger an ownership change.
Wrong (C): Five years exceeds the statutory testing period; Section 382(i) specifies three years.
Wrong (D): The testing period is limited to three years, not the corporation's entire existence; only recent ownership shifts are measured.$EXPL$, 'medium', 2),

-- Q7: hard / L4 — Morris Trust transaction structure evaluation
(6, 'Entity Formation and Restructuring', $EXPL$Silverline Corp wants to sell its pharmaceutical division to BuyerCo but retain its technology division. Silverline's tax advisor proposes a Morris Trust structure: Silverline spins off the technology division to its shareholders under Section 355, then BuyerCo merges with Silverline (which retains only the pharmaceutical division) in a Type A reorganization. However, BuyerCo is substantially larger than Silverline. What is the primary risk to this structure?$EXPL$, $EXPL$["The Type A merger will fail the continuity of interest requirement", "The step transaction doctrine will collapse the spin-off and merger into a taxable asset sale", "Section 355(e) will require Silverline to recognize gain on the spin-off because the merger results in former Silverline shareholders owning less than 50% of the combined entity", "Section 269 will disallow BuyerCo's use of Silverline's operating losses"]$EXPL$::jsonb, 2, $EXPL$Correct (C): Section 355(e), the anti-Morris Trust provision, triggers gain recognition by the distributing corporation when a Section 355 distribution is part of a plan involving a 50%-or-greater change in ownership. Because BuyerCo is substantially larger, former Silverline shareholders will own less than 50% of the post-merger entity, causing Silverline to recognize gain on the spin-off of the technology division.
Wrong (A): The Type A merger can satisfy continuity of interest if former Silverline shareholders receive sufficient BuyerCo stock; the issue is Section 355(e), not COI.
Wrong (B): The step transaction doctrine does not automatically collapse a properly structured Morris Trust; the specific risk is the statutory anti-abuse rule in Section 355(e).
Wrong (D): Section 269 addresses acquisitions made to secure tax benefits like NOLs; it does not apply to the spin-off/merger structure described here.$EXPL$, 'hard', 4),

-- Q8: medium / L3 — Section 384 preacquisition loss limitation
(6, 'Entity Formation and Restructuring', $EXPL$Falcon Corp acquires 100% of the stock of Sparrow Inc. in a Type B reorganization. Sparrow has $2 million in NOL carryforwards. After the acquisition, Falcon transfers an appreciated asset (basis $500,000, FMV $1.5 million) to Sparrow, which sells it for $1.5 million. Sparrow attempts to offset the $1 million built-in gain with its pre-acquisition NOLs. Under Section 384, is this offset permitted?$EXPL$, $EXPL$["Yes, because Sparrow's NOLs can offset any income earned after the acquisition date", "Yes, because Section 384 applies only to net operating losses of the acquiring corporation", "No, because Section 384 was repealed by TCJA and no longer limits NOL usage", "No, because Section 384 prohibits a loss corporation from using preacquisition losses to offset built-in gains in assets acquired from the gain corporation"]$EXPL$::jsonb, 3, $EXPL$Correct (D): Section 384 prevents the use of preacquisition losses of one corporation to offset recognized built-in gains of another corporation following a corporate acquisition. Sparrow's pre-acquisition NOLs cannot shelter the $1 million gain from Falcon's appreciated asset that was contributed post-acquisition, as this is exactly the type of gain trafficking Section 384 targets.
Wrong (A): Section 384 specifically restricts the use of preacquisition NOLs against built-in gains from the other party's assets, regardless of when the gain is recognized.
Wrong (B): Section 384 applies to losses of both the acquiring and acquired corporations; it is not limited to the acquirer's losses.
Wrong (C): Section 384 remains in effect and was not repealed by the Tax Cuts and Jobs Act.$EXPL$, 'medium', 3),

-- Q9: easy / L1 — Party to a reorganization definition
(6, 'Entity Formation and Restructuring', $EXPL$Under Section 368(b), which corporations are considered "a party to a reorganization" in a Type A statutory merger?$EXPL$, $EXPL$["Both the acquiring corporation and the target corporation that are parties to the merger", "Only the surviving corporation in the merger", "Only the corporation whose shareholders receive stock", "All corporations that are members of the same controlled group"]$EXPL$::jsonb, 0, $EXPL$Correct (A): Section 368(b) defines a party to a reorganization to include both corporations resulting from, or parties to, the reorganization. In a Type A merger, both the acquiring (surviving) corporation and the target (merging) corporation are parties to the reorganization, which is essential for applying the nonrecognition provisions of Sections 354 and 361.
Wrong (B): Both the surviving and merging corporations are parties; limiting the definition to only the survivor would exclude shareholders of the target from nonrecognition treatment.
Wrong (C): The definition encompasses both corporations in the merger, not just the one whose shareholders receive stock.
Wrong (D): Controlled group membership is not the test; the corporations must be directly involved in the reorganization transaction.$EXPL$, 'easy', 1),

-- Q10: medium / L3 — Recapitalization Type E bond-for-stock with excess securities
(6, 'Entity Formation and Restructuring', $EXPL$Northgate Corp recapitalizes by exchanging outstanding common stock held by its shareholders for new Northgate bonds with a principal amount of $5 million and Northgate common stock worth $3 million. Each shareholder surrenders stock with basis of $4 million for bonds (principal $5M, FMV $5M) plus stock worth $3M. Under Section 354 in this Type E recapitalization, how are the bonds treated?$EXPL$, $EXPL$["The bonds are fully tax-free because all consideration received in a recapitalization qualifies for nonrecognition", "The bonds are treated as boot under Section 354(a)(2) because securities received in exchange for stock constitute excess securities, triggering gain recognition under Section 356", "The bonds are treated as ordinary income because they represent compensation for surrendered equity", "The bonds are taxable only if their FMV exceeds the basis of the stock surrendered"]$EXPL$::jsonb, 1, $EXPL$Correct (B): Under Section 354(a)(2), when a shareholder receives securities (bonds) in a reorganization but does not surrender securities, the full principal amount of the securities received is treated as boot. Since the shareholders surrendered only stock (not securities), the $5 million in bonds is excess securities treated as boot, and gain is recognized under Section 356 to the extent of the lesser of realized gain or boot.
Wrong (A): Securities received in excess of securities surrendered are not tax-free; Section 354(a)(2) specifically treats them as boot.
Wrong (C): The boot is taxed as gain from the exchange under Section 356 (capital gain or dividend), not as ordinary compensation income.
Wrong (D): The boot treatment applies regardless of whether FMV exceeds basis; the securities are boot because no securities were surrendered in exchange.$EXPL$, 'medium', 3),

-- Q11: easy / L1 — Section 355 distribution requirement
(6, 'Entity Formation and Restructuring', $EXPL$Under Section 355(a)(1)(D), the distributing corporation must distribute stock of the controlled corporation representing at least what minimum percentage of voting power?$EXPL$, $EXPL$["50% of the total voting power of the controlled corporation", "Two-thirds of each class of controlled corporation stock", "80% of the total voting power and 80% of each class of nonvoting stock of the controlled corporation", "100% of each class of controlled corporation stock without exception"]$EXPL$::jsonb, 2, $EXPL$Correct (C): Section 355(a)(1)(D) requires that the distributing corporation distribute stock constituting control of the controlled corporation as defined in Section 368(c) — at least 80% of total voting power and 80% of each class of nonvoting stock. The distributing corporation may retain stock only if it establishes that the retention is not part of a tax avoidance plan.
Wrong (A): The 50% threshold is insufficient; Section 355 requires distribution of Section 368(c) control, which is 80% on both prongs.
Wrong (B): There is no two-thirds requirement in Section 355; the standard is the 80% control test of Section 368(c).
Wrong (D): Distribution of 100% is not required; the distributing corporation may retain up to 20% if it demonstrates no tax avoidance purpose.$EXPL$, 'easy', 1),

-- Q12: medium / L2 — Net value requirement in reorganization
(6, 'Entity Formation and Restructuring', $EXPL$Redleaf Corp proposes to merge into Magnolia Corp under state law. Redleaf's liabilities ($8 million) exceed the fair market value of its assets ($6 million), giving it negative net equity. Magnolia will issue its voting stock to Redleaf shareholders. Tax counsel advises that the reorganization may fail. Under the net value requirement, why might this transaction not qualify?$EXPL$, $EXPL$["Because the Type A reorganization requires the target to have at least $1 million in net equity", "Because Redleaf's negative net worth requires a Section 338 election instead", "Because the acquiring corporation must receive a meaningful ownership interest in the target stock", "Because the target must transfer net value to the acquiring corporation for the transaction to qualify as a reorganization, and a corporation with liabilities exceeding assets transfers no net value"]$EXPL$::jsonb, 3, $EXPL$Correct (D): The IRS and courts require that a target corporation in a reorganization transfer net value — meaning assets with FMV exceeding liabilities — to the acquiring corporation. When liabilities exceed asset FMV, the target transfers no economic value, undermining the premise that the acquiring corporation is obtaining something of worth. This judicially developed requirement can disqualify the reorganization.
Wrong (A): There is no specific dollar threshold for net equity; the requirement is simply that net value be transferred to the acquirer.
Wrong (B): Section 338 elections relate to stock purchases, not mergers, and do not address the net value issue.
Wrong (C): The net value requirement focuses on the target transferring value to the acquirer, not on the acquirer obtaining ownership of target stock.$EXPL$, 'medium', 2),

-- Q13: easy / L1 — Type A reorganization flexibility
(6, 'Entity Formation and Restructuring', $EXPL$Which characteristic distinguishes a Type A reorganization from a Type B and Type C reorganization regarding the form of consideration?$EXPL$, $EXPL$["A Type A reorganization has no statutory limitation on the type or amount of non-stock consideration that may be used", "A Type A reorganization requires at least 90% stock consideration", "A Type A reorganization must use only cash and short-term notes", "A Type A reorganization prohibits assumption of target liabilities"]$EXPL$::jsonb, 0, $EXPL$Correct (A): Unlike Type B (solely for voting stock) and Type C (substantially solely for voting stock), a Type A reorganization has no statutory boot limitation. The only constraint on consideration is the judicial continuity of interest doctrine, which generally requires that a meaningful portion (historically interpreted as approximately 40-50%) be in the form of equity.
Wrong (B): There is no 90% stock requirement for Type A reorganizations; the continuity of interest standard is less restrictive than this.
Wrong (C): A Type A reorganization permits stock, cash, and other property as consideration; it is not limited to cash and notes.
Wrong (D): The assumption of target liabilities is common in Type A mergers and does not affect qualification.$EXPL$, 'easy', 1),

-- Q14: medium / L3 — Section 355(d) disqualified distribution
(6, 'Entity Formation and Restructuring', $EXPL$Keystone Corp purchases 60% of the stock of Granite Corp for cash on the open market. Three years later, Granite Corp distributes the stock of its controlled subsidiary, Marble Inc., to all shareholders under Section 355. Keystone received 60% of the Marble stock. Under Section 355(d), is Granite required to recognize gain on the distribution of Marble stock attributable to Keystone?$EXPL$, $EXPL$["No, because Section 355(d) applies only to purchases within two years of the distribution", "Yes, because Section 355(d) treats the distribution as a sale by Granite to the extent any distributee shareholder holds disqualified stock acquired by purchase within five years", "No, because Keystone acquired its shares on the open market rather than in a private transaction", "Yes, but only if Keystone acquired more than 80% of Granite stock"]$EXPL$::jsonb, 1, $EXPL$Correct (B): Section 355(d) provides that if, immediately after a Section 355 distribution, any person holds disqualified stock in the distributing or controlled corporation that was acquired by purchase within the five-year period before the distribution, the distributing corporation must recognize gain as if it sold the stock. Keystone's purchase of 60% (exceeding the 50% threshold) three years before the distribution falls within the five-year lookback window.
Wrong (A): The lookback period under Section 355(d) is five years, not two years; Keystone's three-year-old purchase is within the window.
Wrong (C): Section 355(d) applies to stock acquired by purchase regardless of whether the acquisition was on the open market or in a private transaction.
Wrong (D): The threshold under Section 355(d) is 50% or more, not 80%; Keystone's 60% stake exceeds this threshold.$EXPL$, 'medium', 3),

-- Q15: medium / L3 — Recapitalization preferred-for-common exchange
(6, 'Entity Formation and Restructuring', $EXPL$Thornhill Corp has outstanding preferred stock held by its founder (basis $200,000, FMV $500,000). In a Type E recapitalization, the founder exchanges all preferred stock for newly issued common stock worth $500,000. Under Section 354, the founder recognizes no gain on the exchange. However, the IRS may scrutinize this transaction for potential application of which anti-abuse provision?$EXPL$, $EXPL$["Section 382, limiting the use of NOL carryforwards after the recapitalization", "Section 269, disallowing deductions if the recapitalization was motivated by tax avoidance", "Section 306, which may taint the common stock received as Section 306 stock if the exchange has the effect of a stock dividend", "Section 357(b), treating assumed liabilities as boot due to tax avoidance"]$EXPL$::jsonb, 2, $EXPL$Correct (C): Section 306 is a potential concern when preferred stock is exchanged for common stock in a recapitalization. If the preferred stock being surrendered was itself Section 306 stock (i.e., originally received as a nontaxable stock dividend), the common stock received could inherit the Section 306 taint. Section 306 prevents shareholders from converting ordinary dividend income into capital gain through stock restructurings.
Wrong (A): Section 382 addresses NOL limitations after ownership changes, which is unrelated to a single-shareholder preferred-for-common recapitalization.
Wrong (B): Section 269 targets acquisitions made to secure tax benefits; a recapitalization of existing equity does not involve an acquisition of control.
Wrong (D): Section 357(b) applies to liability assumptions in formation and reorganization exchanges, not to stock-for-stock recapitalizations.$EXPL$, 'medium', 3),

-- Q16: hard / L4 — Section 382(l) built-in gain/loss adjustments
(6, 'Entity Formation and Restructuring', $EXPL$Cardinal Corp has $8 million in NOL carryforwards and experiences an ownership change. The Section 382 annual limitation is $500,000. At the ownership change date, Cardinal holds assets with aggregate FMV of $15 million and aggregate adjusted basis of $20 million, creating a net unrealized built-in loss (NUBIL) of $5 million. Under Section 382(h), how does the NUBIL affect Cardinal's annual limitation?$EXPL$, $EXPL$["The NUBIL has no effect because only net unrealized built-in gains affect the Section 382 limitation", "The NUBIL increases the annual limitation from $500,000 to $1 million for the first five years", "The NUBIL reduces the annual limitation from $500,000 to $250,000 for a five-year recognition period", "Built-in losses recognized during the five-year recognition period are treated as pre-change losses subject to the Section 382 annual limitation, further constraining deductions beyond the NOL carryforwards"]$EXPL$::jsonb, 3, $EXPL$Correct (D): Under Section 382(h)(1)(B), if a loss corporation has a NUBIL at the ownership change date, any built-in losses recognized during the five-year recognition period are treated as pre-change losses subject to the Section 382 annual limitation. This means the $500,000 annual cap must absorb both the NOL carryforwards and any recognized built-in losses, further constraining the corporation's total deductions.
Wrong (A): Both NUBIG and NUBIL affect the Section 382 analysis; NUBIL subjects recognized built-in losses to the annual limitation.
Wrong (B): A NUBIL does not increase the annual limitation; that treatment applies to net unrealized built-in gains (NUBIG), which can increase the limit.
Wrong (C): The NUBIL does not mathematically reduce the stated annual limitation amount; rather, recognized built-in losses consume a portion of the existing $500,000 cap alongside the NOL carryforwards.$EXPL$, 'hard', 4),

-- Q17: medium / L2 — Dissenting shareholders in reorganization
(6, 'Entity Formation and Restructuring', $EXPL$In a qualifying Type A reorganization between Eclipse Corp and Luna Corp, 95% of Luna shareholders exchange their stock for Eclipse stock. The remaining 5% of Luna shareholders exercise appraisal rights under state law and receive cash for their shares. Under the tax rules, how are the dissenting shareholders treated?$EXPL$, $EXPL$["The dissenting shareholders are treated as having sold their stock in a taxable exchange, recognizing capital gain or loss", "The dissenting shareholders receive tax-free treatment because the underlying reorganization qualifies", "The dissenting shareholders must defer gain under Section 354 until they sell the cash received", "The cash payments to dissenting shareholders disqualify the entire reorganization"]$EXPL$::jsonb, 0, $EXPL$Correct (A): Dissenting shareholders who exercise appraisal rights and receive solely cash are not participating in the reorganization exchange. Their receipt of cash in redemption of their shares is treated as a separate taxable transaction — a sale or exchange of stock — resulting in capital gain or loss. Section 354 nonrecognition does not apply to them.
Wrong (B): Tax-free treatment under Section 354 requires receiving stock of a party to the reorganization; cash-only consideration to dissenters is a taxable event.
Wrong (C): Cash received in a stock redemption is immediately taxable; there is no deferral mechanism for dissenting shareholders.
Wrong (D): The exercise of appraisal rights by a small minority of shareholders does not disqualify the reorganization for the participating shareholders.$EXPL$, 'medium', 2),

-- Q18: medium / L3 — Triangular Type B using parent stock
(6, 'Entity Formation and Restructuring', $EXPL$Olympus Corp wants its subsidiary, Atlas Sub, to acquire all outstanding stock of Titan Corp. Olympus provides its own voting stock to Atlas Sub, which uses it as the sole consideration to acquire Titan's stock from Titan shareholders. After the acquisition, Titan becomes a subsidiary of Atlas Sub. Under the reorganization rules, can this qualify as a Type B reorganization?$EXPL$, $EXPL$["No, because the acquiring subsidiary must use its own stock, not the parent's stock", "Yes, because Section 368(a)(1)(B) permits a subsidiary to use its parent corporation's voting stock to acquire control of a target in a triangular Type B reorganization", "No, because triangular structures are only permitted for Type A reorganizations", "Yes, but only if Olympus also contributes cash to Atlas Sub equal to at least 20% of the acquisition cost"]$EXPL$::jsonb, 1, $EXPL$Correct (B): The parenthetical clause in Section 368(a)(1)(B) permits the use of voting stock of a corporation in control of the acquiring corporation (i.e., the parent's stock) to acquire the target stock. This triangular Type B reorganization allows the parent to maintain a subsidiary structure while using its own equity as acquisition currency.
Wrong (A): The statute expressly permits the use of the parent's voting stock in lieu of the subsidiary's own stock for Type B acquisitions.
Wrong (C): Triangular structures are permitted for Type A (Sections 368(a)(2)(D) and (E)), Type B (parenthetical language), and Type C (parenthetical language) reorganizations.
Wrong (D): The solely-for-voting-stock requirement prohibits any cash consideration in a Type B reorganization, whether direct or triangular.$EXPL$, 'medium', 3),

-- Q19: easy / L1 — Type A consolidation (two corps into new entity)
(6, 'Entity Formation and Restructuring', $EXPL$Under Section 368(a)(1)(A), a consolidation occurs when:$EXPL$, $EXPL$["One corporation acquires the stock of another corporation for cash", "A single corporation changes its state of incorporation", "Two or more corporations combine into a newly formed corporation, with the original corporations ceasing to exist", "A corporation distributes a subsidiary's stock to its shareholders"]$EXPL$::jsonb, 2, $EXPL$Correct (C): A consolidation under Section 368(a)(1)(A) occurs when two or more existing corporations transfer their assets to a newly created corporation and then dissolve. Unlike a merger where one corporation survives, in a consolidation all predecessor corporations cease to exist and a new entity continues the combined operations.
Wrong (A): Acquiring stock for cash describes a taxable stock purchase, not a tax-free consolidation under Section 368(a)(1)(A).
Wrong (B): A mere change in state of incorporation is a Type F reorganization under Section 368(a)(1)(F), not a consolidation.
Wrong (D): Distributing subsidiary stock to shareholders describes a Section 355 spin-off, not a consolidation.$EXPL$, 'easy', 1),

-- Q20: medium / L3 — Section 382(c) continuity of business enterprise
(6, 'Entity Formation and Restructuring', $EXPL$Osprey Corp has $6 million in NOL carryforwards and experiences an ownership change under Section 382. The new owners plan to immediately liquidate Osprey's operating business and invest all proceeds in a passive investment portfolio. Under Section 382(c), what happens to the Section 382 annual limitation?$EXPL$, $EXPL$["The annual limitation is doubled as a penalty for ceasing operations", "The annual limitation continues at the calculated rate because Section 382 does not require business continuity", "The NOLs are fully preserved but can only be used against passive investment income", "The Section 382 limitation is reduced to zero if the loss corporation does not continue its business enterprise for at least two years after the ownership change"]$EXPL$::jsonb, 3, $EXPL$Correct (D): Section 382(c)(1) provides that if the new loss corporation does not continue the business enterprise of the old loss corporation at all times during the two-year period beginning on the change date, the Section 382 limitation for any post-change year is zero. This effectively eliminates the use of the pre-change NOLs.
Wrong (A): There is no doubling penalty; the consequence is a reduction of the annual limitation to zero, not a punitive increase.
Wrong (B): Section 382(c) explicitly imposes a continuity of business enterprise requirement as a condition for using the annual limitation.
Wrong (C): When the COBE test is failed, the annual limitation drops to zero, meaning no NOLs can be used at all — not just a restriction to passive income.$EXPL$, 'medium', 3),

-- Q21: medium / L3 — Section 356 boot gain computation with multiple classes
(6, 'Entity Formation and Restructuring', $EXPL$In a qualifying reorganization, shareholder Chen surrenders two blocks of Target stock: Block 1 (basis $50,000, FMV $80,000) and Block 2 (basis $90,000, FMV $70,000). Chen receives Acquiring Corp stock worth $120,000 and $30,000 cash. Under Section 356 and the regulations, how should Chen compute recognized gain?$EXPL$, $EXPL$["Apply Section 356 separately to each block, recognizing gain on Block 1 and loss on Block 2", "Aggregate both blocks and recognize $10,000 gain (the lesser of $30,000 boot or $10,000 net realized gain)", "Recognize $30,000 gain equal to the total boot received regardless of basis", "Aggregate both blocks and recognize $30,000 gain because boot exceeds the net realized gain"]$EXPL$::jsonb, 0, $EXPL$Correct (A): Under the regulations, when a shareholder surrenders multiple blocks of stock in a reorganization, the boot must be allocated among the blocks and Section 356 is applied separately to each block. Block 1 has a $30,000 realized gain, and Block 2 has a $20,000 realized loss. Gain on Block 1 is recognized to the extent of allocated boot, but loss on Block 2 is not recognized under Section 356(c).
Wrong (B): Aggregating the blocks incorrectly nets the gain and loss; the regulations require a block-by-block analysis when multiple lots with different bases are exchanged.
Wrong (C): Recognized gain is limited to the lesser of boot received or realized gain on each block, not the total boot amount.
Wrong (D): This answer incorrectly assumes aggregation and overstates gain; the block-by-block approach and loss disallowance under Section 356(c) produce a different result.$EXPL$, 'medium', 3),

-- Q22: medium / L2 — Qualified stock purchase definition for Section 338
(6, 'Entity Formation and Restructuring', $EXPL$GlobalTech Corp begins purchasing stock of DataVault Inc. on March 1, Year 1. By September 15, Year 1, GlobalTech has acquired 85% of DataVault's stock through multiple open-market purchases. Under Section 338(d)(3), does this constitute a qualified stock purchase?$EXPL$, $EXPL$["No, because open-market purchases cannot qualify as a qualified stock purchase", "Yes, because GlobalTech acquired at least 80% of DataVault stock by vote and value within a 12-month acquisition period through purchases", "No, because all 80% must be acquired in a single transaction", "Yes, but only if the purchases were made from a single selling shareholder"]$EXPL$::jsonb, 1, $EXPL$Correct (B): Section 338(d)(3) defines a qualified stock purchase as the acquisition by a corporation of at least 80% (by vote and value) of the stock of another corporation by purchase during a 12-month acquisition period. Multiple open-market purchases can collectively satisfy this requirement as long as the 80% threshold is met within 12 months.
Wrong (A): Open-market purchases are valid purchase transactions for purposes of Section 338; there is no restriction on the method of acquisition.
Wrong (C): The statute permits aggregation of purchases over a 12-month period; a single-transaction requirement does not exist.
Wrong (D): Purchases from multiple sellers can be combined to meet the 80% threshold; there is no single-seller requirement.$EXPL$, 'medium', 2),

-- Q23: easy / L2 — Section 368 reorganization plan requirement
(6, 'Entity Formation and Restructuring', $EXPL$Whitfield Corp and Brookdale Corp complete a merger that meets all statutory requirements for a Type A reorganization. However, neither corporation adopted a formal written plan of reorganization before the transaction. Under the reorganization requirements, what is the effect?$EXPL$, $EXPL$["The merger automatically qualifies regardless of documentation", "The merger is automatically disqualified and must be treated as a taxable asset purchase", "The lack of a formal written plan creates audit risk because the IRS may argue the transaction was not conducted pursuant to a plan of reorganization, jeopardizing nonrecognition", "The corporations have 90 days after closing to retroactively adopt a plan"]$EXPL$::jsonb, 2, $EXPL$Correct (C): While courts have not always required a formal written plan, the absence of any plan documentation creates significant audit risk. The IRS may argue the transaction was not conducted pursuant to a plan of reorganization as required by Section 368, potentially jeopardizing nonrecognition treatment under Sections 354 and 361. Best practice is to adopt a written plan before the transaction closes.
Wrong (A): Although no formal written plan is absolutely required, ignoring documentation entirely creates risk that the IRS will challenge the reorganization status.
Wrong (B): Automatic disqualification overstates the consequence; courts examine the totality of circumstances, and a plan can be inferred from conduct.
Wrong (D): There is no 90-day safe harbor for retroactive adoption of a reorganization plan in the Code or regulations.$EXPL$, 'easy', 2),

-- Q24: easy / L1 — Section 361(c) distribution requirement
(6, 'Entity Formation and Restructuring', $EXPL$In an acquisitive reorganization where the target corporation receives stock and other property from the acquiring corporation, Section 361(c) requires the target to:$EXPL$, $EXPL$["Retain the acquiring corporation stock for at least one year", "Reinvest the property in a qualified replacement asset", "Hold the stock in escrow pending IRS approval", "Distribute the stock and other property to its shareholders or creditors pursuant to the plan of reorganization"]$EXPL$::jsonb, 3, $EXPL$Correct (D): Section 361(c) requires the transferor corporation in a reorganization to distribute the stock, securities, and other property received, as well as any other property, to its shareholders or creditors pursuant to the plan of reorganization. This distribution requirement ensures the transferor does not retain assets outside the reorganization structure.
Wrong (A): There is no holding period requirement for the acquired stock; the target must distribute it, not retain it.
Wrong (B): Section 361(c) requires distribution, not reinvestment, of the property received in the exchange.
Wrong (C): No escrow or IRS approval requirement exists; the distribution is made directly to shareholders or creditors.$EXPL$, 'easy', 1),

-- Q25: hard / L4 — Type C boot relaxation with liability interaction
(6, 'Entity Formation and Restructuring', $EXPL$Lakeview Corp proposes to acquire all assets of Ridgeway Corp in a Type C reorganization. The consideration consists of $40 million of Lakeview voting stock and $8 million in cash. As part of the transaction, Lakeview assumes $12 million of Ridgeway's liabilities. Under the Section 368(a)(2)(B) boot relaxation rule, does this transaction qualify as a Type C reorganization?$EXPL$, $EXPL$["No, because the cash ($8M) plus assumed liabilities ($12M) treated as boot total $20M, which exceeds 20% of the total consideration ($60M), disqualifying the transaction", "Yes, because assumed liabilities are never considered for the solely-for-voting-stock test", "Yes, because the $8 million cash alone is less than 20% of total consideration", "No, because Type C reorganizations prohibit any cash consideration under all circumstances"]$EXPL$::jsonb, 0, $EXPL$Correct (A): Under Section 368(a)(2)(B), the boot relaxation rule permits up to 20% non-stock consideration in a Type C reorganization. However, when any boot (such as cash) is paid, assumed liabilities are treated as money for purposes of the solely-for-voting-stock test. Total non-stock consideration is $8M cash + $12M liabilities = $20M out of $60M total (33%), exceeding the 20% threshold and disqualifying the transaction.
Wrong (B): When other boot is paid, Section 368(a)(2)(B) requires that assumed liabilities be treated as money; they are not disregarded.
Wrong (C): While $8M cash alone would be within the 20% limit, the assumed liabilities must be included in the calculation when any boot is present, pushing the total above 20%.
Wrong (D): Type C reorganizations do permit limited cash consideration under the boot relaxation rule, but only if total non-stock consideration (including liabilities when other boot is present) stays within 20%.$EXPL$, 'hard', 4),

-- Q26: easy / L2 — Section 382 value of loss corporation
(6, 'Entity Formation and Restructuring', $EXPL$Birchwood Corp has $12 million in NOL carryforwards and undergoes an ownership change under Section 382. An independent appraisal values Birchwood at $25 million on the change date. The long-term tax-exempt rate is 5%. Under Section 382(b), what is the annual limitation on Birchwood's use of its pre-change NOLs?$EXPL$, $EXPL$["$600,000 per year", "$1,250,000 per year", "$12,000,000 per year with no limitation", "$2,500,000 per year"]$EXPL$::jsonb, 1, $EXPL$Correct (B): Section 382(b) sets the annual limitation as the value of the old loss corporation multiplied by the long-term tax-exempt rate. Birchwood's value of $25,000,000 multiplied by 5% equals $1,250,000 per year. This cap limits how much of the pre-change NOLs can offset post-change taxable income each year.
Wrong (A): This figure incorrectly multiplies the NOL amount by the rate ($12M × 5%) rather than applying the rate to the corporation's value.
Wrong (C): Section 382 imposes an annual limitation after every ownership change; unlimited use is never permitted when Section 382 applies.
Wrong (D): This figure applies the rate at 10% instead of the stated 5% long-term tax-exempt rate.$EXPL$, 'easy', 2),

-- Q27: medium / L2 — Section 368(a)(1)(A) cross-border merger
(6, 'Entity Formation and Restructuring', $EXPL$Patriot Corp, a U.S. corporation, merges with Maple Ltd., a Canadian corporation, under a plan of merger approved under the applicable laws of both countries. Patriot shareholders receive Maple stock. Under Section 368(a)(1)(A), can this cross-border transaction qualify as a Type A reorganization?$EXPL$, $EXPL$["No, because Type A reorganizations are limited to mergers under U.S. state law only", "No, because cross-border mergers must use a Type C or Type D structure exclusively", "Yes, because Section 368(a)(1)(A) was amended to include mergers effected pursuant to the statutes of a foreign country as qualifying statutory mergers", "Yes, but only if the IRS issues a private letter ruling approving the transaction"]$EXPL$::jsonb, 2, $EXPL$Correct (C): Section 368(a)(1)(A) was amended to include transactions effected pursuant to the statute or statutes necessary to effect a merger under the laws of the United States, a state, or a foreign country. This expansion allows cross-border mergers to qualify as Type A reorganizations if they satisfy the applicable foreign merger statute requirements.
Wrong (A): The statutory definition was broadened beyond U.S. state law mergers to include mergers under federal law, state law, and foreign country law.
Wrong (B): Cross-border mergers are not restricted to Type C or Type D structures; Type A qualification is available for statutory mergers under foreign law.
Wrong (D): No private letter ruling is required for a cross-border merger to qualify; the transaction must meet the statutory and regulatory requirements on its own.$EXPL$, 'medium', 2),

-- Q28: hard / L4 — Integrated analysis of restructuring with multiple sections
(6, 'Entity Formation and Restructuring', $EXPL$Vanguard Corp owns two divisions. It transfers Division A assets (basis $10M, FMV $30M) to newly formed NewCo in exchange for all NewCo stock, then distributes the NewCo stock to its shareholders under Section 355. Six months later, unrelated AcquireCo merges with Vanguard (retaining Division B) in a Type A reorganization. Vanguard shareholders receive 45% of AcquireCo stock. Which combination of tax consequences is most likely?$EXPL$, $EXPL$["The Section 355 distribution is tax-free to shareholders, and Vanguard recognizes no gain because the merger occurred after the spin-off", "Both the spin-off and merger qualify for full nonrecognition because each independently meets its respective statutory requirements", "The spin-off fails entirely because Vanguard must retain Division A for at least two years before distributing NewCo stock", "The spin-off is tax-free to shareholders, but Section 355(e) requires Vanguard to recognize $20M gain because the merger within two years caused former Vanguard shareholders to own less than 50% of AcquireCo"]$EXPL$::jsonb, 3, $EXPL$Correct (D): Section 355(e) applies because the spin-off and the merger are part of a plan or series of related transactions (occurring within two years) that result in a greater-than-50% change in ownership of Vanguard. Former Vanguard shareholders own only 45% of AcquireCo, meaning a 55% ownership change occurred. Vanguard must recognize the $20M built-in gain ($30M FMV minus $10M basis) on the Division A stock distributed to shareholders. Shareholders still receive tax-free treatment.
Wrong (A): Section 355(e) specifically addresses this fact pattern — a spin-off followed by an acquisition — and triggers corporate-level gain recognition even though the merger occurred after the spin-off.
Wrong (B): While each transaction may independently meet its statutory requirements, Section 355(e) overrides the nonrecognition for the distributing corporation when a change in ownership occurs.
Wrong (C): There is no two-year holding requirement for spin-off assets; the issue is Section 355(e) gain recognition at the corporate level, not disqualification of the distribution.$EXPL$, 'hard', 4),

-- Q29: hard / L4 — Section 382 and reorganization interaction
(6, 'Entity Formation and Restructuring', $EXPL$Zenith Corp ($20M NOL carryforwards) merges into Pinnacle Corp in a Type A reorganization. Former Zenith shareholders receive 30% of Pinnacle stock. Zenith's pre-merger FMV was $15 million. The long-term tax-exempt rate is 4%. Under Section 382, what annual limitation applies to Zenith's NOLs, and why does a reorganization trigger Section 382?$EXPL$, $EXPL$["$600,000 annual limitation, because the former Zenith shareholders' ownership in Pinnacle (30%) represents a greater-than-50-percentage-point shift that constitutes an ownership change", "No limitation, because Section 382 does not apply to tax-free reorganizations", "$800,000 annual limitation, based on Pinnacle's post-merger value", "The NOLs are permanently disallowed because Zenith ceased to exist in the merger"]$EXPL$::jsonb, 0, $EXPL$Correct (A): Section 382(g)(1) defines an ownership change to include situations where 5-percent shareholders increase their aggregate ownership by more than 50 percentage points. In a merger where former Zenith shareholders receive only 30% of Pinnacle, the Pinnacle shareholders have effectively acquired 70% of Zenith's losses — a greater-than-50-point shift. The annual limitation is Zenith's FMV ($15M) × 4% = $600,000.
Wrong (B): Section 382 applies to tax-free reorganizations whenever the ownership of the loss corporation changes by more than 50 percentage points; tax-free treatment does not exempt the transaction.
Wrong (C): The annual limitation is based on the value of the loss corporation (Zenith at $15M), not the combined or acquiring corporation's value.
Wrong (D): NOLs carry over to the acquiring corporation under Section 381; they are not permanently disallowed but are subject to the Section 382 annual limitation.$EXPL$, 'hard', 4),

-- Q30: medium / L3 — Section 355 split-up transaction
(6, 'Entity Formation and Restructuring', $EXPL$Horizon Industries operates three divisions. To restructure, Horizon transfers each division's assets to three newly formed corporations (AlphaCo, BetaCo, and GammaCo) in exchange for all of each corporation's stock. Horizon then distributes the stock of all three corporations to its shareholders and liquidates. Under Section 355, this transaction is classified as a:$EXPL$, $EXPL$["Spin-off because the shareholders did not surrender any stock", "Split-up, in which the distributing corporation distributes stock of two or more controlled corporations and then liquidates", "Type D acquisitive reorganization because assets were transferred to new corporations", "Partial liquidation under Section 302(b)(4) because Horizon ceased multiple businesses"]$EXPL$::jsonb, 1, $EXPL$Correct (B): A split-up occurs when a distributing corporation transfers its assets to two or more controlled corporations and distributes all of the stock of those corporations to its shareholders in complete liquidation. This is the most comprehensive form of Section 355 transaction, resulting in the distributing corporation ceasing to exist.
Wrong (A): In a spin-off, the distributing corporation survives and distributes stock of only one controlled corporation without receiving back its own stock. Here, Horizon liquidates and distributes stock of multiple corporations.
Wrong (C): While the asset transfers resemble a Type D reorganization, the overall transaction is classified as a Section 355 split-up; the Type D provisions work in conjunction with Section 355 for divisive reorganizations.
Wrong (D): A partial liquidation under Section 302(b)(4) involves a distribution by a continuing corporation, not a complete liquidation into multiple new entities.$EXPL$, 'medium', 3)
;

COMMIT;
