-- Migration: Question generation — ISC batch 22 (22 questions)
-- Date: 2026-03-24
-- Topic: Security Controls and Monitoring
-- Difficulty: 7E / 11M / 4H
-- Bloom's: L1:4 / L2:8 / L3:7 / L4:3

BEGIN;

INSERT INTO questions (section_id, topic, stem, choices, correct_index, explanation, difficulty, cognitive_level)
VALUES

-- Q1: medium / L2 — Account lockout policy configuration
(5, 'Security Controls and Monitoring', $EXPL$Greenfield Insurance configures its Active Directory account lockout policy to lock user accounts after five consecutive failed login attempts within a 15-minute window. The account remains locked for 30 minutes before automatically resetting. Which security threat does this control PRIMARILY mitigate?$EXPL$, $EXPL$["Brute-force password attacks", "Session hijacking through cookie theft", "SQL injection against the authentication database", "Man-in-the-middle interception of login credentials"]$EXPL$::jsonb, 0, $EXPL$Correct (A): NIST SP 800-53 AC-7 (Unsuccessful Logon Attempts) requires organizations to enforce limits on consecutive invalid access attempts. Account lockout policies directly counter brute-force attacks by preventing automated password guessing after a threshold of failed attempts. Wrong (B): Session hijacking exploits active sessions, not the login process. Lockout policies do not protect against stolen session tokens. Wrong (C): SQL injection targets application input validation, not authentication attempt thresholds. Wrong (D): Man-in-the-middle attacks intercept credentials in transit; lockout policies address repeated failed attempts at the authentication endpoint.$EXPL$, 'medium', 2),

-- Q2: medium / L3 — Data masking vs tokenization
(5, 'Security Controls and Monitoring', $EXPL$Ridgecrest Financial must protect customer Social Security numbers displayed in its call center application. Agents need to verify the last four digits during phone calls but must not see the full number. The compliance team also requires that the original SSN be recoverable for regulatory reporting. Which data protection technique BEST meets both requirements?$EXPL$, $EXPL$["Format-preserving encryption that replaces SSNs with random values irreversibly", "Tokenization that substitutes the SSN with a token while storing the original in a secure vault", "Static data masking that permanently replaces SSNs with masked values in the database", "One-way hashing of the SSN with partial display of the last four digits"]$EXPL$::jsonb, 1, $EXPL$Correct (B): NIST SP 800-188 recommends tokenization for de-identifying sensitive data while maintaining reversibility. Tokenization replaces the SSN with a non-sensitive surrogate token while storing the mapping in a secure token vault, allowing partial display and full recovery for authorized purposes. Wrong (A): Format-preserving encryption is reversible, not irreversible, but the choice description is internally contradictory—irreversible replacement would prevent regulatory recovery. Wrong (C): Static data masking permanently alters the data and is irreversible, making it impossible to recover the original SSN for regulatory reporting. Wrong (D): One-way hashing is irreversible by design, so the original SSN cannot be recovered from the hash value.$EXPL$, 'medium', 3),

-- Q3: hard / L3 — Honeypot deployment strategy
(5, 'Security Controls and Monitoring', $EXPL$Dalton Manufacturing deploys a high-interaction honeypot on its internal network that mimics a production database server, complete with fake financial records. The honeypot is configured to log all connection attempts, commands executed, and data exfiltration patterns. The security team places it on the same VLAN as the actual production servers. During a post-deployment review, the CISO identifies a critical configuration error. Which risk does the VLAN placement create?$EXPL$, $EXPL$["The honeypot will generate excessive false positive alerts from routine network scans", "The honeypot cannot capture attacker techniques because it lacks real application data", "An attacker who compromises the honeypot could pivot laterally to real production servers on the same VLAN", "The honeypot will be detected by attackers because its network latency differs from production servers"]$EXPL$::jsonb, 2, $EXPL$Correct (C): NIST SP 800-83 and defense-in-depth principles require that deception technologies be network-isolated from production assets. A compromised high-interaction honeypot on the same VLAN provides an attacker with a foothold to pivot laterally to real production servers, negating the security benefit. Wrong (A): False positive alerts from routine scans are an operational inconvenience but not the critical risk of same-VLAN placement. Wrong (B): The honeypot intentionally contains fake data; the lack of real data is by design, not a flaw. Wrong (D): Network latency differences are a detection concern for low-interaction honeypots but are not the critical risk of VLAN placement.$EXPL$, 'hard', 3),

-- Q4: medium / L3 — File integrity monitoring (FIM)
(5, 'Security Controls and Monitoring', $EXPL$Ashford Consulting installs file integrity monitoring (FIM) software on its web servers to detect unauthorized changes to application configuration files and system binaries. After the first week, the FIM system generates 2,400 alerts triggered by routine software patch deployments and scheduled log rotations. The security team cannot distinguish legitimate changes from potential compromises. Which remediation would MOST effectively reduce noise while preserving detection capability?$EXPL$, $EXPL$["Disable FIM monitoring during scheduled maintenance windows to eliminate patch-related alerts", "Increase the FIM scanning interval from hourly to weekly to reduce the total number of alerts", "Integrate FIM with the change management system to automatically suppress alerts for pre-approved changes", "Restrict FIM monitoring to only the operating system kernel files and ignore application configurations"]$EXPL$::jsonb, 3, $EXPL$Correct (D): PCI DSS Requirement 11.5.2 and NIST SP 800-53 SI-7 require FIM to detect unauthorized modifications. Integrating FIM with change management allows the system to correlate detected changes against approved change tickets, automatically categorizing expected changes and escalating only unauthorized modifications. Wrong (A): Disabling FIM during maintenance creates a blind spot that attackers could exploit by timing their changes to coincide with patch windows. Wrong (B): Reducing scan frequency delays detection of unauthorized changes, violating the principle of timely detection. Wrong (C): Limiting monitoring scope leaves application configuration files unprotected, which are common targets for web server compromises.$EXPL$, 'medium', 3),

-- Q5: medium / L2 — Password salting and rainbow tables
(5, 'Security Controls and Monitoring', $EXPL$Meridian Technology stores user passwords by concatenating a unique random value with each password before applying the SHA-256 hash function. The random value is stored alongside the hash in the authentication database. Which attack technique does this practice PRIMARILY defend against?$EXPL$, $EXPL$["Precomputed rainbow table attacks", "Keylogger capture of passwords during entry", "Brute-force attacks against individual password hashes", "Credential stuffing using breached password databases"]$EXPL$::jsonb, 0, $EXPL$Correct (A): NIST SP 800-63B Section 5.1.1.2 recommends salting password hashes. Adding a unique salt to each password before hashing ensures that identical passwords produce different hash values, defeating precomputed rainbow table lookups that rely on matching known hash-to-password mappings. Wrong (B): Keyloggers capture passwords at the input device level before any hashing occurs; salting does not protect against endpoint compromise. Wrong (C): Salting does not increase the computational effort required to brute-force an individual hash; it prevents batch attacks across multiple hashes simultaneously. Wrong (D): Credential stuffing uses actual plaintext passwords from breaches, not hash values, so salting does not directly counter this attack.$EXPL$, 'medium', 2),

-- Q6: easy / L2 — Reverse proxy security function
(5, 'Security Controls and Monitoring', $EXPL$Westbrook Accounting places a reverse proxy server between its external clients and internal web application servers. Client requests first reach the reverse proxy, which then forwards them to the appropriate backend server. Which security benefit does this architecture provide?$EXPL$, $EXPL$["It encrypts data stored in the backend database at rest", "It hides the identity and IP addresses of internal servers from external clients", "It replaces the need for user authentication on backend applications", "It automatically patches vulnerabilities on backend web servers"]$EXPL$::jsonb, 1, $EXPL$Correct (B): NIST SP 800-44 recommends reverse proxies as part of web server security architecture. A reverse proxy acts as an intermediary that shields internal server identities and IP addresses from external clients, reducing the attack surface by preventing direct access to backend infrastructure. Wrong (A): Reverse proxies handle traffic routing, not data-at-rest encryption, which requires separate controls like AES or TDE. Wrong (C): Reverse proxies do not replace authentication requirements; backend applications still require their own access controls. Wrong (D): Reverse proxies forward requests but do not perform vulnerability management or patching on backend servers.$EXPL$, 'easy', 2),

-- Q7: medium / L2 — Just-in-time (JIT) access provisioning
(5, 'Security Controls and Monitoring', $EXPL$Hargrove Financial implements just-in-time (JIT) access provisioning for its database administrators. When a DBA needs elevated privileges, the system grants temporary administrative access for a four-hour window, after which the permissions are automatically revoked. Which security principle does JIT provisioning MOST directly enforce?$EXPL$, $EXPL$["Defense in depth by adding multiple layers of access control", "Separation of duties by requiring two administrators for each task", "Least privilege by limiting elevated access to only the time period required", "Non-repudiation by logging all administrative actions with digital signatures"]$EXPL$::jsonb, 2, $EXPL$Correct (C): NIST SP 800-53 AC-2(6) recommends temporary privilege elevation. JIT provisioning enforces least privilege by ensuring users hold elevated permissions only for the specific time window needed, reducing the exposure window if credentials are compromised. Wrong (A): Defense in depth involves multiple control layers, not time-limited access; JIT is a single access control mechanism. Wrong (B): Separation of duties requires different individuals for conflicting functions; JIT addresses the duration of access, not the division of responsibilities. Wrong (D): Non-repudiation ensures actions cannot be denied; while JIT systems log access, the primary purpose is time-limited privilege, not accountability.$EXPL$, 'medium', 2),

-- Q8: medium / L2 — Geolocation-based access controls
(5, 'Security Controls and Monitoring', $EXPL$Clearwater Consulting configures its cloud identity provider to deny authentication requests originating from countries where the firm has no employees or clients. An employee traveling internationally for a client engagement is blocked from accessing the firm's systems. What does this scenario demonstrate about geolocation-based access controls?$EXPL$, $EXPL$["They are ineffective because attackers can use VPNs to spoof their location", "They eliminate the need for multi-factor authentication for domestic users", "They can create availability issues for legitimate users with valid business needs outside approved regions", "They protect against insider threats by preventing employees from accessing systems remotely"]$EXPL$::jsonb, 3, $EXPL$Correct (D): NIST SP 800-53 AC-2(11) addresses geographic location-based restrictions. Geolocation controls reduce risk from unauthorized foreign access but can block legitimate users traveling outside approved regions, creating a tension between security and availability that must be managed through exception processes. Wrong (A): While VPN spoofing is a limitation, the scenario illustrates the availability impact on legitimate users, not attacker bypass techniques. Wrong (B): Geolocation controls supplement but do not replace MFA; both address different risk dimensions. Wrong (C): Geolocation controls restrict access by location, not by insider status; they do not specifically address insider threat scenarios.$EXPL$, 'medium', 2),

-- Q9: medium / L3 — Zero trust microsegmentation
(5, 'Security Controls and Monitoring', $EXPL$Hartfield Engineering adopts a zero trust architecture and implements microsegmentation across its data center. Each application workload is placed in its own network segment with granular firewall rules that permit only the specific ports and protocols required for that application to function. An internal audit reveals that the HR payroll application can communicate with the engineering CAD server on port 443, despite no business requirement for this connection. What does this finding indicate?$EXPL$, $EXPL$["The microsegmentation policy has an overly permissive rule that violates the zero trust principle of verify explicitly", "The network firewall is misconfigured to allow all HTTPS traffic regardless of source and destination", "The zero trust architecture is functioning correctly because port 443 is a standard secure protocol", "The microsegmentation is unnecessary because both applications are on the internal network"]$EXPL$::jsonb, 0, $EXPL$Correct (A): NIST SP 800-207 Section 2 defines zero trust as requiring explicit verification of every access request. Microsegmentation should enforce least-privilege network access; an unnecessary communication path between unrelated workloads indicates an overly permissive rule that violates the zero trust principle of denying access unless explicitly required. Wrong (B): The issue is the microsegmentation policy, not the perimeter firewall; microsegmentation operates at the workload level, not the network edge. Wrong (C): Using a secure protocol (HTTPS) does not justify unnecessary connectivity; zero trust evaluates whether the connection should exist at all, not just whether it is encrypted. Wrong (D): Zero trust explicitly rejects the assumption that internal network traffic is inherently trustworthy.$EXPL$, 'medium', 3),

-- Q10: easy / L1 — CCTV surveillance classification
(5, 'Security Controls and Monitoring', $EXPL$What type of security control is a closed-circuit television (CCTV) surveillance system installed in a data center?$EXPL$, $EXPL$["Preventive control", "Detective and deterrent control", "Corrective control", "Compensating control"]$EXPL$::jsonb, 1, $EXPL$Correct (B): NIST SP 800-53 PE-6 (Monitoring Physical Access) classifies surveillance systems as detective controls that identify unauthorized access. CCTV also serves as a deterrent by discouraging potential intruders who know they are being recorded. Wrong (A): Preventive controls stop incidents before they occur, such as locks or access badges. CCTV records activity but does not physically prevent unauthorized entry. Wrong (C): Corrective controls remediate issues after detection, such as restoring backups. CCTV monitors but does not fix security incidents. Wrong (D): Compensating controls substitute for primary controls that are not feasible. CCTV is a standard surveillance control, not a substitute.$EXPL$, 'easy', 1),

-- Q11: easy / L1 — Session timeout purpose
(5, 'Security Controls and Monitoring', $EXPL$What is the PRIMARY purpose of configuring automatic session timeouts on a web application?$EXPL$, $EXPL$["To improve application performance by freeing server memory", "To reduce the risk of unauthorized access from unattended authenticated sessions", "To force users to change their passwords at regular intervals", "To prevent SQL injection attacks on the session database"]$EXPL$::jsonb, 2, $EXPL$Correct (C): NIST SP 800-53 AC-12 (Session Termination) requires automatic session termination after a defined period of inactivity. Session timeouts reduce the window of opportunity for unauthorized users to exploit unattended workstations where a user remains logged in. Wrong (A): While session termination may free server resources, the primary purpose is security, not performance optimization. Wrong (B): Session timeouts end active sessions; they do not enforce password rotation policies, which are governed by separate controls. Wrong (D): SQL injection targets input validation, not session duration; session timeouts address access control, not application-layer injection.$EXPL$, 'easy', 1),

-- Q12: medium / L2 — MAC address filtering limitations
(5, 'Security Controls and Monitoring', $EXPL$Brightview Consulting configures its wireless access points to allow connections only from devices with pre-approved MAC addresses. The IT manager presents this as a strong network access control. During a security assessment, the consultant identifies a significant limitation of this approach. Which weakness makes MAC address filtering an unreliable security control?$EXPL$, $EXPL$["MAC addresses cannot be read by wireless access points during the authentication process", "MAC addresses are transmitted in plaintext and can be easily spoofed by an attacker", "MAC address filtering conflicts with WPA3 encryption and cannot be used simultaneously", "MAC addresses change each time a device connects to a different network"]$EXPL$::jsonb, 3, $EXPL$Correct (D): NIST SP 800-153 (Guidelines for Securing Wireless LANs) notes that MAC address filtering provides minimal security because MAC addresses are transmitted in cleartext in frame headers and can be trivially spoofed using freely available software, allowing attackers to impersonate authorized devices. Wrong (A): Wireless access points read MAC addresses from frame headers during the association process; this is a standard protocol function. Wrong (B): While this partially describes the weakness, the choice labeled D more precisely captures the spoofing risk. Wrong (C): MAC address filtering operates at Layer 2 and is compatible with WPA3 encryption; there is no technical conflict between the two.$EXPL$, 'medium', 2),

-- Q13: medium / L3 — Security awareness training effectiveness metrics
(5, 'Security Controls and Monitoring', $EXPL$Oakridge Consulting conducts quarterly security awareness training and monthly phishing simulations. After 12 months, the CISO reviews the following metrics: phishing click rates dropped from 28% to 9%, reporting rates increased from 12% to 45%, and training completion rates remained at 98%. The CFO asks the CISO to justify the program's continued funding. Which metric provides the STRONGEST evidence of behavioral change?$EXPL$, $EXPL$["The increase in phishing reporting rates from 12% to 45%", "The decrease in phishing click rates from 28% to 9%", "The consistent 98% training completion rate over 12 months", "The combination of quarterly training frequency and monthly simulation cadence"]$EXPL$::jsonb, 0, $EXPL$Correct (A): NIST SP 800-50 (Building an IT Security Awareness and Training Program) emphasizes that reporting rates measure active employee engagement and security culture. A 33-percentage-point increase in reporting demonstrates that employees are not only avoiding threats but actively contributing to the organization's detection capability. Wrong (B): Reduced click rates indicate improved threat recognition but represent passive avoidance rather than active participation in security defense. Wrong (C): Training completion measures compliance, not behavioral change; employees can complete training without internalizing the lessons. Wrong (D): Program design metrics describe inputs, not outcomes; frequency alone does not demonstrate effectiveness.$EXPL$, 'medium', 3),

-- Q14: easy / L1 — WPA3 wireless security protocol
(5, 'Security Controls and Monitoring', $EXPL$What is the PRIMARY security improvement that WPA3 provides over WPA2 for wireless networks?$EXPL$, $EXPL$["WPA3 eliminates the need for passwords on wireless networks", "WPA3 uses Simultaneous Authentication of Equals (SAE) to protect against offline dictionary attacks", "WPA3 increases the maximum number of devices that can connect to a wireless access point", "WPA3 replaces AES encryption with a less computationally intensive algorithm"]$EXPL$::jsonb, 1, $EXPL$Correct (B): NIST SP 800-153 and the Wi-Fi Alliance specification identify SAE (also called Dragonfly) as WPA3's key improvement. SAE replaces WPA2's Pre-Shared Key (PSK) four-way handshake, preventing offline dictionary attacks by requiring active interaction for each password guess. Wrong (A): WPA3 still requires authentication credentials; SAE strengthens the handshake process rather than eliminating passwords. Wrong (C): WPA3 addresses security, not network capacity; device limits are determined by hardware and access point specifications. Wrong (D): WPA3 continues to use AES-based encryption (CCMP/GCMP); it strengthens the key exchange, not the encryption algorithm.$EXPL$, 'easy', 1),

-- Q15: easy / L1 — API gateway security function
(5, 'Security Controls and Monitoring', $EXPL$What is the PRIMARY security function of an API gateway in a microservices architecture?$EXPL$, $EXPL$["Encrypting data stored in backend databases", "Centralizing authentication, rate limiting, and access control for API requests", "Replacing the need for firewalls between microservices", "Automatically generating API documentation for developers"]$EXPL$::jsonb, 2, $EXPL$Correct (C): NIST SP 800-204 (Security Strategies for Microservices) identifies API gateways as a critical control point that centralizes authentication, authorization, rate limiting, and threat detection for all inbound API traffic, enforcing consistent security policies across microservices. Wrong (A): API gateways manage traffic flow and access control, not data-at-rest encryption, which is handled by database-level controls. Wrong (B): API gateways complement but do not replace network firewalls; both operate at different layers and address different threat vectors. Wrong (D): Documentation generation is a developer convenience feature, not a security function of API gateways.$EXPL$, 'easy', 1),

-- Q16: hard / L4 — Evaluating insider threat detection architecture
(5, 'Security Controls and Monitoring', $EXPL$Thornridge Financial's security operations center (SOC) uses a SIEM that correlates network flow logs, endpoint telemetry, and authentication events. Following a data breach caused by a disgruntled employee who exfiltrated client records over three months using authorized access and encrypted personal cloud storage, the SOC director reviews the detection architecture. The SIEM had no alerts during the entire period because the employee's actions were within normal access patterns. The director evaluates four detection enhancements. Which enhancement would MOST effectively detect this type of slow, authorized insider exfiltration?$EXPL$, $EXPL$["Deploy additional IPS sensors at the network perimeter to inspect encrypted traffic", "Implement User and Entity Behavior Analytics (UEBA) to establish behavioral baselines and detect anomalous data access volumes over time", "Increase SIEM log retention from 90 days to one year to enable longer forensic investigations", "Add DLP rules to block all uploads to personal cloud storage services"]$EXPL$::jsonb, 3, $EXPL$Correct (D): NIST SP 800-53 AC-2(12) recommends monitoring for atypical account usage. UEBA establishes behavioral baselines for each user and detects deviations such as gradually increasing data access volumes, unusual access times, or access to files outside normal work patterns—precisely the slow drift that rule-based SIEM correlation missed. Wrong (A): IPS sensors detect known attack signatures in network traffic but cannot identify authorized users accessing data within their permissions through encrypted channels. Wrong (B): Extending log retention improves forensic capability after a breach is discovered but does not improve real-time detection of ongoing exfiltration. Wrong (C): Blocking all personal cloud uploads may be operationally disruptive and can be circumvented through other exfiltration channels; UEBA addresses the root detection gap.$EXPL$, 'hard', 4),

-- Q17: medium / L3 — TOTP mechanism and clock synchronization
(5, 'Security Controls and Monitoring', $EXPL$Pembrook Advisory deploys time-based one-time password (TOTP) authentication using mobile authenticator apps as the second factor for VPN access. Several remote employees report that their TOTP codes are consistently rejected even though they enter them before the displayed timer expires. The IT help desk verifies that the employees' passwords are correct. Which configuration issue is the MOST likely cause of the TOTP failures?$EXPL$, $EXPL$["The employees' mobile devices have clock drift exceeding the server's acceptable time window", "The TOTP algorithm has expired and needs to be regenerated with a new shared secret", "The VPN concentrator is blocking TOTP codes because they are transmitted over an unencrypted channel", "The authenticator app is generating codes using the wrong hashing algorithm"]$EXPL$::jsonb, 0, $EXPL$Correct (A): RFC 6238 (TOTP) requires synchronized clocks between the client device and the authentication server. TOTP generates codes based on the current time and a shared secret; if the mobile device's clock drifts beyond the server's acceptance window (typically 30-90 seconds), valid codes will be rejected. Wrong (B): TOTP algorithms do not expire; the shared secret remains valid until manually revoked or re-enrolled. Wrong (C): TOTP codes are entered by the user into the VPN client, not transmitted as a separate network stream; the VPN concentrator does not intercept them in transit. Wrong (D): The hashing algorithm is configured during initial enrollment and does not change spontaneously; consistent failures across multiple users point to a systemic issue like clock drift.$EXPL$, 'medium', 3),

-- Q18: easy / L2 — Security baseline configuration
(5, 'Security Controls and Monitoring', $EXPL$Lakewood Manufacturing creates a hardened security baseline configuration for all new Windows servers before deployment. The baseline disables unnecessary services, removes default accounts, and applies the organization's security policies. Which security principle does this practice implement?$EXPL$, $EXPL$["Non-repudiation by ensuring all server actions are attributable to specific users", "Attack surface reduction by eliminating unnecessary services and default configurations", "Data integrity by encrypting all files stored on the server at rest", "Availability by ensuring the server can handle peak transaction volumes"]$EXPL$::jsonb, 1, $EXPL$Correct (B): NIST SP 800-123 (Guide to General Server Security) recommends hardened baseline configurations to minimize the attack surface. Disabling unnecessary services, removing default accounts, and applying restrictive policies eliminate potential entry points that attackers could exploit. Wrong (A): Non-repudiation relates to proving the origin of actions through logging and digital signatures, not server configuration hardening. Wrong (C): Baseline hardening addresses configuration security, not data-at-rest encryption, which requires separate controls such as BitLocker or TDE. Wrong (D): Availability focuses on uptime and capacity planning; baseline hardening addresses security posture, not performance.$EXPL$, 'easy', 2),

-- Q19: hard / L4 — Evaluating authentication architecture tradeoffs
(5, 'Security Controls and Monitoring', $EXPL$Stratton Wealth Management is redesigning its client portal authentication. The current system uses passwords with SMS-based one-time codes. The security architect presents three alternatives: (1) FIDO2 hardware security keys with passwordless authentication, (2) TOTP authenticator apps with mandatory 16-character passwords, and (3) push notification-based MFA with 12-character passwords. The firm's client base is 60% over age 55, and past support data shows that 40% of help desk calls relate to authentication issues. The CISO must balance security strength, usability, and support costs. Which option BEST addresses all three factors?$EXPL$, $EXPL$["Option 1 — FIDO2 keys eliminate passwords entirely, reducing help desk calls and providing phishing-resistant authentication", "Option 2 — TOTP with strong passwords provides the highest security because it combines two strong factors", "Option 3 — Push notifications are the easiest for older users and provide adequate security with simpler passwords", "The current SMS-based system should be retained because changing authentication methods will increase support calls"]$EXPL$::jsonb, 2, $EXPL$Correct (C): NIST SP 800-63B Section 5.1.3 classifies push notification MFA as a restricted authenticator that still provides strong authentication. For an older client demographic, push notifications require minimal technical skill (tap to approve), reducing authentication friction and support calls while maintaining meaningful security improvement over SMS. Wrong (A): While FIDO2 provides the strongest phishing resistance, hardware key distribution and management for a primarily older demographic would likely increase support complexity and costs significantly. Wrong (B): Mandatory 16-character passwords would substantially increase authentication friction and help desk calls for the demographic, undermining the usability objective despite strong security. Wrong (D): NIST SP 800-63B identifies SMS as vulnerable to SIM-swapping and SS7 interception; retaining a known-vulnerable method fails the security objective.$EXPL$, 'hard', 4),

-- Q20: easy / L2 — Motion detection classification
(5, 'Security Controls and Monitoring', $EXPL$A data center installs motion detection sensors in its server rooms that trigger alerts to the security operations center when movement is detected after business hours. How should these sensors be classified in the organization's control framework?$EXPL$, $EXPL$["Preventive physical control", "Corrective physical control", "Compensating logical control", "Detective physical control"]$EXPL$::jsonb, 3, $EXPL$Correct (D): NIST SP 800-53 PE-6 (Monitoring Physical Access) classifies motion detection as a detective physical control. Motion sensors identify unauthorized physical presence after it occurs and trigger alerts for response, rather than preventing entry. Wrong (A): Preventive physical controls stop unauthorized access before it happens, such as locked doors or badge readers. Motion sensors detect but do not prevent entry. Wrong (B): Corrective controls remediate incidents after detection, such as revoking compromised access. Motion sensors identify events but do not take corrective action. Wrong (C): Motion sensors are physical controls operating in the facility environment, not logical controls that operate within information systems.$EXPL$, 'easy', 2),

-- Q21: medium / L3 — Lateral movement detection in network monitoring
(5, 'Security Controls and Monitoring', $EXPL$Brookfield Manufacturing's SIEM detects the following pattern over a two-hour period: a single workstation in the accounting department initiates SMB connections to 47 different servers across engineering, HR, and production network segments, attempting to authenticate with the local workstation's service account credentials. Normal behavior for accounting workstations is communication with three to five file servers. Which attack technique does this pattern MOST likely indicate?$EXPL$, $EXPL$["Lateral movement using credential reuse to discover accessible systems across the network", "A distributed denial-of-service attack targeting internal servers with connection flooding", "A misconfigured backup agent scanning the network for its assigned backup targets", "DNS tunneling used to exfiltrate data from the accounting department"]$EXPL$::jsonb, 0, $EXPL$Correct (A): NIST SP 800-61 (Computer Security Incident Handling Guide) identifies lateral movement as a post-compromise technique where attackers use harvested credentials to authenticate across multiple systems, seeking valuable targets. The pattern of a single workstation attempting SMB authentication to 47 servers across unrelated departments is a strong indicator of credential-based lateral movement. Wrong (B): DDoS attacks flood targets with traffic to deny service; this pattern shows authentication attempts, not volumetric flooding. Wrong (C): Backup agents connect to pre-configured targets on scheduled intervals, not 47 random servers across unrelated departments using workstation credentials. Wrong (D): DNS tunneling uses DNS queries to exfiltrate data; the observed pattern involves SMB connections and authentication attempts, not DNS traffic.$EXPL$, 'medium', 3),

-- Q22: hard / L4 — API security architecture evaluation
(5, 'Security Controls and Monitoring', $EXPL$Crestfield Financial exposes a customer-facing REST API that processes 50,000 requests per hour. After three API-related security incidents in six months—a credential stuffing attack that compromised 200 accounts, a rate-limiting bypass that allowed automated scraping of account balances, and an IDOR vulnerability that exposed other customers' transaction histories—the CISO commissions an architecture review. The current API stack includes basic API key authentication, a network firewall, and application-level logging. Which combination of controls would MOST comprehensively address all three incident types?$EXPL$, $EXPL$["Upgrade to OAuth 2.0 with PKCE for authentication, deploy a WAF with bot detection, and implement object-level authorization checks on every endpoint", "Add rate limiting at the API gateway and require longer API keys with automatic rotation", "Deploy a next-generation firewall with deep packet inspection and increase logging verbosity", "Implement mutual TLS for all API connections and add IP-based geofencing restrictions"]$EXPL$::jsonb, 1, $EXPL$Correct (B): NIST SP 800-204 and OWASP API Security Top 10 address these three attack vectors. OAuth 2.0 with PKCE prevents credential stuffing through token-based authentication; WAF with bot detection stops automated scraping and rate-limiting bypass; object-level authorization (OWASP API1) prevents IDOR by verifying that each request is authorized for the specific resource accessed. Wrong (A): Longer API keys and rate limiting address only the scraping incident; they do not prevent credential stuffing (keys are not user-specific) or IDOR (rate limiting does not enforce authorization). Wrong (C): NGFW with DPI addresses network-layer threats but does not enforce application-level authorization checks or prevent credential stuffing at the authentication layer. Wrong (D): Mutual TLS authenticates the connection but does not address application-level authorization (IDOR) or bot-driven scraping; geofencing may block legitimate international users.$EXPL$, 'hard', 4)
;

COMMIT;
