-- Migration: Question generation — ISC batch 26 (19 questions)
-- Date: 2026-03-24
-- Topic: SOC Reporting and Trust Services Criteria
-- Difficulty: 6E / 9M / 4H
-- Bloom's: L1:4 / L2:6 / L3:6 / L4:3

BEGIN;

INSERT INTO questions (section_id, topic, stem, choices, correct_index, explanation, difficulty, cognitive_level)
VALUES

-- Q1: medium / L2 — SOC 2 Type I vs Type II distinction
(5, 'SOC Reporting and Trust Services Criteria', $EXPL$Mercer Analytics engaged a CPA firm to perform a SOC 2 engagement. Management wants to demonstrate that controls not only exist but have been functioning properly over the past twelve months. Which type of SOC 2 report should Mercer request?$EXPL$, $EXPL$["A SOC 2 Type I report covering a point in time", "A SOC 2 Type II report covering a period of time", "A SOC 3 report with general-use distribution", "A SOC 1 Type II report under SSAE 18"]$EXPL$::jsonb, 1, $EXPL$Correct (B): Per SSAE 18 (AT-C 205), a SOC 2 Type II report covers a specified period and includes testing of operating effectiveness over that period. This is the appropriate report when management wants to demonstrate sustained control performance. Wrong (A): A Type I report addresses a point in time and evaluates design suitability only, not operating effectiveness over a period. Wrong (C): A SOC 3 report provides a summary opinion for general distribution but does not include detailed test results needed for evaluating ongoing effectiveness. Wrong (D): A SOC 1 report addresses controls relevant to user entities' financial statements, not Trust Services Criteria.$EXPL$, 'medium', 2),

-- Q2: hard / L4 — Bridge letter sufficiency evaluation
(5, 'SOC Reporting and Trust Services Criteria', $EXPL$Thornton & Pratt LLP audits a financial services company whose fiscal year ends December 31, 2025. The company's payroll processor provides a SOC 1 Type II report covering January 1 through June 30, 2025. The processor's management provides a bridge letter stating no significant changes occurred since July 1. Given the six-month gap, what should Thornton & Pratt conclude?$EXPL$, $EXPL$["The bridge letter fully substitutes for the missing coverage period", "The bridge letter alone is insufficient due to the length of the gap, and additional procedures are needed", "The audit team must obtain a new SOC 1 report covering the full fiscal year before issuing an opinion", "The gap period is irrelevant because the SOC 1 report was unqualified"]$EXPL$::jsonb, 1, $EXPL$Correct (B): Per AU-C 402.15, when a significant gap period exists between the SOC report period and the user entity's year-end, the user entity auditor should perform additional procedures such as inquiry, observation, or review of a subsequent report. A six-month gap is considered lengthy and a bridge letter alone does not provide sufficient assurance. Wrong (A): Bridge letters are management representations, not audit evidence, and are generally sufficient only for short gaps of one to two months. Wrong (C): Obtaining a new full-year report is ideal but not a requirement; the auditor can perform alternative procedures instead. Wrong (D): The gap period is always relevant regardless of whether the report is unqualified.$EXPL$, 'hard', 4),

-- Q3: easy / L1 — SOC 3 distribution rules
(5, 'SOC Reporting and Trust Services Criteria', $EXPL$What is the primary distribution characteristic of a SOC 3 report?$EXPL$, $EXPL$["It is restricted to management and user entity auditors only", "It requires a nondisclosure agreement before sharing", "It is a general-use report that may be freely distributed", "It may only be shared with regulatory agencies"]$EXPL$::jsonb, 2, $EXPL$Correct (C): Per AICPA SOC 2 reporting guidance, a SOC 3 report is designed for general use and may be freely distributed, including posting on a service organization's website. It contains a summary opinion without detailed control descriptions or test results. Wrong (A): Restricted distribution applies to SOC 2 reports, not SOC 3 reports. Wrong (B): No nondisclosure agreement is required because SOC 3 reports contain only summary-level information. Wrong (D): SOC 3 reports are not limited to regulatory agencies; any party may receive them.$EXPL$, 'easy', 1),

-- Q4: medium / L2 — Three elements of auditor's opinion (Section I)
(5, 'SOC Reporting and Trust Services Criteria', $EXPL$Westbrook Consulting receives a SOC 2 Type II report from its cloud hosting provider. In Section I of the report, the service auditor's opinion addresses three specific elements. Which of the following is one of the three elements covered by the auditor's opinion?$EXPL$, $EXPL$["Whether the service organization's pricing model is commercially reasonable", "Whether the user entity has implemented all complementary controls", "Whether the service organization's revenue recognition complies with GAAP", "Whether the controls were suitably designed to meet the applicable Trust Services Criteria"]$EXPL$::jsonb, 3, $EXPL$Correct (D): Per AT-C 205, the service auditor's opinion in a SOC 2 Type II report addresses whether the system description is fairly presented, whether controls were suitably designed, and whether controls operated effectively throughout the period. Suitable design is one of these three elements. Wrong (A): Pricing reasonableness is a business matter outside the scope of a SOC 2 engagement. Wrong (B): The service auditor does not opine on whether user entities have implemented CUECs; that is the user entity auditor's responsibility. Wrong (C): Revenue recognition compliance is a financial statement matter addressed by financial audits, not SOC 2 engagements.$EXPL$, 'medium', 2),

-- Q5: medium / L3 — Multi-criteria control mapping analysis
(5, 'SOC Reporting and Trust Services Criteria', $EXPL$Fielding Data Corp. implements a comprehensive incident response plan that includes breach notification procedures, containment protocols, and recovery steps. The SOC 2 engagement covers Security, Availability, Confidentiality, and Privacy criteria. To which criteria does this single control MOST directly map?$EXPL$, $EXPL$["Security, Availability, Confidentiality, and Privacy", "Security and Availability only", "Security and Confidentiality only", "Security only, since it falls under the common criteria"]$EXPL$::jsonb, 0, $EXPL$Correct (A): Per AICPA TSC mapping guidance, an incident response plan with breach notification maps to Security (detecting and responding to incidents under CC7), Availability (restoring system operations), Confidentiality (containing breaches of confidential data), and Privacy (breach notification for personal information). A single control can address multiple criteria simultaneously. Wrong (B): This omits Confidentiality and Privacy, both of which are directly served by containment and breach notification components. Wrong (C): This omits Availability and Privacy, which are addressed by the recovery steps and breach notification procedures respectively. Wrong (D): While incident response falls under Security common criteria, the plan's scope extends to all four additional criteria in this engagement.$EXPL$, 'medium', 3),

-- Q6: easy / L2 — SOC 2 Section IV and restricted-use rationale
(5, 'SOC Reporting and Trust Services Criteria', $EXPL$Grafton Industries receives its cloud vendor's SOC 2 Type II report and reviews Section IV. The vendor's marketing team asks to publish the full report on the company website. Why would this be inappropriate?$EXPL$, $EXPL$["The report has already expired and is no longer valid", "Section IV contains detailed control descriptions and test results that make SOC 2 reports restricted-use", "The report can only be published after the service auditor provides written consent", "SOC 2 reports automatically become public records after 90 days"]$EXPL$::jsonb, 1, $EXPL$Correct (B): Per AICPA guidance, SOC 2 reports are restricted-use because Section IV contains detailed descriptions of controls, tests performed, and results including exceptions. This sensitive information about the control environment should only be shared with parties who have sufficient understanding to interpret the findings. Wrong (A): SOC reports do not have formal expiration dates, though their relevance diminishes over time. Wrong (C): The restriction is inherent to the report type, not contingent on auditor consent for publication. Wrong (D): SOC 2 reports do not become public records; they remain restricted-use documents.$EXPL$, 'easy', 2),

-- Q7: medium / L3 — User entity auditor SOC report evaluation steps
(5, 'SOC Reporting and Trust Services Criteria', $EXPL$Nguyen & Associates LLP is auditing a retail client that outsources credit card processing to a third party. The firm receives a SOC 1 Type II report from the processor. After reading the report and evaluating the service auditor's competence, the audit team identifies three control exceptions in Section IV. What should the team do next?$EXPL$, $EXPL$["Issue a disclaimer of opinion on the client's financial statements", "Automatically increase substantive testing for all transaction cycles", "Evaluate whether the specific exceptions affect the user entity's financial statements and determine the impact on audit risk", "Require the service organization to remediate the exceptions before completing the audit"]$EXPL$::jsonb, 2, $EXPL$Correct (C): Per AU-C 402.16, the user entity auditor must evaluate control exceptions in the SOC report and assess their potential impact on the user entity's financial statements and overall audit risk. Not all exceptions are relevant to every user entity. Wrong (A): A disclaimer is not warranted solely because exceptions exist; the auditor must first assess their significance. Wrong (B): Increasing substantive testing across all cycles is disproportionate; the response should target the specific areas affected by the exceptions. Wrong (D): The user entity auditor has no authority to require the service organization to remediate controls.$EXPL$, 'medium', 3),

-- Q8: medium / L3 — Management's assertion content (Section II)
(5, 'SOC Reporting and Trust Services Criteria', $EXPL$Brightline SaaS is preparing for its first SOC 2 Type II engagement covering a twelve-month period. Management is drafting the written assertion required for Section II of the report. Which of the following statements should management include in this assertion?$EXPL$, $EXPL$["That all user entities have implemented the required complementary controls", "That the service auditor conducted the engagement in accordance with SSAE 18", "That no competitor offers a more secure platform for the same services", "That controls were suitably designed and operated effectively throughout the specified period"]$EXPL$::jsonb, 3, $EXPL$Correct (D): Per AT-C 205, management's assertion in a SOC 2 Type II report must state that the system description is fairly presented, that controls were suitably designed, and that controls operated effectively throughout the examination period. These three elements mirror the service auditor's opinion. Wrong (A): Management cannot assert that user entities have implemented CUECs, as this is outside the service organization's control and knowledge. Wrong (B): Statements about the auditor's compliance with professional standards belong in the auditor's report, not management's assertion. Wrong (C): Competitive comparisons are marketing claims and have no place in a SOC 2 management assertion.$EXPL$, 'medium', 3),

-- Q9: easy / L1 — SOC 2 report four-section structure
(5, 'SOC Reporting and Trust Services Criteria', $EXPL$What are the four main sections of a SOC 2 Type II report?$EXPL$, $EXPL$["Auditor's opinion, management's assertion, system description, and description of controls with tests and results", "Executive summary, risk assessment, control matrix, and remediation plan", "Engagement letter, fieldwork results, management letter, and final opinion", "Scope statement, vulnerability assessment, penetration test results, and recommendations"]$EXPL$::jsonb, 0, $EXPL$Correct (A): Per AICPA SOC 2 reporting standards (AT-C 205), a SOC 2 Type II report contains four sections: Section I (independent service auditor's report/opinion), Section II (management's assertion), Section III (system description), and Section IV (description of controls, tests performed, and results). Wrong (B): This describes a risk management deliverable, not a SOC 2 report structure. Wrong (C): This describes a generic audit workflow rather than the standardized SOC 2 report sections. Wrong (D): This describes a penetration testing report, which is a different type of assessment entirely.$EXPL$, 'easy', 1),

-- Q10: hard / L4 — Evaluating opinion type given specific deficiencies
(5, 'SOC Reporting and Trust Services Criteria', $EXPL$Sterling Payments processes transactions for 200 bank clients. During a SOC 2 Type II engagement covering January through December 2025, the service auditor discovers that the entity's sole authentication mechanism for administrative access was a single-factor password throughout the entire period, affecting CC6 controls. This deficiency directly undermines the Security criteria across all user entities. What type of opinion should the service auditor most likely issue?$EXPL$, $EXPL$["An unqualified opinion with an emphasis-of-matter paragraph", "An adverse opinion because the deficiency is pervasive and material to the Security criteria", "A qualified opinion limited to the CC6 criteria only", "A disclaimer of opinion due to a scope limitation"]$EXPL$::jsonb, 1, $EXPL$Correct (B): Per AT-C 205, when a control deficiency is both material and pervasive to the applicable Trust Services Criteria, the service auditor issues an adverse opinion. A fundamental authentication weakness affecting all administrative access throughout the entire period represents a systemic failure of the Security criteria's core requirements. Wrong (A): An unqualified opinion indicates controls operated effectively; an emphasis-of-matter paragraph does not address material control failures. Wrong (C): A qualified opinion would be appropriate for isolated or limited exceptions, not a pervasive deficiency undermining the foundational Security criterion. Wrong (D): A disclaimer is issued for scope limitations, not for identified control deficiencies.$EXPL$, 'hard', 4),

-- Q11: hard / L4 — SOC report usage in audit with no report available
(5, 'SOC Reporting and Trust Services Criteria', $EXPL$Park & Rivera CPAs audits a technology company that outsources its entire general ledger function to a cloud-based service organization. The service organization has never undergone a SOC engagement and refuses to allow Park & Rivera to visit its facilities. The general ledger function is material to the client's financial statements. How should Park & Rivera proceed?$EXPL$, $EXPL$["Issue an unqualified opinion since the client's controls are unaffected by outsourcing", "Withdraw from the engagement because no audit can be completed without a SOC report", "Perform alternative procedures such as testing reconciliations and increasing substantive testing of affected balances", "Require the client to terminate the outsourcing arrangement before completing the audit engagement"]$EXPL$::jsonb, 2, $EXPL$Correct (C): Per AU-C 402.12-13, when no SOC report is available and direct access is denied, the user entity auditor must perform alternative procedures to obtain sufficient audit evidence. These may include reviewing available documentation, testing user entity reconciliations, and expanding substantive procedures on the affected account balances. Wrong (A): When a material function is outsourced, the service organization's controls are relevant to the audit and cannot be ignored. Wrong (B): Withdrawal is premature; the auditor should first attempt alternative procedures before considering a scope limitation. Wrong (D): The auditor cannot dictate the client's business relationships; the auditor must work within existing arrangements.$EXPL$, 'hard', 4),

-- Q12: medium / L3 — Gap period handling with significant system changes
(5, 'SOC Reporting and Trust Services Criteria', $EXPL$Kensington Financial relies on a payroll service organization whose SOC 1 Type II report covers January through September 2025. Kensington's fiscal year ends December 31, 2025. During October, the service organization migrated to an entirely new payroll platform. The bridge letter discloses this migration. What additional step should Kensington's auditor take?$EXPL$, $EXPL$["Accept the bridge letter as sufficient since it transparently discloses the platform migration", "Request a completely new SOC report that covers the entire twelve-month calendar year period", "Reduce reliance on controls and expand substantive testing or perform direct procedures for the gap period", "Perform additional procedures to evaluate the new platform's controls and expand substantive payroll testing"]$EXPL$::jsonb, 3, $EXPL$Correct (D): Per AU-C 402.15, when significant changes to the system occur during a gap period, a bridge letter alone is insufficient. The user entity auditor should perform additional procedures such as expanding substantive testing of payroll balances, inquiring about the new platform's controls, or performing direct testing. A complete platform migration fundamentally changes the control environment. Wrong (A): A bridge letter disclosing significant changes actually signals that additional procedures are needed, not that the disclosure itself is sufficient. Wrong (B): While requesting a new report is desirable, it may not be feasible given timing constraints; the auditor must be prepared to perform alternative procedures. Wrong (C): This option partially addresses the situation but the correct answer better captures the full range of appropriate responses including direct procedures.$EXPL$, 'medium', 3),

-- Q13: medium / L2 — SOC 1 vs SOC 2 purpose distinction
(5, 'SOC Reporting and Trust Services Criteria', $EXPL$Redwood Capital outsources its investment accounting to a fund administrator. Redwood's external auditor needs assurance that the administrator's controls are reliable for purposes of auditing Redwood's financial statements. Which type of SOC report is specifically designed for this purpose?$EXPL$, $EXPL$["A SOC 1 report, because it addresses controls relevant to user entities' financial reporting", "A SOC 2 report, because it covers the Trust Services Criteria", "A SOC 3 report, because it provides a general-use opinion on the system", "A SOC for Cybersecurity report, because it addresses entity-wide risk management"]$EXPL$::jsonb, 0, $EXPL$Correct (A): Per SSAE 18 (AT-C 320), SOC 1 reports are specifically designed to address controls at a service organization that are relevant to user entities' internal control over financial reporting. When the outsourced function directly affects financial statement assertions, SOC 1 is the appropriate report type. Wrong (B): SOC 2 reports address the Trust Services Criteria and are designed for operational and compliance purposes, not specifically for financial statement audit reliance. Wrong (C): SOC 3 reports are general-use summaries that lack the detail needed for financial statement audit purposes. Wrong (D): SOC for Cybersecurity reports address entity-wide cybersecurity risk management, not controls relevant to specific user entities' financial reporting.$EXPL$, 'medium', 2),

-- Q14: medium / L2 — User auditor not required to reference service auditor
(5, 'SOC Reporting and Trust Services Criteria', $EXPL$Chen & Associates CPAs completed an audit of a logistics company that relies heavily on a third-party warehousing system. The firm obtained and evaluated a SOC 1 Type II report from the warehouse operator with no exceptions. A junior auditor asks whether the firm must reference the service auditor's work in the audit report. What is the correct guidance?$EXPL$, $EXPL$["The firm must reference the service auditor in the audit opinion paragraph", "The firm is not required to reference the service auditor or the SOC report in its own audit report", "The firm must include the service auditor's opinion as an appendix to the audit report", "The firm must obtain the service auditor's written permission before issuing the audit report"]$EXPL$::jsonb, 1, $EXPL$Correct (B): Per AU-C 402.19, the user entity auditor is not required to reference the service auditor or the SOC report in the audit report, even when relying on a SOC report as part of the audit. The user entity auditor takes sole responsibility for the opinion on the financial statements. Wrong (A): Referencing the service auditor in the opinion could inappropriately imply divided responsibility, which is not the standard. Wrong (C): SOC reports are restricted-use documents and should not be appended to the user entity's audit report. Wrong (D): No permission from the service auditor is needed; the user entity auditor independently decides how to use the SOC report findings.$EXPL$, 'medium', 2),

-- Q15: easy / L1 — Who prepares the system description
(5, 'SOC Reporting and Trust Services Criteria', $EXPL$In a SOC 2 engagement, who is responsible for preparing the management assertion in Section II of the report?$EXPL$, $EXPL$["The user entity's external auditor prepares the management assertion", "The AICPA peer review board drafts the assertion on behalf of the service organization", "The service organization's management prepares and signs the assertion", "The service auditor drafts the assertion as part of the engagement deliverables"]$EXPL$::jsonb, 2, $EXPL$Correct (C): Per AT-C 205, the management assertion in Section II is prepared by the service organization's own management. Management takes responsibility for asserting that the system description is fairly presented and that controls were suitably designed and operated effectively. This is analogous to how management provides representations in a financial audit. Wrong (A): The user entity's auditor is a reader of the report, not a preparer of any section within it. Wrong (B): The AICPA sets the standards for SOC engagements but does not participate in preparing individual report sections. Wrong (D): Although the service auditor may advise on format, the assertion itself is management's responsibility, not the auditor's deliverable.$EXPL$, 'easy', 1),

-- Q16: hard / L3 — Evaluating CUECs and SAS interconnection
(5, 'SOC Reporting and Trust Services Criteria', $EXPL$Apex Financial Group receives a SOC 2 Type II report from its data center provider. The report identifies twelve complementary user entity controls (CUECs), including requirements for Apex to conduct quarterly access reviews, maintain endpoint encryption, and restrict VPN access to authorized personnel. Apex has implemented nine of the twelve CUECs but has not implemented the three related to endpoint encryption and VPN restrictions. How does this gap most likely affect the overall control environment?$EXPL$, $EXPL$["It has no effect because CUECs are merely optional recommendations for user entities", "The SOC 2 report becomes invalid and the service organization must obtain a reissued report", "The service auditor must revise the opinion to reflect the user entity's noncompliance with CUECs", "The service organization's controls may not fully achieve their intended objectives without these complementary controls"]$EXPL$::jsonb, 3, $EXPL$Correct (D): Per AICPA SOC 2 guidance, CUECs are controls that the service organization's system was designed to assume the user entity would implement. When a user entity fails to implement identified CUECs, the combined control environment may not achieve the intended Trust Services Criteria objectives, creating a gap in the overall control structure. Wrong (A): CUECs are not optional recommendations; they are essential controls that the service organization's system design depends upon. Wrong (B): The SOC 2 report reflects the service organization's controls and remains valid regardless of user entity actions. Wrong (C): The service auditor's opinion covers the service organization's controls only and is not affected by whether user entities implement CUECs.$EXPL$, 'hard', 3),

-- Q17: easy / L1 — SOC 3 is Type II only
(5, 'SOC Reporting and Trust Services Criteria', $EXPL$Which report period type is available for SOC 3 engagements?$EXPL$, $EXPL$["Type II only, which covers a specified period of time", "Type I only, which covers a single point in time", "Both Type I and Type II, at the organization's discretion", "Neither Type I nor Type II; SOC 3 uses its own reporting framework"]$EXPL$::jsonb, 0, $EXPL$Correct (A): Per AICPA guidance, SOC 3 reports are available only as Type II engagements, covering a specified period of time. Since SOC 3 reports are intended for general distribution and provide assurance to a broad audience, they require evidence of operating effectiveness over a period rather than design suitability at a single point. Wrong (B): Type I (point-in-time) engagements are available for SOC 1 and SOC 2 but not SOC 3. Wrong (C): Unlike SOC 1 and SOC 2, which offer both Type I and Type II, SOC 3 is limited to Type II. Wrong (D): SOC 3 follows the same Type II period-of-time framework used by other SOC report types.$EXPL$, 'easy', 1),

-- Q18: medium / L3 — SLA monitoring maps to availability and processing integrity
(5, 'SOC Reporting and Trust Services Criteria', $EXPL$Pinnacle Cloud Services implements automated SLA monitoring dashboards that track system uptime percentages and transaction processing accuracy against contractual thresholds. The SOC 2 engagement covers Security, Availability, and Processing Integrity. To which of the additional criteria beyond Security does this SLA monitoring control most directly relate?$EXPL$, $EXPL$["Confidentiality and Privacy", "Availability and Processing Integrity", "Processing Integrity and Confidentiality", "Availability and Privacy"]$EXPL$::jsonb, 1, $EXPL$Correct (B): Per AICPA TSC mapping, SLA monitoring that tracks uptime directly supports Availability criteria (A1) by ensuring the system meets committed service levels. Tracking transaction processing accuracy supports Processing Integrity criteria (PI1) by monitoring whether processing is complete, accurate, and timely. Together, SLA monitoring spans both categories. Wrong (A): SLA monitoring of uptime and transaction accuracy does not directly address protection of confidential information or personal data. Wrong (C): While processing accuracy is relevant, SLA uptime monitoring does not address confidentiality protections. Wrong (D): Uptime monitoring supports Availability, but SLA dashboards tracking accuracy do not address Privacy criteria for personal information.$EXPL$, 'medium', 3),

-- Q19: easy / L2 — Service auditor competence and independence evaluation
(5, 'SOC Reporting and Trust Services Criteria', $EXPL$Harper & Lin CPAs obtains a SOC 1 Type II report to support the audit of a client that uses an external benefits administrator. Before relying on the report's findings, what should the audit team evaluate about the service auditor?$EXPL$, $EXPL$["Whether the service auditor charges fees comparable to other firms in the market", "Whether the service auditor used the same audit software as Harper & Lin", "The competence and independence of the service auditor who performed the engagement", "Whether the service auditor has previously audited Harper & Lin's other clients"]$EXPL$::jsonb, 2, $EXPL$Correct (C): Per AU-C 402.09, the user entity auditor should evaluate the professional competence and independence of the service auditor before relying on the SOC report. This includes considering the service auditor's qualifications and whether they are subject to professional standards and regulatory oversight. Wrong (A): Fee comparability is a business consideration and has no bearing on the reliability of the service auditor's work. Wrong (B): The audit software used is irrelevant to evaluating the service auditor's professional competence and independence. Wrong (D): Whether the service auditor has audited other clients of the same firm is not a relevant factor in assessing competence and independence.$EXPL$, 'easy', 2)
;

COMMIT;
