-- Migration: Question generation — AUD batch 93 (18 questions)
-- Date: 2026-03-25
-- Topic: Terms of Engagement
-- Difficulty: 5E / 9M / 4H
-- Bloom's: L1:5 / L2:5 / L3:5 / L4:3

BEGIN;

INSERT INTO questions (section_id, topic, stem, choices, correct_index, explanation, difficulty, cognitive_level)
VALUES

-- Q1: easy / L1 — Engagement letter and internal audit function
(1, 'Terms of Engagement', 'Which of the following should the engagement letter address regarding the entity''s internal audit function?', '["Whether the external auditor plans to use the work of internal auditors during the engagement", "The internal audit department''s annual budget and staffing levels for the upcoming year", "The specific internal audit reports that will replace substantive testing by the external auditor", "The internal audit function''s authority to issue the external audit opinion on its behalf"]'::jsonb, 0, 'Correct (A): AU-C 210.A23 and AU-C 610 indicate that when the auditor plans to use the work of internal auditors, the engagement terms should address this intent. Although the external auditor retains full responsibility, disclosing planned reliance on internal audit manages expectations.
Wrong (B): The internal audit budget is an operational matter, not something addressed in the external audit engagement letter.
Wrong (C): Internal audit reports do not replace substantive testing; rather, they may supplement the external auditor''s work.
Wrong (D): The internal audit function has no authority to issue the external audit opinion under any circumstances.', 'easy', 1),

-- Q2: easy / L1 — Engagement letter and management representation letter linkage
(1, 'Terms of Engagement', 'What is the relationship between the engagement letter and the management representation letter in an audit?', '["The management representation letter replaces the engagement letter at the end of the audit", "The engagement letter establishes the requirement for management to provide written representations at the conclusion of fieldwork", "The management representation letter must be signed before the engagement letter takes effect", "Both documents serve identical purposes and are interchangeable in practice"]'::jsonb, 1, 'Correct (B): AU-C 210.10 and AU-C 580.09 establish that the engagement letter documents the initial terms, including management''s obligation to provide written representations. While the engagement letter is signed at the outset, the management representation letter is obtained near the conclusion of the audit.
Wrong (A): The management representation letter does not replace the engagement letter; both serve distinct purposes at different stages.
Wrong (C): The engagement letter is effective upon signing, whereas the representation letter is obtained later during audit completion.
Wrong (D): Although both are written agreements, they serve different purposes and are not interchangeable.', 'easy', 1),

-- Q3: medium / L3 — Effect of regulatory requirement on engagement terms scope
(1, 'Terms of Engagement', 'Clearwater Municipal Authority is subject to Government Auditing Standards (GAGAS), which require the auditor to test and report on internal controls over financial reporting. Henderson & Park CPA is engaged for the annual audit. How does this regulatory requirement most likely affect the engagement terms compared to a standard GAAS-only audit?', '["The engagement letter must expand the scope description to include internal control testing and reporting responsibilities mandated by GAGAS", "The engagement letter remains identical to a GAAS audit because internal control testing is always included", "The auditor should decline the engagement because GAGAS and GAAS are incompatible frameworks", "The regulatory requirements should be addressed in a separate addendum signed by the regulatory body"]'::jsonb, 0, 'Correct (A): AU-C 210.A11 requires that when law or regulation prescribes additional audit responsibilities, the engagement letter must describe the expanded scope. Under GAGAS, internal control reporting is required beyond standard GAAS requirements, so the engagement terms must explicitly address this broader scope.
Wrong (B): Although GAAS audits include understanding controls, GAGAS specifically requires testing and reporting on controls, which expands the standard scope.
Wrong (C): GAGAS and GAAS are compatible; GAGAS incorporates GAAS and adds additional requirements.
Wrong (D): The regulatory body does not sign the engagement letter; the expanded scope is addressed directly in the auditor-client agreement.', 'medium', 3),

-- Q4: medium / L2 — Engagement terms for initial audit with opening balances
(1, 'Terms of Engagement', 'Townsend Electronics Inc. is engaging an auditor for the first time after five years without an audit. Prescott & Blake CPA must address opening balances in the engagement terms. What should the engagement letter specifically state about opening balances?', '["The auditor will disclaim an opinion on all comparative financial statements presented", "The predecessor auditor must re-issue their report before the new engagement can begin", "Management acknowledges that the auditor cannot verify the opening balances without prior audit evidence", "The auditor''s procedures will include obtaining sufficient evidence about opening balances to form an opinion on the current period"]'::jsonb, 3, 'Correct (D): AU-C 510.06 requires the auditor to obtain sufficient appropriate evidence about whether opening balances contain misstatements that materially affect the current period. The engagement letter should address this responsibility so management understands the additional procedures that may be required for an initial engagement.
Wrong (A): While a disclaimer is possible if evidence is insufficient, the engagement letter should not presume this outcome before procedures are performed.
Wrong (B): There is no requirement for a predecessor auditor to re-issue a report; however, the successor should communicate with the predecessor per AU-C 210.
Wrong (C): Although obtaining evidence may be challenging, the engagement letter should describe the auditor''s responsibility rather than disclaiming the ability to verify.', 'medium', 2),

-- Q5: medium / L3 — Effect of going concern doubt on engagement terms
(1, 'Terms of Engagement', 'Northbridge Construction LLC is experiencing severe cash flow difficulties and has defaulted on two loan covenants. When Stanton & Voss CPA is negotiating engagement terms for the upcoming audit, management insists that the engagement letter exclude any reference to going concern evaluation. What is the most likely effect of this request on the engagement?', '["The auditor should accommodate management''s request because going concern evaluation is optional under GAAS", "The auditor should refuse to exclude going concern language because AU-C 570 responsibilities cannot be limited by the engagement terms", "The auditor should accept the modified terms and limit procedures to exclude going concern assessment", "The auditor should agree to exclude the language if those charged with governance approve the modification"]'::jsonb, 1, 'Correct (B): AU-C 570.10 requires the auditor to evaluate whether substantial doubt exists about going concern regardless of the engagement terms. Although management may prefer to exclude this language, the auditor''s responsibility under GAAS cannot be contractually restricted.
Wrong (A): Going concern evaluation is a mandatory responsibility under AU-C 570, not optional.
Wrong (C): Accepting modified terms that limit required GAAS procedures would violate the auditor''s professional obligations.
Wrong (D): Governance approval does not override the auditor''s mandatory GAAS responsibilities, whereas the auditor must independently fulfill AU-C 570 requirements.', 'medium', 3),

-- Q6: medium / L3 — Effect of client confidentiality provision on peer review access
(1, 'Terms of Engagement', 'Silverton Retail Group insists that its engagement letter include a strict confidentiality clause prohibiting any third-party access to audit workpapers, including peer reviewers. How does this confidentiality demand most likely affect the engagement terms?', '["The auditor should accept the clause because client confidentiality takes precedence over peer review", "The auditor should explain that professional standards require workpaper access for peer review and that such a restriction is incompatible with a GAAS audit engagement", "The auditor should accept the clause and simply exclude the engagement from the firm''s peer review", "The confidentiality clause is acceptable if the client agrees to compensate the firm for any regulatory penalties"]'::jsonb, 1, 'Correct (B): SQMS No. 1 and AICPA peer review standards require firms to make engagement documentation available for quality review. Although client confidentiality is important, a blanket prohibition on peer reviewer access conflicts with the auditor''s professional obligations and should not be accepted as an engagement term.
Wrong (A): While confidentiality is a fundamental ethical obligation, it does not override the requirement for peer review access to workpapers.
Wrong (C): Excluding an engagement from peer review would violate the firm''s quality management obligations under SQMS No. 1.
Wrong (D): Compensation for penalties does not resolve the underlying conflict with professional standards.', 'medium', 3),

-- Q7: hard / L4 — Evaluating appropriateness of engagement acceptance when framework is questionable
(1, 'Terms of Engagement', 'Granite Peak Holdings LLC wants its financial statements audited using a cash-basis framework, but a review of the entity''s transactions reveals complex accrual-basis items including multi-year construction contracts, derivative instruments, and pension obligations. Evaluate whether Fletcher & Dunn CPA should accept this engagement.', '["Accept the engagement because the client has the right to select any financial reporting framework", "Accept the engagement but require management to disclose all accrual-basis items in the notes", "Evaluate whether the cash-basis framework results in misleading financial statements given the entity''s complexity, and decline if the framework is not acceptable", "Decline the engagement because cash-basis frameworks are never acceptable for audit engagements"]'::jsonb, 2, 'Correct (C): AU-C 210.06(a) establishes that a precondition for the audit is that the financial reporting framework is acceptable. While cash-basis is generally acceptable, the auditor must evaluate whether it results in misleading statements given the entity''s specific circumstances. Complex accrual items may render cash-basis inadequate.
Wrong (A): Although clients select the framework, the auditor must independently assess its acceptability under AU-C 210.
Wrong (B): Note disclosures alone do not cure a fundamentally inappropriate framework choice for the entity.
Wrong (D): Cash-basis frameworks are acceptable for certain entities; however, acceptability depends on the entity''s nature and complexity.', 'hard', 4),

-- Q8: medium / L2 — Engagement terms addressing communication of control deficiencies
(1, 'Terms of Engagement', 'Apex Technology Solutions Inc. engages Whitfield & Crane CPA for its annual audit. The engagement letter includes a provision about communicating internal control deficiencies. Under auditing standards, what must this provision specifically address?', '["The auditor will only communicate material weaknesses verbally to management during exit conferences", "The auditor will prepare a complete redesign of any deficient controls identified during testing", "The auditor commits to identifying every control deficiency that exists within the organization", "The auditor will communicate significant deficiencies and material weaknesses in writing to those charged with governance"]'::jsonb, 3, 'Correct (D): AU-C 210.10 and AU-C 265.10 require the auditor to communicate significant deficiencies and material weaknesses identified during the audit in writing to those charged with governance. The engagement letter should describe this communication responsibility.
Wrong (A): While verbal communication may supplement written reports, AU-C 265 requires written communication of significant deficiencies and material weaknesses.
Wrong (B): Redesigning controls is management''s responsibility, not the auditor''s; the auditor identifies and communicates deficiencies.
Wrong (C): The auditor is not responsible for identifying every deficiency; rather, the audit is designed to identify significant deficiencies and material weaknesses.', 'medium', 2),

-- Q9: hard / L4 — Evaluating engagement terms when management limits communication with governance
(1, 'Terms of Engagement', 'During engagement letter negotiations for Pinnacle Aerospace Corp., the CEO insists that all audit communications be directed exclusively to management, with no direct access to the board''s audit committee. The CEO argues this streamlines communication and avoids unnecessary concern among board members. Evaluate the most appropriate response by Monroe & Associates CPA.', '["Decline to accept or continue the engagement because the restriction on communication with those charged with governance prevents compliance with GAAS requirements", "Accept the restriction because management is the primary client for the audit engagement", "Accept the terms but document the restriction as a scope limitation in the audit report", "Accept the terms and communicate with the audit committee informally outside the engagement letter"]'::jsonb, 0, 'Correct (A): AU-C 260.12 requires direct communication between the auditor and those charged with governance, including the audit committee. Although management may prefer to control information flow, restricting this communication prevents the auditor from fulfilling mandatory GAAS requirements, making the engagement unacceptable.
Wrong (B): While management is an important party, those charged with governance have oversight responsibility, and GAAS requires direct communication with them.
Wrong (C): This is not a scope limitation in the traditional sense; rather, it is a precondition failure that prevents engagement acceptance.
Wrong (D): Informal communication does not satisfy the AU-C 260 requirement for formal communication with governance.', 'hard', 4),

-- Q10: hard / L3 — Analyzing effect of significant unusual transaction on engagement terms
(1, 'Terms of Engagement', 'Shortly after signing the engagement letter for Oakmont Pharmaceuticals Inc., the auditor at Jensen & Cross CPA learns that the client completed a $200 million related party merger that was not disclosed during engagement acceptance discussions. The original engagement terms were based on a standalone entity audit. What is the most likely effect on the engagement?', '["The auditor should continue under the original terms because the engagement letter was already signed", "The auditor should reassess whether the engagement terms adequately address the expanded complexity, revise the terms to include group audit considerations, and re-evaluate management''s integrity", "The auditor should immediately resign from the engagement without further assessment of the situation", "The auditor should issue a scope limitation in the current report and address the terms in next year''s engagement"]'::jsonb, 1, 'Correct (B): AU-C 210.13 requires the auditor to assess whether changed circumstances necessitate revised engagement terms. A $200 million undisclosed merger fundamentally changes the audit scope and raises integrity concerns. Although the letter was signed, the auditor must evaluate whether the preconditions for the audit still exist.
Wrong (A): A signed engagement letter does not prevent revision when material circumstances change after acceptance.
Wrong (C): While resignation may ultimately be warranted, the auditor should first assess the situation and communicate with governance rather than immediately resigning.
Wrong (D): Deferring the issue to the next year is inappropriate when the current engagement terms are inadequate.', 'hard', 3),

-- Q11: easy / L1 — Engagement letter reference to applicable auditing standards
(1, 'Terms of Engagement', 'Why must the engagement letter identify the specific auditing standards under which the audit will be conducted?', '["To satisfy a marketing requirement that differentiates the firm from competitors in the market", "To enable management to select which specific audit procedures the auditor will perform during fieldwork", "To establish the professional framework that governs the auditor''s responsibilities and procedures", "To allow the client to substitute an alternative set of standards after the engagement has commenced"]'::jsonb, 2, 'Correct (C): AU-C 210.10(a) requires the engagement letter to reference the applicable auditing standards to establish the framework governing the audit. This ensures both parties understand the professional basis for the auditor''s work and the level of assurance provided.
Wrong (A): While the engagement letter is a professional document, identifying standards serves a substantive purpose rather than a marketing function.
Wrong (B): Although the standards are identified, management does not select audit procedures — that is the auditor''s responsibility.
Wrong (D): The applicable standards are determined at acceptance; they cannot be unilaterally substituted by the client mid-engagement.', 'easy', 1),

-- Q12: medium / L2 — Applying engagement terms for compilation engagement comparison
(1, 'Terms of Engagement', 'Pacific Coast Bakeries LLC engages Barrett & Sons CPA to perform a compilation of its financial statements under SSARS. Compared to an audit engagement letter, what key difference exists in the compilation engagement terms?', '["The compilation terms require the accountant to obtain reasonable assurance about the financial statements", "The compilation terms must include a detailed description of internal control testing procedures to be performed", "The compilation terms require communication with a predecessor accountant before accepting the engagement", "The compilation terms state that the accountant will not express an opinion or provide any assurance on the financial statements"]'::jsonb, 3, 'Correct (D): AR-C 80.11 requires the compilation engagement letter to state that the accountant will not express an opinion or provide any assurance. This is the key distinction from an audit, whereas an audit engagement letter describes the objective of obtaining reasonable assurance.
Wrong (A): Reasonable assurance is the objective of an audit engagement under AU-C 200, not a compilation under SSARS.
Wrong (B): Although internal control understanding may be relevant in an audit, compilation engagements do not require internal control testing.
Wrong (C): While predecessor communication is required for audits under AU-C 210, it is not a required element of SSARS compilation engagement terms.', 'medium', 2),

-- Q13: hard / L4 — Evaluating terms when management refuses to acknowledge fraud responsibility
(1, 'Terms of Engagement', 'During engagement letter negotiations for Crossroads Manufacturing Inc., management refuses to include language acknowledging its responsibility for designing controls to prevent and detect fraud. Management argues that fraud prevention is primarily the auditor''s responsibility. Evaluate the most appropriate course of action for Blackwell & Keane CPA.', '["Accept the modified terms because fraud detection is indeed the auditor''s primary responsibility during an audit", "Decline the engagement or withdraw because management''s refusal to acknowledge a precondition for the audit under AU-C 210 prevents the auditor from accepting the engagement", "Accept the engagement without the fraud language and address the issue in the management representation letter instead", "Accept the engagement and simply perform additional fraud-related testing to compensate for the missing acknowledgment"]'::jsonb, 1, 'Correct (B): AU-C 210.06(b)(ii) requires management to acknowledge its responsibility for internal control, including controls designed to prevent and detect fraud, as a precondition for the audit. Although the auditor has fraud-related responsibilities under AU-C 240, refusing to accept this precondition means the engagement cannot proceed.
Wrong (A): While the auditor has responsibilities under AU-C 240, fraud prevention through internal controls is management''s responsibility, not the auditor''s.
Wrong (C): The management representation letter cannot substitute for a precondition that must be established before accepting the engagement.
Wrong (D): Additional testing does not resolve the fundamental issue that management has not acknowledged a required precondition.', 'hard', 4),

-- Q14: medium / L3 — Effect of interim date change on engagement terms
(1, 'Terms of Engagement', 'Harper Industries Corp. originally engaged Waverly & Dunn CPA to audit financial statements for the year ending December 31, 2025. In October 2025, management announces a change in fiscal year-end to March 31, 2026, creating a 15-month transition period. How does this change most likely affect the engagement terms?', '["The original engagement letter automatically extends to cover the new fiscal year-end date without modification", "The auditor should issue a new or amended engagement letter reflecting the changed reporting period and any expanded scope implications", "The auditor must decline the engagement because a mid-engagement fiscal year change is prohibited", "The original terms remain valid because only the report date changes and the audit scope is unaffected"]'::jsonb, 1, 'Correct (B): AU-C 210.13 requires the auditor to assess whether circumstances warrant revised engagement terms. A fiscal year-end change alters the reporting period, potentially affects the scope and timing of procedures, and requires updated terms. Although the original engagement letter was valid, the changed circumstances necessitate revision.
Wrong (A): Engagement letters do not automatically extend to cover a different reporting period than originally specified.
Wrong (C): While unusual, a mid-engagement fiscal year change is not prohibited; rather, it requires revised terms and careful planning.
Wrong (D): A 15-month transition period significantly affects audit scope, timing, and procedures beyond just the report date.', 'medium', 3),

-- Q15: easy / L1 — Engagement letter and auditor independence statement
(1, 'Terms of Engagement', 'What is the purpose of including a statement about the auditor''s independence in the engagement letter?', '["To waive the independence requirement for the duration of the current engagement period", "To establish that independence is only required during the reporting phase of the engagement", "To confirm that the auditor meets the independence requirements necessary for conducting the audit", "To transfer responsibility for monitoring auditor independence from the firm to the client"]'::jsonb, 2, 'Correct (C): AU-C 210.A20 and AICPA Code ET 1.200 require auditors to be independent of the client. The engagement letter''s independence statement confirms the auditor meets these requirements, ensuring both parties understand this fundamental prerequisite.
Wrong (A): Independence cannot be waived; it is a mandatory requirement for audit engagements under AICPA standards.
Wrong (B): Independence is required throughout the entire engagement period and the period covered by the financial statements, not just during reporting.
Wrong (D): Although the engagement letter references independence, monitoring remains the firm''s responsibility under SQMS No. 1.', 'easy', 1),

-- Q16: medium / L2 — Engagement terms addressing electronic delivery of audit report
(1, 'Terms of Engagement', 'Crestview Financial Services LLC requests that Aldridge & Park CPA deliver the audit report and audited financial statements exclusively in electronic format. What should the engagement letter address regarding this delivery method?', '["Electronic delivery is prohibited under GAAS and the report must be delivered in physical form only", "Electronic delivery eliminates the need for the auditor to retain copies of the issued report", "The engagement letter need not address delivery format because it is a purely administrative matter", "The engagement terms should specify the agreed-upon format, delivery method, and any limitations on redistribution"]'::jsonb, 3, 'Correct (D): AU-C 210.A26 acknowledges that the engagement terms may address the form and method of communication, including electronic delivery. Although GAAS does not prohibit electronic delivery, the engagement letter should specify the format, delivery mechanism, and any restrictions on redistribution.
Wrong (A): GAAS does not prohibit electronic delivery; rather, the auditor and client may agree on the delivery method in the engagement terms.
Wrong (B): Regardless of delivery format, the auditor must retain documentation including the issued report per AU-C 230.
Wrong (C): While delivery format might seem administrative, specifying it in the engagement letter prevents misunderstandings about report distribution.', 'medium', 2),

-- Q17: easy / L1 — Engagement letter and fee dispute resolution
(1, 'Terms of Engagement', 'What is the primary reason engagement letters typically include provisions addressing fee disputes or arbitration?', '["To prevent the client from hiring a different auditor in subsequent periods after the engagement", "To establish a mechanism for resolving disagreements about fees without litigation affecting the audit", "To require the client to prepay the full audit fee before any fieldwork can begin", "To transfer all billing authority from the audit firm to the client''s accounts payable department"]'::jsonb, 1, 'Correct (B): AU-C 210.A26 permits engagement letters to address fee arrangements and dispute resolution mechanisms. Although not required by GAAS, including arbitration or mediation provisions establishes a process for resolving fee disagreements that does not compromise the professional relationship.
Wrong (A): Preventing the client from switching auditors is not the purpose of fee dispute provisions; engagement letters do not restrict the client''s right to change auditors.
Wrong (C): Prepayment is not a standard engagement letter requirement; fee terms vary by arrangement.
Wrong (D): Billing authority remains with the audit firm; the engagement letter does not transfer this to the client.', 'easy', 1),

-- Q18: medium / L2 — Applying terms when engagement involves other auditors for components
(1, 'Terms of Engagement', 'Summit Regional Healthcare Network operates twelve clinics, three of which are audited by Crawford & Associates CPA while Ellison & Moore CPA serves as the group auditor. When drafting engagement terms, what must Ellison & Moore specifically include regarding the division of responsibilities?', '["A statement that the group auditor accepts no responsibility for the work performed by Crawford & Associates", "The engagement terms should describe the group auditor''s planned involvement with the component auditor and the nature of planned communications", "A requirement that Crawford & Associates sign the group audit engagement letter as a co-auditor of the network", "A provision requiring Crawford & Associates to obtain separate client consent before sharing workpapers with the group auditor"]'::jsonb, 1, 'Correct (B): AU-C 600.14 and AU-C 210 require the group engagement letter to address the group auditor''s planned involvement with component auditors, including the nature and timing of communications. Although Crawford & Associates has separate responsibilities, the group auditor must describe its oversight role in the engagement terms.
Wrong (A): The group auditor cannot disclaim all responsibility for components; rather, AU-C 600 requires the group auditor to be sufficiently involved.
Wrong (C): Component auditors do not sign the group engagement letter as co-auditors; they have separate engagement arrangements with their component clients.
Wrong (D): While workpaper access may require coordination, this provision is not the primary engagement term requirement under AU-C 600.', 'medium', 2)
;

COMMIT;
