-- Migration: Question generation — ISC batch 27 (18 questions)
-- Date: 2026-03-24
-- Topic: IT Audit Frameworks
-- Difficulty: 5E / 9M / 4H
-- Bloom's: L1:4 / L2:6 / L3:5 / L4:3

BEGIN;

INSERT INTO questions (section_id, topic, stem, choices, correct_index, explanation, difficulty, cognitive_level)
VALUES

-- Q1: medium / L3 — COBIT EDM05 ensured stakeholder engagement
(5, 'IT Audit Frameworks', 'Birchwood Pharmaceuticals'' board of directors receives quarterly IT performance dashboards showing project completion rates and uptime metrics. However, IT stakeholders — including regulators, business unit leaders, and external auditors — report that their information needs are not being addressed and that communication about IT governance decisions is one-directional. Under COBIT 2019, which governance objective should the board activate to resolve this stakeholder communication gap?', '["EDM05 — Ensured Stakeholder Engagement", "MEA01 — Managed Performance and Conformance Monitoring", "APO08 — Managed Relationships", "EDM02 — Ensured Benefits Delivery"]'::jsonb, 0, 'Correct (A): COBIT 2019 EDM05 (Ensured Stakeholder Engagement) requires the governance body to ensure that stakeholders are identified, their information needs are understood, and communication is bidirectional. The scenario describes a failure in stakeholder engagement at the governance level. Wrong (B): MEA01 monitors whether processes meet performance targets, but it does not address the broader stakeholder communication and engagement gap described. Wrong (C): APO08 manages relationships at the management level, but the scenario describes a governance-level deficiency requiring board action under EDM05. Wrong (D): EDM02 ensures IT investments deliver expected business value, not that stakeholders are properly engaged in governance communication.', 'medium', 3),

-- Q2: medium / L3 — ITIL 4 keep it simple and practical
(5, 'IT Audit Frameworks', 'Garnet Systems recently added seven approval layers to its service request process after a single security incident. Internal users now wait an average of 14 business days for routine requests that previously took two days. The IT director reviews the process and finds that five of the seven approval layers add no measurable security value. The director proposes removing the unnecessary layers while retaining the two that address the original vulnerability. Which ITIL 4 guiding principle most directly supports this decision?', '["Start where you are", "Focus on value", "Keep it simple and practical", "Progress iteratively with feedback"]'::jsonb, 2, 'Correct (C): ITIL 4''s "keep it simple and practical" principle emphasizes eliminating processes, steps, or controls that do not produce value. Removing five approval layers that add no measurable security benefit while retaining the two that do is a direct application of simplifying without sacrificing necessary outcomes. Wrong (A): "Start where you are" advises assessing the current state before making changes, but the director has already assessed the process and identified the wasteful layers. Wrong (B): "Focus on value" emphasizes that activities should map to stakeholder value, which is related but less specific than the principle of eliminating unnecessary complexity. Wrong (D): "Progress iteratively with feedback" recommends working in small increments with feedback loops, not streamlining an over-engineered process.', 'medium', 3),

-- Q3: hard / L3 — NIST RMF Step 5 (Assess) specifics
(5, 'IT Audit Frameworks', 'Kingfisher Mutual Insurance has deployed security controls for its claims processing system, categorized as moderate impact under FIPS 199. An independent assessment team tests each control by examining documentation, interviewing system administrators, and running automated vulnerability scans. The team determines that 38 of 41 controls are implemented correctly and operating as intended, but three controls — session timeout enforcement, audit log retention, and account lockout thresholds — fail to produce the expected outcomes. Under NIST SP 800-37, which RMF step is the assessment team performing?', '["Implement", "Monitor", "Assess", "Authorize"]'::jsonb, 2, 'Correct (C): NIST SP 800-37 Step 5 (Assess) involves evaluating security controls to determine whether they are implemented correctly, operating as intended, and producing the desired outcome with respect to meeting the security requirements. Testing controls through documentation review, interviews, and automated scanning are assessment activities. Wrong (A): The Implement step (Step 4) involves deploying and configuring controls, which has already been completed in this scenario. Wrong (B): The Monitor step (Step 7) involves ongoing post-authorization surveillance, not the initial pre-authorization evaluation of control effectiveness. Wrong (D): The Authorize step (Step 6) is the senior official''s risk-based decision to grant ATO, which occurs after assessment is complete.', 'hard', 3),

-- Q4: medium / L2 — COBIT DSS05 Managed Security Services
(5, 'IT Audit Frameworks', 'Pembrook Technologies'' security operations team manages endpoint protection across 3,000 workstations, monitors network traffic for intrusions using a SIEM platform, and administers identity and access management tools that control user authentication to production systems. Under COBIT 2019, which management objective governs these day-to-day security operations?', '["APO13 — Managed Security", "MEA02 — Managed System of Internal Control", "BAI06 — Managed IT Changes", "DSS05 — Managed Security Services"]'::jsonb, 3, 'Correct (D): COBIT 2019 DSS05 (Managed Security Services) within the Deliver, Service, and Support domain governs the operational execution of security activities, including endpoint protection, network monitoring, intrusion detection, and identity and access management. Wrong (A): APO13 (Managed Security) establishes the security management system, policies, and strategy at the planning level, not the day-to-day operational execution of security services. Wrong (B): MEA02 monitors and evaluates internal control effectiveness, not the execution of security operations. Wrong (C): BAI06 governs the IT change management process, which is unrelated to ongoing security operations such as endpoint protection and network monitoring.', 'medium', 2),

-- Q5: hard / L4 — COBIT governance distinct from management
(5, 'IT Audit Frameworks', 'Summerfield Holdings'' CIO presents two agenda items to the board. Item 1: a proposal asking the board to evaluate whether the organization''s IT investment portfolio is delivering value aligned with the five-year strategic plan. Item 2: a request for the board to approve the technical specifications for a new ERP implementation, including vendor selection criteria and deployment timelines. An IS auditor reviewing the governance structure should flag which item as a misallocation of board responsibility?', '["Item 1 is misallocated because investment evaluation is a management function", "Item 2 is misallocated because technical specifications and vendor selection are management functions, not governance", "Both items are governance responsibilities because IT spending decisions require board approval", "Neither item is misallocated because the board should approve all IT-related decisions"]'::jsonb, 1, 'Correct (B): Under COBIT 2019''s "governance distinct from management" principle, governance evaluates, directs, and monitors while management plans, builds, runs, and monitors. Technical specifications and vendor selection are management activities (BAI domain), not governance activities. The board should set direction and monitor outcomes, not approve operational details. Wrong (A): Evaluating whether IT investments deliver strategic value is a governance function under EDM02 (Ensured Benefits Delivery) and is appropriately allocated to the board. Wrong (C): The principle specifically separates governance from management; not all IT spending decisions require board-level approval. Wrong (D): COBIT 2019 explicitly states that governance and management serve different purposes and that operational management decisions should not be escalated to the governance level.', 'hard', 4),

-- Q6: medium / L2 — COBIT MEA01 managed performance
(5, 'IT Audit Frameworks', 'Ironwood Capital Services establishes key performance indicators for its IT processes, collects monthly metrics on system availability and incident resolution times, and compares actual performance against defined targets. When variances exceed predefined thresholds, management investigates the root cause. Under COBIT 2019, which management objective governs these performance monitoring activities?', '["DSS01 — Managed Operations", "MEA01 — Managed Performance and Conformance Monitoring", "APO09 — Managed Service Level Agreements", "EDM02 — Ensured Benefits Delivery"]'::jsonb, 1, 'Correct (B): COBIT 2019 MEA01 (Managed Performance and Conformance Monitoring) within the Monitor, Evaluate, and Assess domain governs the collection of performance metrics, comparison against defined targets, and investigation of variances to ensure IT processes meet their objectives. Wrong (A): DSS01 (Managed Operations) executes day-to-day IT operations but does not govern the systematic monitoring and evaluation of process performance against targets. Wrong (C): APO09 manages service level agreements and service expectations, not the broader monitoring of all IT process performance metrics. Wrong (D): EDM02 is a governance objective focused on ensuring IT investments deliver value at the board level, not a management-level performance monitoring function.', 'medium', 2),

-- Q7: medium / L3 — Qualitative risk matrix mechanics
(5, 'IT Audit Frameworks', 'Thornhill Regional Hospital''s IT risk committee uses a 3x3 qualitative risk matrix to prioritize 25 identified risks. The committee rates the probability of a ransomware attack on the electronic health records system as high and the potential impact as high. Using the standard risk matrix approach, how should this risk be classified?', '["Medium risk — high likelihood is offset by existing controls", "Low risk — the hospital''s insurance coverage reduces the financial exposure", "Critical risk — high likelihood combined with high impact produces the highest risk rating", "Moderate risk — qualitative assessments inherently produce moderate classifications"]'::jsonb, 2, 'Correct (C): In a standard qualitative risk matrix, risk is determined by plotting likelihood against impact. High likelihood combined with high impact produces a critical (or highest-tier) risk classification, requiring immediate attention and prioritized resource allocation. Wrong (A): Existing controls may reduce residual risk, but the inherent risk classification on the matrix is determined solely by the assessed likelihood and impact ratings before control adjustments. Wrong (B): Insurance transfers financial consequences but does not change the risk classification on the matrix, which reflects likelihood and impact independent of transfer mechanisms. Wrong (D): There is no inherent limitation in qualitative assessments that caps ratings at moderate; the matrix produces the full range of classifications based on the input ratings.', 'medium', 3),

-- Q8: easy / L2 — ITIL 4 practices definition
(5, 'IT Audit Frameworks', 'ITIL 4 replaced the term "processes" with "practices" to reflect a broader approach to organizing work. What do practices encompass in ITIL 4 that processes alone did not?', '["Only automated workflows and technology tools", "Only governance policies and compliance requirements", "Only financial management and budgeting activities", "Sets of organizational resources designed for performing work, including people, technology, information, and partners"]'::jsonb, 3, 'Correct (D): ITIL 4 defines practices as sets of organizational resources designed for performing work or accomplishing an objective. This broader definition encompasses people, technology, information, value streams, and partners — not just the sequential activities implied by the term "processes." Wrong (A): Practices include automated tools but also encompass people, information, partners, and other organizational resources. Wrong (B): Practices are not limited to governance policies; they include all organizational resources needed to perform work across IT service management. Wrong (C): Financial management is one specific practice, but the concept of practices broadly covers all organizational resources for performing any type of IT service management work.', 'easy', 2),

-- Q9: hard / L4 — ISO 27001 and COBIT integration evaluation
(5, 'IT Audit Frameworks', 'Ridgewater Banking Group currently uses COBIT 2019 for IT governance and ITIL 4 for service management. The CISO proposes adding ISO 27001 certification for the information security management system. The CTO questions whether ISO 27001 is redundant given that COBIT APO13 already addresses managed security. An IS auditor must evaluate the CTO''s concern. Which response most accurately distinguishes the two frameworks'' roles?', '["ISO 27001 provides certifiable ISMS requirements while COBIT APO13 provides governance-level security objectives — they serve complementary purposes at different levels", "The CTO is correct — COBIT APO13 fully replaces the need for ISO 27001 certification", "ISO 27001 focuses exclusively on physical security controls that COBIT does not address", "COBIT 2019 and ISO 27001 are competing frameworks that cannot be implemented simultaneously"]'::jsonb, 0, 'Correct (A): ISO 27001 provides an internationally certifiable set of requirements for establishing, implementing, maintaining, and continually improving an ISMS, while COBIT APO13 provides governance-level objectives for managed security within the broader IT governance framework. They operate at different levels and serve complementary purposes. Wrong (B): COBIT APO13 defines governance objectives for security but does not provide the detailed, certifiable ISMS requirements that ISO 27001 specifies; they are not substitutes. Wrong (C): ISO 27001 addresses all aspects of information security management, not just physical security; it covers organizational, people, physical, and technological controls. Wrong (D): COBIT and ISO 27001 are designed to complement each other; many organizations implement both simultaneously to address governance and certification requirements.', 'hard', 4),

-- Q10: easy / L1 — COBIT EDM05 stakeholder engagement definition
(5, 'IT Audit Frameworks', 'Which COBIT 2019 governance objective specifically addresses ensuring that IT stakeholders are identified and that governance communication is transparent and bidirectional?', '["EDM02 — Ensured Benefits Delivery", "EDM05 — Ensured Stakeholder Engagement", "EDM03 — Ensured Risk Optimization", "EDM01 — Ensured Governance Framework Setting and Maintenance"]'::jsonb, 1, 'Correct (B): COBIT 2019 EDM05 (Ensured Stakeholder Engagement) ensures that enterprise IT stakeholders are identified, their information needs are understood, and governance communication is transparent and bidirectional. Wrong (A): EDM02 ensures IT investments deliver expected business value, not stakeholder engagement and communication. Wrong (C): EDM03 ensures IT-related risk does not exceed the organization''s risk appetite, addressing risk optimization rather than stakeholder communication. Wrong (D): EDM01 focuses on establishing and maintaining the governance framework itself, not on stakeholder identification and engagement.', 'easy', 1),

-- Q11: hard / L4 — COSO risk assessment mapped to NIST RMF and COBIT APO12
(5, 'IT Audit Frameworks', 'Greystone Financial Corporation''s external auditor is evaluating COSO''s risk assessment component as applied to the IT environment. The auditor notes that IT risk identification uses threat modeling and vulnerability scans (aligned with NIST RMF Step 2-3 practices), while risk evaluation uses COBIT APO12 processes to quantify and prioritize IT risks against enterprise risk appetite. A junior auditor asks why both NIST and COBIT are referenced when COSO already requires risk assessment. What is the most accurate explanation?', '["NIST and COBIT are unnecessary because COSO''s risk assessment component provides sufficient IT-specific guidance on its own", "COSO provides the conceptual framework for what risk assessment should achieve, while NIST and COBIT provide the implementation-level IT guidance for how to perform it", "NIST RMF replaces COSO''s risk assessment component entirely in IT environments", "COBIT APO12 is only relevant for organizations that do not follow COSO for internal control evaluation"]'::jsonb, 1, 'Correct (B): COSO provides the conceptual basis defining what internal controls and risk assessment should achieve. NIST RMF and COBIT provide implementation-level IT guidance explaining how to perform risk identification, categorization, and evaluation in technology environments. They complement COSO rather than replacing it. Wrong (A): COSO is a high-level internal control framework that does not provide detailed IT-specific risk assessment procedures; organizations need implementation frameworks like NIST and COBIT for IT-specific guidance. Wrong (C): NIST RMF does not replace COSO; it provides IT-specific implementation procedures that operationalize COSO''s risk assessment requirements in technology environments. Wrong (D): COBIT APO12 complements COSO and is used alongside it, not as an alternative; organizations following COSO for internal control evaluation frequently use COBIT for IT-specific implementation.', 'hard', 4),

-- Q12: medium / L3 — COBIT design factor: role of IT
(5, 'IT Audit Frameworks', 'Mapleton Regional Bank classifies IT as "strategic" — technology drives competitive advantage, enables new product offerings, and differentiates the bank from competitors. Under COBIT 2019, the role of IT is one of the design factors used to tailor the governance system. How does a strategic IT role affect the governance system design compared to a support IT role?', '["A strategic IT role requires fewer governance processes because IT decisions can be delegated entirely to technical staff", "A strategic IT role eliminates the need for the MEA domain because strategic IT is self-monitoring", "Both roles require identical governance systems because COBIT 2019 mandates the same 40 objectives regardless of context", "A strategic IT role requires more comprehensive governance coverage, higher capability targets, and greater board involvement in IT decision-making"]'::jsonb, 3, 'Correct (D): Under COBIT 2019, design factors — including the role of IT — determine the scope and intensity of the governance system. When IT is strategic (driving competitive advantage), the governance system requires broader coverage of objectives, higher target capability levels, and greater governance-level involvement compared to when IT serves a support function. Wrong (A): A strategic IT role requires more governance oversight, not less, because technology decisions directly affect competitive positioning and enterprise value. Wrong (B): The MEA domain is essential regardless of IT''s role; monitoring and evaluation become more critical when IT is strategic. Wrong (C): COBIT 2019''s "tailored to enterprise needs" principle explicitly requires adjusting the governance system based on design factors including the role of IT.', 'medium', 3),

-- Q13: medium / L2 — ITIL 4 deliver and support activity
(5, 'IT Audit Frameworks', 'Oakdale Credit Union''s IT team ensures that its core banking application meets agreed service levels by processing transactions within expected response times, resolving user-reported issues through the service desk, and maintaining system availability during business hours. In ITIL 4''s service value chain, which activity describes this ongoing service delivery work?', '["The deliver and support activity", "The design and transition activity", "The obtain/build activity", "The engage activity"]'::jsonb, 0, 'Correct (A): ITIL 4''s deliver and support value chain activity ensures that services are delivered and supported according to agreed specifications and stakeholder expectations. Processing transactions, resolving issues, and maintaining availability are all delivery and support functions. Wrong (B): The design and transition activity ensures products and services meet quality, cost, and time-to-market expectations before entering production, not ongoing service delivery. Wrong (C): The obtain/build activity ensures service components are available when needed and meet specifications, focusing on acquisition and development rather than ongoing delivery. Wrong (D): The engage activity involves understanding stakeholder needs and maintaining transparency, not the operational delivery of services.', 'medium', 2),

-- Q14: medium / L2 — ITIL 4 obtain/build activity
(5, 'IT Audit Frameworks', 'Stratford Insurance''s IT team procures a new claims management server, configures it to meet agreed specifications, integrates it with the existing infrastructure, and ensures all hardware and software components are available before deployment. In ITIL 4''s service value chain, which activity encompasses this work?', '["The plan activity", "The obtain/build activity", "The deliver and support activity", "The improve activity"]'::jsonb, 1, 'Correct (B): ITIL 4''s obtain/build value chain activity ensures service components are available when and where needed, meeting agreed specifications. Procuring hardware, configuring systems, and integrating components before deployment are obtain/build activities. Wrong (A): The plan activity ensures shared understanding of vision and direction for all products and services but does not cover procurement and configuration of specific components. Wrong (C): The deliver and support activity covers ongoing service delivery after deployment, not the procurement and preparation of service components. Wrong (D): The improve activity focuses on continually enhancing products, services, and practices, not on acquiring and building specific service components.', 'medium', 2),

-- Q15: easy / L1 — ISO 38500 purpose
(5, 'IT Audit Frameworks', 'Which international standard provides principles for the corporate governance of information technology, complementing COBIT 2019 at the board level?', '["ISO 27001", "ISO 20000", "ISO 38500", "ISO 31000"]'::jsonb, 2, 'Correct (C): ISO 38500 provides principles for the corporate governance of IT, guiding board-level oversight of technology. It complements COBIT 2019 by establishing high-level governance principles that COBIT operationalizes through its detailed objectives. Wrong (A): ISO 27001 provides requirements for an information security management system, not corporate IT governance principles. Wrong (B): ISO 20000 provides requirements for an IT service management system, complementing ITIL 4 rather than addressing board-level IT governance. Wrong (D): ISO 31000 provides guidelines for risk management across all organizational activities, not specifically corporate IT governance.', 'easy', 1),

-- Q16: easy / L1 — COBIT Level 0 (Incomplete) definition
(5, 'IT Audit Frameworks', 'An IS auditor assessing an organization''s IT change management finds no evidence that the process exists or produces any results. Under the COBIT 2019 CMMI-based capability model, which rating applies?', '["Level 1 (Performed) — the process partially achieves its goals", "Level 2 (Managed) — the process has documented procedures", "Level 3 (Defined) — the process follows an organizational standard", "Level 0 (Incomplete) — the process is not implemented or fails to achieve its purpose"]'::jsonb, 3, 'Correct (D): In the COBIT 2019 CMMI-based capability model, Level 0 (Incomplete) means the process is either not implemented at all or fails to achieve its intended purpose. No evidence of systematic achievement of process objectives qualifies as Level 0. Wrong (A): Level 1 (Performed) requires that the process at least achieves its purpose, even if informally; the absence of any results rules this out. Wrong (B): Level 2 (Managed) requires that the process is planned, monitored, and adjusted with managed work products, which is far beyond the scenario described. Wrong (C): Level 3 (Defined) requires a process defined as an organizational standard, which does not apply when no process exists.', 'easy', 1),

-- Q17: easy / L1 — COBIT Level 5 (Optimizing) definition
(5, 'IT Audit Frameworks', 'To advance from COBIT 2019 capability Level 4 (Quantitative) to Level 5 (Optimizing), what additional capability must an organization demonstrate?', '["Systematic continuous improvement driven by quantitative performance analysis and innovation", "Documentation of the process as a formal organizational standard", "Assignment of a process owner with planning and monitoring responsibilities", "Collection of performance metrics and comparison against defined targets"]'::jsonb, 0, 'Correct (A): COBIT 2019 Level 5 (Optimizing) requires systematic continuous improvement based on quantitative analysis and innovation feedback loops. Moving from Level 4 to Level 5 means the organization uses its quantitative data to proactively drive process innovation and optimization. Wrong (B): Documenting the process as a formal organizational standard is the requirement for advancing to Level 3 (Defined), not Level 5. Wrong (C): Assigning a process owner with planning and monitoring responsibilities is characteristic of Level 2 (Managed), not the Level 4-to-5 transition. Wrong (D): Collecting metrics and comparing against targets is the hallmark of Level 4 (Quantitative), which is the starting point for this advancement, not the destination.', 'easy', 1),

-- Q18: medium / L2 — ITIL 4 plan value chain activity
(5, 'IT Audit Frameworks', 'Clarkfield Municipal Water Authority''s IT leadership team develops a shared understanding of the organization''s technology vision, assesses the current state of all IT services, and establishes improvement direction for the coming fiscal year. In ITIL 4''s service value chain, which activity describes this strategic planning work?', '["The engage activity", "The plan activity", "The improve activity", "The design and transition activity"]'::jsonb, 1, 'Correct (B): ITIL 4''s plan value chain activity ensures a shared understanding of the vision, current status, and improvement direction for all four dimensions and all products and services. Developing a technology vision, assessing current state, and setting direction are planning activities. Wrong (A): The engage activity focuses on understanding stakeholder needs and maintaining ongoing transparency, not on establishing organizational vision and strategic direction. Wrong (C): The improve activity focuses on continually enhancing existing products, services, and practices, not on establishing the overarching vision and direction. Wrong (D): The design and transition activity ensures specific products and services meet stakeholder expectations before entering production, not organizational-level strategic planning.', 'medium', 2)
;

COMMIT;
