-- Migration: Question generation — REG batch 60 (10 questions)
-- Date: 2026-03-24
-- Topic: Government Regulation of Business
-- Difficulty: 3E / 5M / 2H
-- Bloom's: L1:3 / L2:2 / L3:3 / L4:2

BEGIN;

INSERT INTO questions (section_id, topic, stem, choices, correct_index, explanation, difficulty, cognitive_level)
VALUES

-- Q1: medium / L3 — UCC Section 2-207 battle of the forms
(3, 'Government Regulation of Business', 'Greystone Hardware LLC sends a purchase order for 500 units of industrial fasteners to Titan Supply Co. on March 1, 2026. Titan responds with an acknowledgment that matches all material terms but adds a clause requiring arbitration for disputes. Both parties are merchants. Under UCC Section 2-207, what is the most likely effect of Titan''s additional term?', '["The arbitration clause becomes part of the contract unless Greystone objects within a reasonable time", "No contract is formed because Titan''s response is a counteroffer", "The arbitration clause is automatically excluded because it was not in the original offer", "The contract is formed only on the terms of Greystone''s original purchase order"]'::jsonb, 0, 'Correct (A): UCC Section 2-207(2). Between merchants, additional terms in an acceptance become part of the contract unless they materially alter it, the offer expressly limits acceptance to its terms, or the offeror objects within a reasonable time. An arbitration clause between merchants may become part of the contract if no timely objection is raised. Wrong (B): Under UCC 2-207, a definite expression of acceptance with additional terms still forms a contract, unlike the common law mirror image rule. Wrong (C): Additional terms are not automatically excluded; their inclusion depends on merchant status and whether the term materially alters the contract. Wrong (D): The contract may include additional terms between merchants unless the offeror objects; it is not limited to the original terms alone.', 'medium', 3),

-- Q2: medium / L3 — Respondeat superior scope of employment
(3, 'Government Regulation of Business', 'Rivera, a delivery driver for Cascade Logistics Inc., causes an accident while making an unauthorized personal detour to pick up lunch during a scheduled delivery route on April 5, 2026. The injured third party sues Cascade Logistics. Under the doctrine of respondeat superior, which factor is most critical in determining whether Cascade is liable?', '["Whether Rivera had express permission to take the detour", "Whether Rivera''s detour constituted a minor deviation or a complete departure from the scope of employment", "Whether Cascade Logistics carried adequate insurance coverage", "Whether the third party was aware that Rivera was an employee of Cascade"]'::jsonb, 1, 'Correct (B): Under the respondeat superior doctrine, a principal is liable for torts committed by an agent within the scope of employment. Courts distinguish between a minor detour (employer remains liable) and a substantial frolic (employer not liable). The degree of departure from authorized duties is the critical factor. Wrong (A): Express permission is relevant but not dispositive; implied authority and scope of employment are the controlling standards for vicarious liability. Wrong (C): Insurance coverage is a financial consideration, not a legal factor in determining vicarious liability under respondeat superior. Wrong (D): The third party''s knowledge of the employment relationship does not affect whether respondeat superior liability attaches.', 'medium', 3),

-- Q3: medium / L2 — UCC Article 9 perfection of security interest
(3, 'Government Regulation of Business', 'National Bank lends $250,000 to Whitfield Manufacturing on June 1, 2026, and takes a security interest in Whitfield''s equipment. National Bank files a financing statement with the appropriate state office. Which of the following best describes the effect of filing the financing statement under UCC Article 9?', '["It creates the security interest between the parties", "It satisfies the statute of frauds for the loan agreement", "It perfects the security interest and establishes priority over most subsequent creditors", "It ensures full recovery of the loan amount upon default"]'::jsonb, 2, 'Correct (C): UCC Article 9 requires perfection of a security interest, typically by filing a financing statement, to establish the creditor''s priority over other creditors. Perfection puts third parties on notice and determines the order of claims in the event of default or bankruptcy. Wrong (A): Filing a financing statement perfects an already-created security interest; the security interest itself is created by the security agreement between the parties. Wrong (B): The financing statement is a public notice document, not a substitute for a written loan agreement or statute of frauds compliance. Wrong (D): Perfection establishes priority but does not guarantee full recovery; the debtor''s assets may be insufficient to cover the debt.', 'medium', 2),

-- Q4: easy / L1 — Agent's duty of loyalty
(3, 'Government Regulation of Business', 'Which of the following duties requires an agent to avoid self-dealing and conflicts of interest when acting on behalf of a principal?', '["Duty of care", "Duty of obedience", "Duty to notify", "Duty of loyalty"]'::jsonb, 3, 'Correct (D): The duty of loyalty is the fiduciary obligation requiring an agent to act in the principal''s best interest, avoid self-dealing, and refrain from conflicts of interest. It is the most fundamental duty in an agency relationship. Wrong (A): The duty of care requires the agent to act with reasonable competence and diligence, not to avoid conflicts of interest. Wrong (B): The duty of obedience requires the agent to follow the principal''s lawful instructions, not to avoid self-dealing. Wrong (C): The duty to notify requires the agent to inform the principal of material facts related to the agency, not to avoid conflicts.', 'easy', 1),

-- Q5: easy / L1 — UCC Article 2 firm offer rule
(3, 'Government Regulation of Business', 'Under UCC Article 2, a written offer by a merchant to buy or sell goods that states it will be held open is irrevocable without consideration for a maximum period of how long?', '["Three months", "Six months", "One year", "30 days"]'::jsonb, 0, 'Correct (A): UCC Section 2-205 provides that a firm offer by a merchant, in a signed writing, to buy or sell goods is irrevocable for the time stated or, if no time is stated, for a reasonable time, but in no event may the period of irrevocability exceed three months without consideration. Wrong (B): Six months exceeds the statutory maximum; the firm offer rule caps irrevocability at three months. Wrong (C): One year far exceeds the UCC firm offer limit and would require separate consideration to remain open. Wrong (D): While 30 days may be a reasonable time in some contexts, the maximum period under the statute is three months.', 'easy', 1),

-- Q6: hard / L4 — Undisclosed principal contract liability
(3, 'Government Regulation of Business', 'Dawson acts as an agent for Belmont Holdings LLC to purchase commercial real estate, but Belmont instructs Dawson not to reveal the agency or Belmont''s identity. Dawson signs a purchase agreement with Carlton Properties on May 15, 2026, in Dawson''s own name. After Carlton discovers the agency, Carlton seeks to hold Belmont liable for the $1.2 million purchase price. Evaluate the liability of both Dawson and Belmont under agency law.', '["Only Dawson is liable because Carlton contracted with Dawson individually", "Both Dawson and Belmont are liable, and Carlton may elect to hold either responsible", "Only Belmont is liable as the principal is always solely responsible for agent contracts", "Neither is liable because concealment of the agency relationship voids the contract"]'::jsonb, 1, 'Correct (B): When an undisclosed principal authorizes an agent to act, both the agent and the principal are liable on the contract. The third party, upon discovering the principal''s existence, may elect to enforce the contract against either the agent or the principal, but not both simultaneously. Wrong (A): While the agent is personally liable on contracts made for an undisclosed principal, the principal is also liable once discovered; liability is not limited to the agent alone. Wrong (C): The principal does not bear sole liability; the agent who contracted in their own name remains personally liable as well. Wrong (D): Concealment of the principal''s identity does not void the contract; the undisclosed principal doctrine specifically addresses this situation.', 'hard', 4),

-- Q7: medium / L2 — Agency termination by operation of law
(3, 'Government Regulation of Business', 'An agent has been authorized by a principal to negotiate supply contracts with third parties. The principal dies unexpectedly on July 10, 2026, but the agent is unaware of the death and signs a new contract with a supplier on July 12. Under agency law, what is the status of the contract?', '["The contract is valid because the agent acted in good faith without knowledge of the death", "The contract is voidable at the option of the supplier who dealt with the agent", "The contract does not bind the estate because agency terminated immediately upon death", "The contract is enforceable against the estate because the supplier had no notice of death"]'::jsonb, 2, 'Correct (C): Under common law agency principles, the death of either the principal or the agent terminates the agency relationship immediately by operation of law, regardless of whether the other party or third parties have notice. Contracts entered after termination do not bind the deceased principal''s estate. Wrong (A): Good faith does not preserve authority that has been terminated by operation of law upon the principal''s death. Wrong (B): The contract is void rather than voidable because the agent had no authority at the time it was signed. Wrong (D): Unlike revocation, which may require notice to preserve apparent authority, death terminates the agency automatically without regard to notice.', 'medium', 2),

-- Q8: easy / L1 — Agency formation does not require consideration
(3, 'Government Regulation of Business', 'Which of the following is true regarding the formation of an agency relationship under common law?', '["The agent must receive compensation for the agency to be valid", "A written agreement is always required to create an agency", "The principal must file a registration with the state", "An agency can be created without consideration or a written agreement"]'::jsonb, 3, 'Correct (D): Under common law, an agency relationship requires only that the principal consents to the agent acting on the principal''s behalf and the agent agrees. No consideration, written agreement, or filing is necessary, distinguishing agency from contract formation. Wrong (A): Compensation is not required; a gratuitous agency where the agent acts without pay is legally valid. Wrong (B): An agency may be created orally or through implied conduct; a writing is required only for a power of attorney in certain transactions. Wrong (C): No state registration is needed to form an agency relationship; it arises from the consent of the parties.', 'easy', 1),

-- Q9: hard / L4 — Agency coupled with an interest irrevocability
(3, 'Government Regulation of Business', 'Monroe lends $300,000 to Prescott on February 1, 2026, and receives a security interest in Prescott''s inventory as collateral. Prescott grants Monroe a power of attorney to sell the inventory if Prescott defaults. On March 20, Prescott attempts to revoke Monroe''s authority and notifies all known buyers. Prescott then becomes incapacitated on April 5. Evaluate whether Monroe retains authority to sell the inventory after each event.', '["Monroe retains authority after both events because the agency is coupled with an interest and therefore irrevocable", "Monroe''s authority is revoked on March 20 because principals have an absolute right to revoke any agency", "Monroe retains authority after revocation but loses it upon Prescott''s subsequent incapacity", "Monroe''s authority terminates upon incapacity because all agencies end by operation of law"]'::jsonb, 0, 'Correct (A): An agency coupled with an interest exists when the agent holds a security interest or property interest in the subject matter of the agency. This type of agency is irrevocable by the principal and is not terminated by the principal''s death or incapacity, protecting the agent''s financial stake. Wrong (B): While principals generally may revoke an agency at will, the exception is an agency coupled with an interest, which the principal cannot unilaterally revoke. Wrong (C): An agency coupled with an interest survives both attempted revocation and the principal''s incapacity; it is not terminated by either event. Wrong (D): While most agencies terminate by operation of law upon death or incapacity, the agency coupled with an interest is the recognized exception to this rule.', 'hard', 4),

-- Q10: medium / L3 — UCC Article 2 perfect tender rule
(3, 'Government Regulation of Business', 'Oakridge Electronics orders 1,000 circuit boards from Vertex Components under a single-delivery contract. On delivery, Oakridge inspects the shipment and discovers that 15 of the 1,000 boards have minor cosmetic scratches that do not affect functionality. Under UCC Article 2, what is Oakridge''s right regarding the shipment?', '["Oakridge must accept the entire shipment because the defect is immaterial", "Oakridge may reject the entire shipment because the goods fail to conform to the contract in any respect", "Oakridge may reject only the 15 defective boards but must accept the remaining 985", "Oakridge must accept the shipment but may deduct repair costs from the purchase price"]'::jsonb, 1, 'Correct (B): UCC Section 2-601 establishes the perfect tender rule, which provides that if goods fail to conform to the contract in any respect, the buyer may reject the whole, accept the whole, or accept any commercial unit and reject the rest. Even a minor nonconformity entitles the buyer to reject. Wrong (A): The perfect tender rule does not include a materiality threshold; any nonconformity allows rejection under Article 2. Wrong (C): While the buyer may accept conforming units and reject nonconforming ones, this is an option, not a requirement; the buyer may also reject the entire shipment. Wrong (D): The buyer is not required to accept nonconforming goods and seek a price reduction; full rejection is an available remedy under the perfect tender rule.', 'medium', 3)
;

COMMIT;
