-- Migration: Question generation — TCP batch 19 (30 questions)
-- Date: 2026-03-25
-- Topic: Wealth Transfer and Gifting Strategies
-- Difficulty: 9E / 15M / 6H
-- Bloom's: L1:6 / L2:10 / L3:9 / L4:5

BEGIN;

INSERT INTO questions (section_id, topic, stem, choices, correct_index, explanation, difficulty, cognitive_level)
VALUES

-- Q1: medium / L2 — Gift tax gross-up rule Section 2035(b)
(6, 'Wealth Transfer and Gifting Strategies', $EXPL$Margaret Townsend made a $2,000,000 taxable gift in 2024 and paid $300,000 in gift tax. Margaret dies in 2026. Under Section 2035(b), how is the $300,000 gift tax treated for estate tax purposes?$EXPL$, $EXPL$["The $300,000 gift tax is included in Margaret's gross estate", "The $300,000 gift tax reduces Margaret's taxable estate as a deduction", "The $300,000 gift tax is excluded from the estate because the gift was completed", "The $300,000 gift tax is credited against the estate tax liability"]$EXPL$::jsonb, 0, $EXPL$Correct (A): Section 2035(b) provides that gift tax paid on gifts made within three years of death is included in the decedent's gross estate. This gross-up rule prevents deathbed gifting from reducing the transfer tax base by the amount of gift tax paid. Since Margaret died within three years of the gift, the $300,000 is added back to her gross estate. Wrong (B): Gift tax paid is not deductible from the estate; it is added to the gross estate under the gross-up rule. Wrong (C): While the gifted property itself is excluded, the gift tax paid within three years is specifically pulled back into the estate. Wrong (D): The gross-up rule adds the gift tax to the gross estate rather than providing a credit against estate tax.$EXPL$, 'medium', 2),

-- Q2: medium / L3 — Community property full stepped-up basis
(6, 'Wealth Transfer and Gifting Strategies', $EXPL$Harold and Vivian Pemberton, married and domiciled in a community property state, own stock as community property with a combined basis of $200,000 and a fair market value of $1,400,000. Harold dies in 2026. Vivian wants to sell the stock immediately. Evaluate the income tax consequence to Vivian on the sale.$EXPL$, $EXPL$["Vivian recognizes $600,000 in capital gains because only Harold's half receives a stepped-up basis", "Vivian recognizes $0 in capital gains because both halves of community property receive a stepped-up basis at death", "Vivian recognizes $1,200,000 in capital gains because community property retains the original basis", "Vivian recognizes $300,000 in capital gains because the basis is averaged between the original and stepped-up amounts"]$EXPL$::jsonb, 1, $EXPL$Correct (B): Under Section 1014(b)(6), when one spouse dies, both halves of community property receive a stepped-up basis to fair market value at the date of death. Vivian's entire basis becomes $1,400,000, so selling at $1,400,000 produces zero capital gain. This is a significant advantage over joint tenancy in common law states. Wrong (A): This would apply to jointly held property in a common law state where only the decedent's half receives a step-up, but community property receives a full step-up for both halves. Wrong (C): Community property does not retain the original combined basis at death; it receives a full step-up under Section 1014(b)(6). Wrong (D): There is no averaging mechanism; the entire property receives a new basis equal to fair market value at death.$EXPL$, 'medium', 3),

-- Q3: medium / L2 — Limited vs general power of appointment
(6, 'Wealth Transfer and Gifting Strategies', $EXPL$Graham Whitfield's grandmother established a trust with $3,000,000 in assets. Graham holds a limited power of appointment allowing him to direct trust assets to his siblings and their descendants, but not to himself, his estate, or his creditors. Graham dies in 2026. What amount is included in Graham's gross estate from this trust?$EXPL$, $EXPL$["$3,000,000 because any power of appointment causes estate inclusion", "$1,500,000 because half the trust is included for a limited power", "$0 because a limited power of appointment does not cause estate inclusion", "The amount included depends on whether Graham exercised the power"]$EXPL$::jsonb, 2, $EXPL$Correct (C): Under Section 2041, only a general power of appointment — one exercisable in favor of the holder, the holder's estate, or the holder's creditors — causes inclusion in the gross estate. A limited (or special) power of appointment, which cannot be exercised in favor of the holder or the holder's creditors, does not trigger estate inclusion regardless of the trust value. Wrong (A): Only general powers of appointment cause estate inclusion under Section 2041, not all powers. Wrong (B): There is no half-inclusion rule for powers of appointment; the determination is based on whether the power is general or limited. Wrong (D): Whether a limited power is exercised or not, it does not cause estate inclusion; exercise is irrelevant for limited powers.$EXPL$, 'medium', 2),

-- Q4: hard / L4 — Section 2702 special valuation rules for family trusts
(6, 'Wealth Transfer and Gifting Strategies', $EXPL$Conrad Mercer transfers $5,000,000 in growth stock to an irrevocable trust, retaining an income interest for 15 years with the remainder passing to his adult children. Conrad does not structure the retained interest as a qualified annuity or unitrust interest. Under Section 2702, the IRS values Conrad's retained income interest at zero for gift tax purposes. Evaluate the gift tax consequence and the planning failure.$EXPL$, $EXPL$["The taxable gift is $2,500,000 because the retained interest reduces the gift value by half", "The taxable gift is $5,000,000 minus the actuarial value of the income interest calculated under Section 7520 tables", "The taxable gift equals the full $5,000,000 because Section 2702 values non-qualified retained interests at zero in transfers to family members", "The taxable gift is $0 because Conrad retained an income interest that will return value to him over 15 years"]$EXPL$::jsonb, 2, $EXPL$Correct (C): Section 2702 provides that when a grantor transfers property to a family member and retains an interest, the retained interest is valued at zero unless it is a qualified interest (qualified annuity interest, qualified unitrust interest, or qualified remainder interest). Since Conrad retained a non-qualified income interest, it is valued at zero, making the entire $5,000,000 transfer a taxable gift. Wrong (A): There is no automatic 50% reduction; Section 2702 zero-values non-qualified retained interests entirely. Wrong (B): Section 7520 actuarial tables are used only when the retained interest qualifies under Section 2702; non-qualified interests are valued at zero regardless of actuarial calculations. Wrong (D): The retained income interest does not reduce the gift to zero because Section 2702 disregards non-qualified retained interests in family transfers.$EXPL$, 'hard', 4),

-- Q5: easy / L2 — 5-and-5 power lapse rule
(6, 'Wealth Transfer and Gifting Strategies', $EXPL$Rebecca Ashworth holds a Crummey withdrawal power over an irrevocable trust. The trust received a $19,000 contribution in 2026, and Rebecca's withdrawal right lapses after 30 days. Under the 5-and-5 power rule of Section 2041(b)(2), what is the gift tax consequence of the lapse?$EXPL$, $EXPL$["The lapse is not treated as a taxable transfer because the amount does not exceed the greater of $5,000 or 5% of the trust corpus", "The entire $19,000 lapse is a taxable gift by Rebecca", "The lapse triggers a $14,000 taxable gift equal to the excess over $5,000", "There is no gift tax consequence because Crummey powers are always exempt from the lapse rules"]$EXPL$::jsonb, 0, $EXPL$Correct (A): Under Section 2041(b)(2), the lapse of a general power of appointment is treated as a transfer only to the extent the lapsed amount exceeds the greater of $5,000 or 5% of the trust corpus. If the trust corpus is $380,000 or more, 5% exceeds $19,000, meaning no portion of the lapse is treated as a taxable transfer. This is a key reason Crummey powers are structured with annual exclusion-sized withdrawal rights. Wrong (B): The lapse is not automatically a taxable gift; the 5-and-5 rule provides a safe harbor that shelters lapses within the statutory limits. Wrong (C): The $5,000 floor is only one prong of the test; the 5% of corpus prong often shelters the entire lapse in larger trusts. Wrong (D): Crummey powers are subject to the lapse rules, but the 5-and-5 exception typically prevents adverse tax consequences.$EXPL$, 'easy', 2),

-- Q6: medium / L3 — Section 6166 installment payment of estate tax
(6, 'Wealth Transfer and Gifting Strategies', $EXPL$Harrison Burke dies in 2026 with an estate consisting of a 60% interest in a closely held manufacturing business valued at $12,000,000 and other assets of $6,000,000. Harrison's executor is evaluating whether to elect Section 6166 to defer estate tax attributable to the business interest. The estate qualifies because the business exceeds 35% of the adjusted gross estate. Assess the primary benefit of the Section 6166 election.$EXPL$, $EXPL$["The election eliminates the estate tax on the closely held business interest entirely", "The election allows the estate to defer estate tax attributable to the business interest for up to 14 years with a reduced interest rate on a portion of the deferred tax", "The election converts the estate tax into a capital gains tax at the lower 20% rate", "The election allows the estate to pay the tax only if the business is eventually sold"]$EXPL$::jsonb, 1, $EXPL$Correct (B): Section 6166 allows estates with closely held business interests exceeding 35% of the adjusted gross estate to defer estate tax attributable to the business for up to 5 years (interest only) and then pay in up to 10 annual installments, totaling up to 14 years of deferral. A reduced 2% interest rate applies to the tax on the first $1,000,000 in taxable value (indexed). This provides critical liquidity relief. Wrong (A): Section 6166 defers payment of estate tax but does not eliminate it; the full tax must eventually be paid. Wrong (C): Section 6166 does not convert estate tax into capital gains tax; it only provides an installment payment schedule. Wrong (D): The deferred tax must be paid on schedule regardless of whether the business is sold; it is not contingent on a sale.$EXPL$, 'medium', 3),

-- Q7: hard / L4 — Section 2036(b) retained voting rights in transferred corporation
(6, 'Wealth Transfer and Gifting Strategies', $EXPL$Claudia Fenton transferred 80% of the voting stock in her controlled corporation to an irrevocable trust for her children in 2020 but retained the right to vote the transferred shares through a proxy agreement. Claudia dies in 2026 when the shares are worth $9,000,000. Her estate planning attorney argues the shares were removed from the estate because the transfer was a completed gift. Evaluate the estate tax consequence under Section 2036(b).$EXPL$, $EXPL$["The shares are excluded from the gross estate because the gift was completed and irrevocable", "Only 20% of the share value is included because Claudia directly owned only 20% at death", "The full $9,000,000 is included in Claudia's gross estate because Section 2036(b) treats retained voting rights in a controlled corporation as a retained life estate", "Only the value at the date of the original transfer is included, not the date-of-death value"]$EXPL$::jsonb, 2, $EXPL$Correct (C): Section 2036(b) specifically provides that the retention of voting rights in transferred stock of a controlled corporation is treated as the retention of the enjoyment of the transferred property under Section 2036(a)(1). Because Claudia retained voting control through the proxy agreement, the full date-of-death value of $9,000,000 is pulled back into her gross estate despite the completed gift. Wrong (A): A completed gift does not prevent estate inclusion when the donor retains rights described in Section 2036, including voting rights in a controlled corporation. Wrong (B): Estate inclusion is based on the transferred shares over which voting rights were retained, not merely the shares directly owned at death. Wrong (D): Section 2036 causes inclusion at the date-of-death value (or alternate valuation date), not the transfer-date value.$EXPL$, 'hard', 4),

-- Q8: hard / L4 — Net gift income tax consequence (Diedrich)
(6, 'Wealth Transfer and Gifting Strategies', $EXPL$Owen Prescott makes a net gift of appreciated property (basis $400,000, FMV $2,000,000) to his daughter, who agrees to pay the resulting gift tax of $350,000. Under the Supreme Court's ruling in Diedrich v. Commissioner, the IRS treats the donee's payment of gift tax as consideration received by the donor. Owen's lifetime exemption is fully utilized. Evaluate whether Owen must recognize income on this transaction.$EXPL$, $EXPL$["Owen has no income tax consequences because gifts are excluded from income under Section 102", "Owen recognizes $350,000 of capital gain because the gift tax paid by the donee is treated as an amount realized that exceeds his allocable basis", "Owen recognizes $1,600,000 of capital gain equal to the full appreciation in the property", "Owen recognizes ordinary income of $350,000 because net gift arrangements are recharacterized as compensation"]$EXPL$::jsonb, 1, $EXPL$Correct (B): Under Diedrich v. Commissioner (1982), when a donee pays the gift tax as a condition of receiving the gift, the donor is treated as having sold the property to the extent the gift tax paid exceeds the donor's allocable basis in the property. Owen's amount realized is $350,000 (gift tax paid by the daughter). His allocable basis is $400,000 x ($350,000 / $2,000,000) = $70,000. Capital gain is $350,000 - $70,000 = $280,000. The actual gain depends on the basis allocation, but the key principle is that gain is recognized to the extent gift tax paid exceeds allocable basis. Wrong (A): While gifts are generally excluded from the donee's income under Section 102, the Diedrich ruling creates an income tax event for the donor when the donee pays the gift tax. Wrong (C): Owen does not recognize gain on the full appreciation; gain is limited to the difference between the gift tax paid and the donor's allocable basis. Wrong (D): The transaction is not recharacterized as compensation; it remains a gift, but the donor recognizes capital gain on the deemed sale portion.$EXPL$, 'hard', 4),

-- Q9: easy / L1 — Incomplete gift doctrine
(6, 'Wealth Transfer and Gifting Strategies', $EXPL$What makes a transfer an incomplete gift for federal gift tax purposes?$EXPL$, $EXPL$["The donor retains the power to revoke the transfer or change the beneficiaries", "The donor transfers property to a trust without retaining any interest", "The donee is a minor who cannot accept the gift", "The gift exceeds the annual exclusion amount"]$EXPL$::jsonb, 0, $EXPL$Correct (A): Under Treasury Regulation Section 25.2511-2, a gift is incomplete if the donor retains dominion and control over the transferred property, such as the power to revoke the transfer, alter beneficial interests, or name new beneficiaries. An incomplete gift is not subject to gift tax at the time of transfer. Wrong (B): A transfer to a trust without retained interests is a completed gift and is subject to gift tax. Wrong (C): A donee's age does not determine whether a gift is complete; gifts to minors are completed transfers. Wrong (D): Exceeding the annual exclusion affects whether gift tax is owed, not whether the gift is complete.$EXPL$, 'easy', 1),

-- Q10: medium / L2 — Section 7872 below-market loan $100K exception
(6, 'Wealth Transfer and Gifting Strategies', $EXPL$Nathaniel Drake lends $80,000 to his adult son at 0% interest. The applicable federal rate is 4.5%. The son's net investment income for the year is $800. Under Section 7872, the imputed interest on gift loans of $100,000 or less is limited to the borrower's net investment income. What is the deemed gift from Nathaniel to his son for the year?$EXPL$, $EXPL$["$3,600 representing the full AFR interest that should have been charged", "$800 because the imputed interest is limited to the borrower's net investment income", "There is no deemed gift because loans under $100,000 are fully exempt from Section 7872", "$0 because the borrower's net investment income does not exceed $1,000"]$EXPL$::jsonb, 3, $EXPL$Correct (D): Under Section 7872(d)(1), for gift loans between individuals of $100,000 or less, the imputed interest (and therefore the deemed gift) is limited to the borrower's net investment income. However, Section 7872(d)(1)(E) provides that if the borrower's net investment income does not exceed $1,000, it is treated as zero. Since the son's NII of $800 does not exceed $1,000, the deemed gift is $0. Wrong (A): The full AFR calculation does not apply because the $100,000 exception limits imputed interest to the borrower's NII. Wrong (B): While NII normally caps the deemed gift, the de minimis rule treats NII below $1,000 as zero. Wrong (C): Loans under $100,000 are not fully exempt; they are subject to Section 7872 but with the NII limitation.$EXPL$, 'medium', 2),

-- Q11: easy / L1 — Consideration offset under Section 2043
(6, 'Wealth Transfer and Gifting Strategies', $EXPL$Under Section 2043, how is consideration received by a decedent treated for estate tax purposes?$EXPL$, $EXPL$["Consideration received reduces the gross estate dollar for dollar", "Consideration received increases the gross estate", "Consideration received in money or money's worth offsets the amount included in the gross estate for transfers with retained interests", "Consideration has no effect on estate tax calculations"]$EXPL$::jsonb, 2, $EXPL$Correct (C): Section 2043 provides that when property is transferred for less than adequate and full consideration and is later included in the gross estate under Sections 2035-2038, the amount included is reduced by the consideration received in money or money's worth. This prevents double taxation when partial consideration was received. Wrong (A): Consideration does not reduce the gross estate broadly; it specifically offsets amounts included under the retained interest provisions of Sections 2035-2038. Wrong (B): Consideration received does not increase the gross estate; it reduces inclusion amounts. Wrong (D): Consideration is relevant to estate tax calculations and directly offsets amounts otherwise included in the gross estate.$EXPL$, 'easy', 1),

-- Q12: medium / L2 — Blockage discount for large publicly traded stock holdings
(6, 'Wealth Transfer and Gifting Strategies', $EXPL$Theodore Langston dies in 2026 owning 2,000,000 shares of a publicly traded company, representing 8% of the company's outstanding shares. The stock trades at $25 per share on the date of death, giving a market value of $50,000,000. The estate's appraiser applies a 15% blockage discount, reducing the estate tax value to $42,500,000. What is the rationale for the blockage discount?$EXPL$, $EXPL$["The discount reflects the control premium associated with owning 8% of a public company", "The discount reflects the inability to sell such a large block on the open market without depressing the stock price", "The discount reflects a lack of marketability because the shares are restricted securities", "The discount reflects the time value of money needed to liquidate the position over several years"]$EXPL$::jsonb, 3, $EXPL$Correct (D): A blockage discount applies when a decedent owns such a large block of publicly traded stock that selling the entire position at once would depress the market price below the current trading price. The discount reflects the reality that the block must be sold over time, and the time value of that extended liquidation reduces the present value. Treasury Regulation Section 20.2031-2(e) recognizes this discount. Wrong (A): An 8% holding does not confer a control premium; the blockage discount is about the depressive effect of selling a large block, not about control. Wrong (B): Publicly traded shares are not unmarketable; the discount addresses the market impact of selling a large quantity, not marketability. Wrong (C): The shares are publicly traded, not restricted securities; the discount is about block size impact on price, not legal restrictions on sale.$EXPL$, 'medium', 2),

-- Q13: medium / L2 — Totten trust / POD account estate inclusion
(6, 'Wealth Transfer and Gifting Strategies', $EXPL$Dorothy Sloan maintains a bank account titled in her name as payable-on-death (POD) to her niece, containing $250,000 at Dorothy's death in 2026. Dorothy retained full control of the account during her lifetime, making deposits and withdrawals freely. How is the POD account treated for estate tax purposes?$EXPL$, $EXPL$["The $250,000 is included in Dorothy's gross estate under Section 2033 because she retained complete ownership and control during her lifetime", "The $250,000 is excluded because the POD designation constitutes a completed gift to the niece", "Only the deposits made within three years of death are included in the gross estate", "Half the account balance is included because the niece had a contingent interest"]$EXPL$::jsonb, 0, $EXPL$Correct (A): Under Section 2033, property owned by the decedent at death is included in the gross estate. A POD (payable-on-death) account, also known as a Totten trust, remains the property of the account holder during life because the holder retains full dominion and control. The POD designation is a revocable transfer that takes effect at death, causing full inclusion. Wrong (B): A POD designation is not a completed gift because Dorothy retained full control and could revoke the designation at any time. Wrong (C): There is no rule limiting inclusion to deposits made within three years; the entire account is included because Dorothy owned it at death. Wrong (D): The niece has no vested interest during Dorothy's lifetime, so there is no basis for partial inclusion.$EXPL$, 'medium', 2),

-- Q14: medium / L3 — Section 2519 disposition of QTIP income interest
(6, 'Wealth Transfer and Gifting Strategies', $EXPL$Eleanor Vandermeer is the surviving spouse and income beneficiary of a $6,000,000 QTIP trust created by her late husband's estate. Eleanor assigns her income interest to her daughter. Under Section 2519, the assignment of the income interest is treated as a transfer of the entire trust. Calculate the taxable gift resulting from Eleanor's disposition.$EXPL$, $EXPL$["Only the actuarial value of Eleanor's income interest is a taxable gift", "The full $6,000,000 trust value is treated as a taxable gift by Eleanor", "There is no taxable gift because the trust was already subject to estate tax in her husband's estate", "The taxable gift equals $6,000,000 minus the value of the remainder interest"]$EXPL$::jsonb, 1, $EXPL$Correct (B): Under Section 2519, when a surviving spouse disposes of any part of a qualifying income interest in QTIP property, the spouse is treated as transferring all interests in the trust other than the qualifying income interest. Combined with the actual transfer of the income interest under Section 2511, the entire $6,000,000 trust value is treated as a taxable gift by Eleanor. This prevents the surviving spouse from unbundling the QTIP to avoid transfer tax. Wrong (A): Section 2519 goes beyond the actuarial value of the income interest and treats the disposition as a transfer of the entire trust corpus. Wrong (C): The marital deduction in the first estate deferred transfer tax; the disposition by the surviving spouse triggers a new taxable event. Wrong (D): Section 2519 treats the surviving spouse as transferring all interests, not just the remainder; the full value is a taxable gift.$EXPL$, 'medium', 3),

-- Q15: medium / L3 — Disclaimer trust planning
(6, 'Wealth Transfer and Gifting Strategies', $EXPL$Leonard Whitaker's will leaves his entire $16,000,000 estate to his wife, Carolyn. Carolyn's estate planning attorney advises her to disclaim a portion of the estate to fund a credit shelter (bypass) trust with the amount of Leonard's unused applicable exclusion ($14,500,000). The trust would benefit Carolyn for life with the remainder passing to their children. Assess why the disclaimer strategy is advantageous.$EXPL$, $EXPL$["It allows Carolyn to avoid paying income tax on the trust income", "It allows the disclaimed amount to use Leonard's applicable exclusion and pass to the children estate-tax-free at Carolyn's later death, rather than being taxed in Carolyn's estate", "It converts Leonard's estate tax into a capital gains tax at the lower rate", "It allows Carolyn to claim a double marital deduction on the disclaimed property"]$EXPL$::jsonb, 1, $EXPL$Correct (B): By disclaiming $14,500,000, that amount passes to the credit shelter trust instead of outright to Carolyn. Leonard's applicable exclusion shelters the trust from estate tax, and the trust assets — including future appreciation — are excluded from Carolyn's estate at her later death. Without the disclaimer, the entire $16,000,000 (plus growth) would be in Carolyn's estate. Wrong (A): Trust income is still subject to income tax; the disclaimer strategy addresses estate tax, not income tax. Wrong (C): The disclaimer does not convert estate tax to capital gains tax; it uses the decedent's exclusion to shelter assets from estate tax. Wrong (D): The marital deduction applies only to property that actually passes to the surviving spouse; disclaimed property does not qualify for and does not need the marital deduction.$EXPL$, 'medium', 3),

-- Q16: hard / L3 — Dynasty trust for multi-generational GSTT planning
(6, 'Wealth Transfer and Gifting Strategies', $EXPL$Victoria Ashford, a high-net-worth client, establishes a dynasty trust in a state that has abolished the rule against perpetuities. She funds the trust with $14,500,000 and allocates her entire GST exemption to the trust, achieving an inclusion ratio of zero. The trust is designed to benefit her children, grandchildren, and subsequent generations in perpetuity. Assess the transfer tax advantage of this structure compared to outright gifts passing through each generation.$EXPL$, $EXPL$["The trust avoids income tax on accumulated earnings, which is the primary advantage over outright gifts", "The trust assets are subject to estate tax only once, at Victoria's generation, and then pass through subsequent generations without additional estate or GST tax", "The trust provides no transfer tax advantage because each generation's beneficial interest triggers a taxable termination", "The trust delays estate tax until the trust terminates, but the total tax paid across generations is the same"]$EXPL$::jsonb, 1, $EXPL$Correct (B): A dynasty trust with an inclusion ratio of zero is entirely exempt from GSTT. Because the trust — rather than individual beneficiaries — owns the assets, the trust property is not included in any beneficiary's gross estate. Assets pass through multiple generations with no additional estate tax or GSTT. Compared to outright gifts taxed at each generational transfer (potentially 40% per generation), the dynasty trust preserves significantly more wealth. Wrong (A): Dynasty trusts do not avoid income tax; trust income is taxed either to the trust or distributed to beneficiaries. The primary advantage is eliminating multi-generational transfer taxes. Wrong (C): With an inclusion ratio of zero, distributions and terminations within the trust are not subject to GSTT; the full GST exemption allocation shields all future transfers. Wrong (D): The trust does not merely delay tax; it permanently eliminates estate and GST tax on trust assets for all future generations as long as the trust continues.$EXPL$, 'hard', 3),

-- Q17: easy / L2 — Annual exclusion inflation indexing
(6, 'Wealth Transfer and Gifting Strategies', $EXPL$Walter Simmons, a retired accountant, recalls that the annual gift tax exclusion was $15,000 per donee in 2021. In 2026, the exclusion is $19,000 per donee. Under the Internal Revenue Code, how is the annual exclusion amount adjusted over time?$EXPL$, $EXPL$["The annual exclusion is indexed for inflation and increases in $1,000 increments when the cumulative inflation adjustment reaches that threshold", "The annual exclusion is set by Congress each year through appropriations legislation", "The annual exclusion increases by $1,000 every calendar year automatically", "The annual exclusion is adjusted based on the Consumer Price Index every quarter"]$EXPL$::jsonb, 0, $EXPL$Correct (A): Under Section 2503(b), the annual gift tax exclusion is adjusted for inflation using the Chained Consumer Price Index, rounded down to the nearest $1,000 increment. The exclusion only increases when the cumulative inflation adjustment is sufficient to reach the next $1,000 threshold, which is why it may remain unchanged for several consecutive years. Wrong (B): The annual exclusion is set by statute and adjusted automatically by formula; Congress does not vote on it annually. Wrong (C): The exclusion does not increase by exactly $1,000 every year; it is tied to inflation and may remain flat in low-inflation years. Wrong (D): The exclusion is adjusted annually, not quarterly, and increases only in $1,000 increments rather than continuously tracking the CPI.$EXPL$, 'easy', 2),

-- Q18: hard / L4 — DSUE portability remarriage limitation
(6, 'Wealth Transfer and Gifting Strategies', $EXPL$Meredith Cooper's first husband died in 2020, and his estate elected portability, giving Meredith a $11,580,000 DSUE amount. Meredith remarried Philip in 2022. Philip dies in 2026 having used $3,000,000 of his own $14,500,000 lifetime exemption. Philip's estate elects portability. Evaluate how much total applicable exclusion amount Meredith now has for her own estate planning purposes.$EXPL$, $EXPL$["$26,080,000 — her own exemption plus the DSUE from both deceased husbands", "$14,500,000 — only her own exemption because remarriage forfeits all DSUE", "$26,000,000 — her own exemption plus $11,500,000 DSUE from Philip", "$26,000,000 — her own exemption of $14,500,000 plus Philip's unused exemption of $11,500,000"]$EXPL$::jsonb, 3, $EXPL$Correct (D): Under Section 2010(c)(4), a surviving spouse may only use the DSUE from the last deceased spouse. When Philip died in 2026, Meredith lost access to her first husband's $11,580,000 DSUE. Philip's DSUE is $14,500,000 - $3,000,000 = $11,500,000. Meredith's total applicable exclusion is her own $14,500,000 plus Philip's $11,500,000 DSUE = $26,000,000. Wrong (A): The DSUE from both husbands cannot be stacked; only the last deceased spouse's DSUE is available under the statute. Wrong (B): Remarriage itself does not forfeit DSUE; the DSUE is replaced by the last deceased spouse's unused amount when that spouse dies. Wrong (C): This answer has the correct total but misstates Philip's unused amount; Philip used $3,000,000, leaving $11,500,000, not $11,580,000.$EXPL$, 'hard', 4),

-- Q19: medium / L3 — Taxable termination vs taxable distribution distinction
(6, 'Wealth Transfer and Gifting Strategies', $EXPL$Arthur Brennan established a trust in 2015 with his daughter Claire as the sole income beneficiary and his grandchildren as remainder beneficiaries. In 2026, the trust distributes $100,000 of principal to one of the grandchildren while Claire is still alive and receiving income. Arthur did not allocate any GST exemption to the trust. Determine the type of generation-skipping transfer that occurred.$EXPL$, $EXPL$["A direct skip because the distribution goes to a grandchild", "A taxable termination because the trust is distributing assets to skip persons", "A taxable distribution because a distribution is made from the trust to a skip person while a non-skip person still holds an interest", "No generation-skipping transfer occurred because Arthur's daughter is still a beneficiary"]$EXPL$::jsonb, 2, $EXPL$Correct (C): Under Section 2612(b), a taxable distribution is any distribution from a trust to a skip person (the grandchild) that is not a taxable termination or direct skip. Because Claire (a non-skip person) still holds an interest in the trust, this is not a taxable termination. It is a taxable distribution, and the grandchild (as transferee) is liable for the GSTT. Wrong (A): A direct skip is a transfer directly to a skip person that is subject to estate or gift tax, not a distribution from an existing trust. Wrong (B): A taxable termination under Section 2612(a) occurs when all interests held by non-skip persons terminate; Claire's income interest has not terminated. Wrong (D): A distribution to a skip person from a trust without allocated GST exemption is a taxable distribution regardless of whether non-skip beneficiaries remain.$EXPL$, 'medium', 3),

-- Q20: easy / L2 — Inclusion ratio mechanics for GSTT
(6, 'Wealth Transfer and Gifting Strategies', $EXPL$Margaret Ellison funds a trust with $5,000,000 and allocates $3,000,000 of her GST exemption to the trust. Under Section 2642, the applicable fraction is the GST exemption allocated divided by the value of the property transferred. What is the trust's inclusion ratio?$EXPL$, $EXPL$["0.60 because the inclusion ratio equals the applicable fraction", "1.00 because not all of the transfer was covered by the GST exemption", "0.60 because the inclusion ratio equals 1 minus the applicable fraction", "0.40 because the inclusion ratio equals 1 minus the applicable fraction"]$EXPL$::jsonb, 3, $EXPL$Correct (D): Under Section 2642(a), the inclusion ratio equals 1 minus the applicable fraction. The applicable fraction is $3,000,000 / $5,000,000 = 0.60. Therefore, the inclusion ratio is 1 - 0.60 = 0.40. This means 40% of any future generation-skipping transfer from this trust will be subject to GSTT at the maximum rate. Wrong (A): The inclusion ratio is not the same as the applicable fraction; it is 1 minus the applicable fraction. Wrong (B): An inclusion ratio of 1.00 would mean zero GST exemption was allocated, which is not the case here. Wrong (C): While the formula is correctly stated, the arithmetic is wrong; 1 - 0.60 = 0.40, not 0.60.$EXPL$, 'easy', 2),

-- Q21: easy / L1 — State death tax deduction (Section 2058)
(6, 'Wealth Transfer and Gifting Strategies', $EXPL$What deduction does Section 2058 allow for federal estate tax purposes?$EXPL$, $EXPL$["A deduction for federal income taxes owed by the decedent", "A deduction for state death taxes actually paid by the estate", "A deduction for state income taxes paid during the decedent's final year", "A deduction for property taxes owed by the decedent at death"]$EXPL$::jsonb, 1, $EXPL$Correct (B): Section 2058 allows a deduction from the gross estate for death taxes actually paid to any state, the District of Columbia, or a U.S. territory. This replaced the former state death tax credit under Section 2011. The deduction reduces the taxable estate, providing a federal benefit for estates in states with their own estate or inheritance tax. Wrong (A): Federal income taxes owed by the decedent are deductible as debts under Section 2053, not under the state death tax deduction of Section 2058. Wrong (C): State income taxes for the decedent's final year are deductible as debts of the decedent under Section 2053, not under Section 2058. Wrong (D): Property taxes owed at death are deductible as debts under Section 2053, not under the state death tax deduction of Section 2058.$EXPL$, 'easy', 1),

-- Q22: medium / L2 — Alternate valuation election restrictions
(6, 'Wealth Transfer and Gifting Strategies', $EXPL$Victor Harrington dies in 2026 with an estate valued at $18,000,000 on the date of death. Six months later, the estate's assets are worth $19,500,000 due to market appreciation. The executor is considering the alternate valuation date election under Section 2032 to defer valuation. Can the executor elect alternate valuation?$EXPL$, $EXPL$["Yes, the executor may always elect alternate valuation regardless of the effect on estate value", "No, because Section 2032 requires that the election must decrease both the gross estate value and the estate tax liability", "Yes, but only if the estate tax return is filed within 9 months of death", "No, because alternate valuation is only available for estates under the exemption amount"]$EXPL$::jsonb, 1, $EXPL$Correct (B): Under Section 2032(c), the alternate valuation date election is available only if it results in a decrease in both the value of the gross estate and the amount of estate tax (reduced by credits). Since the estate's value increased from $18,000,000 to $19,500,000 over six months, the election would increase the gross estate, disqualifying it. Wrong (A): The election is not unconditional; Section 2032(c) imposes the dual requirement that both estate value and tax liability must decrease. Wrong (C): While the estate tax return must be timely filed, the primary restriction is that the election must reduce both gross estate value and tax liability. Wrong (D): The alternate valuation election is available to estates of any size, provided the dual decrease requirement is met.$EXPL$, 'medium', 2),

-- Q23: medium / L2 — Section 2039 annuities in gross estate
(6, 'Wealth Transfer and Gifting Strategies', $EXPL$Florence Davenport purchased a joint and survivor annuity for $400,000 that pays $30,000 per year during her life, then continues paying $30,000 per year to her daughter for the daughter's remaining life after Florence's death. Florence dies in 2026. The value of the survivor annuity payable to the daughter is $280,000 at Florence's death. How is the annuity treated for estate tax purposes?$EXPL$, $EXPL$["The annuity is excluded from the gross estate because Florence's interest terminated at death", "The entire $400,000 purchase price is included in the gross estate", "The $280,000 value of the survivor annuity is included in Florence's gross estate under Section 2039", "Only the remaining annuity payments Florence would have received are included"]$EXPL$::jsonb, 2, $EXPL$Correct (C): Under Section 2039, the value of an annuity or other payment receivable by a surviving beneficiary is included in the decedent's gross estate if the decedent was receiving (or had the right to receive) payments during life. The includable amount is the value of the survivor's interest at the date of death, which is $280,000. Since Florence purchased the annuity entirely with her own funds, the full survivor benefit is included. Wrong (A): Although Florence's personal interest terminated at death, Section 2039 specifically includes the survivor's interest in the decedent's gross estate. Wrong (B): The original purchase price is not the measure of inclusion; Section 2039 uses the value of the survivor benefit at the date of death. Wrong (D): The measure is the present value of future payments to the surviving beneficiary, not payments the decedent would have received.$EXPL$, 'medium', 2),

-- Q24: hard / L4 — Fractional interest discount for undivided real estate
(6, 'Wealth Transfer and Gifting Strategies', $EXPL$Charlotte Meriwether and her three siblings each own a 25% undivided interest in a commercial property worth $8,000,000 in total. Charlotte wants to gift her 25% interest to her son. A qualified appraiser determines that a 25% undivided interest in real property commands a fractional interest discount of 20% because a buyer cannot use, sell, or partition the property without the consent of the other co-owners. Charlotte's estate planning attorney argues that the discount is appropriate. Evaluate the gift tax value of Charlotte's transfer.$EXPL$, $EXPL$["$2,000,000 because fractional interest discounts are not allowed for real property", "$1,600,000 because the 20% fractional interest discount applies to the pro rata value of $2,000,000", "$800,000 because both a fractional interest discount and a lack of marketability discount apply cumulatively", "$2,000,000 because the property is not held in an entity so no valuation discount is available"]$EXPL$::jsonb, 1, $EXPL$Correct (B): Fractional (undivided) interest discounts are recognized for gift and estate tax purposes under Revenue Ruling 93-12 and case law including Estate of Barge. A 25% undivided interest in real property is worth less than 25% of the total value because the holder cannot independently sell, develop, or manage the property. The pro rata value is $2,000,000 ($8,000,000 x 25%), and the 20% discount reduces the gift tax value to $1,600,000. Wrong (A): Fractional interest discounts are available for undivided interests in real property; the IRS and courts have recognized these discounts. Wrong (C): While additional discounts could theoretically apply, the question states a single 20% fractional interest discount as determined by the appraiser; layering an unsupported second discount is speculative. Wrong (D): Valuation discounts are not limited to entity interests; undivided interests in directly held real property also qualify for discounts reflecting the co-ownership limitations.$EXPL$, 'hard', 4),

-- Q25: easy / L1 — Credit for tax on prior transfers (Section 2013)
(6, 'Wealth Transfer and Gifting Strategies', $EXPL$What does the credit for tax on prior transfers under Section 2013 provide?$EXPL$, $EXPL$["A credit against estate tax for estate tax paid on property transferred to the decedent from a person who died within 10 years before or 2 years after the decedent's death", "A credit for gift taxes paid by the decedent during the decedent's lifetime", "A credit for income taxes paid on inherited property", "A credit for state estate taxes paid on the same property"]$EXPL$::jsonb, 0, $EXPL$Correct (A): Section 2013 provides a credit against the estate tax for all or part of the estate tax paid on property that was transferred to the current decedent from a transferor who died within 10 years before or 2 years after the current decedent. The credit decreases by 20% for each two-year period beyond the first two years, preventing rapid successive taxation of the same property. Wrong (B): Gift taxes paid during the decedent's lifetime are addressed by the unified credit system, not by Section 2013. Wrong (C): There is no estate tax credit for income taxes paid on inherited property; Section 2013 addresses prior estate taxes. Wrong (D): The deduction for state death taxes is governed by Section 2058, not Section 2013, which specifically addresses federal estate tax on prior transfers.$EXPL$, 'easy', 1),

-- Q26: easy / L1 — Ascertainable standard limits power of appointment
(6, 'Wealth Transfer and Gifting Strategies', $EXPL$Under Section 2041, a power of appointment limited by an ascertainable standard is classified as which type of power?$EXPL$, $EXPL$["A general power of appointment", "A limited (special) power of appointment that does not cause estate inclusion", "A testamentary power that is only exercisable at death", "A power that is void and unenforceable"]$EXPL$::jsonb, 1, $EXPL$Correct (B): Under Section 2041(b)(1)(A), a power limited by an ascertainable standard relating to health, education, support, or maintenance (HEMS) is not treated as a general power of appointment. This means the holder can distribute trust assets to themselves for these purposes without causing estate inclusion. The ascertainable standard provides an objective limitation on the power. Wrong (A): A power limited by an ascertainable standard is specifically excluded from the definition of a general power under Section 2041(b)(1)(A). Wrong (C): The classification as limited versus general does not depend on when the power is exercisable; a HEMS-limited power is a limited power whether exercisable during life or at death. Wrong (D): A power limited by an ascertainable standard is valid and enforceable; it simply does not rise to the level of a general power for estate tax purposes.$EXPL$, 'easy', 1),

-- Q27: easy / L1 — Split-dollar life insurance estate issues
(6, 'Wealth Transfer and Gifting Strategies', $EXPL$In a split-dollar life insurance arrangement, what determines whether the death benefit is included in the insured's gross estate?$EXPL$, $EXPL$["Whether the insured paid the premiums", "Whether the policy has a cash surrender value exceeding $100,000", "Whether the insured held any incidents of ownership in the policy at death under Section 2042", "Whether the insured was the named beneficiary of the policy"]$EXPL$::jsonb, 2, $EXPL$Correct (C): Under Section 2042, life insurance proceeds are included in the insured's gross estate if the insured held any incidents of ownership at death, such as the right to change beneficiaries, borrow against the policy, surrender or cancel the policy, or assign the policy. In split-dollar arrangements, careful structuring is required to ensure the insured does not retain incidents of ownership. Wrong (A): Premium payment alone does not determine estate inclusion; it is the retention of incidents of ownership that controls under Section 2042. Wrong (B): Cash surrender value thresholds do not determine estate inclusion; the test is whether the insured held incidents of ownership. Wrong (D): Being the named beneficiary is relevant for income tax purposes but not for the insured's estate inclusion; the insured's incidents of ownership are what matter.$EXPL$, 'easy', 1),

-- Q28: medium / L3 — Gift causa mortis vs inter vivos gift
(6, 'Wealth Transfer and Gifting Strategies', $EXPL$Dr. Philip Hartwell, terminally ill, transfers $500,000 in securities to his nephew three weeks before his death, telling the nephew "I want you to have this since I won't be here much longer." The transfer is characterized as a gift causa mortis under state property law. Assess the federal transfer tax treatment of this gift.$EXPL$, $EXPL$["The gift is exempt from all transfer taxes because gifts causa mortis are treated as testamentary transfers governed only by state law", "The gift is subject to gift tax as an inter vivos transfer; federal tax law does not distinguish between gifts causa mortis and other lifetime gifts", "The gift is subject to estate tax only and is not a taxable gift because the donor died shortly after the transfer", "The gift is subject to both gift tax and estate tax, resulting in double taxation of the transferred property"]$EXPL$::jsonb, 3, $EXPL$Correct (D): For federal transfer tax purposes, a gift causa mortis is treated as a completed gift subject to gift tax at the time of transfer under Section 2501. Additionally, under Section 2035(a), because the transfer was made within three years of death and was motivated by the donor's contemplation of death, the property may be included in the gross estate. However, Section 2001(b) provides a credit for gift taxes paid to prevent full double taxation. Wrong (A): Federal tax law applies its own classification rules regardless of state property law characterization; gifts causa mortis are subject to federal transfer tax. Wrong (B): While the gift is subject to gift tax, the analysis is incomplete because Section 2035 may also cause estate inclusion for transfers in contemplation of death. Wrong (C): The transfer is not solely subject to estate tax; it is a completed lifetime gift subject to gift tax, with potential estate inclusion under Section 2035.$EXPL$, 'medium', 3),

-- Q29: medium / L3 — Trust remainder interest present value using actuarial tables
(6, 'Wealth Transfer and Gifting Strategies', $EXPL$Andrea Waverly, age 70, transfers $2,000,000 to a charitable remainder annuity trust (CRAT) that pays her $100,000 per year (5% of initial funding) for her life, with the remainder passing to a public charity. The Section 7520 rate is 5.0%, and IRS actuarial tables indicate the present value of Andrea's annuity interest is $1,100,000. Determine the charitable deduction for gift tax purposes.$EXPL$, $EXPL$["$2,000,000 because the entire transfer is to a charitable trust", "$900,000 representing the present value of the charitable remainder interest", "$1,100,000 representing the present value of Andrea's retained annuity interest", "$100,000 representing the annual annuity payment"]$EXPL$::jsonb, 1, $EXPL$Correct (B): The charitable deduction for a CRAT is the present value of the remainder interest passing to charity. Under Section 2522, the remainder value equals the total transfer ($2,000,000) minus the present value of the retained annuity ($1,100,000) = $900,000. The IRS actuarial tables under Section 7520 are used to compute the present value of the retained interest, and the remainder is the charitable deduction. Wrong (A): The entire $2,000,000 is not deductible because Andrea retains an annuity interest; only the remainder qualifies for the charitable deduction. Wrong (C): The $1,100,000 is the value of Andrea's retained interest, not the charitable remainder; the deduction is based on the remainder, not the annuity. Wrong (D): The annual payment amount is not the measure of the charitable deduction; the deduction is based on the present value of the remainder interest.$EXPL$, 'medium', 3),

-- Q30: medium / L3 — Section 2035(a) life insurance transfer within 3 years
(6, 'Wealth Transfer and Gifting Strategies', $EXPL$Roland Ashby transferred ownership of a $4,000,000 whole life insurance policy to an irrevocable life insurance trust (ILIT) in January 2024. Roland dies in October 2026, less than three years after the transfer. The trust is properly structured and Roland held no incidents of ownership after the transfer. Assess the estate tax treatment of the policy proceeds.$EXPL$, $EXPL$["The $4,000,000 proceeds are excluded from Roland's estate because the ILIT is the owner and beneficiary", "The $4,000,000 proceeds are included in Roland's gross estate under Section 2035(a) because the transfer occurred within three years of death", "Only the cash surrender value at the time of transfer is included in the gross estate, not the full death benefit", "The proceeds are included only to the extent of premiums Roland paid after the transfer"]$EXPL$::jsonb, 1, $EXPL$Correct (B): Under Section 2035(a), if a decedent transfers a life insurance policy (or any interest in a policy that would have been included under Section 2042) within three years of death, the full death benefit is included in the gross estate. Roland transferred the policy in January 2024 and died in October 2026 — less than three years later. Despite the ILIT structure, the three-year rule pulls the full $4,000,000 proceeds back into the estate. Wrong (A): The ILIT structure would exclude the proceeds only if Roland survived at least three years after transferring the policy; the three-year rule overrides the ownership transfer. Wrong (C): Section 2035(a) includes the full amount that would have been includable under Section 2042, which is the death benefit, not the cash surrender value at the time of transfer. Wrong (D): Inclusion is not limited to premiums paid; the entire death benefit is included because Roland would have had incidents of ownership at death but for the transfer.$EXPL$, 'medium', 3)
;

COMMIT;
