-- Migration: Question generation — AUD batch 97 (15 questions)
-- Date: 2026-03-25
-- Topic: Tests of Controls
-- Difficulty: 5E / 7M / 3H
-- Bloom's: L1:4 / L2:5 / L3:4 / L4:2

BEGIN;

INSERT INTO questions (section_id, topic, stem, choices, correct_index, explanation, difficulty, cognitive_level)
VALUES

-- Q1: medium / L2 — Nature-timing-extent interrelationship
(1, 'Tests of Controls', 'During the audit of Clearwater Industries, the engagement team decides to test a revenue cycle approval control at an interim date rather than at year-end. To compensate for the reduced timing of testing, the auditor should most appropriately adjust the:', '["Extent of testing by increasing the sample size for the remaining period", "Nature of testing by replacing reperformance with inquiry", "Timing by also testing at a second interim date", "Tolerable deviation rate by raising it to accept more deviations"]'::jsonb, 0, 'Correct (A): AU-C 330.13 requires the auditor to consider the nature, timing, and extent of further audit procedures as interrelated. When controls are tested at interim, the auditor bridges the gap by increasing the extent of testing or performing additional procedures for the remaining period. Wrong (B): Rather than strengthening evidence, replacing reperformance with inquiry weakens it; inquiry alone is never sufficient for operating effectiveness. Wrong (C): Although a second interim date adds evidence, it still does not address the gap between interim and year-end. Wrong (D): Raising the tolerable deviation rate reduces assurance rather than compensating for the timing limitation.', 'medium', 2),

-- Q2: easy / L1 — Minimum testing requirement when relying on controls
(1, 'Tests of Controls', 'When the auditor plans to rely on the operating effectiveness of controls, the minimum requirement is to:', '["Perform a walkthrough of the control process", "Test the controls during the current audit period", "Obtain a written representation from management about control effectiveness", "Review the prior-year working papers for evidence of control testing"]'::jsonb, 1, 'Correct (B): AU-C 330.08 requires the auditor to test the operating effectiveness of controls when relying on them. Rather than accepting representations or prior-year evidence alone, the auditor must perform tests in the current period to support the planned reliance. Wrong (A): Although walkthroughs help the auditor understand the control, they are a risk assessment procedure and do not by themselves constitute testing of operating effectiveness. Wrong (C): Management representations supplement but do not replace testing; however, they are never sufficient evidence of operating effectiveness on their own. Wrong (D): Prior-year working papers may inform planning, but unlike current-period testing, they do not provide evidence that controls operated effectively in the current year.', 'easy', 1),

-- Q3: medium / L2 — Statistical vs non-statistical sampling
(1, 'Tests of Controls', 'Quinn and Lopez, CPAs, are testing accounts payable approval controls at Redstone Manufacturing. The engagement team is deciding between statistical and non-statistical sampling. The primary advantage of statistical sampling over non-statistical sampling for this test of controls is that statistical sampling:', '["Eliminates the need for professional judgment in evaluating results", "Always produces a smaller sample size than non-statistical methods", "Provides a quantitative measure of sampling risk", "Requires less professional judgment than substantive testing procedures"]'::jsonb, 2, 'Correct (C): AU-C 530.05 notes that statistical sampling enables the auditor to quantify and control sampling risk by computing confidence intervals and upper deviation limits. In contrast, non-statistical methods do not provide this quantitative measurement. Wrong (A): Professional judgment is still required in both approaches for defining the population, selecting attributes, and evaluating results. Wrong (B): Statistical sampling does not always produce smaller samples; rather than being inherently smaller, sample size depends on parameters like confidence level and tolerable deviation rate. Wrong (D): Both statistical and non-statistical approaches require professional judgment; the distinction is quantification of risk, not reduction of judgment.', 'medium', 2),

-- Q4: medium / L3 — Roll-forward when controls changed during gap period
(1, 'Tests of Controls', 'During the audit of Pinnacle Resources (fiscal year ending December 31), the auditor tested the purchase order authorization control at September 30 with no deviations. In November, management replaced the manual approval process with an automated workflow system. To rely on this control for the full year, the auditor should:', '["Extend the original sample by testing additional manual approvals from October through December", "Accept the interim results since no deviations were found and the new system is presumably stronger", "Inquire of management about the reasons for the change and document the response as sufficient evidence", "Evaluate the design of the new automated control and test its operating effectiveness after implementation"]'::jsonb, 3, 'Correct (D): AU-C 330.12 requires that when a control has changed, the auditor must evaluate the design of the replacement control and test its operating effectiveness for the period it was in operation, rather than simply extending the original test. Wrong (A): Extending the sample of the old manual control is inappropriate because that control no longer exists after November; however, the new control must be evaluated separately. Wrong (B): Assuming the new system is stronger without testing violates AU-C 330, which requires evidence of operating effectiveness regardless of the presumed improvement. Wrong (C): Inquiry alone is never sufficient to test operating effectiveness of controls per AU-C 330.A28.', 'medium', 3),

-- Q5: medium / L3 — Controls mitigating fraud risk must be tested currently
(1, 'Tests of Controls', 'Hartley and Dunn, CPAs, are auditing Coastal Enterprises for the year ending December 31, 2025. The auditor identified a significant risk of fraudulent revenue recognition and plans to rely on a control that requires credit manager approval before recording revenue on non-standard contracts. This control was tested in the 2024 audit with satisfactory results and has not changed. Under auditing standards, the auditor should:', '["Test the control in the current period because it addresses a significant risk", "Rely on the prior-year test results since the control has not changed", "Test the control on a rotational basis, skipping the current year and testing again in 2026", "Perform only inquiry to confirm the control still operates as designed"]'::jsonb, 0, 'Correct (A): AU-C 330.15 explicitly requires that controls over significant risks must be tested in the current period. Unlike controls over non-significant risks, these cannot rely solely on prior-period testing regardless of whether the controls have changed. Wrong (B): Although prior-year reliance is permitted for non-significant-risk controls, significant risk controls must be tested every year under AU-C 330.15. Wrong (C): Rotational testing under AU-C 330.14 applies only to controls not addressing significant risks; in contrast, fraud-related controls cannot be rotated. Wrong (D): Inquiry alone is never sufficient for testing operating effectiveness, regardless of the risk level.', 'medium', 3),

-- Q6: hard / L4 — Assessed RMM effect on extent of controls testing
(1, 'Tests of Controls', 'During the audit of Westbrook Financial, the engagement team assesses the risk of material misstatement for the loan origination process as high due to the complexity of underwriting judgments and prior-year findings of control deviations. The team plans to rely on three key controls in this process. Compared to a process assessed as low risk with no prior deviations, the auditor''s tests of controls for the loan origination process should differ primarily in that the auditor should:', '["Use only non-statistical sampling to preserve professional judgment flexibility", "Obtain more persuasive evidence by increasing the extent of testing and strengthening procedures", "Reduce planned reliance on controls and shift entirely to substantive procedures", "Decrease sample sizes because the high-risk assessment already provides sufficient awareness"]'::jsonb, 1, 'Correct (B): AU-C 330.A26 states that the greater the reliance placed on controls and the higher the assessed risk, the more persuasive the audit evidence needs to be. Rather than relying on inquiry and inspection alone, the auditor obtains more persuasive evidence by increasing extent and adding reperformance. Wrong (A): The choice between statistical and non-statistical sampling is not driven by risk level; however, either method can be appropriate at any risk level. Wrong (C): The question states the auditor plans to rely on controls; shifting entirely to substantive procedures abandons the planned strategy rather than adjusting it. Wrong (D): Higher risk requires larger, not smaller, sample sizes to obtain sufficient appropriate evidence.', 'hard', 4),

-- Q7: medium / L3 — Service org controls when no SOC report available
(1, 'Tests of Controls', 'Greystone Packaging outsources its inventory management to a third-party logistics provider. The user auditor of Greystone needs to evaluate the operating effectiveness of controls at the service organization but cannot obtain a SOC 1 report because the logistics provider does not engage a service auditor. To obtain evidence about the service organization''s controls, the user auditor''s most appropriate course of action is to:', '["Issue a qualified opinion due to a scope limitation", "Accept management''s written representation that the service organization''s controls are effective", "Perform tests of controls directly at the service organization or arrange for another auditor to do so", "Rely solely on Greystone''s complementary user entity controls as a substitute"]'::jsonb, 2, 'Correct (C): AU-C 402.13 provides that when a SOC report is not available, the user auditor may perform procedures at the service organization directly or use another auditor to do so. Unlike a scope limitation, alternative procedures are available. Wrong (A): The absence of a SOC report does not automatically create a scope limitation; however, the auditor must exhaust alternative procedures before concluding on scope. Wrong (B): Management representations alone do not constitute sufficient appropriate evidence about a third party''s operating effectiveness, rather than replacing direct testing. Wrong (D): CUECs are controls at the user entity; although they complement, they do not replace testing of the service organization''s own controls.', 'medium', 3),

-- Q8: medium / L2 — Parallel simulation as a CAAT
(1, 'Tests of Controls', 'During the audit of Briarwood Electronics, the auditor uses audit software to independently reprocess a set of actual client transactions through a program that mimics the client''s automated pricing control, then compares the auditor''s output with the client''s output to identify discrepancies. This computer-assisted audit technique is best described as:', '["Test data approach", "Integrated test facility", "Generalized audit software", "Parallel simulation"]'::jsonb, 3, 'Correct (D): AU-C 330.A30 describes the use of CAATs for testing automated controls. Parallel simulation involves the auditor creating an independent program that reprocesses actual client data and compares results with the client system''s output, rather than running fictitious data through the client''s system. Wrong (A): In contrast, test data involves submitting fictitious transactions through the client''s own system to see if controls process them correctly. Wrong (B): An integrated test facility embeds a dummy entity within the client''s live production system, unlike parallel simulation which uses a separate auditor-built program. Wrong (C): Although generalized audit software reads and analyzes client data files, it does not reprocess transactions through a simulated control.', 'medium', 2),

-- Q9: hard / L4 — Non-routine transaction controls combined evaluation
(1, 'Tests of Controls', 'Brookfield Industries completed two significant non-routine transactions during the year: a $12 million business combination and a $5 million restructuring charge. The auditor identified controls over each transaction, including management review of the purchase price allocation and CFO approval of restructuring estimates. When evaluating the operating effectiveness of these controls, the auditor faces a challenge because the transactions occurred only once each. To address this limitation, the auditor should primarily:', '["Supplement testing of the one-time controls with substantive procedures for the underlying balances", "Conclude that controls over non-routine transactions cannot be tested and adopt a purely substantive approach", "Increase the sample to include similar transactions from the prior two years for sufficient sample size", "Accept management''s assertion that the controls operated effectively given limited testing opportunity"]'::jsonb, 0, 'Correct (A): AU-C 330.A22 acknowledges that for non-routine transactions occurring infrequently, the auditor may have limited ability to test operating effectiveness through sampling. Rather than abandoning controls entirely, the auditor should supplement control testing with substantive procedures. Wrong (B): Although testing is limited, the auditor is not required to abandon control testing entirely; the control can still be evaluated through inspection and reperformance of the single occurrence. Wrong (C): Including prior-year transactions may not be appropriate because conditions, personnel, and systems may have changed, unlike current-year occurrences. Wrong (D): Management assertions alone do not constitute audit evidence of operating effectiveness; however, the auditor must independently evaluate the control.', 'hard', 4),

-- Q10: hard / L3 — Deficiency aggregation from multiple deviations
(1, 'Tests of Controls', 'During the audit of Ridgeway Holdings, the engagement team found the following control deviations across three revenue cycle controls: (1) two deviations in credit approval out of 25 tested, (2) one deviation in shipping authorization out of 25 tested, and (3) one deviation in invoice review out of 25 tested. Each deviation individually fell within the tolerable rate for its respective control. When evaluating these results, the auditor should consider that:', '["Each control passed individually so no further action is needed", "The combined effect of deviations across related controls may indicate a more severe deficiency", "Only the credit approval control requires additional testing because it had the most deviations", "The deviations must be reported as a material weakness because the total exceeds three"]'::jsonb, 1, 'Correct (B): AU-C 265.A7 requires the auditor to consider whether individual control deficiencies, when combined, represent a significant deficiency or material weakness. Although each deviation individually falls within tolerance, multiple deviations across related controls in the same cycle may collectively indicate a systemic weakness. Wrong (A): Passing individually does not eliminate the need to evaluate the combined effect; in contrast, the aggregation principle requires holistic assessment. Wrong (C): Focusing only on the control with the highest count ignores the aggregation principle, whereas all deviations in related controls must be evaluated together. Wrong (D): The auditor must evaluate the likelihood and magnitude of potential misstatement rather than applying a fixed numerical threshold.', 'hard', 3),

-- Q11: medium / L2 — Confidence level and sample size relationship
(1, 'Tests of Controls', 'Jensen and Park, CPAs, are determining the sample size for testing a billing approval control at Thornton Medical Group. The engagement team decides to increase the desired confidence level from 90% to 95% while keeping all other parameters unchanged. This change will most likely cause the sample size to:', '["Decrease because higher confidence requires less evidence from sampling", "Remain unchanged because confidence level does not affect controls testing sample size", "Increase because higher confidence requires more evidence to reduce sampling risk", "Depend entirely on the size of the population rather than the confidence level"]'::jsonb, 2, 'Correct (C): AU-C 530.A11 notes that sample size is affected by the desired level of assurance. A higher confidence level means the auditor accepts less sampling risk, which requires a larger sample. In contrast, lower confidence allows a smaller sample. Wrong (A): Higher confidence requires more, not less, evidence; this relationship is the inverse of what is stated. Wrong (B): Confidence level is a key determinant of sample size; however, this applies in both statistical and non-statistical approaches for tests of controls. Wrong (D): Although population size can affect sample size for small populations, the confidence level independently and directly affects sample size regardless of population size.', 'medium', 2),

-- Q12: easy / L1 — Timing of controls testing: interim vs year-end
(1, 'Tests of Controls', 'When the auditor tests controls at an interim date rather than at year-end, the auditor must also:', '["Retest all controls at year-end using the same sample size", "Issue a qualified opinion disclosing the interim testing limitation", "Withdraw from the engagement if controls cannot be tested at year-end", "Obtain evidence about significant changes in controls during the remaining period"]'::jsonb, 3, 'Correct (D): AU-C 330.12 requires that when the auditor tests controls at an interim date and plans to rely on those controls, the auditor must obtain evidence about whether significant changes occurred between the interim date and year-end. Wrong (A): Rather than retesting the entire sample at year-end, the auditor needs evidence about changes and may extend testing as warranted. Wrong (B): Testing at interim does not create a scope limitation requiring qualification; in contrast, it is a standard audit approach with established bridging procedures. Wrong (C): Withdrawal is not required; however, the auditor has multiple options for extending interim conclusions to year-end.', 'easy', 1),

-- Q13: easy / L2 — Inquiry must be combined with other procedures
(1, 'Tests of Controls', 'During the audit of Oakdale Services, the auditor interviewed the accounts payable clerk who confirmed that she reviews every invoice for proper approval before processing payment. The auditor documented the inquiry and concluded that the approval control is operating effectively. This conclusion is:', '["Inappropriate because inquiry alone is not sufficient to test operating effectiveness", "Appropriate because the clerk is the most knowledgeable person about the control", "Appropriate because inquiry provides direct evidence of control operation", "Inappropriate only if the auditor suspects fraud in accounts payable"]'::jsonb, 0, 'Correct (A): AU-C 330.A28 states that inquiry alone is not sufficient to test the operating effectiveness of controls. Rather than relying solely on inquiry, the auditor must combine it with at least one other procedure such as inspection, observation, or reperformance. Wrong (B): Although the clerk may be knowledgeable, this does not overcome the inherent limitation of inquiry as a single source of evidence. Wrong (C): Inquiry is generally considered less reliable than inspection or reperformance because it relies on the respondent''s honesty and recall, unlike documentary evidence. Wrong (D): The requirement to combine inquiry with other procedures applies to all tests of controls, not only when fraud is suspected.', 'easy', 2),

-- Q14: easy / L1 — Controls over significant risks require current-period testing
(1, 'Tests of Controls', 'Under AU-C 330, controls that address a significant risk must be tested:', '["Only in the initial year of the engagement", "In the current audit period every year the auditor plans to rely on them", "At least once every three years on a rotational basis", "Only when the auditor suspects a material misstatement has occurred"]'::jsonb, 1, 'Correct (B): AU-C 330.15 requires that if the auditor plans to rely on controls over a significant risk, those controls must be tested in the current period. Unlike non-significant-risk controls, prior-year testing alone is never sufficient regardless of whether the controls have changed. Wrong (A): Testing only in the initial year would leave the auditor without current-period evidence in subsequent years, whereas AU-C 330.15 requires annual testing. Wrong (C): The three-year rotation approach applies only to controls not addressing significant risks; in contrast, significant risk controls must be tested every year. Wrong (D): Testing is required whenever the auditor plans to rely on the control, rather than only when a misstatement is suspected.', 'easy', 1),

-- Q15: easy / L1 — Extent of testing proportional to planned reliance
(1, 'Tests of Controls', 'The extent of the auditor''s tests of controls is primarily influenced by:', '["The total number of employees at the entity", "The fee arrangement agreed upon in the engagement letter", "The degree to which the auditor plans to rely on the controls to reduce substantive testing", "Whether the entity is publicly traded or privately held"]'::jsonb, 2, 'Correct (C): AU-C 330.A26 states that the more the auditor relies on the operating effectiveness of controls in the risk assessment, the greater the extent of tests of controls. In contrast, less reliance permits less extensive testing. Wrong (A): The number of employees does not directly determine the extent of control testing; rather than headcount, population size and control frequency are the relevant factors. Wrong (B): Fee arrangements do not dictate the extent of audit procedures; however, the auditor must obtain sufficient appropriate evidence regardless of fee. Wrong (D): Although being publicly or privately held affects which standards apply, it does not directly determine the extent of tests of controls under AU-C 330.', 'easy', 1)
;

COMMIT;
