-- Migration: Question generation — TCP batch 32 (16 questions)
-- Date: 2026-03-25
-- Topic: Capital Structure Tax Planning
-- Difficulty: 5E / 8M / 3H
-- Bloom's: L1:3 / L2:6 / L3:5 / L4:2

BEGIN;

INSERT INTO questions (section_id, topic, stem, choices, correct_index, explanation, difficulty, cognitive_level)
VALUES

-- Q1: easy / L2 — Section 385 $50 million threshold exemption
(6, 'Capital Structure Tax Planning', $EXPL$Northfield Corp is a member of an expanded group with total related-party debt of $42,000,000. The corporation issues additional notes to its parent company in connection with a distribution. Under the Section 385 recharacterization rules, what is the most likely outcome?$EXPL$, $EXPL$["The debt is exempt from the recharacterization rules because total related-party debt is below the $50 million threshold", "The debt is automatically recharacterized as equity because it was issued in connection with a distribution", "The debt is respected only if the interest rate exceeds the applicable federal rate", "The debt is recharacterized as equity only if the debt-to-equity ratio exceeds 4:1"]$EXPL$::jsonb, 0, $EXPL$Correct (A): Reg. Section 1.385-3 provides a $50 million threshold exemption. Expanded group members with total related-party debt below $50 million are exempt from the automatic recharacterization rules, even when the debt is issued in connection with a distribution or affiliate stock acquisition.
Wrong (B): While debt issued as a distribution is normally subject to recharacterization, the $50 million threshold exemption overrides this rule when total group related-party debt is below the threshold.
Wrong (C): The interest rate relative to AFR is relevant for Section 7872 below-market loan rules, not the Section 385 recharacterization threshold.
Wrong (D): No specific 4:1 ratio trigger exists in the Section 385 recharacterization rules; the exemption is based on total related-party debt.$EXPL$, 'easy', 2),

-- Q2: hard / L3 — EBITDA-to-EBIT transition impact on deductible interest
(6, 'Capital Structure Tax Planning', $EXPL$Ridgeway Manufacturing has taxable income before interest deduction of $4,000,000, business interest expense of $1,800,000, no business interest income, and depreciation and amortization of $1,500,000 for 2025. The CFO wants to compare the current EBIT-basis ATI calculation under Section 163(j) to the former EBITDA-basis rules used before 2022. What is the difference in deductible interest between the two methods?$EXPL$, $EXPL$["The EBITDA basis allows $450,000 more deductible interest than the EBIT basis", "Under the EBITDA basis all $1,800,000 is deductible, but the EBIT basis limits the deduction to $1,740,000, a difference of $60,000", "Both methods allow full deduction of the $1,800,000 because ATI exceeds the interest expense under either calculation", "The EBIT basis is more favorable because it produces a larger deduction limit"]$EXPL$::jsonb, 1, $EXPL$Correct (B): Under IRC Section 163(j), ATI on the EBIT basis (post-2021) is $4,000,000 + $1,800,000 = $5,800,000 (depreciation NOT added back), producing a limit of 30% x $5,800,000 = $1,740,000, so $60,000 is disallowed. Under the EBITDA basis, ATI = $5,800,000 + $1,500,000 = $7,300,000, and the limit is 30% x $7,300,000 = $2,190,000, allowing the full $1,800,000.
Wrong (A): The $450,000 figure does not correspond to the correct calculation under either method.
Wrong (C): The EBIT-basis limit is $1,740,000, which is less than the $1,800,000 interest expense, so not all interest is deductible under current rules.
Wrong (D): The EBIT basis is more restrictive, not more favorable, because excluding D&A from ATI produces a lower base for the 30% calculation.$EXPL$, 'hard', 3),

-- Q3: hard / L4 — Section 382 interaction with 163(j) interest carryforwards
(6, 'Capital Structure Tax Planning', $EXPL$Apex Corp has $500,000 of disallowed business interest expense carried forward under Section 163(j). Apex then undergoes an ownership change as defined under Section 382. The Section 382 annual limitation is $200,000. A tax advisor must evaluate how the carried-forward interest is treated post-ownership change. What is the correct analysis?$EXPL$, $EXPL$["The entire $500,000 carryforward is permanently disallowed after the ownership change", "The carryforward is fully available because Section 382 does not apply to interest expense carryforwards", "Section 382 may limit the use of the acquired corporation's interest carryforwards, restricting the annual deduction to the Section 382 limitation amount even if the Section 163(j) formula would otherwise permit a larger deduction", "The interest carryforward converts to a net operating loss upon the ownership change and follows NOL carryforward rules instead"]$EXPL$::jsonb, 2, $EXPL$Correct (C): Under IRC Section 382, an ownership change limits the annual amount of pre-change tax attributes—including disallowed business interest carryforwards under Section 163(j)—that the loss corporation can use. The Section 382 limitation caps the annual deduction, potentially restricting interest carryforwards below what the 30%-of-ATI formula would otherwise allow.
Wrong (A): The carryforward is not permanently disallowed; it remains available but is subject to the annual Section 382 limitation in each subsequent year.
Wrong (B): Section 382 does apply to interest expense carryforwards from Section 163(j), treating them as pre-change losses subject to the annual limitation.
Wrong (D): Disallowed interest carryforwards retain their character as business interest expense and do not convert to NOLs after an ownership change.$EXPL$, 'hard', 4),

-- Q4: easy / L1 — Principal repayment reclassified as stock redemption
(6, 'Capital Structure Tax Planning', $EXPL$If the IRS successfully reclassifies a shareholder's debt instrument as equity, how is the repayment of principal treated?$EXPL$, $EXPL$["As a tax-free return of the shareholder's original loan amount", "As ordinary income to the shareholder in full", "As a capital loss to the corporation making the payment", "As a stock redemption subject to Section 302 analysis"]$EXPL$::jsonb, 3, $EXPL$Correct (D): When debt is reclassified as equity under Section 385 or the multi-factor test, the repayment of what was characterized as principal is recharacterized as a stock redemption. The shareholder must then apply the Section 302 tests to determine whether the payment is treated as a sale or exchange or as a dividend distribution.
Wrong (A): Once reclassified as equity, the payment is no longer a return of a loan; it is treated as a corporate distribution on stock, not a tax-free return of principal.
Wrong (B): The payment is not automatically ordinary income; it must first be analyzed under the Section 302 redemption rules to determine its character.
Wrong (C): The reclassification affects the shareholder's treatment, not the corporation's; the corporation does not recognize a capital loss from the payment.$EXPL$, 'easy', 1),

-- Q5: medium / L3 — S corp vs partnership interest carryforward tracking
(6, 'Capital Structure Tax Planning', $EXPL$Brentwood LLC (a partnership) and Summerfield Inc (an S corporation) each have $150,000 of disallowed business interest expense under Section 163(j) in 2025. Partner A owns 50% of Brentwood and Shareholder B owns 50% of Summerfield. How is the disallowed interest tracked for each entity type?$EXPL$, $EXPL$["In the partnership, $75,000 is allocated to Partner A and tracked at the partner level; in the S corporation, the full $150,000 is tracked at the corporate level", "Both entities track disallowed interest at the entity level with no allocation to owners", "Both entities allocate disallowed interest to owners proportionally and track it at the owner level", "The partnership tracks interest at the entity level while the S corporation allocates it to shareholders"]$EXPL$::jsonb, 0, $EXPL$Correct (A): Under IRC Section 163(j)(4), partnerships allocate disallowed business interest expense to each partner based on their allocable share, and the carryforward is tracked at the partner level. For S corporations, the disallowed interest is tracked at the corporate level rather than being allocated to individual shareholders.
Wrong (B): Partnerships allocate disallowed interest to partners for tracking at the partner level, not at the entity level.
Wrong (C): While partnerships allocate to owners, S corporations do not; S corporations track the disallowed interest at the corporate level.
Wrong (D): This reverses the correct treatment. Partnerships allocate to partners; S corporations track at the entity level.$EXPL$, 'medium', 3),

-- Q6: medium / L2 — Section 385 72-month funding rule
(6, 'Capital Structure Tax Planning', $EXPL$Crestline Corp issued a $3,000,000 note to its parent company in January 2024. In November 2024, Crestline distributed $2,500,000 in cash to the same parent. Under Reg. Section 1.385-3, assuming no threshold exemption applies, how might the IRS treat the January note?$EXPL$, $EXPL$["The note is respected as debt because it was issued before the distribution occurred", "The note may be recharacterized as equity under the funding rule if it effectively funded the distribution within the 72-month window", "The note is automatically voided and treated as if it was never issued", "The note is respected as debt because the distribution was made in cash rather than property"]$EXPL$::jsonb, 1, $EXPL$Correct (B): Under Reg. Section 1.385-3, the funding rule provides that related-party debt issued within 72 months of a distribution or affiliate stock acquisition may be recharacterized as equity if the debt effectively funded the transaction. The proximity of the January note to the November distribution falls well within this window.
Wrong (A): Issuance before the distribution does not protect the note; the 72-month funding rule looks at debt issued within 72 months before or after the distribution.
Wrong (C): The note is not voided; it is recharacterized as equity, meaning the instrument is treated as stock rather than debt for tax purposes.
Wrong (D): The form of the distribution (cash vs. property) is not relevant to the funding rule analysis; the rule applies regardless of distribution form.$EXPL$, 'medium', 2),

-- Q7: medium / L2 — Proportionality factor in debt-equity classification
(6, 'Capital Structure Tax Planning', $EXPL$Meridian Corp has two equal 50/50 shareholders, Taylor and Jordan. Taylor holds $500,000 of Meridian corporate notes and Jordan holds the other $500,000. Each note bears market-rate interest with a 10-year maturity. Under the multi-factor test, which characteristic most strongly supports recharacterization of the notes as equity?$EXPL$, $EXPL$["The 10-year maturity is excessively long for corporate debt instruments", "The market-rate interest demonstrates the instruments lack a genuine debtor-creditor relationship", "The debt is held in the same proportion as the shareholders' stock ownership, raising the proportionality concern", "The total debt of $1,000,000 is presumptively excessive under statutory thin capitalization limits"]$EXPL$::jsonb, 2, $EXPL$Correct (C): Under the multi-factor debt-equity classification test, proportionality is a critical indicator. When shareholders hold debt in the same proportion as their stock ownership, courts are more likely to view the instruments as disguised equity contributions rather than genuine debt.
Wrong (A): A 10-year maturity is a reasonable term for corporate debt and actually supports debt classification by demonstrating a fixed repayment date.
Wrong (B): Market-rate interest actually favors debt treatment, as it demonstrates arm's-length terms consistent with a genuine debtor-creditor relationship.
Wrong (D): The US has no statutory thin capitalization limit; the total amount alone does not trigger recharacterization without knowing the equity base.$EXPL$, 'medium', 2),

-- Q8: medium / L2 — NOL and Section 199A add-backs in ATI computation
(6, 'Capital Structure Tax Planning', $EXPL$Whitmore Industries reports the following for 2025: taxable income before interest deduction of $2,000,000, business interest expense of $800,000, business interest income of $100,000, a net operating loss deduction of $300,000, and a Section 199A deduction of $150,000. Both the NOL and 199A deductions are already reflected in the $2,000,000 figure. What is Whitmore's adjusted taxable income (ATI) for Section 163(j) purposes?$EXPL$, $EXPL$["$2,000,000", "$2,700,000", "$2,850,000", "$3,150,000"]$EXPL$::jsonb, 3, $EXPL$Correct (D): Under IRC Section 163(j), ATI starts with taxable income ($2,000,000), then adds back business interest expense ($800,000), subtracts business interest income ($100,000), adds back the NOL deduction ($300,000), and adds back the Section 199A deduction ($150,000). ATI = $2,000,000 + $800,000 - $100,000 + $300,000 + $150,000 = $3,150,000.
Wrong (A): This is the unadjusted taxable income before any ATI modifications are applied.
Wrong (B): This omits the NOL deduction add-back ($300,000) and the Section 199A deduction add-back ($150,000) from the ATI computation.
Wrong (C): This omits the NOL deduction add-back, only including the 199A adjustment.$EXPL$, 'medium', 2),

-- Q9: easy / L1 — Floor plan financing interest definition
(6, 'Capital Structure Tax Planning', $EXPL$Under the Section 163(j) business interest limitation formula, floor plan financing interest is associated with which type of business?$EXPL$, $EXPL$["Motor vehicle dealers financing inventory held for sale", "Real estate developers financing construction projects", "Agricultural producers financing crop storage", "Financial institutions financing loan portfolios"]$EXPL$::jsonb, 0, $EXPL$Correct (A): Under IRC Section 163(j)(9), floor plan financing interest is defined as interest paid on debt used to finance the acquisition of motor vehicles held for sale or lease. This component is added to the deduction limit, effectively exempting auto dealer inventory financing from the 30% ATI restriction.
Wrong (B): Real estate developers may elect out of Section 163(j) under the real property trade or business election, but their financing is not classified as floor plan financing.
Wrong (C): Agricultural producers may elect out under the farming business election, but crop storage financing is not floor plan financing interest.
Wrong (D): Financial institutions are generally exempt from Section 163(j), but their loan portfolio financing is not related to floor plan financing.$EXPL$, 'easy', 1),

-- Q10: medium / L3 — Death of taxpayer loses interest carryforward
(6, 'Capital Structure Tax Planning', $EXPL$Marcus Chen, an individual taxpayer, has $175,000 of disallowed business interest expense carried forward under Section 163(j). Marcus passes away on March 15, 2025, with the carryforward still unused. His estate inherits his business assets. How is the unused interest carryforward treated?$EXPL$, $EXPL$["The estate inherits the carryforward and may deduct it in the estate's first tax year", "The unused carryforward is lost upon the taxpayer's death and does not transfer to the estate or beneficiaries", "The carryforward is accelerated as a deduction on the decedent's final individual tax return", "The carryforward passes to beneficiaries in proportion to their inheritance shares"]$EXPL$::jsonb, 1, $EXPL$Correct (B): Under IRC Section 163(j), upon the death of a taxpayer, any unused disallowed business interest expense carryforward is lost. Unlike certain other tax attributes, the interest carryforward does not receive a step-up, does not transfer to the estate, and cannot be claimed by beneficiaries.
Wrong (A): The estate does not inherit the carryforward; it expires upon the taxpayer's death.
Wrong (C): The carryforward cannot be accelerated onto the final return; it is simply lost when the taxpayer dies.
Wrong (D): The carryforward is not an inheritable tax attribute and does not pass to beneficiaries regardless of their shares.$EXPL$, 'medium', 3),

-- Q11: easy / L2 — Section 385 documentation requirements
(6, 'Capital Structure Tax Planning', $EXPL$Lakeview Corp advances $2,000,000 to its wholly owned subsidiary, Bayshore Inc. The subsidiary treats the advance as debt on its books but maintains no written loan agreement. Under Reg. Section 1.385-2, what is the primary documentation deficiency?$EXPL$, $EXPL$["The absence of a sinking fund requirement for principal repayment", "The failure to register the instrument with the Securities and Exchange Commission", "The absence of a written unconditional obligation to pay a fixed or determinable sum on demand or at a specified date", "The failure to obtain a third-party credit rating for the instrument"]$EXPL$::jsonb, 2, $EXPL$Correct (C): Under Reg. Section 1.385-2, related-party debt must be supported by a written unconditional obligation to pay a fixed or determinable sum on demand or at a specified date. Failure to maintain this documentation creates a rebuttable presumption that the instrument is equity rather than debt.
Wrong (A): While a repayment schedule supports debt classification, a sinking fund is not a specific requirement under Reg. 1.385-2 documentation rules.
Wrong (B): SEC registration is a securities law requirement and is not part of the Section 385 tax documentation requirements for related-party debt.
Wrong (D): A third-party credit rating is not among the documentation elements required under Reg. 1.385-2.$EXPL$, 'easy', 2),

-- Q12: medium / L3 — Related-party vs third-party debt scope of Section 385
(6, 'Capital Structure Tax Planning', $EXPL$Silverton Corp borrows $5,000,000 from First National Bank (an unrelated third party) and separately borrows $3,000,000 from its 80% parent company. Both loans have identical terms including 7% interest and 10-year maturity. A CPA is evaluating compliance with Section 385 documentation and recharacterization rules. What is the correct conclusion?$EXPL$, $EXPL$["Both loans must satisfy Section 385 documentation requirements because they have identical terms", "Neither loan is subject to Section 385 because Silverton has less than $50 million in total debt", "Both loans are subject to Section 385 because the corporation has multiple creditors", "Only the $3,000,000 parent company loan is subject to Section 385 requirements because the regulations apply exclusively to related-party debt"]$EXPL$::jsonb, 3, $EXPL$Correct (D): Section 385 regulations (Reg. Sections 1.385-2 and 1.385-3) apply only to related-party debt. The $5,000,000 bank loan from an unrelated third party is not subject to these documentation or automatic recharacterization rules, regardless of its terms. Only the $3,000,000 loan from the 80% parent company falls within the scope.
Wrong (A): Identical loan terms do not bring third-party debt within the scope of Section 385; the regulations are triggered by the related-party relationship, not the terms.
Wrong (B): The $50 million threshold exempts related-party debt from recharacterization rules, but does not determine whether Section 385 applies at all.
Wrong (C): Having multiple creditors is irrelevant; Section 385 focuses on the relationship between the debtor and each creditor individually.$EXPL$, 'medium', 3),

-- Q13: hard / L4 — Multi-factor subordination + repayment source evaluation
(6, 'Capital Structure Tax Planning', $EXPL$Oakmont Industries issues $4,000,000 in notes to its sole shareholder with the following terms: interest payments are made only when the board declares them, the notes are subordinated to all third-party creditors, repayment depends on future profits from a speculative startup division, and the notes have no fixed maturity date. The shareholder argues the instruments are debt because a written promissory note exists. What is the most likely classification?$EXPL$, $EXPL$["Equity, because discretionary payments, full subordination, speculative repayment source, and no fixed maturity overwhelmingly point to equity despite the written instrument", "Debt, because the written promissory note is the single most important factor in the multi-factor test", "Debt, because subordination to third-party creditors demonstrates the shareholder's intent to be a creditor", "Equity, but only if the corporation's debt-to-equity ratio exceeds the statutory 3:1 threshold"]$EXPL$::jsonb, 0, $EXPL$Correct (A): Under the multi-factor debt-equity classification test, no single factor is determinative. Here, four key factors—discretionary interest (not unconditional), full subordination, speculative repayment source, and no fixed maturity—all point strongly toward equity. A written note alone cannot overcome this weight of evidence.
Wrong (B): The written note is one factor among many; courts consistently hold that no single factor controls, and the totality of circumstances here overwhelmingly favors equity classification.
Wrong (C): Subordination to all third-party creditors actually supports equity classification, not debt, because it means the shareholder's claim is junior to all outside creditors, resembling a residual equity interest.
Wrong (D): The US has no statutory 3:1 debt-to-equity threshold; thin capitalization is evaluated under a facts-and-circumstances analysis, and the ratio is only one factor.$EXPL$, 'hard', 4),

-- Q14: easy / L1 — Tax shelters excluded from small business exception
(6, 'Capital Structure Tax Planning', $EXPL$Which type of taxpayer is prohibited from using the Section 163(j) small business exception, regardless of its gross receipts level?$EXPL$, $EXPL$["A sole proprietorship with no employees", "A tax shelter as defined under the Internal Revenue Code", "A partnership with fewer than ten partners", "A corporation that files a consolidated return"]$EXPL$::jsonb, 1, $EXPL$Correct (B): Under IRC Section 163(j)(3), the small business exception based on the gross receipts test is unavailable to tax shelters regardless of their average annual gross receipts. A tax shelter cannot benefit from this exemption even if its three-year average receipts fall below the threshold.
Wrong (A): Sole proprietorships without employees are not excluded from the small business exception; they may qualify if they meet the gross receipts test.
Wrong (C): The number of partners does not affect eligibility for the small business exception; partnerships may qualify based on gross receipts.
Wrong (D): Filing a consolidated return does not preclude use of the small business exception; the exception requires aggregating all group members' receipts but does not exclude consolidated filers.$EXPL$, 'easy', 1),

-- Q15: medium / L3 — Depreciation not added back to ATI post-2021 impact
(6, 'Capital Structure Tax Planning', $EXPL$Westbrook Heavy Equipment has taxable income before interest deduction of $2,000,000, business interest expense of $1,500,000, no business interest income, and depreciation of $1,500,000 for 2025. The controller mistakenly calculates ATI by adding back depreciation to taxable income as was done under the pre-2022 EBITDA rules. What is the effect of this error?$EXPL$, $EXPL$["The error has no effect because depreciation is correctly added back to ATI under current law", "The error understates ATI because depreciation should be subtracted from taxable income", "The error overstates ATI by $1,500,000, inflating the deduction limit from $1,050,000 to $1,500,000 and incorrectly allowing full interest deductibility", "The error understates ATI because only 50% of depreciation should be added back for 2025"]$EXPL$::jsonb, 2, $EXPL$Correct (C): Under IRC Section 163(j) for tax years beginning after 2021, ATI is computed on an EBIT basis—depreciation is NOT added back. Correct ATI = $2,000,000 + $1,500,000 = $3,500,000; limit = 30% x $3,500,000 = $1,050,000, disallowing $450,000. The controller's erroneous ATI = $3,500,000 + $1,500,000 = $5,000,000; limit = 30% x $5,000,000 = $1,500,000, incorrectly allowing full deduction.
Wrong (A): Depreciation was added back under the pre-2022 EBITDA basis but is no longer added back under the post-2021 EBIT basis.
Wrong (B): Depreciation is neither added back nor subtracted; it is simply excluded from the ATI adjustments under current rules.
Wrong (D): There is no 50% depreciation add-back provision; the transition was a complete elimination of the D&A add-back starting in 2022.$EXPL$, 'medium', 3),

-- Q16: medium / L2 — Debt issued as distribution recharacterized as stock under Section 385
(6, 'Capital Structure Tax Planning', $EXPL$Pinecrest Corp issues $1,500,000 in promissory notes directly to its shareholders as a distribution in lieu of a cash dividend. Assuming no threshold exemption applies, how are these notes treated under Reg. Section 1.385-3?$EXPL$, $EXPL$["The notes are treated as valid debt obligations with deductible interest payments", "The notes are treated as a constructive cash dividend reportable at the date of issuance", "The notes are treated as a nontaxable return of capital to the extent of each shareholder's stock basis", "The notes are automatically recharacterized as stock because debt issued to a shareholder as a distribution is treated as equity under the recharacterization rules"]$EXPL$::jsonb, 3, $EXPL$Correct (D): Under Reg. Section 1.385-3, debt issued to a shareholder as a distribution is one of the enumerated transactions that triggers automatic recharacterization of the debt as equity (treated as stock). As a result, interest payments on the notes would not be deductible by Pinecrest Corp.
Wrong (A): Because the notes are recharacterized as stock, the corporation cannot deduct the payments as interest; they are treated as nondeductible distributions on equity.
Wrong (B): The notes are recharacterized as stock, not treated as a cash dividend. The tax treatment follows from equity classification, not dividend characterization of the notes themselves.
Wrong (C): Return of capital treatment applies to actual distributions that exceed E&P, not to the classification of the instrument itself under Section 385.$EXPL$, 'medium', 2)
;

COMMIT;