-- Migration: Question generation — BAR batch 24 (30 questions)
-- Date: 2026-03-25
-- Topic: Intangible Assets Advanced
-- Difficulty: 9E / 15M / 6H
-- Bloom's: L1:6 / L2:10 / L3:9 / L4:5

BEGIN;

INSERT INTO questions (section_id, topic, stem, choices, correct_index, explanation, difficulty, cognitive_level)
VALUES

-- Q1: medium / L3 — Useful life reassessment for finite-lived intangible
(4, 'Intangible Assets Advanced', $EXPL$Sterling Corp. acquired a technology license intangible 3 years ago with an original useful life of 10 years and a carrying amount of $700,000 (net of $300,000 accumulated amortization). A recent regulatory change significantly extends the technology's viability, and management now estimates the remaining useful life is 12 years instead of 7 years. Under ASC 350-30-35-11, how should Sterling account for this change?$EXPL$, $EXPL$["Amortize the $700,000 carrying amount over the revised 12-year remaining life prospectively", "Restate prior periods to reflect the 12-year remaining life from inception", "Continue amortizing over the original 7-year remaining life and disclose the change", "Write the asset up to $880,000 to reflect the extended useful life"]$EXPL$::jsonb, 0, $EXPL$Correct (A): ASC 350-30-35-11 requires that changes in the useful life of a finite-lived intangible asset be accounted for as a change in accounting estimate. The remaining carrying amount of $700,000 is amortized prospectively over the revised remaining useful life of 12 years. Wrong (B): Changes in estimated useful life are prospective, not retroactive; prior period restatement is not required. Wrong (C): Continuing to use the original estimate after a reassessment would not reflect the revised economic reality. Wrong (D): An upward revaluation of intangible assets is not permitted under U.S. GAAP.$EXPL$, 'medium', 3),

-- Q2: medium / L2 — Private company goodwill amortization alternative
(4, 'Intangible Assets Advanced', $EXPL$Oakmont LLC is a private company that elected the accounting alternative for goodwill under ASC 350-20-35-62. The company recognized $2,000,000 of goodwill in a business combination. Under this alternative, what is the default amortization period if the entity cannot determine a more appropriate useful life?$EXPL$, $EXPL$["15 years, consistent with Section 197 tax amortization", "10 years on a straight-line basis", "20 years on a straight-line basis", "No amortization; the alternative only simplifies the impairment test"]$EXPL$::jsonb, 1, $EXPL$Correct (B): ASC 350-20-35-63 provides a 10-year default amortization period on a straight-line basis when the entity elects the private company alternative and cannot determine a more appropriate useful life. This alternative allows amortization instead of the annual impairment-only model. Wrong (A): The 15-year Section 197 period applies for tax purposes, not the GAAP private company alternative. Wrong (C): Twenty years is not the default period under the alternative. Wrong (D): The private company alternative specifically permits amortization of goodwill; it is not limited to impairment test simplification.$EXPL$, 'medium', 2),

-- Q3: hard / L4 — Reacquired rights in a business combination
(4, 'Intangible Assets Advanced', $EXPL$Prior to acquiring Zenith Corp., Apex Inc. had licensed its proprietary technology to Zenith under a 7-year agreement with 4 years remaining. The license terms were favorable to Zenith relative to current market rates. In accounting for the business combination under ASC 805, how should Apex treat the reacquired right?$EXPL$, $EXPL$["Recognize the reacquired right at fair value and amortize over 7 years", "Do not recognize the reacquired right since it is between the combined entity and itself", "Recognize the reacquired right as an intangible asset measured based on the remaining contractual term and recognize any settlement gain or loss separately", "Eliminate the license and adjust goodwill for any off-market terms"]$EXPL$::jsonb, 2, $EXPL$Correct (C): ASC 805-20-25-14 requires that a reacquired right be recognized as an identifiable intangible asset separate from goodwill. It is measured based on the remaining contractual term (4 years here), excluding renewals. Any settlement gain or loss from favorable or unfavorable terms relative to market is recognized separately per ASC 805-20-30-20. Wrong (A): The amortization period is the remaining 4-year contractual term, not the original 7-year term. Wrong (B): Despite being between the same combined entity, reacquired rights must be separately recognized under ASC 805. Wrong (D): Goodwill is not adjusted for off-market terms; a settlement gain or loss is recognized separately.$EXPL$, 'hard', 4),

-- Q4: medium / L2 — Goodwill allocated on disposal of portion of reporting unit
(4, 'Intangible Assets Advanced', $EXPL$Pinnacle Corp. has a single reporting unit with a carrying amount of $25,000,000, including $6,000,000 of goodwill. Pinnacle disposes of a business that constitutes a portion of the reporting unit. The disposed business has a fair value of $5,000,000, and the entire reporting unit has a fair value of $25,000,000. Under ASC 350-20-40-3, how much goodwill should be included in the carrying amount of the disposed business?$EXPL$, $EXPL$["The full $5,000,000 fair value of the disposed business", "All $6,000,000 of the reporting unit goodwill", "No goodwill, because it stays with the retained portion", "$1,200,000 based on relative fair values"]$EXPL$::jsonb, 3, $EXPL$Correct (D): ASC 350-20-40-3 requires that when a business constituting a portion of a reporting unit is disposed of, goodwill is allocated based on the relative fair values. Allocated goodwill = $6,000,000 x ($5,000,000 / $25,000,000) = $1,200,000. Wrong (A): This amount represents the fair value of the disposed business, not the allocated goodwill. Wrong (B): Allocating all goodwill to the disposed portion ignores the relative fair value requirement. Wrong (C): Goodwill must be allocated to the disposed business under ASC 350-20-40-3 when a portion of a reporting unit is disposed.$EXPL$, 'medium', 2),

-- Q5: hard / L4 — Reorganization of reporting units — goodwill reallocation
(4, 'Intangible Assets Advanced', $EXPL$Meridian Corp. reorganizes from two reporting units (Alpha and Beta) into three (North, South, and Central). Alpha had $4,000,000 of goodwill with a fair value of $10,000,000. After reorganization, North receives assets formerly in Alpha with a fair value of $6,000,000, and South receives the remainder with a fair value of $4,000,000. Under ASC 350-20-35-45, how much goodwill is allocated to North?$EXPL$, $EXPL$["$2,400,000", "$4,000,000", "$2,000,000", "$1,600,000"]$EXPL$::jsonb, 0, $EXPL$Correct (A): ASC 350-20-35-45 requires that when reporting units are reorganized, goodwill is reallocated using a relative fair value approach. North receives $4,000,000 x ($6,000,000 / $10,000,000) = $2,400,000. Wrong (B): Allocating all of Alpha's goodwill to North ignores the relative fair value allocation requirement. Wrong (C): This would be an equal split, which is not the required methodology. Wrong (D): This is the amount allocated to South ($4,000,000 x $4,000,000 / $10,000,000 = $1,600,000), not to North.$EXPL$, 'hard', 4),

-- Q6: easy / L1 — Internally developed intangibles expensed
(4, 'Intangible Assets Advanced', $EXPL$Under U.S. GAAP, how are costs of internally developing an intangible asset such as a brand name or customer list generally treated?$EXPL$, $EXPL$["Capitalized as an indefinite-lived intangible asset", "Expensed as incurred", "Capitalized and amortized over 15 years", "Deferred and recognized when the asset generates revenue"]$EXPL$::jsonb, 1, $EXPL$Correct (B): ASC 350-30-25-3 states that costs of internally developing intangible assets such as brand names, customer lists, and similar items are expensed as incurred. Only intangible assets acquired from external parties or in a business combination are eligible for capitalization. Wrong (A): Internally developed intangibles cannot be capitalized under GAAP regardless of useful life classification. Wrong (C): The 15-year amortization applies to Section 197 tax intangibles, not GAAP capitalization of internally developed items. Wrong (D): GAAP does not permit deferral of these costs until revenue generation.$EXPL$, 'easy', 1),

-- Q7: medium / L2 — ASC 805 identifiability criterion
(4, 'Intangible Assets Advanced', $EXPL$Harbor Inc. acquires Crest Corp. in a business combination. During the purchase price allocation, Harbor identifies a proprietary manufacturing process that Crest has never licensed to third parties and that could not be sold separately. Under ASC 805-20-25-10, can Harbor recognize this manufacturing process as a separate intangible asset?$EXPL$, $EXPL$["No, because it cannot be sold or licensed separately", "No, because manufacturing processes are always absorbed into goodwill", "Yes, if the process arose from contractual or legal rights such as a patent", "Yes, because all manufacturing processes are identifiable in a business combination"]$EXPL$::jsonb, 2, $EXPL$Correct (C): ASC 805-20-25-10 establishes two paths for identifiability: (1) the asset is separable (can be sold, transferred, or licensed) or (2) it arises from contractual or legal rights. Even if not separable, a patented manufacturing process meets the contractual-legal criterion and is recognized separately. Wrong (A): Separability is only one of two identifiability criteria; the contractual-legal criterion is an alternative path. Wrong (B): Manufacturing processes can be separately recognized if they meet either identifiability criterion. Wrong (D): Not all processes are identifiable; they must meet at least one of the two criteria.$EXPL$, 'medium', 2),

-- Q8: easy / L2 — Residual value for finite-lived intangible assets
(4, 'Intangible Assets Advanced', $EXPL$Birch Corp. acquires a customer relationship intangible in a business combination for $500,000 with an estimated useful life of 8 years. No third party has committed to purchase the asset at the end of its useful life, and there is no active market for such assets. Under ASC 350-30-35-8, what residual value should Birch assume for amortization purposes?$EXPL$, $EXPL$["10% of the initial fair value", "Estimated fair value at the end of the useful life", "Present value of remaining expected cash flows", "Zero, because neither a purchase commitment nor active market exists"]$EXPL$::jsonb, 3, $EXPL$Correct (D): ASC 350-30-35-8 requires the residual value of a finite-lived intangible asset to be assumed to be zero unless a third party has committed to purchase the asset or an active exchange market exists for the asset. Neither condition is met here. Wrong (A): A 10% residual value is a common convention for tangible assets in some contexts but is not the default for intangible assets under ASC 350. Wrong (B): Estimating future fair market value is not permitted as a basis when neither criterion is met. Wrong (C): Present value of remaining cash flows is used in ASC 360 impairment measurement, not in determining amortization residual value.$EXPL$, 'easy', 2),

-- Q9: hard / L4 — Below-market contract acquired as intangible
(4, 'Intangible Assets Advanced', $EXPL$In a business combination, Summit Corp. acquires a supply contract with a vendor that requires payments 20% below current market rates. The contract has 5 years remaining and generates estimated savings of $200,000 per year compared to market rates. Summit determines the fair value of this favorable contract at $850,000 using a present value technique. Two years later, the vendor terminates the contract early. What should Summit recognize at termination?$EXPL$, $EXPL$["A loss equal to the remaining carrying amount of the intangible asset", "No gain or loss because the contract was below market", "A gain equal to the remaining carrying amount", "A loss only if the carrying amount exceeds the fair value of any replacement contract"]$EXPL$::jsonb, 0, $EXPL$Correct (A): Under ASC 805-20-25-10 and ASC 350-30-40-1, a favorable below-market contract acquired in a business combination is recognized as an identifiable intangible asset. When the contract is terminated early, the remaining unamortized carrying amount is written off as a loss because the asset no longer provides future economic benefit. Wrong (B): The favorable contract was a recognized asset with a carrying amount that must be derecognized at termination. Wrong (C): A gain would not arise from losing a favorable contract; the entity loses the expected future savings. Wrong (D): The full carrying amount is written off as a loss upon termination regardless of replacement contracts.$EXPL$, 'hard', 4),

-- Q10: hard / L3 — Foreign currency translation of intangible assets
(4, 'Intangible Assets Advanced', $EXPL$Global Inc. has a foreign subsidiary with a functional currency that is not the U.S. dollar. The subsidiary carries goodwill of 8,000,000 foreign currency units from a prior business combination. At the beginning of the year, the exchange rate was $0.80 per foreign unit. At year-end, the rate is $0.72 per foreign unit. Under ASC 830-10-45-17, how does the change in exchange rate affect the translated goodwill reported in Global's consolidated financial statements?$EXPL$, $EXPL$["An impairment loss of $640,000 is recognized in net income", "A cumulative translation adjustment of $640,000 is recognized in other comprehensive income", "No adjustment because goodwill is a nonmonetary asset translated at the historical rate", "A foreign currency transaction gain of $640,000 is recognized in net income"]$EXPL$::jsonb, 1, $EXPL$Correct (B): ASC 830-10-45-17 requires that goodwill arising from a foreign entity acquisition be translated at the current exchange rate. The change in translated amount flows through the cumulative translation adjustment in other comprehensive income: (8,000,000 x $0.80) - (8,000,000 x $0.72) = $6,400,000 - $5,760,000 = $640,000 decrease in OCI. Wrong (A): Translation adjustments for goodwill do not create impairment losses in net income; they are recorded in OCI. Wrong (C): Unlike the temporal method for nonmonetary assets, goodwill of a foreign entity is translated at the current rate under ASC 830. Wrong (D): Translation adjustments are not transaction gains and are not recorded in net income.$EXPL$, 'hard', 3),

-- Q11: medium / L2 — Renewal and extension costs for intangible assets
(4, 'Intangible Assets Advanced', $EXPL$Ridgeway Corp. holds a patent acquired in a business combination with a remaining legal life of 12 years and a carrying amount of $960,000. Ridgeway spends $150,000 in legal fees to successfully renew the patent for an additional 10 years. Under ASC 350-30-25-6, how should Ridgeway account for the $150,000 renewal costs?$EXPL$, $EXPL$["Expense the $150,000 immediately because the patent is an existing intangible", "Recognize the $150,000 as a separate intangible asset", "Capitalize the $150,000 and add it to the carrying amount of the patent", "Recognize the $150,000 as a reduction of accumulated amortization"]$EXPL$::jsonb, 2, $EXPL$Correct (C): ASC 350-30-25-6 states that costs incurred to renew or extend the term of a recognized intangible asset are capitalized and added to the carrying amount of the intangible. The revised carrying amount is then amortized over the revised remaining useful life. Wrong (A): Renewal costs are not expensed when they successfully extend the asset's useful life. Wrong (B): The costs relate to the existing patent, not a new separate asset. Wrong (D): The costs are added to the asset's carrying amount, not netted against accumulated amortization.$EXPL$, 'medium', 2),

-- Q12: easy / L1 — Internally generated goodwill
(4, 'Intangible Assets Advanced', $EXPL$Under U.S. GAAP, what is the proper accounting treatment for internally generated goodwill?$EXPL$, $EXPL$["Capitalize and test for impairment annually", "Capitalize and amortize over 10 years", "Capitalize and amortize over the estimated useful life", "It is never recognized as an asset"]$EXPL$::jsonb, 3, $EXPL$Correct (D): ASC 350-20-25-2 prohibits the recognition of internally generated goodwill as an asset. Only goodwill acquired in a business combination under ASC 805 is recognized on the balance sheet. Wrong (A): Annual impairment testing applies only to acquired goodwill, not internally generated goodwill. Wrong (B): Amortization over 10 years is the private company alternative for acquired goodwill, not internally generated goodwill. Wrong (C): Internally generated goodwill cannot be capitalized under any useful life assumption.$EXPL$, 'easy', 1),

-- Q13: medium / L3 — Website development costs (ASC 350-50)
(4, 'Intangible Assets Advanced', $EXPL$Netwave Corp. spends $80,000 planning a new customer-facing website and $350,000 developing the website's application and infrastructure. After launch, Netwave spends $40,000 on content updates and $60,000 adding new functionality. Under ASC 350-50, what total amount should Netwave capitalize?$EXPL$, $EXPL$["$410,000", "$430,000", "$350,000", "$470,000"]$EXPL$::jsonb, 0, $EXPL$Correct (A): ASC 350-50-25 requires that planning-stage costs ($80,000) be expensed. Application and infrastructure development costs ($350,000) are capitalized. Post-launch content costs ($40,000) are expensed. Costs to add new functionality ($60,000) are capitalized. Total capitalized: $350,000 + $60,000 = $410,000. Wrong (B): This incorrectly includes the planning-stage costs. Wrong (C): This omits the $60,000 for new functionality, which is capitalizable under ASC 350-50. Wrong (D): This includes both planning costs and content update costs, which must be expensed.$EXPL$, 'medium', 3),

-- Q14: medium / L3 — Amortization pattern of economic benefit
(4, 'Intangible Assets Advanced', $EXPL$Quarry Inc. acquires a customer relationship intangible for $1,200,000 in a business combination. Management determines that the expected pattern of economic benefit declines significantly over the 10-year estimated useful life, with 60% of benefits expected in the first 4 years. Under ASC 350-30-35-6, what amortization method should Quarry use?$EXPL$, $EXPL$["Straight-line over 10 years, regardless of the benefit pattern", "An accelerated method reflecting the pattern in which economic benefits are consumed", "Units-of-production based on customer revenue", "Amortize over 4 years since 60% of benefits occur in that period"]$EXPL$::jsonb, 1, $EXPL$Correct (B): ASC 350-30-35-6 requires that a finite-lived intangible asset be amortized over its useful life in a manner that reflects the pattern in which the economic benefits are consumed. When that pattern is reliably determinable and shows declining benefit, an accelerated method is appropriate. Wrong (A): Straight-line is the default only when the pattern of benefit cannot be reliably determined; here it can be. Wrong (C): Units-of-production is used when output-based measurement is most representative, not merely because revenue is involved. Wrong (D): The useful life is 10 years; amortizing over only 4 years would understate the asset's life.$EXPL$, 'medium', 3),

-- Q15: easy / L1 — Research and development costs
(4, 'Intangible Assets Advanced', $EXPL$Under ASC 730, how are research and development costs generally treated in a company's financial statements?$EXPL$, $EXPL$["Capitalized as an intangible asset", "Capitalized and amortized once the project is completed", "Expensed as incurred", "Deferred until technological feasibility is established"]$EXPL$::jsonb, 2, $EXPL$Correct (C): ASC 730-10-25-1 requires that research and development costs be expensed as incurred. This applies to both the research phase and the development phase for most internally developed projects. Wrong (A): R&D costs are not capitalized as intangible assets under GAAP, except for R&D acquired in a business combination. Wrong (B): Unlike IFRS, U.S. GAAP does not permit capitalization of development costs upon meeting certain criteria (except for software under ASC 985 or ASC 350-40). Wrong (D): Technological feasibility is a capitalization trigger for software development costs under ASC 985-20, not for general R&D.$EXPL$, 'easy', 1),

-- Q16: medium / L2 — Goodwill in a disposal group
(4, 'Intangible Assets Advanced', $EXPL$Titan Corp. classifies a business within one of its reporting units as held for sale. The reporting unit has total goodwill of $9,000,000. The business being sold has a fair value of $3,000,000, while the entire reporting unit has a fair value of $18,000,000. Under ASC 350-20-40-3, how much goodwill should Titan include in the disposal group?$EXPL$, $EXPL$["All $9,000,000 of the reporting unit goodwill", "The full $3,000,000 fair value of the business sold", "No goodwill, because it remains with the continuing unit", "$1,500,000 based on the relative fair value allocation"]$EXPL$::jsonb, 3, $EXPL$Correct (D): ASC 350-20-40-3 requires goodwill to be included in the disposal group based on relative fair values when a business within a reporting unit is being disposed. Allocated goodwill = $9,000,000 x ($3,000,000 / $18,000,000) = $1,500,000. Wrong (A): All of the reporting unit's goodwill cannot be assigned to just a portion being sold. Wrong (B): This is the fair value of the disposed business, not the allocated goodwill amount. Wrong (C): Goodwill must be allocated to the disposal group when a business is being disposed of.$EXPL$, 'medium', 2),

-- Q17: medium / L3 — Measurement period adjustments
(4, 'Intangible Assets Advanced', $EXPL$Vertex Corp. completed a business combination on January 1, Year 1 and provisionally recognized a customer relationship intangible at $2,000,000. On September 1, Year 1, Vertex obtains new information indicating the fair value at the acquisition date was actually $2,500,000. Under ASC 805-10-25-17, how should Vertex account for this adjustment?$EXPL$, $EXPL$["Retrospectively adjust the acquisition-date amounts and revise any related amortization as if the revised value had been recognized from the start", "Recognize the $500,000 increase as a gain in Year 1 income", "Adjust the intangible asset prospectively from September 1, Year 1", "Recognize the $500,000 as an adjustment to goodwill only"]$EXPL$::jsonb, 0, $EXPL$Correct (A): ASC 805-10-25-17 requires measurement period adjustments to be recognized retrospectively as if the accounting had been completed at the acquisition date. This includes adjusting the asset to $2,500,000 and revising depreciation/amortization that would have been recorded. Wrong (B): Measurement period adjustments are not recognized as gains; they are retrospective corrections to provisional amounts. Wrong (C): Prospective treatment applies after the measurement period ends (maximum 1 year), not during it. Wrong (D): The adjustment increases the intangible asset value, with a corresponding decrease to goodwill, plus catch-up amortization.$EXPL$, 'medium', 3),

-- Q18: easy / L1 — Order/production backlog classification
(4, 'Intangible Assets Advanced', $EXPL$Under ASC 805, into which category of identifiable intangible assets does an order or production backlog fall?$EXPL$, $EXPL$["Technology-based", "Contract-based", "Customer-related", "Marketing-related"]$EXPL$::jsonb, 1, $EXPL$Correct (B): ASC 805-20-55-15 classifies order or production backlogs as contract-based intangible assets because they arise from contractual arrangements with customers. They are recognized separately in a business combination if they meet the identifiability criteria. Wrong (A): Technology-based intangibles include patents, trade secrets, and software — not customer order backlogs. Wrong (C): Customer-related intangibles include customer lists and non-contractual customer relationships, but backlogs arise from specific contracts. Wrong (D): Marketing-related intangibles include trademarks, trade names, and internet domains.$EXPL$, 'easy', 1),

-- Q19: medium / L3 — Customer relationship attrition pattern amortization
(4, 'Intangible Assets Advanced', $EXPL$Keystone Corp. acquires a customer relationship intangible valued at $900,000 with an estimated useful life of 6 years. Historical data shows that 25% of the customer base attrites each year. Management determines that the pattern of economic benefit mirrors the declining customer base. Under ASC 350-30-35-6, what is the approximate amortization expense in Year 1?$EXPL$, $EXPL$["$150,000", "$225,000", "$270,000", "$360,000"]$EXPL$::jsonb, 2, $EXPL$Correct (C): ASC 350-30-35-6 requires amortization to reflect the pattern of economic benefit consumption. With a 25% annual attrition rate, the relative benefit in Year 1 is proportional to the full customer base. Using a declining-balance approach: Year 1 benefit ratio is approximately 100/333 of total benefits (sum of 100+75+56.25+42.19+31.64+23.73 = ~328.8), yielding approximately $900,000 x (100/328.8) = ~$273,700, closest to $270,000. Wrong (A): This is the straight-line amount ($900,000 / 6), which ignores the accelerated attrition pattern. Wrong (B): This understates the Year 1 expense relative to the attrition pattern. Wrong (D): This overstates the Year 1 expense and would exhaust the asset too quickly.$EXPL$, 'medium', 3),

-- Q20: medium / L3 — Favorable lease terms acquired as intangible
(4, 'Intangible Assets Advanced', $EXPL$In a business combination, Drake Corp. acquires a building lease with 8 years remaining. The lease requires annual payments of $200,000, while the current market rate for a comparable lease is $280,000 per year. Drake determines the fair value of this favorable lease intangible at $430,000. Under ASC 805, how should Drake account for this favorable lease?$EXPL$, $EXPL$["Adjust the right-of-use asset for the favorable terms and do not recognize a separate intangible", "Recognize a lease liability adjustment for the below-market terms", "Include the favorable lease value in goodwill", "Recognize it as a separate finite-lived intangible asset amortized over the 8-year remaining lease term"]$EXPL$::jsonb, 3, $EXPL$Correct (D): Under ASC 805-20-25-10, favorable lease terms acquired in a business combination that meet the contractual-legal identifiability criterion are recognized as a separate intangible asset. The asset is amortized over the remaining lease term of 8 years. Wrong (A): While ASC 842 may affect lease classification, favorable lease terms identified in a business combination under ASC 805 are recognized as separate intangible assets. Wrong (B): A lease liability adjustment does not capture the favorable terms as an identifiable intangible. Wrong (C): Since the favorable lease meets the contractual-legal criterion, it must be recognized separately from goodwill.$EXPL$, 'medium', 3),

-- Q21: easy / L2 — Domain names as marketing-related intangibles
(4, 'Intangible Assets Advanced', $EXPL$Vista Corp. acquires a company in a business combination and identifies an internet domain name valued at $120,000. Under ASC 805-20-55-12, how should Vista classify this domain name?$EXPL$, $EXPL$["As a marketing-related intangible asset", "As a technology-based intangible asset", "As a customer-related intangible asset", "As part of goodwill because domain names lack separability"]$EXPL$::jsonb, 0, $EXPL$Correct (A): ASC 805-20-55-12 classifies internet domain names as marketing-related intangible assets alongside trademarks and trade names. They are recognized separately in a business combination when identifiability criteria are met. Wrong (B): Technology-based intangibles include patents, software, and databases — not domain names. Wrong (C): Customer-related intangibles include customer lists and relationships, not domain names. Wrong (D): Domain names are separable and meet the identifiability criterion, so they are recognized separately from goodwill.$EXPL$, 'easy', 2),

-- Q22: medium / L3 — Crypto assets as intangible assets (impairment-only model)
(4, 'Intangible Assets Advanced', $EXPL$Prior to the adoption of ASU 2023-08, Ledger Corp. holds 50 Bitcoin purchased at $30,000 each (total cost $1,500,000). During the reporting period, Bitcoin's price drops to $22,000 and then recovers to $35,000 by period end. Under the pre-ASU 2023-08 intangible asset model, what amount does Ledger report on the balance sheet?$EXPL$, $EXPL$["$1,750,000, reflecting the period-end fair value", "$1,100,000, reflecting the impairment to the intra-period low", "$1,500,000, at historical cost because the period-end price exceeds cost", "The lower of cost or period-end fair value, which is $1,500,000"]$EXPL$::jsonb, 1, $EXPL$Correct (B): Prior to ASU 2023-08, crypto assets were classified as indefinite-lived intangible assets under ASC 350. The impairment-only model requires write-down to fair value when impaired, and impairment cannot be reversed. The intra-period low of $22,000 per unit triggers impairment: 50 x $22,000 = $1,100,000. The subsequent recovery does not allow reversal. Wrong (A): Fair value measurement at period end was not permitted under the pre-ASU intangible asset model. Wrong (C): The intra-period decline constitutes an impairment event that must be recognized regardless of subsequent recovery. Wrong (D): The lower of cost or period-end fair value is not the correct test; impairment is measured at the lowest fair value during the period.$EXPL$, 'medium', 3),

-- Q23: easy / L1 — Goodwill is not amortized for public companies
(4, 'Intangible Assets Advanced', $EXPL$Under U.S. GAAP, how do public business entities account for goodwill after its initial recognition in a business combination?$EXPL$, $EXPL$["Amortize it over 15 years on a straight-line basis", "Amortize it over the estimated useful life of the acquired business", "Test it for impairment annually but do not amortize it", "Expense it immediately in the period of acquisition"]$EXPL$::jsonb, 2, $EXPL$Correct (C): ASC 350-20-35-1 requires that goodwill not be amortized by public business entities. Instead, it is tested for impairment at least annually at the reporting unit level, or more frequently if triggering events occur. Wrong (A): The 15-year amortization applies to Section 197 intangibles for tax purposes, not to goodwill under GAAP for public entities. Wrong (B): Goodwill does not have an estimated useful life for public entities; amortization is available only under the private company alternative. Wrong (D): Goodwill is a recognized asset on the balance sheet, not expensed at acquisition.$EXPL$, 'easy', 1),

-- Q24: medium / L2 — Asset group impairment for finite-lived intangibles
(4, 'Intangible Assets Advanced', $EXPL$Crest Corp. has a finite-lived customer list intangible with a carrying amount of $400,000 that is part of an asset group. The entire asset group has a carrying amount of $2,000,000 and generates expected undiscounted future cash flows of $2,200,000. The fair value of the asset group is $1,600,000. Under ASC 360-10-35-17, what impairment loss should Crest recognize on the customer list?$EXPL$, $EXPL$["$400,000 — the full carrying amount of the customer list", "$80,000 — proportional to the customer list within the group", "$160,000 — the difference between carrying amount and fair value", "$0 — the asset group passes the recoverability test"]$EXPL$::jsonb, 3, $EXPL$Correct (D): Under ASC 360-10-35-17, the recoverability test compares undiscounted future cash flows ($2,200,000) to the carrying amount ($2,000,000). Because undiscounted cash flows exceed the carrying amount, the asset group passes the recoverability test and no impairment is recognized. The fair value of $1,600,000 is irrelevant because Step 2 is never reached. Wrong (A): Writing off the entire customer list ignores the recoverability test result. Wrong (B): This assumes an impairment loss is measured, but the asset passes the recoverability screen. Wrong (C): No impairment is recognized because the undiscounted cash flow test is passed.$EXPL$, 'medium', 2),

-- Q25: easy / L2 — Goodwill impairment reversal prohibition
(4, 'Intangible Assets Advanced', $EXPL$Elm Corp. recognized a $500,000 goodwill impairment loss last year. This year, economic conditions have improved significantly and the reporting unit's fair value now exceeds its carrying amount by $800,000. Under ASC 350, what adjustment should Elm make to goodwill?$EXPL$, $EXPL$["No adjustment — goodwill impairment losses are never reversed under GAAP", "Reverse the $500,000 impairment and restore goodwill to its original carrying amount", "Recognize a $500,000 gain in other comprehensive income", "Reverse the impairment up to the amount of the fair value excess"]$EXPL$::jsonb, 0, $EXPL$Correct (A): ASC 350-20-35-9 explicitly prohibits the reversal of previously recognized goodwill impairment losses. Once goodwill is written down, it cannot be written back up regardless of subsequent improvements in fair value. Wrong (B): GAAP does not permit reversal of goodwill impairment under any circumstances. Wrong (C): Goodwill recoveries are not recognized in either net income or other comprehensive income. Wrong (D): There is no partial or full reversal mechanism for goodwill impairment under GAAP.$EXPL$, 'easy', 2),

-- Q26: medium / L2 — Tax-deductible goodwill and deferred taxes
(4, 'Intangible Assets Advanced', $EXPL$Maple Corp. acquires a business and recognizes $5,000,000 of goodwill for financial reporting purposes. The goodwill is also deductible for tax purposes under Section 197 over 15 years. In Year 1, tax amortization is $333,333 while book goodwill is not amortized. Assuming a 25% tax rate, what deferred tax consequence arises from the Year 1 temporary difference?$EXPL$, $EXPL$["A deferred tax asset of $83,333", "A deferred tax liability of $83,333", "No deferred tax consequence because of the initial recognition exception", "A deferred tax asset of $333,333"]$EXPL$::jsonb, 1, $EXPL$Correct (B): When goodwill is deductible for tax purposes but not amortized for book purposes, the tax basis decreases below the book basis, creating a taxable temporary difference. This results in a deferred tax liability of $333,333 x 25% = $83,333 in Year 1. The initial recognition exception under ASC 740-10-25-15(d) does not apply to goodwill recognized in a business combination where book and tax goodwill exist simultaneously. Wrong (A): The temporary difference creates a DTL, not a DTA, because the tax basis is lower than the book basis. Wrong (C): The initial recognition exception does not apply when goodwill arises in a taxable business combination with simultaneous book and tax goodwill. Wrong (D): This is the full tax amortization amount, not the deferred tax effect.$EXPL$, 'medium', 2),

-- Q27: hard / L4 — Contingent consideration adjustment post-measurement period
(4, 'Intangible Assets Advanced', $EXPL$Prism Corp. completed a business combination 18 months ago, recognizing a contingent consideration liability of $1,000,000 at the acquisition date. The measurement period has closed. The contingent consideration, classified as a liability, is now remeasured at $1,400,000 due to improved earnings of the acquired business. Under ASC 805-30-35-1, how should Prism account for the $400,000 increase?$EXPL$, $EXPL$["Increase goodwill by $400,000", "Record a measurement period adjustment retroactively", "Recognize a $400,000 loss in earnings in the current period", "Adjust retained earnings directly as a prior period correction"]$EXPL$::jsonb, 2, $EXPL$Correct (C): ASC 805-30-35-1 requires that changes in fair value of contingent consideration classified as a liability that occur after the measurement period be recognized in earnings. Since the measurement period has closed, the $400,000 increase is recorded as a loss in the current period. Wrong (A): Goodwill adjustments for contingent consideration are only permitted during the measurement period (maximum 1 year from acquisition). Wrong (B): Measurement period adjustments are no longer available because the measurement period has closed. Wrong (D): Post-measurement period changes are recognized in current earnings, not as prior period adjustments.$EXPL$, 'hard', 4),

-- Q28: hard / L4 — Reporting unit reorganization with simultaneous impairment
(4, 'Intangible Assets Advanced', $EXPL$Atlas Corp. reorganizes its operations, splitting Reporting Unit X (carrying amount $20,000,000 including $7,000,000 goodwill, fair value $18,000,000) into two new units: Unit P (fair value $12,000,000) and Unit Q (fair value $6,000,000). Before the reorganization, Atlas must test Unit X for impairment. After the reorganization, goodwill is reallocated. What is the goodwill allocated to Unit P after both the impairment test and reallocation?$EXPL$, $EXPL$["$2,500,000", "$4,666,667", "$3,500,000", "$3,333,333"]$EXPL$::jsonb, 3, $EXPL$Correct (D): First, test Unit X for impairment: carrying amount $20,000,000 exceeds fair value $18,000,000 by $2,000,000. Goodwill impairment = $2,000,000 (capped at goodwill of $7,000,000). Remaining goodwill = $5,000,000. Then reallocate using relative fair values: Unit P = $5,000,000 x ($12,000,000 / $18,000,000) = $3,333,333. Wrong (A): This would result from an equal split ($5,000,000 / 2) rather than using relative fair values. Wrong (B): This allocates the pre-impairment goodwill of $7,000,000 using relative fair values without first testing for impairment. Wrong (C): This uses an equal split rather than relative fair values for reallocation.$EXPL$, 'hard', 4),

-- Q29: medium / L3 — Intangible asset disposal gain or loss
(4, 'Intangible Assets Advanced', $EXPL$Forge Corp. sells a technology patent with an original cost of $2,400,000 and accumulated amortization of $1,600,000 for cash proceeds of $1,100,000. Under ASC 350-30-40-1, what gain or loss should Forge recognize on the disposal?$EXPL$, $EXPL$["A gain of $300,000 on the disposal", "A loss of $1,300,000 on the disposal", "A gain of $1,100,000 equal to the full proceeds", "No gain or loss because proceeds exceed book value"]$EXPL$::jsonb, 0, $EXPL$Correct (A): Under ASC 350-30-40-1, the gain or loss on disposal equals proceeds minus carrying amount. Carrying amount = $2,400,000 - $1,600,000 = $800,000. Gain = $1,100,000 - $800,000 = $300,000. Wrong (B): This incorrectly compares proceeds to original cost instead of net carrying amount. Wrong (C): This treats the full proceeds as a gain without subtracting the carrying amount. Wrong (D): While the statement that proceeds exceed net book value is correct, a gain of $300,000 must be recognized — not zero.$EXPL$, 'medium', 3),

-- Q30: easy / L1 — Goodwill recognized only in business combinations
(4, 'Intangible Assets Advanced', $EXPL$Under ASC 805, in what type of transaction is goodwill initially recognized on the acquirer's balance sheet?$EXPL$, $EXPL$["An asset purchase of individual assets at fair value", "A business combination where consideration exceeds net identifiable assets acquired", "An exchange of equity securities between unrelated parties", "A contribution of net assets to a joint venture"]$EXPL$::jsonb, 1, $EXPL$Correct (B): ASC 805-30-30-1 defines goodwill as the excess of consideration transferred over the net identifiable assets acquired in a business combination. Goodwill is recognized only in a business combination accounted for under the acquisition method. Wrong (A): An asset purchase of individual assets does not give rise to goodwill; any premium is allocated to the acquired assets. Wrong (C): An exchange of equity securities is not itself a business combination that generates goodwill. Wrong (D): A contribution to a joint venture is accounted for under ASC 845 or ASC 323, not the acquisition method that produces goodwill.$EXPL$, 'easy', 1)
;

COMMIT;
