-- Migration: Question generation — BAR batch 27 (21 questions)
-- Date: 2026-03-25
-- Topic: Financial Valuation Methods
-- Difficulty: 6E / 11M / 4H
-- Bloom's: L1:4 / L2:8 / L3:6 / L4:3

BEGIN;

INSERT INTO questions (section_id, topic, stem, choices, correct_index, explanation, difficulty, cognitive_level)
VALUES

-- Q1: medium / L3 — M&M Proposition I with taxes: calculating interest tax shield value
(4, 'Financial Valuation Methods', $EXPL$Mercer Industries is currently an all-equity firm with a total value of $80 million. The CEO proposes a recapitalization that would replace $30 million of equity with permanent debt at a 6% coupon rate. The corporate tax rate is 25%. Under Modigliani-Miller Proposition I with corporate taxes, the value of the levered firm after recapitalization is closest to:$EXPL$, $EXPL$["$87.5 million", "$80.0 million", "$110.0 million", "$72.5 million"]$EXPL$::jsonb, 0, $EXPL$Correct (A): Under M&M Proposition I with taxes, V(levered) = V(unlevered) + Tax rate × Debt = $80M + 0.25 × $30M = $87.5M. The tax shield adds $7.5 million to firm value because interest expense is tax-deductible. Wrong (B): Ignores the present value of the interest tax shield, which is the entire basis of M&M with taxes. Wrong (C): Incorrectly adds the full $30M debt amount rather than only the tax shield (25% of debt). Wrong (D): Subtracts the tax shield instead of adding it, reversing the value-creating effect of debt.$EXPL$, 'medium', 3),

-- Q2: easy / L2 — Cost of preferred stock calculation
(4, 'Financial Valuation Methods', $EXPL$Halcyon Corp. issues preferred stock that pays an annual dividend of $6.00 per share. The net issuance price after flotation costs is $75 per share. What is Halcyon's cost of preferred stock?$EXPL$, $EXPL$["6.0%", "8.0%", "10.0%", "12.0%"]$EXPL$::jsonb, 1, $EXPL$Correct (B): Cost of preferred stock = Annual dividend / Net issuance price = $6.00 / $75.00 = 8.0%. Preferred dividends are not tax-deductible, so no tax adjustment applies. Wrong (A): Uses an incorrect denominator such as a $100 par value rather than the $75 net issuance price. Wrong (C): Overstates the cost, possibly by using a lower denominator or adding a tax adjustment that does not apply to preferred stock. Wrong (D): Further overstates the cost by applying an erroneous calculation or confusing preferred cost with an equity cost estimate.$EXPL$, 'easy', 2),

-- Q3: medium / L2 — M&M Proposition II: cost of equity rises with leverage
(4, 'Financial Valuation Methods', $EXPL$Whitfield Manufacturing has a debt-to-equity ratio of 0.5 and a cost of equity of 13%. The company then increases its leverage to a debt-to-equity ratio of 1.0 while holding the cost of debt constant. Under Modigliani-Miller Proposition II, the cost of equity would most likely:$EXPL$, $EXPL$["Decrease because the interest tax shield reduces the overall cost of capital", "Remain unchanged because WACC is independent of capital structure", "Increase because equity holders bear greater financial risk from higher leverage", "Increase only if the company's operating risk also increases simultaneously"]$EXPL$::jsonb, 2, $EXPL$Correct (C): Under M&M Proposition II, the cost of equity increases linearly with the debt-to-equity ratio. As leverage rises, equity holders face greater financial risk because debt claims are senior, making residual equity cash flows more volatile. Wrong (A): The tax shield lowers WACC but does not reduce the cost of equity; it actually rises. Wrong (B): WACC may be independent of structure in a no-tax world, but cost of equity still changes with leverage. Wrong (D): Operating risk is separate; financial risk alone drives the equity cost increase under M&M II.$EXPL$, 'medium', 2),

-- Q4: hard / L3 — Trade-off theory: optimal capital structure
(4, 'Financial Valuation Methods', $EXPL$Ridgecrest Holdings currently has no debt and a WACC of 12%. The CFO evaluates three recapitalization scenarios: Scenario A (20% debt, WACC 10.8%, negligible distress costs), Scenario B (50% debt, WACC 9.5%, moderate distress costs of $2 million annually), and Scenario C (80% debt, WACC 11.2%, severe distress costs of $8 million annually). Under the trade-off theory of capital structure, the optimal scenario is:$EXPL$, $EXPL$["No debt, because preserving an all-equity structure maximizes financial flexibility", "Scenario A, because the lowest debt level minimizes the probability of financial distress", "Scenario C, because maximum leverage produces the largest interest tax shield", "Scenario B, because it achieves the lowest WACC where the marginal tax benefit still exceeds marginal distress costs"]$EXPL$::jsonb, 3, $EXPL$Correct (D): The trade-off theory holds that the optimal capital structure minimizes WACC by balancing the tax benefit of debt against the costs of financial distress. Scenario B has the lowest WACC at 9.5%, indicating that the marginal tax shield still exceeds marginal distress costs at 50% debt. Wrong (A): Ignoring debt entirely foregoes the value-creating interest tax shield, producing a higher WACC. Wrong (B): Scenario A has a higher WACC than B, meaning additional debt would still add more tax benefit than distress cost. Wrong (C): Scenario C's 11.2% WACC shows distress costs have overwhelmed the tax benefit.$EXPL$, 'hard', 3),

-- Q5: medium / L2 — Pecking order theory: why profitable firms use less debt
(4, 'Financial Valuation Methods', $EXPL$Crestview Technologies is highly profitable with significant retained earnings, yet its balance sheet shows minimal long-term debt. An analyst notes this pattern is common among profitable companies. Under the pecking order theory, this is best explained by:$EXPL$, $EXPL$["Profitable firms prefer internal financing because it avoids issuance costs and information asymmetry problems", "Profitable firms avoid debt because Modigliani-Miller demonstrates capital structure is irrelevant to firm value", "Profitable firms maintain low debt to signal to the market that their equity is undervalued", "Profitable firms hold minimal debt because high earnings eliminate the benefit of the interest tax shield"]$EXPL$::jsonb, 0, $EXPL$Correct (A): The pecking order theory states firms prefer internal funds first, then debt, then equity as a last resort. Profitable firms generate enough retained earnings to fund investments internally, avoiding flotation costs and the adverse selection problem of external financing. Wrong (B): M&M irrelevance applies only in perfect markets; the pecking order theory addresses imperfections like information asymmetry. Wrong (C): Signaling theory is a separate concept; pecking order focuses on financing hierarchy, not market signals. Wrong (D): High earnings do not eliminate the tax shield benefit; profitable firms simply do not need external financing.$EXPL$, 'medium', 2),

-- Q6: easy / L1 — Duration definition
(4, 'Financial Valuation Methods', $EXPL$What does duration measure in the context of bond valuation?$EXPL$, $EXPL$["The time remaining until the bond's maturity date", "The sensitivity of a bond's price to changes in interest rates", "The credit risk premium embedded in the bond's yield spread", "The probability that the bond issuer will default before maturity"]$EXPL$::jsonb, 1, $EXPL$Correct (B): Duration measures the approximate percentage change in a bond's price for a 1% change in interest rates. It represents the weighted average time to receive all cash flows and serves as the primary measure of interest rate sensitivity. Wrong (A): Describes time to maturity, which is a single input to duration but not what duration itself measures. Wrong (C): Describes a credit spread or default risk metric, not interest rate sensitivity. Wrong (D): Describes credit risk or default probability, which is measured by credit ratings and default models, not duration.$EXPL$, 'easy', 1),

-- Q7: medium / L3 — Degree of financial leverage (DFL) calculation and EPS impact
(4, 'Financial Valuation Methods', $EXPL$Covington Industries reports EBIT of $600,000 and annual interest expense of $200,000. Management forecasts that EBIT will increase by 15% next year due to higher sales volume. Applying the degree of financial leverage, the expected percentage change in earnings per share is closest to:$EXPL$, $EXPL$["10.0%", "15.0%", "22.5%", "30.0%"]$EXPL$::jsonb, 2, $EXPL$Correct (C): DFL = EBIT / (EBIT − Interest) = $600,000 / ($600,000 − $200,000) = 1.5. Expected EPS change = DFL × EBIT change = 1.5 × 15% = 22.5%. Financial leverage amplifies the effect of operating income changes on EPS. Wrong (A): Understates the leverage effect, possibly dividing rather than multiplying. Wrong (B): Uses only the EBIT percentage change without applying the DFL multiplier. Wrong (D): Applies a DFL of 2.0 (as if interest were $300,000), overstating the leverage effect.$EXPL$, 'medium', 3),

-- Q8: medium / L2 — Degree of total leverage (DTL) interpretation
(4, 'Financial Valuation Methods', $EXPL$Westgate Corp. has a degree of operating leverage (DOL) of 2.5 and a degree of financial leverage (DFL) of 1.6, producing a degree of total leverage (DTL) of 4.0. If the company's sales increase by 8%, the expected percentage change in earnings per share is closest to:$EXPL$, $EXPL$["8%", "12.8%", "20%", "32%"]$EXPL$::jsonb, 3, $EXPL$Correct (D): DTL = DOL × DFL = 2.5 × 1.6 = 4.0. The percentage change in EPS = DTL × percentage change in sales = 4.0 × 8% = 32%. DTL captures the combined amplification effect of both operating and financial leverage on EPS. Wrong (A): Uses the raw sales change without applying any leverage multiplier. Wrong (B): Applies only the DFL (1.6 × 8% = 12.8%), ignoring operating leverage. Wrong (C): Applies only the DOL (2.5 × 8% = 20%), ignoring financial leverage.$EXPL$, 'medium', 2),

-- Q9: medium / L3 — Degree of operating leverage (DOL) from cost structure change
(4, 'Financial Valuation Methods', $EXPL$Bramwell Manufacturing has sales of $1,200,000, variable costs of $720,000, and fixed operating costs of $300,000. Management considers investing in automation that would increase fixed costs to $500,000 while reducing variable costs to $480,000. Analyze how this operational change affects the degree of operating leverage.
$EXPL$, $EXPL$["DOL increases from 2.67 to 3.27, amplifying both upside gains and downside losses from sales changes", "DOL decreases because shifting to fixed costs lowers the breakeven point", "DOL remains unchanged because total costs at the current sales level are the same", "DOL increases from 2.67 to 3.27, but operating risk decreases because automation improves efficiency"]$EXPL$::jsonb, 0, $EXPL$Correct (A): Current: CM = $480K, EBIT = $180K, DOL = 2.67. After automation: CM = $720K, EBIT = $220K, DOL = 3.27. Higher fixed costs and lower variable costs increase the contribution margin ratio, raising DOL and amplifying sensitivity to sales changes in both directions. Wrong (B): The breakeven point actually increases with higher fixed costs, and DOL rises, not falls. Wrong (C): Although total costs at current sales differ ($1,020K vs $980K), the key point is that DOL changes due to the cost structure shift. Wrong (D): Higher DOL by definition means greater operating risk; efficiency gains do not offset this leverage effect.$EXPL$, 'medium', 3),

-- Q10: medium / L2 — Market value weights vs book value weights in WACC
(4, 'Financial Valuation Methods', $EXPL$Ashford Industries has a book value of equity of $50 million and a market capitalization of $120 million. The book value of debt is $80 million, which closely approximates its market value. An analyst computing WACC uses the book value weight of equity at 38.5% rather than the market value weight of 60%. This error most likely causes the analyst to:$EXPL$, $EXPL$["Overstate WACC because equity is weighted too heavily", "Understate WACC because the more expensive equity component receives too little weight", "Overstate WACC because the debt tax shield is overstated at the higher debt weight", "Have no material effect because both weighting methods converge over time"]$EXPL$::jsonb, 1, $EXPL$Correct (B): WACC must use market value weights, not book values. Equity typically has a higher cost than after-tax debt. By underweighting equity (38.5% vs the correct 60%), the analyst assigns too much weight to the cheaper debt component, understating the true blended cost of capital. Wrong (A): Using book value underweights equity, which would understate WACC, not overstate it. Wrong (C): The debt tax shield calculation is separate from the weighting error; the net effect is still an understated WACC. Wrong (D): The difference between 38.5% and 60% equity weight is material and produces a meaningfully different WACC.$EXPL$, 'medium', 2),

-- Q11: easy / L1 — Interest rate swap for variable-rate debt hedging
(4, 'Financial Valuation Methods', $EXPL$What hedging instrument converts variable-rate debt payments into fixed-rate payments?$EXPL$, $EXPL$["A currency forward contract to lock in exchange rates", "An interest rate cap that limits the maximum borrowing rate", "An interest rate swap where the company pays fixed and receives floating", "A credit default swap that transfers counterparty default risk"]$EXPL$::jsonb, 2, $EXPL$Correct (C): An interest rate swap where the company pays a fixed rate and receives a floating rate effectively converts variable-rate debt into fixed-rate debt. The floating receipts offset the variable interest payments, leaving only the fixed obligation. Wrong (A): A currency forward hedges foreign exchange risk, not interest rate risk on debt payments. Wrong (B): An interest rate cap limits the maximum rate but does not convert variable to fixed; the borrower still pays variable rates below the cap. Wrong (D): A credit default swap transfers default risk to a counterparty and does not address interest rate fluctuations on debt.$EXPL$, 'easy', 1),

-- Q12: hard / L4 — Forward contract currency hedge outcome analysis
(4, 'Financial Valuation Methods', $EXPL$Briarwood Exports, a U.S. company, expects to receive EUR 2,000,000 in 90 days from a European customer. The current spot rate is $1.12/EUR. Fearing euro depreciation, Briarwood enters a 90-day forward contract at $1.10/EUR. At settlement, the actual spot rate is $1.06/EUR. Evaluate the hedging outcome and determine the net benefit of the forward contract compared to remaining unhedged.$EXPL$, $EXPL$["A cost of $40,000 because the forward rate of $1.10 was below the $1.12 spot rate at inception", "A benefit of $120,000 based on the full difference between the inception spot and settlement spot rates", "No net benefit because the forward discount exactly offsets the favorable hedge settlement", "A benefit of $80,000, representing the difference between the $1.10 forward rate and the $1.06 actual spot rate applied to EUR 2,000,000"]$EXPL$::jsonb, 3, $EXPL$Correct (D): Hedged proceeds = 2,000,000 × $1.10 = $2,200,000. Unhedged proceeds at settlement = 2,000,000 × $1.06 = $2,120,000. Net benefit = $2,200,000 − $2,120,000 = $80,000. The forward locked in a rate $0.04 above the realized spot. Wrong (A): The $40,000 difference between inception spot and forward rate is the forward discount, not the hedge cost; the hedge still provided net benefit. Wrong (B): Incorrectly uses the inception spot rate ($1.12) rather than the forward rate ($1.10) as the hedged rate. Wrong (C): The forward discount and settlement gain are separate; the net benefit is a real $80,000 cash difference.$EXPL$, 'hard', 4),

-- Q13: medium / L3 — Transaction vs translation exposure classification
(4, 'Financial Valuation Methods', $EXPL$Prescott Dynamics, a U.S. manufacturer, signs a contract to sell equipment to a Japanese firm for JPY 500 million payable in 60 days. Separately, Prescott's Japanese subsidiary reports its financial statements in yen, which must be converted to U.S. dollars for consolidated reporting. The equipment sale and the subsidiary's financial statement conversion represent, respectively:$EXPL$, $EXPL$["Transaction exposure and translation exposure", "Economic exposure and transaction exposure", "Translation exposure and economic exposure", "Transaction exposure and economic exposure"]$EXPL$::jsonb, 0, $EXPL$Correct (A): Transaction exposure arises from existing contractual commitments denominated in a foreign currency — the JPY 500 million receivable. Translation exposure arises when converting a foreign subsidiary's financial statements into the parent's reporting currency for consolidation. Wrong (B): Economic exposure relates to long-term competitive effects of exchange rate changes, not a specific contractual receivable. Wrong (C): Reverses the classification; the sale is transactional, and the consolidation is translational. Wrong (D): The subsidiary conversion is translation exposure (financial statement conversion), not economic exposure.$EXPL$, 'medium', 3),

-- Q14: medium / L3 — Modified duration bond price change calculation
(4, 'Financial Valuation Methods', $EXPL$Fenwick Investments holds a corporate bond with a modified duration of 6.2 years. Interest rates increase by 75 basis points following a Federal Reserve policy announcement. The approximate percentage change in the bond's price is closest to:$EXPL$, $EXPL$["A decrease of 4.00%", "A decrease of 4.65%", "An increase of 4.65%", "A decrease of 6.95%"]$EXPL$::jsonb, 1, $EXPL$Correct (B): Approximate price change = −Modified duration × Change in yield = −6.2 × 0.75% = −4.65%. Modified duration provides a linear estimate of the percentage price change for a given yield change. Wrong (A): Understates the decline, likely using a 65-basis-point change or a lower duration estimate. Wrong (C): Gets the magnitude right but reverses the direction; bond prices decrease when interest rates rise. Wrong (D): Overstates the decline, possibly multiplying 6.2 × 0.75 as 4.65 then adding 2.30 for convexity incorrectly, or using 112.5 basis points.$EXPL$, 'medium', 3),

-- Q15: hard / L4 — Currency option asymmetric payoff vs forward contract
(4, 'Financial Valuation Methods', $EXPL$Rowan International, a U.S. importer, owes EUR 5 million to a German supplier in 90 days. The treasurer chooses between a forward contract at $1.08/EUR and a euro call option with a strike of $1.08/EUR and a premium of $0.02/EUR. At settlement, the euro weakens to $1.02/EUR. Evaluate which instrument produces the better economic outcome and identify the key tradeoff.$EXPL$, $EXPL$["The forward contract is better because it costs $5,400,000 with no premium", "Both instruments produce identical costs because the strike equals the forward rate", "The option is better because the company lets it expire, buys euros at $1.02, and saves $200,000 net of the premium versus the forward", "The option is worse because the $100,000 premium exceeds any benefit from the lower spot rate"]$EXPL$::jsonb, 2, $EXPL$Correct (C): Forward cost = 5M × $1.08 = $5,400,000. Option: let call expire, buy at spot = 5M × $1.02 = $5,100,000 + premium 5M × $0.02 = $100,000 = $5,200,000 total. Savings = $200,000. Options provide asymmetric payoff — downside protection with upside participation. Wrong (A): The forward locks in $5.4M regardless; it is $200,000 more expensive than the option outcome here. Wrong (B): The costs differ by $200,000 because the option allows the holder to benefit from favorable rate movements. Wrong (D): The premium is $100,000, but the spot savings is $300,000, yielding a net $200,000 advantage.$EXPL$, 'hard', 4),

-- Q16: easy / L2 — Business cycle trough phase characteristics
(4, 'Financial Valuation Methods', $EXPL$Glendale Analytics is reviewing macroeconomic data showing minimum economic output, high unemployment, and low inflation. These conditions are most consistent with which phase of the business cycle?$EXPL$, $EXPL$["Expansion", "Peak", "Contraction", "Trough"]$EXPL$::jsonb, 3, $EXPL$Correct (D): A trough is the lowest point of the business cycle, characterized by minimum output, high unemployment, and low inflation. It marks the transition from contraction to expansion. Wrong (A): Expansion features rising GDP, falling unemployment, and rising prices — the opposite of minimum output and high unemployment. Wrong (B): A peak features maximum output, full employment, and inflation pressure — not minimum output. Wrong (C): Contraction features falling GDP and rising unemployment but has not yet reached the minimum output level that defines a trough.$EXPL$, 'easy', 2),

-- Q17: hard / L4 — Combined DOL/DFL/DTL analysis with cost structure change
(4, 'Financial Valuation Methods', $EXPL$Stonewell Corp. has sales of $2,000,000, variable costs of $1,200,000, fixed operating costs of $400,000, and interest expense of $150,000. The CEO proposes replacing variable labor with automation, shifting $200,000 from variable to fixed costs. Evaluate how this changes the degree of total leverage and its implications if sales subsequently decline by 10%.$EXPL$, $EXPL$["DTL increases from 3.20 to 4.00, meaning a 10% sales decline would reduce EPS by 40% instead of 32%, significantly increasing shareholder risk", "DTL decreases from 3.20 to 2.50 because lower variable costs reduce the company's breakeven point and overall risk", "DTL remains at 3.20 because the shift between cost categories does not change total costs at current sales volume", "DTL increases from 3.20 to 5.00, making the company unable to service its debt obligations if sales decline by 10%"]$EXPL$::jsonb, 0, $EXPL$Correct (A): Current: CM = $800K, EBIT = $400K, DOL = 2.0, DFL = 400/250 = 1.6, DTL = 3.2. After change: CM = $1,000K, EBIT = $400K, DOL = 2.5, DFL = 1.6, DTL = 4.0. A 10% sales drop causes a 40% EPS decline versus 32% before. Wrong (B): Shifting variable to fixed costs increases operating leverage, raising DOL and DTL, not lowering them. Wrong (C): Although EBIT is unchanged at current sales, DOL changes because the contribution margin and cost structure shift. Wrong (D): DTL is 4.0, not 5.0; the calculation uses DOL of 2.5 times DFL of 1.6.$EXPL$, 'hard', 4),

-- Q18: easy / L1 — Leading economic indicators
(4, 'Financial Valuation Methods', $EXPL$What type of economic indicator do stock market returns and new building permits represent?$EXPL$, $EXPL$["Coincident indicators", "Leading indicators", "Lagging indicators", "Countercyclical indicators"]$EXPL$::jsonb, 1, $EXPL$Correct (B): Stock market returns and building permits are leading indicators because they change before the overall economy changes direction. Markets are forward-looking, and building permits reflect future construction activity. Wrong (A): Coincident indicators such as real GDP and industrial production move in sync with the economy, not ahead of it. Wrong (C): Lagging indicators such as the unemployment rate and CPI change after the economy has already turned. Wrong (D): Countercyclical describes the direction of movement relative to the cycle, not a timing classification of economic indicators.$EXPL$, 'easy', 1),

-- Q19: easy / L1 — Natural hedging definition
(4, 'Financial Valuation Methods', $EXPL$What is natural hedging in foreign currency risk management?$EXPL$, $EXPL$["Denominating all contracts in the home currency regardless of counterparty preference", "Entering forward contracts that match the natural maturity of each exposure", "Matching revenues and expenses in the same foreign currency to reduce net exposure", "Investing exclusively in domestic markets to avoid all currency fluctuations"]$EXPL$::jsonb, 2, $EXPL$Correct (C): Natural hedging involves structuring operations so that revenues and expenses occur in the same currency, reducing net foreign currency exposure without derivative instruments. For example, borrowing in the same currency where revenue is earned. Wrong (A): Requiring home-currency denomination shifts FX risk to the counterparty rather than hedging it; natural hedging manages the exposure operationally. Wrong (B): Forward contracts are financial hedging instruments, not natural hedges; natural hedging avoids derivatives entirely. Wrong (D): Avoiding international operations entirely is not hedging — it is risk avoidance that foregoes global business opportunities.$EXPL$, 'easy', 1),

-- Q20: medium / L2 — FCFE net borrowing adjustment from FCFF
(4, 'Financial Valuation Methods', $EXPL$Alderton Industries reports FCFF of $8,000,000 for the current year. The company paid after-tax interest expense of $1,500,000 and issued $3,000,000 in new long-term debt. The analyst is calculating free cash flow to equity. Alderton's FCFE is closest to:$EXPL$, $EXPL$["$4,500,000", "$6,500,000", "$8,000,000", "$9,500,000"]$EXPL$::jsonb, 3, $EXPL$Correct (D): FCFE = FCFF − Interest(1 − T) + Net borrowing = $8,000,000 − $1,500,000 + $3,000,000 = $9,500,000. FCFE deducts after-tax interest (cash paid to debtholders) and adds net new borrowing (cash received from debtholders). Wrong (A): Subtracts both interest and borrowing, treating new debt as a cash outflow rather than an inflow. Wrong (B): Subtracts interest but ignores net borrowing, understating cash available to equity holders. Wrong (C): Uses FCFF unchanged, ignoring that FCFE must adjust for debt-related cash flows to isolate equity cash flows.$EXPL$, 'medium', 2),

-- Q21: medium / L2 — Lagging indicator classification
(4, 'Financial Valuation Methods', $EXPL$Kellerton Research is tracking macroeconomic data to forecast when the economy will exit a recession. An analyst focuses on the unemployment rate as a primary forecasting tool. In macroeconomic analysis, the unemployment rate is classified as a:$EXPL$, $EXPL$["Lagging indicator, because it typically declines only after economic recovery is already underway", "Leading indicator, because rising unemployment signals an approaching end to the contraction", "Coincident indicator, because unemployment moves in lockstep with real GDP changes", "Countercyclical indicator, because it always moves inversely to the business cycle"]$EXPL$::jsonb, 0, $EXPL$Correct (A): The unemployment rate is a lagging indicator — it rises after a recession has begun and falls after recovery is underway. Employers delay hiring until demand has clearly recovered, making unemployment a poor tool for predicting turning points. Wrong (B): Leading indicators such as stock prices and building permits change before the economy turns; unemployment changes after. Wrong (C): Coincident indicators like real GDP and industrial production move simultaneously with the economy; unemployment lags behind. Wrong (D): Countercyclical describes direction (inverse to GDP), not timing; the unemployment rate is specifically classified as lagging.$EXPL$, 'medium', 2)
;

COMMIT;
