-- Migration: Question generation — FAR batch 97 (30 questions)
-- Date: 2026-03-26
-- Topic: Employee Benefit Plans
-- Difficulty: 9E / 15M / 6H
-- Bloom's: L1:8 / L2:9 / L3:8 / L4:5

BEGIN;

INSERT INTO questions (section_id, topic, stem, choices, correct_index, explanation, difficulty, cognitive_level)
VALUES

-- Q1: medium / L3 — Service cost income statement classification
(2, 'Pension and Postretirement Benefits', $EXPL$Midland Corp. reports net periodic pension cost of $800,000, of which $500,000 is service cost and $300,000 comprises interest cost, expected return on plan assets, and amortization of prior service cost. How should Midland classify these components on its income statement?$EXPL$, $EXPL$["Service cost in operating income; other components in a separate line item outside operating income", "All components combined in a single operating expense line item", "All components reported below the line in other comprehensive income", "Service cost in cost of goods sold; other components in selling expenses"]$EXPL$::jsonb, 0, $EXPL$Correct (A): ASC 715-30-35-4 requires service cost to be presented in the same income statement line items as other compensation costs from the employees' services. All other components of net periodic pension cost must be presented separately from service cost and outside operating income. Wrong (B): ASC 715 explicitly requires bifurcation of service cost from other components. Wrong (C): Other components are reported in income, not OCI; only actuarial gains/losses and prior service cost changes go to OCI initially. Wrong (D): The standard does not prescribe allocation between COGS and selling expenses for non-service-cost components.$EXPL$, 'medium', 3),

-- Q2: easy / L1 — Defined benefit vs defined contribution distinction
(2, 'Pension and Postretirement Benefits', $EXPL$What distinguishes a defined benefit plan from a defined contribution plan?$EXPL$, $EXPL$["The employer bears no investment risk under a defined benefit plan", "A defined benefit plan specifies the pension benefits an employee will receive at retirement", "A defined benefit plan limits employer contributions to a fixed percentage of salary", "A defined benefit plan requires employee contributions while a defined contribution plan does not"]$EXPL$::jsonb, 1, $EXPL$Correct (B): ASC 715-30-20 defines a defined benefit plan as one that specifies a determinable pension benefit, typically based on factors such as age, years of service, and compensation. The employer bears the investment and actuarial risk. Wrong (A): The opposite is true — the employer bears investment risk in a defined benefit plan. Wrong (C): Fixed contribution amounts describe a defined contribution plan, not a defined benefit plan. Wrong (D): Employee contributions are not a distinguishing characteristic between the two plan types.$EXPL$, 'easy', 1),

-- Q3: medium / L2 — Funded status reporting
(2, 'Pension and Postretirement Benefits', $EXPL$At December 31, Year 2, Stellar Industries has a projected benefit obligation of $4,200,000 and plan assets at fair value of $3,800,000. How should Stellar report the pension plan on its balance sheet?$EXPL$, $EXPL$["A noncurrent asset of $400,000", "A prepaid pension cost of $400,000", "A net pension liability of $400,000", "No balance sheet amount because the plan is less than 10% underfunded"]$EXPL$::jsonb, 2, $EXPL$Correct (C): ASC 715-30-25-1 requires an employer to recognize the funded status of a defined benefit plan — the difference between the PBO and the fair value of plan assets — as a liability (if underfunded) or an asset (if overfunded). Here, $4,200,000 − $3,800,000 = $400,000 liability. Wrong (A): Because PBO exceeds plan assets, the plan is underfunded, resulting in a liability, not an asset. Wrong (B): The prepaid pension cost approach was eliminated by ASC 715 (formerly SFAS 158). Wrong (D): There is no materiality threshold exempting recognition of funded status.$EXPL$, 'medium', 2),

-- Q4: hard / L3 — Postemployment benefits before retirement (ASC 712)
(2, 'Pension and Postretirement Benefits', $EXPL$Trident Corp. announces a restructuring and expects to lay off 150 employees over the next six months. Under the existing severance policy, affected employees receive two weeks of pay per year of service. The estimated liability is $2,400,000. Trident also expects $300,000 in ongoing health benefits for displaced workers during the job-search period. How should Trident account for these postemployment benefits?$EXPL$, $EXPL$["Recognize only the severance liability; health benefits for displaced workers are not accrued", "Defer recognition of both amounts until the employees are actually terminated", "Expense both amounts only when cash payments are made to the affected employees", "Accrue both the severance and health care costs when the obligation is probable and estimable"]$EXPL$::jsonb, 3, $EXPL$Correct (D): ASC 712-10-25-1 requires employers to accrue a liability for postemployment benefits (including severance and continuation of health benefits) when the obligation is attributable to services already rendered, rights accumulate or vest, payment is probable, and the amount is reasonably estimable. Both the severance and health continuation meet these criteria. Wrong (A): ASC 712 covers all postemployment benefits, including health care continuation for former employees. Wrong (B): Accrual is required when the conditions are met, not deferred until actual termination. Wrong (C): Cash-basis recognition is not permitted; accrual accounting applies under ASC 712.$EXPL$, 'hard', 3),

-- Q5: easy / L2 — Expected return on plan assets effect
(2, 'Pension and Postretirement Benefits', $EXPL$River Corp. has plan assets of $5,000,000 with an expected long-term rate of return of 7%. Actual return on plan assets during Year 1 was $400,000. What amount should River use as the expected return on plan assets in computing net periodic pension cost?$EXPL$, $EXPL$["$350,000", "$400,000", "$50,000", "$300,000"]$EXPL$::jsonb, 0, $EXPL$Correct (A): ASC 715-30-35-10 requires using the expected return on plan assets, calculated as the expected long-term rate of return multiplied by the market-related value of plan assets. Expected return = $5,000,000 × 7% = $350,000. The actual return is irrelevant for this component. Wrong (B): This is the actual return, not the expected return used in the pension cost calculation. Wrong (C): This is the difference between actual and expected returns, which creates an actuarial gain/loss. Wrong (D): There is no basis for reducing the expected return to $300,000.$EXPL$, 'easy', 2),

-- Q6: medium / L2 — Interest cost component calculation
(2, 'Pension and Postretirement Benefits', $EXPL$At January 1, Year 4, Oakwood Inc. has a projected benefit obligation of $6,000,000. The discount rate used to measure the PBO is 5.5%. Service cost for Year 4 is $420,000 and benefits paid to retirees during Year 4 total $280,000. Assuming no amendments or curtailments, what is the interest cost component of net periodic pension cost for Year 4?$EXPL$, $EXPL$["$353,100", "$330,000", "$341,000", "$420,000"]$EXPL$::jsonb, 1, $EXPL$Correct (B): ASC 715-30-35-8 defines interest cost as the increase in PBO due to the passage of time, calculated as the beginning PBO multiplied by the discount rate. Interest cost = $6,000,000 × 5.5% = $330,000. Benefits paid and service cost do not affect the beginning-of-year interest cost calculation. Wrong (A): This incorrectly factors in partial-year adjustments for benefit payments. Wrong (C): This appears to interpolate mid-year accruals, which is not the standard approach. Wrong (D): This is the service cost, not the interest cost component.$EXPL$, 'medium', 2),

-- Q7: medium / L2 — Prior service cost initial recognition
(2, 'Pension and Postretirement Benefits', $EXPL$Harmon Corp. amends its defined benefit plan on July 1, Year 5, retroactively increasing benefits. The amendment results in prior service cost of $720,000. The average remaining service period of active employees expected to receive benefits is 12 years. How should Harmon initially recognize the prior service cost?$EXPL$, $EXPL$["As an immediate charge to pension expense of $720,000", "As an increase to the projected benefit obligation and a debit to retained earnings", "As a charge to other comprehensive income of $720,000, then amortized to pension cost over 12 years", "As a direct reduction of plan assets of $720,000"]$EXPL$::jsonb, 2, $EXPL$Correct (C): ASC 715-30-35-3 requires prior service cost arising from a plan amendment to be recognized in other comprehensive income in the period of the amendment and then amortized to net periodic pension cost over the future service periods of active employees expected to receive benefits. Wrong (A): Prior service cost is not expensed immediately; it is amortized over the remaining service period. Wrong (B): Prior service cost is debited to OCI, not retained earnings. Wrong (D): Plan amendments affect the PBO, not plan assets.$EXPL$, 'medium', 2),

-- Q8: medium / L3 — Settlement accounting threshold and recognition
(2, 'Pension and Postretirement Benefits', $EXPL$Bryson Corp. has a projected benefit obligation of $12,000,000 and service cost plus interest cost totaling $900,000 for Year 6. During Year 6, Bryson purchases annuities from an insurance company for $3,200,000, irrevocably settling a portion of its pension obligation. At what point must Bryson apply settlement accounting?$EXPL$, $EXPL$["Only if the settlement exceeds 50% of the PBO", "Only when the entire obligation is settled", "Only if settlement gains or losses exceed the corridor", "When the cost of all settlements in a period exceeds the sum of service cost and interest cost"]$EXPL$::jsonb, 3, $EXPL$Correct (D): ASC 715-30-35-79 provides that if the cost of all settlements in a period is less than or equal to the sum of the service cost and interest cost components, the employer may elect not to recognize settlement gain or loss. Settlement accounting is required when the cost exceeds this threshold. Here, $3,200,000 > $900,000, so settlement accounting is required. Wrong (A): The 50% threshold is not the standard for settlement recognition. Wrong (B): Partial settlements can also trigger settlement accounting. Wrong (C): The corridor concept applies to actuarial gain/loss amortization, not settlement recognition.$EXPL$, 'medium', 3),

-- Q9: hard / L4 — Curtailment vs settlement vs termination benefit analysis
(2, 'Pension and Postretirement Benefits', $EXPL$Apex Corp. closes a manufacturing plant, laying off 300 employees. Apex offers a one-time lump-sum payment of $15,000 to each employee who accepts within 60 days, eliminates future benefit accruals for all affected employees, and purchases annuity contracts to settle the pension obligations of 100 employees who are already retired. How should Apex account for these three events?$EXPL$, $EXPL$["Lump-sum payments are termination benefits (ASC 420); ceasing accruals is a curtailment; annuity purchase is a settlement (ASC 715)", "All three events are settlements under ASC 715 because they each eliminate pension obligations", "The lump-sum payments and cessation of accruals are both curtailments; the annuity purchase is a termination benefit", "All three events are termination benefits because they arise from the same plant closure event"]$EXPL$::jsonb, 0, $EXPL$Correct (A): The lump-sum offer is a one-time termination benefit under ASC 420-10 because it is a special inducement to accept early termination. Eliminating future accruals is a curtailment under ASC 715-30-35-92 because it significantly reduces expected future service. The annuity purchase irrevocably transfers the obligation, qualifying as a settlement under ASC 715-30-35-74. Wrong (B): The lump-sum payments are not part of the existing plan obligation and do not qualify as settlements. Wrong (C): Purchasing annuities transfers obligation to a third party, making it a settlement, not a termination benefit. Wrong (D): Each event has distinct accounting treatment based on its nature, not the triggering event.$EXPL$, 'hard', 4),

-- Q10: medium / L3 — Multiemployer plan accounting
(2, 'Pension and Postretirement Benefits', $EXPL$Kenmore Construction participates in a multiemployer defined benefit pension plan with five other companies. Kenmore contributed $1,200,000 for Year 7 per the collective bargaining agreement. The plan is underfunded by $18,000,000 in total. How should Kenmore account for its participation?$EXPL$, $EXPL$["Record a liability for its proportionate share of the $18,000,000 underfunding", "Recognize $1,200,000 as pension expense for Year 7", "Record both the contribution expense and a disclosure-only withdrawal liability", "Capitalize the contribution as a long-term pension asset"]$EXPL$::jsonb, 1, $EXPL$Correct (B): ASC 715-80-35-1 requires that an employer participating in a multiemployer plan recognize as net pension cost the required contribution for the period. Kenmore records $1,200,000 as pension expense. The plan's total underfunding is not allocated to individual employers on the balance sheet. Wrong (A): Employers in multiemployer plans generally do not recognize a proportionate share of the plan's underfunding unless withdrawal is probable. Wrong (C): Withdrawal liability is only recognized when withdrawal is probable and the amount is estimable. Wrong (D): Contributions to multiemployer plans are expensed, not capitalized.$EXPL$, 'medium', 3),

-- Q11: medium / L3 — ABO supplemental disclosure requirement
(2, 'Pension and Postretirement Benefits', $EXPL$At year-end, Radford Inc. reports a PBO of $9,500,000, plan assets at fair value of $8,700,000, and an accumulated benefit obligation (ABO) of $8,400,000. The company has recognized the funded status on its balance sheet based on the PBO. What additional reporting obligation does the ABO create?$EXPL$, $EXPL$["An additional minimum liability must be recognized for the excess of ABO over plan assets", "The ABO triggers a reclassification of the pension liability from noncurrent to current", "The ABO must be disclosed in the notes to the financial statements", "No additional obligation because the ABO is less than plan asset fair value"]$EXPL$::jsonb, 2, $EXPL$Correct (C): ASC 715-20-50-1 requires disclosure of the ABO in the notes to the financial statements. The balance sheet reports funded status based on PBO, but the ABO remains a required disclosure item. Wrong (A): The additional minimum liability concept was eliminated by SFAS 158 (now codified in ASC 715). Funded status is based on PBO. Wrong (B): The ABO does not drive current/noncurrent classification of the pension liability. Wrong (D): Even though ABO is less than plan assets here, disclosure is still required.$EXPL$, 'medium', 3),

-- Q12: easy / L1 — ERISA funding requirement vs GAAP accounting
(2, 'Pension and Postretirement Benefits', $EXPL$What is the relationship between ERISA minimum funding requirements and pension expense recognized under GAAP?$EXPL$, $EXPL$["ERISA funding requirements and GAAP pension expense are always identical amounts", "ERISA minimum funding is based on tax law and actuarial standards while GAAP expense follows ASC 715", "GAAP pension expense is always greater than the ERISA minimum funding requirement", "ERISA funding directly determines the amount of pension expense reported on the income statement"]$EXPL$::jsonb, 3, $EXPL$Correct (D): ERISA minimum funding requirements are determined under IRC and actuarial standards (e.g., IRC Section 430), while GAAP pension expense is calculated under ASC 715-30-35. The two amounts typically differ because they use different assumptions, methods, and objectives. ERISA governs cash contributions; ASC 715 governs financial reporting. Wrong (A): The two amounts are calculated independently and rarely match. Wrong (B): While partially correct in distinguishing the frameworks, this choice incorrectly implies ERISA is solely tax-law-based. Wrong (C): GAAP expense may be greater or less than ERISA funding in any given year.$EXPL$, 'easy', 1),

-- Q13: easy / L1 — Projected benefit obligation definition
(2, 'Pension and Postretirement Benefits', $EXPL$What does the projected benefit obligation (PBO) represent?$EXPL$, $EXPL$["The actuarial present value of all benefits attributed to employee service to date, using assumptions about future compensation levels", "The total undiscounted future benefit payments expected to be made to current retirees", "The amount an employer would owe if the plan were terminated immediately at current salary levels", "The employer's cumulative cash contributions to the plan trust since inception"]$EXPL$::jsonb, 0, $EXPL$Correct (A): ASC 715-30-20 defines the PBO as the actuarial present value of all benefits attributed by the pension benefit formula to employee service rendered before that date, measured using assumptions about future compensation levels. Wrong (B): The PBO is discounted to present value, not undiscounted, and includes active employees, not just retirees. Wrong (C): This describes a concept closer to the vested benefit obligation upon plan termination, not the PBO. Wrong (D): The PBO is an actuarial measure of obligation, not a measure of cumulative contributions.$EXPL$, 'easy', 1),

-- Q14: hard / L4 — Negative plan amendment reducing PBO and prior service credit
(2, 'Pension and Postretirement Benefits', $EXPL$Delta Corp. amends its defined benefit plan to reduce future benefits, resulting in a $500,000 decrease in the PBO. Delta has $180,000 of unrecognized prior service cost remaining in accumulated OCI from a previous amendment. The average remaining service period is 8 years. How should Delta account for this negative plan amendment?$EXPL$, $EXPL$["Offset the $500,000 against the existing $180,000 prior service cost and amortize the $320,000 net credit over 8 years", "Recognize the $500,000 as a prior service credit in OCI, and continue amortizing the existing $180,000 separately", "Record an immediate gain of $500,000 in pension expense", "Reduce the $180,000 prior service cost first, then recognize the remaining $320,000 credit in OCI and amortize over 8 years"]$EXPL$::jsonb, 1, $EXPL$Correct (B): ASC 715-30-35-14 states that a plan amendment that retroactively reduces benefits creates a negative prior service cost (credit) recognized in OCI. Under ASC 715-30-35-15, the new prior service credit is accounted for separately from existing prior service cost. Each amount follows its own amortization schedule. Wrong (A): The standard does not require netting of prior service cost and credits from different amendments. Wrong (C): Negative amendments are not recognized as immediate gains; they go through OCI and are amortized. Wrong (D): This netting approach is not prescribed by ASC 715; each amendment is tracked independently.$EXPL$, 'hard', 4),

-- Q15: medium / L2 — Discount rate selection basis
(2, 'Pension and Postretirement Benefits', $EXPL$Westlake Inc. is selecting a discount rate for measuring its projected benefit obligation at December 31, Year 8. Current yields on high-quality corporate bonds with maturities matching the expected benefit payments range from 4.8% to 5.4%, while the 30-year Treasury rate is 4.2%. What rate should Westlake use?$EXPL$, $EXPL$["The 30-year Treasury rate of 4.2%", "The midpoint between the Treasury rate and corporate bond yields", "A rate within the 4.8% to 5.4% range based on high-quality corporate bond yields", "The plan's expected long-term rate of return on assets"]$EXPL$::jsonb, 2, $EXPL$Correct (C): ASC 715-30-35-43 requires the discount rate to reflect the rates at which pension benefits could be effectively settled, referencing high-quality fixed-income investments with cash flows matching the timing and amount of expected benefit payments. Wrong (A): Treasury rates are not the prescribed benchmark for PBO discount rates under ASC 715. Wrong (B): There is no blending methodology prescribed; the standard specifically references high-quality corporate bonds. Wrong (D): The expected return on plan assets is a separate assumption used for the return component, not for discounting the obligation.$EXPL$, 'medium', 2),

-- Q16: medium / L2 — Plan assets measurement and permissible investments
(2, 'Pension and Postretirement Benefits', $EXPL$Pinehurst Corp. holds the following in its pension plan trust: publicly traded equity securities valued at $3,000,000, corporate bonds at $2,000,000, and a company-owned office building used by plan administrators valued at $500,000. At what amount should Pinehurst report total plan assets?$EXPL$, $EXPL$["$5,500,000 at fair value", "$5,000,000 at fair value", "$5,000,000 at amortized cost", "$5,500,000 at fair value, with the building reported at depreciated cost"]$EXPL$::jsonb, 3, $EXPL$Correct (D): ASC 715-30-35-58 requires plan assets to be measured at fair value. Per ASC 715-30-35-59, assets used in plan operations (such as a building used by plan administrators) are plan assets measured at fair value. All $5,500,000 is included, with the building at fair value. Wrong (A): While the total is correct, plan assets are specifically measured at fair value — this choice does not address the building question fully. Wrong (B): This incorrectly excludes the building, but property used in plan operations qualifies as a plan asset. Wrong (C): Plan assets are measured at fair value, not amortized cost.$EXPL$, 'medium', 2),

-- Q17: easy / L1 — Employer contribution accounting in defined contribution plan
(2, 'Pension and Postretirement Benefits', $EXPL$How does an employer account for its required annual contribution to a defined contribution plan?$EXPL$, $EXPL$["As compensation expense in the period the contribution is required", "As a reduction of retained earnings in the period earned by employees", "As a deferred asset amortized over the employees' remaining service life", "As a direct charge to other comprehensive income"]$EXPL$::jsonb, 0, $EXPL$Correct (A): ASC 715-70-25-1 requires the employer to recognize the contribution required for a period as net pension cost (compensation expense) for that period. In a defined contribution plan, the employer's obligation is limited to the contribution amount. Wrong (B): Pension contributions are expensed on the income statement, not charged directly to retained earnings. Wrong (C): Contributions are expensed when required, not deferred and amortized. Wrong (D): Defined contribution plan costs are recognized in net income, not OCI.$EXPL$, 'easy', 1),

-- Q18: easy / L1 — Vested benefit obligation definition
(2, 'Pension and Postretirement Benefits', $EXPL$What is the vested benefit obligation (VBO) of a defined benefit pension plan?$EXPL$, $EXPL$["The present value of all benefits expected to be paid based on projected future salaries", "The portion of the accumulated benefit obligation that employees are entitled to receive regardless of continued employment", "The total amount of employer contributions made to the plan trust", "The present value of benefits payable only to employees who have reached retirement age"]$EXPL$::jsonb, 1, $EXPL$Correct (B): ASC 715-30-20 defines the vested benefit obligation as the portion of the ABO to which employees have a nonforfeitable right, meaning they are entitled to receive benefits regardless of whether they continue working for the employer. Wrong (A): This describes the projected benefit obligation, not the VBO. Wrong (C): The VBO is an obligation measure, not a measure of contributions. Wrong (D): The VBO includes all vested benefits, not just those for employees who have reached retirement age.$EXPL$, 'easy', 1),

-- Q19: hard / L4 — OPEB vs pension measurement differences and transition
(2, 'Pension and Postretirement Benefits', $EXPL$Bellingham Corp. sponsors both a defined benefit pension plan and a retiree health care plan (OPEB). The OPEB plan provides medical benefits to retirees over age 55 with at least 15 years of service. A newly hired 40-year-old employee will reach full eligibility at age 55. How does the attribution period for this employee's OPEB benefits differ from the pension benefit attribution, and what is the practical consequence?$EXPL$, $EXPL$["OPEB benefits are attributed from hire date to expected retirement date, identical to pension benefits", "OPEB cost is front-loaded because the attribution period ends at the full eligibility date rather than the expected retirement date", "OPEB benefits use the expected retirement date while pension benefits use the full eligibility date for attribution", "There is no difference; both OPEB and pension benefits are attributed over the same service period"]$EXPL$::jsonb, 2, $EXPL$Correct (C): ASC 715-60-35-6 requires OPEB benefits to be attributed from the employee's date of hire to the full eligibility date (age 55 with 15 years of service), not the expected retirement date. This is unlike pensions, where benefits accrue until retirement. This front-loads OPEB cost recognition because the attribution period is shorter. Wrong (A): OPEB attribution ends at full eligibility, not expected retirement; this is a key distinction from pension accounting. Wrong (B): While the result is correct (front-loading), the answer choice reverses which plan uses which date. Wrong (D): The attribution periods differ significantly between OPEB and pension plans, which is a fundamental distinction under ASC 715.$EXPL$, 'hard', 4),

-- Q20: medium / L2 — Remeasurement trigger for interim events
(2, 'Pension and Postretirement Benefits', $EXPL$On September 1, Year 9, Crestview Corp. amends its defined benefit pension plan, significantly increasing benefits. Crestview's fiscal year ends December 31. What measurement action is required as a result of this amendment?$EXPL$, $EXPL$["No remeasurement until the next annual measurement date", "Remeasurement of the PBO and plan assets only if the amendment increases costs by more than 10%", "Remeasurement at year-end only, using September 1 assumptions", "Remeasurement of the PBO as of the amendment date using current assumptions"]$EXPL$::jsonb, 3, $EXPL$Correct (D): ASC 715-30-35-68 requires remeasurement of plan assets and benefit obligations when a significant event such as a plan amendment occurs. The PBO must be remeasured as of the date of the amendment using current discount rates and other assumptions. Wrong (A): A plan amendment is a significant event that triggers interim remeasurement. Wrong (B): There is no 10% materiality threshold for triggering remeasurement upon a plan amendment. Wrong (C): The remeasurement date is the date of the event, not deferred to year-end.$EXPL$, 'medium', 2),

-- Q21: medium / L3 — Actuarial gain/loss recognition in OCI
(2, 'Pension and Postretirement Benefits', $EXPL$Langley Inc. expected a return of $600,000 on plan assets but earned an actual return of $820,000 during Year 10. The beginning-of-year net actuarial loss in accumulated OCI was $200,000, and the corridor threshold is $350,000. How does the $220,000 asset gain affect Langley's financial statements for Year 10?$EXPL$, $EXPL$["Recognized as a credit to other comprehensive income, reducing the net actuarial loss in AOCI to a net loss of zero", "Recognized as a $220,000 gain in net periodic pension cost immediately", "Recognized in OCI, reducing the net actuarial loss in AOCI from $200,000 to a net gain of $20,000", "Offset against the $200,000 existing loss, with the $20,000 excess deferred"]$EXPL$::jsonb, 0, $EXPL$Correct (A): ASC 715-30-35-22 requires the difference between actual and expected return ($820,000 − $600,000 = $220,000 gain) to be recognized in OCI. This reduces the net actuarial loss in AOCI from $200,000 to a net gain position. However, the net amount at year-end determines corridor amortization, not immediate income recognition. Wrong (B): Asset-related gains and losses are not immediately recognized in pension expense; they flow through OCI first. Wrong (C): While the direction is correct, the net position would be a $20,000 gain (credit), not just reducing to zero. Wrong (D): The full $220,000 gain goes to OCI; there is no deferral mechanism separate from the OCI process.$EXPL$, 'medium', 3),

-- Q22: easy / L1 — ASC 965 health and welfare plan financial statements
(2, 'Pension and Postretirement Benefits', $EXPL$What primary financial statement does a health and welfare benefit plan prepare under ASC 965?$EXPL$, $EXPL$["A standard corporate income statement showing plan revenues and expenses", "A statement of net assets available for benefits showing plan investments and obligations", "A statement of cash flows showing only benefit payments to participants", "A balance sheet identical to the sponsoring employer's pension disclosures"]$EXPL$::jsonb, 1, $EXPL$Correct (B): ASC 965-205-45-1 requires a health and welfare benefit plan to present a statement of net assets available for benefits, which includes plan investments at fair value, receivables, and liabilities. This is the primary financial statement for plan-level reporting. Wrong (A): Benefit plans do not use corporate income statement formats. Wrong (C): A statement of cash flows is not the primary required statement for health and welfare plans. Wrong (D): Plan-level financial statements are separate from the employer's pension disclosures and follow different presentation requirements.$EXPL$, 'easy', 1),

-- Q23: medium / L3 — Curtailment gain/loss calculation
(2, 'Pension and Postretirement Benefits', $EXPL$Noble Corp. eliminates a division, resulting in a curtailment that reduces the PBO by $1,800,000. At the curtailment date, Noble has unrecognized prior service cost of $600,000 and a net actuarial loss in AOCI of $400,000. The proportion of future service eliminated is 40%. What is the net curtailment gain or loss?$EXPL$, $EXPL$["Net curtailment gain of $1,800,000", "Net curtailment gain of $1,560,000", "Net curtailment gain of $1,640,000", "Net curtailment gain of $1,200,000"]$EXPL$::jsonb, 2, $EXPL$Correct (C): ASC 715-30-35-93 requires recognizing in curtailment: (1) the unrecognized prior service cost associated with eliminated service = 40% × $600,000 = $240,000 loss, and (2) if the curtailment reduces the PBO, a gain equal to the PBO decrease minus the proportionate share of net loss = $1,800,000. The net actuarial loss proportion recognized = 40% × $400,000 = $160,000. Net curtailment effect = $1,800,000 − $240,000 + $240,000 − $160,000 = $1,640,000 gain. Wrong (A): This ignores the required acceleration of prior service cost and net loss. Wrong (B): This only accounts for the prior service cost acceleration but omits the net actuarial loss acceleration. Wrong (D): This incorrectly nets only the PBO reduction less prior service cost without addressing actuarial losses.$EXPL$, 'medium', 3),

-- Q24: medium / L3 — Pension plan with negative amendment and OCI treatment
(2, 'Pension and Postretirement Benefits', $EXPL$Grant Industries amends its pension plan to freeze benefit accruals for all active participants, reducing the PBO by $2,100,000. At the amendment date, accumulated OCI includes $900,000 of prior service cost from a prior amendment. How should Grant account for the freeze?$EXPL$, $EXPL$["Recognize the $2,100,000 PBO reduction in pension expense immediately", "Accelerate the $900,000 prior service cost to pension expense and ignore the PBO reduction", "Record a $2,100,000 prior service credit in OCI and continue amortizing the $900,000 existing cost", "Record the $2,100,000 PBO reduction as a credit to OCI, offset by immediate recognition of the $900,000 prior service cost as a curtailment loss"]$EXPL$::jsonb, 3, $EXPL$Correct (D): A benefit freeze is both a plan amendment (creating prior service credit in OCI) and a curtailment (significantly reducing future service). Under ASC 715-30-35-93, curtailment requires accelerating the remaining unrecognized prior service cost ($900,000) to pension expense. The PBO reduction of $2,100,000 is recognized as a curtailment gain in OCI. The net effect combines both items. Wrong (A): The PBO reduction is not recognized entirely in pension expense; curtailment accounting applies. Wrong (B): The PBO reduction cannot be ignored; it creates a curtailment gain. Wrong (C): A benefit freeze triggers curtailment accounting, requiring acceleration of existing prior service cost rather than continued amortization.$EXPL$, 'medium', 3),

-- Q25: hard / L4 — ASC 960 plan-level financial statements
(2, 'Pension and Postretirement Benefits', $EXPL$A defined benefit pension plan prepares its own financial statements under ASC 960. The plan holds equity securities at fair value of $45,000,000, bonds at fair value of $30,000,000, and has an actuarially determined present value of accumulated plan benefits of $68,000,000. The plan paid $4,200,000 in benefits during the year. What financial statements and key disclosures does ASC 960 require the plan to present?$EXPL$, $EXPL$["A statement of net assets available for benefits and a statement of changes in net assets, with the actuarial present value of accumulated plan benefits disclosed either in a separate statement or in the notes", "An income statement and balance sheet identical to a corporate entity's financial statements", "Only a statement of cash flows showing benefit payments and employer contributions", "A statement of net assets available for benefits only, with no actuarial information required"]$EXPL$::jsonb, 0, $EXPL$Correct (A): ASC 960-205-45 requires a defined benefit plan to present a statement of net assets available for benefits and a statement of changes in net assets available for benefits. ASC 960-20-50 requires the actuarial present value of accumulated plan benefits to be presented either in a separate financial statement or disclosed in the notes. Wrong (B): Pension plans do not follow corporate entity financial statement formats; they use plan-specific statements. Wrong (C): A statement of cash flows is not the primary required statement; ASC 960 focuses on net assets and accumulated plan benefits. Wrong (D): Actuarial information about accumulated plan benefits is a required element, not optional.$EXPL$, 'hard', 4),

-- Q26: easy / L1 — Accumulated benefit obligation definition
(2, 'Pension and Postretirement Benefits', $EXPL$How does the accumulated benefit obligation (ABO) differ from the projected benefit obligation (PBO)?$EXPL$, $EXPL$["The ABO is always greater than the PBO", "The ABO uses current salary levels rather than projected future salary levels", "The ABO includes only benefits for retired employees, not active employees", "The ABO uses a higher discount rate than the PBO"]$EXPL$::jsonb, 1, $EXPL$Correct (B): ASC 715-30-20 defines the ABO as the actuarial present value of benefits attributed to employee service rendered before a specified date, measured using current compensation levels. The PBO uses projected future compensation, making it generally larger than the ABO. Wrong (A): The PBO is typically greater than the ABO because it incorporates future salary increases. Wrong (C): The ABO includes benefits for both active and retired employees, measured at current salary levels. Wrong (D): Both the ABO and PBO use the same discount rate; the difference is in the salary assumption.$EXPL$, 'easy', 1),

-- Q27: easy / L1 — OCI items related to pensions
(2, 'Pension and Postretirement Benefits', $EXPL$Which pension-related item is initially recognized in other comprehensive income rather than net income?$EXPL$, $EXPL$["Service cost for the current period", "Employer contributions to the plan trust", "Net actuarial gains and losses arising during the period", "Interest cost on the projected benefit obligation"]$EXPL$::jsonb, 2, $EXPL$Correct (C): ASC 715-30-35-22 requires net actuarial gains and losses arising during the period (including differences between expected and actual returns and changes in actuarial assumptions) to be recognized in other comprehensive income. They are subsequently amortized to pension expense. Wrong (A): Service cost is a component of net periodic pension cost recognized in net income. Wrong (B): Employer contributions are cash flows, not recognized in OCI. Wrong (D): Interest cost is a component of net periodic pension cost recognized in net income.$EXPL$, 'easy', 1),

-- Q28: medium / L2 — Measurement date requirements
(2, 'Pension and Postretirement Benefits', $EXPL$Prescott Inc. has a fiscal year ending June 30. The company previously measured its pension plan obligations as of April 30. Under current ASC 715 requirements, when must Prescott measure its projected benefit obligation and plan assets?$EXPL$, $EXPL$["Any date within three months of the fiscal year-end", "The first day of the fiscal year", "The date of the most recent actuarial valuation regardless of timing", "As of the fiscal year-end date, June 30"]$EXPL$::jsonb, 3, $EXPL$Correct (D): ASC 715-30-35-63 requires the measurement date for plan assets and obligations to be the employer's fiscal year-end date. The earlier practice of using a measurement date up to three months before year-end was eliminated by SFAS 158 (codified in ASC 715). Wrong (A): The three-month early measurement option was eliminated; measurement must be at fiscal year-end. Wrong (B): Measurement is at the end, not the beginning, of the fiscal year. Wrong (C): The actuarial valuation may be performed at a different date, but the results must be rolled forward to the fiscal year-end measurement date.$EXPL$, 'medium', 2),

-- Q29: medium / L2 — Expected long-term rate of return assumption
(2, 'Pension and Postretirement Benefits', $EXPL$Thornton Corp. is selecting its expected long-term rate of return on plan assets. The plan's asset allocation is 60% equities and 40% bonds. Historical equity returns average 9% and bond returns average 4%. Thornton's investment manager projects future returns of 7.5% for equities and 3.5% for bonds. What basis should Thornton use?$EXPL$, $EXPL$["A forward-looking estimate considering the plan's asset allocation, expected returns by asset class, and historical patterns", "Strictly the historical average weighted return of 7% (60% × 9% + 40% × 4%)", "The risk-free rate plus a fixed equity risk premium mandated by ASC 715", "The same rate as the discount rate used for the PBO to maintain consistency"]$EXPL$::jsonb, 0, $EXPL$Correct (A): ASC 715-30-35-47 states the expected long-term rate of return should reflect the average rate of earnings expected on assets invested and to be invested. This requires considering the plan's current and target asset allocation, expected future returns by asset class, and historical experience as a reference. Wrong (B): Purely historical returns without forward-looking adjustment do not comply with ASC 715 guidance. Wrong (C): ASC 715 does not prescribe a formula based on risk-free rate plus a fixed premium. Wrong (D): The discount rate and expected return serve different purposes and are determined independently.$EXPL$, 'medium', 2),

-- Q30: hard / L4 — Withdrawal liability from multiemployer plan
(2, 'Pension and Postretirement Benefits', $EXPL$Hartford Mfg. plans to withdraw from a multiemployer defined benefit pension plan in which it participated for 20 years. The plan's actuary estimates Hartford's withdrawal liability at $8,500,000, payable in annual installments over 15 years. Hartford disputes the calculation and believes the liability is closer to $5,000,000. Under what conditions should Hartford recognize a withdrawal liability, and at what amount?$EXPL$, $EXPL$["Only upon actual withdrawal; recognize at the undiscounted $8,500,000 assessed by the plan", "When withdrawal is probable and the amount is reasonably estimable; recognize the best estimate within the $5,000,000 to $8,500,000 range, or $5,000,000 if no amount in the range is a better estimate", "Upon formal notification from the plan; recognize at the discounted present value of $8,500,000", "No recognition is required because multiemployer plan liabilities are disclosed only"]$EXPL$::jsonb, 1, $EXPL$Correct (B): ASC 715-80-35-3 and ASC 450-20-25 require recognition of a withdrawal liability when it is probable and reasonably estimable. When a range of estimates exists with no best estimate, the minimum of the range ($5,000,000) is recognized per ASC 450-20-30. If a best estimate exists within the range, that amount is used. Wrong (A): Recognition is required when withdrawal is probable, not necessarily upon actual withdrawal, and the employer's own best estimate may be used. Wrong (C): Formal notification is not the recognition trigger; probability and estimability are the criteria. Wrong (D): Withdrawal liabilities must be recognized on the balance sheet when probable and estimable, not merely disclosed.$EXPL$, 'hard', 4)
;

COMMIT;
