-- Migration: Quality fix -- AUD batch 2 (30 questions)
-- Generated by generate-quality-scaffold.ts
-- Issues: #1 (giveaway longest), #3 (incomplete explanation)

-- Q287: Internal Controls [hard/L1]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["Controls implemented by the service organization at the user entity''s location","Controls the user entity must operate for the service organization''s controls to be effective","Optional controls the service auditor recommends for best practices","Controls the PCAOB tests during its annual inspection cycle"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (B): Under AU-C 402.09 and .A13, complementary user entity controls (CUECs) are controls that the service organization''s system assumes the user entity will implement. AU-C 402.15 requires the user auditor to evaluate and test CUECs because the service organization''s controls alone may not achieve objectives without them.
Wrong (A): CUECs are the user entity''s own controls, not controls the service organization implements at the user entity.
Wrong (C): CUECs are not optional recommendations — they are assumed to be in place by the service organization''s control design.
Wrong (D): CUECs are evaluated by the user auditor, not tested by the PCAOB during inspections.$EXPL$
WHERE id = 287;

-- Q289: Internal Controls [easy/L1]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["Both revenue accounts and expense accounts within the same cycle","Authorization, recording, and custody of assets for the same transactions","Both the external audit engagement and the annual tax return","Both financial statement preparation and the annual budgeting process"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (B): Segregation of duties is a fundamental internal control principle requiring separation of three functions: authorization of transactions, recording (bookkeeping), and custody of related assets. When one person controls all three, the risk of undetected errors or fraud increases significantly.
Wrong (A): Revenue and expense accounts are separate line items, not the three incompatible functions that segregation of duties addresses.
Wrong (C): Audit and tax return preparation are separate professional services, not internal control functions within the entity.
Wrong (D): Financial statement preparation and budgeting are both accounting functions but do not represent the three incompatible duties.$EXPL$
WHERE id = 289;

-- Q290: Internal Controls [medium/L2]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["Covers security and availability controls rather than financial reporting controls","Reports on control design at a point in time, not operating effectiveness over a period","Is intended for unrestricted general public distribution and use","Can only be issued by auditors registered with the PCAOB"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (B): Under AU-C 402.14, a SOC 1 Type 1 report covers the description and design of controls at a specific point in time. A Type 2 report additionally tests operating effectiveness over a specified period, typically 6 to 12 months.
Wrong (A): Both Type 1 and Type 2 SOC 1 reports address controls relevant to user entities'' financial reporting, not IT security criteria.
Wrong (C): SOC 1 reports are restricted-use reports intended for user entities and their auditors, not for general public distribution.
Wrong (D): SOC 1 reports are issued by service auditors under AICPA standards, not exclusively by PCAOB-registered firms.$EXPL$
WHERE id = 290;

-- Q291: Internal Controls [easy/L1]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["Modify the client''s accounting software to automatically correct detected errors","Issue the audit opinion without requiring further manual review procedures","Eliminate the need for all substantive testing of account balances","Read, analyze, and sample client data files without altering original records"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (D): Under AU-C 315.A82, generalized audit software (GAS) allows the auditor to directly access and analyze electronic data files. GAS capabilities include sorting, summarizing, selecting samples, comparing files, and detecting duplicates — all without modifying original data.
Wrong (A): GAS does not modify the client''s software or data — it is a read-only analytical tool used by the auditor.
Wrong (B): GAS assists with data analysis but does not generate or issue the audit opinion, which requires professional judgment.
Wrong (C): GAS supports substantive procedures but does not replace them; the auditor must still evaluate results and draw conclusions.$EXPL$
WHERE id = 291;

-- Q292: Internal Controls [medium/L2]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["Only to the engagement quality reviewer assigned to the audit","To the SEC within 30 days of discovery of the weakness","Orally to management during the exit conference at fieldwork conclusion","In writing to management and governance within 60 days of report release"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (D): Under AU-C 265.13, when a material weakness is identified during a non-issuer audit, the auditor must communicate it in writing to management and those charged with governance no later than 60 days following the report release date. Significant deficiencies follow the same requirement.
Wrong (A): Communication must go to management and those charged with governance, not only to the engagement quality reviewer.
Wrong (B): Non-issuer audits are governed by AU-C standards, not SEC reporting requirements; SEC filing applies to issuers.
Wrong (C): Oral communication alone is insufficient for material weaknesses — AU-C 265 specifically requires written communication.$EXPL$
WHERE id = 292;

-- Q294: Audit Evidence [easy/L1]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["Whether account balances reconcile to the general ledger totals","Whether third-party confirmations agree with the recorded balances","Whether all recorded transactions received proper management authorization","Whether leading-digit frequencies in the data follow the expected mathematical pattern"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (D): Benford''s Law predicts the expected frequency distribution of leading digits in naturally occurring numerical data. Significant deviations from this pattern may indicate manipulation, errors, or fabricated data warranting further investigation under AU-C 520.
Wrong (A): Reconciling balances to the general ledger is a standard substantive procedure, not a digital analysis technique based on Benford''s Law.
Wrong (B): Confirming balances with third parties is a confirmation procedure under AU-C 505, unrelated to digit frequency analysis.
Wrong (C): Testing transaction authorization is a test of controls, not a data analytics technique examining digit distributions.$EXPL$
WHERE id = 294;

-- Q302: Audit Evidence [easy/L1]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["Individual balances are large and the assessed risk of misstatement is high","The misstatement risk is low, balances are small and numerous, and few exceptions are expected","Management has specifically refused to permit the use of positive confirmations","The auditor needs to obtain the highest possible level of assurance over balances"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (B): Under AU-C 505.16, negative confirmations are appropriate when the risk of material misstatement is assessed as low, the population consists of many small balances, and the auditor expects few exceptions. Non-responses are treated as agreement with the recorded balance.
Wrong (A): Large balances with high assessed risk warrant positive confirmations, which require explicit responses from recipients.
Wrong (C): Management''s refusal to allow positive confirmations is not a valid basis for using negative confirmations; it may constitute a scope limitation.
Wrong (D): Negative confirmations provide less assurance than positive confirmations because non-response is assumed to indicate agreement.$EXPL$
WHERE id = 302;

-- Q304: Audit Sampling [medium/L1]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["Increase the total number of items the auditor must test","Reduce variability within subgroups, potentially reducing required sample size","Eliminate sampling risk entirely from the testing procedure","Ensure the auditor tests only the largest items in the population"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (B): Under AU-C 530.A11, stratification divides the population into subgroups with similar characteristics, reducing variability within each stratum. This allows the auditor to design more efficient samples, often resulting in a smaller total sample size while maintaining the desired assurance level.
Wrong (A): Stratification typically reduces rather than increases the total number of items tested by improving sampling efficiency.
Wrong (C): No sampling technique can eliminate sampling risk entirely — only a 100% examination of the population achieves that.
Wrong (D): Stratification ensures appropriate coverage of all strata, not exclusive focus on large items.$EXPL$
WHERE id = 304;

-- Q305: Audit Sampling [medium/L2]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["Audit sampling because items are selected from a defined population","A complete examination of a subpopulation, not audit sampling","An analytical procedure applied to the top dollar stratum","A violation of the professional sampling standards requirements"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (B): Under AU-C 530.05, audit sampling involves applying procedures to less than 100% of items within a population. Testing all items in a stratum constitutes complete examination, not sampling. AU-C 530.A4 notes that auditors commonly combine complete examination of the top stratum with sampling of remaining strata.
Wrong (A): Selecting every item in a subgroup is 100% testing of that subgroup, which by definition is not sampling under AU-C 530.
Wrong (C): Testing all items above a dollar threshold is a substantive test of details, not an analytical procedure.
Wrong (D): Complete examination of a high-value stratum is a recognized and appropriate audit strategy, not a violation of standards.$EXPL$
WHERE id = 305;

-- Q307: Audit Sampling [hard/L1]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["Determine the appropriate sample size for the MUS test","Measure the overall reliability of the sampling method used","Calculate the tolerable deviation rate for the population","Project a sample item''s misstatement proportionally to the sampling interval"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (D): Under AU-C 530.A24, the tainting percentage in MUS projects misstatements from sampled items to the population. It is calculated as (Book Value minus Audit Value) divided by Book Value, then multiplied by the sampling interval to compute the projected misstatement for that item.
Wrong (A): Sample size in MUS is determined by tolerable misstatement, expected misstatement, and desired confidence — not by the tainting percentage.
Wrong (B): The tainting percentage measures the proportional error in a specific item, not the overall reliability of the sampling method.
Wrong (C): Tolerable deviation rate applies to tests of controls (attribute sampling), not to MUS substantive testing.$EXPL$
WHERE id = 307;

-- Q309: Audit Sampling [medium/L2]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["The population is acceptable as stated and no further work is needed","The sample selected was too large for the population being tested","The population may be materially misstated and additional procedures are needed","Sampling risk has been fully eliminated by the projection calculation"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (C): Under AU-C 530.14, if projected misstatement plus the allowance for sampling risk exceeds tolerable misstatement, the auditor cannot conclude the population is free from material misstatement. Here, $185,000 + $90,000 = $275,000 exceeds the $250,000 threshold. The auditor should expand testing, perform alternative procedures, or request management adjustment.
Wrong (A): Accepting the population would be inappropriate because the sampling results indicate a risk of material misstatement exceeding the tolerable threshold.
Wrong (B): The issue is not sample size — the projected misstatement plus allowance exceeds tolerable misstatement regardless of sample size.
Wrong (D): Sampling risk cannot be eliminated through MUS; it exists whenever less than 100% of the population is tested.$EXPL$
WHERE id = 309;

-- Q313: Audit Sampling [easy/L1]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["It requires the auditor to use specialized computer audit software","A single block of consecutive items may not represent the entire population","It is significantly more expensive than using random selection methods","It can only be applied to tests of controls, not substantive tests"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (B): Under AU-C 530.A11, block selection — choosing a contiguous set of items such as all transactions from one month — is discouraged because a single block may not represent the full population across the entire period. Conditions in the selected block may differ from other periods.
Wrong (A): Block selection does not require computer software; it is a manual selection method that simply picks consecutive items.
Wrong (C): Block selection is not more expensive than random selection — the concern is representativeness, not cost.
Wrong (D): Block selection can be applied to both tests of controls and substantive tests, but the representativeness concern applies in either case.$EXPL$
WHERE id = 313;

-- Q316: Substantive Procedures [easy/L1]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["Accept management''s estimate without further inquiry or testing","Review the aging schedule, evaluate collection history, and assess specific accounts","Confirm every individual receivable balance directly with customers","Calculate the allowance using a fixed percentage of total outstanding receivables"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (B): Under AU-C 540.13, testing an accounting estimate requires evaluating the data and assumptions underlying it. For the allowance for doubtful accounts, this includes reviewing the receivables aging, analyzing historical collection experience, evaluating economic conditions, and assessing specific doubtful accounts.
Wrong (A): Accepting management''s estimate without inquiry fails to meet AU-C 540 requirements for evaluating the reasonableness of estimates.
Wrong (C): Confirming all balances tests existence and rights but does not directly evaluate the reasonableness of the valuation allowance.
Wrong (D): A fixed percentage is arbitrary and does not reflect the entity-specific conditions that AU-C 540 requires the auditor to evaluate.$EXPL$
WHERE id = 316;

-- Q317: Substantive Procedures [medium/L4]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["Evaluate management''s plans to mitigate the going concern conditions","Immediately issue a disclaimer of opinion on the financial statements","Withdraw from the engagement due to the going concern uncertainty","Issue a qualified opinion citing the going concern indicators identified"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (A): Under AU-C 570.12, when the auditor identifies conditions raising substantial doubt about going concern — such as recurring losses and working capital deficiency — the auditor must evaluate management''s plans to mitigate the conditions. Plans may include asset dispositions, debt restructuring, or cost reductions, and the auditor assesses their feasibility.
Wrong (B): Issuing a disclaimer is not the immediate next step; the auditor must first evaluate management''s plans before determining the report impact.
Wrong (C): Withdrawal is not appropriate in response to going concern indicators; the auditor should complete the evaluation process.
Wrong (D): A qualified opinion is not issued solely based on identifying indicators — the auditor must first evaluate management''s plans and assess disclosure adequacy.$EXPL$
WHERE id = 317;

-- Q318: Substantive Procedures [easy/L1]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["One year from the balance sheet date of the financial statements","One year from the date the financial statements are issued or available to be issued","Two years from the balance sheet date of the financial statements","Six months from the date the auditor''s report is issued"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (B): Under AU-C 570.03, the going concern evaluation covers a reasonable period defined as one year from the date the financial statements are issued or available to be issued. This is an important distinction from the balance sheet date and extends the evaluation period further.
Wrong (A): Measuring from the balance sheet date would shorten the evaluation period and does not match AU-C 570.03.
Wrong (C): Two years exceeds the standard''s one-year requirement and is not the defined reasonable period.
Wrong (D): Six months is too short and does not align with the one-year requirement under AU-C 570.$EXPL$
WHERE id = 318;

-- Q319: Substantive Procedures [medium/L2]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["Issue an adverse opinion on the financial statements as presented","Issue an unmodified opinion with an emphasis-of-matter paragraph","Issue a disclaimer of opinion due to the going concern uncertainty","Withdraw from the engagement and decline to issue any report"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (B): Under AU-C 570.20 and AU-C 706.06, when substantial doubt about going concern exists and the entity provides adequate disclosure, the auditor issues an unmodified opinion with an emphasis-of-matter paragraph drawing attention to the going concern disclosure in the notes.
Wrong (A): An adverse opinion is for material misstatements, not for adequately disclosed going concern uncertainties.
Wrong (C): A disclaimer applies to scope limitations where sufficient evidence cannot be obtained, not to going concern with adequate disclosure.
Wrong (D): Withdrawal is not appropriate when the auditor has sufficient evidence and the entity has provided adequate going concern disclosure.$EXPL$
WHERE id = 319;

-- Q327: Audit Reports [easy/L1]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["A matter that automatically results in a modified audit opinion","A matter communicated to the audit committee involving especially challenging judgment","A material weakness identified in internal controls over financial reporting","A deficiency that requires the auditor to issue a disclaimer of opinion"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (B): Under PCAOB AS 3101.11, a CAM must meet three criteria: (1) communicated or required to be communicated to the audit committee, (2) related to accounts or disclosures material to the financial statements, and (3) involved especially challenging, subjective, or complex auditor judgment.
Wrong (A): A CAM does not automatically change the type of opinion issued — it is communicated within an unmodified report.
Wrong (C): A material weakness in ICFR is a separate reporting concept under AS 2201, distinct from CAM requirements.
Wrong (D): A CAM does not require a disclaimer; it is an informational communication about significant audit matters.$EXPL$
WHERE id = 327;

-- Q329: Audit Reports [easy/L1]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["A material misstatement has been identified in the financial statements","The auditor wants to highlight a matter appropriately disclosed in the statements","The auditor is unable to obtain sufficient appropriate audit evidence","The client has decided to change its external accounting firm"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (B): Under AU-C 706.06, an emphasis-of-matter paragraph draws attention to a matter that is appropriately presented or disclosed in the financial statements and is fundamental to users'' understanding. Common situations include going concern uncertainties and significant related-party transactions.
Wrong (A): A material misstatement results in a modified (qualified or adverse) opinion, not an emphasis-of-matter paragraph.
Wrong (C): Inability to obtain sufficient evidence is a scope limitation leading to a qualified opinion or disclaimer, not an emphasis paragraph.
Wrong (D): A change in accounting firm is not a financial statement matter requiring an emphasis-of-matter paragraph.$EXPL$
WHERE id = 329;

-- Q332: Audit Reports [hard/L1]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["An adverse opinion on internal controls and a qualified opinion on the financial statements","A disclaimer of opinion on both internal controls and the financial statements","Automatic withdrawal from the engagement by the audit firm","An adverse ICFR opinion, with the financial statement opinion assessed separately"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (D): Under PCAOB AS 2201.90, a material weakness in ICFR requires an adverse opinion on internal control over financial reporting. However, the financial statement opinion is determined separately based on whether the statements are materially misstated. An adverse ICFR opinion can accompany an unmodified financial statement opinion if misstatements were detected and corrected.
Wrong (A): A material weakness does not automatically result in a qualified financial statement opinion; the two opinions are assessed independently.
Wrong (B): A disclaimer applies to scope limitations, not to the identification of a material weakness in ICFR.
Wrong (C): The auditor does not withdraw from an engagement solely because a material weakness is found.$EXPL$
WHERE id = 332;

-- Q335: Audit Reports [easy/L1]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["The balance sheet date of the financial statements under audit","The date on which the engagement letter was originally signed","The date the auditor obtained sufficient appropriate evidence for the opinion","Sixty calendar days after the entity''s balance sheet date"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (C): Under AU-C 700.41, the report date should be no earlier than the date the auditor obtained sufficient appropriate audit evidence to support the opinion, including evidence regarding subsequent events through that date.
Wrong (A): The balance sheet date precedes the completion of audit fieldwork and does not reflect when sufficient evidence was obtained.
Wrong (B): The engagement letter date marks the beginning of the engagement, not the completion of evidence gathering.
Wrong (D): No standard prescribes a fixed number of days after the balance sheet date as the report date; it depends on when sufficient evidence is obtained.$EXPL$
WHERE id = 335;

-- Q338: Review and Compilation [medium/L1]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["A preparation engagement requires the accountant to be independent of the entity","A preparation engagement requires performing inquiry and analytical procedures","A preparation engagement provides limited assurance on the financial statements","No report is issued in a preparation — only a legend appears on each page"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (D): Under AR-C 70.05, a preparation engagement does not result in a report. Instead, each page of the financial statements must include a legend stating no assurance is provided. A compilation under AR-C 80.20 requires a written compilation report.
Wrong (A): Neither a preparation nor a compilation engagement requires independence, though AR-C 80.24 requires independence disclosure in a compilation report.
Wrong (B): Inquiry and analytical procedures are required for review engagements under AR-C 90, not for preparations.
Wrong (C): A preparation engagement provides no assurance whatsoever; limited assurance is the level provided by a review engagement.$EXPL$
WHERE id = 338;

-- Q341: Review and Compilation [medium/L2]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["Convert the review engagement to a full audit of the financial statements","Issue a qualified conclusion in the review engagement report","Withdraw from the review engagement immediately without further action","Perform additional procedures to determine whether material modification is needed"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (D): Under AR-C 90.60–.62, if during a review the accountant becomes aware of information indicating potential material misstatement, the accountant should perform additional procedures sufficient to resolve the matter. These procedures remain within the scope of a review and do not require conversion to an audit.
Wrong (A): Converting to an audit is not required — additional review-level procedures such as revised inquiries or targeted analytics may suffice.
Wrong (B): A qualified conclusion is not the immediate response; the accountant must first perform additional procedures to assess whether modification is actually needed.
Wrong (C): Immediate withdrawal is not appropriate when additional review procedures may resolve the concern.$EXPL$
WHERE id = 341;

-- Q342: Review and Compilation [easy/L1]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["Has obtained reasonable assurance about the financial statements presented","Has not audited or reviewed them and expresses no opinion or conclusion","Provides limited assurance that no material modifications are needed","Has tested the entity''s internal controls over financial reporting"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (B): Under AR-C 80.21, the compilation report explicitly states that the accountant has not audited or reviewed the financial statements and accordingly does not express an opinion or conclusion on them. This language distinguishes compilations from higher-level services.
Wrong (A): Reasonable assurance is the level provided by an audit under AU-C standards, not a compilation engagement.
Wrong (C): Limited assurance is the level provided by a review engagement under AR-C 90, not a compilation.
Wrong (D): Internal control testing is an audit procedure; compilations involve no verification or testing of data.$EXPL$
WHERE id = 342;

-- Q343: Review and Compilation [medium/L2]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["Never permitted under any circumstances regardless of the engagement type","Permitted in a compilation if the omission is disclosed and not intended to mislead","Permitted in both compilation and review engagements under SSARS guidance","Only permitted when the client is a governmental or not-for-profit entity"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (B): Under AR-C 80.22, SSARS permits management to omit substantially all required disclosures in a compilation provided that the omission is clearly indicated in the report and, to the accountant''s knowledge, is not undertaken to mislead financial statement users.
Wrong (A): SSARS explicitly permits disclosure omission in compilations under specified conditions, so a blanket prohibition is incorrect.
Wrong (C): Review engagements require complete disclosures; the omission option is available only for compilations.
Wrong (D): The compilation disclosure omission option applies to all entity types, not exclusively to governmental or not-for-profit entities.$EXPL$
WHERE id = 343;

-- Q344: Review and Compilation [medium/L2]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["Evaluate the reason for the change and determine whether it is appropriate","Automatically agree to the downgrade request to accommodate the client","Refuse the request because engagement downgrades are always prohibited","Issue the originally planned audit report regardless of the request"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (A): Under AR-C 90.67–.69, when a client requests a change from an audit to a review, the accountant must evaluate the reason before agreeing. Legitimate reasons include a change in lender requirements or a misunderstanding about the engagement. Unacceptable reasons include limiting access to information or concealing misstatements.
Wrong (B): Automatically accepting without evaluating the reason fails to meet professional standards requiring the accountant to assess appropriateness.
Wrong (C): Engagement downgrades are not categorically prohibited; they are permitted when the reason is legitimate under AR-C 90.68.
Wrong (D): Issuing an audit report when the client has requested and qualifies for a downgrade would not reflect the agreed-upon engagement terms.$EXPL$
WHERE id = 344;

-- Q350: Attestation Engagements [medium/L1]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["GAAP and IFRS financial reporting framework requirements","The Trust Services Criteria: security, availability, integrity, confidentiality, and privacy","The COSO Internal Control — Integrated Framework exclusively","SEC periodic reporting and disclosure requirements"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (B): Under AT-C 205 and SSAE 18, a SOC 2 report evaluates controls based on the Trust Services Criteria (TSC): security (required for all SOC 2 reports), availability, processing integrity, confidentiality, and privacy. The service organization selects which additional criteria beyond security are relevant.
Wrong (A): GAAP and IFRS are financial reporting frameworks used for preparing financial statements, not criteria for SOC 2 examinations.
Wrong (C): While COSO concepts inform the TSC, SOC 2 specifically uses the Trust Services Criteria, not the COSO framework directly.
Wrong (D): SEC reporting requirements govern public company disclosures and are unrelated to SOC 2 attestation engagements.$EXPL$
WHERE id = 350;

-- Q353: Attestation Engagements [medium/L2]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["File a federal tax return with the IRS for the grant funds received","Have a single audit or program-specific audit of their federal award programs","Obtain a SOC 1 Type 2 report from each federal granting agency","Submit to a PCAOB inspection of their grant compliance procedures"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (B): Under the Single Audit Act and Uniform Guidance (2 CFR 200.501), entities expending $750,000 or more in federal awards in a fiscal year must have a single audit or program-specific audit conducted under GAGAS. The auditor tests compliance with requirements applicable to major federal programs.
Wrong (A): Federal grants do not create a tax filing requirement with the IRS; the Single Audit Act requires an audit of federal programs, not a tax return.
Wrong (C): SOC 1 reports relate to service organization controls for financial reporting, not to compliance with federal grant requirements.
Wrong (D): PCAOB inspections apply to firms auditing public companies, not to entities receiving federal awards.$EXPL$
WHERE id = 353;

-- Q354: Attestation Engagements [hard/L1]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["Only the financial statements of the governmental entity under audit","Internal control, compliance with laws and regulations, and the financial statements","Only compliance with specific federal grant requirements and agreements","The entity''s budget-to-actual performance and variance explanations"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (B): Under GAGAS Chapter 6, Government Auditing Standards require reporting beyond GAAS: the auditor must report on internal control over financial reporting and compliance with laws, regulations, contracts, and grant agreements that could materially affect the financial statements, in addition to the financial statement opinion.
Wrong (A): Reporting only on financial statements omits the additional GAGAS requirements for internal control and compliance reporting.
Wrong (C): Yellow Book audits cover all applicable laws and regulations, not only grant-specific compliance requirements.
Wrong (D): Budget-to-actual reporting is a governmental financial statement presentation issue, not a separate Yellow Book reporting requirement.$EXPL$
WHERE id = 354;

-- Q357: Attestation Engagements [medium/L2]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["Security of systems and data against unauthorized access","Availability of systems for operation and use as committed","Financial reporting accuracy and completeness of transactions","Confidentiality of information designated as confidential"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (C): The five Trust Services Criteria are security, availability, processing integrity, confidentiality, and privacy. Financial reporting accuracy is not a Trust Services Criterion — financial reporting controls are addressed by SOC 1 reports, not SOC 2 reports.
Wrong (A): Security is the common criterion required for all SOC 2 engagements and is a valid Trust Services Criterion.
Wrong (B): Availability is a Trust Services Criterion that addresses whether systems are operational and usable as committed.
Wrong (D): Confidentiality is a Trust Services Criterion addressing protection of information designated as confidential.$EXPL$
WHERE id = 357;

-- Q364: Quality Management [medium/L1]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["PCAOB inspections cover issuer audits while peer review covers non-issuer audits","Peer review is a more rigorous process than PCAOB inspections of audit firms","PCAOB inspections are voluntary for firms that audit public company clients","Peer review applies exclusively to tax practices rather than audit engagements"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (A): The PCAOB conducts mandatory inspections of firms auditing public companies (issuers) under the Sarbanes-Oxley Act. AICPA peer review applies to firms performing audits, reviews, and compilations of private companies (non-issuers). Firms auditing both are subject to both oversight mechanisms.
Wrong (B): PCAOB inspections are generally considered more rigorous due to their scope and enforcement authority; peer review is not more rigorous.
Wrong (C): PCAOB inspections are mandatory for registered firms that audit issuers, not voluntary.
Wrong (D): Peer review covers audit, review, and compilation engagements for non-issuers, not exclusively tax practices.$EXPL$
WHERE id = 364;
