-- Migration: Quality fix -- FAR batch 4 (30 questions)
-- Generated by generate-quality-scaffold.ts
-- Issues: #1 (giveaway longest), #3 (incomplete explanation)

-- Q416: Intangible Assets [easy/L1]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (A): Under IAS 38, paragraph 54 (comparable to ASC 730-10-25-2 under U.S. GAAP), all research phase expenditures must be expensed as incurred. The entity cannot demonstrate that an intangible asset exists that will generate probable future economic benefits during the research phase. Only development costs may be capitalized when all six criteria in IAS 38.57 are met.
Wrong (B): IAS 38 prohibits research phase capitalization regardless of expected profitability. Expected profitability is relevant only to the development phase criteria, not the research phase.
Wrong (C): The six development criteria in IAS 38.57 apply exclusively to development phase costs. Research expenditures are always expensed, even if development criteria could theoretically be met.
Wrong (D): IAS 38 does not permit deferral and amortization of research costs. All research expenditures are expensed immediately with no capitalization or deferral option available.$EXPL$
WHERE id = 416;

-- Q422: Leases [hard/L2]
-- Issues: #1
UPDATE questions SET
  choices = $EXPL$["As a failed sale with the asset retained and proceeds recorded as a financing obligation","As a completed sale with immediate gain recognition and a new operating lease","As an operating lease with the asset removed from the seller-lessee''s balance sheet","As a deferred gain on sale amortized proportionally over the full lease term"]$EXPL$::jsonb
WHERE id = 422;

-- Q427: Leases [medium/L2]
-- Issues: #1
UPDATE questions SET
  choices = $EXPL$["Continue accounting for the lease under its original terms without any adjustment","Reclassify the lease from finance to operating and remeasure at current rates","Recognize all remaining lease payments as an immediate expense in the current period","Reduce the ROU asset proportionately, remeasure the liability, and recognize any difference"]$EXPL$::jsonb
WHERE id = 427;

-- Q436: Debt [medium/L2]
-- Issues: #1
UPDATE questions SET
  choices = $EXPL$["Directly in retained earnings, bypassing both net income and comprehensive income","In a contra-liability account offset against the carrying amount on the balance sheet","Entirely in other comprehensive income each period, with no effect on net income","In net income, except for own credit risk changes which are reported in OCI"]$EXPL$::jsonb
WHERE id = 436;

-- Q441: Equity [medium/L1]
-- Issues: #1
UPDATE questions SET
  choices = $EXPL$["Restricted stock requires liability classification whereas RSUs require equity classification","Restricted stock involves issuing actual shares at grant date while RSUs promise shares upon vesting","RSUs always carry voting rights from the grant date while restricted stock does not","Both instruments are treated identically under ASC 718 with no accounting differences"]$EXPL$::jsonb
WHERE id = 441;

-- Q445: Equity [medium/L2]
-- Issues: #1
UPDATE questions SET
  choices = $EXPL$["Foreign currency translation adjustments upon sale of the foreign entity","Unrealized gains on equity securities held at the reporting date","Revaluation surplus under IFRS upon disposal of the revalued asset","Minimum pension liability adjustments recognized in prior periods"]$EXPL$::jsonb
WHERE id = 445;

-- Q455: Income Taxes [easy/L1]
-- Issues: #1
UPDATE questions SET
  choices = $EXPL$["Warranty costs accrued for book purposes but deducted for tax when paid","Goodwill amortization computed identically for both book and tax purposes","Municipal bond interest that is permanently excluded from taxable income","Installment sales revenue recognized at sale for books but deferred for tax until collected"]$EXPL$::jsonb
WHERE id = 455;

-- Q467: Not-for-Profit Accounting [medium/L1]
-- Issues: #1
UPDATE questions SET
  choices = $EXPL$["A barrier that must be overcome plus a right of return if the barrier is not met","A donor-imposed restriction specifying how the contributed funds must be used","A donor''s expressed preference for the intended purpose of the contribution","An administrative requirement to provide the donor with periodic financial reports"]$EXPL$::jsonb
WHERE id = 467;

-- Q475: Consolidations [medium/L1]
-- Issues: #1
UPDATE questions SET
  choices = $EXPL$["Equity investors lack sufficient equity at risk to finance activities without subordinated support","Equity investors have power to direct the entity''s activities and absorb its expected losses","The entity''s total assets exceed a specified quantitative threshold such as $100 million","The entity is publicly traded on a nationally recognized securities exchange"]$EXPL$::jsonb
WHERE id = 475;

-- Q477: Consolidations [hard/L2]
-- Issues: #1
UPDATE questions SET
  choices = $EXPL$["It continues at its original equity method carrying amount without any adjustment","It is reclassified from equity method investment to available-for-sale securities","It is written down to zero with any remaining value absorbed into goodwill","It is remeasured to fair value with any resulting gain or loss in net income"]$EXPL$::jsonb
WHERE id = 477;

-- Q1103: Trade Receivables [hard/L1]
-- Issues: #1
UPDATE questions SET
  choices = $EXPL$["Vintage analysis tracking historical loss experience by origination year","Probability-of-default method using default and loss-given-default inputs","Incurred loss model that requires losses to be probable before recognition","Discounted cash flow method comparing expected to contractual cash flows"]$EXPL$::jsonb
WHERE id = 1103;

-- Q1117: Special Purpose Frameworks [medium/L3]
-- Issues: #1
UPDATE questions SET
  choices = $EXPL$["Tax-basis income is $36,000 lower because MACRS accelerates cost recovery relative to GAAP straight-line","Tax-basis income is $36,000 higher because MACRS produces smaller depreciation deductions in early years","Both frameworks produce identical Year 1 expense because depreciation methods converge for equipment","Tax-basis depreciation is always $480,000 in Year 1 under full Section 179 expensing"]$EXPL$::jsonb
WHERE id = 1117;

-- Q1119: Special Purpose Frameworks [medium/L1]
-- Issues: #1
UPDATE questions SET
  choices = $EXPL$["All four modifications are acceptable because each has substantial support in accounting literature","Modifications 1, 2, and 4 would make the statements indistinguishable from GAAP, disqualifying the SPF","All four modifications are prohibited because only depreciation is an acceptable cash-basis modification","Any additional modification would automatically convert the statements to a tax-basis framework"]$EXPL$::jsonb
WHERE id = 1119;

-- Q1124: Special Purpose Frameworks [hard/L2]
-- Issues: #1
UPDATE questions SET
  choices = $EXPL$["Each modification is evaluated individually so all three are acceptable if each has substantial support","Accruing trade receivables alone would disqualify the framework as the defining cash-to-accrual difference","Accruing both receivables and payables together would make the statements substantially similar to GAAP","All three modifications are prohibited because only depreciation and long-term debt are permitted"]$EXPL$::jsonb
WHERE id = 1124;

-- Q1142: Contingencies [medium/L4]
-- Issues: #1
UPDATE questions SET
  choices = $EXPL$["Accrue $1,500,000 as the minimum amount within the estimated loss range","Accrue $2,000,000 calculated as the midpoint of the estimated loss range","Disclose the contingency nature and the estimated range of loss in the notes","Neither accrual nor disclosure is required for this level of likelihood"]$EXPL$::jsonb
WHERE id = 1142;

-- Q1889: Statement of Cash Flows [medium/L2]
-- Issues: #1
UPDATE questions SET
  choices = $EXPL$["Both items should be added because all noncash items uniformly increase operating cash flow","The premium amortization should be reclassified from operating activities to financing activities","Depreciation is added back as a noncash charge while premium amortization is subtracted for overstating income","Both items should be subtracted because noncash adjustments always reduce operating cash flow"]$EXPL$::jsonb
WHERE id = 1889;

-- Q1945: Revenue Recognition [medium/L1]
-- Issues: #1
UPDATE questions SET
  choices = $EXPL$["The timing of payments provides a significant financing benefit to either party","Payment is due within 30 days of the transfer of goods or services","The contract includes a volume discount tied to the purchase quantities","The customer elects to pay in advance for administrative convenience"]$EXPL$::jsonb
WHERE id = 1945;

-- Q1947: Revenue Recognition [medium/L2]
-- Issues: #1
UPDATE questions SET
  choices = $EXPL$["Ratably over the full license period on a straight-line basis","At the point in time when control of the license transfers","When the customer first installs and uses the licensed software","At the date the contract is signed by both parties"]$EXPL$::jsonb
WHERE id = 1947;

-- Q1950: Revenue Recognition [medium/L2]
-- Issues: #1
UPDATE questions SET
  choices = $EXPL$["The customer has contractually agreed to pay the specific variable amount","The variable consideration exceeds a 10% threshold of the fixed contract price","The entity has accumulated historical data for at least three reporting years","A significant reversal of cumulative revenue is probable not to occur upon resolution"]$EXPL$::jsonb
WHERE id = 1950;

-- Q1961: Inventory [easy/L1]
-- Issues: #1
UPDATE questions SET
  choices = $EXPL$["Historical cost without any subsequent adjustment for market decline","Lower of cost or net realizable value as required by ASC 330","Net realizable value regardless of the original historical cost paid","Fair value less estimated costs to complete and sell the goods"]$EXPL$::jsonb
WHERE id = 1961;

-- Q1985: Inventory [hard/L1]
-- Issues: #1
UPDATE questions SET
  choices = $EXPL$["Freight-in costs added to the cost layer of goods available","Employee discounts applied as a reduction of recorded sales","Net markups added to the retail value of goods available","Purchase returns reducing the retail value of goods available"]$EXPL$::jsonb
WHERE id = 1985;

-- Q1993: Property, Plant and Equipment [medium/L2]
-- Issues: #1
UPDATE questions SET
  choices = $EXPL$["Expense the full $250,000 as a period repair cost","Capitalize $250,000 and continue depreciating the old roof component","Capitalize $250,000 for the new roof and write off the $40,000 old component","Capitalize only the $210,000 incremental cost above the old book value"]$EXPL$::jsonb
WHERE id = 1993;

-- Q1996: Property, Plant and Equipment [easy/L1]
-- Issues: #1
UPDATE questions SET
  choices = $EXPL$["Ordinary repairs that maintain the asset''s existing operating condition","Repainting the exterior of a building to improve its appearance","Scheduled annual maintenance costs for production equipment upkeep","Replacement of a major component that extends the asset''s useful life"]$EXPL$::jsonb
WHERE id = 1996;

-- Q2001: Property, Plant and Equipment [hard/L2]
-- Issues: #1
UPDATE questions SET
  choices = $EXPL$["Recognize the full $200,000 as a current period expense immediately","Increase the ARO liability by $200,000 undiscounted and debit the related asset","Discount the $200,000 at the current 5% rate and increase both liability and asset","Record the entire $200,000 adjustment directly in other comprehensive income"]$EXPL$::jsonb
WHERE id = 2001;

-- Q2011: Property, Plant and Equipment [medium/L2]
-- Issues: #1
UPDATE questions SET
  choices = $EXPL$["The asset retirement cost capitalized to the well is never depreciated","Over a standard 40-year recovery period using the straight-line method","Expensed immediately in the period the asset retirement obligation is recognized","Over the well''s remaining useful life using a systematic and rational method"]$EXPL$::jsonb
WHERE id = 2011;

-- Q2029: Intangible Assets [hard/L2]
-- Issues: #1
UPDATE questions SET
  choices = $EXPL$["Capitalize as a separate indefinite-lived intangible and test annually for impairment","Amortize as a separate finite-lived intangible over the employees'' expected tenure","Include in goodwill because assembled workforce is not separately recognizable","Expense the full $150,000 immediately in the period of the acquisition"]$EXPL$::jsonb
WHERE id = 2029;

-- Q2067: Leases [medium/L1]
-- Issues: #1
UPDATE questions SET
  choices = $EXPL$["A contract to use specific office space exclusively for three years","A contract for warehouse space where the customer controls access and usage","A contract for exclusive use of a delivery vehicle for two years","A contract for server capacity where the supplier can substitute at any time"]$EXPL$::jsonb
WHERE id = 2067;

-- Q2075: Leases [easy/L2]
-- Issues: #1
UPDATE questions SET
  choices = $EXPL$["Sales-type lease requiring derecognition of the underlying asset from the books","Direct financing lease with a net investment recorded on the balance sheet","Operating lease with the asset retained and rental income recognized straight-line","Finance lease requiring the lessee to record a right-of-use asset on its books"]$EXPL$::jsonb
WHERE id = 2075;

-- Q2100: Debt [medium/L2]
-- Issues: #1
UPDATE questions SET
  choices = $EXPL$["Allocated proportionally between separate debt and equity components at issuance","Recorded entirely as a liability premium and amortized over the bond term","Credited to additional paid-in capital to reflect the value of the conversion feature","Recognized as revenue at issuance because the proceeds exceed the face value"]$EXPL$::jsonb
WHERE id = 2100;

-- Q2122: Equity [medium/L2]
-- Issues: #1
UPDATE questions SET
  choices = $EXPL$["The appropriation sets aside cash in a separate fund for the plant expansion","The appropriation reduces total shareholders'' equity reported on the balance sheet","The appropriation creates a liability that must be reported as a current obligation","The appropriation restricts dividends but does not segregate or set aside any cash"]$EXPL$::jsonb
WHERE id = 2122;
