-- Migration: Quality fix -- BAR batch 7 (30 questions)
-- Generated by generate-quality-scaffold.ts
-- Issues: #1 (giveaway longest), #3 (incomplete explanation)

-- Q3320: Fund-to-Government-Wide Reconciliation [hard/L2]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["Both amounts are reported as revenue and expense on government-wide statements","The new bonds create a liability while the old bonds remain until legally defeased","No adjustment is needed because fund and government-wide treatments are identical","The old bonds are immediately removed from the government-wide balance sheet"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (B): Under GASB Statement No. 65, when a government advance refunds debt, the government-wide statements record the new bonds as a long-term liability while the old bonds remain until legally defeased. The difference between the reacquisition price and the net carrying amount is recognized as a deferred outflow or inflow of resources.
Wrong (A): Bond proceeds and escrow payments are not reported as revenue and expense; they are financing activities on the fund statements and liability adjustments on government-wide statements.
Wrong (C): An adjustment is required because governmental funds report proceeds and payments as other financing sources/uses, while government-wide statements use full accrual.
Wrong (D): The old bonds are not immediately removed; they remain as liabilities until the escrow legally defeases them.$EXPL$
WHERE id = 3320;

-- Q3323: Fund-to-Government-Wide Reconciliation [hard/L2]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["Add the increase in supplies inventory to reconcile to government-wide basis","Subtract the decrease in supplies inventory to reconcile to government-wide basis","Add the net increase because government-wide records supplies as assets until consumed","No adjustment is needed because supplies are treated the same in both statements"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (C): Under GASB Statement No. 34, paragraph 78, when governmental funds use the purchases method, supplies are expensed when purchased. Government-wide statements use the consumption method, expensing supplies when used. A net increase in inventory means fewer supplies were consumed than purchased, so the excess must be added back to reconcile.
Wrong (A): Simply adding the increase is incomplete without recognizing the measurement focus difference between purchases and consumption methods.
Wrong (B): Subtracting a decrease would be the wrong direction; a decrease means more was consumed than purchased.
Wrong (D): Supplies are not treated the same — funds use purchases basis while government-wide uses consumption basis.$EXPL$
WHERE id = 3323;

-- Q3324: Fund-to-Government-Wide Reconciliation [medium/L2]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["Amortized over the bond term using the effective interest method","Reported as other financing sources in the period of issuance","Not recorded in the governmental fund financial statements","Reported as deferred revenue to be recognized over the bond term"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (B): Under GASB Statement No. 34, paragraphs 77-79, bond premiums received at issuance are reported as other financing sources in governmental funds alongside the face amount of the bonds. They are not amortized because governmental funds use the current financial resources measurement focus.
Wrong (A): Amortization over the bond term occurs on the government-wide statements under the economic resources measurement focus, not in governmental funds.
Wrong (C): The premium is recorded in governmental funds — as an other financing source in the issuance period.
Wrong (D): A bond premium is not deferred revenue; it is a financing source recognized immediately in the fund statements.$EXPL$
WHERE id = 3324;

-- Q3327: Interfund Transactions [easy/L1]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["A reciprocal exchange of goods or services between two separate funds","A one-way flow of resources from one fund to another without repayment","A temporary loan between funds that must be repaid within one year","A payment for services rendered by one fund to another at market rates"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (B): Under GASB Statement No. 34, an interfund transfer is a one-way movement of resources between funds without a corresponding return flow of assets, services, or repayment. Transfers are reported as other financing sources in the receiving fund and other financing uses in the providing fund.
Wrong (A): A reciprocal exchange of goods or services describes an interfund service provided and used, not a transfer.
Wrong (C): A temporary loan between funds is an interfund advance or borrowing, which creates receivable and payable balances.
Wrong (D): A payment for services at market rates is an interfund service provided and used, treated like an external transaction.$EXPL$
WHERE id = 3327;

-- Q3329: Interfund Transactions [medium/L2]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["Both are classified as transfers because all interfund flows are nonreciprocal resource movements","The IT payment is a transfer reported below the operating line; the road funding is an operating expenditure","Both are reported as revenues and expenses because GASB treats all interfund activity as quasi-external","The IT payment is revenue/expense (exchange at market rates); the road transfer is other financing sources/uses (nonreciprocal)"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (D): GASB Statement No. 34 distinguishes interfund services provided and used from interfund transfers based on whether a genuine exchange occurs. The IT services payment is exchange-like at market rates, so it is reported as revenue in the General Fund and expense in the Enterprise Fund. The road transfer is nonreciprocal, reported as other financing sources/uses.
Wrong (A): Not all interfund flows are transfers; GASB distinguishes exchange-type services from nonreciprocal transfers.
Wrong (B): This reverses the classification — the IT payment is the exchange transaction reported as revenue/expense, not a transfer.
Wrong (C): GASB does not treat all interfund activity as quasi-external; only genuine exchange transactions receive revenue/expense treatment.$EXPL$
WHERE id = 3329;

-- Q3330: Interfund Transactions [medium/L1]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["Revenue recognized in the fund providing the reimbursement payment","Other financing sources reported below the operating expenditure line","Transfers between the two funds reported as financing activities","A reduction of expenditures or expenses in the fund that is reimbursed"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (D): Under GASB Statement No. 34, an interfund reimbursement occurs when one fund pays for a cost that properly belongs to another fund. The reimbursement reduces expenditures in the fund initially charged (general fund) and records the expenditure in the fund that should bear the cost (special revenue fund).
Wrong (A): Reimbursements are not revenue — they are cost corrections that restore expenditures to the proper fund.
Wrong (B): Other financing sources applies to transfers, not reimbursements that correct misclassified expenditures.
Wrong (C): Reimbursements are distinct from transfers; they correct errors rather than move resources as a policy decision.$EXPL$
WHERE id = 3330;

-- Q3332: Interfund Transactions [easy/L2]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["An expenditure reported in the operating section of the statement","An other financing use reported as a transfer out below the operating line","A liability owed to the debt service fund until settlement occurs","A reduction of revenue offset against the General Fund''s tax collections"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (B): Under GASB Statement No. 34, transfers out are reported as other financing uses on the fund statement of revenues, expenditures, and changes in fund balances. They appear below the operating section and reduce fund balance. The receiving debt service fund reports a corresponding other financing source.
Wrong (A): Transfers are not expenditures; they are classified separately as other financing uses below the excess/deficiency line.
Wrong (C): A transfer is not a liability — it is a completed resource movement, not an obligation to pay.
Wrong (D): Transfers do not reduce revenue; they are a distinct category reported after the excess/deficiency of revenues over expenditures.$EXPL$
WHERE id = 3332;

-- Q3333: Interfund Transactions [easy/L1]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["A transfer out in the General Fund and a transfer in for Capital Projects","Revenue in the Capital Projects Fund and an expenditure in the General Fund","A receivable in the General Fund and a payable in the Capital Projects Fund","An expenditure in the General Fund reported in the operating activity section"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (C): Under GASB Statement No. 34, paragraph 112a, an interfund loan creates reciprocal receivable and payable balances: a ''due from other funds'' in the lending General Fund and a ''due to other funds'' in the borrowing Capital Projects Fund. These are balance sheet items that do not affect revenues or expenditures.
Wrong (A): A transfer implies a permanent one-way resource movement; loans are temporary and must be repaid.
Wrong (B): Loans do not generate revenue or expenditures — they create reciprocal balance sheet accounts.
Wrong (D): An interfund loan is not an expenditure; it is a temporary advance creating an asset in the lending fund.$EXPL$
WHERE id = 3333;

-- Q3335: Interfund Transactions [medium/L2]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["An interfund transfer reported as other financing sources and uses","An interfund reimbursement that corrects a prior period misclassification","An interfund service provided and used, recorded as revenue and expenditure","An interfund loan creating reciprocal receivable and payable balances"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (C): Under GASB Statement No. 34, paragraph 112, when a proprietary fund provides services to other government funds at its normal billing rate, the transaction is classified as an interfund service provided and used. The enterprise fund recognizes revenue and the general fund records an expenditure, mirroring external transaction treatment.
Wrong (A): A transfer is a nonreciprocal one-way resource movement; this transaction involves an exchange of services for payment.
Wrong (B): A reimbursement corrects costs charged to the wrong fund, not an ongoing service arrangement at normal rates.
Wrong (D): An interfund loan involves temporary borrowing, not an exchange of services for payment.$EXPL$
WHERE id = 3335;

-- Q3337: Interfund Transactions [medium/L2]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["Eliminated during the government-wide consolidation process entirely","Reported as an expense of governmental activities on the statement","Reported as revenue of business-type activities on the statement","Reported separately as transfers in and transfers out on the statement"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (D): Under GASB Statement No. 34, paragraph 61, transfers between governmental activities and business-type activities are not eliminated on the government-wide statements because they cross activity boundaries. The transfer is reported as a transfer out in governmental activities and a transfer in for business-type activities.
Wrong (A): Cross-activity transfers are not eliminated; only interfund balances within the same activity type are eliminated during consolidation.
Wrong (B): The transfer is not reclassified as an expense; it retains its character as a transfer on the statement of activities.
Wrong (C): The transfer is not reported as revenue; it is shown as a separate transfer-in line item distinct from program or general revenues.$EXPL$
WHERE id = 3337;

-- Q3339: Interfund Transactions [medium/L2]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["Eliminated during the government-wide consolidation process entirely","Disclosed only in the notes to the financial statements as supplementary detail","Reported as a note receivable and note payable between the two activity types","Reported as an internal balance between governmental and business-type activities"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (D): Under GASB Statement No. 34, paragraph 58, interfund balances between governmental activities and business-type activities are reported as internal balances on the government-wide statement of net position. These balances are not eliminated because they cross activity-type boundaries.
Wrong (A): Cross-activity balances are not eliminated; only balances within the same activity type are eliminated during consolidation.
Wrong (B): The balance is reported on the face of the statement of net position, not solely in the notes.
Wrong (C): The balances are labeled as ''internal balances,'' not as note receivables and payables, which implies external debt instruments.$EXPL$
WHERE id = 3339;

-- Q3340: Interfund Transactions [easy/L2]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["An interfund transfer moving resources permanently to the correct fund","Writing off the overpayment as a miscellaneous expenditure of the period","An interfund reimbursement from the Special Revenue Fund to the General Fund","Recognizing additional revenue in the General Fund to offset the overpayment"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (C): Under GASB Statement No. 34, paragraph 112, an interfund reimbursement restores costs initially charged to the wrong fund. The Special Revenue Fund reimburses the General Fund, reducing the General Fund''s expenditures while recording the cost in the proper fund.
Wrong (A): A transfer is a policy-based nonreciprocal resource movement, not a correction of a misclassified expenditure.
Wrong (B): Writing off the overpayment would leave the cost in the wrong fund and fail to correct the misclassification.
Wrong (D): Recognizing revenue is incorrect because a reimbursement is a cost correction, not an income-generating event.$EXPL$
WHERE id = 3340;

-- Q3341: Interfund Transactions [hard/L2]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["Eliminated to the extent it creates a profit margin above actual cost","Left as reported because internal service funds are self-sustaining entities","Reported as miscellaneous revenue of the internal service fund operations","Charged against the internal service fund''s unrestricted net position"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (A): Under GASB Statement No. 34, paragraph 61, internal service fund charges that exceed actual cost create internal profits that must be eliminated on the government-wide financial statements. The 10% markup inflates both expenses and revenues, which does not represent an arm''s-length external transaction.
Wrong (B): Leaving overcharges as reported would overstate the government''s actual cost of operations on government-wide statements.
Wrong (C): The overcharge is not miscellaneous revenue; it is an internal markup that must be eliminated in consolidation.
Wrong (D): The overcharge is not charged against net position; it is eliminated as an adjustment during the government-wide conversion process.$EXPL$
WHERE id = 3341;

-- Q3343: Interfund Transactions [easy/L1]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["Comply with SEC requirements for municipal financial reporting","Provide transparency about resource flows and interfund balance purposes","Replace the need for presenting individual fund financial statements","Satisfy IRS reporting requirements for tax-exempt government entities"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (B): Under GASB Statement No. 38, note disclosures of interfund activity provide transparency about the purpose of transfers, balances due to and from other funds, and the nature of significant interfund transactions. This helps financial statement users understand resource flows between funds.
Wrong (A): SEC requirements apply to publicly traded companies, not state and local governments; GASB sets government reporting standards.
Wrong (C): Note disclosures supplement fund financial statements; they do not replace the requirement to present individual fund statements.
Wrong (D): IRS reporting requirements are unrelated to GASB''s note disclosure standards for interfund activity.$EXPL$
WHERE id = 3343;

-- Q3344: Interfund Transactions [medium/L1]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["An interfund service provided and used at approximate market value","An interfund transfer representing a nonreciprocal resource movement","An interfund reimbursement correcting a prior misclassified expenditure","An interfund loan requiring future repayment to the providing fund"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (A): Under GASB Statement No. 34, paragraph 112, what was previously called a quasi-external transaction is now classified as an interfund service provided and used. These transactions involve one fund providing services to another at rates approximating fair market value, treated as revenue and expenditure.
Wrong (B): A transfer is a nonreciprocal one-way movement of resources; this transaction involves an exchange of IT services for payment.
Wrong (C): A reimbursement corrects costs charged to the wrong fund, not an ongoing service arrangement at market rates.
Wrong (D): An interfund loan involves temporary borrowing with repayment, not a service exchange.$EXPL$
WHERE id = 3344;

-- Q3345: Interfund Transactions [medium/L2]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["The transfer is eliminated during the government-wide consolidation process","It is reported as an expense of governmental activities on the statement","Governmental activities shows transfers out and business-type shows transfers in","It is reported as program revenue of the business-type activities column"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (C): Under GASB Statement No. 34, paragraph 61, transfers between governmental and business-type activities are not eliminated on the government-wide statements. Governmental activities report transfers out of $1,000,000 (reducing its change in net position) and business-type activities report transfers in of $1,000,000 (increasing its change in net position).
Wrong (A): Cross-activity transfers are not eliminated; they are preserved to show resource flows between the two activity types.
Wrong (B): The transfer is not reclassified as an expense; it retains its separate character as a transfer on the statement of activities.
Wrong (D): A subsidy transfer is not program revenue; program revenue must be directly associated with a specific program or function.$EXPL$
WHERE id = 3345;

-- Q3349: Interfund Transactions [easy/L1]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["Unusual and should be investigated by the external auditor","A routine transfer commonly used to fund annual debt service payments","An indication of fiscal distress requiring additional note disclosure","Required to be reported as a special item on the financial statements"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (B): Under GASB Statement No. 34, recurring transfers from the General Fund to a debt service fund are routine government financial management. They move tax revenues and other general resources to the fund designated for bond principal and interest payments, and are common practice.
Wrong (A): Annual transfers to debt service funds are expected and routine, not unusual transactions requiring investigation.
Wrong (C): Routine debt service transfers are standard practice and do not indicate fiscal distress.
Wrong (D): Recurring transfers are not special items; special items are unusual and within management''s control under GASB standards.$EXPL$
WHERE id = 3349;

-- Q3350: Interfund Transactions [easy/L2]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["As revenue in the receiving fund and expenditures in the providing fund","In the notes to the financial statements only, not on the face","As a direct adjustment to fund balance without flowing through the statement","Below the excess/deficiency line as other financing sources or uses"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (D): Under GASB Statement No. 34, interfund transfers are reported below the line showing excess (deficiency) of revenues over expenditures. They are classified as other financing sources (transfers in) or other financing uses (transfers out), distinguishing them from operating activity.
Wrong (A): Transfers are not revenues or expenditures; they are reported separately as other financing sources/uses.
Wrong (B): Transfers appear on the face of the fund financial statements, not solely in the notes.
Wrong (C): Transfers flow through the statement as other financing sources/uses before reaching the net change in fund balance.$EXPL$
WHERE id = 3350;

-- Q3361: Stock Compensation and Business Combinations [medium/L1]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["Liability awards remeasured at fair value each reporting period","Equity awards measured only at the grant date fair value","Revenue recognized over the three-year vesting service period","Off-balance-sheet items disclosed only in the financial statement notes"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (A): Under ASC 718, cash-settled SARs are liability-classified awards. The liability is remeasured at fair value each reporting period until settlement, with changes recognized as compensation expense. This differs from equity-classified awards measured only at the grant date.
Wrong (B): Equity classification applies to share-settled awards, not cash-settled SARs that create an obligation to pay cash.
Wrong (C): Stock compensation is an expense, not revenue; SARs create compensation cost recognized over the vesting period.
Wrong (D): Cash-settled SARs must be recognized as liabilities on the balance sheet, not disclosed off-balance-sheet.$EXPL$
WHERE id = 3361;

-- Q3363: Stock Compensation and Business Combinations [medium/L2]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["Full fair value of the options recognized over the service period","Zero because the performance condition is not yet probable of achievement","Half the fair value as a conservative estimate of probable achievement","The intrinsic value of the options at the end of the reporting period"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (B): Under ASC 718, when a performance condition is not probable of achievement, no compensation expense is recognized. Once the condition becomes probable, cumulative catch-up expense is recognized for the elapsed portion of the service period. Performance conditions affect the number of awards expected to vest.
Wrong (A): Full fair value recognition requires that the performance condition be probable; expense is deferred until probability is established.
Wrong (C): ASC 718 does not allow a conservative partial estimate; it is an all-or-nothing assessment based on probability of achievement.
Wrong (D): Stock options with performance conditions are measured at grant-date fair value, not intrinsic value at period end.$EXPL$
WHERE id = 3363;

-- Q3365: Stock Compensation and Business Combinations [medium/L2]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["Only the Black-Scholes model without any adjustment to term inputs","The vesting period only as the expected term for option valuation","The contractual term only as the expected term for option valuation","The simplified method using the midpoint between vesting date and contractual term"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (D): Under SEC Staff Accounting Bulletin guidance and ASC 718, the simplified method estimates expected term as (vesting period + contractual term) / 2. This is available when a company lacks sufficient historical exercise data. For example, options vesting in 4 years with a 10-year term yield an expected term of 7 years.
Wrong (A): Black-Scholes is a pricing model, not a method for estimating expected term; expected term is an input to the model.
Wrong (B): Using only the vesting period would underestimate the expected term, as employees typically hold options beyond the vesting date.
Wrong (C): Using only the contractual term would overestimate expected term, as employees rarely hold options until expiration.$EXPL$
WHERE id = 3365;

-- Q3367: Stock Compensation and Business Combinations [hard/L2]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["The contingency is assessed as remote under the ASC 450 probability threshold","The fair value of the contingent liability can be determined at acquisition date","Only after the contingency is fully resolved through settlement or judgment","Contingent liabilities are never recognized separately in a business combination"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (B): Under ASC 805, contingent liabilities assumed in a business combination are recognized at fair value at the acquisition date if fair value can be determined during the measurement period. This is a lower threshold than ASC 450, which generally requires probability of loss for recognition.
Wrong (A): ASC 805 does not use the remote/probable framework from ASC 450; fair value determinability is the recognition criterion.
Wrong (C): Waiting for resolution is not required; ASC 805 requires recognition at acquisition date when fair value is determinable.
Wrong (D): Contingent liabilities are recognized in business combinations when fair value can be measured, unlike the general ASC 450 framework.$EXPL$
WHERE id = 3367;

-- Q3371: Advanced Consolidations [medium/L2]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["Proceeds minus the original purchase price paid at acquisition date","Proceeds minus the subsidiary''s book value of equity at date of sale","Fair value of proceeds minus the fair value of net assets retained","Proceeds minus the carrying amount of the investment on an equity method basis"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (D): The gain or loss on disposal of a subsidiary equals proceeds received minus the carrying amount of the parent''s investment at the disposal date on an equity method basis, including unamortized fair value adjustments and goodwill. This reflects the parent''s net interest in the subsidiary.
Wrong (A): The original purchase price ignores subsequent equity method adjustments, share of earnings, dividends, and amortization of basis differences.
Wrong (B): The subsidiary''s book value of equity does not include fair value adjustments and goodwill recognized by the parent at acquisition.
Wrong (C): This formula conflates fair value measurement with carrying amount; the investment is measured at its equity method carrying amount, not remeasured to fair value.$EXPL$
WHERE id = 3371;

-- Q3373: Advanced Consolidations [medium/L1]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["Other comprehensive income accumulated in the equity section","Current period earnings on the consolidated income statement","An adjustment to goodwill from the foreign subsidiary acquisition","A separate liability on the consolidated balance sheet"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (A): Under ASC 830, translation adjustments arising from translating a foreign subsidiary''s financial statements from its functional currency to the reporting currency are reported in other comprehensive income. They accumulate in equity as cumulative translation adjustments (CTA) and are reclassified to earnings upon sale or liquidation.
Wrong (B): Translation adjustments bypass current period earnings and are reported in other comprehensive income until disposal of the subsidiary.
Wrong (C): Translation adjustments are not recorded as goodwill adjustments; goodwill is translated at the current exchange rate with differences flowing to CTA.
Wrong (D): Translation adjustments are an equity component, not a liability; they represent unrealized effects of exchange rate changes.$EXPL$
WHERE id = 3373;

-- Q3375: Derivatives and Hedging [medium/L2]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["Can designate the hedge retroactively to the inception date","Cannot apply hedge accounting and must report all fair value changes in earnings","Must wait until the next fiscal year to formally designate the hedge","Can apply hedge accounting after a mandatory 30-day waiting period"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (B): Under ASC 815, hedge accounting requires formal designation and documentation at inception of the hedge relationship. If the entity fails to designate at inception, hedge accounting cannot be applied retroactively. All changes in the derivative''s fair value are recognized in current earnings.
Wrong (A): Retroactive designation is not permitted; ASC 815 requires contemporaneous documentation at inception.
Wrong (C): There is no next-fiscal-year waiting provision; the entity may designate a new hedge relationship prospectively at any time with proper documentation.
Wrong (D): ASC 815 contains no 30-day waiting period; designation must occur at inception or not at all for that specific hedge relationship.$EXPL$
WHERE id = 3375;

-- Q3377: Derivatives and Hedging [hard/L2]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["Reclassified to earnings immediately upon discontinuation of hedge accounting","Written off against retained earnings as a prior period adjustment","Reversed against the derivative''s fair value on the balance sheet","Remain in AOCI and reclassified to earnings when the forecasted transaction occurs"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (D): Under ASC 815, when a cash flow hedge is discontinued because it is no longer effective but the forecasted transaction is still expected to occur, amounts previously recorded in AOCI remain there. They are reclassified to earnings in the same period(s) the forecasted transaction affects earnings.
Wrong (A): Immediate reclassification would only occur if the forecasted transaction is no longer expected to occur, which is not the case here.
Wrong (B): AOCI amounts from discontinued hedges are not written off against retained earnings; they follow the forecasted transaction timing.
Wrong (C): The AOCI balance is not reversed against the derivative; it remains in equity until the forecasted transaction affects earnings.$EXPL$
WHERE id = 3377;

-- Q3380: State and Local Government Reporting [easy/L2]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["Long-term liabilities reported only on the government-wide financial statements","Short-term liabilities reported in the governmental fund receiving the proceeds","Off-balance-sheet financing disclosed only in the notes to the statements","Deferred revenue recognized over the period until tax collections arrive"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (B): Tax anticipation notes are short-term borrowings expected to be repaid from tax collections within the current fiscal period. Because they mature within the current period, they meet the current financial resources measurement focus and are reported as fund liabilities in governmental funds.
Wrong (A): Because these notes mature within the current period, they are not classified as long-term debt; they appear in the fund statements as current liabilities.
Wrong (C): Tax anticipation notes are recognized on the balance sheet as liabilities, not treated as off-balance-sheet financing.
Wrong (D): Borrowing proceeds are not deferred revenue; they create a liability that will be repaid from future tax collections.$EXPL$
WHERE id = 3380;

-- Q3381: State and Local Government Reporting [hard/L1]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["A state, general purpose local, or special purpose government meeting three criteria","Any government entity that receives and distributes federal funding to subrecipients","Only state-level governments that issue general obligation bonds to investors","Any public entity that collects property taxes from residents within its jurisdiction"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (A): Under GASB Statement No. 14, a primary government is a state government, general purpose local government, or special purpose government that has a separately elected governing body, is legally separate, and is fiscally independent. All three criteria must be met for special purpose governments to qualify.
Wrong (B): Receiving and distributing federal funding does not define a primary government; the definition centers on governance, legal separation, and fiscal independence.
Wrong (C): Primary governments include cities, counties, and qualifying special purpose governments — not only state-level entities that issue bonds.
Wrong (D): Collecting property taxes is not sufficient; a primary government must have an elected governing body, legal separation, and fiscal independence.$EXPL$
WHERE id = 3381;

-- Q3382: Internal-Use Software and Cloud Computing [medium/L2]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["Always five years matching the initial contract term exactly","Ten years by default unless a shorter period is justified","The useful life of the underlying technology platform being hosted","The term of the hosting arrangement including reasonably certain renewals"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (D): Under ASU 2018-15, capitalized implementation costs for a cloud computing service contract are amortized over the term of the hosting arrangement, including periods covered by renewal options that are reasonably certain to be exercised. This aligns cost recognition with the period of benefit.
Wrong (A): The amortization period is not automatically five years; it depends on the hosting arrangement term including reasonably certain renewals, which may differ from the initial contract.
Wrong (B): There is no default ten-year amortization period under ASU 2018-15; the term is based on the specific hosting arrangement.
Wrong (C): The useful life of the underlying technology is irrelevant; SaaS implementation costs follow the hosting arrangement term, not the technology''s lifespan.$EXPL$
WHERE id = 3382;

-- Q3383: Internal-Use Software and Cloud Computing [easy/L2]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["Expensed as incurred because training costs are never capitalizable","Capitalized as an implementation cost during the application development stage","Deferred until the system go-live date and then amortized over its life","Offset against subscription fees to reduce the net hosting arrangement cost"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (A): Under ASU 2018-15 and ASC 350-40, training costs are always expensed as incurred regardless of when they occur during the project lifecycle. Training does not contribute to the development or configuration of the software and therefore does not qualify for capitalization.
Wrong (B): Training costs are explicitly excluded from capitalizable implementation costs, even when incurred during the application development stage.
Wrong (C): Deferring training costs is not permitted; they must be expensed when incurred, not accumulated for later amortization.
Wrong (D): Training costs cannot be offset against subscription fees; they are a separate expense recognized in the period incurred.$EXPL$
WHERE id = 3383;
