-- Migration: Quality fix -- REG batch 14 (30 questions)
-- Generated by generate-quality-scaffold.ts
-- Issues: #1 (giveaway longest), #3 (incomplete explanation)

-- Q2584: Property Transactions: Gains/Losses [easy/L2]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (B): When Section 1231 losses exceed gains, the net result is an ordinary loss under IRC Section 1231(a). Linda''s net is $50,000 - $65,000 = ($15,000), treated as a $15,000 ordinary loss fully deductible against other income.
Wrong (A): A long-term capital loss would apply only if the net Section 1231 result were a gain; net Section 1231 losses are ordinary, not capital.
Wrong (C): Short-term capital loss treatment does not apply to Section 1231 property regardless of the net outcome.
Wrong (D): The gains and losses are netted to produce a single $15,000 result, not reported separately as $65,000 and $50,000.$EXPL$
WHERE id = 2584;

-- Q2585: Property Transactions: Gains/Losses [hard/L2]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (B): Tony''s adjusted basis is $350,000 - $100,000 = $250,000, producing a $250,000 total gain. Under IRC Section 1250, ordinary recapture applies only to depreciation in excess of straight-line. Since only straight-line was claimed, Section 1250 ordinary recapture is $0 and the $100,000 of straight-line depreciation is unrecaptured Section 1250 gain taxed at a maximum 25% rate.
Wrong (A): Treating $100,000 as ordinary recapture confuses Section 1245 full recapture with Section 1250, which only recaptures excess depreciation over straight-line.
Wrong (C): Splitting the depreciation 50/50 between ordinary and unrecaptured has no basis in the Code when only straight-line depreciation was claimed.
Wrong (D): Only the $100,000 of depreciation is unrecaptured Section 1250 gain, not the entire $250,000 total gain.$EXPL$
WHERE id = 2585;

-- Q2586: Property Transactions: Gains/Losses [medium/L1]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (D): Under IRC Section 1091, when a taxpayer sells stock at a loss and buys substantially identical stock within 30 days before or after the sale, the loss is disallowed. However, the disallowed loss is added to the basis of the replacement stock, preserving the economic loss for future recognition.
Wrong (A): The loss is not permanently disallowed; it is deferred by adding it to the replacement stock''s basis.
Wrong (B): The wash sale rule applies only to losses, not gains, so this statement reverses the rule entirely.
Wrong (C): The taxpayer purchased replacement stock 20 days after the sale, which is within the 30-day window, so the rule applies.$EXPL$
WHERE id = 2586;

-- Q2587: Property Transactions: Gains/Losses [easy/L2]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (A): Amy''s adjusted basis is $35,000 - $30,000 = $5,000, producing a $3,000 gain ($8,000 - $5,000). Under IRC Section 1245, gain on depreciable personal property is ordinary income to the extent of all prior depreciation. Since the $3,000 gain is within the $30,000 depreciation claimed, the entire gain is Section 1245 ordinary income.
Wrong (B): Section 1245 recapture takes priority over Section 1231 treatment; the gain must first be characterized as ordinary income.
Wrong (C): Amy has a gain, not a loss, because the sale price of $8,000 exceeds her $5,000 adjusted basis.
Wrong (D): Long-term capital gain treatment is unavailable because Section 1245 recapture converts the gain to ordinary income.$EXPL$
WHERE id = 2587;

-- Q2588: Property Transactions: Gains/Losses [medium/L2]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (A): Greg''s adjusted basis is $400,000 and he sells for $380,000, resulting in a $20,000 loss. Under IRC Section 1231, losses on business property held more than one year are treated as ordinary losses when the net Section 1231 result is a loss. No depreciation recapture applies on a loss transaction.
Wrong (B): Section 1231 losses are ordinary losses, not long-term capital losses, giving the taxpayer more favorable treatment.
Wrong (C): Unrecaptured Section 1250 gain applies only when there is a gain on the sale, not a loss.
Wrong (D): Greg realized a $20,000 loss ($380,000 - $400,000), so a gain or loss must be recognized.$EXPL$
WHERE id = 2588;

-- Q2589: Property Transactions: Gains/Losses [easy/L2]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (B): Under IRC Section 1245, gain on depreciable personal property is recaptured as ordinary income to the extent of all depreciation previously allowed or allowable. This is full recapture, covering both straight-line and accelerated depreciation.
Wrong (A): Section 1245 recaptures all prior depreciation, not just the current year''s amount.
Wrong (C): Section 1245 recaptures all depreciation methods, not only straight-line; that limitation applies to Section 1250 for real property.
Wrong (D): This describes the Section 1250 concept of excess depreciation recapture, not the broader Section 1245 full recapture rule.$EXPL$
WHERE id = 2589;

-- Q2590: Property Transactions: Gains/Losses [hard/L2]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (A): Building: adjusted basis = $800,000 - $200,000 = $600,000; gain = $600,000. With straight-line depreciation only, Section 1250 ordinary recapture is $0 (the $200,000 is unrecaptured Section 1250 gain at 25% max rate, not ordinary). Furniture (Section 1245): adjusted basis = $100,000 - $70,000 = $30,000; gain = $30,000, all ordinary recapture. Total ordinary income = $0 + $30,000 = $30,000.
Wrong (B): The $200,000 of building depreciation is unrecaptured Section 1250 gain taxed at 25%, not ordinary income under Section 1250.
Wrong (C): This incorrectly adds the building''s $200,000 unrecaptured gain to the furniture''s $30,000 ordinary recapture as if both were ordinary.
Wrong (D): This overstates ordinary income by treating the building''s entire $600,000 gain as ordinary recapture.$EXPL$
WHERE id = 2590;

-- Q2591: Property Transactions: Gains/Losses [medium/L2]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (A): Henry''s gain is $150,000 - $110,000 = $40,000. Under IRC Section 1222, property held for 8 months (not more than one year) produces a short-term capital gain. Short-term capital gains are taxed at the taxpayer''s ordinary income tax rates rather than preferential rates.
Wrong (B): Long-term capital gain treatment requires a holding period of more than one year; 8 months does not qualify.
Wrong (C): Section 1231 applies only to property used in a trade or business, not investment property such as land held for appreciation.
Wrong (D): The gain is a short-term capital gain, not ordinary income; capital gain characterization applies to investment assets.$EXPL$
WHERE id = 2591;

-- Q2592: Property Transactions: Gains/Losses [hard/L2]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (A): Section 1231 gains of $80,000 equal Section 1231 losses of $80,000, producing a net result of $0. Under IRC Section 1231(c), the five-year lookback rule applies only when there is a net Section 1231 gain. Since the net is zero, the $10,000 of prior unrecaptured losses remains tracked for the remaining lookback period.
Wrong (B): The lookback rule recharacterizes net gains as ordinary income, not the other way around, and only applies when a net gain exists.
Wrong (C): Section 1231 gains and losses are netted together first; they are not separately characterized as LTCG and ordinary loss.
Wrong (D): No net gain exists to trigger recharacterization under the lookback rule, so no $10,000 amount is recognized.$EXPL$
WHERE id = 2592;

-- Q2597: Like-Kind Exchanges [easy/L1]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (D): Under Treas. Reg. Section 1.1031(k)-1(g)(4), a qualified intermediary facilitates a deferred like-kind exchange by holding the sale proceeds from the relinquished property and using them to acquire the replacement property on behalf of the taxpayer. This prevents the taxpayer from having actual or constructive receipt of funds.
Wrong (A): Appraising properties for fair market value is the role of a licensed appraiser, not a qualified intermediary.
Wrong (B): Providing tax advice is the role of a tax advisor or CPA, not the qualified intermediary who handles the transactional mechanics.
Wrong (C): A qualified intermediary is a private facilitator engaged by the taxpayer, not an IRS representative.$EXPL$
WHERE id = 2597;

-- Q2603: Like-Kind Exchanges [medium/L2]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (C): Under IRC Sec. 1031(b) and Treas. Reg. Sec. 1.1031(b)-1(c), when both parties transfer mortgaged properties, the mortgages are netted. Mortgage relief of $150,000 minus the $90,000 mortgage assumed equals $60,000 in net boot received. Only this net amount determines recognized gain.
Wrong (A): $150,000 is the gross mortgage relief without netting the $90,000 mortgage assumed, which offsets the boot effect.
Wrong (B): $90,000 is the mortgage assumed, not the net boot; the netting calculation produces $60,000.
Wrong (D): $240,000 incorrectly adds the two mortgages together rather than netting them as required.$EXPL$
WHERE id = 2603;

-- Q2604: Like-Kind Exchanges [medium/L2]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (C): Under IRC Section 1031(f), if a like-kind exchange occurs between related parties and either party disposes of the property within two years, the exchange is disqualified and deferred gain must be recognized. This anti-abuse rule prevents related parties from using exchanges to cash out at deferred rates.
Wrong (A): An office building for raw land is a valid exchange because both are real property held for investment under Section 1031.
Wrong (B): Using a qualified intermediary for a deferred exchange is the standard mechanism authorized by Treas. Reg. Section 1.1031(k)-1(g)(4).
Wrong (D): A rental house for a commercial warehouse qualifies because both are real property held for business or investment use.$EXPL$
WHERE id = 2604;

-- Q2605: Like-Kind Exchanges [hard/L2]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (B): Under IRC Section 1031(d), the basis of replacement property equals the old basis ($175,000) plus recognized gain ($25,000) minus boot received ($25,000), which nets to $175,000. Rachel''s realized gain is $100,000 ($275,000 - $175,000), and recognized gain is the lesser of realized gain or boot received ($25,000).
Wrong (A): $250,000 would be the FMV of the replacement property, but Section 1031(d) uses a substituted basis, not fair market value.
Wrong (C): $200,000 incorrectly adds the $25,000 boot to the old basis without subtracting it, double-counting the boot.
Wrong (D): $225,000 appears to subtract boot from FMV rather than applying the substituted basis formula under Section 1031(d).$EXPL$
WHERE id = 2605;

-- Q2606: Like-Kind Exchanges [easy/L2]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (C): IRC Section 1031 does not require a simultaneous exchange. Deferred exchanges are explicitly permitted under Treas. Reg. Section 1.1031(k)-1, provided the 45-day identification and 180-day closing deadlines are met and a qualified intermediary holds the proceeds.
Wrong (A): The like-kind requirement (real property for real property) is a valid statutory requirement under Section 1031(a)(1).
Wrong (B): The business-use or investment-use requirement is a valid requirement; personal-use property does not qualify under Section 1031.
Wrong (D): Avoiding constructive receipt of proceeds is a genuine requirement; actual or constructive receipt disqualifies the exchange.$EXPL$
WHERE id = 2606;

-- Q2607: Like-Kind Exchanges [hard/L2]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (C): Under IRC Sec. 1031(b), recognized gain equals the lesser of realized gain or net boot received. Tom''s realized gain is ($140,000 + $20,000) - $90,000 - $5,000 = $65,000. Boot received is $20,000 cash reduced by $5,000 exchange expenses, yielding net boot of $15,000. The lesser of $65,000 or $15,000 is $15,000.
Wrong (A): $70,000 ignores the exchange expenses and overstates the realized gain calculation.
Wrong (B): $20,000 is gross boot before subtracting the $5,000 exchange expenses that reduce net boot.
Wrong (D): $0 would apply only if no boot were received, but Tom received $20,000 in cash.$EXPL$
WHERE id = 2607;

-- Q2608: Like-Kind Exchanges [medium/L2]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (B): Under IRC Section 1031(h), real property located in the United States and real property located outside the United States are not like-kind. A domestic-for-foreign real property exchange does not qualify for tax deferral, regardless of property type or use.
Wrong (A): Although both properties are real property held for investment, Section 1031(h) prohibits cross-border exchanges between U.S. and foreign real property.
Wrong (C): Using a qualified intermediary does not overcome the Section 1031(h) geographic restriction on domestic-foreign exchanges.
Wrong (D): Section 1031 does apply to rental property; the disqualification here is the cross-border nature of the exchange, not the property type.$EXPL$
WHERE id = 2608;

-- Q2609: Like-Kind Exchanges [hard/L1]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (D): Under Treas. Reg. Section 1.1031(k)-1(c)(4), the three-property rule allows identification of up to three properties without value limits. Janet identified four, exceeding this rule. However, the 200% rule permits identifying more than three properties if their total FMV does not exceed 200% of the relinquished property''s FMV.
Wrong (A): Identifying more than three properties does not automatically fail the exchange; the 200% rule and 95% rule provide alternative qualification paths.
Wrong (B): There are limits on identification; the three-property rule, 200% rule, and 95% rule each impose specific constraints.
Wrong (C): Simply acquiring one property within 180 days is not sufficient; the identification rules must also be satisfied at the time of identification.$EXPL$
WHERE id = 2609;

-- Q2610: Like-Kind Exchanges [easy/L2]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (C): Under IRC Section 1031(a), an apartment building held for rental income exchanged for raw land held for investment qualifies because both are real property held for business use or investment. All real property is like-kind to all other real property regardless of improvement status.
Wrong (A): A personal automobile is personal-use property and does not qualify under Section 1031, which requires business or investment use.
Wrong (B): Stocks and securities are specifically excluded from Section 1031 treatment under IRC Section 1031(a)(2)(B).
Wrong (D): Inventory is specifically excluded from Section 1031 treatment under IRC Section 1031(a)(2)(A).$EXPL$
WHERE id = 2610;

-- Q2611: Like-Kind Exchanges [medium/L2]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (B): Under IRC Section 1031(d), in a like-kind exchange with no boot, the replacement property takes a substituted basis equal to the relinquished property''s adjusted basis of $120,000. Under IRC Section 1223(1), the holding period of the relinquished property tacks onto the replacement, so Ed''s 3 years carry over.
Wrong (A): The basis is $120,000 (substituted), not $200,000 (FMV), and the holding period tacks rather than starting fresh.
Wrong (C): The basis of $120,000 is correct, but the holding period tacks under Section 1223(1) rather than starting fresh on the exchange date.
Wrong (D): The basis is $120,000 (substituted), not $200,000 (FMV); using FMV as basis applies only to taxable purchases.$EXPL$
WHERE id = 2611;

-- Q2612: Like-Kind Exchanges [hard/L2]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (B): Under IRC Section 1031(d), Sandra''s replacement basis equals her old basis of $250,000. Her realized gain is $400,000 - $250,000 = $150,000, but because the full value was reinvested through the QI in like-kind property plus improvements under Treas. Reg. Section 1.1031(k)-1, no boot was received and recognized gain is $0.
Wrong (A): $400,000 is the FMV of the replacement property, not the substituted basis; Section 1031(d) requires carrying over the old basis when no gain is recognized.
Wrong (C): $300,000 is the purchase price before improvements and does not reflect the Section 1031(d) substituted basis calculation.
Wrong (D): $350,000 does not correspond to any valid basis calculation under the Section 1031(d) formula.$EXPL$
WHERE id = 2612;

-- Q2613: Like-Kind Exchanges [medium/L2]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (D): Under IRC Section 1031(f), if either party to a related-party like-kind exchange disposes of the exchanged property within two years, the deferred gain is recognized. Carl''s sale at 14 months triggers Bob''s recognition of the $80,000 deferred gain ($180,000 FMV - $100,000 basis).
Wrong (A): The two-year rule applies to both parties; if either Bob or Carl disposes within two years, the exchange is disqualified.
Wrong (B): Carl does not pay Bob''s gain; the rule requires the original exchanger (Bob) to recognize his own deferred gain.
Wrong (C): Bob does not lose his basis; instead, he must recognize the previously deferred gain as if the exchange never qualified.$EXPL$
WHERE id = 2613;

-- Q2614: Like-Kind Exchanges [medium/L2]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (D): Under IRC Section 1031(a)(3)(A), replacement property must be identified in writing within 45 calendar days after the relinquished property is transferred. The 45th day after March 1 is April 15, 2026, which is the strict deadline per Treas. Reg. Section 1.1031(k)-1(c)(2).
Wrong (A): March 31 is only 30 days after the transfer date, not the required 45 calendar days.
Wrong (B): August 28 is the 180-day exchange completion deadline, not the 45-day identification deadline.
Wrong (C): April 30 is 60 days after the transfer, which exceeds the strict 45-day identification period.$EXPL$
WHERE id = 2614;

-- Q2617: Individual Taxation: Income [easy/L1]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (D): Interest on a savings account at a commercial bank is fully taxable and included in gross income under IRC Section 61(a)(4). All interest income is taxable unless specifically excluded by statute.
Wrong (A): Municipal bond interest is generally excluded from gross income under IRC Section 103 and would not be reported on Schedule B.
Wrong (B): U.S. Treasury bond interest is taxable for federal purposes but exempt from state income tax; the question asks about federal gross income inclusion.
Wrong (C): Qualified private activity bond interest is typically excluded for regular tax purposes under Section 103, though it may be a preference item for AMT.$EXPL$
WHERE id = 2617;

-- Q2623: Individual Taxation: Income [medium/L2]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (C): Under IRC Sec. 86(a)(2), married taxpayers filing jointly with provisional income at or above the $44,000 second-tier threshold may have up to 85% of Social Security benefits included in gross income. Henry and Martha''s provisional income of $44,000 reaches this threshold, subjecting up to 85% of benefits to taxation.
Wrong (A): 0% inclusion applies only when provisional income is below the first-tier threshold of $32,000 for MFJ filers.
Wrong (B): 50% is the maximum inclusion under the first-tier threshold of $32,000 under Section 86(a)(1), not the second tier.
Wrong (D): Social Security benefits are never 100% taxable; the statutory maximum under Section 86 is 85%.$EXPL$
WHERE id = 2623;

-- Q2624: Individual Taxation: Income [medium/L2]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (A): Under IRC Sec. 215 and Section 71 (pre-TCJA), for divorce agreements executed before January 1, 2019, alimony is deductible by the payor and includible in the recipient''s gross income. David and Susan''s 2016 decree falls under these pre-TCJA rules.
Wrong (B): This describes the post-TCJA rule for agreements executed after December 31, 2018, which does not apply to a 2016 decree.
Wrong (C): Under pre-TCJA rules, alimony is both deductible by the payor and taxable to the recipient; it cannot be deductible without being taxable.
Wrong (D): This reverses the pre-TCJA treatment; alimony under a pre-2019 agreement is deductible by the payor, not just taxable to the recipient.$EXPL$
WHERE id = 2624;

-- Q2625: Individual Taxation: Income [easy/L2]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (B): Under IRC Section 71 as amended by TCJA Section 11051, alimony payments under divorce agreements executed after December 31, 2018 are not deductible by the payor and not included in the recipient''s gross income. The 2026 divorce falls under this post-TCJA rule.
Wrong (A): This describes the pre-TCJA rule for agreements executed before 2019; post-2018 agreements eliminate both the deduction and income inclusion.
Wrong (C): Under post-TCJA rules, alimony is neither deductible nor taxable; a deduction without income inclusion is not how the statute operates.
Wrong (D): Under post-TCJA rules, alimony is not taxable to the recipient and not deductible by the payor; this choice incorrectly includes taxation.$EXPL$
WHERE id = 2625;

-- Q2626: Individual Taxation: Income [medium/L2]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (A): Under IRC Section 61(a), gambling winnings of $10,000 are fully includible in gross income. Under IRC Section 165(d), gambling losses are deductible only as an itemized deduction limited to gambling winnings. The $10,000 must be reported in gross income; the $4,000 loss is a separate Schedule A deduction, not a direct offset.
Wrong (B): $6,000 incorrectly nets the losses against the winnings on the income side, but Section 165(d) allows losses only as an itemized deduction.
Wrong (C): $4,000 has no basis in the calculation; the full $10,000 in winnings must be reported as gross income.
Wrong (D): $14,000 incorrectly adds winnings and losses together rather than recognizing that losses are deductible, not additional income.$EXPL$
WHERE id = 2626;

-- Q2629: Individual Taxation: Income [hard/L2]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (C): Wendy is insolvent because liabilities ($80,000) exceed assets ($55,000) by $25,000. Under IRC Section 108(a)(1)(B), COD income is excluded to the extent of insolvency. Of the $30,000 cancelled, $25,000 is excluded (the insolvency amount), and the remaining $5,000 is includible because it makes her solvent.
Wrong (A): $30,000 is the total cancelled debt, but Section 108 excludes the portion covered by insolvency ($25,000), so only $5,000 is taxable.
Wrong (B): $25,000 is the insolvency amount that is excluded, not the amount included in income.
Wrong (D): $0 would apply only if Wendy were insolvent by at least $30,000, but her insolvency is only $25,000.$EXPL$
WHERE id = 2629;

-- Q2630: Individual Taxation: Income [medium/L2]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (D): Under IRC Section 108(a)(1)(A), COD income arising in a Title 11 bankruptcy case is fully excluded from gross income regardless of the taxpayer''s solvency. This is the broadest COD exclusion available and takes priority over the insolvency exclusion.
Wrong (A): Including $40,000 in gross income ignores the bankruptcy exclusion under Section 108(a)(1)(A), which fully excludes COD income in Title 11 cases.
Wrong (B): While tax attribute reduction under Section 108(b) is required, this choice incorrectly implies partial treatment; the full $40,000 is excluded from current income.
Wrong (C): The bankruptcy exclusion is all-or-nothing for COD arising in the proceeding; there is no 50/50 split.$EXPL$
WHERE id = 2630;

-- Q2631: Individual Taxation: Income [medium/L2]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (A): Under IRC Section 62(a)(23) as added by H.R. 1 (2025 legislation), qualifying tip income remains includable in gross income under Section 61 but is eligible for a new above-the-line deduction that effectively offsets the income tax on tips while preserving FICA obligations.
Wrong (B): Tips are not excluded from gross income; they remain includable under Section 61, with the tax benefit provided through a deduction mechanism.
Wrong (C): No flat-rate provision exists for tip income; the deduction reduces AGI rather than applying a special tax rate.
Wrong (D): Tips remain subject to Social Security and Medicare taxes under IRC Section 3121; the provision does not exclude them from FICA wages.$EXPL$
WHERE id = 2631;
