-- Migration: Quality fix -- ISC batch 26 (30 questions)
-- Generated by generate-quality-scaffold.ts
-- Issues: #1 (giveaway longest), #3 (incomplete explanation)

-- Q3475: ERP and Accounting Information Systems [easy/L1]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["Validating account numbers at the point of data entry","Requiring manager approval before journal entries are posted","Comparing a printed aging report total to the general ledger balance","Using encryption to protect sensitive data in transit"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (C): Comparing the aging report total to the general ledger balance is an output reconciliation control that verifies accuracy and completeness of processed information, per COBIT 2019 DSS06.02 (Control of Information Processing). Output controls ensure results are accurate and distributed only to authorized recipients.
Wrong (A): Validating account numbers at data entry is an input control, not an output control. It checks data before processing, not after.
Wrong (B): Requiring manager approval is an authorization control over transaction processing, not a control over output distribution or accuracy.
Wrong (D): Encryption protects data confidentiality during transmission but does not verify the accuracy or completeness of processed output.$EXPL$
WHERE id = 3475;

-- Q3476: ERP and Accounting Information Systems [medium/L2]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["XML files are always smaller than flat file equivalents","XML does not require any parsing or processing by receivers","XML eliminates the need for data validation between systems","XML uses self-describing tags, enabling easier validation and extension"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (D): XML uses self-describing tags that label each data element, making the structure human-readable and machine-parseable per COBIT 2019 BAI03.03. New fields can be added without breaking existing integrations that ignore unknown tags, providing superior extensibility over fixed-format flat files.
Wrong (A): XML files are typically larger than flat files due to the overhead of opening and closing tags for every element.
Wrong (B): XML requires dedicated parsing and processing; receivers must use an XML parser to extract data from the tagged structure.
Wrong (C): XML does not eliminate data validation needs. While tags aid structure, business-rule validation is still required.$EXPL$
WHERE id = 3476;

-- Q3477: ERP and Accounting Information Systems [medium/L2]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["Comparing the payroll register to HR''s active employee master file independently","Encrypting payroll direct deposit files before transmission to the bank","Requiring all employees to use direct deposit instead of paper checks","Increasing payroll processing frequency from biweekly to weekly cycles"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (A): Independently comparing the payroll register to the HR active employee master file detects names on payroll that do not correspond to real, active employees, per COBIT 2019 DSS06.03. Ghost employee fraud involves paying fictitious employees, and cross-referencing is the most direct detection method.
Wrong (B): Encrypting direct deposit files protects data confidentiality during transmission but does not detect whether a payee is a legitimate employee.
Wrong (C): Requiring direct deposit changes the payment delivery method but does not prevent fictitious employees from being added to the payroll.
Wrong (D): Increasing payroll frequency processes payments more often but does not address whether the payees are valid employees.$EXPL$
WHERE id = 3477;

-- Q3480: ERP and Accounting Information Systems [easy/L1]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["They are embedded in a specific business process to ensure transaction data integrity","They apply uniformly to all IT systems across the entire organization","They are physical security measures designed to protect server hardware","They are only manual procedures that end users perform outside the system"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (A): Under the COSO Internal Control — Integrated Framework, application controls are embedded within specific business applications to ensure completeness, accuracy, and validity of individual transactions. The three-way match in AP is a classic example of a process-specific application control.
Wrong (B): Controls that apply to all IT systems organization-wide are IT general controls (ITGCs), not application controls. Application controls target a single business process.
Wrong (C): Physical security measures protect hardware and facilities. Application controls are logical controls within software, not physical measures.
Wrong (D): Application controls can be automated, manual, or a combination. The scenario describes an automated control built into the ERP module.$EXPL$
WHERE id = 3480;

-- Q3481: ERP and Accounting Information Systems [medium/L2]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["Setting the default screen color scheme to match corporate branding guidelines","Enabling the fastest available database query mode for report generation","Aligning depreciation methods, useful lives, and salvage values with accounting policies","Maximizing the number of concurrent users who can access the fixed assets module"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (C): Per COBIT 2019 BAI05 and ASC 360-10, the fixed assets module''s depreciation configuration directly impacts financial statement accuracy. Methods, useful lives, and salvage values must align with GAAP accounting policies to produce correct depreciation expense and net book values.
Wrong (A): Screen color settings are cosmetic preferences with no impact on financial reporting accuracy or depreciation calculations.
Wrong (B): Database query performance affects speed of report generation but does not influence the correctness of depreciation amounts recorded.
Wrong (D): Concurrent user capacity is an infrastructure concern that affects accessibility, not the accuracy of financial calculations.$EXPL$
WHERE id = 3481;

-- Q3483: ERP and Accounting Information Systems [medium/L1]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["Accept the entries since they are system-generated and inherently correct","Test only recurring entries that exceed the established materiality thresholds","Interview the CFO and accept verbal confirmation of the entry authorization","Review entry templates and authorization, then trace samples to supporting data"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (D): Per COBIT 2019 DSS06.03, automated recurring journal entries still require proper authorization of underlying templates. The auditor should review who authorized the templates, verify calculations, and trace sample entries to supporting documentation.
Wrong (A): System-generated entries are not inherently correct. Misconfigured templates can produce incorrect amounts, so auditors cannot rely solely on automation.
Wrong (B): Testing only entries above materiality ignores that smaller recurring entries can accumulate to material amounts over multiple periods.
Wrong (C): Verbal confirmation alone is insufficient audit evidence. Auditors require documented authorization and corroborating support per auditing standards.$EXPL$
WHERE id = 3483;

-- Q3488: ERP and Accounting Information Systems [hard/L2]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["The workflow engine is functioning correctly as designed by the vendor","Directors are senior enough to approve purchase orders of any amount","The threshold configuration is wrong or directors were granted excessive authority","The ERP system cannot enforce dollar-based approval routing rules"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (C): Per COBIT 2019 DSS06, automated workflow controls must enforce proper authorization thresholds. When orders over $50,000 are approved by directors instead of VPs, the most likely cause is misconfigured threshold settings or improperly assigned role permissions in the ERP system.
Wrong (A): If 15% of high-value orders bypass the required VP approval, the workflow engine is not functioning as intended. The pattern indicates a control deficiency.
Wrong (B): Organizational seniority does not determine system permissions. Authorization levels must match the configured approval matrix regardless of job title.
Wrong (D): ERP systems routinely enforce dollar-based routing. The fact that most orders follow the thresholds confirms the system has this capability.$EXPL$
WHERE id = 3488;

-- Q3490: ERP and Accounting Information Systems [medium/L2]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["Authorization controls requiring board-level approval before debt or equity processing","Spell-checking on text fields within loan agreement documents in the system","Color-coding of different financing transaction types displayed on screen","Automatic email notifications sent for all financing cycle transactions"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (A): Per COBIT 2019 DSS06.02, automated authorization controls are most critical in the financing cycle. Debt issuance, stock repurchases, and dividend declarations are high-value events requiring board or executive-level approval to prevent unauthorized financial commitments.
Wrong (B): Spell-checking is a text formatting feature that does not address authorization, data integrity, or financial risk in the financing cycle.
Wrong (C): Color-coding is a display preference that aids visual identification but provides no control over whether transactions are properly authorized.
Wrong (D): Email notifications are informational alerts. They notify stakeholders after the fact but do not prevent unauthorized transactions from being processed.$EXPL$
WHERE id = 3490;

-- Q3496: ERP and Accounting Information Systems [hard/L2]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["Manual spreadsheet adjustments uploaded to the consolidation system monthly","Separate ERP instances for each subsidiary with no intercompany integration","A standalone reporting tool estimating eliminations from historical patterns","Built-in intercompany tagging with automated elimination rules at consolidation"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (D): Per COBIT 2019 BAI03 and ASC 810 (Consolidation), modern ERP systems support automated intercompany elimination by tagging transactions at entry and applying predefined rules during consolidation. This systematically identifies and removes reciprocal balances with full traceability.
Wrong (A): Manual spreadsheet adjustments are error-prone, difficult to audit, and do not scale across multiple subsidiaries with high transaction volumes.
Wrong (B): Separate ERP instances with no integration make intercompany elimination harder, not easier, by requiring manual reconciliation of disconnected data.
Wrong (C): Estimating eliminations from historical patterns introduces inaccuracy because current-period intercompany activity may differ significantly from past trends.$EXPL$
WHERE id = 3496;

-- Q3497: ERP and Accounting Information Systems [easy/L1]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["Each receipt and issue is recorded in real time, maintaining a continuous balance","Inventory is counted and valued only at year-end during a physical count","Inventory quantities are estimated using published industry benchmark data","Inventory is recorded only when a quarterly physical count is performed"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (A): Per ASC 330 and COBIT 2019 APO14, a perpetual inventory system records every receipt, issue, transfer, and adjustment in real time through the ERP, maintaining continuously updated quantity and cost records. Physical counts verify but are not the primary record-keeping basis.
Wrong (B): Counting and valuing inventory only at year-end describes the periodic inventory method, not the perpetual method.
Wrong (C): Estimating quantities from industry benchmarks is not an accepted inventory accounting method under GAAP. Actual transaction data must be recorded.
Wrong (D): Recording inventory only at quarterly counts is a variation of the periodic method and does not maintain continuous real-time balances.$EXPL$
WHERE id = 3497;

-- Q3498: ERP and Accounting Information Systems [hard/L4]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["Whether the system administrator has completed all required annual training","Whether the system administrator used a sufficiently strong password to log in","Whether the parameter change temporarily suppressed overdue invoices from reports","Whether the ERP software license permits users to modify aging parameters"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (C): Per AICPA Trust Services Criteria CC7.2 and COBIT 2019 DSS05, temporarily modifying aging parameters at quarter-end and reverting them the next day is a red flag for financial statement manipulation. The change could have suppressed overdue invoices from reports used by management or auditors, masking cash flow problems.
Wrong (A): Training completion is a general HR matter that does not address the specific risk of quarter-end parameter manipulation or its financial reporting impact.
Wrong (B): Password strength is an access control concern unrelated to why aging parameters were temporarily changed and then reversed at a reporting date.
Wrong (D): Licensing permissions are a vendor contractual matter. The audit concern is the purpose and financial impact of the temporary change, not whether the software allows it.$EXPL$
WHERE id = 3498;

-- Q3499: ERP and Accounting Information Systems [medium/L1]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["A monthly report listing all payments made during the reporting period","A quarterly internal audit reviewing vendor payment transactions for errors","An annual review of the approved vendor master list by management","A three-way match rule that blocks payment when documents do not agree"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (D): A system-enforced three-way match that blocks payment when the purchase order, receiving report, and invoice disagree is an automated preventive control per COBIT APO13.01 and AICPA Trust Services Criteria CC6.1. It stops erroneous or unauthorized payments before processing.
Wrong (A): A monthly payment report is a detective control that identifies discrepancies after transactions have already been processed, not a preventive control.
Wrong (B): A quarterly internal audit is a detective activity performed after the fact and is neither automated nor preventive in nature.
Wrong (C): An annual vendor list review is a periodic detective control that occurs too infrequently to prevent individual erroneous payments.$EXPL$
WHERE id = 3499;

-- Q3500: ERP and Accounting Information Systems [hard/L2]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["The ERP must support healthcare data standards like HL7/FHIR for accurate exchange","The ERP should use the same screen color scheme as the existing EHR system","The ERP vendor should be headquartered within the same region as the hospital","The ERP should replicate all clinical functionality already present in the EHR"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (A): Per COBIT APO10.03, healthcare ERP-EHR integration requires adherence to HL7 and FHIR data standards. These ensure patient demographics, diagnoses, and charges flow accurately between clinical and financial systems without data translation errors or rejected claims.
Wrong (B): Screen color matching is a cosmetic preference that has no bearing on data interoperability, billing accuracy, or system integration capability.
Wrong (C): Vendor geographic proximity does not affect technical integration quality. Data standards compliance and API compatibility determine integration success.
Wrong (D): Replicating clinical functionality would create redundancy and scope creep. The ERP should exchange data with the EHR, not duplicate its clinical features.$EXPL$
WHERE id = 3500;

-- Q3501: Data Management and Lifecycle [easy/L1]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["A flat file system that stores data in text files with no defined relationships","A spreadsheet application used primarily for ad hoc financial analysis tasks","A system with structured tables, defined relationships, and SQL query support","A document storage system with no structured query or retrieval capability"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (C): An RDBMS organizes data into structured tables linked through primary and foreign key relationships and uses SQL for data manipulation, per the ANSI/ISO SQL standard. This architecture enforces referential integrity and supports complex queries across related tables.
Wrong (A): Flat file systems store data in unstructured text without defined relationships or referential integrity, failing the controller''s data integrity requirement.
Wrong (B): Spreadsheet applications lack enforced relationships, ACID compliance, and multi-user concurrency controls required for an accounting system.
Wrong (D): A document storage system without query capability cannot support the structured data retrieval and relationship enforcement the controller requires.$EXPL$
WHERE id = 3501;

-- Q3503: Data Management and Lifecycle [easy/L1]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["A foreign key constraint enforcing referential integrity","A check constraint validating values against defined rules","A unique constraint preventing duplicate values in a column","A not-null constraint requiring a value in every row"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (A): A foreign key constraint enforces referential integrity by requiring every value in the child column to match an existing primary key in the parent table, per COBIT 2019 DSS06.02. This prevents orphaned records in the orders table.
Wrong (B): A check constraint validates values against specific conditions such as numeric ranges or allowed values but cannot verify that a referenced row exists in another table.
Wrong (C): A unique constraint prevents duplicate values within a single column but does not enforce cross-table relationships between parent and child records.
Wrong (D): A not-null constraint ensures a column is never empty but does not validate that the entered value matches an existing record in a referenced table.$EXPL$
WHERE id = 3503;

-- Q3504: Data Management and Lifecycle [easy/L1]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["Stronger enforcement of ACID transactions across all stored documents","A flexible schema accommodating varying structures without predefined tables","Better support for complex SQL JOIN operations across multiple collections","Mandatory data normalization enforced automatically across all documents"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (B): A NoSQL document database stores data as flexible JSON-like documents where each can have a different structure, per COBIT 2019 APO03.02. This schema flexibility accommodates varying content types without requiring a rigid predefined table schema.
Wrong (A): Relational databases provide stronger ACID transaction enforcement. Most NoSQL document stores trade strict ACID compliance for scalability and flexibility.
Wrong (C): SQL JOIN operations are a strength of relational databases. NoSQL document databases typically embed related data within documents rather than joining tables.
Wrong (D): NoSQL document databases do not enforce normalization. Their advantage is allowing denormalized, flexible structures tailored to each document type.$EXPL$
WHERE id = 3504;

-- Q3505: Data Management and Lifecycle [easy/L1]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["Creating new data records from original source transactions in the system","Permanently destroying data that has exceeded its required retention period","Moving inactive data to lower-cost storage while retaining it for compliance","Processing raw transactional data into meaningful information for reporting"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (C): Data archival involves moving inactive data to cost-effective long-term storage while retaining it for legal or regulatory requirements, per COBIT 2019 DSS06.06 and NIST SP 800-88. Archived data is typically read-only and infrequently accessed.
Wrong (A): Creating new data from source transactions describes data creation or generation, which is an earlier phase of the data lifecycle, not archival.
Wrong (B): Permanently destroying data describes data destruction or disposal, which occurs only after the retention period expires. Archival preserves data.
Wrong (D): Processing raw data into meaningful information describes data transformation or analysis, not the archival process of relocating inactive records.$EXPL$
WHERE id = 3505;

-- Q3509: Data Management and Lifecycle [easy/L1]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["Processes individual transactions in real time for operational OLTP systems","Pulls data from sources, standardizes formats, and loads into the warehouse","Distributes web content to users through a global delivery network","Performs multidimensional analysis of historical datasets using OLAP cubes"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (B): ETL (Extract, Transform, Load) is the standard data integration process for populating a data warehouse, per COBIT 2019 DSS06. Data is extracted from source systems, transformed to reconcile differing formats, and loaded into the target warehouse for analysis.
Wrong (A): Real-time transaction processing describes OLTP system operations, not the batch-oriented ETL process used to populate data warehouses.
Wrong (C): Distributing web content through a global network describes a content delivery network (CDN), which is unrelated to data warehouse integration.
Wrong (D): Multidimensional analysis using OLAP cubes occurs after the warehouse is populated. OLAP queries data; ETL loads it.$EXPL$
WHERE id = 3509;

-- Q3510: Data Management and Lifecycle [medium/L1]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["A central fact table with metrics surrounded by descriptive dimension tables","A single denormalized table that contains all organizational data together","A fully normalized set of tables structured in third normal form","A collection of unrelated flat files stored in a shared directory"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (A): Per COBIT 2019 APO03, a star schema organizes a data warehouse with a central fact table containing quantitative measures surrounded by denormalized dimension tables for date, product, customer, and geography. This creates the characteristic star pattern optimized for analytical queries.
Wrong (B): A single denormalized table lacks the dimensional structure that enables efficient analytical querying and drill-down capabilities in a star schema.
Wrong (C): A fully normalized third normal form design is used in OLTP systems for transactional integrity, not for analytical data warehouse performance.
Wrong (D): Unrelated flat files provide no relational structure, dimensional modeling, or query optimization for analytical reporting workloads.$EXPL$
WHERE id = 3510;

-- Q3511: Data Management and Lifecycle [easy/L1]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["OLAP handles individual transactions while OLTP performs bulk analytical queries","OLAP and OLTP are identical technologies serving the same business purpose","OLAP handles complex historical queries while OLTP handles fast transactions","OLAP only works with spreadsheets while OLTP only works with databases"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (C): Per COBIT 2019 APO03, OLAP systems are purpose-built for complex aggregate queries across large volumes of historical data, supporting dimensional modeling and read-heavy analytical workloads. OLTP systems are optimized for fast concurrent transaction processing with ACID compliance.
Wrong (A): This reverses the roles. OLTP handles individual transactions, and OLAP handles bulk analytical queries, not the other way around.
Wrong (B): OLAP and OLTP are fundamentally different technologies with distinct architectures, schemas, and performance optimization strategies.
Wrong (D): Both OLAP and OLTP systems use databases. OLAP is not limited to spreadsheets, and OLTP is not the only technology that uses databases.$EXPL$
WHERE id = 3511;

-- Q3515: Data Management and Lifecycle [medium/L2]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["Rewriting application source code to synchronize the two databases automatically","Investigating root causes, enforcing data quality standards, and coordinating fixes","Purchasing new server hardware to improve database replication performance","Approving capital expenditures for a third-party data cleansing vendor contract"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (B): Per COBIT 2019 APO14.02, data stewards manage day-to-day data quality within their domain by enforcing standards, resolving quality issues, and coordinating with system owners. They are the operational guardians of data integrity and consistency.
Wrong (A): Rewriting application source code is a developer or IT engineering responsibility. Data stewards focus on data quality rules and governance, not code changes.
Wrong (C): Purchasing server hardware is an infrastructure decision belonging to IT operations or management, not within the data steward''s governance role.
Wrong (D): Approving capital expenditures is a financial authority held by management or executives, not a data steward responsibility.$EXPL$
WHERE id = 3515;

-- Q3517: Data Management and Lifecycle [medium/L2]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["The IT director, because IT controls all technical infrastructure and permissions","The data owner (CMO), because data owners authorize all access to their data","The compliance department, because HIPAA regulations govern all access decisions","The contractors'' project manager, because external teams manage their own access"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (B): Per COBIT 2019 APO01.06 and NIST SP 800-18, the data owner is accountable for determining classification levels and authorizing who may access the data asset. The IT director should not have granted access without the CMO''s approval as data owner.
Wrong (A): The IT department implements technical access controls but does not have authority to make access authorization decisions. That authority belongs to the data owner.
Wrong (C): Compliance departments advise on regulatory requirements but do not exclusively make access decisions. The data owner retains ultimate authorization authority.
Wrong (D): External project managers have no authority over data access decisions. Access must be authorized by the data owner regardless of the requester''s organizational role.$EXPL$
WHERE id = 3517;

-- Q3518: Data Management and Lifecycle [medium/L2]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["Reformatting is the most secure data destruction method currently available","Reformatting destroys data more thoroughly than physical destruction methods","Financial data on decommissioned drives does not require secure destruction","Reformatting removes only file references, leaving data recoverable by forensic tools"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (D): Per NIST SP 800-88, standard reformatting only removes file system metadata without overwriting actual data blocks, leaving the underlying information recoverable by forensic tools. Secure destruction requires cryptographic erasure, degaussing, overwriting, or physical shredding.
Wrong (A): Reformatting is among the least secure methods. It merely clears directory pointers without destroying the underlying data on disk platters.
Wrong (B): Physical destruction methods like shredding or incineration are far more thorough than reformatting, which leaves data intact on the media.
Wrong (C): Financial data contains sensitive information that requires secure destruction under regulatory and organizational data protection policies.$EXPL$
WHERE id = 3518;

-- Q3520: Data Management and Lifecycle [easy/L1]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["To perform daily database backup operations and disaster recovery testing","To establish enterprise data policies, resolve disputes, and align with objectives","To write and maintain application source code for all data management systems","To review and approve all employee vacation requests across the organization"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (B): Per COBIT 2019 APO01, a cross-functional data governance council provides strategic oversight by balancing business, regulatory, and technical perspectives when setting enterprise-wide data policies. The council resolves cross-domain disputes and monitors quality metrics.
Wrong (A): Daily database backups are an operational IT task performed by database administrators, not a strategic governance council responsibility.
Wrong (C): Writing application source code is a software development function. Governance councils set policies and standards, not build technical solutions.
Wrong (D): Approving vacation requests is an HR management function entirely outside the scope of data governance activities.$EXPL$
WHERE id = 3520;

-- Q3522: Data Management and Lifecycle [hard/L1]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["The data warehouse will contain no data from the failed batch load","Reports will use unconverted currencies, non-standard dates, and duplicate records","The source systems will lose their original transactional data permanently","Users will receive an explicit error message when they attempt to access reports"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (B): Per COBIT 2019 DSS06, a silent ETL transform failure loads untransformed data into the warehouse, causing currency mismatches, inconsistent date formats, and duplicate records that inflate financial totals. Reports appear normal while containing materially inaccurate data.
Wrong (A): A silent failure means data still loads — it just loads without proper transformation. The warehouse receives raw, untransformed records rather than no records.
Wrong (C): ETL extracts copies of source data. Source systems retain their original data regardless of whether the ETL transform step succeeds or fails.
Wrong (D): A silent failure by definition produces no error message. Users see reports that appear normal, making the inaccuracy harder to detect.$EXPL$
WHERE id = 3522;

-- Q3523: Data Management and Lifecycle [easy/L1]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["INSERT INTO — adds new records to tables","CREATE TABLE — defines a new table structure","DROP TABLE — permanently removes a table and its data","SELECT ... FROM ... WHERE — retrieves filtered data"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (D): The SELECT statement with FROM and WHERE clauses retrieves specific columns and rows from a database table, per COBIT 2019 DSS06. SELECT specifies columns, FROM identifies the source table, and WHERE filters rows by condition.
Wrong (A): INSERT INTO adds new records to a table. It is a data manipulation command for writing, not retrieving, information from the database.
Wrong (B): CREATE TABLE defines a new table structure in the database. It is a data definition command, not a data retrieval command.
Wrong (C): DROP TABLE permanently removes a table and all its data from the database. It destroys data rather than retrieving it.$EXPL$
WHERE id = 3523;

-- Q3524: Data Management and Lifecycle [medium/L3]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["OLTP transaction processing optimized for individual record operations","Exporting all ten years of data to spreadsheets for manual trend analysis","Full table scans of the entire general ledger without dimensional indexing","OLAP cube analysis with drill-down, slice, and dice across dimensions"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (D): Per COBIT 2019 APO14, OLAP cube analysis enables multidimensional exploration of aggregated data, allowing the CFO to drill down from annual to quarterly revenue, slice by product lines, and dice across regions interactively. It is specifically designed for this type of analysis.
Wrong (A): OLTP transaction processing is optimized for individual record operations, not the complex multi-dimensional analytical queries the CFO requires.
Wrong (B): Exporting ten years of data to spreadsheets is impractical at scale and lacks the interactive drill-down and dimensional analysis capabilities OLAP provides.
Wrong (C): Full table scans are inefficient for large datasets and do not provide dimensional structure for the multi-axis trend analysis requested.$EXPL$
WHERE id = 3524;

-- Q3528: Data Management and Lifecycle [easy/L1]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["It automatically deletes duplicate data found across all connected systems","It replaces the need for database backups across the entire organization","It lets users discover, understand, and assess data assets via searchable metadata","It encrypts all cataloged data assets stored at rest across every system"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (C): Per COBIT 2019 APO14.06, a data catalog serves as a searchable inventory of an organization''s data assets, providing metadata, descriptions, ownership, lineage, and quality scores. It empowers users to discover relevant data and assess its suitability.
Wrong (A): A data catalog indexes metadata about data assets but does not modify, deduplicate, or delete the underlying data in source systems.
Wrong (B): A data catalog is a metadata discovery tool. It does not perform backup operations, which remain the responsibility of IT operations.
Wrong (D): A data catalog provides metadata and lineage information. Encryption of data at rest is a security function handled by separate infrastructure controls.$EXPL$
WHERE id = 3528;

-- Q3529: Data Management and Lifecycle [hard/L2]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["Degaussing is too expensive to be practical for solid-state drive media","SSDs use flash memory cells unaffected by magnetic fields, so degaussing fails","Degaussing works perfectly well on SSDs and is the recommended approach","SSDs cannot store sensitive customer data requiring secure destruction"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (B): Per NIST SP 800-88 Rev. 1, degaussing is effective only for magnetic storage media. SSDs store data using electrical charges in NAND flash memory cells, which are completely unaffected by magnetic fields. Organizations must use cryptographic erasure, ATA Secure Erase, or physical destruction.
Wrong (A): Cost is not the reason degaussing fails on SSDs. The issue is physical incompatibility — magnetic fields have no effect on flash memory technology.
Wrong (C): Degaussing has zero effect on SSDs. NIST SP 800-88 explicitly states that degaussing is not a valid sanitization method for flash-based storage.
Wrong (D): SSDs routinely store sensitive data including financial records. The issue is the destruction method, not the storage medium''s data handling capability.$EXPL$
WHERE id = 3529;

-- Q3531: Data Management and Lifecycle [hard/L4]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["Ignore the discrepancy since it falls below the established materiality threshold","Run a reconciliation query to identify specific records causing the difference","Assume the general ledger is correct and adjust the subledger to match it","Delete the entire subledger and recreate it using general ledger balances"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (B): Per AICPA Trust Services Criteria PI1.4, data discrepancies require systematic investigation. The auditor should first perform a detailed reconciliation to isolate specific records causing the $47,000 difference, revealing whether the issue stems from unposted batches, entry errors, or unauthorized adjustments.
Wrong (A): Ignoring a discrepancy without investigation violates auditing standards. The $47,000 difference may indicate fraud or systemic errors regardless of materiality.
Wrong (C): Assuming either system is correct without investigation could mask the root cause and propagate errors through financial statements.
Wrong (D): Deleting and recreating the subledger destroys audit evidence and does not identify the root cause of the discrepancy.$EXPL$
WHERE id = 3531;
