-- Migration: Quality fix -- TCP batch 23 (30 questions)
-- Generated by generate-quality-scaffold.ts
-- Issues: #1 (giveaway longest), #3 (incomplete explanation)

-- Q5001: Entity Formation and Restructuring [hard/L2]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["Yes, because the boot relaxation rule permits up to 20% non-stock consideration when 80% is voting stock","Yes, because any combination of stock and cash is permitted in a Type C reorganization","No, because a Type C reorganization requires 100% voting stock with no boot exceptions","No, because the $30 million cash component exceeds the de minimis threshold for boot"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (A): Under Section 368(a)(2)(B), a Type C reorganization permits non-stock consideration (boot) if at least 80% of the target''s gross assets are acquired solely for voting stock. However, any assumed liabilities count as boot for the 80% test, which can cause failure if total non-stock consideration exceeds 20%.
Wrong (B): Type C reorganizations have a strict ''solely for voting stock'' requirement with only the limited boot relaxation exception, not unlimited flexibility.
Wrong (C): The 100% requirement is the general rule, but Section 368(a)(2)(B) provides a specific boot relaxation exception permitting up to 20%.
Wrong (D): There is no $10 million de minimis threshold in the Type C reorganization rules; the test is based on the 80% percentage of gross asset value.$EXPL$
WHERE id = 5001;

-- Q5002: Entity Formation and Restructuring [medium/L1]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["Using a distribution to circumvent the continuity of interest requirement","Using a spin-off principally as a device for distributing E&P as capital gains instead of dividends","Transferring assets between related corporations without recognizing gain","Acquiring a loss corporation solely to use its net operating losses"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (B): Under Section 355(a)(1)(B), the device test prevents taxpayers from using corporate divisions (spin-offs, split-offs, split-ups) primarily as a mechanism to distribute earnings and profits at capital gains rates rather than as ordinary dividends. The IRS examines objective factors such as subsequent sales of distributed stock.
Wrong (A): The continuity of interest requirement is a separate doctrine under Section 368, not the purpose of the device test in Section 355.
Wrong (C): Section 351 and related provisions address nonrecognition transfers between related corporations, which is distinct from the device limitation.
Wrong (D): Section 269 addresses acquisitions made to obtain tax benefits like NOLs, not the device test under Section 355.$EXPL$
WHERE id = 5002;

-- Q5003: Entity Formation and Restructuring [hard/L2]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["A Type B stock-for-stock reorganization, preserving the target''s historical asset basis","A Type A statutory merger with no boot, carrying over the target''s existing basis","A taxable asset purchase directly from Target, triggering corporate and shareholder-level tax","A taxable stock purchase with a Section 338(h)(10) election for an eligible target entity"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (D): Under IRC Section 338(h)(10), a buyer who acquires target stock can elect to treat the purchase as a deemed asset sale, obtaining a stepped-up basis in assets. This election avoids double taxation that occurs with a direct asset purchase because the stock sale is disregarded and only the deemed asset sale is recognized on the target''s final return.
Wrong (A): A Type B reorganization is tax-free and preserves the target''s carryover basis in assets, providing no step-up.
Wrong (B): A Type A merger is also tax-free, meaning the acquiring corporation takes a carryover basis rather than a stepped-up basis.
Wrong (C): A direct taxable asset purchase provides a step-up but triggers two levels of tax: corporate-level gain on the sale plus shareholder-level gain on liquidation.$EXPL$
WHERE id = 5003;

-- Q5953: Passive Activity and At-Risk Rules [easy/L1]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["Nonrecourse debt secured by personal property used in a trade or business activity","Nonrecourse debt backed by a federal agency regardless of the collateral type","Recourse debt obtained from a lender who is related to the taxpayer","Nonrecourse financing from a qualified lender secured by real property in the activity"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (D): Under Section 465(b)(6), qualified nonrecourse financing is nonrecourse debt from a qualified lender (such as a bank or government agency) that is secured by real property used in the activity of holding real property. This exception allows real estate investors to include certain nonrecourse debt in their at-risk amounts.
Wrong (A): The qualified nonrecourse financing exception applies only to real property, not personal property used in a business.
Wrong (B): While government agencies can be qualified lenders, the collateral must be real property used in the activity, not any type of collateral.
Wrong (C): Recourse debt from related parties raises separate issues; qualified nonrecourse financing by definition involves nonrecourse debt from unrelated qualified lenders.$EXPL$
WHERE id = 5953;

-- Q5961: Passive Activity and At-Risk Rules [easy/L1]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["S corporations with individual shareholders who are subject to at-risk rules","Partnerships composed entirely of individual partners subject to the rules","Widely held C corporations that are not closely held or personal service corporations","Single-member LLCs disregarded for federal tax purposes as pass-through entities"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (C): Under Section 465(a), the at-risk rules apply to individuals and certain closely held corporations (including S corporations through their shareholders and personal service corporations). Widely held C corporations that are neither closely held nor personal service corporations are generally exempt from these limitations.
Wrong (A): S corporation losses flow through to individual shareholders, who are themselves subject to at-risk rules at the shareholder level under Section 465.
Wrong (B): Individual partners in a partnership are subject to at-risk rules on their allocable share of partnership losses.
Wrong (D): A single-member LLC disregarded for tax purposes is treated as the individual owner, who is subject to at-risk rules.$EXPL$
WHERE id = 5961;

-- Q5989: Passive Activity and At-Risk Rules [hard/L4]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["$200,000, because qualified nonrecourse financing provides sufficient at-risk and basis amounts","$25,000, under the active participation rental real estate allowance for eligible taxpayers","$150,000, limited to the qualified nonrecourse financing amount allocated to Ingram","$0, because the passive activity rules suspend the entire loss with no offsetting income"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (D): Under Section 469 and Section 465(b)(6), Ingram''s basis ($350,000) and at-risk amount ($350,000 with qualified nonrecourse financing) both exceed the $200,000 loss. However, as a limited partner without active participation and AGI above $150,000, the $25,000 allowance is fully phased out. With no passive income to offset, the entire $200,000 loss is suspended.
Wrong (A): While basis and at-risk amounts are sufficient, the passive activity limitation under Section 469 is the binding constraint that suspends the loss.
Wrong (B): Limited partners cannot claim active participation under Section 469(i)(6)(C), and even if eligible, the $25,000 allowance phases out completely at AGI above $150,000.
Wrong (C): The $150,000 figure does not correspond to any applicable limitation in this scenario.$EXPL$
WHERE id = 5989;

-- Q6000: Passive Activity and At-Risk Rules [medium/L2]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["$20,000, because her AGI is below the $100,000 phase-out threshold for active participants","$0, because married-filing-separately taxpayers who live together get no special allowance","$10,000, because the allowance is reduced to $12,500 for married taxpayers filing separately","$12,500, because married-filing-separately taxpayers receive half the standard $25,000 amount"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (B): Under IRC Section 469(i)(5), a taxpayer who is married filing separately and lives with the spouse at any time during the year receives a $0 special allowance. This rule prevents income splitting to exploit the rental loss allowance twice by filing separately.
Wrong (A): Although Patterson''s AGI is below $100,000, the special allowance is completely eliminated for MFS taxpayers who live together, regardless of AGI.
Wrong (C): The reduced $12,500 allowance applies only to married-filing-separately taxpayers who live apart for the entire taxable year, not those who cohabitate.
Wrong (D): The $12,500 half-allowance is only available when the spouses live apart for the entire year; living together at any point reduces it to $0.$EXPL$
WHERE id = 6000;

-- Q6005: Passive Activity and At-Risk Rules [medium/L2]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["A trade or business activity because the average period of customer use is 7 days or less","A rental activity because customers pay to use the property for their occupancy","A portfolio activity because short-term rental income is treated as investment income","A rental activity that qualifies for the $25,000 special loss allowance for participants"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (A): Under Treas. Reg. 1.469-1T(e)(3)(ii)(A), an activity is not treated as a rental activity if the average period of customer use is 7 days or less. Brighton''s 4.5-day average triggers this exception, reclassifying the activity as a trade or business subject to material participation tests rather than rental activity rules.
Wrong (B): Despite customers paying for property use, the short-term rental exception removes the activity from rental classification when the average stay is 7 days or less.
Wrong (C): Short-term rental income is not portfolio income; portfolio income under Section 469(e) includes interest, dividends, and royalties.
Wrong (D): Because the activity is not classified as a rental activity, the $25,000 special allowance for rental losses does not apply.$EXPL$
WHERE id = 6005;

-- Q6021: Passive Activity and At-Risk Rules [medium/L2]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["Crawford can freely regroup activities each year based on the most favorable tax result","Crawford cannot separate unless a material change in facts makes the grouping inappropriate","Crawford must wait five years before making any change to a prior grouping election","Crawford can separate by filing an amended return for the original 2023 grouping year"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (B): Under Treas. Reg. 1.469-4(e), once activities are grouped, the grouping may only be changed if the original grouping is clearly inappropriate or if a material change in facts and circumstances makes the existing grouping clearly inappropriate. A taxpayer cannot regroup solely for tax benefit.
Wrong (A): The regulations specifically prevent annual regrouping to manipulate passive income and loss netting across activities.
Wrong (C): There is no five-year waiting period in the regulations; the standard is material change in facts and circumstances, not a fixed time period.
Wrong (D): Filing an amended return does not permit a retroactive change to a prior grouping election; the regulations do not provide this mechanism.$EXPL$
WHERE id = 6021;

-- Q6032: Passive Activity and At-Risk Rules [medium/L3]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["Patel deducts $40,000 because the at-risk limitation is the most restrictive single constraint","Patel deducts $55,000 because LLC members are exempt from at-risk limits under Section 465","Patel deducts nothing because the passive activity rules apply first and block the entire loss","Patel deducts nothing: basis caps the loss at $55,000, at-risk caps it at $40,000, then passive rules suspend it"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (D): Loss deductions follow strict ordering: basis limitation (Section 704(d)), then at-risk rules (Section 465), then passive activity rules (Section 469). Patel''s $60,000 loss is first reduced to $55,000 by basis, then to $40,000 by the at-risk amount, and the remaining $40,000 is fully suspended as a passive loss because Patel does not materially participate.
Wrong (A): While the at-risk amount does limit the loss to $40,000, the passive activity rules then suspend the entire $40,000 since Patel has no passive income.
Wrong (B): LLC members are not exempt from at-risk rules; Section 465 applies to individuals regardless of entity type.
Wrong (C): Passive activity rules are the last tier applied, not the first; the ordering is basis, at-risk, then passive.$EXPL$
WHERE id = 6032;

-- Q6047: Passive Activity and At-Risk Rules [medium/L3]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["Not a rental activity because significant personal services are provided with the property use","A rental activity because the average lease term exceeds the 7-day threshold","A rental activity regardless of services because it involves real property leasing","Not a rental activity solely because Cortez participates for more than 500 hours annually"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (A): Under Treas. Reg. 1.469-1T(e)(3)(ii)(B), an activity is not treated as a rental activity if significant personal services are provided in connection with making the property available for use. The executive suite services (reception, mail, IT support) go beyond merely providing property, so the activity is classified as a trade or business.
Wrong (B): The 7-day average period is a separate exception under Reg. 1.469-1T(e)(3)(ii)(A); the significant services exception applies regardless of lease duration.
Wrong (C): The presence of real property does not automatically make an activity a rental activity when significant personal services are provided.
Wrong (D): The 500-hour test determines material participation, not whether an activity is classified as rental versus trade or business.$EXPL$
WHERE id = 6047;

-- Q6068: Passive Activity and At-Risk Rules [easy/L1]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["Recourse loans obtained from unrelated commercial bank lenders","Qualified nonrecourse financing that is secured by real property in the activity","Amounts borrowed from a person who has an interest in the activity as an owner","Cash contributions made directly by the individual taxpayer to the activity"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (C): Under Section 465(b)(3), borrowed amounts are excluded from the at-risk amount when the lender has an ownership interest in the activity (other than as a creditor) or is related to a person with such an interest. This prevents artificial inflation of at-risk amounts through related-party or interested-party lending.
Wrong (A): Recourse loans from commercial banks are included in the at-risk amount under Section 465(b)(2) because the taxpayer bears personal liability.
Wrong (B): Qualified nonrecourse financing secured by real property is a specific exception under Section 465(b)(6) that increases the at-risk amount.
Wrong (D): Cash contributions are the most basic form of at-risk investment under Section 465(b)(1) and are never excluded.$EXPL$
WHERE id = 6068;

-- Q6072: Passive Activity and At-Risk Rules [easy/L2]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["Not deductible because 30 hours is insufficient participation for any rental allowance","Fully deductible as a nonpassive loss because Knox materially participates in the rental","Deductible in full under the Section 469(i) special allowance for active participants","Deductible but limited to $15,000 due to the AGI phase-out starting at $90,000"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (C): Under Section 469(i), active participation requires only bona fide management involvement such as tenant selection and lease approval, with no minimum hour requirement. Knox''s AGI of $95,000 is below the $100,000 phase-out threshold, so the full $20,000 rental loss is deductible under the $25,000 special allowance.
Wrong (A): Active participation has no minimum hour threshold; making management decisions about tenant selection and lease terms satisfies the standard.
Wrong (B): Rental activities are generally passive regardless of participation level; Knox benefits from the special allowance exception, not material participation reclassification.
Wrong (D): The phase-out begins at $100,000 AGI, not $90,000; Knox''s $95,000 AGI is entirely below the threshold.$EXPL$
WHERE id = 6072;

-- Q6074: Passive Activity and At-Risk Rules [hard/L3]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["$130,000, because qualified nonrecourse financing creates unlimited real estate deductibility","$110,000, because basis and at-risk rules apply but passive rules do not limit the loss","$25,000, because the rental loss allowance overrides the at-risk limitation amount","$0 currently, because limited partner status bars active participation and the loss is suspended"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (D): Loss limitations apply in order: (1) basis limits Callahan''s deductible amount, (2) at-risk rules allow $110,000 ($60,000 cash plus $50,000 qualified nonrecourse financing), and (3) the passive activity rules suspend the full $110,000 because Callahan has no passive income and, as a limited partner under Section 469(i)(6)(C), cannot claim the $25,000 active participation allowance.
Wrong (A): Qualified nonrecourse financing increases the at-risk amount but does not override the passive activity limitation under Section 469.
Wrong (B): Passive activity rules do restrict real estate losses for limited partners who cannot claim active participation and have no passive income.
Wrong (C): The $25,000 allowance is unavailable because limited partners are barred from active participation status under Section 469(i)(6)(C).$EXPL$
WHERE id = 6074;

-- Q6080: Passive Activity and At-Risk Rules [easy/L1]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["Any activity generating less than $25,000 of annual gross income","A trade or business without material participation, or any rental activity","Any investment activity that produces portfolio income such as dividends","Any activity conducted through a limited liability company structure"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (B): Under Section 469(c), a passive activity is defined as any trade or business in which the taxpayer does not materially participate, plus any rental activity (subject to limited exceptions). This two-part definition captures both non-participatory business activities and rental activities.
Wrong (A): The $25,000 figure relates to the special rental loss allowance, not the definition of a passive activity; income level does not determine passive status.
Wrong (C): Portfolio income (interest, dividends, royalties) is specifically excluded from the passive activity category under Section 469(e).
Wrong (D): The entity structure (LLC, partnership, etc.) does not determine whether an activity is passive; the test is based on the taxpayer''s level of participation.$EXPL$
WHERE id = 6080;

-- Q6082: Passive Activity and At-Risk Rules [medium/L2]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["No, because qualified nonrecourse financing must come from a person unrelated to the taxpayer","Yes, because the loan is nonrecourse and is secured by real property in the activity","Yes, because the lender holds no partnership interest in the borrowing entity","No, because only federally regulated banks and government agencies qualify as lenders"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (A): Under Section 465(b)(6)(D), qualified nonrecourse financing must come from a qualified person who is not related to the taxpayer under Section 49(a)(1)(D)(iv). Fletcher''s sibling is a related party, disqualifying the loan regardless of its other characteristics. The $100,000 does not increase Fletcher''s at-risk amount.
Wrong (B): Being nonrecourse and secured by real property satisfies two requirements, but the lender must also be a qualified unrelated person to meet all conditions.
Wrong (C): The lender''s lack of a partnership interest addresses Section 465(b)(3) related-party lending, but the sibling relationship independently disqualifies the loan.
Wrong (D): The definition of qualified person is broader than banks and government agencies; it includes any person actively and regularly engaged in lending, provided they are unrelated.$EXPL$
WHERE id = 6082;

-- Q7792: Retirement Plans and Education Savings [hard/L4]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["Not advisable because Harold''s expected lower future bracket makes the upfront conversion tax costly","Advisable because Roth 401(k) contributions are tax-deductible and also avoid required distributions","Not advisable because Roth 401(k)s remain subject to RMDs under current law after SECURE 2.0","Advisable because all converted amounts become tax-free to Harold immediately upon conversion"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (A): Under SECURE 2.0 Section 325, Roth 401(k)s are exempt from RMDs starting 2024. However, Roth conversions are fully taxable under IRC Section 402A. Since Harold expects a lower tax bracket post-retirement, paying a higher current rate now to avoid lower-taxed future RMDs is economically disadvantageous.
Wrong (B): Roth 401(k) contributions are made with after-tax dollars and are not tax-deductible; this misstates the fundamental Roth tax treatment.
Wrong (C): SECURE 2.0 did eliminate Roth 401(k) RMDs starting in 2024, so this statement is factually incorrect under current law.
Wrong (D): Converted amounts are taxable in the year of conversion; they do not become tax-free immediately upon conversion.$EXPL$
WHERE id = 7792;

-- Q14181: Wealth Transfer and Gifting Strategies [medium/L3]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["It allows Carolyn to avoid paying income tax on the trust''s future income distributions","It uses Leonard''s exclusion so the disclaimed amount passes to children estate-tax-free","It converts Leonard''s estate tax liability into a capital gains tax at a lower rate","It allows Carolyn to claim a double marital deduction on the disclaimed property portion"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (B): Under IRC Section 2518, a qualified disclaimer redirects assets into a credit shelter (bypass) trust funded with the decedent''s unused applicable exclusion ($14,500,000). The trust assets, including future appreciation, are excluded from Carolyn''s gross estate under Section 2041, permanently removing them from both estates rather than merely deferring estate tax.
Wrong (A): The disclaimer strategy addresses estate tax planning, not income tax; trust income is still subject to income tax under the applicable trust or beneficiary rates.
Wrong (C): There is no mechanism to convert estate tax into capital gains tax through a disclaimer; the two are separate tax regimes.
Wrong (D): The marital deduction under Section 2056 applies to property passing to the surviving spouse; disclaimed property passes to the trust beneficiaries, not to Carolyn.$EXPL$
WHERE id = 14181;

-- Q14386: Nontaxable Dispositions [medium/L2]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["The sale is recharacterized as a gift for the amount below market value","The installment method is automatically disallowed for the entire transaction","A portion of each principal payment is recharacterized as imputed interest income","The buyer must pay the interest rate difference between 1% and 5% directly to the IRS"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (C): Under IRC Sections 483 and 1274, when an installment sale note carries stated interest below the applicable federal rate, a portion of each principal payment is recharacterized as imputed (unstated) interest. This increases the seller''s ordinary interest income while reducing the selling price used to compute capital gain.
Wrong (A): Below-market interest does not recharacterize the sale as a gift; the imputed interest rules reallocate payments between principal and interest components.
Wrong (B): The installment method remains available; the OID rules simply adjust how payments are allocated between interest and principal.
Wrong (D): The buyer does not pay the rate difference to the IRS; instead, the imputed interest rules treat a portion of each principal payment as interest for both parties.$EXPL$
WHERE id = 14386;

-- Q896: Individual Tax Planning: Compensation [easy/L2]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (A): By filing a Section 83(b) election, the employee recognized $50,000 of ordinary income at the grant date ($5 x 10,000 shares). Under Section 83(b), no additional ordinary income is recognized at vesting because the election accelerated all compensation income to the grant date. Any appreciation above $5 per share is treated as capital gain upon sale.
Wrong (B): $50,000 represents the income recognized at the grant date, not at vesting; the election eliminates vesting-date recognition.
Wrong (C): $200,000 ($20 x 10,000) would be the income without an 83(b) election, recognizing the full FMV at vesting as compensation.
Wrong (D): $150,000 ($200,000 minus $50,000) confuses the appreciation with vesting-date income; the election means no ordinary income at vesting.$EXPL$
WHERE id = 896;

-- Q897: Individual Tax Planning: Compensation [easy/L2]
-- Issues: #1
UPDATE questions SET
  choices = $EXPL$["The election always benefits Sarah because it locks in the $12 value and any decline triggers an ordinary loss deduction","With the election, Sarah pays $42,000 tax at grant; the bull case saves on appreciation but the bear case causes a permanent overpayment with no forfeiture deduction","The election defers all taxation until sale, making it universally preferable to immediate recognition","The election converts all future appreciation into capital loss rather than capital gain for downside protection"]$EXPL$::jsonb
WHERE id = 897;

-- Q898: Individual Tax Planning: Compensation [medium/L2]
-- Issues: #1
UPDATE questions SET
  choices = $EXPL$["Executive A pays no regular tax at exercise and recognizes $300,000 of LTCG at sale, but the $200,000 spread is an AMT preference item; Executive B pays ordinary income at exercise","Both pay identical total tax because ISOs and NQSOs produce the same economic income with only timing differences","Executive A pays LTCG on $300,000 with no AMT impact because TCJA repealed the ISO AMT preference item","Executive A recognizes $200,000 ordinary income at exercise plus $100,000 capital gain because the holding period was not met"]$EXPL$::jsonb
WHERE id = 898;

-- Q899: Individual Tax Planning: Compensation [medium/L1]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (A): Under Section 409A, distributions from nonqualified deferred compensation plans are limited to six permissible events: separation from service, disability, death, a specified time or fixed schedule, change in control, and unforeseeable emergency. Separation from service is the most commonly triggered distribution event.
Wrong (B): Section 409A strictly prohibits employee-discretion distributions; allowing access at any time would violate the constructive receipt doctrine that NQDC plans must navigate.
Wrong (C): A change in investment preferences is not a permissible distribution trigger; it relates to plan administration, not the six statutory events.
Wrong (D): An arbitrary age milestone such as a 50th birthday is not a permissible event unless designated as a specified time in the plan document.$EXPL$
WHERE id = 899;

-- Q900: Individual Tax Planning: Compensation [hard/L4]
-- Issues: #1
UPDATE questions SET
  choices = $EXPL$["Exercise all options this year because ISOs are never subject to tax until shares are sold, making timing irrelevant","Split across two years to keep the annual AMT adjustment at $250,000, minimizing the excess over regular tax in each year","Exercise all this year because the Section 53 AMT credit carryforward guarantees full and timely recovery of AMT","Delay all exercises until Caldwell terminates employment because ISOs can only be exercised tax-free post-separation"]$EXPL$::jsonb
WHERE id = 900;

-- Q901: Individual Tax Planning: Compensation [hard/L4]
-- Issues: #1
UPDATE questions SET
  choices = $EXPL$["Defer the maximum $200,000 because the income drop from $800,000 to $150,000 guarantees a lower bracket on deferred amounts","Do not defer at all because the risk of employer insolvency makes NQDC plans unsuitable for any executive","Defer approximately $100,000 to balance the bracket reduction against insolvency risk and potential future rate increases","Defer the full $200,000 and invest the tax savings in a brokerage account to hedge the insolvency risk"]$EXPL$::jsonb
WHERE id = 901;

-- Q902: Individual Tax Planning: Compensation [easy/L1]
-- Issues: #1
UPDATE questions SET
  choices = $EXPL$["To include restricted stock''s FMV in gross income at grant rather than at vesting","To defer all taxation on restricted stock until the shares are ultimately sold","To convert ordinary compensation income on restricted stock into long-term capital gain","To exclude restricted stock from gross income entirely when vesting exceeds three years"]$EXPL$::jsonb
WHERE id = 902;

-- Q903: Individual Tax Planning: Compensation [medium/L1]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (B): Under IRC Section 422(a), gain from an ISO sale is treated as long-term capital gain when both holding periods are met: shares held at least 2 years from grant and at least 1 year from exercise. Here, 26 months from grant and 14 months from exercise both satisfy the requirements, so the entire gain qualifies as long-term capital gain.
Wrong (A): Ordinary income treatment applies only to a disqualifying disposition under Section 421(b), where the holding periods are not met.
Wrong (C): A split treatment (partly ordinary, partly capital gain) occurs in a disqualifying disposition, not a qualifying disposition that meets both holding periods.
Wrong (D): While the ISO spread was an AMT preference item at exercise, the gain at sale is regular long-term capital gain, not merely an AMT item with no regular tax.$EXPL$
WHERE id = 903;

-- Q906: Individual Tax Planning: Compensation [easy/L2]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (B): Under Section 162(m), the deduction for compensation paid to covered employees of publicly held corporations is limited to $1,000,000 per person per year. After the Tax Cuts and Jobs Act eliminated the performance-based compensation exception, virtually all forms of compensation are subject to this cap.
Wrong (A): $500,000 is not the Section 162(m) limit; the statutory cap has been $1,000,000 since the provision was enacted.
Wrong (C): $2,000,000 overstates the limit; Section 162(m) caps the deduction at $1,000,000, not $2,000,000.
Wrong (D): Section 162(m) applies specifically to publicly held corporations and their covered employees, so a deduction limit does apply to NovaTech''s CEO compensation.$EXPL$
WHERE id = 906;

-- Q907: Individual Tax Planning: Compensation [hard/L2]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (C): Under IRC Section 56(b)(3), the spread between FMV and exercise price at ISO exercise is an AMT adjustment. The calculation is ($60 - $25) x 500 shares = $17,500, which is added to alternative minimum taxable income in the exercise year (assuming shares are not sold in the same calendar year).
Wrong (A): $0 would apply only if the shares were sold in the same year as exercise, which would be a disqualifying disposition removing the AMT adjustment.
Wrong (B): $12,500 equals the exercise price times 500 shares ($25 x 500), which is not the correct calculation for the AMT adjustment.
Wrong (D): $30,000 equals $60 x 500 shares, which is the total FMV at exercise, not the spread between FMV and exercise price.$EXPL$
WHERE id = 907;

-- Q908: Individual Tax Planning: Compensation [hard/L2]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (D): Under Section 409A(a)(1)(B), a plan violation causes immediate income inclusion of all vested deferrals, plus a 20% additional tax on the amount included, plus an interest charge calculated from the year the compensation was first deferred. For Mercer, the $300,000 would be immediately included in income with these additional penalties.
Wrong (A): The 10% early distribution penalty applies to qualified retirement plans under Section 72(t), not to NQDC plan violations under Section 409A.
Wrong (B): Section 409A violations carry severe consequences; Congress specifically enacted the 20% penalty and interest charge to deter noncompliance.
Wrong (C): There is no 50% excise tax in the Section 409A penalty framework; the additional tax rate is 20%.$EXPL$
WHERE id = 908;
