-- Migration: Quality fix -- FAR batch 28 (30 questions)
-- Generated by generate-quality-scaffold.ts
-- Issues: #1 (giveaway longest), #3 (incomplete explanation)

-- Q2128: Equity [hard/L1]
-- Issues: #1
UPDATE questions SET
  choices = $EXPL$["Shown as negative with a fresh-start disclosure notation","Dated to indicate the reset period (e.g., ''retained earnings since quasi-reorganization'')","Eliminated entirely from the balance sheet presentation","Replaced by a newly created additional paid-in capital account"]$EXPL$::jsonb
WHERE id = 2128;

-- Q2131: Equity [easy/L2]
-- Issues: #1
UPDATE questions SET
  choices = $EXPL$["Total equity increases by $300,000","Total equity decreases by $300,000","Total equity remains unchanged after the dividend","Total equity decreases by $25,000"]$EXPL$::jsonb
WHERE id = 2131;

-- Q2143: Contingencies [medium/L2]
-- Issues: #1
UPDATE questions SET
  choices = $EXPL$["Accrue the $750,000 gain as an asset","Record $750,000 as deferred revenue on the books","Make no accrual and provide no note disclosure","Disclose the contingency in the notes without accrual"]$EXPL$::jsonb
WHERE id = 2143;

-- Q2148: Contingencies [medium/L1]
-- Issues: #1
UPDATE questions SET
  choices = $EXPL$["An existing obligation whose outcome depends on uncertain future events","A claim asserted against the entity by an outside third party","A probable future outflow of economic resources from the entity","A contractual obligation to perform that does not depend on uncertain events"]$EXPL$::jsonb
WHERE id = 2148;

-- Q2164: Income Taxes [easy/L1]
-- Issues: #1
UPDATE questions SET
  choices = $EXPL$["Any uncertainty about future realization of the DTA exists","The entity reports a net operating loss carryforward on its return","The deferred tax asset balance exceeds a specified dollar threshold","Realization of some or all of the DTA is not more likely than not"]$EXPL$::jsonb
WHERE id = 2164;

-- Q2199: Consolidations [medium/L2]
-- Issues: #1
UPDATE questions SET
  choices = $EXPL$["Allocated 100% to the controlling parent interest","Allocated 100% to the noncontrolling interest share","Allocated 80% to the parent and 20% to the NCI","Charged entirely against consolidated retained earnings"]$EXPL$::jsonb
WHERE id = 2199;

-- Q2202: Consolidations [medium/L1]
-- Issues: #1
UPDATE questions SET
  choices = $EXPL$["The subsidiary is legally dissolved at the acquisition date","The parent''s investment replaces the subsidiary''s equity accounts","The investment and subsidiary equity represent the same net assets","The subsidiary''s equity has no economic value after acquisition"]$EXPL$::jsonb
WHERE id = 2202;

-- Q2216: Consolidations [hard/L2]
-- Issues: #1
UPDATE questions SET
  choices = $EXPL$["Continue carrying the 30% at its equity method book value","Combine the 30% historical cost with the new 40% purchase cost","Write off the previously held 30% investment balance entirely","Remeasure the 30% to fair value and recognize any resulting gain or loss"]$EXPL$::jsonb
WHERE id = 2216;

-- Q2225: Fair Value [easy/L2]
-- Issues: #1
UPDATE questions SET
  choices = $EXPL$["Quoted prices for identical assets in active markets","Matrix pricing derived from observable benchmark bond yields","Discounted cash flow model using significant unobservable inputs","Market approach using comparable publicly traded transaction multiples"]$EXPL$::jsonb
WHERE id = 2225;

-- Q2234: Fair Value [easy/L1]
-- Issues: #1
UPDATE questions SET
  choices = $EXPL$["Historical acquisition cost less accumulated depreciation to date","The estimated liquidation value under a forced-sale scenario","The net realizable value after completion and disposal costs","The current cost to replace the service capacity of the asset"]$EXPL$::jsonb
WHERE id = 2234;

-- Q2236: Fair Value [hard/L2]
-- Issues: #1
UPDATE questions SET
  choices = $EXPL$["Apply a valuation technique from the counterparty''s perspective","Conclude that fair value measurement is not permitted here","Use the original historical issuance price as fair value","Record the liability at its stated par or face value"]$EXPL$::jsonb
WHERE id = 2236;

-- Q2295: Not-for-Profit Accounting [hard/L2]
-- Issues: #1
UPDATE questions SET
  choices = $EXPL$["$2,000,000 as revenue because the matching funds were provided","$0 because the annual compliance report has not been submitted","$2,000,000 as revenue if the compliance report is merely administrative","$1,500,000 representing the total grant amount minus the match"]$EXPL$::jsonb
WHERE id = 2295;

-- Q2325: State and Local Government [hard/L2]
-- Issues: #1
UPDATE questions SET
  choices = $EXPL$["Revenue of $20,400,000 in the Capital Projects Fund","A single combined other financing source of $20,400,000","Face amount as bond proceeds with the premium transferred out","Face amount and premium reported as separate other financing sources"]$EXPL$::jsonb
WHERE id = 2325;

-- Q2355: Special Purpose Frameworks [medium/L1]
-- Issues: #1
UPDATE questions SET
  choices = $EXPL$["Tax basis follows IRC Section 263A UNICAP rules, differing from GAAP","Tax basis always requires the FIFO cost flow assumption for inventory","Tax basis prohibits all standard inventory valuation methods entirely","Tax basis and GAAP treat inventory capitalization costs identically"]$EXPL$::jsonb
WHERE id = 2355;

-- Q2371: Special Purpose Frameworks [medium/L2]
-- Issues: #1
UPDATE questions SET
  choices = $EXPL$["The divergence is irrelevant because the contractual definition governs and the covenant is satisfied","The divergence constitutes financial fraud because excluding $1,200,000 of real expenses inflates EBITDA","The covenant cushion masks potential risk since Bellwood passes only by excluding charges that may recur","The bank should require a switch from contractual basis to GAAP to eliminate the reporting divergence"]$EXPL$::jsonb
WHERE id = 2371;

-- Q2373: Special Purpose Frameworks [hard/L2]
-- Issues: #1
UPDATE questions SET
  choices = $EXPL$["Recorded as revenue of $1,000,000 in the period received","Recorded as a cash receipt with a corresponding liability recognized","Recorded only as a cash receipt with no liability on the books","Not recorded because borrowings are excluded from the cash basis"]$EXPL$::jsonb
WHERE id = 2373;

-- Q4706: Financial Reporting: For-Profit [easy/L1]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (A): Under ASC 105-10-05 and SFAC No. 8 (OB2), the primary objective of general-purpose financial reporting is to provide information useful to existing and potential investors, lenders, and other creditors in making resource allocation decisions. This decision-usefulness objective drives all other aspects of the Conceptual Framework.
Wrong (B): Determining taxable income is governed by the IRC, not the objective of general-purpose financial reporting under GAAP.
Wrong (C): General-purpose financial statements target external users such as investors and creditors, not exclusively internal management.
Wrong (D): Calculating liquidation value relates to a specific measurement basis, not the overarching objective of financial reporting.$EXPL$
WHERE id = 4706;

-- Q4708: Financial Reporting: For-Profit [easy/L1]
-- Issues: #1
UPDATE questions SET
  choices = $EXPL$["Timeliness of the information","Comparability across entities","Faithful representation of events","Understandability to users"]$EXPL$::jsonb
WHERE id = 4708;

-- Q4709: Financial Reporting: For-Profit [easy/L1]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (D): Under the FASB Conceptual Framework (SFAC No. 6, paragraph 82), gains are defined as increases in equity from peripheral or incidental transactions of an entity, distinct from revenues or investments by owners. A land sale outside core operations fits this definition precisely.
Wrong (A): Revenue arises from an entity''s ongoing major or central operations, not from peripheral transactions like selling surplus land.
Wrong (B): Expenses are decreases in equity from delivering goods or services in the entity''s core operations, not increases from incidental transactions.
Wrong (C): Comprehensive income is the total change in equity from non-owner sources for the period and is a broader measure, not a specific element describing peripheral gains.$EXPL$
WHERE id = 4709;

-- Q4711: Financial Reporting: For-Profit [medium/L2]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (B): Under ASC 105-10-05 and SFAC No. 8 (QC6-QC10), relevance means information has predictive value, confirmatory value, or both, enabling it to make a difference in the decisions made by users. Without relevance, information cannot be useful regardless of other qualities.
Wrong (A): Information that is free from error and complete describes faithful representation under ASC 105-10-05 (QC12), the other fundamental characteristic, not relevance.
Wrong (C): Information that can be independently verified describes verifiability, which is an enhancing characteristic under SFAC No. 8 (QC26).
Wrong (D): Information presented in a clear and concise manner describes understandability, another enhancing characteristic (QC30), not a fundamental one.$EXPL$
WHERE id = 4711;

-- Q4712: Financial Reporting: For-Profit [medium/L1]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (C): Under ASC 105-10-05 and SFAC No. 8 (QC12), faithful representation requires three attributes: completeness (all necessary information is included), neutrality (free from bias), and freedom from error (no mistakes in description or process). All three must be present for a faithfully represented depiction.
Wrong (A): Predictive value, confirmatory value, and materiality are components of relevance under ASC 105-10-05 (QC6-QC11), the other fundamental characteristic.
Wrong (B): Relevance, timeliness, and comparability mix a fundamental characteristic with two enhancing characteristics and do not describe faithful representation.
Wrong (D): Verifiability, timeliness, and understandability are all enhancing qualitative characteristics, not attributes of faithful representation.$EXPL$
WHERE id = 4712;

-- Q4714: Financial Reporting: For-Profit [easy/L1]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (A): Under SFAC No. 8, Chapter 1, paragraph OB7 and ASC 205-40-50, the going concern assumption presumes the entity will continue in operation long enough to carry out its existing objectives and commitments. This assumption underlies historical cost accounting, systematic depreciation, and the current/noncurrent balance sheet classification.
Wrong (B): Liquidating assets within 12 months describes liquidation-basis accounting under ASC 205-30, which is the opposite of the going concern presumption.
Wrong (C): Preparing financial statements on a tax basis is a special purpose framework choice unrelated to the going concern assumption.
Wrong (D): Distributing all earnings to shareholders annually describes a dividend policy, not the going concern assumption about continuity of operations.$EXPL$
WHERE id = 4714;

-- Q4715: Financial Reporting: For-Profit [medium/L2]
-- Issues: #1
UPDATE questions SET
  choices = $EXPL$["International Financial Reporting Standards as nonauthoritative guidance","Practices commonly found within the entity''s specific industry","Internal management preferences for financial statement presentation","Guidance within the ASC for analogous transactions or similar events"]$EXPL$::jsonb
WHERE id = 4715;

-- Q4717: Financial Reporting: For-Profit [medium/L2]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (C): Under SFAC No. 8 (QC20-QC25), comparability enables users to identify similarities and differences across entities and periods. Changing the depreciation method mid-stream disrupts period-to-period trend analysis, directly impairing comparability and requiring ASC 250-10-45 disclosures.
Wrong (A): Verifiability (QC26) means independent observers could reach consensus on the measurement. The analyst''s difficulty stems from inconsistent methods, not inability to verify amounts.
Wrong (B): Timeliness (QC29) means information is available early enough to influence decisions. The depreciation change does not affect when information is reported.
Wrong (D): Understandability (QC30) concerns clarity of presentation. The change impairs cross-period consistency, not the clarity of the reported figures themselves.$EXPL$
WHERE id = 4717;

-- Q4720: Financial Reporting: For-Profit [hard/L4]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (D): Under ASC 105-10-05 and SFAC No. 8 (QC8), financial information has predictive value if it can be used as input to processes employed by users to predict future outcomes. Prior-year revenue figures used to forecast future trends directly exemplify this forward-looking relevance component.
Wrong (A): Historical cost confirming an original purchase price illustrates confirmatory value under ASC 105-10-05 (QC9), not predictive value, because it validates a prior expectation rather than informing a forecast.
Wrong (B): An auditor verifying inventory counts demonstrates verifiability, an enhancing qualitative characteristic, not a component of relevance.
Wrong (C): Disclosing accounting policies in the notes supports understandability and comparability but does not itself illustrate predictive value.$EXPL$
WHERE id = 4720;

-- Q4722: Financial Reporting: For-Profit [hard/L2]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (C): Under the FASB Conceptual Framework (SFAC No. 5, paragraphs 63-70), recognition requires the item to meet the definition of a financial statement element and possess a relevant attribute measurable with sufficient reliability. Both criteria must be satisfied before an item appears in the body of the financial statements.
Wrong (A): Being denominated in a foreign currency is not a recognition criterion; many recognized items are in the reporting currency, and foreign currency is a measurement consideration, not a gating requirement.
Wrong (B): Footnote disclosure and board approval are not recognition criteria under the Conceptual Framework; disclosure supplements recognized amounts but does not gate recognition.
Wrong (D): While materiality affects reporting, SEC authorization is not a recognition criterion under GAAP. Recognition depends on element definition and measurability, not regulatory approval.$EXPL$
WHERE id = 4722;

-- Q4725: Financial Reporting: For-Profit [hard/L2]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (B): Under the FASB Conceptual Framework (SFAC No. 5, paragraph 67b), current replacement cost is the amount of cash that would be required to acquire the same or an equivalent asset today. It reflects current market acquisition conditions for equivalent service capacity.
Wrong (A): Historical cost records the original purchase price at the transaction date and does not update for current market conditions, so it does not reflect what is currently required.
Wrong (C): Present value of future cash flows measures the discounted expected inflows or outflows, reflecting an income-based measurement rather than the current acquisition cost of an equivalent asset.
Wrong (D): Net realizable value represents selling price less completion and disposal costs, an exit-price concept from inventory accounting (ASC 330), not the entry-price replacement concept.$EXPL$
WHERE id = 4725;

-- Q4751: Accounting Changes and Error Corrections [medium/L2]
-- Issues: #1
UPDATE questions SET
  choices = $EXPL$["A change in accounting principle accounted for retrospectively","An estimate change effected by a principle change, applied prospectively","An error correction that requires prior-period restatement","A change in reporting entity requiring retrospective application"]$EXPL$::jsonb
WHERE id = 4751;

-- Q4764: Accounting Changes and Error Corrections [easy/L2]
-- Issues: #1
UPDATE questions SET
  choices = $EXPL$["A principle change affects only future periods; an estimate change is retrospective","A principle change adopts a different method; an estimate change revises an assumption","Both are treated identically under ASC 250 using prospective application","An estimate change always requires restatement of prior-period financial statements"]$EXPL$::jsonb
WHERE id = 4764;

-- Q4771: State and Local Government [medium/L2]
-- Issues: #1
UPDATE questions SET
  choices = $EXPL$["The goods are received and the related invoice is paid","A purchase order or contract is issued for goods or services","The annual operating budget is formally adopted by the council","The fiscal year ends and outstanding commitments are reviewed"]$EXPL$::jsonb
WHERE id = 4771;
