-- Migration: Quality fix -- AUD batch 35 (30 questions)
-- Generated by generate-quality-scaffold.ts
-- Issues: #1 (giveaway longest), #3 (incomplete explanation)

-- Q4690: Other Information and Supplementary Information [medium/L2]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["The supplementary information is complete and accurate in every respect","The supplementary information is fairly stated, in all material respects, in relation to the statements as a whole","The supplementary information complies with all applicable regulatory requirements","The supplementary information is more reliable than the basic financial statements"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (B): Under AU-C 725, when reporting on supplementary information in relation to the audited financial statements as a whole, the auditor opines on whether it is fairly stated in all material respects in relation to the financial statements as a whole. This is a lower threshold than opining on the information taken by itself.
Wrong (A): The opinion addresses fair statement in relation to the financial statements, not completeness and accuracy in all respects.
Wrong (C): The opinion relates to fair presentation relative to the financial statements, not regulatory compliance.
Wrong (D): Supplementary information is not characterized as more or less reliable than the basic statements.$EXPL$
WHERE id = 4690;

-- Q4692: Other Information and Supplementary Information [hard/L2]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["Include a paragraph noting the omission without modifying the opinion on the financial statements","Issue a qualified opinion on the financial statements due to the omission of required information","Refuse to issue the audit report until all required supplementary information is included","Issue an adverse opinion because omitted RSI renders the statements misleading"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (A): Under AU-C 730, if RSI required by GASB is omitted, the auditor includes an other-matter paragraph noting the omission. The omission does not modify the opinion on the basic financial statements because RSI is not part of those statements.
Wrong (B): Omission of RSI does not warrant a qualified opinion since RSI is supplementary, not part of the basic financial statements.
Wrong (C): The auditor has no basis to refuse the report; noting the omission in the report is the appropriate response.
Wrong (D): An adverse opinion addresses pervasive misstatements in the financial statements, not missing RSI.$EXPL$
WHERE id = 4692;

-- Q4695: Other Information and Supplementary Information [easy/L2]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["An integral part of the audited financial statements subject to the audit opinion","Required supplementary information mandated by the applicable framework","Other information that the auditor reads and considers for material inconsistencies","Information entirely outside the scope of the auditor''s consideration"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (C): Under AU-C 720, an unaudited five-year financial summary in the annual report is other information. The auditor reads it and considers whether it is materially inconsistent with the audited financial statements or the auditor''s knowledge obtained during the audit.
Wrong (A): The summary is not audited and is not part of the basic financial statements covered by the audit opinion.
Wrong (B): RSI is specifically designated by the applicable framework; an unaudited summary does not meet that definition.
Wrong (D): The auditor has a responsibility to read other information accompanying the audited statements.$EXPL$
WHERE id = 4695;

-- Q4696: Other Information and Supplementary Information [hard/L2]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["Issue a qualified opinion on the financial statements to alert users to the inconsistency","Accept management''s decision and take no further action regarding the matter","Describe the inconsistency in an other-matter paragraph or take other appropriate action","Adjust the financial statements so they agree with the other information presented"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (C): Under AU-C 720.A8, if management refuses to correct a material inconsistency in the other information and the financial statements are correct, the auditor should describe the inconsistency in an other-matter paragraph, withhold the report, or withdraw from the engagement.
Wrong (A): The financial statements are correct, so no qualification of the opinion is warranted.
Wrong (B): The auditor cannot simply accept a material inconsistency; professional standards require action.
Wrong (D): The financial statements are not in error, so adjusting them to match incorrect other information is inappropriate.$EXPL$
WHERE id = 4696;

-- Q4697: Other Information and Supplementary Information [medium/L2]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["Can be presented in a separate report or as an other-matter paragraph in the auditor''s report","Must always be presented in a separate stand-alone report on the supplementary information","Must be combined with the financial statement opinion in a single unified paragraph","Cannot appear anywhere within the auditor''s report on the financial statements"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (A): Under AU-C 725, the auditor''s opinion on supplementary information in relation to the financial statements as a whole may be presented in a separate report or as an other-matter paragraph in the auditor''s report on the financial statements. Either format is acceptable.
Wrong (B): A separate report is one option but is not required; an other-matter paragraph is equally acceptable.
Wrong (C): The supplementary information opinion is distinct from the financial statement opinion and is not combined in a single paragraph.
Wrong (D): Presenting the opinion in the auditor''s report via an other-matter paragraph is specifically permitted.$EXPL$
WHERE id = 4697;

-- Q4698: Other Information and Supplementary Information [easy/L2]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["The auditor bears no responsibility whatsoever for the other information presented","The auditor must ensure the accuracy of all other information in the annual report","The auditor audits the other information and issues a separate opinion on it","The auditor reads the other information for inconsistencies but does not audit it"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (D): Under AU-C 720, the auditor''s responsibility for other information is limited to reading it and considering whether it is materially inconsistent with the audited financial statements or the auditor''s knowledge. The auditor does not audit or express an opinion on it.
Wrong (A): The auditor does have a limited responsibility to read other information and identify material inconsistencies.
Wrong (B): The auditor is not responsible for ensuring accuracy; the responsibility is limited to reading and considering consistency.
Wrong (C): The auditor does not audit other information or issue a separate opinion on it.$EXPL$
WHERE id = 4698;

-- Q4699: Other Information and Supplementary Information [hard/L2]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["Part of the basic financial statements included in the audit opinion","Other information with no additional reporting requirement beyond reading","Supplementary information reported on in relation to the financial statements as a whole","Required supplementary information prescribed by GASB standards for note disclosure"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (C): Under the Uniform Guidance (2 CFR 200) and AU-C 725, the schedule of expenditures of federal awards is supplementary information that the auditor reports on in relation to the financial statements as a whole. The auditor opines on whether it is fairly stated in all material respects.
Wrong (A): The schedule is not part of the basic financial statements; it accompanies them as supplementary information.
Wrong (B): The schedule requires the auditor to issue an opinion, not merely read it as other information.
Wrong (D): The schedule is required by federal regulation (Uniform Guidance), not by GASB, and is classified as supplementary information rather than RSI.$EXPL$
WHERE id = 4699;

-- Q4700: Other Information and Supplementary Information [medium/L2]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["Audit the supplementary information as though an engagement had been established","Request that management remove all supplementary information from the document","Ignore the supplementary information entirely since no engagement exists","Include an other-matter paragraph stating the information has not been audited"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (D): Under AU-C 725, when supplementary information accompanies audited financial statements but the auditor has not been engaged to report on it, the auditor should include an other-matter paragraph indicating that the information has not been subjected to auditing procedures and the auditor does not express an opinion on it.
Wrong (A): The auditor has no obligation to audit supplementary information without a specific engagement to do so.
Wrong (B): The auditor cannot require management to remove information; an other-matter paragraph is the appropriate response.
Wrong (C): The auditor cannot ignore the supplementary information; professional standards require the disclaimer paragraph.$EXPL$
WHERE id = 4700;

-- Q4701: Other Information and Supplementary Information [easy/L1]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["The other information contradicts information in the audited statements and could undermine credibility","The other information uses a different format or layout than the financial statements","The other information provides greater detail than what appears in the financial statements","The other information is printed on physically different paper than the financial statements"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (A): Under AU-C 720, a material inconsistency exists when other information contradicts information in the audited financial statements in a way that could undermine the credibility of those statements. The scenario''s revenue growth discrepancy is a clear example.
Wrong (B): Differences in formatting or layout do not constitute a material inconsistency under auditing standards.
Wrong (C): Additional detail is not a contradiction; material inconsistency requires conflicting information.
Wrong (D): Physical presentation characteristics are unrelated to the concept of material inconsistency.$EXPL$
WHERE id = 4701;

-- Q4702: Other Information and Supplementary Information [easy/L2]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["The RSI has been audited and is covered by the audit opinion on the statements","The auditor guarantees the accuracy and completeness of all RSI presented","The RSI is considered more reliable than the basic financial statements themselves","The auditor applied limited procedures to the RSI but did not audit it"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (D): Under AU-C 730, the auditor''s report on RSI states that certain limited procedures (inquiries of management and comparison for consistency) were applied but the RSI was not audited. The auditor does not express an opinion or provide any assurance on it.
Wrong (A): RSI is not audited and is not covered by the opinion on the basic financial statements.
Wrong (B): The auditor provides no guarantee regarding RSI; only limited procedures are applied.
Wrong (C): RSI is not characterized as more or less reliable than the basic financial statements.$EXPL$
WHERE id = 4702;

-- Q4703: Other Information and Supplementary Information [hard/L2]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["Has no further responsibility for information received after the report date","Must re-audit the financial statements to reflect the new other information","Must reissue the auditor''s report with a revised date to cover the annual report","Still must read the other information and consider it for material inconsistencies"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (D): Under AU-C 720.14, even if other information is received after the date of the auditor''s report, the auditor still has a responsibility to read it and consider whether there is a material inconsistency with the audited financial statements or a material misstatement of fact.
Wrong (A): The auditor''s responsibility for other information extends beyond the report date when the information is received before issuance of the financial statements.
Wrong (B): Receiving other information does not require re-auditing the financial statements.
Wrong (C): The auditor is not required to reissue the report solely because other information was received later.$EXPL$
WHERE id = 4703;

-- Q4704: Other Information and Supplementary Information [medium/L2]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["A matter requiring no further auditor action or communication with management","A normal difference between narrative descriptions and quantitative financial data","A reason to modify the audit opinion on the basic financial statements","A material inconsistency that the auditor should discuss and resolve with management"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (D): Under AU-C 720, a contradiction between the MD&A''s description of declining profit margins and the financial statements'' evidence of stable margins is a material inconsistency. The auditor should discuss the matter with management and request correction of the incorrect information.
Wrong (A): A material inconsistency requires the auditor to take action, including discussing it with management.
Wrong (B): This is not a normal narrative-quantitative difference; it is a factual contradiction that could mislead users.
Wrong (C): If the financial statements are correct, the inconsistency is in the other information and does not warrant modifying the audit opinion.$EXPL$
WHERE id = 4704;

-- Q4705: Specific Areas and Transactions [hard/L2]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["Accept management''s discount rate since management has the most knowledge of the property","Disclaim an opinion because fair value measurements are inherently too subjective to audit","Require management to apply the highest available discount rate for conservatism","Evaluate the rate''s reasonableness by comparing it to market rates and assessing bias"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (D): Under AU-C 540, the auditor evaluates the reasonableness of management''s assumptions by comparing them to market benchmarks, considering risk characteristics of the asset, and assessing whether the selection indicates management bias toward higher valuations. An unreasonably low discount rate inflates fair value.
Wrong (A): The auditor cannot simply accept management''s rate without evaluating its reasonableness against market data.
Wrong (B): Fair value measurements are auditable; the auditor evaluates assumptions and models, not disclaims.
Wrong (C): Requiring the highest rate is not appropriate; the auditor evaluates reasonableness, not prescribes specific inputs.$EXPL$
WHERE id = 4705;

-- Q5023: Misstatements and Control Deficiencies [medium/L2]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["Whether the misstatement masks an earnings trend or affects covenant compliance","Whether the misstatement was detected through analytical procedures or substantive tests","Whether the misstatement originated in the current period or a prior period","Whether similar misstatements have been found at other comparable public companies"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (A): Under AU-C 450.A16-.A17, qualitative factors may cause a quantitatively immaterial misstatement to be considered material. These include whether the misstatement masks an earnings trend, converts a loss to income, affects regulatory compliance, or conceals management compensation.
Wrong (B): The detection method is an audit efficiency consideration, not a qualitative factor in evaluating materiality of the misstatement itself.
Wrong (C): The period of origin is relevant to carryforward analysis, but the key qualitative concern here is the effect on trends and covenants.
Wrong (D): The existence of similar misstatements at other entities is not a qualitative factor under AU-C 450.$EXPL$
WHERE id = 5023;

-- Q5026: Misstatements and Control Deficiencies [medium/L4]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["Evaluate the fraud''s implications on the audit, including the reliability of management representations","Conclude the misstatement is immaterial since it falls below the materiality threshold","Report the fraud directly to law enforcement before communicating with management","Reclassify the misstatement as a judgmental difference involving management estimates"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (A): Under AU-C 240.35-.36, when a misstatement results from fraud, the auditor must consider its implications for other audit aspects, particularly the reliability of management representations. The intentional nature raises questions about management integrity regardless of amount.
Wrong (B): Fraud-related misstatements cannot be evaluated solely on quantitative grounds; the intentional nature elevates the concern beyond dollar materiality.
Wrong (C): The auditor''s primary obligation is to communicate with those charged with governance, not to report directly to law enforcement absent a legal duty.
Wrong (D): Intentional reclassification of personal expenses is fraud, not a judgmental difference involving estimates.$EXPL$
WHERE id = 5026;

-- Q5292: Misstatements and Control Deficiencies [medium/L3]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["The reversal eliminates the misstatement entirely, requiring no current-year consideration","The iron curtain approach still requires evaluating the cumulative balance sheet effect","The auditor must require management to restate the prior-year financial statements first","The reversal automatically converts the misstatement from a factual to a projected type"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (B): Under AU-C 450.A16, the iron curtain approach evaluates the cumulative effect on the ending balance sheet, while the rollover approach focuses on the current-year income statement effect. Even though the income statement impact reverses, the balance sheet may still carry effects of prior-year misstatements.
Wrong (A): A reversal in the income statement does not eliminate the need to evaluate cumulative balance sheet effects under the iron curtain methodology.
Wrong (C): Restatement is not automatically required; the auditor evaluates whether the aggregate effect is material.
Wrong (D): A reversal does not change the classification of a misstatement from factual to projected.$EXPL$
WHERE id = 5292;

-- Q6139: Misstatements and Control Deficiencies [hard/L3]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["The lack of segregation of duties is automatically a material weakness regardless of compensating controls","The compensating control eliminates the deficiency entirely, so no communication to governance is required","The classification depends solely on the volume of transactions below $5,000 not subject to review","The deficiency remains at least significant, but the compensating control may prevent material weakness"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (D): Under AU-C 265.A10, compensating controls can mitigate deficiency severity. While lack of segregation of duties is inherently a deficiency, an effective compensating control like detailed management review may reduce the likelihood of undetected material misstatement, potentially preventing classification as a material weakness.
Wrong (A): AU-C 265 requires evaluating the totality of controls, including compensating controls, before classifying severity; it is not automatically a material weakness.
Wrong (B): Compensating controls mitigate but do not eliminate the underlying deficiency; it still warrants communication as at least a significant deficiency.
Wrong (C): Classification considers both magnitude and likelihood holistically, not solely the volume of unreviewed transactions.$EXPL$
WHERE id = 6139;

-- Q6233: Misstatements and Control Deficiencies [medium/L2]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["A deficiency not requiring communication because it involves routine cash transactions","A significant deficiency only, because the bookkeeper appears competent and trustworthy","At least a significant deficiency, and likely a material weakness given the dollar magnitude","An operational matter that falls outside the scope of the financial statement audit"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (C): Under AU-C 265.A12, lack of segregation of duties over significant asset classes indicates at least a significant deficiency. When one person controls recording, custody, and reconciliation of $6.5 million in cash, there is a reasonable possibility of material misstatement, meeting the definition of a material weakness.
Wrong (A): A segregation of duties deficiency over a significant dollar amount must be communicated regardless of transaction routine.
Wrong (B): Personal trustworthiness cannot substitute for structural controls; auditing standards evaluate control design, not individual character.
Wrong (D): Segregation of duties over financial assets is directly within the scope of a financial statement audit.$EXPL$
WHERE id = 6233;

-- Q6406: Misstatements and Control Deficiencies [hard/L4]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["Disregard the reversal since the misstatement was already evaluated in the prior year","Evaluate how the reversal affects current-year income alongside any new misstatements","Accept the favorable impact because it reduces the risk of current-year material misstatement","Require a prior-period adjustment to completely eliminate the carryforward effect"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (B): Under AU-C 450.10-.11, the auditor must evaluate prior-period uncorrected misstatements that affect current-period financial statements. A reversing overstatement inflates current-year income and must be assessed in combination with any new misstatements to determine aggregate impact.
Wrong (A): Prior-year carryforward effects on the current period cannot be ignored; they must be included in the current-year evaluation.
Wrong (C): A favorable income effect from a reversal does not reduce risk; it creates a current-year misstatement of operating results.
Wrong (D): A prior-period adjustment is a management decision; the auditor evaluates materiality and may request correction but does not unilaterally require restatement.$EXPL$
WHERE id = 6406;

-- Q6422: Misstatements and Control Deficiencies [medium/L3]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["The deficiency is not reportable because no actual misstatement resulted from the weakness","The deficiency is a significant deficiency because it involves a segregation of duties conflict","The deficiency is a material weakness given the magnitude and likelihood of potential misstatement","The deficiency requires additional testing before any severity classification can be determined"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (C): Under AU-C 265.A8, severity depends on the magnitude of potential misstatement and likelihood of occurrence. The lack of segregation over $8 million in annual transactions creates both substantial magnitude and a reasonable possibility of occurrence, meeting the material weakness threshold.
Wrong (A): Deficiency evaluation considers potential misstatements, not only those actually detected; the absence of a detected error does not make the deficiency unreportable.
Wrong (B): Significant deficiency understates the severity given the $8 million magnitude and lack of independent review.
Wrong (D): The auditor has sufficient information to classify severity based on the control design and transaction volume.$EXPL$
WHERE id = 6422;

-- Q6465: Misstatements and Control Deficiencies [medium/L3]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["The selective correction pattern suggests possible bias, requiring reassessment of materiality","The uncorrected misstatements are acceptable because they fall well below the materiality level","The auditor must independently correct the misstatements regardless of management''s decisions","Management''s correction of some misstatements demonstrates good faith and eliminates bias"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (A): Under AU-C 450.A13, the auditor considers whether the pattern of uncorrected misstatements indicates possible management bias. Selectively correcting only income-decreasing misstatements while leaving income-increasing ones uncorrected is a strong indicator of bias affecting the overall materiality assessment.
Wrong (B): Even though the dollar amount is below materiality, the bias pattern is a qualitative factor that may render the uncorrected misstatements material.
Wrong (C): The auditor does not independently correct misstatements; the auditor evaluates their effect and communicates with management and governance.
Wrong (D): Correcting some misstatements does not negate bias concerns when the correction pattern consistently favors a particular outcome.$EXPL$
WHERE id = 6465;

-- Q7604: Specific Areas and Transactions [hard/L3]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["Management''s estimate is unreasonable because it falls below the midpoint of the auditor''s range","Management''s estimate is within the reasonable range but the low-end pattern warrants further evaluation","Management''s estimate must be adjusted to the midpoint of the auditor''s range to eliminate bias","Management''s estimate should be disallowed because the reasonable range exceeds 10% of the amount"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (B): Under AU-C 540, when the auditor develops a range, any point within that range is considered reasonable. Management''s $3.9 million falls within $3.8M-$5.1M and is acceptable. However, the auditor should evaluate whether a pattern of consistently selecting the low end across multiple estimates indicates management bias.
Wrong (A): Falling below the midpoint does not make an estimate unreasonable; the entire range represents acceptable outcomes.
Wrong (C): The auditor does not require adjustment to the midpoint; any point within the range is acceptable.
Wrong (D): The width of the reasonable range does not disqualify the estimate; the test is whether the estimate falls within the range.$EXPL$
WHERE id = 7604;

-- Q7612: Specific Areas and Transactions [hard/L4]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["No action is required because the fire occurred after the audit report date was established","Adjust the December 31, 2025 financial statements to reflect the $6.2 million uninsured loss","Evaluate whether the fire is disclosed as a Type II subsequent event and assess going concern","Require Creekside to delay issuance until the insurance claim is fully resolved"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (C): Under AU-C 560, facts discovered after the report date but before issuance require the auditor to evaluate whether the statements need revision. A March 5 fire is a Type II subsequent event requiring note disclosure, not adjustment. Given the 40% asset loss, the auditor should also assess going concern implications.
Wrong (A): The auditor has responsibility for subsequent events through the issuance date, not just the report date.
Wrong (B): A post-year-end fire is a Type II event (new conditions) requiring disclosure, not adjustment of year-end balances.
Wrong (D): Delaying issuance for insurance resolution is not required; disclosure of the event is the appropriate treatment.$EXPL$
WHERE id = 7612;

-- Q7939: Written Representations [medium/L3]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["Have been verified and confirmed by an independent third-party pricing service","Are reasonable and reflect management''s intent and ability to carry out planned actions","Will produce valuations that match quoted market prices for comparable instruments","Were selected by the auditor and subsequently approved by the client''s management"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (B): Under AU-C 540.22 and AU-C 580.A9, the auditor obtains representations that significant assumptions used in fair value measurements are reasonable and reflect management''s intent and ability to carry out specific courses of action. This addresses the subjective nature of Level 3 inputs.
Wrong (A): Independent pricing verification is a substantive procedure the auditor might perform, not a management representation required by the standard.
Wrong (C): Level 3 investments lack quoted market prices by definition; representations cannot guarantee matching nonexistent quotes.
Wrong (D): Assumptions are management''s responsibility; they are not selected by the auditor.$EXPL$
WHERE id = 7939;

-- Q8320: Written Representations [hard/L4]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["Accept management''s verbal assurance and proceed without further action on the prior year","Withdraw from the engagement because the prior-year deficiency indicates unreliable management","Require the representation letter to cover all periods presented, including prior-year fraud and related parties","Issue a disclaimer on the prior-year comparatives and an unmodified opinion on the current year"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (C): Under AU-C 580.14, written representations cover all periods referred to in the auditor''s report. When comparative financial statements are presented, the successor auditor should obtain representations covering all periods, including specific representations about fraud and related parties for the prior period.
Wrong (A): Verbal assurances do not satisfy AU-C 580 requirements; written representations are mandatory.
Wrong (B): Omissions in the prior-year letter do not necessarily indicate management unreliability; obtaining complete representations is the appropriate remedy.
Wrong (D): A disclaimer is not warranted when the auditor can obtain the required representations for all presented periods.$EXPL$
WHERE id = 8320;

-- Q8330: Written Representations [medium/L3]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["Backdate the representation letter to match the March 10 report date for consistency","Consider revising the report date to March 15 or obtain supplemental representations","Restart the engagement from the planning phase because the timing is invalid","Issue the report without the signed letter and document the delay in the workpapers"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (B): Under AU-C 580.15, the representation letter should be dated no earlier than the date of the auditor''s report. If received after the report date, the auditor should either revise the report date or obtain a letter dated as of the original date with supplemental coverage through receipt date.
Wrong (A): Backdating falsifies the date on which management actually signed, which is inappropriate under professional standards.
Wrong (C): A timing discrepancy in the representation letter does not invalidate the entire engagement or require restarting.
Wrong (D): Issuing a report without the required signed representation letter violates AU-C 580.$EXPL$
WHERE id = 8330;

-- Q8669: Written Representations [hard/L4]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["Issue a disclaimer for the full year because the former CFO refused to provide representations","Obtain full-year representations from the current CFO and perform additional pre-October procedures","Limit the audit scope to October through December and disclose the scope limitation","Accept the former CFO''s refusal and note it as a subsequent event in the financial statements"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (B): Under AU-C 580.A11, the representation letter is obtained from current management, who is responsible for financial statements covering the full period. The current CFO can provide representations for the full year. The auditor should also perform additional procedures to address increased risk for the pre-October period.
Wrong (A): The former officer''s refusal does not require a disclaimer because current management can provide representations covering the full period.
Wrong (C): The audit cannot be arbitrarily limited to a partial year; current management is responsible for the full-year statements.
Wrong (D): A former officer''s refusal to provide representations is not a subsequent event; it is an audit procedure matter.$EXPL$
WHERE id = 8669;

-- Q8813: Written Representations [hard/L3]
-- Issues: #1, #3
UPDATE questions SET
  choices = $EXPL$["Automatically issue a disclaimer of opinion because any representation refusal is a scope limitation","Evaluate the refusal''s implications and determine whether additional procedures or modification is needed","Accept the refusal without further action because additional representations are entirely discretionary","Withdraw from the engagement immediately because the refusal indicates management lacks integrity"]$EXPL$::jsonb,
  explanation = $EXPL$Correct (B): Under AU-C 580.20-.21, when management does not provide a requested representation, the auditor evaluates the implications, considers the effect on reliability of other representations, and determines whether additional procedures are needed or a modified opinion is warranted. Professional judgment is required.
Wrong (A): Automatic disclaimer applies only to refusals of required representations under AU-C 580; additional representations require the auditor to exercise judgment.
Wrong (C): The auditor cannot simply accept a refusal without evaluating its implications for the audit.
Wrong (D): Refusal of an additional representation does not automatically indicate lack of integrity; the auditor evaluates the reasons and circumstances.$EXPL$
WHERE id = 8813;

-- Q1: Ethics and Independence [easy/L1]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (A): Under the AICPA Code of Professional Conduct ET 1.270, a direct financial interest owned by an auditor''s immediate family member (spouse) impairs independence regardless of materiality. This is a bright-line rule with no exceptions for size or nature of the interest.
Wrong (B): Tax return preparation is generally a permissible nonattest service when the client makes all tax decisions and appropriate safeguards are applied under ET 1.296.
Wrong (C): Management advisory services do not automatically impair independence, provided the member does not assume management responsibilities and appropriate safeguards exist.
Wrong (D): Sharing an office building with a client is not an independence-impairing relationship under the AICPA Code.$EXPL$
WHERE id = 1;

-- Q2: Ethics and Independence [medium/L2]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (D): Under the AICPA Code of Professional Conduct ET 1.295 (Management Participation), independence is impaired when a member assumes a management responsibility for an attest client. Making management decisions such as hiring, authorizing transactions, or directing operations constitutes assuming management''s role.
Wrong (A): Preparing tax returns based on client-provided information is generally permissible under ET 1.296 with appropriate safeguards and client oversight.
Wrong (B): Assisting with software implementation is permissible when the client makes all management decisions regarding the system and the member does not assume a management role.
Wrong (C): Providing advice on internal control improvements is an advisory service that does not impair independence, provided management evaluates and implements the recommendations.$EXPL$
WHERE id = 2;
