-- Migration: Quality fix -- REG batch 28 (30 questions)
-- Generated by generate-quality-scaffold.ts
-- Issues: #1 (giveaway longest), #3 (incomplete explanation)

-- Q2399: Circular 230 [hard/L2]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (C): Under Circular 230 Section 10.34, undisclosed return positions must meet the substantial authority standard. A mere reasonable basis is insufficient without disclosure. The more-likely-than-not standard applies only to tax shelters and reportable transactions, not all positions.
Wrong (A): Reasonable basis is the minimum only for disclosed positions. Undisclosed positions require the higher substantial authority standard.
Wrong (B): The more-likely-than-not standard applies to tax shelters and reportable transactions, not to ordinary return positions.
Wrong (D): Not all positions must meet the more-likely-than-not standard; that threshold is reserved for tax shelters and reportable transactions under Section 10.35.$EXPL$
WHERE id = 2399;

-- Q2400: Circular 230 [medium/L1]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (A): Under Circular 230 Section 10.50(c), censure is the least severe of the three primary disciplinary sanctions and constitutes a public reprimand. Importantly, censure does not restrict or terminate the practitioner''s right to practice before the IRS, unlike suspension or disbarment.
Wrong (B): A temporary prohibition from practicing describes suspension under Section 10.50(a), not censure.
Wrong (C): Circular 230 does not impose monetary penalties equal to the client''s tax deficiency as a disciplinary sanction.
Wrong (D): A permanent prohibition from practicing describes disbarment under Section 10.50(a), the most severe sanction.$EXPL$
WHERE id = 2400;

-- Q2401: Circular 230 [easy/L2]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (C): Under Circular 230 Section 10.23, a practitioner with a valid power of attorney must exercise due diligence by promptly informing the client of IRS correspondence and taking appropriate action within the scope of the engagement. This duty ensures the client''s interests and deadlines are protected.
Wrong (A): Responding without informing the client violates the practitioner''s obligation to keep the client informed of matters affecting their account.
Wrong (B): A practitioner cannot simply ignore IRS notices; the duty of prompt disposition applies regardless of the tax year involved.
Wrong (D): Returning the notice and redirecting correspondence abandons the practitioner''s responsibility under the power of attorney.$EXPL$
WHERE id = 2401;

-- Q2402: Circular 230 [hard/L2]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (D): Under Circular 230 Section 10.29, a practitioner may represent conflicting interests before the IRS if each party provides informed written consent after full disclosure of the conflict. The practitioner must also reasonably believe they can provide competent and diligent representation to each client.
Wrong (A): Dual representation is not automatically prohibited. Section 10.29 permits it with proper disclosure and written consent from each party.
Wrong (B): Spouses are not treated as one taxpayer for conflict-of-interest purposes; each spouse is a separate client requiring individual consent.
Wrong (C): Referral to separate practitioners is not mandatory. The practitioner may continue if informed written consent is obtained from both spouses.$EXPL$
WHERE id = 2402;

-- Q2403: Professional Ethics in Tax [easy/L4]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (A): Under AICPA SSTS No. 1, a CPA should not recommend a tax return position unless there is at least a realistic possibility of being sustained on its merits. Per IRC Sec. 6694, this aligns with the substantial authority standard for undisclosed positions and the reasonable basis standard for disclosed positions.
Wrong (B): The CPA need not believe the position will definitely be sustained. SSTS No. 1 requires only a realistic possibility, not certainty.
Wrong (C): A CPA cannot recommend a position based solely on client wishes without adequate legal support and authority.
Wrong (D): IRS pre-approval is not required. The CPA must independently evaluate the position against applicable tax authority.$EXPL$
WHERE id = 2403;

-- Q2404: Professional Ethics in Tax [medium/L1]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (B): Under AICPA SSTS No. 1, the realistic possibility standard requires approximately a one-in-three (33%) likelihood that the position will be sustained on its merits if challenged. This is the minimum confidence level before a CPA may recommend a position without disclosure.
Wrong (A): A greater than 50% chance describes the more-likely-than-not standard under IRC Sec. 6662(d)(2)(B), which is a higher threshold than realistic possibility.
Wrong (C): SSTS No. 1 does not require specific published IRS guidance authorizing each position taken on a return.
Wrong (D): A private letter ruling is not required. The realistic possibility standard is met through analysis of applicable tax authority, not IRS pre-approval.$EXPL$
WHERE id = 2404;

-- Q2405: Professional Ethics in Tax [easy/L1]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (D): Under Circular 230 Section 10.21, when a practitioner discovers a client''s noncompliance with tax obligations, the practitioner must promptly advise the client of the noncompliance, its consequences, and the corrective steps available. The obligation runs to the client, not to the government.
Wrong (A): Circular 230 does not require the practitioner to report the client to the IRS Criminal Investigation Division. The client-practitioner relationship is maintained.
Wrong (B): Termination is not automatically required. The practitioner must advise the client and may continue the engagement if the client takes corrective action.
Wrong (C): The practitioner cannot unilaterally file corrective returns on behalf of the client. The decision to amend rests with the client.$EXPL$
WHERE id = 2405;

-- Q2406: Professional Ethics in Tax [easy/L3]
-- Issues: #1
UPDATE questions SET
  choices = $EXPL$["SSTS No. 6 requires Walsh to recommend corrective action such as an amended return, balancing confidentiality, compliance duty, and the prohibition against aiding noncompliance","Walsh must immediately report the unreported income to the IRS because the duty to the tax system overrides client confidentiality","Walsh should ignore the error because SSTS No. 6 applies only to current-year returns and not to prior-year omissions","Walsh should silently withdraw without informing the client, because withdrawal alone eliminates any continuing ethical obligation"]$EXPL$::jsonb
WHERE id = 2406;

-- Q2407: Professional Ethics in Tax [easy/L1]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (A): Under AICPA SSTS No. 4 (Use of Estimates), a CPA may use estimates on a tax return when it is impracticable to obtain exact data and the CPA determines the estimates are reasonable based on known facts and circumstances. Estimates should not be presented as exact figures.
Wrong (B): SSTS No. 4 does not require specific IRS guidance authorizing estimates for a particular item. The standard permits estimates whenever exact data is unavailable.
Wrong (C): There is no $500 materiality threshold in SSTS No. 4. The standard applies based on reasonableness, not a fixed dollar amount.
Wrong (D): SSTS No. 4 explicitly permits the use of reasonable estimates. It does not require exact figures for every item on the return.$EXPL$
WHERE id = 2407;

-- Q2409: Professional Ethics in Tax [easy/L1]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (B): Under AICPA SSTS No. 2 (Answers to Questions on Returns), a CPA should make a reasonable effort to obtain information but may leave a question unanswered when the information is not readily available and the answer is not significant in determining the correct tax liability.
Wrong (A): A CPA cannot leave any question unanswered without limitation. SSTS No. 2 requires the CPA to evaluate whether the omission may cause the return to be deemed incomplete.
Wrong (C): A written client directive is not sufficient by itself. The CPA must independently assess the significance of the omitted answer.
Wrong (D): SSTS No. 2 does not require every question to be answered. It permits omissions when the information is unavailable and insignificant to the tax liability.$EXPL$
WHERE id = 2409;

-- Q2411: Professional Ethics in Tax [medium/L4]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (C): Under AICPA SSTS No. 5, a CPA may recommend a position contrary to a prior IRS administrative settlement when the facts and circumstances have changed or new legal authority supports the different position. The standard requires an objective basis to justify the departure.
Wrong (A): The mere passage of time does not justify departing from a prior settlement. SSTS No. 5 requires changed facts or new authority, not a waiting period.
Wrong (B): Client insistence alone is insufficient. The CPA must have an independent objective basis such as changed facts or new legal authority.
Wrong (D): The likelihood of a future audit is irrelevant. SSTS No. 5 requires substantive justification, not an assessment of audit risk.$EXPL$
WHERE id = 2411;

-- Q2412: Professional Ethics in Tax [easy/L1]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (D): Under AICPA SSTS No. 1, a CPA should not recommend a tax return position unless the CPA has a good-faith belief that the position has a realistic possibility of being sustained on its merits if challenged. This is generally interpreted as approximately a one-in-three likelihood.
Wrong (A): Certainty is not required. SSTS No. 1 sets the threshold at realistic possibility, which is well below absolute certainty.
Wrong (B): A private letter ruling is not required before recommending any position. The CPA evaluates the position against existing tax authority.
Wrong (C): A 75% probability exceeds the SSTS No. 1 standard. The realistic possibility threshold is approximately 33%, not 75%.$EXPL$
WHERE id = 2412;

-- Q2414: Professional Ethics in Tax [medium/L2]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (C): Under AICPA SSTS No. 6 (Knowledge of Error), when a CPA becomes aware of a possible error on a previously filed return, regardless of who prepared it, the CPA should promptly inform the client and recommend corrective measures such as filing an amended return.
Wrong (A): The CPA cannot ignore the error simply because another firm prepared the prior return. SSTS No. 6 applies regardless of who was the original preparer.
Wrong (B): The CPA should not contact the prior firm without the client''s consent. The obligation runs to the client, not the prior preparer.
Wrong (D): The CPA has no obligation or authority to report errors to the IRS whistleblower office. The duty is to advise the client of corrective action.$EXPL$
WHERE id = 2414;

-- Q2416: Professional Ethics in Tax [easy/L2]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (D): Under the AICPA Code of Professional Conduct, CPAs performing tax services must maintain integrity and objectivity. Unlike attest engagements, tax engagements do not require independence from the client, but the CPA must not subordinate professional judgment to client wishes.
Wrong (A): Independence identical to attest engagements is not required for tax services. The AICPA independence rules apply primarily to audit and review engagements.
Wrong (B): CPAs have ethical obligations beyond IRS requirements, including the AICPA Code of Professional Conduct and applicable SSTS standards.
Wrong (C): Client loyalty does not override all other professional obligations. The CPA must balance client advocacy with integrity and objectivity.$EXPL$
WHERE id = 2416;

-- Q2418: Professional Ethics in Tax [hard/L2]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (C): Under Circular 230 Section 10.21 and AICPA SSTS No. 6, when a CPA discovers that a client used fraudulent information on a return, the CPA must withdraw from the engagement and advise the client to take corrective action. The CPA must not sign any future returns affected by the fraud.
Wrong (A): The CPA cannot continue the engagement simply because the fraud was unknown at filing. Once discovered, the CPA must withdraw and cannot be complicit in ongoing noncompliance.
Wrong (B): Circular 230 does not require the practitioner to report the client directly to law enforcement absent a court order.
Wrong (D): The CPA cannot unilaterally file an amended return without the client''s authorization. The corrective action decision rests with the client.$EXPL$
WHERE id = 2418;

-- Q2419: Professional Ethics in Tax [medium/L2]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (D): Under AICPA SSTS No. 3, when a discrepancy exists between a third-party information return and the client''s claim, the CPA must make reasonable inquiries, request supporting documentation, and exercise professional judgment in determining the correct amount to report.
Wrong (A): Blindly accepting the 1099 amount without inquiry ignores the CPA''s duty to exercise professional judgment when information suggests a discrepancy.
Wrong (B): Splitting the difference has no basis in professional standards. SSTS No. 3 requires investigation, not arbitrary compromise.
Wrong (C): Accepting the client''s oral statement alone is insufficient. The CPA must request supporting documentation and evaluate the evidence before determining the correct amount.$EXPL$
WHERE id = 2419;

-- Q2421: Professional Ethics in Tax [easy/L2]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (C): Under the AICPA Code of Professional Conduct, independence rules apply primarily to attest (audit and review) engagements. A CPA may perform tax preparation and bookkeeping services for the same client without violating independence rules, since these are non-attest services.
Wrong (A): Performing both tax and bookkeeping services does not violate independence rules. An independence issue arises only if the CPA also performs attest services for the same client.
Wrong (B): No waiver from the state board is required for providing multiple non-attest services to the same client.
Wrong (D): No IRS disclosure is required for performing dual non-attest services. The IRS does not regulate AICPA independence standards.$EXPL$
WHERE id = 2421;

-- Q2423: Professional Ethics in Tax [medium/L2]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (A): Under SSTS No. 1 and IRC Section 280A(c), a home office deduction requires exclusive and regular use for business. When the taxpayer has an employer-provided office, the home office must also meet the convenience-of-the-employer test under Section 280A(c)(1). The CPA must evaluate these requirements before recommending the position.
Wrong (B): Working from home most of the week does not automatically qualify the deduction. The statutory requirements of exclusive use and employer convenience must still be met.
Wrong (C): A blanket refusal is inappropriate. SSTS No. 1 requires the CPA to evaluate whether the position has a reasonable basis before accepting or rejecting it.
Wrong (D): A partial deduction based on days worked at home is not how Section 280A operates. The deduction depends on meeting the statutory tests, not a day-ratio calculation.$EXPL$
WHERE id = 2423;

-- Q2425: Professional Ethics in Tax [easy/L2]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (C): Under Circular 230 Section 10.34(a), by signing a return as paid preparer, the CPA represents that the return is based on all information known to the practitioner and that the positions taken meet applicable standards, including at minimum a reasonable basis for each position.
Wrong (A): Signing a return does not guarantee freedom from audit. The CPA''s representation relates to the quality and basis of the positions taken, not audit likelihood.
Wrong (B): The CPA is not certifying personal verification of every transaction. The representation is that positions meet applicable standards based on known information.
Wrong (D): Signing the return does not create personal liability for the client''s tax deficiency. The CPA''s liability is limited to preparer penalties for noncompliance with standards.$EXPL$
WHERE id = 2425;

-- Q2426: Professional Ethics in Tax [hard/L2]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (A): Under AICPA SSTS No. 7, when a CPA becomes aware of significant new developments that affect previously provided written advice and maintains an ongoing client relationship, the CPA should consider informing the client of the changed circumstances. This reflects a continuing obligation tied to the advisory relationship.
Wrong (B): While SSTS No. 7 does not impose an absolute mandatory update duty, a CPA with an ongoing relationship should consider updating the client when significant adverse developments arise.
Wrong (C): An amended return is not automatically required. The CPA''s obligation is to inform the client of the changed authority, not to unilaterally file amended returns.
Wrong (D): Waiting for an IRS challenge is not consistent with the CPA''s advisory duty. Proactive communication about adverse developments protects the client''s interests.$EXPL$
WHERE id = 2426;

-- Q2427: Professional Ethics in Tax [medium/L2]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (C): Under AICPA SSTS No. 3, a CPA may generally rely on client-provided information but must not ignore implications of information known to the CPA. When income appears significantly understated, the CPA must make reasonable inquiries, evaluate the reliability of records, and document conclusions.
Wrong (A): Simply accepting records that appear incomplete ignores the CPA''s duty under SSTS No. 3 to inquire when known information raises concerns about reliability.
Wrong (B): The CPA is not required to report the client to the IRS. SSTS No. 3 calls for inquiry and professional judgment, not refusal and reporting.
Wrong (D): Adjusting income to match industry averages has no basis in SSTS No. 3. The CPA should investigate the actual facts rather than apply arbitrary benchmarks.$EXPL$
WHERE id = 2427;

-- Q2430: Tax Procedures [easy/L1]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (A): Under IRC Section 6501(c), there is no statute of limitations on assessment when the taxpayer files a false or fraudulent return with the intent to evade tax, or when no return is filed at all. The IRS may assess additional tax at any time in these circumstances.
Wrong (B): Filing a late return does not eliminate the statute of limitations. The three-year period generally runs from the actual filing date under Section 6501(a).
Wrong (C): Underpaying estimated taxes does not affect the assessment statute of limitations. Estimated tax penalties are governed separately under Section 6654.
Wrong (D): Claiming too many exemptions does not create an unlimited assessment period. This may trigger other penalties but does not override the standard limitations period.$EXPL$
WHERE id = 2430;

-- Q2432: Tax Procedures [easy/L1]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (A): Under IRC Sec. 7803(e) (as amended by the Taxpayer First Act), after receiving a 30-day letter, a taxpayer may request a conference with the Independent Office of Appeals for an independent administrative review. For deficiencies over $25,000, a formal written protest is required.
Wrong (B): The U.S. Supreme Court does not hear tax disputes directly. Tax litigation begins in the Tax Court, District Court, or Court of Federal Claims.
Wrong (C): A written protest goes to the Appeals Office, not back to the examining agent. The examiner''s role ends once the 30-day letter is issued.
Wrong (D): Congressional representatives have no formal role in the IRS appeals process. The administrative appeal is handled through the Independent Office of Appeals.$EXPL$
WHERE id = 2432;

-- Q2433: Tax Procedures [easy/L2]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (C): Under 28 U.S.C. Sec. 1346(a)(1), the U.S. District Court has jurisdiction over federal tax refund suits and is the only court that provides the right to a jury trial in tax disputes. The taxpayer must first pay the assessed tax and file a refund claim under IRC Sec. 7422(a).
Wrong (A): The U.S. Tax Court adjudicates deficiency cases before judges without juries. It does not offer jury trials.
Wrong (B): The U.S. Court of Federal Claims under 28 U.S.C. Sec. 1491 also hears tax refund suits but conducts bench trials only, with no jury right.
Wrong (D): The IRS Appeals Office is an administrative body, not a court. It cannot conduct trials or provide jury proceedings.$EXPL$
WHERE id = 2433;

-- Q2434: Tax Procedures [easy/L2]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (A): Under IRC Section 6651(a)(1), the failure-to-file penalty is 5% of the unpaid tax for each month or part of a month the return is late, up to a maximum of 25%. This penalty is separate from and in addition to the failure-to-pay penalty.
Wrong (B): The 0.5% per month rate is the failure-to-pay penalty under Section 6651(a)(2), not the failure-to-file penalty.
Wrong (C): The failure-to-file penalty is percentage-based, not a flat amount. It is calculated as a percentage of the unpaid tax for each month of delinquency.
Wrong (D): The penalty is 5% per month up to 25%, not a flat 10% of total liability. The calculation is based on unpaid tax, not total tax liability for the year.$EXPL$
WHERE id = 2434;

-- Q2435: Tax Procedures [easy/L2]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (D): Under IRC Section 6651(a)(2), the failure-to-pay penalty is 0.5% of the unpaid tax for each month or part of a month the tax remains unpaid, up to a maximum of 25%. The rate increases to 1% per month after an IRS notice of intent to levy if the tax remains unpaid for 10 days.
Wrong (A): The 5% per month rate is the failure-to-file penalty under Section 6651(a)(1), not the failure-to-pay penalty.
Wrong (B): The failure-to-pay penalty is a monthly percentage, not a flat 10% charge on the unpaid balance.
Wrong (C): Filing on time avoids the failure-to-file penalty but does not eliminate the failure-to-pay penalty when the full tax is not remitted.$EXPL$
WHERE id = 2435;

-- Q2436: Tax Procedures [easy/L2]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (C): Under IRC Section 6662, the accuracy-related penalty is 20% of the underpayment attributable to negligence, disregard of rules, or substantial understatement. The penalty can be avoided if the taxpayer demonstrates reasonable cause and good faith under Section 6664(c).
Wrong (A): The 5% rate does not correspond to any accuracy-related penalty under Section 6662. It is the monthly failure-to-file penalty rate under Section 6651.
Wrong (B): There is no 10% accuracy-related penalty rate. Section 6662 imposes a flat 20% penalty on the applicable underpayment.
Wrong (D): The 75% rate applies to civil fraud under Section 6663, not negligence. Fraud requires clear and convincing evidence of intent to evade tax.$EXPL$
WHERE id = 2436;

-- Q2437: Tax Procedures [medium/L2]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (B): Under IRC Section 6663, the civil fraud penalty is 75% of the underpayment attributable to fraud. The IRS must prove fraud by clear and convincing evidence. This penalty is significantly more severe than the 20% accuracy-related penalty.
Wrong (A): The 20% rate is the accuracy-related penalty under Section 6662 for negligence or substantial understatement, not fraud.
Wrong (C): There is no 50% civil fraud penalty rate in the Internal Revenue Code. Section 6663 specifies 75%.
Wrong (D): The Code does not impose a 100% fraud penalty. The maximum civil fraud penalty rate is 75% of the underpayment attributable to fraud.$EXPL$
WHERE id = 2437;

-- Q2438: Tax Procedures [medium/L2]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (C): Under IRS administrative procedures, a 30-day letter gives the taxpayer 30 days to agree or file a written protest requesting a conference with the IRS Appeals Office under IRC Section 7803(e). This is an administrative appeal that can resolve disputes without litigation.
Wrong (A): The taxpayer is not limited to accepting the proposed changes. The 30-day letter specifically provides the opportunity to request an administrative appeal.
Wrong (B): A Tax Court petition requires a statutory notice of deficiency (90-day letter) under IRC Section 6213(a), not a 30-day letter.
Wrong (D): Ignoring the 30-day letter forfeits the administrative appeal opportunity, and the IRS will proceed to issue a statutory notice of deficiency.$EXPL$
WHERE id = 2438;

-- Q2440: Tax Procedures [medium/L2]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (D): Under IRC Section 6662(d)(1)(A), a substantial understatement for individuals exists when the understatement exceeds the greater of $5,000 or 10% of the tax required to be shown on the return. This triggers the 20% accuracy-related penalty under Section 6662(a).
Wrong (A): The $1,000 or 5% threshold is not the standard for substantial understatement. The correct thresholds are $5,000 or 10%.
Wrong (B): The $10,000 threshold applies to corporations under Section 6662(d)(1)(B), not individuals. The individual threshold is $5,000.
Wrong (C): There is no $25,000 or 25% threshold for substantial understatement in the Code. This overstates both the dollar amount and percentage.$EXPL$
WHERE id = 2440;
