-- Migration: Question generation — AUD batch 100 (15 questions)
-- Date: 2026-03-30
-- Topic: Specific Areas and Transactions
-- Difficulty: 5E / 7M / 3H
-- Bloom's: L1:4 / L2:5 / L3:4 / L4:2

BEGIN;

INSERT INTO questions (section_id, topic, stem, choices, correct_index, explanation, difficulty, cognitive_level)
VALUES

-- Q1: hard / L3 — Attorney letter procedures for litigation contingencies
(1, 'Specific Areas and Transactions', $EXPL$Thornhill Manufacturing is involved in three pending lawsuits totaling $8.4 million as of December 31, 2025. The engagement team at Kendall & Associates is designing procedures to evaluate the litigation contingencies. Management has provided a list of all pending and threatened litigation. The auditor's next step should be to:$EXPL$, $EXPL$["Send a letter of inquiry to the entity's outside legal counsel requesting corroboration of management's litigation representations", "Accept management's assessment of the probable outcome and record the amounts management recommends without further corroboration", "Limit the inquiry to lawsuits exceeding materiality and exclude smaller claims from the attorney letter", "Request that the entity's internal legal department provide a written summary in lieu of contacting outside counsel"]$EXPL$::jsonb, 0, $EXPL$Correct (A): AU-C 501.09-.10. The auditor must send a letter of inquiry to the entity's outside legal counsel to corroborate management's completeness assertion and obtain an independent assessment of the likelihood and amount of pending or threatened litigation. This is the primary substantive procedure for litigation contingencies.
Wrong (B): Management's assessment alone is insufficient. Auditing standards require independent corroboration from legal counsel because litigation outcomes involve specialized legal judgment.
Wrong (C): The attorney letter should cover all pending and threatened litigation, not just claims exceeding materiality, because individually immaterial claims may be material in the aggregate.
Wrong (D): Internal legal counsel lacks the independence required. AU-C 501 specifically requires inquiry of outside legal counsel responsible for the litigation.$EXPL$, 'hard', 3),

-- Q2: easy / L1 — When negative confirmations are appropriate
(1, 'Specific Areas and Transactions', $EXPL$Under what circumstances are negative confirmations most appropriate for testing accounts receivable?$EXPL$, $EXPL$["When the population consists of a large number of small, routine balances and the risk of material misstatement is low", "When the auditor expects a high rate of exceptions in the population", "When individual account balances are large and unusual", "When the combined assessed risk of material misstatement is high"]$EXPL$::jsonb, 0, $EXPL$Correct (A): AU-C 505.16. Negative confirmations are appropriate when the assessed risk of material misstatement is low, the population consists of many small balances, and the auditor expects respondents to give adequate consideration to the request. These conditions make non-responses reasonably interpretable as agreement.
Wrong (B): A high expected exception rate suggests positive confirmations are needed to obtain explicit responses from customers.
Wrong (C): Large and unusual balances require positive confirmations, which provide more persuasive evidence by requiring an affirmative reply.
Wrong (D): High combined risk demands more persuasive evidence such as positive confirmations, not negative confirmations that assume silence means agreement.$EXPL$, 'easy', 1),

-- Q3: medium / L2 — Inventory net realizable value testing
(1, 'Specific Areas and Transactions', $EXPL$While auditing Glenwood Industries' inventory at December 31, 2025, the engagement team identifies 1,200 units of a product line with a recorded cost of $47 per unit. Recent sales invoices show the product is currently selling for $41 per unit with $3 per unit in estimated selling costs. The auditor should conclude that:$EXPL$, $EXPL$["The inventory is properly stated because the recorded amount reflects historical cost", "Management should write down the inventory because net realizable value exceeds cost", "Management should write down the inventory to $38 per unit because net realizable value is below cost", "The auditor should request a specialist to determine an appropriate valuation"]$EXPL$::jsonb, 2, $EXPL$Correct (C): AU-C 501 and ASC 330-10-35. Inventory must be reported at the lower of cost or net realizable value (NRV). NRV equals selling price ($41) minus estimated costs to complete and sell ($3), yielding $38 per unit. Since $38 is below the $47 cost, a write-down to $38 is required.
Wrong (A): Historical cost is not appropriate when NRV has fallen below cost. The lower of cost or NRV rule requires adjustment.
Wrong (B): This reverses the relationship. NRV ($38) is below cost ($47), not above it, so a write-down is necessary.
Wrong (D): NRV calculations based on observable selling prices and known costs do not require a specialist. The auditor can evaluate this directly.$EXPL$, 'medium', 2),

-- Q4: medium / L3 — Purchase cutoff testing near year-end
(1, 'Specific Areas and Transactions', $EXPL$During the audit of Briarwood Supply's December 31, 2025 financial statements, the engagement team selects receiving reports from the last five days of December and the first five days of January to test purchase cutoff. For goods received on December 29 with an invoice recorded on January 4, the auditor should verify that:$EXPL$, $EXPL$["The purchase and liability were excluded from the December 31 financial statements since the invoice was not received until January", "The goods were included in the physical inventory count but excluded from accounts payable", "Both the purchase was not recorded until January because the invoice date controls the recording period", "The goods were included in ending inventory and the corresponding liability was recorded in accounts payable at December 31"]$EXPL$::jsonb, 3, $EXPL$Correct (D): AU-C 330 and ASC 330-10-30. When title transfers upon receipt (FOB destination received or FOB shipping point shipped), goods received before year-end must be included in inventory and the corresponding payable must be recorded, regardless of when the invoice arrives. Proper cutoff requires matching inventory and liabilities in the same period.
Wrong (A): The invoice date does not determine when a liability is recognized. The receipt of goods establishes the obligation under accrual accounting.
Wrong (B): Including inventory without the corresponding payable would understate liabilities and overstate income, creating a cutoff misstatement.
Wrong (C): Recording is governed by when title passes and goods are received, not by the invoice date.$EXPL$, 'medium', 3),

-- Q5: easy / L1 — Positive confirmation definition
(1, 'Specific Areas and Transactions', $EXPL$What distinguishes a positive confirmation from a negative confirmation in accounts receivable testing?$EXPL$, $EXPL$["A positive confirmation requests the recipient to respond whether they agree or disagree with the stated balance", "A positive confirmation is sent only to customers with past-due balances", "A positive confirmation requires no response if the recipient agrees with the balance", "A positive confirmation is sent by management rather than the auditor"]$EXPL$::jsonb, 0, $EXPL$Correct (A): AU-C 505.06. A positive confirmation requests that the confirming party respond directly to the auditor in all cases, indicating whether the party agrees or disagrees with the information stated. This provides more persuasive evidence than a negative confirmation.
Wrong (B): Positive confirmations are not limited to past-due balances. They are typically sent for large, unusual, or higher-risk balances regardless of aging status.
Wrong (C): This describes a negative confirmation, which requests a response only if the recipient disagrees with the stated amount.
Wrong (D): Confirmations must be controlled by the auditor, not management, to maintain the reliability of the evidence obtained.$EXPL$, 'easy', 1),

-- Q6: hard / L4 — Evaluating management's specialist for complex estimate
(1, 'Specific Areas and Transactions', $EXPL$Prescott Holdings engaged an independent appraiser to value $14 million in commercial real estate for the December 31, 2025 financial statements. The engagement team at Moore & Chen reviews the appraiser's report and discovers the appraiser used capitalization rates from 2022 market data rather than current rates. The appraisal firm has a long-standing business relationship with Prescott's CFO. The engagement partner must evaluate how these findings affect reliance on the specialist's work.$EXPL$, $EXPL$["Accept the appraisal because the appraiser is an independent specialist and the auditor is not qualified to second-guess valuation methodology", "Evaluate the outdated assumptions, assess the specialist's objectivity given the CFO relationship, and consider whether an auditor's specialist is needed", "Disclaim an opinion because the auditor cannot evaluate the work of a management specialist", "Issue a qualified opinion solely because management used a specialist, which indicates a scope limitation"]$EXPL$::jsonb, 1, $EXPL$Correct (B): AU-C 500.08-.09. When management uses a specialist, the auditor must evaluate the specialist's competence, capabilities, and objectivity. The auditor must also assess whether the specialist's work is adequate, including the relevance and reasonableness of assumptions. Outdated market data and a personal relationship both warrant further evaluation and possible alternative procedures.
Wrong (A): The auditor cannot blindly accept a specialist's work. AU-C 500 requires evaluation of assumptions, methods, and objectivity regardless of the specialist's qualifications.
Wrong (C): The use of a management specialist does not create a scope limitation. The auditor has procedures available to evaluate the specialist's work and obtain additional evidence.
Wrong (D): Using a specialist is a normal practice for complex estimates and does not constitute a scope limitation or basis for qualification.$EXPL$, 'hard', 4),

-- Q7: medium / L2 — Disaggregation improving analytical procedure effectiveness
(1, 'Specific Areas and Transactions', $EXPL$While performing substantive analytical procedures on Parkside Hotels' revenue for the year ended December 31, 2025, the engagement team initially compares total revenue to the prior year. The team then decides to disaggregate the analysis by property location and room type. The primary reason for increasing the level of disaggregation is to:$EXPL$, $EXPL$["Reduce the amount of documentation required for the analytical procedure", "Increase the precision of the auditor's expectation, thereby providing more persuasive evidence", "Eliminate the need for any additional tests of details on revenue", "Shift the burden of proof to management for any differences identified"]$EXPL$::jsonb, 1, $EXPL$Correct (B): AU-C 520.05. Disaggregating data improves the precision of the auditor's expectation because more granular data produces more predictable relationships. A property-by-property, room-type analysis yields a tighter expected range than a single total, making the procedure more effective at detecting misstatements.
Wrong (A): Greater disaggregation typically increases documentation requirements because the auditor must document expectations and thresholds at each level.
Wrong (C): Disaggregation enhances analytical procedures but does not eliminate the need for tests of details. The auditor must still assess whether analytical procedures alone provide sufficient evidence.
Wrong (D): Analytical procedures do not shift the burden of proof to management. The auditor retains responsibility for evaluating differences.$EXPL$, 'medium', 2),

-- Q8: easy / L1 — Written representations about accounting estimates
(1, 'Specific Areas and Transactions', $EXPL$What is the purpose of obtaining written representations from management regarding accounting estimates?$EXPL$, $EXPL$["To replace the need for substantive testing of the estimates", "To provide the auditor with a legal defense if the estimates prove materially misstated", "To confirm that management believes the significant assumptions used are reasonable and accepts responsibility for the estimates", "To eliminate the auditor's obligation to evaluate the estimates independently"]$EXPL$::jsonb, 2, $EXPL$Correct (C): AU-C 580.11. Written representations confirm that management acknowledges responsibility for the reasonableness of significant assumptions and the appropriateness of measurement methods used in accounting estimates. They also confirm that management believes the estimates are reasonable in the circumstances.
Wrong (A): Written representations are complementary evidence and do not replace substantive procedures. The auditor must still test estimates through independent methods.
Wrong (B): Representations are not primarily a legal defense mechanism. Their purpose is to obtain acknowledgment of management's responsibility and beliefs about the estimates.
Wrong (D): Written representations do not eliminate the auditor's obligation to evaluate estimates. The auditor retains full responsibility for assessing reasonableness regardless of representations obtained.$EXPL$, 'easy', 1),

-- Q9: easy / L2 — PP&E additions vouching procedure
(1, 'Specific Areas and Transactions', $EXPL$During the audit of Cascade Construction's December 31, 2025 financial statements, the engagement team selects $1.8 million in property, plant, and equipment additions recorded during the year. To test the existence and valuation of these additions, the auditor should:$EXPL$, $EXPL$["Vouch the recorded additions to vendor invoices, contracts, and physical inspection where practicable", "Rely exclusively on management's representations about the additions", "Confirm the additions with the entity's insurance company", "Test only additions exceeding $500,000 individually and accept smaller items without testing"]$EXPL$::jsonb, 0, $EXPL$Correct (A): AU-C 330.18-.20. To test existence and valuation of PP&E additions, the auditor vouches recorded amounts to supporting documentation such as vendor invoices, purchase contracts, and title documents. Physical inspection of significant additions provides additional evidence of existence.
Wrong (B): Management representations alone are insufficient evidence for significant additions. The auditor must corroborate with external documentation and inspection.
Wrong (C): Insurance confirmation verifies coverage, not the existence or cost of individual additions. It provides only indirect evidence.
Wrong (D): The auditor selects a sample based on risk assessment and materiality, not an arbitrary dollar threshold. Smaller items may be tested through sampling.$EXPL$, 'easy', 2),

-- Q10: medium / L3 — Lease right-of-use asset and liability audit approach
(1, 'Specific Areas and Transactions', $EXPL$Ridgeline Properties has 42 operating leases recorded under ASC 842, with a total right-of-use asset balance of $6.3 million at December 31, 2025. The engagement team at Webb & Partners is planning substantive procedures for these lease balances. The most effective approach to auditing the right-of-use assets and lease liabilities is to:$EXPL$, $EXPL$["Confirm lease balances directly with lessors to verify the recorded amounts", "Recalculate the present value of lease payments using the lease terms and discount rate from the underlying lease agreements, and compare to recorded amounts", "Accept the prior year audit balance and test only new leases entered during 2025", "Test only the lease expense on the income statement because balance sheet amounts are derived from expense"]$EXPL$::jsonb, 1, $EXPL$Correct (B): AU-C 540.13 and ASC 842-20-30. Right-of-use assets and lease liabilities are accounting estimates based on lease terms, payment schedules, and discount rates. The auditor should recalculate the present value using data from the lease agreements and evaluate the appropriateness of the discount rate applied to verify the recorded amounts.
Wrong (A): Lessors do not maintain the lessee's right-of-use asset or liability balances. Confirmation would verify payment terms but not the accounting measurement under ASC 842.
Wrong (C): Accepting prior year balances without retesting violates AU-C 330. Existing leases require ongoing evaluation for modifications, reassessments, and proper amortization.
Wrong (D): Under ASC 842, the balance sheet amounts drive the expense, not the reverse. Testing expense alone does not verify the underlying asset and liability measurements.$EXPL$, 'medium', 3),

-- Q11: medium / L2 — Journal entry testing for fraud risk
(1, 'Specific Areas and Transactions', $EXPL$During the audit of Westlake Media's December 31, 2025 financial statements, the engagement team is required to test journal entries as part of the response to the assessed risk of management override of controls. When selecting journal entries for testing, the auditor should focus primarily on:$EXPL$, $EXPL$["Only entries made by the accounting department during normal business hours", "Entries made at or near the end of the reporting period and unusual entries that lack adequate supporting documentation", "A random sample of all journal entries recorded during the year without regard to timing or characteristics", "Only adjusting entries that exceed the materiality threshold established during planning"]$EXPL$::jsonb, 1, $EXPL$Correct (B): AU-C 240.32-.33. When testing journal entries for management override, the auditor should focus on entries with fraud risk characteristics: those made at or near period-end, entries with unusual amounts or accounts, entries made by individuals who do not typically make entries, and entries lacking adequate documentation. These characteristics indicate higher fraud risk.
Wrong (A): Limiting testing to entries made during normal business hours would miss entries posted after hours or on weekends, which are common fraud indicators.
Wrong (C): A purely random sample without considering risk characteristics would not effectively target potential management override. The auditor must apply professional judgment to identify high-risk entries.
Wrong (D): Fraudulent entries may be individually below materiality but material in aggregate. Limiting testing to entries above materiality would miss intentional misstatements designed to avoid detection.$EXPL$, 'medium', 2),

-- Q12: medium / L2 — Threshold for investigating analytical procedure differences
(1, 'Specific Areas and Transactions', $EXPL$During the audit of Oakridge Transport's December 31, 2025 financial statements, the engagement team develops an independent expectation of fuel expense and compares it to the recorded amount. The difference between the expected and recorded amounts exceeds the auditor's predetermined threshold. The auditor's most appropriate next step is to:$EXPL$, $EXPL$["Propose an audit adjustment equal to the full difference between the expected and recorded amounts", "Accept the recorded amount because substantive analytical procedures provide only limited assurance", "Inquire of management and investigate the difference to determine whether it indicates a misstatement", "Increase the threshold to accommodate the difference and conclude that fuel expense is fairly stated"]$EXPL$::jsonb, 2, $EXPL$Correct (C): AU-C 520.07. When a difference exceeds the auditor's threshold, the auditor must investigate by inquiring of management, obtaining corroborating evidence, and performing additional procedures as necessary. The goal is to determine whether the difference represents a misstatement or has a plausible explanation supported by evidence.
Wrong (A): The difference is not automatically a misstatement. The auditor must investigate the cause before proposing any adjustment.
Wrong (B): Substantive analytical procedures can provide sufficient appropriate evidence for their intended purpose. An unexplained difference exceeding the threshold cannot simply be accepted.
Wrong (D): Adjusting the threshold after the fact to accommodate an unexplained difference undermines the procedure's objectivity and violates the auditor's professional skepticism.$EXPL$, 'medium', 2),

-- Q13: easy / L1 — Definition of substantive procedures
(1, 'Specific Areas and Transactions', $EXPL$What are the two categories of substantive procedures an auditor performs during a financial statement audit?$EXPL$, $EXPL$["Tests of details and substantive analytical procedures", "Tests of controls and compliance testing", "Inquiry of management and observation of processes", "Risk assessment procedures and tests of controls"]$EXPL$::jsonb, 0, $EXPL$Correct (A): AU-C 330.04. Substantive procedures consist of two categories: tests of details (examining individual transactions, balances, or disclosures) and substantive analytical procedures (evaluating financial information through analysis of plausible relationships among data). Both are designed to detect material misstatements at the assertion level.
Wrong (B): Tests of controls evaluate the operating effectiveness of internal controls, not financial statement amounts. They are a separate category from substantive procedures.
Wrong (C): Inquiry and observation are audit techniques used within various procedure types, not the two defined categories of substantive procedures.
Wrong (D): Risk assessment procedures are performed during planning to identify risks. They are a distinct phase from substantive procedures performed in response to assessed risks.$EXPL$, 'easy', 1),

-- Q14: hard / L4 — Revenue side agreements and undisclosed terms
(1, 'Specific Areas and Transactions', $EXPL$During the December 31, 2025 audit of Meridian Software, the engagement team at Foster & Blake discovers an unsigned email between the VP of Sales and a major customer suggesting a verbal agreement to accept product returns beyond the standard 30-day policy. Meridian recognized $2.6 million in revenue from this customer during Q4 2025. The standard return provision is $130,000 based on the written policy. The engagement partner must determine the most appropriate response.$EXPL$, $EXPL$["Disregard the email because it is unsigned and therefore does not constitute audit evidence of a side agreement", "Investigate by inquiring of the VP of Sales and the customer, evaluate the impact on revenue recognition and the return provision, and assess fraud risk implications", "Accept the $130,000 return provision because it is based on the written return policy that governs the transaction", "Issue a qualified opinion solely based on the existence of the email without further investigation"]$EXPL$::jsonb, 1, $EXPL$Correct (B): AU-C 240.32 and AU-C 550.10. Evidence of undisclosed side agreements raises significant concerns about revenue recognition completeness and potential fraud. The auditor must investigate by inquiring of relevant parties, evaluating whether the extended return rights affect the transaction price under ASC 606, reassessing the return provision, and considering implications for management integrity and fraud risk.
Wrong (A): Unsigned communications can constitute relevant audit evidence. The auditor cannot disregard potential evidence of side agreements based solely on the absence of a signature.
Wrong (C): The written policy may not reflect the actual terms of the transaction if a side agreement exists. The auditor must evaluate the substance of the arrangement, not just the form.
Wrong (D): A qualified opinion requires completing the investigation first. The auditor must gather sufficient evidence before concluding on the financial statement impact.$EXPL$, 'hard', 4),

-- Q15: medium / L3 — Goodwill impairment testing audit procedures
(1, 'Specific Areas and Transactions', $EXPL$Northgate Holdings recorded $22 million in goodwill from a 2023 acquisition. For the December 31, 2025 annual assessment, management concludes that the reporting unit's fair value exceeds its carrying amount by 8%, so no impairment is recorded. The engagement team at Palmer & Kline notes that the reporting unit's revenue declined 15% during 2025. The auditor should:$EXPL$, $EXPL$["Accept management's conclusion because a positive cushion of 8% demonstrates no impairment exists", "Evaluate the reasonableness of management's fair value assumptions, particularly given the revenue decline, and consider whether alternative assumptions would change the conclusion", "Require management to record a full impairment write-down because the revenue decline indicates the goodwill is worthless", "Limit testing to verifying the mathematical accuracy of management's model without evaluating the underlying assumptions"]$EXPL$::jsonb, 2, $EXPL$Correct (C): AU-C 540.13-.15. When auditing goodwill impairment, the auditor must evaluate the reasonableness of significant assumptions used in the fair value measurement. A 15% revenue decline combined with only an 8% cushion increases estimation uncertainty. The auditor should challenge whether growth rates, discount rates, and projections are realistic given current conditions and assess sensitivity to alternative assumptions.
Wrong (A): A narrow cushion combined with deteriorating performance warrants skeptical evaluation of assumptions, not automatic acceptance of management's conclusion.
Wrong (B): Revenue decline alone does not mean goodwill is worthless. The auditor evaluates whether fair value still exceeds carrying amount using reasonable assumptions, not whether to write off the entire balance.
Wrong (D): Verifying only mathematical accuracy without evaluating assumptions is insufficient for estimates with high uncertainty. AU-C 540 requires evaluation of methods, data, and assumptions.$EXPL$, 'medium', 3)
;

COMMIT;
