-- Migration: Question generation — TCP batch 33 (12 questions)
-- Date: 2026-03-30
-- Topic: Entity Choice and Planning
-- Difficulty: 4E / 6M / 2H
-- Bloom's: L1:2 / L2:4 / L3:4 / L4:2

BEGIN;

INSERT INTO questions (section_id, topic, stem, choices, correct_index, explanation, difficulty, cognitive_level)
VALUES

-- Q1: easy / L2 — Check-the-box: state-law corporation cannot elect partnership
(6, 'Entity Choice and Planning', $EXPL$Westfield Holdings is incorporated under Delaware state law as a corporation. The owners want to reclassify the entity as a partnership for federal tax purposes by filing Form 8832. What is the result of this attempted election?$EXPL$, $EXPL$["The election is invalid because a state-law corporation cannot elect out of corporate classification", "The election is valid and takes effect 60 days after filing", "The election is valid but requires unanimous shareholder consent", "The election is valid only if the corporation has fewer than 100 shareholders"]$EXPL$::jsonb, 0, $EXPL$Correct (A): Under Treas. Reg. Section 301.7701-2(b), an entity incorporated under state law is a per se corporation for federal tax purposes and cannot use the check-the-box regulations to elect partnership or disregarded entity status. Only unincorporated entities (LLCs, LPs) have the check-the-box option. Wrong (B): Form 8832 is unavailable to per se corporations regardless of timing. Wrong (C): Shareholder consent is irrelevant because the election itself is prohibited. Wrong (D): The shareholder count limitation applies to S elections, not to entity classification elections.$EXPL$, 'easy', 2),

-- Q2: medium / L2 — PTET election to bypass SALT cap
(6, 'Entity Choice and Planning', $EXPL$Harmon Partners LLC (taxed as a partnership) operates in a state that offers a pass-through entity tax (PTET) election. The three partners each have $400,000 of individual income and are subject to the $10,000 SALT deduction cap. The partnership's state tax liability is $60,000. The partners are evaluating whether to make the PTET election. What is the primary federal tax benefit of electing the PTET?$EXPL$, $EXPL$["The PTET converts state taxes into a credit that offsets federal taxes dollar-for-dollar", "The entity-level state tax payment is deductible as a business expense, bypassing the $10,000 individual SALT cap", "The PTET eliminates the partners' obligation to file individual state returns", "The PTET reduces the partnership's qualified business income by the amount of state taxes paid"]$EXPL$::jsonb, 1, $EXPL$Correct (B): Under state PTET statutes (enacted in over 30 states), the pass-through entity pays state income tax at the entity level. This payment is deductible as a business expense on the federal return under IRC Section 162, which is not subject to the $10,000 SALT cap that applies to individual itemized deductions under IRC Section 164. Wrong (A): PTET generates a deduction, not a dollar-for-dollar credit against federal tax. Wrong (C): Partners generally still must file individual state returns; the PTET does not eliminate that obligation. Wrong (D): While QBI may be reduced by the entity-level tax, that is a secondary consequence, not the primary benefit.$EXPL$, 'medium', 2),

-- Q3: medium / L3 — LIFO recapture on C-to-S conversion
(6, 'Entity Choice and Planning', $EXPL$Thornton Manufacturing Inc. is a C corporation that uses the LIFO inventory method. Its LIFO reserve (excess of FIFO value over LIFO value) is $180,000. The shareholders vote to elect S corporation status effective January 1, 2027. The corporate tax rate is 21%. What is the tax consequence of the LIFO reserve upon conversion?$EXPL$, $EXPL$["The LIFO reserve is carried forward to the S corporation with no immediate tax impact", "The $180,000 LIFO reserve is taxed as a built-in gain under Section 1374 over five years", "The $180,000 LIFO reserve must be included in income on the last C corporation return, resulting in $37,800 of additional tax", "The LIFO reserve is eliminated and the S corporation must switch to FIFO with no tax consequences"]$EXPL$::jsonb, 2, $EXPL$Correct (C): Under IRC Section 1363(d), a C corporation using LIFO that elects S status must include the LIFO recapture amount (the excess of FIFO value over LIFO value) in gross income on its final C corporation return. The $180,000 recapture at 21% produces $37,800 of additional tax. This tax may be paid in four equal installments. Wrong (A): The LIFO reserve cannot be carried forward; recapture is mandatory upon conversion. Wrong (B): LIFO recapture is governed by Section 1363(d), not the built-in gains tax under Section 1374. Wrong (D): The switch to FIFO does trigger tax consequences through the recapture mechanism.$EXPL$, 'medium', 3),

-- Q4: hard / L4 — Section 199A W-2 wage/UBIA limitation
(6, 'Entity Choice and Planning', $EXPL$Calloway Engineering LLC (taxed as a partnership) generates $600,000 of qualified business income. The firm pays $120,000 in total W-2 wages and holds qualified property with an unadjusted basis immediately after acquisition (UBIA) of $2,000,000. The sole owner, Marcus Calloway, files as single with taxable income of $350,000 (well above the upper phase-in threshold). Engineering is not a specified service trade or business. What is the maximum Section 199A deduction?$EXPL$, $EXPL$["$60,000 — limited to 50% of W-2 wages", "$80,000 — limited to 25% of W-2 wages plus 2.5% of UBIA", "$120,000 — the full 20% of QBI", "The greater of $60,000 or $80,000, which is $80,000"]$EXPL$::jsonb, 3, $EXPL$Correct (D): Under IRC Section 199A(b)(2), for taxpayers above the upper threshold, the QBI deduction is limited to the greater of: (a) 50% of W-2 wages ($120,000 x 50% = $60,000), or (b) 25% of W-2 wages plus 2.5% of UBIA ($120,000 x 25% + $2,000,000 x 2.5% = $30,000 + $50,000 = $80,000). The 20% of QBI amount is $120,000, but the W-2/UBIA limitation caps the deduction at the greater of $60,000 or $80,000, which is $80,000. Wrong (A): This is only the 50% wage test; the taxpayer also qualifies for the alternative UBIA test. Wrong (B): This is the correct alternative calculation but the answer must state it is the greater of the two tests. Wrong (C): The full 20% is unavailable because the W-2/UBIA limitation applies above the threshold.$EXPL$, 'hard', 4),

-- Q5: medium / L3 — Assets-over vs assets-up partnership-to-corporation conversion
(6, 'Entity Choice and Planning', $EXPL$Ridgeline Ventures LP is converting to a corporation. The partnership holds assets with a fair market value of $2,000,000 and an adjusted basis of $800,000. The tax advisor recommends the assets-over method under Section 351. Under this method, what sequence of transactions is deemed to occur?$EXPL$, $EXPL$["The partnership transfers its assets to the new corporation in exchange for stock, distributes the stock to the partners, and liquidates", "The partnership first distributes assets to the partners, who then individually contribute them to the new corporation", "The partners exchange their partnership interests directly for corporate stock in a tax-free swap", "The partnership sells its assets to the new corporation at fair market value and distributes the cash proceeds"]$EXPL$::jsonb, 0, $EXPL$Correct (A): Under Rev. Rul. 84-111, the assets-over method treats the partnership as transferring its assets to the new corporation under IRC Section 351 in exchange for stock, then distributing the stock to the partners in liquidation of their partnership interests. This is generally tax-free if the 80% control test is met. Wrong (B): This describes the assets-up method, where partners receive assets first and then contribute them individually. Wrong (C): A direct exchange of partnership interests for stock is not a recognized conversion method under the ruling. Wrong (D): A sale at fair market value would be a taxable transaction, not a tax-free conversion.$EXPL$, 'medium', 3),

-- Q6: hard / L4 — Section 1375 passive investment income penalty
(6, 'Entity Choice and Planning', $EXPL$Meridian Holdings Inc. converted from a C corporation to an S corporation three years ago. The company retained $400,000 of accumulated earnings and profits (E&P) from its C corporation years. In 2026, Meridian's gross receipts are $200,000, of which $120,000 consists of dividends, interest, and rental income (passive investment income). The company has $30,000 of expenses directly connected to the passive income. A CPA is advising on the tax consequences. What penalty applies under these facts?$EXPL$, $EXPL$["No penalty applies because Meridian converted to S corporation status and is no longer subject to C corporation rules", "A corporate-level tax applies on excess net passive income because the 25% gross receipts threshold is exceeded with accumulated C corp E&P", "The S election is automatically terminated in the current year, but no additional corporate-level tax is imposed on the income", "A 20% surtax applies to all passive investment income regardless of the gross receipts percentage or accumulated E&P balance"]$EXPL$::jsonb, 1, $EXPL$Correct (B): Under IRC Section 1375, if an S corporation has accumulated E&P from C corporation years and passive investment income exceeds 25% of gross receipts, a corporate-level tax is imposed on excess net passive investment income. Here, passive income of $120,000 is 60% of $200,000 gross receipts, well exceeding the 25% threshold. The tax equals the highest corporate rate (21%) applied to the excess net passive income. Additionally, under Section 1362(d)(3), if this occurs for three consecutive years, the S election is terminated. Wrong (A): S corporation status does not shield from this penalty when accumulated C corp E&P exists. Wrong (C): Termination occurs only after three consecutive years of excess passive income, not immediately. Wrong (D): The tax applies to excess net passive income, not to all gross receipts.$EXPL$, 'hard', 4),

-- Q7: easy / L1 — S corp family attribution rule
(6, 'Entity Choice and Planning', $EXPL$For purposes of the 100-shareholder limit on S corporations, how are members of the same family treated?$EXPL$, $EXPL$["Each family member counts as a separate shareholder regardless of relationship", "Family members within six generations of a common ancestor are counted as one shareholder", "Only spouses are counted as one shareholder; all others count separately", "Family members are counted as one shareholder only if they hold stock jointly"]$EXPL$::jsonb, 2, $EXPL$Correct (C): Under IRC Section 1361(c)(1), members of a family — defined as a common ancestor and all lineal descendants within six generations, plus their spouses — are treated as a single shareholder for the 100-shareholder limit. This allows large family-owned businesses to maintain S status. Wrong (A): Family attribution specifically reduces the shareholder count by grouping family members. Wrong (B): While this correctly states the six-generation rule, the answer to the question is that they are counted as one shareholder, which is choice C. Wrong (D): Joint ownership is not the operative rule; the family attribution applies regardless of how shares are titled.$EXPL$, 'easy', 1),

-- Q8: medium / L3 — AAA frozen on S-to-C conversion distribution ordering
(6, 'Entity Choice and Planning', $EXPL$Prescott Industries was an S corporation for 10 years, accumulating an AAA balance of $250,000. The company revokes its S election and becomes a C corporation. In its first year as a C corporation, Prescott earns $150,000 and distributes $300,000 to its sole shareholder. The shareholder's stock basis is $400,000. In what order are the distributions sourced?$EXPL$, $EXPL$["First from AAA ($250,000 tax-free return of basis), then from current E&P ($50,000 taxable dividend)", "First from current E&P ($150,000 taxable dividend), then from the frozen AAA balance ($150,000 tax-free return of basis)", "Entirely from current E&P ($150,000 taxable dividend) and then return of basis ($150,000 reducing stock basis)", "First from current E&P ($150,000 taxable dividend), then from AAA ($150,000 tax-free), with no basis reduction"]$EXPL$::jsonb, 3, $EXPL$Correct (D): When an S corporation converts to a C corporation, the AAA balance is frozen. Under IRC Section 1371(e), distributions are sourced first from current E&P ($150,000 taxable as a dividend), then from accumulated E&P (none here), then from the frozen AAA balance ($150,000 tax-free as a return of previously taxed S corporation income). The AAA distributions are not taxable because they represent income already taxed to the shareholder during S years. Wrong (A): Current E&P must be distributed before AAA under C corporation distribution ordering rules. Wrong (B): Close but incorrectly characterizes the AAA distribution as return of basis rather than return of previously taxed income. Wrong (C): This ignores the frozen AAA balance, which is available before reducing stock basis.$EXPL$, 'medium', 3),

-- Q9: easy / L2 — IRC 721 partnership formation no control test
(6, 'Entity Choice and Planning', $EXPL$Rivera and Tanaka form Cascade Partners LLC, each contributing property in exchange for a 50% partnership interest. Rivera contributes land worth $300,000 (basis $100,000) and Tanaka contributes equipment worth $300,000 (basis $200,000). What is the tax treatment of these contributions?$EXPL$, $EXPL$["The contributions are tax-free under IRC Section 721 with no minimum ownership requirement", "The contributions are tax-free only because the partners together own more than 80% of the partnership", "Each partner recognizes gain equal to the difference between fair market value and basis", "The contributions are tax-free only if the partnership makes a Section 754 election"]$EXPL$::jsonb, 0, $EXPL$Correct (A): Under IRC Section 721, contributions of property to a partnership in exchange for a partnership interest are generally tax-free. Unlike corporate formations under Section 351 (which require 80% control), partnership formations have no minimum ownership threshold. Partners take a carryover basis in their interests. Wrong (B): The 80% control test applies to Section 351 corporate formations, not to partnership contributions under Section 721. Wrong (C): No gain is recognized on property contributions to a partnership under Section 721. Wrong (D): Section 754 governs optional basis adjustments on transfers and distributions, not the tax treatment of initial contributions.$EXPL$, 'easy', 2),

-- Q10: medium / L3 — SSTB complete phase-out above upper threshold
(6, 'Entity Choice and Planning', $EXPL$Dr. Patel operates a medical practice as a sole proprietorship generating $500,000 of qualified business income. Her taxable income before the QBI deduction is $300,000 (filing single). The upper phase-in threshold for single filers is $247,300 (2025). Medical practice is a specified service trade or business (SSTB). What is Dr. Patel's Section 199A deduction?$EXPL$, $EXPL$["$100,000 — the full 20% of QBI applies", "$0 — the deduction is completely phased out for SSTBs above the upper threshold", "$50,000 — the deduction is reduced by 50% for being an SSTB", "$80,000 — limited to the W-2 wage and UBIA calculation"]$EXPL$::jsonb, 1, $EXPL$Correct (B): Under IRC Section 199A(d), specified service trades or businesses (including medical practices under Section 199A(d)(2)) are completely excluded from the QBI deduction once the taxpayer's taxable income exceeds the upper phase-in threshold ($247,300 for single filers in 2025). Dr. Patel's $300,000 exceeds this threshold, so the deduction is zero. Wrong (A): The full 20% deduction is available only below the lower threshold for SSTBs. Wrong (C): There is no flat 50% reduction; the phase-out occurs ratably between the lower and upper thresholds, and above the upper threshold the deduction is eliminated entirely. Wrong (D): The W-2/UBIA limitation is irrelevant because SSTBs above the upper threshold receive no deduction at all.$EXPL$, 'medium', 3),

-- Q11: easy / L1 — State apportionment most common formula
(6, 'Entity Choice and Planning', $EXPL$What is the most commonly used formula for apportioning a multi-state business's income among states?$EXPL$, $EXPL$["Equal weighting of sales, property, and payroll (one-third each)", "Double-weighted sales with property and payroll (50%/25%/25%)", "Single sales factor that allocates 100% based on sales", "Equal weighting of sales and payroll only (50%/50%)"]$EXPL$::jsonb, 2, $EXPL$Correct (C): Most states have adopted a single sales factor apportionment formula, which allocates 100% of apportionable income based on the proportion of sales within the state. This approach has largely replaced the traditional three-factor formula. Wrong (A): The equal three-factor formula was the traditional approach but has been abandoned by most states. Wrong (B): The double-weighted sales formula is used by some states but is less common than the single sales factor. Wrong (D): No state uses a two-factor sales-and-payroll formula as its standard apportionment method.$EXPL$, 'easy', 1),

-- Q12: medium / L2 — S corp election timing Form 2553 deadline
(6, 'Entity Choice and Planning', $EXPL$Brightwater Services Inc., a calendar-year C corporation, decides on February 1, 2027, to elect S corporation status for the 2027 tax year. The company has four U.S. individual shareholders and one class of stock. By what date must the company file Form 2553 for the election to be effective for 2027?$EXPL$, $EXPL$["January 1, 2027", "February 15, 2027", "December 31, 2027", "March 15, 2027"]$EXPL$::jsonb, 3, $EXPL$Correct (D): Under IRC Section 1362(b), a corporation must file Form 2553 by the 15th day of the 3rd month of the tax year for which the election is to take effect. For a calendar-year corporation seeking a 2027 effective date, the deadline is March 15, 2027. Late elections may qualify for relief under Rev. Proc. 2013-30. Wrong (A): January 1 is the effective date of the election, not the filing deadline. Wrong (B): February 15 is not a recognized deadline for S elections. Wrong (C): December 31 is the last day of the tax year; filing by that date would make the election effective for the following year, not the current year.$EXPL$, 'medium', 2)
;

COMMIT;
