-- Migration: Quality fix -- REG batch 47 (30 questions)
-- Generated by generate-quality-scaffold.ts
-- Issues: #1 (giveaway longest), #3 (incomplete explanation)

-- Q10916: Alternative Minimum Tax [easy/L1]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (A): Under IRC Section 55 (AMT) and Section 1411 (NIIT), these are separate, independent tax computations applied to different tax bases with different thresholds. A taxpayer may owe both AMT and the 3.8% NIIT in the same year.
Wrong (B): The NIIT was enacted alongside the AMT as an additional tax on net investment income, not as a replacement for it.
Wrong (C): The AMT is computed on Form 6251 and the NIIT on Form 8960; they are never combined into a single surtax computation.
Wrong (D): The NIIT applies based on net investment income and MAGI thresholds, regardless of whether the taxpayer also owes AMT.$EXPL$
WHERE id = 10916;

-- Q10918: Alternative Minimum Tax [hard/L3]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (A): Under IRC Section 55(b)(3), the AMT computation preserves preferential capital gains rates. Mercer''s $180,000 in long-term gains is taxed at 15% within the AMT, and only the remaining $320,000 of ordinary AMTI is subject to the 26%/28% rate structure.
Wrong (B): Congress specifically provided that capital gains retain preferential rates within the AMT, so the full $500,000 is not subject to ordinary AMT rates.
Wrong (C): Capital gains are not excluded from AMTI; they remain in the computation but are taxed at preferential rates rather than the standard AMT rates.
Wrong (D): The AMT applies the same preferential capital gains rates as regular tax (15%/20%), not a special 20% AMT rate.$EXPL$
WHERE id = 10918;

-- Q10919: Alternative Minimum Tax [medium/L2]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (D): Under IRC Section 56, the standard deduction is added back for AMT purposes, increasing Rivera''s AMTI to $180,000 + $15,000 = $195,000. For Shaw, only the $10,000 SALT is added back under Section 56(b)(1)(A); the $5,000 charitable deduction is allowed for AMT, making Shaw''s AMTI $190,000.
Wrong (A): Both taxpayers have deductions that must be added back for AMT; neither remains at $180,000.
Wrong (B): Shaw''s AMTI is $190,000, not $195,000, because the charitable deduction is not an AMT add-back item.
Wrong (C): Rivera''s AMTI is $195,000 because the full standard deduction is added back, not $180,000.$EXPL$
WHERE id = 10919;

-- Q10920: Individual Taxation: Credits [hard/L4]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (A): Under Section 904, the FTC limitation equals U.S. tax multiplied by the ratio of foreign-source income to worldwide income: $52,000 x ($75,000 / $250,000) = $15,600. Because Whitfield paid $18,000, the credit is limited to $15,600, with the $2,400 excess available for carryback/carryforward under Section 904(c).
Wrong (B): The full $18,000 paid is not creditable because the limitation formula caps the credit at $15,600.
Wrong (C): The $2,400 excess does not disappear; Section 904(c) allows a one-year carryback and ten-year carryforward for unused credits.
Wrong (D): The $52,000 is the total U.S. tax liability, not the foreign tax credit; the credit is limited by the foreign-source income ratio.$EXPL$
WHERE id = 10920;

-- Q10921: Individual Taxation: Credits [medium/L2]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (B): Under Section 25B, the Saver''s Credit is a nonrefundable credit based on eligible retirement contributions up to $2,000 per individual. At AGI of $21,000 (single), Torres qualifies for the 50% rate: 50% x $2,000 = $1,000.
Wrong (A): The 50% rate applies to the $2,000 statutory maximum per individual, not the full $3,000 contribution.
Wrong (C): The 20% rate applies at higher AGI levels; Torres''s $21,000 AGI qualifies for the 50% rate.
Wrong (D): The 10% rate applies at the highest eligible AGI bracket, not at Torres''s income level, and the calculation is also incorrect.$EXPL$
WHERE id = 10921;

-- Q10922: Individual Taxation: Credits [medium/L3]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (C): Under Section 21, the maximum qualifying expenses for two or more individuals are $6,000. Henderson''s actual expenses of $4,200 fall below this cap. At AGI of $25,000, the applicable percentage is 30% (35% reduced by one percentage point for each $2,000 above $15,000). The credit is 30% x $4,200 = $1,260.
Wrong (A): The 20% rate applies at higher AGI levels; Henderson''s $25,000 AGI yields a 30% rate.
Wrong (B): This incorrectly uses the $6,000 statutory cap rather than Henderson''s actual expenses of $4,200, and applies the wrong percentage.
Wrong (D): While the 30% rate is correct, the credit is based on actual expenses ($4,200), not the $6,000 statutory maximum.$EXPL$
WHERE id = 10922;

-- Q10925: Individual Taxation: Credits [easy/L1]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (A): Under Section 904(c), foreign tax credits that exceed the current-year limitation may be carried back one year and forward ten years. This allows taxpayers like Patel to use the $7,000 excess in years when their limitation is higher.
Wrong (B): Unlike NOLs under current law, the foreign tax credit retains its one-year carryback provision; "no carryback" is incorrect.
Wrong (C): The carryback period is one year, not two, and the carryforward is ten years, not twenty.
Wrong (D): The carryback period is one year, not three, and the carryforward is ten years, not fifteen.$EXPL$
WHERE id = 10925;

-- Q10926: Individual Taxation: Credits [medium/L2]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (C): Under Section 25A(b)(2)(A), the AOTC is available only for the first four taxable years of post-secondary education. Since Dawson already claimed the credit for 2022-2025, his son is ineligible for 2026 regardless of enrollment status or degree completion.
Wrong (A): Half-time enrollment is a requirement but does not override the four-year statutory limit once exhausted.
Wrong (B): There is no fifth-year exception; the four-year limit is absolute regardless of whether a degree has been awarded.
Wrong (D): There is no age-24 requirement for AOTC eligibility; the disqualification is based on exceeding four taxable years of claims.$EXPL$
WHERE id = 10926;

-- Q10930: Individual Taxation: Credits [easy/L1]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (C): Under Section 6654(c), estimated tax payments for individuals are due April 15, June 15, September 15 of the current year, and January 15 of the following year. The quarters are not evenly spaced; the second installment is due only two months after the first.
Wrong (A): March 15 and December 15 are not individual estimated tax due dates; March 15 is used for corporate and partnership returns.
Wrong (B): January 15 is the fourth-quarter due date, not the first; the cycle begins with April 15.
Wrong (D): The second payment is due June 15, not July 15; this choice incorrectly assumes evenly spaced quarterly intervals.$EXPL$
WHERE id = 10930;

-- Q10931: Individual Taxation: Credits [hard/L3]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (B): Under Section 25A(c), the Lifetime Learning Credit is computed per return, not per student. The maximum qualified expenses considered are $10,000 per return, yielding a credit of 20% x $10,000 = $2,000, even though combined expenses total $12,000.
Wrong (A): The LLC is not calculated on a per-student basis; that structure applies to the AOTC. Applying per-student treatment would overstate the credit.
Wrong (C): The $10,000 cap applies regardless of actual expenses, so 20% of the uncapped $12,000 overstates the allowable credit.
Wrong (D): The LLC considers combined expenses for all eligible students up to the $10,000 cap, not just the higher-expense student.$EXPL$
WHERE id = 10931;

-- Q10932: Individual Taxation: Credits [medium/L3]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (A): Under Section 901, the foreign tax credit provides a dollar-for-dollar reduction in U.S. tax liability. Since Lin''s limitation exceeds the $3,000 paid, the full amount offsets U.S. tax, saving $3,000.
Wrong (B): A deduction under Section 164 reduces taxable income, not tax liability, saving only 32% x $3,000 = $960, not the full $3,000.
Wrong (C): A taxpayer cannot split the same foreign taxes between credit and deduction; Section 275 requires an all-or-nothing election for each year.
Wrong (D): The credit saves $3,000 dollar-for-dollar while the deduction saves only $960, so they are not identical.$EXPL$
WHERE id = 10932;

-- Q10933: Individual Taxation: Credits [hard/L4]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (D): Under Section 56(b)(3), the ISO spread ($35 - $15) x 2,000 = $40,000 is added to regular taxable income to compute AMTI of $240,000. After the $88,000 exemption, the AMT base of $152,000 is taxed at 26%, yielding a tentative minimum tax of $39,520. This exceeds the $38,000 regular tax by $1,520.
Wrong (A): While ISOs create no regular tax event, the spread is an AMT adjustment under Section 56(b)(3), creating AMT exposure.
Wrong (B): The ISO spread is subject to AMT rates after the exemption, not taxed at ordinary rates on the full amount; $40,000 is the adjustment, not the tax.
Wrong (C): The tentative minimum tax of $39,520 exceeds the $38,000 regular tax, so additional AMT of $1,520 is owed.$EXPL$
WHERE id = 10933;

-- Q10935: Individual Taxation: Credits [easy/L1]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (B): Under Section 24(h)(4), a $500 nonrefundable credit is available for dependents who do not qualify for the full child tax credit, such as children age 17 or older and dependent parents. It shares the same phase-out thresholds as the CTC.
Wrong (A): The Credit for Other Dependents was specifically created for dependents outside the CTC age requirement; a credit is available.
Wrong (C): The other dependent credit is nonrefundable; it cannot generate a refund, unlike the partially refundable child tax credit.
Wrong (D): The credit amount is $500 per qualifying dependent, not $1,000.$EXPL$
WHERE id = 10935;

-- Q10936: Individual Taxation: Credits [medium/L3]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (D): Under Section 6654(e)(2), no underpayment penalty applies if the taxpayer had zero tax liability in the prior year and was a U.S. citizen or resident for the entire prior year. Kowalski meets both conditions, so the exception eliminates any 2026 penalty regardless of current-year income.
Wrong (A): The zero-liability exception under Section 6654(e)(2) overrides the general penalty rules, even when current-year liability exceeds $1,000.
Wrong (B): The 110% safe harbor is irrelevant when the prior-year liability is zero; 110% of zero is still zero.
Wrong (C): There is no AGI limitation on the zero-liability exception; it applies at any income level provided the prior year tax was zero.$EXPL$
WHERE id = 10936;

-- Q10938: Individual Taxation: Credits [medium/L2]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (C): Under Section 32(a), the EIC during the phase-in range equals the credit percentage multiplied by earned income. With two qualifying children at approximately 40%, Hoffman''s credit is about 40% x $8,000 = $3,200. The credit increases as earned income rises until reaching the maximum.
Wrong (A): The credit is not fixed; it varies with earned income during the phase-in range and phases out at higher income levels.
Wrong (B): During the phase-in range the credit increases with earned income, not decreases; the phase-out occurs at higher income levels.
Wrong (D): The EIC is computed on earned income, not AGI; Section 32(a) specifically uses earned income as the computation base.$EXPL$
WHERE id = 10938;

-- Q10949: Individual Taxation: Credits [easy/L1]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (B): Under Section 57, AMT preference items are specific tax benefits that must always be added to taxable income when computing AMTI, such as private activity bond interest and excess intangible drilling costs. Unlike adjustments under Section 56, preferences only increase AMTI.
Wrong (A): This describes AMT adjustments under Section 56, which may increase or decrease AMTI; preference items under Section 57 always increase it.
Wrong (C): Preference items are income or deduction adjustments, not credit disallowances; credits have separate AMT rules.
Wrong (D): Preference items represent tax benefits allowed for regular tax but partially or fully disallowed for AMT, so they do not reduce both taxes equally.$EXPL$
WHERE id = 10949;

-- Q10950: Individual Taxation: Credits/AMT [medium/L3]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (A): Under IRC Section 24, the Child Tax Credit provides $2,000 per qualifying child under 17, totaling $4,000 for two children. The credit phases out by $50 per $1,000 of AGI above $200,000 (single). Patterson''s $15,000 excess yields a $750 reduction: $4,000 - $750 = $3,250.
Wrong (B): A $3,500 credit implies only a $500 phaseout reduction, which would correspond to $10,000 excess AGI rather than the actual $15,000.
Wrong (C): The $4,000 figure ignores the mandatory phaseout reduction that applies once AGI exceeds $200,000.
Wrong (D): A $2,500 credit implies a $1,500 reduction, which overstates the phaseout; $15,000 excess AGI produces only a $750 reduction.$EXPL$
WHERE id = 10950;

-- Q10951: Individual Taxation: Credits/AMT [hard/L4]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (C): Under IRC Section 25A, the AOTC ($2,500 per student, first four years) applies to both undergraduates, yielding $5,000. The LLC (20% of up to $10,000 per return) covers the graduate student: 20% x $5,000 = $1,000. Total credit: $6,000.
Wrong (A): Claiming only the LLC for all three students would yield at most $2,000 (20% x $10,000 cap), forfeiting the more valuable AOTC for the undergraduates.
Wrong (B): This captures only the AOTC for undergraduates and omits the LLC available for the graduate student, leaving $1,000 on the table.
Wrong (D): Graduate students are ineligible for the AOTC, which is limited to the first four years of postsecondary education.$EXPL$
WHERE id = 10951;

-- Q10952: Individual Taxation: Credits/AMT [medium/L2]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (B): Under IRC Section 904, the foreign tax credit is limited to U.S. tax multiplied by the ratio of foreign-source to worldwide income: $60,000 x ($75,000 / $300,000) = $15,000. The $3,000 excess carries back one year and forward ten years.
Wrong (A): The full $18,000 paid is not creditable because the limitation formula caps the credit at $15,000 to prevent offsetting tax on U.S.-source income.
Wrong (C): A $12,000 credit would imply an incorrect income ratio; the correct ratio is $75,000/$300,000 = 25%, yielding $15,000.
Wrong (D): The $60,000 is total U.S. tax liability, not the foreign tax credit; the credit cannot exceed the portion attributable to foreign-source income.$EXPL$
WHERE id = 10952;

-- Q10953: Individual Taxation: Credits/AMT [easy/L1]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (D): Under IRC Section 6401, a refundable credit can reduce tax liability below zero, resulting in a cash refund to the taxpayer. Examples include the EITC and the refundable portion of the CTC.
Wrong (A): Credits reduce tax liability, not taxable income; deductions reduce taxable income. This confuses credits with deductions.
Wrong (B): Nonrefundable credits can only reduce tax to zero; they cannot generate a refund. This reverses the correct classification.
Wrong (C): The refundable or nonrefundable nature of a credit does not determine its dollar amount; either type can be larger depending on the specific credit.$EXPL$
WHERE id = 10953;

-- Q10954: Individual Taxation: Credits/AMT [hard/L4]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (A): Under IRC Section 6654, taxpayers with prior year AGI exceeding $150,000 must pay the lesser of 90% of current year tax ($49,500) or 110% of prior year tax ($38,500) to avoid the underpayment penalty. The minimum safe harbor is $38,500.
Wrong (B): The $35,000 figure applies 100% of prior year tax, but the 100% threshold only applies when prior year AGI is $150,000 or less; Dawson''s $180,000 AGI requires the 110% threshold.
Wrong (C): The $49,500 (90% of current year tax) is one prong of the safe harbor test, but the lesser amount of $38,500 (110% of prior year) satisfies the requirement.
Wrong (D): Paying the full projected $55,000 exceeds the minimum required; the safe harbor does not require payment of 100% of current year tax.$EXPL$
WHERE id = 10954;

-- Q10955: Individual Taxation: Credits/AMT [hard/L4]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (D): Under IRC Section 1(g), the kiddie tax applies only to unearned income exceeding approximately $2,500. Harper''s $6,000 wages are taxed at her own rate. Of her $18,000 dividends, the first $1,250 is tax-free, the next $1,250 is taxed at her rate, and the remaining $15,500 is taxed at the parents'' 37% rate.
Wrong (A): Earned income is never subject to the kiddie tax; only unearned income above the threshold is taxed at the parents'' rate.
Wrong (B): The kiddie tax applies to unearned income above the $2,500 threshold at the parents'' rate, not the child''s rate.
Wrong (C): Wages are always taxed at the child''s own rate; the kiddie tax under Section 1(g) applies only to unearned income.$EXPL$
WHERE id = 10955;

-- Q10956: Individual Taxation: Credits/AMT [easy/L1]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (B): Under IRC Section 25A(i), the AOTC provides a maximum credit of $2,500 per eligible student: 100% of the first $2,000 plus 25% of the next $2,000 in qualified tuition and course materials.
Wrong (A): The $2,000 figure is the maximum Lifetime Learning Credit per return, not the maximum AOTC per student.
Wrong (C): The $1,000 amount represents the maximum refundable portion (40% of $2,500), not the full AOTC credit.
Wrong (D): The $4,000 figure represents the maximum qualified expenses used in the AOTC formula, not the credit amount itself.$EXPL$
WHERE id = 10956;

-- Q10957: Individual Taxation: Credits/AMT [medium/L2]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (C): Under IRC Section 21, qualifying expenses are capped at $3,000 for one qualifying individual. Even though Velasquez paid $4,500, only $3,000 qualifies. At the maximum 35% rate: 35% x $3,000 = $1,050.
Wrong (A): The $1,575 incorrectly applies 35% to the full $4,500 paid without capping expenses at the $3,000 statutory limit for one child.
Wrong (B): The $1,500 appears to use 50% of $3,000 or some other incorrect rate; the applicable rate at $14,000 AGI is 35%.
Wrong (D): The $4,500 represents total expenses paid, not the credit amount; the credit is a percentage of capped qualifying expenses.$EXPL$
WHERE id = 10957;

-- Q10958: Individual Taxation: Credits/AMT [hard/L3]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (B): Under IRC Section 904, the FTC limitation is computed separately for each basket. General: $90,000 x ($60,000/$400,000) = $13,500. Passive: $90,000 x ($40,000/$400,000) = $9,000. Total allowable credit: $13,500 + $9,000 = $22,500.
Wrong (A): The $30,000 ignores the per-basket limitation by simply adding the $16,000 and $14,000 paid; each basket is separately capped.
Wrong (C): A $25,000 total does not match any correct combination of the basket-by-basket limitation calculations.
Wrong (D): The $18,000 understates the credit; the combined limitation across both baskets totals $22,500.$EXPL$
WHERE id = 10958;

-- Q10959: Individual Taxation: Credits/AMT [medium/L2]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (D): Under IRC Section 32(i), a taxpayer is ineligible for the EITC if investment income exceeds approximately $11,600. Williams''s $12,500 in investment income exceeds this threshold, disqualifying her regardless of earned income level or number of children.
Wrong (A): Having earned income is necessary but not sufficient; the separate investment income cap under Section 32(i) must also be met.
Wrong (B): While the EITC does phase out based on AGI, there is a separate investment income disqualification rule that applies independently.
Wrong (C): The number of qualifying children affects the credit amount and phase-out range but does not determine eligibility when the investment income cap is exceeded.$EXPL$
WHERE id = 10959;

-- Q10961: Individual Taxation: Credits/AMT [easy/L1]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (C): Under IRC Section 24(c), a qualifying child for the Child Tax Credit must be under age 17 at the end of the tax year. The 10- and 14-year-old children qualify, but the 17-year-old does not.
Wrong (A): The under-13 threshold applies to the Child and Dependent Care Credit under Section 21, not the Child Tax Credit.
Wrong (B): A child who is 17 at year-end does not qualify for the $2,000 CTC; the cutoff is under 17, not under 18.
Wrong (D): The under-19 threshold relates to the dependency exemption rules, not the Child Tax Credit age requirement.$EXPL$
WHERE id = 10961;

-- Q10962: Individual Taxation: Credits/AMT [medium/L3]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (B): Under IRC Section 25A(i), 40% of the AOTC ($1,000) is refundable, while 60% ($1,500) is nonrefundable. The nonrefundable portion reduces Franklin''s $800 liability to $0, wasting $700. The $1,000 refundable portion generates a refund. Total benefit: $800 + $1,000 = $1,800.
Wrong (A): The $800 accounts only for the nonrefundable offset and ignores the $1,000 refundable portion that generates a cash refund.
Wrong (C): The full $2,500 is not realized because the $700 excess nonrefundable portion is lost when tax liability is only $800.
Wrong (D): The $1,000 represents only the refundable portion; it omits the $800 tax reduction from the nonrefundable portion.$EXPL$
WHERE id = 10962;

-- Q10963: Individual Taxation: Credits/AMT [medium/L2]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (C): Under IRC Section 25B, the Saver''s Credit equals the applicable percentage times qualified contributions up to $2,000 ($4,000 MFJ). At the 50% rate, Cooper''s credit is 50% x $1,500 = $750, based on his actual contribution.
Wrong (A): The $1,500 incorrectly treats the full contribution as the credit amount; the credit is a percentage of contributions, not the contribution itself.
Wrong (B): The $1,000 would require either a $2,000 contribution at 50% or a different rate; Cooper''s actual $1,500 contribution at 50% yields $750.
Wrong (D): The $300 would require a 20% rate, but Cooper''s AGI of $20,000 qualifies him for the 50% rate, not 20%.$EXPL$
WHERE id = 10963;

-- Q10964: Individual Taxation: Credits/AMT [medium/L3]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (A): Under IRC Section 6654, taxpayers with prior year AGI of $150,000 or less must pay the lesser of 90% of current year tax ($22,500) or 100% of prior year tax ($18,000). The safe harbor is $18,000, less $2,000 withholding, requiring $16,000 in estimated payments.
Wrong (B): The $20,500 applies 90% of current year tax ($22,500) minus withholding, but the lesser 100%-of-prior-year safe harbor of $18,000 is more favorable.
Wrong (C): The $17,800 incorrectly applies the 110% prior year threshold ($19,800 minus $2,000), but the 110% rule only applies when prior year AGI exceeds $150,000.
Wrong (D): The $23,000 overstates the requirement; the safe harbor does not require payment of the full current year liability minus withholding.$EXPL$
WHERE id = 10964;
