-- Migration: Quality fix -- FAR batch 39 (30 questions)
-- Generated by generate-quality-scaffold.ts
-- Issues: #1 (giveaway longest), #3 (incomplete explanation)

-- Q15131: Financial Statement Ratios [hard/L4]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (C): Per ASC 280-10 and financial analysis best practices, industry-specific business models drive fundamentally different ratio profiles. Grocery chains have high inventory turnover and thin margins by design, while luxury retailers operate with low turnover and high margins. Comparing ratios across structurally different industries as if higher values indicate superiority is misleading.
Wrong (A): Adding more ratios does not solve the fundamental cross-industry incomparability problem; the analyst needs a different analytical framework, not more data points.
Wrong (B): Adjusting to the same accounting policies does not address structural business model differences that drive ratio divergence.
Wrong (D): Overweighting ROA does not resolve the issue because ROA itself varies structurally across industries with different asset intensity.$EXPL$
WHERE id = 15131;

-- Q15132: Financial Statement Ratios [easy/L1]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (A): Per ASC 260-10 and SEC reporting requirements, market capitalization equals the current market price per share multiplied by total shares outstanding. For Crestview: $62 x 8,000,000 = $496,000,000. Market capitalization represents the total market value of a company''s equity as determined by investors.
Wrong (B): Total assets minus total liabilities equals book value of equity under ASC 210-10, which reflects historical cost accounting rather than current market pricing.
Wrong (C): Net income divided by shares outstanding calculates earnings per share, a profitability metric, not market value.
Wrong (D): Book value per share multiplied by shares outstanding yields total book equity, which typically differs from market capitalization.$EXPL$
WHERE id = 15132;

-- Q15133: Financial Statement Ratios [medium/L3]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (B): Per ASC 270-10 (Interim Reporting), seasonal businesses can experience distorted year-end ratios from post-peak cash buildups. Using average current ratios across interim periods provides a more representative view of ongoing liquidity. For Snowpeak, the December 31 current ratio of 3.2 overstates liquidity because Q4 cash collections inflate current assets.
Wrong (A): Using the year-end ratio simply because it is the most recent ignores the seasonal distortion that makes it unrepresentative of normal operations.
Wrong (C): CPI adjustments address inflation, not seasonal cash flow patterns; they are irrelevant to correcting seasonal ratio distortion.
Wrong (D): Using the lowest quarterly ratio introduces a conservative bias that may understate actual liquidity rather than providing a representative measure.$EXPL$
WHERE id = 15133;

-- Q15162: Subsequent Events [easy/L1]
-- Issues: #1
UPDATE questions SET
  choices = $EXPL$["The evaluation date and whether it is the issuance or available-to-be-issued date","Only the aggregate dollar amount of all recognized subsequent events","The identities of all third parties involved in any subsequent event transactions","A comprehensive list of every event occurring between year-end and the issuance date"]$EXPL$::jsonb
WHERE id = 15162;

-- Q15165: Investments [medium/L3]
-- Issues: #1
UPDATE questions SET
  choices = $EXPL$["Net income increases by $6,500 due to the change in fair value","Other comprehensive income increases by $6,500 with no net income effect","Retained earnings increases directly by $6,500 from the fair value change","No recognition occurs until the security is ultimately sold to a third party"]$EXPL$::jsonb
WHERE id = 15165;

-- Q15170: Investments [hard/L3]
-- Issues: #1
UPDATE questions SET
  choices = $EXPL$["The $3,400 unrealized gain is recognized immediately in net income at transfer date","The security is recorded at $88,000 amortized cost with no OCI adjustment required","The security is recorded at $91,400 fair value and the $3,400 AOCI amortizes over remaining life","The $3,400 in AOCI is reclassified as a lump sum directly to retained earnings upon transfer"]$EXPL$::jsonb
WHERE id = 15170;

-- Q15172: Investments [hard/L4]
-- Issues: #1
UPDATE questions SET
  choices = $EXPL$["Fair value changes flow through net income under ASC 825, aligning with Meridian''s transparency goal","The fair value option eliminates all required disclosures about the investee''s financial position","The equity method produces higher reported income during periods of heavy R&D spending","The fair value option election can be revoked if the investee later becomes profitable"]$EXPL$::jsonb
WHERE id = 15172;

-- Q15176: Investments [hard/L4]
-- Issues: #1
UPDATE questions SET
  choices = $EXPL$["Remeasure the 10% interest to fair value, recognize a $30,000 gain, and apply equity method prospectively","Carry the original 10% at $150,000 historical cost and apply the equity method only to the new 15%","Restate all prior periods as if the equity method had been applied from the inception date","Recognize a $430,000 gain for the total difference between combined fair value and original cost"]$EXPL$::jsonb
WHERE id = 15176;

-- Q15183: Investments [medium/L3]
-- Issues: #1
UPDATE questions SET
  choices = $EXPL$["No accounting effect because Bellamy retains the equity method after ownership dilution","A gain of $50,000 recognized in net income from the investee''s stock issuance event","A loss of $120,000 recognized in net income from the reduction in ownership percentage","A loss of $70,000 in net income reflecting dilution of Bellamy''s proportionate net assets"]$EXPL$::jsonb
WHERE id = 15183;

-- Q15186: Investments [easy/L1]
-- Issues: #1
UPDATE questions SET
  choices = $EXPL$["A management estimate of the investee''s increased intrinsic value or earning potential","A favorable analyst report or rating upgrade on the investee''s financial outlook","An observable price change from an orderly transaction for an identical or similar security","An increase in the investee''s reported net income for the most recent fiscal period"]$EXPL$::jsonb
WHERE id = 15186;

-- Q15191: Investments [medium/L2]
-- Issues: #1
UPDATE questions SET
  choices = $EXPL$["Reduce equity income by the full $60,000 intercompany profit without depreciation recovery","Reduce equity income by $18,000 and recognize a separate $3,600 depreciation recovery amount","Reduce equity income by the net $14,400 amount without separately identifying the components","Reduce equity income by $18,000 with $3,600 annual depreciation recovery, netting to $14,400"]$EXPL$::jsonb
WHERE id = 15191;

-- Q15195: Financial Statement Ratios [easy/L1]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (B): Per ASC 210-10-45, the cash ratio (cash and cash equivalents divided by current liabilities) is the most conservative liquidity measure. It evaluates whether a company can cover short-term obligations using only its most liquid assets without relying on receivables, inventory, or other current assets.
Wrong (A): Total cash inflows relative to outflows describes a cash flow statement measure, not a balance sheet liquidity ratio like the cash ratio.
Wrong (C): The percentage of assets held in liquid form describes asset composition, not the ability to meet specific current liabilities.
Wrong (D): The speed of cash collection from customers describes receivables turnover or days sales outstanding, not the cash ratio.$EXPL$
WHERE id = 15195;

-- Q15198: Financial Statement Ratios [medium/L2]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (A): Per ASC 842 (Leases) and financial analysis standards, the fixed charge coverage ratio equals (EBIT + lease payments) / (interest expense + lease payments). For Ironclad: ($1,200,000 + $200,000) / ($300,000 + $200,000) = $1,400,000 / $500,000 = 2.80 times. This measures the ability to cover all fixed financing obligations including lease commitments.
Wrong (B): 2.40 results from using only EBIT in the numerator ($1,200,000 / $500,000), which understates coverage by excluding earnings that fund lease obligations.
Wrong (C): 3.00 does not correspond to any correct combination of the given figures.
Wrong (D): 4.00 results from dividing EBIT by interest expense alone ($1,200,000 / $300,000), which is the interest coverage ratio, not the fixed charge coverage ratio.$EXPL$
WHERE id = 15198;

-- Q15199: Financial Statement Ratios [medium/L2]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (A): Per ASC 280-10 and financial efficiency analysis, revenue per employee = $24,000,000 / 150 = $160,000. This falls below the industry benchmark of $200,000, indicating Clarendon generates less revenue per headcount than peers and may signal overstaffing, lower billing rates, or underutilized capacity.
Wrong (B): $160,000 is 20% below the $200,000 benchmark, so claiming the firm operates above industry efficiency contradicts the data.
Wrong (C): Revenue per employee is $160,000, not $150,000; the division of $24,000,000 by 150 employees yields $160,000.
Wrong (D): Revenue per employee is $160,000, not $200,000; stating it matches the benchmark exactly is arithmetically incorrect.$EXPL$
WHERE id = 15199;

-- Q15201: Financial Statement Ratios [easy/L1]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (D): Per ASC 220-10 (Income Statement), the operating expense ratio equals total operating expenses divided by net revenue. For Ashford: $4,200,000 / $12,800,000 = 32.8%. This metric measures the proportion of revenue consumed by day-to-day operations, with a lower ratio indicating greater cost efficiency.
Wrong (A): Net income as a percentage of total assets describes return on assets (ROA), a profitability metric unrelated to the given calculation.
Wrong (B): Total debt as a percentage of equity describes the debt-to-equity ratio, a leverage metric, not an income statement measure.
Wrong (C): Operating income relative to interest expense describes the interest coverage ratio, which measures debt service capacity.$EXPL$
WHERE id = 15201;

-- Q15203: Financial Statement Ratios [medium/L3]
-- Issues: #1
UPDATE questions SET
  choices = $EXPL$["Liquidity is strong because the current ratio of 2.1 exceeds the typical 2.0 benchmark","The cash flow ratio below 1.0 signals operations cannot fully cover current liabilities despite the adequate current ratio","An operating cash flow ratio below 1.0 automatically indicates the company is in financial distress","The current ratio and cash flow ratio measure the same thing, so only one metric is needed"]$EXPL$::jsonb
WHERE id = 15203;

-- Q15204: Financial Statement Ratios [medium/L2]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (C): Per ASC 210-10 and financial analysis standards, invested capital = total debt + equity - cash = $8,000,000 + $12,000,000 - $2,000,000 = $18,000,000. Invested capital turnover = net sales / invested capital = $20,000,000 / $18,000,000 = 1.11 times. This measures how efficiently deployed capital generates revenue.
Wrong (A): 1.00 results from dividing sales by total debt plus equity without subtracting cash ($20M / $20M), overstating the capital base with idle cash.
Wrong (B): 1.67 results from dividing sales by only equity ($20M / $12M), ignoring the debt component of invested capital.
Wrong (D): 2.50 results from dividing sales by total debt alone ($20M / $8M), excluding equity from the capital base entirely.$EXPL$
WHERE id = 15204;

-- Q15205: Financial Statement Ratios [easy/L1]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (D): Per SEC reporting guidance and ASC 235-10-50, the Beneish M-Score model uses eight financial ratios including the days sales in receivables index, gross margin index, and asset quality index. An M-Score above -1.78 suggests a higher probability of financial statement manipulation, helping analysts benchmark earnings quality against expected patterns.
Wrong (A): Predicting bankruptcy likelihood is the purpose of the Altman Z-Score model, not the Beneish M-Score.
Wrong (B): Estimating intrinsic value through discounted cash flows is a valuation technique, not a forensic accounting detection model.
Wrong (C): Detecting earnings manipulation is closely related to the M-Score''s function, but the model''s primary output benchmarks financial metrics against peer patterns.$EXPL$
WHERE id = 15205;

-- Q15206: Financial Statement Ratios [hard/L4]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (A): Per ASC 820 and economic value analysis, EVA equals NOPAT minus the capital charge (invested capital x WACC). Meridian''s EVA = $4,200,000 - ($30,000,000 x 10%) = $1,200,000. Positive EVA means Meridian earns above its cost of capital, creating shareholder value. The competitor''s higher ROE with negative EVA likely reflects excessive leverage inflating returns.
Wrong (B): A higher ROE does not indicate a better investment when EVA is negative, since ROE can be inflated by leverage while the firm destroys economic value.
Wrong (C): EVA and ROE measure different things and can produce different rankings; EVA accounts for the full cost of capital while ROE does not.
Wrong (D): Comparing NOPAT to invested capital without applying the WACC percentage is incorrect; EVA subtracts the capital charge ($3,000,000), not the full capital base.$EXPL$
WHERE id = 15206;

-- Q15207: Financial Statement Ratios [medium/L2]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (B): Per ASC 820 and commercial real estate lending standards, debt yield = NOI / loan balance = $3,600,000 / $30,000,000 = 12%. Since 12% exceeds the 10% minimum covenant, Crestline is in compliance. Debt yield measures the lender''s return on the loan independent of interest rate or amortization assumptions.
Wrong (A): 10% is the covenant threshold, not the actual computed debt yield; confusing the minimum requirement with the calculated result leads to an incorrect compliance assessment.
Wrong (C): 8% does not result from dividing $3,600,000 by $30,000,000; it would require NOI of only $2,400,000.
Wrong (D): 15% would require NOI of $4,500,000, which exceeds the reported $3,600,000.$EXPL$
WHERE id = 15207;

-- Q15208: Financial Statement Ratios [medium/L3]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (A): Per ASC 230-10, market cap = 5,000,000 x $30 = $150,000,000. Free cash flow = CFO - CapEx = $18,000,000 - $6,000,000 = $12,000,000. FCF yield = $12,000,000 / $150,000,000 = 8.0%. Since 8.0% exceeds the 6.0% industry average, the stock generates more free cash per dollar of market value than peers, supporting the undervaluation thesis.
Wrong (B): FCF of $12,000,000 against $150,000,000 market cap yields an 8% return, which is above average and does not indicate overvaluation.
Wrong (C): FCF yield is specifically designed for cross-company comparisons within an industry, making this dismissal of the metric incorrect.
Wrong (D): An 8% yield that is 33% above the 6% average represents a meaningful premium, not a rounding difference within normal range.$EXPL$
WHERE id = 15208;

-- Q15209: Financial Statement Ratios [easy/L1]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (D): Per ASC 220-10, operating profit margin equals operating income (EBIT) divided by net sales, excluding interest expense and income taxes. Net profit margin equals net income divided by net sales, including interest and taxes. This distinction explains Westbrook''s gap from 18% to 9%.
Wrong (A): Both margins use net revenue (net sales) as the denominator; operating margin does not substitute a different denominator.
Wrong (B): Depreciation is included in both operating income and net income as an operating expense; it does not differ between the two margins.
Wrong (C): Operating margin uses operating income (EBIT), not gross profit, and net margin uses net income, not EBITDA.$EXPL$
WHERE id = 15209;

-- Q15210: Financial Statement Ratios [medium/L3]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (A): Per ASC 260-10 and growth-adjusted valuation analysis, the PEG ratio divides P/E by expected earnings growth. Atlas PEG = 35 / 25 = 1.40; Zenon PEG = 18 / 8 = 2.25. A lower PEG suggests better value relative to growth, making Atlas more attractive on this metric despite its higher absolute P/E.
Wrong (B): While Zenon''s PEG of 2.25 does exceed 2.0, the conclusion should focus on the relative comparison; a PEG above 2.0 alone does not determine overvaluation.
Wrong (C): A higher absolute P/E reflects market expectations but does not indicate better value without adjusting for growth rates.
Wrong (D): This analysis is partially correct on the math but incorrectly concludes the comparison is uninformative; the PEG ratio''s purpose is precisely this growth-adjusted comparison.$EXPL$
WHERE id = 15210;

-- Q15211: Financial Statement Ratios [medium/L2]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (B): Per ASC 470-10 (Debt) and ASC 210-10, long-term debt = total liabilities - current liabilities = $9,000,000 - $2,500,000 = $6,500,000. Long-term debt-to-equity = $6,500,000 / $6,500,000 = 1.00. This ratio measures the proportion of long-term financing provided by creditors versus shareholders.
Wrong (A): 0.38 results from dividing current liabilities by total liabilities ($2,500,000 / $6,500,000), which is not a meaningful leverage ratio.
Wrong (C): 1.38 results from dividing total liabilities by equity ($9,000,000 / $6,500,000), producing the total debt-to-equity ratio rather than the long-term ratio.
Wrong (D): 0.63 does not correspond to any correct combination of the given balance sheet figures.$EXPL$
WHERE id = 15211;

-- Q15212: Financial Statement Ratios [medium/L2]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (C): Per ASC 230-10, CFO per share = $9,000,000 / 2,000,000 = $4.50. Price-to-cash-flow = $36 / $4.50 = 8.0x. This ratio measures how much investors pay per dollar of operating cash flow, offering a valuation alternative less subject to accrual distortions than P/E.
Wrong (A): 4.0x would result from dividing price by total CFO in millions ($36 / $9), confusing per-share and aggregate figures.
Wrong (B): 7.2x does not correspond to any correct combination of the given figures.
Wrong (D): 3.6x would result from an incorrect calculation, such as dividing share price by 10 rather than by CFO per share.$EXPL$
WHERE id = 15212;

-- Q15213: Financial Statement Ratios [medium/L3]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (D): Per ASC 220-10 and financial leverage analysis, DOL multiplies the percentage change in revenue to determine the percentage change in EBIT. With DOL of 3.0 and a 10% revenue increase, EBIT increases by 3.0 x 10% = 30%. This is verified by DOL = contribution margin / EBIT = ($12,000,000 - $6,000,000) / $2,000,000 = 3.0.
Wrong (A): 10% assumes EBIT changes proportionally with revenue, ignoring the operating leverage effect entirely.
Wrong (B): 13% does not correspond to any valid application of the DOL formula with the given inputs.
Wrong (C): 20% would require a DOL of 2.0, not the given 3.0.$EXPL$
WHERE id = 15213;

-- Q15215: Financial Statement Ratios [medium/L3]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (B): Per ASC 470-10 and financial leverage analysis, DTL = DOL x DFL = 2.5 x 1.6 = 4.0. The expected percentage change in EPS = DTL x percentage change in revenue = 4.0 x 8% = 32%. DTL captures the combined amplification from both operating and financial fixed costs.
Wrong (A): 8% assumes EPS changes proportionally with revenue, ignoring both operating and financial leverage effects.
Wrong (C): 20% results from applying only operating leverage (2.5 x 8%), omitting the additional amplification from financial leverage.
Wrong (D): 12.8% results from applying only financial leverage (1.6 x 8%), omitting the amplification from operating leverage.$EXPL$
WHERE id = 15215;

-- Q15216: Financial Statement Ratios [easy/L1]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (C): Per ASC 820-10 and financial analysis standards, enterprise value equals market capitalization plus total debt minus cash and cash equivalents. EV represents the total theoretical cost to acquire the firm, accounting for both the equity purchase price and net debt assumed by the acquirer.
Wrong (A): Revenue minus operating expenses describes operating income, not enterprise value; revenue and expenses are income statement items, not valuation components.
Wrong (B): Total assets minus total liabilities equals book value of equity under ASC 210-10, a historical cost measure distinct from market-based enterprise value.
Wrong (D): Net income plus depreciation plus amortization approximates EBITDA, an earnings metric, not a valuation measure like enterprise value.$EXPL$
WHERE id = 15216;

-- Q15218: Financial Statement Ratios [easy/L1]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (A): Per ASC 310-10-50, accounts receivable turnover equals net credit sales divided by average accounts receivable. Average AR = ($280,000 + $320,000) / 2 = $300,000. Turnover = $3,600,000 / $300,000 = 12 times. This measures how efficiently a company converts credit sales into cash.
Wrong (B): Using total revenue instead of net credit sales inflates the numerator with cash transactions, and using ending AR instead of average ignores balance changes throughout the period.
Wrong (C): Dividing average receivables by net credit sales inverts the formula and produces a fraction (days ratio concept), not a turnover measure.
Wrong (D): Cost of goods sold divided by average receivables would be appropriate for inventory-related ratios, not receivables turnover.$EXPL$
WHERE id = 15218;

-- Q15220: Financial Statement Ratios [medium/L2]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (C): Per ASC 280-10-50 and DuPont decomposition, NOPAT = EBIT x (1 - tax rate) = $5,000,000 x 0.75 = $3,750,000. NOPAT margin = $3,750,000 / $40,000,000 = 9.375%. This metric isolates after-tax operating profitability independent of financing decisions.
Wrong (A): 12.5% equals EBIT / net sales ($5,000,000 / $40,000,000), which is the operating profit margin before tax adjustment.
Wrong (B): 10.0% does not correspond to any correct combination of the given figures and the NOPAT formula.
Wrong (D): 15.0% would require NOPAT of $6,000,000, which exceeds even the pre-tax EBIT of $5,000,000.$EXPL$
WHERE id = 15220;
