-- Migration: Quality fix -- AUD batch 49 (30 questions)
-- Generated by generate-quality-scaffold.ts
-- Issues: #1 (giveaway longest), #3 (incomplete explanation)

-- Q7932: Written Representations [medium/L3]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (B): Under AU-C 570.17 and AU-C 580.A9, when substantial doubt about going concern exists, the auditor obtains written representations regarding management''s plans to mitigate the conditions. These representations help evaluate feasibility and whether the plans can be implemented.
Wrong (A): A promise not to file bankruptcy is an unenforceable forward-looking commitment, not a representation about management''s remediation plans as contemplated by AU-C 580.
Wrong (C): An agreement to liquidate is not a going concern mitigation plan; the standard requires representations about plans intended to address the doubt, not contingency liquidation agreements.
Wrong (D): Certification of going concern status by a valuation firm is not a management representation and is not required or contemplated by AU-C 580.$EXPL$
WHERE id = 7932;

-- Q7933: Written Representations [medium/L3]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (B): AU-C 580.A11 and AU-C 560 require management to represent that all events occurring between the balance sheet date and the date of the representation letter have been properly reflected. The representation letter date matches the auditor''s report date, ensuring coverage of subsequent events through that date.
Wrong (A): The end of the fiscal quarter following year-end is an arbitrary cutoff with no basis in auditing standards for subsequent events representation coverage.
Wrong (C): The filing date with regulators typically occurs well after the report date and would extend the representation window beyond what AU-C 580 contemplates.
Wrong (D): Ninety days after the balance sheet date is not a standard-defined cutoff; the representation period is tied to the auditor''s report date, not a fixed number of days.$EXPL$
WHERE id = 7933;

-- Q7934: Written Representations [medium/L3]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (B): Under AU-C 580.A24, when the auditor identifies information inconsistent with written representations, the auditor should investigate the circumstances and reconsider the reliability of related representations. The undisclosed $200,000 payment to the CFO''s spouse''s entity directly contradicts the related party representation.
Wrong (A): Accepting the signed letter at face value ignores the contradictory bank statement evidence and violates the auditor''s professional skepticism obligation.
Wrong (C): Issuing an adverse opinion immediately is premature; the auditor must first investigate the inconsistency and assess its implications before determining the effect on the opinion.
Wrong (D): Deleting the related party representation from the letter would remove required content under AU-C 580 rather than addressing the underlying disclosure failure.$EXPL$
WHERE id = 7934;

-- Q7936: Written Representations [hard/L3]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (B): AU-C 580.A10 permits the auditor to request additional written representations beyond those required by the standard when the auditor determines they are necessary to support other audit evidence. A complex milestone revenue arrangement warrants entity-specific representations about recognition criteria.
Wrong (A): Omitting the topic entirely would leave a gap in evidence supporting the revenue recognition treatment of a material and complex transaction.
Wrong (C): External legal counsel cannot provide management representations; written representations must come from management with appropriate responsibilities under AU-C 580.09.
Wrong (D): A general disclaimer noting an omission does not substitute for obtaining the specific representations needed to support audit conclusions.$EXPL$
WHERE id = 7936;

-- Q7937: Written Representations [hard/L4]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (C): AU-C 800.14 and AU-C 580 require that the management representation letter for a special purpose framework audit reference the applicable framework and confirm that all informative disclosures are adequate. The letter must be tailored to the cash-basis framework rather than using a standard GAAP template.
Wrong (A): A GAAP audit representation letter without modification would reference inappropriate standards and assertions that do not apply to a cash-basis framework.
Wrong (B): Omitting the fair presentation representation ignores that AU-C 800 still requires management to confirm presentation within the applicable special purpose framework.
Wrong (D): Replacing the representation letter with an engagement acknowledgment eliminates required audit evidence; the engagement letter and representation letter serve distinct purposes under AU-C 580.$EXPL$
WHERE id = 7937;

-- Q7942: Written Representations [hard/L4]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (B): AU-C 580.15 requires the representation letter to be dated as of the date of the auditor''s report. When the auditor reissues a report on restated financial statements, a new representation letter dated as of the new report date must be obtained to cover the restatement and intervening events. See also AU-C 560.
Wrong (A): The original March 15 letter would not cover the restatement period or events discovered between March and July, leaving significant audit evidence gaps.
Wrong (C): Backdating the new letter to March 15 would misrepresent the period covered and fail to address the restatement and intervening events.
Wrong (D): Waiving the representation letter is not permitted; AU-C 580.04 requires written representations for every audit, including reissued reports.$EXPL$
WHERE id = 7942;

-- Q7944: Written Representations [medium/L3]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (B): AU-C 550.23 and AU-C 580 require that when management asserts related party transactions were conducted at arms-length terms, the auditor must obtain sufficient appropriate evidence to evaluate whether the assertion is supportable. The above-market lease rate ($35 vs. $28) necessitates corroboration.
Wrong (A): Accepting the assertion at face value without corroborating the above-market lease rate fails to satisfy the auditor''s evidence requirements under AU-C 550.
Wrong (C): Removing the assertion from the notes does not resolve the underlying issue and would result in incomplete financial statement disclosure of related party terms.
Wrong (D): Issuing an adverse opinion solely because a related party transaction occurred is unwarranted; related party transactions are permissible if properly disclosed.$EXPL$
WHERE id = 7944;

-- Q7945: Written Representations [medium/L2]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (B): AU-C 580.A9 requires representations about management''s intent and ability to carry out specific courses of action when those intentions affect classification or measurement. For held-to-maturity securities under ASC 320, management must represent both positive intent and ability to hold to maturity.
Wrong (A): An agreement to reclassify if the auditor requests it is not a proper representation; classification is management''s responsibility, not the auditor''s directive.
Wrong (C): Projecting that bond issuers will not default is a credit risk assessment unrelated to management''s own holding intent and ability as required by the standard.
Wrong (D): Calculation of unrealized gains and losses is a measurement matter for available-for-sale securities, not a representation relevant to held-to-maturity classification.$EXPL$
WHERE id = 7945;

-- Q7947: Written Representations [hard/L4]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (B): AU-C 580.20 states that if management does not provide one or more requested written representations, the auditor should discuss the matter, re-evaluate management''s integrity, and evaluate the effect on the auditor''s ability to rely on other representations. The refusal itself may signal broader concerns about management''s reliability.
Wrong (A): Issuing an unmodified opinion solely because alternative evidence exists ignores that the refusal to provide representations raises questions about management''s candor and integrity.
Wrong (C): Accepting the partial letter and noting the exclusion in workpapers without further action fails to address the auditor''s obligation to evaluate the implications of the refusal.
Wrong (D): Immediate withdrawal without further consideration is premature; AU-C 580.20 requires discussion and evaluation before determining the appropriate response.$EXPL$
WHERE id = 7947;

-- Q8073: Written Representations [medium/L3]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (D): AU-C 580.12 requires management to represent that it believes the selection of accounting policies is appropriate under the applicable financial reporting framework. When a policy change occurs, management should confirm the new method is appropriate and justified.
Wrong (A): Retroactive restatement is an accounting treatment decision, not a representation the auditor seeks; the representation concerns appropriateness of the policy change itself.
Wrong (B): A specific income impact percentage is a financial projection, not an appropriate representation about the policy change''s conformity with the framework.
Wrong (C): The auditor does not approve accounting changes; that is management''s decision, and the representation confirms management''s own assessment of appropriateness.$EXPL$
WHERE id = 8073;

-- Q8078: Written Representations [hard/L4]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (B): AU-C 580.17 requires the auditor to reconsider the reliability of representations when contradictory evidence exists. A material contradiction between the representation letter and the attorney''s confirmation regarding a $4.5 million undisclosed claim raises doubt about all representations and requires evaluation of broader audit implications.
Wrong (A): The formal nature of the signed letter does not make it sufficient when direct contradictory evidence from the attorney''s confirmation exists.
Wrong (C): Immediate withdrawal without further investigation is premature; the auditor should first evaluate the inconsistency and its effect on the audit.
Wrong (D): Management representations do not take precedence over external evidence; the auditor must consider all relevant evidence, including attorney confirmations.$EXPL$
WHERE id = 8078;

-- Q8079: Written Representations [hard/L4]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (C): AU-C 580.16 requires the auditor to evaluate whether written representations are consistent with other audit evidence. Under AU-C 570, the auditor must assess management''s going concern plans for feasibility. An unexecuted contract does not constitute sufficient evidence to support the turnaround projection.
Wrong (A): Simply accepting the representation without corroborating evidence is insufficient when substantial doubt indicators exist, including $8.2 million in losses and an imminent loan maturity.
Wrong (B): Disclaiming an opinion solely because of operating losses is inappropriate; a disclaimer requires inability to obtain sufficient evidence, not merely adverse financial conditions.
Wrong (D): Requiring removal of the going concern representation eliminates required content rather than addressing whether management''s plans are adequately supported.$EXPL$
WHERE id = 8079;

-- Q8084: Written Representations [medium/L2]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (A): AU-C 580.14 permits the auditor to request additional written representations beyond those specifically required when the engagement circumstances warrant them. Specialized industries with complex transactions or regulatory requirements may necessitate entity-specific representations.
Wrong (B): Additional representations supplement rather than replace substantive procedures; they do not reduce the need for other audit evidence.
Wrong (C): Management''s voluntary offer is not the basis for requesting additional representations; the auditor''s professional judgment about engagement circumstances drives the decision.
Wrong (D): The engagement fee amount has no bearing on whether additional representations are appropriate; the decision depends on the nature and complexity of the entity''s transactions.$EXPL$
WHERE id = 8084;

-- Q8086: Written Representations [hard/L4]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (A): AU-C 580.12 requires management to represent that all noncompliance with contractual agreements has been disclosed. Under ASC 470-10, a covenant violation at the balance sheet date generally requires reclassification of debt as current unless a formal waiver is obtained, so the auditor must evaluate disclosure and documentation.
Wrong (B): The auditor cannot accept an oral explanation of an informal waiver without further documentation; the covenant violation must be represented and evaluated for proper disclosure.
Wrong (C): Requiring the lender to provide a separate representation letter to the auditor is not a standard requirement; the representation about covenant compliance comes from management.
Wrong (D): Omitting the covenant matter from the representation letter when a technical default exists would leave a gap in required representations about contractual noncompliance.$EXPL$
WHERE id = 8086;

-- Q8088: Written Representations [medium/L3]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (B): AU-C 580.12 requires representations about the reasonableness of significant assumptions, including management''s plans affecting carrying values. AU-C 580.05 clarifies that representations alone are not sufficient evidence, so the auditor must evaluate feasibility using corroborating evidence such as liquidation agreements or buyer commitments.
Wrong (A): Accepting the representation at face value without corroboration violates AU-C 580.05, which states representations do not substitute for other audit evidence.
Wrong (C): Writing down inventory to zero regardless of actual liquidation potential is an arbitrary and unsupported accounting treatment unrelated to the auditor''s evaluation responsibilities.
Wrong (D): Excluding the discontinued inventory from the representation letter would remove coverage of a material item requiring management''s specific representations.$EXPL$
WHERE id = 8088;

-- Q8131: Written Representations [hard/L4]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (B): Under AU-C 580.A25, when contradictory evidence exists regarding a written representation, the auditor must investigate and reconsider the reliability of other representations. The auditor should also evaluate the effect on the audit opinion and management''s integrity before determining the appropriate response.
Wrong (A): Written representations do not constitute sufficient appropriate audit evidence on their own under AU-C 580.05, especially when contradicted by documentary evidence.
Wrong (C): Withdrawing without further procedures is premature; the auditor should first investigate the inconsistency and evaluate its broader implications for the audit.
Wrong (D): Requesting a second letter that supersedes the original does not resolve the underlying contradiction or address the reliability concern raised by the conflicting evidence.$EXPL$
WHERE id = 8131;

-- Q8133: Written Representations [easy/L2]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (D): Under AU-C 580.15, the management representation letter should be dated as of the date of the auditor''s report. This ensures management''s representations cover the entire period, including subsequent events through the report date of March 3, 2026.
Wrong (A): The balance sheet date of December 31, 2025 is too early because events between year-end and the report date must also be covered by management''s representations.
Wrong (B): The fieldwork completion date of February 20, 2026 predates the report and would leave a gap in representation coverage for events occurring after fieldwork.
Wrong (C): The physical signing date is not the controlling date; AU-C 580.15 specifies the letter should bear the auditor''s report date regardless of when it is physically signed.$EXPL$
WHERE id = 8133;

-- Q8134: Written Representations [medium/L2]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (C): Under AU-C 580.A11, the auditor may request representations about accounting estimates, including that management believes the methods, assumptions, and data used are appropriate and reasonable. This ensures management takes responsibility for the estimate''s basis.
Wrong (A): Confirmation of using the same method as the prior year is not required; methods may appropriately change when circumstances change, so consistency alone is not the relevant representation.
Wrong (B): No estimate can provide assurance about future outcomes; representing that no future adjustment will be needed is inappropriate and unenforceable.
Wrong (D): A statement that actual bad debts will not exceed the estimate is a guarantee of future results that management cannot provide and the standard does not require.$EXPL$
WHERE id = 8134;

-- Q8137: Written Representations [hard/L4]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (A): Under AU-C 580.20, when management qualifies a representation, the auditor must investigate the reasons for the exception, assess its effect on other representations, and determine the impact on the audit opinion. The environmental remediation qualification requires understanding before proceeding.
Wrong (B): Management does not have a right to limit the scope of representations; a qualification signals a potential scope limitation or integrity concern requiring investigation.
Wrong (C): An emphasis-of-matter paragraph is not the appropriate response to a qualified representation; it addresses matters adequately presented in the financial statements, not representation deficiencies.
Wrong (D): Rejecting the letter outright and requiring resubmission is premature; the auditor should first evaluate the circumstances and determine whether the qualification can be resolved.$EXPL$
WHERE id = 8137;

-- Q8138: Written Representations [medium/L3]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (C): Under AU-C 580.15, the representation letter must be dated as of the date of the auditor''s report to ensure continuous coverage. Since the report is dated March 10, the letter should also bear that date, requiring a corrected letter.
Wrong (A): There is no five-business-day grace period in auditing standards; the letter date must match the auditor''s report date per AU-C 580.15.
Wrong (B): The fact that the letter covers through December 31 is insufficient; the representation must extend through the report date to cover subsequent events under AU-C 560.
Wrong (D): Changing the report date to match the letter would improperly extend the auditor''s subsequent events responsibilities without cause and is not the appropriate remedy.$EXPL$
WHERE id = 8138;

-- Q8141: Written Representations [hard/L4]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (C): Under AU-C 580.04, written representations are required for every audit with no exceptions for entity size. Oral representations do not substitute for written ones because they lack the reliability and retention characteristics needed for audit documentation.
Wrong (A): There is no small entity exception under AU-C 580 permitting verbal confirmation in lieu of written representations, regardless of entity size or ownership structure.
Wrong (B): Waiving the written representation requirement based on cooperation or transparency is not permitted; AU-C 580.04 makes written representations mandatory for all audits.
Wrong (D): The engagement letter defines the terms of the engagement and serves a different purpose than the representation letter, which covers specific assertions about the financial statements under AU-C 580.$EXPL$
WHERE id = 8141;

-- Q8143: Written Representations [medium/L2]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (B): Under AU-C 580.11, when uncorrected misstatements exist, the representation letter must include management''s acknowledgment that the effects are immaterial, individually and in the aggregate, to the financial statements as a whole. A summary of uncorrected items is typically attached.
Wrong (A): Representing that misstatements were corrected in the subsequent period is not the required representation; AU-C 580.11 requires an immateriality acknowledgment, not a subsequent correction claim.
Wrong (C): Attributing misstatements to system errors that have been resolved does not address the required representation about immateriality of the uncorrected items in the current-period statements.
Wrong (D): The auditor does not approve management''s decision to leave items uncorrected; management bears sole responsibility for the financial statements and the judgment of immateriality.$EXPL$
WHERE id = 8143;

-- Q8147: Written Representations [hard/L4]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (D): Under AU-C 580.A24, when written representations are contradicted by other audit evidence, the auditor must reconsider the reliability of all representations and assess management''s integrity. A $425,000 undisclosed related-party loan directly contradicts the representation and cannot be dismissed as a mere oversight.
Wrong (A): Simply accepting the CFO''s explanation and amending the letter does not address the broader reliability concern raised by the contradiction regarding management''s integrity.
Wrong (B): Issuing a qualified opinion solely for the disclosure omission is premature; the auditor must first evaluate whether the contradiction affects the reliability of all representations.
Wrong (C): Documenting the finding in the management letter and proceeding with an unmodified opinion ignores the contradictory evidence and the requirement to reassess management''s integrity.$EXPL$
WHERE id = 8147;

-- Q8151: Written Representations [medium/L3]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (B): Under AU-C 580.15, the auditor should obtain the signed management representation letter on or before the date of the auditor''s report. Issuing the report without the signed letter is a departure from professional standards because the auditor lacked required audit evidence when the opinion was formed.
Wrong (A): The delayed receipt does have implications; the auditor lacked required evidence at the time the opinion was formed, creating a procedural deficiency that must be evaluated.
Wrong (C): The representation letter is not automatically void because of late signing; however, the procedural deficiency of issuing the report without it must be assessed.
Wrong (D): Reissuing the report with a revised date of March 20 is not necessarily required; the appropriate response depends on evaluating the procedural deficiency and its implications.$EXPL$
WHERE id = 8151;

-- Q8250: Written Representations [medium/L3]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (A): Under AU-C 580.15, the written representation letter is addressed to the auditor. The letter is a direct communication from management to the engagement team confirming matters relevant to the audit.
Wrong (B): The board of directors receives governance communications, not the management representation letter, which serves an evidentiary purpose for the auditor.
Wrong (C): External legal counsel is not the addressee; the representation letter is directed to the auditor, not to the entity''s attorneys.
Wrong (D): The SEC receives regulatory filings, not management representation letters; the letter is an audit communication between management and the auditor.$EXPL$
WHERE id = 8250;

-- Q8327: Written Representations [hard/L4]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (C): Under AU-C 580.19 and AU-C 240.35, when contradictory evidence from those charged with governance challenges management''s representations, the auditor must investigate the inconsistency, reassess the reliability of all representations, and determine the impact on the audit report. The audit committee chair''s disclosure of the undisclosed loan guarantee requires comprehensive evaluation.
Wrong (A): Relying on the signed letter as authoritative while ignoring contradictory information from the audit committee chair violates the auditor''s obligation to evaluate all evidence.
Wrong (B): Requesting corrections is too narrow; it assumes management will cooperate without addressing the deeper integrity concern raised by the undisclosed loan guarantee.
Wrong (D): Reporting the CEO directly to the SEC is not the auditor''s immediate obligation; the auditor must first evaluate the inconsistency and its implications for the audit.$EXPL$
WHERE id = 8327;

-- Q8404: Written Representations [medium/L2]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (B): AU-C 580.11 requires the management representation letter to be addressed to the auditor. The representations support the auditor''s conclusions, so the letter is directed to the engagement partner or audit firm performing the engagement.
Wrong (A): The audit committee chair has governance oversight but is not the addressee; written representations are a communication from management to the auditor, not to those charged with governance.
Wrong (C): The board of directors receives governance communications from the auditor, but the representation letter flows in the opposite direction—from management to the auditor.
Wrong (D): The SEC receives regulatory filings and is not a party to the management representation letter, which is an audit-specific communication.$EXPL$
WHERE id = 8404;

-- Q8421: Written Representations [medium/L3]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (A): Under AU-C 580.17, the auditor must evaluate whether written representations are consistent with other audit evidence. A 200-basis-point discount rate deviation from market-comparable rates raises questions about the reasonableness of fair value assumptions, requiring assessment of potential misstatement under AU-C 540.
Wrong (B): While management exercises judgment in selecting assumptions, the auditor must independently evaluate reasonableness when evidence suggests a material deviation from market data.
Wrong (C): Requiring a third-party specialist before signing the letter is not a standard requirement; the auditor evaluates reasonableness using available evidence and may engage a specialist at the auditor''s discretion.
Wrong (D): Removing the fair value representation because Level 3 measurements are subjective would eliminate required content; subjectivity does not exempt management from representing the reasonableness of assumptions.$EXPL$
WHERE id = 8421;

-- Q8425: Written Representations [medium/L3]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (A): Under AU-C 580.17, the auditor evaluates contradictions between written representations and other audit evidence, including attorney response letters under AU-C 501. A probable loss that is material and estimable requires accrual under ASC 450-20, and the inconsistency between management''s representation and the attorney''s assessment must be resolved.
Wrong (B): While management makes accounting decisions, the auditor cannot ignore contradictory evidence from the entity''s own legal counsel regarding loss contingencies.
Wrong (C): The auditor does not override management''s judgment; rather, the auditor evaluates the inconsistency and determines whether an adjustment or disclosure is required.
Wrong (D): Requesting a revised attorney''s response to align with management''s assessment would compromise the independence and reliability of the attorney''s professional evaluation.$EXPL$
WHERE id = 8425;

-- Q8569: Written Representations [hard/L4]
-- Issues: #3
UPDATE questions SET
  explanation = $EXPL$Correct (D): AU-C 580.09 requires the auditor to request representations from management with appropriate responsibilities and knowledge of the matters concerned. When signatories lack knowledge of specific transactions, the auditor should evaluate whether additional or different personnel should provide representations.
Wrong (A): The CEO''s general confirmation does not address the knowledge gap; accepting representations from someone who cannot explain specific entries undermines their reliability.
Wrong (B): Having the divisional controller co-sign as the sole corrective action is too narrow; the auditor must first evaluate the overall adequacy of the knowledge base supporting all representations.
Wrong (C): Concluding automatic unreliability and immediately withdrawing is premature; AU-C 580 requires evaluation and discussion before determining the appropriate response.$EXPL$
WHERE id = 8569;
