-- Migration: Stem rewrite -- TCP batch 3 (50 questions)
-- Generated by generate-stem-rewrite-scaffold.ts
-- Issues: #10 (citation in stem), #11 (short/no-scenario)

-- Q4346: Nontaxable Dispositions [easy/L2]
-- Issues: #11
-- Original stem: A taxpayer sells land with a basis of $100,000 for $250,000, receiving $50,000 in the year of sale and a $200,000 instal
UPDATE questions SET
  stem = $EXPL$In 2025, Marcus Delgado sells a parcel of undeveloped land to a private buyer for $250,000. Delgado''s adjusted basis in the land is $100,000. The buyer pays $50,000 at closing and signs a $200,000 installment note for the balance. What is the gross profit ratio on this installment sale?$EXPL$
WHERE id = 4346;

-- Q4347: Nontaxable Dispositions [easy/L2]
-- Issues: #11
-- Original stem: Using the previous example (60% gross profit ratio, $50,000 received in Year 1), how much gain does the taxpayer recogni
UPDATE questions SET
  stem = $EXPL$Marcus Delgado sold land on the installment method with a gross profit ratio of 60%. In Year 1, he receives a $50,000 payment from the buyer. How much gain does Delgado recognize in Year 1?$EXPL$
WHERE id = 4347;

-- Q4349: Nontaxable Dispositions [medium/L2]
-- Issues: #11
-- Original stem: A taxpayer sells property to her brother on the installment method. The brother resells the property within 2 years. Und
UPDATE questions SET
  stem = $EXPL$In January 2025, Linda Pearson sells commercial property to her brother, Todd, for $600,000 on the installment method. Eighteen months later, Todd resells the property to an unrelated buyer for $650,000. Under the related party installment sale rules, what happens to Linda''s remaining deferred gain?$EXPL$
WHERE id = 4349;

-- Q4353: Nontaxable Dispositions [medium/L2]
-- Issues: #11
-- Original stem: Using the previous example ($400,000 proceeds, $250,000 basis, $350,000 replacement property, $50,000 gain recognized),
UPDATE questions SET
  stem = $EXPL$A warehouse owned by Ridgeway Storage is destroyed by a fire in 2025. The insurance company pays $400,000 in proceeds, and the warehouse had an adjusted basis of $250,000. Ridgeway purchases a replacement warehouse for $350,000 and recognizes $50,000 of gain on the involuntary conversion. What is Ridgeway''s basis in the replacement property?$EXPL$
WHERE id = 4353;

-- Q4365: Nontaxable Dispositions [hard/L2]
-- Issues: #11
-- Original stem: A taxpayer sells property on the installment method and later disposes of the installment obligation by gift., what happ
UPDATE questions SET
  stem = $EXPL$In 2024, Carolyn Whitfield sold a rental property on the installment method, deferring $180,000 of gain through a $300,000 installment note. In 2025, Carolyn gifts the installment note to her adult son, Derek. The note has a fair market value of $280,000 at the time of the gift. What happens when the installment obligation is disposed of by gift?$EXPL$
WHERE id = 4365;

-- Q4380: Related Party Transactions [medium/L2]
-- Issues: #11
-- Original stem: A taxpayer sells depreciable equipment to his wholly owned corporation for $120,000. The equipment cost $80,000 and has
UPDATE questions SET
  stem = $EXPL$Vernon Mitchell sells fully depreciated packaging equipment (original cost $80,000, adjusted basis $0) to Mitchell Enterprises Inc., a corporation he wholly owns, for $120,000. How is the $120,000 gain on this related party sale of depreciable property treated?$EXPL$
WHERE id = 4380;

-- Q4381: Related Party Transactions [medium/L2]
-- Issues: #11
-- Original stem: 1), if a partner owning more than 50% of the capital or profits interest sells property to the partnership at a loss, th
UPDATE questions SET
  stem = $EXPL$Diana Hartwell owns a 65% capital and profits interest in Cedar Ridge Partners. In 2025, she sells a commercial lot to the partnership for $180,000, which is $40,000 less than her adjusted basis of $220,000. How is the $40,000 loss on this sale treated?$EXPL$
WHERE id = 4381;

-- Q4385: Related Party Transactions [medium/L2]
-- Issues: #11
-- Original stem: A taxpayer sells stock at a $8,000 loss on March 10. The taxpayer's spouse purchases the same stock on March 25. Does th
UPDATE questions SET
  stem = $EXPL$On March 10, 2025, Brian Novak sells 200 shares of Greenfield Corp stock at an $8,000 loss. On March 25, Brian''s wife, Jillian, purchases 200 shares of the same Greenfield Corp stock through her brokerage account. Does the wash sale rule apply to Brian''s loss?$EXPL$
WHERE id = 4385;

-- Q4390: Related Party Transactions [medium/L2]
-- Issues: #11
-- Original stem: 2), if an accrual-basis corporation accrues a $50,000 expense payable to a related cash-basis taxpayer, when can the cor
UPDATE questions SET
  stem = $EXPL$Weston Manufacturing Inc., an accrual-basis C corporation, accrues a $50,000 management fee on December 31, 2025, payable to its sole shareholder, Patricia Weston, who reports on the cash basis. Patricia does not receive payment until March 2026. When can Weston Manufacturing deduct the $50,000 expense?$EXPL$
WHERE id = 4390;

-- Q4397: Related Party Transactions [easy/L2]
-- Issues: #11
-- Original stem: A taxpayer sells a rental building (basis $200,000, FMV $350,000) to her 100%-owned S corporation., the $150,000 gain is
UPDATE questions SET
  stem = $EXPL$Naomi Kessler sells a rental office building with an adjusted basis of $200,000 and a fair market value of $350,000 to Kessler Properties LLC, her 100%-owned S corporation. The building will continue to be used as a rental property by the S corporation. How is the $150,000 gain characterized, and why?$EXPL$
WHERE id = 4397;

-- Q4967: Multi-Jurisdictional Tax Planning [easy/L2]
-- Issues: #11
-- Original stem: Under the Wayfair decision, which standard did the U.S. Supreme Court establish for state sales tax collection obligatio
UPDATE questions SET
  stem = $EXPL$Riverstone Home Goods, an online retailer based in Oregon, ships products to customers in 42 states but has no physical offices, warehouses, or employees outside Oregon. Several states have sent notices requiring Riverstone to collect and remit sales tax. Under the Wayfair decision, which standard did the U.S. Supreme Court establish for state sales tax collection obligations on remote sellers?$EXPL$
WHERE id = 4967;

-- Q4986: Entity Formation and Restructuring [easy/L2]
-- Issues: #10
-- Original stem: In a Type A reorganization under Section 368(a)(1)(A), a target corporation merges into an acquiring corporation. Which
UPDATE questions SET
  stem = $EXPL$Westfield Industries merges into Grandview Corp under the state merger statute. Westfield shareholders receive Grandview stock in exchange for their Westfield shares, and Westfield ceases to exist. For this statutory merger to qualify as a tax-free reorganization, which requirement must be satisfied?$EXPL$
WHERE id = 4986;

-- Q4995: Entity Formation and Restructuring [hard/L2]
-- Issues: #10
-- Original stem: In a Type D reorganization under Section 368(a)(1)(D), a corporation transfers assets to a controlled corporation. What
UPDATE questions SET
  stem = $EXPL$Vanguard Corp transfers its operating division assets to a newly formed subsidiary, Atlas Corp, and distributes the Atlas stock to Vanguard shareholders in a divisive transaction. For this transfer to qualify as a tax-free divisive reorganization, what is the minimum stock ownership requirement for the transferee corporation?$EXPL$
WHERE id = 4995;

-- Q5917: Passive Activity and At-Risk Rules [easy/L1]
-- Issues: #10
-- Original stem: What is the maximum annual rental loss that an active participant may deduct against nonpassive income under the Section
UPDATE questions SET
  stem = $EXPL$Joanne Fielding owns a rental duplex that she actively manages, approving tenants and setting lease terms. Her modified AGI is $78,000. The duplex generates a $32,000 rental loss for 2025. What is the maximum annual rental loss that an active participant may deduct against nonpassive income under the special allowance?$EXPL$
WHERE id = 5917;

-- Q5923: Passive Activity and At-Risk Rules [easy/L1]
-- Issues: #11
-- Original stem: 7), how many hours must a taxpayer spend in real property trades or businesses to meet the first prong of the real estat
UPDATE questions SET
  stem = $EXPL$Sandra Okafor is a licensed real estate broker who spends extensive time managing her brokerage and rental portfolio. She wants to qualify as a real estate professional so her rental losses are not automatically treated as passive. How many hours must she spend in real property trades or businesses to meet the first prong of the real estate professional test?$EXPL$
WHERE id = 5923;

-- Q5925: Passive Activity and At-Risk Rules [easy/L2]
-- Issues: #10
-- Original stem: Fitzgerald invests $35,000 cash in a partnership and personally guarantees $25,000 of partnership recourse debt. What is
UPDATE questions SET
  stem = $EXPL$Fitzgerald invests $35,000 cash in a partnership that acquires commercial equipment. He also personally guarantees $25,000 of the partnership''s recourse debt to a local bank. What is Fitzgerald''s at-risk amount for purposes of deducting losses from this activity?$EXPL$
WHERE id = 5925;

-- Q5940: Passive Activity and At-Risk Rules [medium/L2]
-- Issues: #10
-- Original stem: Dr. Evelyn Whitmore has $310,000 of W-2 income, $48,000 of passive rental income, and $22,000 of passive losses from a l
UPDATE questions SET
  stem = $EXPL$Dr. Evelyn Whitmore has $310,000 of W-2 income, $48,000 of passive rental income, and $22,000 of passive losses from a limited partnership. She files jointly with MAGI of $358,000. What is the net investment income tax attributable to her passive activities?$EXPL$
WHERE id = 5940;

-- Q5943: Passive Activity and At-Risk Rules [medium/L2]
-- Issues: #10
-- Original stem: Ramos holds interests in two passive activities: a publicly traded partnership (PTP) generating $18,000 in passive losse
UPDATE questions SET
  stem = $EXPL$Ramos holds interests in two passive activities: a publicly traded partnership (PTP) generating $18,000 in passive losses and a private limited partnership generating $25,000 in passive income. What is the correct treatment of the $18,000 PTP loss?$EXPL$
WHERE id = 5943;

-- Q5961: Passive Activity and At-Risk Rules [easy/L1]
-- Issues: #10
-- Original stem: Westbrook Consulting LLC invests in a leveraged equipment leasing venture. The tax manager is determining whether the at
UPDATE questions SET
  stem = $EXPL$Westbrook Consulting LLC invests in a leveraged equipment leasing venture. The tax manager is determining whether the at-risk limitation rules apply to the entity. Which type of entity is generally exempt from these rules?$EXPL$
WHERE id = 5961;

-- Q5998: Passive Activity and At-Risk Rules [easy/L1]
-- Issues: #10
-- Original stem: Brennan owns a lakefront cabin that she rents to vacationers for weekly stays throughout the summer. She also owns a com
UPDATE questions SET
  stem = $EXPL$Brennan owns a lakefront cabin that she rents to vacationers for weekly stays throughout the summer. She also owns a commercial office building leased to a single tenant on a five-year term. For passive activity purposes, which characteristic defines an activity as a rental activity?$EXPL$
WHERE id = 5998;

-- Q6014: Passive Activity and At-Risk Rules [easy/L1]
-- Issues: #10
-- Original stem: Diane owns a duplex that generated a $22,000 rental loss in 2025. She personally approved the tenants and set rental ter
UPDATE questions SET
  stem = $EXPL$Diane owns a duplex that generated a $22,000 rental loss in 2025. She personally approved the tenants and set rental terms but hired a property manager for day-to-day operations. What does active participation in a rental real estate activity require?$EXPL$
WHERE id = 6014;

-- Q6029: Passive Activity and At-Risk Rules [hard/L4]
-- Issues: #10
-- Original stem: Gallagher plans to sell her entire interest in a passive activity for $400,000, generating a $160,000 gain. She has $145
UPDATE questions SET
  stem = $EXPL$Gallagher plans to sell her entire interest in a passive activity for $400,000, generating a $160,000 gain. She has $145,000 in suspended passive losses from this activity. The buyer proposes a 4-year installment arrangement with equal annual payments. Gallagher''s CPA notes that electing out of the installment method would require recognizing the full $160,000 gain in the year of sale. Evaluate whether Gallagher should elect out of the installment method.$EXPL$
WHERE id = 6029;

-- Q6030: Passive Activity and At-Risk Rules [easy/L1]
-- Issues: #10
-- Original stem: Thornton LLC leases heavy construction equipment to contractors under long-term agreements. The owners are determining w
UPDATE questions SET
  stem = $EXPL$Thornton LLC leases heavy construction equipment to contractors under long-term agreements. The owners are determining whether the activity is classified as a rental activity for passive loss purposes. Which characteristic defines an activity as a rental activity?$EXPL$
WHERE id = 6030;

-- Q6035: Passive Activity and At-Risk Rules [easy/L1]
-- Issues: #11
-- Original stem: 3), which type of interest in an oil and gas activity is exempt from the passive activity loss rules?
UPDATE questions SET
  stem = $EXPL$Fletcher Energy Partners operates several oil and gas wells in West Texas. One of the investors, Carl Draper, holds a direct working interest through a general partnership that does not limit his personal liability. Carl''s tax advisor is evaluating whether the passive activity loss rules apply. Which type of interest in an oil and gas activity is exempt from the passive activity loss rules?$EXPL$
WHERE id = 6035;

-- Q6059: Passive Activity and At-Risk Rules [easy/L1]
-- Issues: #10
-- Original stem: Simone owns a duplex that generates a $20,000 rental loss for 2025. Her modified AGI is $85,000 and she personally appro
UPDATE questions SET
  stem = $EXPL$Simone owns a duplex that generates a $20,000 rental loss for 2025. Her modified AGI is $85,000 and she personally approves tenants and sets rental terms. What level of involvement is required for a taxpayer to claim the special rental real estate loss allowance?$EXPL$
WHERE id = 6059;

-- Q6080: Passive Activity and At-Risk Rules [easy/L1]
-- Issues: #10
-- Original stem: Dr. Holt, a full-time surgeon, owns a 30% interest in a restaurant where she spends fewer than 50 hours per year. She is
UPDATE questions SET
  stem = $EXPL$Dr. Holt, a full-time surgeon, owns a 30% interest in a restaurant where she spends fewer than 50 hours per year. She is determining how to classify the restaurant for tax purposes. What is the general definition of a passive activity?$EXPL$
WHERE id = 6080;

-- Q7788: Retirement Plans and Education Savings [easy/L1]
-- Issues: #10
-- Original stem: Elena Torres contributes $20,000 to an Illinois Section 529 plan for her daughter''s future college expenses. Elena is p
UPDATE questions SET
  stem = $EXPL$Elena Torres contributes $20,000 to an Illinois 529 college savings plan for her daughter''s future tuition expenses. Elena is preparing her federal income tax return and asks her CPA about the deductibility of the contribution. What is the federal income tax treatment of contributions made to a 529 plan?$EXPL$
WHERE id = 7788;

-- Q7797: Retirement Plans and Education Savings [easy/L1]
-- Issues: #11
-- Original stem: Under SECURE 2.0, what is the excise tax rate for failing to take a required minimum distribution from a traditional IRA
UPDATE questions SET
  stem = $EXPL$Arthur Grayson, age 76, failed to take his required minimum distribution of $18,000 from his traditional IRA for 2025. His tax advisor explains that the penalty structure for missed RMDs was changed by SECURE 2.0. What is the current excise tax rate for failing to take a required minimum distribution?$EXPL$
WHERE id = 7797;

-- Q12641: Individual Tax Planning: Compensation [medium/L2]
-- Issues: #10
-- Original stem: Marlow Industries offers an employee stock purchase plan (ESPP) under Section 423. The plan allows employees to purchase
UPDATE questions SET
  stem = $EXPL$Marlow Industries offers a qualified employee stock purchase plan (ESPP) that allows employees to purchase company stock at a discount. The HR director is reviewing whether the plan''s discount percentage complies with the requirements for a qualified plan. What is the maximum discount from fair market value that a qualified ESPP may offer?$EXPL$
WHERE id = 12641;

-- Q12645: Individual Tax Planning: Compensation [easy/L2]
-- Issues: #11
-- Original stem: Harper & Associates provides employee Ben Calloway with $6,000 in dependent care assistance during 2026 through a qualif
UPDATE questions SET
  stem = $EXPL$Harper & Associates provides employee Ben Calloway with $6,000 in dependent care assistance during 2026 through a qualified dependent care assistance program. Calloway is married filing jointly. What amount of the dependent care assistance must Calloway include in gross income?$EXPL$
WHERE id = 12645;

-- Q12653: Individual Tax Planning: Compensation [medium/L3]
-- Issues: #10
-- Original stem: Elise Brannigan is a single taxpayer who earns $140,000 of qualified business income from her pass-through landscaping L
UPDATE questions SET
  stem = $EXPL$Elise Brannigan is a single taxpayer who earns $140,000 of qualified business income from her pass-through landscaping LLC, which is not a specified service trade or business. Her taxable income before the QBI deduction is $155,000, and she has no capital gains. What is her qualified business income deduction?$EXPL$
WHERE id = 12653;

-- Q12656: Individual Tax Planning: Compensation [easy/L1]
-- Issues: #10
-- Original stem: Coastal Resort & Spa provides free meals to its kitchen and front-desk staff in the hotel dining room during their shift
UPDATE questions SET
  stem = $EXPL$Coastal Resort & Spa provides free meals to its kitchen and front-desk staff in the hotel dining room during their shifts. The resort''s controller is reviewing whether these meals can be excluded from the employees'' gross income. What conditions must be met for employer-provided meals to be excluded from an employee''s income?$EXPL$
WHERE id = 12656;

-- Q12789: Wealth Transfer and Gifting Strategies [medium/L2]
-- Issues: #10
-- Original stem: Howard Brennan dies in 2026, leaving $3 million to his adult son, Kevin. Kevin does not need the funds and wants them to
UPDATE questions SET
  stem = $EXPL$Howard Brennan dies in 2026, leaving $3 million to his adult son, Kevin. Kevin does not need the funds and wants them to pass directly to his own children without making a taxable gift. Kevin''s attorney advises him to execute a qualified disclaimer. Which requirement must Kevin satisfy for the disclaimer to be valid?$EXPL$
WHERE id = 12789;

-- Q12905: Advanced Basis Calculations [medium/L2]
-- Issues: #10
-- Original stem: Nguyen purchases a 50% partnership interest for $300,000 when the partnership has total assets with a basis of $1,200,00
UPDATE questions SET
  stem = $EXPL$Nguyen purchases a 50% partnership interest for $300,000 when the partnership has total assets with a basis of $1,200,000 and FMV of $600,000. The partnership has not made a Section 754 election. Nguyen''s share of inside basis is $600,000. Under post-2004 rules, what is the partnership required to do regarding basis adjustments?$EXPL$
WHERE id = 12905;

-- Q12917: Advanced Basis Calculations [easy/L1]
-- Issues: #11
-- Original stem: 6), which type of financing qualifies as an exception to the general at-risk rules, allowing the borrowed amount to coun
UPDATE questions SET
  stem = $EXPL$Lakewood Properties LLC purchases a $2,000,000 apartment building using $500,000 in equity from its members and a $1,500,000 nonrecourse mortgage from a commercial bank, secured by the building itself. The tax advisor is evaluating the at-risk amounts for each member. Which type of financing qualifies as an exception to the general at-risk rules, allowing the borrowed amount to count toward the taxpayer''s at-risk amount?$EXPL$
WHERE id = 12917;

-- Q12920: Advanced Basis Calculations [medium/L2]
-- Issues: #10
-- Original stem: Lawson is a 1/3 partner in Pinnacle Partners and passes away. At death, Lawson's partnership interest has an FMV of $500
UPDATE questions SET
  stem = $EXPL$Lawson is a 1/3 partner in Pinnacle Partners and passes away in 2025. At death, Lawson''s partnership interest has an FMV of $500,000 and an outside basis of $200,000. The partnership''s total inside basis is $900,000 (Lawson''s 1/3 share = $300,000). The partnership has a Section 754 election in effect. Lawson''s heir inherits the interest. What is the heir''s basis adjustment to partnership assets?$EXPL$
WHERE id = 12920;

-- Q13250: Entity Formation and Liquidation [easy/L1]
-- Issues: #11
-- Original stem: , when a parent corporation owns at least 80% of a subsidiary's voting power and value, the tax-free liquidation treatme
UPDATE questions SET
  stem = $EXPL$Baxter Holdings Inc. owns 90% of the voting stock and 92% of the total value of its subsidiary, Sterling Components Corp. Baxter''s board of directors adopts a plan to liquidate Sterling and absorb its assets. Because Baxter meets the 80% ownership threshold for a tax-free subsidiary liquidation, is the nonrecognition treatment elective or mandatory?$EXPL$
WHERE id = 13250;

-- Q13266: Entity Formation and Liquidation [medium/L3]
-- Issues: #10
-- Original stem: Caldwell Corp owns 100% of Hayes Inc. and adopts a plan to liquidate Hayes. The liquidation takes 18 months to complete.
UPDATE questions SET
  stem = $EXPL$Caldwell Corp owns 100% of Hayes Inc. and adopts a plan to liquidate Hayes. The liquidation takes 18 months to complete. What timing requirement must the liquidating distributions satisfy for tax-free treatment to apply in a parent-subsidiary liquidation?$EXPL$
WHERE id = 13266;

-- Q13270: Entity Formation and Liquidation [hard/L4]
-- Issues: #10
-- Original stem: A CPA is reviewing a Section 351 transaction where Marchetti contributes property (basis $500,000, FMV $800,000) to a co
UPDATE questions SET
  stem = $EXPL$A CPA is reviewing a tax-free incorporation where Marchetti contributes property (basis $500,000, FMV $800,000) to a corporation for stock. Before the transfer, Marchetti encumbers the property with a $400,000 loan and uses the proceeds for personal expenses unrelated to the business. The IRS argues that the liability assumption was tax-motivated. If the IRS prevails, what is the tax consequence compared to normal treatment of assumed liabilities?$EXPL$
WHERE id = 13270;

-- Q13274: Entity Formation and Liquidation [easy/L2]
-- Issues: #10
-- Original stem: Harper contributes property for 85% of a corporation's voting stock but only 70% of its single class of nonvoting prefer
UPDATE questions SET
  stem = $EXPL$Harper contributes property to a new corporation in exchange for 85% of its voting stock but only 70% of its single class of nonvoting preferred stock. The remaining interests are held by unrelated parties who did not participate in the exchange. Does Harper satisfy the control requirement for a tax-free incorporation?$EXPL$
WHERE id = 13274;

-- Q13279: Entity Formation and Liquidation [hard/L4]
-- Issues: #10
-- Original stem: Keystone Holdings is acquiring 100% of Pinnacle Services, an S corporation, for $4,000,000. Pinnacle's assets include de
UPDATE questions SET
  stem = $EXPL$Keystone Holdings is acquiring 100% of Pinnacle Services, an S corporation, for $4,000,000. Pinnacle''s assets include depreciable equipment (basis $500,000, FMV $1,200,000), goodwill (basis $0, FMV $1,800,000), and inventory (basis $600,000, FMV $1,000,000). The selling shareholders have a combined stock basis of $1,100,000. A tax advisor is evaluating whether a deemed asset sale election benefits the buyer. Which factor provides the primary advantage to Keystone as the buyer?$EXPL$
WHERE id = 13279;

-- Q13496: Owner-Entity Transactions [easy/L2]
-- Issues: #11
-- Original stem: A father makes a $75,000 interest-free gift loan to his daughter. The daughter's net investment income for the year is $
UPDATE questions SET
  stem = $EXPL$Gerald Conway lends $75,000 to his daughter, Megan, to help her purchase a condominium. The loan bears no interest and has no fixed repayment schedule. Megan''s net investment income for 2025 is $800. Gerald''s CPA is determining the amount of imputed interest on this below-market gift loan. What is the imputed interest for the year?$EXPL$
WHERE id = 13496;

-- Q13498: Owner-Entity Transactions [easy/L1]
-- Issues: #10
-- Original stem: Montrose Corp is evaluating whether a stock redemption from a 40% shareholder qualifies as a sale or exchange. The share
UPDATE questions SET
  stem = $EXPL$Montrose Corp is evaluating whether a stock redemption from a 40% shareholder qualifies as a sale or exchange. The shareholder''s spouse and adult children also own shares. What is the purpose of the constructive ownership rules that attribute stock ownership among related parties?$EXPL$
WHERE id = 13498;

-- Q13560: Entity Formation and Restructuring [hard/L3]
-- Issues: #10
-- Original stem: Apex Corp forms a wholly owned subsidiary, Apex Sub, and merges Target Inc. into Apex Sub under applicable state law. Ap
UPDATE questions SET
  stem = $EXPL$Apex Corp forms a wholly owned subsidiary, Apex Sub, and merges Target Inc. into Apex Sub under applicable state law. Apex issues its own voting stock to Target shareholders, and Apex Sub receives all of Target''s assets and liabilities. Target dissolves. For this forward triangular merger to qualify as a tax-free reorganization, which additional requirement must be satisfied beyond the standard reorganization requirements?$EXPL$
WHERE id = 13560;

-- Q13568: Entity Formation and Restructuring [medium/L3]
-- Issues: #10
-- Original stem: Monarch Corp creates Merger Sub and merges Merger Sub into Target Corp, with Target surviving. Monarch issues its voting
UPDATE questions SET
  stem = $EXPL$Monarch Corp creates Merger Sub and merges Merger Sub into Target Corp, with Target surviving. Monarch issues its voting stock to Target''s former shareholders, who surrender their Target shares. After the merger, Target holds all of its historic assets and liabilities and becomes a wholly owned subsidiary of Monarch. For this reverse triangular merger to qualify as a tax-free reorganization, what additional requirement applies?$EXPL$
WHERE id = 13568;

-- Q13575: Entity Formation and Restructuring [medium/L2]
-- Issues: #10
-- Original stem: Spruce Corp transfers all of its operating assets to Cedar Corp, a newly formed corporation, in exchange for 100% of Ced
UPDATE questions SET
  stem = $EXPL$Spruce Corp transfers all of its operating assets to Cedar Corp, a newly formed corporation, in exchange for 100% of Cedar stock. Spruce then distributes the Cedar stock to its shareholders and liquidates. Spruce''s shareholders owned 100% of both Spruce and Cedar. Which requirement distinguishes an acquisitive divisive reorganization from other reorganization types?$EXPL$
WHERE id = 13575;

-- Q13577: Entity Formation and Restructuring [easy/L1]
-- Issues: #11
-- Original stem: , if a shareholder receives boot in a qualifying reorganization and realizes a loss on the exchange, the shareholder:
UPDATE questions SET
  stem = $EXPL$Pinnacle Corp merges into Broadstone Inc. in a qualifying tax-free reorganization. Shareholder Rachel Whitman exchanges her Pinnacle shares (basis $250,000) for Broadstone stock worth $210,000 and $20,000 in cash. Rachel realizes a $20,000 loss on the exchange. How is the loss treated when a shareholder receives boot in a qualifying reorganization but realizes a loss?$EXPL$
WHERE id = 13577;

-- Q13582: Entity Formation and Restructuring [easy/L1]
-- Issues: #10
-- Original stem: Warren holds 500 shares of Redwood Corp Class A voting common stock. Redwood offers shareholders the option to exchange
UPDATE questions SET
  stem = $EXPL$Warren holds 500 shares of Redwood Corp Class A voting common stock. Redwood offers shareholders the option to exchange their Class A shares for newly issued Class B nonvoting common stock on a share-for-share basis. Under what circumstances is a tax-free exchange of stock permitted within the same corporation?$EXPL$
WHERE id = 13582;

-- Q13743: Entity Tax Compliance: NOLs and Consolidated Returns [medium/L2]
-- Issues: #10
-- Original stem: Harmon Group files a consolidated return. During 2025, Subsidiary A recognizes a $200,000 Section 1231 gain on sale of e
UPDATE questions SET
  stem = $EXPL$Harmon Group files a consolidated return. During 2025, Subsidiary A recognizes a $200,000 gain on the sale of equipment held for more than one year, while Subsidiary B recognizes a $275,000 loss on the sale of real property also held for more than one year. What is the consolidated group''s net result from these transactions?$EXPL$
WHERE id = 13743;

-- Q14070: Individual Tax Planning: Compensation [hard/L3]
-- Issues: #10
-- Original stem: Clearwater Industries (a publicly traded company) maintains a Section 409A nonqualified deferred compensation plan. Chie
UPDATE questions SET
  stem = $EXPL$Clearwater Industries, a publicly traded company, maintains a nonqualified deferred compensation plan. Chief Operating Officer Daniel Frost, a specified employee, separates from service on April 1, 2026, with $400,000 of deferred compensation payable upon separation. The plan provides for lump-sum distribution upon separation from service. Frost''s tax advisor must determine the earliest permissible payment date. When may Clearwater distribute the deferred compensation to Frost?$EXPL$
WHERE id = 14070;
