-- Migration: Stem rewrite -- TCP batch 5 (12 questions)
-- Generated by generate-stem-rewrite-scaffold.ts
-- Issues: #10 (citation in stem), #11 (short/no-scenario)

-- Q14655: International Tax [easy/L1]
-- Issues: #10
-- Original stem: Aragon Ltd., a CFC incorporated in the UK, currently uses a March 31 fiscal year. Its majority U.S. shareholder files on a calendar-year basis. Under Section 898, what taxable year is required for a specified foreign corporation?
UPDATE questions SET
  stem = $EXPL$Aragon Ltd., a controlled foreign corporation incorporated in the UK, currently uses a March 31 fiscal year. Its majority U.S. shareholder files on a calendar-year basis. What taxable year is required for a specified foreign corporation in this situation?$EXPL$
WHERE id = 14655;

-- Q14658: International Tax [hard/L3]
-- Issues: #10
-- Original stem: Whitfield Corp, a U.S. parent, operates a branch in Country N that generates a $3,000,000 loss. Country N's tax rules allow a related Country N entity to use this same loss against its local income. Under the dual consolidated loss rules of Section 1503(d), Whitfield wants to use the $3,000,000 loss against its U.S. consolidated group income. The tax advisor considers filing a domestic use agreement. Apply Section 1503(d) to determine whether Whitfield can claim the loss in the United States.
UPDATE questions SET
  stem = $EXPL$Whitfield Corp, a U.S. parent, operates a branch in Country N that generates a $3,000,000 loss. Country N''s tax rules allow a related Country N entity to use this same loss against its local income. Whitfield wants to use the $3,000,000 loss against its U.S. consolidated group income and its tax advisor considers filing a domestic use agreement. Under the dual consolidated loss rules, can Whitfield claim the loss in the United States?$EXPL$
WHERE id = 14658;

-- Q14679: Capital Structure Tax Planning [hard/L4]
-- Issues: #10
-- Original stem: Apex Corp has $500,000 of disallowed business interest expense carried forward under Section 163(j). Apex then undergoes an ownership change as defined under Section 382. The Section 382 annual limitation is $200,000. A tax advisor must evaluate how the carried-forward interest is treated post-ownership change. What is the correct analysis?
UPDATE questions SET
  stem = $EXPL$Apex Corp has $500,000 of disallowed business interest expense carried forward under the business interest limitation rules. Apex then undergoes an ownership change that triggers annual loss-usage limitations. The computed annual limitation is $200,000. A tax advisor must evaluate how the carried-forward interest is treated post-ownership change. What is the correct analysis?$EXPL$
WHERE id = 14679;

-- Q14684: Capital Structure Tax Planning [medium/L2]
-- Issues: #10
-- Original stem: Whitmore Industries reports the following for 2025: taxable income before interest deduction of $2,000,000, business interest expense of $800,000, business interest income of $100,000, a net operating loss deduction of $300,000, and a Section 199A deduction of $150,000. Both the NOL and 199A deductions are already reflected in the $2,000,000 figure. What is Whitmore's adjusted taxable income (ATI) for Section 163(j) purposes?
UPDATE questions SET
  stem = $EXPL$Whitmore Industries reports the following for 2025: taxable income before interest deduction of $2,000,000, business interest expense of $800,000, business interest income of $100,000, a net operating loss deduction of $300,000, and a qualified business income deduction of $150,000. Both the NOL and QBI deductions are already reflected in the $2,000,000 figure. What is Whitmore''s adjusted taxable income (ATI) for purposes of the business interest expense limitation?$EXPL$
WHERE id = 14684;

-- Q14690: Capital Structure Tax Planning [easy/L1]
-- Issues: #10
-- Original stem: A CPA advisor reviews several clients to determine eligibility for the Section 163(j) small business exception. One client's average annual gross receipts are under $30 million but it is still ineligible. Which type of taxpayer is prohibited from using the exception regardless of gross receipts?
UPDATE questions SET
  stem = $EXPL$A CPA advisor reviews several clients to determine eligibility for the small business exception to the business interest expense limitation. One client''s average annual gross receipts are under $30 million but it is still ineligible. Which type of taxpayer is prohibited from using the exception regardless of gross receipts?$EXPL$
WHERE id = 14690;

-- Q15770: Retirement Plans and Education Savings [easy/L1]
-- Issues: #11
-- Original stem: In a defined benefit pension plan, who bears the investment risk for plan assets?
UPDATE questions SET
  stem = $EXPL$Hartwell Manufacturing sponsors a defined benefit pension plan for its 200 employees. During 2025, the plan''s investment portfolio declined by 8%, creating an unfunded liability. The CFO is concerned about who is responsible for covering the shortfall. In a defined benefit pension plan, who bears the investment risk for plan assets?$EXPL$
WHERE id = 15770;

-- Q15780: Retirement Plans and Education Savings [easy/L1]
-- Issues: #11
-- Original stem: Under SECURE 2.0, what is required for new 401(k) plans established after December 29, 2022?
UPDATE questions SET
  stem = $EXPL$In January 2025, Redline Logistics forms a new company and establishes a 401(k) plan for its employees. The plan administrator asks the company''s CPA what enrollment requirements apply to plans established after December 29, 2022. What is required for these newly established 401(k) plans?$EXPL$
WHERE id = 15780;

-- Q15791: Entity Choice and Planning [hard/L4]
-- Issues: #10
-- Original stem: Calloway Engineering LLC (taxed as a partnership) generates $600,000 of qualified business income. The firm pays $120,000 in total W-2 wages and holds qualified property with an unadjusted basis immediately after acquisition (UBIA) of $2,000,000. The sole owner, Marcus Calloway, files as single with taxable income of $350,000 (well above the upper phase-in threshold). Engineering is not a specified service trade or business. What is the maximum Section 199A deduction?
UPDATE questions SET
  stem = $EXPL$Calloway Engineering LLC (taxed as a partnership) generates $600,000 of qualified business income. The firm pays $120,000 in total W-2 wages and holds qualified property with an unadjusted basis immediately after acquisition (UBIA) of $2,000,000. The sole owner, Marcus Calloway, files as single with taxable income of $350,000 (well above the upper phase-in threshold). Engineering is not a specified service trade or business. What is the maximum qualified business income deduction?$EXPL$
WHERE id = 15791;

-- Q15794: Entity Choice and Planning [easy/L1]
-- Issues: #11
-- Original stem: For purposes of the 100-shareholder limit on S corporations, how are members of the same family treated?
UPDATE questions SET
  stem = $EXPL$The Warren family owns all shares of Cedar Ridge Construction Inc., an S corporation. The family includes 14 members across three generations who each hold stock individually. The company''s CPA is evaluating whether the corporation can add new non-family investors without exceeding the 100-shareholder limit. For purposes of the S corporation shareholder limit, how are members of the same family treated?$EXPL$
WHERE id = 15794;

-- Q15797: Entity Choice and Planning [medium/L3]
-- Issues: #10
-- Original stem: Dr. Patel operates a medical practice as a sole proprietorship generating $500,000 of qualified business income. Her taxable income before the QBI deduction is $300,000 (filing single). The upper phase-in threshold for single filers is $247,300 (2025). Medical practice is a specified service trade or business (SSTB). What is Dr. Patel's Section 199A deduction?
UPDATE questions SET
  stem = $EXPL$Dr. Patel operates a medical practice as a sole proprietorship generating $500,000 of qualified business income. Her taxable income before the QBI deduction is $300,000 (filing single). The upper phase-in threshold for single filers is $247,300 (2025). Medical practice is a specified service trade or business (SSTB). What is Dr. Patel''s qualified business income deduction?$EXPL$
WHERE id = 15797;

-- Q15818: Multi-Jurisdictional Tax Planning [easy/L1]
-- Issues: #11
-- Original stem: In multistate taxation, what distinguishes allocation from apportionment?
UPDATE questions SET
  stem = $EXPL$Prescott Industries, headquartered in Ohio, earns revenue from operations in six states and also receives $400,000 of rental income from a warehouse it owns in Georgia. The company''s tax department must determine how to divide its income among the states where it files returns. In multistate taxation, what distinguishes allocation from apportionment?$EXPL$
WHERE id = 15818;

-- Q15819: Multi-Jurisdictional Tax Planning [medium/L2]
-- Issues: #10
-- Original stem: Brennan Manufacturing places $2 million of qualifying equipment in service during 2026 and claims 60% federal bonus depreciation under IRC Section 168(k). Brennan files in State L, which has decoupled from bonus depreciation and requires use of the pre-bonus MACRS schedule. What adjustment must Brennan make on its State L return?
UPDATE questions SET
  stem = $EXPL$Brennan Manufacturing places $2 million of qualifying equipment in service during 2026 and claims 60% federal bonus depreciation. Brennan files in State L, which has decoupled from bonus depreciation and requires use of the pre-bonus MACRS schedule. What adjustment must Brennan make on its State L return?$EXPL$
WHERE id = 15819;
