-- Migration: Question generation — TCP batch 36 (30 questions)
-- Date: 2026-04-14
-- Topic: International Tax
-- Difficulty: 9E / 15M / 6H
-- Bloom's: L1:6 / L2:10 / L3:9 / L4:5

BEGIN;

INSERT INTO questions (section_id, topic, stem, choices, correct_index, explanation, difficulty, cognitive_level)
VALUES

-- Q1: hard / L4 — Multi-entity CFC ownership analysis with indirect holdings
(6, 'International Tax', $EXPL$Ridgemont Holdings, a U.S. corporation, owns 30% of the voting stock of Zenith SA, a foreign corporation. Ridgemont's wholly owned domestic subsidiary, Beacon Inc., separately owns 25% of Zenith's voting stock. An unrelated U.S. individual, Torres, owns 12%. The remaining 33% is held by foreign persons. Evaluate whether Zenith qualifies as a controlled foreign corporation.$EXPL$, $EXPL$["Zenith is a CFC because Ridgemont and Beacon collectively own 55%, and Torres owns 12%, so U.S. shareholders owning at least 10% hold more than 50% in aggregate", "Zenith is not a CFC because no single U.S. person owns more than 50% of the voting stock", "Zenith is a CFC only if Ridgemont and Beacon are treated as a single shareholder for the 10% test", "Zenith is not a CFC because the 50% threshold requires direct ownership only, and neither Ridgemont nor Beacon individually exceeds 50%"]$EXPL$::jsonb, 0, $EXPL$Correct (A): Under IRC Section 957, a CFC is a foreign corporation in which U.S. shareholders (each owning at least 10% of vote or value per Section 951(b)) collectively own more than 50%. Ridgemont (30%), Beacon (25%), and Torres (12%) each meet the 10% threshold and together hold 67%, well above 50%. Wrong (B): The 50% test aggregates all qualifying U.S. shareholders, not just one person. Wrong (C): Ridgemont and Beacon each independently exceed 10% and are counted separately. Wrong (D): The CFC test aggregates all U.S. shareholders meeting the 10% threshold, not just direct majority holders.$EXPL$, 'hard', 4),

-- Q2: medium / L2 — Sourcing of purchased inventory income (title passage)
(6, 'International Tax', $EXPL$Caldwell Trading Co., a U.S. corporation, purchases finished electronics from a manufacturer in South Korea and resells them to customers in Brazil. Caldwell does not manufacture or further process the goods. Title to the goods passes to the Brazilian buyers at a port in Brazil. Under IRC Sections 861-862, how is Caldwell's profit from these sales sourced?$EXPL$, $EXPL$["U.S.-source because Caldwell is a U.S. corporation", "Foreign-source because title passes outside the United States", "Split between U.S. and foreign source based on the relative activities in each country", "Foreign-source because the goods were manufactured outside the United States"]$EXPL$::jsonb, 1, $EXPL$Correct (B): Under IRC Section 861(a)(6) and Section 862(a)(6), income from the sale of purchased inventory is sourced based on where title passes to the buyer. Since title passes in Brazil, the income is foreign-source. Wrong (A): The residence of the seller does not determine sourcing for purchased inventory sales. Wrong (C): The production-and-sale split applies to goods the taxpayer manufactures, not to purchased inventory. Wrong (D): The origin of manufacturing is irrelevant for purchased inventory; only the title passage location controls.$EXPL$, 'medium', 2),

-- Q3: medium / L2 — Allocation of services income performed in multiple jurisdictions
(6, 'International Tax', $EXPL$Fleming, a U.S. resident management consultant, earns $240,000 from a six-month engagement with a German client. Fleming performs four months of work in Germany and two months in the United States. Under IRC Sections 861-862, how is this services income sourced?$EXPL$, $EXPL$["Entirely U.S.-source because Fleming is a U.S. resident", "Entirely foreign-source because the client is a foreign person", "$160,000 foreign-source and $80,000 U.S.-source based on where the services were performed", "Entirely foreign-source because the majority of the work was performed outside the United States"]$EXPL$::jsonb, 2, $EXPL$Correct (C): Under IRC Section 861(a)(3) and Section 862(a)(3), compensation for personal services is sourced based on where the services are performed. Four months in Germany (4/6 of $240,000 = $160,000) is foreign-source, and two months in the U.S. (2/6 of $240,000 = $80,000) is U.S.-source. Wrong (A): The residence of the service provider does not control sourcing of services income. Wrong (B): The residence of the payer is irrelevant for services sourcing. Wrong (D): The majority rule does not apply; the income is allocated proportionally based on where services were performed.$EXPL$, 'medium', 2),

-- Q4: easy / L2 — Independent agent does not create PE
(6, 'International Tax', $EXPL$Nordvik AS, a Norwegian corporation, sells industrial equipment in the U.S. exclusively through Apex Distributors, an unrelated independent U.S. company that buys Nordvik's products at arm's length and resells them to U.S. customers. Nordvik has no office, employees, or other presence in the United States. Does Nordvik have a U.S. permanent establishment?$EXPL$, $EXPL$["Yes, because Nordvik earns income from U.S. customers", "Yes, because Apex acts as Nordvik's agent in the United States", "Yes, because Nordvik's products are physically present in the United States", "No, because an independent agent acting in its own name does not create a permanent establishment for the foreign principal"]$EXPL$::jsonb, 3, $EXPL$Correct (D): Under the permanent establishment framework, an independent agent operating in the ordinary course of its own business does not create a PE for the foreign enterprise. Apex buys and resells at arm's length as an independent party. Wrong (A): Earning U.S. income alone does not create a PE; a fixed place of business or dependent agent is required. Wrong (B): An independent distributor buying at arm's length is not a dependent agent. Wrong (C): Physical presence of goods does not itself establish a PE for the foreign seller.$EXPL$, 'easy', 2),

-- Q5: medium / L3 — ECI taxed on net basis vs FDAP on gross basis
(6, 'International Tax', $EXPL$Tivoli SpA, an Italian corporation, earns two types of U.S.-source income: (1) $500,000 in profits from a retail store it operates in Chicago, and (2) $200,000 in interest from a U.S. corporate bond unconnected to any U.S. business. Analyze how each income stream is taxed differently under U.S. federal income tax rules.$EXPL$, $EXPL$["The retail profits are taxed on a net basis after deducting business expenses, while the bond interest is subject to withholding at a flat rate on the gross amount", "Both income streams are taxed identically at the regular U.S. corporate rate on net income", "The bond interest is taxed on a net basis, and the retail profits are subject to flat-rate withholding", "Both income streams are subject to 30% withholding on the gross amount"]$EXPL$::jsonb, 0, $EXPL$Correct (A): Under IRC Sections 871 and 882, effectively connected income (the retail store profits) is taxed on a net basis at regular U.S. rates after allowable deductions. Fixed, determinable, annual, or periodical (FDAP) income (the bond interest) not connected to a U.S. business is taxed via withholding at a flat statutory rate on the gross amount. Wrong (B): ECI and FDAP income are taxed under fundamentally different mechanisms. Wrong (C): This reverses the treatment; ECI is net-basis and FDAP is gross-basis. Wrong (D): ECI is not subject to flat-rate withholding; it is taxed on a net basis through a tax return.$EXPL$, 'medium', 3),

-- Q6: easy / L1 — Who qualifies as a U.S. person for CFC purposes
(6, 'International Tax', $EXPL$Which of the following is considered a "U.S. person" for purposes of the controlled foreign corporation rules?$EXPL$, $EXPL$["A nonresident alien individual", "A domestic corporation", "A foreign partnership", "A foreign trust"]$EXPL$::jsonb, 1, $EXPL$Correct (B): Under IRC Section 7701(a)(30), a U.S. person includes U.S. citizens, resident aliens, domestic partnerships, domestic corporations, and certain domestic trusts and estates. A domestic corporation qualifies as a U.S. person. Wrong (A): A nonresident alien is not a U.S. person. Wrong (C): A foreign partnership is not a U.S. person. Wrong (D): A foreign trust is not a U.S. person.$EXPL$, 'easy', 1),

-- Q7: hard / L4 — Evaluating how ECI and FDAP income are taxed differently for same entity
(6, 'International Tax', $EXPL$Norsk Teknikk AS, a Norwegian corporation, operates a consulting office in Boston generating $900,000 in net profits after $300,000 in deductible expenses. Separately, Norsk receives $200,000 in U.S.-source dividends from a portfolio investment unconnected to its consulting business. Evaluate how these two income streams are taxed under U.S. federal income tax rules and determine the total U.S. tax base for each.$EXPL$, $EXPL$["Both streams are taxed on a net basis after deductions, yielding a combined tax base of $800,000", "Both streams are taxed on gross receipts at a flat rate, yielding a combined tax base of $1,400,000", "The consulting profits are taxed on $900,000 net income after deductions, and the dividends are taxed on $200,000 gross with no deductions allowed against them", "The consulting profits are taxed on $1,200,000 gross receipts, and the dividends are tax-exempt"]$EXPL$::jsonb, 2, $EXPL$Correct (C): Under IRC Sections 871 and 882, effectively connected income (consulting profits) is taxed on a net basis after deducting business expenses ($900,000 net). FDAP income (portfolio dividends) not connected to a U.S. business is taxed on the gross amount ($200,000) via withholding, with no deductions allowed. Wrong (A): FDAP income is taxed on gross, not net, so deductions cannot reduce the dividend base. Wrong (B): ECI is taxed on net income after deductions, not on gross receipts. Wrong (D): The consulting income tax base is net ($900,000), not gross ($1,200,000), and the dividends are taxable, not exempt.$EXPL$, 'hard', 4),

-- Q8: medium / L3 — Branch losses deductible currently vs subsidiary losses not
(6, 'International Tax', $EXPL$Lockhart Corp, a U.S. corporation, is deciding how to structure a new operation in Country R that is expected to generate $800,000 in losses during its first two years before becoming profitable. Lockhart's tax advisor recommends choosing the structure that allows the losses to reduce Lockhart's current U.S. taxable income. Analyze which structure accomplishes this objective.$EXPL$, $EXPL$["A foreign subsidiary, because subsidiary losses flow through to the U.S. parent's return", "A foreign subsidiary, because the U.S. parent can elect to deduct subsidiary losses", "Either structure achieves the same result because foreign losses always reduce U.S. income", "A foreign branch, because branch income and losses are included in the U.S. corporation's tax return currently"]$EXPL$::jsonb, 3, $EXPL$Correct (D): A foreign branch is not a separate legal entity, so its income and losses are reported on the U.S. corporation's tax return in the year incurred. Branch losses directly reduce the parent's U.S. taxable income. Wrong (A): A foreign subsidiary is a separate legal entity; its losses do not flow through to the U.S. parent's return. Wrong (B): No general election exists for a U.S. parent to deduct a foreign subsidiary's operating losses. Wrong (C): The two structures produce different timing results; branch losses are currently deductible, while subsidiary losses generally are not.$EXPL$, 'medium', 3),

-- Q9: medium / L2 — Sourcing of interest paid by a foreign corporation
(6, 'International Tax', $EXPL$Vanguard Industries, a U.S. corporation, holds a $5,000,000 note receivable from Solis Ltd., a corporation incorporated in and operating exclusively from Brazil. Solis pays $300,000 in annual interest on the note. Under IRC Sections 861-862, how is this interest income sourced on Vanguard's U.S. return?$EXPL$, $EXPL$["Foreign-source income because the payer is a foreign corporation", "U.S.-source income because the recipient is a U.S. corporation", "Foreign-source income because the loan funds are used outside the United States", "U.S.-source income because the note is held by a U.S. person"]$EXPL$::jsonb, 0, $EXPL$Correct (A): Under IRC Section 862(a)(1), interest paid by a foreign corporation is generally foreign-source income. The sourcing of interest follows the residence of the payer, not the recipient. Wrong (B): The residence of the recipient does not determine the source of interest income. Wrong (C): While the funds are used abroad, the controlling rule is the residence of the payer, not the use of proceeds. Wrong (D): Where the note is held is irrelevant to interest sourcing.$EXPL$, 'medium', 2),

-- Q10: medium / L2 — Preparatory/auxiliary activity does not create PE
(6, 'International Tax', $EXPL$Kanto Corp, a Japanese manufacturer, leases a small facility in Nevada used solely to store spare parts for warranty repairs handled by independent U.S. service providers. No sales, contract negotiations, or manufacturing occur at the facility. Does this facility constitute a permanent establishment for Kanto under the PE framework?$EXPL$, $EXPL$["Yes, because Kanto maintains a fixed place of business in the United States", "No, because a facility used solely for storage of goods is generally considered a preparatory or auxiliary activity that does not create a permanent establishment", "Yes, because the facility supports Kanto's business operations in the United States", "No, because Kanto does not have any employees in the United States"]$EXPL$::jsonb, 1, $EXPL$Correct (B): Under the PE framework, a facility maintained solely for storage, display, or delivery of goods is considered preparatory or auxiliary in nature and is specifically excluded from the PE definition. Wrong (A): A fixed location alone is not sufficient if the activity is preparatory or auxiliary. Wrong (C): Supporting business operations through storage is specifically excluded from PE when it is merely preparatory or auxiliary. Wrong (D): PE exclusion here is based on the nature of the activity, not the absence of employees.$EXPL$, 'medium', 2),

-- Q11: medium / L3 — CFC vote OR value test (disjunctive)
(6, 'International Tax', $EXPL$Cascadia Inc. and three other unrelated U.S. corporations each own 15% of the voting stock of Orienta Ltd., a foreign corporation (60% total voting power). However, due to a special class of nonvoting preferred stock, these same U.S. shareholders own only 40% of Orienta's total value. Analyze whether Orienta qualifies as a controlled foreign corporation.$EXPL$, $EXPL$["Orienta is not a CFC because U.S. shareholders do not own more than 50% of total value", "Orienta is not a CFC because both the vote and value tests must be satisfied simultaneously", "Orienta is a CFC because U.S. shareholders own more than 50% of total combined voting power, which independently satisfies the CFC definition", "Orienta is a CFC only if the IRS determines that the nonvoting preferred stock arrangement lacks economic substance"]$EXPL$::jsonb, 2, $EXPL$Correct (C): Under IRC Section 957(a), a foreign corporation is a CFC if U.S. shareholders own more than 50% of total combined voting power OR more than 50% of total value. The tests are disjunctive. Since U.S. shareholders hold 60% of voting power, the vote test is satisfied regardless of the value percentage. Wrong (A): Failing the value test does not prevent CFC status if the vote test is met. Wrong (B): The tests are disjunctive (or), not conjunctive (and). Wrong (D): The CFC determination is a mechanical ownership test, not a substance inquiry.$EXPL$, 'medium', 3),

-- Q12: medium / L3 — Worldwide taxation principle applied to U.S. citizens abroad
(6, 'International Tax', $EXPL$Donovan, a U.S. citizen, has lived and worked exclusively in Australia for the past five years. All of Donovan's income is earned in Australia from an Australian employer, deposited in Australian bank accounts, and subject to Australian income tax. Donovan's Australian tax advisor suggests that since Donovan has no U.S. income, no U.S. filing obligation exists. Analyze whether this advice is correct.$EXPL$, $EXPL$["The advice is correct because Donovan earns no U.S.-source income", "The advice is correct because Donovan is subject to Australian tax on all income", "The advice is correct because Donovan has established tax residency in Australia", "The advice is incorrect because U.S. citizens are taxed on worldwide income regardless of where they live or earn income"]$EXPL$::jsonb, 3, $EXPL$Correct (D): The United States taxes its citizens on worldwide income regardless of where the income is earned or where the citizen resides. Donovan must file a U.S. return reporting all Australian-source income. The U.S. may provide relief for double taxation through credits for foreign taxes paid. Wrong (A): U.S. citizens must report worldwide income, not just U.S.-source income. Wrong (B): Being taxed by another country does not eliminate U.S. filing obligations. Wrong (C): Establishing foreign tax residency does not override U.S. citizenship-based taxation.$EXPL$, 'medium', 3),

-- Q13: medium / L3 — Sourcing of rental income from real property (situs rule)
(6, 'International Tax', $EXPL$Montrose Ltd., a UK corporation, owns an apartment building in Miami generating $600,000 in annual rent and a commercial office in London generating $400,000 in annual rent. Montrose has no other U.S. connections. Apply the income sourcing rules to determine which rental income is U.S.-source.$EXPL$, $EXPL$["Only the $600,000 Miami rent is U.S.-source because rental income from real property is sourced to where the property is located", "Both rental streams are U.S.-source because Montrose earns income connected to U.S. persons", "Neither rental stream is U.S.-source because Montrose is a foreign corporation", "The $400,000 London rent is U.S.-source because it is paid to a corporation with U.S. real property interests"]$EXPL$::jsonb, 0, $EXPL$Correct (A): Under IRC Section 861(a)(4), rental income from real property is sourced based on the location (situs) of the property. The Miami property generates U.S.-source income; the London property generates foreign-source income. Wrong (B): Rental income sourcing depends on property location, not on the nationality of tenants. Wrong (C): A foreign corporation can still have U.S.-source rental income if the property is located in the United States. Wrong (D): London rent is foreign-source regardless of the landlord's other U.S. holdings.$EXPL$, 'medium', 3),

-- Q14: easy / L1 — Purpose of withholding on FDAP payments to foreign persons
(6, 'International Tax', $EXPL$What is the primary purpose of requiring U.S. withholding on certain payments to foreign persons?$EXPL$, $EXPL$["To penalize foreign persons for investing in the United States", "To ensure collection of U.S. tax on income paid to persons who may not file a U.S. tax return", "To prevent foreign persons from earning U.S.-source income", "To equalize the tax rates between domestic and foreign taxpayers"]$EXPL$::jsonb, 1, $EXPL$Correct (B): Withholding on payments to foreign persons serves as a collection mechanism. Because foreign recipients of U.S.-source FDAP income typically have no U.S. filing obligation for that income, withholding at the source ensures the U.S. collects tax on the payment. Wrong (A): Withholding is a tax collection tool, not a penalty. Wrong (C): The United States does not prohibit foreign persons from earning U.S.-source income. Wrong (D): Withholding is not designed to equalize rates; it is a compliance mechanism.$EXPL$, 'easy', 1),

-- Q15: easy / L1 — Definition of effectively connected income
(6, 'International Tax', $EXPL$What does the term "effectively connected income" mean for a foreign corporation operating in the United States?$EXPL$, $EXPL$["Income earned by a foreign corporation from any source worldwide", "Income that a foreign corporation earns from passive investments in U.S. securities", "Income of a foreign corporation that is connected to the conduct of a U.S. trade or business", "Income that a U.S. corporation earns from transactions with foreign related parties"]$EXPL$::jsonb, 2, $EXPL$Correct (C): Under IRC Section 864(c), effectively connected income (ECI) is income of a foreign person that is connected to the conduct of a trade or business within the United States. ECI is taxed on a net basis at regular U.S. rates. Wrong (A): ECI is specifically U.S.-connected income, not worldwide income. Wrong (B): Passive investment income unconnected to a U.S. business is FDAP, not ECI. Wrong (D): ECI applies to foreign persons with U.S. business activities, not to U.S. corporations.$EXPL$, 'easy', 1),

-- Q16: easy / L1 — Consequence of CFC classification for U.S. shareholders
(6, 'International Tax', $EXPL$What is the primary tax consequence when a foreign corporation is classified as a controlled foreign corporation?$EXPL$, $EXPL$["The CFC itself must pay U.S. corporate income tax on all worldwide earnings", "The CFC is prohibited from distributing dividends to its U.S. shareholders", "The foreign country must share its tax revenue with the United States", "Certain income of the CFC may be taxed currently to its U.S. shareholders even without a distribution"]$EXPL$::jsonb, 3, $EXPL$Correct (D): Under IRC Section 951, when a foreign corporation qualifies as a CFC, its U.S. shareholders may be required to include certain categories of CFC income in their own gross income currently, regardless of whether the CFC distributes any cash. Wrong (A): The CFC itself does not become a U.S. taxpayer; the inclusion falls on the U.S. shareholders. Wrong (B): CFC status does not restrict dividend payments. Wrong (C): CFC rules are a U.S. domestic anti-deferral mechanism, not a revenue-sharing arrangement between countries.$EXPL$, 'easy', 1),

-- Q17: easy / L1 — The 30% default statutory withholding rate
(6, 'International Tax', $EXPL$What is the default U.S. statutory withholding tax rate on U.S.-source fixed, determinable, annual, or periodical income paid to a foreign person?$EXPL$, $EXPL$["30%", "21%", "15%", "10%"]$EXPL$::jsonb, 0, $EXPL$Correct (A): Under IRC Sections 1441 and 1442, the default statutory withholding rate on FDAP income (such as interest, dividends, rents, and royalties) paid to foreign persons is 30%. This rate may be reduced by an applicable bilateral tax agreement. Wrong (B): 21% is the regular U.S. corporate income tax rate, not the withholding rate on FDAP. Wrong (C): 15% may apply under certain bilateral agreements but is not the statutory default. Wrong (D): 10% may apply under certain bilateral agreements but is not the default rate.$EXPL$, 'easy', 1),

-- Q18: medium / L2 — Attribution through domestic partnership for CFC ownership
(6, 'International Tax', $EXPL$Ortega, a U.S. citizen, owns a 40% interest in Delta Partners, a domestic partnership. Delta Partners directly owns 30% of the voting stock of Lantana SA, a foreign corporation. Ortega has no other direct or indirect ownership in Lantana. Under the constructive ownership rules for CFC purposes, what percentage of Lantana does Ortega own?$EXPL$, $EXPL$["30%, because a partner is treated as owning the partnership's full shareholding", "12%, because Ortega is treated as owning a proportionate share of the partnership's stock ownership", "0%, because ownership through a partnership is not attributed for CFC purposes", "40%, because Ortega's partnership interest is treated as direct stock ownership"]$EXPL$::jsonb, 1, $EXPL$Correct (B): Under IRC Section 958(a)(2), stock owned by a partnership is considered owned proportionately by its partners. Ortega's 40% partnership interest x Delta's 30% Lantana stock = 12% constructive ownership. Wrong (A): Proportionate, not full, attribution applies through partnerships. Wrong (C): Partnership attribution is explicitly provided under Section 958(a)(2). Wrong (D): The 40% partnership interest is not itself converted to stock ownership; it is used to calculate proportionate attribution.$EXPL$, 'medium', 2),

-- Q19: hard / L4 — Evaluating PE for temporary construction project duration threshold
(6, 'International Tax', $EXPL$Brenner Bau AG, a German construction company, wins two U.S. contracts: (1) a 10-month highway bridge project in Ohio, and (2) a 14-month office tower project in Texas. Brenner has no other U.S. presence. The applicable bilateral tax agreement provides that a building site or construction project constitutes a permanent establishment only if it lasts more than 12 months. Evaluate Brenner's PE status.$EXPL$, $EXPL$["Neither project creates a PE because each is a temporary activity", "Both projects create PEs because Brenner has a fixed place of business at each site", "Only the Texas project creates a PE because it exceeds the 12-month duration threshold, while the Ohio project does not", "Both projects create a single PE because they should be aggregated for duration purposes"]$EXPL$::jsonb, 2, $EXPL$Correct (C): Under the bilateral construction clause, a building site constitutes a PE only if it lasts more than 12 months. Each project is evaluated independently. The Ohio project (10 months) falls below the threshold. The Texas project (14 months) exceeds it and creates a PE. Wrong (A): The Texas project exceeds the duration threshold and does create a PE. Wrong (B): The PE construction clause requires exceeding the duration threshold, not merely having a fixed site. Wrong (D): Separate, unrelated construction projects are generally evaluated independently under the construction clause.$EXPL$, 'hard', 4),

-- Q20: medium / L3 — Subsidiary income deferred until distribution
(6, 'International Tax', $EXPL$Crawford Corp, a U.S. corporation, owns 100% of Magellan Ltd., a foreign subsidiary incorporated in Ireland. Magellan earns $4,000,000 in operating income during Year 1 but declares no dividend. In Year 2, Magellan declares and pays a $2,000,000 dividend to Crawford. Analyze when Crawford generally recognizes income from Magellan's operations for U.S. tax purposes, assuming no anti-deferral provisions apply.$EXPL$, $EXPL$["Crawford recognizes $4,000,000 in Year 1 when Magellan earns the income", "Crawford recognizes $4,000,000 in Year 1 and receives a refund when the dividend is paid in Year 2", "Crawford recognizes $2,000,000 in each year, allocated proportionally", "Crawford generally recognizes no income in Year 1 and recognizes $2,000,000 of dividend income in Year 2 when the distribution occurs"]$EXPL$::jsonb, 3, $EXPL$Correct (D): Under the general rule, a foreign subsidiary is a separate legal entity and its undistributed earnings are not included in the U.S. parent's income. Crawford recognizes income when Magellan distributes a dividend. Without anti-deferral rules, no Year 1 inclusion occurs. Wrong (A): Subsidiary income is not automatically included when earned; deferral applies. Wrong (B): There is no refund mechanism; the parent simply does not include undistributed subsidiary income. Wrong (C): Income is recognized when distributed, not allocated across years.$EXPL$, 'medium', 3),

-- Q21: hard / L4 — Multi-item sourcing analysis with mixed rules
(6, 'International Tax', $EXPL$Prescott Corp, a U.S. corporation, earns the following during the year: (1) $500,000 in fees for consulting services performed in Japan; (2) $200,000 in dividends from Lumina SA, a French corporation; (3) $150,000 in interest on a loan to its U.S. subsidiary; and (4) $300,000 in rent from a warehouse Prescott owns in Chicago leased to a Canadian tenant. Determine Prescott's total U.S.-source income.$EXPL$, $EXPL$["$450,000", "$700,000", "$650,000", "$1,150,000"]$EXPL$::jsonb, 0, $EXPL$Correct (A): Services performed in Japan = foreign-source ($0 U.S.). Dividends from a French corporation = foreign-source ($0 U.S.). Interest from a U.S. subsidiary = U.S.-source ($150,000, payer residence rule). Chicago warehouse rent = U.S.-source ($300,000, property situs rule). Total U.S.-source = $150,000 + $300,000 = $450,000. Wrong (B): This incorrectly includes the Japanese consulting fees as U.S.-source. Wrong (C): This incorrectly includes the French dividends as U.S.-source. Wrong (D): This includes all items, ignoring the foreign-source classification of services and dividends.$EXPL$, 'hard', 4),

-- Q22: hard / L3 — 10% threshold is "at least 10%" not "more than 10%"
(6, 'International Tax', $EXPL$Thornton, a U.S. citizen, directly owns exactly 10% of the voting stock of Meridian SA, a foreign corporation. Three other unrelated U.S. persons each own 15%, and the remaining 25% is held by non-U.S. persons. Thornton's tax advisor states that Thornton is not a U.S. shareholder for CFC purposes because Thornton does not own more than 10%. Analyze this advice.$EXPL$, $EXPL$["The advice is correct because the 10% threshold requires ownership exceeding 10%", "The advice is incorrect because a U.S. shareholder is any U.S. person owning at least 10% of vote or value, which includes exactly 10%", "The advice is correct because the CFC rules require more than 50% ownership by a single U.S. shareholder", "The advice is incorrect because all U.S. persons with any ownership in a foreign corporation are U.S. shareholders"]$EXPL$::jsonb, 1, $EXPL$Correct (B): Under IRC Section 951(b), a U.S. shareholder is any U.S. person who owns 10% or more of the total combined voting power or value. The threshold is "at least 10%," so exactly 10% qualifies Thornton as a U.S. shareholder. Wrong (A): The statute uses "10 percent or more," not "more than 10 percent." Wrong (C): The 50% test applies to aggregate U.S. shareholder ownership for CFC status, not to individual shareholders. Wrong (D): Only U.S. persons meeting the 10% threshold are U.S. shareholders, not all owners.$EXPL$, 'hard', 3),

-- Q23: hard / L4 — Evaluating withholding obligations on different payment types
(6, 'International Tax', $EXPL$Atlas Corp, a U.S. corporation, makes three payments to unrelated foreign corporations with no U.S. business activities: (1) $250,000 in royalties for licensed technology; (2) $180,000 for raw materials shipped from abroad; and (3) $120,000 in dividends on preferred stock held by a foreign investor. Atlas's new controller asks which payments require withholding. Evaluate the withholding obligations.$EXPL$, $EXPL$["All three payments require 30% withholding", "Only the royalties require withholding", "The royalties and dividends require withholding, but the payment for raw materials does not", "Only the payment for raw materials requires withholding because it involves a cross-border transaction"]$EXPL$::jsonb, 2, $EXPL$Correct (C): Under IRC Sections 1441-1442, the 30% statutory withholding applies to FDAP income such as royalties and dividends paid to foreign persons. Payments for the purchase of goods (raw materials) are not FDAP income and are not subject to withholding. Wrong (A): Payments for goods are not subject to FDAP withholding. Wrong (B): Dividends paid to foreign persons are also FDAP income subject to withholding. Wrong (D): Goods purchases are commercial transactions, not FDAP income, and do not trigger withholding.$EXPL$, 'hard', 4),

-- Q24: easy / L1 — Worldwide taxation for U.S. corporations
(6, 'International Tax', $EXPL$On what basis does the United States generally tax its domestic corporations?$EXPL$, $EXPL$["Only on income earned within the United States", "Only on income received in U.S. dollars", "Only on income remitted to the United States from foreign operations", "On worldwide income regardless of where it is earned"]$EXPL$::jsonb, 3, $EXPL$Correct (D): The United States taxes domestic corporations on their worldwide income, meaning all income from both U.S. and foreign sources is subject to U.S. federal income tax. Credits for foreign taxes paid may mitigate resulting double taxation. Wrong (A): U.S. taxation is not limited to domestically earned income. Wrong (B): The currency of receipt is irrelevant to U.S. taxing jurisdiction. Wrong (C): Worldwide income is taxable when earned, not just when remitted.$EXPL$, 'easy', 1),

-- Q25: easy / L2 — Withholding agent responsibility on FDAP payments
(6, 'International Tax', $EXPL$Westbrook Corp, a U.S. corporation, pays $100,000 in annual rent to Masson SARL, a French corporation that owns a U.S. office building. Masson has no U.S. trade or business. Under IRC Sections 1441-1442, who bears the responsibility to withhold U.S. tax on this rental payment?$EXPL$, $EXPL$["Westbrook, as the U.S. person making the payment, is the withholding agent responsible for withholding and remitting the tax", "Masson, as the foreign recipient, must self-assess and remit the tax", "The IRS collects the tax directly from Masson through international agreements", "No withholding is required because rental payments are exempt from FDAP withholding"]$EXPL$::jsonb, 0, $EXPL$Correct (A): Under IRC Sections 1441-1442, the payor of U.S.-source FDAP income to a foreign person is the withholding agent. Westbrook must withhold the applicable tax from the rental payment and remit it to the IRS. Wrong (B): The foreign recipient is not responsible for self-assessment of FDAP withholding; the burden falls on the payor. Wrong (C): FDAP withholding is administered through the payor as withholding agent, not through direct IRS collection. Wrong (D): Rental payments to foreign persons are FDAP income subject to withholding.$EXPL$, 'easy', 2),

-- Q26: medium / L3 — PE threshold prevents taxation of business profits
(6, 'International Tax', $EXPL$Hanssen Electronics, a Danish corporation, sends a team of sales representatives to a U.S. trade show for three weeks. The team demonstrates products, takes orders, and returns to Denmark. Hanssen has no office, warehouse, or permanent staff in the United States. Under the applicable bilateral tax agreement, business profits of a Danish enterprise are taxable in the U.S. only if attributable to a permanent establishment. Analyze whether the U.S. can tax Hanssen's business profits from these sales.$EXPL$, $EXPL$["Yes, because Hanssen earned income from U.S. customers", "No, because Hanssen does not have a permanent establishment in the United States, and the bilateral agreement protects its business profits from U.S. taxation", "Yes, because taking orders in the United States automatically creates a permanent establishment", "No, because trade show income is specifically exempt under all bilateral tax agreements"]$EXPL$::jsonb, 1, $EXPL$Correct (B): Under the bilateral tax agreement, business profits of a Danish enterprise are taxable in the U.S. only if attributable to a U.S. permanent establishment. A temporary trade show presence without a fixed place of business does not create a PE. Without a PE, the agreement prevents U.S. taxation of Hanssen's business profits. Wrong (A): Earning U.S. income does not override the PE-based protections for business profits. Wrong (C): Temporary order-taking at a trade show does not constitute a fixed place of business or dependent agent PE. Wrong (D): There is no blanket trade show exemption; the protection arises from the absence of a PE.$EXPL$, 'medium', 3),

-- Q27: medium / L2 — Sourcing of royalties based on where property is used
(6, 'International Tax', $EXPL$Vertex Corp, a U.S. corporation, licenses patented manufacturing technology to Primus AG, a German corporation that uses the patent exclusively in its German factories. Primus pays Vertex $350,000 in annual royalties. Under IRC Sections 861-862, how is Vertex's royalty income sourced?$EXPL$, $EXPL$["U.S.-source because Vertex is a U.S. corporation", "U.S.-source because the patent was developed in the United States", "Foreign-source because the patent is used outside the United States", "Split between U.S. and foreign source based on Vertex's worldwide revenue"]$EXPL$::jsonb, 2, $EXPL$Correct (C): Under IRC Section 862(a)(4), royalties from property used outside the United States are foreign-source income. Since the patent is used exclusively in German factories, the royalty income is foreign-source. Wrong (A): The residence of the licensor does not determine royalty sourcing. Wrong (B): Where the patent was developed is irrelevant; the sourcing rule looks at where the property is used. Wrong (D): Royalty sourcing is based on property use location, not a revenue-based allocation.$EXPL$, 'medium', 2),

-- Q28: easy / L2 — Foreign corporation with ECI must file a U.S. return
(6, 'International Tax', $EXPL$Nagoya Industries, a Japanese corporation, operates a small manufacturing plant in Michigan that produces auto parts sold to U.S. customers. The plant generates $1,200,000 in annual profits. Nagoya's compliance team asks whether the company has a U.S. federal income tax filing obligation. How should the compliance team respond?$EXPL$, $EXPL$["Nagoya has no filing obligation because it is a foreign corporation", "Nagoya has no filing obligation if it pays income tax in Japan on the same profits", "Nagoya has no filing obligation because the profits are below the threshold for foreign corporations", "Nagoya must file a U.S. federal income tax return because it has effectively connected income from a U.S. trade or business"]$EXPL$::jsonb, 3, $EXPL$Correct (D): A foreign corporation engaged in a U.S. trade or business must file a U.S. federal income tax return to report its effectively connected income. Operating a U.S. manufacturing plant constitutes a U.S. trade or business. Wrong (A): Foreign corporations with U.S. trade or business activities have U.S. filing obligations. Wrong (B): Paying tax in another country does not eliminate the U.S. filing requirement. Wrong (C): There is no minimum income threshold that exempts a foreign corporation with ECI from filing.$EXPL$, 'easy', 2),

-- Q29: medium / L3 — Dependent agent with contracting authority creates PE
(6, 'International Tax', $EXPL$Glenmore PLC, a UK corporation, has no U.S. office but employs Rivera, a U.S.-based sales manager. Rivera has authority to negotiate and sign binding contracts with U.S. customers on Glenmore's behalf, and she regularly exercises this authority from her home office. Glenmore's tax advisor is evaluating whether Rivera's activities create a U.S. permanent establishment. Analyze the PE implications.$EXPL$, $EXPL$["Rivera's activities create a U.S. permanent establishment for Glenmore because a dependent agent who habitually exercises authority to conclude contracts on behalf of the enterprise creates a PE", "Rivera's activities do not create a PE because she works from a home office rather than a company facility", "Rivera's activities do not create a PE because she is only one employee", "Rivera's activities create a PE only if her annual sales exceed a specified dollar threshold"]$EXPL$::jsonb, 0, $EXPL$Correct (A): Under the permanent establishment framework, a dependent agent who habitually exercises authority to conclude contracts in the name of the foreign enterprise creates a PE, even without a formal company office. Rivera meets this definition. Wrong (B): The PE analysis focuses on the agent's authority, not the physical nature of the workspace. Wrong (C): The number of employees is irrelevant; a single dependent agent with contracting authority is sufficient to create a PE. Wrong (D): PE determinations are based on the nature of activities, not dollar thresholds.$EXPL$, 'medium', 3),

-- Q30: medium / L2 — Withholding does not apply to payments for goods
(6, 'International Tax', $EXPL$Redstone Inc., a U.S. corporation, pays Fabrica SRL, an Italian manufacturer with no U.S. presence, $800,000 for custom machinery delivered to Redstone's factory. Redstone's accounts payable clerk asks whether the company must withhold U.S. tax on this payment. Under IRC Sections 1441-1442, what is the correct answer?$EXPL$, $EXPL$["Yes, withholding at 30% is required on all payments to foreign persons", "No, withholding is not required because payments for the purchase of goods are not fixed, determinable, annual, or periodical income subject to withholding", "Yes, withholding at 30% is required because the machinery is delivered to the United States", "No, withholding is not required because Italy has a bilateral tax agreement with the United States"]$EXPL$::jsonb, 1, $EXPL$Correct (B): Under IRC Sections 1441-1442, withholding applies to FDAP income such as interest, dividends, rents, and royalties. Payments for the purchase of tangible goods are proceeds from a sale, not FDAP income, and are not subject to withholding. Wrong (A): Withholding does not apply to all payments to foreign persons, only to FDAP income. Wrong (C): The delivery location does not convert a goods purchase into FDAP income. Wrong (D): The exemption is based on the nature of the payment (goods purchase), not on bilateral agreement provisions.$EXPL$, 'medium', 2)
;

COMMIT;
